import type { StaticGkLessonManifest } from "./types";

export const STANDARD_MERIDIAN_LESSON_MANIFEST: StaticGkLessonManifest = {
  schemaVersion: "1.0",
  manifestVersion: "1.0",
  visualId: "SGK-VIS-IND-GEO-002",
  title: "Standard Meridian of India",
  categoryTag: "STATIC GK · INDIA GEOGRAPHY",
  durationMs: 33_000,
  viewport: {
    aspectRatio: "9:16",
    width: 1080,
    height: 1920,
    safeArea: { top: 170, right: 80, bottom: 230, left: 80 },
    projection: "geoMercator",
  },
  learningObjectives: [
    "Recall India's Standard Meridian as 82°30′E.",
    "Recall Mirzapur in Uttar Pradesh as the key place association.",
    "Connect the Standard Meridian to IST and GMT +5:30.",
  ],
  shots: [
    {
      id: "SGK002-SHOT-01-HOOK",
      startMs: 0,
      endMs: 3_000,
      role: "hook",
      headline: "STANDARD MERIDIAN OF INDIA",
      supportingText: ["Why is 82°30′E important?"],
      narrationRef: "SGK002-N01",
      factIds: ["SGK002-F01", "SGK002-F03"],
      actions: [{ layer: "base-map", action: "show", targetRef: "geo.india", text: "Why 82°30′E?" }],
    },
    {
      id: "SGK002-SHOT-02-MAP",
      startMs: 3_000,
      endMs: 6_000,
      role: "map-intro",
      supportingText: ["Static GK · India Geography"],
      factIds: ["SGK002-F01"],
      actions: [{ layer: "base-map", action: "show", targetRef: "geo.india", text: "India" }],
    },
    {
      id: "SGK002-SHOT-03-MERIDIAN",
      startMs: 6_000,
      endMs: 10_000,
      role: "concept",
      headline: "Standard Meridian = 82°30′E",
      narrationRef: "SGK002-N02",
      factIds: ["SGK002-F01"],
      actions: [{ layer: "longitude-line", action: "trace", targetRef: "line.standard-meridian", text: "82°30′E" }],
    },
    {
      id: "SGK002-SHOT-04-UP",
      startMs: 10_000,
      endMs: 14_000,
      role: "concept",
      headline: "State: Uttar Pradesh",
      factIds: ["SGK002-F02"],
      actions: [{ layer: "state-highlight", action: "highlight", targetRef: "state.UP", text: "Uttar Pradesh" }],
    },
    {
      id: "SGK002-SHOT-05-MIRZAPUR",
      startMs: 14_000,
      endMs: 19_000,
      role: "concept",
      headline: "District: Mirzapur",
      factIds: ["SGK002-F02"],
      actions: [{ layer: "district-highlight", action: "highlight", targetRef: "district.mirzapur", text: "Mirzapur district" }],
    },
    {
      id: "SGK002-SHOT-06-IST",
      startMs: 19_000,
      endMs: 25_000,
      role: "exam-takeaway",
      headline: "82°30′E → IST",
      supportingText: ["IST = GMT +5:30"],
      narrationRef: "SGK002-N03",
      factIds: ["SGK002-F03", "SGK002-F04"],
      actions: [{ layer: "labels", action: "hold", text: "IST · GMT +5:30" }],
    },
    {
      id: "SGK002-SHOT-07-RECAP",
      startMs: 25_000,
      endMs: 29_000,
      role: "recap",
      headline: "Remember",
      supportingText: ["82°30′E", "Mirzapur", "IST"],
      factIds: ["SGK002-F01", "SGK002-F02", "SGK002-F03"],
      actions: [{ layer: "labels", action: "hold", text: "82°30′E · Mirzapur · IST" }],
    },
    {
      id: "SGK002-SHOT-08-QUIZ",
      startMs: 29_000,
      endMs: 33_000,
      role: "quiz",
      headline: "Quick Question",
      factIds: ["SGK002-F01", "SGK002-F02"],
      actions: [{ layer: "quiz", action: "quiz", text: "Which longitude is India's Standard Meridian?" }],
    },
  ],
};
