import { deterministicIndex } from "../../../../core/deterministic";
import { ENG004_CP003_LEXICON_V1,eng004Cp003PoolV1,type Eng004Cp003Difficulty,type Eng004Cp003LexicalEntryV1,type Eng004Cp003RelationType } from "./eng-004-cp003-lexicon-v1";
export interface GenerateEng004Cp003V1Input{seed:string;difficulty:Eng004Cp003Difficulty;relationType?:Eng004Cp003RelationType;entryId?:string;}
export interface Eng004Cp003QuestionV1{questionId:string;stem:string;context?:string;options:readonly string[];correctOptionIndex:number;explanation:string;metadata:{track:"english";chapterId:"ENG-004";cpId:"ENG-004-CP003";difficulty:Eng004Cp003Difficulty;relationType:Eng004Cp003RelationType;entryId:string;word:string;partOfSpeech:string;senseRank:number;senseCount:number;sourceSynsetOffset:string;seed:string;reviewOnly:true};}
const SYN=[(w:string)=>`Choose the word most similar in meaning to “${w}”.`,(w:string)=>`Select the synonym of “${w}”.`,(w:string)=>`Which option is closest in meaning to “${w}”?`] as const;
const ANT=[(w:string)=>`Choose the word most opposite in meaning to “${w}”.`,(w:string)=>`Select the antonym of “${w}”.`,(w:string)=>`Which option is opposite in meaning to “${w}”?`] as const;
function hash(v:string){let h=0x811c9dc5;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0;}return h>>>0;}
function resolve(input:GenerateEng004Cp003V1Input):Eng004Cp003LexicalEntryV1{if(input.entryId){const e=ENG004_CP003_LEXICON_V1.find(x=>x.id===input.entryId);if(!e)throw new Error(`Unknown ENG-004 CP003 entry ${input.entryId}`);if(e.difficulty!==input.difficulty)throw new Error(`${e.id} is not ${input.difficulty}`);return e;}const p=eng004Cp003PoolV1(input.difficulty);return p[deterministicIndex(`${input.seed}:eng004-cp003-entry`,p.length)]!;}
function place(seed:string,correct:string,distractors:readonly string[]){let xs=[...new Set(distractors.map(x=>x.toLowerCase()))].filter(x=>x!==correct.toLowerCase());if(xs.length<3)throw new Error(`ENG-004 CP003 needs three distractors for ${correct}`);for(let i=xs.length-1;i>0;i--){const j=deterministicIndex(`${seed}:eng004-cp003-shuffle:${i}`,i+1);[xs[i],xs[j]]=[xs[j]!,xs[i]!];}xs=xs.slice(0,3);const ci=hash(`${seed}:eng004-cp003-position`)%4,opts:string[]=[];let w=0;for(let i=0;i<4;i++)opts.push(i===ci?correct:xs[w++]!);return{options:opts,correctOptionIndex:ci};}
export function generateEng004Cp003QuestionV1(input:GenerateEng004Cp003V1Input):Eng004Cp003QuestionV1{const e=resolve(input),modes:Eng004Cp003RelationType[]=[];if(e.synonyms.length)modes.push("synonym");if(e.antonyms.length)modes.push("antonym");if(!modes.length)throw new Error(`${e.id} has no lexical relation`);const relationType=input.relationType??modes[deterministicIndex(`${input.seed}:eng004-cp003-relation`,modes.length)]!;if(!modes.includes(relationType))throw new Error(`${e.id} has no approved ${relationType}`);const answers=relationType==="synonym"?e.synonyms:e.antonyms,correct=answers[deterministicIndex(`${input.seed}:eng004-cp003-answer`,answers.length)]!;const blocked=new Set([e.word,...e.synonyms,...e.antonyms].map(x=>x.toLowerCase())),d=e.distractors.filter(x=>!blocked.has(x.toLowerCase())),placed=place(input.seed,correct,d);const contextual=e.senseCount>1&&Boolean(e.example),stems=relationType==="synonym"?SYN:ANT,stem=contextual?`In the sentence below, choose the ${relationType} of “${e.word}” as used there.`:stems[deterministicIndex(`${input.seed}:eng004-cp003-stem`,stems.length)]!(e.word),context=contextual?e.example:undefined,rt=relationType==="synonym"?"has the closest meaning":"expresses the opposite meaning";return{questionId:`ENG-004-CP003-${e.id}-${relationType.toUpperCase()}-${hash(input.seed).toString(16).padStart(8,"0")}`,stem,context,options:placed.options,correctOptionIndex:placed.correctOptionIndex,explanation:`“${e.word}” here means ${e.meaning}. “${correct}” ${rt} in this sense.`,metadata:{track:"english",chapterId:"ENG-004",cpId:"ENG-004-CP003",difficulty:e.difficulty,relationType,entryId:e.id,word:e.word,partOfSpeech:e.pos,senseRank:e.senseRank,senseCount:e.senseCount,sourceSynsetOffset:e.source.synsetOffset,seed:input.seed,reviewOnly:true}};}
