export type Eng009Cp003Difficulty="medium"|"hard";
export type Eng009Cp003BlankKind="grammar"|"vocabulary"|"collocation"|"context"|"discourse"|"phrase-fit";
export interface Eng009Cp003BlankV1{
 id:string;blankNo:1|2|3|4|5|6;difficulty:Eng009Cp003Difficulty;kind:Eng009Cp003BlankKind;
 answer:string;distractors:readonly[string,string,string];explanation:string;clue:string;
}
export interface Eng009Cp003PassageV1{
 id:string;title:string;topic:string;template:string;blanks:readonly Eng009Cp003BlankV1[];
}
const b=(id:string,blankNo:1|2|3|4|5|6,difficulty:Eng009Cp003Difficulty,kind:Eng009Cp003BlankKind,answer:string,distractors:readonly[string,string,string],explanation:string,clue:string):Eng009Cp003BlankV1=>({id,blankNo,difficulty,kind,answer,distractors,explanation,clue});

export const ENG009_CP003_PASSAGES_V1:readonly Eng009Cp003PassageV1[]=[
{
 id:"ENG009-BP-C01",title:"Digital Payment Habits",topic:"digital payments",
 template:`Digital payments have made small transactions faster for many users, but convenience alone does not guarantee safe use. People who pay frequently through mobile apps may begin to approve requests without checking the amount or the receiver carefully. Banks therefore encourage customers to __(1)__ transaction details before entering a PIN. This habit becomes especially important when a message or link creates a sense of urgency. Fraud attempts often rely on pressure because hurried users are less likely to notice unusual details. Customers should also avoid sharing passwords or one-time codes, even when the caller claims to represent a bank. Genuine support teams do not need these secrets to __(2)__ a complaint. Another useful habit is to keep payment apps updated, since updates may fix security problems. None of these steps can remove all risk, but together they can __(3)__ the chance of avoidable loss. The wider lesson is simple: digital payments work best when speed is balanced with attention. A transaction may take only a few seconds, but those seconds should still include a quick __(4)__ of the key details. Safe use depends not on fear of technology but on using it __(5)__. As payment systems become more common, basic security habits need to become equally __(6)__.`,
 blanks:[
 b("C01-B1",1,"medium","collocation","verify",["observe","inspect","confirm"],"'Verify the details' means check that they are correct.","transaction details before entering a PIN"),
 b("C01-B2",2,"medium","vocabulary","resolve",["remove","cancel","avoid"],"'Resolve a complaint' means deal with it and solve the issue.","support teams ... a complaint"),
 b("C01-B3",3,"hard","context","reduce",["limit","lower","cut"],"These steps make avoidable loss less likely, so 'reduce' fits.","chance of avoidable loss"),
 b("C01-B4",4,"medium","phrase-fit","review",["glance","reading","look"],"'A quick review of the key details' is the natural phrase here.","include a quick ... of the key details"),
 b("C01-B5",5,"hard","context","carefully",["slowly","strictly","formally"],"The passage stresses attention and checking, so 'carefully' fits.","using it ..."),
 b("C01-B6",6,"medium","discourse","common",["regular","normal","usual"],"Security habits should become as common as digital payments themselves.","need to become equally ...")
 ]
},
{
 id:"ENG009-BP-C02",title:"Small Businesses and Inventory",topic:"business management",
 template:`A small shop can lose money not only by buying too much stock but also by running out of products that customers expect to find. Good inventory management tries to __(1)__ these two risks. Shop owners often begin by tracking which items sell quickly and which remain on shelves for long periods. This information helps them decide how much to reorder and when. Seasonal demand also matters. A product that sells slowly for most of the year may suddenly become popular during a festival or a change in weather. If the owner relies only on last week's sales, the order may be too small or too large. For this reason, past records should be read together with current conditions. Some businesses use simple software, while others use notebooks or spreadsheets. The method matters less than the habit of keeping records __(2)__. Reliable records make it easier to identify slow-moving stock, plan purchases and avoid emergency orders. They also help owners see whether a discount actually increases sales enough to justify the lower price. Inventory decisions are therefore not just about counting products; they are about using information to make buying more __(3)__. A shop that understands its demand can keep less unnecessary stock without __(4)__ customers. This can improve cash flow because money is not locked in goods that may take months to sell. In small businesses, even basic records can have a __(5)__ effect when they are used regularly. The goal is not perfect prediction, but better decisions based on evidence rather than __(6)__.`,
 blanks:[
 b("C02-B1",1,"hard","context","balance",["compare","match","join"],"The shop must manage both overstock and stockouts, so 'balance' fits.","two risks"),
 b("C02-B2",2,"medium","collocation","consistently",["frequently","regularly","carefully"],"'Keep records consistently' means do it in a steady way over time.","keeping records ..."),
 b("C02-B3",3,"hard","vocabulary","efficient",["accurate","useful","effective"],"Good information helps make buying more efficient, with less waste.","make buying more ..."),
 b("C02-B4",4,"medium","context","disappointing",["ignoring","losing","refusing"],"Running out of expected items can disappoint customers.","without ... customers"),
 b("C02-B5",5,"medium","phrase-fit","significant",["visible","large","strong"],"'A significant effect' means an important effect.","have a ... effect"),
 b("C02-B6",6,"hard","discourse","guesswork",["chance","instinct","memory"],"The contrast is between evidence and guessing, so 'guesswork' fits.","evidence rather than ...")
 ]
},
{
 id:"ENG009-BP-C03",title:"Why Savings Need a Purpose",topic:"personal finance",
 template:`Saving money becomes easier when the saver knows what the money is for. A person who simply decides to "save more" may struggle because the goal is too vague. A clearer target, such as building an emergency fund or paying for a course, gives the effort a specific __(1)__. The amount does not have to be large at the beginning. What matters more is creating a habit that can be maintained. Some people choose to transfer a fixed amount soon after receiving income so that saving happens before other spending begins. This reduces the need to make the same decision repeatedly. It can also make progress easier to measure. However, a savings plan should remain realistic. If the amount is set too high, the saver may need to withdraw money frequently and may eventually stop following the plan. A better approach is to choose an amount that is challenging but still __(2)__. Expenses also change over time, so the plan may need to be adjusted. This does not mean the original goal has failed; it means the method is being made more __(3)__. A clear purpose can also help people decide when not to use the money. Emergency savings, for example, should not be spent on routine wants simply because the balance is available. In this way, a goal gives savings both direction and __(4)__. Financial habits improve when people can see progress and understand why they are making the effort. A useful plan is therefore specific enough to guide action but flexible enough to __(5)__ changing circumstances. Saving becomes more sustainable when it feels like a planned choice rather than a constant __(6)__.`,
 blanks:[
 b("C03-B1",1,"medium","vocabulary","purpose",["reason","target","direction"],"'Purpose' means the clear reason for saving.","gives the effort a specific ..."),
 b("C03-B2",2,"medium","context","manageable",["possible","reasonable","comfortable"],"The amount should be difficult enough to matter but still manageable.","challenging but still ..."),
 b("C03-B3",3,"hard","vocabulary","practical",["flexible","realistic","effective"],"Adjusting the method can make the plan more practical in real life.","method is being made more ..."),
 b("C03-B4",4,"hard","collocation","discipline",["control","order","limit"],"'Direction and discipline' fits the idea of knowing both why and when to save.","both direction and ..."),
 b("C03-B5",5,"medium","grammar","adapt to",["adapt with","adjust on","change for"],"'Adapt to changing circumstances' is the correct phrase.","flexible enough to ... changing circumstances"),
 b("C03-B6",6,"hard","discourse","sacrifice",["restriction","burden","loss"],"The passage contrasts planned saving with feeling deprived, so 'sacrifice' fits.","rather than a constant ...")
 ]
},
{
 id:"ENG009-BP-C04",title:"Remote Work and Communication",topic:"workplace communication",
 template:`Remote work can reduce travel time and give employees more flexibility, but it also changes how information moves through a team. In an office, people can often ask a quick question by turning to a colleague. Online, the same question may require a message, a call or a scheduled meeting. If every small issue becomes a meeting, the team can lose large amounts of time. If people avoid asking questions, mistakes may go __(1)__ for longer. Good remote communication therefore depends on choosing the right channel for each type of problem. A short factual question may be handled by message, while a complex decision may need discussion. Teams also benefit from writing down important decisions so that people who were absent can understand what was agreed. This reduces dependence on memory and repeated explanation. Clear written records are especially useful when people work at different times. They allow work to continue without requiring everyone to be online __(2)__. At the same time, written communication has limits. Tone can be misunderstood, and long message threads may create confusion. Managers should therefore encourage people to move to a call when a written discussion becomes too complex. The goal is not to use one tool for everything, but to use each tool __(3)__. Remote work becomes easier when team members know where to ask questions, where decisions are recorded and when a discussion should be moved to another format. In this way, communication becomes more __(4)__ and less dependent on individual habits. Good systems do not remove the need for judgment, but they make that judgment easier to __(5)__. The best remote teams treat communication as a process that needs design, not as something that will happen __(6)__.`,
 blanks:[
 b("C04-B1",1,"medium","vocabulary","unnoticed",["unseen","unknown","unchecked"],"'Go unnoticed' means not be noticed for some time.","mistakes may go ..."),
 b("C04-B2",2,"medium","phrase-fit","at the same time",["all at once","at one point","in the same place"],"Different schedules mean everyone need not be online at the same time.","everyone to be online ..."),
 b("C04-B3",3,"hard","context","appropriately",["carefully","properly","efficiently"],"Each tool should be used in the right situation, so 'appropriately' fits.","use each tool ..."),
 b("C04-B4",4,"hard","vocabulary","predictable",["formal","standard","regular"],"Clear systems make communication easier to understand and expect.","communication becomes more ..."),
 b("C04-B5",5,"medium","collocation","apply",["make","use","follow"],"'Apply judgment' means use judgment in a situation.","judgment easier to ..."),
 b("C04-B6",6,"hard","discourse","automatically",["naturally","informally","normally"],"The passage says communication needs design, so it should not be assumed to happen automatically.","will happen ...")
 ]
},
{
 id:"ENG009-BP-C05",title:"Customer Complaints as Information",topic:"customer service",
 template:`Businesses often treat complaints as problems to be closed quickly, but complaints can also provide useful information. A single complaint may be unusual, yet repeated complaints about the same issue can reveal a pattern. For this reason, companies should not only answer customers but also record the cause of each problem. If several customers report the same delivery delay, for example, the issue may lie in the process rather than in isolated bad luck. A good complaint system therefore helps the business distinguish between one-time events and problems that need a broader __(1)__. Staff should also know which complaints they can solve themselves and which require escalation. This prevents simple issues from becoming unnecessarily slow while ensuring that serious cases receive the right attention. The response given to the customer still matters. People are more likely to accept a problem when they feel that it has been heard and explained clearly. A quick reply that does not address the real issue may create more frustration. Effective complaint handling therefore combines speed with __(2)__. It also requires businesses to learn from the information they receive. A complaint that is resolved for one customer but never analysed may return again and again. Over time, repeated records can help managers identify weak points and __(3)__ improvements. This turns complaints from isolated messages into a source of operational insight. The aim is not to avoid every complaint, which may be impossible, but to respond well and reduce the causes that can be __(4)__. A mature service system treats complaints seriously without treating every complaint as a crisis. It looks for patterns, acts on evidence and communicates __(5)__. In this way, customer feedback becomes more than a reaction to failure; it becomes part of a process for __(6)__ service.`,
 blanks:[
 b("C05-B1",1,"hard","vocabulary","response",["solution","review","change"],"A repeated problem needs a broader response, not only one reply.","need a broader ..."),
 b("C05-B2",2,"medium","collocation","accuracy",["clarity","detail","care"],"Fast service must still address the real issue accurately.","combines speed with ..."),
 b("C05-B3",3,"hard","phrase-fit","target",["plan","make","direct"],"'Target improvements' means focus improvements where problems are repeated.","... improvements"),
 b("C05-B4",4,"medium","context","prevented",["controlled","avoided","reduced"],"The business should reduce causes that can be prevented.","causes that can be ..."),
 b("C05-B5",5,"medium","vocabulary","clearly",["politely","carefully","openly"],"The passage stresses clear explanation, so 'clearly' fits.","communicates ..."),
 b("C05-B6",6,"hard","discourse","improving",["managing","repairing","supporting"],"The final idea is using complaints to make service better.","process for ... service")
 ]
},
{
 id:"ENG009-BP-C06",title:"Public Transport Reliability",topic:"urban transport",
 template:`Passengers often care as much about reliability as they do about speed. A bus that is slightly slower but arrives near the expected time can be easier to plan around than a faster service that is highly uncertain. This is why transport agencies study not only average journey time but also how much that time __(1)__ from day to day. Large variation makes it difficult for passengers to decide when to leave home or how much extra time to allow. Reliability can be affected by traffic, road works, boarding delays and the way vehicles are scheduled. Some causes are difficult to control, but others can be reduced through better planning. For example, schedules that leave no recovery time may cause one small delay to continue through the entire route. Adding a limited amount of recovery time can help the service return closer to schedule. However, too much extra time can make the published journey unnecessarily long. Planners therefore need to find a balance between efficiency and __(2)__. Real-time information can also help passengers when delays do occur. A late bus is still inconvenient, but accurate information allows people to adjust their plans. This means reliability has two parts: making the service more dependable and making unavoidable disruption more __(3)__. Good transport information should therefore be timely, accurate and easy to understand. A system that gives frequent but unreliable updates may create more confusion than confidence. Trust grows when the information passengers receive is usually __(4)__. Over time, agencies can use delay data to identify problem locations and decide where action would have the greatest effect. The best improvements are often those that reduce repeated causes rather than only responding to individual delays. In this way, reliability becomes something that can be measured, understood and gradually __(5)__. For passengers, the result is not simply a faster journey but a service that is easier to __(6)__.`,
 blanks:[
 b("C06-B1",1,"medium","vocabulary","varies",["changes","moves","shifts"],"'Varies' means changes from one day to another.","time ... from day to day"),
 b("C06-B2",2,"hard","context","reliability",["stability","consistency","flexibility"],"The schedule must be efficient but also reliable.","balance between efficiency and ..."),
 b("C06-B3",3,"hard","vocabulary","manageable",["predictable","acceptable","limited"],"Good information makes disruption easier to handle, so 'manageable' fits.","disruption more ..."),
 b("C06-B4",4,"medium","collocation","correct",["true","accurate","valid"],"Passengers trust updates when the information is usually correct.","information ... is usually ..."),
 b("C06-B5",5,"medium","grammar","improved",["improve","improving","improves"],"After 'can be', we need the past participle 'improved'.","can be measured, understood and gradually ..."),
 b("C06-B6",6,"hard","phrase-fit","plan around",["depend upon","wait for","travel with"],"'Plan around' means organise your time knowing when the service will arrive.","service that is easier to ...")
 ]
},
{
 id:"ENG009-BP-C07",title:"Learning from Pilot Projects",topic:"public policy",
 template:`A pilot project allows an organisation to test an idea on a small scale before expanding it. This can reduce risk because problems are discovered while the programme is still limited. However, a pilot is useful only if its results are studied carefully. A project that appears successful in one location may depend on local conditions that do not exist elsewhere. For this reason, evaluators should ask not only whether the pilot worked, but also why it worked and under what conditions. They should also define success before the project begins. If the goals are changed after the results are known, almost any outcome can be described as positive. Clear measures make the evaluation more __(1)__. A pilot should also include enough time to observe problems that may not appear immediately. Early enthusiasm can make a programme look stronger than it really is. At the same time, testing should not continue forever. Once the main uncertainties have been reduced, decision-makers need to decide whether to expand, modify or stop the project. This requires evidence, judgment and a willingness to accept mixed results. A pilot does not have to be perfect to be useful. It can still provide value by showing what should be changed before a wider __(2)__. The strongest pilots are designed as learning exercises rather than as attempts to prove that an idea was right from the beginning. This makes it easier to discuss failures __(3)__ and use them to improve the next version. Good evaluation separates the question of whether the team worked hard from the question of whether the programme actually produced the desired result. In this way, evidence remains more __(4)__. A small trial cannot answer every question, but it can make the next decision better informed. Its purpose is to replace some uncertainty with knowledge, not to create the __(5)__ of certainty where none exists. Expansion should follow evidence, not simply enthusiasm or pressure. That makes the final decision more __(6)__.`,
 blanks:[
 b("C07-B1",1,"medium","vocabulary","objective",["fair","clear","accurate"],"Clear measures make evaluation more objective and less dependent on opinion.","evaluation more ..."),
 b("C07-B2",2,"hard","collocation","rollout",["launch","release","spread"],"'Wider rollout' is the natural phrase for expanding a programme.","before a wider ..."),
 b("C07-B3",3,"medium","context","openly",["honestly","clearly","freely"],"Learning improves when failures can be discussed openly.","discuss failures ..."),
 b("C07-B4",4,"hard","vocabulary","credible",["reliable","valid","useful"],"Separating effort from results makes the evidence more credible.","evidence remains more ..."),
 b("C07-B5",5,"hard","phrase-fit","illusion",["sense","appearance","idea"],"'Illusion of certainty' means a false feeling that everything is known.","create the ... of certainty"),
 b("C07-B6",6,"medium","discourse","defensible",["reasonable","acceptable","practical"],"Evidence makes the final decision easier to justify, so 'defensible' fits.","decision more ...")
 ]
},
{
 id:"ENG009-BP-C08",title:"Energy Use in Offices",topic:"energy efficiency",
 template:`Office energy use is influenced by more than the efficiency of lights and computers. Behaviour also matters. Equipment may remain switched on overnight, air-conditioning may run in empty rooms and windows may be opened while cooling is active. These small actions can add up across a large building. For this reason, energy programmes often combine technical upgrades with changes in everyday practice. Replacing old equipment can reduce electricity use, but the benefit may be smaller than expected if new equipment is used __(1)__. Managers therefore need data that shows when and where energy is being consumed. Monthly bills give a broad picture, while more detailed meters can reveal patterns during the day. This information can help identify unusual use and check whether a change has had the expected effect. However, measurement alone does not save energy. The data must lead to action. Staff also need clear instructions that fit normal work. A rule that is too difficult to follow may be ignored even if it looks good on paper. Effective programmes therefore try to make the energy-saving choice the __(2)__ choice. Automatic controls can help, but they should not create discomfort or disrupt important work. The aim is to reduce waste rather than simply reduce consumption at any cost. Offices should also compare performance over time because weather and occupancy can change. A higher bill does not always mean lower efficiency if the building was used more heavily. Good analysis therefore compares similar conditions before drawing a __(3)__. When technical and behavioural measures are used together, savings are often more __(4)__. The programme becomes easier to maintain because responsibility is shared between systems and people. Energy efficiency is strongest when it is treated as an ongoing management task rather than a one-time __(5)__. Small improvements can continue to matter when they are repeated across many rooms and many days. In that sense, consistency can be as important as any single __(6)__.`,
 blanks:[
 b("C08-B1",1,"hard","context","carelessly",["heavily","frequently","poorly"],"Efficient equipment can still waste energy if it is used carelessly.","equipment is used ..."),
 b("C08-B2",2,"medium","collocation","easy",["simple","natural","obvious"],"'Make the energy-saving choice the easy choice' means make good behaviour convenient.","the ... choice"),
 b("C08-B3",3,"hard","phrase-fit","conclusion",["judgment","decision","result"],"'Draw a conclusion' is the natural phrase.","before drawing a ..."),
 b("C08-B4",4,"medium","vocabulary","sustainable",["stable","reliable","lasting"],"Combined measures are easier to continue over time, so 'sustainable' fits.","savings are often more ..."),
 b("C08-B5",5,"medium","context","project",["exercise","campaign","effort"],"The passage contrasts ongoing management with a one-time project.","rather than a one-time ..."),
 b("C08-B6",6,"hard","discourse","upgrade",["change","action","investment"],"The sentence contrasts steady small improvements with one single upgrade.","any single ...")
 ]
},
{
 id:"ENG009-BP-C09",title:"The Role of Feedback in Training",topic:"workplace learning",
 template:`Training is most useful when learners can see not only whether an answer is wrong but also why it is wrong. A score alone shows performance, but it may not show what should change next. Good feedback points to the specific mistake and gives enough guidance for the learner to try again. However, feedback can become less useful when it is too long or too general. A learner who receives a page of comments after every small task may struggle to identify the main point. Effective feedback therefore needs to be __(1)__ as well as clear. Timing also matters. Advice given soon after a task is easier to connect with the learner's actual decision. If feedback arrives weeks later, the details may already be forgotten. At the same time, immediate correction is not always best for every activity. Some tasks benefit from allowing learners to think again before seeing the answer. This can strengthen recall and encourage active problem-solving. Trainers should therefore match the timing of feedback to the learning goal. They should also avoid correcting every minor issue at once when one major problem deserves attention first. Priorities help learners focus on what will produce the greatest improvement. Good feedback is not simply criticism. It should show what was done well, what needs to change and what the learner can do next. This makes the process more __(2)__ and less discouraging. Learners are also more likely to use feedback when they understand the reason behind it. A rule without explanation may be remembered for one example but not transferred to a new situation. Clear reasoning helps the learner __(3)__ the idea more widely. In this sense, feedback should support future performance, not merely judge past work. The best comments are specific enough to guide action but concise enough to be __(4)__. Training improves when feedback is treated as part of the learning process rather than as a final __(5)__. Its value comes from helping the learner make a better next attempt. That makes improvement more __(6)__.`,
 blanks:[
 b("C09-B1",1,"medium","vocabulary","focused",["brief","direct","limited"],"'Focused' means centred on the most useful point.","needs to be ... as well as clear"),
 b("C09-B2",2,"hard","context","constructive",["positive","helpful","practical"],"Feedback that shows what to do next is constructive.","process more ... and less discouraging"),
 b("C09-B3",3,"medium","collocation","apply",["use","extend","carry"],"'Apply the idea' means use it in new situations.","helps the learner ... the idea"),
 b("C09-B4",4,"hard","phrase-fit","usable",["readable","useful","memorable"],"Feedback must be short enough that the learner can actually use it.","concise enough to be ..."),
 b("C09-B5",5,"medium","discourse","judgment",["mark","result","comment"],"The passage says feedback should support learning, not only judge it.","rather than as a final ..."),
 b("C09-B6",6,"hard","vocabulary","deliberate",["visible","steady","likely"],"Feedback helps make improvement more deliberate and planned.","improvement more ...")
 ]
},
{
 id:"ENG009-BP-C10",title:"Why Forecasts Need Updating",topic:"business forecasting",
 template:`A forecast is a useful planning tool, but it is not a promise about the future. Businesses use forecasts to estimate sales, costs or demand based on the information available at the time. As new information appears, the forecast may need to change. This does not necessarily mean the earlier forecast was poor. A sudden change in prices, weather or customer behaviour may alter the conditions on which the estimate was based. Good forecasting therefore requires regular __(1)__ rather than blind attachment to the first number. Managers should compare actual results with earlier estimates and ask why the difference occurred. Some differences may come from random variation, while others may reveal that an assumption was wrong. The purpose of this comparison is not to punish whoever made the forecast, but to improve the next one. Forecasts are most useful when their assumptions are written clearly. This allows other people to understand what would need to change before the estimate should be revised. It also helps prevent false precision. A forecast of 10,000 units may look exact, but the real outcome could reasonably fall within a range. Presenting a range can sometimes be more __(2)__ than presenting one precise figure. However, wide ranges are not automatically better because they may become too vague to guide decisions. The forecast must be detailed enough to support action while still acknowledging uncertainty. This balance makes planning more __(3)__. Businesses should also avoid changing forecasts simply to make past performance look better. Revisions should be based on new evidence, not on a desire to hide error. When updates are made openly, the forecast becomes a living planning tool instead of a fixed target. Over time, comparing forecasts with outcomes can reveal which assumptions are most often wrong. This helps teams improve both the data they collect and the way they interpret it. Forecasting becomes more useful when uncertainty is recognised rather than __(4)__. The goal is not to predict perfectly, but to make better decisions under uncertainty. A forecast should therefore guide action without creating false __(5)__. Its real value lies in helping managers prepare for several possible outcomes and adjust when conditions __(6)__.`,
 blanks:[
 b("C10-B1",1,"medium","vocabulary","revision",["review","change","correction"],"Forecasts need regular revision when new information appears.","requires regular ..."),
 b("C10-B2",2,"hard","context","honest",["accurate","realistic","useful"],"A range can be more honest because it shows uncertainty.","more ... than presenting one precise figure"),
 b("C10-B3",3,"hard","vocabulary","robust",["stable","reliable","practical"],"Planning that works under uncertainty is more robust.","balance makes planning more ..."),
 b("C10-B4",4,"medium","discourse","hidden",["ignored","reduced","removed"],"The passage says uncertainty should be recognised, not hidden.","rather than ..."),
 b("C10-B5",5,"hard","phrase-fit","certainty",["confidence","accuracy","security"],"'False certainty' means appearing more sure than the evidence allows.","without creating false ..."),
 b("C10-B6",6,"medium","grammar","change",["changed","changes","changing"],"After 'when conditions', the simple present 'change' fits.","when conditions ...")
 ]
}
];

export const ENG009_CP003_BLANKS_V1=ENG009_CP003_PASSAGES_V1.flatMap(p=>p.blanks.map(blank=>({passage:p,blank})));
