import type { KnowledgeV1Difficulty } from "../../types";
import { ENV_CP014_FACT_BY_ID_V1 } from "./env-cp014-facts";
import type { EnvCp014ReviewQuestion } from "./env-cp014-review-types";

type Seed = {
  qlId: string;
  qlName: string;
  difficulty: KnowledgeV1Difficulty;
  stem: string;
  correct: string;
  distractors: readonly [string, string, string];
  explanation: string;
  sourceFactIds: readonly string[];
};

const POSITIONS = [0, 1, 2, 3] as const;

const S: readonly Seed[] = Object.freeze([
  { qlId:"ENV-014-QL-001", qlName:"Human-caused warming", difficulty:"Easy", stem:"According to IPCC, recent global warming has been caused mainly by:", correct:"Human greenhouse-gas emissions", distractors:["Changes in ocean tides","Earth's magnetic field","Volcanic activity alone"], explanation:"Human greenhouse-gas emissions have unequivocally caused recent global warming.", sourceFactIds:["env-cp014-human-warming"] },
  { qlId:"ENV-014-QL-001", qlName:"Human-caused warming", difficulty:"Easy", stem:"Human influence has warmed which parts of the climate system?", correct:"Atmosphere, ocean and land", distractors:["Only the atmosphere","Only the ocean","Only polar regions"], explanation:"IPCC finds human influence has warmed the atmosphere, ocean and land.", sourceFactIds:["env-cp014-system-warming"] },
  { qlId:"ENV-014-QL-001", qlName:"Human-caused warming", difficulty:"Easy", stem:"Burning fossil fuels contributes to climate change mainly by increasing:", correct:"Greenhouse-gas emissions", distractors:["Earth's rotation speed","Ocean salinity everywhere","Incoming solar radiation"], explanation:"Fossil-fuel use is a major human source of greenhouse-gas emissions.", sourceFactIds:["env-cp014-ghg-sources"] },
  { qlId:"ENV-014-QL-001", qlName:"Human-caused warming", difficulty:"Easy", stem:"Land-use change can contribute to climate change by:", correct:"Releasing greenhouse gases and reducing carbon sinks", distractors:["Stopping all evaporation","Increasing Earth's distance from the Sun","Removing nitrogen from the atmosphere"], explanation:"Land-use change can emit greenhouse gases and reduce carbon storage.", sourceFactIds:["env-cp014-ghg-sources","env-cp014-carbon-sinks"] },

  { qlId:"ENV-014-QL-002", qlName:"Evidence of climate change", difficulty:"Easy", stem:"Which is a major observed indicator of climate change?", correct:"Rising global surface temperature", distractors:["Constant global temperature","Permanent sea-level decline","Expansion of all glaciers"], explanation:"Global average surface temperature has risen since the late nineteenth century.", sourceFactIds:["env-cp014-temperature-evidence"] },
  { qlId:"ENV-014-QL-002", qlName:"Evidence of climate change", difficulty:"Easy", stem:"Which observed change provides evidence of a warming climate?", correct:"Warming of the global ocean", distractors:["Cooling of every ocean basin","Growth of every glacier","Falling sea level everywhere"], explanation:"Ocean warming is an observed part of climate-system warming.", sourceFactIds:["env-cp014-ocean-warming"] },
  { qlId:"ENV-014-QL-002", qlName:"Evidence of climate change", difficulty:"Easy", stem:"Shrinking glaciers are evidence of changes in the Earth's:", correct:"Cryosphere", distractors:["Core only","Magnetic field only","Tectonic plates only"], explanation:"Glaciers are part of the cryosphere and many have lost ice as climate warms.", sourceFactIds:["env-cp014-glacier-loss"] },
  { qlId:"ENV-014-QL-002", qlName:"Evidence of climate change", difficulty:"Easy", stem:"Which combination is consistent with observed climate change?", correct:"Rising temperature, ocean warming and glacier loss", distractors:["Global cooling, glacier growth and falling seas","No temperature change and no ice loss","Only changes in earthquakes"], explanation:"Temperature rise, ocean warming and glacier loss are observed climate indicators.", sourceFactIds:["env-cp014-temperature-evidence","env-cp014-ocean-warming","env-cp014-glacier-loss"] },

  { qlId:"ENV-014-QL-003", qlName:"Sea-level rise", difficulty:"Easy", stem:"Warming seawater raises sea level mainly because it:", correct:"Expands as it warms", distractors:["Becomes solid","Loses all salt","Stops moving"], explanation:"Thermal expansion of warming seawater contributes to sea-level rise.", sourceFactIds:["env-cp014-sea-level-causes"] },
  { qlId:"ENV-014-QL-003", qlName:"Sea-level rise", difficulty:"Easy", stem:"Which process directly adds water to the ocean and raises sea level?", correct:"Melting of land glaciers and ice sheets", distractors:["Melting of floating sea ice only","Evaporation from lakes","Formation of sea ice"], explanation:"Melting land ice adds water to the ocean.", sourceFactIds:["env-cp014-land-ice"] },
  { qlId:"ENV-014-QL-003", qlName:"Sea-level rise", difficulty:"Easy", stem:"Which is NOT a main direct cause of global sea-level rise?", correct:"Melting of floating sea ice", distractors:["Thermal expansion of seawater","Melting mountain glaciers","Loss of ice-sheet mass on land"], explanation:"Floating sea ice already displaces water; land-ice melt and thermal expansion are the main direct causes.", sourceFactIds:["env-cp014-sea-ice-distinction","env-cp014-sea-level-causes"] },
  { qlId:"ENV-014-QL-003", qlName:"Sea-level rise", difficulty:"Easy", stem:"The two main causes of global sea-level rise are:", correct:"Ocean thermal expansion and melting land ice", distractors:["Earthquakes and tides","Sea-ice melt and river flow only","Wind and ocean salinity only"], explanation:"Warming seawater expands and melting land ice adds water to the ocean.", sourceFactIds:["env-cp014-sea-level-causes"] },

  { qlId:"ENV-014-QL-004", qlName:"Cryosphere changes", difficulty:"Medium", stem:"Loss of glacier mass is most directly a change in the:", correct:"Cryosphere", distractors:["Lithosphere only","Magnetosphere","Core"], explanation:"Glaciers and ice sheets are major parts of the cryosphere.", sourceFactIds:["env-cp014-glacier-loss"] },
  { qlId:"ENV-014-QL-004", qlName:"Cryosphere changes", difficulty:"Medium", stem:"Why does melting land ice matter for global sea level?", correct:"It transfers stored land water into the ocean", distractors:["It removes water from the ocean","It prevents thermal expansion","It lowers ocean volume"], explanation:"Land-ice melt adds previously land-stored water to the ocean.", sourceFactIds:["env-cp014-land-ice"] },
  { qlId:"ENV-014-QL-004", qlName:"Cryosphere changes", difficulty:"Medium", stem:"Which statement correctly distinguishes land ice from floating sea ice?", correct:"Land-ice melt directly adds water to the ocean", distractors:["Sea-ice melt is the main direct sea-level driver","Both add the same new water volume to the ocean","Land ice has no effect on sea level"], explanation:"Melting land ice directly increases ocean water volume.", sourceFactIds:["env-cp014-land-ice","env-cp014-sea-ice-distinction"] },
  { qlId:"ENV-014-QL-004", qlName:"Cryosphere changes", difficulty:"Medium", stem:"Which observed change best indicates loss of stored land ice?", correct:"Shrinking glaciers and ice-sheet mass loss", distractors:["More ocean tides","Higher atmospheric nitrogen","Faster plate movement"], explanation:"Glacier retreat and ice-sheet mass loss show declining land ice.", sourceFactIds:["env-cp014-glacier-loss"] },

  { qlId:"ENV-014-QL-005", qlName:"Weather and climate extremes", difficulty:"Medium", stem:"Human-caused climate change has made hot extremes across most land regions generally:", correct:"More frequent and more intense", distractors:["Less frequent and weaker everywhere","Unchanged everywhere","Impossible to observe"], explanation:"Hot extremes have become more frequent and intense across most land regions.", sourceFactIds:["env-cp014-hot-extremes"] },
  { qlId:"ENV-014-QL-005", qlName:"Weather and climate extremes", difficulty:"Medium", stem:"With increasing global warming, heavy precipitation events generally tend to become:", correct:"More intense", distractors:["Impossible","Always weaker","Completely unrelated to warming"], explanation:"IPCC finds heavy precipitation generally intensifies with more global warming.", sourceFactIds:["env-cp014-heavy-rain"] },
  { qlId:"ENV-014-QL-005", qlName:"Weather and climate extremes", difficulty:"Medium", stem:"Which extreme has a particularly strong global link with human-caused warming?", correct:"Hot extremes and heatwaves", distractors:["Earthquakes","Volcanic eruptions","Tsunamis"], explanation:"Human influence is a main driver of the observed increase in hot extremes.", sourceFactIds:["env-cp014-hot-extremes"] },
  { qlId:"ENV-014-QL-005", qlName:"Weather and climate extremes", difficulty:"Medium", stem:"Which statement about climate extremes is most accurate?", correct:"Warming can increase the intensity of some extremes such as heat and heavy rainfall", distractors:["Climate change affects no extremes","Every extreme has the same trend everywhere","Only earthquakes respond to greenhouse gases"], explanation:"Warming strengthens several climate extremes, though regional patterns differ.", sourceFactIds:["env-cp014-hot-extremes","env-cp014-heavy-rain"] },

  { qlId:"ENV-014-QL-006", qlName:"Ocean warming and acidification", difficulty:"Medium", stem:"Ocean acidification occurs mainly because seawater absorbs more:", correct:"Carbon dioxide", distractors:["Helium","Argon","Nitrogen gas only"], explanation:"Absorbed carbon dioxide changes seawater chemistry and increases acidity.", sourceFactIds:["env-cp014-ocean-acidification"] },
  { qlId:"ENV-014-QL-006", qlName:"Ocean warming and acidification", difficulty:"Medium", stem:"As ocean acidification increases, seawater pH generally:", correct:"Decreases", distractors:["Increases without limit","Becomes exactly neutral","Becomes unrelated to carbon dioxide"], explanation:"Greater acidity means lower pH.", sourceFactIds:["env-cp014-ocean-acidification"] },
  { qlId:"ENV-014-QL-006", qlName:"Ocean warming and acidification", difficulty:"Medium", stem:"Which observed ocean change is part of the warming climate system?", correct:"Rising ocean temperature", distractors:["Permanent global ocean cooling","No ocean heat change","Loss of all dissolved salts"], explanation:"The ocean has warmed as the climate system has warmed.", sourceFactIds:["env-cp014-ocean-warming"] },
  { qlId:"ENV-014-QL-006", qlName:"Ocean warming and acidification", difficulty:"Medium", stem:"Which pair is correctly matched?", correct:"CO2 absorption — ocean acidification", distractors:["Ocean warming — lower sea level by contraction","Land-ice melt — lower ocean volume","Sea-level rise — no link with warming"], explanation:"Seawater absorption of carbon dioxide drives ocean acidification.", sourceFactIds:["env-cp014-ocean-acidification"] },

  { qlId:"ENV-014-QL-007", qlName:"Climate-change impacts", difficulty:"Medium", stem:"Climate change can affect which group of systems?", correct:"Food, water, health and ecosystems", distractors:["Only tectonic plates","Only Earth's magnetic field","Only lunar tides"], explanation:"Climate change already affects food, water, health, ecosystems and societies.", sourceFactIds:["env-cp014-impacts"] },
  { qlId:"ENV-014-QL-007", qlName:"Climate-change impacts", difficulty:"Medium", stem:"Which is a broad documented consequence of climate change?", correct:"Growing risks to ecosystems and human systems", distractors:["Elimination of all weather hazards","Stopping all sea-level change","Uniform benefits in every region"], explanation:"Climate change creates widespread risks for natural and human systems.", sourceFactIds:["env-cp014-impacts"] },
  { qlId:"ENV-014-QL-007", qlName:"Climate-change impacts", difficulty:"Medium", stem:"Water and food security are affected by climate change mainly through changes in:", correct:"Temperature, rainfall and extremes", distractors:["Earth's core temperature only","Magnetic north only","Lunar phases only"], explanation:"Climate impacts on temperature, rainfall and extremes affect water and food systems.", sourceFactIds:["env-cp014-impacts","env-cp014-hot-extremes","env-cp014-heavy-rain"] },
  { qlId:"ENV-014-QL-007", qlName:"Climate-change impacts", difficulty:"Medium", stem:"Which statement about climate impacts is correct?", correct:"They affect both natural ecosystems and human societies", distractors:["They affect only oceans","They affect only polar wildlife","They do not affect health or food systems"], explanation:"Observed climate impacts extend across ecosystems and human societies.", sourceFactIds:["env-cp014-impacts"] },

  { qlId:"ENV-014-QL-008", qlName:"Mitigation", difficulty:"Medium", stem:"Climate-change mitigation mainly aims to:", correct:"Reduce emissions or enhance greenhouse-gas sinks", distractors:["Measure earthquakes","Increase vulnerability","Respond only after flood damage"], explanation:"Mitigation acts on climate causes by reducing emissions or enhancing sinks.", sourceFactIds:["env-cp014-mitigation-definition"] },
  { qlId:"ENV-014-QL-008", qlName:"Mitigation", difficulty:"Medium", stem:"Replacing fossil-fuel electricity with renewable energy is an example of:", correct:"Mitigation", distractors:["Adaptation only","Weather forecasting","Disaster relief only"], explanation:"Renewable energy can reduce greenhouse-gas emissions.", sourceFactIds:["env-cp014-mitigation-examples"] },
  { qlId:"ENV-014-QL-008", qlName:"Mitigation", difficulty:"Medium", stem:"Improving energy efficiency is mainly a climate:", correct:"Mitigation measure", distractors:["Adaptation measure only","Sea-level indicator","Ozone-depletion mechanism"], explanation:"Energy efficiency can reduce energy use and greenhouse-gas emissions.", sourceFactIds:["env-cp014-mitigation-examples"] },
  { qlId:"ENV-014-QL-008", qlName:"Mitigation", difficulty:"Medium", stem:"Protecting and restoring forests can support mitigation by:", correct:"Maintaining or increasing carbon sinks", distractors:["Increasing fossil-fuel use","Reducing all rainfall","Increasing sea-level rise"], explanation:"Forests remove and store carbon dioxide, so protecting them can strengthen sinks.", sourceFactIds:["env-cp014-mitigation-examples","env-cp014-carbon-sinks"] },

  { qlId:"ENV-014-QL-009", qlName:"Adaptation", difficulty:"Medium", stem:"Climate adaptation mainly aims to:", correct:"Reduce vulnerability to climate impacts", distractors:["Increase greenhouse-gas emissions","Cause global warming","Destroy carbon sinks"], explanation:"Adaptation adjusts systems to reduce harm from current or expected impacts.", sourceFactIds:["env-cp014-adaptation-definition"] },
  { qlId:"ENV-014-QL-009", qlName:"Adaptation", difficulty:"Medium", stem:"Building flood defences against rising flood risk is an example of:", correct:"Adaptation", distractors:["Mitigation only","Ozone protection","Carbon emission accounting only"], explanation:"Flood defences reduce vulnerability to climate-related impacts.", sourceFactIds:["env-cp014-adaptation-examples"] },
  { qlId:"ENV-014-QL-009", qlName:"Adaptation", difficulty:"Medium", stem:"Developing drought-resilient crop varieties is mainly a form of:", correct:"Adaptation", distractors:["Ozone depletion","Sea-level mitigation only","Carbon combustion"], explanation:"Drought-resilient crops help food systems cope with climate impacts.", sourceFactIds:["env-cp014-adaptation-examples"] },
  { qlId:"ENV-014-QL-009", qlName:"Adaptation", difficulty:"Medium", stem:"Early-warning systems for climate-related hazards are mainly an example of:", correct:"Adaptation", distractors:["Fossil-fuel expansion","Greenhouse-gas generation","Ozone depletion"], explanation:"Early-warning systems help societies prepare for climate hazards.", sourceFactIds:["env-cp014-adaptation-examples"] },

  { qlId:"ENV-014-QL-010", qlName:"Mitigation vs adaptation and sinks", difficulty:"Medium", stem:"Which option correctly distinguishes mitigation from adaptation?", correct:"Mitigation addresses causes; adaptation addresses impacts and vulnerability", distractors:["Both mean only disaster relief","Adaptation reduces emissions only","Mitigation means only flood defence"], explanation:"Mitigation tackles emissions and sinks, while adaptation reduces climate vulnerability.", sourceFactIds:["env-cp014-mitigation-adaptation"] },
  { qlId:"ENV-014-QL-010", qlName:"Mitigation vs adaptation and sinks", difficulty:"Medium", stem:"Which of the following is a carbon sink?", correct:"Forest", distractors:["Coal-fired power plant","Petrol engine","Cement kiln"], explanation:"Forests can remove and store carbon dioxide from the atmosphere.", sourceFactIds:["env-cp014-carbon-sinks"] },
  { qlId:"ENV-014-QL-010", qlName:"Mitigation vs adaptation and sinks", difficulty:"Medium", stem:"Enhancing a carbon sink is classified as:", correct:"Mitigation", distractors:["Adaptation only","Weather observation only","Disaster reporting only"], explanation:"Mitigation includes enhancing sinks that remove greenhouse gases.", sourceFactIds:["env-cp014-enhance-sinks","env-cp014-mitigation-definition"] },
  { qlId:"ENV-014-QL-010", qlName:"Mitigation vs adaptation and sinks", difficulty:"Medium", stem:"Which pair contains one mitigation and one adaptation measure, respectively?", correct:"Renewable energy; flood defence", distractors:["Flood defence; renewable energy","Drought-resilient crop; early warning","Coal expansion; deforestation"], explanation:"Renewable energy reduces emissions; flood defence reduces vulnerability to impacts.", sourceFactIds:["env-cp014-mitigation-examples","env-cp014-adaptation-examples","env-cp014-mitigation-adaptation"] },

  { qlId:"ENV-014-QL-011", qlName:"Correct / incorrect pair", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"Thermal expansion — sea-level rise", distractors:["Land-ice melt — falling sea level","Mitigation — increasing vulnerability","Adaptation — increasing emissions"], explanation:"Warming seawater expands and contributes to sea-level rise.", sourceFactIds:["env-cp014-sea-level-causes"] },
  { qlId:"ENV-014-QL-011", qlName:"Correct / incorrect pair", difficulty:"Hard", stem:"Which pair is incorrectly matched?", correct:"Flood defence — mitigation", distractors:["Renewable energy — mitigation","Drought-resilient crops — adaptation","Forest protection — sink enhancement"], explanation:"Flood defence is adaptation because it reduces vulnerability to impacts.", sourceFactIds:["env-cp014-adaptation-examples","env-cp014-mitigation-examples"] },
  { qlId:"ENV-014-QL-011", qlName:"Correct / incorrect pair", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"Carbon sink — removes CO2 from the atmosphere", distractors:["Ocean acidification — rising pH","Biomass burning — adaptation","Heatwave increase — cryosphere growth"], explanation:"A carbon sink removes more carbon dioxide than it releases over the relevant period.", sourceFactIds:["env-cp014-carbon-sinks"] },
  { qlId:"ENV-014-QL-011", qlName:"Correct / incorrect pair", difficulty:"Hard", stem:"Which pair is incorrectly matched?", correct:"Ocean acidification — higher seawater pH", distractors:["Hot extremes — stronger with warming","Land-ice melt — sea-level rise","Energy efficiency — mitigation"], explanation:"Ocean acidification lowers, rather than raises, seawater pH.", sourceFactIds:["env-cp014-ocean-acidification","env-cp014-hot-extremes","env-cp014-land-ice","env-cp014-mitigation-examples"] },

  { qlId:"ENV-014-QL-012", qlName:"Statements and applied identification", difficulty:"Hard", stem:"Consider the statements:\n1. Human greenhouse-gas emissions have caused recent global warming.\n2. Ocean warming and glacier loss are observed climate indicators.\n3. Melting floating sea ice is the main direct cause of sea-level rise.\nHow many are correct?", correct:"Two", distractors:["One","Three","None"], explanation:"Statements 1 and 2 are correct; floating sea ice is not the main direct sea-level driver.", sourceFactIds:["env-cp014-human-warming","env-cp014-ocean-warming","env-cp014-glacier-loss","env-cp014-sea-ice-distinction"] },
  { qlId:"ENV-014-QL-012", qlName:"Statements and applied identification", difficulty:"Hard", stem:"Consider the statements:\n1. Mitigation can reduce emissions or enhance sinks.\n2. Adaptation can reduce vulnerability to climate impacts.\n3. Flood defence is mainly a mitigation measure.\nHow many are correct?", correct:"Two", distractors:["One","Three","None"], explanation:"The first two are correct; flood defence is adaptation.", sourceFactIds:["env-cp014-mitigation-definition","env-cp014-adaptation-definition","env-cp014-adaptation-examples"] },
  { qlId:"ENV-014-QL-012", qlName:"Statements and applied identification", difficulty:"Hard", stem:"A coastal city builds sea walls and improves flood warnings. These actions are mainly:", correct:"Adaptation", distractors:["Mitigation only","Ozone depletion","Carbon-source expansion"], explanation:"These measures reduce vulnerability to climate impacts rather than emissions.", sourceFactIds:["env-cp014-adaptation-examples","env-cp014-adaptation-definition"] },
  { qlId:"ENV-014-QL-012", qlName:"Statements and applied identification", difficulty:"Hard", stem:"A country expands solar power and restores forests. The main climate purpose is:", correct:"Mitigation", distractors:["Adaptation only","Increasing emissions","Increasing ocean acidity"], explanation:"Solar power can reduce emissions and forest restoration can enhance carbon sinks.", sourceFactIds:["env-cp014-mitigation-examples","env-cp014-carbon-sinks","env-cp014-enhance-sinks"] },
]);

function sourceIdsFor(sourceFactIds: readonly string[]): string[] {
  return [...new Set(sourceFactIds.flatMap((id) => ENV_CP014_FACT_BY_ID_V1.get(id)?.sourceIds ?? []))];
}

export const ENV_CP014_REVIEW_QUESTIONS_V1: readonly EnvCp014ReviewQuestion[] = Object.freeze(
  S.map((seed, index) => {
    const localIndex = index % 4;
    const correctIndex = POSITIONS[localIndex];
    const options = [...seed.distractors];
    options.splice(correctIndex, 0, seed.correct);
    return {
      questionId: `ENV-CP014-V1-${String(index + 1).padStart(3, "0")}`,
      chapterId: "ENV-001",
      cpId: "ENV-CP-014",
      qlId: seed.qlId,
      qlName: seed.qlName,
      difficulty: seed.difficulty,
      stem: seed.stem,
      options,
      correctIndex,
      canonicalAnswer: seed.correct,
      explanation: seed.explanation,
      sourceIds: sourceIdsFor(seed.sourceFactIds),
      sourceFactIds: [...seed.sourceFactIds],
      reviewOnly: true,
      runtimeRegistered: false,
    };
  }),
);
