import {
  SAP_CP003_PROTOTYPE_IDS,
  type SapCp003PrototypeAuthority,
  type SapCp003PrototypeId,
} from "./types";

const AUTHORITIES: Readonly<Record<SapCp003PrototypeId, Omit<SapCp003PrototypeAuthority, "prototypeId" | "sourceStatus">>> = Object.freeze({
  "SAP-CP003-PROT-TERMINATING-DECIMAL-EXPRESSION": {
    solveMode: "evaluateTerminatingDecimalExpression",
    title: "Evaluate a terminating-decimal expression",
    solveAuthority: "Preserve place value and operation order while evaluating terminating decimals exactly.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["TERMINATING_DECIMAL", "MIXED_OPERATION"],
  },
  "SAP-CP003-PROT-DECIMAL-FRACTION-MIXED-EXPRESSION": {
    solveMode: "evaluateDecimalFractionMixedExpression",
    title: "Evaluate a mixed decimal-and-fraction expression",
    solveAuthority: "Convert representations only where useful and keep one exact rational value throughout.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["TERMINATING_DECIMAL", "FRACTION"],
  },
  "SAP-CP003-PROT-DECIMAL-PRODUCT-PLACE-VALUE": {
    solveMode: "evaluateDecimalProductByPlaceValue",
    title: "Multiply decimals using place value",
    solveAuthority: "Multiply the corresponding integers and restore the total number of decimal places.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["DECIMAL_PRODUCT", "PLACE_VALUE"],
  },
  "SAP-CP003-PROT-DECIMAL-DIVISION-POWER-OF-TEN": {
    solveMode: "evaluateDecimalDivisionByPowerOfTen",
    title: "Divide a decimal by a power of ten",
    solveAuthority: "Shift the decimal point left by the number of zeros in the divisor.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["DECIMAL_DIVISION", "POWER_OF_TEN"],
  },
  "SAP-CP003-PROT-DECIMAL-DIVISION-COMPATIBLE-FACTOR": {
    solveMode: "evaluateDecimalDivisionByCompatibleFactor",
    title: "Divide by a compatible decimal factor",
    solveAuthority: "Replace the divisor by an equivalent fraction or scale both terms to obtain an integer divisor.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["DECIMAL_DIVISION", "COMPATIBLE_FACTOR"],
  },
  "SAP-CP003-PROT-PERCENTAGE-AS-NUMERIC-FACTOR": {
    solveMode: "evaluatePercentageAsNumericFactor",
    title: "Use a percentage as an exact numeric factor",
    solveAuthority: "Replace p% by p/100 and evaluate the resulting arithmetic expression.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["PERCENTAGE_LITERAL", "NUMERIC_FACTOR"],
  },
  "SAP-CP003-PROT-PERCENT-OF-QUANTITY-IN-EXPRESSION": {
    solveMode: "evaluatePercentOfQuantityInsideExpression",
    title: "Evaluate a scoped percentage-of quantity inside an expression",
    solveAuthority: "Evaluate the complete percentage-of block before combining it with the remaining expression.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["SCOPED_OF", "PERCENTAGE_LITERAL"],
  },
  "SAP-CP003-PROT-MIXED-PERCENT-FRACTION-DECIMAL": {
    solveMode: "evaluateMixedPercentFractionDecimalExpression",
    title: "Evaluate a mixed percentage, fraction and decimal expression",
    solveAuthority: "Normalise all displayed values to one exact representation and then apply operation order.",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLIFIED_RATIONAL",
    representations: ["PERCENTAGE_LITERAL", "FRACTION", "TERMINATING_DECIMAL"],
  },
  "SAP-CP003-PROT-CONVERT-TERMS-TO-FRACTIONS": {
    solveMode: "convertDisplayedTermsToFractionsThenEvaluate",
    title: "Convert displayed decimals and percentages to fractions",
    solveAuthority: "Convert each terminating decimal or percentage to an exact fraction before evaluation.",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLIFIED_RATIONAL",
    representations: ["REPRESENTATION_SWITCH", "FRACTION_TARGET"],
  },
  "SAP-CP003-PROT-CONVERT-TERMS-TO-DECIMALS": {
    solveMode: "convertDisplayedTermsToDecimalsThenEvaluate",
    title: "Convert compatible fractions and percentages to decimals",
    solveAuthority: "Use terminating decimal equivalents and evaluate by place value.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["REPRESENTATION_SWITCH", "DECIMAL_TARGET"],
  },
  "SAP-CP003-PROT-KNOWN-FRACTION-DECIMAL-EQUIVALENCE": {
    solveMode: "useKnownFractionDecimalEquivalence",
    title: "Use known fraction-decimal equivalences",
    solveAuthority: "Recognise benchmark equivalents such as 1/8 = 0.125 and 3/8 = 0.375 to shorten exact evaluation.",
    taskDirection: "FORWARD",
    answerSemantic: "INTEGER",
    representations: ["BENCHMARK_EQUIVALENCE", "FRACTION", "DECIMAL"],
  },
  "SAP-CP003-PROT-RECURRING-DECIMAL-IN-EXPRESSION": {
    solveMode: "evaluateRecurringDecimalInsideExpression",
    title: "Use a recurring decimal inside a larger exact expression",
    solveAuthority: "Convert the supported recurring decimal to its exact rational value and then evaluate the complete expression.",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLIFIED_RATIONAL",
    representations: ["RECURRING_DECIMAL", "FRACTION"],
  },
  "SAP-CP003-PROT-COMPLEMENTARY-PERCENTAGE-EXPRESSION": {
    solveMode: "evaluateComplementaryPercentageExpression",
    title: "Evaluate complementary percentage factors",
    solveAuthority: "Combine percentage factors that total one whole before multiplying by the shared quantity.",
    taskDirection: "FORWARD",
    answerSemantic: "INTEGER",
    representations: ["COMPLEMENTARY_PERCENTAGES", "COMMON_QUANTITY"],
  },
  "SAP-CP003-PROT-SUCCESSIVE-PERCENT-FACTORS": {
    solveMode: "evaluateSuccessivePercentFactorsAsPureArithmetic",
    title: "Evaluate successive percentage factors as pure arithmetic",
    solveAuthority: "Convert every percentage factor to an exact rational multiplier and multiply in order.",
    taskDirection: "FORWARD",
    answerSemantic: "TERMINATING_DECIMAL",
    representations: ["SUCCESSIVE_FACTORS", "PERCENTAGE_LITERAL"],
  },
  "SAP-CP003-PROT-MISSING-DECIMAL-OPERAND": {
    solveMode: "findMissingDecimalOperandInFixedExpression",
    title: "Find a missing decimal operand",
    solveAuthority: "Apply one direct inverse operation and verify the missing decimal by substitution.",
    taskDirection: "INVERSE",
    answerSemantic: "MISSING_DECIMAL",
    representations: ["FIXED_EQUALITY", "MISSING_DECIMAL"],
  },
  "SAP-CP003-PROT-MISSING-PERCENTAGE-LITERAL": {
    solveMode: "findMissingPercentageLiteralInFixedArithmeticExpression",
    title: "Find a missing percentage literal in a fixed expression",
    solveAuthority: "Isolate the percentage factor and convert the resulting exact multiplier to a percentage literal.",
    taskDirection: "INVERSE",
    answerSemantic: "MISSING_PERCENTAGE",
    representations: ["FIXED_EQUALITY", "MISSING_PERCENTAGE"],
  },
  "SAP-CP003-PROT-COMPARE-FRACTION-DECIMAL-PERCENT": {
    solveMode: "compareEquivalentFractionDecimalPercentResults",
    title: "Compare exact results shown in different representations",
    solveAuthority: "Convert both sides to exact rational values and compare without rounding.",
    taskDirection: "COMPARISON",
    answerSemantic: "COMPARISON_CLASS",
    representations: ["FRACTION", "DECIMAL", "PERCENTAGE_LITERAL"],
  },
  "SAP-CP003-PROT-SELECT-CORRECT-DECIMAL-PLACEMENT": {
    solveMode: "selectCorrectDecimalPlacement",
    title: "Select the correctly placed decimal point",
    solveAuthority: "Determine the exact integer product or quotient first, then restore the required decimal scale.",
    taskDirection: "SELECTION",
    answerSemantic: "OPTION_VALUE",
    representations: ["DECIMAL_PLACEMENT", "HOMOGENEOUS_NUMERIC_OPTIONS"],
  },
  "SAP-CP003-PROT-IDENTIFY-INCORRECT-CONVERSION-STEP": {
    solveMode: "identifyIncorrectRepresentationConversionStep",
    title: "Identify the first incorrect representation-conversion step",
    solveAuthority: "Compare consecutive exact values and select the earliest conversion or arithmetic step that changes the value.",
    taskDirection: "DIAGNOSIS",
    answerSemantic: "STEP_SELECTION",
    representations: ["WORKED_CHAIN", "DECIMAL", "FRACTION", "PERCENTAGE_LITERAL"],
  },
});

export const SAP_CP003_PROTOTYPE_AUTHORITIES: readonly SapCp003PrototypeAuthority[] = Object.freeze(
  SAP_CP003_PROTOTYPE_IDS.map((prototypeId) => Object.freeze({
    prototypeId,
    ...AUTHORITIES[prototypeId],
    sourceStatus: "SCOPE_AUTHORITY_APPROVED_EXECUTABLE_DISCOVERY" as const,
  })),
);

export const SAP_CP003_AUTHORITY_BY_ID: Readonly<Record<SapCp003PrototypeId, SapCp003PrototypeAuthority>> = Object.freeze(
  Object.fromEntries(SAP_CP003_PROTOTYPE_AUTHORITIES.map((authority) => [authority.prototypeId, authority])) as Record<SapCp003PrototypeId, SapCp003PrototypeAuthority>,
);

export const SAP_CP003_DISCOVERY_STATE = Object.freeze({
  packageId: "SAP-001" as const,
  checkpointId: "SAP-CP-003" as const,
  scopeAuthority: "SAP-CP-001-TO-CP-012-SCOPE-AUTHORITY.md" as const,
  prototypeCount: SAP_CP003_PROTOTYPE_IDS.length,
  permanentQlRange: null,
  nextAvailableQlId: "SAP-QL-034" as const,
  lifecycle: "EXECUTABLE_DISCOVERY_HUMAN_REVIEW_PENDING" as const,
  questionStudioDiscoverable: false as const,
  questionBankWritable: false as const,
  testEligible: false as const,
  publiclyPublishable: false as const,
});
