export type SemanticDomainV4 =
  | "education"
  | "transport"
  | "commerce"
  | "science"
  | "sports"
  | "public-service"
  | "technology"
  | "environment"
  | "hospitality"
  | "healthcare"
  | "agriculture"
  | "media"
  | "household"
  | "infrastructure"
  | "banking"
  | "manufacturing"
  | "energy"
  | "postal"
  | "culture"
  | "emergency-service";

interface PredicateFrameV4 {
  id: string;
  singularVerb: string;
  pluralVerb: string;
  segment3: string;
  segment4: string;
}

interface SemanticFamilyV4 {
  id: string;
  domain: SemanticDomainV4;
  singular: string;
  plural: string;
  modifiers: readonly [string, string];
  predicates: readonly [PredicateFrameV4, PredicateFrameV4, PredicateFrameV4, PredicateFrameV4];
}

export interface SemanticSceneV4 {
  id: string;
  familyId: string;
  domain: SemanticDomainV4;
  singular: string;
  plural: string;
  singularVerb: string;
  pluralVerb: string;
  segment3: string;
  segment4: string;
  modifiers: readonly [string, string];
}

const p = (id: string, singularVerb: string, pluralVerb: string, segment3: string, segment4: string): PredicateFrameV4 => ({ id, singularVerb, pluralVerb, segment3, segment4 });
const f = (id: string, domain: SemanticDomainV4, singular: string, plural: string, modifiers: readonly [string, string], predicates: readonly [PredicateFrameV4, PredicateFrameV4, PredicateFrameV4, PredicateFrameV4]): SemanticFamilyV4 => ({ id, domain, singular, plural, modifiers, predicates });

export const SEMANTIC_FAMILIES_V4: readonly SemanticFamilyV4[] = [
  // Education
  f("edu-student", "education", "student", "students", ["from the senior class", "preparing for the final test"], [p("borrow-book", "has borrowed", "have borrowed", "a reference book", "from the library."), p("complete-assignment", "has completed", "have completed", "the science assignment", "before the deadline."), p("join-workshop", "is attending", "are attending", "the revision workshop", "this afternoon."), p("read-guidelines", "has read", "have read", "the examination guidelines", "carefully.")]),
  f("edu-teacher", "education", "teacher", "teachers", ["teaching the senior section", "handling the revision class"], [p("prepare-lesson", "has prepared", "have prepared", "the lesson plan", "for tomorrow's class."), p("check-notebooks", "has checked", "have checked", "the exercise notebooks", "before the meeting."), p("arrange-quiz", "is arranging", "are arranging", "a short classroom quiz", "for the next period."), p("review-project", "has reviewed", "have reviewed", "the group project", "with the students.")]),
  f("edu-librarian", "education", "librarian", "librarians", ["working at the issue desk", "assigned to the reference section"], [p("catalogue-books", "has catalogued", "have catalogued", "the new books", "in the library system."), p("issue-card", "has issued", "have issued", "a new library card", "to the reader."), p("update-register", "has updated", "have updated", "the issue register", "before closing time."), p("arrange-shelf", "is arranging", "are arranging", "the returned books", "on the correct shelves.")]),
  f("edu-pupil", "education", "pupil", "pupils", ["working on the class project", "joining the reading programme"], [p("submit-project", "has submitted", "have submitted", "the class project", "on time."), p("solve-worksheet", "has solved", "have solved", "the practice worksheet", "without help."), p("attend-reading", "is attending", "are attending", "the reading session", "after lunch."), p("return-book", "has returned", "have returned", "the library book", "before the due date.")]),
  f("edu-lecturer", "education", "lecturer", "lecturers", ["teaching the afternoon course", "leading the seminar group"], [p("deliver-lecture", "has delivered", "have delivered", "the opening lecture", "for the new course."), p("review-papers", "has reviewed", "have reviewed", "the seminar papers", "before discussion."), p("prepare-slides", "has prepared", "have prepared", "the presentation slides", "for the next lecture."), p("answer-questions", "is answering", "are answering", "the students' questions", "after the lecture.")]),
  f("edu-tutor", "education", "tutor", "tutors", ["working with the study group", "handling the evening class"], [p("explain-chapter", "has explained", "have explained", "the difficult chapter", "with simple examples."), p("mark-test", "has marked", "have marked", "the practice test", "before the next class."), p("schedule-class", "has scheduled", "have scheduled", "an extra class", "for the weekend."), p("share-notes", "has shared", "have shared", "the revision notes", "with the learners.")]),
  f("edu-candidate", "education", "candidate", "candidates", ["appearing in the final stage", "registered for the written test"], [p("download-card", "has downloaded", "have downloaded", "the admit card", "from the examination portal."), p("read-instructions", "has read", "have read", "the reporting instructions", "before the test."), p("check-schedule", "has checked", "have checked", "the examination schedule", "twice."), p("carry-id", "is carrying", "are carrying", "a valid identity card", "for verification.")]),
  f("edu-trainee", "education", "trainee", "trainees", ["enrolled in the practical course", "attending the morning batch"], [p("complete-module", "has completed", "have completed", "the first training module", "successfully."), p("attend-demo", "is attending", "are attending", "the practical demonstration", "in the workshop."), p("submit-feedback", "has submitted", "have submitted", "the course feedback", "after the session."), p("practise-procedure", "is practising", "are practising", "the safety procedure", "under supervision.")]),

  // Transport
  f("tr-passenger", "transport", "passenger", "passengers", ["holding a reserved ticket", "travelling on the morning service"], [p("wait-gate", "is waiting", "are waiting", "near the departure gate", "for the train."), p("carry-bag", "is carrying", "are carrying", "a small travel bag", "onto the platform."), p("check-board", "has checked", "have checked", "the departure board", "before boarding."), p("request-seat", "has requested", "have requested", "a window seat", "for the journey.")]),
  f("tr-driver", "transport", "driver", "drivers", ["assigned to the early service", "driving the longer route"], [p("check-brakes", "has checked", "have checked", "the vehicle's brakes", "before departure."), p("report-delay", "has reported", "have reported", "the traffic delay", "to the control room."), p("follow-route", "is following", "are following", "the revised route", "during the road closure."), p("inspect-tyres", "has inspected", "have inspected", "the front tyres", "before the trip.")]),
  f("tr-conductor", "transport", "conductor", "conductors", ["working on the late service", "assigned to the express route"], [p("check-tickets", "is checking", "are checking", "the passengers' tickets", "after departure."), p("announce-stop", "has announced", "have announced", "the next stop", "over the public system."), p("help-passenger", "is helping", "are helping", "an elderly passenger", "with the luggage."), p("count-seats", "has counted", "have counted", "the vacant seats", "in the rear coach.")]),
  f("tr-cyclist", "transport", "cyclist", "cyclists", ["riding after sunset", "using the marked cycle lane"], [p("wear-jacket", "is wearing", "are wearing", "a reflective jacket", "for the evening ride."), p("check-brakes", "has checked", "have checked", "the bicycle brakes", "before leaving home."), p("carry-light", "is carrying", "are carrying", "a working rear light", "for better visibility."), p("follow-lane", "is using", "are using", "the marked cycle lane", "through the busy section.")]),
  f("tr-commuter", "transport", "commuter", "commuters", ["travelling during peak hours", "using the weekly travel pass"], [p("board-bus", "has boarded", "have boarded", "the first available bus", "after a short wait."), p("check-time", "has checked", "have checked", "the revised timetable", "before leaving."), p("change-route", "is taking", "are taking", "an alternative route", "because of the closure."), p("renew-pass", "has renewed", "have renewed", "the travel pass", "for another week.")]),
  f("tr-mechanic", "transport", "mechanic", "mechanics", ["working in the vehicle workshop", "assigned to the maintenance bay"], [p("repair-engine", "has repaired", "have repaired", "the faulty engine", "before the next shift."), p("replace-belt", "has replaced", "have replaced", "the worn belt", "during servicing."), p("test-brakes", "is testing", "are testing", "the braking system", "after the repair."), p("record-service", "has recorded", "have recorded", "the maintenance work", "in the service log.")]),
  f("tr-inspector", "transport", "inspector", "inspectors", ["checking the morning services", "assigned to the safety review"], [p("inspect-vehicle", "has inspected", "have inspected", "the passenger vehicle", "before it entered service."), p("check-permit", "has checked", "have checked", "the route permit", "at the terminal."), p("record-defect", "has recorded", "have recorded", "a minor safety defect", "in the inspection report."), p("verify-log", "is verifying", "are verifying", "the driver's log", "during the routine check.")]),
  f("tr-traveller", "transport", "traveller", "travellers", ["continuing a long journey", "carrying only hand luggage"], [p("book-seat", "has booked", "have booked", "a seat on the overnight service", "in advance."), p("collect-ticket", "has collected", "have collected", "the printed ticket", "from the counter."), p("check-platform", "is checking", "are checking", "the platform number", "on the display board."), p("keep-receipt", "has kept", "have kept", "the travel receipt", "with the ticket.")]),

  // Commerce
  f("com-customer", "commerce", "customer", "customers", ["waiting at the service desk", "shopping during the weekend sale"], [p("return-product", "has returned", "have returned", "the damaged product", "with the receipt."), p("compare-price", "has compared", "have compared", "the listed prices", "before buying."), p("request-refund", "has requested", "have requested", "a full refund", "for the faulty item."), p("collect-order", "has collected", "have collected", "the online order", "from the pickup counter.")]),
  f("com-seller", "commerce", "seller", "sellers", ["working at the market stall", "offering seasonal goods"], [p("display-price", "has displayed", "have displayed", "the price list", "near the counter."), p("pack-order", "has packed", "have packed", "the customer's order", "for delivery."), p("check-stock", "is checking", "are checking", "the remaining stock", "before closing."), p("issue-bill", "has issued", "have issued", "a printed bill", "for the purchase.")]),
  f("com-buyer", "commerce", "buyer", "buyers", ["looking for a replacement item", "visiting the wholesale market"], [p("inspect-goods", "has inspected", "have inspected", "the packaged goods", "before payment."), p("confirm-order", "has confirmed", "have confirmed", "the bulk order", "with the supplier."), p("check-quality", "is checking", "are checking", "the product quality", "before accepting delivery."), p("keep-invoice", "has kept", "have kept", "the purchase invoice", "for future reference.")]),
  f("com-cashier", "commerce", "cashier", "cashiers", ["working at the front counter", "handling the evening shift"], [p("count-cash", "has counted", "have counted", "the cash balance", "before closing."), p("scan-items", "is scanning", "are scanning", "the selected items", "at the billing counter."), p("print-receipt", "has printed", "have printed", "the payment receipt", "for the customer."), p("check-payment", "has checked", "have checked", "the digital payment", "before completing the sale.")]),
  f("com-vendor", "commerce", "vendor", "vendors", ["selling fresh produce", "working in the covered market"], [p("arrange-goods", "has arranged", "have arranged", "the goods", "on the display table."), p("update-rate", "has updated", "have updated", "the daily rate card", "before opening."), p("weigh-produce", "is weighing", "are weighing", "the fresh produce", "for the customer."), p("cover-stock", "has covered", "have covered", "the remaining stock", "before the rain.")]),
  f("com-retailer", "commerce", "retailer", "retailers", ["running a small outlet", "preparing for the holiday rush"], [p("order-stock", "has ordered", "have ordered", "additional stock", "from the distributor."), p("mark-prices", "has marked", "have marked", "the new prices", "on the shelves."), p("check-delivery", "is checking", "are checking", "the morning delivery", "against the invoice."), p("offer-discount", "has offered", "have offered", "a limited discount", "on selected items.")]),
  f("com-wholesaler", "commerce", "wholesaler", "wholesalers", ["supplying several small shops", "handling a large seasonal order"], [p("dispatch-goods", "has dispatched", "have dispatched", "the ordered goods", "to the retailers."), p("check-invoice", "has checked", "have checked", "the supplier invoice", "before payment."), p("update-stock", "is updating", "are updating", "the warehouse stock", "after the delivery."), p("confirm-rate", "has confirmed", "have confirmed", "the revised rate", "with the buyer.")]),
  f("com-shopper", "commerce", "shopper", "shoppers", ["using a digital payment card", "waiting in the shorter queue"], [p("pay-items", "has paid", "have paid", "for the selected items", "at the counter."), p("carry-bag", "is carrying", "are carrying", "a reusable shopping bag", "through the store."), p("check-offer", "has checked", "have checked", "the discount offer", "before payment."), p("keep-receipt", "has kept", "have kept", "the purchase receipt", "after leaving the store.")]),

  // Science
  f("sci-researcher", "science", "researcher", "researchers", ["working at the field station", "assigned to the observation team"], [p("record-readings", "has recorded", "have recorded", "the temperature readings", "at regular intervals."), p("collect-samples", "has collected", "have collected", "the soil samples", "from the test plots."), p("review-data", "is reviewing", "are reviewing", "the preliminary data", "before analysis."), p("write-note", "has written", "have written", "a field note", "in the research log.")]),
  f("sci-scientist", "science", "scientist", "scientists", ["working on the new experiment", "leading the laboratory study"], [p("test-sample", "has tested", "have tested", "the first sample", "under controlled conditions."), p("repeat-trial", "has repeated", "have repeated", "the trial", "to confirm the result."), p("examine-pattern", "is examining", "are examining", "the unusual pattern", "in the data."), p("prepare-report", "has prepared", "have prepared", "the experiment report", "for review.")]),
  f("sci-technician", "science", "technician", "technicians", ["working in the chemistry laboratory", "assigned to the morning experiment"], [p("label-containers", "has labelled", "have labelled", "the sample containers", "before the experiment."), p("calibrate-device", "has calibrated", "have calibrated", "the measuring device", "before use."), p("clean-equipment", "is cleaning", "are cleaning", "the glass equipment", "after the test."), p("record-setting", "has recorded", "have recorded", "the instrument setting", "in the laboratory log.")]),
  f("sci-observer", "science", "observer", "observers", ["working near the observation point", "recording the morning session"], [p("enter-notes", "has entered", "have entered", "the field notes", "in the survey register."), p("count-birds", "has counted", "have counted", "the birds in the study area", "before noon."), p("mark-time", "is marking", "are marking", "the exact observation time", "on each entry."), p("check-weather", "has checked", "have checked", "the weather conditions", "before starting work.")]),
  f("sci-analyst", "science", "analyst", "analysts", ["working with the latest dataset", "reviewing the second trial"], [p("compare-results", "has compared", "have compared", "the two sets of results", "carefully."), p("identify-error", "has identified", "have identified", "a recording error", "in the raw data."), p("prepare-chart", "is preparing", "are preparing", "a summary chart", "for the report."), p("verify-total", "has verified", "have verified", "the final total", "against the source data.")]),
  f("sci-chemist", "science", "chemist", "chemists", ["working with the test solution", "handling the controlled reaction"], [p("measure-liquid", "has measured", "have measured", "the required liquid", "with a clean cylinder."), p("mix-solution", "has mixed", "have mixed", "the test solution", "in the correct ratio."), p("observe-change", "is observing", "are observing", "the colour change", "during the reaction."), p("store-sample", "has stored", "have stored", "the prepared sample", "in a sealed container.")]),
  f("sci-biologist", "science", "biologist", "biologists", ["studying the plant samples", "working in the field laboratory"], [p("examine-leaf", "has examined", "have examined", "the leaf tissue", "under the microscope."), p("record-growth", "has recorded", "have recorded", "the plant growth", "over four weeks."), p("collect-specimen", "is collecting", "are collecting", "a fresh specimen", "for the next test."), p("compare-species", "has compared", "have compared", "the two species", "using the same method.")]),
  f("sci-physicist", "science", "physicist", "physicists", ["testing the new apparatus", "working on the measurement trial"], [p("measure-force", "has measured", "have measured", "the applied force", "with the calibrated instrument."), p("repeat-measurement", "has repeated", "have repeated", "the measurement", "to reduce error."), p("check-reading", "is checking", "are checking", "the final reading", "against the expected value."), p("note-variation", "has noted", "have noted", "a small variation", "during the second trial.")]),

  // Sports
  f("sp-player", "sports", "player", "players", ["selected for the opening match", "returning after a short break"], [p("complete-warmup", "has completed", "have completed", "the warm-up drills", "before the match."), p("attend-practice", "is attending", "are attending", "the final practice session", "this morning."), p("check-kit", "has checked", "have checked", "the playing kit", "before entering the field."), p("review-plan", "has reviewed", "have reviewed", "the match plan", "with the coach.")]),
  f("sp-runner", "sports", "runner", "runners", ["training for the relay event", "returning after an injury break"], [p("finish-lap", "has completed", "have completed", "the final practice lap", "within the target time."), p("wear-bib", "is wearing", "are wearing", "the numbered bib", "during the trial."), p("record-time", "has recorded", "have recorded", "a faster time", "in the second run."), p("stretch-muscles", "is stretching", "are stretching", "the leg muscles", "before training.")]),
  f("sp-swimmer", "sports", "swimmer", "swimmers", ["training in the main pool", "preparing for the qualifying event"], [p("complete-laps", "has completed", "have completed", "ten practice laps", "before the session ended."), p("check-goggles", "has checked", "have checked", "the swimming goggles", "before entering the pool."), p("practise-turn", "is practising", "are practising", "the final turn", "with the coach."), p("record-time", "has recorded", "have recorded", "the lap time", "after the trial.")]),
  f("sp-coach", "sports", "coach", "coaches", ["working with the senior squad", "leading the morning practice"], [p("plan-session", "has planned", "have planned", "the training session", "for the whole squad."), p("review-video", "has reviewed", "have reviewed", "the match recording", "with the players."), p("explain-drill", "is explaining", "are explaining", "the new drill", "before practice."), p("check-fitness", "has checked", "have checked", "the fitness reports", "before selection.")]),
  f("sp-referee", "sports", "referee", "referees", ["officiating the final match", "assigned to the afternoon fixture"], [p("check-ground", "has checked", "have checked", "the playing area", "before the match."), p("inspect-ball", "has inspected", "have inspected", "the match ball", "before play began."), p("record-foul", "is recording", "are recording", "the reported foul", "in the match notes."), p("signal-start", "has signalled", "have signalled", "the start of play", "at the scheduled time.")]),
  f("sp-bowler", "sports", "bowler", "bowlers", ["training with the senior squad", "preparing for the next match"], [p("complete-spell", "has completed", "have completed", "the practice spell", "without a break."), p("mark-runup", "has marked", "have marked", "the run-up", "before practice."), p("test-grip", "is testing", "are testing", "a new grip", "during the net session."), p("review-action", "has reviewed", "have reviewed", "the bowling action", "with the coach.")]),
  f("sp-goalkeeper", "sports", "goalkeeper", "goalkeepers", ["training before the league match", "working with the defence unit"], [p("practise-save", "has practised", "have practised", "the low save", "several times."), p("check-gloves", "has checked", "have checked", "the goalkeeping gloves", "before training."), p("direct-defence", "is directing", "are directing", "the defensive line", "during the drill."), p("review-corners", "has reviewed", "have reviewed", "the corner routine", "with the coach.")]),
  f("sp-athlete", "sports", "athlete", "athletes", ["preparing for the qualifying round", "training under the new programme"], [p("complete-session", "has completed", "have completed", "the conditioning session", "before breakfast."), p("record-result", "has recorded", "have recorded", "a personal best", "in the practice trial."), p("follow-plan", "is following", "are following", "the revised training plan", "this week."), p("attend-check", "has attended", "have attended", "the fitness check", "before competition.")]),

  // Public service
  f("pub-resident", "public-service", "resident", "residents", ["living in the housing complex", "using the online complaint service"], [p("report-light", "has reported", "have reported", "the broken streetlight", "through the public helpline."), p("request-repair", "has requested", "have requested", "a drainage repair", "through the service portal."), p("collect-form", "has collected", "have collected", "the service form", "from the help desk."), p("check-status", "is checking", "are checking", "the complaint status", "online.")]),
  f("pub-citizen", "public-service", "citizen", "citizens", ["registered on the service portal", "visiting the public help centre"], [p("pay-bill", "has paid", "have paid", "the utility bill", "through the online service."), p("submit-request", "has submitted", "have submitted", "a service request", "before the closing date."), p("download-receipt", "has downloaded", "have downloaded", "the payment receipt", "for personal records."), p("update-detail", "has updated", "have updated", "the contact details", "on the portal.")]),
  f("pub-visitor", "public-service", "visitor", "visitors", ["waiting near the enquiry counter", "seeking information about the service"], [p("collect-form", "has collected", "have collected", "an application form", "from the help desk."), p("read-notice", "has read", "have read", "the public notice", "near the entrance."), p("ask-direction", "has asked", "have asked", "for directions", "at the enquiry desk."), p("take-token", "has taken", "have taken", "a service token", "from the machine.")]),
  f("pub-clerk", "public-service", "clerk", "clerks", ["working at the service counter", "handling the morning applications"], [p("check-form", "has checked", "have checked", "the submitted form", "for missing details."), p("issue-receipt", "has issued", "have issued", "an acknowledgement receipt", "to the applicant."), p("update-record", "is updating", "are updating", "the public record", "in the system."), p("arrange-files", "has arranged", "have arranged", "the completed files", "for review.")]),
  f("pub-inspector", "public-service", "inspector", "inspectors", ["conducting the routine field visit", "assigned to the service review"], [p("check-facility", "has checked", "have checked", "the public facility", "during the inspection."), p("record-defect", "has recorded", "have recorded", "the maintenance defect", "in the field report."), p("verify-notice", "is verifying", "are verifying", "the displayed notice", "against the official copy."), p("submit-report", "has submitted", "have submitted", "the inspection report", "before the deadline.")]),
  f("pub-volunteer", "public-service", "volunteer", "volunteers", ["helping at the information desk", "working during the public campaign"], [p("guide-visitor", "has guided", "have guided", "a visitor", "to the correct counter."), p("distribute-leaflet", "has distributed", "have distributed", "the information leaflets", "among the residents."), p("arrange-queue", "is arranging", "are arranging", "the waiting queue", "near the entrance."), p("record-name", "has recorded", "have recorded", "the participant names", "in the register.")]),
  f("pub-applicant", "public-service", "applicant", "applicants", ["applying for the public service", "waiting for document checking"], [p("submit-form", "has submitted", "have submitted", "the completed application", "with the required documents."), p("check-status", "has checked", "have checked", "the application status", "on the portal."), p("carry-copy", "is carrying", "are carrying", "a photocopy of the certificate", "for verification."), p("collect-receipt", "has collected", "have collected", "the acknowledgement slip", "from the counter.")]),
  f("pub-attendant", "public-service", "attendant", "attendants", ["working near the entrance", "assigned to the waiting area"], [p("open-counter", "has opened", "have opened", "the service counter", "at the scheduled time."), p("guide-queue", "is guiding", "are guiding", "the visitors", "towards the correct desk."), p("check-token", "has checked", "have checked", "the token number", "before allowing entry."), p("close-gate", "has closed", "have closed", "the side gate", "after office hours.")]),

  // Technology
  f("tech-user", "technology", "user", "users", ["using the mobile application", "responding to the security alert"], [p("change-password", "has changed", "have changed", "the account password", "after the security warning."), p("install-update", "has installed", "have installed", "the latest software update", "on the device."), p("backup-files", "is backing up", "are backing up", "the important files", "before the upgrade."), p("enable-lock", "has enabled", "have enabled", "the screen lock", "for better security.")]),
  f("tech-programmer", "technology", "programmer", "programmers", ["working on the test build", "reviewing the latest module"], [p("fix-error", "has fixed", "have fixed", "the reported error", "in the test version."), p("write-script", "has written", "have written", "a short test script", "for the new feature."), p("review-code", "is reviewing", "are reviewing", "the updated code", "before release."), p("run-test", "has run", "have run", "the full test suite", "after the change.")]),
  f("tech-technician", "technology", "technician", "technicians", ["working in the equipment room", "assigned to the network check"], [p("replace-cable", "has replaced", "have replaced", "the damaged cable", "behind the main panel."), p("test-device", "has tested", "have tested", "the faulty device", "after repair."), p("check-network", "is checking", "are checking", "the network connection", "on each terminal."), p("record-fault", "has recorded", "have recorded", "the equipment fault", "in the service log.")]),
  f("tech-operator", "technology", "operator", "operators", ["monitoring the control screen", "handling the night shift"], [p("restart-system", "has restarted", "have restarted", "the control system", "after the warning."), p("check-alert", "has checked", "have checked", "the active alert", "on the display."), p("monitor-load", "is monitoring", "are monitoring", "the system load", "during peak use."), p("record-event", "has recorded", "have recorded", "the unusual event", "in the operations log.")]),
  f("tech-computer", "technology", "computer", "computers", ["connected to the backup server", "installed in the training room"], [p("complete-backup", "has completed", "have completed", "the automatic backup", "without any warning."), p("install-patch", "has installed", "have installed", "the security patch", "during the restart."), p("display-message", "is displaying", "are displaying", "a system message", "on the screen."), p("store-copy", "has stored", "have stored", "a backup copy", "on the secure drive.")]),
  f("tech-device", "technology", "device", "devices", ["connected to the test network", "kept in the equipment room"], [p("require-update", "requires", "require", "a software update", "before normal use."), p("show-warning", "is showing", "are showing", "a battery warning", "on the main screen."), p("complete-test", "has completed", "have completed", "the self-test", "without an error."), p("save-setting", "has saved", "have saved", "the new setting", "after restart.")]),
  f("tech-router", "technology", "router", "routers", ["connected to the office network", "installed near the control room"], [p("handle-traffic", "is handling", "are handling", "the network traffic", "without interruption."), p("receive-update", "has received", "have received", "the latest firmware update", "from the server."), p("restart-auto", "has restarted", "have restarted", "automatically", "after the power check."), p("show-status", "is showing", "are showing", "a normal status light", "on the front panel.")]),
  f("tech-printer", "technology", "printer", "printers", ["connected to the shared network", "placed near the service desk"], [p("print-report", "has printed", "have printed", "the test report", "without a paper jam."), p("require-toner", "requires", "require", "a new toner cartridge", "before further use."), p("show-error", "is showing", "are showing", "an error message", "on the control panel."), p("complete-job", "has completed", "have completed", "the queued print job", "successfully.")]),

  // Environment
  f("env-tree", "environment", "tree", "trees", ["planted beside the water channel", "growing on the open slope"], [p("survive-dry", "has survived", "have survived", "the long dry spell", "without additional watering."), p("produce-shade", "is providing", "are providing", "dense shade", "along the walking path."), p("lose-leaves", "has lost", "have lost", "some leaves", "during the hot period."), p("show-growth", "has shown", "have shown", "steady growth", "since the last survey.")]),
  f("env-bird", "environment", "bird", "birds", ["tagged during the earlier survey", "seen near the wetland last year"], [p("return-nest", "has returned", "have returned", "to the nesting area", "after the winter season."), p("build-nest", "is building", "are building", "a nest", "near the water edge."), p("feed-young", "is feeding", "are feeding", "the young chicks", "throughout the morning."), p("cross-area", "has crossed", "have crossed", "the observation zone", "several times today.")]),
  f("env-gardener", "environment", "gardener", "gardeners", ["working in the plant nursery", "preparing the beds for summer"], [p("move-seedlings", "has moved", "have moved", "the young seedlings", "into the shaded area."), p("trim-hedge", "has trimmed", "have trimmed", "the boundary hedge", "before the rainy season."), p("water-plants", "is watering", "are watering", "the new plants", "early in the morning."), p("prepare-compost", "has prepared", "have prepared", "the compost mixture", "for the flower beds.")]),
  f("env-volunteer", "environment", "volunteer", "volunteers", ["joining the cleanup drive", "working near the public park"], [p("collect-litter", "has collected", "have collected", "the plastic litter", "from the walking trail."), p("plant-sapling", "has planted", "have planted", "a native sapling", "beside the path."), p("sort-waste", "is sorting", "are sorting", "the collected waste", "into separate bags."), p("record-count", "has recorded", "have recorded", "the number of filled bags", "after the cleanup.")]),
  f("env-ranger", "environment", "ranger", "rangers", ["patrolling the protected area", "working on the wildlife survey"], [p("inspect-trail", "has inspected", "have inspected", "the forest trail", "after the storm."), p("record-sighting", "has recorded", "have recorded", "a wildlife sighting", "in the patrol log."), p("check-fence", "is checking", "are checking", "the boundary fence", "for damage."), p("guide-team", "has guided", "have guided", "the survey team", "through the marked route.")]),
  f("env-sapling", "environment", "sapling", "saplings", ["planted during the rainy season", "growing near the boundary fence"], [p("survive-heat", "has survived", "have survived", "the first hot month", "with regular watering."), p("grow-leaves", "has produced", "have produced", "new leaves", "since planting."), p("need-support", "requires", "require", "a support stake", "during strong winds."), p("show-damage", "is showing", "are showing", "minor leaf damage", "after the storm.")]),
  f("env-plant", "environment", "plant", "plants", ["growing in the shaded plot", "included in the garden trial"], [p("need-water", "requires", "require", "regular watering", "during the summer."), p("produce-flower", "has produced", "have produced", "new flowers", "after the rain."), p("show-growth", "is showing", "are showing", "healthy growth", "in the new soil mix."), p("survive-cold", "has survived", "have survived", "the cold spell", "without visible damage.")]),
  f("env-observer", "environment", "observer", "observers", ["working near the wetland", "recording the morning survey"], [p("count-birds", "has counted", "have counted", "the water birds", "before noon."), p("note-level", "has noted", "have noted", "the water level", "at the marked point."), p("photograph-area", "is photographing", "are photographing", "the vegetation cover", "for comparison."), p("record-weather", "has recorded", "have recorded", "the weather conditions", "in the field sheet.")]),

  // Hospitality
  f("hos-guest", "hospitality", "guest", "guests", ["invited to the evening programme", "arriving before the scheduled time"], [p("wait-host", "is waiting", "are waiting", "in the reception area", "for the host to arrive."), p("collect-key", "has collected", "have collected", "the room key", "from reception."), p("request-towel", "has requested", "have requested", "an extra towel", "from housekeeping."), p("read-menu", "has read", "have read", "the dinner menu", "before ordering.")]),
  f("hos-tourist", "hospitality", "tourist", "tourists", ["joining the morning tour", "waiting near the main entrance"], [p("pick-map", "has picked up", "have picked up", "a route map", "from the information counter."), p("book-tour", "has booked", "have booked", "the guided tour", "for the afternoon."), p("check-time", "is checking", "are checking", "the departure time", "on the notice board."), p("carry-bottle", "is carrying", "are carrying", "a water bottle", "for the walking tour.")]),
  f("hos-cook", "hospitality", "cook", "cooks", ["working in the main kitchen", "handling the evening service"], [p("prepare-meal", "has prepared", "have prepared", "the evening meal", "before the guests arrived."), p("check-stock", "has checked", "have checked", "the kitchen stock", "before cooking."), p("cut-vegetables", "is cutting", "are cutting", "the fresh vegetables", "for the soup."), p("clean-worktop", "has cleaned", "have cleaned", "the work surface", "after preparation.")]),
  f("hos-waiter", "hospitality", "waiter", "waiters", ["serving the outdoor tables", "working during the dinner shift"], [p("take-order", "has taken", "have taken", "the table order", "without delay."), p("serve-drinks", "is serving", "are serving", "the drinks", "before the meal."), p("clear-table", "has cleared", "have cleared", "the empty plates", "from the table."), p("bring-bill", "has brought", "have brought", "the final bill", "to the guest.")]),
  f("hos-chef", "hospitality", "chef", "chefs", ["leading the evening kitchen team", "preparing the special menu"], [p("plan-menu", "has planned", "have planned", "the dinner menu", "for the event."), p("taste-soup", "has tasted", "have tasted", "the prepared soup", "before service."), p("check-dish", "is checking", "are checking", "the main dish", "before it leaves the kitchen."), p("brief-staff", "has briefed", "have briefed", "the kitchen staff", "before the evening rush.")]),
  f("hos-receptionist", "hospitality", "receptionist", "receptionists", ["working at the front desk", "handling the morning arrivals"], [p("confirm-booking", "has confirmed", "have confirmed", "the room booking", "with the guest."), p("issue-key", "has issued", "have issued", "the room key", "after check-in."), p("answer-call", "is answering", "are answering", "a guest enquiry", "over the phone."), p("update-register", "has updated", "have updated", "the arrival register", "before the next check-in.")]),
  f("hos-attendant", "hospitality", "attendant", "attendants", ["working on the guest floor", "assigned to the morning service"], [p("deliver-towel", "has delivered", "have delivered", "fresh towels", "to the room."), p("check-room", "has checked", "have checked", "the prepared room", "before the guest arrived."), p("carry-luggage", "is carrying", "are carrying", "the guest's luggage", "towards the lift."), p("report-fault", "has reported", "have reported", "the faulty light", "to maintenance.")]),
  f("hos-host", "hospitality", "host", "hosts", ["welcoming the evening guests", "organising the small reception"], [p("greet-guests", "has greeted", "have greeted", "the arriving guests", "at the entrance."), p("announce-programme", "has announced", "have announced", "the programme schedule", "before dinner."), p("guide-seating", "is guiding", "are guiding", "the guests to their seats", "before the event."), p("thank-staff", "has thanked", "have thanked", "the service staff", "after the programme.")]),

  // Healthcare
  f("hc-patient", "healthcare", "patient", "patients", ["recovering from the procedure", "referred by the duty doctor"], [p("need-followup", "needs", "need", "a follow-up examination", "after the treatment."), p("take-medicine", "is taking", "are taking", "the prescribed medicine", "at regular times."), p("bring-report", "has brought", "have brought", "the previous test report", "to the appointment."), p("wait-doctor", "is waiting", "are waiting", "outside the consultation room", "for the doctor.")]),
  f("hc-nurse", "healthcare", "nurse", "nurses", ["working in the recovery ward", "assigned to the morning shift"], [p("update-chart", "has updated", "have updated", "the patient chart", "before the next round."), p("check-temperature", "has checked", "have checked", "the patient's temperature", "twice this morning."), p("prepare-room", "is preparing", "are preparing", "the treatment room", "for the next patient."), p("record-dose", "has recorded", "have recorded", "the medicine dose", "in the chart.")]),
  f("hc-doctor", "healthcare", "doctor", "doctors", ["working in the outpatient clinic", "handling the follow-up cases"], [p("review-report", "has reviewed", "have reviewed", "the test report", "before prescribing treatment."), p("examine-patient", "has examined", "have examined", "the patient", "during the morning round."), p("write-note", "is writing", "are writing", "the clinical note", "after consultation."), p("order-test", "has ordered", "have ordered", "a routine test", "for further assessment.")]),
  f("hc-pharmacist", "healthcare", "pharmacist", "pharmacists", ["working at the medicine counter", "handling the afternoon shift"], [p("check-prescription", "has checked", "have checked", "the prescription", "before issuing medicine."), p("label-medicine", "has labelled", "have labelled", "the medicine packet", "with clear instructions."), p("explain-dose", "is explaining", "are explaining", "the dosage instructions", "to the patient."), p("update-stock", "has updated", "have updated", "the medicine stock", "after the delivery.")]),
  f("hc-therapist", "healthcare", "therapist", "therapists", ["working with the rehabilitation group", "handling the morning appointments"], [p("demonstrate-exercise", "has demonstrated", "have demonstrated", "the first exercise", "to the patient."), p("record-progress", "has recorded", "have recorded", "the patient's progress", "in the treatment notes."), p("adjust-plan", "is adjusting", "are adjusting", "the exercise plan", "for the next week."), p("check-movement", "has checked", "have checked", "the joint movement", "during the session.")]),
  f("hc-technician", "healthcare", "technician", "technicians", ["working in the diagnostic unit", "assigned to the morning tests"], [p("prepare-machine", "has prepared", "have prepared", "the diagnostic machine", "for the next test."), p("label-sample", "has labelled", "have labelled", "the patient sample", "before processing."), p("check-image", "is checking", "are checking", "the scan image", "for clarity."), p("record-test", "has recorded", "have recorded", "the test details", "in the laboratory system.")]),
  f("hc-surgeon", "healthcare", "surgeon", "surgeons", ["preparing for the scheduled procedure", "leading the operating team"], [p("review-scan", "has reviewed", "have reviewed", "the latest scan", "before the procedure."), p("check-plan", "has checked", "have checked", "the surgical plan", "with the team."), p("brief-team", "is briefing", "are briefing", "the operating team", "before entering the theatre."), p("write-summary", "has written", "have written", "the procedure summary", "after completion.")]),
  f("hc-caregiver", "healthcare", "caregiver", "caregivers", ["assisting an elderly patient", "working during the daytime shift"], [p("prepare-meal", "has prepared", "have prepared", "a light meal", "for the patient."), p("record-time", "has recorded", "have recorded", "the medicine time", "on the daily sheet."), p("help-walk", "is helping", "are helping", "the patient to walk", "along the corridor."), p("check-water", "has checked", "have checked", "the drinking water", "beside the bed.")]),

  // Agriculture
  f("ag-farmer", "agriculture", "farmer", "farmers", ["working on a small holding", "facing a shortage of water"], [p("adopt-irrigation", "has adopted", "have adopted", "the new irrigation method", "for the summer crop."), p("check-soil", "has checked", "have checked", "the soil moisture", "before watering."), p("sow-seed", "is sowing", "are sowing", "the certified seed", "in the prepared field."), p("store-grain", "has stored", "have stored", "the harvested grain", "in a dry shed.")]),
  f("ag-grower", "agriculture", "grower", "growers", ["preparing for the next sowing season", "using the shared storage shed"], [p("store-seed", "has stored", "have stored", "the seed bags", "in a dry room."), p("inspect-crop", "has inspected", "have inspected", "the young crop", "after the rain."), p("apply-compost", "is applying", "are applying", "organic compost", "to the vegetable beds."), p("check-pump", "has checked", "have checked", "the irrigation pump", "before use.")]),
  f("ag-labourer", "agriculture", "labourer", "labourers", ["working in the storage yard", "helping with the grain harvest"], [p("load-grain", "has loaded", "have loaded", "the harvested grain", "onto the waiting trailer."), p("stack-bags", "has stacked", "have stacked", "the grain bags", "inside the store."), p("clean-yard", "is cleaning", "are cleaning", "the storage yard", "after loading."), p("cover-bags", "has covered", "have covered", "the seed bags", "before the rain.")]),
  f("ag-cultivator", "agriculture", "cultivator", "cultivators", ["preparing the field for sowing", "working with the seasonal crop"], [p("level-field", "has levelled", "have levelled", "the field", "before irrigation."), p("select-seed", "has selected", "have selected", "the seed variety", "for the next crop."), p("inspect-channel", "is inspecting", "are inspecting", "the irrigation channel", "for blockages."), p("repair-fence", "has repaired", "have repaired", "the field fence", "before grazing season.")]),
  f("ag-tractor", "agriculture", "tractor", "tractors", ["used during the sowing season", "kept in the machinery shed"], [p("need-service", "requires", "require", "regular servicing", "before heavy field work."), p("pull-trailer", "is pulling", "are pulling", "a loaded trailer", "towards the storage yard."), p("show-leak", "is showing", "are showing", "a minor oil leak", "near the engine."), p("complete-hours", "has completed", "have completed", "many working hours", "since the last service.")]),
  f("ag-pump", "agriculture", "pump", "pumps", ["installed beside the irrigation channel", "used for the summer crop"], [p("supply-water", "is supplying", "are supplying", "water to the field", "through the main pipe."), p("need-repair", "requires", "require", "a small repair", "before continuous use."), p("show-pressure", "is showing", "are showing", "low pressure", "at the outlet."), p("complete-run", "has completed", "have completed", "the morning run", "without interruption.")]),
  f("ag-sprayer", "agriculture", "sprayer", "sprayers", ["used in the vegetable field", "kept near the equipment shed"], [p("need-cleaning", "requires", "require", "thorough cleaning", "after each use."), p("show-blockage", "is showing", "are showing", "a nozzle blockage", "during operation."), p("complete-test", "has completed", "have completed", "the pressure test", "successfully."), p("carry-solution", "is carrying", "are carrying", "the prepared solution", "to the field.")]),
  f("ag-seedling", "agriculture", "seedling", "seedlings", ["raised in the nursery bed", "planted after the first rain"], [p("need-water", "requires", "require", "regular watering", "during the first week."), p("show-growth", "is showing", "are showing", "healthy growth", "after transplanting."), p("survive-rain", "has survived", "have survived", "the heavy rain", "without major damage."), p("produce-leaf", "has produced", "have produced", "new leaves", "within two weeks.")]),

  // Media
  f("med-reader", "media", "reader", "readers", ["waiting in the reading room", "interested in the science section"], [p("request-issue", "has requested", "have requested", "a copy of the latest issue", "from the reading desk."), p("read-editorial", "has read", "have read", "the main editorial", "before lunch."), p("mark-article", "is marking", "are marking", "an interesting article", "for later reference."), p("return-magazine", "has returned", "have returned", "the magazine", "to the reading desk.")]),
  f("med-viewer", "media", "viewer", "viewers", ["following the science series", "watching the weekend programme"], [p("watch-documentary", "has watched", "have watched", "the documentary", "on the education channel."), p("record-programme", "has recorded", "have recorded", "the evening programme", "for later viewing."), p("check-schedule", "is checking", "are checking", "the broadcast schedule", "before the programme."), p("share-feedback", "has shared", "have shared", "the programme feedback", "through the website.")]),
  f("med-journalist", "media", "journalist", "journalists", ["covering the sports event", "working for the evening edition"], [p("file-report", "has filed", "have filed", "the match report", "before the evening deadline."), p("interview-player", "has interviewed", "have interviewed", "the winning player", "after the match."), p("check-facts", "is checking", "are checking", "the reported facts", "before publication."), p("write-caption", "has written", "have written", "the photo caption", "for the final page.")]),
  f("med-reporter", "media", "reporter", "reporters", ["covering the public event", "working on the morning bulletin"], [p("record-interview", "has recorded", "have recorded", "a short interview", "at the venue."), p("send-update", "has sent", "have sent", "the latest update", "to the news desk."), p("check-location", "is checking", "are checking", "the event details", "before going live."), p("prepare-note", "has prepared", "have prepared", "a brief news note", "for the bulletin.")]),
  f("med-editor", "media", "editor", "editors", ["working on the weekend edition", "reviewing the final page"], [p("check-copy", "has checked", "have checked", "the article copy", "for factual errors."), p("approve-headline", "has approved", "have approved", "the final headline", "for publication."), p("review-layout", "is reviewing", "are reviewing", "the page layout", "before printing."), p("shorten-report", "has shortened", "have shortened", "the long report", "to fit the page.")]),
  f("med-photographer", "media", "photographer", "photographers", ["covering the outdoor event", "working near the main stage"], [p("capture-image", "has captured", "have captured", "the closing moment", "from the front row."), p("check-camera", "has checked", "have checked", "the camera settings", "before the event."), p("select-photo", "is selecting", "are selecting", "the best photograph", "for publication."), p("send-images", "has sent", "have sent", "the selected images", "to the news desk.")]),
  f("med-subscriber", "media", "subscriber", "subscribers", ["using the digital edition", "renewing the annual plan"], [p("renew-plan", "has renewed", "have renewed", "the subscription", "for another year."), p("download-issue", "has downloaded", "have downloaded", "the latest issue", "to the tablet."), p("update-email", "is updating", "are updating", "the contact email", "in the account settings."), p("save-article", "has saved", "have saved", "an article", "for offline reading.")]),
  f("med-presenter", "media", "presenter", "presenters", ["hosting the evening programme", "preparing for the live segment"], [p("read-script", "has read", "have read", "the programme script", "before the broadcast."), p("introduce-guest", "has introduced", "have introduced", "the guest speaker", "at the start of the segment."), p("check-timing", "is checking", "are checking", "the remaining time", "before the final break."), p("close-show", "has closed", "have closed", "the programme", "with a short summary.")]),

  // Household
  f("home-tenant", "household", "tenant", "tenants", ["living on the upper floor", "using the shared complaint register"], [p("report-tap", "has reported", "have reported", "the leaking tap", "to the maintenance desk."), p("check-meter", "has checked", "have checked", "the electricity meter", "before paying the bill."), p("clean-balcony", "is cleaning", "are cleaning", "the balcony", "before the guests arrive."), p("replace-bulb", "has replaced", "have replaced", "the faulty bulb", "in the hallway.")]),
  f("home-owner", "household", "homeowner", "homeowners", ["preparing the house for winter", "checking the monthly expenses"], [p("repair-door", "has repaired", "have repaired", "the loose door handle", "before it broke completely."), p("paint-wall", "has painted", "have painted", "the front wall", "with a lighter shade."), p("inspect-roof", "is inspecting", "are inspecting", "the roof", "after the heavy rain."), p("service-heater", "has serviced", "have serviced", "the water heater", "before winter.")]),
  f("home-cleaner", "household", "cleaner", "cleaners", ["working in the common area", "handling the morning cleaning round"], [p("mop-floor", "has mopped", "have mopped", "the corridor floor", "before opening time."), p("empty-bin", "has emptied", "have emptied", "the waste bin", "near the entrance."), p("clean-window", "is cleaning", "are cleaning", "the front windows", "with fresh water."), p("store-tools", "has stored", "have stored", "the cleaning tools", "in the utility room.")]),
  f("home-appliance", "household", "appliance", "appliances", ["used in the kitchen", "connected to the main power line"], [p("need-service", "requires", "require", "regular servicing", "for safe operation."), p("show-warning", "is showing", "are showing", "a warning light", "during use."), p("consume-power", "is consuming", "are consuming", "less electricity", "after the repair."), p("complete-cycle", "has completed", "have completed", "the full operating cycle", "without interruption.")]),
  f("home-fan", "household", "fan", "fans", ["installed in the front room", "used throughout the summer"], [p("make-noise", "is making", "are making", "a slight noise", "at high speed."), p("need-cleaning", "requires", "require", "thorough cleaning", "before summer."), p("run-smooth", "is running", "are running", "smoothly", "after servicing."), p("collect-dust", "has collected", "have collected", "a layer of dust", "on the blades.")]),
  f("home-heater", "household", "heater", "heaters", ["installed near the bathroom", "used during cold mornings"], [p("need-repair", "requires", "require", "a small repair", "before winter use."), p("heat-water", "is heating", "are heating", "the water", "more quickly after servicing."), p("show-leak", "is showing", "are showing", "a minor leak", "near the outlet."), p("complete-test", "has completed", "have completed", "the safety test", "without a fault.")]),
  f("home-lamp", "household", "lamp", "lamps", ["placed beside the reading chair", "fitted with an energy-saving bulb"], [p("provide-light", "is providing", "are providing", "enough light", "for reading."), p("need-bulb", "requires", "require", "a replacement bulb", "after long use."), p("show-flicker", "is showing", "are showing", "a slight flicker", "when switched on."), p("use-less-power", "is using", "are using", "less electricity", "than the older model.")]),
  f("home-window", "household", "window", "windows", ["facing the main street", "installed in the front room"], [p("need-repair", "requires", "require", "a small frame repair", "before the rainy season."), p("let-light", "is allowing", "are allowing", "more natural light", "into the room."), p("show-crack", "is showing", "are showing", "a small crack", "near the lower corner."), p("close-tight", "is closing", "are closing", "properly", "after the hinge adjustment.")]),

  // Infrastructure
  f("inf-engineer", "infrastructure", "engineer", "engineers", ["working on the repair project", "assigned to the safety inspection"], [p("inspect-bridge", "has inspected", "have inspected", "the bridge supports", "before reopening the lane."), p("review-plan", "has reviewed", "have reviewed", "the repair plan", "with the site team."), p("check-level", "is checking", "are checking", "the road level", "against the design."), p("record-defect", "has recorded", "have recorded", "a structural defect", "in the site report.")]),
  f("inf-worker", "infrastructure", "worker", "workers", ["repairing the roadside drain", "working on the night shift"], [p("clear-drain", "has cleared", "have cleared", "the blocked drain", "before the rain."), p("place-barrier", "has placed", "have placed", "the safety barrier", "around the work area."), p("mix-concrete", "is mixing", "are mixing", "the repair concrete", "near the damaged section."), p("carry-tools", "is carrying", "are carrying", "the hand tools", "to the next work point.")]),
  f("inf-inspector", "infrastructure", "inspector", "inspectors", ["conducting the routine bridge check", "assigned to the road safety survey"], [p("check-surface", "has checked", "have checked", "the road surface", "for fresh damage."), p("measure-crack", "has measured", "have measured", "the visible crack", "in the concrete wall."), p("inspect-light", "is inspecting", "are inspecting", "the roadside lights", "after sunset."), p("submit-note", "has submitted", "have submitted", "the inspection note", "to the project office.")]),
  f("inf-bridge", "infrastructure", "bridge", "bridges", ["carrying heavy daily traffic", "located on the main route"], [p("need-repair", "requires", "require", "regular maintenance", "during the dry season."), p("show-crack", "is showing", "are showing", "a minor surface crack", "near one support."), p("carry-traffic", "is carrying", "are carrying", "normal traffic", "after the inspection."), p("complete-test", "has completed", "have completed", "the load test", "successfully.")]),
  f("inf-road", "infrastructure", "road", "roads", ["linking the two service areas", "carrying heavy morning traffic"], [p("need-resurface", "requires", "require", "resurfacing", "along the damaged stretch."), p("show-pothole", "is showing", "are showing", "several potholes", "after the rainy season."), p("remain-open", "is remaining", "are remaining", "open to light traffic", "during the repair work."), p("receive-marking", "has received", "have received", "fresh lane markings", "after resurfacing.")]),
  f("inf-pipeline", "infrastructure", "pipeline", "pipelines", ["running beneath the service road", "supplying the new housing area"], [p("need-check", "requires", "require", "a pressure check", "before full operation."), p("show-leak", "is showing", "are showing", "a small leak", "near the joint."), p("carry-water", "is carrying", "are carrying", "water", "at normal pressure."), p("complete-flush", "has completed", "have completed", "the cleaning flush", "before commissioning.")]),
  f("inf-streetlight", "infrastructure", "streetlight", "streetlights", ["installed along the service road", "connected to the new power line"], [p("need-bulb", "requires", "require", "a replacement lamp", "after repeated failure."), p("switch-on", "has switched on", "have switched on", "automatically", "after sunset."), p("show-fault", "is showing", "are showing", "an electrical fault", "in the control unit."), p("provide-light", "is providing", "are providing", "adequate light", "along the footpath.")]),
  f("inf-lift", "infrastructure", "lift", "lifts", ["installed in the public building", "used throughout the working day"], [p("need-service", "requires", "require", "scheduled servicing", "every few months."), p("show-warning", "is showing", "are showing", "a door warning", "on the display."), p("complete-test", "has completed", "have completed", "the safety test", "without an error."), p("operate-normal", "is operating", "are operating", "normally", "after the repair.")]),

  // Banking
  f("bank-customer", "banking", "customer", "customers", ["waiting at the service counter", "using the mobile banking service"], [p("deposit-cash", "has deposited", "have deposited", "the cash amount", "at the counter."), p("update-phone", "has updated", "have updated", "the registered phone number", "in the account."), p("check-balance", "is checking", "are checking", "the account balance", "on the mobile application."), p("request-card", "has requested", "have requested", "a replacement card", "after losing the old one.")]),
  f("bank-depositor", "banking", "depositor", "depositors", ["holding a fixed-term account", "visiting the branch for renewal"], [p("renew-deposit", "has renewed", "have renewed", "the fixed deposit", "for another term."), p("check-rate", "has checked", "have checked", "the current interest rate", "before renewal."), p("submit-form", "has submitted", "have submitted", "the renewal form", "at the counter."), p("collect-receipt", "has collected", "have collected", "the deposit receipt", "after the transaction.")]),
  f("bank-borrower", "banking", "borrower", "borrowers", ["repaying the monthly instalment", "reviewing the loan statement"], [p("pay-instalment", "has paid", "have paid", "the monthly instalment", "before the due date."), p("check-statement", "has checked", "have checked", "the loan statement", "for the remaining balance."), p("submit-document", "is submitting", "are submitting", "an income document", "for account review."), p("request-schedule", "has requested", "have requested", "a repayment schedule", "from the loan desk.")]),
  f("bank-teller", "banking", "teller", "tellers", ["working at the cash counter", "handling the morning transactions"], [p("count-notes", "has counted", "have counted", "the cash notes", "before accepting the deposit."), p("verify-slip", "has verified", "have verified", "the deposit slip", "against the account number."), p("process-withdrawal", "is processing", "are processing", "a cash withdrawal", "for the customer."), p("balance-drawer", "has balanced", "have balanced", "the cash drawer", "at the end of the shift.")]),
  f("bank-account-holder", "banking", "account holder", "account holders", ["using online banking regularly", "reviewing the monthly statement"], [p("change-pin", "has changed", "have changed", "the card PIN", "after the security notice."), p("download-statement", "has downloaded", "have downloaded", "the monthly statement", "for personal records."), p("set-alert", "is setting", "are setting", "a transaction alert", "on the account."), p("verify-entry", "has verified", "have verified", "the latest account entry", "against the receipt.")]),
  f("bank-clerk", "banking", "clerk", "clerks", ["working at the account desk", "handling the new account forms"], [p("check-form", "has checked", "have checked", "the account-opening form", "for missing details."), p("scan-document", "has scanned", "have scanned", "the identity document", "into the system."), p("update-record", "is updating", "are updating", "the customer record", "after verification."), p("issue-copy", "has issued", "have issued", "an acknowledgement copy", "to the customer.")]),
  f("bank-auditor", "banking", "auditor", "auditors", ["reviewing the quarterly accounts", "checking the cash records"], [p("verify-entry", "has verified", "have verified", "the ledger entry", "against the supporting document."), p("identify-gap", "has identified", "have identified", "a missing record", "during the audit."), p("review-total", "is reviewing", "are reviewing", "the daily totals", "for unusual differences."), p("prepare-note", "has prepared", "have prepared", "the audit note", "for the final report.")]),
  f("bank-manager", "banking", "manager", "managers", ["handling the branch review", "meeting the service team"], [p("approve-request", "has approved", "have approved", "the customer request", "after verification."), p("review-target", "has reviewed", "have reviewed", "the monthly service target", "with the staff."), p("check-report", "is checking", "are checking", "the daily branch report", "before closing."), p("schedule-meeting", "has scheduled", "have scheduled", "a staff meeting", "for the next morning.")]),

  // Manufacturing
  f("mfg-worker", "manufacturing", "worker", "workers", ["working on the assembly line", "handling the morning shift"], [p("fit-part", "has fitted", "have fitted", "the metal part", "into the main assembly."), p("check-piece", "has checked", "have checked", "the finished piece", "for visible defects."), p("pack-item", "is packing", "are packing", "the completed item", "for dispatch."), p("record-count", "has recorded", "have recorded", "the production count", "at the end of the shift.")]),
  f("mfg-operator", "manufacturing", "operator", "operators", ["running the cutting machine", "working during the second shift"], [p("start-machine", "has started", "have started", "the production machine", "after the safety check."), p("adjust-speed", "has adjusted", "have adjusted", "the machine speed", "for the new material."), p("monitor-panel", "is monitoring", "are monitoring", "the control panel", "during operation."), p("record-stop", "has recorded", "have recorded", "the short stoppage", "in the shift log.")]),
  f("mfg-technician", "manufacturing", "technician", "technicians", ["working in the maintenance section", "assigned to the repair call"], [p("replace-bearing", "has replaced", "have replaced", "the worn bearing", "in the drive unit."), p("test-machine", "has tested", "have tested", "the repaired machine", "before production resumed."), p("check-sensor", "is checking", "are checking", "the safety sensor", "for correct response."), p("record-repair", "has recorded", "have recorded", "the maintenance work", "in the service log.")]),
  f("mfg-machine", "manufacturing", "machine", "machines", ["installed on the production line", "used during both shifts"], [p("need-service", "requires", "require", "scheduled servicing", "after long operation."), p("produce-parts", "is producing", "are producing", "the metal parts", "at the normal rate."), p("show-warning", "is showing", "are showing", "a temperature warning", "on the control panel."), p("complete-cycle", "has completed", "have completed", "the test cycle", "without a fault.")]),
  f("mfg-supervisor", "manufacturing", "supervisor", "supervisors", ["overseeing the packaging line", "handling the evening shift"], [p("check-output", "has checked", "have checked", "the production output", "against the shift target."), p("brief-workers", "has briefed", "have briefed", "the line workers", "before production began."), p("inspect-area", "is inspecting", "are inspecting", "the work area", "for safety issues."), p("approve-record", "has approved", "have approved", "the shift record", "after review.")]),
  f("mfg-assembler", "manufacturing", "assembler", "assemblers", ["working on the final assembly stage", "handling the small components"], [p("fit-cover", "has fitted", "have fitted", "the outer cover", "onto the unit."), p("tighten-bolt", "has tightened", "have tightened", "the fixing bolts", "to the required level."), p("check-alignment", "is checking", "are checking", "the component alignment", "before closing the unit."), p("place-label", "has placed", "have placed", "the product label", "on the finished unit.")]),
  f("mfg-inspector", "manufacturing", "inspector", "inspectors", ["checking the final products", "assigned to the quality station"], [p("inspect-surface", "has inspected", "have inspected", "the product surface", "for scratches."), p("measure-part", "has measured", "have measured", "the critical dimension", "with a gauge."), p("check-label", "is checking", "are checking", "the safety label", "before packing."), p("record-defect", "has recorded", "have recorded", "the identified defect", "in the quality report.")]),
  f("mfg-packer", "manufacturing", "packer", "packers", ["working near the dispatch area", "handling the final packing stage"], [p("seal-box", "has sealed", "have sealed", "the product box", "with packing tape."), p("check-label", "has checked", "have checked", "the shipping label", "before dispatch."), p("place-manual", "is placing", "are placing", "the instruction manual", "inside each box."), p("stack-carton", "has stacked", "have stacked", "the packed carton", "on the dispatch pallet.")]),

  // Energy
  f("en-meter", "energy", "meter", "meters", ["installed outside the building", "connected to the new supply line"], [p("record-use", "has recorded", "have recorded", "the monthly consumption", "without an error."), p("show-reading", "is showing", "are showing", "a normal reading", "on the digital display."), p("need-check", "requires", "require", "a routine accuracy check", "this year."), p("store-data", "has stored", "have stored", "the latest reading", "in memory.")]),
  f("en-turbine", "energy", "turbine", "turbines", ["operating at the power station", "running after scheduled maintenance"], [p("generate-power", "is generating", "are generating", "electricity", "at the expected output."), p("need-inspection", "requires", "require", "a blade inspection", "after extended operation."), p("show-vibration", "is showing", "are showing", "minor vibration", "at high speed."), p("complete-test", "has completed", "have completed", "the startup test", "successfully.")]),
  f("en-technician", "energy", "technician", "technicians", ["working near the control panel", "assigned to the maintenance team"], [p("check-cable", "has checked", "have checked", "the power cable", "for visible damage."), p("test-meter", "has tested", "have tested", "the digital meter", "against a reference unit."), p("inspect-panel", "is inspecting", "are inspecting", "the switch panel", "during the shutdown."), p("record-reading", "has recorded", "have recorded", "the test reading", "in the maintenance log.")]),
  f("en-engineer", "energy", "engineer", "engineers", ["reviewing the power system", "working on the efficiency study"], [p("analyse-load", "has analysed", "have analysed", "the daily load pattern", "for the past week."), p("review-plan", "has reviewed", "have reviewed", "the maintenance plan", "with the technical team."), p("check-output", "is checking", "are checking", "the unit output", "against the target."), p("prepare-report", "has prepared", "have prepared", "the efficiency report", "for management.")]),
  f("en-consumer", "energy", "consumer", "consumers", ["using the online billing service", "monitoring household consumption"], [p("pay-bill", "has paid", "have paid", "the electricity bill", "before the due date."), p("check-usage", "has checked", "have checked", "the monthly energy use", "on the portal."), p("report-outage", "is reporting", "are reporting", "a power outage", "through the helpline."), p("download-receipt", "has downloaded", "have downloaded", "the payment receipt", "for personal records.")]),
  f("en-panel", "energy", "solar panel", "solar panels", ["installed on the building roof", "cleaned before the summer season"], [p("generate-power", "is generating", "are generating", "electricity", "during daylight hours."), p("need-cleaning", "requires", "require", "regular cleaning", "for better output."), p("show-damage", "is showing", "are showing", "a small surface crack", "near one corner."), p("complete-test", "has completed", "have completed", "the output test", "within the expected range.")]),
  f("en-battery", "energy", "battery", "batteries", ["used in the backup system", "stored in the equipment room"], [p("need-charge", "requires", "require", "a full charge", "before the test."), p("hold-charge", "is holding", "are holding", "the charge", "for the expected duration."), p("show-warning", "is showing", "are showing", "a low-voltage warning", "during startup."), p("complete-cycle", "has completed", "have completed", "the discharge cycle", "without overheating.")]),
  f("en-transformer", "energy", "transformer", "transformers", ["installed near the distribution line", "serving the new housing block"], [p("need-service", "requires", "require", "periodic inspection", "for safe operation."), p("carry-load", "is carrying", "are carrying", "the normal electrical load", "without overheating."), p("show-noise", "is producing", "are producing", "a slight humming sound", "during operation."), p("complete-test", "has completed", "have completed", "the insulation test", "successfully.")]),

  // Postal
  f("post-parcel", "postal", "parcel", "parcels", ["booked through the counter service", "marked for standard delivery"], [p("reach-centre", "has reached", "have reached", "the sorting centre", "before the evening dispatch."), p("receive-label", "has received", "have received", "a tracking label", "at the booking counter."), p("show-status", "is showing", "are showing", "an in-transit status", "on the tracking page."), p("need-repack", "requires", "require", "secure repacking", "before onward dispatch.")]),
  f("post-letter", "postal", "letter", "letters", ["placed in the morning collection box", "addressed in clear handwriting"], [p("reach-office", "has reached", "have reached", "the delivery office", "before noon."), p("carry-stamp", "is carrying", "are carrying", "the correct postage", "for standard delivery."), p("receive-mark", "has received", "have received", "the dispatch mark", "at the sorting desk."), p("need-address", "requires", "require", "a clearer address", "before delivery.")]),
  f("post-courier", "postal", "courier", "couriers", ["handling the morning deliveries", "working on the business route"], [p("deliver-packet", "has delivered", "have delivered", "the document packet", "to the recipient."), p("collect-signature", "has collected", "have collected", "the recipient's signature", "after delivery."), p("check-route", "is checking", "are checking", "the delivery route", "before leaving the depot."), p("update-status", "has updated", "have updated", "the delivery status", "on the handheld device.")]),
  f("post-sender", "postal", "sender", "senders", ["booking an important document", "using the tracked delivery service"], [p("write-address", "has written", "have written", "the full address", "clearly on the envelope."), p("keep-receipt", "has kept", "have kept", "the booking receipt", "for tracking."), p("check-number", "is checking", "are checking", "the tracking number", "on the receipt."), p("seal-packet", "has sealed", "have sealed", "the document packet", "before booking.")]),
  f("post-recipient", "postal", "recipient", "recipients", ["waiting for a tracked parcel", "working during the daytime delivery window"], [p("receive-message", "has received", "have received", "the delivery message", "on the phone."), p("check-status", "has checked", "have checked", "the parcel status", "on the tracking page."), p("show-id", "is showing", "are showing", "a valid identity card", "to the delivery worker."), p("sign-receipt", "has signed", "have signed", "the delivery receipt", "after receiving the packet.")]),
  f("post-worker", "postal", "postal worker", "postal workers", ["working at the sorting desk", "handling the afternoon dispatch"], [p("sort-letters", "has sorted", "have sorted", "the outgoing letters", "by route."), p("scan-parcel", "has scanned", "have scanned", "the tracked parcel", "before dispatch."), p("tie-bag", "is tying", "are tying", "the mail bag", "for transport."), p("record-count", "has recorded", "have recorded", "the item count", "on the dispatch sheet.")]),
  f("post-clerk", "postal", "clerk", "clerks", ["working at the booking counter", "handling the morning queue"], [p("weigh-parcel", "has weighed", "have weighed", "the parcel", "before calculating postage."), p("issue-receipt", "has issued", "have issued", "the booking receipt", "to the sender."), p("check-address", "is checking", "are checking", "the written address", "before acceptance."), p("print-label", "has printed", "have printed", "the tracking label", "for the packet.")]),
  f("post-agent", "postal", "delivery agent", "delivery agents", ["carrying the afternoon mail", "working on the residential route"], [p("deliver-letter", "has delivered", "have delivered", "the registered letter", "to the named recipient."), p("scan-item", "has scanned", "have scanned", "the delivery item", "before handing it over."), p("check-address", "is checking", "are checking", "the house address", "against the label."), p("mark-attempt", "has marked", "have marked", "a delivery attempt", "in the handheld system.")]),

  // Culture
  f("cul-artist", "culture", "artist", "artists", ["preparing for the public exhibition", "working in the shared studio"], [p("finish-painting", "has finished", "have finished", "the main painting", "before the exhibition."), p("select-work", "has selected", "have selected", "three works", "for display."), p("arrange-frame", "is arranging", "are arranging", "the picture frame", "for hanging."), p("write-note", "has written", "have written", "a short description", "for the display card.")]),
  f("cul-musician", "culture", "musician", "musicians", ["rehearsing for the evening concert", "working with the chamber group"], [p("practise-piece", "has practised", "have practised", "the opening piece", "several times."), p("tune-instrument", "has tuned", "have tuned", "the instrument", "before rehearsal."), p("read-score", "is reading", "are reading", "the new score", "during practice."), p("check-timing", "has checked", "have checked", "the entry timing", "with the conductor.")]),
  f("cul-dancer", "culture", "dancer", "dancers", ["rehearsing for the stage performance", "learning the final sequence"], [p("practise-step", "has practised", "have practised", "the difficult step", "with the instructor."), p("complete-rehearsal", "has completed", "have completed", "the full rehearsal", "without a break."), p("check-costume", "is checking", "are checking", "the stage costume", "before the performance."), p("review-sequence", "has reviewed", "have reviewed", "the final sequence", "with the group.")]),
  f("cul-actor", "culture", "actor", "actors", ["preparing for the evening play", "rehearsing the final scene"], [p("learn-lines", "has learned", "have learned", "the dialogue", "for the opening scene."), p("attend-rehearsal", "has attended", "have attended", "the full rehearsal", "before the performance."), p("check-costume", "is checking", "are checking", "the stage costume", "in the dressing room."), p("review-cue", "has reviewed", "have reviewed", "the entrance cue", "with the director.")]),
  f("cul-visitor", "culture", "visitor", "visitors", ["attending the public exhibition", "walking through the gallery"], [p("read-label", "has read", "have read", "the exhibit label", "beside the display."), p("collect-guide", "has collected", "have collected", "a gallery guide", "at the entrance."), p("view-display", "is viewing", "are viewing", "the main exhibition", "in the central hall."), p("join-tour", "has joined", "have joined", "the guided tour", "through the museum.")]),
  f("cul-curator", "culture", "curator", "curators", ["preparing the new exhibition", "working in the main gallery"], [p("arrange-display", "has arranged", "have arranged", "the new display", "in chronological order."), p("check-label", "has checked", "have checked", "the exhibit labels", "for accuracy."), p("inspect-frame", "is inspecting", "are inspecting", "the picture frames", "before opening."), p("update-catalogue", "has updated", "have updated", "the exhibition catalogue", "with the new entries.")]),
  f("cul-performer", "culture", "performer", "performers", ["waiting behind the main stage", "taking part in the evening programme"], [p("complete-rehearsal", "has completed", "have completed", "the sound rehearsal", "before the audience arrived."), p("check-microphone", "has checked", "have checked", "the microphone", "before going on stage."), p("wait-cue", "is waiting", "are waiting", "for the stage cue", "behind the curtain."), p("review-programme", "has reviewed", "have reviewed", "the running order", "with the organiser.")]),
  f("cul-painter", "culture", "painter", "painters", ["working on the final canvas", "preparing work for the exhibition"], [p("mix-colour", "has mixed", "have mixed", "the required colour", "for the background."), p("finish-canvas", "has finished", "have finished", "the large canvas", "before the deadline."), p("clean-brush", "is cleaning", "are cleaning", "the paint brushes", "after work."), p("sign-work", "has signed", "have signed", "the completed painting", "in the lower corner.")]),

  // Emergency service
  f("em-firefighter", "emergency-service", "firefighter", "firefighters", ["assigned to the night crew", "taking part in the safety drill"], [p("check-hose", "has checked", "have checked", "the fire hose", "before the drill."), p("wear-gear", "is wearing", "are wearing", "the protective gear", "during the exercise."), p("inspect-mask", "has inspected", "have inspected", "the breathing mask", "before duty."), p("record-test", "has recorded", "have recorded", "the equipment test", "in the station log.")]),
  f("em-paramedic", "emergency-service", "paramedic", "paramedics", ["working on the emergency vehicle", "assigned to the daytime shift"], [p("check-kit", "has checked", "have checked", "the medical kit", "before leaving the station."), p("prepare-stretcher", "has prepared", "have prepared", "the stretcher", "for immediate use."), p("record-vitals", "is recording", "are recording", "the patient's vital signs", "during transport."), p("restock-supplies", "has restocked", "have restocked", "the emergency supplies", "after the call.")]),
  f("em-rescuer", "emergency-service", "rescuer", "rescuers", ["training with the response team", "working near the incident area"], [p("secure-rope", "has secured", "have secured", "the rescue rope", "before the descent."), p("check-helmet", "has checked", "have checked", "the safety helmet", "before entering the area."), p("carry-kit", "is carrying", "are carrying", "the rescue kit", "towards the site."), p("mark-route", "has marked", "have marked", "the safe route", "for the following team.")]),
  f("em-volunteer", "emergency-service", "volunteer", "volunteers", ["helping at the relief centre", "working during the supply distribution"], [p("pack-water", "has packed", "have packed", "the drinking-water bottles", "into relief boxes."), p("record-name", "has recorded", "have recorded", "the family names", "in the assistance register."), p("guide-people", "is guiding", "are guiding", "the waiting people", "towards the correct desk."), p("sort-blankets", "has sorted", "have sorted", "the donated blankets", "by size.")]),
  f("em-driver", "emergency-service", "driver", "drivers", ["assigned to the response vehicle", "working during the night shift"], [p("check-fuel", "has checked", "have checked", "the fuel level", "before the emergency call."), p("inspect-tyres", "has inspected", "have inspected", "the vehicle tyres", "before leaving the station."), p("follow-route", "is following", "are following", "the cleared route", "towards the incident site."), p("record-distance", "has recorded", "have recorded", "the trip distance", "after returning.")]),
  f("em-dispatcher", "emergency-service", "dispatcher", "dispatchers", ["working in the control room", "handling the busy evening shift"], [p("receive-call", "has received", "have received", "the emergency call", "through the control line."), p("confirm-location", "has confirmed", "have confirmed", "the reported location", "with the caller."), p("send-unit", "is sending", "are sending", "the nearest response unit", "to the incident."), p("record-time", "has recorded", "have recorded", "the call time", "in the control log.")]),
  f("em-responder", "emergency-service", "responder", "responders", ["working with the first response team", "carrying standard safety equipment"], [p("assess-area", "has assessed", "have assessed", "the immediate area", "for safety risks."), p("place-marker", "has placed", "have placed", "the warning marker", "near the hazard."), p("assist-person", "is assisting", "are assisting", "an injured person", "until medical help arrives."), p("report-status", "has reported", "have reported", "the current situation", "to the control room.")]),
  f("em-technician", "emergency-service", "technician", "technicians", ["maintaining the emergency equipment", "working in the station workshop"], [p("test-radio", "has tested", "have tested", "the portable radio", "before issue."), p("charge-battery", "has charged", "have charged", "the backup battery", "for the response unit."), p("inspect-light", "is inspecting", "are inspecting", "the emergency light", "for damage."), p("record-service", "has recorded", "have recorded", "the completed service", "in the equipment log.")]),
] as const;

export const BASE_SCENES_V4: readonly SemanticSceneV4[] = SEMANTIC_FAMILIES_V4.flatMap((family) =>
  family.predicates.map((predicate) => ({
    id: `${family.id}:${predicate.id}`,
    familyId: family.id,
    domain: family.domain,
    singular: family.singular,
    plural: family.plural,
    singularVerb: predicate.singularVerb,
    pluralVerb: predicate.pluralVerb,
    segment3: predicate.segment3,
    segment4: predicate.segment4,
    modifiers: family.modifiers,
  })),
);

export const SEMANTIC_DOMAINS_V4: readonly SemanticDomainV4[] = [
  "education", "transport", "commerce", "science", "sports", "public-service", "technology", "environment", "hospitality", "healthcare",
  "agriculture", "media", "household", "infrastructure", "banking", "manufacturing", "energy", "postal", "culture", "emergency-service",
] as const;

export const CP001_V4_BASE_SCENE_COUNT = BASE_SCENES_V4.length;
