export const COD_SOURCE_GAP_WORD_POOL = Object.freeze([
  "ANT", "AXE", "BEE", "BOX", "CAT", "CUP", "DOG", "FAN", "GEM", "HUT", "INK", "JAR", "KEY", "LOG", "MAP", "NET", "OWL", "PEN", "RUG", "SUN", "VAN", "WEB", "YAK", "ZIP",
  "ARCH", "BARK", "BEAM", "BIRD", "BLUE", "BOOK", "CAVE", "CLAY", "COIN", "DAWN", "DRUM", "FARM", "FISH", "GATE", "GOLD", "HILL", "LAMP", "LEAF", "MOON", "NEST", "PINE", "ROAD", "STAR", "WAVE",
  "APPLE", "BRICK", "CLOUD", "DREAM", "EAGLE", "FLAME", "GRAPE", "HORSE", "IVORY", "LEMON", "MANGO", "NIGHT", "OCEAN", "PEARL", "QUEEN", "RIVER", "STONE", "TIGER", "URBAN", "WHEAT", "YOUTH", "ZEBRA", "PLANT", "CHAIR",
  "ANCHOR", "BASKET", "CANDLE", "DESERT", "FOREST", "GARDEN", "HARBOR", "ISLAND", "JACKET", "KERNEL", "MAGNET", "NECTAR", "ORANGE", "PLANET", "SILVER", "TEMPLE", "VALLEY", "WINTER", "YELLOW", "BRIDGE", "CASTLE", "DRAGON", "FABRIC", "HUNTER",
  "AIRPORT", "BLANKET", "CRYSTAL", "DOLPHIN", "EMERALD", "FREEDOM", "GALLERY", "HIGHWAY", "JOURNEY", "KINGDOM", "LANTERN", "MACHINE", "ORCHARD", "PICTURE", "RAINBOW", "STATION", "THUNDER", "VILLAGE", "WEATHER", "BICYCLE", "CAPTAIN", "DIAMOND", "EVENING", "HARVEST",
  "ELEPHANT", "MOUNTAIN", "NOTEBOOK", "BUILDING", "HOSPITAL", "SUNSHINE", "COMPUTER", "FOOTBALL", "DAUGHTER", "FESTIVAL", "LANGUAGE", "MEDICINE", "PAINTING", "SANDWICH", "SHOULDER", "UMBRELLA", "VACATION", "WILDLIFE", "AIRPLANE", "CALENDAR", "DINOSAUR", "ENVELOPE", "FOUNTAIN", "HEADACHE",
  "ADVENTURE", "CHOCOLATE", "EDUCATION", "FIREPLACE", "HAPPINESS", "NEWSPAPER", "ORCHESTRA", "TELEPHONE", "VEGETABLE", "WATERFALL", "APARTMENT", "BREAKFAST", "CHEMISTRY", "DIRECTION", "EVERGREEN", "FURNITURE", "GEOGRAPHY", "HOUSEHOLD", "IMPORTANT", "JELLYFISH", "KNOWLEDGE", "LANDSCAPE", "MOONLIGHT", "PASSENGER",
  "STRAWBERRY", "BASKETBALL", "BLACKBOARD", "FRIENDSHIP", "PLAYGROUND", "RESTAURANT", "TOOTHBRUSH", "UNDERSTAND", "VOLLEYBALL", "WATERMELON", "EARTHQUAKE", "EVERYWHERE", "FLASHLIGHT", "HELICOPTER", "LIGHTHOUSE", "MOTORCYCLE", "POPULATION", "SPACECRAFT", "TELEVISION", "UNIVERSITY"
] as const);

export const COD_SOURCE_GAP_WORD_POOL_STATS = Object.freeze({
  total: COD_SOURCE_GAP_WORD_POOL.length,
  unique: new Set(COD_SOURCE_GAP_WORD_POOL).size,
  minLength: Math.min(...COD_SOURCE_GAP_WORD_POOL.map((word) => word.length)),
  maxLength: Math.max(...COD_SOURCE_GAP_WORD_POOL.map((word) => word.length)),
});
