import { compare } from "./rational";
import { required } from "./cp001-helpers";
import { tmwCp009NetRate } from "./cp009-engine";
import type { TmwCp009Parameters, TmwCp009RegistryEntry } from "./cp009-types";
import { ZERO, boundaryWord, flowUnit, hours, num, pipeList, quantity, targetPipe } from "./cp009-presentation-helpers";
export function renderTmwCp009Stem(entry:TmwCp009RegistryEntry,p:TmwCp009Parameters):string{const tank=p.context.tankLabel,net=tmwCp009NetRate(p.pipes);switch(entry.solveMode){
 case"findFillTimeFromPositiveInlets":return `At ${p.context.setting}, the ${tank} is initially empty. ${pipeList(p)}. If all the inlets are opened together, how long will they take to fill the tank completely?`;
 case"findFillTimeFromMixedPipes":return `At ${p.context.setting}, the ${tank} is initially empty. ${pipeList(p)}. All pipes remain open continuously. In how much time will the tank become full?`;
 case"findEmptyTimeFromMixedPipes":return `At ${p.context.setting}, the ${tank} is initially full. ${pipeList(p)}. All pipes remain open continuously. In how much time will the tank become empty?`;
 case"findNetFractionChangedInGivenTime":return `At ${p.context.setting}, ${pipeList(p)}. The tank is initially ${compare(net,ZERO)>0?"empty":"full"}, and all pipes remain open for ${hours(required(p.duration,"duration"))}. What fraction of the tank is ${compare(net,ZERO)>0?"filled":"emptied"} during this period?`;
 case"findMissingInletTime":{const unknown=targetPipe(p),combined=required(p.targetCompletionTime,"targetCompletionTime"),boundary=required(p.targetBoundary,"targetBoundary");return `At ${p.context.setting}, ${pipeList(p,required(p.unknownPipeIndex,"unknownPipeIndex"))}. An additional ${unknown.label} is opened simultaneously. Together, the pipes make the initially ${boundary==="FULL"?"empty":"full"} ${tank} ${boundaryWord(boundary)} in ${hours(combined)}. How long would ${unknown.label} take to fill the tank alone?`;}
 case"findMissingOutletOrLeakTime":{const unknown=targetPipe(p),combined=required(p.targetCompletionTime,"targetCompletionTime"),boundary=required(p.targetBoundary,"targetBoundary"),action=unknown.kind==="LEAK"?"the leak":"the outlet";return `At ${p.context.setting}, ${pipeList(p,required(p.unknownPipeIndex,"unknownPipeIndex"))}. An additional ${unknown.label} operates continuously. Together, the pipes make the initially ${boundary==="FULL"?"empty":"full"} ${tank} ${boundaryWord(boundary)} in ${hours(combined)}. How long would ${action} take to empty a full tank if acting alone?`;}
 case"findIdenticalPipeCountForTargetTime":return `At ${p.context.setting}, one inlet pipe can fill the empty ${tank} in ${hours(required(p.identicalPipeSoloTime,"identicalPipeSoloTime"))}. How many identical inlet pipes must be opened together to fill it in ${hours(required(p.targetCompletionTime,"targetCompletionTime"))}?`;
 case"findTankCapacityFromFlowAndTime":return `At ${p.context.setting}, an inlet supplies ${quantity(required(p.physicalFlow,"physicalFlow"))} litres of water per hour and fills the empty ${tank} in ${hours(required(p.physicalTime,"physicalTime"))}. What is the tank's capacity?`;
 case"findFlowRateFromCapacityAndTime":return `The ${tank} at ${p.context.setting} has a capacity of ${quantity(required(p.capacity,"capacity"))} litres. An inlet fills it from empty in ${hours(required(p.physicalTime,"physicalTime"))}. What is the inlet's flow rate in litres per hour?`;
 case"findTimeFromCapacityAndNetFlow":return `At ${p.context.setting}, the empty ${tank} has a capacity of ${quantity(required(p.capacity,"capacity"))} litres. The simultaneous pipes provide a net inflow of ${quantity(required(p.physicalFlow,"physicalFlow"))} litres per hour. How long will the tank take to become full?`;
 case"convertFlowUnits":return `A supply pipe at ${p.context.setting} delivers ${quantity(required(p.physicalFlow,"physicalFlow"))} ${flowUnit(required(p.sourceFlowUnit,"sourceFlowUnit"))}. What is the same flow rate in ${flowUnit(required(p.targetFlowUnit,"targetFlowUnit"))}?`;
 case"findTimeFromInitialLevelToBoundary":{const initial=required(p.initialLevel,"initialLevel"),boundary=required(p.targetBoundary,"targetBoundary");return `At ${p.context.setting}, the ${tank} is initially ${num(initial)} full. ${pipeList(p)}. All pipes remain open continuously. How long will the tank take to become ${boundaryWord(boundary)}?`;}
 case"findFinalLevelAfterGivenTime":return `At ${p.context.setting}, the ${tank} is initially ${num(required(p.initialLevel,"initialLevel"))} full. ${pipeList(p)}. If all pipes remain open for ${hours(required(p.duration,"duration"))} and no boundary is reached earlier, what fraction of the tank is full at the end?`;
 case"compareTankCapacities":{const c=required(p.comparison,"comparison");return `Two water tanks at ${p.context.setting} are filled separately. Tank A receives ${num(c.flowA)} litres per hour for ${hours(c.timeA)}, while Tank B receives ${num(c.flowB)} litres per hour for ${hours(c.timeB)}. Both start empty and become exactly full. What is the ratio of the capacity of Tank A to that of Tank B?`;}
 case"findReducedPipeEfficiencyFromChangedTime":return `An inlet at ${p.context.setting} originally filled the empty ${tank} in ${hours(required(p.originalTime,"originalTime"))}. After mineral deposits reduced its flow, it takes ${hours(required(p.changedTime,"changedTime"))}. What is the ratio of the inlet's new efficiency to its original efficiency?`;
 case"findBlockagePercentFromChangedTime":return `An inlet at ${p.context.setting} originally filled the empty ${tank} in ${hours(required(p.originalTime,"originalTime"))}. After a blockage, the same tank takes ${hours(required(p.changedTime,"changedTime"))} to fill. By what percentage has the inlet's effective flow rate been reduced?`;
 case"findNetRateDirection":return `At ${p.context.setting}, ${pipeList(p)}. When all pipes are opened together, what happens to the water level in the ${tank}?`;
 case"findBoundaryEventFeasibility":{const boundary=required(p.targetBoundary,"targetBoundary");return `At ${p.context.setting}, the ${tank} is initially ${num(required(p.initialLevel,"initialLevel"))} full. ${pipeList(p)}. All pipes remain open for ${hours(required(p.decisionWindow,"decisionWindow"))}. Will the tank become ${boundaryWord(boundary)} within this period?`;}
 }}
