export const SEA_001_MULTILINGUAL_FREEZE_V1 = Object.freeze({
  authorityId: "SEA_001_MULTILINGUAL_FREEZE_V1",
  date: "2026-10-01",
  status: "MULTILINGUAL_CONTENT_FROZEN",
  sourceEnglishAuthority: "SEA_001_ENGLISH_FREEZE_V1",
  localizationAuthority: "SEA_001_LOCALIZATION_V2_NATIVE",
  englishItems: 324,
  hindiItems: 324,
  punjabiItems: 324,
  blueprintAuthorities: 20,
  permanentQlCount: 9,
  permanentQlRange: "SEA-QL-001..SEA-QL-009",
  supportedLanguages: ["en", "hi", "pa"] as const,
  supportedDifficulties: ["Easy", "Medium", "Hard"] as const,
  correctIndexParity: true,
  qlParity: true,
  difficultyParity: true,
  untranslatedLatinProse: 0,
  diagramPolicy: "EXPLANATION_ONLY" as const,
  questionStudioReviewRegistrationPermitted: true,
  questionBankWritable: false,
  testEligible: false,
  mockTestEligible: false,
  publiclyPublishable: false,
  automaticStudentPublication: false,
});
