# Manual build of Question Studio TRG-002 worker, not the entire web app.
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--file', 'Dockerfile.question-studio-worker', '--tag', '${_IMAGE}', '.']
images: ['${_IMAGE}']
timeout: 1800s
