import assert from "node:assert/strict";
import { HIS_CP005_REQUIRED_FACTS_V1,HIS_CP005_REVIEW_BATCH_V1,auditHisCp005ReviewBatchV1 } from "./his-cp005-review-v1";

const audit=auditHisCp005ReviewBatchV1();
assert.equal(audit.valid,true,audit.issues.join(" | "));
assert.equal(audit.questionCount,60);
assert.equal(audit.semanticCount,60);
assert.deepEqual(audit.difficultyCounts,{Easy:18,Medium:30,Hard:12});
assert.equal(Object.keys(audit.qlCounts).length,10);
assert.ok(Object.values(audit.qlCounts).every(count=>count===6));
assert.ok(Math.max(...audit.answerPositions)-Math.min(...audit.answerPositions)<=1);
assert.equal(audit.requiredFactCount,audit.canonicalFactCount);
assert.equal(HIS_CP005_REQUIRED_FACTS_V1.length,audit.canonicalFactCount);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.every(q=>q.reviewOnly&&!q.runtimeRegistered),true);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.some(q=>/\b(?:NIOS|NCERT|UNESCO|textbook)\b/i.test(q.stem)),false);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.some(q=>/\b(?:NIOS|NCERT|UNESCO|textbook)\b/i.test(q.explanation)),false);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.some(q=>/(?:school-level|this CP|review batch|internal wording|canonical fact|source fact)/i.test(q.stem)),false);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.some(q=>/(?:school-level|this CP|review batch|internal wording|canonical fact|source fact)/i.test(q.explanation)),false);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.every(q=>q.stem.length<=190),true);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.every(q=>q.explanation.length>=140&&q.explanation.length<=360),true);
assert.equal(HIS_CP005_REVIEW_BATCH_V1.every(q=>(q.explanation.match(/[.!?](?:\s|$)/g)??[]).length>=2),true);
const hard=HIS_CP005_REVIEW_BATCH_V1.filter(q=>q.difficulty==="Hard");
const statementHard=hard.filter(q=>/^\d+\./.test(q.stem));
assert.ok(statementHard.length>=6);
assert.ok(new Set(statementHard.map(q=>q.canonicalAnswer)).size>=3);
assert.ok(statementHard.filter(q=>q.canonicalAnswer==="1, 2 and 3").length<=1);
console.log(JSON.stringify(audit,null,2));
