import{buildEng013BreadthAuthoritiesV4,type Eng013BreadthRecordV4}from"./eng-013-breadth3-factory-v4";
const R:readonly Eng013BreadthRecordV4[]=[
["aberrant","The result appears {x} the broader trend.",["aberrant from","aberrant to","aberrant with","aberrant on"],"Aberrant from means deviating from what is normal or expected."],
["adverse","The policy may have an {x} effect on small firms.",["adverse","adverse to","adverse with","adverse for"],"Adverse directly modifies a noun to mean harmful or unfavourable."],
["ambivalent","The committee remains {x} the proposed merger.",["ambivalent about","ambivalent to","ambivalent with","ambivalent on"],"Ambivalent about means having mixed feelings about something."],
["antithetical","The practice is {x} the stated principles of the policy.",["antithetical to","antithetical with","antithetical for","antithetical on"],"Antithetical to means directly opposed or contrary to something."],
["attendant","The reform may bring {x} risks as well as benefits.",["attendant","attendant to","attendant with","attendant on"],"Attendant can directly modify a noun to mean accompanying or associated."],
["concomitant","Rapid growth may produce {x} pressure on infrastructure.",["concomitant","concomitant to","concomitant with","concomitant on"],"Concomitant can mean naturally accompanying or associated with something."],
["correlative","The study found a {x} relationship between the two variables.",["correlative","correlative to","correlative with","correlative on"],"Correlative describes a relationship in which things vary together."],
["deleterious","Prolonged uncertainty can be {x} investment.",["deleterious to","deleterious for to","deleterious with","deleterious on"],"Deleterious to means causing harm or damage."],
["disparate","The committee combined evidence from {x} sources.",["disparate","disparate to","disparate with","disparate from"],"Disparate directly modifies a noun to mean essentially different or dissimilar."],
["divergent","The two reports reached {x} conclusions.",["divergent","divergent to","divergent with","divergent on"],"Divergent means moving apart or differing from one another."],
["endemic","The problem appears {x} the entire sector.",["endemic to","endemic in to","endemic with","endemic on"],"Endemic to means regularly found or deeply rooted in a particular place or group."],
["exogenous","The model treats the shock as {x} the system.",["exogenous to","exogenous with","exogenous for","exogenous on"],"Exogenous to means originating outside the system being studied."],
["extrinsic","The reward is {x} the activity itself.",["extrinsic to","extrinsic from to","extrinsic with","extrinsic on"],"Extrinsic to means coming from outside rather than being inherent."],
["fallacious","The conclusion rests on a {x} assumption.",["fallacious","fallacious to","fallacious with","fallacious on"],"Fallacious means based on mistaken reasoning."],
["incompatible","The new requirement is {x} the existing rule.",["incompatible with","incompatible to","incompatible for","incompatible on"],"Incompatible with means unable to coexist or work together consistently."],
["inconsistent","The statement is {x} the evidence on record.",["inconsistent with","inconsistent to","inconsistent for","inconsistent on"],"Inconsistent with means not in agreement with something."],
["indeterminate","The available evidence leaves the result {x}.",["indeterminate","indeterminate to","indeterminate with","indeterminate on"],"Indeterminate means not definitely known, fixed or decided."],
["inextricable","The two issues are {x} linked.",["inextricably","inextricable to","inextricable with","inextricable on"],"Inextricably linked means connected so closely that they cannot be separated."],
["invariant","The relationship remained {x} across all tested conditions.",["invariant","invariant to","invariant with","invariant on"],"Invariant means unchanged despite changes in conditions."],
["latent","The analysis attempts to identify {x} factors.",["latent","latent to","latent with","latent on"],"Latent directly modifies a noun to mean hidden or not yet visible."],
["material","The omission is {x} the final decision.",["material to","material for","material with","material on"],"Material to means sufficiently important or relevant to affect a decision."],
["nominal","The increase was only {x} after adjusting for inflation.",["nominal","nominal to","nominal with","nominal on"],"Nominal can mean stated in current money terms without adjustment for inflation."],
["orthogonal","The two dimensions are designed to be {x} one another.",["orthogonal to","orthogonal with","orthogonal for","orthogonal on"],"Orthogonal to can mean independent or at right angles in a formal sense."],
["pernicious","Persistent misinformation can be {x} public trust.",["pernicious to","pernicious for","pernicious with","pernicious on"],"Pernicious to means having a harmful effect, often gradually."],
["plausible","The explanation is {x} the evidence currently available.",["plausible given","plausible to given","plausible with","plausible on"],"Plausible given means reasonable in light of available evidence."],
["prejudicial","The disclosure could be {x} a fair hearing.",["prejudicial to","prejudicial for","prejudicial with","prejudicial on"],"Prejudicial to means harmful or damaging to someone's interests or a fair process."],
["presumptive","The test provides {x} evidence rather than final proof.",["presumptive","presumptive to","presumptive with","presumptive on"],"Presumptive means giving reasonable grounds for a conclusion but not conclusive proof."],
["proximate","The report identifies the {x} cause of the failure.",["proximate","proximate to","proximate with","proximate on"],"Proximate means nearest or most immediate in cause, time or place."],
["putative","The {x} cause has not yet been confirmed.",["putative","putative to","putative with","putative on"],"Putative means generally considered or supposed to be, though not proven."],
["requisite","The applicant lacks the {x} experience for the role.",["requisite","requisite to","requisite with","requisite on"],"Requisite means necessary for a particular purpose."],
["residual","The model still leaves a {x} error after adjustment.",["residual","residual to","residual with","residual on"],"Residual means remaining after the main part has been removed or accounted for."],
["salutary","The warning had a {x} effect on compliance.",["salutary","salutary to","salutary with","salutary on"],"Salutary means producing a beneficial or corrective effect."],
["seminal","The paper had a {x} influence on later research.",["seminal","seminal to","seminal with","seminal on"],"Seminal means highly influential and important in shaping later developments."],
["spurious","The apparent relationship may be {x}.",["spurious","spurious to","spurious with","spurious on"],"Spurious means apparently valid but actually false or misleading."],
["subordinate","Administrative convenience should remain {x} fairness.",["subordinate to","subordinate with","subordinate for","subordinate on"],"Subordinate to means lower in rank, importance or priority."],
["substantive","The objection is {x} rather than merely procedural.",["substantive","substantive to","substantive with","substantive on"],"Substantive means concerned with real content or essential issues."],
["superfluous","Several paragraphs are {x} the central argument.",["superfluous to","superfluous for","superfluous with","superfluous on"],"Superfluous to means unnecessary for something."],
["tenuous","The link between the two events is {x}.",["tenuous","tenuous to","tenuous with","tenuous on"],"Tenuous means weak, slight or not well supported."],
["tractable","The problem becomes more {x} after the scope is narrowed.",["tractable","tractable to","tractable with","tractable on"],"Tractable means manageable or easier to deal with."],
["unwarranted","The evidence does not justify such an {x} conclusion.",["unwarranted","unwarranted to","unwarranted with","unwarranted on"],"Unwarranted means not justified or authorized by the evidence or circumstances."],
["verifiable","The claim must be {x} independent records.",["verifiable against","verifiable to","verifiable with","verifiable on"],"Verifiable against means capable of being checked using an external reference."],
["cumulative","The effect is {x} rather than immediate.",["cumulative","cumulative to","cumulative with","cumulative on"],"Cumulative means increasing progressively by repeated additions."],
["detrimental","The delay may be {x} public confidence.",["detrimental to","detrimental for","detrimental with","detrimental on"],"Detrimental to means harmful to something."],
["indigenous","The programme draws on {x} knowledge.",["indigenous","indigenous to","indigenous with","indigenous on"],"Indigenous directly modifies a noun to mean originating naturally in a place or community."],
["inelastic","Demand for the service appears relatively {x} price changes.",["inelastic to","inelastic with","inelastic for","inelastic on"],"Inelastic to means not very responsive to changes in a factor."],
["interdependent","The two systems are highly {x}.",["interdependent","interdependent to","interdependent with","interdependent on"],"Interdependent means mutually dependent on one another."],
["normative","The statement is {x} rather than purely descriptive.",["normative","normative to","normative with","normative on"],"Normative means expressing a value judgment about what ought to be."],
["parsimonious","The simpler model is more {x} without sacrificing accuracy.",["parsimonious","parsimonious to","parsimonious with","parsimonious on"],"Parsimonious means economical or simple while explaining adequately."]
];
export const ENG013_BREADTH3_SSC_ADVANCED_B_V4=buildEng013BreadthAuthoritiesV4("WU-BR3-AB","ENG-013-CP002",R);
