import type{CardinalDirection}from"../foundation/types";import{CARDINAL_DIRECTIONS,applyTurnSequence,inferFacingFromShadowSide,relativeSideOfDirection,secondPersonFacing,shadowDirection}from"./environmental-orientation";import type{EnvironmentalTarget,PersonOrientationRelation,RelativeShadowSide,SunTimePeriod,TurnInstruction}from"./types";
const N=["Aman","Beena","Charan","Deepa","Farhan","Gurpreet","Harpreet","Isha","Jasleen","Karan","Meena","Naman","Pooja","Ravi","Simran","Tanvi"]as const;const P=["a school playground","a public park","an open field","a courtyard","a village square","a garden","a sports ground","a market yard","a college lawn","an office compound","a roadside clearing","a farmyard"]as const;const O=["vertical pole","flagpost","lamp post","tree trunk","statue","signboard post","tower mast","goalpost"]as const;const S=["LEFT","RIGHT","FRONT","BEHIND"]as const;const T=["LEFT","RIGHT","ABOUT"]as const;
const name=(s:number,o=0)=>N[(s*5+o*7+Math.floor(s/3))%N.length];const place=(s:number)=>P[(s*7+Math.floor(s/5))%P.length];function rnd(seed:number){let st=(seed^0x85ebca6b)>>>0;return()=>{st+=0x6d2b79f5;let v=st;v=Math.imul(v^(v>>>15),v|1);v^=v+Math.imul(v^(v>>>7),v|61);return((v^(v>>>14))>>>0)/4294967296;};}const pick=<T>(a:readonly T[],r:()=>number)=>a[Math.floor(r()*a.length)];
export function absoluteScenario(seed:number){const period:SunTimePeriod=seed%2===0?"MORNING":"EVENING";const target:EnvironmentalTarget=seed%4<2?"SUN":"SHADOW";const answer:CardinalDirection=target==="SUN"?(period==="MORNING"?"EAST":"WEST"):(period==="MORNING"?"WEST":"EAST");return{period,target,answer,object:O[(seed*3+Math.floor(seed/4))%O.length],variation:seed};}
export function facingScenario(seed:number){const period:SunTimePeriod=seed%2===0?"MORNING":"EVENING";const side=S[(seed*3+Math.floor(seed/2))%4];return{name:name(seed),period,side,facing:inferFacingFromShadowSide(period,side),activity:seed%3===0?"walking"as const:"standing"as const,place:place(seed),variation:seed};}
export function sideScenario(seed:number){const period:SunTimePeriod=seed%2===0?"MORNING":"EVENING";const facing=CARDINAL_DIRECTIONS[(seed*3+Math.floor(seed/4))%4];return{name:name(seed,1),period,facing,side:relativeSideOfDirection(facing,shadowDirection(period)),place:place(seed+2),variation:seed+17};}
export function timeScenario(seed:number){const period:SunTimePeriod=seed%2===0?"MORNING":"EVENING";const facing=CARDINAL_DIRECTIONS[Math.floor(seed/2)%4];return{name:name(seed,2),period,facing,side:relativeSideOfDirection(facing,shadowDirection(period)),place:place(seed+4),variation:seed+31};}
export function compoundScenario(seed:number){const r=rnd(seed*59+23),period:SunTimePeriod=seed%2===0?"MORNING":"EVENING",side=S[(seed*7+Math.floor(seed/2))%4],initialFacing=inferFacingFromShadowSide(period,side),count=1+seed%3,turns:TurnInstruction[]=[];for(let i=0;i<count;i++)turns.push(pick(T,r));return{name:name(seed,3),period,side,initialFacing,turns,finalFacing:applyTurnSequence(initialFacing,turns),place:place(seed+6),variation:seed+47};}
export function mutualScenario(seed:number){const period:SunTimePeriod=seed%2===0?"MORNING":"EVENING",side=S[(seed*5+Math.floor(seed/2))%4],firstFacing=inferFacingFromShadowSide(period,side),relation:PersonOrientationRelation=seed%3===0?"SAME_DIRECTION":"OPPOSITE_DIRECTION",firstName=name(seed,4);let secondName=name(seed,5);if(secondName===firstName)secondName=name(seed+1,6);return{firstName,secondName,period,side,firstFacing,relation,secondFacing:secondPersonFacing(firstFacing,relation),place:place(seed+8),variation:seed+61};}
