import { idiomaticUsageScene, type IdiomaticUsageSceneV1 } from "./cp013-scene-types";

export const CP013_MEDIUM_SCENES_V1: readonly IdiomaticUsageSceneV1[] = [
  idiomaticUsageScene({ id: "USG-M-001", difficulty: "medium", ruleId: "GR-USG-001", domain: "work-pattern", errorIndex: 0,
    correctSegments: ["Several analysts prefer working from the branch office to commuting between temporary sites", "when the monthly review", "requires access to paper records", "that are kept centrally."],
    errorSegments: ["Several analysts prefer working from the branch office than commuting between temporary sites", "when the monthly review", "requires access to paper records", "that are kept centrally."],
    reason: "The sentence directly compares two -ing activities after 'prefer'. The standard pair is 'prefer working ... to commuting ...'." }),
  idiomaticUsageScene({ id: "USG-M-002", difficulty: "medium", ruleId: "GR-USG-001", domain: "data-entry-method", errorIndex: 1,
    correctSegments: ["For routine data entry,", "the team prefers using the central portal to maintaining separate spreadsheets", "because the shared record", "is easier to verify."],
    errorSegments: ["For routine data entry,", "the team prefers using the central portal than maintaining separate spreadsheets", "because the shared record", "is easier to verify."],
    reason: "Two activities are compared after 'prefers', so use 'to': 'prefers using ... to maintaining ...'." }),
  idiomaticUsageScene({ id: "USG-M-003", difficulty: "medium", ruleId: "GR-USG-002", domain: "project-hierarchy", errorIndex: 2,
    correctSegments: ["Although both officers joined the project this year,", "their assigned grades are different,", "and Kavita is senior to Arjun", "in the approved hierarchy."],
    errorSegments: ["Although both officers joined the project this year,", "their assigned grades are different,", "and Kavita is senior than Arjun", "in the approved hierarchy."],
    reason: "The comparison is about official rank, not age. In that sense, 'senior' takes 'to'." }),
  idiomaticUsageScene({ id: "USG-M-004", difficulty: "medium", ruleId: "GR-USG-002", domain: "committee-role", errorIndex: 3,
    correctSegments: ["During the committee meeting,", "the coordinator clarified that", "the research assistant remained", "junior to the project officer."],
    errorSegments: ["During the committee meeting,", "the coordinator clarified that", "the research assistant remained", "junior than the project officer."],
    reason: "For a direct comparison of rank, the correct expression is 'junior to the project officer'." }),
  idiomaticUsageScene({ id: "USG-M-005", difficulty: "medium", ruleId: "GR-USG-003", domain: "software-layout", errorIndex: 0,
    correctSegments: ["The revised dashboard is different from the version used last quarter", "because the navigation panel", "has been moved to the left", "after user testing."],
    errorSegments: ["The revised dashboard is different with the version used last quarter", "because the navigation panel", "has been moved to the left", "after user testing."],
    reason: "The dashboard is compared with an earlier version. This checkpoint uses the standard surface 'different from'; 'different with' is invalid here." }),
  idiomaticUsageScene({ id: "USG-M-006", difficulty: "medium", ruleId: "GR-USG-003", domain: "policy-draft", errorIndex: 1,
    correctSegments: ["After legal review,", "the final policy was substantially different from the circulated draft", "in its definition of eligibility", "for the scheme."],
    errorSegments: ["After legal review,", "the final policy was substantially different with the circulated draft", "in its definition of eligibility", "for the scheme."],
    reason: "The correct comparison is 'different from the circulated draft'. 'Different with' is not a standard form for this meaning." }),
  idiomaticUsageScene({ id: "USG-M-007", difficulty: "medium", ruleId: "GR-USG-004", domain: "software-capacity", errorIndex: 2,
    correctSegments: ["With the upgraded memory,", "the workstation can process larger files", "and is capable of running several analysis tools", "at the same time."],
    errorSegments: ["With the upgraded memory,", "the workstation can process larger files", "and is capable to run several analysis tools", "at the same time."],
    reason: "After 'capable', the activity is expressed with 'of + -ing': 'capable of running'." }),
  idiomaticUsageScene({ id: "USG-M-008", difficulty: "medium", ruleId: "GR-USG-004", domain: "research-team", errorIndex: 3,
    correctSegments: ["After two weeks of training,", "the field team demonstrated", "that it was capable", "of recording the readings accurately."],
    errorSegments: ["After two weeks of training,", "the field team demonstrated", "that it was capable", "to record the readings accurately."],
    reason: "The standard complement is 'capable of recording', not 'capable to record'." }),
  idiomaticUsageScene({ id: "USG-M-009", difficulty: "medium", ruleId: "GR-USG-005", domain: "inspection-record", errorIndex: 0,
    correctSegments: ["The inspecting officer insisted on recording every damaged item", "before the warehouse was reopened", "to the staff", "after lunch."],
    errorSegments: ["The inspecting officer insisted for recording every damaged item", "before the warehouse was reopened", "to the staff", "after lunch."],
    reason: "Here 'insisted' takes an -ing complement. Use 'insisted on recording', not 'insisted for recording'." }),
  idiomaticUsageScene({ id: "USG-M-010", difficulty: "medium", ruleId: "GR-USG-005", domain: "written-confirmation", errorIndex: 1,
    correctSegments: ["Before releasing the equipment,", "the storekeeper insisted on a written acknowledgement", "from the receiving department", "for the handover."],
    errorSegments: ["Before releasing the equipment,", "the storekeeper insisted for a written acknowledgement", "from the receiving department", "for the handover."],
    reason: "A noun complement follows this use of 'insist on': 'insisted on a written acknowledgement'." }),
  idiomaticUsageScene({ id: "USG-M-011", difficulty: "medium", ruleId: "GR-USG-006", domain: "server-access", errorIndex: 2,
    correctSegments: ["During the security update,", "temporary restrictions", "prevented staff from accessing the internal server", "from outside the office network."],
    errorSegments: ["During the security update,", "temporary restrictions", "prevented staff to access the internal server", "from outside the office network."],
    reason: "The explicit standard pattern is 'prevented staff from accessing', not 'prevented staff to access'." }),
  idiomaticUsageScene({ id: "USG-M-012", difficulty: "medium", ruleId: "GR-USG-006", domain: "storage-moisture", errorIndex: 3,
    correctSegments: ["The technician added a second seal", "around the storage cabinet", "to prevent moisture", "from entering during the monsoon."],
    errorSegments: ["The technician added a second seal", "around the storage cabinet", "to prevent moisture", "to enter during the monsoon."],
    reason: "Use 'prevent ... from + -ing': 'prevent moisture from entering'." }),
  idiomaticUsageScene({ id: "USG-M-013", difficulty: "medium", ruleId: "GR-USG-007", domain: "deadline-completion", errorIndex: 0,
    correctSegments: ["Despite repeated power interruptions,", "the data team completed the upload", "before the revised deadline", "on Friday evening."],
    errorSegments: ["Despite of repeated power interruptions,", "the data team completed the upload", "before the revised deadline", "on Friday evening."],
    reason: "'Despite' takes the noun phrase directly. The extra 'of' makes the expression incorrect." }),
  idiomaticUsageScene({ id: "USG-M-014", difficulty: "medium", ruleId: "GR-USG-007", domain: "road-diversion", errorIndex: 1,
    correctSegments: ["The ambulance reached the hospital", "in spite of a long traffic diversion", "created by road repairs", "near the flyover."],
    errorSegments: ["The ambulance reached the hospital", "in spite a long traffic diversion", "created by road repairs", "near the flyover."],
    reason: "The fixed expression is 'in spite of'; the noun phrase must be introduced by 'of'." }),
  idiomaticUsageScene({ id: "USG-M-015", difficulty: "medium", ruleId: "GR-USG-008", domain: "inspection-begin", errorIndex: 2,
    correctSegments: ["The inspection team had no sooner started", "checking the first set of records", "than the server failed", "and the review was paused."],
    errorSegments: ["The inspection team had no sooner started", "checking the first set of records", "when the server failed", "and the review was paused."],
    reason: "The immediate-succession construction pairs 'no sooner' with 'than', even though the two parts are separated here." }),
  idiomaticUsageScene({ id: "USG-M-016", difficulty: "medium", ruleId: "GR-USG-008", domain: "train-platform", errorIndex: 3,
    correctSegments: ["The passengers had no sooner reached", "the far end of the platform", "after the announcement", "than the train changed tracks."],
    errorSegments: ["The passengers had no sooner reached", "the far end of the platform", "after the announcement", "when the train changed tracks."],
    reason: "In this paired construction, 'no sooner' requires 'than' before the second event." }),
  idiomaticUsageScene({ id: "USG-M-017", difficulty: "medium", ruleId: "GR-USG-008", domain: "meeting-notice", errorIndex: 0,
    correctSegments: ["No sooner had the revised notice been circulated than the meeting time changed again", "because the chairperson", "was delayed by another engagement", "at headquarters."],
    errorSegments: ["No sooner had the revised notice been circulated when the meeting time changed again", "because the chairperson", "was delayed by another engagement", "at headquarters."],
    reason: "The fronted form is 'No sooner had ... than ...'. The connector 'when' does not complete this pair." }),
  idiomaticUsageScene({ id: "USG-M-018", difficulty: "medium", ruleId: "GR-USG-009", domain: "database-backup", errorIndex: 1,
    correctSegments: ["The operator had hardly completed the backup", "when the system displayed another warning", "about low storage space", "on the main drive."],
    errorSegments: ["The operator had hardly completed the backup", "than the system displayed another warning", "about low storage space", "on the main drive."],
    reason: "The second event followed immediately, so the fixed pair is 'hardly ... when'." }),
  idiomaticUsageScene({ id: "USG-M-019", difficulty: "medium", ruleId: "GR-USG-009", domain: "auditor-arrival", errorIndex: 2,
    correctSegments: ["The branch staff had scarcely finished arranging the files", "for the scheduled inspection", "when the auditors arrived", "earlier than expected."],
    errorSegments: ["The branch staff had scarcely finished arranging the files", "for the scheduled inspection", "than the auditors arrived", "earlier than expected."],
    reason: "'Scarcely' takes 'when' to introduce the immediately following event." }),
  idiomaticUsageScene({ id: "USG-M-020", difficulty: "medium", ruleId: "GR-USG-009", domain: "presentation-start", errorIndex: 3,
    correctSegments: ["Hardly had the speaker begun the presentation", "after the brief introduction", "to the visiting officers", "when the projector stopped working."],
    errorSegments: ["Hardly had the speaker begun the presentation", "after the brief introduction", "to the visiting officers", "than the projector stopped working."],
    reason: "The formal fronted pattern is 'Hardly had ... when ...', so 'when' is required." }),
];
