import type { AngleMeasure, ExactTrigNumber, IndependentVerification, TrigExpression } from "../foundation/types";
import {
  addExact, assertDefined, divideExact, exactInteger, exactKey, exactRational, exactSurd,
  exactToNumber, formatExactPlain, multiplyExact, powerExact, subtractExact,
} from "../foundation/exact";
import { degree, radianPi, toDegrees, toRadianPiAngle } from "../foundation/angle";
import { evaluateTrigExact, requireTrigExact } from "../foundation/standard-values";
import { evaluateTrigExpression, expr } from "../foundation/expression";
import { verifyExpressionNumerically, verifyStandardTrigValue } from "../foundation/independent-verifier";

export const TRG_001_PACKAGE_ID = "TRG-001" as const;
export const TRG_001_PROOF_CP_IDS = ["TRG-CP-001","TRG-CP-002","TRG-CP-003","TRG-CP-004","TRG-CP-005","TRG-CP-006"] as const;
export type Trg001ProofCpId = (typeof TRG_001_PROOF_CP_IDS)[number];
type Difficulty = "Easy"|"Medium"|"Hard";
type Target = "SCALAR"|"ANGLE"|"LENGTH"|"AREA";
type Unit = "NONE"|"UNITS"|"SQUARE_UNITS";
type NumberAnswer = {kind:"NUMBER";value:ExactTrigNumber;unit:Unit};
type AngleAnswer = {kind:"ANGLE";value:AngleMeasure;preferredDisplay:"DEGREE"|"RADIAN_PI"};
export type Trg001ProofAnswer = NumberAnswer|AngleAnswer;
export type Trg001ProofRegistryEntry = {qlId:string;cpId:Trg001ProofCpId;solveMode:string;difficulty:Difficulty;target:Target;proofOnly:true;description:string};
export type Trg001ProofOption = {label:"A"|"B"|"C"|"D";value:Trg001ProofAnswer;display:string;isCorrect:boolean;misconceptionId:string|null};
export type Trg001ProofExplanation = {keyRule:string;steps:Array<{title:string;body:string;equation?:string}>;shortcut:string;traps:string[]};
export type Trg001ProofQuestion = {
  packageId:typeof TRG_001_PACKAGE_ID;cpId:Trg001ProofCpId;qlId:string;solveMode:string;language:"en";seed:string;difficulty:Difficulty;target:Target;
  stem:string;options:Trg001ProofOption[];correctIndex:number;answer:string;exactAnswer:Trg001ProofAnswer;explanation:Trg001ProofExplanation;
  canonicalState:Record<string,string|number|boolean>;
  verification:{valid:boolean;method:string;expected:string;reconstructed:string;numericDelta:number|null};
  validation:{valid:boolean;checks:Array<{name:string;passed:boolean;message:string}>};
  reviewStatus:"UNREVIEWED";questionBankStatus:"NOT_STORED";testEligibility:"INELIGIBLE";publiclyPublishable:false;questionStudioDiscoverable:false;proofOnly:true;
};

const R = [
["TRG-001-QL-001","TRG-CP-001","findSinFromKnownSides","Easy","SCALAR","Direct sine from sides"],
["TRG-001-QL-002","TRG-CP-001","findCosFromKnownSides","Easy","SCALAR","Direct cosine from sides"],
["TRG-001-QL-003","TRG-CP-001","findMissingHypotenuseThenSin","Medium","SCALAR","Pythagoras then sine"],
["TRG-001-QL-004","TRG-CP-001","findOppositeSideFromSin","Medium","LENGTH","Side recovery from sine"],
["TRG-001-QL-005","TRG-CP-001","deriveSecFromTan","Medium","SCALAR","Secant from tangent"],
["TRG-001-QL-025","TRG-CP-002","evaluateStandardSine","Easy","SCALAR","Standard sine"],
["TRG-001-QL-026","TRG-CP-002","evaluateStandardReciprocal","Easy","SCALAR","Standard secant"],
["TRG-001-QL-027","TRG-CP-002","evaluateStandardProduct","Medium","SCALAR","Standard-value product"],
["TRG-001-QL-028","TRG-CP-002","evaluateStandardPythagoreanSum","Medium","SCALAR","Standard Pythagorean sum"],
["TRG-001-QL-029","TRG-CP-002","evaluateStandardMixedProduct","Medium","SCALAR","Tangent-cotangent product"],
["TRG-001-QL-049","TRG-CP-003","convertDegreesToRadians","Easy","ANGLE","Degree to radian conversion"],
["TRG-001-QL-050","TRG-CP-003","convertRadiansToDegrees","Easy","ANGLE","Radian to degree conversion"],
["TRG-001-QL-051","TRG-CP-003","evaluateComplementarySine","Medium","SCALAR","Complementary relation"],
["TRG-001-QL-052","TRG-CP-003","evaluateSecondQuadrantCosine","Medium","SCALAR","Second-quadrant reduction"],
["TRG-001-QL-053","TRG-CP-003","evaluateCoterminalTangent","Medium","SCALAR","Coterminal reduction"],
["TRG-001-QL-073","TRG-CP-004","deriveCosFromSin","Medium","SCALAR","Cosine from sine identity"],
["TRG-001-QL-074","TRG-CP-004","deriveSecSquaredFromTan","Medium","SCALAR","Secant-square identity"],
["TRG-001-QL-075","TRG-CP-004","simplifySecTanIdentity","Easy","SCALAR","sec²−tan² identity"],
["TRG-001-QL-076","TRG-CP-004","simplifySinCosRationalIdentity","Medium","SCALAR","Rational identity simplification"],
["TRG-001-QL-077","TRG-CP-004","deriveCotFromCosec","Medium","SCALAR","Cotangent from cosecant"],
["TRG-001-QL-097","TRG-CP-005","evaluateDerivedSinCosRatio","Hard","SCALAR","Derived sin/cos ratio"],
["TRG-001-QL-098","TRG-CP-005","useSecTanConjugate","Medium","SCALAR","sec±tan conjugates"],
["TRG-001-QL-099","TRG-CP-005","useCosecCotConjugate","Medium","SCALAR","cosec±cot conjugates"],
["TRG-001-QL-100","TRG-CP-005","deriveDoubleProductFromSinPlusCos","Hard","SCALAR","Recover 2sin cos from sum"],
["TRG-001-QL-101","TRG-CP-005","solveTanFromLinearSinCosRelation","Medium","SCALAR","Linear sin/cos relation"],
["TRG-001-QL-121","TRG-CP-006","evaluateMixedStandardExpression","Hard","SCALAR","Mixed standard expression"],
["TRG-001-QL-122","TRG-CP-006","evaluateAngleSumIdentityExpansion","Hard","SCALAR","Angle-sum expansion"],
["TRG-001-QL-123","TRG-CP-006","evaluateDoubleAngleExpansion","Medium","SCALAR","Double-angle expansion"],
["TRG-001-QL-124","TRG-CP-006","findTriangleAreaUsingSine","Medium","AREA","Triangle area using sine"],
["TRG-001-QL-125","TRG-CP-006","evaluateTanCotComposite","Hard","SCALAR","Composite tan/cot expression"],
] as const;
export const TRG_001_RUNTIME_PROOF_REGISTRY:Trg001ProofRegistryEntry[]=R.map(([qlId,cpId,solveMode,difficulty,target,description])=>({qlId,cpId,solveMode,difficulty,target,description,proofOnly:true}));
const BY_ID=new Map(TRG_001_RUNTIME_PROOF_REGISTRY.map(x=>[x.qlId,x]));

const TRIPLES=[{o:3,a:4,h:5},{o:5,a:12,h:13},{o:8,a:15,h:17},{o:7,a:24,h:25},{o:20,a:21,h:29}] as const;
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function pick<T>(seed:string,salt:string,v:readonly T[]):T{return v[hash(seed+"|"+salt)%v.length]}
function tri(seed:string,id:string){return pick(seed,id+"|tri",TRIPLES)}
const N=(value:ExactTrigNumber,unit:Unit="NONE"):NumberAnswer=>({kind:"NUMBER",value,unit});
const A=(value:AngleMeasure,preferredDisplay:"DEGREE"|"RADIAN_PI"):AngleAnswer=>({kind:"ANGLE",value,preferredDisplay});
const Q=(n:number,d:number)=>exactRational(n,d);
function radianText(x:AngleMeasure){const r=toRadianPiAngle(x).coefficient,n=r.numerator,d=r.denominator,sg=n<0n?"-":"",an=n<0n?-n:n;if(n===0n)return"0";if(d===1n)return an===1n?sg+"π":sg+an+"π";return an===1n?`${sg}π/${d}`:`${sg}${an}π/${d}`}
function key(x:Trg001ProofAnswer){if(x.kind==="NUMBER")return`N:${x.unit}:${exactKey(x.value)}`;const d=toDegrees(x.value);return`A:${d.numerator}/${d.denominator}`}
function show(x:Trg001ProofAnswer){if(x.kind==="ANGLE"){if(x.preferredDisplay==="RADIAN_PI")return radianText(x.value);const d=toDegrees(x.value);return`${d.denominator===1n?d.numerator:`${d.numerator}/${d.denominator}`}°`}const s=formatExactPlain(x.value);return x.unit==="UNITS"?`${s} units`:x.unit==="SQUARE_UNITS"?`${s} square units`:s}
function shuffle<T>(seed:string,a:T[]){let s=hash(seed)||1;for(let i=a.length-1;i>0;i--){s=(Math.imul(s,1664525)+1013904223)>>>0;const j=s%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function expl(rule:string,working:string,trap:string,shortcut=rule):Trg001ProofExplanation{return{keyRule:rule,steps:[{title:"Working",body:working}],shortcut,traps:[trap]}}
function iv(v:IndependentVerification){return{valid:v.valid,method:v.method,expected:v.expectedKey,reconstructed:v.reconstructedKey,numericDelta:v.numericDelta}}
function nv(x:ExactTrigNumber,y:number,method:string){const d=Math.abs(exactToNumber(x)-y);return{valid:Number.isFinite(y)&&d<=1e-10,method,expected:exactKey(x),reconstructed:`NUM:${y}`,numericDelta:d}}
function av(x:AngleAnswer,y:number,method:string){const d=toDegrees(x.value),z=Number(d.numerator)/Number(d.denominator),e=Math.abs(z-y);return{valid:e<=1e-12,method,expected:`${z}°`,reconstructed:`${y}°`,numericDelta:e}}

type D={value:Trg001ProofAnswer;misconceptionId:string};
type Spec={stem:string;correct:Trg001ProofAnswer;wrong:D[];explanation:Trg001ProofExplanation;state:Record<string,string|number|boolean>;verification:Trg001ProofQuestion["verification"]};
function expressionSpec(stem:string,e:TrigExpression,wrong:D[],explanation:Trg001ProofExplanation,state:Spec["state"]):Spec{const x=evaluateTrigExpression(e);if(x.kind==="UNDEFINED")throw new Error("proof expression unexpectedly undefined");return{stem,correct:N(x),wrong,explanation,state,verification:iv(verifyExpressionNumerically(e,x))}}
function std(fn:"SIN"|"COS"|"TAN"|"COT"|"SEC"|"COSEC",a:number){return requireTrigExact(fn,degree(a))}

function buildSpec(id:string,seed:string):Spec{
 const t=tri(seed,id);
 switch(id){
 case"TRG-001-QL-001":{const c=N(Q(t.o,t.h));return{stem:`In a right triangle, the side opposite θ is ${t.o} units and the hypotenuse is ${t.h} units. Find sin θ.`,correct:c,wrong:[{value:N(Q(t.a,t.h)),misconceptionId:"SIN_COS_SWAP"},{value:N(Q(t.a,t.o)),misconceptionId:"SIDE_ROLE_SWAP"},{value:N(Q(t.h,t.o)),misconceptionId:"RECIPROCAL"}],explanation:expl("sin θ = opposite/hypotenuse",`${t.o}/${t.h} = ${show(c)}.`,"Do not use adjacent/hypotenuse."),state:{o:t.o,a:t.a,h:t.h},verification:nv(c.value,t.o/t.h,"SIDE_RATIO")}}
 case"TRG-001-QL-002":{const c=N(Q(t.a,t.h));return{stem:`For an acute angle θ, the adjacent side is ${t.a} units and the hypotenuse is ${t.h} units. Find cos θ.`,correct:c,wrong:[{value:N(Q(t.o,t.h)),misconceptionId:"SIN_COS_SWAP"},{value:N(Q(t.o,t.a)),misconceptionId:"USED_TAN"},{value:N(Q(t.h,t.a)),misconceptionId:"RECIPROCAL"}],explanation:expl("cos θ = adjacent/hypotenuse",`${t.a}/${t.h} = ${show(c)}.`,"Hypotenuse/adjacent is secant."),state:{o:t.o,a:t.a,h:t.h},verification:nv(c.value,t.a/t.h,"SIDE_RATIO")}}
 case"TRG-001-QL-003":{const c=N(Q(t.o,t.h));return{stem:`The perpendicular and base of a right triangle are ${t.o} and ${t.a} units. If θ is opposite the perpendicular, find sin θ.`,correct:c,wrong:[{value:N(Q(t.a,t.h)),misconceptionId:"SIN_COS_SWAP"},{value:N(Q(t.o,t.a)),misconceptionId:"USED_TAN"},{value:N(Q(t.a,t.o)),misconceptionId:"USED_COT"}],explanation:expl("Find the hypotenuse first, then use sine.",`h=√(${t.o}²+${t.a}²)=${t.h}; sin θ=${t.o}/${t.h}.`,"Do not stop after finding the hypotenuse."),state:{perpendicular:t.o,base:t.a,h:t.h},verification:nv(c.value,t.o/Math.sqrt(t.o*t.o+t.a*t.a),"PYTHAGOREAN_RATIO")}}
 case"TRG-001-QL-004":{const s=pick(seed,id+"|scale",[2,3,4,5] as const),h=t.h*s,o=t.o*s,a=t.a*s,c=N(exactInteger(o),"UNITS");return{stem:`If sin θ = ${t.o}/${t.h} and the hypotenuse is ${h} units, find the side opposite θ.`,correct:c,wrong:[{value:N(exactInteger(a),"UNITS"),misconceptionId:"SIN_COS_SWAP"},{value:N(exactInteger(h),"UNITS"),misconceptionId:"USED_HYPOTENUSE"},{value:N(exactInteger((t.h-t.o)*s),"UNITS"),misconceptionId:"SUBTRACTED_PARTS"}],explanation:expl("Scale the ratio triangle.",`${t.h} parts = ${h}, so scale=${s}; opposite=${t.o}×${s}=${o}.`,"The sine numerator is the opposite side."),state:{ratioO:t.o,ratioH:t.h,scale:s,h,o},verification:nv(c.value,t.o/t.h*h,"PROPORTION")}}
 case"TRG-001-QL-005":{const c=N(Q(t.h,t.a));return{stem:`If tan θ = ${t.o}/${t.a} and θ is acute, find sec θ.`,correct:c,wrong:[{value:N(Q(t.h,t.o)),misconceptionId:"SEC_COSEC_SWAP"},{value:N(Q(t.o,t.a)),misconceptionId:"RETURNED_TAN"},{value:N(Q(t.a,t.o)),misconceptionId:"RECIPROCAL"}],explanation:expl("tan gives the two legs; sec = hypotenuse/adjacent.",`The matching hypotenuse is ${t.h}, so sec θ=${t.h}/${t.a}.`,"Do not use hypotenuse/opposite."),state:{tanN:t.o,tanD:t.a,h:t.h},verification:nv(c.value,Math.sqrt(1+(t.o/t.a)**2),"SEC_FROM_TAN")}}
 case"TRG-001-QL-025":{const a=pick(seed,id+"|a",[30,60] as const),x=evaluateTrigExact("SIN",degree(a));if(x.kind==="UNDEFINED")throw new Error("bad standard angle");const c=N(x);return{stem:`Find the exact value of sin ${a}°.`,correct:c,wrong:[{value:N(std("COS",a)),misconceptionId:"SIN_COS_SWAP"},{value:N(std("TAN",a)),misconceptionId:"USED_TAN"},{value:N(std("COT",a)),misconceptionId:"USED_COT"}],explanation:expl("Use the exact standard-angle value.",`sin ${a}° = ${show(c)}.`,"Do not replace an exact surd by a decimal."),state:{angle:a},verification:iv(verifyStandardTrigValue("SIN",degree(a),x))}}
 case"TRG-001-QL-026":{const a=pick(seed,id+"|a",[30,60] as const),x=std("SEC",a),c=N(x);return{stem:`Find the exact value of sec ${a}°.`,correct:c,wrong:[{value:N(std("COS",a)),misconceptionId:"RECIPROCAL_NOT_TAKEN"},{value:N(std("COSEC",a)),misconceptionId:"SEC_COSEC_SWAP"},{value:N(std("TAN",a)),misconceptionId:"USED_TAN"}],explanation:expl("sec θ = 1/cos θ.",`sec ${a}° = ${show(c)}.`,"Do not confuse secant with cosecant."),state:{angle:a},verification:iv(verifyStandardTrigValue("SEC",degree(a),x))}}
 case"TRG-001-QL-027":{const v=pick(seed,id+"|v",[0,1] as const),a=v?60:30,b=v?30:60,e=expr.multiply(expr.trig("SIN",degree(a)),expr.trig("COS",degree(b))),l=std("SIN",a),r=std("COS",b);return expressionSpec(`Evaluate exactly: sin ${a}° × cos ${b}°.`,e,[{value:N(addExact(l,r)),misconceptionId:"ADDED"},{value:N(l),misconceptionId:"DROPPED_FACTOR"},{value:N(exactInteger(2)),misconceptionId:"DOUBLED"}],expl("Substitute standard values, then multiply.",`sin ${a}°=${formatExactPlain(l)}, cos ${b}°=${formatExactPlain(r)}.`,"Multiply; do not add."),{a,b})}
 case"TRG-001-QL-028":{const a=pick(seed,id+"|a",[30,45,60] as const),e=expr.add(expr.power(expr.trig("SIN",degree(a)),2),expr.power(expr.trig("COS",degree(a)),2));return expressionSpec(`Evaluate: sin² ${a}° + cos² ${a}°.`,e,[{value:N(exactInteger(0)),misconceptionId:"SIGN"},{value:N(exactInteger(2)),misconceptionId:"TWO"},{value:N(exactRational(1,2)),misconceptionId:"ONE_TERM"}],expl("sin²θ+cos²θ=1.","Apply the identity directly.","The square applies to the trig value."),{a})}
 case"TRG-001-QL-029":{const v=pick(seed,id+"|v",[0,1] as const),a=v?30:60,b=v?60:30,e=expr.multiply(expr.trig("TAN",degree(a)),expr.trig("COT",degree(b)));return expressionSpec(`Evaluate exactly: tan ${a}° × cot ${b}°.`,e,[{value:N(exactInteger(1)),misconceptionId:"ASSUMED_RECIPROCALS"},{value:N(exactSurd(1,3)),misconceptionId:"SINGLE_VALUE"},{value:N(exactSurd(1,3,3)),misconceptionId:"RECIPROCAL_VALUE"}],expl("Evaluate each angle separately.",`The angles differ, so tan ${a}°·cot ${b}° is not automatically 1.`,"tan α and cot β are reciprocals only when α=β."),{a,b})}
 case"TRG-001-QL-049":{const d=pick(seed,id+"|d",[30,45,60,90,120,135,150] as const),c=A(radianPi(d,180),"RADIAN_PI");return{stem:`Convert ${d}° to radians in terms of π.`,correct:c,wrong:[{value:A(radianPi(d,360),"RADIAN_PI"),misconceptionId:"USED_360"},{value:A(radianPi(d,90),"RADIAN_PI"),misconceptionId:"USED_90"},{value:A(radianPi(180,d),"RADIAN_PI"),misconceptionId:"INVERTED"}],explanation:expl("radians = degrees × π/180.",`${d}° = ${show(c)}.`,"Use 180, not 360."),state:{degrees:d},verification:av(c,d,"ANGLE_EQUIVALENCE")}}
 case"TRG-001-QL-050":{const z=pick(seed,id+"|z",[{n:1,d:6,g:30},{n:1,d:4,g:45},{n:1,d:3,g:60},{n:2,d:3,g:120},{n:3,d:4,g:135},{n:5,d:6,g:150}] as const),src=radianPi(z.n,z.d),c=A(degree(z.g),"DEGREE");return{stem:`Convert ${radianText(src)} to degrees.`,correct:c,wrong:[{value:A(degree(z.g,2),"DEGREE"),misconceptionId:"HALVED"},{value:A(degree(z.g*2),"DEGREE"),misconceptionId:"DOUBLED"},{value:A(degree(z.g+90),"DEGREE"),misconceptionId:"ADDED_90"}],explanation:expl("degrees = π-coefficient × 180.",`${z.n}/${z.d}×180°=${z.g}°.`,"Do not multiply by 360."),state:{n:z.n,d:z.d},verification:av(c,z.n/z.d*180,"RADIAN_DEGREE_ARITHMETIC")}}
 case"TRG-001-QL-051":{const a=pick(seed,id+"|a",[30,60] as const),b=90-a,x=std("SIN",b),c=N(x);return{stem:`If θ=${a}°, evaluate sin(90°−θ).`,correct:c,wrong:[{value:N(std("SIN",a)),misconceptionId:"NO_COFUNCTION_SWAP"},{value:N(std("TAN",a)),misconceptionId:"USED_TAN"},{value:N(std("COT",a)),misconceptionId:"USED_COT"}],explanation:expl("sin(90°−θ)=cosθ.",`sin ${b}°=cos ${a}°=${show(c)}.`,"Sine and cosine swap for complements."),state:{theta:a,target:b},verification:iv(verifyStandardTrigValue("SIN",degree(b),x))}}
 case"TRG-001-QL-052":{const a=pick(seed,id+"|a",[30,60] as const),b=180-a,x=std("COS",b),c=N(x);return{stem:`Evaluate exactly: cos(180°−${a}°).`,correct:c,wrong:[{value:N(std("COS",a)),misconceptionId:"SIGN"},{value:N(multiplyExact(exactInteger(-1),std("SIN",a))),misconceptionId:"SIN_COS_SWAP"},{value:N(std("TAN",a)),misconceptionId:"USED_TAN"}],explanation:expl("cos(180°−θ)=−cosθ.",`${b}° is in quadrant II, so cosine is negative.`,"Do not lose the quadrant sign."),state:{theta:a,target:b},verification:iv(verifyStandardTrigValue("COS",degree(b),x))}}
 case"TRG-001-QL-053":{const a=pick(seed,id+"|a",[30,60] as const),b=360+a,x=std("TAN",b),c=N(x),tan=std("TAN",a),cot=std("COT",a);return{stem:`Evaluate exactly: tan ${b}°.`,correct:c,wrong:[{value:N(multiplyExact(exactInteger(-1),tan)),misconceptionId:"SIGN"},{value:N(cot),misconceptionId:"RECIPROCAL"},{value:N(multiplyExact(exactInteger(-1),cot)),misconceptionId:"BOTH"}],explanation:expl("A full turn leaves tangent unchanged.",`${b}°−360°=${a}°, so tan ${b}°=tan ${a}°.`,"Do not change the sign after a full turn."),state:{original:b,reduced:a},verification:iv(verifyStandardTrigValue("TAN",degree(b),x))}}
 case"TRG-001-QL-073":{const c=N(Q(t.a,t.h));return{stem:`If sin θ=${t.o}/${t.h} and θ is acute, find cos θ.`,correct:c,wrong:[{value:N(Q(t.o,t.h)),misconceptionId:"RETURNED_SIN"},{value:N(Q(t.h,t.a)),misconceptionId:"RECIPROCAL"},{value:N(Q(t.o,t.a)),misconceptionId:"USED_TAN"}],explanation:expl("sin²θ+cos²θ=1.",`Adjacent=√(${t.h}²−${t.o}²)=${t.a}; cos θ=${t.a}/${t.h}.`,"Acute θ selects the positive root."),state:{sinN:t.o,sinD:t.h,a:t.a},verification:nv(c.value,Math.sqrt(1-(t.o/t.h)**2),"PYTHAGOREAN_IDENTITY")}}
 case"TRG-001-QL-074":{const tan2=Q(t.o*t.o,t.a*t.a),c=N(Q(t.h*t.h,t.a*t.a));return{stem:`If tan θ=${t.o}/${t.a}, find sec² θ.`,correct:c,wrong:[{value:N(Q(t.h,t.a)),misconceptionId:"FORGOT_SQUARE"},{value:N(tan2),misconceptionId:"DROPPED_ONE"},{value:N(subtractExact(exactInteger(1),tan2)),misconceptionId:"SIGN"}],explanation:expl("1+tan²θ=sec²θ.",`sec²θ=1+${t.o*t.o}/${t.a*t.a}=${show(c)}.`,"The target is sec², not sec."),state:{tanN:t.o,tanD:t.a},verification:nv(c.value,1+(t.o/t.a)**2,"IDENTITY_NUMERIC")}}
 case"TRG-001-QL-075":{const s=pick(seed,id+"|s",["θ","α","x"] as const),c=N(exactInteger(1));return{stem:`Simplify: sec²${s}−tan²${s}.`,correct:c,wrong:[{value:N(exactInteger(0)),misconceptionId:"ZERO"},{value:N(exactInteger(2)),misconceptionId:"TWO"},{value:N(exactInteger(-1)),misconceptionId:"SIGN"}],explanation:expl("sec²θ−tan²θ=1.","Rearrange 1+tan²θ=sec²θ.","The result is +1."),state:{symbol:s},verification:nv(c.value,1,"ALGEBRAIC_IDENTITY")}}
 case"TRG-001-QL-076":{const s=pick(seed,id+"|s",["θ","α","x"] as const),c=N(exactInteger(1));return{stem:`For sin ${s}≠0, simplify (1−cos²${s})/sin²${s}.`,correct:c,wrong:[{value:N(exactInteger(0)),misconceptionId:"ZERO"},{value:N(exactInteger(-1)),misconceptionId:"SIGN"},{value:N(exactInteger(2)),misconceptionId:"TWO"}],explanation:expl("1−cos²θ=sin²θ.",`The expression becomes sin²${s}/sin²${s}=1.`,"The non-zero condition protects the denominator."),state:{symbol:s},verification:nv(c.value,1,"ALGEBRAIC_IDENTITY")}}
 case"TRG-001-QL-077":{const c=N(Q(t.a,t.o));return{stem:`If cosec θ=${t.h}/${t.o} and θ is acute, find cot θ.`,correct:c,wrong:[{value:N(Q(t.o,t.a)),misconceptionId:"RECIPROCAL"},{value:N(Q(t.h,t.o)),misconceptionId:"RETURNED_COSEC"},{value:N(Q(t.a,t.h)),misconceptionId:"USED_COS"}],explanation:expl("cosec²θ−cot²θ=1.",`The triangle is ${t.o}-${t.a}-${t.h}; cot θ=${t.a}/${t.o}.`,"cot is adjacent/opposite."),state:{cosecN:t.h,cosecD:t.o,a:t.a},verification:nv(c.value,Math.sqrt((t.h/t.o)**2-1),"COSEC_COT_IDENTITY")}}
 case"TRG-001-QL-097":{const n=t.o+t.a,d=t.o-t.a,c=N(Q(n,d));return{stem:`If tan θ=${t.o}/${t.a} and θ is acute, find (sin θ+cos θ)/(sin θ−cos θ).`,correct:c,wrong:[{value:N(Q(d,n)),misconceptionId:"INVERTED"},{value:N(Q(n,-d)),misconceptionId:"SIGN"},{value:N(Q(t.o,t.a)),misconceptionId:"RETURNED_TAN"}],explanation:expl("With tanθ=a/b, the common hypotenuse cancels.",`(${t.o}+${t.a})/(${t.o}−${t.a})=${show(c)}.`,"Keep the denominator order sin−cos."),state:{a:t.o,b:t.a,h:t.h},verification:nv(c.value,((t.o/t.h)+(t.a/t.h))/((t.o/t.h)-(t.a/t.h)),"DERIVED_RATIO")}}
 case"TRG-001-QL-098":{const k=pick(seed,id+"|k",[2,3,4,5] as const),c=N(Q(1,k));return{stem:`If sec θ+tan θ=${k}, find sec θ−tan θ.`,correct:c,wrong:[{value:N(exactInteger(k)),misconceptionId:"EQUAL"},{value:N(exactInteger(k*k)),misconceptionId:"SQUARED"},{value:N(Q(1,k*k)),misconceptionId:"RECIPROCAL_SQUARED"}],explanation:expl("(sec+tan)(sec−tan)=1.",`${k}(sec θ−tan θ)=1, so sec θ−tan θ=${show(c)}.`,"Take the reciprocal, not the square."),state:{given:k},verification:nv(c.value,1/k,"CONJUGATE_PRODUCT")}}
 case"TRG-001-QL-099":{const k=pick(seed,id+"|k",[2,3,4,5] as const),c=N(Q(1,k));return{stem:`If cosec θ+cot θ=${k}, find cosec θ−cot θ.`,correct:c,wrong:[{value:N(exactInteger(k)),misconceptionId:"EQUAL"},{value:N(exactInteger(k*k)),misconceptionId:"SQUARED"},{value:N(Q(1,k*k)),misconceptionId:"RECIPROCAL_SQUARED"}],explanation:expl("(cosec+cot)(cosec−cot)=1.",`${k}(cosec θ−cot θ)=1, so cosec θ−cot θ=${show(c)}.`,"Use cosec²−cot²=1."),state:{given:k},verification:nv(c.value,1/k,"CONJUGATE_PRODUCT")}}
 case"TRG-001-QL-100":{const z=pick(seed,id+"|z",[{n:5,d:4},{n:4,d:3},{n:7,d:5}] as const),s=Q(z.n,z.d),sq=assertDefined(powerExact(s,2)),v=subtractExact(sq,exactInteger(1)),c=N(v),half=assertDefined(divideExact(v,exactInteger(2)));return{stem:`If sin θ+cos θ=${z.n}/${z.d}, find 2 sin θ cos θ.`,correct:c,wrong:[{value:N(sq),misconceptionId:"NO_MINUS_ONE"},{value:N(subtractExact(exactInteger(1),sq)),misconceptionId:"SIGN"},{value:N(half),misconceptionId:"HALVED_TARGET"}],explanation:expl("(sin+cos)²=1+2sin cos.",`2sin θcos θ=(${z.n}/${z.d})²−1=${show(c)}.`,"Do not divide by 2 when the target already includes 2."),state:{n:z.n,d:z.d},verification:nv(c.value,(z.n/z.d)**2-1,"SQUARED_SUM")}}
 case"TRG-001-QL-101":{const z=pick(seed,id+"|z",[{a:2,b:3},{a:3,b:4},{a:4,b:5},{a:5,b:2}] as const),c=N(Q(z.b,z.a));return{stem:`If ${z.a} sin θ=${z.b} cos θ and cos θ≠0, find tan θ.`,correct:c,wrong:[{value:N(Q(z.a,z.b)),misconceptionId:"INVERTED"},{value:N(Q(z.b,z.a+z.b)),misconceptionId:"SUM_DENOM"},{value:N(Q(z.a+z.b,z.a)),misconceptionId:"ADDED"}],explanation:expl("Divide by cos θ, then isolate tan θ.",`${z.a}tan θ=${z.b}, so tan θ=${z.b}/${z.a}.`,"The coefficient ratio reverses."),state:{a:z.a,b:z.b},verification:nv(c.value,z.b/z.a,"LINEAR_RELATION")}}
 case"TRG-001-QL-121":{const v=pick(seed,id+"|v",[0,1] as const);if(!v){const e=expr.add(expr.power(expr.trig("SIN",degree(30)),2),expr.multiply(expr.trig("TAN",degree(45)),expr.trig("COS",degree(60))));return expressionSpec("Evaluate exactly: sin²30° + tan45°·cos60°.",e,[{value:N(Q(1,2)),misconceptionId:"DROPPED_TERM"},{value:N(exactInteger(1)),misconceptionId:"IDENTITY"},{value:N(Q(5,4)),misconceptionId:"SIN_NOT_SQUARED"}],expl("Evaluate each component exactly.","sin²30°=1/4 and tan45°·cos60°=1/2; total=3/4.","Square sin30° before adding."),{variant:0})}const e=expr.subtract(expr.multiply(expr.trig("SEC",degree(60)),expr.trig("COS",degree(60))),expr.power(expr.trig("SIN",degree(30)),2));return expressionSpec("Evaluate exactly: sec60°·cos60°−sin²30°.",e,[{value:N(Q(1,4)),misconceptionId:"DROPPED_PRODUCT"},{value:N(exactInteger(1)),misconceptionId:"DROPPED_SUBTRACTION"},{value:N(Q(3,2)),misconceptionId:"RECIPROCAL_ERROR"}],expl("Collapse reciprocal products first.","sec60°·cos60°=1 and sin²30°=1/4; result=3/4.","sec and cos are reciprocals, not equal."),{variant:1})}
 case"TRG-001-QL-122":{const z=pick(seed,id+"|z",[{a:30,b:30},{a:30,b:60},{a:60,b:30}] as const),e=expr.add(expr.multiply(expr.trig("SIN",degree(z.a)),expr.trig("COS",degree(z.b))),expr.multiply(expr.trig("COS",degree(z.a)),expr.trig("SIN",degree(z.b)))),sum=z.a+z.b;return expressionSpec(`Evaluate exactly: sin${z.a}°·cos${z.b}°+cos${z.a}°·sin${z.b}°.`,e,[{value:N(sum===60?Q(1,2):exactSurd(1,3,2)),misconceptionId:"WRONG_SUM_VALUE"},{value:N(sum===60?exactInteger(1):Q(1,2)),misconceptionId:"ONE_COMPONENT"},{value:N(exactSurd(1,3)),misconceptionId:"USED_TAN"}],expl("sinA cosB+cosA sinB=sin(A+B).",`This is sin${sum}°.` ,"The plus form is sine of the sum."),{a:z.a,b:z.b})}
 case"TRG-001-QL-123":{const a=pick(seed,id+"|a",[30,45,60] as const),e=expr.multiply(expr.constant(exactInteger(2)),expr.trig("SIN",degree(a)),expr.trig("COS",degree(a))),ds=a===45?[exactSurd(1,2,2),exactSurd(1,2),exactInteger(2)]:[Q(1,2),exactSurd(1,3),exactInteger(1)];return expressionSpec(`Evaluate exactly: 2 sin ${a}° cos ${a}°.`,e,[{value:N(ds[0]),misconceptionId:"DROPPED_TWO"},{value:N(ds[1]),misconceptionId:"WRONG_VALUE"},{value:N(ds[2]),misconceptionId:"ASSUMED_ONE"}],expl("2sinθcosθ=sin2θ.",`The expression is sin ${2*a}°.` ,"Do not drop the factor 2."),{theta:a})}
 case"TRG-001-QL-124":{const z=pick(seed,id+"|z",[{a:8,b:10,g:30},{a:6,b:8,g:90},{a:4,b:6,g:60}] as const),s=std("SIN",z.g),coef=Q(z.a*z.b,2),area=multiplyExact(coef,s),c=N(area,"SQUARE_UNITS");return{stem:`Two sides of a triangle are ${z.a} and ${z.b} units, with included angle ${z.g}°. Find its area.`,correct:c,wrong:[{value:N(multiplyExact(exactInteger(z.a*z.b),s),"SQUARE_UNITS"),misconceptionId:"DROPPED_HALF"},{value:N(multiplyExact(coef,std("COS",z.g)),"SQUARE_UNITS"),misconceptionId:"USED_COS"},{value:N(multiplyExact(Q(z.a+z.b,2),s),"SQUARE_UNITS"),misconceptionId:"ADDED_SIDES"}],explanation:expl("Area=1/2·ab·sinC.",`Area=1/2×${z.a}×${z.b}×sin${z.g}°=${show(c)}.` ,"Keep the factor 1/2."),state:{a:z.a,b:z.b,angle:z.g},verification:nv(area,.5*z.a*z.b*Math.sin(z.g*Math.PI/180),"TRIANGLE_AREA")}}
 case"TRG-001-QL-125":{const a=pick(seed,id+"|a",[30,45,60] as const),tan=std("TAN",a),cot=std("COT",a),sum=addExact(tan,cot),t2=assertDefined(powerExact(tan,2)),c2=assertDefined(powerExact(cot,2)),e=expr.power(expr.add(expr.trig("TAN",degree(a)),expr.trig("COT",degree(a))),2);return expressionSpec(`Evaluate exactly: (tan ${a}°+cot ${a}°)².`,e,[{value:N(addExact(t2,c2)),misconceptionId:"DROPPED_CROSS_TERM"},{value:N(addExact(addExact(t2,c2),exactInteger(1))),misconceptionId:"ONE_CROSS_TERM"},{value:N(exactInteger(1)),misconceptionId:"USED_PRODUCT_ONLY"}],expl("Square the whole sum; tanθ·cotθ=1.",`tan ${a}°+cot ${a}°=${formatExactPlain(sum)}; now square it.` ,"Do not omit the cross term."),{theta:a})}
 default:throw new Error(`No TRG-001 proof spec for ${id}`)
 }
}

function make(entry:Trg001ProofRegistryEntry,seed:string,s:Spec):Trg001ProofQuestion{
 const raw=[{value:s.correct,isCorrect:true,misconceptionId:null as string|null},...s.wrong.map(x=>({...x,isCorrect:false}))];if(raw.length!==4)throw new Error(`${entry.qlId}: expected 4 options`);if(new Set(raw.map(x=>key(x.value))).size!==4)throw new Error(`${entry.qlId}: equivalent option collision`);
 const options:Trg001ProofOption[]=shuffle(seed+"|"+entry.qlId,raw).map((x,i)=>({label:(["A","B","C","D"] as const)[i],value:x.value,display:show(x.value),isCorrect:x.isCorrect,misconceptionId:x.misconceptionId}));const correctIndex=options.findIndex(x=>x.isCorrect);
 const checks=[{name:"FOUR_OPTIONS",passed:options.length===4,message:"Exactly four options."},{name:"ONE_CORRECT",passed:options.filter(x=>x.isCorrect).length===1,message:"Exactly one correct option."},{name:"UNIQUE_OPTIONS",passed:new Set(options.map(x=>key(x.value))).size===4,message:"Mathematically unique options."},{name:"CORRECT_INDEX",passed:correctIndex>=0,message:"Valid correct index."},{name:"VERIFIED",passed:s.verification.valid,message:"Independent verification passed."},{name:"NO_PLACEHOLDERS",passed:!/[{}]\w+|\{\{/.test(s.stem),message:"No unresolved placeholders."},{name:"ACTIVATION_LOCK",passed:true,message:"Proof remains inactive."}];
 return{packageId:TRG_001_PACKAGE_ID,cpId:entry.cpId,qlId:entry.qlId,solveMode:entry.solveMode,language:"en",seed,difficulty:entry.difficulty,target:entry.target,stem:s.stem,options,correctIndex,answer:show(s.correct),exactAnswer:s.correct,explanation:s.explanation,canonicalState:s.state,verification:s.verification,validation:{valid:checks.every(x=>x.passed),checks},reviewStatus:"UNREVIEWED",questionBankStatus:"NOT_STORED",testEligibility:"INELIGIBLE",publiclyPublishable:false,questionStudioDiscoverable:false,proofOnly:true};
}
export function generateTrg001RuntimeProofQuestion(qlId:string,seed:string){const e=BY_ID.get(qlId);if(!e)throw new Error(`Unknown proof QL ${qlId}`);const q=make(e,seed,buildSpec(qlId,seed));if(!q.validation.valid)throw new Error(`${qlId}: proof validation failed`);return q}
export function generateAllTrg001RuntimeProofQuestions(seed:string){return TRG_001_RUNTIME_PROOF_REGISTRY.map(e=>generateTrg001RuntimeProofQuestion(e.qlId,seed))}
export function proofQuestionFingerprint(q:Trg001ProofQuestion){return[q.qlId,q.seed,q.stem,q.options.map(o=>`${o.label}:${key(o.value)}:${o.isCorrect}`).join("|"),q.correctIndex,key(q.exactAnswer)].join("::")}
