import { INT_CP003_FINAL_REGISTRY, INT_CP003_LEGACY_FAMILIES, INT_CP003_QL_IDS, add, amount, canonical, div, eq, factor, getIntCp003RegistryEntry, hash, integer, mul, pick, pow, rat, stateFor, sub, verify, yearInterest, type AnnualState, type Cp003Difficulty, type Cp003Representation, type Cp003Semantic, type IntCp003QlId, type Rational } from "./cp003-core";
export { INT_CP003_FINAL_REGISTRY, INT_CP003_LEGACY_FAMILIES, INT_CP003_QL_IDS, getIntCp003RegistryEntry, type IntCp003QlId, type Rational } from "./cp003-core";

export interface IntCp003OptionAudit { text:string; value:Rational; misconceptionId:string; explanation:string }
export interface IntCp003Explanation { mainRule:string; workedSteps:readonly string[]; examShortcut:string; verification:string; conclusion:string; trapAnalysis:readonly {optionNumber:number;misconceptionId:string;explanation:string}[] }
export interface IntCp003GeneratedQuestion {
  packageId:"INT-001"; canonicalProblemId:"INT-CP-003"; checkpointId:"INT-CP-003-ANNUAL-COMPOUND-COMPLETION"; qlId:IntCp003QlId; permanentQlId:IntCp003QlId; solveContract:string; seed:string; language:"en"; questionLanguageId:"en-IN";
  answerSemantic:Cp003Semantic; difficulty:Cp003Difficulty; representation:Cp003Representation; stem:string; options:readonly string[]; optionAudit:readonly IntCp003OptionAudit[]; correctIndex:number; solution:Rational; verifierAnswer:Rational; explanation:IntCp003Explanation; mathematicalFingerprint:string; hiddenState:Readonly<Record<string,string|number>>; validation:Readonly<{ok:boolean;errors:readonly string[]}>;
  releaseCandidateId:"INT-CP-003-EN-v1-candidate"; maturity:"FINAL_ENGLISH_REVIEW_CANDIDATE"; reviewStatus:"FINAL_ENGLISH_REVIEW_CANDIDATE"; enabled:false; stagingStatus:"NOT_STAGED"; registrationStatus:"NOT_REGISTERED"; questionStudioDiscoverable:false; questionBankStatus:"NOT_STORED"; testEligibility:"INELIGIBLE"; publiclyPublishable:false;
}
const NAMES=["Aarav","Meera","Kabir","Simran","Rohan","Navya","Arjun","Harleen"] as const;
const ordinal=(n:number)=>`${n}${n%10===1&&n%100!==11?"st":n%10===2&&n%100!==12?"nd":n%10===3&&n%100!==13?"rd":"th"}`;
const abs=(n:bigint)=>n<0n?-n:n;
function digits(n:bigint):string{const s=abs(n).toString(),g=[] as string[];for(let i=s.length;i>0;i-=3)g.unshift(s.slice(Math.max(0,i-3),i));return(n<0n?"-":"")+g.join(",")}
function decimal(x:Rational,places=6):string{if(x.denominator===1n)return x.numerator.toString();let r=abs(x.numerator)%x.denominator,d="",i=0;while(r&&i++<places){r*=10n;d+=(r/x.denominator).toString();r%=x.denominator}return r?`${x.numerator}/${x.denominator}`:`${x.numerator<0n?"-":""}${abs(x.numerator)/x.denominator}.${d}`}
const money=(x:Rational)=>x.denominator===1n?`₹${digits(x.numerator)}`:`₹${decimal(x,4)}`;
const answer=(s:Cp003Semantic,x:Rational)=>s==="RATE_PERCENT"?`${decimal(x,2)}%`:s==="TIME_YEARS"?`${decimal(x,0)} year${integer(x)===1?"":"s"}`:money(x);
function round(x:Rational,places:number):Rational{const scale=10n**BigInt(places),n=abs(x.numerator)*scale,q=n/x.denominator+(n%x.denominator*2n>=x.denominator?1n:0n);return rat(x.numerator<0n?-q:q,scale)}
const normalize=(s:Cp003Semantic,x:Rational)=>s==="RATE_PERCENT"?round(x,2):round(x,0);
const simpleAmount=(s:AnnualState)=>mul(s.principal,add(rat(1),div(mul(s.ratePercent,rat(s.years)),rat(100))));

function wrongs(id:IntCp003QlId,s:AnnualState,correct:Rational){
  const sem=getIntCp003RegistryEntry(id).answerSemantic,f=factor(s.ratePercent),A=amount(s.principal,s.ratePercent,s.years),I=sub(A,s.principal),J=yearInterest(s.principal,s.ratePercent,s.specifiedYear),O=amount(s.principal,s.ratePercent,s.observationYear),N=amount(s.principal,s.ratePercent,s.observationYear+1),D=sub(N,O),out:{value:Rational;id:string;explanation:string}[]=[];
  const push=(raw:Rational,id2:string,explanation:string)=>{const v=normalize(sem,raw);if(v.numerator<=0n||eq(v,correct)||verify(id,s,v)||out.some(x=>eq(x.value,v)))return;out.push({value:v,id:id2,explanation:!eq(v,raw)?`${explanation} The displayed option is the rounded result of that mistaken calculation.`:explanation})};
  switch(id){
    case"INT-QL-053":push(I,"RETURN_INTEREST","Returns interest, not amount.");push(simpleAmount(s),"USE_SI","Uses simple instead of compound interest.");push(mul(s.principal,f),"ONE_YEAR","Compounds for one year only.");break;
    case"INT-QL-054":push(A,"RETURN_AMOUNT","Returns amount, not interest.");push(sub(simpleAmount(s),s.principal),"USE_SI","Uses simple interest.");push(yearInterest(s.principal,s.ratePercent,1),"FIRST_YEAR_ONLY","Returns first-year interest only.");break;
    case"INT-QL-055":push(A,"COPY_AMOUNT","Copies the amount.");push(div(A,add(rat(1),div(mul(s.ratePercent,rat(s.years)),rat(100)))),"REVERSE_SI","Reverses a simple-interest amount.");push(div(A,pow(f,Math.max(1,s.years-1))),"ONE_FEWER_YEAR","Reverses one fewer year.");break;
    case"INT-QL-056":push(I,"COPY_INTEREST","Copies the interest.");push(div(I,div(mul(s.ratePercent,rat(s.years)),rat(100))),"SI_INVERSE","Uses the simple-interest inverse.");push(div(I,sub(f,rat(1))),"ONE_YEAR","Assumes one year.");break;
    case"INT-QL-057":{const g=sub(div(A,s.principal),rat(1));push(div(mul(g,rat(100)),rat(s.years)),"SIMPLE_RATE","Divides total growth equally across years.");push(mul(g,rat(100)),"TOTAL_GROWTH","Returns total growth percent.");push(add(s.ratePercent,rat(5)),"NEARBY_RATE","Chooses a nearby unverified rate.");break}
    case"INT-QL-058":{const g=sub(div(A,s.principal),rat(1));push(div(mul(g,rat(100)),s.ratePercent),"SIMPLE_TIME","Uses linear growth.");push(rat(Math.max(1,s.years-1)),"ONE_FEWER_YEAR","Stops one year early.");push(rat(s.years+1),"ONE_EXTRA_YEAR","Adds one year.");break}
    case"INT-QL-059":push(yearInterest(s.principal,s.ratePercent,1),"FIRST_YEAR","Uses first-year interest.");push(yearInterest(s.principal,s.ratePercent,Math.max(1,s.specifiedYear-1)),"PREVIOUS_YEAR","Uses previous-year interest.");push(sub(amount(s.principal,s.ratePercent,s.specifiedYear),s.principal),"CUMULATIVE","Returns cumulative interest.");break;
    case"INT-QL-060":push(div(J,div(s.ratePercent,rat(100))),"FIRST_YEAR_INVERSE","Treats the observed interest as first-year interest.");push(div(J,mul(div(s.ratePercent,rat(100)),pow(f,s.specifiedYear))),"EXTRA_FACTOR","Reverses one extra factor.");push(div(J,mul(div(s.ratePercent,rat(100)),rat(s.specifiedYear))),"SIMPLE_MULTIPLIER","Uses a simple year multiplier.");break;
    case"INT-QL-061":push(mul(div(J,s.principal),rat(100)),"FIRST_YEAR_RATE","Treats it as first-year interest.");push(rat(Math.max(1,(integer(s.ratePercent)??10)-5)),"LOW_RATE","Chooses a nearby low rate.");push(add(s.ratePercent,rat(5)),"HIGH_RATE","Chooses a nearby high rate.");break;
    case"INT-QL-062":push(O,"COPY_LATER","Copies the later balance.");push(mul(O,sub(rat(1),div(s.ratePercent,rat(100)))),"SUBTRACT_RATE","Subtracts the rate instead of dividing by the factor.");push(div(O,sub(rat(1),div(s.ratePercent,rat(100)))),"DECAY_INVERSE","Uses a decay inverse.");break;
    case"INT-QL-063":push(mul(div(D,N),rat(100)),"LATER_BASE","Divides by the closing balance.");push(mul(div(sub(N,s.principal),s.principal),rat(100)),"CUMULATIVE_RATE","Uses cumulative growth.");push(add(s.ratePercent,rat(5)),"NEARBY_RATE","Uses a nearby rate.");break;
    case"INT-QL-064":push(O,"COPY_OBSERVATION","Returns the observed balance.");push(div(O,pow(f,s.observationYear+1)),"EXTRA_YEAR","Reverses one extra year.");push(div(N,pow(f,s.observationYear)),"FEWER_YEAR","Reverses one fewer year.");break;
    case"INT-QL-065":push(sub(amount(s.principal,s.ratePercent,s.laterYear),s.principal),"LATER_CI","Returns later cumulative interest.");push(sub(amount(s.principal,s.ratePercent,s.earlierYear),s.principal),"EARLIER_CI","Returns earlier cumulative interest.");push(mul(s.principal,div(mul(s.ratePercent,rat(s.laterYear)),rat(100))),"SI_TO_LATER","Uses simple interest to the later date.");break;
    case"INT-QL-066":{const E=yearInterest(s.principal,s.ratePercent,s.earlierYear);push(E,"CONSTANT_INTEREST","Keeps yearly interest constant.");push(sub(correct,E),"INCREASE_ONLY","Returns only the increase.");push(mul(E,pow(f,s.laterYear-s.earlierYear+1)),"EXTRA_GAP","Uses one extra growth factor.");break}
  }
  let i=1n;while(out.length<3)push(add(correct,rat(i++)),"OFFSET","A nearby value that fails the recurrence.");return out.slice(0,3);
}

function stem(id:IntCp003QlId,s:AnnualState,seed:string):string{
  const name=pick(NAMES,seed,`${id}:name`),P=money(s.principal),r=answer("RATE_PERCENT",s.ratePercent),A=amount(s.principal,s.ratePercent,s.years),I=sub(A,s.principal),J=yearInterest(s.principal,s.ratePercent,s.specifiedYear),O=amount(s.principal,s.ratePercent,s.observationYear),N=amount(s.principal,s.ratePercent,s.observationYear+1),EA=amount(s.principal,s.ratePercent,s.earlierYear),LA=amount(s.principal,s.ratePercent,s.laterYear),EJ=yearInterest(s.principal,s.ratePercent,s.earlierYear),F=pow(factor(s.ratePercent),s.years);
  switch(id){
    case"INT-QL-053":return `${name} invests ${P} at ${r} per annum, compounded annually, for ${s.years} complete years. Find the maturity amount.`;
    case"INT-QL-054":return `${P} is invested at ${r} per annum, compounded annually, for ${s.years} complete years. Find the compound interest.`;
    case"INT-QL-055":return `A sum amounts to ${money(A)} in ${s.years} complete years at ${r} per annum, compounded annually. Find the principal.`;
    case"INT-QL-056":return `The compound interest for ${s.years} complete years at ${r} per annum is ${money(I)}. Find the principal.`;
    case"INT-QL-057":return s.useGrowthFactorEvidence?`The amount becomes ${decimal(F)} times the principal in ${s.years} complete years under annual compounding. Find the rate.`:`A principal of ${P} grows to ${money(A)} in ${s.years} complete years under annual compounding. Find the rate.`;
    case"INT-QL-058":return `${name} invests ${P} at ${r} per annum, compounded annually. It becomes ${money(A)}. After how many complete years?`;
    case"INT-QL-059":return `${P} is invested at ${r} per annum, compounded annually. Find the interest earned during the ${ordinal(s.specifiedYear)} year alone.`;
    case"INT-QL-060":return `At ${r} per annum compounded annually, the interest earned during the ${ordinal(s.specifiedYear)} year is ${money(J)}. Find the principal.`;
    case"INT-QL-061":return `On a principal of ${P}, the interest earned during the ${ordinal(s.specifiedYear)} year is ${money(J)}. Find the annual compound rate.`;
    case"INT-QL-062":return `At ${r} per annum compounded annually, the balance at the end of year ${s.observationYear} is ${money(O)}. Find the balance one year earlier.`;
    case"INT-QL-063":return `A compound account shows ${money(O)} at the end of year ${s.observationYear} and ${money(N)} at the end of year ${s.observationYear+1}. Find the annual rate.`;
    case"INT-QL-064":return `A sum grows to ${money(O)} after ${s.observationYear} year${s.observationYear===1?"":"s"} and ${money(N)} after ${s.observationYear+1} years at one annual compound rate. Find the principal.`;
    case"INT-QL-065":return `${P} is compounded annually at ${r}. The amounts after ${s.earlierYear} and ${s.laterYear} years are ${money(EA)} and ${money(LA)}. Find their difference.`;
    case"INT-QL-066":return `At ${r} annual compounding, the interest during the ${ordinal(s.earlierYear)} year is ${money(EJ)}. Find the interest during the ${ordinal(s.laterYear)} year.`;
  }
}

function explanation(id:IntCp003QlId,s:AnnualState,sol:Rational,audit:readonly IntCp003OptionAudit[],correctIndex:number):IntCp003Explanation{
  const f=factor(s.ratePercent),A=amount(s.principal,s.ratePercent,s.years),O=amount(s.principal,s.ratePercent,s.observationYear),N=amount(s.principal,s.ratePercent,s.observationYear+1),E=yearInterest(s.principal,s.ratePercent,s.earlierYear); let rule="For annual compounding, multiply the opening balance by (1 + r/100) once per complete year.", shortcut="Use exact annual factors and cancel before multiplying.", steps:string[]=[];
  switch(id){
    case"INT-QL-053":steps=[`Annual factor = ${decimal(f)}.`,`Complete periods = ${s.years}.`,`Amount = ${money(s.principal)} × (${decimal(f)})^${s.years}.`,`Amount = ${money(sol)}.`];break;
    case"INT-QL-054":steps=[`Annual factor = ${decimal(f)}.`,`Amount = ${money(s.principal)} × (${decimal(f)})^${s.years} = ${money(A)}.`,`CI = amount − principal.`,`${money(A)} − ${money(s.principal)} = ${money(sol)}.`];break;
    case"INT-QL-055":steps=[`Growth factor = (${decimal(f)})^${s.years}.`,`P = A ÷ growth factor.`,`P = ${money(A)} ÷ (${decimal(f)})^${s.years}.`,`P = ${money(sol)}.`];break;
    case"INT-QL-056":steps=[`CI = P[(${decimal(f)})^${s.years} − 1].`,`Use the exact CI factor.`,`P = given CI ÷ CI factor.`,`P = ${money(sol)}.`];break;
    case"INT-QL-057":rule="Match A/P = (1 + r/100)^n by bounded exact factor search.";shortcut="Do not use a rounded floating root.";steps=[`Observed factor = ${decimal(div(A,s.principal))}.`,`Periods = ${s.years}.`,`Exact annual factor = ${decimal(f)}.`,`Rate = ${answer("RATE_PERCENT",sol)}.`];break;
    case"INT-QL-058":rule="Match repeated exact annual factors by bounded period search.";shortcut="Build a short factor ladder instead of using logarithms.";steps=[`Annual factor = ${decimal(f)}.`,`Observed factor = ${decimal(div(A,s.principal))}.`,`The exact factor appears after ${s.years} periods.`,`Time = ${answer("TIME_YEARS",sol)}.`];break;
    case"INT-QL-059":steps=[`Opening balance of year ${s.specifiedYear} = P × (${decimal(f)})^${s.specifiedYear-1}.`,`Opening balance = ${money(amount(s.principal,s.ratePercent,s.specifiedYear-1))}.`,`Year interest = opening balance × ${decimal(s.ratePercent)}/100.`,`Interest = ${money(sol)}.`];break;
    case"INT-QL-060":steps=[`Jk = P(r/100)(${decimal(f)})^${s.specifiedYear-1}.`,`The yearly-interest factor is exact.`,`Divide the shown interest by that factor.`,`P = ${money(sol)}.`];break;
    case"INT-QL-061":rule="Match Jk = P(r/100)(1 + r/100)^(k−1) by exact bounded rate substitution.";steps=[`Principal = ${money(s.principal)}.`,`Specified year = ${s.specifiedYear}.`,`Only ${answer("RATE_PERCENT",sol)} reproduces the shown interest.`,`Direct substitution verifies the answer.`];break;
    case"INT-QL-062":steps=[`Later balance = previous balance × ${decimal(f)}.`,`Previous balance = later balance ÷ ${decimal(f)}.`,`${money(O)} ÷ ${decimal(f)} = ${money(sol)}.`,`Multiplication returns ${money(O)}.`];break;
    case"INT-QL-063":steps=[`One-year interest = ${money(N)} − ${money(O)}.`,`Rate = interest ÷ opening balance × 100.`,`Use ${money(O)} as that year's opening balance.`,`Rate = ${answer("RATE_PERCENT",sol)}.`];break;
    case"INT-QL-064":steps=[`Consecutive factor = ${money(N)} ÷ ${money(O)} = ${decimal(f)}.`,`Reverse ${s.observationYear} complete period${s.observationYear===1?"":"s"}.`,`P = ${money(O)} ÷ (${decimal(f)})^${s.observationYear}.`,`P = ${money(sol)}.`];break;
    case"INT-QL-065":steps=[`Earlier amount = ${money(amount(s.principal,s.ratePercent,s.earlierYear))}.`,`Later amount = ${money(amount(s.principal,s.ratePercent,s.laterYear))}.`,`Difference = later − earlier.`,`Difference = ${money(sol)}.`];break;
    case"INT-QL-066":shortcut="Successive yearly interests form a GP with ratio 1 + r/100.";steps=[`Annual factor = ${decimal(f)}.`,`Year gap = ${s.laterYear-s.earlierYear}.`,`Later interest = ${money(E)} × (${decimal(f)})^${s.laterYear-s.earlierYear}.`,`Later interest = ${money(sol)}.`];break;
  }
  const trapAnalysis=audit.map((x,i)=>({x,i})).filter(x=>x.i!==correctIndex).map(({x,i})=>Object.freeze({optionNumber:i+1,misconceptionId:x.misconceptionId,explanation:x.explanation}));
  return Object.freeze({mainRule:rule,workedSteps:Object.freeze(steps),examShortcut:shortcut,verification:"Rebuild the annual balance year by year and confirm the requested value.",conclusion:`Therefore the answer is ${answer(getIntCp003RegistryEntry(id).answerSemantic,sol)}.`,trapAnalysis:Object.freeze(trapAnalysis)});
}
function difficulty(id:IntCp003QlId,s:AnnualState):Cp003Difficulty{if(id==="INT-QL-053"||id==="INT-QL-054")return s.years===2&&(integer(s.ratePercent)??99)<=20?"Easy":"Medium";return ["INT-QL-057","INT-QL-058","INT-QL-061","INT-QL-063","INT-QL-064"].includes(id)||s.laterYear>=4||s.specifiedYear>=4?"Hard":"Medium"}
function deep<T>(v:T):T{if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const x of Object.values(v as Record<string,unknown>))deep(x);Object.freeze(v)}return v}
export function generateIntCp003Question(id:IntCp003QlId,seed="int-cp003-default"):IntCp003GeneratedQuestion{
  const reg=getIntCp003RegistryEntry(id),s=stateFor(id,seed),sol=canonical(id,s),bad=wrongs(id,s,sol),correct:IntCp003OptionAudit=Object.freeze({text:answer(reg.answerSemantic,sol),value:sol,misconceptionId:"CORRECT",explanation:"Satisfies the complete annual-compounding state."}),wrong=bad.map(x=>Object.freeze({text:answer(reg.answerSemantic,x.value),value:x.value,misconceptionId:x.id,explanation:x.explanation})),correctIndex=hash(`${id}:${seed}:pos`)%4,audit:IntCp003OptionAudit[]=[];let j=0;for(let i=0;i<4;i++)audit.push(i===correctIndex?correct:wrong[j++]!);const options=audit.map(x=>x.text),errors:string[]=[];if(new Set(options).size!==4)errors.push("options");const accepted=audit.map(x=>verify(id,s,x.value));if(accepted.filter(Boolean).length!==1||!accepted[correctIndex])errors.push("verifier");const exp=explanation(id,s,sol,audit,correctIndex),q:IntCp003GeneratedQuestion={packageId:"INT-001",canonicalProblemId:"INT-CP-003",checkpointId:"INT-CP-003-ANNUAL-COMPOUND-COMPLETION",qlId:id,permanentQlId:id,solveContract:reg.solveContract,seed,language:"en",questionLanguageId:"en-IN",answerSemantic:reg.answerSemantic,difficulty:difficulty(id,s),representation:s.representation,stem:stem(id,s,seed),options:Object.freeze(options),optionAudit:Object.freeze(audit),correctIndex,solution:sol,verifierAnswer:canonical(id,s),explanation:exp,mathematicalFingerprint:[id,s.principal.numerator,s.ratePercent.numerator,s.years,s.specifiedYear,s.earlierYear,s.laterYear,s.observationYear,sol.numerator].join("|"),hiddenState:Object.freeze({principal:`${s.principal.numerator}/${s.principal.denominator}`,ratePercent:`${s.ratePercent.numerator}/${s.ratePercent.denominator}`,years:s.years,specifiedYear:s.specifiedYear,earlierYear:s.earlierYear,laterYear:s.laterYear,observationYear:s.observationYear}),validation:Object.freeze({ok:errors.length===0,errors:Object.freeze(errors)}),releaseCandidateId:"INT-CP-003-EN-v1-candidate",maturity:"FINAL_ENGLISH_REVIEW_CANDIDATE",reviewStatus:"FINAL_ENGLISH_REVIEW_CANDIDATE",enabled:false,stagingStatus:"NOT_STAGED",registrationStatus:"NOT_REGISTERED",questionStudioDiscoverable:false,questionBankStatus:"NOT_STORED",testEligibility:"INELIGIBLE",publiclyPublishable:false};return deep(q)}
export const verifyIntCp003Option=(id:IntCp003QlId,seed:string,c:Rational)=>verify(id,stateFor(id,seed),c);
