import fs from "node:fs";
import path from "node:path";
import { INT_CP007_LOCALIZED_VERSION, generateIntCp007LocalizedReviewQuestion } from "./cp007-scheme-equivalence-localized-v4";
import { INT_CP007_QL_IDS } from "./cp007-scheme-equivalence-runtime-v3-final";
function surface(q:any):string{return JSON.stringify({stem:q.presentation.markdown,answer:q.correctAnswer,explanation:q.explanation});}
function render(q:any):string{const l:string[]=[];l.push(`**Question:** ${q.presentation.markdown}`,"","**Options:**");q.options.forEach((o:any,i:number)=>l.push(`${String.fromCharCode(65+i)}. ${o.text}${i===q.correctIndex?" **✓**":""}`));l.push("",`**Correct answer:** ${q.correctAnswer}`,"",`**Approach:** ${q.explanation.keyIdea}`,"","**Calculation:**");q.explanation.steps.forEach((s:string,i:number)=>l.push(`${i+1}. ${s}`));l.push("",`**Final answer:** ${q.explanation.finalAnswer}`,"",`**Common mistake:** ${q.explanation.commonMistake}`);return l.join("\n");}
const out:string[]=["# INT-CP-007 — Hindi/Punjabi Final-Language Review V4","",`Localized candidate: **${INT_CP007_LOCALIZED_VERSION}**`,"","Source authority: **INT-CP-007-EN-v8-frozen**.","","Punjabi Compound Interest authority: **ਮਿਸ਼ਰਤ ਵਿਆਜ**.","","Status: **MULTILINGUAL PRODUCT REVIEW ONLY**. Delivery remains closed.",""];
let matchedSeeds=0,localizedQuestions=0;
for(const qlId of INT_CP007_QL_IDS){const selected:string[]=[],seen=new Set<string>(),families=new Set<string>();for(let i=0;i<400&&selected.length<4;i++){const seed=`int-cp007-localized-v4-review-${qlId}-${i}`;const hi=generateIntCp007LocalizedReviewQuestion(qlId,seed,"hi-IN") as any;const key=surface(hi);if(seen.has(key))continue;const fam=hi.presentation.stemFamilyId as string;if(selected.length<3&&families.has(fam))continue;selected.push(seed);seen.add(key);families.add(fam);}if(selected.length!==4||families.size<3)throw new Error(`${qlId}: failed to select four meaningful V4 surfaces`);out.push(`## ${qlId}`,"");selected.forEach((seed,idx)=>{const hi=generateIntCp007LocalizedReviewQuestion(qlId,seed,"hi-IN") as any;const pa=generateIntCp007LocalizedReviewQuestion(qlId,seed,"pa-IN") as any;out.push(`### Review ${idx+1} — ${hi.presentation.stemFamilyId} — seed \`${seed}\``,"","#### Hindi","",render(hi),"","#### Punjabi","",render(pa),"");matchedSeeds++;localizedQuestions+=2;});}
const dest=path.resolve("dist/quant-v4/INT-CP-007-HI-PA-V4-FINAL-LANGUAGE-REVIEW.md");fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,`${out.join("\n")}\n`,"utf8");console.log(JSON.stringify({output:dest,qls:INT_CP007_QL_IDS.length,matchedSeeds,localizedQuestions},null,2));console.log("PASS_INT_CP007_LOCALIZED_V4_REVIEW_EXPORT");
