export const PART_1 = [
[1,"Easy","Quicklime is the common name of:","calcium oxide",["calcium hydroxide","calcium carbonate","calcium chloride"],"Quicklime is calcium oxide, CaO. It is produced by strongly heating limestone so that carbon dioxide is removed. Adding water to it produces calcium hydroxide and releases considerable heat.",["sci018-v2-quicklime"]],
[1,"Easy","Slaked lime is chemically:","calcium hydroxide",["calcium oxide","calcium carbonate","sodium hydroxide"],"Slaked lime is calcium hydroxide, Ca(OH)₂. It forms when water is added to quicklime. It is used in whitewashing, soil treatment and several construction-related applications.",["sci018-v2-slaked-lime"]],
[1,"Easy","Limestone consists largely of:","calcium carbonate",["calcium oxide","sodium carbonate","magnesium sulphate"],"Limestone is largely calcium carbonate, CaCO₃. Chalk and marble are also largely forms of calcium carbonate. Heating limestone strongly produces quicklime and carbon dioxide.",["sci018-v2-limestone"]],
[1,"Easy","Caustic soda is the common name of:","sodium hydroxide",["potassium hydroxide","sodium carbonate","calcium hydroxide"],"Caustic soda is sodium hydroxide, NaOH. It is a strong alkali used in several industrial processes. Its strong basic nature makes careful handling necessary.",["sci018-v2-caustic-soda"]],
[1,"Easy","Caustic potash is:","potassium hydroxide",["sodium hydroxide","potassium nitrate","calcium oxide"],"Caustic potash is the common name for potassium hydroxide, KOH, a strong alkali. Like sodium hydroxide, it dissociates strongly in water and produces hydroxide ions.",["sci018-v2-caustic-potash"]],
[1,"Easy","Soda ash is commonly identified as:","anhydrous sodium carbonate",["sodium hydrogen carbonate","sodium chloride","calcium carbonate"],"Soda ash is anhydrous sodium carbonate, Na₂CO₃. Washing soda is its hydrated form with water of crystallization. The absence of crystal water distinguishes soda ash from washing soda.",["sci018-v2-soda-ash"]],
[2,"Easy","CNG consists largely of:","methane",["propane only","carbon dioxide only","acetylene"],"Compressed natural gas is largely methane. It is stored at high pressure and used as a relatively clean-burning fuel. Its high methane content gives efficient combustion with relatively low particulate pollution.",["sci018-v2-cng"]],
[2,"Easy","Domestic LPG contains:","propane and butane",["methane only","hydrogen and oxygen","carbon dioxide and nitrogen"],"Liquefied petroleum gas used domestically is a mixture of propane and butane, stored as a liquid under pressure. Pressure keeps these hydrocarbons liquefied inside the cylinder until they are released.",["sci018-v2-lpg"]],
[2,"Easy","Biogas contains a large proportion of:","methane",["oxygen","chlorine","sulphur dioxide"],"Biogas is produced by anaerobic decomposition of organic matter and contains a large proportion of methane along with carbon dioxide and small amounts of other gases.",["sci018-v2-biogas"]],
[2,"Easy","Acetylene is commonly used with oxygen for:","welding and cutting metals",["softening hard water","fertilizing crops","making glass transparent"],"Acetylene burns with a very hot flame in oxygen. Oxy-acetylene flames are therefore used for welding and cutting metals. Its high flame temperature makes it suitable for joining or cutting metal workpieces.",["sci018-v2-acetylene"]],
[2,"Easy","Carbon dioxide is used in many fire extinguishers because it:","does not support combustion and can displace air around the flame",["burns more strongly than fuel","is a strong metal","produces sparks"],"Carbon dioxide is non-combustible and can reduce the oxygen available around a fire. It also leaves no solid residue. It is especially useful where a clean extinguishing agent is preferred.",["sci018-v2-co2-extinguisher"]],
[2,"Easy","Which gas directly supports combustion but is itself not a fuel?","oxygen",["carbon dioxide","nitrogen","argon"],"Oxygen supports the oxidation reactions involved in burning. It is not itself the fuel being consumed. It helps fuels burn by accepting electrons during oxidation reactions.",["sci018-v2-oxygen"]],
[3,"Easy","In NPK fertilizer, the letter K represents:","potassium",["krypton","calcium","carbon"],"NPK stands for nitrogen, phosphorus and potassium. K is the chemical symbol for potassium. The three letters identify the primary fertilizer nutrients nitrogen, phosphorus and potassium.",["sci018-v2-npk"]],
[3,"Easy","Urea is used as a fertilizer to supply:","nitrogen",["phosphorus","potassium","calcium only"],"Urea has a high nitrogen content and is widely used as a nitrogen fertilizer. Plants use nitrogen to make amino acids, proteins and chlorophyll-containing tissues.",["sci018-v2-urea"]],
[3,"Easy","Superphosphate fertilizers supply:","phosphorus",["nitrogen","potassium","sodium"],"Superphosphate contains plant-available phosphate compounds and is used to supply phosphorus. Phosphorus is important for root development and energy-transfer compounds in plants.",["sci018-v2-superphosphate"]]
] as const;
