export const PART_3 = [
[6,"Medium","Sodium benzoate is commonly used in foods as a:","preservative",["fertilizer","fuel","bleaching metal"],"Sodium benzoate slows the growth of many microorganisms in suitable foods and drinks, helping extend shelf life. It works particularly well in acidic foods where its antimicrobial action is stronger.",["sci018-v2-sodium-benzoate"]],
[6,"Medium","Sodium metabisulphite is commonly used in food processing as a:","preservative and antioxidant",["fertilizer supplying potassium","glass former","fuel gas"],"Sodium metabisulphite can inhibit microbial growth and also help reduce oxidation in suitable foods and beverages. Its preservative action must be controlled because sulphites can affect sensitive individuals.",["sci018-v2-metabisulphite"]],
[6,"Medium","Common salt helps preserve pickles and other foods because it:","reduces water available for microbial growth",["adds oxygen to the food","makes every food strongly basic","converts food into metal"],"A high salt concentration lowers available water and draws water from many microbial cells. This slows the growth of spoilage organisms.",["sci018-v2-salt-preservation"]],
[6,"Medium","Sugar helps preserve jams and jellies by:","lowering available water for microorganisms",["producing chlorine gas","raising the food temperature permanently","removing all carbon"],"High sugar concentration binds water and creates conditions in which many microorganisms grow poorly. Reducing available water makes the environment less suitable for microbial growth.",["sci018-v2-sugar-preservation"]],
[6,"Medium","Antioxidants added to food help by:","slowing oxidation",["increasing rusting","producing more oxidizing radicals","making all food alkaline"],"Oxidation can spoil fats, flavours and colours. Antioxidants slow these reactions and therefore help protect the food. They delay rancidity and other oxidative changes rather than killing all microorganisms.",["sci018-v2-antioxidants"]],
[6,"Medium","Citric acid is naturally abundant in:","citrus fruits",["limestone","iron nails","common salt crystals"],"Lemons, oranges and other citrus fruits contain citric acid, which contributes to their sour taste. It is also widely used as an acidulant and flavouring ingredient in foods and drinks.",["sci018-v2-citric-acid"]],
[7,"Medium","Temporary hardness of water is caused by bicarbonates of calcium and:","magnesium",["sodium","potassium","silver"],"Temporary hardness is due to dissolved calcium and magnesium bicarbonates. Much of it can be removed by boiling. Heating converts these bicarbonates into less soluble compounds that can be removed.",["sci018-v2-temporary-hardness"]],
[7,"Medium","Permanent hardness is commonly caused by sulphates and chlorides of calcium and:","magnesium",["sodium","potassium","hydrogen"],"Calcium and magnesium sulphates or chlorides cause permanent hardness. This hardness is not removed simply by boiling. Chemical softening or ion-exchange methods are needed because boiling is ineffective.",["sci018-v2-permanent-hardness"]],
[7,"Medium","Which simple treatment can remove much of temporary hardness?","boiling",["adding common salt","cooling only","passing nitrogen gas"],"Boiling decomposes bicarbonates and leads to insoluble deposits, removing much of temporary hardness. The insoluble products can then separate from the water as deposits.",["sci018-v2-boiling-hardness"]],
[7,"Medium","Alum helps clarify muddy water by promoting:","coagulation and floc formation",["formation of methane","increase of permanent hardness","polymerization of water"],"Alum helps very fine suspended particles join into larger flocs. These settle more easily or can be removed by filtration.",["sci018-v2-alum"]],
[7,"Medium","Chlorination of drinking water is used for:","disinfection",["increasing hardness","removing every dissolved salt","producing fertilizer"],"Chlorine or chlorine-releasing compounds kill many disease-causing microorganisms. Correct dosing is important for safe treatment. Disinfection reduces pathogens but does not by itself remove all dissolved chemical impurities.",["sci018-v2-chlorination"]],
[7,"Medium","Activated charcoal in a water filter is useful because it:","adsorbs many dissolved organic substances and odours",["produces oxygen from water","increases hardness","forms calcium carbonate crystals"],"Activated charcoal has a very large surface area. Many molecules stick to its surface by adsorption, helping reduce odours and some impurities.",["sci018-v2-activated-charcoal"]],
[8,"Medium","Vulcanization strengthens natural rubber by heating it with:","sulphur",["sodium chloride","calcium carbonate","nitrogen gas"],"Sulphur forms cross-links between rubber chains during vulcanization. This improves strength, elasticity and temperature behaviour. The sulphur cross-links stop the polymer chains from sliding too freely past one another.",["sci018-v2-vulcanization"]],
[8,"Medium","The main raw material in ordinary glass is:","silica",["urea","methane","sodium chloride only"],"Ordinary glass is made largely from silica, usually obtained from sand, together with materials such as soda ash and limestone.",["sci018-v2-glass-silica"]],
[8,"Medium","Gypsum is added during cement manufacture to:","control the setting time",["make cement a fuel","supply methane","remove all calcium"],"A small amount of gypsum is added to cement clinker to slow and control setting, preventing the cement from setting too rapidly.",["sci018-v2-cement-gypsum"]]
] as const;
