export const HIS_CP009_EXPLANATION_OVERRIDES_V1:Readonly<Record<number,string>>={
1:"Alauddin Hasan Bahman Shah founded the Bahmani Sultanate in 1347 after Deccan officers broke away from Delhi rule. His accession marks the beginning of an independent Deccan sultanate centred first at Gulbarga.",
2:"Gulbarga was the first capital of the Bahmani Sultanate. It should be distinguished from later centres such as Bidar and from Vijayanagara across the Deccan political frontier.",
3:"Bahmani provinces were called tarafs. The term refers to a territorial administrative division and is different from Delhi Sultanate units such as iqtas or shiqs.",
4:"A Bahmani province or taraf was governed by a tarafdar, also called a subedar. The office combined provincial authority with military responsibilities under the central state.",
5:"Khalisa land remained under direct royal control and its revenue supported the ruler and royal household. It therefore differed from territories placed under provincial officers or military commanders.",
6:"Dabhol gave the Bahmani state access to an important west-coast port. Control of such ports mattered because overseas trade and imported war horses had both economic and military value.",
7:"Mahmud Gawan was Iranian by birth and first came to the Deccan as a trader. His rise from merchant background to leading Bahmani administrator is one of the notable features of his career.",
8:"Mahmud Gawan received the title Malik-ut-Tujjar, meaning Chief of the Merchants. The title reflects his commercial background before he became one of the most powerful officials in the Bahmani state.",
9:"Mahmud Gawan became wazir and emerged as the leading administrator of the Bahmani Sultanate. His reforms tried to strengthen central control over powerful provincial officers.",
10:"Gawan reduced tarafdar military power by placing most provincial forts under centrally appointed qiladars. The reform limited the ability of provincial governors to control both territory and fortifications independently.",
11:"Under Mahmud Gawan, Bahmani forces gained Goa and Dabhol. These acquisitions strengthened access to western maritime trade and improved control over routes connected with overseas commerce.",
12:"Rivalry between Deccani nobles and Afaquis weakened the Bahmani state, and the kingdom later broke into several successor Sultanates. Internal factional conflict therefore combined with political fragmentation in the later phase.",
13:"Harihara and Bukka are associated with the foundation of Vijayanagara in the fourteenth century. Their dynasty established a major southern empire that became a central power in Deccan politics.",
14:"The Vijayanagara capital stood on the banks of the Tungabhadra River. The river and surrounding rocky landscape shaped both the city's geography and its defensive setting.",
15:"The Sangama dynasty was the first ruling house of Vijayanagara. It was later replaced by the Saluvas, followed by the Tuluvas and then the Aravidu line.",
16:"The Saluva dynasty replaced the Sangamas in the late fifteenth century. This transition was one stage in the sequence of ruling houses before the rise of the Tuluvas.",
17:"Krishnadeva Raya belonged to the Tuluva dynasty, which succeeded the Saluvas. His reign became the best-known phase of Vijayanagara power in the early sixteenth century.",
18:"Domingo Paes was one of several travellers who left accounts of Vijayanagara, along with Abdur Razzaq and Nicolo Conti. Such accounts provide outside descriptions of the capital and imperial society.",
19:"Krishnadeva Raya was a Tuluva ruler whose reign saw major success in the Raichur region and against Orissa and Bijapur. These victories explain why his reign is often associated with the height of Vijayanagara power.",
20:"Krishnadeva Raya composed the Telugu work Amuktamalyada. The ruler-work-language association is important because it shows royal participation in regional literary and political thought.",
21:"Krishnadeva Raya's reign included acquisition of the Raichur doab, victories against Orissa and a major defeat of Bijapur. The record combines expansion in both the eastern and western Deccan theatres.",
22:"Krishnadeva Raya is associated with both Amuktamalyada and the foundation of Nagalapuram near Vijayanagara. One reflects literary patronage, while the other shows royal urban development.",
23:"After Krishnadeva Raya's death, succession disputes and rebellious nayakas placed pressure on the imperial structure. The weakening did not immediately end Vijayanagara but made later political instability more serious.",
24:"After Krishnadeva Raya, succession strain was followed by Rama Raya's dominance, defeat at Talikota in 1565, and an eastward shift under the Aravidus. The sequence captures the empire's transition from peak power to a new political centre.",
25:"Vijayanagara rulers depended heavily on effective cavalry, so high-quality imported horses were strategically important. This need linked warfare directly with western coastal trade routes.",
26:"Vijayanagara used firearms and employed foreign specialists, including Turkish and Portuguese experts. The policy shows that the empire adapted new military techniques instead of relying only on traditional arms.",
27:"Deva Raya II recruited Muslims into the Vijayanagara armed forces and provided facilities for them in the capital. The measure illustrates the practical military policies adopted by the empire.",
28:"An amara-nayaka was a military commander who received territory to administer and maintained troops for the raya. The system connected local revenue control with military service to the central ruler.",
29:"Amara-nayakas collected revenue, promoted agriculture, maintained troops and contributed to irrigation and temple upkeep. Their responsibilities therefore extended beyond purely military service.",
30:"Amara-nayakas sent annual tribute and appeared at court with gifts as signs of loyalty to the raya. These practices reinforced the political relationship between territorial commanders and the imperial centre.",
31:"The Raichur doab lay between the Krishna and Tungabhadra rivers and was valued for fertile land and resources. Its location and economic importance made it a recurring zone of Deccan conflict.",
32:"Bahmani-Vijayanagara rivalry involved Raichur, Marathwada and the Krishna-Godavari delta, along with ports and trade routes. The conflict therefore had broad territorial and economic causes rather than a single frontier dispute.",
33:"Marathwada and the Krishna-Godavari delta were also important zones of Bahmani-Vijayanagara rivalry. These regions added strategic and economic depth to the better-known struggle over Raichur.",
34:"Ports and coastal routes mattered because they linked the Deccan to overseas trade and the import of war horses. Economic access to maritime networks therefore strengthened military capacity as well.",
35:"The Bahmani-Vijayanagara struggle was driven mainly by territorial and economic interests rather than religion alone. Both states competed over fertile land, strategic zones, ports and trade routes.",
36:"Repeated warfare weakened both Bahmani and Vijayanagara power while Portuguese influence increased along the western coast. The long conflict therefore had consequences beyond the immediate battlefield.",
37:"Malik Sarwar in Jaunpur, Zafar Khan in Gujarat and Ilyas Shah in Bengal reflect the rise of regional powers as Delhi weakened. Their emergence shows how provincial elites turned local authority into independent states.",
38:"Jaunpur was ruled by the Sharqi Sultans, while Zain-ul-Abidin is associated with Kashmir. The pairing correctly matches a regional dynasty with one of the best-known rulers of another kingdom.",
39:"Ibrahim Shah Sharqi was noted for scholarship and patronage of music, fine arts and architecture. His reign represents the cultural importance of the Sharqi court at Jaunpur.",
40:"Sikandar Lodi ultimately annexed Jaunpur and ended Sharqi rule. The event brought an important regional kingdom back under the authority of Delhi.",
41:"Shamsuddin Shah established Muslim rule in Kashmir, while Zain-ul-Abidin later became popularly known as Bud Shah. The two rulers belong to different stages of medieval Kashmiri political history.",
42:"Zain-ul-Abidin abolished jaziya, encouraged displaced Hindus to return and supported agriculture and handicrafts. These policies help explain his reputation for conciliation and economic development.",
43:"Ilyas Shah founded a ruling dynasty in Bengal, while Ghiyasuddin Azam Shah later maintained cordial relations with China. The pairing links dynastic formation with Bengal's wider diplomatic connections.",
44:"Ghiyasuddin Azam Shah promoted Persian literature and maintained cordial relations with China. His reign shows that Bengal's regional court was connected both culturally and diplomatically beyond the subcontinent.",
45:"Chittagong was an important port in Bengal's trade with China. Its maritime role helped connect the eastern Indian region with wider Bay of Bengal commercial networks.",
46:"Pandua and Gaur served as important capitals of medieval Bengal. Remembering the pair helps distinguish Bengal's political centres from major cities of Gujarat or the Deccan.",
47:"Zafar Khan asserted independence in Gujarat and later assumed the title Muzaffar Shah. His rise marks the establishment of an independent regional sultanate as Delhi's authority weakened.",
48:"Ahmad Shah founded Ahmedabad, Mahmud Begarha captured Girnar and Champaner, and Gujarat prospered through seaports and handicrafts. The combination links political expansion, urban growth and a strong commercial economy.",
49:"The ruling sequence Sangama, Saluva, Tuluva and Aravidu is correct for Vijayanagara. The order is important because Krishnadeva Raya belongs specifically to the Tuluva phase.",
50:"Hasan Bahman Shah founded the Bahmani state, Harihara and Bukka are linked with Vijayanagara, and Ilyas Shah founded a Bengal dynasty. The option correctly matches three regional states with their founders.",
51:"A taraf was a Bahmani province, a tarafdar governed it, and an amara-nayaka was a Vijayanagara territorial military commander. The set compares administrative institutions from the two major Deccan powers.",
52:"Mahmud Gawan is linked with Goa and Dabhol, Krishnadeva Raya with Amuktamalyada, and Ahmad Shah with Ahmedabad. The correct set combines military-commercial expansion, literature and urban foundation.",
53:"Raichur lay between the Krishna and Tungabhadra, Chittagong served Bengal-China trade, and Goa-Dabhol linked to western sea trade. The option correctly matches places with their geographical or commercial significance.",
54:"Zain-ul-Abidin belongs to Kashmir, Mahmud Begarha to Gujarat and Ibrahim Shah Sharqi to Jaunpur. These associations distinguish three important rulers of regional medieval kingdoms.",
55:"Statements 1 and 3 are correct: Gulbarga was the first Bahmani capital and a taraf was governed by a tarafdar. Statement 2 is false because Bahmani provinces were called tarafs, not iqtas.",
56:"Statements 2 and 3 are correct: Mahmud Gawan became wazir and reduced tarafdar power by placing forts under central qiladars. Statement 1 is false because he was Iranian by birth, not Deccan-born.",
57:"Statements 1 and 2 are correct: Harihara and Bukka are linked with Vijayanagara's foundation and Sangama was its first dynasty. Statement 3 is false because Krishnadeva Raya belonged to the Tuluva dynasty.",
58:"Statements 1 and 3 are correct: Krishnadeva Raya wrote Amuktamalyada and Rama Raya later became a dominant political figure. Statement 2 is false because Talikota occurred in 1565, after Krishnadeva Raya's reign.",
59:"Statements 1 and 2 are correct: Zain-ul-Abidin was associated with Kashmir and Ilyas Shah founded a Bengal dynasty. Statement 3 is false because Ahmad Shah founded Ahmedabad, not Gulbarga.",
60:"All four statements are correct: trade and agricultural surplus supported regional states, regional languages expanded, political rivalry did not prevent exchange, and Deccan conflict had more than religious causes. The set summarizes the broader regional-state pattern.",
};
