import { strict as assert } from "node:assert";
import { TMW_CP004_REGISTRY } from "./foundation/cp004-registry";
import { runTmwCp004Pipeline } from "./foundation/cp004-runtime";
function normalize(v:string){return v.toLowerCase().replace(/\\\([^)]*\\\)/g,"<math>").replace(/\d+(?:\s+\d+\/\d+|\/\d+)?/g,"<n>").replace(/[^a-z<>]+/g," ").trim();}
const exactStemOwner=new Map<string,string>(),normalizedStemOwner=new Map<string,string>(),exactExplanationOwner=new Map<string,string>(),contexts=new Set<string>(),actors=new Set<string>();
let audited=0,invalid=0,unresolved=0,malformedMath=0,unwrappedMath=0,optionFailures=0,genericExplanationHits=0,controlCharacterHits=0,assignmentWordHits=0;
for(const entry of TMW_CP004_REGISTRY){for(let i=0;i<12;i++){const g=runTmwCp004Pipeline({questionLanguageId:entry.qlId,seed:`tmw-cp004-audit:${entry.qlId}:${i}`});audited++;contexts.add(g.parameters.context.jobPhrase);actors.add(g.parameters.context.actorA);if(!g.validation.valid)invalid++;const explanation=[g.explanation.opening,g.explanation.formula,...g.explanation.steps,g.explanation.conclusion].join(" ");if(/\{\{[^}]+\}\}|\$\{[^}]+\}/.test(g.stem+explanation))unresolved++;if((explanation.match(/\\\(/g)??[]).length!==(explanation.match(/\\\)/g)??[]).length)malformedMath++;if(!/^\\\(.+\\\)$/.test(g.explanation.formula)||g.explanation.steps.some(x=>!/^\\\(.+\\\)$/.test(x)))unwrappedMath++;if(g.options.length!==4||new Set(g.options).size!==4||g.correctIndex<0)optionFailures++;if(/now calculate carefully|use the formula|therefore we calculate/i.test(explanation))genericExplanationHits++;if(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(g.stem+explanation))controlCharacterHits++;assignmentWordHits=(g.stem.match(/\bassignment\b/gi)??[]).length;const e=exactStemOwner.get(g.stem);if(e&&e!==entry.qlId)throw new Error(`Exact cross-QL stem collision: ${e}/${entry.qlId}`);exactStemOwner.set(g.stem,entry.qlId);const n=normalize(g.stem),no=normalizedStemOwner.get(n);if(no&&no!==entry.qlId)throw new Error(`Normalized cross-QL stem collision: ${no}/${entry.qlId}: ${n}`);normalizedStemOwner.set(n,entry.qlId);const eo=exactExplanationOwner.get(explanation);if(eo&&eo!==entry.qlId)throw new Error(`Exact cross-QL explanation duplicate: ${eo}/${entry.qlId}`);exactExplanationOwner.set(explanation,entry.qlId);}}
assert.equal(invalid,0);assert.equal(unresolved,0);assert.equal(malformedMath,0);assert.equal(unwrappedMath,0);assert.equal(optionFailures,0);assert.equal(genericExplanationHits,0);assert.equal(controlCharacterHits,0);assert.equal(assignmentWordHits,0);assert.ok(contexts.size>=10);assert.ok(actors.size>=10);
console.log(JSON.stringify({chapter:"TMW-001",checkpoint:"TMW-CP-004",qlCount:24,seedsPerQl:12,audited,invalid,unresolved,malformedMath,unwrappedMath,optionFailures,genericExplanationHits,controlCharacterHits,assignmentWordHits,distinctContextPhrases:contexts.size,distinctContextActors:actors.size,exactCrossQlStemCollisions:0,normalizedCrossQlStemCollisions:0,exactCrossQlExplanationDuplicates:0,status:"PASS"},null,2));
