export const ENG011_BREADTH_WAVE3_V1=[
{ id:"SR-SSC-S13",cpId:"ENG-011-CP001",difficulty:"easy",topic:"school",fragments:["the teacher","explained the new timetable","to the class","before the first period"],order:[1,2,3,4],explanation:"The subject comes first, followed by the verb phrase, the recipient and the time phrase."},
{ id:"SR-SSC-S14",cpId:"ENG-011-CP001",difficulty:"easy",topic:"cleanliness",fragments:["workers emptied","the public bins","before they became full","during the evening round"],order:[1,2,3,4],explanation:"The action begins the sentence, followed by the object, condition and time phrase."},
{ id:"SR-SSC-S15",cpId:"ENG-011-CP001",difficulty:"medium",topic:"transport",fragments:["passengers should stand","behind the marked line","until the bus stops","at the platform"],order:[1,2,3,4],explanation:"The instruction comes first, followed by location and the until-clause."},
{ id:"SR-SSC-S16",cpId:"ENG-011-CP001",difficulty:"medium",topic:"environment",fragments:["the volunteers collected","plastic waste","from the riverbank","during the cleanup drive"],order:[1,2,3,4],explanation:"The subject and verb are followed by the object, location and time phrase."},
{ id:"SR-SSC-S17",cpId:"ENG-011-CP001",difficulty:"easy",topic:"health",fragments:["people should wash","their hands thoroughly","before preparing food","or eating a meal"],order:[1,2,3,4],explanation:"The main instruction is followed by the object and two coordinated time conditions."},
{ id:"SR-SSC-S18",cpId:"ENG-011-CP001",difficulty:"medium",topic:"community",fragments:["the local group organised","a free reading session","for children","at the community hall"],order:[1,2,3,4],explanation:"The subject and verb come first, followed by the activity, beneficiary and place phrase."},

{ id:"SR-SSC-A13",cpId:"ENG-011-CP002",difficulty:"medium",topic:"decision making",fragments:["because the evidence was incomplete","the committee decided","to postpone the final decision","until more information","could be collected"],order:[1,2,3,4,5],explanation:"The reason clause comes first, followed by the main decision and the until-clause."},
{ id:"SR-SSC-A14",cpId:"ENG-011-CP002",difficulty:"hard",topic:"communication",fragments:["although the instructions were accurate","many users misunderstood them","because the wording","was unnecessarily technical","for a general audience"],order:[1,2,3,4,5],explanation:"The concessive clause is followed by the main clause and then the reason clause."},
{ id:"SR-SSC-A15",cpId:"ENG-011-CP002",difficulty:"hard",topic:"research",fragments:["when the original assumption changes","the analysis should be updated","so that the conclusion","continues to reflect","the available evidence"],order:[1,2,3,4,5],explanation:"The condition comes first, followed by the main clause and the purpose clause."},
{ id:"SR-SSC-A16",cpId:"ENG-011-CP002",difficulty:"medium",topic:"services",fragments:["before changing the process","managers should identify","which delays are avoidable","and which arise","from necessary checks"],order:[1,2,3,4,5],explanation:"The opening time phrase is followed by 'should identify' and two coordinated relative clauses."},
{ id:"SR-SSC-A17",cpId:"ENG-011-CP002",difficulty:"hard",topic:"planning",fragments:["even if the average demand is stable","short periods of unusually high use","can still create shortages","when spare capacity","is very limited"],order:[1,2,3,4,5],explanation:"The concessive clause comes first, then the main clause and the condition explaining shortages."},
{ id:"SR-SSC-A18",cpId:"ENG-011-CP002",difficulty:"medium",topic:"training",fragments:["because each learner improves differently","trainers should adjust","the amount of guidance","according to progress","rather than time alone"],order:[1,2,3,4,5],explanation:"The reason clause comes first, followed by the main instruction and the comparison phrase."},

{ id:"SR-BP-S13",cpId:"ENG-011-CP003",difficulty:"medium",topic:"debit cards",fragments:["the amount is deducted","from the linked account","when a customer uses","a debit card for payment"],order:[1,2,3,4],explanation:"The main passive clause is followed by the source account and the time clause."},
{ id:"SR-BP-S14",cpId:"ENG-011-CP003",difficulty:"medium",topic:"fixed deposits",fragments:["customers may earn","a fixed rate of interest","by keeping money","for an agreed period"],order:[1,2,3,4],explanation:"The subject and modal verb are followed by the object, method and duration phrase."},
{ id:"SR-BP-S15",cpId:"ENG-011-CP003",difficulty:"hard",topic:"credit cards",fragments:["if the outstanding balance remains unpaid","interest may be charged","on the amount due","until the customer","makes the required payment"],order:[1,2,3,4,5],explanation:"The condition comes first, followed by the main clause and the until-clause."},
{ id:"SR-BP-S16",cpId:"ENG-011-CP003",difficulty:"hard",topic:"payments",fragments:["when a scheduled payment fails","the bank may attempt","the transaction again","after confirming that","the account can be debited"],order:[1,2,3,4,5],explanation:"The condition comes first, followed by the main action and the confirmation clause."},
{ id:"SR-BP-S17",cpId:"ENG-011-CP003",difficulty:"medium",topic:"savings",fragments:["customers can compare","different savings products","by looking at rates","and the conditions","attached to withdrawal"],order:[1,2,3,4,5],explanation:"The action comes first, followed by the object and two comparison criteria."},
{ id:"SR-BP-S18",cpId:"ENG-011-CP003",difficulty:"hard",topic:"working capital",fragments:["even when sales are strong","a business can face cash pressure","if customers pay late","while supplier bills","fall due earlier"],order:[1,2,3,4,5],explanation:"The concessive clause comes first, followed by the main clause and the timing mismatch."},

{ id:"SR-BM-S13",cpId:"ENG-011-CP004",difficulty:"hard",topic:"credit cycles",fragments:["when lending expands rapidly","borrower leverage may increase","to levels that become difficult","to sustain","during a downturn"],order:[1,2,3,4,5],explanation:"The condition comes first, followed by the main clause and the infinitive chain describing sustainability."},
{ id:"SR-BM-S14",cpId:"ENG-011-CP004",difficulty:"hard",topic:"liquidity",fragments:["although liquid assets may earn less","they can provide protection","when normal funding sources","become unavailable","during periods of stress"],order:[1,2,3,4,5],explanation:"The concessive clause is followed by the main benefit and the condition explaining when it matters."},
{ id:"SR-BM-S15",cpId:"ENG-011-CP004",difficulty:"medium",topic:"financial inclusion",fragments:["access to an account","does not guarantee","that customers can use it effectively","unless the service","is affordable and understandable"],order:[1,2,3,4,5],explanation:"The subject comes first, followed by the main clause and the unless-condition."},
{ id:"SR-BM-S16",cpId:"ENG-011-CP004",difficulty:"hard",topic:"operational risk",fragments:["because repeated small failures","can create large cumulative losses","firms should track","patterns of incidents","rather than isolated events alone"],order:[1,2,3,4,5],explanation:"The reason clause comes first, followed by the main instruction and the comparison phrase."},
{ id:"SR-BM-S17",cpId:"ENG-011-CP004",difficulty:"hard",topic:"asset quality",fragments:["when overdue loans rise steadily","analysts may conclude","that repayment stress is increasing","especially if the trend","persists across several periods"],order:[1,2,3,4,5],explanation:"The condition comes first, followed by the inference and the persistence qualification."},
{ id:"SR-BM-S18",cpId:"ENG-011-CP004",difficulty:"medium",topic:"compliance",fragments:["even when policies are well written","compliance can remain weak","if employees do not understand","how the rules apply","to their daily work"],order:[1,2,3,4,5],explanation:"The concessive clause comes first, followed by the main clause and the condition explaining weak implementation."}
] as const;