import type { PolCp024SeedRow } from "./pol-cp024-types";

export const POL_CP024_PART_3: readonly PolCp024SeedRow[] = [
  ["POL-024-QL-011","Medium","Who appoints the Special Officer for Linguistic Minorities under Article 350B?","President","Prime Minister","Chief Justice of India","Parliament","Article 350B provides for a Special Officer for Linguistic Minorities appointed by the President.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-011","Medium","What is the Special Officer's main constitutional duty under Article 350B?","Investigating safeguards for linguistic minorities","Auditing State accounts","Conducting elections","Recommending tax shares","The Special Officer investigates matters relating to constitutional safeguards for linguistic minorities and reports on those safeguards.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-011","Medium","To whom does the Special Officer for Linguistic Minorities report?","President","Prime Minister alone","Supreme Court","Finance Commission","Article 350B requires the Special Officer to report to the President at intervals directed by the President.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-011","Medium","What specific professional qualification does Article 350B prescribe for the Special Officer?","No specific qualification is prescribed","Ten years as a High Court advocate","Five years as a High Court judge","Twenty-five years in civil service","Article 350B creates the office and states its duties, but it does not prescribe a specific educational, judicial or professional qualification.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-012","Medium","Article 351 directs the Union to promote the spread of which language?","Hindi","English","Sanskrit only","Urdu only","Article 351 places a directive on the Union to promote the spread of Hindi and develop it for wider expression.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-012","Medium","Article 351 asks Hindi to serve as a medium of expression for what?","Composite culture of India","Only Union taxation","Only court procedure","Only parliamentary elections","Article 351 directs development of Hindi so it can serve as a medium of expression for all elements of India's composite culture.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-012","Medium","Article 351 says Hindi vocabulary should be drawn primarily from which language?","Sanskrit","English","Persian","Portuguese","Article 351 directs enrichment of Hindi vocabulary primarily from Sanskrit and secondarily from other languages where necessary or desirable.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-012","Medium","Which Schedule's languages are specifically relevant to Article 351's development directive?","Eighth Schedule","Fifth Schedule","Sixth Schedule","Tenth Schedule","Article 351 refers to forms, styles and expressions used in Hindustani and the other languages specified in the Eighth Schedule.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-013","Medium","How many languages are currently listed in the Eighth Schedule?","Twenty-two","Fourteen","Eighteen","Twenty-four","The Eighth Schedule currently lists twenty-two languages; the original Constitution listed fourteen languages at commencement.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-013","Medium","The Eighth Schedule is expressly linked to which two Articles?","Articles 344(1) and 351","Articles 343 and 345","Articles 350A and 350B","Articles 244 and 275","The heading of the Eighth Schedule expressly links it to Article 344(1) and Article 351.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-013","Medium","Which language is listed in the Eighth Schedule?","Santhali","English","French","Portuguese","Santhali is one of the twenty-two languages in the Eighth Schedule; English is not included in that Schedule.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-013","Medium","Which language is not included in the Eighth Schedule?","English","Punjabi","Urdu","Sanskrit","English has important official uses under the Constitution and law, but it is not one of the Eighth Schedule languages.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-014","Medium","Which Constitutional Amendment added Sindhi to the Eighth Schedule?","Twenty-first Amendment","Forty-second Amendment","Seventy-first Amendment","Ninety-second Amendment","The Constitution (Twenty-first Amendment) Act, 1967 added Sindhi to the Eighth Schedule as a new listed language.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-014","Medium","Which languages were added by the Seventy-first Amendment?","Konkani, Manipuri and Nepali","Bodo, Dogri and Maithili","Sindhi, Tamil and Telugu","Odia, Punjabi and Urdu","The Seventy-first Amendment added Konkani, Manipuri and Nepali to the Eighth Schedule in 1992.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-014","Medium","Which group was added by the Ninety-second Amendment?","Bodo, Dogri, Maithili and Santhali","Konkani, Manipuri and Nepali","Sindhi, Sanskrit and Urdu","Tamil, Telugu, Marathi and Gujarati","The Ninety-second Amendment added Bodo, Dogri, Maithili and Santhali, taking the Eighth Schedule total to twenty-two languages.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-014","Medium","Which Amendment changed the Eighth Schedule name 'Oriya' to 'Odia'?","Ninety-sixth Amendment","Seventy-first Amendment","Ninety-second Amendment","One Hundred and First Amendment","The Ninety-sixth Amendment changed the constitutional name of the language from 'Oriya' to 'Odia'.",["CONSTITUTION-EIGHTH-SCHEDULE"]],
  ["POL-024-QL-015","Medium","Article 244(1) applies which Schedule to Scheduled Areas and Scheduled Tribes?","Fifth Schedule","Fourth Schedule","Sixth Schedule","Seventh Schedule","Article 244(1) links the administration and control of Scheduled Areas and Scheduled Tribes with the Fifth Schedule.",["CONSTITUTION-FIFTH-SCHEDULE"]],
  ["POL-024-QL-015","Medium","Article 244(2) applies which Schedule to specified tribal areas in the Northeast?","Sixth Schedule","Fifth Schedule","Eighth Schedule","Ninth Schedule","Article 244(2) connects specified tribal areas in Assam, Meghalaya, Tripura and Mizoram with the Sixth Schedule.",["CONSTITUTION-SIXTH-SCHEDULE"]],
  ["POL-024-QL-015","Medium","Which set of States is associated with the Sixth Schedule under Article 244(2)?","Assam, Meghalaya, Tripura and Mizoram","Assam, Nagaland, Manipur and Sikkim","Odisha, Jharkhand, Chhattisgarh and Gujarat","Punjab, Haryana, Rajasthan and Gujarat","The Sixth Schedule provides autonomous tribal-area administration in Assam, Meghalaya, Tripura and Mizoram.",["CONSTITUTION-SIXTH-SCHEDULE"]],
  ["POL-024-QL-015","Medium","Which Schedule primarily governs Scheduled Areas outside the four Sixth Schedule States?","Fifth Schedule","Second Schedule","Sixth Schedule","Eighth Schedule","The Fifth Schedule is the main constitutional framework for Scheduled Areas outside Assam, Meghalaya, Tripura and Mizoram.",["CONSTITUTION-FIFTH-SCHEDULE"]],
];