import type { PolCp024SeedRow } from "./pol-cp024-types";

export const POL_CP024_PART_2: readonly PolCp024SeedRow[] = [
  ["POL-024-QL-006","Easy","Which Article governs official communication between States and between a State and the Union?","Article 346","Article 344","Article 348","Article 351","Article 346 governs the official language used for communication between States and between a State and the Union.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-006","Easy","Two States may agree to use which language for communication between themselves under Article 346?","Hindi","Only English","Sanskrit only","Any Eighth Schedule language automatically","Article 346 permits two or more States to agree that Hindi may be used for official communication between those States.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-006","Easy","Which Article allows special recognition of a language spoken by a substantial section of a State's population?","Article 347","Article 345","Article 349","Article 350A","Article 347 allows the President, on a qualifying demand, to direct official recognition of a language in a State or part of it.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-006","Easy","Who may issue a direction under Article 347 for recognition of a language in a State?","President","Governor alone","Parliamentary Committee","Supreme Court","Under Article 347, the President may direct recognition of a language when satisfied that a substantial section of the State population desires it.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-007","Medium","Under Article 348, which language is ordinarily used in Supreme Court proceedings?","English","Hindi only","Sanskrit","Any language chosen by parties","Article 348 provides that Supreme Court proceedings are ordinarily conducted in English unless Parliament provides otherwise by law.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-007","Medium","Under Article 348, which language is ordinarily used in High Court proceedings?","English","Hindi in every State","State official language automatically","Any Eighth Schedule language","Article 348 keeps English as the ordinary language of High Court proceedings, subject to the Constitution's limited authorisation mechanism.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-007","Medium","A Governor needs whose previous consent to authorise Hindi or another State official language in High Court proceedings?","President","Chief Justice of India","Prime Minister","State Legislature","Article 348 permits such High Court use only when the Governor acts with the President's previous consent.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-007","Medium","A State language authorised for High Court proceedings under Article 348 does not automatically cover what?","Judgments, decrees and orders","Oral arguments","Petitions","Witness statements","Article 348's State-language authorisation for High Court proceedings does not extend to judgments, decrees or orders of that High Court.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-008","Medium","Which Article sets a special procedure for certain language laws during the Constitution's first fifteen years?","Article 349","Article 344","Article 347","Article 351","Article 349 imposed a special procedure during the first fifteen years for specified Bills or amendments dealing with language matters.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-008","Medium","During Article 349's initial period, what was required before introducing specified language legislation?","Previous sanction of the President","Approval of the Supreme Court","Consent of every State","Recommendation of the CAG","Article 349 required the President's previous sanction before specified language Bills or amendments could be introduced during the initial period.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-008","Medium","Before giving sanction under Article 349, what recommendations had to be considered?","Article 344 Commission and Committee recommendations","Finance Commission recommendations","Election Commission recommendations","Inter-State Council recommendations","Article 349 links presidential sanction to consideration of the recommendations made under Article 344 by the Commission and Parliamentary Committee.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-008","Medium","Article 349's special restriction primarily concerned laws affecting which constitutional language provisions?","Article 348-related language matters","Emergency provisions","Citizenship provisions","Election provisions","Article 349 controlled specified legislation altering the language framework covered by Article 348 during the Constitution's first fifteen years.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-009","Medium","Which Article protects the choice of language for representations seeking redress of grievances?","Article 350","Article 343","Article 347","Article 351","Article 350 allows a person to submit a grievance representation in any language used in the Union or State, as applicable.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-009","Medium","A grievance representation under Article 350 may be submitted to which authority?","Any Union or State officer or authority concerned","Only the President","Only a High Court","Only Parliament","Article 350 applies to representations for grievance redress addressed to officers or authorities of the Union or a State.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-009","Medium","Article 350 mainly protects which practical right?","Using an accepted Union or State language for a grievance representation","Choosing the language of every court judgment","Demanding a new State","Selecting an election symbol","Article 350 makes grievance access easier by permitting representations in languages used in the Union or the relevant State.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-009","Medium","Does Article 350 restrict grievance representations to the Union's official language alone?","No","Yes, always","Yes, except for MPs","Yes, unless Parliament permits otherwise","No. Article 350 expressly permits a grievance representation in any language used in the Union or in the State concerned.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-010","Medium","Article 350A concerns instruction in what language at the primary stage?","Mother tongue of children from linguistic minority groups","Hindi only","English only","Sanskrit only","Article 350A seeks adequate facilities for mother-tongue instruction at the primary stage for children belonging to linguistic minority groups.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-010","Medium","Who should endeavour to provide Article 350A mother-tongue facilities?","Every State and local authority within the State","Only Parliament","Only private schools","Only the President","Article 350A places the endeavour on every State and on local authorities within the State to provide adequate primary-stage facilities.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-010","Medium","Who may issue directions to a State for securing facilities under Article 350A?","President","Governor only","Chief Justice of India","Election Commission","Article 350A authorises the President to issue directions considered necessary or proper for securing the required mother-tongue facilities.",["CONSTITUTION-PART-XVII"]],
  ["POL-024-QL-010","Medium","Article 350A is aimed specifically at children belonging to which group?","Linguistic minority groups","Only Scheduled Castes","Only religious majorities","Only government employees","The constitutional focus of Article 350A is primary-stage mother-tongue instruction for children from linguistic minority groups.",["CONSTITUTION-PART-XVII"]],
];