import type {
  NumCp003NonRetainedPrototypeDisposition,
  NumCp003RetainedTemplateEntry,
} from "./types";

const locked = {
  permanentQlId: null,
  publiclyPublishable: false,
  questionStudioDiscoverable: false,
} as const;

export const NUM_CP003_RETAINED_TEMPLATE_REGISTRY = [
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-01",
    authorityId: "APPLY_DIVISIBILITY_RULE",
    taskDirection: "FORWARD_SELECTION",
    answerSemantic: "DIVISOR",
    targetProjection: "SELECT_DIVISOR_BY_POLARITY",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 end-to-end CP-003 baseline", "SSC direct divisibility patterns"],
    prototypeAncestry: ["NUM-CP003-PROT-DIRECT-COMPOSITE-DIVISIBILITY"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-02",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "INVERSE_RECONSTRUCTION",
    answerSemantic: "DIGIT",
    targetProjection: "UNIQUE_VALID_DIGIT",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["SSC missing-digit PYQs", "Quant V3 NS-DIV-001 CP-001"],
    prototypeAncestry: [
      "NUM-CP003-PROT-SINGLE-MISSING-DIGIT-UNIQUE",
      "NUM-CP003-W2-PROT-LEADING-MISSING-DIGIT",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-03",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "DIGIT",
    targetProjection: "EXTREMUM_VALID_DIGIT",
    extremumDirectionParameter: true,
    representation: "STANDARD",
    sourceEvidence: ["SSC missing-digit extremum patterns", "Quant V3 NS-DIV-001 CP-002/CP-003"],
    prototypeAncestry: [
      "NUM-CP003-W5-PROT-LARGEST-VALID-DIGIT",
      "NUM-CP003-W5-PROT-SMALLEST-VALID-DIGIT",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-04",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "COUNT",
    targetProjection: "VALID_DIGIT_COUNT",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 open discovery count predicate", "Quant V3 NS-DIV-001 CP-004"],
    prototypeAncestry: ["NUM-CP003-PROT-SINGLE-MISSING-DIGIT-COUNT"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-05",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "DIGIT_SUM",
    targetProjection: "VALID_DIGIT_SUM",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["Quant V3 NS-DIV-001 CP-005", "uploaded source saturation audit"],
    prototypeAncestry: ["NUM-CP003-W5-PROT-SUM-VALID-DIGITS"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-06",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "DIGIT_SET",
    targetProjection: "COMPLETE_VALID_DIGIT_SET",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 open discovery set predicate"],
    prototypeAncestry: ["NUM-CP003-W2-PROT-ALL-VALID-DIGITS-SET"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-07",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "NUMBER",
    targetProjection: "EXTREMUM_COMPLETED_NUMBER",
    extremumDirectionParameter: true,
    representation: "STANDARD",
    sourceEvidence: ["Quant V3 NS-DIV-001 CP-006/CP-007", "uploaded source saturation audit"],
    prototypeAncestry: [
      "NUM-CP003-W5-PROT-GREATEST-COMPLETED-NUMBER",
      "NUM-CP003-W5-PROT-SMALLEST-COMPLETED-NUMBER",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-08",
    authorityId: "RESOLVE_ORDERED_DIGIT_PAIR_SET",
    taskDirection: "INVERSE_RECONSTRUCTION",
    answerSemantic: "ORDERED_DIGIT_PAIR",
    targetProjection: "UNIQUE_VALID_ORDERED_PAIR",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["SSC two-missing-digit patterns", "NUM-001 CP-003 inverse baseline"],
    prototypeAncestry: [
      "NUM-CP003-PROT-TWO-MISSING-DIGITS-MULTI-RULE",
      "NUM-CP003-W2-PROT-TWO-DIGITS-NO-SUM",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-09",
    authorityId: "RESOLVE_ORDERED_DIGIT_PAIR_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "COUNT",
    targetProjection: "VALID_ORDERED_PAIR_COUNT",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 open discovery count predicate"],
    prototypeAncestry: ["NUM-CP003-W3-PROT-TWO-DIGIT-PAIR-COUNT"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-10",
    authorityId: "RESOLVE_ORDERED_DIGIT_PAIR_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "ORDERED_PAIR_SET",
    targetProjection: "COMPLETE_VALID_ORDERED_PAIR_SET",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 open discovery set predicate"],
    prototypeAncestry: ["NUM-CP003-W4-PROT-TWO-DIGIT-PAIR-SET"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-11",
    authorityId: "RESOLVE_ORDERED_DIGIT_PAIR_SET",
    taskDirection: "CANDIDATE_SET_PROJECTION",
    answerSemantic: "SOLUTION_CLASS",
    targetProjection: "PAIR_SOLUTION_CLASS",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["NUM-001 possible/impossible and no/one/many audit"],
    prototypeAncestry: ["NUM-CP003-W4-PROT-TWO-DIGIT-SOLUTION-CLASS"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-12",
    authorityId: "FIND_DIGIT_BOUND_MULTIPLE",
    taskDirection: "BOUNDARY_OPTIMISATION",
    answerSemantic: "NUMBER",
    targetProjection: "EXTREMUM_N_DIGIT_MULTIPLE",
    extremumDirectionParameter: true,
    representation: "STANDARD",
    sourceEvidence: ["SSC least/greatest n-digit divisible-number PYQs", "NUM-001 CP-003 baseline"],
    prototypeAncestry: [
      "NUM-CP003-PROT-LEAST-N-DIGIT-MULTIPLE",
      "NUM-CP003-W2-PROT-GREATEST-N-DIGIT-MULTIPLE",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-13",
    authorityId: "COUNT_ONE_DIVISOR_IN_RANGE",
    taskDirection: "RANGE_COUNT",
    answerSemantic: "COUNT",
    targetProjection: "INCLUSIVE_MULTIPLE_COUNT",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["SSC count-of-multiples PYQs", "NUM-001 CP-003 range baseline"],
    prototypeAncestry: ["NUM-CP003-W2-PROT-COUNT-MULTIPLES-IN-RANGE"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-14",
    authorityId: "TEST_IMPLICIT_REPEATED_NUMERAL",
    taskDirection: "REPRESENTATION_CONSTRUCTION",
    answerSemantic: "DIVISOR",
    targetProjection: "DIVISOR_OF_CONSTRUCTED_REPEATED_NUMERAL",
    extremumDirectionParameter: false,
    representation: "STANDARD",
    sourceEvidence: ["SSC repeated-digit/block patterns", "NUM-001 CP-003 concatenation baseline"],
    prototypeAncestry: ["NUM-CP003-PROT-REPEATED-BLOCK-DIVISIBILITY"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-15",
    authorityId: "RESOLVE_LINKED_ARITHMETIC_DIVISIBILITY",
    taskDirection: "LINKED_CONSTRAINT_RECONSTRUCTION",
    answerSemantic: "DIGIT",
    targetProjection: "EXTREMUM_LINKED_DIGIT",
    extremumDirectionParameter: true,
    representation: "STANDARD",
    sourceEvidence: ["SSC linked arithmetic-result divisibility PYQ", "Wave 05 materiality proof"],
    prototypeAncestry: ["NUM-CP003-W5-PROT-LINKED-ADDITION-DIVISIBILITY-EXTREMUM"],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-16",
    authorityId: "RESOLVE_SINGLE_DIGIT_CANDIDATE_SET",
    taskDirection: "EVIDENCE_SUFFICIENCY",
    answerSemantic: "SUFFICIENCY_CLASS",
    targetProjection: "FIVE_CLASS_DATA_SUFFICIENCY",
    extremumDirectionParameter: false,
    representation: "DATA_SUFFICIENCY",
    sourceEvidence: ["banking data-sufficiency representation", "NUM-001 representation audit"],
    prototypeAncestry: [
      "NUM-CP003-W3-PROT-MISSING-DIGIT-DATA-SUFFICIENCY",
      "NUM-CP003-W4-PROT-EACH-STATEMENT-ALONE-SUFFICIENT",
    ],
    ...locked,
  },
  {
    temporaryTemplateLabel: "NUM-CP003-QLT2-17",
    authorityId: "APPLY_DIVISIBILITY_RULE",
    taskDirection: "CLAIM_VALIDATION",
    answerSemantic: "TRUTH_CLAIM",
    targetProjection: "SELECT_CLAIM_BY_POLARITY",
    extremumDirectionParameter: false,
    representation: "CLAIM",
    sourceEvidence: ["NUM-001 statement representation audit", "multi-condition divisibility claim baseline"],
    prototypeAncestry: ["NUM-CP003-W3-PROT-DIVISIBILITY-CLAIM-VERIFICATION"],
    ...locked,
  },
] as const satisfies readonly NumCp003RetainedTemplateEntry[];

export const NUM_CP003_NON_RETAINED_PROTOTYPE_DISPOSITIONS = [
  {
    prototypeId: "NUM-CP003-W2-PROT-MISSING-DIGIT-IN-SUM",
    disposition: "REJECT",
    reason: "Visible arithmetic alone fixes the digit; divisibility is decorative.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-MISSING-DIGIT-IN-DIFFERENCE",
    disposition: "REJECT",
    reason: "Visible arithmetic alone fixes the digit; divisibility is decorative.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-MISSING-DIGIT-IN-PRODUCT",
    disposition: "REJECT",
    reason: "Visible arithmetic alone fixes the digit; divisibility is decorative.",
  },
  {
    prototypeId: "NUM-CP003-W2-PROT-LEAST-REPUNIT-LENGTH",
    disposition: "REASSIGN",
    destination: "NUM-CP-008",
    reason: "Remainder recurrence is the governing engine.",
  },
  {
    prototypeId: "NUM-CP003-W2-PROT-POWER-EXPRESSION-DIVISIBILITY",
    disposition: "REASSIGN",
    destination: "NUM-CP-008",
    reason: "Modular exponentiation is the governing engine.",
  },
  {
    prototypeId: "NUM-CP003-W2-PROT-COUNT-ONE-NOT-ANOTHER",
    disposition: "OWNERSHIP_HOLD",
    destination: "SHARED_SET_COUNTING",
    reason: "Requires overlap counting and LCM/inclusion-exclusion ownership review.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-COUNT-DIVISIBLE-BY-EITHER",
    disposition: "OWNERSHIP_HOLD",
    destination: "SHARED_SET_COUNTING",
    reason: "Inclusion-exclusion is the governing engine.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-COUNT-DIVISIBLE-BY-NEITHER",
    disposition: "OWNERSHIP_HOLD",
    destination: "SHARED_SET_COUNTING",
    reason: "Complement plus inclusion-exclusion is the governing engine.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-COUNT-DIVISIBLE-BY-EXACTLY-ONE",
    disposition: "OWNERSHIP_HOLD",
    destination: "SHARED_SET_COUNTING",
    reason: "Symmetric-difference counting is the governing engine.",
  },
  {
    prototypeId: "NUM-CP003-W4-PROT-COUNT-THREE-DIVISORS-AT-LEAST-ONE",
    disposition: "OWNERSHIP_HOLD",
    destination: "SHARED_SET_COUNTING",
    reason: "Three-set inclusion-exclusion requires owner closure.",
  },
  {
    prototypeId: "NUM-CP003-W3-PROT-GUARANTEED-POWER-DIFFERENCE-DIVISOR",
    disposition: "OWNERSHIP_HOLD",
    destination: "ALGEBRA_OR_NUM_CP008",
    reason: "Factorisation or modular arithmetic is the governing inference.",
  },
  {
    prototypeId: "NUM-CP003-W4-PROT-REPEATED-BLOCK-GUARANTEED-DIVISOR",
    disposition: "OWNERSHIP_HOLD",
    destination: "ALGEBRA_OR_NUM_CP008",
    reason: "General place-value factor identity exceeds concrete repeated-numeral testing.",
  },
  {
    prototypeId: "NUM-CP003-W4-PROT-POWER-SUM-GUARANTEED-DIVISOR",
    disposition: "OWNERSHIP_HOLD",
    destination: "ALGEBRA_OR_NUM_CP008",
    reason: "Odd-power sum factorisation is the governing inference.",
  },
  {
    prototypeId: "NUM-CP003-W4-PROT-DIVISOR-FROM-RULE",
    disposition: "STUDY_ONLY",
    reason: "Useful concept check but no distinct recurring exam-task fixture is established.",
  },
  {
    prototypeId: "NUM-CP003-W4-PROT-RULE-FROM-DIVISOR",
    disposition: "STUDY_ONLY",
    reason: "Useful rule-registry check but not retained as a learner QL without exam-task evidence.",
  },
] as const satisfies readonly NumCp003NonRetainedPrototypeDisposition[];
