export const HIS_CP024_QL_NAMES_V1:Record<number,string>={
  "1": "Congress session supplements, 1924–1927",
  "2": "HRA and Kakori action",
  "3": "Kakori aftermath and HSRA reorientation",
  "4": "Communal Award and Poona Pact",
  "5": "Faizpur Congress and peasant turn",
  "6": "Haripura Congress and constitutional programme",
  "7": "Tripuri crisis and Forward Bloc",
  "8": "Wavell Plan and Simla Conference",
  "9": "Chronology and political comparison",
  "10": "INA trials and 1946 constitutional transition"
};
export type HisCp024Spec=readonly[ql:number,stem:string,answer:string,distractors:readonly[string,string,string],factIds:readonly string[]];
export const HIS_CP024_SPECS_V1:readonly HisCp024Spec[]=[
  [1,"The only Congress session presided over by Mahatma Gandhi was held at:","Belgaum",["Faizpur","Haripura","Tripuri"],["belgaum-gandhi","belgaum-1924"]],
  [1,"The 39th session of the Indian National Congress was held in:","1924",["1927","1936","1938"],["belgaum-1924"]],
  [1,"Who presided over the Madras Congress session of 1927?","Mukhtar Ahmed Ansari",["Jawaharlal Nehru","Subhas Chandra Bose","Mahatma Gandhi"],["madras-ansari","madras-1927-session"]],
  [1,"The Madras Congress session of 1927 resolved to boycott the:","Simon Commission",["Butler Committee","Hunter Commission","Cabinet Mission"],["madras-simon-boycott"]],
  [1,"Who introduced the Independence Resolution at the Madras Congress session of 1927?","Jawaharlal Nehru",["M.A. Jinnah","C.R. Das","Vallabhbhai Patel"],["madras-independence"]],
  [1,"The Madras Congress session of 1927 was the:","42nd annual session",["39th annual session","50th annual session","51st annual session"],["madras-1927-session"]],
  [2,"The Hindustan Republican Association was formed in:","1924",["1919","1928","1931"],["hra-1924"]],
  [2,"The rise of the HRA was closely linked with disillusionment after the withdrawal of the:","Non-Cooperation Movement",["Civil Disobedience Movement","Quit India Movement","Swadeshi Movement"],["hra-post-ncm"]],
  [2,"The pamphlet The Revolutionary was issued by the HRA in:","1925",["1916","1929","1935"],["hra-revolutionary-pamphlet"]],
  [2,"The Kakori train action took place on:","9 August 1925",["8 August 1942","6 April 1930","3 February 1928"],["kakori-date"]],
  [2,"The Kakori action was primarily aimed at seizing:","Colonial government treasury cash",["Private peasant savings","Temple donations","Congress funds"],["kakori-treasury"]],
  [2,"Which group contains prominent participants in the Kakori action?","Bismil, Ashfaqulla, Bakshi and Rajendra Lahiri",["Gandhi, Nehru, Patel and Azad","Tilak, Pal, Rai and Gokhale","Bose, Sehgal, Dhillon and Shah Nawaz"],["kakori-participants"]],
  [3,"What followed the Kakori action within about a month?","Arrest of more than a dozen HRA members",["Formation of the Cabinet Mission","Repeal of the Rowlatt Act","Beginning of Quit India"],["kakori-arrests"]],
  [3,"Which group was sentenced to death in the Kakori case?","Bismil, Ashfaqulla Khan, Roshan Singh and Rajendra Lahiri",["Bhagat Singh, Rajguru, Sukhdev and Azad","Shah Nawaz, Sahgal, Dhillon and Bose","Nehru, Patel, Azad and Prasad"],["kakori-four-martyrs"]],
  [3,"Rajendra Nath Lahiri was executed on:","17 December 1927",["19 December 1927","23 March 1931","5 November 1945"],["kakori-lahiri-date"]],
  [3,"Sachin Sanyal and Jogesh Chatterji were linked with the formation of the:","Hindustan Republican Association",["Forward Bloc","Swaraj Party","Home Rule League"],["hra-up-founders"]],
  [3,"The HRA developed links with the Punjab revolutionary group led by:","Bhagat Singh",["Mahatma Gandhi","C.R. Das","M.A. Ansari"],["hra-bhagat-link"]],
  [3,"The HRA was renamed HSRA under the growing influence of:","Socialist ideas",["Orientalist ideas","Liberal imperialism","Communal electorates"],["hsra-socialist"]],
  [4,"The Communal Award was announced on:","17 August 1932",["20 September 1932","24 September 1932","26 September 1932"],["communal-award-date"]],
  [4,"The provision that triggered Gandhi's 1932 fast was separate electorates for the:","Depressed Classes",["European community","Princely rulers","Civil servants"],["communal-award-depressed"]],
  [4,"Gandhi began his Yeravada fast against separate electorates on:","20 September 1932",["17 August 1932","24 September 1932","30 September 1932"],["gandhi-fast-start"]],
  [4,"The Poona Pact was concluded on:","24 September 1932",["17 August 1932","20 September 1932","26 September 1932"],["poona-pact-date"]],
  [4,"Gandhi ended his 1932 fast on:","26 September 1932",["20 September 1932","24 September 1932","30 September 1932"],["gandhi-fast-end"]],
  [4,"The Harijan Sevak Sangh was established shortly after the:","Poona Pact",["Lucknow Pact","Gandhi-Irwin Pact","Delhi Pact"],["harijan-sevak-sangh","poona-pact-date"]],
  [5,"The Faizpur meeting was which session of the Indian National Congress?","50th",["42nd","51st","39th"],["faizpur-50th"]],
  [5,"The Faizpur Congress session was held in:","December 1936",["December 1927","February 1938","March 1939"],["faizpur-dates"]],
  [5,"Faizpur is remembered as the first Congress session held in a:","Rural setting",["Princely capital","University campus","Military cantonment"],["faizpur-first-rural"]],
  [5,"Who presided over the Faizpur Congress session?","Jawaharlal Nehru",["Subhas Chandra Bose","Mahatma Gandhi","Pattabhi Sitaramayya"],["faizpur-nehru"]],
  [5,"Which feature marked the Faizpur Congress session?","Large-scale peasant participation",["Formation of the Muslim League","Launch of Quit India","Signing of the Poona Pact"],["faizpur-peasants"]],
  [5,"At Faizpur, Nehru argued that India should not supply resources for an:","Imperialist war",["Agrarian conference","Educational commission","Anti-untouchability campaign"],["faizpur-war-stance"]],
  [6,"The Haripura meeting was the Congress's:","51st session",["39th session","42nd session","50th session"],["haripura-51st"]],
  [6,"The Haripura Congress session was held in:","1938",["1936","1939","1945"],["haripura-date"]],
  [6,"Who presided over the Haripura session of 1938?","Subhas Chandra Bose",["Jawaharlal Nehru","Mahatma Gandhi","M.A. Ansari"],["haripura-bose"]],
  [6,"The Haripura Congress reaffirmed its commitment to:","Purna Swaraj",["Dominion Status only","Separate electorates","Provincial partition"],["haripura-purna"]],
  [6,"The Haripura session rejected the federal structure proposed under the:","Government of India Act 1935",["Indian Councils Act 1909","Government of India Act 1919","Regulating Act 1773"],["haripura-federation"]],
  [6,"Haripura called for a Constituent Assembly elected on the basis of:","Adult franchise",["Property qualification only","Separate communal electorates only","Nomination by princes only"],["haripura-ca"]],
  [7,"The Tripuri Congress session was held in:","1939",["1936","1938","1942"],["tripuri-date"]],
  [7,"At Tripuri, Subhas Chandra Bose defeated:","Pattabhi Sitaramayya",["Rajendra Prasad","Maulana Azad","Jawaharlal Nehru"],["tripuri-bose-win"]],
  [7,"Whose candidate was Pattabhi Sitaramayya in the 1939 Congress presidential contest?","Mahatma Gandhi's",["Subhas Bose's","B.R. Ambedkar's","M.A. Jinnah's"],["tripuri-gandhi-candidate"]],
  [7,"What followed Bose's re-election at Tripuri?","Strong opposition from the dominant Congress leadership",["Immediate acceptance of the Wavell Plan","Formation of the Cabinet Mission","Launch of Civil Disobedience"],["tripuri-conflict"]],
  [7,"Subhas Chandra Bose resigned as Congress president on:","29 April 1939",["19 February 1938","8 August 1942","25 June 1945"],["bose-resign-1939"]],
  [7,"After the Tripuri conflict, Bose formed the:","Forward Bloc",["Swaraj Party","Home Rule League","Khudai Khidmatgar"],["forward-bloc"]],
  [8,"The Wavell Plan of 1945 centred on reconstituting the:","Viceroy's Executive Council",["Constituent Assembly","Indian National Congress","Central Legislative Assembly"],["wavell-plan-1945"]],
  [8,"Under the Wavell proposal, which two offices were to remain outside full Indianisation?","Viceroy and Commander-in-Chief",["Home and Finance Members","Governors of Bombay and Madras","Congress and League presidents"],["wavell-indianisation"]],
  [8,"The Wavell arrangement was intended as:","An interim political arrangement",["The final constitution of India","A permanent partition plan","A provincial land settlement"],["wavell-interim"]],
  [8,"The Simla Conference convened by Wavell began on:","25 June 1945",["5 November 1945","16 August 1946","3 June 1947"],["simla-date"]],
  [8,"The central deadlock at the Simla Conference concerned who would nominate:","Muslim members of the Executive Council",["Provincial governors","Members of the Simon Commission","Judges of the Federal Court"],["simla-league-demand"]],
  [8,"At Simla, the Congress rejected being treated solely as a:","Caste-Hindu organisation",["Labour organisation","Princely-state body","Revolutionary secret society"],["simla-congress-position"]],
  [9,"Which sequence is chronologically correct?","Belgaum → Madras → Faizpur → Haripura",["Madras → Belgaum → Haripura → Faizpur","Faizpur → Madras → Belgaum → Haripura","Belgaum → Faizpur → Madras → Haripura"],["belgaum-1924","madras-1927-session","faizpur-dates","haripura-date"]],
  [9,"Which sequence correctly traces the revolutionary reorganisation?","HRA formation → The Revolutionary pamphlet → Kakori action → HSRA turn",["Kakori action → HRA formation → HSRA turn → The Revolutionary pamphlet","The Revolutionary pamphlet → HRA formation → Kakori action → Non-Cooperation","HSRA turn → Kakori action → HRA formation → The Revolutionary pamphlet"],["hra-1924","hra-revolutionary-pamphlet","kakori-date","hsra-socialist"]],
  [9,"Which sequence correctly traces the 1932 crisis?","Communal Award → Gandhi's fast → Poona Pact → fast ends",["Gandhi's fast → Communal Award → fast ends → Poona Pact","Poona Pact → Communal Award → Gandhi's fast → fast ends","Communal Award → Poona Pact → Gandhi's fast → fast ends"],["communal-award-date","gandhi-fast-start","poona-pact-date","gandhi-fast-end"]],
  [9,"Which comparison of Haripura and Tripuri is correct?","Bose presided at Haripura and was re-elected against Pattabhi Sitaramayya at Tripuri",["Nehru presided at both sessions","Gandhi presided at Haripura and Bose at Belgaum","Tripuri preceded Haripura"],["haripura-bose","tripuri-bose-win","tripuri-gandhi-candidate"]],
  [9,"Which statement correctly links the Wavell Plan and Simla Conference?","The plan proposed an interim reconstituted Executive Council, but the conference failed over Muslim representation",["The plan created the Constituent Assembly and the conference adopted it unanimously","The plan launched Quit India and the conference ended Company rule","The plan introduced separate electorates and the conference repealed them"],["wavell-plan-1945","wavell-interim","simla-league-demand"]],
  [9,"The first post-war negotiations and the Simla deadlock were linked by disagreement over:","The Muslim League's claim to sole Muslim representation",["The salt tax","The Permanent Settlement","The Simon Commission membership"],["postwar-talks-fail","simla-league-demand"]],
  [10,"The first major INA trial at the Red Fort began on:","5 November 1945",["25 June 1945","16 August 1946","3 June 1947"],["ina-trial-start","simla-date"]],
  [10,"Which trio was tried in the best-known Red Fort INA case?","Shah Nawaz Khan, Prem Sahgal and Gurbaksh Singh Dhillon",["Bismil, Ashfaqulla and Rajendra Lahiri","Bhagat Singh, Rajguru and Sukhdev","Nehru, Patel and Azad"],["ina-three-defendants","ina-charge"]],
  [10,"Which combination correctly describes the INA trials?","Charges of waging war; defence by leading nationalist lawyers; widespread public sympathy",["Land-revenue charges; no nationalist defence; little public interest","Press offences; trial at Simla; no Congress response","Election offences; trial at Bombay; support only from princes"],["ina-charge","ina-defense","ina-congress-sympathy","ina-public-reaction"]],
  [10,"What constitutional arrangement did the Cabinet Mission propose in 1946?","A federal government",["Immediate unitary monarchy","Permanent military rule","Restoration of Company government"],["cabinet-federal","postwar-talks-fail"]],
  [10,"According to the NIOS account, Constituent Assembly elections gave Congress and the Muslim League respectively:","199 and 73 seats",["73 and 199 seats","199 and 199 seats","73 and 73 seats"],["ca-election-congress","ca-election-league"]],
  [10,"Which sequence correctly describes the Cabinet Mission phase?","Plan proposed → parties later consented → Constituent Assembly election → League rejected the plan",["League rejected plan → mission arrived → election → plan proposed","Election → mission arrived → plan proposed → parties consented","Plan proposed → League rejected immediately → mission arrived → election"],["cabinet-federal","cabinet-party-response","ca-election-congress","league-reject-mid1946"]],
];
