import type { ComparisonRuleId, EnglishGrammarRule } from "../core/types";

export const COMPARISON_RULES_V1: readonly EnglishGrammarRule[] = [
  {
    ruleId: "GR-CMP-001",
    category: "adjectives_adverbs_comparison",
    name: "Adverb for manner after an action verb",
    principle: "Use an adverb to describe how an action is performed when the word modifies an ordinary action verb.",
    mutationId: "MUT-CMP-ADVERB-MANNER-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "Use verbs and adjective/adverb pairs whose standard forms are distinct and whose meaning clearly expresses manner.",
  },
  {
    ruleId: "GR-CMP-002",
    category: "adjectives_adverbs_comparison",
    name: "Adjective after a linking verb",
    principle: "Use an adjective after linking verbs such as look, seem, feel, become and remain when the word describes the subject.",
    mutationId: "MUT-CMP-LINKING-ADJECTIVE-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "The verb must clearly function as a linking verb rather than an action verb.",
  },
  {
    ruleId: "GR-CMP-003",
    category: "adjectives_adverbs_comparison",
    name: "Positive degree in as ... as comparison",
    principle: "Use the positive degree of an adjective or adverb between as and as.",
    mutationId: "MUT-CMP-AS-AS-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "Both sides of the comparison must be explicit so that the as ... as frame is unmistakable.",
  },
  {
    ruleId: "GR-CMP-004",
    category: "adjectives_adverbs_comparison",
    name: "Comparative degree with than",
    principle: "Use the comparative degree when two persons, things or quantities are directly compared with than.",
    mutationId: "MUT-CMP-COMPARATIVE-THAN-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "The sentence must compare exactly two explicit entities or states and use an ordinary standard comparative.",
  },
  {
    ruleId: "GR-CMP-005",
    category: "adjectives_adverbs_comparison",
    name: "Definite article with a superlative",
    principle: "Use the before a superlative when one member is identified as highest or lowest within a stated group.",
    mutationId: "MUT-CMP-SUPERLATIVE-ARTICLE-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "Use ordinary attributive superlatives and avoid fixed expressions where article usage follows a different convention.",
  },
  {
    ruleId: "GR-CMP-006",
    category: "adjectives_adverbs_comparison",
    name: "One of the + superlative + plural noun",
    principle: "After one of the, use a superlative followed by a plural count noun when selecting one member from an extreme group.",
    mutationId: "MUT-CMP-ONE-OF-SUPERLATIVE-001",
    allowedDifficulties: ["medium", "hard"],
    ambiguityGuard: "The noun denotes a clear plural class and the sentence does not depend on a disputed article or countability choice.",
  },
  {
    ruleId: "GR-CMP-007",
    category: "adjectives_adverbs_comparison",
    name: "Avoid double comparative forms",
    principle: "Do not combine more or less with an adjective that is already in comparative form, such as more better or more easier.",
    mutationId: "MUT-CMP-DOUBLE-COMPARATIVE-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "Only standard gradable adjectives with undisputed comparative forms are used.",
  },
  {
    ruleId: "GR-CMP-008",
    category: "adjectives_adverbs_comparison",
    name: "Avoid double superlative forms",
    principle: "Do not combine most or least with an adjective that is already in superlative form, such as most fastest or most easiest.",
    mutationId: "MUT-CMP-DOUBLE-SUPERLATIVE-001",
    allowedDifficulties: ["medium", "hard"],
    ambiguityGuard: "Only ordinary standard superlatives are used; emphatic literary constructions are excluded.",
  },
  {
    ruleId: "GR-CMP-009",
    category: "adjectives_adverbs_comparison",
    name: "Standard intensifiers with comparatives",
    principle: "Use standard comparative intensifiers such as much, far, even or a little; do not use very directly before a comparative form.",
    mutationId: "MUT-CMP-COMPARATIVE-INTENSIFIER-001",
    allowedDifficulties: ["medium", "hard"],
    ambiguityGuard: "V1 tests only the clear very-versus-standard-comparative-intensifier contrast and avoids informal edge cases.",
  },
  {
    ruleId: "GR-CMP-010",
    category: "adjectives_adverbs_comparison",
    name: "Irregular degrees of comparison",
    principle: "Use the standard irregular comparative or superlative form required by the comparison, such as better/best, worse/worst and less/least.",
    mutationId: "MUT-CMP-IRREGULAR-DEGREE-001",
    allowedDifficulties: ["easy", "medium", "hard"],
    ambiguityGuard: "Only high-frequency irregular forms are used; little/fewer quantity distinctions remain outside this CP.",
  },
] as const;

export const COMPARISON_RULE_BY_ID: Readonly<Record<ComparisonRuleId, EnglishGrammarRule>> = Object.freeze(
  Object.fromEntries(COMPARISON_RULES_V1.map((rule) => [rule.ruleId, rule])) as Record<ComparisonRuleId, EnglishGrammarRule>,
);
