import type{Eng009Cp001PassageV1}from"./eng-009-cp001-authorities-v1";
export const ENG009_CP001_BREADTH_WAVE4:readonly Eng009Cp001PassageV1[]=[
{id:"ENG009-SSC-C17",title:"Why Attendance Reminders Help",topic:"school administration",template:`Schools often contact families when attendance begins to fall. A short reminder can help when absences are caused by forgotten schedules, transport confusion or simple lack of routine. The message should be clear about the dates missed and what the family needs to do next. It should not sound threatening when the problem may be temporary. A respectful tone makes the reminder more __(1)__. Schools can also look for patterns, such as repeated absence on the same day or after a timetable change. This helps staff identify whether the issue needs practical support rather than only another warning. Early contact can make follow-up more __(2)__ because problems are easier to address before they become long-term habits. Families should also know who to contact if there is a genuine difficulty. Good attendance systems therefore combine records, communication and support. Their purpose is to make regular attendance easier to __(3)__. When messages are accurate and timely, they reduce confusion and help schools act more __(4)__. The strongest approach depends on cooperation between school staff and __(5)__.`,blanks:[
{id:"C17-B1",blankNo:1,difficulty:"easy",kind:"context",answer:"effective",distractors:["formal","silent","distant"],explanation:"A respectful reminder is more likely to work, so 'effective' fits.",clue:"reminder more ..."},
{id:"C17-B2",blankNo:2,difficulty:"medium",kind:"vocabulary",answer:"manageable",distractors:["visible","private","narrow"],explanation:"Early action makes the problem easier to manage.",clue:"follow-up more ..."},
{id:"C17-B3",blankNo:3,difficulty:"easy",kind:"collocation",answer:"maintain",distractors:["borrow","divide","erase"],explanation:"The goal is to maintain regular attendance.",clue:"attendance easier to ..."},
{id:"C17-B4",blankNo:4,difficulty:"medium",kind:"context",answer:"promptly",distractors:["rarely","roughly","loosely"],explanation:"Timely messages help schools act promptly.",clue:"act more ..."},
{id:"C17-B5",blankNo:5,difficulty:"medium",kind:"vocabulary",answer:"families",distractors:["machines","buildings","forms"],explanation:"Attendance improvement needs cooperation with families.",clue:"school staff and ..."}]},
{id:"ENG009-SSC-C18",title:"A Clear Public Water Notice",topic:"civic communication",template:`When a local water supply is interrupted, residents need simple and accurate information. A useful notice should explain which area is affected, when the interruption began and what people should do. If the expected restoration time is uncertain, the notice should say so rather than giving a time that may later prove wrong. This keeps the message more __(1)__. Updates should be issued when new information becomes available. People also need to know whether water is safe to use after service returns or whether any precaution is needed. Technical details may be important for engineers, but public notices should keep the main instruction easy to __(2)__. Maps or street names can reduce confusion about the affected area. A good notice should also provide a contact point for urgent problems. Repeating the same clear format during each incident makes information easier to __(3)__. In this way, good communication reduces unnecessary calls and helps residents respond more __(4)__. The purpose of the notice is not to explain every technical cause; it is to give the public information that is useful, timely and __(5)__.`,blanks:[
{id:"C18-B1",blankNo:1,difficulty:"medium",kind:"vocabulary",answer:"trustworthy",distractors:["formal","long","private"],explanation:"An honest notice is more trustworthy.",clue:"message more ..."},
{id:"C18-B2",blankNo:2,difficulty:"easy",kind:"context",answer:"understand",distractors:["hide","borrow","divide"],explanation:"The main instruction should be easy for residents to understand.",clue:"easy to ..."},
{id:"C18-B3",blankNo:3,difficulty:"medium",kind:"collocation",answer:"recognise",distractors:["remove","repeat","ignore"],explanation:"A consistent format makes important information easier to recognise.",clue:"information easier to ..."},
{id:"C18-B4",blankNo:4,difficulty:"medium",kind:"context",answer:"appropriately",distractors:["privately","rarely","loosely"],explanation:"Clear instructions help residents respond appropriately.",clue:"respond more ..."},
{id:"C18-B5",blankNo:5,difficulty:"easy",kind:"vocabulary",answer:"clear",distractors:["distant","silent","narrow"],explanation:"Public notices should be useful, timely and clear.",clue:"useful, timely and ..."}]}
];