export const HIS_CP001_SOURCES_V1=[
  ["NIOS-HISTORY-315-LESSON2-PREHISTORIC","NIOS History 315 — Lesson 2: The Earliest Societies","https://digital.nios.ac.in/content/315en/315_History_Eng_Lesson2.pdf","textbook"],
  ["NIOS-HISTORY-315-LESSON3-HARAPPAN","NIOS History 315 — Lesson 3: The Harappan Civilization","https://digital.nios.ac.in/content/315en/315_History_Eng_Lesson3.pdf","textbook"],
  ["NCERT-THEMES-INDIAN-HISTORY-I-HARAPPAN","NCERT Themes in Indian History I — Bricks, Beads and Bones: The Harappan Civilisation","https://ncert.nic.in/textbook.php?lehs1=3-4","textbook"],
  ["UNESCO-BHIMBETKA-925","UNESCO World Heritage Centre — Rock Shelters of Bhimbetka","https://whc.unesco.org/en/list/925/","official"],
  ["UNESCO-DHOLAVIRA-1645","UNESCO World Heritage Centre — Dholavira: a Harappan City","https://whc.unesco.org/en/list/1645/","official"],
] as const;
type Fact=readonly[id:string,sentence:string,sourceIds:readonly string[]];
export const HIS_CP001_FACTS_V1:readonly Fact[]=[
  ["pre-lower-tools","Lower Palaeolithic assemblages are marked by heavy tools such as handaxes, cleavers and choppers.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-middle-tools","Flake tools became prominent in the Middle Palaeolithic.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-upper-tools","Burins and scrapers are characteristic Upper Palaeolithic tools in the NIOS school-level sequence.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-mesolithic-microliths","The Mesolithic is strongly associated with small stone tools called microliths.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-neolithic-polished-tools","Ground and polished stone tools are a characteristic Neolithic feature.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-neolithic-food-production","The Neolithic saw cultivation, animal domestication and more settled village life.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-bhimbetka-rock-art","Bhimbetka is known for prehistoric rock shelters and a long sequence of rock paintings.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC","UNESCO-BHIMBETKA-925"]],
  ["pre-bhimbetka-location","Bhimbetka lies in Madhya Pradesh, south of Bhopal.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC","UNESCO-BHIMBETKA-925"]],
  ["pre-langhnaj-location","Langhnaj is an important Mesolithic site in Gujarat.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-chopani-mando-location","Chopani Mando is a Mesolithic site in the Belan Valley of Uttar Pradesh.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["pre-sanganakallu-location","Sanganakallu is an important prehistoric site in Karnataka.",["NIOS-HISTORY-315-LESSON2-PREHISTORIC"]],
  ["har-discovery-harappa","Harappa was excavated under D. R. Sahni in the 1920–22 discovery phase.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-discovery-mohenjo","Mohenjo-daro was excavated under R. D. Banerji in the 1920–22 discovery phase.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-mature-dates","NIOS places the Mature Harappan phase at about 2600–1900 BCE.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-phases-order","The standard phase sequence is Early Harappan, Mature Harappan and Late Harappan.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-script","The Harappan script remains undeciphered.",["NIOS-HISTORY-315-LESSON3-HARAPPAN","NCERT-THEMES-INDIAN-HISTORY-I-HARAPPAN"]],
  ["har-harappa-river","Harappa is situated on/near the Ravi river system in Punjab, Pakistan.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-mohenjo-river","Mohenjo-daro is located in Sindh in the Indus river region.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-kalibangan-location","Kalibangan is a Harappan site in Rajasthan.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-lothal-location","Lothal is a Harappan site in Gujarat.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-rakhigarhi-location","Rakhigarhi is a Harappan site in Haryana.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-dholavira-location","Dholavira is a Harappan city on Khadir island in Gujarat.",["NIOS-HISTORY-315-LESSON3-HARAPPAN","UNESCO-DHOLAVIRA-1645"]],
  ["har-great-bath","The Great Bath is one of the best-known public structures at Mohenjo-daro.",["NIOS-HISTORY-315-LESSON3-HARAPPAN","NCERT-THEMES-INDIAN-HISTORY-I-HARAPPAN"]],
  ["har-lothal-dockyard","A large brick structure at Lothal has traditionally been identified as a dockyard in school-level history.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-kalibangan-plough","Kalibangan has evidence of plough marks in a field.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-banawali-plough","A terracotta model of a plough has been found at Banawali.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-dholavira-water","Dholavira is notable for an elaborate system of reservoirs and water management.",["UNESCO-DHOLAVIRA-1645"]],
  ["har-dancing-girl","The bronze figure popularly called the Dancing Girl was found at Mohenjo-daro.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-woven-cloth","Evidence of woven cloth is reported from Mohenjo-daro.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-bead-shops","Bead-makers' shops have been found at Chanhudaro and Lothal.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-rice-sites","NIOS notes evidence of rice from Lothal and Rangpur.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-copper-khetri","The Khetri region of Rajasthan is noted as an important copper source in Harappan trade networks.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-steatite-beads","Steatite was among the materials used for Harappan bead making.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
  ["har-no-iron","School-level Harappan accounts list copper, bronze, gold, silver and lead, but not iron.",["NIOS-HISTORY-315-LESSON3-HARAPPAN"]],
];
export const HIS_CP001_FACT_BY_ID_V1=new Map(HIS_CP001_FACTS_V1.map(f=>[f[0],f] as const));
export const HIS_CP001_SOURCE_IDS_V1=new Set<string>(HIS_CP001_SOURCES_V1.map(s=>s[0]));