import type { PolCp017ReviewSeed } from "./pol-cp017-review-seed-types";

const S = ["LEGISLATIVE-DEPT-CONSTITUTION-2026"] as const;

export const POL_CP017_SEEDS_C: readonly PolCp017ReviewSeed[] = Object.freeze([
  { qlId:"POL-017-QL-013", difficulty:"Medium", stem:"Which Article deals with adjudication of disputes over inter-State river waters?", answer:"Article 262", distractors:["Article 256","Article 263","Article 293"], explanation:"Article 262 empowers Parliament to provide a legal mechanism for adjudicating disputes concerning inter-State rivers or river valleys.", sourceIds:S },
  { qlId:"POL-017-QL-013", difficulty:"Medium", stem:"Who may create a legal mechanism for adjudicating inter-State river-water disputes under Article 262?", answer:"Parliament", distractors:["Each State Legislature separately","Inter-State Council alone","Finance Commission"], explanation:"Article 262 places the legislative power to provide for adjudication of inter-State river-water disputes with Parliament.", sourceIds:S },
  { qlId:"POL-017-QL-013", difficulty:"Medium", stem:"May Parliament exclude Supreme Court jurisdiction over specified inter-State river-water disputes?", answer:"Yes", distractors:["No","Only during an Emergency","Only with every State's consent"], explanation:"Article 262(2) expressly permits Parliament to exclude the jurisdiction of the Supreme Court and other courts over covered water disputes.", sourceIds:S },
  { qlId:"POL-017-QL-013", difficulty:"Medium", stem:"Article 262 concerns disputes relating to the use, distribution or control of what?", answer:"Waters of inter-State rivers or river valleys", distractors:["All municipal water supplies","Only coastal waters","Only groundwater within one district"], explanation:"The constitutional subject is specifically the waters of an inter-State river or river valley, including use, distribution and control disputes.", sourceIds:S },

  { qlId:"POL-017-QL-014", difficulty:"Medium", stem:"Who may establish an Inter-State Council under Article 263?", answer:"President", distractors:["Prime Minister alone","Rajya Sabha","Supreme Court"], explanation:"Article 263 authorises the President to establish an Inter-State Council by order when public interest would be served.", sourceIds:S },
  { qlId:"POL-017-QL-014", difficulty:"Medium", stem:"What constitutional condition must the President consider before establishing an Inter-State Council?", answer:"Public interest would be served", distractors:["A National Emergency is in force","Every State has given consent","A Finance Commission has recommended it"], explanation:"Article 263 makes public interest the constitutional trigger for establishing an Inter-State Council.", sourceIds:S },
  { qlId:"POL-017-QL-014", difficulty:"Medium", stem:"Which is one constitutional function that may be assigned to an Inter-State Council?", answer:"Investigating and discussing subjects of common Union-State interest", distractors:["Passing binding national laws","Removing Governors","Deciding criminal appeals"], explanation:"Article 263 allows the Council to investigate and discuss subjects in which States or the Union and States share a common interest.", sourceIds:S },
  { qlId:"POL-017-QL-014", difficulty:"Medium", stem:"Who defines the duties, organisation and procedure of an Inter-State Council established under Article 263?", answer:"President by order", distractors:["Supreme Court","Finance Commission","Election Commission"], explanation:"Article 263 lets the President's establishing order define the Council's duties, organisation and procedure.", sourceIds:S },

  { qlId:"POL-017-QL-015", difficulty:"Medium", stem:"Under Article 268, specified stamp duties are levied by whom?", answer:"Government of India", distractors:["State Governments only","Local authorities","Finance Commission"], explanation:"Article 268 places the levy of specified Union List stamp duties with the Government of India.", sourceIds:S },
  { qlId:"POL-017-QL-015", difficulty:"Medium", stem:"Outside Union territories, who generally collects the Article 268 stamp duties within a State?", answer:"The State", distractors:["Government of India only","GST Council","Reserve Bank of India"], explanation:"Article 268 distinguishes levy from collection: outside Union territories, the State where the duty is leviable generally collects it.", sourceIds:S },
  { qlId:"POL-017-QL-015", difficulty:"Medium", stem:"Do proceeds of Article 268 duties attributable to a State form part of the Consolidated Fund of India?", answer:"No", distractors:["Yes","Only for one year","Only after Finance Commission approval"], explanation:"Article 268 provides that proceeds attributable to a State do not enter the Consolidated Fund of India and are assigned to that State.", sourceIds:S },
  { qlId:"POL-017-QL-015", difficulty:"Medium", stem:"Which description best fits Article 268 duties?", answer:"Union levies them, but States collect and appropriate specified proceeds", distractors:["States levy them and Union collects them","Union levies and keeps all proceeds","Local bodies levy and share them"], explanation:"Article 268 separates the Union's levy from State collection and appropriation of the relevant proceeds.", sourceIds:S },

  { qlId:"POL-017-QL-016", difficulty:"Medium", stem:"Article 269 concerns certain taxes that are levied and collected by whom but assigned to the States?", answer:"Union", distractors:["States","Local authorities","Finance Commission"], explanation:"Article 269 follows the model of Union levy and collection with constitutional assignment of specified proceeds to the States.", sourceIds:S },
  { qlId:"POL-017-QL-016", difficulty:"Medium", stem:"Who levies and collects GST on inter-State supplies under Article 269A?", answer:"Government of India", distractors:["Destination State alone","Origin State alone","GST Council directly"], explanation:"Article 269A provides for levy and collection of inter-State GST by the Government of India before apportionment between Union and States.", sourceIds:S },
  { qlId:"POL-017-QL-016", difficulty:"Medium", stem:"How is inter-State GST under Article 269A apportioned between Union and States?", answer:"By parliamentary law on GST Council recommendations", distractors:["By each State independently","By Supreme Court order","By annual presidential ordinance"], explanation:"Article 269A requires apportionment in the manner Parliament provides by law on recommendations of the GST Council.", sourceIds:S },
  { qlId:"POL-017-QL-016", difficulty:"Medium", stem:"Which Article is specifically associated with GST on inter-State trade or commerce?", answer:"Article 269A", distractors:["Article 268","Article 270","Article 275"], explanation:"Article 269A is the Constitution's specific revenue-distribution provision for GST on inter-State supplies.", sourceIds:S },

  { qlId:"POL-017-QL-017", difficulty:"Medium", stem:"Article 270 mainly concerns which fiscal relationship?", answer:"Distribution of specified Union taxes and duties between Union and States", distractors:["State borrowing from markets","Inter-State water disputes","Creation of Legislative Councils"], explanation:"Article 270 provides the principal constitutional framework for distributing specified Union tax and duty proceeds between Union and States.", sourceIds:S },
  { qlId:"POL-017-QL-017", difficulty:"Medium", stem:"Which of the following is excluded from the ordinary Article 270 divisible pool?", answer:"Article 271 surcharge", distractors:["Every tax in the Union List","All State taxes","All grants under Article 282"], explanation:"Article 270 excludes Article 271 surcharge proceeds, along with other constitutionally specified exclusions, from its ordinary distribution framework.", sourceIds:S },
  { qlId:"POL-017-QL-017", difficulty:"Medium", stem:"For whose purposes may Parliament impose a surcharge under Article 271?", answer:"Union", distractors:["States collectively","Local bodies only","Inter-State Council"], explanation:"Article 271 authorises a surcharge for Union purposes and places the entire proceeds in the Consolidated Fund of India.", sourceIds:S },
  { qlId:"POL-017-QL-017", difficulty:"Medium", stem:"Does Article 271 permit a surcharge on GST under Article 246A?", answer:"No", distractors:["Yes","Only on inter-State GST","Only with State consent"], explanation:"The current text of Article 271 expressly excludes GST under Article 246A from the surcharge power.", sourceIds:S },

  { qlId:"POL-017-QL-018", difficulty:"Medium", stem:"Which Article provides grants-in-aid of revenues to States determined to need assistance?", answer:"Article 275", distractors:["Article 268","Article 282","Article 293"], explanation:"Article 275 authorises grants-in-aid from the Consolidated Fund of India to States Parliament determines to need assistance.", sourceIds:S },
  { qlId:"POL-017-QL-018", difficulty:"Medium", stem:"From which fund are Article 275 grants-in-aid charged?", answer:"Consolidated Fund of India", distractors:["Public Account of India","State Contingency Fund","Consolidated Fund of the receiving State"], explanation:"Article 275 charges the constitutionally provided grants-in-aid on the Consolidated Fund of India.", sourceIds:S },
  { qlId:"POL-017-QL-018", difficulty:"Medium", stem:"Must Article 275 grants be identical for every State receiving assistance?", answer:"No", distractors:["Yes","Only if States are equal in population","Only during an Emergency"], explanation:"Article 275 expressly allows different sums to be fixed for different States according to the constitutional grant framework.", sourceIds:S },
  { qlId:"POL-017-QL-018", difficulty:"Medium", stem:"Who may by law provide the sums paid as Article 275 grants-in-aid?", answer:"Parliament", distractors:["GST Council","Supreme Court","Inter-State Council"], explanation:"Article 275 states that such sums as Parliament may by law provide are charged as grants-in-aid to eligible States.", sourceIds:S },
]);
