import type { Avg001Cp004PairLexicon } from "./cp004-localization-types";

export const AVG001_CP004_PAIR_HI: Record<string, Avg001Cp004PairLexicon> = {
  boysGirlsMarks: { first: "लड़के", second: "लड़कियाँ", firstMeasure: "लड़कों के अंकों का औसत", secondMeasure: "लड़कियों के अंकों का औसत", result: "सभी विद्यार्थियों के अंकों का संयुक्त औसत", secondCount: "लड़कियों की संख्या", unit: "marks" },
  morningEveningOutput: { first: "सुबह की पाली के कर्मी", second: "शाम की पाली के कर्मी", firstMeasure: "सुबह की पाली का औसत उत्पादन", secondMeasure: "शाम की पाली का औसत उत्पादन", result: "दोनों पालियों का संयुक्त औसत उत्पादन", secondCount: "शाम की पाली के कर्मियों की संख्या", unit: "units" },
  permanentContractSalary: { first: "स्थायी कर्मचारी", second: "अनुबंध कर्मचारी", firstMeasure: "स्थायी कर्मचारियों का औसत वेतन", secondMeasure: "अनुबंध कर्मचारियों का औसत वेतन", result: "सभी कर्मचारियों का संयुक्त औसत वेतन", secondCount: "अनुबंध कर्मचारियों की संख्या", unit: "currency" },
  urbanRuralSales: { first: "शहरी बिक्री केंद्र", second: "ग्रामीण बिक्री केंद्र", firstMeasure: "शहरी केंद्रों की औसत बिक्री", secondMeasure: "ग्रामीण केंद्रों की औसत बिक्री", result: "सभी केंद्रों की संयुक्त औसत बिक्री", secondCount: "ग्रामीण बिक्री केंद्रों की संख्या", unit: "currency" },
  twoBatchesWeight: { first: "पहले लॉट के पार्सल", second: "दूसरे लॉट के पार्सल", firstMeasure: "पहले लॉट का औसत पार्सल-वजन", secondMeasure: "दूसरे लॉट का औसत पार्सल-वजन", result: "दोनों लॉटों का संयुक्त औसत पार्सल-वजन", secondCount: "दूसरे लॉट के पार्सलों की संख्या", unit: "kg" },
  dayNightPassengers: { first: "दिन की यात्राएँ", second: "रात की यात्राएँ", firstMeasure: "दिन की यात्राओं में यात्रियों की औसत संख्या", secondMeasure: "रात की यात्राओं में यात्रियों की औसत संख्या", result: "सभी यात्राओं में यात्रियों की संयुक्त औसत संख्या", secondCount: "रात की यात्राओं की संख्या", unit: "none" },
  menWomenAge: { first: "पुरुष", second: "महिलाएँ", firstMeasure: "पुरुषों की औसत आयु", secondMeasure: "महिलाओं की औसत आयु", result: "सभी लोगों की संयुक्त औसत आयु", secondCount: "महिलाओं की संख्या", unit: "years" },
  twoSectionsScores: { first: "अनुभाग 1 के विद्यार्थी", second: "अनुभाग 2 के विद्यार्थी", firstMeasure: "अनुभाग 1 के विद्यार्थियों के अंकों का औसत", secondMeasure: "अनुभाग 2 के विद्यार्थियों के अंकों का औसत", result: "पूरी कक्षा के अंकों का संयुक्त औसत", secondCount: "अनुभाग 2 के विद्यार्थियों की संख्या", unit: "marks" },
  branchesRevenue: { first: "पहले क्षेत्र की शाखाएँ", second: "दूसरे क्षेत्र की शाखाएँ", firstMeasure: "पहले क्षेत्र की शाखाओं का औसत राजस्व", secondMeasure: "दूसरे क्षेत्र की शाखाओं का औसत राजस्व", result: "सभी शाखाओं का संयुक्त औसत राजस्व", secondCount: "दूसरे क्षेत्र की शाखाओं की संख्या", unit: "currency" },
  machinesOutput: { first: "पुरानी मशीनें", second: "नई मशीनें", firstMeasure: "पुरानी मशीनों का औसत उत्पादन", secondMeasure: "नई मशीनों का औसत उत्पादन", result: "सभी मशीनों का संयुक्त औसत उत्पादन", secondCount: "नई मशीनों की संख्या", unit: "units" },
  departmentsSalary: { first: "विभाग 1 के कर्मचारी", second: "विभाग 2 के कर्मचारी", firstMeasure: "विभाग 1 के कर्मचारियों का औसत वेतन", secondMeasure: "विभाग 2 के कर्मचारियों का औसत वेतन", result: "दोनों विभागों का संयुक्त औसत वेतन", secondCount: "विभाग 2 के कर्मचारियों की संख्या", unit: "currency" },
  parcelsWeight: { first: "बैच 1 के पैकेज", second: "बैच 2 के पैकेज", firstMeasure: "बैच 1 के पैकेजों का औसत वजन", secondMeasure: "बैच 2 के पैकेजों का औसत वजन", result: "सभी पैकेजों का संयुक्त औसत वजन", secondCount: "बैच 2 के पैकेजों की संख्या", unit: "kg" },
  teamsRuns: { first: "टीम 1 के खिलाड़ी", second: "टीम 2 के खिलाड़ी", firstMeasure: "टीम 1 के खिलाड़ियों के औसत रन", secondMeasure: "टीम 2 के खिलाड़ियों के औसत रन", result: "दोनों टीमों का संयुक्त बल्लेबाजी औसत", secondCount: "टीम 2 के खिलाड़ियों की संख्या", unit: "runs" },
  hostelGroupsExpense: { first: "छात्रावास 1 के निवासी", second: "छात्रावास 2 के निवासी", firstMeasure: "छात्रावास 1 का औसत दैनिक खर्च", secondMeasure: "छात्रावास 2 का औसत दैनिक खर्च", result: "दोनों छात्रावासों का संयुक्त औसत दैनिक खर्च", secondCount: "छात्रावास 2 के निवासियों की संख्या", unit: "currency" },
  villagesYield: { first: "गाँव 1 के खेत", second: "गाँव 2 के खेत", firstMeasure: "गाँव 1 के खेतों की औसत उपज", secondMeasure: "गाँव 2 के खेतों की औसत उपज", result: "दोनों गाँवों की संयुक्त औसत उपज", secondCount: "गाँव 2 के खेतों की संख्या", unit: "units" },
  abstractTwoGroups: { first: "पहले समूह के मान", second: "दूसरे समूह के मान", firstMeasure: "पहले समूह के मानों का औसत", secondMeasure: "दूसरे समूह के मानों का औसत", result: "दोनों समूहों का संयुक्त औसत", secondCount: "दूसरे समूह के मानों की संख्या", unit: "none" },
};
