const editorialStemOverrides: Record<string, string> = {
  "AVG-QL-001": "The average marks of {count} students are {average}. Find their total marks.",
  "AVG-QL-002": "A factory produces an average of {average} units per day for {count} days. Find the total production.",
  "AVG-QL-003": "A shop records average daily sales of ₹{average} for {count} days. Find the total sales.",
  "AVG-QL-005": "A bus carries an average of {average} passengers per trip over {count} trips. Find the total number of passengers carried.",
  "AVG-QL-006": "A family's average daily expenditure is ₹{average} for {count} days. Find the total expenditure.",
  "AVG-QL-013": "A factory produces {total} units at an average of {average} units per day. Find the number of working days.",
  "AVG-QL-018": "A family spends ₹{total} at an average of ₹{average} per day. Find the number of days.",
  "AVG-QL-019": "The average score in {count} tests is {average}. The total score in the first {knownCount} tests is {knownTotal}. Find the score in the remaining test.",
  "AVG-QL-020": "The average output over {count} shifts is {average} units. The first {knownCount} shifts produce {knownTotal} units. Find the output in the remaining shift.",
  "AVG-QL-021": "The average daily sale for {count} days is ₹{average}. Sales in the first {knownCount} days total ₹{knownTotal}. Find the sale on the remaining day.",
  "AVG-QL-022": "A family's average daily expenditure for {count} days is ₹{average}. Its expenditure in the first {knownCount} days is ₹{knownTotal}. Find the expenditure on the remaining day.",
  "AVG-QL-023": "A rider covers an average of {average} km per day for {count} days. The distance covered in the first {knownCount} days is {knownTotal} km. Find the distance covered on the remaining day.",

  "AVG-QL-073": "What is the mean of the {count} consecutive integers from {firstTerm} to {lastTerm}?",
  "AVG-QL-074": "A row contains {count} seats numbered consecutively from {firstTerm} to {lastTerm}. Find the mean seat number.",
  "AVG-QL-075": "The house numbers from {firstTerm} to {lastTerm} are consecutive. Find their mean.",
  "AVG-QL-076": "The first and last of {count} consecutive integers are {firstTerm} and {lastTerm}. Find their mean.",
  "AVG-QL-077": "An arithmetic progression begins at {firstTerm}, ends at {lastTerm}, and has common difference {commonDifference}. Find its mean.",
  "AVG-QL-078": "Production targets rise uniformly from {firstTerm} to {lastTerm} in steps of {commonDifference}. Find the mean target.",
  "AVG-QL-079": "The equally spaced numbers {firstTerm}, {nextTerm}, …, {lastTerm} differ by {commonDifference}. Find their mean.",
  "AVG-QL-080": "A student's {count} scores increase by {commonDifference} each test, from {firstTerm} to {lastTerm}. Find the mean score.",
  "AVG-QL-081": "Across {count} shifts, the targets increase uniformly from {firstTerm} units to {lastTerm} units, by {commonDifference} each shift. Find the mean target.",
  "AVG-QL-082": "The {count} equally spaced terms from {firstTerm} to {lastTerm} differ by {commonDifference}. Find their mean.",
  "AVG-QL-083": "The {count} prices are equally spaced from ₹{firstTerm} to ₹{lastTerm}, differing by ₹{commonDifference}. Find the mean price.",
  "AVG-QL-084": "A set of {count} equally spaced numbers has first term {firstTerm} and last term {lastTerm}. Find its mean.",
  "AVG-QL-085": "Output in {count} successive periods changes by a fixed amount from {firstTerm} units to {lastTerm} units. Find the mean output.",
  "AVG-QL-086": "There are {count} consecutive integers from {firstTerm} to {lastTerm}. Find their mean.",
  "AVG-QL-087": "The mean of {count} consecutive integers is {average}. Find the middle integer.",
  "AVG-QL-088": "The mean of {count} consecutive even numbers is {average}. Find the middle term.",
  "AVG-QL-089": "The mean of {count} consecutive odd numbers is {average}. Find the middle term.",
  "AVG-QL-090": "The mean of {count} consecutive seat numbers is {average}. Find the middle seat number.",
  "AVG-QL-091": "The mean of {count} consecutive house numbers is {average}. Find the middle house number.",
  "AVG-QL-092": "The {count} production targets are equally spaced by {commonDifference} units and have mean {average}. Find the middle target.",
  "AVG-QL-093": "The {count} equally spaced scores have mean {average}. Find the middle score.",
  "AVG-QL-094": "An arithmetic progression has {count} terms, common difference {commonDifference}, and mean {average}. Find its middle term.",
  "AVG-QL-095": "A {count}-day target schedule changes by an equal amount each day and has mean {average} units. Find the middle day's target.",
  "AVG-QL-096": "The {count} equally spaced terms have mean {average}. Find the middle term.",
  "AVG-QL-097": "The {count} equally spaced prices have mean ₹{average}. Find the middle price.",
  "AVG-QL-098": "The {count} equally spaced merit scores have mean {average}. Find the central score.",
  "AVG-QL-099": "The mean of {count} consecutive integers is {average}. Find the greatest integer.",
  "AVG-QL-100": "The mean of {count} consecutive integers is {average}. Find the least integer.",
  "AVG-QL-101": "The mean of {count} consecutive even numbers is {average}. Find the greatest term.",
  "AVG-QL-102": "The mean of {count} consecutive odd numbers is {average}. Find the least term.",
  "AVG-QL-103": "The {count} seat numbers are equally spaced by {commonDifference} and have mean {average}. Find the greatest seat number.",
  "AVG-QL-104": "The {count} production targets are equally spaced by {commonDifference} units and have mean {average}. Find the least target.",
  "AVG-QL-105": "An arithmetic progression has {count} terms, common difference {commonDifference}, and mean {average}. Find its greatest term.",
  "AVG-QL-106": "The {count} prices are equally spaced by ₹{commonDifference} and have mean ₹{average}. Find the least price.",
  "AVG-QL-107": "If the mean of {count} consecutive integers is {average}, what is the greatest integer?",
  "AVG-QL-108": "If {count} consecutive integers have mean {average}, what is the least integer?",
  "AVG-QL-109": "Targets for {count} shifts rise by {commonDifference} units each time and have mean {average} units. Find the greatest target.",
  "AVG-QL-110": "The {count} scores are equally spaced by {commonDifference} and have mean {average}. Find the least score.",
  "AVG-QL-111": "Find the mean of the {count} consecutive even numbers from {firstTerm} to {lastTerm}.",
  "AVG-QL-112": "Find the mean of the {count} consecutive odd numbers from {firstTerm} to {lastTerm}.",
  "AVG-QL-113": "Find the mean of {count} consecutive even numbers beginning with {firstTerm}.",
  "AVG-QL-114": "Find the mean of {count} consecutive odd numbers beginning with {firstTerm}.",
  "AVG-QL-115": "A block contains {count} consecutive even-numbered seats from {firstTerm} to {lastTerm}. Find the mean seat number.",
  "AVG-QL-116": "The first of {count} consecutive even numbers is {firstTerm}. Find their mean.",
  "AVG-QL-117": "The last of {count} consecutive odd numbers is {lastTerm}. Find their mean.",
  "AVG-QL-118": "Odd-numbered houses range from {firstTerm} to {lastTerm}. Find the mean house number.",
  "AVG-QL-119": "Even roll numbers range from {firstTerm} to {lastTerm}. Find their mean.",
  "AVG-QL-120": "The first of {count} consecutive odd numbers is {firstTerm}. Find their mean.",
  "AVG-QL-121": "The last of {count} consecutive even numbers is {lastTerm}. Find their mean.",
  "AVG-QL-122": "A factory labels {count} batches with consecutive even numbers from {firstTerm} to {lastTerm}. Find the mean batch number.",

  "AVG-QL-197": "A batter averages {oldAverage} runs after {inningsCount} innings. Find the score needed in the next innings to make the average {newAverage}.",

  "AVG-QL-212": "{count1} urban outlets average sales of ₹{average1}, while {count2} rural outlets average ₹{average2}. Find the average sales for all outlets.",

  "AVG-QL-225": "Three classes have {count1}, {count2}, and {count3} students. Their average marks are {average1}, {average2}, and {average3}. Find the average marks for all students.",
  "AVG-QL-226": "Three shifts have {count1}, {count2}, and {count3} workers. Their average outputs are {average1}, {average2}, and {average3} units. Find the average output for all workers.",
  "AVG-QL-227": "Three departments have {count1}, {count2}, and {count3} employees. Their average salaries are ₹{average1}, ₹{average2}, and ₹{average3}. Find the average salary for all employees.",
  "AVG-QL-228": "Three lots have {count1}, {count2}, and {count3} packages. Their average weights are {average1}, {average2}, and {average3} kg. Find the average weight for all packages.",
  "AVG-QL-229": "Three areas have {count1}, {count2}, and {count3} outlets. Their average sales are ₹{average1}, ₹{average2}, and ₹{average3}. Find the average sales for all outlets.",
  "AVG-QL-230": "Three groups have {count1}, {count2}, and {count3} people. Their average ages are {average1}, {average2}, and {average3} years. Find the average age of everyone.",
  "AVG-QL-231": "Four batches have {count1}, {count2}, {count3}, and {count4} candidates. Their average scores are {average1}, {average2}, {average3}, and {average4} marks. Find the average score for all candidates.",
  "AVG-QL-232": "Four factory units have {count1}, {count2}, {count3}, and {count4} machines. Their average outputs are {average1}, {average2}, {average3}, and {average4} units. Find the average output for all machines.",
  "AVG-QL-233": "Four teams have {count1}, {count2}, {count3}, and {count4} players. Their batting averages are {average1}, {average2}, {average3}, and {average4} runs. Find the average for all players.",
  "AVG-QL-234": "Four departments have {count1}, {count2}, {count3}, and {count4} employees. Their average salaries are ₹{average1}, ₹{average2}, ₹{average3}, and ₹{average4}. Find the average salary for all employees.",
  "AVG-QL-235": "Four lots have {count1}, {count2}, {count3}, and {count4} parcels. Their average weights are {average1}, {average2}, {average3}, and {average4} kg. Find the average weight for all parcels.",
  "AVG-QL-236": "Four groups have {count1}, {count2}, {count3}, and {count4} values. Their averages are {average1}, {average2}, {average3}, and {average4}. Find the average of all values.",

  "AVG-QL-237": "{knownCount} boys average {knownAverage} marks. The girls average {unknownAverage} marks, and the whole class averages {combinedAverage} marks. Find the number of girls.",
  "AVG-QL-238": "{knownCount} morning-shift workers average {knownAverage} units. Evening-shift workers average {unknownAverage} units. All workers average {combinedAverage} units. How many work the evening shift?",
  "AVG-QL-239": "{knownCount} permanent employees average ₹{knownAverage}. Contract employees average ₹{unknownAverage}, and all employees average ₹{combinedAverage}. Find the number of contract employees.",
  "AVG-QL-240": "{knownCount} urban outlets average sales of ₹{knownAverage}. Rural outlets average ₹{unknownAverage}, and all outlets average ₹{combinedAverage}. Find the number of rural outlets.",
  "AVG-QL-241": "The first lot has {knownCount} parcels averaging {knownAverage} kg. The second lot averages {unknownAverage} kg, and both lots average {combinedAverage} kg. Find the number of parcels in the second lot.",
  "AVG-QL-242": "{knownCount} day trips average {knownAverage} passengers. Night trips average {unknownAverage} passengers, and all trips average {combinedAverage} passengers. Find the number of night trips.",
  "AVG-QL-243": "{knownCount} men average {knownAverage} years. The women average {unknownAverage} years, and all people average {combinedAverage} years. Find the number of women.",
  "AVG-QL-244": "Section A has {knownCount} students averaging {knownAverage} marks. Section B averages {unknownAverage} marks. The whole class averages {combinedAverage} marks. How many students are in Section B?",
  "AVG-QL-245": "The first region has {knownCount} branches averaging ₹{knownAverage}. The second averages ₹{unknownAverage}. All branches average ₹{combinedAverage}. How many are in the second region?",
  "AVG-QL-246": "{knownCount} older machines average {knownAverage} units. Newer machines average {unknownAverage} units, and all machines average {combinedAverage} units. Find the number of newer machines.",
  "AVG-QL-247": "Department A has {knownCount} employees averaging ₹{knownAverage}. Department B averages ₹{unknownAverage}. All employees average ₹{combinedAverage}. How many are in Department B?",
};

export function applyAvg001EditorialStem<T extends { qlId: string; template: string }>(entry: T): T {
  const template = editorialStemOverrides[entry.qlId];
  return template ? { ...entry, template } : entry;
}

export function getAvg001EditorialStemOverrideIds() {
  return Object.keys(editorialStemOverrides);
}
