export const TSD_CP008_DISCOVERY_CANDIDATES = Object.freeze([
  "findCrossingTimeForOppositeDirectionTrains",
  "findCrossingTimeForSameDirectionTrains",
  "findOvertakeTimeForTrains",
  "findRelativeSpeedFromTrainCrossing",
  "findUnknownTrainLengthFromCrossing",
  "findUnknownTrainSpeedFromCrossing",
  "findSumOfTrainLengthsFromCrossing",
  "findLengthRatioFromCrossingTimes",
  "findSpeedRatioFromCrossingTimes",
  "findTrainCrossingTimeForMovingPersonSameDirection",
  "findTrainCrossingTimeForMovingPersonOppositeDirection",
  "findTrainSpeedFromTwoMovingObservers",
  "findObserverSpeedFromTrainCrossingTimes",
  "findMeetingTimeBetweenStations",
  "findStationDistanceFromDepartureAndMeetingData",
  "findTrainMeetingPointBetweenStations",
  "findStaggeredTrainDepartureMeetingTime",
  "findDepartureDelayFromMeetingState",
  "findPostMeetingTimesToStations",
  "findSpeedRatioFromPostMeetingTrainTimes",
  "findStationDistanceFromPostMeetingTrainTimes",
  "findTimeGapBetweenPassingTwoObservers",
  "findTimeGapBetweenTwoTrainCrossings",
  "findUnknownPlatformLengthUsingTwoTrains",
  "findUnknownTrainLengthUsingCommonPlatform",
  "findDualPlatformOrBridgeState",
  "findTrainOvertakeClockTime",
  "findTrainMeetingClockTime",
  "findCrossingAfterOneTrainStops",
  "findCrossingAfterOneTrainChangesSpeed",
  "findSequenceOfTrainCrossings",
  "findMaximumOrCompleteOverlapDuration",
  "reconstructTrainNetworkCaselet",
  "detectContradictoryTrainStatements",
  "classifyTrainSystemAsPossibleUniqueOrMultiple",
  "verifyTrainSystemClaim",
  "solveTrainSystemDataSufficiency",
] as const);

export type TsdCp008SolveMode = typeof TSD_CP008_DISCOVERY_CANDIDATES[number];

export const TSD_CP008_DISCOVERY_AUTHORITY = Object.freeze({
  checkpointId: "TSD-CP-008" as const,
  chapterId: "TSD-002" as const,
  title: "Train-Train Relative Motion and Station Systems",
  dependencyCheckpoints: Object.freeze(["TSD-CP-004", "TSD-CP-005", "TSD-CP-007"] as const),
  sourceCandidateCount: TSD_CP008_DISCOVERY_CANDIDATES.length,
  ownership: Object.freeze([
    "two finite-length trains crossing, meeting or overtaking",
    "finite-length train crossing a moving observer",
    "relative-speed recovery from train-train or train-observer crossing evidence",
    "station-to-station meeting systems with one or two trains",
    "post-meeting travel-time identities between stations",
    "common-platform or shared fixed-object evidence involving two trains",
    "clock-time reconstruction for train meeting, crossing and overtaking events",
    "multi-event train schedules where interaction between moving bodies is essential",
    "maximum or complete overlap intervals between finite-length trains",
    "train-system reconstruction, contradiction detection and data sufficiency",
  ] as const),
  exclusions: Object.freeze([
    "a single finite train crossing only fixed geometry belongs to TSD-CP-007",
    "relative motion of negligible-length point bodies without train/station semantics remains TSD-CP-004 or TSD-CP-005",
    "circular-track repeated meetings belong to TSD-CP-006",
    "sound or whistle propagation is outside Quant Time, Speed & Distance",
    "boats, streams and medium-relative motion belong to TSD-CP-009",
  ] as const),
  permanentQlCount: 0 as const,
  nextAvailableQl: "TSD-QL-095" as const,
  englishFreezeStatus: "UNFROZEN" as const,
  questionStudioEnabled: false as const,
  questionBankStatus: "NOT_STORED" as const,
  testEligibility: "INELIGIBLE" as const,
  publiclyPublishable: false as const,
});

if (TSD_CP008_DISCOVERY_CANDIDATES.length !== 37) {
  throw new Error(`TSD-CP-008 discovery inventory drift: expected 37 candidates, found ${TSD_CP008_DISCOVERY_CANDIDATES.length}.`);
}
