import { generateDi001TableSet as foundation } from "./table-set";
import { hashSeed, pick, ratioDisplay, seededRandom, shuffle } from "./exact";
import type { Di001ExamProfile } from "./types";
import type { Di001V2Difficulty, Di001V2Explanation, Di001V2Option, Di001V2Question, Di001V2Set, Di001V2Stimulus, Di001V2TaskKind } from "./table-v2-types";

export const DI001_V2_TASK_KINDS: readonly Di001V2TaskKind[] = ["DIRECT_SELECTED","TOTAL_APPLICANTS","LARGEST_SELECTED","DIFFERENCE_SELECTED","PERCENTAGE_SELECTED","RATIO_APPLICANTS","AVERAGE_SELECTED","OVERALL_SELECTION_PERCENTAGE","SELECTED_TO_NOT_SELECTED_RATIO","SELECTION_RATE_DIFFERENCE"];
export const DI001_V2_DIFFICULTY: Readonly<Record<Di001V2TaskKind,Di001V2Difficulty>> = {
  DIRECT_SELECTED:"Easy",TOTAL_APPLICANTS:"Easy",LARGEST_SELECTED:"Easy",
  DIFFERENCE_SELECTED:"Medium",PERCENTAGE_SELECTED:"Medium",RATIO_APPLICANTS:"Medium",AVERAGE_SELECTED:"Medium",
  OVERALL_SELECTION_PERCENTAGE:"Hard",SELECTED_TO_NOT_SELECTED_RATIO:"Hard",SELECTION_RATE_DIFFERENCE:"Hard",
};
const OPTION_COUNT:Record<Di001ExamProfile,4|5>={SSC_CGL_TIER_I:4,BANKING_PRELIMS:5};
const LABELS=[["Centre P","Centre Q","Centre R","Centre S","Centre T"],["Centre A","Centre B","Centre C","Centre D","Centre E"],["Centre 1","Centre 2","Centre 3","Centre 4","Centre 5"]] as const;
type C={text:string;misconceptionId:string;derivation:string};
type D={kind:Di001V2TaskKind;difficulty:Di001V2Difficulty;stem:string;answer:string;candidates:readonly C[];explanation:Di001V2Explanation;evidence:Readonly<Record<string,string|number>>;normalize?:(v:string)=>string};

const fmt=(n:number)=>String(Math.round(n));
const norm=(s:string)=>s.trim().replace(/\s+/g," ").toLowerCase();
const normRatio=(s:string)=>{const m=s.trim().match(/^(\d+)\s*:\s*(\d+)$/);return m?ratioDisplay(Number(m[1]),Number(m[2])):norm(s)};
const pct=(s:number,a:number)=>(s*100)/a;
const choose=(seed:string,values:readonly string[])=>pick(seededRandom(seed),values);
const pair=(seed:string,n:number)=>shuffle(seededRandom(seed),Array.from({length:n},(_,i)=>i)).slice(0,2) as [number,number];
function fallback(answer:string):C[]{const out:C[]=[];const r=answer.match(/^(\d+):(\d+)$/);if(r){const a=Number(r[1]),b=Number(r[2]);out.push({text:`${b}:${a}`,misconceptionId:"REVERSED_RATIO",derivation:"Reverses the requested ratio."},{text:ratioDisplay(a,a+b),misconceptionId:"PART_TO_TOTAL",derivation:"Compares a part with the combined total."},{text:ratioDisplay(a+b,b),misconceptionId:"TOTAL_TO_PART",derivation:"Compares the combined total with a part."},{text:`${a+1}:${b}`,misconceptionId:"NEARBY_RATIO_A",derivation:"Uses a nearby first ratio term."},{text:`${a}:${b+1}`,misconceptionId:"NEARBY_RATIO_B",derivation:"Uses a nearby second ratio term."});return out}const m=answer.match(/^(\d+(?:\.\d+)?)(%)?$/);if(!m)return out;const v=Number(m[1]),suffix=m[2]??"",step=suffix?5:Number.isInteger(v)?10:1;return[-2,-1,1,2,3].map((d,i)=>({text:`${fmt(v+d*step)}${suffix}`,misconceptionId:`NEARBY_${i}`,derivation:"A nearby result from a small reading or arithmetic error."})).filter(x=>!x.text.startsWith("-"))}
function options(seed:string,count:4|5,answer:string,candidates:readonly C[],normalize:(v:string)=>string=norm){const seen=new Set<string>(),kept:Di001V2Option[]=[];const add=(x:C)=>{const k=normalize(x.text);if(!x.text.trim()||seen.has(k))return;seen.add(k);kept.push(x)};add({text:answer,misconceptionId:"CORRECT",derivation:"Exact recomputation from the shared table."});candidates.forEach(add);fallback(answer).forEach(add);if(kept.length<count)throw new Error(`DI-001 V2 ${seed} has only ${kept.length} unique options for ${answer}.`);const shuffled=shuffle(seededRandom(`${seed}:options`),kept.slice(0,count)),correctIndex=shuffled.findIndex(x=>x.misconceptionId==="CORRECT");return{options:shuffled.map(x=>x.text),optionMetadata:shuffled,correctIndex}}
function stimulus(seed:string,examProfile:Di001ExamProfile):Di001V2Stimulus{const base=foundation({seed,examProfile}).stimulus,labels=pick(seededRandom(`${seed}:labels`),LABELS);return{kind:"TABLE",title:"Applicants and selected candidates at five centres",instruction:"Study the table and answer the questions that follow.",columns:["Centre","Applicants","Selected"],unit:"candidates",rows:base.rows.map((r,i)=>({centre:labels[i]!,applicants:r.applicants,selected:r.selected}))}}

function drafts(seed:string,s:Di001V2Stimulus):D[]{const rows=s.rows,totalA=rows.reduce((x,r)=>x+r.applicants,0),totalS=rows.reduce((x,r)=>x+r.selected,0),notS=totalA-totalS,avg=totalS/5,overall=pct(totalS,totalA),largest=rows.reduce((b,r)=>r.selected>b.selected?r:b,rows[0]!);const directI=hashSeed(`${seed}:direct`)%5,direct=rows[directI]!;const[d1,d2]=pair(`${seed}:difference`,5),da=rows[d1]!,db=rows[d2]!,diff=Math.abs(da.selected-db.selected);const pI=hashSeed(`${seed}:percent`)%5,pr=rows[pI]!,prate=pct(pr.selected,pr.applicants);const[r1,r2]=pair(`${seed}:ratio`,5),ra=rows[r1]!,rb=rows[r2]!,rr=ratioDisplay(ra.applicants,rb.applicants);const[g1,g2]=pair(`${seed}:gap`,5),ga=rows[g1]!,gb=rows[g2]!,gap=Math.abs(pct(ga.selected,ga.applicants)-pct(gb.selected,gb.applicants));const rowRates=rows.map((r,i)=>({text:`${fmt(pct(r.selected,r.applicants))}%`,misconceptionId:`ROW_RATE_${i}`,derivation:`Uses ${r.centre}'s selection rate instead of the required result.`}));const gapOptions:C[]=[{text:`${fmt(pct(ga.selected,ga.applicants))} percentage points`,misconceptionId:"FIRST_RATE",derivation:`Reports ${ga.centre}'s rate itself.`},{text:`${fmt(pct(gb.selected,gb.applicants))} percentage points`,misconceptionId:"SECOND_RATE",derivation:`Reports ${gb.centre}'s rate itself.`},...[5,10,15,20,25,30,35,40,45,50].map((v,i)=>({text:`${v} percentage points`,misconceptionId:`GAP_${i}`,derivation:"Chooses a nearby plausible percentage-point difference."}))];return[
{kind:"DIRECT_SELECTED",difficulty:"Easy",stem:choose(`${seed}:direct:stem`,[`How many candidates were selected at ${direct.centre}?`,`What is the number of selected candidates at ${direct.centre}?`,`According to the table, how many candidates were selected at ${direct.centre}?`]),answer:fmt(direct.selected),candidates:rows.filter((_r,i)=>i!==directI).map((r,i)=>({text:fmt(r.selected),misconceptionId:`OTHER_${i}`,derivation:`Reads ${r.centre}'s Selected value instead.`})),explanation:{keyIdea:`Read the Selected entry for ${direct.centre}.`,steps:[`The ${direct.centre} row shows ${direct.selected} in the Selected column.`,`So the answer is ${direct.selected}.`]},evidence:{rowIndex:directI}},
{kind:"TOTAL_APPLICANTS",difficulty:"Easy",stem:choose(`${seed}:total:stem`,["What is the total number of applicants at all five centres?","How many applicants are there altogether across the five centres?","Find the combined number of applicants shown in the table."]),answer:fmt(totalA),candidates:[{text:fmt(totalS),misconceptionId:"SUM_SELECTED",derivation:"Adds Selected instead of Applicants."},{text:fmt(totalA-rows[0]!.applicants),misconceptionId:"OMIT_FIRST",derivation:`Leaves out ${rows[0]!.centre}.`},{text:fmt(totalA-rows[4]!.applicants),misconceptionId:"OMIT_LAST",derivation:`Leaves out ${rows[4]!.centre}.`},{text:fmt(totalA/5),misconceptionId:"AVERAGE",derivation:"Reports the mean instead of the total."}],explanation:{keyIdea:"Add the Applicants values for all five centres.",steps:[`${rows.map(r=>r.applicants).join(" + ")} = ${totalA}.`,`Therefore, the total is ${totalA}.`]},evidence:{totalA}},
{kind:"LARGEST_SELECTED",difficulty:"Easy",stem:choose(`${seed}:largest:stem`,["At which centre was the number of selected candidates the highest?","Which centre has the largest Selected value?","The maximum number of selected candidates is recorded at which centre?"]),answer:largest.centre,candidates:rows.filter(r=>r.centre!==largest.centre).map((r,i)=>({text:r.centre,misconceptionId:`OTHER_CENTRE_${i}`,derivation:`Chooses ${r.centre}, whose Selected value is lower.`})),explanation:{keyIdea:"Compare the five entries in the Selected column.",steps:[`Selected values: ${rows.map(r=>`${r.centre} ${r.selected}`).join(", ")}.`,`${largest.centre} has the highest value, ${largest.selected}.`]},evidence:{rowIndex:rows.indexOf(largest)}},
{kind:"DIFFERENCE_SELECTED",difficulty:"Medium",stem:choose(`${seed}:difference:stem`,[`What is the difference between the numbers selected at ${da.centre} and ${db.centre}?`,`How many candidates separate the Selected figures for ${da.centre} and ${db.centre}?`,`Find the difference in selected candidates between ${da.centre} and ${db.centre}.`]),answer:fmt(diff),candidates:[{text:fmt(da.selected+db.selected),misconceptionId:"ADD",derivation:"Adds the two Selected values."},{text:fmt(Math.abs(da.applicants-db.applicants)),misconceptionId:"WRONG_COLUMN",derivation:"Uses Applicants instead of Selected."},{text:fmt(da.selected),misconceptionId:"FIRST_ONLY",derivation:`Reports only ${da.centre}.`},{text:fmt(db.selected),misconceptionId:"SECOND_ONLY",derivation:`Reports only ${db.centre}.`}],explanation:{keyIdea:"Use the Selected values of the two named centres and subtract the smaller from the larger.",steps:[`|${da.selected} - ${db.selected}| = ${diff}.`]},evidence:{rowA:d1,rowB:d2}},
{kind:"PERCENTAGE_SELECTED",difficulty:"Medium",stem:choose(`${seed}:percent:stem`,[`To the nearest whole percent, what percentage of the applicants at ${pr.centre} were selected?`,`Selected candidates at ${pr.centre} are approximately what whole percent of its applicants?`,`Find the selection percentage for ${pr.centre}, rounded to the nearest whole percent.`]),answer:`${fmt(prate)}%`,candidates:rowRates.filter((_x,i)=>i!==pI),explanation:{keyIdea:"Selection percentage = Selected ÷ Applicants × 100.",steps:[`${pr.selected} ÷ ${pr.applicants} × 100 ≈ ${fmt(prate)}% to the nearest whole percent.`]},evidence:{rowIndex:pI}},
{kind:"RATIO_APPLICANTS",difficulty:"Medium",stem:choose(`${seed}:ratio:stem`,[`What is the ratio of applicants at ${ra.centre} to applicants at ${rb.centre}?`,`Applicants at ${ra.centre} and ${rb.centre} are in what ratio?`,`Applicants at ${ra.centre} and ${rb.centre} are in what ratio, in that order?`]),answer:rr,normalize:normRatio,candidates:[{text:ratioDisplay(rb.applicants,ra.applicants),misconceptionId:"REVERSE",derivation:"Reverses the centre order."},{text:ratioDisplay(ra.selected,rb.selected),misconceptionId:"SELECTED_RATIO",derivation:"Uses Selected instead of Applicants."},{text:ratioDisplay(ra.applicants,ra.selected),misconceptionId:"WITHIN_ROW",derivation:`Uses values within ${ra.centre}.`}],explanation:{keyIdea:"Take the Applicants values in the order named and reduce the ratio.",steps:[`${ra.applicants}:${rb.applicants} = ${rr}.`]},evidence:{rowA:r1,rowB:r2}},
{kind:"AVERAGE_SELECTED",difficulty:"Medium",stem:choose(`${seed}:average:stem`,["To the nearest whole number, what is the average number of selected candidates per centre?","Find the mean number of selected candidates across the five centres, rounded to the nearest whole number.","On average, approximately how many candidates were selected at each centre? Give the nearest whole number."]),answer:fmt(avg),candidates:[{text:fmt(totalS),misconceptionId:"TOTAL",derivation:"Adds Selected values but does not divide by five."},{text:fmt(totalA/5),misconceptionId:"APPLICANT_AVERAGE",derivation:"Averages Applicants instead of Selected."},...rows.slice(0,3).map((r,i)=>({text:fmt(r.selected),misconceptionId:`ROW_${i}`,derivation:`Uses ${r.centre}'s value instead of the mean.`}))],explanation:{keyIdea:"Add all Selected values and divide by five.",steps:[`${rows.map(r=>r.selected).join(" + ")} = ${totalS}.`,`${totalS} ÷ 5 ≈ ${fmt(avg)} to the nearest whole number.`]},evidence:{totalS}},
{kind:"OVERALL_SELECTION_PERCENTAGE",difficulty:"Hard",stem:choose(`${seed}:overall:stem`,["To the nearest whole percent, what percentage of all applicants across the five centres were selected?","Selected candidates form approximately what whole percent of the combined applicants?","Find the overall selection percentage for all five centres together, rounded to the nearest whole percent."]),answer:`${fmt(overall)}%`,candidates:rowRates,explanation:{keyIdea:"Use the combined totals rather than averaging the five centre percentages.",steps:[`Total selected = ${totalS}; total applicants = ${totalA}.`,`${totalS} ÷ ${totalA} × 100 ≈ ${fmt(overall)}% to the nearest whole percent.`],workingTable:{headers:["Combined selected","Combined applicants","Overall selection %"],rows:[[String(totalS),String(totalA),`${fmt(overall)}%`]]}},evidence:{totalA,totalS}},
{kind:"SELECTED_TO_NOT_SELECTED_RATIO",difficulty:"Hard",stem:choose(`${seed}:selnot:stem`,["What is the ratio of all selected candidates to all candidates not selected?","For the five centres together, find Selected : Not selected.","The combined numbers selected and not selected are in what ratio?"]),answer:ratioDisplay(totalS,notS),normalize:normRatio,candidates:[{text:ratioDisplay(notS,totalS),misconceptionId:"REVERSE",derivation:"Reverses selected and not-selected totals."},{text:ratioDisplay(totalS,totalA),misconceptionId:"SELECTED_TO_ALL",derivation:"Compares selected candidates with all applicants."},{text:ratioDisplay(totalA,notS),misconceptionId:"ALL_TO_NOT",derivation:"Uses total applicants as the first ratio term."}],explanation:{keyIdea:"First find the total not selected, then form the required ratio.",steps:[`Not selected = ${totalA} - ${totalS} = ${notS}.`,`Selected : Not selected = ${totalS}:${notS} = ${ratioDisplay(totalS,notS)}.`],workingTable:{headers:["Selected","Not selected"],rows:[[String(totalS),String(notS)]]}},evidence:{totalS,notS}},
{kind:"SELECTION_RATE_DIFFERENCE",difficulty:"Hard",stem:choose(`${seed}:gap:stem`,[`To the nearest whole percentage point, by how much do the selection rates of ${ga.centre} and ${gb.centre} differ?`,`Find the difference between the selection percentages of ${ga.centre} and ${gb.centre}, rounded to the nearest whole percentage point.`,`What is the selection-rate gap between ${ga.centre} and ${gb.centre}, to the nearest whole percentage point?`]),answer:`${fmt(gap)} percentage points`,candidates:gapOptions,explanation:{keyIdea:"Find each centre's selection percentage first, then subtract the smaller rate from the larger.",steps:[`${ga.centre}: ${ga.selected} ÷ ${ga.applicants} × 100.`,`${gb.centre}: ${gb.selected} ÷ ${gb.applicants} × 100.`,`Using the unrounded rates, the difference ≈ ${fmt(gap)} percentage points to the nearest whole percentage point.`],workingTable:{headers:["Centre","Applicants","Selected","Selection %"],rows:[[ga.centre,String(ga.applicants),String(ga.selected),`${fmt(pct(ga.selected,ga.applicants))}%`],[gb.centre,String(gb.applicants),String(gb.selected),`${fmt(pct(gb.selected,gb.applicants))}%`]]}},evidence:{rowA:g1,rowB:g2}}
]}
function mix(seed:string,all:readonly D[]){const by=(d:Di001V2Difficulty)=>shuffle(seededRandom(`${seed}:mix:${d}`),all.filter(x=>x.difficulty===d));const e=by("Easy"),m=by("Medium"),h=by("Hard");return shuffle(seededRandom(`${seed}:mix:order`),[e[0]!,m[0]!,m[1]!,h[0]!,h[1]!])}
function independent(s:Di001V2Stimulus,q:Di001V2Question){const r=s.rows,e=q.evidence;switch(q.kind){case"DIRECT_SELECTED":return fmt(r[Number(e.rowIndex)]!.selected);case"TOTAL_APPLICANTS":return fmt(r.reduce((x,y)=>x+y.applicants,0));case"LARGEST_SELECTED":return r.reduce((b,x)=>x.selected>b.selected?x:b,r[0]!).centre;case"DIFFERENCE_SELECTED":return fmt(Math.abs(r[Number(e.rowA)]!.selected-r[Number(e.rowB)]!.selected));case"PERCENTAGE_SELECTED":{const x=r[Number(e.rowIndex)]!;return`${fmt(pct(x.selected,x.applicants))}%`}case"RATIO_APPLICANTS":return ratioDisplay(r[Number(e.rowA)]!.applicants,r[Number(e.rowB)]!.applicants);case"AVERAGE_SELECTED":return fmt(r.reduce((x,y)=>x+y.selected,0)/5);case"OVERALL_SELECTION_PERCENTAGE":{const a=r.reduce((x,y)=>x+y.applicants,0),s0=r.reduce((x,y)=>x+y.selected,0);return`${fmt(pct(s0,a))}%`}case"SELECTED_TO_NOT_SELECTED_RATIO":{const a=r.reduce((x,y)=>x+y.applicants,0),s0=r.reduce((x,y)=>x+y.selected,0);return ratioDisplay(s0,a-s0)}case"SELECTION_RATE_DIFFERENCE":{const a=r[Number(e.rowA)]!,b=r[Number(e.rowB)]!;return`${fmt(Math.abs(pct(a.selected,a.applicants)-pct(b.selected,b.applicants)))} percentage points`}}}
function hasDecimalLearnerSurface(q:Di001V2Question){const t=q.explanation.workingTable;return /\d+\.\d+/u.test([q.stem,...q.options,q.answer,q.explanation.keyIdea,...q.explanation.steps,...(t?.headers??[]),...(t?.rows.flat()??[])].join(" "))}
function validate(base:Omit<Di001V2Set,"validation">){const c:Array<{id:string;passed:boolean;message:string}>=[],add=(id:string,passed:boolean,message:string)=>c.push({id,passed,message});add("FIVE_ROWS",base.stimulus.rows.length===5,"Five rows required.");add("FIVE_TASKS",base.questions.length===5&&new Set(base.questions.map(q=>q.kind)).size===5,"Five distinct tasks required.");add("DIFFICULTY_MIX",base.questions.filter(q=>q.difficulty==="Easy").length===1&&base.questions.filter(q=>q.difficulty==="Medium").length===2&&base.questions.filter(q=>q.difficulty==="Hard").length===2,"Requires 1 Easy, 2 Medium, 2 Hard.");add("DIFFICULTY_POLICY",base.questions.every(q=>q.difficulty===DI001_V2_DIFFICULTY[q.kind]),"Difficulty drifted.");add("OPTIONS",base.questions.every(q=>q.options.length===base.optionCount&&new Set(q.options).size===q.options.length),"Option contract failed.");add("ANSWER_BINDING",base.questions.every(q=>q.options[q.correctIndex]===q.answer&&q.optionMetadata[q.correctIndex]?.misconceptionId==="CORRECT"),"Answer binding failed.");add("NO_DECIMAL_LEARNER_SURFACE",base.questions.every(q=>!hasDecimalLearnerSurface(q)),"Learner-facing DI-001 values must contain no decimals.");add("INDEPENDENT",base.questions.every(q=>independent(base.stimulus,q)===q.answer),"Independent verifier failed.");add("EXPLANATION",base.questions.every(q=>q.explanation.keyIdea.length>15&&q.explanation.steps.length>=1),"Explanation missing.");add("LANGUAGE",base.questions.every(q=>!/associated|shortcut|common trap|\btrap\b/i.test(`${q.stem} ${q.explanation.keyIdea} ${q.explanation.steps.join(" ")}`)),"Blocked wording found.");add("LOCKS",!base.traceability.questionStudioDiscoverable&&base.traceability.questionBankStatus==="NOT_STORED"&&!base.traceability.questionBankWritable&&base.traceability.testEligibility==="INELIGIBLE"&&!base.traceability.testEligible&&!base.traceability.mockTestEligible&&!base.traceability.publiclyPublishable&&!base.traceability.automaticStudentPublication&&!base.traceability.productionReleaseAuthorized,"Lifecycle widened.");return{valid:c.every(x=>x.passed),checks:c}as const}
export function generateDi001TableV2Set(input:{seed:string;examProfile:Di001ExamProfile}):Di001V2Set{const seed=input.seed.trim();if(!seed)throw new Error("DI-001 V2 requires a seed.");const st=stimulus(seed,input.examProfile),chosen=mix(seed,drafts(seed,st)),setId=`DI-001-V2-${input.examProfile}-${hashSeed(`${seed}:${input.examProfile}`).toString(16).padStart(8,"0")}`;const questions:Di001V2Question[]=chosen.map((d,i)=>{const o=options(`${seed}:${input.examProfile}:${d.kind}:${i}`,OPTION_COUNT[input.examProfile],d.answer,d.candidates,d.normalize);return{questionId:`${setId}-Q${i+1}-${d.kind}`,setId,kind:d.kind,difficulty:d.difficulty,stem:d.stem,options:o.options,optionMetadata:o.optionMetadata,correctIndex:o.correctIndex,answer:d.answer,explanation:d.explanation,evidence:d.evidence}});const base={packageId:"DI-001"as const,reviewVersion:"V2"as const,setId,seed,language:"en"as const,examProfile:input.examProfile,optionCount:OPTION_COUNT[input.examProfile],setDifficulty:"TABLE_MIXED_V2"as const,stimulus:st,questions,traceability:{packageId:"DI-001"as const,representation:"TABLE"as const,sourceFoundation:"DI-001-PHASE0-TABLE-STATE"as const,setContractVersion:"DI-001-SET-CONTRACT-V2"as const,arithmeticAuthority:"EXACT_SOURCE_WITH_EXPLICIT_WHOLE_ROUNDING"as const,reviewStatus:"UNREVIEWED"as const,questionStudioDiscoverable:false as const,questionBankStatus:"NOT_STORED"as const,questionBankWritable:false as const,testEligibility:"INELIGIBLE"as const,testEligible:false as const,mockTestEligible:false as const,publiclyPublishable:false as const,automaticStudentPublication:false as const,productionReleaseAuthorized:false as const}};const validation=validate(base);if(!validation.valid)throw new Error(`DI-001 V2 validation failed: ${validation.checks.filter(x=>!x.passed).map(x=>x.id).join(", ")}`);return{...base,validation}}
export function verifyDi001TableV2Set(set:Di001V2Set){const{validation:_v,...base}=set;return validate(base).valid}
