import { buildGeoPopQl, finalizeGeoPopCp, auditGeoPopCp } from "./geo-pop-001-review-builder";
const SRC=["NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-POPULATION","CENSUS-OF-INDIA-2011-PRIMARY-CENSUS-ABSTRACT"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoPopQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("POPULATION-DISTRIBUTION","Population distribution and spatial concentration",[
{stem:"What does population distribution describe?",answer:"How people are spread across an area",distractors:["Only the birth rate","Only the literacy rate","Only the sex ratio"],explanation:"Population distribution refers to the spatial pattern of where people live.",sourceFactId:"POP-DIST-DEFINITION"},
{stem:"Why is India's population distribution uneven?",answer:"Physical and economic conditions vary greatly between regions",distractors:["Every region has identical relief","All states have equal rainfall","All places have the same industries"],explanation:"Relief, climate, soil, water, transport, urbanisation and economic opportunities differ across India.",sourceFactId:"POP-DIST-UNEVEN"},
{stem:"Consider the statements: I. Population is unevenly distributed in India. II. Plains and major urban-industrial regions generally attract more people. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both physical suitability and economic opportunity shape India's population distribution.",sourceFactId:"POP-DIST-STATEMENT"},
{stem:"Which pair is correctly matched in population geography?",answer:"Distribution — spatial spread of population",distractors:["Distribution — births per thousand only","Density — literacy rate","Growth — sex ratio"],explanation:"Distribution tells us where population is located across space.",sourceFactId:"POP-DIST-MATCH"},
{stem:"Which pattern is most typical of India's population distribution?",answer:"Dense concentration in favourable plains and urban-industrial regions",distractors:["Equal distribution everywhere","Highest concentration only in deserts","No population in coastal regions"],explanation:"Fertile plains, cities, industrial belts and well-connected regions support larger concentrations.",sourceFactId:"POP-DIST-PATTERN"},
{stem:"A map shows very high population concentration in some plains and cities but low concentration in mountains and deserts. What does it show?",answer:"Uneven population distribution",distractors:["Uniform population distribution","Only migration rate","Only literacy pattern"],explanation:"Large regional contrasts in population concentration indicate uneven distribution.",sourceFactId:"POP-DIST-CLUE"}
]),
q("POPULATION-DENSITY","Population density concept",[
{stem:"What is population density?",answer:"Number of people per unit area",distractors:["Number of births per year","Number of towns in a state","Number of workers in one industry"],explanation:"Population density measures the concentration of people in relation to land area.",sourceFactId:"POP-DENSITY-DEFINITION"},
{stem:"How is population density usually expressed in Indian census geography?",answer:"Persons per square kilometre",distractors:["Kilometres per person","Births per village","Households per river"],explanation:"Census density is normally expressed as persons per square kilometre.",sourceFactId:"POP-DENSITY-UNIT"},
{stem:"Consider the statements: I. Density relates population to area. II. A small, heavily populated area can have high density. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Density depends on both population size and the area over which it is distributed.",sourceFactId:"POP-DENSITY-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Population density — persons per square kilometre",distractors:["Population density — births minus deaths","Population density — females per thousand males","Population density — literates per hundred"],explanation:"Density is the number of people living per unit of land area.",sourceFactId:"POP-DENSITY-MATCH"},
{stem:"Two districts have the same population, but District A has half the area of District B. Which district has higher density?",answer:"District A",distractors:["District B","Both must have equal density","Density cannot be compared"],explanation:"With the same population in a smaller area, District A has more persons per square kilometre.",sourceFactId:"POP-DENSITY-CALC"},
{stem:"A district has a large population concentrated in a small area. Which measure is likely to be high?",answer:"Population density",distractors:["Area size","River length","Mountain height"],explanation:"High population relative to land area produces high density.",sourceFactId:"POP-DENSITY-CLUE"}
]),
q("PHYSICAL-FACTORS-DISTRIBUTION","Physical factors influencing population distribution",[
{stem:"Which physical factor most directly favours dense settlement in large plains?",answer:"Level terrain",distractors:["Steep slopes","Permanent snow cover","Very high altitude"],explanation:"Level terrain is easier for farming, transport, construction and settlement.",sourceFactId:"POP-PHYS-RELIEF"},
{stem:"Why does reliable water supply encourage population concentration?",answer:"It supports domestic use, farming and industry",distractors:["It prevents settlement","It reduces agricultural activity","It blocks transport everywhere"],explanation:"Water availability is fundamental to households, agriculture and economic activity.",sourceFactId:"POP-PHYS-WATER"},
{stem:"Consider the statements: I. Fertile soil can support dense rural settlement. II. Harsh climate can reduce population concentration. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Productive land attracts settlement, while severe climatic conditions can discourage it.",sourceFactId:"POP-PHYS-STATEMENT"},
{stem:"Which pair is correctly matched in population distribution?",answer:"Fertile plain — favourable for dense settlement",distractors:["Glaciated highland — maximum farming density","Arid desert — uniformly dense population","Steep mountain — easiest transport access"],explanation:"Fertile plains provide productive land and relatively easy transport and construction.",sourceFactId:"POP-PHYS-MATCH"},
{stem:"Which combination most strongly favours dense population?",answer:"Level land, fertile soil and reliable water",distractors:["Steep slopes, snow and thin soil","Extreme aridity and scarce water","High altitude and difficult access"],explanation:"A combination of favourable relief, soil and water supports intensive settlement.",sourceFactId:"POP-PHYS-COMBINATION"},
{stem:"A region has steep slopes, severe winters and limited cultivable land. What population pattern is most likely?",answer:"Sparse population",distractors:["Very high density everywhere","Uniform metropolitan growth","Dense agricultural settlement"],explanation:"Difficult terrain and limited farming potential generally restrict population concentration.",sourceFactId:"POP-PHYS-CLUE"}
]),
q("GANGA-PLAIN-CONCENTRATION","Population concentration in the northern plains",[
{stem:"Why is the Ganga plain one of India's most densely populated regions?",answer:"Fertile land, water availability and long-settled agriculture",distractors:["Permanent snow cover","Lack of rivers","Very steep terrain"],explanation:"The plain combines fertile alluvium, abundant water, level land and long agricultural settlement.",sourceFactId:"POP-GANGA-FACTORS"},
{stem:"Which physical feature helps explain dense population in the northern plains?",answer:"Extensive level alluvial land",distractors:["High glaciated relief","Rocky desert surface","Permanent ice sheet"],explanation:"Level alluvial plains are well suited to farming, settlement and transport.",sourceFactId:"POP-GANGA-RELIEF"},
{stem:"Consider the statements: I. The Ganga plain has fertile alluvial soils. II. It also has dense transport and settlement networks. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both natural and human factors reinforce high population concentration.",sourceFactId:"POP-GANGA-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Ganga plain — high population concentration",distractors:["Ganga plain — permanent sparse settlement","Thar core — uniformly highest density","High Himalaya — dense agricultural belt"],explanation:"The Ganga plain is one of India's major densely settled regions.",sourceFactId:"POP-GANGA-MATCH"},
{stem:"Which economic activity historically supported dense rural population in the Ganga plain?",answer:"Intensive agriculture",distractors:["Deep-sea fishing only","High-altitude pastoralism only","Offshore drilling only"],explanation:"Fertile soils and water availability supported intensive agriculture and dense villages.",sourceFactId:"POP-GANGA-AGRI"},
{stem:"A region has fertile alluvial soil, perennial rivers, level terrain and dense villages. Which region fits best?",answer:"Northern plains",distractors:["High Himalaya","Western desert core","Ladakh plateau"],explanation:"These features characterise the densely populated northern plains.",sourceFactId:"POP-GANGA-CLUE"}
]),
q("MOUNTAIN-SPARSE-POPULATION","Sparse population in mountain regions",[
{stem:"Why are high mountain regions generally sparsely populated?",answer:"Steep relief and harsh climatic conditions",distractors:["Extremely fertile flat land everywhere","Dense industrial corridors everywhere","Easy year-round transport"],explanation:"Steep slopes, cold climate and limited cultivable land restrict large settlements.",sourceFactId:"POP-MOUNTAIN-SPARSE"},
{stem:"Which factor limits settlement most directly in very high Himalayan areas?",answer:"Severe relief and climate",distractors:["Abundant flat farmland","Dense port network","Tropical coastal climate"],explanation:"High altitude, cold conditions and difficult terrain reduce settlement suitability.",sourceFactId:"POP-MOUNTAIN-LIMIT"},
{stem:"Consider the statements: I. Mountain terrain raises transport difficulty. II. Cultivable land is often limited at high altitude. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both factors contribute to low population concentration in high mountains.",sourceFactId:"POP-MOUNTAIN-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"High Himalaya — sparse population",distractors:["High Himalaya — highest agricultural density","Glaciated zone — dense metropolitan belt","Steep mountain — easiest settlement terrain"],explanation:"High Himalayan terrain generally supports lower population densities.",sourceFactId:"POP-MOUNTAIN-MATCH"},
{stem:"Which settlement pattern is common in difficult mountain terrain?",answer:"Small and scattered settlements",distractors:["Continuous mega-city belt everywhere","Uniform dense plains settlement","Large port cities at every location"],explanation:"Limited usable land and difficult access often produce scattered settlement patterns.",sourceFactId:"POP-MOUNTAIN-SETTLEMENT"},
{stem:"A region has high altitude, steep slopes and very limited arable land. Which population pattern is expected?",answer:"Low population density",distractors:["Highest national density","Uniform urban concentration","Dense deltaic settlement"],explanation:"The physical environment limits large-scale permanent settlement.",sourceFactId:"POP-MOUNTAIN-CLUE"}
]),
q("DESERT-SPARSE-POPULATION","Sparse population in arid regions",[
{stem:"What is the main physical constraint on population in hot desert regions?",answer:"Scarcity of water",distractors:["Excessive river density","Permanent snow cover","Abundant rainfall"],explanation:"Water shortage strongly limits farming, settlement and economic activity in deserts.",sourceFactId:"POP-DESERT-WATER"},
{stem:"Why is population often concentrated around oases and irrigated areas in deserts?",answer:"Water becomes locally available",distractors:["Snowfall increases","Sea ports appear","Mountain slopes flatten"],explanation:"Reliable water allows settlement and agriculture in otherwise arid surroundings.",sourceFactId:"POP-DESERT-OASIS"},
{stem:"Consider the statements: I. Aridity can reduce population density. II. Irrigation can create local population concentrations. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Water scarcity lowers settlement potential, while irrigation can support denser pockets.",sourceFactId:"POP-DESERT-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Arid desert — sparse population",distractors:["Arid desert — uniformly highest density","Irrigated oasis — no settlement","Water scarcity — dense farming everywhere"],explanation:"Extreme aridity generally produces low population density.",sourceFactId:"POP-DESERT-MATCH"},
{stem:"Which development can increase population concentration in an arid area?",answer:"Irrigation",distractors:["Reduced water supply","Loss of transport links","Greater aridity"],explanation:"Irrigation supports farming and permanent settlement where rainfall is insufficient.",sourceFactId:"POP-DESERT-IRRIGATION"},
{stem:"A dry region has scattered settlements clustered near canals and wells. What factor explains the pattern?",answer:"Water availability",distractors:["Railway gauge","Sea depth","Mountain snowfall"],explanation:"In arid regions, settlements concentrate where dependable water exists.",sourceFactId:"POP-DESERT-CLUE"}
]),
q("URBAN-INDUSTRIAL-CONCENTRATION","Urban and industrial population concentration",[
{stem:"Why do major cities attract population?",answer:"They offer employment and services",distractors:["They eliminate economic opportunities","They lack transport links","They prohibit migration"],explanation:"Jobs, education, health care, markets and transport attract people to cities.",sourceFactId:"POP-URBAN-ATTRACT"},
{stem:"How can industrialisation affect population distribution?",answer:"It can concentrate population around industrial centres",distractors:["It always empties cities","It removes transport demand","It prevents employment"],explanation:"Factories and related services create jobs and attract workers and households.",sourceFactId:"POP-INDUSTRIAL-CONCENTRATION"},
{stem:"Consider the statements: I. Employment opportunities attract migrants. II. Transport hubs can support urban population growth. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Economic opportunity and connectivity both reinforce urban concentration.",sourceFactId:"POP-URBAN-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Industrial centre — population concentration",distractors:["Employment growth — automatic depopulation","Transport hub — no settlement effect","City services — reduced attraction"],explanation:"Industrial and service employment encourages population concentration.",sourceFactId:"POP-URBAN-MATCH"},
{stem:"Which factor is a major human cause of high population density?",answer:"Concentration of jobs and services",distractors:["Permanent ice cover","Extreme aridity","Steep inaccessible relief"],explanation:"Economic opportunities can support dense settlement even where physical conditions are not ideal.",sourceFactId:"POP-URBAN-HUMAN"},
{stem:"A district contains a large industrial city, universities and major transport links. What population pattern is likely?",answer:"High population concentration",distractors:["Uniformly sparse population","No migration","Only seasonal pastoral settlement"],explanation:"Employment, services and connectivity attract population into urban-industrial districts.",sourceFactId:"POP-URBAN-CLUE"}
]),
q("CENSUS2011-DENSITY-RANKING","Census 2011 state density pattern",[
{stem:"As per Census 2011, which state had the highest population density among Indian states?",answer:"Bihar",distractors:["Arunachal Pradesh","Rajasthan","Sikkim"],explanation:"Census 2011 recorded Bihar as the most densely populated state, excluding Union Territories.",sourceFactId:"C2011-DENSITY-HIGHEST"},
{stem:"As per Census 2011, which state had the lowest population density?",answer:"Arunachal Pradesh",distractors:["Bihar","Kerala","Uttar Pradesh"],explanation:"Arunachal Pradesh had the lowest population density among states in Census 2011.",sourceFactId:"C2011-DENSITY-LOWEST"},
{stem:"Consider Census 2011: I. Bihar had very high population density. II. Arunachal Pradesh had very low population density. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two states represented opposite ends of state-level density in Census 2011.",sourceFactId:"C2011-DENSITY-STATEMENT"},
{stem:"Which pair is correctly matched as per Census 2011?",answer:"Bihar — highest density among states",distractors:["Arunachal Pradesh — highest density","Bihar — lowest density","Sikkim — highest density"],explanation:"Bihar ranked highest among states in population density in Census 2011.",sourceFactId:"C2011-DENSITY-MATCH"},
{stem:"Which contrast is correct as per Census 2011?",answer:"Bihar was very densely populated, while Arunachal Pradesh was sparsely populated",distractors:["Arunachal Pradesh was denser than Bihar","Both had identical density","Bihar had the lowest density"],explanation:"Census 2011 shows a sharp density contrast between the two states.",sourceFactId:"C2011-DENSITY-COMPARE"},
{stem:"A Census 2011 map shows one state at the highest end of density and another at the lowest. Which pair fits?",answer:"Bihar and Arunachal Pradesh",distractors:["Arunachal Pradesh and Bihar","Sikkim and Kerala","Rajasthan and Bihar"],explanation:"Bihar and Arunachal Pradesh mark the high and low ends among states.",sourceFactId:"C2011-DENSITY-CLUE"}
]),
q("CENSUS2011-POPULATION-RANKING","Census 2011 state population size",[
{stem:"As per Census 2011, which state had the largest population?",answer:"Uttar Pradesh",distractors:["Sikkim","Goa","Arunachal Pradesh"],explanation:"Uttar Pradesh had the largest population among Indian states in Census 2011.",sourceFactId:"C2011-POP-HIGHEST"},
{stem:"As per Census 2011, which state had the smallest population among states?",answer:"Sikkim",distractors:["Uttar Pradesh","Maharashtra","Bihar"],explanation:"Sikkim had the smallest population among states in Census 2011.",sourceFactId:"C2011-POP-LOWEST"},
{stem:"Consider Census 2011: I. Uttar Pradesh was the most populous state. II. Sikkim was the least populous state. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both state-level population rankings are correct for Census 2011.",sourceFactId:"C2011-POP-STATEMENT"},
{stem:"Which pair is correctly matched as per Census 2011?",answer:"Uttar Pradesh — largest state population",distractors:["Sikkim — largest state population","Uttar Pradesh — smallest state population","Bihar — smallest state population"],explanation:"Uttar Pradesh ranked first among states by population in Census 2011.",sourceFactId:"C2011-POP-MATCH"},
{stem:"Which comparison is correct as per Census 2011?",answer:"Uttar Pradesh had a much larger population than Sikkim",distractors:["Sikkim had a larger population than Uttar Pradesh","Both had equal population","Uttar Pradesh was the least populous state"],explanation:"The two states were at opposite ends of the state population ranking.",sourceFactId:"C2011-POP-COMPARE"},
{stem:"A question asks for the most populous Indian state in Census 2011. Which answer should be selected?",answer:"Uttar Pradesh",distractors:["Sikkim","Goa","Mizoram"],explanation:"Uttar Pradesh had India's largest state population in Census 2011.",sourceFactId:"C2011-POP-CLUE"}
]),
q("DENSITY-VS-DISTRIBUTION","Distribution and density distinction",[
{stem:"Which statement correctly distinguishes population distribution from density?",answer:"Distribution shows spatial spread; density relates population to area",distractors:["Both mean only birth rate","Density shows language only","Distribution is persons per square kilometre only"],explanation:"Distribution describes where people live, while density measures concentration per unit area.",sourceFactId:"POP-DIST-DENSITY-DIFF"},
{stem:"A map shows where people live but gives no population-per-area values. What does it primarily show?",answer:"Population distribution",distractors:["Population density only","Sex ratio","Literacy rate"],explanation:"Spatial location and concentration patterns describe distribution.",sourceFactId:"POP-DIST-MAP"},
{stem:"A table gives persons per square kilometre for each state. What does it measure?",answer:"Population density",distractors:["Population distribution only","Natural increase","Urban classification"],explanation:"Persons per square kilometre is the standard measure of population density.",sourceFactId:"POP-DENSITY-TABLE"},
{stem:"Consider the statements: I. Distribution is spatial. II. Density is a ratio of population to land area. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two concepts are related but not identical.",sourceFactId:"POP-DIST-DENSITY-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Density — numerical concentration per unit area",distractors:["Distribution — females per thousand males","Density — births minus deaths","Distribution — literacy percentage"],explanation:"Density is a numerical measure of population concentration relative to area.",sourceFactId:"POP-DIST-DENSITY-MATCH"},
{stem:"One region is widely settled but has few people per square kilometre. Which concepts help describe it?",answer:"Distribution and density",distractors:["Only sex ratio","Only literacy","Only birth rate"],explanation:"The spread of settlements and the number of people per area are separate but complementary measures.",sourceFactId:"POP-DIST-DENSITY-CLUE"}
])
]);
export const GEO_POP_001_CP001_REVIEW_BATCH_V1=finalizeGeoPopCp(1,QLS);
export function auditGeoPop001Cp001ReviewBatchV1(){return auditGeoPopCp(1,QLS,GEO_POP_001_CP001_REVIEW_BATCH_V1);}
