import {rational as r} from "../TSD-001/foundation/rational";
import * as motion from "./source-motion-extension-solvers";
import {solveMeetingSpeedExchange,solveStationQueuedDispatch} from "./source-transition-review-solvers";
import {EDITORIAL_REVIEW_LOCK} from "./worked-calculation";
type Triple=readonly[string,string,string];
type Case=Readonly<{id:string;source:string;model:string;stems:Triple;steps:readonly Triple[];answers:readonly string[];correct:number;unit?:"speed"|"distance"|"hours"|"seconds";solution:object;advanced?:boolean}>;
const messages=[{id:"A",position:r(10),sentAt:r(0)},{id:"D",position:r(40),sentAt:r(0)},{id:"C",position:r(30),sentAt:r(4)},{id:"B",position:r(20),sentAt:r(5)},{id:"E",position:r(50),sentAt:r(9)}];
const dispatchStem:Triple=[
 "Five machines A, B, C, D and E lie10,20,30,40 and50m from a robot station. A robot travels at10m/s and serves machines instantly in the order encountered. A and D request service at0s, C at4s, B at5s and E at9s. Requests received during a trip are read only after the robot reaches a station. After each trip it returns to the origin. How far has it travelled when it first reads E's request?",
 "एक रोबोट स्टेशन से मशीनें A, B, C, D और E क्रमशः10,20,30,40 और50मीटर दूर हैं। रोबोट10मी/सेकंड की गति से चलता है और रास्ते में आने वाली मशीनों को तुरंत सेवा देता है। A और D का अनुरोध0सेकंड पर, C का4सेकंड पर, B का5सेकंड पर और E का9सेकंड पर आता है। यात्रा के दौरान आए अनुरोध स्टेशन पर लौटने के बाद ही पढ़े जाते हैं। हर यात्रा के बाद रोबोट मूल स्टेशन पर लौटता है। E का अनुरोध पहली बार पढ़ने तक वह कितनी दूरी तय करता है?",
 "ਰੋਬੋਟ ਸਟੇਸ਼ਨ ਤੋਂ ਮਸ਼ੀਨਾਂ A, B, C, D ਅਤੇ E ਕ੍ਰਮਵਾਰ10,20,30,40 ਅਤੇ50ਮੀਟਰ ਦੂਰ ਹਨ। ਰੋਬੋਟ10ਮੀ/ਸਕਿੰਟ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਚੱਲਦਾ ਹੈ ਅਤੇ ਰਸਤੇ ਵਿੱਚ ਆਉਣ ਵਾਲੀਆਂ ਮਸ਼ੀਨਾਂ ਨੂੰ ਤੁਰੰਤ ਸੇਵਾ ਦਿੰਦਾ ਹੈ। A ਅਤੇ D ਦੀ ਬੇਨਤੀ0ਸਕਿੰਟ 'ਤੇ, C ਦੀ4ਸਕਿੰਟ 'ਤੇ, B ਦੀ5ਸਕਿੰਟ 'ਤੇ ਅਤੇ E ਦੀ9ਸਕਿੰਟ 'ਤੇ ਆਉਂਦੀ ਹੈ। ਸਫ਼ਰ ਦੌਰਾਨ ਆਈਆਂ ਬੇਨਤੀਆਂ ਸਟੇਸ਼ਨ 'ਤੇ ਪਰਤਣ ਮਗਰੋਂ ਹੀ ਪੜ੍ਹੀਆਂ ਜਾਂਦੀਆਂ ਹਨ। ਹਰ ਸਫ਼ਰ ਮਗਰੋਂ ਰੋਬੋਟ ਮੁੱਢਲੇ ਸਟੇਸ਼ਨ 'ਤੇ ਪਰਤਦਾ ਹੈ। E ਦੀ ਬੇਨਤੀ ਪਹਿਲੀ ਵਾਰ ਪੜ੍ਹਨ ਤੱਕ ਉਹ ਕਿੰਨੀ ਦੂਰੀ ਤੈਅ ਕਰਦਾ ਹੈ?",
];
const cases:readonly Case[]=[
 {id:"VECTOR",source:"TASTE-Q78",model:"oppositeBankCrossing",solution:motion.solveOppositeBankCrossing(r(20),r(6)),answers:["14","26","2√91","2√109"],correct:2,unit:"speed",stems:[
 "A boat can travel at20km/h in still water. A river flows at6km/h. The boat is steered to land directly opposite its starting point. What is its speed across the river?",
 "एक नाव की शांत पानी में गति20किमी/घंटा है। नदी का बहाव6किमी/घंटा है। नाव को इस तरह चलाया जाता है कि वह दूसरे किनारे पर अपने शुरुआती बिंदु के ठीक सामने पहुँचे। नदी के आर-पार उसकी गति कितनी है?",
 "ਇੱਕ ਕਿਸ਼ਤੀ ਦੀ ਖੜ੍ਹੇ ਪਾਣੀ ਵਿੱਚ ਰਫ਼ਤਾਰ20ਕਿਮੀ/ਘੰਟਾ ਹੈ। ਦਰਿਆ ਦਾ ਵਹਾਅ6ਕਿਮੀ/ਘੰਟਾ ਹੈ। ਕਿਸ਼ਤੀ ਇਸ ਤਰ੍ਹਾਂ ਚਲਾਈ ਜਾਂਦੀ ਹੈ ਕਿ ਉਹ ਦੂਜੇ ਕੰਢੇ 'ਤੇ ਆਪਣੇ ਸ਼ੁਰੂਆਤੀ ਬਿੰਦੂ ਦੇ ਠੀਕ ਸਾਹਮਣੇ ਪਹੁੰਚੇ। ਦਰਿਆ ਦੇ ਆਰ-ਪਾਰ ਉਸ ਦੀ ਰਫ਼ਤਾਰ ਕਿੰਨੀ ਹੈ?"],steps:[
 ["The upstream component of the boat's velocity must cancel the6km/h current.","नाव की गति का बहाव के विपरीत घटक6किमी/घंटा होना चाहिए।","ਕਿਸ਼ਤੀ ਦੀ ਰਫ਼ਤਾਰ ਦਾ ਵਹਾਅ ਦੇ ਉਲਟ ਹਿੱਸਾ6ਕਿਮੀ/ਘੰਟਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।"],
 ["Across-river speed²=20²−6²=364; speed=2√91km/h.","आर-पार गति²=20²−6²=364; गति=2√91किमी/घंटा।","ਆਰ-ਪਾਰ ਰਫ਼ਤਾਰ²=20²−6²=364; ਰਫ਼ਤਾਰ=2√91ਕਿਮੀ/ਘੰਟਾ।"]]},
 {id:"BOAT-RATIO",source:"TASTE-Q107",model:"doubledBoatTimeRatio",solution:motion.solveDoubledBoatTimeRatio(r(1,4)),answers:["√6:√2","√7:2","2√5:3","3:2"],correct:1,stems:[
 "A boat makes a round trip between two points on a riverbank. Doubling its speed in still water reduces the total travel time by75%; the current remains unchanged. What is the ratio of its original speed in still water to the current speed?",
 "एक नाव नदी के किनारे स्थित दो बिंदुओं के बीच जाकर लौटती है। शांत पानी में नाव की गति दोगुनी करने पर कुल यात्रा समय75%कम हो जाता है। बहाव की गति समान रहती है। नाव की मूल गति और बहाव की गति का अनुपात क्या है?",
 "ਇੱਕ ਕਿਸ਼ਤੀ ਦਰਿਆ ਦੇ ਕੰਢੇ ਦੇ ਦੋ ਬਿੰਦੂਆਂ ਵਿਚਕਾਰ ਜਾ ਕੇ ਪਰਤਦੀ ਹੈ। ਖੜ੍ਹੇ ਪਾਣੀ ਵਿੱਚ ਕਿਸ਼ਤੀ ਦੀ ਰਫ਼ਤਾਰ ਦੁੱਗਣੀ ਕਰਨ 'ਤੇ ਕੁੱਲ ਸਫ਼ਰ ਦਾ ਸਮਾਂ75%ਘਟ ਜਾਂਦਾ ਹੈ। ਵਹਾਅ ਦੀ ਰਫ਼ਤਾਰ ਇੱਕੋ ਰਹਿੰਦੀ ਹੈ। ਕਿਸ਼ਤੀ ਦੀ ਮੁੱਢਲੀ ਰਫ਼ਤਾਰ ਅਤੇ ਵਹਾਅ ਦੀ ਰਫ਼ਤਾਰ ਦਾ ਅਨੁਪਾਤ ਕੀ ਹੈ?"],steps:[
 ["Let the original boat speed be u and current speed c. For one-way distance D, T=2Du/(u²−c²).","नाव की मूल गति u, बहाव की गति c और एक ओर की दूरी D मानें। कुल समय T=2Du/(u²−c²)।","ਕਿਸ਼ਤੀ ਦੀ ਮੁੱਢਲੀ ਰਫ਼ਤਾਰ u, ਵਹਾਅ ਦੀ ਰਫ਼ਤਾਰ c ਅਤੇ ਇੱਕ ਪਾਸੇ ਦੀ ਦੂਰੀ D ਮੰਨੋ। ਕੁੱਲ ਸਮਾਂ T=2Du/(u²−c²)।"],
 ["New time/original time=2(u²−c²)/(4u²−c²)=1/4.","नया समय/मूल समय=2(u²−c²)/(4u²−c²)=1/4।","ਨਵਾਂ ਸਮਾਂ/ਮੁੱਢਲਾ ਸਮਾਂ=2(u²−c²)/(4u²−c²)=1/4।"],
 ["4u²=7c², so u:c=√7:2.","4u²=7c², इसलिए u:c=√7:2।","4u²=7c², ਇਸ ਲਈ u:c=√7:2।"]]},
 {id:"SOUND",source:"LOD-I-Q23",model:"approachingSoundReceiver",solution:motion.solveApproachingSoundReceiver(r(330),r(720),r(690)),answers:["660/23","330/23","110/23","330/7"],correct:1,stems:[
 "Two sounds are produced12minutes apart at the same place. A passenger on a train approaching that place hears them11minutes30seconds apart. Sound travels at330m/s. What is the train's speed?",
 "एक ही स्थान पर12मिनट के अंतर से दो आवाज़ें उत्पन्न होती हैं। उस स्थान की ओर आ रही ट्रेन का यात्री उन्हें11मिनट30सेकंड के अंतर से सुनता है। ध्वनि की गति330मी/सेकंड है। ट्रेन की गति कितनी है?",
 "ਇੱਕੋ ਥਾਂ 'ਤੇ12ਮਿੰਟ ਦੇ ਫ਼ਰਕ ਨਾਲ ਦੋ ਆਵਾਜ਼ਾਂ ਪੈਦਾ ਹੁੰਦੀਆਂ ਹਨ। ਉਸ ਥਾਂ ਵੱਲ ਆ ਰਹੀ ਰੇਲਗੱਡੀ ਦਾ ਯਾਤਰੀ ਉਨ੍ਹਾਂ ਨੂੰ11ਮਿੰਟ30ਸਕਿੰਟ ਦੇ ਫ਼ਰਕ ਨਾਲ ਸੁਣਦਾ ਹੈ। ਆਵਾਜ਼ ਦੀ ਰਫ਼ਤਾਰ330ਮੀ/ਸਕਿੰਟ ਹੈ। ਰੇਲਗੱਡੀ ਦੀ ਰਫ਼ਤਾਰ ਕਿੰਨੀ ਹੈ?"],steps:[
 ["The sound waves are330×720m apart. Their closing speed with the train is330+v.","ध्वनि की दोनों तरंगों के बीच दूरी330×720मीटर है। ट्रेन के सापेक्ष उनकी गति330+v है।","ਆਵਾਜ਼ ਦੀਆਂ ਦੋਵਾਂ ਲਹਿਰਾਂ ਵਿਚਕਾਰ ਦੂਰੀ330×720ਮੀਟਰ ਹੈ। ਰੇਲਗੱਡੀ ਦੇ ਮੁਕਾਬਲੇ ਉਨ੍ਹਾਂ ਦੀ ਰਫ਼ਤਾਰ330+v ਹੈ।"],
 ["(330+v)×690=330×720; v=330×30/690=330/23m/s.","(330+v)×690=330×720; v=330×30/690=330/23मी/सेकंड।","(330+v)×690=330×720; v=330×30/690=330/23ਮੀ/ਸਕਿੰਟ।"]]},
 {id:"BIRD",source:"LOD-II-Q42",model:"birdIntercepts",solution:motion.solveBirdIntercepts({separation:r(12),speedA:r(60),speedB:r(60),birdSpeed:r(120),visits:3}),answers:["12","104/9","32/3","100/9"],correct:1,unit:"distance",stems:[
 "Two cars12km apart approach each other at60km/h each. A bird flies at120km/h from the first car to the second, back to the first, and then to the second again. How far has the bird flown when it reaches the second car for the second time?",
 "12किमी दूर दो कारें60किमी/घंटा की गति से एक-दूसरे की ओर चलती हैं। एक पक्षी120किमी/घंटा की गति से पहली कार से दूसरी कार तक, फिर पहली कार तक और फिर दूसरी कार तक उड़ता है। दूसरी कार पर दूसरी बार पहुँचने तक पक्षी कितनी दूरी तय करता है?",
 "12ਕਿਮੀ ਦੂਰ ਦੋ ਕਾਰਾਂ60ਕਿਮੀ/ਘੰਟਾ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਇੱਕ-ਦੂਜੇ ਵੱਲ ਚੱਲਦੀਆਂ ਹਨ। ਇੱਕ ਪੰਛੀ120ਕਿਮੀ/ਘੰਟਾ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਪਹਿਲੀ ਕਾਰ ਤੋਂ ਦੂਜੀ ਕਾਰ ਤੱਕ, ਫਿਰ ਪਹਿਲੀ ਕਾਰ ਤੱਕ ਅਤੇ ਮੁੜ ਦੂਜੀ ਕਾਰ ਤੱਕ ਉੱਡਦਾ ਹੈ। ਦੂਜੀ ਕਾਰ ਕੋਲ ਦੂਜੀ ਵਾਰ ਪਹੁੰਚਣ ਤੱਕ ਪੰਛੀ ਕਿੰਨੀ ਦੂਰੀ ਤੈਅ ਕਰਦਾ ਹੈ?"],steps:[
 ["The bird closes each gap at120+60=180km/h. The gaps before its three flights are12,4 and4/3km; flight times are1/15,1/45 and1/135hours.","पक्षी हर अंतर को120+60=180किमी/घंटा की सापेक्ष गति से तय करता है। तीन उड़ानों से पहले कारों के अंतर12,4और4/3किमी हैं। उड़ान के समय1/15,1/45और1/135घंटे हैं।","ਪੰਛੀ ਹਰ ਫ਼ਰਕ120+60=180ਕਿਮੀ/ਘੰਟਾ ਦੀ ਸਾਪੇਖ ਰਫ਼ਤਾਰ ਨਾਲ ਤੈਅ ਕਰਦਾ ਹੈ। ਤਿੰਨ ਉਡਾਣਾਂ ਤੋਂ ਪਹਿਲਾਂ ਕਾਰਾਂ ਦੇ ਫ਼ਰਕ12,4ਅਤੇ4/3ਕਿਮੀ ਹਨ। ਉਡਾਣ ਦੇ ਸਮੇਂ1/15,1/45ਅਤੇ1/135ਘੰਟੇ ਹਨ।"],
 ["Distance=120×(1/15+1/45+1/135)=104/9km.","दूरी=120×(1/15+1/45+1/135)=104/9किमी।","ਦੂਰੀ=120×(1/15+1/45+1/135)=104/9ਕਿਮੀ।"]]},
 {id:"CLOSEST",source:"LOD-III-Q17",model:"closestApproach",solution:motion.solveClosestApproach({positionSquared:r(40000),positionVelocityDot:r(-8000),velocitySquared:r(2000),until:r(5)}),answers:["5/2","4","5","10"],correct:1,unit:"hours",stems:[
 "A and B are200km apart on a straight road. A car leaves A towards B at40km/h. At the same instant another car leaves B at20km/h along a road perpendicular to AB. After how many hours are the cars closest?",
 "एक सीधी सड़क पर A और B की दूरी200किमी है। एक कार A से B की ओर40किमी/घंटा की गति से चलती है। उसी समय दूसरी कार B से AB के लंबवत सड़क पर20किमी/घंटा की गति से चलती है। कितने घंटे बाद दोनों कारों के बीच दूरी सबसे कम होगी?",
 "ਇੱਕ ਸਿੱਧੀ ਸੜਕ 'ਤੇ A ਅਤੇ B ਵਿਚਕਾਰ ਦੂਰੀ200ਕਿਮੀ ਹੈ। ਇੱਕ ਕਾਰ A ਤੋਂ B ਵੱਲ40ਕਿਮੀ/ਘੰਟਾ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਚੱਲਦੀ ਹੈ। ਉਸੇ ਵੇਲੇ ਦੂਜੀ ਕਾਰ B ਤੋਂ AB ਦੇ ਲੰਬਵਤ ਸੜਕ 'ਤੇ20ਕਿਮੀ/ਘੰਟਾ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਚੱਲਦੀ ਹੈ। ਕਿੰਨੇ ਘੰਟਿਆਂ ਬਾਅਦ ਦੋਵਾਂ ਕਾਰਾਂ ਵਿਚਕਾਰ ਦੂਰੀ ਸਭ ਤੋਂ ਘੱਟ ਹੋਵੇਗੀ?"],steps:[
 ["After t hours, distance²=(200−40t)²+(20t)².","tघंटे बाद दूरी²=(200−40t)²+(20t)²।","tਘੰਟਿਆਂ ਬਾਅਦ ਦੂਰੀ²=(200−40t)²+(20t)²।"],
 ["Distance²=2000(t−4)²+8000, which is least at t=4hours.","दूरी²=2000(t−4)²+8000। यह t=4घंटे पर सबसे कम है।","ਦੂਰੀ²=2000(t−4)²+8000। ਇਹ t=4ਘੰਟਿਆਂ 'ਤੇ ਸਭ ਤੋਂ ਘੱਟ ਹੈ।"]]},
 {id:"POLYNOMIAL",source:"CORRECTED-LOD-III-Q21",model:"polynomialMotion",advanced:true,solution:motion.solvePolynomialMotion({coefficients:[r(4),r(-5),r(1)],at:r(6),sampleSeconds:7}),answers:["14","22","28","10"],correct:1,stems:[
 "A particle moves on a straight line. During the second beginning at integer time t, it keeps velocity v=t²−5t+4m/s; a negative value means motion in the opposite direction. What distance does it travel in the first7seconds?",
 "एक कण सीधी रेखा पर चलता है। पूर्णांक समय tसे शुरू होने वाले प्रत्येक सेकंड में उसका वेग v=t²−5t+4मी/सेकंड स्थिर रहता है। ऋणात्मक वेग का अर्थ विपरीत दिशा में चलना है। पहले7सेकंड में कण कितनी दूरी तय करता है?",
 "ਇੱਕ ਕਣ ਸਿੱਧੀ ਰੇਖਾ 'ਤੇ ਚੱਲਦਾ ਹੈ। ਪੂਰਨ ਅੰਕ ਸਮੇਂ tਤੋਂ ਸ਼ੁਰੂ ਹੋਣ ਵਾਲੇ ਹਰ ਸਕਿੰਟ ਵਿੱਚ ਉਸ ਦਾ ਵੇਗ v=t²−5t+4ਮੀ/ਸਕਿੰਟ ਇੱਕਸਾਰ ਰਹਿੰਦਾ ਹੈ। ਰਿਣਾਤਮਕ ਵੇਗ ਦਾ ਅਰਥ ਉਲਟ ਦਿਸ਼ਾ ਵਿੱਚ ਚੱਲਣਾ ਹੈ। ਪਹਿਲੇ7ਸਕਿੰਟਾਂ ਵਿੱਚ ਕਣ ਕਿੰਨੀ ਦੂਰੀ ਤੈਅ ਕਰਦਾ ਹੈ?"],steps:[
 ["For t=0,1,2,3,4,5,6, the velocities are4,0,−2,−2,0,4,10m/s.","t=0,1,2,3,4,5,6पर वेग क्रमशः4,0,−2,−2,0,4,10मी/सेकंड हैं।","t=0,1,2,3,4,5,6'ਤੇ ਵੇਗ ਕ੍ਰਮਵਾਰ4,0,−2,−2,0,4,10ਮੀ/ਸਕਿੰਟ ਹਨ।"],
 ["Distance uses magnitudes:4+0+2+2+0+4+10=22m. Signed displacement is14m.","दूरी के लिए वेग के परिमाण लेते हैं:4+0+2+2+0+4+10=22मीटर। विस्थापन14मीटर है।","ਦੂਰੀ ਲਈ ਵੇਗ ਦੇ ਪਰਿਮਾਣ ਲੈਂਦੇ ਹਾਂ:4+0+2+2+0+4+10=22ਮੀਟਰ। ਵਿਸਥਾਪਨ14ਮੀਟਰ ਹੈ।"]]},
 {id:"BRAKING",source:"AUTHORED-VARIANT-LOD-III-Q14",model:"constantAcceleration",advanced:true,solution:motion.solveConstantAcceleration({initialSpeed:r(20),acceleration:r(-1,10),time:r(240),stopAtZero:true}),answers:["1000","2000","2400","4000"],correct:1,stems:[
 "A boat moving at20m/s slows uniformly at0.1m/s² until it stops. How far does it travel while slowing down?",
 "20मी/सेकंड की गति से चल रही नाव रुकने तक0.1मी/सेकंड²की दर से समान रूप से धीमी होती है। इस दौरान वह कितनी दूरी तय करती है?",
 "20ਮੀ/ਸਕਿੰਟ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਚੱਲ ਰਹੀ ਕਿਸ਼ਤੀ ਰੁਕਣ ਤੱਕ0.1ਮੀ/ਸਕਿੰਟ²ਦੀ ਦਰ ਨਾਲ ਇੱਕਸਾਰ ਹੌਲੀ ਹੁੰਦੀ ਹੈ। ਇਸ ਦੌਰਾਨ ਉਹ ਕਿੰਨੀ ਦੂਰੀ ਤੈਅ ਕਰਦੀ ਹੈ?"],steps:[
 ["Stopping time=20/0.1=200seconds.","रुकने का समय=20/0.1=200सेकंड।","ਰੁਕਣ ਦਾ ਸਮਾਂ=20/0.1=200ਸਕਿੰਟ।"],
 ["Average speed=(20+0)/2=10m/s; distance=10×200=2000m.","औसत गति=(20+0)/2=10मी/सेकंड; दूरी=10×200=2000मीटर।","ਔਸਤ ਰਫ਼ਤਾਰ=(20+0)/2=10ਮੀ/ਸਕਿੰਟ; ਦੂਰੀ=10×200=2000ਮੀਟਰ।"]]},
 {id:"HIGHWAY",source:"LOD-III-Q19",model:"highwayTurn",advanced:true,solution:motion.solveHighwayTurn({projectionDistance:r(30),perpendicularDistance:r(16),highwaySpeed:r(10),offRoadSpeed:r(6)}),answers:["12","18","20","30"],correct:1,unit:"distance",stems:[
 "A destination is16km from a straight highway. Its perpendicular projection onto the highway is30km ahead of a cyclist's starting point. The cyclist travels at10km/h on the highway and6km/h off it. How far along the highway should the cyclist travel before turning towards the destination to minimize travel time?",
 "एक गंतव्य सीधी मुख्य सड़क से16किमी दूर है। गंतव्य से सड़क पर खींचे गए लंब का पाद साइकिल चालक के शुरुआती बिंदु से30किमी आगे है। मुख्य सड़क पर गति10किमी/घंटा और उसके बाहर6किमी/घंटा है। सबसे कम समय में पहुँचने के लिए चालक कितनी दूरी मुख्य सड़क पर चलने के बाद गंतव्य की ओर मुड़े?",
 "ਇੱਕ ਮੰਜ਼ਿਲ ਸਿੱਧੀ ਮੁੱਖ ਸੜਕ ਤੋਂ16ਕਿਮੀ ਦੂਰ ਹੈ। ਮੰਜ਼ਿਲ ਤੋਂ ਸੜਕ 'ਤੇ ਖਿੱਚੇ ਲੰਬ ਦਾ ਪੈਰ ਸਾਈਕਲ ਸਵਾਰ ਦੇ ਸ਼ੁਰੂਆਤੀ ਬਿੰਦੂ ਤੋਂ30ਕਿਮੀ ਅੱਗੇ ਹੈ। ਮੁੱਖ ਸੜਕ 'ਤੇ ਰਫ਼ਤਾਰ10ਕਿਮੀ/ਘੰਟਾ ਅਤੇ ਉਸ ਤੋਂ ਬਾਹਰ6ਕਿਮੀ/ਘੰਟਾ ਹੈ। ਸਭ ਤੋਂ ਘੱਟ ਸਮੇਂ ਵਿੱਚ ਪਹੁੰਚਣ ਲਈ ਉਹ ਮੁੱਖ ਸੜਕ 'ਤੇ ਕਿੰਨੀ ਦੂਰੀ ਚੱਲਣ ਮਗਰੋਂ ਮੰਜ਼ਿਲ ਵੱਲ ਮੁੜੇ?"],steps:[
 ["Let x be the highway distance still left before the projection. Travel time=(30−x)/10+√(x²+256)/6.","लंब के पाद तक सड़क पर बची दूरी xमानें। समय=(30−x)/10+√(x²+256)/6।","ਲੰਬ ਦੇ ਪੈਰ ਤੱਕ ਸੜਕ 'ਤੇ ਬਾਕੀ ਦੂਰੀ xਮੰਨੋ। ਸਮਾਂ=(30−x)/10+√(x²+256)/6।"],
 ["At the minimum, x/√(x²+256)=6/10, giving x=12. Turn after30−12=18km.","न्यूनतम समय के लिए x/√(x²+256)=6/10से x=12मिलता है।30−12=18किमी बाद मुड़ना चाहिए।","ਘੱਟੋ-ਘੱਟ ਸਮੇਂ ਲਈ x/√(x²+256)=6/10ਤੋਂ x=12ਮਿਲਦਾ ਹੈ।30−12=18ਕਿਮੀ ਬਾਅਦ ਮੁੜਨਾ ਚਾਹੀਦਾ ਹੈ।"]]},
 {id:"CATCH",source:"AUTHORED-VARIANT-LOD-III-Q27",model:"acceleratedCatch",advanced:true,solution:motion.solveAcceleratedCatch({initialLeaderSpeed:r(5),leaderAcceleration:r(4),chaserSpeed:r(9)}),answers:["1","2","3","4"],correct:1,unit:"seconds",stems:[
 "Two vehicles start at the same point and move in the same direction. The first starts at5m/s and accelerates uniformly at4m/s². The second keeps a constant speed of9m/s. After how many seconds do they meet again?",
 "दो वाहन एक ही बिंदु से एक ही दिशा में चलना शुरू करते हैं। पहला5मी/सेकंड की शुरुआती गति से4मी/सेकंड²के समान त्वरण के साथ चलता है। दूसरा9मी/सेकंड की स्थिर गति से चलता है। कितने सेकंड बाद वे फिर मिलेंगे?",
 "ਦੋ ਵਾਹਨ ਇੱਕੋ ਬਿੰਦੂ ਤੋਂ ਇੱਕੋ ਦਿਸ਼ਾ ਵਿੱਚ ਚੱਲਣਾ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ। ਪਹਿਲਾ5ਮੀ/ਸਕਿੰਟ ਦੀ ਸ਼ੁਰੂਆਤੀ ਰਫ਼ਤਾਰ ਨਾਲ4ਮੀ/ਸਕਿੰਟ²ਦੇ ਇੱਕਸਾਰ ਪ੍ਰਵੇਗ ਨਾਲ ਚੱਲਦਾ ਹੈ। ਦੂਜਾ9ਮੀ/ਸਕਿੰਟ ਦੀ ਇੱਕਸਾਰ ਰਫ਼ਤਾਰ ਨਾਲ ਚੱਲਦਾ ਹੈ। ਕਿੰਨੇ ਸਕਿੰਟਾਂ ਬਾਅਦ ਉਹ ਮੁੜ ਮਿਲਣਗੇ?"],steps:[
 ["First distance=5t+2t²; second distance=9t.","पहले वाहन की दूरी=5t+2t²; दूसरे की दूरी=9t।","ਪਹਿਲੇ ਵਾਹਨ ਦੀ ਦੂਰੀ=5t+2t²; ਦੂਜੇ ਦੀ ਦੂਰੀ=9t।"],
 ["2t²−4t=0. Excluding their shared start t=0, they meet at t=2seconds.","2t²−4t=0। शुरुआती समय t=0को छोड़कर दोनों t=2सेकंड पर मिलते हैं।","2t²−4t=0। ਸ਼ੁਰੂਆਤੀ ਸਮਾਂ t=0ਛੱਡ ਕੇ ਦੋਵੇਂ t=2ਸਕਿੰਟਾਂ 'ਤੇ ਮਿਲਦੇ ਹਨ।"]]},
 {id:"LAP",source:"TASTE-Q41",model:"geometricLapTime",solution:motion.solveGeometricLapTime(2),answers:["4","8","16","32"],correct:2,stems:[
 "A runner covers a circular track in successive stages, each covering a quarter of a lap. Each stage takes twice as long as the previous one. What is the ratio of the time for any lap after the first to that for the immediately preceding lap?",
 "एक धावक वृत्ताकार पथ पर चरणों में दौड़ता है। हर चरण में वह एक चौथाई चक्कर पूरा करता है और पिछले चरण से दोगुना समय लेता है। पहले चक्कर के बाद किसी चक्कर के समय और उससे ठीक पहले वाले चक्कर के समय का अनुपात क्या है?",
 "ਇੱਕ ਦੌੜਾਕ ਗੋਲ ਪਥ 'ਤੇ ਪੜਾਵਾਂ ਵਿੱਚ ਦੌੜਦਾ ਹੈ। ਹਰ ਪੜਾਅ ਵਿੱਚ ਉਹ ਚੌਥਾਈ ਚੱਕਰ ਪੂਰਾ ਕਰਦਾ ਹੈ ਅਤੇ ਪਿਛਲੇ ਪੜਾਅ ਨਾਲੋਂ ਦੁੱਗਣਾ ਸਮਾਂ ਲੈਂਦਾ ਹੈ। ਪਹਿਲੇ ਚੱਕਰ ਮਗਰੋਂ ਕਿਸੇ ਚੱਕਰ ਦੇ ਸਮੇਂ ਅਤੇ ਉਸ ਤੋਂ ਠੀਕ ਪਹਿਲੇ ਚੱਕਰ ਦੇ ਸਮੇਂ ਦਾ ਅਨੁਪਾਤ ਕੀ ਹੈ?"],steps:[
 ["One lap contains4stages. Corresponding stages of consecutive laps are4doublings apart.","एक चक्कर में4चरण हैं। लगातार दो चक्करों के समान स्थान वाले चरणों के बीच समय4बार दोगुना होता है।","ਇੱਕ ਚੱਕਰ ਵਿੱਚ4ਪੜਾਅ ਹਨ। ਲਗਾਤਾਰ ਦੋ ਚੱਕਰਾਂ ਦੇ ਇੱਕੋ ਸਥਾਨ ਵਾਲੇ ਪੜਾਵਾਂ ਵਿਚਕਾਰ ਸਮਾਂ4ਵਾਰ ਦੁੱਗਣਾ ਹੁੰਦਾ ਹੈ।"],
 ["Each stage time, and therefore each lap time, is multiplied by2⁴=16.","हर चरण का समय और इसलिए पूरे चक्कर का समय2⁴=16गुना होता है।","ਹਰ ਪੜਾਅ ਦਾ ਸਮਾਂ ਅਤੇ ਇਸ ਲਈ ਪੂਰੇ ਚੱਕਰ ਦਾ ਸਮਾਂ2⁴=16ਗੁਣਾ ਹੁੰਦਾ ਹੈ।"]]},
 {id:"LIFT",source:"AUTHORED-VARIANT-LOD-III-Q43",model:"returnLiftInverse",solution:motion.solveReturnLiftInverse({route:r(5),driverTimeFactor:r(13,5),walkTimeSaved:r(2,3)}),answers:["3","9/2","6","18"],correct:1,unit:"speed",stems:[
 "A motorcyclist leaves P for Q while a walker leaves Q for P; PQ is5km. They meet, and the motorcyclist carries the walker back to P before continuing to Q. The motorcyclist takes13/5of the usual P-to-Q time, while the walker saves40minutes. Both keep their respective constant speeds. What is the walker's speed?",
 "Pऔर Qकी दूरी5किमी है। एक मोटरसाइकिल चालक Pसे Qऔर एक पैदल यात्री Qसे Pकी ओर चलते हैं। मिलने पर चालक यात्री को Pले जाता है और फिर Qजाता है। चालक अपनी सामान्य यात्रा के13/5गुना समय में Qपहुँचता है, जबकि यात्री के40मिनट बचते हैं। दोनों की अपनी-अपनी गति स्थिर है। पैदल यात्री की गति कितनी है?",
 "Pਅਤੇ Qਵਿਚਕਾਰ ਦੂਰੀ5ਕਿਮੀ ਹੈ। ਇੱਕ ਮੋਟਰਸਾਈਕਲ ਸਵਾਰ Pਤੋਂ Qਅਤੇ ਇੱਕ ਪੈਦਲ ਯਾਤਰੀ Qਤੋਂ Pਵੱਲ ਚੱਲਦੇ ਹਨ। ਮਿਲਣ 'ਤੇ ਸਵਾਰ ਯਾਤਰੀ ਨੂੰ Pਲੈ ਜਾਂਦਾ ਹੈ ਅਤੇ ਫਿਰ Qਜਾਂਦਾ ਹੈ। ਸਵਾਰ ਆਪਣੀ ਆਮ ਯਾਤਰਾ ਦੇ13/5ਗੁਣਾ ਸਮੇਂ ਵਿੱਚ Qਪਹੁੰਚਦਾ ਹੈ, ਜਦਕਿ ਯਾਤਰੀ ਦੇ40ਮਿੰਟ ਬਚਦੇ ਹਨ। ਦੋਵਾਂ ਦੀ ਆਪਣੀ-ਆਪਣੀ ਰਫ਼ਤਾਰ ਇੱਕਸਾਰ ਹੈ। ਪੈਦਲ ਯਾਤਰੀ ਦੀ ਰਫ਼ਤਾਰ ਕਿੰਨੀ ਹੈ?"],steps:[
 ["Let the meeting point be xkm from P. The motorcyclist travels5+2xkm, so5+2x=(13/5)×5 and x=4.","मिलने का बिंदु Pसे xकिमी दूर मानें। चालक5+2xकिमी चलता है।5+2x=(13/5)×5से x=4मिलता है।","ਮਿਲਣ ਦਾ ਬਿੰਦੂ Pਤੋਂ xਕਿਮੀ ਦੂਰ ਮੰਨੋ। ਸਵਾਰ5+2xਕਿਮੀ ਚੱਲਦਾ ਹੈ।5+2x=(13/5)×5ਤੋਂ x=4ਮਿਲਦਾ ਹੈ।"],
 ["Speed ratio=4:1. If walking speed is v, time saved=4/v−4/(4v)=3/vhours.","गति का अनुपात4:1है। पैदल गति vहोने पर बचा समय=4/v−4/(4v)=3/vघंटे।","ਰਫ਼ਤਾਰਾਂ ਦਾ ਅਨੁਪਾਤ4:1ਹੈ। ਪੈਦਲ ਰਫ਼ਤਾਰ vਹੋਣ 'ਤੇ ਬਚਿਆ ਸਮਾਂ=4/v−4/(4v)=3/vਘੰਟੇ।"],
 ["3/v=40/60=2/3, so v=9/2km/h.","3/v=40/60=2/3से v=9/2किमी/घंटा।","3/v=40/60=2/3ਤੋਂ v=9/2ਕਿਮੀ/ਘੰਟਾ।"]]},
 {id:"PICKUP",source:"AUTHORED-VARIANT-LOD-III-Q45",model:"sharedRideDropPickup",solution:motion.solveSharedRideDropPickup({route:r(10),dropPoint:r(5),driverSpeed:r(25),walkSpeed:r(10)}),answers:["9/7","10/7","5/3","2"],correct:0,unit:"distance",stems:[
 "P and Q are10km apart. A motorcyclist A travels at25km/h; runners B and C travel at10km/h. All start at P, with B riding with A. A drops B at the midpoint, turns back to collect C, then takes C to Q. B runs towards Q after being dropped. How far is B from Q when A and C reach Q?",
 "Pऔर Qकी दूरी10किमी है। मोटरसाइकिल चालक Aकी गति25किमी/घंटा और धावकों Bऔर Cकी गति10किमी/घंटा है। तीनों Pसे शुरू करते हैं; B, Aके साथ बैठता है। A, Bको बीच के बिंदु पर उतारकर Cको लेने लौटता है और फिर Cको Qले जाता है। उतरने के बाद B, Qकी ओर दौड़ता है। Aऔर Cके Qपहुँचने पर B, Qसे कितना दूर है?",
 "Pਅਤੇ Qਵਿਚਕਾਰ ਦੂਰੀ10ਕਿਮੀ ਹੈ। ਮੋਟਰਸਾਈਕਲ ਸਵਾਰ Aਦੀ ਰਫ਼ਤਾਰ25ਕਿਮੀ/ਘੰਟਾ ਅਤੇ ਦੌੜਾਕਾਂ Bਅਤੇ Cਦੀ ਰਫ਼ਤਾਰ10ਕਿਮੀ/ਘੰਟਾ ਹੈ। ਤਿੰਨੇ Pਤੋਂ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ; B, Aਨਾਲ ਬੈਠਦਾ ਹੈ। A, Bਨੂੰ ਵਿਚਕਾਰਲੇ ਬਿੰਦੂ 'ਤੇ ਉਤਾਰ ਕੇ Cਨੂੰ ਲੈਣ ਪਰਤਦਾ ਹੈ ਅਤੇ ਫਿਰ Cਨੂੰ Qਲੈ ਜਾਂਦਾ ਹੈ। ਉਤਰਨ ਮਗਰੋਂ B, Qਵੱਲ ਦੌੜਦਾ ਹੈ। Aਅਤੇ Cਦੇ Qਪਹੁੰਚਣ 'ਤੇ B, Qਤੋਂ ਕਿੰਨਾ ਦੂਰ ਹੈ?"],steps:[
 ["A drops B after5/25=1/5hour; C has run2km. A and C close the3km gap at35km/h, taking3/35hour.","A, Bको1/5घंटे बाद उतारता है। तब Cने2किमी तय किए हैं। Aऔर Cका3किमी का अंतर35किमी/घंटा की सापेक्ष गति से3/35घंटे में मिटता है।","A, Bਨੂੰ1/5ਘੰਟੇ ਬਾਅਦ ਉਤਾਰਦਾ ਹੈ। ਉਦੋਂ Cਨੇ2ਕਿਮੀ ਤੈਅ ਕੀਤੇ ਹਨ। Aਅਤੇ Cਦਾ3ਕਿਮੀ ਦਾ ਫ਼ਰਕ35ਕਿਮੀ/ਘੰਟਾ ਦੀ ਸਾਪੇਖ ਰਫ਼ਤਾਰ ਨਾਲ3/35ਘੰਟੇ ਵਿੱਚ ਮੁੱਕਦਾ ਹੈ।"],
 ["Pickup time=2/7hour and point=20/7km. A and C reach Q at4/7hour.","Cको लेने का समय2/7घंटा और बिंदु Pसे20/7किमी दूर है। Aऔर C,4/7घंटे में Qपहुँचते हैं।","Cਨੂੰ ਲੈਣ ਦਾ ਸਮਾਂ2/7ਘੰਟਾ ਅਤੇ ਬਿੰਦੂ Pਤੋਂ20/7ਕਿਮੀ ਦੂਰ ਹੈ। Aਅਤੇ C,4/7ਘੰਟੇ ਵਿੱਚ Qਪਹੁੰਚਦੇ ਹਨ।"],
 ["B's position=5+10(4/7−1/5)=61/7km. Remaining distance=10−61/7=9/7km.","Bकी दूरी=5+10(4/7−1/5)=61/7किमी। बची दूरी=10−61/7=9/7किमी।","Bਦੀ ਦੂਰੀ=5+10(4/7−1/5)=61/7ਕਿਮੀ। ਬਾਕੀ ਦੂਰੀ=10−61/7=9/7ਕਿਮੀ।"]]},
 {id:"EXCHANGE",source:"AUTHORED-VARIANT-REVIEW3-Q9",model:"meetingSpeedExchange",solution:solveMeetingSpeedExchange({track:r(400),speedA:r(3),speedB:r(1),events:3}),answers:["500","600","700","900"],correct:2,stems:[
 "Two runners start together on a400m circular track in opposite directions at3m/s and1m/s. At each meeting away from the start, both reverse direction and exchange speeds. How far has the initially faster runner travelled by their third meeting?",
 "दो धावक400मीटर के वृत्ताकार पथ पर एक ही बिंदु से विपरीत दिशाओं में3मी/सेकंड और1मी/सेकंड की गति से शुरू करते हैं। शुरुआती बिंदु के अलावा हर मिलने पर दोनों दिशा उलटते हैं और अपनी गति आपस में बदलते हैं। तीसरी बार मिलने तक शुरू में तेज धावक कितनी दूरी तय करता है?",
 "ਦੋ ਦੌੜਾਕ400ਮੀਟਰ ਦੇ ਗੋਲ ਪਥ 'ਤੇ ਇੱਕੋ ਬਿੰਦੂ ਤੋਂ ਉਲਟ ਦਿਸ਼ਾਵਾਂ ਵਿੱਚ3ਮੀ/ਸਕਿੰਟ ਅਤੇ1ਮੀ/ਸਕਿੰਟ ਦੀ ਰਫ਼ਤਾਰ ਨਾਲ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ। ਸ਼ੁਰੂਆਤੀ ਬਿੰਦੂ ਤੋਂ ਇਲਾਵਾ ਹਰ ਵਾਰ ਮਿਲਣ 'ਤੇ ਦੋਵੇਂ ਦਿਸ਼ਾ ਉਲਟਦੇ ਹਨ ਅਤੇ ਆਪਣੀਆਂ ਰਫ਼ਤਾਰਾਂ ਆਪਸ ਵਿੱਚ ਬਦਲਦੇ ਹਨ। ਤੀਜੀ ਵਾਰ ਮਿਲਣ ਤੱਕ ਸ਼ੁਰੂ ਵਿੱਚ ਤੇਜ਼ ਦੌੜਾਕ ਕਿੰਨੀ ਦੂਰੀ ਤੈਅ ਕਰਦਾ ਹੈ?"],steps:[
 ["Their combined speed stays4m/s, so successive meetings are400/4=100seconds apart.","दोनों की संयुक्त गति4मी/सेकंड रहती है। इसलिए लगातार मिलने का अंतर400/4=100सेकंड है।","ਦੋਵਾਂ ਦੀ ਸਾਂਝੀ ਰਫ਼ਤਾਰ4ਮੀ/ਸਕਿੰਟ ਰਹਿੰਦੀ ਹੈ। ਇਸ ਲਈ ਲਗਾਤਾਰ ਮਿਲਣ ਦਾ ਫ਼ਰਕ400/4=100ਸਕਿੰਟ ਹੈ।"],
 ["The initially faster runner's speeds in the first three intervals are3,1,3m/s. Distance=100(3+1+3)=700m.","पहले तीन अंतरालों में शुरू के तेज धावक की गति3,1,3मी/सेकंड है। दूरी=100(3+1+3)=700मीटर।","ਪਹਿਲੇ ਤਿੰਨ ਵਕਫ਼ਿਆਂ ਵਿੱਚ ਸ਼ੁਰੂ ਦੇ ਤੇਜ਼ ਦੌੜਾਕ ਦੀ ਰਫ਼ਤਾਰ3,1,3ਮੀ/ਸਕਿੰਟ ਹੈ। ਦੂਰੀ=100(3+1+3)=700ਮੀਟਰ।"]]},
 {id:"DISPATCH-ORIGIN",source:"TASTE-Q16",model:"stationQueuedDispatch",solution:solveStationQueuedDispatch({length:r(60),speed:r(10),messages,nearestStation:false}),answers:["80","120","140","160"],correct:2,stems:dispatchStem,steps:[
 ["First trip serves A,D and returns:40+40=80m, ending at8s. C and B are then read.","पहली यात्रा में Aऔर Dकी सेवा करके रोबोट लौटता है:40+40=80मीटर, समय8सेकंड। तब Cऔर Bके अनुरोध पढ़े जाते हैं।","ਪਹਿਲੇ ਸਫ਼ਰ ਵਿੱਚ Aਅਤੇ Dਨੂੰ ਸੇਵਾ ਦੇ ਕੇ ਰੋਬੋਟ ਪਰਤਦਾ ਹੈ:40+40=80ਮੀਟਰ, ਸਮਾਂ8ਸਕਿੰਟ। ਉਦੋਂ Cਅਤੇ Bਦੀਆਂ ਬੇਨਤੀਆਂ ਪੜ੍ਹੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।"],
 ["Second trip serves B,C and returns:30+30=60m, ending at14s. E's request is read then; total=80+60=140m.","दूसरी यात्रा में Bऔर Cकी सेवा करके रोबोट लौटता है:30+30=60मीटर, समय14सेकंड। Eका अनुरोध तब पढ़ा जाता है। कुल दूरी=80+60=140मीटर।","ਦੂਜੇ ਸਫ਼ਰ ਵਿੱਚ Bਅਤੇ Cਨੂੰ ਸੇਵਾ ਦੇ ਕੇ ਰੋਬੋਟ ਪਰਤਦਾ ਹੈ:30+30=60ਮੀਟਰ, ਸਮਾਂ14ਸਕਿੰਟ। Eਦੀ ਬੇਨਤੀ ਉਦੋਂ ਪੜ੍ਹੀ ਜਾਂਦੀ ਹੈ। ਕੁੱਲ ਦੂਰੀ=80+60=140ਮੀਟਰ।"]]},
 {id:"DISPATCH-NEAREST",source:"TASTE-Q17",model:"stationQueuedDispatch",solution:solveStationQueuedDispatch({length:r(60),speed:r(10),messages,nearestStation:true}),answers:["80","120","140","160"],correct:1,stems:[
 dispatchStem[0].replace("After each trip it returns to the origin.","There is a second station60m from the origin. After each trip the robot returns to the nearer station, choosing the origin in a tie; both stations receive every request."),
 dispatchStem[1].replace("हर यात्रा के बाद रोबोट मूल स्टेशन पर लौटता है।","मूल स्टेशन से60मीटर दूर एक दूसरा स्टेशन है। हर यात्रा के बाद रोबोट नज़दीकी स्टेशन पर लौटता है; दूरी समान होने पर मूल स्टेशन चुनता है। दोनों स्टेशनों को सभी अनुरोध मिलते हैं।"),
 dispatchStem[2].replace("ਹਰ ਸਫ਼ਰ ਮਗਰੋਂ ਰੋਬੋਟ ਮੁੱਢਲੇ ਸਟੇਸ਼ਨ 'ਤੇ ਪਰਤਦਾ ਹੈ।","ਮੁੱਢਲੇ ਸਟੇਸ਼ਨ ਤੋਂ60ਮੀਟਰ ਦੂਰ ਇੱਕ ਦੂਜਾ ਸਟੇਸ਼ਨ ਹੈ। ਹਰ ਸਫ਼ਰ ਮਗਰੋਂ ਰੋਬੋਟ ਨੇੜਲੇ ਸਟੇਸ਼ਨ 'ਤੇ ਪਰਤਦਾ ਹੈ; ਦੂਰੀ ਬਰਾਬਰ ਹੋਣ 'ਤੇ ਮੁੱਢਲਾ ਸਟੇਸ਼ਨ ਚੁਣਦਾ ਹੈ। ਦੋਵਾਂ ਸਟੇਸ਼ਨਾਂ ਨੂੰ ਸਾਰੀਆਂ ਬੇਨਤੀਆਂ ਮਿਲਦੀਆਂ ਹਨ।")],steps:[
 ["First trip goes to D at40m, then the station at60m: distance60m, time6s. It now reads C,B.","पहली यात्रा Dके40मीटर वाले बिंदु से होकर60मीटर वाले स्टेशन पर समाप्त होती है। दूरी60मीटर और समय6सेकंड है। अब Cऔर Bके अनुरोध पढ़े जाते हैं।","ਪਹਿਲਾ ਸਫ਼ਰ Dਦੇ40ਮੀਟਰ ਵਾਲੇ ਬਿੰਦੂ ਤੋਂ ਹੋ ਕੇ60ਮੀਟਰ ਵਾਲੇ ਸਟੇਸ਼ਨ 'ਤੇ ਮੁੱਕਦਾ ਹੈ। ਦੂਰੀ60ਮੀਟਰ ਅਤੇ ਸਮਾਂ6ਸਕਿੰਟ ਹੈ। ਹੁਣ Cਅਤੇ Bਦੀਆਂ ਬੇਨਤੀਆਂ ਪੜ੍ਹੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।"],
 ["Second trip serves C,B and returns to the origin:60−20+20=60m. It ends at12s, when E is read. Total=120m.","दूसरी यात्रा में Cऔर Bकी सेवा के बाद रोबोट मूल स्टेशन पर लौटता है:60−20+20=60मीटर।12सेकंड पर Eका अनुरोध पढ़ा जाता है। कुल दूरी120मीटर है।","ਦੂਜੇ ਸਫ਼ਰ ਵਿੱਚ Cਅਤੇ Bਨੂੰ ਸੇਵਾ ਦੇਣ ਮਗਰੋਂ ਰੋਬੋਟ ਮੁੱਢਲੇ ਸਟੇਸ਼ਨ 'ਤੇ ਪਰਤਦਾ ਹੈ:60−20+20=60ਮੀਟਰ।12ਸਕਿੰਟਾਂ 'ਤੇ Eਦੀ ਬੇਨਤੀ ਪੜ੍ਹੀ ਜਾਂਦੀ ਹੈ। ਕੁੱਲ ਦੂਰੀ120ਮੀਟਰ ਹੈ।"]]},
];
const locales=["en","hi","pa"] as const;
const units={speed:["km/h","किमी/घंटा","ਕਿਮੀ/ਘੰਟਾ"],distance:["km","किमी","ਕਿਮੀ"],hours:["hours","घंटे","ਘੰਟੇ"],seconds:["seconds","सेकंड","ਸਕਿੰਟ"]} as const;
// Fifteen independently authored states,14models; no numeric-variant inflation.
export const TSD_SOURCE_MOTION_EXTENSION_REVIEW=Object.freeze(cases.flatMap((item,index)=>locales.map((locale,l)=>{
 const suffix=item.unit?units[item.unit][l]:item.id==="SOUND"?["m/s","मी/सेकंड","ਮੀ/ਸਕਿੰਟ"][l]:["POLYNOMIAL","BRAKING","EXCHANGE","DISPATCH-ORIGIN","DISPATCH-NEAREST"].includes(item.id)?["m","मीटर","ਮੀਟਰ"][l]:"";
 const values=item.answers.map(value=>`${value}${suffix?` ${suffix}`:""}`);
 const offset=(index+l)%4,options=Object.freeze([...values.slice(offset),...values.slice(0,offset)]);
 // Keep numbers/formulae unchanged; add spacing between Latin numbers and prose.
 const spacing=(s:string)=>s.replace(/([A-Za-z\u0900-\u097F\u0A00-\u0A7F])(\d)/gu,"$1 $2").replace(/(\d)([A-Za-z\u0900-\u097F\u0A00-\u0A7F])/gu,"$1 $2");
 return Object.freeze({...EDITORIAL_REVIEW_LOCK,version:"TSD-SOURCE-MOTION-REVIEW-V1",familyId:`TSD-SOURCE-${item.id}`,model:item.model,sourceObservation:item.source,locale,advancedSourceOnly:item.advanced??false,
  stem:spacing(item.stems[l]),options,answerText:values[item.correct],correctIndex:(item.correct-offset+4)%4,solution:item.solution,explanation:Object.freeze({steps:Object.freeze(item.steps.map(step=>spacing(step[l])))})});
})));
