import type { ArticleSceneV1 } from "./cp003-catalog-v1";

export const CP003_EXTRA_EASY_SCENES_V1: readonly ArticleSceneV1[] = [
  { id:"E081",domain:"environment",ruleId:"GR-ART-001",difficulty:"easy",correctSegments:["The ranger carried","a map","during the patrol","through the park."],errorSegments:["The ranger carried","map","during the patrol","through the park."],errorIndex:1,correction:"a map",reason:"A singular count noun needs a determiner here." },
  { id:"E082",domain:"hospitality",ruleId:"GR-ART-002",difficulty:"easy",correctSegments:["The guest waited for","an hour","in the lobby","before check-in."],errorSegments:["The guest waited for","a hour","in the lobby","before check-in."],errorIndex:1,correction:"an hour",reason:"Hour begins with a vowel sound, so it takes an." },
  { id:"E083",domain:"household",ruleId:"GR-ART-003",difficulty:"easy",correctSegments:["This is","the smallest room","in the house","near the stairs."],errorSegments:["This is","a smallest room","in the house","near the stairs."],errorIndex:1,correction:"the smallest room",reason:"A superlative identifying one item in a group normally takes the." },
  { id:"E084",domain:"manufacturing",ruleId:"GR-ART-006",difficulty:"easy",correctSegments:["His sister is","a machine operator","at the factory","outside the town."],errorSegments:["His sister is","machine operator","at the factory","outside the town."],errorIndex:1,correction:"a machine operator",reason:"A singular profession after be needs an indefinite article." },
  { id:"E085",domain:"emergency-service",ruleId:"GR-ART-001",difficulty:"easy",correctSegments:["The responder carried","a first-aid box","to the vehicle","before leaving."],errorSegments:["The responder carried","first-aid box","to the vehicle","before leaving."],errorIndex:1,correction:"a first-aid box",reason:"A singular count noun needs a determiner here." },
  { id:"E086",domain:"banking",ruleId:"GR-ART-002",difficulty:"easy",correctSegments:["The officer gave","an honest reply","to the customer","during the meeting."],errorSegments:["The officer gave","a honest reply","to the customer","during the meeting."],errorIndex:1,correction:"an honest reply",reason:"Honest begins with a vowel sound, so it takes an." },
  { id:"E087",domain:"agriculture",ruleId:"GR-ART-003",difficulty:"easy",correctSegments:["This was","the largest field","on the farm","that season."],errorSegments:["This was","a largest field","on the farm","that season."],errorIndex:1,correction:"the largest field",reason:"A superlative identifying one item in a group normally takes the." },
  { id:"E088",domain:"infrastructure",ruleId:"GR-ART-006",difficulty:"easy",correctSegments:["Her uncle is","an engineer","with the road project","near the city."],errorSegments:["Her uncle is","engineer","with the road project","near the city."],errorIndex:1,correction:"an engineer",reason:"A singular profession after be needs an indefinite article." }
] as const;
