import { writeFileSync } from "node:fs";
import { escapeHtml, selectDi009V2ReviewSets } from "./review-utils";
const outputPath = process.argv[2] || "DI-009-REVIEW-V4.html";
const sets = selectDi009V2ReviewSets();
function table(headers: readonly string[], rows: readonly (readonly string[])[]) { return `<table><thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`; }
const sections = sets.map((set, setIndex) => {
  const questions = set.questions.map((question, questionIndex) => { const options = question.options.map((option, index) => `<li><span class="option-letter">${String.fromCharCode(65 + index)}.</span> ${escapeHtml(option)}</li>`).join(""); const steps = question.explanation.steps.map((step) => `<li>${escapeHtml(step)}</li>`).join(""); const working = question.explanation.workingTable ? table(question.explanation.workingTable.headers, question.explanation.workingTable.rows) : ""; return `<article class="question"><h3>Q${questionIndex + 1}. ${escapeHtml(question.stem)}</h3><ol class="options">${options}</ol><div class="answer"><strong>Answer:</strong> ${String.fromCharCode(65 + question.correctIndex)}. ${escapeHtml(question.answer)}</div><div class="explanation"><strong>Explanation:</strong> ${escapeHtml(question.explanation.keyIdea)}<ol>${steps}</ol>${working}</div><div class="meta">${escapeHtml(question.kind)} · ${escapeHtml(question.difficulty)}</div></article>`; }).join("");
  return `<section class="set"><div class="set-heading"><div><h2>Set ${setIndex + 1} — ${escapeHtml(set.examProfile)}</h2><p class="set-meta"><strong>Shape:</strong> ${escapeHtml(set.stimulus.shape)} &nbsp; <strong>Classes:</strong> ${set.stimulus.bins.length} &nbsp; <strong>Context:</strong> ${escapeHtml(set.stimulus.title)}</p></div><span class="visual-badge">DI Visual V4</span></div><div class="histogram">${set.stimulus.svg}</div>${questions}</section>`;
}).join("");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DI-009 Histogram V4 Review</title><style>:root{--bg:#eef3f8;--card:#fff;--text:#102a43;--muted:#61758a;--line:#dce6f0;--accent:#1f5b99;--accent-dark:#173a5e;--answer:#eef8f1;--soft:#f7fafe;--blue-soft:#edf5ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,-apple-system,"Segoe UI",Arial,sans-serif;line-height:1.55}main{width:min(1160px,calc(100% - 24px));margin:24px auto 60px}.hero,.set{background:var(--card);border:1px solid var(--line);border-radius:20px;padding:clamp(18px,4vw,38px);margin-bottom:24px;box-shadow:0 12px 34px rgba(23,58,94,.065)}h1{margin:0 0 10px;font-size:clamp(28px,5vw,42px);letter-spacing:-.02em;color:#102a43}h2{margin:0;color:var(--accent-dark);font-size:clamp(20px,3vw,26px)}.set-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;border-bottom:1px solid var(--line);padding-bottom:14px}.set-meta,.meta{color:var(--muted)}.set-meta{margin:8px 0 0}.visual-badge{flex:none;background:var(--blue-soft);border:1px solid #cfe1f5;color:var(--accent);border-radius:999px;padding:6px 10px;font-size:.76rem;font-weight:750}.histogram{overflow-x:auto;margin:22px 0 32px;padding:18px;border:1px solid var(--line);border-radius:18px;background:#fff;box-shadow:0 5px 18px rgba(23,58,94,.04);scrollbar-gutter:stable}.histogram svg{display:block;width:100%;min-width:700px;max-width:920px;height:auto;margin:auto}.question{padding:22px 0;border-top:1px solid var(--line)}.question h3{font-size:1.07rem;margin:0 0 12px}.options{list-style:none;padding:0}.options li{padding:8px 11px;margin:7px 0;background:var(--soft);border:1px solid #e6edf5;border-radius:9px}.option-letter{font-weight:700;display:inline-block;width:24px;color:var(--accent-dark)}.answer{background:var(--answer);padding:10px 12px;border-radius:9px;margin:12px 0}.meta{font-size:.86rem;margin-top:12px}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid var(--line);padding:8px 10px;text-align:left}th{background:#f4f8fc;color:#173a5e}@media(max-width:700px){main{width:calc(100% - 12px)}.hero,.set{padding:15px}.set-heading{display:block}.visual-badge{display:inline-block;margin-top:10px}.histogram{padding:9px}.histogram svg{min-width:680px}}@media print{body{background:#fff}.hero,.set{box-shadow:none;border:0}.histogram svg{min-width:0}}</style></head><body><main><section class="hero"><h1>DI-009 Histogram — V4 Visual Review</h1><p>Review-only. V4 corrects axis/tick geometry, exact contiguous bar boundaries, chart headroom and adds a restrained single-series ExamTree blue palette.</p><p><strong>${sets.length} sets · ${sets.reduce((sum, set) => sum + set.questions.length, 0)} questions · 13/13 contract families represented</strong></p></section>${sections}</main></body></html>`;
writeFileSync(outputPath, html, "utf8"); console.log(JSON.stringify({ outputPath, visualVersion: "V4", palette: "EXAMTREE_BLUE_SINGLE_SERIES", sets: sets.length, questions: sets.reduce((sum, set) => sum + set.questions.length, 0) }));
