export const TSD_CP004_STATUS = Object.freeze({
  checkpointId: "TSD-CP-004" as const,
  title: "Straight-Line Relative Motion, Meeting and Pursuit",
  designAuthority: "TSD-END-TO-END-DESIGN-BLUEPRINT.md",
  blueprintDiscoveryCandidates: 33,
  proposedLearnerAuthorities: 16,
  proposedQlRange: Object.freeze({ first: "TSD-QL-048", last: "TSD-QL-063", permanent: false }),
  englishRuntimeStatus: "EXECUTABLE_REVIEW_CANDIDATE" as const,
  hindiStatus: "NATIVE_REVIEW_CANDIDATE" as const,
  punjabiStatus: "NATIVE_REVIEW_CANDIDATE" as const,
  retainedCountApprovedByProductOwner: false,
  permanentQlAllocationAuthorized: false,
  englishFreezeAuthorized: false,
  multilingualFreezeAuthorized: false,
  reviewStatus: "READY_FOR_PRODUCT_OWNER_CP004_COUNT_AND_CONTENT_REVIEW" as const,
  questionStudioDiscoverable: false,
  questionBankStatus: "NOT_STORED" as const,
  testEligibility: "INELIGIBLE" as const,
  publiclyPublishable: false,
  mergeAuthorized: false,
});
