export const MEN_CP_013_DISCOVERY_AUTHORITY = "MEN-CP013-DISCOVERY-CLOSURE-V1" as const;

export type MenCp013Wave = "WAVE01" | "WAVE02" | "WAVE03";
export type MenCp013Disposition = "RETAIN_FOR_MERGE_SPLIT" | "MERGE_AS_REPRESENTATION" | "REASSIGN_BOUNDARY_REVIEW";
export type MenCp013Cluster =
  | "COMPOSITE_VOLUME"
  | "COMPOSITE_SURFACE"
  | "REMOVED_MATERIAL"
  | "INSCRIBED_CONTAINMENT"
  | "VACANT_SPACE"
  | "TANK_CAPACITY"
  | "DISPLACEMENT_LEVEL"
  | "DISPLACEMENT_INVERSE"
  | "OVERFLOW"
  | "PARTIAL_FILL"
  | "SECONDARY_MEASURE";

export interface MenCp013Definition {
  readonly id: string;
  readonly wave: MenCp013Wave;
  readonly cluster: MenCp013Cluster;
  readonly title: string;
  readonly disposition: MenCp013Disposition;
  readonly evidence: string;
  readonly sourceBacked: boolean;
}

export interface MenCp013Question {
  readonly authority: typeof MEN_CP_013_DISCOVERY_AUTHORITY;
  readonly id: string;
  readonly wave: MenCp013Wave;
  readonly cluster: MenCp013Cluster;
  readonly seed: string;
  readonly stem: string;
  readonly options: readonly { readonly label: "A"|"B"|"C"|"D"; readonly display: string; readonly isCorrect: boolean; readonly misconception: string|null }[];
  readonly correctIndex: number;
  readonly answer: string;
  readonly explanation: {
    readonly keyRule: string;
    readonly steps: readonly { readonly title: string; readonly body: string }[];
    readonly shortcut: string;
    readonly traps: readonly string[];
  };
  readonly verification: { readonly valid: true; readonly method: string };
  readonly permanentQlId: null;
  readonly questionStudioDiscoverable: false;
  readonly questionBankStatus: "NOT_STORED";
  readonly testEligibility: "INELIGIBLE";
  readonly publiclyPublishable: false;
}

type Rat={n:bigint;d:bigint};
function gcd(a:bigint,b:bigint){a=a<0n?-a:a;b=b<0n?-b:b;while(b){const t=a%b;a=b;b=t;}return a||1n;}
function R(n:number|bigint,d:number|bigint=1):Rat{let N=BigInt(n),D=BigInt(d);if(D===0n)throw new Error("zero denominator");if(D<0n){N=-N;D=-D;}const g=gcd(N,D);return{n:N/g,d:D/g};}
function add(a:Rat,b:Rat){return R(a.n*b.d+b.n*a.d,a.d*b.d)}
function sub(a:Rat,b:Rat){return R(a.n*b.d-b.n*a.d,a.d*b.d)}
function mul(a:Rat,b:Rat){return R(a.n*b.n,a.d*b.d)}
function div(a:Rat,b:Rat){return R(a.n*b.d,a.d*b.n)}
function pow3(n:number){return BigInt(n)*BigInt(n)*BigInt(n)}
function sq(n:number){return BigInt(n)*BigInt(n)}
function ratText(x:Rat){return x.d===1n?`${x.n}`:`${x.n}/${x.d}`;}
function piText(x:Rat,unit:string){const c=ratText(x);return `${c==="1"?"":c}π ${unit}`;}
function valText(x:Rat,unit:string){return `${ratText(x)} ${unit}`;}
function ratioText(a:number,b:number){const g=Number(gcd(BigInt(a),BigInt(b)));return `${a/g}:${b/g}`;}
function hash(text:string){let h=2166136261>>>0;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}return h>>>0;}
function variant(seed:string,count=5){const m=/(\d+)$/.exec(seed);return m?Math.floor(Number(m[1])/4)%count:hash(`${seed}:v`)%count;}
function pos(seed:string){const m=/(\d+)$/.exec(seed);return m?Number(m[1])%4:hash(`${seed}:p`)%4;}
const LABELS=["A","B","C","D"] as const;

interface Draft{stem:string;answer:string;wrongs:readonly [string,string,string];keyRule:string;steps:readonly {title:string;body:string}[];shortcut:string;traps:readonly string[];verify:string;}
function finalize(def:MenCp013Definition,seed:string,d:Draft):MenCp013Question{
  const unique=new Set([d.answer,...d.wrongs]);if(unique.size!==4)throw new Error(`${def.id}/${seed}: duplicate option value`);
  const ci=pos(seed);let wi=0;
  const opts=LABELS.map((label,index)=>index===ci?{label,display:d.answer,isCorrect:true,misconception:null}:{label,display:d.wrongs[wi]!,isCorrect:false,misconception:`${def.id}-M${++wi}`});
  return{authority:MEN_CP_013_DISCOVERY_AUTHORITY,id:def.id,wave:def.wave,cluster:def.cluster,seed,stem:d.stem,options:opts,correctIndex:ci,answer:d.answer,explanation:{keyRule:d.keyRule,steps:d.steps,shortcut:d.shortcut,traps:d.traps},verification:{valid:true,method:d.verify},permanentQlId:null,questionStudioDiscoverable:false,questionBankStatus:"NOT_STORED",testEligibility:"INELIGIBLE",publiclyPublishable:false};
}

const defs:MenCp013Definition[]=[
  // Wave 01 foundation
  ["CP013-W1-CYLINDER-HEMISPHERE-VOLUME","WAVE01","COMPOSITE_VOLUME","Cylinder + hemisphere toy volume","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: composite added solids",false],
  ["CP013-W1-CONE-HEMISPHERE-VOLUME","WAVE01","COMPOSITE_VOLUME","Cone + hemisphere toy volume","MERGE_AS_REPRESENTATION","MEN-002 authority: composite added solids",false],
  ["CP013-W1-CAPSULE-VOLUME","WAVE01","COMPOSITE_VOLUME","Cylinder + two hemispheres capsule volume","MERGE_AS_REPRESENTATION","MEN-002 authority: composite added solids",false],
  ["CP013-W1-CONE-HEMISPHERE-SURFACE","WAVE01","COMPOSITE_SURFACE","Cone + hemisphere exposed surface","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: composite exposed surface when CP-011 is not dominant",false],
  ["CP013-W1-CAPSULE-SURFACE","WAVE01","COMPOSITE_SURFACE","Capsule exposed surface","MERGE_AS_REPRESENTATION","MEN-002 authority: composite exposed surface",false],
  ["CP013-W1-DRILLED-CYLINDER-VOLUME","WAVE01","REMOVED_MATERIAL","Cylinder drilled coaxially","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: drilled/removed solid region",false],
  ["CP013-W1-CUBE-MINUS-SPHERE-VOLUME","WAVE01","REMOVED_MATERIAL","Cube with largest sphere carved out","MERGE_AS_REPRESENTATION","MEN-002 authority: added/removed regions",false],
  ["CP013-W1-LARGEST-SPHERE-IN-CUBE","WAVE01","INSCRIBED_CONTAINMENT","Largest sphere inside cube","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: inscribed solids",false],
  ["CP013-W1-LARGEST-CONE-IN-CUBE","WAVE01","INSCRIBED_CONTAINMENT","Largest cone inside cube","MERGE_AS_REPRESENTATION","MEN-002 authority: inscribed solids",false],
  ["CP013-W1-SPHERE-IN-CYLINDER-VACANT","WAVE01","VACANT_SPACE","Sphere inside minimum cylinder vacant volume","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: containment difference",false],
  ["CP013-W1-CUBOID-TANK-CAPACITY","WAVE01","TANK_CAPACITY","Cuboid tank capacity","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: static tank capacity",false],
  ["CP013-W1-CYLINDER-TANK-CAPACITY","WAVE01","TANK_CAPACITY","Cylinder tank capacity","MERGE_AS_REPRESENTATION","MEN-002 authority: static tank capacity",false],
  ["CP013-W1-SPHERE-CYLINDER-LEVEL-RISE","WAVE01","DISPLACEMENT_LEVEL","Sphere immersed in cylindrical vessel","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: displacement and level change",false],
  ["CP013-W1-CUBE-CUBOID-LEVEL-RISE","WAVE01","DISPLACEMENT_LEVEL","Cube immersed in rectangular tank","MERGE_AS_REPRESENTATION","MEN-002 authority: displacement and level change",false],
  ["CP013-W1-MULTI-SPHERE-LEVEL-RISE","WAVE01","DISPLACEMENT_LEVEL","Multiple spheres immersed in rectangular tank","MERGE_AS_REPRESENTATION","MEN-002 authority: multiple immersed objects",false],
  ["CP013-W1-PARTIAL-FILL-FINAL-LEVEL","WAVE01","PARTIAL_FILL","Partially filled tank after adding liquid","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: partially filled static tanks",false],
  // Wave 02 inverse/topology discovery
  ["CP013-W2-INVERSE-SPHERE-COUNT","WAVE02","DISPLACEMENT_INVERSE","Find number of immersed spheres from level rise","RETAIN_FOR_MERGE_SPLIT","Inverse displacement axis",false],
  ["CP013-W2-INVERSE-CUBE-SIDE","WAVE02","DISPLACEMENT_INVERSE","Find cube side from level rise","MERGE_AS_REPRESENTATION","Inverse displacement axis",false],
  ["CP013-W2-INVERSE-TANK-BASE-AREA","WAVE02","DISPLACEMENT_INVERSE","Find tank base area from displacement","MERGE_AS_REPRESENTATION","Inverse displacement axis",false],
  ["CP013-W2-DRAW-OFF-LEVEL-DROP","WAVE02","DISPLACEMENT_LEVEL","Water removed from tank causes level fall","RETAIN_FOR_MERGE_SPLIT","Static level decrease representation",false],
  ["CP013-W2-IMMERSION-OVERFLOW","WAVE02","OVERFLOW","Overflow caused by complete immersion","RETAIN_FOR_MERGE_SPLIT","MEN-002 authority: overflow state",false],
  ["CP013-W2-PARTIAL-FILL-OVERFLOW","WAVE02","OVERFLOW","Partially filled tank with immersion and overflow","MERGE_AS_REPRESENTATION","MEN-002 authority: partial fill + overflow",false],
  ["CP013-W2-BORED-CUBOID-VOLUME","WAVE02","REMOVED_MATERIAL","Cylindrical bore through cuboid","MERGE_AS_REPRESENTATION","Drilled/cut solid topology",false],
  ["CP013-W2-LARGEST-CUBE-IN-SPHERE","WAVE02","INSCRIBED_CONTAINMENT","Largest cube inside sphere","RETAIN_FOR_MERGE_SPLIT","Containment relation changes to body diagonal",false],
  ["CP013-W2-CONE-IN-CYLINDER-RATIO","WAVE02","INSCRIBED_CONTAINMENT","Cone and cylinder same base and height volume ratio","MERGE_AS_REPRESENTATION","Containment ratio representation",false],
  ["CP013-W2-COMPOSITE-TOTAL-HEIGHT","WAVE02","COMPOSITE_VOLUME","Composite toy from total height","MERGE_AS_REPRESENTATION","Derived component dimension inside composite",false],
  // Wave 03 source-backed saturation
  ["CP013-W3-SSC-CUBE-TANK-RISE","WAVE03","DISPLACEMENT_LEVEL","SSC CGL cube dropped into rectangular container","MERGE_AS_REPRESENTATION","SSC CGL 2021 Tier-I held 11 Apr 2022: cube immersion level rise",true],
  ["CP013-W3-SSC-SPHERE-CAN-RISE","WAVE03","DISPLACEMENT_LEVEL","SSC CGL sphere immersed in cylindrical can","MERGE_AS_REPRESENTATION","SSC CGL Tier-II memory based 3 Mar 2023: sphere immersion level rise",true],
  ["CP013-W3-SSC-SPHERE-IN-CUBE-TSA","WAVE03","SECONDARY_MEASURE","SSC CGL sphere inscribed in cube then TSA","RETAIN_FOR_MERGE_SPLIT","SSC CGL 2025 held 23 Sep Shift 1: cube volume -> sphere TSA",true],
  ["CP013-W3-SSC-CYL-HEMI-TOY-VOLUME","WAVE03","COMPOSITE_VOLUME","SSC MTS cylinder surmounted by hemisphere volume","MERGE_AS_REPRESENTATION","SSC MTS 11 Jul 2022 Shift 3: composite toy volume",true],
  ["CP013-W3-SSC-LARGEST-SPHERE-CUBE","WAVE03","INSCRIBED_CONTAINMENT","SSC MTS largest sphere carved from cube","MERGE_AS_REPRESENTATION","SSC MTS 9 May 2023 Shift 1: largest sphere in cube",true],
  ["CP013-W3-SSC-LARGEST-CONE-CUBE","WAVE03","INSCRIBED_CONTAINMENT","SSC largest cone inside cube","MERGE_AS_REPRESENTATION","SSC source pattern: largest cone inscribed in cube",true],
  ["CP013-W3-SSC-MULTI-STONE-RISE","WAVE03","DISPLACEMENT_LEVEL","Multiple spherical stones in rectangular tank","MERGE_AS_REPRESENTATION","SSC-style multiple immersed spheres/stones level rise",true],
  ["CP013-W3-SSC-CONE-HEMI-SURFACE","WAVE03","COMPOSITE_SURFACE","SSC CGL cone mounted on hemisphere surface area","MERGE_AS_REPRESENTATION","SSC CGL Tier-II 18 Jan 2025: cone + hemisphere exposed surface",true],
] .map(([id,wave,cluster,title,disposition,evidence,sourceBacked])=>({id:id as string,wave:wave as MenCp013Wave,cluster:cluster as MenCp013Cluster,title:title as string,disposition:disposition as MenCp013Disposition,evidence:evidence as string,sourceBacked:sourceBacked as boolean}));

export const MEN_CP_013_DEFINITIONS=defs as readonly MenCp013Definition[];
export const MEN_CP_013_WAVE01_DEFINITIONS=defs.filter(d=>d.wave==="WAVE01");
export const MEN_CP_013_WAVE02_DEFINITIONS=defs.filter(d=>d.wave==="WAVE02");
export const MEN_CP_013_WAVE03_DEFINITIONS=defs.filter(d=>d.wave==="WAVE03");

function params(seed:string){const v=variant(seed,5);return {v,scale:v+1};}
function baseDraft(id:string,seed:string):Draft{
  const {v,scale}=params(seed);
  switch(id){
    case "CP013-W1-CYLINDER-HEMISPHERE-VOLUME":{const r=[3,4,5,6,7][v]!,h=[8,9,10,11,12][v]!;const c=add(R(r*r*h),R(2*Number(pow3(r)),3));const a=piText(c,"cm³");return{stem:`A solid toy consists of a cylinder of radius ${r} cm and height ${h} cm surmounted by a hemisphere of the same radius. Find its volume.`,answer:a,wrongs:[piText(R(r*r*h),"cm³"),piText(add(R(r*r*h),R(4*Number(pow3(r)),3)),"cm³"),piText(add(R(2*r*r*h),R(2*Number(pow3(r)),3)),"cm³")],keyRule:"Composite volume = sum of non-overlapping component volumes.",steps:[{title:"Split the toy",body:"Use one cylinder and one hemisphere; the circular joining face is internal."},{title:"Write volumes",body:`V = π(${r})²(${h}) + (2/3)π(${r})³.`},{title:"Add exactly",body:`The coefficient of π is ${ratText(c)}.`},{title:"State the volume",body:`Volume = ${a}.`}],shortcut:"Factor π before adding the two component coefficients.",traps:["Do not use the volume of a full sphere.","Do not subtract the joining face: faces affect surface area, not volume."],verify:"independent component-volume addition"};}
    case "CP013-W1-CONE-HEMISPHERE-VOLUME":{const r=[3,6,9,12,15][v]!,h=[8,10,12,14,16][v]!;const c=add(R(r*r*h,3),R(2*Number(pow3(r)),3));const a=piText(c,"cm³");return{stem:`A solid toy is formed by mounting a right circular cone of radius ${r} cm and height ${h} cm on a hemisphere of radius ${r} cm. Find the volume of the toy.`,answer:a,wrongs:[piText(R(r*r*h,3),"cm³"),piText(add(R(r*r*h),R(2*Number(pow3(r)),3)),"cm³"),piText(add(R(r*r*h,3),R(4*Number(pow3(r)),3)),"cm³")],keyRule:"Add cone volume and hemisphere volume.",steps:[{title:"Identify components",body:"The toy is cone + hemisphere."},{title:"Use both volume formulae",body:`V = (1/3)π(${r})²(${h}) + (2/3)π(${r})³.`},{title:"Combine",body:`Coefficient = ${ratText(c)}.`},{title:"Answer",body:`${a}.`}],shortcut:"Take πr²/3 common: V = πr²(h+2r)/3.",traps:["Do not omit the cone factor 1/3.","Use hemisphere volume 2πr³/3, not sphere volume."],verify:"independent cone-plus-hemisphere volume identity"};}
    case "CP013-W1-CAPSULE-VOLUME":{const r=[2,3,4,5,6][v]!,h=[8,10,12,14,16][v]!;const c=add(R(r*r*h),R(4*Number(pow3(r)),3));const a=piText(c,"cm³");return{stem:`A capsule consists of a cylinder of radius ${r} cm and length ${h} cm with a hemisphere attached at each end. Find its volume.`,answer:a,wrongs:[piText(add(R(r*r*h),R(2*Number(pow3(r)),3)),"cm³"),piText(R(r*r*h),"cm³"),piText(add(R(2*r*r*h),R(4*Number(pow3(r)),3)),"cm³")],keyRule:"Two hemispheres together form one sphere.",steps:[{title:"Combine the caps",body:"The two hemispherical ends make one complete sphere."},{title:"Write volume",body:`V = π(${r})²(${h}) + (4/3)π(${r})³.`},{title:"Add",body:`Coefficient = ${ratText(c)}.`},{title:"Answer",body:`${a}.`}],shortcut:"Treat the two end caps as one sphere immediately.",traps:["Do not count only one hemisphere.","The cylinder length excludes the hemispherical caps."],verify:"cylinder plus equivalent full sphere"};}
    case "CP013-W1-CONE-HEMISPHERE-SURFACE":{const r=[3,4,5,6,8][v]!,h=[4,3,12,8,15][v]!;const l=Math.sqrt(r*r+h*h);if(!Number.isInteger(l))return baseDraft(id,`${seed}:0`);const c=R(r*Number(l)+2*r*r);const a=piText(c,"cm²");return{stem:`A closed solid toy is a cone of radius ${r} cm and height ${h} cm mounted on a hemisphere of the same radius. Find the exposed surface area; the common circular face is not exposed.`,answer:a,wrongs:[piText(R(r*Number(l)+3*r*r),"cm²"),piText(R(r*Number(l)+r*r),"cm²"),piText(R(r*Number(l)+4*r*r),"cm²")],keyRule:"For joined solids, count only exposed outer surfaces.",steps:[{title:"Find cone slant height",body:`l = √(${r}²+${h}²) = ${l} cm.`},{title:"Select exposed parts",body:"Use cone CSA + hemisphere CSA; exclude the joining circle."},{title:"Add",body:`Area = π(${r})(${l}) + 2π(${r})².`},{title:"Answer",body:`${a}.`}],shortcut:"Joined cone+hemisphere surface = πr(l+2r).",traps:["Do not add the hidden circular base of the cone.","Hemisphere curved area is 2πr², not 3πr² when its base is joined."],verify:"exposed-surface component accounting"};}
    case "CP013-W1-CAPSULE-SURFACE":{const r=[2,3,4,5,6][v]!,h=[8,10,12,14,16][v]!;const c=R(2*r*h+4*r*r);const a=piText(c,"cm²");return{stem:`A capsule has a cylindrical middle part of radius ${r} cm and length ${h} cm, with hemispherical ends. Find its external surface area.`,answer:a,wrongs:[piText(R(2*r*h+2*r*r),"cm²"),piText(R(2*r*h+6*r*r),"cm²"),piText(R(2*r*h+8*r*r),"cm²")],keyRule:"External area = cylinder curved area + area of two hemispheres.",steps:[{title:"Ignore internal joining circles",body:"The circular end faces are covered by the hemispheres."},{title:"Use curved areas",body:`Area = 2π(${r})(${h}) + 4π(${r})².`},{title:"Combine",body:`Coefficient = ${ratText(c)}.`},{title:"Answer",body:`${a}.`}],shortcut:"Capsule area = 2πr(h+2r).",traps:["Do not add cylinder end discs.","Two hemispheres contribute the area of one sphere."],verify:"external capsule surface identity"};}
    case "CP013-W1-DRILLED-CYLINDER-VOLUME":{const Rr=[5,6,7,8,9][v]!,r=[2,3,4,5,6][v]!,h=[10,12,14,16,18][v]!;const c=R((Rr*Rr-r*r)*h);const a=piText(c,"cm³");return{stem:`A cylindrical block of radius ${Rr} cm and height ${h} cm is drilled coaxially throughout with a cylindrical hole of radius ${r} cm. Find the volume of material left.`,answer:a,wrongs:[piText(R(Rr*Rr*h),"cm³"),piText(R(r*r*h),"cm³"),piText(R(Rr*r*h),"cm³")],keyRule:"Material left = outer solid volume − removed bore volume.",steps:[{title:"Find outer volume",body:`Outer = π(${Rr})²(${h}).`},{title:"Find removed volume",body:`Hole = π(${r})²(${h}).`},{title:"Subtract",body:`Material = π(${h})(${Rr}²−${r}²).`},{title:"Answer",body:`${a}.`}],shortcut:"Use πh(R²−r²) directly for a coaxially drilled cylinder.",traps:["Subtract volumes, not radii.","Do not use (R−r)² for annular area."],verify:"outer-minus-inner cylinder volume"};}
    case "CP013-W1-CUBE-MINUS-SPHERE-VOLUME":{const aSide=[6,8,10,12,14][v]!,r=aSide/2;const cube=R(aSide*aSide*aSide);const sphere=mul(R(4,3),R(Number(pow3(r))));const left=sub(cube,mul(sphere,R(22,7)));const ans=valText(left,"cm³");return{stem:`The largest possible sphere is carved from a cube of side ${aSide} cm. Using π = 22/7, find the volume of material remaining in the cube.`,answer:ans,wrongs:[valText(cube,"cm³"),valText(mul(sphere,R(22,7)),"cm³"),valText(sub(cube,sphere),"cm³")],keyRule:"Remaining material = cube volume − inscribed sphere volume.",steps:[{title:"Relate dimensions",body:`Largest sphere radius = ${aSide}/2 = ${r} cm.`},{title:"Compute both volumes",body:`Cube = ${aSide}³; sphere = (4/3)(22/7)(${r})³.`},{title:"Subtract",body:"Remove the carved spherical volume from the cube."},{title:"Answer",body:`${ans}.`}],shortcut:"For largest sphere in cube, r=a/2 before any volume work.",traps:["Do not subtract surface areas.","Use the actual declared π=22/7 consistently."],verify:"cube volume minus 22/7 sphere volume"};}
    case "CP013-W1-LARGEST-SPHERE-IN-CUBE":{const a=[6,8,10,12,14][v]!,r=a/2;const c=mul(R(4,3),R(Number(pow3(r))));const ans=piText(c,"cm³");return{stem:`Find the volume of the largest sphere that can be fitted inside a cube of edge ${a} cm.`,answer:ans,wrongs:[piText(R(Number(pow3(a))),"cm³"),piText(mul(R(4,3),R(Number(pow3(a)))),"cm³"),piText(R(Number(pow3(r))),"cm³")],keyRule:"For the largest sphere in a cube, sphere diameter = cube edge.",steps:[{title:"Use containment",body:`2r = ${a}, so r = ${r} cm.`},{title:"Use sphere volume",body:"V = 4πr³/3."},{title:"Substitute",body:`V = (4/3)π(${r})³.`},{title:"Answer",body:`${ans}.`}],shortcut:"Set r=a/2 immediately.",traps:["The cube edge is the sphere diameter, not radius.","Do not use cube volume as the sphere volume."],verify:"diameter-edge containment plus sphere volume"};}
    case "CP013-W1-LARGEST-CONE-IN-CUBE":{const a=[6,8,10,12,14][v]!,r=a/2,h=a;const c=R(r*r*h,3);const ans=piText(c,"cm³");return{stem:`A right circular cone of maximum size is placed inside a cube of edge ${a} cm with its base on one face and vertex at the centre of the opposite face. Find the cone's volume.`,answer:ans,wrongs:[piText(R(r*r*h),"cm³"),piText(R(a*a*a,3),"cm³"),piText(R(r*r*r,3),"cm³")],keyRule:"Largest axial cone in a cube has base diameter = edge and height = edge.",steps:[{title:"Use containment",body:`r = ${r} cm and h = ${h} cm.`},{title:"Use cone volume",body:"V = πr²h/3."},{title:"Substitute",body:`V = π(${r})²(${h})/3.`},{title:"Answer",body:`${ans}.`}],shortcut:"For this standard configuration, V = πa³/12.",traps:["Do not take cone radius equal to cube edge.","Do not omit the cone factor 1/3."],verify:"max cone cube relation r=a/2,h=a"};}
    case "CP013-W1-SPHERE-IN-CYLINDER-VACANT":{const r=[3,4,5,6,7][v]!,h=2*r;const cyl=R(r*r*h),sph=R(4*Number(pow3(r)),3);const vacant=sub(cyl,sph);const ans=piText(vacant,"cm³");return{stem:`A sphere of radius ${r} cm is exactly enclosed by a right circular cylinder whose radius equals the sphere radius and whose height equals the sphere diameter. Find the vacant space inside the cylinder.`,answer:ans,wrongs:[piText(cyl,"cm³"),piText(sph,"cm³"),piText(add(cyl,sph),"cm³")],keyRule:"Vacant space = containing cylinder volume − sphere volume.",steps:[{title:"Use containment dimensions",body:`Cylinder radius = ${r} cm, height = ${h} cm.`},{title:"Find both volumes",body:`Cylinder = ${ratText(cyl)}π; sphere = ${ratText(sph)}π.`},{title:"Subtract",body:`Vacant coefficient = ${ratText(vacant)}.`},{title:"Answer",body:`${ans}.`}],shortcut:"In the minimum enclosing cylinder, sphere:cylinder volume = 2:3, so vacant = 1/3 of cylinder.",traps:["Do not add the two volumes.","Vacant space is not a surface-area difference."],verify:"container volume minus contained sphere"};}
    case "CP013-W1-CUBOID-TANK-CAPACITY":{const l=[2,3,4,5,6][v]!,b=[1,2,2,3,4][v]!,h=[1,1,2,2,3][v]!;const litres=R(l*b*h*1000);const ans=valText(litres,"litres");return{stem:`A rectangular water tank has internal dimensions ${l} m × ${b} m × ${h} m. Find its capacity in litres.`,answer:ans,wrongs:[valText(R(l*b*h),"litres"),valText(R(l*b*h*100),"litres"),valText(R(l*b*h*1000000),"litres")],keyRule:"Capacity is internal volume; 1 m³ = 1000 litres.",steps:[{title:"Find tank volume",body:`V = ${l}×${b}×${h} = ${l*b*h} m³.`},{title:"Convert capacity",body:"Multiply cubic metres by 1000."},{title:"Compute",body:`${l*b*h}×1000 = ${l*b*h*1000}.`},{title:"Answer",body:`${ans}.`}],shortcut:"For metre dimensions, compute m³ first then append ×1000 litres.",traps:["Do not use a linear 100 conversion for volume.","Use internal, not external, dimensions for capacity."],verify:"cuboid volume and m3-to-litre conversion"};}
    case "CP013-W1-CYLINDER-TANK-CAPACITY":{const r=[0.7,1.4,2.1,2.8,3.5][v]!,h=[1,2,3,4,5][v]!;const litres=Math.round((22/7)*r*r*h*1000);const ans=`${litres} litres`;return{stem:`A cylindrical tank has internal radius ${r} m and height ${h} m. Using π = 22/7, find its capacity in litres.`,answer:ans,wrongs:[`${Math.round((22/7)*r*r*h)} litres`,`${Math.round(2*(22/7)*r*h*1000)} litres`,`${Math.round((22/7)*(2*r)*(2*r)*h*1000)} litres`],keyRule:"Cylinder capacity = πr²h, followed by cubic-metre to litre conversion.",steps:[{title:"Use internal volume",body:`V = (22/7)(${r})²(${h}) m³.`},{title:"Evaluate",body:`Volume = ${litres/1000} m³.`},{title:"Convert",body:"1 m³ = 1000 litres."},{title:"Answer",body:`${ans}.`}],shortcut:"Keep the litre ×1000 conversion until after cylinder volume is found.",traps:["Do not use curved surface area.","Do not treat diameter as radius."],verify:"declared 22/7 cylindrical capacity"};}
    case "CP013-W1-SPHERE-CYLINDER-LEVEL-RISE": case "CP013-W3-SSC-SPHERE-CAN-RISE":{const Rv=[6,8,10,12,15][v]!,r=[3,4,5,6,9][v]!;const rise=R(4*Number(pow3(r)),3*Rv*Rv);const ans=valText(rise,"cm");return{stem:`A cylindrical vessel of radius ${Rv} cm is partly filled with water. A solid sphere of radius ${r} cm is completely immersed. Find the rise in water level.`,answer:ans,wrongs:[valText(R(Number(pow3(r)),Rv*Rv),"cm"),valText(R(4*r*r,3*Rv),"cm"),valText(R(4*Number(pow3(r)),3*2*Rv*2*Rv),"cm")],keyRule:"For complete immersion, displaced volume = object volume = tank base area × level rise.",steps:[{title:"Find displaced volume",body:`Sphere volume = (4/3)π(${r})³.`},{title:"Use vessel base area",body:`Rise volume = π(${Rv})²x.`},{title:"Equate and cancel π",body:`x = 4(${r})³/[3(${Rv})²].`},{title:"Answer",body:`${ans}.`}],shortcut:"For sphere in cylinder, rise = 4r³/(3R²).",traps:["Use vessel base area, not vessel volume.","The displaced volume is the immersed sphere volume."],verify:"sphere displacement equals cylindrical rise prism"};}
    case "CP013-W1-CUBE-CUBOID-LEVEL-RISE": case "CP013-W3-SSC-CUBE-TANK-RISE":{const s=[4,6,8,10,12][v]!,l=[8,12,16,20,24][v]!,b=[4,6,8,10,12][v]!;const rise=R(Number(pow3(s)),l*b);const ans=valText(rise,"cm");return{stem:`A solid cube of side ${s} cm is completely submerged in a rectangular tank whose base is ${l} cm × ${b} cm. Find the rise in water level.`,answer:ans,wrongs:[valText(R(s*s,l*b),"cm"),valText(R(Number(pow3(s)),l*b*2),"cm"),valText(R(Number(pow3(s)),l+b),"cm")],keyRule:"Object volume = rectangular tank base area × rise.",steps:[{title:"Cube volume",body:`${s}³ = ${s*s*s} cm³.`},{title:"Tank base area",body:`${l}×${b} = ${l*b} cm².`},{title:"Divide",body:`Rise = ${s*s*s}/${l*b}.`},{title:"Answer",body:`${ans}.`}],shortcut:"Rise = immersed volume ÷ tank base area.",traps:["Do not divide by tank perimeter.","Use cube volume s³, not face area s²."],verify:"cube volume divided by rectangular base area"};}
    case "CP013-W1-MULTI-SPHERE-LEVEL-RISE": case "CP013-W3-SSC-MULTI-STONE-RISE":{const n=[2,3,4,5,6][v]!,r=[3,4,5,6,7][v]!,l=[24,30,40,50,60][v]!,b=[12,15,20,25,30][v]!;const rise=R(n*4*Number(pow3(r)),3*l*b);const ans=piText(rise,"cm").replace("π cm","π cm");return{stem:`${n} identical solid spherical stones of radius ${r} cm are completely submerged in a rectangular tank with base ${l} cm × ${b} cm. Find the rise in water level.`,answer:ans,wrongs:[piText(R(4*Number(pow3(r)),3*l*b),"cm"),piText(R(n*Number(pow3(r)),l*b),"cm"),piText(R(n*4*r*r,3*l*b),"cm")],keyRule:"Total displaced volume is the sum of the volumes of all fully immersed objects.",steps:[{title:"One sphere",body:`Volume = (4/3)π(${r})³.`},{title:"All spheres",body:`Multiply by ${n}.`},{title:"Divide by tank base area",body:`Rise = total displaced volume / (${l}×${b}).`},{title:"Answer",body:`${ans}.`}],shortcut:"For n equal spheres in a rectangular tank, rise = 4nπr³/(3LB).",traps:["Do not forget the number of spheres.","Do not multiply the tank base area by π."],verify:"sum of sphere volumes over rectangular base area"};}
    case "CP013-W1-PARTIAL-FILL-FINAL-LEVEL":{const l=[20,25,30,40,50][v]!,b=[10,12,15,20,25][v]!,initial=[4,5,6,7,8][v]!,added=[2,3,4,5,6][v]!;const volume=l*b*added;const final=initial+added;const ans=`${final} cm`;return{stem:`A rectangular tank of base ${l} cm × ${b} cm contains water to a depth of ${initial} cm. If ${volume} cm³ of water is added, what is the new water depth?`,answer:ans,wrongs:[`${added} cm`,`${initial+volume/(l+b)} cm`,`${initial+volume/(2*l*b)} cm`],keyRule:"Added volume changes level by volume/base area; then add the initial depth.",steps:[{title:"Base area",body:`A = ${l}×${b} = ${l*b} cm².`},{title:"Find rise",body:`Rise = ${volume}/${l*b} = ${added} cm.`},{title:"Add initial depth",body:`New depth = ${initial}+${added}.`},{title:"Answer",body:`${ans}.`}],shortcut:"New depth = initial depth + added volume/base area.",traps:["Do not report only the rise when final level is asked.","Do not divide by perimeter."],verify:"initial level plus added-volume/base-area rise"};}
    case "CP013-W2-INVERSE-SPHERE-COUNT":{const r=[2,3,4,5,6][v]!,Rr=[8,9,12,15,18][v]!,n=[3,4,5,6,8][v]!;const rise=R(n*4*Number(pow3(r)),3*Rr*Rr);const ans=`${n} spheres`;return{stem:`A cylindrical vessel of radius ${Rr} cm shows a water-level rise of ${ratText(rise)} cm when identical solid spheres of radius ${r} cm are completely immersed. How many spheres were immersed?`,answer:ans,wrongs:[`${Math.max(1,Math.floor(n/2))} spheres`,`${n*2} spheres`,`${n*3} spheres`],keyRule:"Number = total displaced volume ÷ volume of one immersed object.",steps:[{title:"Translate level rise",body:`Displaced volume = π(${Rr})² × ${ratText(rise)}; this must equal the combined sphere volume.`},{title:"One sphere volume",body:`(4/3)π(${r})³.`},{title:"Form count",body:"Divide total displacement by one sphere volume and cancel common π."},{title:"Answer",body:`${n} spheres.`}],shortcut:"Use n = 3R²h/(4r³) after cancelling π; the stem's rise coefficient is constructed for an integer n.",traps:["Count must be a whole number.","Do not multiply by one-sphere volume when solving for count."],verify:"inverse of multi-sphere displacement identity"};}
    case "CP013-W2-INVERSE-CUBE-SIDE":{const s=[4,6,8,10,12][v]!,l=[16,18,20,25,30][v]!,b=[8,12,16,20,24][v]!;const rise=R(Number(pow3(s)),l*b);const ans=`${s} cm`;return{stem:`A cube is completely submerged in a rectangular tank of base ${l} cm × ${b} cm, raising the water level by ${ratText(rise)} cm. Find the cube's side.`,answer:ans,wrongs:[`${s*s} cm`,`${Math.max(1,s/2)} cm`,`${s*2} cm`],keyRule:"First recover displaced volume, then take the cube root for the cube side.",steps:[{title:"Displaced volume",body:`V = ${l}×${b}×${ratText(rise)} cm³.`},{title:"Set equal to cube volume",body:"s³ = displaced volume."},{title:"Cube-root",body:`The constructed volume is ${s}³.`},{title:"Answer",body:`${ans}.`}],shortcut:"s = ∛(LBh).",traps:["Do not stop at s³.","The inverse requires a cube root, not a square root."],verify:"reconstruct cube volume from tank rise then cube-root"};}
    case "CP013-W2-INVERSE-TANK-BASE-AREA":{const V=[240,360,480,600,720][v]!,rise=[2,3,4,5,6][v]!,area=V/rise;const ans=`${area} cm²`;return{stem:`A completely immersed solid displaces ${V} cm³ of water and the water level rises by ${rise} cm in a vertical-sided tank. Find the tank's base area.`,answer:ans,wrongs:[`${V*rise} cm²`,`${area*3} cm²`,`${area*2} cm²`],keyRule:"Displaced volume = base area × level change.",steps:[{title:"Use displacement prism",body:"V = A×h."},{title:"Rearrange",body:"A = V/h."},{title:"Substitute",body:`A = ${V}/${rise} = ${area}.`},{title:"Answer",body:`${ans}.`}],shortcut:"Base area = displaced volume ÷ rise.",traps:["Do not multiply volume by rise.","Area unit must be squared."],verify:"inverse level-change prism identity"};}
    case "CP013-W2-DRAW-OFF-LEVEL-DROP":{const r=[7,14,21,28,35][v]!,litres=[3.08,12.32,27.72,49.28,77][v]!,V=Math.round(litres*1000);const drop=R(V*7,22*r*r);const ans=valText(drop,"cm");return{stem:`A cylindrical tank of radius ${r} cm contains water. If ${litres} litres of water are drawn off, by how much does the water level fall? Use π = 22/7.`,answer:ans,wrongs:[valText(R(V,r*r),"cm"),valText(R(V*22,7*r*r),"cm"),valText(R(V*7,44*r*r),"cm")],keyRule:"Static level fall = removed volume ÷ tank base area.",steps:[{title:"Convert removed water",body:`${litres} L = ${V} cm³.`},{title:"Base area",body:`A = (22/7)(${r})².`},{title:"Divide",body:"Fall = removed volume/base area."},{title:"Answer",body:`${ans}.`}],shortcut:"This is a static volume-height question, not a flow-rate problem.",traps:["Convert litres to cm³ before dividing.","Use tank base area, not curved surface area."],verify:"removed volume over circular base area"};}
    case "CP013-W2-IMMERSION-OVERFLOW":{const tankL=[20,25,30,40,50][v]!,tankB=[10,12,15,20,25][v]!,head=[1,2,3,4,5][v]!,cube=[8,10,12,16,20][v]!;const displaced=Number(pow3(cube));const spare=tankL*tankB*head;const overflow=Math.max(0,displaced-spare);const ans=`${overflow} cm³`;return{stem:`A rectangular tank of base ${tankL} cm × ${tankB} cm is filled to ${head} cm below the brim. A solid cube of side ${cube} cm is completely immersed. How much water overflows?`,answer:ans,wrongs:[`${displaced} cm³`,`${spare} cm³`,`${displaced+spare} cm³`],keyRule:"Overflow = displaced volume − unused capacity above the initial water level, if positive.",steps:[{title:"Object displacement",body:`Cube displaces ${cube}³ = ${displaced} cm³.`},{title:"Unused capacity",body:`Headroom = ${tankL}×${tankB}×${head} = ${spare} cm³.`},{title:"Compare",body:"Only displacement beyond the headroom overflows."},{title:"Answer",body:`${ans}.`}],shortcut:"Overflow = max(0, Vobject − base area×headroom).",traps:["Do not call the whole displaced volume overflow.","Headroom must be converted to a volume before subtraction."],verify:"displacement minus pre-existing free capacity"};}
    case "CP013-W2-PARTIAL-FILL-OVERFLOW":{const l=[20,25,30,40,50][v]!,b=[10,12,15,20,25][v]!,H=[10,12,15,20,25][v]!,initial=H-[2,3,4,5,6][v]!;const capacity=l*b*(H-initial);const added=capacity*3;const overflow=added-capacity;const ans=`${overflow} cm³`;return{stem:`A rectangular tank of base ${l} cm × ${b} cm and height ${H} cm contains water to depth ${initial} cm. If ${added} cm³ more water is poured in, how much overflows?`,answer:ans,wrongs:[`${added} cm³`,`${capacity} cm³`,`${added+capacity} cm³`],keyRule:"Overflow occurs only after the unused tank capacity is filled.",steps:[{title:"Find headroom",body:`Unused height = ${H-initial} cm.`},{title:"Unused capacity",body:`${l}×${b}×${H-initial} = ${capacity} cm³.`},{title:"Subtract from addition",body:"Overflow = added volume − unused capacity, if positive."},{title:"Answer",body:`${ans}.`}],shortcut:"Overflow = max(0, added volume − base area×headroom).",traps:["Do not subtract initial water volume from added volume.","If added volume is below headroom capacity, overflow is zero."],verify:"added volume versus remaining tank capacity"};}
    case "CP013-W2-BORED-CUBOID-VOLUME":{const l=[20,24,28,32,36][v]!,b=[10,12,14,16,18][v]!,h=[8,10,12,14,16][v]!,r=[2,3,4,5,6][v]!;const cub=R(l*b*h);const bore=mul(R(22,7),R(r*r*h));const left=sub(cub,bore);const ans=valText(left,"cm³");return{stem:`A cuboid ${l} cm × ${b} cm × ${h} cm has a cylindrical hole of radius ${r} cm bored through its full height ${h} cm. Using π = 22/7, find the material left.`,answer:ans,wrongs:[valText(cub,"cm³"),valText(bore,"cm³"),valText(add(cub,bore),"cm³")],keyRule:"Subtract the bored cylinder volume from the cuboid volume.",steps:[{title:"Cuboid volume",body:`${l}×${b}×${h}.`},{title:"Bore volume",body:`(22/7)×${r}²×${h}.`},{title:"Subtract",body:"Material left = cuboid − bore."},{title:"Answer",body:`${ans}.`}],shortcut:"Keep both volumes in cm³ before subtracting.",traps:["Do not subtract cross-sectional areas without multiplying by bore length.","The bore is removed, so its volume must be subtracted."],verify:"cuboid minus full-height cylindrical bore"};}
    case "CP013-W2-LARGEST-CUBE-IN-SPHERE":{const a=[4,6,8,10,12][v]!,diam=`${a}√3 cm`;return{stem:`A cube of edge ${a} cm is inscribed in a sphere. Find the sphere's diameter.`,answer:diam,wrongs:[`${a} cm`,`${a*3} cm`,`2${a}√3 cm`],keyRule:"For a cube inscribed in a sphere, cube body diagonal = sphere diameter.",steps:[{title:"Use cube diagonal",body:"Body diagonal = a√3."},{title:"Match containment",body:"The sphere's diameter spans opposite cube vertices."},{title:"Substitute",body:`Diameter = ${a}√3 cm.`},{title:"Answer",body:diam}],shortcut:"Remember 2R = a√3.",traps:["Do not use face diagonal a√2.","The cube edge itself is not the sphere diameter in this inverse containment."],verify:"cube body diagonal equals circumsphere diameter"};}
    case "CP013-W2-CONE-IN-CYLINDER-RATIO":{const rr=[3,4,5,6,7][v]!,hh=[8,10,12,14,16][v]!,ans="1:3";return{stem:`A right circular cone of radius ${rr} cm and height ${hh} cm is inscribed in a cylinder with the same base radius and height. Find the ratio of the cone's volume to the cylinder's volume.`,answer:ans,wrongs:["1:2","2:3","3:1"],keyRule:"Same r and h: cone volume is one-third of cylinder volume.",steps:[{title:"Cylinder",body:"Vcyl = πr²h."},{title:"Cone",body:"Vcone = πr²h/3."},{title:"Form ratio",body:"Common πr²h cancels."},{title:"Answer",body:"1:3."}],shortcut:"Same base and height ⇒ cone:cylinder = 1:3.",traps:["Do not use surface-area ratios.","The factor 1/3 belongs to cone volume."],verify:"shared-base-height cone cylinder volume ratio"};}
    case "CP013-W2-COMPOSITE-TOTAL-HEIGHT": case "CP013-W3-SSC-CYL-HEMI-TOY-VOLUME":{const r=[3,4,5,6,7][v]!,total=[10,12,14,15,18][v]!,h=total-r;const c=add(R(r*r*h),R(2*Number(pow3(r)),3));const ans=piText(c,"cm³");return{stem:`A toy is a cylinder surmounted by a hemisphere of radius ${r} cm. The total height of the toy is ${total} cm. Find its volume.`,answer:ans,wrongs:[piText(add(R(r*r*total),R(2*Number(pow3(r)),3)),"cm³"),piText(R(r*r*h),"cm³"),piText(add(R(r*r*h),R(4*Number(pow3(r)),3)),"cm³")],keyRule:"Derive cylinder height from total height before adding component volumes.",steps:[{title:"Recover cylinder height",body:`Cylinder height = ${total}−${r} = ${h} cm.`},{title:"Cylinder volume",body:`π(${r})²(${h}).`},{title:"Hemisphere volume",body:`(2/3)π(${r})³.`},{title:"Add",body:`${ans}.`}],shortcut:"For cylinder+hemisphere total height H, cylinder height = H−r.",traps:["Do not use total toy height as cylinder height.","Use hemisphere, not full-sphere, volume."],verify:"derived component height plus composite volume"};}
    case "CP013-W3-SSC-SPHERE-IN-CUBE-TSA": case "CP013-W1-LARGEST-SPHERE-IN-CUBE-SECONDARY":{const a=[6,8,10,12,14][v]!,r=a/2;const ans=piText(R(4*r*r),"cm²");return{stem:`A sphere is inscribed in a cube of edge ${a} cm. Find the total surface area of the sphere.`,answer:ans,wrongs:[piText(R(4*a*a),"cm²"),piText(R(r*r),"cm²"),piText(R(6*a*a),"cm²")],keyRule:"Containment gives the sphere radius first; the requested measure is then computed separately.",steps:[{title:"Containment relation",body:`Sphere diameter = cube edge ${a} cm, so r=${r} cm.`},{title:"Use sphere TSA",body:"Area = 4πr²."},{title:"Substitute",body:`4π(${r})².`},{title:"Answer",body:`${ans}.`}],shortcut:"For sphere in cube, TSA = πa².",traps:["Do not use sphere volume.","The cube edge is the sphere diameter."],verify:"inscribed radius then secondary surface measure"};}
    case "CP013-W3-SSC-LARGEST-SPHERE-CUBE": return baseDraft("CP013-W1-LARGEST-SPHERE-IN-CUBE",seed);
    case "CP013-W3-SSC-LARGEST-CONE-CUBE": return baseDraft("CP013-W1-LARGEST-CONE-IN-CUBE",seed);
    case "CP013-W3-SSC-CONE-HEMI-SURFACE": return baseDraft("CP013-W1-CONE-HEMISPHERE-SURFACE",seed);
    default: throw new Error(`No CP013 builder for ${id}`);
  }
}

function sourcePolish(id:string,d:Draft):Draft{
  if(id==="CP013-W3-SSC-CUBE-TANK-RISE")return{...d,stem:d.stem.replace("A solid cube","A metal cube")};
  if(id==="CP013-W3-SSC-SPHERE-CAN-RISE")return{...d,stem:d.stem.replace("A cylindrical vessel","A cylindrical can")};
  if(id==="CP013-W3-SSC-MULTI-STONE-RISE")return{...d,stem:d.stem.replace("identical solid spherical stones","identical metal balls")};
  if(id==="CP013-W3-SSC-LARGEST-SPHERE-CUBE")return{...d,stem:d.stem.replace("Find the volume of the largest sphere that can be fitted inside a cube","A solid cube is carved to form the largest possible sphere. Find the volume of that sphere when the cube has edge") .replace(/edge (\d+) cm cm/,"edge $1 cm")};
  if(id==="CP013-W3-SSC-LARGEST-CONE-CUBE")return{...d,stem:d.stem.replace("A right circular cone of maximum size is placed inside a cube","The largest right circular cone is fitted inside a cube")};
  if(id==="CP013-W3-SSC-CONE-HEMI-SURFACE")return{...d,stem:d.stem.replace("A closed solid toy","A decorative solid toy")};
  return d;
}
export function generateMenCp013Question(id:string,seed:string){const def=defs.find(d=>d.id===id);if(!def)throw new Error(`Unknown CP013 candidate ${id}`);return finalize(def,seed,sourcePolish(id,baseDraft(id,seed)));}

export function auditMenCp013Definitions(){return{
  authority:MEN_CP_013_DISCOVERY_AUTHORITY,
  total:defs.length,
  wave01:MEN_CP_013_WAVE01_DEFINITIONS.length,
  wave02:MEN_CP_013_WAVE02_DEFINITIONS.length,
  wave03:MEN_CP_013_WAVE03_DEFINITIONS.length,
  sourceBacked:defs.filter(d=>d.sourceBacked).length,
  permanentQlCount:0,
  productLocked:true,
};}
