import type{Eng008Cp004PassageV1}from"./eng-008-cp004-authorities-v1";
const q=(id:string,familyId:any,difficulty:any,question:string,correctAnswer:string,distractors:readonly[string,string,string],explanation:string,evidence:string)=>({id,familyId,difficulty,question,correctAnswer,distractors,explanation,evidence});
export const ENG008_CP004_EXPANSION_WAVE7_V1:readonly Eng008Cp004PassageV1[]=[
{
 id:"ENG008-BM-E06",title:"Why GDP per Person Does Not Fully Describe Household Welfare",genre:"economy",
 text:`GDP per person is often used to compare economic performance across countries or over time. It is useful because it relates total economic output to population size, but it is not the same thing as the income or living standard of a typical household.

Part of GDP can come from profits that flow to a small group, government activity or sectors whose gains do not reach households evenly. A rise in GDP per person can therefore coexist with weak growth in median household income.

Prices also matter. If housing, transport or healthcare costs rise quickly, households may feel more financial pressure even when nominal income and GDP increase.

Non-market activity is another limitation. Caring for children at home, unpaid community work and many household tasks create value without being fully counted in GDP.

The measure also says little about distribution. Two economies with similar GDP per person can differ greatly in how income is shared, how secure employment is and how accessible essential services are.

None of this makes GDP useless. It remains important for understanding productive capacity, tax bases and broad economic trends. The better approach is to treat GDP per person as one indicator among several. Median income, employment quality, household consumption, inequality, public services and cost-of-living measures can add context. A country can become richer in aggregate without every household becoming better off at the same pace. Economic welfare is therefore best understood by asking not only how much an economy produces, but also how gains reach people and what those gains can actually buy.

Household balance sheets can widen the gap between output and lived welfare further. Two households with the same income may face very different conditions if one has savings, manageable debt and secure housing while the other spends a large share of income on rent and loan repayments. GDP per person does not describe those differences. Analysts therefore sometimes pair income measures with wealth, housing cost and debt-service data. These indicators do not replace GDP, but they help explain why households can experience the same macroeconomic expansion very differently.

Time horizon also matters. A country may invest heavily in infrastructure, education or machinery, raising current output and future productive capacity without producing an immediate rise in household consumption. Conversely, a temporary consumption boom can raise measured activity without improving long-run resilience. Welfare analysis should therefore distinguish current living standards from investment that may create benefits later. The most useful reading of GDP is not as a final score of wellbeing, but as one important part of a broader account of how resources are produced, distributed and used. That broader account is especially important when headline growth and household experience move in different directions for several years.`,
 questions:[
 q("E06-Q1","BM-F01","medium","Why can GDP per person rise while median household income grows slowly?","Economic gains may not be distributed evenly across households",["GDP excludes all business profits","Population must be falling","Prices always decline"],"The passage explains that output gains can be concentrated.","do not reach households evenly"),
 q("E06-Q2","BM-F02","hard","What can be inferred if essential living costs rise faster than household income?","Households may feel worse off even while headline GDP rises",["GDP must fall","Public services disappear","Unpaid work becomes counted"],"The passage separates aggregate output from purchasing pressure.","households may feel more financial pressure"),
 q("E06-Q3","BM-F03","hard","Which option best states the central argument?","GDP per person is useful but should be interpreted with distribution, income and cost-of-living measures",["GDP should never be used","Median income alone is sufficient","Unpaid work is the only welfare measure"],"The passage consistently treats GDP as one indicator among several.","one indicator among several"),
 q("E06-Q4","BM-F04","hard","What is the author's tone?","Analytical and balanced",["Hostile toward GDP","Celebratory","Sarcastic"],"The author explains both usefulness and limitations.","None of this makes GDP useless"),
 q("E06-Q5","BM-F05","medium","Why does the author mention unpaid care and community work?","To show that some valuable activity is not fully captured by GDP",["To argue all unpaid work should be taxed","To explain inflation","To compare exports"],"These activities create value outside market measurement.","create value without being fully counted"),
 q("E06-Q6","BM-F06","hard","Which statement cannot be inferred?","A higher GDP per person guarantees that the typical household is better off",["Distribution affects welfare","Prices affect purchasing power","Public services add context"],"The passage explicitly rejects this guarantee.","not the same thing as ... typical household"),
 q("E06-Q7","BM-F07","hard","What role does the seventh paragraph play?","It lists complementary indicators that can improve interpretation",["It defines GDP","It rejects all averages","It introduces population"],"The paragraph names median income, consumption and other measures.","can add context"),
 q("E06-Q8","BM-F08","hard","Which conclusion follows most logically?","Economic welfare should be judged using several measures rather than output alone",["GDP should be ignored in policy","Only inequality matters","Prices never matter"],"The conclusion explicitly broadens evaluation beyond output.","not only how much an economy produces"),
 q("E06-Q9","BM-F09","medium","In context, “aggregate” most nearly means:","combined across the economy as a whole",["individual household","temporary","unpaid"],"The passage contrasts economy-wide gains with household experience.","richer in aggregate"),
 q("E06-Q10","BM-F10","hard","Which assumption does the passage challenge?","That average economic output per person is identical to typical household welfare",["Production can rise","Prices can change","Income can be distributed unevenly"],"This is the central distinction.","not the same thing as")
 ]
},
{
 id:"ENG008-BM-B05",title:"When Dynamic Pricing Improves Efficiency but Feels Unfair",genre:"business",
 text:`Dynamic pricing changes prices in response to demand, supply or timing. Airlines and hotels have used versions of it for years, and digital systems now allow many other businesses to adjust prices rapidly.

From an operational perspective, variable pricing can improve efficiency. Higher prices during scarce periods may reduce demand or encourage suppliers to add capacity, while lower prices during quiet periods can attract customers who are flexible.

The same system can nevertheless feel unfair. Two customers may pay different amounts for the same service simply because they booked at different times or because demand changed between transactions.

Transparency therefore matters. Customers are more likely to understand variable prices when the rules are visible and when sudden increases are not disguised as arbitrary fees.

There are also limits to what customers can reasonably avoid. A person choosing a leisure trip may be able to wait for a cheaper time; someone seeking emergency transport has much less flexibility.

This distinction raises an ethical design question. A pricing rule that works well in optional markets may be harder to justify for essential or urgent services. Businesses also need to consider trust. A short-term revenue gain can be offset if customers believe prices are being personalised in opaque ways or targeted at people with fewer alternatives. Regulation and company policy can set boundaries, such as maximum surge levels or exemptions during emergencies. The broader lesson is that dynamic pricing is not simply a technical optimisation problem. Its acceptability depends on transparency, consumer choice, necessity and whether the rule is applied in a way people can understand and anticipate.

Data can also make dynamic pricing appear more precise than it really is. A system may predict demand from past behaviour, weather, location or event schedules, but forecasts can fail when conditions change suddenly. If customers see prices jump because of a noisy prediction rather than genuine scarcity, trust may fall even when the algorithm follows its rules consistently. Companies therefore need monitoring that compares price changes with actual capacity pressure and checks whether unusual spikes were justified by real conditions.

Fairness concerns become sharper when personal data influences price. Charging different amounts because demand differs by time is easier to explain than charging different customers differently because the system predicts one person will tolerate a higher price. Even when such personalisation is legal, the practice can feel exploitative if users cannot understand or challenge it. A defensible pricing design should therefore separate demand management from opaque willingness-to-pay targeting, and give customers enough information to anticipate how timing or service conditions affect the price they see. Clear appeal or refund rules can also matter when unusual price spikes occur because of system error rather than genuine scarcity.`,
 questions:[
 q("B05-Q1","BM-F01","medium","How can higher prices during scarce periods affect demand?","They may reduce demand or encourage more supply",["They always increase demand","They eliminate capacity","They make pricing fixed"],"The second paragraph states these possible effects.","reduce demand or encourage suppliers"),
 q("B05-Q2","BM-F02","hard","Why might the same dynamic-pricing rule feel different in emergency transport than in leisure travel?","Customers have much less ability to wait or choose an alternative",["Emergency transport has no costs","Leisure travel never uses prices","Demand is always identical"],"The passage contrasts flexible and urgent choices.","much less flexibility"),
 q("B05-Q3","BM-F03","hard","Which option best states the central argument?","Dynamic pricing can improve efficiency, but fairness depends on transparency, choice and context",["Dynamic pricing is always unfair","Fixed prices are always efficient","Customers should never compare prices"],"The passage balances operational benefits with fairness concerns.","not simply a technical optimisation problem"),
 q("B05-Q4","BM-F04","hard","What is the author's tone?","Balanced and analytical",["Promotional","Hostile","Sarcastic"],"Both benefits and concerns are considered.","can improve efficiency ... can nevertheless feel unfair"),
 q("B05-Q5","BM-F05","medium","Why does the author discuss transparency?","Visible rules can make price differences easier for customers to understand",["Transparency makes prices identical","It removes demand changes","It prevents all complaints"],"The passage links visible rules to comprehensibility.","rules are visible"),
 q("B05-Q6","BM-F06","hard","Which statement cannot be inferred?","Dynamic pricing is equally acceptable in every type of service",["Trust matters","Urgency affects choice","Price caps can set boundaries"],"The passage explicitly says context changes acceptability.","harder to justify for essential or urgent services"),
 q("B05-Q7","BM-F07","hard","What role does the fifth and sixth paragraphs play?","They introduce limits to consumer choice and explain why necessity changes the fairness question",["They define hotels","They argue for no regulation","They explain supply curves only"],"Those paragraphs contrast leisure flexibility with urgent need.","much less flexibility"),
 q("B05-Q8","BM-F08","hard","Which conclusion follows most logically?","Pricing systems should consider how much real choice customers have when demand is high",["All surge pricing should be banned","Only revenue matters","Emergency demand should be ignored"],"The passage treats consumer flexibility as central to fairness.","consumer choice, necessity"),
 q("B05-Q9","BM-F09","medium","In context, “opaque” most nearly means:","difficult to understand or see through",["cheap","temporary","regulated"],"Opaque pricing rules make customers unsure how prices were set.","opaque ways"),
 q("B05-Q10","BM-F10","hard","Which assumption does the passage challenge?","That an efficient pricing rule is automatically a fair one",["Demand can change","Prices can vary","Suppliers respond to incentives"],"The core passage separates efficiency from acceptability.","not simply a technical optimisation problem")
 ]
},
{
 id:"ENG008-BM-T04",title:"Why a Useful Ranking Is Not the Same as a Neutral Ranking",genre:"technology",
 text:`Digital platforms rank search results, products, videos and other content so users do not have to examine everything at once. Ranking is useful precisely because attention is limited.

But every ranking reflects choices. A system may prioritise freshness, popularity, relevance, price, predicted engagement or some combination of these. Different objectives can produce different orderings from the same underlying set.

This means a ranking is not neutral simply because an algorithm produced it. The design decides which signals matter and how much weight they receive.

Personalisation adds another layer. Two users may see different rankings because the system predicts different preferences. This can improve relevance but also makes it harder to know whether everyone is seeing the same options.

Evaluation therefore needs a clear objective. A shopping search optimised only for clicks may perform differently from one designed to help users find suitable products quickly with low return rates.

Feedback loops can also develop. Items placed near the top receive more attention, which can make them appear more popular and justify keeping them near the top. Platforms can reduce this effect by testing alternatives, reserving some exposure for new items and measuring outcomes beyond immediate clicks. Transparency does not require revealing every line of code. It can mean explaining the main factors that affect ranking and giving users controls to sort or filter differently. The broader lesson is that ranking systems organise attention according to chosen goals. Their quality should be judged by whether those goals serve the user task, not by assuming the order is automatically objective.

Ranking quality can also change over time because user behaviour adapts to what is shown. Sellers may rewrite titles to match ranking signals, publishers may choose topics that attract clicks and creators may imitate formats that the system already rewards. The algorithm then observes behaviour partly produced by its own incentives. This makes evaluation harder because the data is no longer independent of the ranking policy. Periodic experiments with different objectives can help reveal whether the system is learning genuine user preference or merely reinforcing patterns it previously created.

There is also a difference between relevance and diversity. A highly personalised system may become very good at predicting the next item a user is likely to click while repeatedly showing similar material. For some tasks that is useful; for others it can reduce discovery. Platforms can therefore include exploration signals, category diversity or user controls without abandoning personalisation. The right balance depends on the task. A search engine answering a specific query may prioritise precision, while a discovery feed may need broader exposure to avoid becoming narrow and repetitive.`,
 questions:[
 q("T04-Q1","BM-F01","medium","Why are ranking systems useful?","They help users focus attention on a smaller ordered set",["They remove all choices","They make every result identical","They eliminate relevance"],"The opening paragraph says ranking helps when attention is limited.","attention is limited"),
 q("T04-Q2","BM-F02","hard","What can be inferred from different ranking objectives?","The same items can appear in different orders depending on what the system optimises",["All algorithms produce one neutral order","Popularity and relevance are identical","Users always see the same list"],"The passage explicitly says different objectives produce different orderings.","Different objectives can produce different orderings"),
 q("T04-Q3","BM-F03","hard","Which option best states the central argument?","Algorithmic rankings reflect design goals and should be evaluated against the task they are meant to serve",["Algorithms are always biased in the same way","Rankings should be removed","Popularity is the only useful signal"],"The conclusion emphasises chosen goals and user tasks.","organise attention according to chosen goals"),
 q("T04-Q4","BM-F04","hard","What is the author's tone?","Analytical and qualified",["Anti-technology","Promotional","Humorous"],"The author explains usefulness while rejecting automatic neutrality.","Ranking is useful ... not neutral"),
 q("T04-Q5","BM-F05","medium","Why does the author mention low return rates in shopping search?","To show that clicks may not be the best measure of successful ranking",["To discuss shipping costs","To argue users dislike search","To compare product prices"],"A broader objective may better reflect a useful purchase outcome.","beyond immediate clicks"),
 q("T04-Q6","BM-F06","hard","Which statement cannot be inferred?","An algorithmic ranking is neutral because no human manually ordered the items",["Personalisation can create different rankings","Top placement can reinforce popularity","Users can benefit from sorting controls"],"The passage explicitly rejects automatic neutrality.","not neutral simply because an algorithm produced it"),
 q("T04-Q7","BM-F07","hard","What role does the sixth paragraph play?","It explains how ranking position can influence the signals later used to justify that position",["It defines personalisation","It argues clicks are useless","It introduces search"],"The paragraph describes a feedback loop.","Items placed near the top receive more attention"),
 q("T04-Q8","BM-F08","hard","Which conclusion follows most logically?","Ranking systems should be tested using outcomes that match their intended purpose",["Every ranking should maximise clicks","All users should see identical results","New items should always rank first"],"The passage says evaluation needs a clear objective.","clear objective"),
 q("T04-Q9","BM-F09","medium","In context, “neutral” most nearly means:","not shaped by particular priorities or preferences",["fast","personalised","popular"],"The passage contrasts neutrality with chosen weighting of signals.","not neutral"),
 q("T04-Q10","BM-F10","hard","Which assumption does the passage challenge?","That algorithmic ordering is automatically objective",["Users have limited attention","Platforms can test alternatives","Different signals exist"],"This is the central misconception addressed.","assuming the order is automatically objective")
 ]
},
{
 id:"ENG008-BM-SP03",title:"Why Benefit Cut-offs Can Create Sharp Incentives",genre:"social-policy",
 text:`Many public benefits use income cut-offs to decide eligibility. A clear threshold is easy to administer, but it can create a sharp difference between people whose circumstances are nearly identical.

If a benefit ends completely when income crosses one line, a small pay increase can sometimes produce a larger loss in support. This is known as a cliff effect.

Such cliffs can discourage additional work or create anxiety about accepting overtime when households are unsure how much support they may lose.

One solution is gradual withdrawal. Instead of ending immediately, the benefit decreases as income rises. This reduces the size of the sudden change but makes the calculation more complex.

Complexity has its own cost. If people cannot predict how earnings affect benefits, they may still avoid changes because the system feels uncertain.

Administrative data can help smooth transitions, but income can vary from month to month, especially for workers with irregular hours. Policy design therefore has to balance simplicity, targeting and incentives. A single threshold is easy to explain, while a taper can better reflect gradual changes in ability to pay. The broader lesson is that eligibility rules do more than divide people into categories. They can change behaviour around the boundary. Good design asks not only who qualifies today, but also what happens when someone's circumstances improve slightly and whether the transition supports rather than penalises that improvement.

Cliff effects can interact with several programmes at once. A household may face changes in food support, housing assistance and healthcare contributions around similar income levels. Even if each programme uses a modest threshold, the combined loss can create a much steeper effective penalty. Analysts therefore examine the total marginal effect of earning more, not only the rule inside one benefit. Coordination across programmes can reveal situations where separate policies unintentionally stack on top of each other.

Administrative timing matters as well. If eligibility is based on last month's income, a worker with irregular earnings may move in and out of support even though annual income changes little. Frequent recalculation can improve accuracy but create instability, while longer averaging periods are smoother but respond more slowly to genuine need. Policy design therefore involves a trade-off between precision and predictability. A system can be mathematically well targeted yet still be difficult for households to plan around if support changes too often or with little warning.`,
 questions:[
 q("SP03-Q1","BM-F01","medium","What is a cliff effect?","A sharp loss of benefits after crossing an eligibility threshold",["A gradual increase in benefits","A tax refund","A change in work location"],"The passage defines it directly.","benefit ends completely when income crosses one line"),
 q("SP03-Q2","BM-F02","hard","Why might workers avoid overtime near a benefit threshold?","A small earnings increase could trigger a larger loss of support",["Overtime always lowers wages","Benefits increase with overtime","Thresholds guarantee higher income"],"The passage links cliffs with anxiety about added work.","larger loss in support"),
 q("SP03-Q3","BM-F03","hard","Which option best states the central argument?","Eligibility rules should consider how abrupt transitions affect incentives and household decisions",["Benefits should never use income","All cut-offs should be identical","Gradual withdrawal has no drawbacks"],"The passage focuses on behaviour around boundaries.","change behaviour around the boundary"),
 q("SP03-Q4","BM-F04","hard","What is the author's tone?","Analytical and policy-focused",["Hostile toward benefits","Promotional","Sarcastic"],"The author weighs simplicity against incentives and complexity.","balance simplicity, targeting and incentives"),
 q("SP03-Q5","BM-F05","medium","Why does the author discuss gradual withdrawal?","It can reduce the sudden loss created by a hard threshold",["It removes all administrative work","It guarantees higher benefits","It makes income stable"],"The taper smooths the transition.","reduces the size of the sudden change"),
 q("SP03-Q6","BM-F06","hard","Which statement cannot be inferred?","A gradual taper is automatically simple for households to understand",["Cliffs can affect work decisions","Income may vary monthly","Hard thresholds are easy to explain"],"The passage explicitly notes that tapers can add complexity.","makes the calculation more complex"),
 q("SP03-Q7","BM-F07","hard","What role does the fifth paragraph play?","It shows that smoothing the financial cliff can still leave an information problem",["It defines income","It rejects tapers","It introduces thresholds"],"The paragraph says uncertainty itself can affect behaviour.","Complexity has its own cost"),
 q("SP03-Q8","BM-F08","hard","Which conclusion follows most logically?","Policy should evaluate both eligibility accuracy and the transition faced by people near the boundary",["Only current eligibility matters","Income changes should be ignored","All benefits should end suddenly"],"The conclusion explicitly asks what happens as circumstances improve.","what happens when someone's circumstances improve slightly"),
 q("SP03-Q9","BM-F09","medium","In context, “taper” most nearly means:","a gradual reduction rather than a sudden stop",["a fixed cut-off","a new benefit","a monthly wage"],"The passage uses taper to describe gradual withdrawal.","a taper can better reflect gradual changes"),
 q("SP03-Q10","BM-F10","hard","Which assumption does the passage challenge?","That a simple eligibility boundary has no effect on behaviour",["Income can vary","Benefits have rules","Administration matters"],"The passage shows boundaries can alter work choices.","change behaviour around the boundary")
 ]
}
] as const;