export type Eng008Cp004Difficulty="medium"|"hard";
export type Eng008Cp004Genre="economy"|"business"|"technology"|"health"|"environment"|"social-policy"|"philosophy"|"media";
export type Eng008Cp004FamilyId="BM-F01"|"BM-F02"|"BM-F03"|"BM-F04"|"BM-F05"|"BM-F06"|"BM-F07"|"BM-F08"|"BM-F09"|"BM-F10";

export interface Eng008Cp004QuestionAuthorityV1{
 id:string;familyId:Eng008Cp004FamilyId;difficulty:Eng008Cp004Difficulty;question:string;correctAnswer:string;
 distractors:readonly [string,string,string];explanation:string;evidence:string;
}
export interface Eng008Cp004PassageV1{
 id:string;title:string;genre:Eng008Cp004Genre;text:string;questions:readonly Eng008Cp004QuestionAuthorityV1[];
}
const q=(id:string,familyId:Eng008Cp004FamilyId,difficulty:Eng008Cp004Difficulty,question:string,correctAnswer:string,distractors:readonly [string,string,string],explanation:string,evidence:string):Eng008Cp004QuestionAuthorityV1=>({id,familyId,difficulty,question,correctAnswer,distractors,explanation,evidence});

export const ENG008_CP004_PASSAGES_V1:readonly Eng008Cp004PassageV1[]=[
{
 id:"ENG008-BM-E01",title:"When Hiring Numbers Look Better Than Jobs Feel",genre:"economy",
 text:`Employment reports often attract attention through a single headline number: how many jobs were added or how low unemployment has fallen. Such figures are useful, but they can hide important changes in the quality and stability of work. A labour market may create many positions while workers still feel insecure if hours are irregular, wages fail to keep pace with living costs or new roles are concentrated in temporary contracts.

This does not mean headline employment data is misleading by definition. Without broad measures, it would be difficult to judge whether more people are finding work at all. The problem begins when one indicator is treated as a complete description of conditions that are actually multi-dimensional.

Consider two regions that each add the same number of jobs. In one, most positions are full-time and offer predictable hours. In the other, many workers are placed on short contracts that fluctuate from month to month. The headline increase may look identical, yet the effect on household planning, borrowing decisions and spending confidence can be very different.

For banks and businesses, this distinction matters because consumer behaviour responds not only to whether people are employed, but also to whether they expect their income to remain stable. A worker who doubts next month's earnings may postpone a large purchase even while officially counted as employed. In that sense, job security can influence demand in ways the unemployment rate alone cannot reveal.

Policymakers therefore increasingly examine several indicators together: participation, wage growth, hours worked, contract type and transitions between jobs. None is sufficient on its own. A broader set of measures does not eliminate uncertainty, but it makes hidden weaknesses easier to detect.

The larger lesson is methodological. Economic indicators are not useless because they are incomplete; they become misleading when their limits are forgotten. Good analysis asks what a number captures, what it leaves out and whether another measure is needed before drawing a wider conclusion.

There is also a distribution problem hidden inside averages. Wage growth may look healthy overall even if gains are concentrated among a narrow group of workers, while lower-paid workers experience little improvement. Likewise, a rise in average hours can reflect voluntary overtime for some people and involuntary overwork for others. Aggregate data remains useful, but interpretation improves when analysts ask who is driving the change.

This is why labour-market commentary can become misleading even without any false numbers. The mistake may lie in moving too quickly from a true statistic to a broader story that the statistic cannot support on its own. Better analysis does not require rejecting headline indicators; it requires treating them as the beginning of a question rather than the end of one. That distinction matters especially when a single figure becomes the basis for policy headlines, investment decisions or public confidence.`,
 questions:[
  q("E01-Q1","BM-F01","medium","Which factor does the passage identify as affecting workers' sense of security even when employment rises?","Irregular hours and unstable contracts",["Higher participation automatically reducing wages","A fall in the number of economic indicators","The complete absence of temporary work"],"The first paragraph directly links insecurity to irregular hours, weak wage growth and temporary contracts.","hours are irregular ... temporary contracts"),
  q("E01-Q2","BM-F02","hard","What can be inferred about two regions with identical job-growth figures?","Their economic effects may differ if the quality and stability of the jobs differ",["Their household spending patterns must be identical","Their unemployment rates must also be identical","Their wage growth must move in the same direction"],"The passage explicitly contrasts equal job growth with different contract stability and household effects.","headline increase may look identical, yet the effect ... can be very different"),
  q("E01-Q3","BM-F03","hard","Which option best states the central argument?","Employment data is useful, but job quantity alone cannot fully describe labour-market conditions",["Headline employment figures should be abandoned","Temporary work is always harmful to the economy","Consumer spending depends only on wage growth"],"The passage repeatedly argues for combining quantity with measures of quality and stability.","one indicator is treated as a complete description"),
  q("E01-Q4","BM-F04","hard","What is the author's tone?","Analytical and cautionary",["Dismissive of economic statistics","Celebratory about job creation","Alarmist about temporary work"],"The author values employment data but warns against over-reading it.","not useless because they are incomplete"),
  q("E01-Q5","BM-F05","medium","Why does the author compare two regions with the same job-growth figure?","To show how identical headline data can mask different underlying conditions",["To prove full-time jobs always create more jobs overall","To argue regional comparisons are impossible","To show unemployment is irrelevant"],"The example demonstrates the limits of relying on one aggregate number.","headline increase may look identical"),
  q("E01-Q6","BM-F06","hard","Which of the following cannot be inferred from the passage?","Any rise in employment will necessarily increase large consumer purchases",["Income stability can influence spending decisions","Headline job growth may hide differences in contract quality","Multiple labour indicators can reveal weaknesses missed by one measure"],"The passage says insecure workers may postpone large purchases, so the necessary increase claim is unsupported.","may postpone a large purchase"),
  q("E01-Q7","BM-F07","hard","What role does the fourth paragraph play in the passage?","It connects labour-market quality to consumer and business behaviour",["It introduces the original definition of unemployment","It rejects the need for wage data","It gives a historical account of banking policy"],"That paragraph explains why job stability matters beyond labour statistics, especially for spending and lending.","For banks and businesses, this distinction matters"),
  q("E01-Q8","BM-F08","hard","Which conclusion follows most logically?","A labour-market assessment is stronger when it combines quantity, stability and income indicators",["Unemployment should never be reported","Contract type alone predicts all consumer behaviour","More indicators always remove uncertainty"],"The fifth and sixth paragraphs advocate combining indicators while acknowledging remaining uncertainty.","examine several indicators together"),
  q("E01-Q9","BM-F09","medium","In context, “multi-dimensional” most nearly means:","having several important aspects",["difficult to measure numerically","limited to regional differences","changing only over long periods"],"The passage contrasts a single indicator with several dimensions such as wages, hours and contract type.","conditions that are actually multi-dimensional"),
  q("E01-Q10","BM-F10","hard","Which statement best distinguishes evidence from assumption in the passage?","Job counts show whether employment is rising; assuming they also capture job security goes beyond what the measure shows",["Job counts and job security are identical measures","Household spending always falls when temporary contracts rise","Wage growth is unrelated to employment quality"],"The passage's core methodological point is that a valid indicator can be overextended beyond its actual scope.","what a number captures, what it leaves out")
 ]
},
{
 id:"ENG008-BM-B01",title:"The Hidden Cost of Endless Choice",genre:"business",
 text:`Digital marketplaces often compete by expanding choice. A platform that lists more products, sellers or plans can appear more useful because users are less likely to leave in search of an option that is missing. Yet a large catalogue creates a second problem: finding a suitable choice becomes harder.

At first, platforms tried to solve this by adding filters. Users could narrow results by price, rating, size, delivery time or brand. Filters help when people already know which features matter. They are less useful when the user is unsure how to compare dozens of similar products or when important differences are difficult to express as a checkbox.

Recommendation systems emerged partly to reduce this burden. Instead of asking users to inspect the entire catalogue, a platform predicts which small group of items is likely to be relevant. This can save time, but it also shifts power toward the system that decides what becomes visible.

The commercial incentive is not always identical to the user's interest. A platform may earn more from some products than others, or sellers may pay for prominent placement. If these influences are not clear, a recommendation can look neutral even when business rules shape the ranking.

That does not make recommendations inherently untrustworthy. Personalisation can be genuinely useful, especially when catalogues are large. The issue is whether users can understand why certain options are shown, distinguish paid promotion from ordinary ranking and still reach alternatives without excessive effort.

A good marketplace therefore has to balance breadth with navigability. More choice creates value only if users can meaningfully compare it. The difficult design question is not simply how many options a platform can offer, but how much control users retain over the path by which those options are presented.

This problem becomes more important when users cannot easily observe the ranking rules. A supermarket shelf is physically visible, and shoppers can usually scan neighbouring products. A digital list can reorder itself for each person, hide many alternatives below several screens and change according to signals the user never sees. Personalisation therefore affects not only convenience but also the boundaries of comparison.

Regulators and platform designers increasingly debate whether transparency should mean publishing technical algorithms or providing simpler explanations that ordinary users can act on. Full technical disclosure may be too complex to help most people, while vague labels such as “recommended for you” reveal very little. The practical challenge is to give users enough information to recognise commercial influence and recover meaningful choice without overwhelming them with detail. In other words, transparency is useful only when it changes what a user can understand or do. A disclosure that is technically complete but practically unreadable may satisfy a formal requirement while leaving the real information imbalance almost untouched.`,
 questions:[
  q("B01-Q1","BM-F01","medium","Why are filters less useful for some users?","They may not know which features are important enough to filter by",["Filters always remove the cheapest products","Filters work only on small catalogues","Platforms do not allow users to combine filters"],"The second paragraph says filters depend on users knowing which features matter.","when people already know which features matter"),
  q("B01-Q2","BM-F02","hard","What can be inferred about recommendation systems?","They reduce search effort but also influence which options users are most likely to notice",["They remove all commercial influence from rankings","They make large catalogues unnecessary","They guarantee the objectively best choice"],"The passage presents recommendations as both a convenience and a visibility gatekeeper.","shifts power toward the system that decides what becomes visible"),
  q("B01-Q3","BM-F03","hard","What is the central argument?","Large marketplaces need transparency and user control as well as abundant choice",["Platforms should reduce product variety","Paid promotion should be banned entirely","Filters are better than recommendations in every case"],"The final paragraph ties value to navigability and control, not choice alone.","balance breadth with navigability"),
  q("B01-Q4","BM-F04","hard","What is the author's attitude toward personalisation?","Qualified support",["Complete rejection","Uncritical enthusiasm","Indifference"],"The author calls it useful but highlights the need for transparency and alternatives.","can be genuinely useful ... The issue is whether"),
  q("B01-Q5","BM-F05","medium","Why does the author mention seller payments for prominent placement?","To illustrate how commercial incentives can shape apparently neutral recommendations",["To show all recommendations are advertisements","To argue sellers should control rankings","To prove users prefer paid listings"],"The example supports the concern that ranking may reflect business rules.","a recommendation can look neutral even when business rules shape the ranking"),
  q("B01-Q6","BM-F06","hard","Which statement cannot be inferred?","Recommendation systems are always designed primarily to maximise user welfare",["Large catalogues can increase search difficulty","Commercial incentives may affect visibility","Users benefit from being able to reach alternatives"],"The passage explicitly warns that commercial incentives may differ from user interests.","commercial incentive is not always identical to the user's interest"),
  q("B01-Q7","BM-F07","hard","How does the third paragraph relate to the second?","It introduces a different solution to the search problem that filters do not fully solve",["It rejects the existence of search difficulty","It repeats the same solution using different wording","It shifts the topic from users to logistics"],"The third paragraph presents recommendation systems after explaining filters' limits.","Recommendation systems emerged partly to reduce this burden"),
  q("B01-Q8","BM-F08","hard","Which conclusion follows from the passage?","Choice has limited value if users cannot understand or navigate how options are presented",["More products always improve decisions","Users should avoid personalised systems entirely","Paid placement makes comparison impossible"],"The final paragraph explicitly links value to meaningful comparison and user control.","More choice creates value only if users can meaningfully compare it"),
  q("B01-Q9","BM-F09","medium","In context, “navigability” refers to:","how easily users can move through and compare available options",["the speed of product delivery","the legal ownership of a platform","the number of sellers on a site"],"The term is paired with breadth and meaningful comparison.","balance breadth with navigability"),
  q("B01-Q10","BM-F10","hard","Which assumption does the passage challenge most directly?","That displaying more options automatically improves user choice",["That ratings can be useful","That paid promotion exists","That filters can narrow results"],"The opening and conclusion both argue that abundance without usable navigation may reduce practical choice.","More choice creates value only if users can meaningfully compare it")
 ]
},
{
 id:"ENG008-BM-T01",title:"AI Assistance and the Illusion of Effortless Accuracy",genre:"technology",
 text:`As writing and analysis tools powered by artificial intelligence become common, organisations face a tempting assumption: if a system can produce a polished answer quickly, the cost of verification must also be low. In practice, the opposite can occur. Fluent output may make errors harder to notice because incorrect statements are presented with the same confidence and structure as correct ones.

Human reviewers therefore need a different skill from simple proofreading. They must identify which parts of a response are high-risk, which claims require external checking and where a plausible explanation may be based on a false premise. The better the prose sounds, the more important it becomes to separate presentation quality from evidential quality.

This changes the economics of automation. A system may save time on drafting yet create new work in supervision. Whether the overall process becomes more efficient depends on the cost of checking the output, the consequences of error and the availability of reliable sources against which claims can be tested.

For low-stakes tasks, occasional mistakes may be tolerable. For credit decisions, compliance, medical communication or financial reporting, verification requirements are much stricter. The same model can therefore be useful in one workflow and unsuitable in another without any contradiction.

Organisations sometimes respond by demanding that every AI-generated sentence be checked manually. That rule appears safe, but it can erase much of the efficiency benefit. A better approach is often risk-based: verify claims that matter most, constrain the system to trusted data where possible and design workflows in which uncertain outputs are easy to identify.

The important question is not whether AI is accurate in the abstract. It is whether a particular system, used for a particular task under a particular review process, produces acceptable results at an acceptable cost. Automation succeeds when the whole workflow improves, not merely when the first draft arrives faster.

The same principle applies to error measurement. A system that is wrong only occasionally may still be expensive if its rare mistakes occur in precisely the cases that are hardest to check or most costly to correct. Average accuracy can therefore hide operational risk. Review design should focus not only on how often errors occur, but also on where they occur and how easily they can be detected.

This is why organisations benefit from keeping records of corrections, escalations and reviewer effort. Those records turn vague impressions into workflow evidence. If a tool appears fast but repeatedly creates difficult verification work, the apparent productivity gain may disappear. Conversely, a tool with modest limitations may still be valuable when its uncertainty is predictable and the review process is well designed. This makes benchmarking more demanding than comparing model scores in isolation. Organisations need to compare complete workflows: time saved, review effort, correction rates, escalation frequency and the cost of mistakes that survive review.`,
 questions:[
  q("T01-Q1","BM-F01","medium","Why can fluent AI output make errors harder to detect?","Incorrect claims may be presented with the same confidence as correct ones",["Fluent systems never cite sources","Reviewers read polished prose more slowly","AI errors occur only in long answers"],"The opening paragraph directly explains the risk of confident presentation.","incorrect statements are presented with the same confidence"),
  q("T01-Q2","BM-F02","hard","What can be inferred about automation efficiency?","Drafting speed alone is insufficient to judge whether a workflow is more efficient",["Faster drafting always reduces total cost","Manual review always makes automation uneconomical","Verification cost is identical across tasks"],"The passage says total efficiency depends on checking cost and error consequences.","depends on the cost of checking the output"),
  q("T01-Q3","BM-F03","hard","Which option best states the central argument?","AI should be evaluated at the workflow level, including verification and risk, rather than by output speed alone",["AI is unsuitable for high-stakes work","All AI-generated content should be manually checked","Polished prose is usually inaccurate"],"The final paragraph explicitly reframes evaluation around the whole workflow.","Automation succeeds when the whole workflow improves"),
  q("T01-Q4","BM-F04","hard","What is the author's tone?","Cautiously pragmatic",["Technophobic and dismissive","Enthusiastic without reservation","Sarcastic"],"The author accepts AI's usefulness but insists on risk-aware verification.","can therefore be useful in one workflow and unsuitable in another"),
  q("T01-Q5","BM-F05","medium","Why does the author contrast low-stakes and high-stakes tasks?","To show that acceptable verification standards depend on the consequences of error",["To prove high-stakes tasks should never use automation","To show low-stakes tasks require no review","To compare model brands"],"The contrast demonstrates task-specific risk tolerance.","verification requirements are much stricter"),
  q("T01-Q6","BM-F06","hard","Which statement cannot be inferred?","A single universal verification rule is always optimal across organisations",["Different tasks may justify different review intensity","Verification can reduce the net time saved by automation","Trusted data can lower some review risk"],"The passage argues for risk-based rather than universal checking.","A better approach is often risk-based"),
  q("T01-Q7","BM-F07","hard","What is the role of the fifth paragraph?","It critiques an overly broad safety rule and proposes a more targeted alternative",["It introduces the first example of AI use","It proves manual review is unnecessary","It defines artificial intelligence"],"The paragraph rejects checking every sentence and suggests risk-based verification.","That rule appears safe ... A better approach"),
  q("T01-Q8","BM-F08","hard","Which conclusion follows most logically?","A model can be valuable even if it is not equally suitable for every workflow",["Accuracy matters only in financial tasks","A faster first draft guarantees lower cost","High-stakes users should avoid all automation"],"The fourth and final paragraphs emphasise task-specific suitability.","useful in one workflow and unsuitable in another without any contradiction"),
  q("T01-Q9","BM-F09","medium","In context, “constrain” most nearly means:","limit the system within controlled boundaries",["replace the system entirely","make the system faster","hide uncertain outputs"],"The passage refers to limiting AI to trusted data where possible.","constrain the system to trusted data"),
  q("T01-Q10","BM-F10","hard","Which distinction is most important to the author's argument?","Presentation quality is not the same as evidential reliability",["Drafting and reviewing are always performed by different people","High-stakes and low-stakes tasks use different software","External sources are always more accurate than internal data"],"The second paragraph explicitly separates polished presentation from evidence quality.","separate presentation quality from evidential quality")
 ]
},
{
 id:"ENG008-BM-H01",title:"Why Better Health Data Can Initially Look Worse",genre:"health",
 text:`When a health system improves screening, the number of recorded cases of a disease may rise sharply. To a casual observer, the increase can look like evidence that the underlying health situation has deteriorated. Sometimes that is true. But an increase in detected cases can also result from finding conditions that were previously missed.

This creates a communication problem. Public dashboards often display trends without explaining how testing practices have changed. If a new screening programme reaches more people or uses a more sensitive method, a rise in recorded cases may partly reflect better detection rather than a sudden increase in illness.

The opposite problem can occur as well. If testing falls because clinics are understaffed or people face barriers to access, reported cases may decline even while actual disease remains unchanged. Lower numbers therefore do not automatically mean better health.

Researchers address this by examining related measures: testing volume, positivity rates, hospital admissions, severity, geographic coverage and demographic reach. None perfectly reveals the true number of cases, but together they help distinguish changes in detection from changes in underlying conditions.

For administrators, the challenge is not only technical. If improved screening makes official numbers look worse in the short term, institutions may be tempted to avoid programmes that reveal hidden problems. That would reward ignorance rather than improvement.

A mature health system should therefore treat better measurement as a gain even when it produces uncomfortable statistics. The objective is not to make dashboards look favourable; it is to understand reality well enough to respond. Numbers are most useful when changes in measurement are explained alongside changes in outcomes.

The timing of interpretation also matters. A new screening campaign may initially produce a sharp rise in detected cases because previously untested groups enter the system all at once. Months later, the pattern may stabilise. Judging the programme only during the first surge could confuse improved visibility with deteriorating health, while judging only after stabilisation could hide the transition that produced the change.

Communication should therefore distinguish between surveillance effects and health effects. Surveillance effects arise because the system looks more carefully or reaches more people. Health effects concern whether the underlying condition is becoming more or less common or severe. The two can occur together, but they are conceptually different, and policy decisions are stronger when dashboards and reports make that difference explicit. Without that separation, the same rise in recorded cases can be interpreted as failure by one audience and as improved detection by another, even when both are looking at the same underlying data. Clear reporting should therefore state whether a change reflects broader testing, a different case definition, altered access to clinics, or a genuine shift in health outcomes. That context does not weaken the data; it makes the data more usable.`,
 questions:[
  q("H01-Q1","BM-F01","medium","Why might recorded disease cases rise after screening improves?","Previously missed cases may begin to be detected",["The disease must have become more severe","Hospitals may stop reporting cases","Testing methods always create false positives"],"The opening paragraph explicitly identifies improved detection as one cause.","finding conditions that were previously missed"),
  q("H01-Q2","BM-F02","hard","What can be inferred about falling reported case numbers?","They can be misleading if testing access also declines",["They always indicate successful treatment","They prove prevalence has fallen","They are irrelevant when staffing changes"],"The third paragraph warns that reduced testing can lower reported cases without changing actual disease.","reported cases may decline even while actual disease remains unchanged"),
  q("H01-Q3","BM-F03","hard","What is the central argument?","Health trends should be interpreted together with information about how measurement and testing changed",["Screening programmes usually exaggerate disease","Dashboards should stop reporting case counts","Hospital admissions are the only reliable indicator"],"The passage repeatedly argues that case counts need measurement context.","changes in measurement are explained alongside changes in outcomes"),
  q("H01-Q4","BM-F04","hard","What is the author's tone?","Explanatory and cautionary",["Distrustful of health data","Optimistic about every screening programme","Accusatory toward patients"],"The author explains measurement effects while warning against simple interpretation.","Lower numbers therefore do not automatically mean better health"),
  q("H01-Q5","BM-F05","medium","Why does the author mention testing volume, positivity and hospital admissions?","To show how multiple indicators can help separate detection changes from real health changes",["To argue dashboards should show only hospital data","To prove screening is unnecessary","To rank indicators by importance"],"The fourth paragraph presents these as complementary evidence.","together they help distinguish changes in detection"),
  q("H01-Q6","BM-F06","hard","Which statement cannot be inferred?","A higher recorded case count always means population health has worsened",["Improved screening can make official numbers rise","Lower testing can make reported numbers fall","Measurement context affects interpretation"],"The passage explicitly rejects the automatic worsening interpretation.","can also result from finding conditions that were previously missed"),
  q("H01-Q7","BM-F07","hard","What role does the fifth paragraph play?","It extends the measurement problem into an institutional incentive problem",["It introduces the definition of screening","It contradicts the earlier discussion of data","It shifts entirely to treatment methods"],"The paragraph explains how institutions might avoid revealing bad-looking statistics.","institutions may be tempted to avoid programmes that reveal hidden problems"),
  q("H01-Q8","BM-F08","hard","Which conclusion follows?","Better measurement may temporarily worsen reported statistics while improving decision quality",["More testing always lowers positivity","Administrators should avoid publishing uncomfortable data","Disease counts are unusable without perfect measurement"],"The conclusion values improved understanding even when the numbers look worse.","treat better measurement as a gain even when it produces uncomfortable statistics"),
  q("H01-Q9","BM-F09","medium","In context, “mature” most nearly means:","capable of handling evidence responsibly",["old in age","large in size","fully automated"],"The phrase refers to a health system that interprets uncomfortable evidence sensibly.","A mature health system"),
  q("H01-Q10","BM-F10","hard","Which assumption does the passage challenge?","That better-looking statistics necessarily reflect better underlying conditions",["That screening requires trained staff","That health systems use dashboards","That geography can affect access"],"The passage gives examples where lower or higher counts do not map directly to better or worse health.","Lower numbers therefore do not automatically mean better health")
 ]
},
{
 id:"ENG008-BM-EN01",title:"The Limits of Counting Trees",genre:"environment",
 text:`Cities often announce tree-planting targets in simple numbers: ten thousand saplings this year, fifty thousand over five years, or a certain percentage increase in green cover. Such targets are easy to communicate and can mobilise resources. But counting planted trees is not the same as measuring the long-term benefits of an urban forest.

A sapling that dies within two summers contributes little shade. A tree planted where roots have no space may never mature. Species choice matters too: some trees tolerate heat, pollution and limited water better than others. The location of planting also determines who benefits. A row of trees in an already green district may add less public value than shade along a heavily used walking route in a hotter neighbourhood.

This makes survival rates and canopy growth important. So do maintenance budgets, soil conditions and access to water during early years. These measures are less dramatic than a planting-day photograph, but they reveal whether a programme is likely to deliver lasting results.

There is also a timing issue. Mature trees provide benefits that new saplings cannot immediately replace. Removing an old tree and planting several young ones may increase the number of trees on paper while reducing shade for years. Replacement ratios therefore need to consider time, not only quantity.

None of this is an argument against ambitious planting. Cities facing heat and poor air quality often need more trees. The point is that a target should be connected to survival, location and future canopy rather than treated as complete once the sapling enters the ground.

Good environmental policy often requires moving from activity metrics to outcome metrics. Planting is an activity. Durable shade, cooling, habitat and healthier streets are outcomes. The two are related, but they are not identical.

Distribution also matters within the city. A planting programme may achieve a high survival rate overall while still doing little for the neighbourhoods most exposed to heat. If the healthiest trees are concentrated in parks that already have strong canopy, the programme can look successful on average while leaving major gaps untouched. Spatial measures therefore matter alongside survival measures.

Long-term monitoring can also reveal whether maintenance resources are aligned with planting ambition. Cities sometimes fund the initial purchase of saplings more easily than the years of watering, pruning and replacement that follow. If maintenance capacity does not grow with planting targets, a large programme can create impressive short-term activity but weak long-term outcomes. The quality of an urban-forest strategy is therefore visible not only on planting day, but in the years after it. This longer horizon also changes accountability: success should include whether trees remain healthy, whether canopy expands where it is needed and whether maintenance budgets keep pace with the promises made at launch.`,
 questions:[
  q("EN01-Q1","BM-F01","medium","Which factor does the passage say affects whether a newly planted tree delivers long-term benefit?","Survival and ability to mature in its location",["The number of planting-day photographs","The age of nearby buildings alone","Whether every district receives the same species"],"The passage repeatedly links outcomes to survival, space, species and maintenance.","survival rates and canopy growth"),
  q("EN01-Q2","BM-F02","hard","Why might planting several saplings after removing one mature tree still reduce benefits for years?","Young trees cannot immediately replace the mature tree's canopy and shade",["Saplings always die after transplanting","Mature trees provide no habitat","Tree counts fall whenever replacement occurs"],"The fourth paragraph makes the timing issue explicit.","Mature trees provide benefits that new saplings cannot immediately replace"),
  q("EN01-Q3","BM-F03","hard","What is the central argument?","Tree-planting programmes should be judged by lasting outcomes, not planting counts alone",["Cities should stop using numerical targets","Only mature trees should ever be planted","Green cover is impossible to measure"],"The final paragraph contrasts activity metrics with outcome metrics.","Planting is an activity ... shade ... are outcomes"),
  q("EN01-Q4","BM-F04","hard","What is the author's tone?","Supportive but critical of simplistic metrics",["Opposed to urban tree planting","Celebratory about planting targets","Indifferent to maintenance"],"The author supports ambitious planting but critiques counting alone.","None of this is an argument against ambitious planting"),
  q("EN01-Q5","BM-F05","medium","Why does the author compare planting in an already green district with planting along a hot walking route?","To show that location affects the public value of the same number of trees",["To prove green districts should lose trees","To argue walking routes are the only useful planting sites","To show species choice does not matter"],"The comparison demonstrates unequal benefit from identical planting counts.","location of planting also determines who benefits"),
  q("EN01-Q6","BM-F06","hard","Which statement cannot be inferred?","Any increase in the number of planted trees guarantees more urban shade",["Maintenance affects long-term success","Location influences who benefits","Replacement ratios should consider time"],"The passage explicitly explains why more planted trees may still produce less shade.","may increase the number of trees on paper while reducing shade"),
  q("EN01-Q7","BM-F07","hard","What role does the fourth paragraph play?","It introduces time as an additional dimension missing from simple tree counts",["It explains how to calculate air pollution","It rejects maintenance as a useful measure","It summarises the entire passage before the conclusion"],"That paragraph focuses on mature versus young trees and delayed replacement benefits.","There is also a timing issue"),
  q("EN01-Q8","BM-F08","hard","Which conclusion follows most logically?","A credible planting target should include measures of survival and future canopy",["Planting-day totals are never useful","Saplings should be counted only after ten years","Urban forestry has no short-term value"],"The fifth paragraph directly argues for linking targets to survival and canopy.","target should be connected to survival, location and future canopy"),
  q("EN01-Q9","BM-F09","medium","In context, “mobilise resources” most nearly means:","organise money, people or effort toward the programme",["measure canopy precisely","move trees between districts","reduce public participation"],"The phrase describes how simple targets can help gather support and capacity.","can mobilise resources"),
  q("EN01-Q10","BM-F10","hard","Which distinction is fundamental to the passage?","Activity metrics record what was done; outcome metrics assess what lasting result was achieved",["Public and private trees require different species","Green cover and air quality are unrelated","Saplings and mature trees are counted by different agencies"],"The final paragraph explicitly defines the distinction.","Planting is an activity ... are outcomes")
 ]
},
{
 id:"ENG008-BM-SP01",title:"Why Universal Services Still Need Targeted Design",genre:"social-policy",
 text:`Public services are often described as either universal or targeted. Universal programmes are open to everyone who meets a broad condition, while targeted programmes focus resources on groups judged to have greater need. The distinction is useful, but in practice even a universal service may require targeted design.

Consider a city bus system. It may be available to all residents, yet the same service is not equally usable by everyone. A route without step-free access can exclude passengers with limited mobility. A timetable available only through a smartphone can disadvantage people without reliable digital access. A stop placed far from residential areas may technically serve a neighbourhood while remaining impractical for many residents.

Responding to such barriers does not make the bus system less universal. On the contrary, targeted adjustments may be what allow a universal promise to become real. Low-floor buses, printed information, safer walking links and discounted passes address different obstacles without restricting the service to a narrow group.

The same principle appears in education, healthcare and digital public services. Equal rules can produce unequal access when people face different starting conditions. Yet targeted design also carries risks. If eligibility rules are complicated, users may not know what support exists or may avoid applying because the process is burdensome.

The policy challenge is therefore two-sided. Services should be broad enough to avoid unnecessary exclusion, but specific barriers should still be identified and reduced. Treating everyone identically is not always the same as treating everyone fairly.

A useful test is practical access: can people actually use the service with reasonable effort, cost and information? Universal policy defines who is included in principle. Targeted design helps determine whether that inclusion exists in practice.

There is also a question of administrative visibility. A barrier may exist even when official usage statistics look acceptable, because people who cannot use the service may never enter the dataset at all. Low complaint numbers, for example, do not prove that access is easy if excluded users do not know where or how to complain. Measuring only current users can therefore produce an incomplete picture of inclusion.

This is why service evaluation often needs outreach as well as usage data. Surveys, community feedback and observation of unsuccessful attempts can reveal barriers that transaction records miss. The aim is not to create a separate programme for every possible difficulty, but to identify recurring obstacles and remove those that prevent a broadly available service from functioning as broadly as intended. This approach also avoids a false choice between universalism and targeting. A service can remain broadly available while using targeted adjustments to make that broad availability meaningful for people who face recurring barriers. It also gives administrators a clearer basis for prioritisation. Not every inconvenience requires a separate programme, but barriers that repeatedly exclude the same groups deserve attention because they reveal a gap between nominal availability and practical access.`,
 questions:[
  q("SP01-Q1","BM-F01","medium","Which example illustrates a formally universal service that may still be hard to use?","A bus timetable available only through a smartphone",["A bus route open only to employees","A school restricted to one profession","A private taxi service"],"The second paragraph uses digital-only timetables as an access barrier within a universal bus system.","timetable available only through a smartphone"),
  q("SP01-Q2","BM-F02","hard","What can be inferred about targeted adjustments within universal services?","They can strengthen universal access rather than contradict it",["They necessarily convert the service into a targeted programme","They should be used only for low-income users","They always require complex eligibility rules"],"The third paragraph says targeted adjustments may make the universal promise real.","what allow a universal promise to become real"),
  q("SP01-Q3","BM-F03","hard","What is the central argument?","Universal eligibility may still require targeted design to achieve practical fairness",["Universal services should be replaced by targeted programmes","Equal rules always create equal access","Targeted programmes are easier to administer"],"The passage distinguishes inclusion in principle from usability in practice.","Universal policy defines who is included in principle"),
  q("SP01-Q4","BM-F04","hard","What is the author's tone?","Balanced and policy-oriented",["Hostile toward universal programmes","Dismissive of fairness concerns","Certain that targeted design has no risks"],"The author supports targeted adjustments while acknowledging administrative risks.","targeted design also carries risks"),
  q("SP01-Q5","BM-F05","medium","Why does the author use the bus-system example?","To show how equal formal access can coexist with unequal practical access",["To argue public transport should be free","To compare cities by population","To prove smartphone access is rare"],"The example translates the abstract universal/targeted distinction into practical barriers.","same service is not equally usable by everyone"),
  q("SP01-Q6","BM-F06","hard","Which statement cannot be inferred?","If a service is legally open to everyone, no further access analysis is needed",["Different users may face different barriers","Complex support rules can discourage use","Practical access matters alongside formal inclusion"],"The entire passage argues that formal openness is insufficient.","inclusion exists in practice"),
  q("SP01-Q7","BM-F07","hard","What role does the fourth paragraph play?","It broadens the argument beyond transport and introduces a risk of targeted design",["It abandons the idea of universal services","It provides evidence that buses are uniquely unequal","It defines fairness for the first time"],"The paragraph extends the principle to other sectors and notes complexity risks.","The same principle appears in education, healthcare and digital public services"),
  q("SP01-Q8","BM-F08","hard","Which conclusion follows?","Fair access may require different forms of support for different barriers",["Fairness requires identical treatment in every circumstance","Universal services should avoid any special accommodation","Eligibility rules should always be detailed"],"The fifth paragraph explicitly separates identical treatment from fair treatment.","Treating everyone identically is not always the same as treating everyone fairly"),
  q("SP01-Q9","BM-F09","medium","In context, “burdensome” most nearly means:","difficult or demanding to complete",["financially profitable","widely advertised","automatically approved"],"The word describes an application process that may discourage users.","process is burdensome"),
  q("SP01-Q10","BM-F10","hard","Which distinction best captures the passage's logic?","Formal inclusion concerns eligibility; practical inclusion concerns actual usability",["Universal services are public while targeted services are private","Printed information is universal while digital information is targeted","Fairness can be measured only by cost"],"The conclusion explicitly states this principle/practice distinction.","included in principle ... inclusion exists in practice")
 ]
},
{
 id:"ENG008-BM-PH01",title:"The Productive Value of Changing One's Mind",genre:"philosophy",
 text:`People often treat consistency as evidence of strength. A leader who repeats the same position over time may appear dependable, while someone who changes an opinion can be accused of weakness or indecision. Yet consistency is valuable only when the original belief remains supported by good reasons.

If new evidence appears, refusing to revise a belief can become a form of stubbornness rather than strength. Scientific progress depends on this distinction. A theory is respected not because it can never be changed, but because it can survive testing and be revised when better explanations emerge.

The same logic applies outside science, though the evidence may be less precise. A manager may change a staffing plan after learning that a key assumption was wrong. A household may revise a budget when income changes. In both cases, changing course can reflect attention to reality rather than lack of conviction.

Of course, constant reversal is not automatically wise. A person who changes direction after every minor criticism may lack stable principles. The question is why the change occurred. Revision based on stronger evidence is different from change driven only by pressure or convenience.

This makes intellectual flexibility demanding rather than easy. It requires a person to hold beliefs strongly enough to act on them, but lightly enough to revise them when the case changes. That balance can be uncomfortable because admitting error may carry social cost.

The deeper form of consistency, then, may lie not in repeating the same conclusion but in applying the same standard of evidence across different situations. A person can change an opinion and still remain consistent in method.

This distinction also helps explain why public debate often rewards the wrong kind of consistency. Statements can be replayed years later without the context in which they were made, making any change look suspicious. Yet a refusal to update can be intellectually weaker than a transparent explanation of what new evidence caused the revision. Accountability should therefore examine both the change and the reason for it.

None of this means people should revise beliefs merely to appear open-minded. Genuine flexibility is disciplined: the standard for changing a view should be related to the strength and relevance of the new evidence. Otherwise, “being flexible” can become another excuse for convenience. The value lies in keeping the method stable enough that both persistence and revision can be justified by reasons rather than image. In this sense, intellectual flexibility is not the opposite of commitment. It is a commitment to a method strong enough to survive the discomfort of revision when the evidence no longer supports the conclusion that once seemed reasonable. The discipline lies in making the reason for revision visible. A person who can explain which evidence changed, why it mattered and what threshold was crossed demonstrates a more stable method than someone who simply repeats the same conclusion to avoid appearing inconsistent.`,
 questions:[
  q("PH01-Q1","BM-F01","medium","According to the passage, when does consistency lose value?","When a belief is maintained despite better contrary reasons",["When a leader communicates clearly","When evidence remains unchanged","When a principle is applied repeatedly"],"The first two paragraphs distinguish justified consistency from stubbornness.","refusing to revise a belief can become a form of stubbornness"),
  q("PH01-Q2","BM-F02","hard","What can be inferred about changing one's mind?","Its value depends on the reason and evidence behind the change",["It always signals uncertainty","It is wise whenever criticism appears","It is valuable only in scientific work"],"The fourth paragraph explicitly distinguishes evidence-based revision from pressure-driven change.","The question is why the change occurred"),
  q("PH01-Q3","BM-F03","hard","What is the central argument?","Methodological consistency can coexist with changing conclusions when evidence changes",["Strong people never change their views","Scientific theories should be abandoned frequently","Stable principles prevent intellectual growth"],"The final paragraph states that conclusions may change while standards remain consistent.","consistent in method"),
  q("PH01-Q4","BM-F04","hard","What is the author's tone?","Reflective and reasoned",["Mocking toward consistent people","Dogmatic about flexibility","Indifferent to evidence"],"The passage carefully qualifies both consistency and revision.","constant reversal is not automatically wise"),
  q("PH01-Q5","BM-F05","medium","Why does the author mention a manager and a household?","To show that evidence-based revision applies in ordinary practical decisions too",["To compare scientific and financial careers","To argue managers should change plans often","To prove household budgets are scientific theories"],"These examples extend the principle beyond science.","same logic applies outside science"),
  q("PH01-Q6","BM-F06","hard","Which statement cannot be inferred?","Changing a position after social pressure is necessarily intellectually flexible",["Admitting error may carry social cost","Stable principles and revision can coexist","Evidence-based change differs from convenience-based change"],"The passage explicitly separates principled revision from pressure-driven reversal.","different from change driven only by pressure"),
  q("PH01-Q7","BM-F07","hard","What role does the fourth paragraph play?","It limits the argument by explaining that not every change of mind is wise",["It contradicts the defence of revision","It introduces scientific testing","It concludes that principles are unimportant"],"The paragraph adds a qualification to prevent overgeneralisation.","constant reversal is not automatically wise"),
  q("PH01-Q8","BM-F08","hard","Which conclusion follows?","A person may be consistent in standards even while changing a conclusion",["Changing conclusions always weakens credibility","Evidence should matter only before a decision is made","Flexibility requires avoiding strong beliefs"],"This is the final explicit conclusion of the passage.","change an opinion and still remain consistent in method"),
  q("PH01-Q9","BM-F09","medium","In context, “conviction” most nearly means:","firm belief or commitment",["public criticism","scientific proof","temporary hesitation"],"The passage contrasts conviction with changing direction too easily.","lack of conviction"),
  q("PH01-Q10","BM-F10","hard","Which assumption does the passage reject?","That consistency requires preserving the same conclusion regardless of new evidence",["That people use evidence in decisions","That social cost can affect behaviour","That scientific theories are tested"],"The final paragraph redefines consistency as applying the same evidential standard.","not in repeating the same conclusion")
 ]
},
{
 id:"ENG008-BM-M01",title:"The Problem with Information That Arrives Too Easily",genre:"media",
 text:`Modern information systems remove many barriers between an event and the audience. A short video, alert or post can spread within minutes, allowing people to learn about developments quickly. Speed has obvious value, especially during emergencies or rapidly changing events. But speed also changes the conditions under which information is judged.

When people encounter a claim repeatedly in a short period, familiarity can be mistaken for confirmation. Ten posts may appear to provide ten independent signals even when all of them trace back to one uncertain source. The structure of a network can therefore create an illusion of agreement.

Platforms try to address this through labels, source information and links to additional context. These tools help, but they compete with a strong behavioural fact: users often decide whether to share or believe a claim before opening the underlying article. Design features that arrive after that first judgment may have limited effect.

Slowing every piece of information would be neither practical nor desirable. The goal is not to recreate an era of delayed communication. Instead, systems can create small moments of friction where the cost of a mistaken share is high: asking whether an article was opened, showing the original source, or warning when many posts repeat the same claim.

Friction is often treated as bad design because it makes a process less seamless. Yet in information systems, a little friction can sometimes improve judgment. The same extra step that annoys a user may also create time to notice uncertainty.

The challenge is to decide where friction helps more than it harms. Too much can block useful communication; too little can reward speed over verification. Good design does not maximise either speed or caution in isolation. It tries to match the pace of sharing to the reliability required by the situation.

The source environment further complicates the problem. In many breaking events, reliable information is genuinely incomplete for a period of time. Demanding certainty too early can suppress useful warnings, while treating every early report as equally credible can amplify error. Systems therefore need ways to communicate confidence and provenance, not merely a binary label of true or false.

User behaviour also changes in response to design. If warnings appear on too many harmless posts, people may learn to ignore them. If friction is applied only after a claim has already gone viral, it may arrive too late. Effective design therefore requires calibration: enough intervention to interrupt risky sharing, but not so much that caution itself becomes background noise. The objective is a better decision environment, not simply more warnings. That requires continuous testing because the same intervention may work differently across communities, topics and moments of urgency. Friction should therefore be treated as a design variable to be measured and adjusted, not as a moral signal that more interruption is always safer.`,
 questions:[
  q("M01-Q1","BM-F01","medium","Why can repeated posts create a false sense of confirmation?","They may all originate from the same uncertain source",["Users always ignore source information","Repeated claims become legally verified","Platforms count every post as evidence"],"The second paragraph explains that apparent multiplicity may come from one source.","all of them trace back to one uncertain source"),
  q("M01-Q2","BM-F02","hard","What can be inferred about design labels that appear after a user's first judgment?","Their influence may be limited because the user may already have decided what to believe or share",["They are always ignored","They increase sharing speed","They eliminate source confusion"],"The third paragraph explicitly notes the timing problem.","before opening the underlying article"),
  q("M01-Q3","BM-F03","hard","What is the central argument?","Information systems should balance speed with carefully placed friction that supports verification",["Fast communication should be abandoned","Users should be prevented from sharing uncertain claims","Labels are sufficient to solve misinformation"],"The conclusion argues against maximising either speed or caution alone.","match the pace of sharing to the reliability required"),
  q("M01-Q4","BM-F04","hard","What is the author's tone?","Analytical and balanced",["Nostalgic for slower media","Hostile toward social platforms","Uncritically optimistic about friction"],"The passage acknowledges both the benefits of speed and the costs of too much friction.","Too much can block useful communication; too little can reward speed"),
  q("M01-Q5","BM-F05","medium","Why does the author give examples such as asking whether an article was opened?","To illustrate small forms of friction that may prompt users to reconsider before sharing",["To show articles should be hidden","To prove users never read sources","To recommend slower internet speeds"],"These examples operationalise the idea of useful friction.","create small moments of friction"),
  q("M01-Q6","BM-F06","hard","Which statement cannot be inferred?","The safest information system is always the one with the most friction",["Speed can be useful during emergencies","Repeated exposure can mimic independent confirmation","Too little friction can favour unverified sharing"],"The final paragraph explicitly says too much friction can also be harmful.","Too much can block useful communication"),
  q("M01-Q7","BM-F07","hard","What role does the fifth paragraph play?","It reframes friction from a design flaw into a possible aid to judgment",["It introduces the first example of misinformation","It rejects the need for fast communication","It explains how algorithms rank posts"],"The paragraph challenges the usual assumption that seamlessness is always better.","Friction is often treated as bad design ... Yet"),
  q("M01-Q8","BM-F08","hard","Which conclusion follows?","The appropriate amount of friction depends on the reliability demands of the context",["Every post should require manual verification","Fast sharing is never justified","Users should trust familiar claims"],"The final sentence makes the context-dependent standard explicit.","reliability required by the situation"),
  q("M01-Q9","BM-F09","medium","In context, “seamless” most nearly means:","smooth and requiring little interruption",["verified by experts","widely shared","technically complex"],"The passage contrasts seamless processes with added steps or friction.","makes a process less seamless"),
  q("M01-Q10","BM-F10","hard","Which distinction underlies the passage?","Repeated visibility is not the same as independent evidence",["Emergency information is always reliable","Source labels are the same as fact checks","Slow communication is always more accurate"],"The second paragraph directly separates repetition from independent confirmation.","illusion of agreement")
 ]
}
] as const;

export const ENG008_CP004_QUESTION_AUTHORITIES_V1=ENG008_CP004_PASSAGES_V1.flatMap(p=>p.questions.map(question=>({passage:p,question})));
