export const HIS_CP020_EXPLANATION_NOTES_V1:Readonly<Record<number,string>>={
  1:"Surplus cultivable land meant agricultural growth often came from extending the cultivated frontier. The state therefore had a direct fiscal interest in bringing new land under the plough.",
  2:"Forest clearance and reclamation increased the cultivated area and also expanded the revenue base. This process affected tribal, outlying and previously uncultivated zones.",
  3:"The cultivated area continued to grow across the Mughal period. The comparison with Akbar's reign shows that agricultural expansion remained active even in the later seventeenth century.",
  4:"The food-crop list shows a diversified subsistence base built around cereals and pulses. It should be kept separate from commercial crops grown mainly for sale or processing.",
  5:"Sugarcane, cotton, indigo, opium and silk were important commercial products. Their production connected agriculture with textile, dye, sugar and export markets.",
  6:"Bengal combined fertile agriculture with strong commercial production. Its reputation for sugarcane also fits the wider pattern of Bengal as a major productive region.",
  7:"Bayana and Sarkhej are useful place-product markers for indigo. Indigo mattered because its blue dye had strong demand in textile production and trade.",
  8:"Sericulture became much more widespread under the Mughals. Bengal's emergence as the chief silk-producing region linked agriculture directly with textile manufacture.",
  9:"Tobacco belongs to the group of crops introduced after overseas contact intensified. Its Portuguese introduction distinguishes it from older Indian food and cash crops.",
  10:"Pineapple, papaya and cashew are examples of crops introduced through Portuguese contact. These changes show how overseas exchange altered Indian agriculture and diet.",
  11:"The Persian wheel was a mechanical improvement over simpler lifting devices. Gears, pots and animal power made it possible to raise water more efficiently from wells.",
  12:"Canal irrigation expanded under several rulers, but Firuz Shah Tughlaq created the most extensive network among the Delhi Sultans. Irrigation policy therefore formed part of state support for cultivation.",
  13:"Land revenue mattered because agriculture produced the largest share of economic output. Medieval fiscal systems consequently devoted major administrative effort to assessing and collecting it.",
  14:"Batai focused on the actual crop rather than only the measured area. The state's share was taken directly from the produce under a crop-sharing arrangement.",
  15:"Khet-batai was a form of crop sharing carried out while the crop was still standing. The field itself became the basis for dividing the cultivator's and state's shares.",
  16:"Lang-batai differed because the crop was first cut and stacked. The state's share was then determined from the heaps before the grain was separated.",
  17:"Kankut combined two ideas: measurement and estimation of productivity. This made it more calculation-based than simple sharing of the harvested crop.",
  18:"Sher Shah's one-third demand was based on average yield. This helped make assessment more systematic while still tying the demand to agricultural productivity.",
  19:"The rai converted crop-specific assessment into a stated revenue rate per bigha. Early Mughal administration initially made use of these rates before later refinements.",
  20:"Zabt relied on measured land and prescribed rates rather than dividing the harvest itself. It therefore differed clearly from batai.",
  21:"Dasturs were revenue circles created to account for local differences in productivity and prices. Cash rates could then be worked out for crops within each circle.",
  22:"Dahsala reduced the effect of a single unusual year by using a ten-year average. It supported a more stable calculation of cash revenue demand.",
  23:"These four categories reflected how regularly land was cultivated. Polaj was the most regularly cultivated, while banjar stood at the least cultivated end of the scale.",
  24:"Patta and qabuliyat worked as paired documents. One stated the assessment and land details; the other recorded the cultivator's acceptance of the revenue obligation.",
  25:"Zamindars stood between the state and cultivators and possessed hereditary claims in many regions. Their share existed alongside, not instead of, the state's revenue demand.",
  26:"Muqaddams and patels were local headmen rather than high imperial officers. Their role joined village administration, order and revenue collection.",
  27:"Patwaris and kulkarnis handled village accounts in different regions. They were important because revenue administration depended on local records as well as central rules.",
  28:"Khudkasht cultivators formed the wealthier end of the peasant spectrum. Their larger holdings and access to labour separated them from poorer cultivators and village menials.",
  29:"Raiyat was a broad social and fiscal term for ordinary cultivators. It is more general than labels for particular wealthy, migrant or service groups.",
  30:"Peasant hardship came from several pressures acting together rather than one tax alone. Revenue demands, intermediary shares, borrowing and natural disasters could all reduce subsistence margins.",
  31:"Medieval textile production was diverse rather than limited to cotton. Silk, wool and coarse mixed fabrics supported different regional markets and consumer groups.",
  32:"Textile manufacture was geographically widespread. The long list of centres shows why cloth became one of the most important manufactured goods in internal and overseas trade.",
  33:"Kashmir, Lahore and Agra developed specialised reputations in higher-value textile products. Shawls and carpets were distinct from ordinary cotton cloth.",
  34:"Dyeing and bleaching became specialised crafts with their own production centres. This reflects increasing division of labour within the textile economy.",
  35:"Saltpetre was economically important because it fed the manufacture of gunpowder. Its value therefore connected mining and chemical processing with military technology.",
  36:"Patna's importance in saltpetre processing grew strongly by the later seventeenth century. This made the city significant in both inland trade and military-supply networks.",
  37:"Golconda became famous internationally for diamonds. It should be separated from centres such as Khetri, which specialised in a different mineral.",
  38:"Khetri's importance lay in copper rather than precious stones. Place-product matching is a useful way to distinguish major medieval mining centres.",
  39:"Paper-making spread after entering India in the Sultanate period. By Mughal times it supported administration, scholarship, book production and commercial record-keeping across many regions.",
  40:"The charkha increased the speed of yarn production compared with older spindle methods. It therefore affected productivity before the weaving stage itself.",
  41:"The pit loom improved the speed of weaving and belongs to the fifteenth-century technology sequence. It should not be confused with the earlier spinning wheel.",
  42:"The drawloom made complex coloured patterns easier to weave. Its function was therefore different from both spinning and ordinary loom improvements.",
  43:"Bidri work represents a specialised medieval metal craft based on alloy technology. Copper and zinc were combined to create a distinctive material for decorative objects.",
  44:"Artillery technology reached India through more than one channel. Babur brought techniques linked to Persian-Ottoman warfare, while Portuguese contact added another route of transmission.",
  45:"Tin coating had a practical household purpose rather than a decorative one. It created a protective layer inside copper and brass vessels used for food.",
  46:"The jajmani system tied rural artisans into customary village relationships. Their work was often exchanged through established service obligations rather than only open-market sale.",
  47:"Balutedars were part of the more organised village service structure found in the Deccan and Maharashtra. The term belongs to rural craft and service organisation.",
  48:"Dadni connected merchant capital with artisan labour. Advances of money and raw material allowed production to grow beyond what a poorly financed individual artisan could manage alone.",
  49:"Royal karkhanas were state-supervised production units. Their output often included expensive goods for the court, while some specialised units such as mints and arms workshops worked on a larger scale.",
  50:"Hats and penths made regular exchange possible even where permanent urban markets were absent. Their fixed weekly schedule connected villages with nearby commercial activity.",
  51:"The spread of trade centres across north, west, south and the Deccan shows the scale of Mughal-period inland commerce. These centres linked local markets with wider regional networks.",
  52:"Bengal's trade network connected several major towns and ports. Their inter-regional links helped make the province one of the most commercially active parts of the empire.",
  53:"These imports show demand for both luxury goods and strategic commodities. Horses were especially important because high-quality cavalry animals were not produced everywhere in sufficient numbers.",
  54:"Spices and cotton cloth were major export goods, while ivory and precious stones added high-value products. Export patterns therefore combined bulk manufactures and luxury items.",
  55:"Karwanis linked grain-producing countryside with markets by moving in groups. Their role shows that food supply depended on specialised transport merchants as well as cultivators.",
  56:"Banjaras continued the mobile carrying tradition on a large scale. Their movement between villages and towns made them important to internal distribution networks.",
  57:"Sarrafs combined several functions that modern systems often separate. Their expertise in coins, credit, deposits, precious metals and hundis made them central to commercial finance.",
  58:"Dalals reduced the information gap between buyers and sellers, especially for outsiders unfamiliar with local markets. Their brokerage became increasingly common in Mughal commerce.",
  59:"Hundis allowed money to be transferred through trusted commercial networks rather than physically carried over long distances. This reduced risk and made large transactions easier.",
  60:"Insurance spread because long-distance trade involved transport risk. Commercial firms accepted a premium and compensated merchants when covered goods were damaged in transit.",
};
