/**
 * Rich question template support.
 *
 * A rich template is a self-contained pattern definition that includes the
 * question logic (with [VAR] placeholders), variable specifications, a math
 * formula to compute the correct answer, and optional constraints. Questions
 * are generated by sampling variables, substituting them into the question
 * text, evaluating the formula, and producing plausible distractor options.
 */

import type { MockSection, MockDifficulty } from "@workspace/db";
import { db } from "./db";
import { questions, tests, categories } from "@workspace/db";
import { eq, sql } from "drizzle-orm";
import type { GeneratedQuestion } from "./generator.service";

// ─── Types ──────────────────────────────────────────────────────────────────

export type RichTemplateFields = {
  questionLogic: string;
  variables: Record<string, string | string[] | number>;
  mathFormula: string;
  constraints?: string;
};

export type RichTemplate = {
  kind: "rich";
  examName?: string;
  section: MockSection;
  topic: string;
  subtopic: string;
  patternId?: string;
  patternName?: string;
  difficulty: MockDifficulty;
  questionCount: number;
  fields: RichTemplateFields;
};

// ─── Normalizers ────────────────────────────────────────────────────────────

const SECTION_MAP: Record<string, MockSection> = {
  quant: "quant",
  quantitative: "quant",
  "quantitative aptitude": "quant",
  math: "quant",
  maths: "quant",
  mathematics: "quant",
  arithmetic: "quant",
  reasoning: "reasoning",
  "logical reasoning": "reasoning",
  "general intelligence": "reasoning",
  "general intelligence and reasoning": "reasoning",
  english: "english",
  "english language": "english",
  "english comprehension": "english",
  verbal: "english",
  general: "general",
  "general awareness": "general",
  "general knowledge": "general",
  gk: "general",
  ga: "general",
};

const DIFF_MAP: Record<string, MockDifficulty> = {
  easy: "easy",
  e: "easy",
  basic: "easy",
  moderate: "medium",
  medium: "medium",
  m: "medium",
  intermediate: "medium",
  hard: "hard",
  difficult: "hard",
  tough: "hard",
  advanced: "hard",
};

export function mapSection(value: unknown): MockSection {
  const key = String(value ?? "").trim().toLowerCase();
  return SECTION_MAP[key] ?? "quant";
}

export function mapDifficulty(value: unknown): MockDifficulty {
  const key = String(value ?? "").trim().toLowerCase();
  return DIFF_MAP[key] ?? "medium";
}

/**
 * Detect whether a raw payload represents a rich template (has fields with
 * question_logic / variables / math_formula).
 */
export function isRichPayload(raw: any): boolean {
  if (!raw || typeof raw !== "object") return false;
  if (raw.kind === "rich") return true;
  const fields = raw.fields ?? raw.template?.fields ?? raw;
  return Boolean(
    fields &&
      (fields.question_logic || fields.questionLogic) &&
      (fields.math_formula || fields.mathFormula),
  );
}

/**
 * Normalize an arbitrary JSON payload into a RichTemplate. Accepts both
 * snake_case (the user's documented format) and camelCase variants, as well
 * as wrappers like {name, template:{...}}.
 */
export function normalizeRichTemplate(raw: any): RichTemplate {
  // Unwrap common shapes.
  let src = raw;
  if (src?.template && (src.template.fields || src.fields == null)) {
    src = { ...src, ...src.template };
  }

  const fieldsRaw = src.fields ?? {};
  const variables = (fieldsRaw.variables ?? {}) as Record<string, any>;

  const questionCount = Math.max(
    1,
    Math.floor(Number(src.questionCount ?? src.question_count ?? 5) || 5),
  );

  return {
    kind: "rich",
    examName: src.exam_name ?? src.examName ?? undefined,
    section: mapSection(src.section),
    topic: String(src.topic ?? "").trim() || "General",
    subtopic: String(src.subtopic ?? src.sub_topic ?? "").trim() || "General",
    patternId: src.template_id ?? src.patternId ?? undefined,
    patternName: src.pattern_name ?? src.patternName ?? src.name ?? undefined,
    difficulty: mapDifficulty(src.difficulty),
    questionCount,
    fields: {
      questionLogic: String(
        fieldsRaw.question_logic ?? fieldsRaw.questionLogic ?? "",
      ).trim(),
      variables,
      mathFormula: String(
        fieldsRaw.math_formula ?? fieldsRaw.mathFormula ?? "",
      ).trim(),
      constraints: fieldsRaw.constraints
        ? String(fieldsRaw.constraints).trim()
        : undefined,
    },
  };
}

// ─── Variable sampling ──────────────────────────────────────────────────────

function randInt(min: number, max: number): number {
  const lo = Math.min(min, max);
  const hi = Math.max(min, max);
  return Math.floor(Math.random() * (hi - lo + 1)) + lo;
}

function randPick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

/**
 * Try to interpret a variable spec string (e.g. "Integer (range 700-950)") and
 * return a sampled value. Returns the original string if no rule matches.
 */
function sampleSpec(spec: string, allValues: Record<string, any>): string | number {
  const trimmed = spec.trim();

  // Plain number, e.g. "1000 (standard 1kg)" or "1000".
  const numberPrefix = trimmed.match(/^(-?\d+(?:\.\d+)?)/);
  if (numberPrefix && /^-?\d+(?:\.\d+)?\s*(?:\(|$)/.test(trimmed)) {
    return Number(numberPrefix[1]);
  }

  // Conditional integer ranges, e.g.
  //   "Integer (0 if Cost Price, 1-20 if Profit/Loss)"
  // Pick a numeric range from one of the clauses based on prior chosen vars.
  const condMatch = trimmed.match(/^Integer\s*\((.+)\)\s*$/i);
  if (condMatch) {
    const inner = condMatch[1];
    // Try to find one of the conditional branches matching a previously
    // chosen variable. Each clause is split by comma at depth 0.
    const clauses = inner.split(/\s*,\s*/);
    for (const clause of clauses) {
      // "0 if Cost Price"
      const fixedIf = clause.match(/^(-?\d+(?:\.\d+)?)\s+if\s+(.+)$/i);
      if (fixedIf) {
        const cond = fixedIf[2].toLowerCase();
        if (Object.values(allValues).some((v) => String(v).toLowerCase() === cond)) {
          return Number(fixedIf[1]);
        }
        continue;
      }
      // "1-20 if Profit/Loss"
      const rangeIf = clause.match(/^(-?\d+)\s*[-–]\s*(-?\d+)\s+if\s+(.+)$/i);
      if (rangeIf) {
        const conds = rangeIf[3].split(/\s*\/\s*/).map((s) => s.toLowerCase());
        if (
          Object.values(allValues).some((v) =>
            conds.includes(String(v).toLowerCase()),
          )
        ) {
          return randInt(Number(rangeIf[1]), Number(rangeIf[2]));
        }
        continue;
      }
      // "range 700-950" or "700-950"
      const rangeOnly = clause.match(/(-?\d+)\s*[-–]\s*(-?\d+)/);
      if (rangeOnly) {
        return randInt(Number(rangeOnly[1]), Number(rangeOnly[2]));
      }
      // single number
      const single = clause.match(/^(-?\d+(?:\.\d+)?)$/);
      if (single) return Number(single[1]);
    }
    // Fallback: any range anywhere.
    const anyRange = inner.match(/(-?\d+)\s*[-–]\s*(-?\d+)/);
    if (anyRange) return randInt(Number(anyRange[1]), Number(anyRange[2]));
    const anyNum = inner.match(/(-?\d+(?:\.\d+)?)/);
    if (anyNum) return Number(anyNum[1]);
  }

  // Decimal range, e.g. "Decimal (range 1.5-3.0)"
  const decimalRange = trimmed.match(/Decimal[^)]*\(([^)]+)\)/i);
  if (decimalRange) {
    const m = decimalRange[1].match(/(-?\d+(?:\.\d+)?)\s*[-–]\s*(-?\d+(?:\.\d+)?)/);
    if (m) {
      const lo = Number(m[1]);
      const hi = Number(m[2]);
      const v = lo + Math.random() * (hi - lo);
      return Math.round(v * 100) / 100;
    }
  }

  // Generic "range A-B" anywhere.
  const range = trimmed.match(/(?:range\s*)?(-?\d+)\s*[-–]\s*(-?\d+)/i);
  if (range && /integer/i.test(trimmed)) {
    return randInt(Number(range[1]), Number(range[2]));
  }
  if (range) {
    return randInt(Number(range[1]), Number(range[2]));
  }

  return trimmed;
}

export function sampleVariables(
  variables: Record<string, any>,
): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  // Sample list-typed vars first so conditional integer specs can reference
  // them.
  const entries = Object.entries(variables);
  const lists = entries.filter(([, v]) => Array.isArray(v));
  const others = entries.filter(([, v]) => !Array.isArray(v));

  for (const [name, spec] of lists) {
    out[name] = String(randPick(spec as any[]));
  }
  for (const [name, spec] of others) {
    if (typeof spec === "number") {
      out[name] = spec;
    } else {
      out[name] = sampleSpec(String(spec), out);
    }
  }
  return out;
}

// ─── Text substitution ──────────────────────────────────────────────────────

export function substitutePlaceholders(
  text: string,
  values: Record<string, string | number>,
): string {
  return text.replace(/\[([A-Z0-9_]+)\]/g, (_, key) => {
    const v = values[key];
    return v == null ? `[${key}]` : String(v);
  });
}

// ─── Formula evaluation ─────────────────────────────────────────────────────

/**
 * Evaluate a math formula given variable values. Handles formulas like:
 *   "Profit% = [((Target_Weight * (1 + Claim_Value/100)) / Actual_Weight) - 1] * 100"
 *
 * Returns { value, isPercent }. Throws if the expression cannot be evaluated.
 */
export function evaluateFormula(
  formula: string,
  values: Record<string, string | number>,
): { value: number; isPercent: boolean; expression: string } {
  // Drop the LHS label, e.g. "Profit% = ..."
  let expr = formula.includes("=") ? formula.split("=").slice(1).join("=") : formula;
  expr = expr.trim();

  const isPercent = /%/.test(formula.split("=")[0] ?? "");

  // The user format uses [] as grouping brackets. Convert them to parentheses.
  expr = expr.replace(/\[/g, "(").replace(/\]/g, ")");

  // Replace variable names (case-insensitive) with their numeric values.
  // Match longest names first to avoid partial-replacements.
  const varEntries = Object.entries(values).sort(
    (a, b) => b[0].length - a[0].length,
  );
  for (const [name, raw] of varEntries) {
    const numeric = typeof raw === "number" ? raw : Number(raw);
    if (!Number.isFinite(numeric)) continue;
    const pattern = new RegExp(`\\b${escapeRegex(name)}\\b`, "gi");
    expr = expr.replace(pattern, String(numeric));
  }

  // Strip any remaining alpha characters (units etc.) and ensure only safe
  // tokens remain.
  if (/[A-Za-z_]/.test(expr)) {
    throw new Error(
      `Formula references unknown identifier after substitution: ${expr}`,
    );
  }
  if (!/^[\s\d.+\-*/()%]+$/.test(expr)) {
    throw new Error(`Unsafe characters in formula expression: ${expr}`);
  }
  // Replace lone `%` (Math modulo) — treat as nothing if attached to a label.
  // We already removed the LHS label, so any remaining `%` is unlikely; keep
  // it as JS modulo if present.

  // eslint-disable-next-line no-new-func
  const fn = new Function(`"use strict"; return (${expr});`);
  const value = Number(fn());
  if (!Number.isFinite(value)) {
    throw new Error(`Formula evaluation produced non-finite value: ${expr}`);
  }
  return { value, isPercent, expression: expr };
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ─── Answer formatting + distractors ────────────────────────────────────────

function roundNice(n: number): number {
  // Round to 2 decimals; if very close to an integer, snap to integer.
  const rounded = Math.round(n * 100) / 100;
  if (Math.abs(rounded - Math.round(rounded)) < 1e-6) return Math.round(rounded);
  return rounded;
}

export function formatAnswer(value: number, isPercent: boolean): string {
  const v = roundNice(value);
  return isPercent ? `${v}%` : `${v}`;
}

export function buildDistractors(
  correct: number,
  isPercent: boolean,
): string[] {
  const correctStr = formatAnswer(correct, isPercent);
  const candidates = new Set<string>([correctStr]);

  // Generate plausible distractors using ±X% perturbations and absolute deltas.
  const offsets = [
    correct * 0.9,
    correct * 1.1,
    correct + (correct >= 1 ? 1 : 0.1),
    correct - (correct >= 1 ? 1 : 0.1),
    correct * 0.75,
    correct * 1.25,
    correct + 5,
    correct - 5,
  ];
  for (const v of offsets) {
    if (candidates.size >= 4) break;
    const formatted = formatAnswer(v, isPercent);
    candidates.add(formatted);
  }
  // Pad if we still don't have four (e.g. tiny numbers collapsing to same).
  let pad = 1;
  while (candidates.size < 4) {
    candidates.add(formatAnswer(correct + pad, isPercent));
    pad += 1;
  }

  const arr = Array.from(candidates);
  // Shuffle but keep correct in the result set.
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// ─── Persistence ────────────────────────────────────────────────────────────

const BANK_TEST_ID = "__bank__";
const RICH_TOPIC_FALLBACK_ID = "topic-rich-template";

// Resolve a valid topics_global.id to satisfy questions.global_topic_id NOT NULL FK.
// Strategy:
//   1. Try to find an existing topics_global row whose name matches the
//      template's topic (case-insensitive).
//   2. Otherwise ensure a single sentinel row "topic-rich-template" exists
//      and use it.
async function resolveGlobalTopicId(topicName: string): Promise<string> {
  try {
    if (topicName && topicName.trim()) {
      const rows = (await db.execute(sql`
        SELECT id FROM topics_global
        WHERE LOWER(name) = LOWER(${topicName.trim()})
        LIMIT 1
      `)) as unknown as { rows?: Array<{ id: string }> } | Array<{ id: string }>;
      const list = Array.isArray(rows) ? rows : rows.rows ?? [];
      if (list.length > 0 && list[0]?.id) return list[0].id;
    }
  } catch {
    // fall through to sentinel
  }
  try {
    await db.execute(sql`
      INSERT INTO topics_global (id, name)
      VALUES (${RICH_TOPIC_FALLBACK_ID}, ${"Rich Template (System)"})
      ON CONFLICT (id) DO NOTHING
    `);
  } catch {
    // best-effort
  }
  return RICH_TOPIC_FALLBACK_ID;
}

async function ensureBankTestExists(): Promise<string | null> {
  try {
    const [existing] = await db
      .select({ id: tests.id })
      .from(tests)
      .where(eq(tests.id, BANK_TEST_ID))
      .limit(1);
    if (existing) return existing.id;

    await db.execute(sql`
      INSERT INTO tests (id, name, category, category_id, duration, total_questions, difficulty, sections)
      SELECT ${BANK_TEST_ID}, 'Question Bank (System)', t.category, t.category_id, 1, 0, 'Easy', '[]'::jsonb
      FROM tests t
      WHERE t.id <> ${BANK_TEST_ID}
      LIMIT 1
      ON CONFLICT (id) DO NOTHING
    `);

    const [created] = await db
      .select({ id: tests.id })
      .from(tests)
      .where(eq(tests.id, BANK_TEST_ID))
      .limit(1);
    return created?.id ?? null;
  } catch {
    return null;
  }
}

// ─── End-to-end generator ───────────────────────────────────────────────────

export async function generateRichQuestions(
  template: RichTemplate,
  opts: { persist?: boolean } = {},
): Promise<GeneratedQuestion[]> {
  if (!template.fields.questionLogic) {
    throw new Error("Rich template is missing fields.question_logic");
  }
  if (!template.fields.mathFormula) {
    throw new Error("Rich template is missing fields.math_formula");
  }

  const out: GeneratedQuestion[] = [];
  const seen = new Set<string>();
  const maxAttempts = template.questionCount * 6;
  let attempts = 0;

  const persist = opts.persist !== false;
  let resolvedGlobalTopicId = "";
  if (persist) {
    await ensureBankTestExists();
    resolvedGlobalTopicId = await resolveGlobalTopicId(template.topic ?? "");
  }

  while (out.length < template.questionCount && attempts < maxAttempts) {
    attempts += 1;
    let vars: Record<string, string | number>;
    let evald: { value: number; isPercent: boolean; expression: string };
    try {
      vars = sampleVariables(template.fields.variables);
      evald = evaluateFormula(template.fields.mathFormula, vars);
    } catch (err) {
      // Skip bad samples (e.g. division by zero)
      console.warn("[rich-template] sample/eval failed:", (err as Error).message);
      continue;
    }
    if (!Number.isFinite(evald.value)) continue;

    const text = substitutePlaceholders(template.fields.questionLogic, vars);
    const correctStr = formatAnswer(evald.value, evald.isPercent);
    const options = buildDistractors(evald.value, evald.isPercent);

    const dedupeKey = `${text.toLowerCase()}|${correctStr}`;
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);

    const explanationLines = [
      template.fields.constraints
        ? `Pattern constraint: ${template.fields.constraints}`
        : null,
      `Given values: ${Object.entries(vars)
        .map(([k, v]) => `${k} = ${v}`)
        .join(", ")}.`,
      `Apply the formula: ${template.fields.mathFormula}.`,
      `Substitute → ${evald.expression} = ${correctStr}.`,
      `Hence the answer is ${correctStr}.`,
    ].filter(Boolean) as string[];
    const explanation = explanationLines.join("\n");

    let savedId: number | undefined;
    if (persist) {
      try {
        const correctIndex = options.indexOf(correctStr);
        if (correctIndex < 0) continue;
        const difficultyLabel =
          template.difficulty === "easy"
            ? "Easy"
            : template.difficulty === "medium"
              ? "Medium"
              : "Hard";
        // Use raw SQL so we can guarantee a value for `global_topic_id`
        // (NOT NULL, no DEFAULT in production) without relying on Drizzle's
        // column-set inference.
        const inserted = await db.execute(sql`
          INSERT INTO questions
            (client_id, test_id, pattern_id, text, options, correct,
             section, topic, subtopic, global_topic_id, explanation,
             difficulty, ai_refined, quality_score, question_type)
          VALUES
            (${""}, ${BANK_TEST_ID}, ${null},
             ${text}, ${JSON.stringify(options)}::jsonb, ${correctIndex},
             ${template.section}, ${template.topic ?? "General"},
             ${template.subtopic ?? ""}, ${resolvedGlobalTopicId}, ${explanation},
             ${difficultyLabel}, ${0}, ${90}, ${"text"})
          RETURNING id
        `);
        const firstRow = (inserted as unknown as { rows?: Array<{ id: number }> })
          .rows?.[0] ??
          (Array.isArray(inserted) ? (inserted as Array<{ id: number }>)[0] : undefined);
        savedId = firstRow?.id;
      } catch (err) {
        const e = err as { message?: string; cause?: { message?: string; code?: string } };
        console.warn(
          "[rich-template] persist failed, returning question without id:",
          e?.message,
          e?.cause?.code ? `(cause ${e.cause.code}: ${e.cause.message})` : "",
        );
      }
    }

    out.push({
      id: savedId,
      patternId: template.patternId ?? "rich",
      patternName: template.patternName ?? "Rich Template",
      section: template.section,
      topic: template.topic,
      subtopic: template.subtopic,
      difficulty: template.difficulty,
      questionText: text,
      options,
      correctAnswer: correctStr,
      explanation,
      qualityScore: 90,
      aiRefined: false,
      aiSource: "skipped",
      validation: { valid: true, issues: [] },
    });
  }

  if (out.length === 0) {
    throw new Error(
      "Could not generate any questions from this rich template. Check the variable specs and formula.",
    );
  }
  return out;
}

// Re-export so callers can use them without importing drizzle.
export const __internals = { ensureBankTestExists, categories };
