import type{Eng009Cp002PassageV1}from"./eng-009-cp002-authorities-v1";
export const ENG009_CP002_BREADTH_WAVE2:readonly Eng009Cp002PassageV1[]=[
{id:"ENG009-SSC-A13",title:"Why Warning Messages Fail",topic:"risk communication",template:`A warning message may be technically correct and still fail to change behaviour. One reason is that people often see too many alerts and begin to ignore them. If every minor event produces the same urgent message, users may stop treating any warning as important. Effective design therefore depends on matching the strength of the message to the seriousness of the risk. The warning should state what is wrong, what action is needed and what may happen if the action is not taken. Vague wording can create uncertainty, while excessive detail can hide the main instruction. Good warnings therefore make the required action __(1)__. Timing also matters. A message shown too early may be forgotten, while one shown after the risky action is too late. The best moment is often just before the user must decide. Visual emphasis can help, but colour or symbols should not replace clear language. Designers should also test whether users actually understand the message. A phrase that seems obvious to an expert may be interpreted differently by the public. Testing reveals whether the wording is genuinely __(2)__. Repeated false alarms create another problem because they reduce trust. When users learn that alerts rarely matter, they become less likely to respond quickly. This means accuracy is part of warning design. The system should avoid both missing serious risks and __(3)__ harmless events. The strongest warnings are therefore selective, timely and easy to act on. Their purpose is not simply to attract attention but to direct it toward the correct response. In this sense, a warning succeeds when it changes behaviour in a way that is __(4)__ to the risk. Good communication does not remove danger, but it makes the required response more __(5)__.`,blanks:[
{id:"A13-B1",blankNo:1,difficulty:"medium",kind:"collocation",answer:"clear",distractors:["visible","direct","simple"],explanation:"The user should immediately understand the required action, so 'clear' fits.",clue:"make the required action ..."},
{id:"A13-B2",blankNo:2,difficulty:"hard",kind:"context",answer:"unambiguous",distractors:["brief","formal","precise"],explanation:"Testing checks whether users understand the message in only one intended way.",clue:"wording is genuinely ..."},
{id:"A13-B3",blankNo:3,difficulty:"hard",kind:"vocabulary",answer:"overstating",distractors:["reporting","noticing","listing"],explanation:"The system should not make harmless events seem more serious than they are.",clue:"... harmless events"},
{id:"A13-B4",blankNo:4,difficulty:"hard",kind:"discourse",answer:"proportionate",distractors:["equal","general","ordinary"],explanation:"The response should match the seriousness of the risk, so 'proportionate' fits.",clue:"response ... to the risk"},
{id:"A13-B5",blankNo:5,difficulty:"medium",kind:"context",answer:"manageable",distractors:["visible","formal","stable"],explanation:"Clear instructions make the response easier to handle.",clue:"response more ..."}]},
{id:"ENG009-SSC-A14",title:"Why Queue Numbers Help",topic:"service design",template:`A visible queue can feel longer than it really is when people do not know how quickly it is moving. Numbered tokens or digital queue displays can reduce this uncertainty by showing customers that their turn has been recorded. The system does not necessarily reduce the actual waiting time, but it can make the process feel more organised. Customers are less likely to crowd a counter when they know they will not lose their place. This can improve both comfort and staff efficiency. However, a queue system works only when the sequence is followed consistently. If staff regularly call people out of order without explanation, trust in the system may __(1)__. Different services may also need separate queues because some transactions take much longer than others. A single line can be fair, but it may also allow one complex case to delay many simple ones. Service managers therefore need to choose a structure that matches the type of work. They can study arrival patterns and transaction times to identify busy periods. This information helps them allocate staff more __(2)__. Clear signs are equally important because customers need to know where to wait and what number is currently being served. Confusing displays can create the same uncertainty the system was meant to reduce. The best queue design therefore combines order, information and flexibility. It gives customers a reliable place in line while allowing staff to respond to different service needs. The goal is not to remove all waiting, which may be impossible, but to make waiting more __(3)__. A predictable process can also reduce conflict because customers can see that the order is being followed. When exceptions are necessary, staff should explain them. This keeps the system more __(4)__ and prevents special cases from appearing unfair. Good queue management therefore depends as much on communication as on speed. A well-designed system makes service flow easier to understand and easier to __(5)__.`,blanks:[
{id:"A14-B1",blankNo:1,difficulty:"hard",kind:"vocabulary",answer:"weaken",distractors:["fall","drop","move"],explanation:"If the order is not followed, trust in the system can weaken.",clue:"trust ... may ..."},
{id:"A14-B2",blankNo:2,difficulty:"medium",kind:"collocation",answer:"efficiently",distractors:["privately","rarely","roughly"],explanation:"Arrival data helps managers use staff more efficiently.",clue:"allocate staff more ..."},
{id:"A14-B3",blankNo:3,difficulty:"hard",kind:"context",answer:"tolerable",distractors:["short","simple","visible"],explanation:"The system may not remove waiting, but it can make waiting easier to accept.",clue:"make waiting more ..."},
{id:"A14-B4",blankNo:4,difficulty:"hard",kind:"discourse",answer:"transparent",distractors:["formal","strict","regular"],explanation:"Explaining exceptions keeps the process easy to understand.",clue:"system more ..."},
{id:"A14-B5",blankNo:5,difficulty:"medium",kind:"context",answer:"manage",distractors:["count","hide","divide"],explanation:"A clear system makes service flow easier to manage.",clue:"easier to ..."}]}
];