import type{Eng009Cp002PassageV1}from"./eng-009-cp002-authorities-v1";
export const ENG009_CP002_BREADTH_WAVE3:readonly Eng009Cp002PassageV1[]=[
{id:"ENG009-SSC-A15",title:"Why Feedback Forms Can Mislead",topic:"survey design",template:`Feedback forms are easy to distribute, but the results can mislead when only a small or unusual group responds. People with very good or very bad experiences may be more likely to complete the form than people whose experience was ordinary. The responses may therefore not __(1)__ the full customer population. Question wording creates another risk. A vague question may be interpreted in different ways, while a leading question can push people toward a preferred answer. Good forms use clear, neutral language. Timing matters too. Asking immediately captures fresh impressions but may miss problems that appear later. A high satisfaction score is useful evidence, but it should not be treated as __(2)__ proof that the service is working perfectly. Complaint data, repeat usage and observation can add context. Combining several sources makes the final judgment more __(3)__. Feedback is strongest when it is used to identify patterns rather than defend a preferred conclusion. This requires managers to interpret results with both interest and __(4)__. A good feedback system values responses while remaining aware of their __(5)__.`,blanks:[
{id:"A15-B1",blankNo:1,difficulty:"hard",kind:"vocabulary",answer:"represent",distractors:["contain","repeat","display"],explanation:"The respondents may not represent the full customer population.",clue:"may not ... the full customer population"},
{id:"A15-B2",blankNo:2,difficulty:"medium",kind:"context",answer:"conclusive",distractors:["useful","visible","formal"],explanation:"One survey score should not be treated as final proof. 'Conclusive' fits.",clue:"should not be treated as ... proof"},
{id:"A15-B3",blankNo:3,difficulty:"hard",kind:"discourse",answer:"reliable",distractors:["detailed","large","fast"],explanation:"Several evidence sources make the judgment more reliable.",clue:"judgment more ..."},
{id:"A15-B4",blankNo:4,difficulty:"hard",kind:"collocation",answer:"caution",distractors:["speed","pressure","silence"],explanation:"Survey results should be interpreted with caution.",clue:"with both interest and ..."},
{id:"A15-B5",blankNo:5,difficulty:"medium",kind:"context",answer:"limits",distractors:["colours","distances","shapes"],explanation:"A good system recognises what feedback cannot fully show.",clue:"aware of their ..."}]},
{id:"ENG009-SSC-A16",title:"Why Evacuation Signs Need Testing",topic:"emergency communication",template:`Emergency signs are meant to guide people quickly when normal routes may be unsafe. Their wording may look simple, but effectiveness depends on whether people can understand them under stress. A sign placed too high, hidden by equipment or visible from only one direction may fail when needed. Organisations should therefore test signs from the viewpoint of someone who does not know the building. Clear arrows and consistent symbols reduce the need for interpretation. Emergency lighting may also be needed so signs remain __(1)__ during power loss. Drills can reveal whether people hesitate at the same point or misread a direction. A sign is not effective simply because it follows a design rule; it is effective when it helps people move __(2)__ toward safety. Regular checks matter because furniture or construction can change what people can see. Emergency guidance therefore requires ongoing __(3)__ rather than one-time installation. Testing keeps instructions more __(4)__ and makes the correct action easier to __(5)__.`,blanks:[
{id:"A16-B1",blankNo:1,difficulty:"medium",kind:"vocabulary",answer:"visible",distractors:["formal","silent","fixed"],explanation:"Emergency signs must remain visible even during poor lighting.",clue:"signs remain ..."},
{id:"A16-B2",blankNo:2,difficulty:"hard",kind:"context",answer:"decisively",distractors:["quietly","privately","slowly"],explanation:"Good signs help people move without hesitation, so 'decisively' fits.",clue:"move ... toward safety"},
{id:"A16-B3",blankNo:3,difficulty:"hard",kind:"collocation",answer:"maintenance",distractors:["distance","silence","colour"],explanation:"The system needs regular maintenance, not just installation.",clue:"requires ... rather than a one-time installation"},
{id:"A16-B4",blankNo:4,difficulty:"hard",kind:"discourse",answer:"consistent",distractors:["large","brief","formal"],explanation:"Regular testing helps instructions remain consistent.",clue:"instructions more ..."},
{id:"A16-B5",blankNo:5,difficulty:"medium",kind:"context",answer:"identify",distractors:["borrow","divide","hide"],explanation:"The sign should make the correct action easy to identify.",clue:"correct action easier to ..."}]}
];