import type { PolCp026SeedRow } from "./pol-cp026-types";

const T=["CONSTITUTION-TRIBUNALS-2025"] as const;
const A=["ADMINISTRATIVE-TRIBUNALS-ACT-1985"] as const;
const S=["SUPREME-COURT-L-CHANDRA-KUMAR"] as const;

export const POL_CP026_PART_4: readonly PolCp026SeedRow[] = [
["POL-026-QL-016","Medium","Article 323A allows an administrative tribunal for the Union and:","Separate tribunals for States or two or more States","Only one tribunal for all States","Only district-level tribunals","Only military tribunals","Article 323A permits Parliament to provide a Union administrative tribunal and separate tribunals for individual States or for two or more States together.",T],
["POL-026-QL-016","Medium","Can a law under Article 323A give an administrative tribunal contempt powers?","Yes","No","Only the Supreme Court may have contempt power","Only during Emergency","Article 323A expressly allows the Parliamentary law to specify tribunal jurisdiction and powers, including the power to punish for contempt.",T],
["POL-026-QL-016","Medium","The procedure prescribed for Article 323A tribunals may include rules on:","Limitation and evidence","Constitutional amendments only","Election schedules only","State boundaries only","Article 323A allows the law to prescribe tribunal procedure, expressly mentioning matters such as limitation and rules of evidence.",T],
["POL-026-QL-016","Medium","Can pending cases within the new tribunal's jurisdiction be transferred to it under an Article 323A law?","Yes","No","Only criminal appeals","Only with a constitutional amendment","Article 323A permits Parliament to provide for transfer of pending cases that would fall within the administrative tribunal's jurisdiction after its establishment.",T],

["POL-026-QL-017","Hard","Tax assessment and collection are among the tribunal subjects listed in:","Article 323B","Article 323A","Article 312","Article 315","Article 323B expressly includes levy, assessment, collection and enforcement of taxes among the matters for which the competent Legislature may establish tribunals.",T],
["POL-026-QL-017","Hard","Does Article 323B include industrial and labour disputes among its listed matters?","Yes","No","Only during a Financial Emergency","Only if Parliament amends Article 323A","Industrial and labour disputes are expressly listed in Article 323B, alongside subjects such as taxation, land reforms and specified economic matters.",T],
["POL-026-QL-017","Hard","The Seventy-fifth Amendment added this subject to Article 323B:","Rent regulation and tenancy issues","All-India Services","Public Service Commissions","Official language disputes","The Seventy-fifth Amendment added rent regulation, control and tenancy issues to the list of tribunal subjects in Article 323B.",T],
["POL-026-QL-017","Hard","Which subject falls within Article 323B rather than Article 323A?","Foreign exchange and customs-frontier imports or exports","Recruitment to Union civil services","Conditions of service of State employees","Service complaints of government-controlled corporations","Article 323B includes foreign exchange and import-export matters, while Article 323A is specifically centred on recruitment and service-condition disputes.",T],

["POL-026-QL-018","Hard","The law-making power under Article 323A belongs to Parliament; under Article 323B it belongs to:","The appropriate Legislature competent on the subject","Only the President","Only the Supreme Court","Only Rajya Sabha","Article 323B uses the broader expression appropriate Legislature, meaning Parliament or a competent State Legislature depending on legislative power over the subject.",T],
["POL-026-QL-018","Hard","Which distinction between Articles 323A and 323B is correct?","323A centres on service matters; 323B lists several other subject areas","323A covers elections only; 323B covers services only","Both deal only with public employment","323B applies only to Union employees","Article 323A is designed around public-service recruitment and conditions, whereas Article 323B authorises tribunals across several specifically listed legislative subjects.",T],
["POL-026-QL-018","Hard","A hierarchy of tribunals is expressly contemplated in:","Article 323B","Article 323A only","Article 309","Article 312A","Article 323B expressly says the law may provide for a hierarchy of tribunals, a feature stated directly in that Article.",T],
["POL-026-QL-018","Hard","Can laws under both Articles 323A and 323B specify tribunal jurisdiction, powers and procedure?","Yes","No, only Article 323A can","No, only Article 323B can","Only after State ratification","Both tribunal Articles allow the relevant law to define jurisdiction, powers and procedure, although their subjects and law-making authorities differ.",T],

["POL-026-QL-019","Hard","The Administrative Tribunals Act was enacted in:","1985","1976","1991","2005","The Administrative Tribunals Act, 1985 was enacted to implement Article 323A for adjudication of specified public-service recruitment and service-condition disputes.",A],
["POL-026-QL-019","Hard","Which body is established under the 1985 Act for central service disputes?","Central Administrative Tribunal","Election Commission of India","Inter-State Council","Finance Commission","Section 4 of the Administrative Tribunals Act provides for establishment of the Central Administrative Tribunal by notification of the Central Government.",A],
["POL-026-QL-019","Hard","The Central Administrative Tribunal provisions of the 1985 Act came into force on:","1 July 1985","26 January 1950","3 January 1977","15 May 1994","India Code records 1 July 1985 as the enforcement date for the Act's Central Administrative Tribunal provisions.",A],
["POL-026-QL-019","Hard","Does the Administrative Tribunals Act apply to members of the Union armed forces?","No","Yes, without exception","Only to commissioned officers","Only during peacetime","Section 2 excludes members of the naval, military, air and other armed forces of the Union from the Act's application.",A],

["POL-026-QL-020","Hard","The leading case preserving High Court scrutiny of tribunal decisions is:","L. Chandra Kumar v. Union of India","Kesavananda Bharati v. State of Kerala","S. R. Bommai v. Union of India","Minerva Mills v. Union of India","L. Chandra Kumar is the leading tribunal case establishing that constitutional judicial review by High Courts cannot be excluded from tribunal decisions.",S],
["POL-026-QL-020","Hard","After L. Chandra Kumar, tribunal decisions remain subject to High Court jurisdiction under:","Articles 226 and 227","Article 123 only","Article 280 only","Article 360 only","The Supreme Court has reiterated that tribunal decisions are subject to High Court writ and supervisory jurisdiction under Articles 226 and 227.",S],
["POL-026-QL-020","Hard","Judicial review by High Courts and the Supreme Court was treated in L. Chandra Kumar as part of:","The basic structure of the Constitution","The pleasure doctrine","The Eighth Schedule","The electoral-roll system","L. Chandra Kumar treated constitutional judicial review as an integral feature of the basic structure, preventing tribunal arrangements from fully excluding constitutional-court scrutiny.",S],
["POL-026-QL-020","Hard","Can an administrative tribunal's decision be made completely immune from High Court judicial review merely by relying on Article 323A?","No","Yes, in every service matter","Yes, if the tribunal has contempt power","Only State tribunals are immune","The present constitutional position after L. Chandra Kumar is that tribunal decisions remain open to High Court scrutiny under Articles 226 and 227.",S],
];
