import type { PolCp026SeedRow } from "./pol-cp026-types";

const T=["CONSTITUTION-TRIBUNALS-2025"] as const;
const A=["ADMINISTRATIVE-TRIBUNALS-ACT-1985"] as const;
const S=["SUPREME-COURT-L-CHANDRA-KUMAR"] as const;

export const POL_CP026_PART_4: readonly PolCp026SeedRow[] = [
["POL-026-QL-016","Medium","Under Article 323A, Parliament may establish a Union tribunal and:","Separate tribunals for States or two or more States","Only one tribunal for all States","Only district-level tribunals","Only military tribunals","Article 323A permits Parliament to provide a Union administrative tribunal and separate tribunals for individual States or for two or more States together.",T],
["POL-026-QL-016","Medium","Can an administrative tribunal be given contempt powers under Article 323A?","Yes","No","Only the Supreme Court may have contempt power","Only during Emergency","Article 323A expressly allows the Parliamentary law to specify tribunal jurisdiction and powers, including the power to punish for contempt.",T],
["POL-026-QL-016","Medium","Procedure under Article 323A may include rules relating to:","Limitation and evidence","Constitutional amendments only","Election schedules only","State boundaries only","Article 323A allows the law to prescribe tribunal procedure, expressly mentioning matters such as limitation and rules of evidence.",T],
["POL-026-QL-016","Medium","Can pending cases be transferred to a tribunal created under Article 323A?","Yes","No","Only criminal appeals","Only with a constitutional amendment","Article 323A permits Parliament to provide for transfer of pending cases that would fall within the administrative tribunal's jurisdiction after its establishment.",T],

["POL-026-QL-017","Hard","Tribunals for tax assessment and collection are specifically covered by:","Article 323B","Article 323A","Article 312","Article 315","Article 323B expressly includes levy, assessment, collection and enforcement of taxes among the matters for which the competent Legislature may establish tribunals.",T],
["POL-026-QL-017","Hard","Are industrial and labour disputes included among the subjects listed in Article 323B?","Yes","No","Only during a Financial Emergency","Only if Parliament amends Article 323A","Industrial and labour disputes are expressly listed in Article 323B, alongside subjects such as taxation, land reforms and specified economic matters.",T],
["POL-026-QL-017","Hard","The Seventy-fifth Amendment added which subject to Article 323B?","Rent regulation and tenancy issues","All-India Services","Public Service Commissions","Official language disputes","The Seventy-fifth Amendment added rent regulation, control and tenancy issues to the list of tribunal subjects in Article 323B.",T],
["POL-026-QL-017","Hard","Which of the following falls under Article 323B rather than Article 323A?","Foreign exchange and customs-frontier imports or exports","Recruitment to Union civil services","Conditions of service of State employees","Service complaints of government-controlled corporations","Article 323B includes foreign exchange and import-export matters, while Article 323A is specifically centred on recruitment and service-condition disputes.",T],

["POL-026-QL-018","Hard","Under Article 323B, tribunal laws may be made by:","The appropriate Legislature competent on the subject","Only the President","Only the Supreme Court","Only Rajya Sabha","Article 323B uses the broader expression appropriate Legislature, meaning Parliament or a competent State Legislature depending on legislative power over the subject.",T],
["POL-026-QL-018","Hard","Which statement correctly distinguishes Articles 323A and 323B?","323A centres on service matters; 323B lists several other subject areas","323A covers elections only; 323B covers services only","Both deal only with public employment","323B applies only to Union employees","Article 323A is designed around public-service recruitment and conditions, whereas Article 323B authorises tribunals across several specifically listed legislative subjects.",T],
["POL-026-QL-018","Hard","A hierarchy of tribunals is expressly contemplated under:","Article 323B","Article 323A only","Article 309","Article 312A","Article 323B expressly says the law may provide for a hierarchy of tribunals, a feature stated directly in that Article.",T],
["POL-026-QL-018","Hard","Can laws under both Articles 323A and 323B define tribunal jurisdiction, powers and procedure?","Yes","No, only Article 323A can","No, only Article 323B can","Only after State ratification","Both tribunal Articles allow the relevant law to define jurisdiction, powers and procedure, although their subjects and law-making authorities differ.",T],

["POL-026-QL-019","Hard","The Administrative Tribunals Act was enacted in:","1985","1976","1991","2005","The Administrative Tribunals Act, 1985 was enacted to implement Article 323A for adjudication of specified public-service recruitment and service-condition disputes.",A],
["POL-026-QL-019","Hard","Which tribunal deals with central service disputes under the Administrative Tribunals Act, 1985?","Central Administrative Tribunal","Election Commission of India","Inter-State Council","Finance Commission","Section 4 of the Administrative Tribunals Act provides for establishment of the Central Administrative Tribunal by notification of the Central Government.",A],
["POL-026-QL-019","Hard","The Central Administrative Tribunal provisions came into force on:","1 July 1985","26 January 1950","3 January 1977","15 May 1994","India Code records 1 July 1985 as the enforcement date for the Act's Central Administrative Tribunal provisions.",A],
["POL-026-QL-019","Hard","Does the Administrative Tribunals Act, 1985 apply to members of the Union armed forces?","No","Yes, without exception","Only to commissioned officers","Only during peacetime","Section 2 excludes members of the naval, military, air and other armed forces of the Union from the Act's application.",A],

["POL-026-QL-020","Hard","Which case restored the constitutional position that tribunal decisions remain subject to High Court scrutiny?","L. Chandra Kumar v. Union of India","Kesavananda Bharati v. State of Kerala","S. R. Bommai v. Union of India","Minerva Mills v. Union of India","L. Chandra Kumar is the leading tribunal case establishing that constitutional judicial review by High Courts cannot be excluded from tribunal decisions.",S],
["POL-026-QL-020","Hard","After L. Chandra Kumar, tribunal decisions remain subject to High Court jurisdiction under:","Articles 226 and 227","Article 123 only","Article 280 only","Article 360 only","The Supreme Court has reiterated that tribunal decisions are subject to High Court writ and supervisory jurisdiction under Articles 226 and 227.",S],
["POL-026-QL-020","Hard","In L. Chandra Kumar, judicial review by constitutional courts was treated as part of:","The basic structure of the Constitution","The pleasure doctrine","The Eighth Schedule","The electoral-roll system","L. Chandra Kumar treated constitutional judicial review as an integral feature of the basic structure, preventing tribunal arrangements from fully excluding constitutional-court scrutiny.",S],
["POL-026-QL-020","Hard","Can an administrative tribunal's decision be completely insulated from High Court judicial review under Article 323A?","No","Yes, in every service matter","Yes, if the tribunal has contempt power","Only State tribunals are immune","The present constitutional position after L. Chandra Kumar is that tribunal decisions remain open to High Court scrutiny under Articles 226 and 227.",S],
];
