import type { PolCp026SeedRow } from "./pol-cp026-types";

const C=["CONSTITUTION-SERVICES-2025"] as const;

export const POL_CP026_PART_2: readonly PolCp026SeedRow[] = [
["POL-026-QL-006","Easy","An Article 311 inquiry may be skipped after conduct leading to:","Conviction on a criminal charge","A routine transfer order","A delayed promotion","A leave application","Article 311(2) expressly permits the ordinary inquiry safeguard to be skipped when the disciplinary action is based on conduct that led to criminal conviction.",C],
["POL-026-QL-006","Easy","Can the inquiry be dispensed with when holding it is not reasonably practicable?","Yes, with the required written satisfaction","No, never","Only with Parliament's approval","Only after retirement","Article 311 allows the empowered authority to dispense with the inquiry when it is not reasonably practicable, and the reason must be recorded in writing.",C],
["POL-026-QL-006","Easy","The security-of-State exception under Article 311 depends on satisfaction of the:","President or Governor, as applicable","Election Commission","Public Service Commission","Speaker of the Legislature","Article 311 permits the inquiry to be omitted when the President or Governor is satisfied that holding it is not expedient in the interest of State security.",C],
["POL-026-QL-006","Easy","Which is NOT one of the three constitutional exceptions to the ordinary Article 311 inquiry?","Administrative inconvenience alone","Criminal conviction","Inquiry not reasonably practicable","Security of the State","Article 311 lists criminal conviction, impracticability of inquiry and State-security grounds; ordinary administrative inconvenience by itself is not one of these exceptions.",C],

["POL-026-QL-007","Medium","A new All-India Service under Article 312 requires a prior resolution of the:","Rajya Sabha","Lok Sabha","Supreme Court","Inter-State Council","Article 312 first requires the Council of States to adopt the specified national-interest resolution before Parliament may create a new All-India Service by law.",C],
["POL-026-QL-007","Medium","Which majority is required in Rajya Sabha for an Article 312 resolution?","Not less than two-thirds of members present and voting","Simple majority of total membership","Two-thirds of total membership","Three-fourths of members present","Article 312 requires not less than two-thirds of Rajya Sabha members present and voting, rather than two-thirds of the total membership.",C],
["POL-026-QL-007","Medium","The Rajya Sabha resolution under Article 312 must declare creation of the service necessary or expedient in:","The national interest","A State election","A financial emergency","A judicial reference","The constitutional trigger is a Rajya Sabha resolution declaring that creation of one or more All-India Services is necessary or expedient in the national interest.",C],
["POL-026-QL-007","Medium","After the required Rajya Sabha resolution, can Parliament create an All-India Service by law?","Yes","No, a constitutional amendment is always required","Only after every State ratifies it","Only by presidential ordinance","Once the Article 312 resolution is passed with the required majority, Parliament may provide by law for an All-India Service common to Union and States.",C],

["POL-026-QL-008","Medium","The Constitution deems these two services to have been created under Article 312:","Indian Administrative Service and Indian Police Service","Indian Revenue Service and Indian Forest Service","Indian Foreign Service and Indian Police Service","Indian Audit Service and Indian Administrative Service","Article 312(2) specifically deems the Indian Administrative Service and Indian Police Service existing at commencement to be services created under that Article.",C],
["POL-026-QL-008","Medium","Does Article 312 expressly permit creation of an All-India Judicial Service?","Yes","No","Only during Emergency","Only through a referendum","The current text of Article 312 expressly includes an All-India Judicial Service among the All-India Services Parliament may create after the required Rajya Sabha resolution.",C],
["POL-026-QL-008","Medium","An All-India Service created under Article 312 is common to:","The Union and the States","Only the Union","Only participating municipal bodies","Only High Courts","Article 312 describes All-India Services as services common to the Union and the States, distinguishing them from services confined to one government.",C],
["POL-026-QL-008","Medium","Which amendment added the express reference to an All-India Judicial Service in Article 312?","Forty-second Amendment","Twenty-eighth Amendment","Forty-fourth Amendment","Seventy-fifth Amendment","The Constitution (Forty-second Amendment) Act, 1976 inserted the express reference to an All-India Judicial Service in Article 312.",C],

["POL-026-QL-009","Medium","An All-India Judicial Service cannot include a post inferior to:","District judge","High Court judge","Civil judge junior division","Chief Judicial Magistrate","Article 312(3) sets the constitutional floor at district judge, as defined in Article 236, for posts included in an All-India Judicial Service.",C],
["POL-026-QL-009","Medium","Which Article supplies the definition of district judge referenced by Article 312?","Article 236","Article 214","Article 233","Article 217","Article 312(3) expressly links its district-judge threshold to the definition in Article 236 of the Constitution.",C],
["POL-026-QL-009","Medium","A law creating an All-India Judicial Service may make necessary changes to:","Chapter VI of Part VI","Part XVII on official language","Part IX on Panchayats","Part XV on elections","Article 312(4) permits the creating law to include necessary changes to Chapter VI of Part VI so the All-India Judicial Service framework can operate.",C],
["POL-026-QL-009","Medium","Is such a law treated as a constitutional amendment under Article 368 merely because it adjusts Chapter VI of Part VI?","No","Yes, always","Only if Rajya Sabha agrees unanimously","Only if half the States ratify it","Article 312(4) expressly says a law making necessary Chapter VI adjustments for the All-India Judicial Service is not deemed an Article 368 amendment.",C],

["POL-026-QL-010","Medium","Article 312A mainly concerns service conditions of certain officers originally appointed by the:","Secretary of State or Secretary of State in Council","Election Commission","Supreme Court","Union Public Service Commission","Article 312A addresses specified service rights of officers appointed to Crown civil services before the Constitution by the Secretary of State or Secretary of State in Council.",C],
["POL-026-QL-010","Medium","Which amendment inserted Article 312A?","Twenty-eighth Amendment","Forty-second Amendment","Fifteenth Amendment","Seventh Amendment","Article 312A was inserted by the Constitution (Twenty-eighth Amendment) Act, 1972 as part of changes affecting certain pre-Constitution service protections.",C],
["POL-026-QL-010","Medium","Parliament's power under Article 312A may operate:","Prospectively or retrospectively","Prospectively only","Retrospectively only","Only during a Financial Emergency","Article 312A expressly permits Parliament, within its defined scope, to vary or revoke specified service conditions either prospectively or retrospectively.",C],
["POL-026-QL-010","Medium","Can Article 312A cover remuneration, leave, pension and disciplinary rights within its defined class?","Yes","No, pension only","No, leave only","Only judicial salaries","The Article expressly identifies remuneration, leave, pension and disciplinary rights among the service conditions Parliament may vary or revoke for the covered class.",C],
];
