import type { PolCp026SeedRow } from "./pol-cp026-types";

const C=["CONSTITUTION-SERVICES-2025"] as const;
const T=["CONSTITUTION-TRIBUNALS-2025"] as const;

export const POL_CP026_PART_3: readonly PolCp026SeedRow[] = [
["POL-026-QL-011","Medium","Article 313 continues pre-Constitution service laws that are:","Consistent with the Constitution","Approved by the Supreme Court individually","Limited to defence services","Passed again every year","Article 313 continues existing service laws after commencement only so far as they remain consistent with the Constitution and until other constitutional provision is made.",C],
["POL-026-QL-011","Medium","Did all pre-Constitution public-service laws automatically lapse when the Constitution commenced?","No","Yes","Only State laws survive","Only Union laws survive","Article 313 provides continuity for applicable pre-Constitution service laws, subject to constitutional consistency and later replacement under the Constitution.",C],
["POL-026-QL-011","Medium","The transitional provision continuing existing service laws is:","Article 313","Article 309","Article 312A","Article 323A","Article 313 is the transitional provision that keeps applicable pre-Constitution service laws in force until replaced, provided they are consistent with the Constitution.",C],
["POL-026-QL-011","Medium","How long may an existing service law continue under Article 313?","Until other provision is made, subject to constitutional consistency","Exactly five years","Until the first general election","Only until Parliament first meets","Article 313 does not prescribe a fixed number of years; continuity lasts until other provision is made, while constitutional inconsistency cannot be preserved.",C],

["POL-026-QL-012","Medium","In the present Constitution, Article 314 is:","Omitted","A provision on All-India Services","A provision on tribunals","A Public Service Commission article","The original Article 314 protected certain existing service officers, but the provision was omitted by the Constitution (Twenty-eighth Amendment) Act, 1972.",C],
["POL-026-QL-012","Medium","Article 314 was omitted by the:","Twenty-eighth Amendment","Forty-second Amendment","Forty-fourth Amendment","Seventh Amendment","The Twenty-eighth Amendment of 1972 omitted Article 314 and also inserted Article 312A dealing with specified pre-Constitution service conditions.",C],
["POL-026-QL-012","Medium","The Twenty-eighth Amendment changed the services provisions by:","Article 312A and omission of Article 314","Creation of Article 323A only","Insertion of Article 311","Creation of UPSC","In the service chapter, the Twenty-eighth Amendment inserted Article 312A and omitted Article 314, reshaping protections connected with certain pre-Constitution officers.",C],
["POL-026-QL-012","Medium","Does Article 314 currently provide an operative service safeguard?","No","Yes, for IAS officers","Yes, for judges only","Yes, during Emergency","Article 314 is shown as omitted in the current constitutional text, so it no longer supplies an operative service-protection rule.",C],

["POL-026-QL-013","Medium","Articles 309–314 are located in:","Part XIV, Chapter I","Part XIVA","Part XV","Part XVII","Articles 309–314 sit in Part XIV, Chapter I, titled Services, while Articles 315–323 form the separate Public Service Commissions chapter.",C],
["POL-026-QL-013","Medium","Which constitutional block follows the Services chapter in Part XIV?","Public Service Commissions under Articles 315–323","Fundamental Duties","Emergency Provisions","Official Language","Part XIV places Chapter II on Public Service Commissions immediately after the service provisions ending with Article 314.",C],
["POL-026-QL-013","Medium","Which Article begins the constitutional provisions on Public Service Commissions?","Article 315","Article 309","Article 323A","Article 324","Article 315 begins Chapter II of Part XIV, which contains the constitutional provisions relating to Union and State Public Service Commissions.",C],
["POL-026-QL-013","Medium","Article 315 begins the constitutional provisions relating to:","Public Service Commissions","Elections","Tribunals","Official language","After the services chapter closes at Article 314, Article 315 begins Chapter II of Part XIV dealing with Public Service Commissions.",C],

["POL-026-QL-014","Medium","Part XIVA of the Constitution deals with:","Tribunals","Services","Elections","Finance","Part XIVA is the constitutional part devoted to tribunals and contains Articles 323A and 323B.",T],
["POL-026-QL-014","Medium","Part XIVA was inserted by the:","Forty-second Amendment","Twenty-eighth Amendment","Forty-fourth Amendment","Seventy-fifth Amendment","The Constitution (Forty-second Amendment) Act, 1976 inserted Part XIVA and Articles 323A and 323B, effective in 1977.",T],
["POL-026-QL-014","Medium","How many Articles are contained in Part XIVA?","Two: 323A and 323B","One: 323A only","Three: 323A to 323C","Nine: 315 to 323","The tribunal part is compact: Article 323A covers administrative tribunals and Article 323B covers tribunals for specified other matters.",T],
["POL-026-QL-014","Medium","Is Article 323A part of the Public Service Commission chapter in Part XIV?","No","Yes","Only after an amendment","Only for State tribunals","Article 323A is in the separate Part XIVA on Tribunals, not in Part XIV Chapter II on Public Service Commissions.",T],

["POL-026-QL-015","Medium","Article 323A mainly covers disputes relating to:","Recruitment and conditions of service in public services and posts","Election symbols","Inter-State river water only","Municipal taxation only","Article 323A authorises administrative tribunals for disputes and complaints concerning recruitment and service conditions in specified public services and posts.",T],
["POL-026-QL-015","Medium","A law establishing administrative tribunals under Article 323A may be made by:","Parliament","Any municipal council","State Legislature alone","District Council alone","Article 323A specifically gives Parliament power to provide by law for administrative tribunals dealing with the covered service disputes.",T],
["POL-026-QL-015","Medium","Can Article 323A cover service disputes involving government-controlled authorities or corporations?","Yes","No","Only if they are courts","Only during Emergency","The Article extends beyond conventional Union and State departments to specified local or other authorities and government-owned or government-controlled corporations.",T],
["POL-026-QL-015","Medium","The main subject of Article 323A is:","Administrative tribunals for service matters","Tax tribunals for all taxes","Election tribunals only","Land reform tribunals only","Article 323A is the service-matters tribunal provision; Article 323B separately lists a wider group of subject areas for other tribunals.",T],
];
