import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import categoriesRouter from "./categories";
import subcategoriesRouter from "./subcategories";
import testsRouter from "./tests";
import learningResourcesRouter from "./learning-resources";
import adminLearningResourcesRouter from "./admin-learning-resources";
import adminLearningResourceEditorRouter from "./admin-learning-resource-editor";
import adminNotesStudioJobListRouter from "./admin-notes-studio-job-list";
import adminNotesStudioRouter from "./admin-notes-studio";
import adminNotesStudioBriefEditorRouter from "./admin-notes-studio-brief-editor";
import adminNotesStudioSourcePolicyRouter from "./admin-notes-studio-source-policy";
import adminNotesStudioSourceCoverageRouter from "./admin-notes-studio-source-coverage";
import adminNotesStudioSourcePackProposalsRouter from "./admin-notes-studio-source-pack-proposals";
import adminNotesStudioEvidenceRouter from "./admin-notes-studio-evidence";
import adminNotesStudioSectionsRouter from "./admin-notes-studio-sections";
import adminNotesStudioQualityRouter from "./admin-notes-studio-quality";
import adminNotesStudioApprovalRouter from "./admin-notes-studio-approval";
import adminNotesStudioReleaseRouter from "./admin-notes-studio-release";
import adminNotesStudioOperationsRouter from "./admin-notes-studio-operations";
import adminNotesStudioPlanningRouter from "./admin-notes-studio-planning";
import adminNotesStudioSourceLibraryRouter from "./admin-notes-studio-source-library";
import adminAuditEventsHardeningRouter from "./admin-audit-events-hardening";
import adminAccessControlHardeningRouter from "./admin-access-control-hardening";
import adminAccessControlRouter from "./admin-access-control";
import adminAttemptExportsRouter from "./admin-attempt-exports";
import adminAttemptInvestigationsRouter from "./admin-attempt-investigations";
import adminAttemptIntegrityRouter from "./admin-attempt-integrity";
import adminAttemptsRouter from "./admin-attempts";
import adminBusinessAnalyticsRouter from "./admin-business-analytics";
import adminContentQualityRouter from "./admin-content-quality";
import adminExamConfigurationRouter from "./admin-exam-configuration";
import adminCommerceCouponsRouter from "./admin-commerce-coupons";
import adminCommerceEntitlementsRouter from "./admin-commerce-entitlements";
import adminCommerceOrdersRouter from "./admin-commerce-orders";
import adminCommerceProductsRouter from "./admin-commerce-products";
import adminQuestionAnalyticsQualityRouter from "./admin-question-analytics-quality";
import adminQuestionAnalyticsDetailRouter from "./admin-question-analytics-detail";
import adminQuestionAnalyticsRouter from "./admin-question-analytics";
import adminTestAnalyticsQualityRouter from "./admin-test-analytics-quality";
import adminTestAnalyticsRouter from "./admin-test-analytics";
import adminContentIntelligenceRouter from "./admin-content-intelligence";
import adminContentReviewRouter from "./admin-content-review";
import adminQuestionStudioRegistryRouter from "./admin-question-studio-registry";
import adminQuestionBulkWorkflowRouter from "./admin-question-bulk-workflow";
import adminQuestionLifecycleHardeningRouter from "./admin-question-lifecycle-hardening";
import adminQuestionTaxonomyHardeningRouter from "./admin-question-taxonomy-hardening";
import adminQuestionsRouter from "./admin-questions";
import adminStudentDirectoryResilientRouter from "./admin-student-directory-resilient";
import adminStudentDirectoryHardeningRouter from "./admin-student-directory-hardening";
import adminStudentFirebaseSyncRouter from "./admin-student-firebase-sync";
import adminStudentProfileManagementRouter from "./admin-student-profile-management";
import adminStudentAccountRecoveryRouter from "./admin-student-account-recovery";
import adminStudentRecoveryRequestsRouter from "./admin-student-recovery-requests";
import adminStudentLifecycleConsistencyRouter from "./admin-student-lifecycle-consistency";
import adminStudentOperationsRouter from "./admin-student-operations";
import adminStudentDisableActionsRouter from "./admin-student-disable-actions";
import adminStudentActionsRouter from "./admin-student-actions";
import adminStudentsRouter from "./admin-students";
import adminRequestFailuresRouter from "./admin-request-failures";
import adminSystemHealthActionsRouter from "./admin-system-health-actions";
import adminSystemHealthRedactionRouter from "./admin-system-health-redaction";
import adminSystemHealthRouter from "./admin-system-health";
import adminTaxonomyCoverageRouter from "./admin-taxonomy-coverage";
import adminTaxonomyRouter from "./admin-taxonomy";
import adminTestBlueprintAssemblyRouter from "./admin-test-blueprint-assembly";
import adminTestBlueprintsRouter from "./admin-test-blueprints";
import adminTestBulkWorkflowRouter from "./admin-test-bulk-workflow";
import adminTestLocalizationGateRouter from "./admin-test-localization-gate";
import adminTestSeriesRouter from "./admin-test-series";
import adminTestQaGateRouter from "./admin-test-qa-gate";
import adminTestQaRouter from "./admin-test-qa";
import adminTestTranslationsRouter from "./admin-test-translations";
import adminTestsRouter from "./admin-tests";
import adminTranslationActionsRouter from "./admin-translation-actions";
import adminTranslationHardeningRouter from "./admin-translation-hardening";
import adminTranslationsRouter from "./admin-translations";
import canonicalCommerceAccessGuardRouter from "./canonical-commerce-access-guard";
import canonicalCommerceCheckoutRouter from "./canonical-commerce-checkout";
import canonicalCommercePurchasesRouter from "./canonical-commerce-purchases";
import publishedTestsRouter from "./published-tests";
import publishedTestMultilingualRunnerRouter from "./published-test-multilingual-runner";
import publishedTestRunnerRouter from "./published-test-runner";
import attemptReliabilityRouter from "./attempt-reliability";
import canonicalAttemptResultsRouter from "./canonical-attempt-results";
import canonicalStudentReadRouter from "./canonical-student-read";
import studentAccountDeletionRouter from "./student-account-deletion";
import studentAccountRecoveryRouter from "./student-account-recovery";
import studentExamPreferencesRouter from "./student-exam-preferences";
import studentTestSeriesRouter from "./student-test-series";
import adminSessionRouter from "./admin-session";
import retiredLegacyRouter from "./retired-legacy";

const router: IRouter = Router();
router.use(healthRouter);
router.use("/account-recovery", studentAccountRecoveryRouter);
router.use("/users", studentAccountDeletionRouter);
router.use("/users", studentExamPreferencesRouter);
router.use("/users", usersRouter);
router.use("/categories", categoriesRouter);
router.use("/subcategories", subcategoriesRouter);
router.use("/tests", testsRouter);
router.use(learningResourcesRouter);
router.use(canonicalCommerceCheckoutRouter);
router.use(canonicalCommercePurchasesRouter);
router.use(canonicalCommerceAccessGuardRouter);
router.use(studentTestSeriesRouter);
router.use(attemptReliabilityRouter);
router.use(canonicalAttemptResultsRouter);
router.use(canonicalStudentReadRouter);
router.use(publishedTestMultilingualRunnerRouter);
router.use(publishedTestRunnerRouter);
router.use("/published-tests", publishedTestsRouter);
router.use("/admin/session", adminSessionRouter);
router.use("/admin/learning-resources", adminLearningResourcesRouter);
router.use("/admin/learning-resource-editor", adminLearningResourceEditorRouter);
router.use("/admin/notes-studio", adminNotesStudioJobListRouter);
router.use("/admin/notes-studio", adminNotesStudioRouter);
router.use("/admin/notes-studio", adminNotesStudioBriefEditorRouter);
router.use("/admin/notes-studio", adminNotesStudioSourcePolicyRouter);
router.use("/admin/notes-studio", adminNotesStudioSourceCoverageRouter);
router.use("/admin/notes-studio", adminNotesStudioSourcePackProposalsRouter);
router.use("/admin/notes-studio", adminNotesStudioEvidenceRouter);
router.use("/admin/notes-studio", adminNotesStudioSectionsRouter);
router.use("/admin/notes-studio", adminNotesStudioQualityRouter);
router.use("/admin/notes-studio", adminNotesStudioApprovalRouter);
router.use("/admin/notes-studio", adminNotesStudioReleaseRouter);
router.use("/admin/notes-studio", adminNotesStudioOperationsRouter);
router.use("/admin/notes-studio", adminNotesStudioPlanningRouter);
router.use("/admin/notes-studio", adminNotesStudioSourceLibraryRouter);
router.use("/admin/access-control", adminAuditEventsHardeningRouter);
router.use("/admin/access-control", adminAccessControlHardeningRouter);
router.use("/admin/access-control", adminAccessControlRouter);
router.use("/admin/analytics", adminBusinessAnalyticsRouter);
router.use("/admin/analytics", adminContentQualityRouter);
router.use("/admin/analytics", adminQuestionAnalyticsQualityRouter);
router.use("/admin/analytics", adminQuestionAnalyticsDetailRouter);
router.use("/admin/analytics", adminQuestionAnalyticsRouter);
router.use("/admin/analytics", adminTestAnalyticsQualityRouter);
router.use("/admin/analytics", adminTestAnalyticsRouter);
router.use("/admin/commerce/coupons", adminCommerceCouponsRouter);
router.use("/admin/commerce/entitlements", adminCommerceEntitlementsRouter);
router.use("/admin/commerce/orders", adminCommerceOrdersRouter);
router.use("/admin/commerce/products", adminCommerceProductsRouter);
router.use("/admin/attempts", adminAttemptExportsRouter);
router.use("/admin/attempts", adminAttemptInvestigationsRouter);
router.use("/admin/attempts", adminAttemptIntegrityRouter);
router.use("/admin/attempts", adminAttemptsRouter);
router.use("/admin/students", adminStudentDirectoryResilientRouter);
router.use("/admin/students", adminStudentDirectoryHardeningRouter);
router.use("/admin/students", adminStudentFirebaseSyncRouter);
router.use("/admin/students", adminStudentProfileManagementRouter);
router.use("/admin/students", adminStudentAccountRecoveryRouter);
router.use("/admin/students", adminStudentRecoveryRequestsRouter);
router.use("/admin/students", adminStudentLifecycleConsistencyRouter);
router.use("/admin/students", adminStudentOperationsRouter);
router.use("/admin/students", adminStudentDisableActionsRouter);
router.use("/admin/students", adminStudentActionsRouter);
router.use("/admin/students", adminStudentsRouter);
router.use("/admin/content-review", adminContentIntelligenceRouter);
router.use("/admin/content-review", adminContentReviewRouter);
router.use("/admin/question-studio", adminQuestionStudioRegistryRouter);
router.use("/admin/questions", adminQuestionBulkWorkflowRouter);
router.use("/admin/questions", adminQuestionLifecycleHardeningRouter);
router.use("/admin/questions", adminQuestionTaxonomyHardeningRouter);
router.use("/admin/questions", adminQuestionsRouter);
router.use("/admin/translations", adminTranslationHardeningRouter);
router.use("/admin/translations", adminTranslationActionsRouter);
router.use("/admin/translations", adminTestTranslationsRouter);
router.use("/admin/translations", adminTranslationsRouter);
router.use("/admin/system-health", adminRequestFailuresRouter);
router.use("/admin/system-health", adminSystemHealthRedactionRouter);
router.use("/admin/system-health", adminSystemHealthActionsRouter);
router.use("/admin/system-health", adminSystemHealthRouter);
router.use("/admin/taxonomy", adminTaxonomyCoverageRouter);
router.use("/admin/taxonomy", adminTaxonomyRouter);
router.use("/admin/exam-configuration", adminExamConfigurationRouter);
router.use("/admin/test-blueprints", adminTestBlueprintAssemblyRouter);
router.use("/admin/test-blueprints", adminTestBlueprintsRouter);
router.use("/admin/test-series", adminTestSeriesRouter);
router.use("/admin/test-qa", adminTestQaRouter);
router.use("/admin/tests", adminTestBulkWorkflowRouter);
router.use("/admin/tests", adminTestLocalizationGateRouter);
router.use("/admin/tests", adminTestQaGateRouter);
router.use("/admin/tests", adminTestsRouter);
router.use(retiredLegacyRouter);
export default router;
