export const PGK_001_CP026_SOURCE_IDS = Object.freeze({
  amritsar: "NIC-DISTRICT-AMRITSAR",
  tarnTaran: "NIC-DISTRICT-TARN-TARAN",
  gurdaspur: "NIC-DISTRICT-GURDASPUR",
  pathankot: "NIC-DISTRICT-PATHANKOT",
  jalandhar: "NIC-DISTRICT-JALANDHAR",
  kapurthala: "NIC-DISTRICT-KAPURTHALA",
  hoshiarpur: "NIC-DISTRICT-HOSHIARPUR",
  sbsNagar: "NIC-DISTRICT-SBS-NAGAR",
  ludhiana: "NIC-DISTRICT-LUDHIANA",
  moga: "NIC-DISTRICT-MOGA",
  barnala: "NIC-DISTRICT-BARNALA",
  sangrur: "NIC-DISTRICT-SANGRUR",
  malerkotla: "NIC-DISTRICT-MALERKOTLA",
  patiala: "NIC-DISTRICT-PATIALA",
  fatehgarh: "NIC-DISTRICT-FATEHGARH-SAHIB",
  sasNagar: "NIC-DISTRICT-SAS-NAGAR",
  rupnagar: "NIC-DISTRICT-RUPNAGAR",
  bathinda: "NIC-DISTRICT-BATHINDA",
  mansa: "NIC-DISTRICT-MANSA",
  faridkot: "NIC-DISTRICT-FARIDKOT",
  ferozepur: "NIC-DISTRICT-FEROZEPUR",
  fazilka: "NIC-DISTRICT-FAZILKA",
  muktsar: "NIC-DISTRICT-SRI-MUKTSAR-SAHIB",
  harikeMoef: "MOEFCC-HARIKE-WILDLIFE-SANCTUARY",
  scienceCity: "PUSHPA-GUJRAL-SCIENCE-CITY-OFFICIAL",
  pau: "PUNJAB-AGRICULTURAL-UNIVERSITY-OFFICIAL",
  iiserMohali: "IISER-MOHALI-OFFICIAL",
  nisPatiala: "SAI-NETAJI-SUBHAS-NIS-PATIALA",
  industrialPolicy: "GOV-PUNJAB-INDUSTRIAL-POLICY",
} as const);

export const PGK_001_CP026_FACTS = Object.freeze([
  { id: "amritsar-harmandir-jallianwala", district: "Amritsar", value: "Sri Harmandir Sahib and Jallianwala Bagh are in Amritsar.", sourceIds: [PGK_001_CP026_SOURCE_IDS.amritsar] },
  { id: "tarn-taran-goindwal", district: "Tarn Taran", value: "Goindwal Sahib is in Tarn Taran district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.tarnTaran] },
  { id: "harike-confluence-multidistrict", value: "Harike Wetland lies at the Beas-Sutlej confluence and the sanctuary extends across Tarn Taran, Ferozepur and Kapurthala districts.", sourceIds: [PGK_001_CP026_SOURCE_IDS.harikeMoef] },
  { id: "gurdaspur-kalanaur", district: "Gurdaspur", value: "Kalanaur is in Gurdaspur district and is connected with Akbar's installation in 1556.", sourceIds: [PGK_001_CP026_SOURCE_IDS.gurdaspur] },
  { id: "gurdaspur-dera-baba-nanak", district: "Gurdaspur", value: "Dera Baba Nanak is in Gurdaspur district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.gurdaspur] },
  { id: "pathankot-ranjit-sagar", district: "Pathankot", value: "Ranjit Sagar Dam at Shahpurkandi is in Pathankot district on the Ravi.", sourceIds: [PGK_001_CP026_SOURCE_IDS.pathankot] },

  { id: "jalandhar-sports-goods", district: "Jalandhar", value: "Jalandhar is a major sports-goods manufacturing centre.", sourceIds: [PGK_001_CP026_SOURCE_IDS.jalandhar, PGK_001_CP026_SOURCE_IDS.industrialPolicy] },
  { id: "kapurthala-science-city", district: "Kapurthala", value: "Pushpa Gujral Science City is in Kapurthala district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.kapurthala, PGK_001_CP026_SOURCE_IDS.scienceCity] },
  { id: "kapurthala-sultanpur-jagatjit", district: "Kapurthala", value: "Sultanpur Lodhi and Jagatjit Palace are in Kapurthala district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.kapurthala] },
  { id: "hoshiarpur-wood-inlay", district: "Hoshiarpur", value: "Hoshiarpur is a major centre of decorative wood inlay work.", sourceIds: [PGK_001_CP026_SOURCE_IDS.hoshiarpur] },
  { id: "sbs-khatkar-kalan", district: "Shaheed Bhagat Singh Nagar", value: "Khatkar Kalan is in Shaheed Bhagat Singh Nagar district and is the ancestral village of Shaheed Bhagat Singh.", sourceIds: [PGK_001_CP026_SOURCE_IDS.sbsNagar] },

  { id: "ludhiana-pau-bicycles", district: "Ludhiana", value: "Punjab Agricultural University is in Ludhiana, which is also a major bicycle-manufacturing centre.", sourceIds: [PGK_001_CP026_SOURCE_IDS.ludhiana, PGK_001_CP026_SOURCE_IDS.pau, PGK_001_CP026_SOURCE_IDS.industrialPolicy] },
  { id: "moga-food-processing", district: "Moga", value: "Moga has a major Nestle food-processing plant.", sourceIds: [PGK_001_CP026_SOURCE_IDS.moga] },
  { id: "barnala-textile-combine", district: "Barnala", value: "Barnala has prominent textile, towel and combine-manufacturing industries.", sourceIds: [PGK_001_CP026_SOURCE_IDS.barnala] },
  { id: "sangrur-sunam", district: "Sangrur", value: "Sunam, birthplace of Shaheed Udham Singh, is in Sangrur district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.sangrur] },
  { id: "malerkotla-princely", district: "Malerkotla", value: "Malerkotla district takes its name from the former princely state of Maler Kotla and was created from Sangrur district in 2021.", sourceIds: [PGK_001_CP026_SOURCE_IDS.malerkotla] },

  { id: "patiala-nis-qila", district: "Patiala", value: "Netaji Subhas National Institute of Sports and Qila Mubarak are in Patiala.", sourceIds: [PGK_001_CP026_SOURCE_IDS.patiala, PGK_001_CP026_SOURCE_IDS.nisPatiala] },
  { id: "patiala-old-moti-bagh", district: "Patiala", value: "Netaji Subhas National Institute of Sports operates from the Old Moti Bagh Palace complex in Patiala.", sourceIds: [PGK_001_CP026_SOURCE_IDS.nisPatiala, PGK_001_CP026_SOURCE_IDS.patiala] },
  { id: "fatehgarh-mandi-gobindgarh", district: "Fatehgarh Sahib", value: "Mandi Gobindgarh, a major steel-rolling centre, is in Fatehgarh Sahib district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.fatehgarh, PGK_001_CP026_SOURCE_IDS.industrialPolicy] },
  { id: "sas-iiser", district: "S.A.S. Nagar", value: "IISER Mohali is in Sahibzada Ajit Singh Nagar district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.sasNagar, PGK_001_CP026_SOURCE_IDS.iiserMohali] },
  { id: "rupnagar-harappan", district: "Rupnagar", value: "The Ropar archaeological site is in Rupnagar district and was the first Harappan site excavated in independent India.", sourceIds: [PGK_001_CP026_SOURCE_IDS.rupnagar] },

  { id: "bathinda-qila-damdama", district: "Bathinda", value: "Qila Mubarak and Takht Sri Damdama Sahib at Talwandi Sabo are in Bathinda district.", sourceIds: [PGK_001_CP026_SOURCE_IDS.bathinda] },
  { id: "mansa-cotton", district: "Mansa", value: "Mansa lies in Punjab's cotton belt and is described by the district administration as an area of white gold.", sourceIds: [PGK_001_CP026_SOURCE_IDS.mansa] },
  { id: "faridkot-baba-farid", district: "Faridkot", value: "Faridkot's name tradition is connected with Baba Farid.", sourceIds: [PGK_001_CP026_SOURCE_IDS.faridkot] },
  { id: "ferozepur-hussainiwala", district: "Ferozepur", value: "The National Martyrs Memorial at Hussainiwala is in Ferozepur district and commemorates Bhagat Singh, Rajguru and Sukhdev.", sourceIds: [PGK_001_CP026_SOURCE_IDS.ferozepur] },
  { id: "fazilka-abohar", district: "Fazilka", value: "Abohar Wildlife Sanctuary is in Fazilka district and is noted for blackbuck conservation across Bishnoi-community farmland.", sourceIds: [PGK_001_CP026_SOURCE_IDS.fazilka] },
  { id: "muktsar-chali-mukte", district: "Sri Muktsar Sahib", value: "Sri Muktsar Sahib is connected with the battle of Khidrana and the Chali Mukte.", sourceIds: [PGK_001_CP026_SOURCE_IDS.muktsar] },
  { id: "muktsar-mukta-minar", district: "Sri Muktsar Sahib", value: "Mukta Minar at Sri Muktsar Sahib commemorates the Chali Mukte.", sourceIds: [PGK_001_CP026_SOURCE_IDS.muktsar] },
] as const);
