export const PGK_001_CP023_FACTS = Object.freeze([
  { id: "bhangra-harvest-dhol", dance: "Bhangra", type: "folk dance", setting: "agrarian and harvest celebration", centralInstrument: "dhol", traditionalPerformance: "primarily male groups" },
  { id: "giddha-women-boliyan", dance: "Giddha", type: "song-and-dance", traditionalPerformance: "women", songElement: "boliyan" },
  { id: "kikli-paired-spin", dance: "Kikli", performers: "girls", movement: "pairs hold hands and spin" },
  { id: "jhumar-style", dance: "Jhumar", type: "Punjabi folk dance", style: "slower and more graceful than energetic Bhangra" },
  { id: "sammi-style", dance: "Sammi", type: "Punjabi folk dance", traditionalPerformance: "women" },
  { id: "luddi-style", dance: "Luddi", type: "Punjabi folk dance", setting: "celebratory performance" },
  { id: "dhol-instrument", instrument: "Dhol", family: "percussion", construction: "double-headed drum", use: "Bhangra and Punjabi folk performance" },
  { id: "dholak-instrument", instrument: "Dholak", family: "percussion", construction: "smaller hand-played drum", use: "folk singing and domestic celebrations" },
  { id: "algoza-instrument", instrument: "Algoza", family: "wind", construction: "paired flutes", use: "Punjabi folk music" },
  { id: "tumbi-instrument", instrument: "Tumbi", aliases: ["Tumba"], family: "string", construction: "single-string plucked folk instrument" },
  { id: "chimta-instrument", instrument: "Chimta", family: "percussion", construction: "metal tong-like instrument with jingles", use: "Punjabi folk performance including Bhangra" },
  { id: "sarangi-instrument", instrument: "Sarangi", family: "bowed string", use: "folk and classical performance" },
  { id: "ghara-instrument", instrument: "Ghara", family: "percussion", construction: "earthen pot", use: "rhythm in Punjabi folk music" },
  { id: "boliyan-form", form: "Boliyan", type: "short folk verses/couplets", use: "commonly sung in Giddha" },
  { id: "tappa-form", form: "Tappa", type: "semi-classical vocal form", style: "fast and ornamented", roots: "folk music of Punjab and Sindh" },
  { id: "phulkari-craft", item: "Phulkari", type: "traditional embroidery", region: "Punjab" },
  { id: "punjabi-jutti", item: "Punjabi jutti", type: "traditional footwear" },
  { id: "men-dress", item: "Punjabi kurta and tehmat", type: "traditional men's dress" },
  { id: "women-dress", item: "Punjabi salwar suit", type: "traditional women's dress" },
  { id: "rural-museum-instruments", instruments: ["Dholak", "Sarangi", "Algoza", "Tumba", "Sitar"], context: "Punjab rural heritage collections" },
] as const);
