type QuantV4Language = "en" | "hi" | "pa";

const HI_LABELS: Record<string, string> = {
  "accounts": "खाते",
  "adult passengers": "वयस्क यात्री",
  "annual turnover": "वार्षिक कारोबार",
  "amount": "राशि",
  "applicants": "आवेदक",
  "asset value": "संपत्ति का मूल्य",
  "assessed value": "आकलित मूल्य",
  "assessment score": "मूल्यांकन अंक",
  "attendance": "उपस्थिति",
  "attendance in school a": "स्कूल A की उपस्थिति",
  "attendance in school b": "स्कूल B की उपस्थिति",
  "active users": "सक्रिय उपयोगकर्ता",
  "admissions": "प्रवेश",
  "bags of cement": "सीमेंट की बोरियां",
  "bill amount": "बिल राशि",
  "bonus fund": "बोनस कोष",
  "boys": "लड़के",
  "branch a sales": "शाखा A की बिक्री",
  "branch a stock": "शाखा A का स्टॉक",
  "branch b sales": "शाखा B की बिक्री",
  "branch b stock": "शाखा B का स्टॉक",
  "budget": "बजट",
  "budget allocation": "बजट आवंटन",
  "budget amount": "बजट राशि",
  "bags": "बोरियां",
  "boxes": "डिब्बे",
  "books": "पुस्तकें",
  "cartons": "कार्टन",
  "cattle population": "पशुधन की संख्या",
  "child passengers": "बाल यात्री",
  "commission income": "कमीशन आय",
  "contract employees": "संविदा कर्मचारी",
  "contract value": "संविदा मूल्य",
  "consumption": "खपत",
  "cost index": "लागत सूचकांक",
  "crates": "पेटियां",
  "crop production": "फसल उत्पादन",
  "crop yield": "फसल उपज",
  "damaged items": "क्षतिग्रस्त वस्तुएँ",
  "day scholars": "डे-स्कॉलर",
  "electricity consumption": "बिजली की खपत",
  "electricity usage": "बिजली का उपयोग",
  "employees": "कर्मचारी",
  "expenditure": "व्यय",
  "expenses": "खर्च",
  "female voters": "महिला मतदाता",
  "female workers": "महिला श्रमिक",
  "fixed deposit": "सावधि जमा",
  "fund a value": "फंड A का मूल्य",
  "fund b value": "फंड B का मूल्य",
  "fund value": "कोष का मूल्य",
  "girls": "लड़कियाँ",
  "good items": "अच्छी वस्तुएँ",
  "good units": "अच्छी इकाइयाँ",
  "hostellers": "छात्रावासी",
  "households": "परिवार",
  "illiterate residents": "अशिक्षित निवासी",
  "income": "आय",
  "index value": "सूचकांक मान",
  "internet users": "इंटरनेट उपयोगकर्ता",
  "inventory": "भंडार",
  "investment": "निवेश",
  "investment value": "निवेश का मूल्य",
  "items": "वस्तुएँ",
  "kg": "किलोग्राम",
  "literate residents": "साक्षर निवासी",
  "litres": "लीटर",
  "machine a value": "मशीन A का मूल्य",
  "machine b value": "मशीन B का मूल्य",
  "machine output": "मशीन का उत्पादन",
  "machine value": "मशीन का मूल्य",
  "male voters": "पुरुष मतदाता",
  "male workers": "पुरुष श्रमिक",
  "market demand": "बाज़ार मांग",
  "market value": "बाज़ार मूल्य",
  "marks": "अंक",
  "milk production": "दूध उत्पादन",
  "mixture": "मिश्रण",
  "monthly income": "मासिक आय",
  "monthly salary": "मासिक वेतन",
  "monthly turnover": "मासिक कारोबार",
  "no responses": "नकारात्मक प्रतिक्रियाएँ",
  "number of internet users": "इंटरनेट उपयोगकर्ताओं की संख्या",
  "number of mobile users": "मोबाइल उपयोगकर्ताओं की संख्या",
  "number of students": "छात्रों की संख्या",
  "number of users": "उपयोगकर्ताओं की संख्या",
  "number of visitors": "आगंतुकों की संख्या",
  "offline respondents": "ऑफलाइन उत्तरदाता",
  "online respondents": "ऑनलाइन उत्तरदाता",
  "output": "उत्पादन",
  "output level": "उत्पादन स्तर",
  "passenger count": "यात्रियों की संख्या",
  "passengers": "यात्री",
  "patients": "मरीज",
  "permanent employees": "स्थायी कर्मचारी",
  "population": "जनसंख्या",
  "people": "लोग",
  "population of town a": "Town A की जनसंख्या",
  "population of town b": "Town B की जनसंख्या",
  "portfolio value": "पोर्टफोलियो का मूल्य",
  "premium amount": "प्रीमियम राशि",
  "premium collection": "प्रीमियम संग्रह",
  "price": "मूल्य",
  "price of product a": "Product A का मूल्य",
  "price of product b": "Product B का मूल्य",
  "product a price": "Product A का मूल्य",
  "product b price": "Product B का मूल्य",
  "production": "उत्पादन",
  "production a": "उत्पादन A",
  "production b": "उत्पादन B",
  "production level": "उत्पादन स्तर",
  "production value": "उत्पादन मूल्य",
  "productivity index": "उत्पादकता सूचकांक",
  "profit": "लाभ",
  "quantity": "मात्रा",
  "quintals": "क्विंटल",
  "rainfall": "वर्षा",
  "rent": "किराया",
  "rent collection": "किराया संग्रह",
  "reams": "रीम",
  "residents": "निवासी",
  "respondents": "उत्तरदाता",
  "revenue": "राजस्व",
  "route a passengers": "Route A के यात्री",
  "route b passengers": "Route B के यात्री",
  "rural workers": "ग्रामीण श्रमिक",
  "salary": "वेतन",
  "salary a": "वेतन A",
  "salary b": "वेतन B",
  "sales": "बिक्री",
  "sales figure": "बिक्री का आंकड़ा",
  "sales target": "बिक्री लक्ष्य",
  "school a's attendance": "स्कूल A की उपस्थिति",
  "school b's attendance": "स्कूल B की उपस्थिति",
  "seating capacity": "बैठने की क्षमता",
  "section a attendance": "अनुभाग A की उपस्थिति",
  "section b attendance": "अनुभाग B की उपस्थिति",
  "shop a revenue": "दुकान A का राजस्व",
  "shop b revenue": "दुकान B का राजस्व",
  "skilled workers": "कुशल श्रमिक",
  "solution": "विलयन",
  "stock": "स्टॉक",
  "stock in branch a": "शाखा A का स्टॉक",
  "stock in branch b": "शाखा B का स्टॉक",
  "store a sales": "स्टोर A की बिक्री",
  "store a turnover": "स्टोर A का कारोबार",
  "store b sales": "स्टोर B की बिक्री",
  "store b turnover": "स्टोर B का कारोबार",
  "student passengers": "छात्र यात्री",
  "students": "छात्र",
  "subscriber count": "सदस्य संख्या",
  "strength": "संख्या",
  "supply": "आपूर्ति",
  "tax collection": "कर संग्रह",
  "town a population": "Town A की जनसंख्या",
  "town b population": "Town B की जनसंख्या",
  "traffic volume": "यातायात मात्रा",
  "trained employees": "प्रशिक्षित कर्मचारी",
  "turnout": "मतदान प्रतिशत",
  "turnover": "कारोबार",
  "unit a output": "इकाई A का उत्पादन",
  "unit b output": "इकाई B का उत्पादन",
  "units": "इकाइयाँ",
  "unskilled workers": "अकुशल श्रमिक",
  "untrained employees": "अप्रशिक्षित कर्मचारी",
  "urban workers": "शहरी श्रमिक",
  "usage": "उपयोग",
  "usage index": "उपयोग सूचकांक",
  "value": "मान",
  "voter turnout": "मतदाता उपस्थिति",
  "voters": "मतदाता",
  "votes": "मत",
  "warehouse a stock": "Warehouse A का स्टॉक",
  "warehouse b stock": "Warehouse B का स्टॉक",
  "wildlife population": "वन्यजीव जनसंख्या",
  "workers": "श्रमिक",
  "yes responses": "सकारात्मक प्रतिक्रियाएँ",
};

const PA_LABELS: Record<string, string> = {
  "accounts": "ਖਾਤੇ",
  "active users": "ਸਕ੍ਰਿਯ ਵਰਤੋਂਕਾਰ",
  "adult passengers": "ਵਯਸਕ ਯਾਤਰੀ",
  "annual turnover": "ਸਾਲਾਨਾ ਟਰਨਓਵਰ",
  "amount": "ਰਕਮ",
  "applicants": "ਅਰਜ਼ੀਕਾਰ",
  "asset value": "ਸੰਪਤੀ ਦਾ ਮੁੱਲ",
  "assessed value": "ਅੰਕਿਤ ਮੁੱਲ",
  "assessment score": "ਮੁਲਾਂਕਣ ਅੰਕ",
  "attendance": "ਹਾਜ਼ਰੀ",
  "attendance in school a": "ਸਕੂਲ A ਦੀ ਹਾਜ਼ਰੀ",
  "attendance in school b": "ਸਕੂਲ B ਦੀ ਹਾਜ਼ਰੀ",
  "admissions": "ਦਾਖਲੇ",
  "bags of cement": "ਸੀਮੈਂਟ ਦੇ ਬੋਰੇ",
  "bill amount": "ਬਿਲ ਰਕਮ",
  "bonus fund": "ਬੋਨਸ ਫੰਡ",
  "boys": "ਲੜਕੇ",
  "branch a sales": "ਸ਼ਾਖਾ A ਦੀ ਵਿਕਰੀ",
  "branch a stock": "ਸ਼ਾਖਾ A ਦਾ ਸਟਾਕ",
  "branch b sales": "ਸ਼ਾਖਾ B ਦੀ ਵਿਕਰੀ",
  "branch b stock": "ਸ਼ਾਖਾ B ਦਾ ਸਟਾਕ",
  "budget": "ਬਜਟ",
  "budget allocation": "ਬਜਟ ਵੰਡ",
  "budget amount": "ਬਜਟ ਰਕਮ",
  "bags": "ਬੋਰੇ",
  "boxes": "ਡੱਬੇ",
  "books": "ਪੁਸਤਕਾਂ",
  "cartons": "ਕਾਰਟਨ",
  "cattle population": "ਪਸ਼ੂ ਸੰਖਿਆ",
  "child passengers": "ਬਾਲ ਯਾਤਰੀ",
  "commission income": "ਕਮੀਸ਼ਨ ਆਮਦਨ",
  "contract employees": "ਠੇਕੇ ਦੇ ਕਰਮਚਾਰੀ",
  "contract value": "ਠੇਕੇ ਦਾ ਮੁੱਲ",
  "consumption": "ਖਪਤ",
  "cost index": "ਲਾਗਤ ਸੂਚਕਾਂਕ",
  "crates": "ਪੇਟੀਆਂ",
  "crop production": "ਫਸਲ ਉਤਪਾਦਨ",
  "crop yield": "ਫਸਲ ਉਪਜ",
  "damaged items": "ਨੁਕਸਾਨੀ ਚੀਜ਼ਾਂ",
  "day scholars": "ਡੇ-ਸਕਾਲਰ",
  "electricity consumption": "ਬਿਜਲੀ ਦੀ ਖਪਤ",
  "electricity usage": "ਬਿਜਲੀ ਦੀ ਵਰਤੋਂ",
  "employees": "ਕਰਮਚਾਰੀ",
  "expenditure": "ਖਰਚ",
  "expenses": "ਖਰਚੇ",
  "female voters": "ਮਹਿਲਾ ਮਤਦਾਤਾ",
  "female workers": "ਮਹਿਲਾ ਮਜ਼ਦੂਰ",
  "fixed deposit": "ਮਿਆਦੀ ਜਮ੍ਹਾ",
  "fund a value": "ਫੰਡ A ਦਾ ਮੁੱਲ",
  "fund b value": "ਫੰਡ B ਦਾ ਮੁੱਲ",
  "fund value": "ਫੰਡ ਦਾ ਮੁੱਲ",
  "girls": "ਲੜਕੀਆਂ",
  "good items": "ਵਧੀਆ ਚੀਜ਼ਾਂ",
  "good units": "ਚੰਗੀਆਂ ਇਕਾਈਆਂ",
  "hostellers": "ਹੋਸਟਲ ਰਹਿਣ ਵਾਲੇ ਵਿਦਿਆਰਥੀ",
  "households": "ਘਰ-ਪਰਿਵਾਰ",
  "illiterate residents": "ਅਨਪੜ੍ਹ ਨਿਵਾਸੀ",
  "income": "ਆਮਦਨ",
  "index value": "ਸੂਚਕਾਂਕ ਮੁੱਲ",
  "internet users": "ਇੰਟਰਨੈੱਟ ਵਰਤੋਂਕਾਰ",
  "inventory": "ਭੰਡਾਰ",
  "investment": "ਨਿਵੇਸ਼",
  "investment value": "ਨਿਵੇਸ਼ ਦਾ ਮੁੱਲ",
  "items": "ਵਸਤੂਆਂ",
  "kg": "ਕਿਲੋਗ੍ਰਾਮ",
  "literate residents": "ਸਾਖਰ ਨਿਵਾਸੀ",
  "litres": "ਲੀਟਰ",
  "machine a value": "ਮਸ਼ੀਨ A ਦਾ ਮੁੱਲ",
  "machine b value": "ਮਸ਼ੀਨ B ਦਾ ਮੁੱਲ",
  "machine output": "ਮਸ਼ੀਨ ਦਾ ਉਤਪਾਦਨ",
  "machine value": "ਮਸ਼ੀਨ ਦਾ ਮੁੱਲ",
  "male voters": "ਪੁਰਸ਼ ਮਤਦਾਤਾ",
  "male workers": "ਪੁਰਸ਼ ਮਜ਼ਦੂਰ",
  "market demand": "ਬਾਜ਼ਾਰ ਮੰਗ",
  "market value": "ਬਾਜ਼ਾਰ ਮੁੱਲ",
  "marks": "ਅੰਕ",
  "milk production": "ਦੂਧ ਉਤਪਾਦਨ",
  "mixture": "ਮਿਸ਼ਰਣ",
  "monthly income": "ਮਾਸਿਕ ਆਮਦਨ",
  "monthly salary": "ਮਾਸਿਕ ਤਨਖ਼ਾਹ",
  "monthly turnover": "ਮਾਸਿਕ ਟਰਨਓਵਰ",
  "no responses": "ਨਕਾਰਾਤਮਕ ਜਵਾਬ",
  "number of internet users": "ਇੰਟਰਨੈੱਟ ਵਰਤੋਂਕਾਰਾਂ ਦੀ ਗਿਣਤੀ",
  "number of mobile users": "ਮੋਬਾਈਲ ਵਰਤੋਂਕਾਰਾਂ ਦੀ ਗਿਣਤੀ",
  "number of students": "ਵਿਦਿਆਰਥੀਆਂ ਦੀ ਗਿਣਤੀ",
  "number of users": "ਵਰਤੋਂਕਾਰਾਂ ਦੀ ਗਿਣਤੀ",
  "number of visitors": "ਆਗੰਤੁਕਾਂ ਦੀ ਗਿਣਤੀ",
  "offline respondents": "ਆਫਲਾਈਨ ਉੱਤਰਦਾਤਾ",
  "online respondents": "ਆਨਲਾਈਨ ਉੱਤਰਦਾਤਾ",
  "output": "ਉਤਪਾਦਨ",
  "output level": "ਉਤਪਾਦਨ ਪੱਧਰ",
  "passenger count": "ਯਾਤਰੀਆਂ ਦੀ ਗਿਣਤੀ",
  "passengers": "ਯਾਤਰੀ",
  "patients": "ਮਰੀਜ਼",
  "permanent employees": "ਸਥਾਈ ਕਰਮਚਾਰੀ",
  "population": "ਆਬਾਦੀ",
  "people": "ਲੋਕ",
  "population of town a": "Town A ਦੀ ਆਬਾਦੀ",
  "population of town b": "Town B ਦੀ ਆਬਾਦੀ",
  "portfolio value": "ਪੋਰਟਫੋਲਿਓ ਦਾ ਮੁੱਲ",
  "premium amount": "ਪ੍ਰੀਮੀਅਮ ਰਕਮ",
  "premium collection": "ਪ੍ਰੀਮੀਅਮ ਇਕੱਠ",
  "price": "ਕੀਮਤ",
  "price of product a": "Product A ਦੀ ਕੀਮਤ",
  "price of product b": "Product B ਦੀ ਕੀਮਤ",
  "product a price": "Product A ਦੀ ਕੀਮਤ",
  "product b price": "Product B ਦੀ ਕੀਮਤ",
  "production": "ਉਤਪਾਦਨ",
  "production a": "ਉਤਪਾਦਨ A",
  "production b": "ਉਤਪਾਦਨ B",
  "production level": "ਉਤਪਾਦਨ ਪੱਧਰ",
  "production value": "ਉਤਪਾਦਨ ਮੁੱਲ",
  "productivity index": "ਉਤਪਾਦਕਤਾ ਸੂਚਕਾਂਕ",
  "profit": "ਮੁਨਾਫ਼ਾ",
  "quantity": "ਮਾਤਰਾ",
  "quintals": "ਕੁਇੰਟਲ",
  "rainfall": "ਵਰਖਾ",
  "rent": "ਕਿਰਾਇਆ",
  "rent collection": "ਕਿਰਾਇਆ ਇਕੱਠ",
  "reams": "ਰੀਮ",
  "residents": "ਨਿਵਾਸੀ",
  "respondents": "ਉੱਤਰਦਾਤਾ",
  "revenue": "ਰਾਜਸਵ",
  "route a passengers": "Route A ਦੇ ਯਾਤਰੀ",
  "route b passengers": "Route B ਦੇ ਯਾਤਰੀ",
  "rural workers": "ਪੇਂਡੂ ਮਜ਼ਦੂਰ",
  "salary": "ਤਨਖ਼ਾਹ",
  "salary a": "ਤਨਖ਼ਾਹ A",
  "salary b": "ਤਨਖ਼ਾਹ B",
  "sales": "ਵਿਕਰੀ",
  "sales figure": "ਵਿਕਰੀ ਦਾ ਅੰਕੜਾ",
  "sales target": "ਵਿਕਰੀ ਲਕਸ਼",
  "school a's attendance": "ਸਕੂਲ A ਦੀ ਹਾਜ਼ਰੀ",
  "school b's attendance": "ਸਕੂਲ B ਦੀ ਹਾਜ਼ਰੀ",
  "seating capacity": "ਬੈਠਕ ਸਮਰੱਥਾ",
  "section a attendance": "ਸੈਕਸ਼ਨ A ਦੀ ਹਾਜ਼ਰੀ",
  "section b attendance": "ਸੈਕਸ਼ਨ B ਦੀ ਹਾਜ਼ਰੀ",
  "shop a revenue": "ਦੁਕਾਨ A ਦਾ ਰਾਜਸਵ",
  "shop b revenue": "ਦੁਕਾਨ B ਦਾ ਰਾਜਸਵ",
  "skilled workers": "ਨਿਪੁੰਨ ਮਜ਼ਦੂਰ",
  "solution": "ਘੋਲ",
  "stock": "ਸਟਾਕ",
  "stock in branch a": "ਸ਼ਾਖਾ A ਦਾ ਸਟਾਕ",
  "stock in branch b": "ਸ਼ਾਖਾ B ਦਾ ਸਟਾਕ",
  "store a sales": "ਸਟੋਰ A ਦੀ ਵਿਕਰੀ",
  "store a turnover": "ਸਟੋਰ A ਦਾ ਟਰਨਓਵਰ",
  "store b sales": "ਸਟੋਰ B ਦੀ ਵਿਕਰੀ",
  "store b turnover": "ਸਟੋਰ B ਦਾ ਟਰਨਓਵਰ",
  "student passengers": "ਵਿਦਿਆਰਥੀ ਯਾਤਰੀ",
  "students": "ਵਿਦਿਆਰਥੀ",
  "subscriber count": "ਗ੍ਰਾਹਕ ਗਿਣਤੀ",
  "strength": "ਗਿਣਤੀ",
  "supply": "ਸਪਲਾਈ",
  "tax collection": "ਕਰ ਇਕੱਠ",
  "town a population": "Town A ਦੀ ਆਬਾਦੀ",
  "town b population": "Town B ਦੀ ਆਬਾਦੀ",
  "traffic volume": "ਯਾਤਾਯਾਤ ਮਾਤਰਾ",
  "trained employees": "ਤਿਆਰ ਕੀਤੇ ਕਰਮਚਾਰੀ",
  "turnout": "ਮਤਦਾਨ ਹਾਜ਼ਰੀ",
  "turnover": "ਟਰਨਓਵਰ",
  "unit a output": "ਇਕਾਈ A ਦਾ ਉਤਪਾਦਨ",
  "unit b output": "ਇਕਾਈ B ਦਾ ਉਤਪਾਦਨ",
  "units": "ਇਕਾਈਆਂ",
  "unskilled workers": "ਅਨਿਪੁੰਨ ਮਜ਼ਦੂਰ",
  "untrained employees": "ਬਿਨਾ ਤਰਬੀਅਤ ਕਰਮਚਾਰੀ",
  "urban workers": "ਸ਼ਹਿਰੀ ਮਜ਼ਦੂਰ",
  "usage": "ਵਰਤੋਂ",
  "usage index": "ਵਰਤੋਂ ਸੂਚਕਾਂਕ",
  "value": "ਮੁੱਲ",
  "voter turnout": "ਵੋਟਰ ਹਾਜ਼ਰੀ",
  "voters": "ਮਤਦਾਤਾ",
  "votes": "ਵੋਟ",
  "warehouse a stock": "Warehouse A ਦਾ ਸਟਾਕ",
  "warehouse b stock": "Warehouse B ਦਾ ਸਟਾਕ",
  "wildlife population": "ਜੰਗਲੀ ਜੀਵ ਆਬਾਦੀ",
  "workers": "ਮਜ਼ਦੂਰ",
  "yes responses": "ਸਕਾਰਾਤਮਕ ਜਵਾਬ",
};

const LABELS_BY_LANGUAGE: Record<Exclude<QuantV4Language, "en">, Record<string, string>> = {
  hi: HI_LABELS,
  pa: PA_LABELS,
};

export function localizePercentageLabel(label: string, language: QuantV4Language) {
  if (language === "en") return label;
  const localized = LABELS_BY_LANGUAGE[language][label.trim().toLowerCase()];
  if (!localized) {
    throw new Error(`Missing percentage label localization for "${label}" in ${language}.`);
  }
  return localized;
}

export function localizePercentageLabelFields<
  TVariables extends Record<string, string | number>,
>(
  variables: TVariables,
  language: QuantV4Language,
  labelFields: readonly string[],
) {
  if (language === "en") return variables;
  const localized = { ...variables };
  for (const field of labelFields) {
    const value = localized[field];
    if (typeof value !== "string") continue;
    localized[field] = localizePercentageLabel(value, language) as TVariables[keyof TVariables];
  }
  return localized;
}
