import { buildGeoMinQl, finalizeGeoMinCp, auditGeoMinCp } from "./geo-min-001-review-builder";
const SRC=["NCERT-CLASS10-CONTEMPORARY-INDIA-II-CH5-MINERALS-ENERGY-2025-26","CEA-LIST-OF-POWER-STATIONS","CEA-HYDRO-PLANNING-INVESTIGATION"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoMinQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("THERMAL-POWER-FUEL-LOGIC","Thermal power and fuel-location logic",[
{stem:"Coal-based thermal power stations convert which form of energy first?",answer:"Chemical energy of fuel into heat",distractors:["Solar radiation directly into electricity","Wind energy into heat","Tidal energy into coal"],explanation:"Coal is burned to release chemical energy as heat. That heat produces steam, which drives a turbine connected to an electric generator.",sourceFactId:"POWER-THERMAL-BASIC"},
{stem:"Why are many large thermal stations located near coalfields?",answer:"Coal is bulky and costly to transport in large quantities",distractors:["Coal can only burn underground","Electricity cannot be transmitted","Thermal plants require sea coasts only"],explanation:"Coal-fired stations consume very large volumes of fuel. Locating near mines reduces coal-haulage cost, while electricity can be transmitted to distant demand centres.",sourceFactId:"POWER-MINEMOUTH"},
{stem:"Consider the statements: I. Thermal power can use coal or lignite. II. Mine-mouth location can reduce fuel transport. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Coal and lignite are major thermal-power fuels, and large stations are often sited near mines to reduce transport requirements. Both statements are correct.",sourceFactId:"POWER-THERMAL-STATEMENT"},
{stem:"Which pair is correctly matched in Thermal power and fuel-location logic?",answer:"Thermal power — combustion of fuel",distractors:["Hydel power — coal combustion","Thermal power — river-head energy only","Hydel power — petroleum refining"],explanation:"Thermal stations generate heat by burning fuel, whereas hydropower uses the energy of flowing or falling water. The two systems rely on different primary energy sources.",sourceFactId:"POWER-THERMAL-MATCH"},
{stem:"A power plant is supplied continuously by conveyor from a nearby open-cast coal mine. What location type is this?",answer:"Mine-mouth thermal plant",distractors:["Offshore wind farm","Run-of-river hydro plant","Nuclear fuel mine"],explanation:"A thermal plant beside its coal source is called a mine-mouth plant. Conveyor transport of coal is a common clue to this resource-location relationship.",sourceFactId:"POWER-MINEMOUTH-CLUE"},
{stem:"Which factor most directly links coal geography with thermal-power geography?",answer:"Bulk fuel supply",distractors:["Need for mica sheets","Need for beach sand","Need for rock phosphate"],explanation:"Coal-based thermal stations require a constant bulk supply of fuel. That makes coalfield location and transport infrastructure central to thermal-power geography.",sourceFactId:"POWER-COAL-LINK"}
]),
q("SINGRAULI-THERMAL-POWER-COMPLEX","Singrauli thermal-power complex",[
{stem:"Singrauli is especially known for the combination of coal mining and what activity?",answer:"Thermal power generation",distractors:["Marine salt production","Tea cultivation","Mica cutting"],explanation:"Singrauli is a major coalfield and thermal-power complex across Madhya Pradesh and Uttar Pradesh. Large mine-mouth stations use nearby coal resources.",sourceFactId:"POWER-SINGRAULI"},
{stem:"Which two states share the Singrauli coal-power region?",answer:"Madhya Pradesh and Uttar Pradesh",distractors:["Odisha and Jharkhand","Tamil Nadu and Kerala","Gujarat and Rajasthan"],explanation:"The Singrauli region straddles northeastern Madhya Pradesh and southeastern Uttar Pradesh. Its coal mines and power plants form an integrated energy complex.",sourceFactId:"POWER-SINGRAULI-STATES"},
{stem:"Consider the statements: I. Singrauli is a coalfield. II. It also contains major thermal stations. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Singrauli's identity rests on both coal extraction and large-scale thermal generation. The two activities are directly linked by mine-mouth fuel supply.",sourceFactId:"POWER-SINGRAULI-STATEMENT"},
{stem:"Which pair is correctly matched in Singrauli thermal-power complex?",answer:"Singrauli — coal-based power",distractors:["Singrauli — offshore oil","Singrauli — mica belt","Singrauli — marine salt"],explanation:"Singrauli is a classic coal-and-power region. The other resources have different geographical centres.",sourceFactId:"POWER-SINGRAULI-MATCH"},
{stem:"A map marks a major coal-power cluster near the Madhya Pradesh–Uttar Pradesh border. Which region is indicated?",answer:"Singrauli",distractors:["Neyveli","Raniganj","Digboi"],explanation:"The MP-UP border location is the key clue for Singrauli. Neyveli is in Tamil Nadu, Raniganj in West Bengal and Digboi in Assam.",sourceFactId:"POWER-SINGRAULI-MAP"},
{stem:"Why is Singrauli a good example of resource-based power-plant location?",answer:"Large thermal stations developed beside abundant coal deposits",distractors:["The region lacks coal","The plants rely only on imported gas","Hydropower requires no river there"],explanation:"Singrauli demonstrates how abundant local coal can attract large thermal stations. This reduces fuel-haulage needs and ties energy production closely to mineral geography.",sourceFactId:"POWER-SINGRAULI-REASONING"}
]),
q("KORBA-THERMAL-POWER","Korba thermal-power region",[
{stem:"Korba, a major thermal-power centre, is located in which state?",answer:"Chhattisgarh",distractors:["Assam","Rajasthan","Tamil Nadu"],explanation:"Korba lies in Chhattisgarh and combines major coal resources with large thermal-power capacity. It is one of central India's classic coal-power centres.",sourceFactId:"POWER-KORBA-STATE"},
{stem:"Which fuel provides the main resource base for Korba's large thermal stations?",answer:"Coal",distractors:["Uranium","Natural gas only","Mica"],explanation:"Korba is located within a major coalfield of Chhattisgarh. Nearby coal provides the bulk fuel supply for its thermal-power stations.",sourceFactId:"POWER-KORBA-FUEL"},
{stem:"Consider the statements: I. Korba is a coalfield. II. Korba is also a thermal-power centre. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Korba combines coal mining and electricity generation in the same region. This is a direct example of mine-mouth thermal-power geography.",sourceFactId:"POWER-KORBA-STATEMENT"},
{stem:"Which pair is correctly matched in Korba thermal-power region?",answer:"Korba — Chhattisgarh thermal power",distractors:["Korba — Assam petroleum","Korba — Tamil Nadu lignite","Korba — Rajasthan gypsum"],explanation:"Korba is a major Chhattisgarh coal and power region. The alternative resource-state combinations are incorrect.",sourceFactId:"POWER-KORBA-MATCH"},
{stem:"Which comparison is correct for Korba thermal-power region?",answer:"Korba is in Chhattisgarh, while Talcher is in Odisha",distractors:["Both are in Assam","Korba is in Odisha and Talcher in Chhattisgarh","Both are nuclear-only centres"],explanation:"Korba and Talcher are major coal-based energy centres in neighbouring mineral-rich states. Korba lies in Chhattisgarh and Talcher in Odisha.",sourceFactId:"POWER-KORBA-TALCHER"},
{stem:"A district has coal mines, large thermal stations and heavy industry. Which place is a strong example?",answer:"Korba",distractors:["Koderma","Panna","Sambhar"],explanation:"Korba's coal deposits and thermal stations make it a major energy-industrial centre. Koderma, Panna and Sambhar are associated with mica, diamond and salt respectively.",sourceFactId:"POWER-KORBA-CLUE"}
]),
q("TALCHER-POWER-AND-COAL","Talcher coal-power region",[
{stem:"Talcher thermal-power region is located in which state?",answer:"Odisha",distractors:["Jharkhand","Gujarat","Tamil Nadu"],explanation:"Talcher is a major coalfield and thermal-power region of Odisha. Its coal resources support electricity generation and nearby industries.",sourceFactId:"POWER-TALCHER"},
{stem:"Which fuel is the principal local resource behind Talcher's thermal-power development?",answer:"Coal",distractors:["Lignite only","Uranium","Natural gas only"],explanation:"Talcher is one of Odisha's principal coalfields, so coal provides the direct fuel base for thermal generation in the region.",sourceFactId:"POWER-TALCHER-FUEL"},
{stem:"Consider the statements: I. Talcher is in Odisha. II. It is part of a major coal-power complex. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Talcher combines a large Odisha coalfield with substantial thermal-power development. Both statements correctly describe the region.",sourceFactId:"POWER-TALCHER-STATEMENT"},
{stem:"Which pair is correctly matched in Talcher coal-power region?",answer:"Talcher — Odisha coal and power",distractors:["Talcher — Assam oil","Talcher — Rajasthan lead-zinc","Talcher — Kerala beach sand"],explanation:"Talcher is a major Odisha coal-and-power centre. The other pairings attach unrelated resources to the location.",sourceFactId:"POWER-TALCHER-MATCH"},
{stem:"Which state is identified by the clues 'Talcher, Ib Valley, coal and large thermal generation'?",answer:"Odisha",distractors:["Punjab","Kerala","Goa"],explanation:"Talcher and Ib Valley are Odisha's major coalfields, and their coal supports extensive power generation. The combined clues identify Odisha.",sourceFactId:"POWER-ODISHA-CLUE"},
{stem:"Why are Talcher's coal resources important beyond mining alone?",answer:"They support thermal power and mineral-based industry",distractors:["They are used only for jewellery","They are the state's main fertilizer mineral","They form beach placers"],explanation:"Coal from Talcher provides energy for power stations and industry. The region therefore illustrates how a mineral resource shapes wider industrial geography.",sourceFactId:"POWER-TALCHER-REASONING"}
]),
q("HYDROPOWER-PRINCIPLE-AND-LOCATION","Hydropower principle and location",[
{stem:"Hydroelectric power uses the energy of what?",answer:"Flowing or falling water",distractors:["Burning coal","Uranium fission","Natural gas combustion"],explanation:"Hydropower converts the potential and kinetic energy of water into mechanical energy in turbines and then electricity in generators. It does not require fuel combustion.",sourceFactId:"HYDRO-BASIC"},
{stem:"Which physical factor is especially favourable for hydropower generation?",answer:"Large water discharge with significant elevation difference",distractors:["Flat dry desert without rivers","Absence of relief","No water storage or flow"],explanation:"Hydropower benefits from both water volume and hydraulic head, the vertical drop through which water falls. Mountainous river systems therefore offer strong potential.",sourceFactId:"HYDRO-HEAD"},
{stem:"Consider the statements: I. Hydropower is renewable. II. It depends on river flow and relief. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Hydropower is renewable because the water cycle replenishes flows, though output depends on hydrology and elevation. Both statements are correct.",sourceFactId:"HYDRO-STATEMENT"},
{stem:"Which pair is correctly matched in Hydropower principle and location?",answer:"Hydropower — hydraulic head",distractors:["Thermal power — hydraulic head only","Hydropower — coking coal","Hydropower — uranium fuel"],explanation:"Hydraulic head is the elevation difference that gives water usable potential energy for hydropower. Coal and uranium belong to thermal and nuclear energy systems.",sourceFactId:"HYDRO-MATCH"},
{stem:"A river descends rapidly through a mountain valley with high discharge. Which energy resource is especially favoured?",answer:"Hydroelectric power",distractors:["Lignite mining","Offshore petroleum","Salt production"],explanation:"Steep gradients provide high hydraulic head, while strong discharge supplies water volume. Together they create favourable hydropower conditions.",sourceFactId:"HYDRO-MOUNTAIN-CLUE"},
{stem:"Why can the Himalayan region have high hydropower potential?",answer:"Many rivers combine large flows with steep relief",distractors:["It has no rivers","Coal seams create hydraulic head","Petroleum traps generate electricity directly"],explanation:"Himalayan rivers descend through large elevation differences and carry substantial flows. This combination creates significant hydropower potential.",sourceFactId:"HYDRO-HIMALAYA"}
]),
q("BHAKRA-NANGAL-HYDROPOWER","Bhakra-Nangal hydropower",[
{stem:"Bhakra-Nangal project is built on which river?",answer:"Sutlej",distractors:["Godavari","Mahanadi","Narmada"],explanation:"Bhakra Dam is built across the Sutlej River and forms a major multipurpose project of north-western India. Hydropower is one of its important functions.",sourceFactId:"HYDRO-BHAKRA-RIVER"},
{stem:"Which project is most strongly linked with the Sutlej River?",answer:"Bhakra-Nangal",distractors:["Hirakud","Tehri","Koyna"],explanation:"Bhakra-Nangal is the classic Sutlej multipurpose project. Hirakud is on the Mahanadi, Tehri on the Bhagirathi and Koyna on the Koyna River.",sourceFactId:"HYDRO-BHAKRA"},
{stem:"Consider the statements: I. Bhakra-Nangal generates hydropower. II. It is a multipurpose river-valley project. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Bhakra-Nangal serves several purposes including irrigation, flood control and electricity generation. It is therefore more than a single-purpose hydropower installation.",sourceFactId:"HYDRO-BHAKRA-STATEMENT"},
{stem:"Which pair is correctly matched in Bhakra-Nangal hydropower?",answer:"Bhakra-Nangal — Sutlej",distractors:["Bhakra-Nangal — Mahanadi","Bhakra-Nangal — Koyna","Bhakra-Nangal — Krishna"],explanation:"The Bhakra-Nangal project is on the Sutlej River. The other river pairings belong to different projects and regions.",sourceFactId:"HYDRO-BHAKRA-MATCH"},
{stem:"Which northern project combines irrigation and hydropower on the Sutlej?",answer:"Bhakra-Nangal",distractors:["Neyveli","Talcher","Korba"],explanation:"Bhakra-Nangal is a major multipurpose Sutlej project with both irrigation and hydropower functions. Neyveli, Talcher and Korba are thermal-energy regions.",sourceFactId:"HYDRO-BHAKRA-CLUE"},
{stem:"Why is Bhakra-Nangal classed as a multipurpose project?",answer:"It provides several benefits including irrigation and power generation",distractors:["It produces only coal","It is an offshore oilfield","It mines uranium"],explanation:"Multipurpose river projects combine functions such as irrigation, power, water supply and flood moderation. Bhakra-Nangal is a classic Indian example.",sourceFactId:"HYDRO-BHAKRA-REASONING"}
]),
q("TEHRI-HYDROPOWER","Tehri hydropower",[
{stem:"Tehri Dam is built on which river?",answer:"Bhagirathi",distractors:["Sutlej","Mahanadi","Koyna"],explanation:"Tehri Dam is constructed on the Bhagirathi River in Uttarakhand. It is one of India's major Himalayan hydropower and water-storage projects.",sourceFactId:"HYDRO-TEHRI-RIVER"},
{stem:"Tehri hydropower project is located in which state?",answer:"Uttarakhand",distractors:["Odisha","Tamil Nadu","Gujarat"],explanation:"Tehri is in Uttarakhand in the Himalayan region. The area's steep relief and major river systems make it favourable for hydropower.",sourceFactId:"HYDRO-TEHRI-STATE"},
{stem:"Consider the statements: I. Tehri lies on the Bhagirathi. II. It is a Himalayan hydropower project. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Tehri Dam is on the Bhagirathi in Uttarakhand and is a major Himalayan hydropower project. Both statements are correct.",sourceFactId:"HYDRO-TEHRI-STATEMENT"},
{stem:"Which pair is correctly matched in Tehri hydropower?",answer:"Tehri — Bhagirathi",distractors:["Tehri — Mahanadi","Tehri — Sutlej","Tehri — Godavari"],explanation:"Tehri is built on the Bhagirathi River. Mahanadi, Sutlej and Godavari are linked with other river systems and projects.",sourceFactId:"HYDRO-TEHRI-MATCH"},
{stem:"A major dam in Uttarakhand is identified by the clues 'Bhagirathi and hydropower'. Which project is it?",answer:"Tehri",distractors:["Hirakud","Koyna","Neyveli"],explanation:"The Bhagirathi and Uttarakhand clues identify Tehri. Hirakud is in Odisha, Koyna in Maharashtra and Neyveli is a lignite-power centre.",sourceFactId:"HYDRO-TEHRI-CLUE"},
{stem:"Which feature of Uttarakhand favours projects such as Tehri?",answer:"Steep river gradients in mountainous terrain",distractors:["Flat desert relief","Absence of perennial rivers","Offshore petroleum basins"],explanation:"Mountainous terrain creates large elevation differences that provide hydraulic head. Combined with river flow, this favours hydropower development.",sourceFactId:"HYDRO-TEHRI-REASONING"}
]),
q("HIRAKUD-HYDROPOWER","Hirakud multipurpose project",[
{stem:"Hirakud Dam is built on which river?",answer:"Mahanadi",distractors:["Sutlej","Bhagirathi","Koyna"],explanation:"Hirakud Dam is built across the Mahanadi River in Odisha. It is a major multipurpose project with irrigation, flood-control and power functions.",sourceFactId:"HYDRO-HIRAKUD-RIVER"},
{stem:"Hirakud project is located in which state?",answer:"Odisha",distractors:["Punjab","Uttarakhand","Maharashtra"],explanation:"Hirakud lies in Odisha on the Mahanadi. It is one of eastern India's best-known multipurpose river projects.",sourceFactId:"HYDRO-HIRAKUD-STATE"},
{stem:"Consider the statements: I. Hirakud is on the Mahanadi. II. Hydropower is one of its functions. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Hirakud uses the Mahanadi for a multipurpose system that includes electricity generation. Both the river and energy statements are correct.",sourceFactId:"HYDRO-HIRAKUD-STATEMENT"},
{stem:"Which pair is correctly matched in Hirakud multipurpose project?",answer:"Hirakud — Mahanadi",distractors:["Hirakud — Sutlej","Hirakud — Bhagirathi","Hirakud — Koyna"],explanation:"Hirakud is a Mahanadi project in Odisha. The other rivers are linked with Bhakra, Tehri and Koyna respectively.",sourceFactId:"HYDRO-HIRAKUD-MATCH"},
{stem:"Which Odisha project combines flood moderation, irrigation and electricity generation?",answer:"Hirakud",distractors:["Singrauli","Neyveli","Digboi"],explanation:"Hirakud is a multipurpose Mahanadi project in Odisha. Singrauli and Neyveli are fuel-based power regions, while Digboi is a petroleum centre.",sourceFactId:"HYDRO-HIRAKUD-CLUE"},
{stem:"Why is Hirakud relevant to both river and energy geography?",answer:"It stores Mahanadi water and generates hydroelectric power",distractors:["It mines coal beneath the reservoir","It is an offshore oil platform","It extracts uranium"],explanation:"Hirakud links river management with hydropower generation. Its reservoir also supports irrigation and flood-control functions.",sourceFactId:"HYDRO-HIRAKUD-REASONING"}
]),
q("KOYNA-HYDROPOWER","Koyna hydropower",[
{stem:"Koyna hydroelectric project is located in which state?",answer:"Maharashtra",distractors:["Odisha","Punjab","Assam"],explanation:"The Koyna project is in Maharashtra in the Western Ghats. It is one of India's major hydroelectric developments.",sourceFactId:"HYDRO-KOYNA-STATE"},
{stem:"Koyna project is built on which river?",answer:"Koyna River",distractors:["Sutlej","Mahanadi","Bhagirathi"],explanation:"The project takes its name from the Koyna River, a tributary of the Krishna. Its Western Ghats setting provides favourable relief for hydropower.",sourceFactId:"HYDRO-KOYNA-RIVER"},
{stem:"Consider the statements: I. Koyna is in Maharashtra. II. It is a hydroelectric project. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Koyna is a major Maharashtra hydroelectric project in the Western Ghats. Both statements are correct.",sourceFactId:"HYDRO-KOYNA-STATEMENT"},
{stem:"Which pair is correctly matched in Koyna hydropower?",answer:"Koyna — Maharashtra hydropower",distractors:["Koyna — Assam oil","Koyna — Rajasthan lignite","Koyna — Jharkhand coal"],explanation:"Koyna is a hydropower project in Maharashtra. The alternative resources and states are unrelated.",sourceFactId:"HYDRO-KOYNA-MATCH"},
{stem:"Which physiographic feature helps Koyna generate hydropower?",answer:"Western Ghats relief",distractors:["Thar Desert dunes","Flat Indo-Gangetic plain only","Offshore continental shelf"],explanation:"The Western Ghats provide substantial elevation differences and high rainfall. These conditions are favourable for reservoir and hydropower development.",sourceFactId:"HYDRO-KOYNA-RELIEF"},
{stem:"Which comparison is correct for Koyna hydropower?",answer:"Koyna is in Maharashtra, while Tehri is in Uttarakhand",distractors:["Both are in Odisha","Koyna is in Uttarakhand and Tehri in Maharashtra","Both are coal-based thermal stations"],explanation:"Koyna is a Western Ghats hydropower project in Maharashtra, while Tehri is a Himalayan project in Uttarakhand. Both use water energy in different physiographic regions.",sourceFactId:"HYDRO-KOYNA-TEHRI"}
])
]);
export const GEO_MIN_001_CP008_REVIEW_BATCH_V1=finalizeGeoMinCp(8,QLS);
export function auditGeoMin001Cp008ReviewBatchV1(){return auditGeoMinCp(8,QLS,GEO_MIN_001_CP008_REVIEW_BATCH_V1);}
