import { buildGeoMinQl, finalizeGeoMinCp, auditGeoMinCp } from "./geo-min-001-review-builder";
const SRC=["NCERT-CLASS10-CONTEMPORARY-INDIA-II-CH5-MINERALS-ENERGY-2025-26","MINISTRY-OF-NEW-AND-RENEWABLE-ENERGY-INDIA","CEA-RENEWABLE-ENERGY-GEOGRAPHY"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoMinQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("SOLAR-ENERGY-BASICS-AND-GEOGRAPHY","Solar energy basics and Indian geography",[
{stem:"Which source provides the energy used by solar photovoltaic systems?",answer:"Sunlight",distractors:["Coal combustion","River head","Uranium fission"],explanation:"Solar photovoltaic systems convert sunlight directly into electricity using semiconductor cells. They do not depend on fuel combustion or flowing water.",sourceFactId:"RE-SOLAR-BASIC"},
{stem:"Which part of India is especially favourable for large solar projects because of high sunshine and arid conditions?",answer:"Western Rajasthan",distractors:["Upper Assam valley only","Sundarbans delta only","Kashmir Valley only"],explanation:"Western Rajasthan receives strong solar radiation and has large open arid areas, making it highly suitable for utility-scale solar development.",sourceFactId:"RE-SOLAR-RAJASTHAN"},
{stem:"Consider the statements: I. Solar power is renewable. II. It depends on incoming solar radiation. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Solar energy is continuously replenished by the Sun and output depends on available radiation. Both statements correctly describe solar power.",sourceFactId:"RE-SOLAR-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Solar power — photovoltaic cells",distractors:["Solar power — coking coal","Solar power — uranium ore","Solar power — hydraulic head"],explanation:"Photovoltaic cells convert sunlight to electricity. Coal, uranium and hydraulic head belong to thermal, nuclear and hydel systems respectively.",sourceFactId:"RE-SOLAR-MATCH"},
{stem:"Why can desert regions be suitable for solar parks?",answer:"They often combine high solar radiation with large open land areas",distractors:["They contain the most rivers","Solar panels require coal seams","They have no sunlight"],explanation:"High insolation and available land are favourable for large solar installations. Arid western India therefore has strong solar potential.",sourceFactId:"RE-SOLAR-DESERT"},
{stem:"A state is identified by the clues 'Thar Desert, high solar radiation, large solar parks'. Which state is it?",answer:"Rajasthan",distractors:["Kerala","Assam","Bihar"],explanation:"The Thar Desert and strong solar resource make Rajasthan one of India's most important solar-energy regions.",sourceFactId:"RE-SOLAR-CLUE"}
]),
q("WIND-ENERGY-BASICS-AND-CORRIDORS","Wind energy basics and major corridors",[
{stem:"Wind turbines generate electricity by using which energy?",answer:"Kinetic energy of moving air",distractors:["Heat from coal","Nuclear fission","Chemical energy of petroleum"],explanation:"Wind turbines capture the kinetic energy of moving air and convert it into rotational mechanical energy and then electricity.",sourceFactId:"RE-WIND-BASIC"},
{stem:"Which state is well known for major wind-energy development around Muppandal?",answer:"Tamil Nadu",distractors:["Punjab","Jharkhand","Bihar"],explanation:"Muppandal in Tamil Nadu is one of India's best-known wind-energy locations. Strong seasonal winds and suitable terrain helped large-scale development.",sourceFactId:"RE-WIND-MUPPANDAL"},
{stem:"Consider the statements: I. Wind power is renewable. II. Coastal and elevated corridors can offer strong wind resources. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Wind is continuously renewed by atmospheric circulation, and coastal or elevated regions can experience stronger and more persistent winds.",sourceFactId:"RE-WIND-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Muppandal — wind power",distractors:["Muppandal — uranium","Muppandal — coking coal","Muppandal — lignite"],explanation:"Muppandal is a major wind-energy centre in Tamil Nadu. The alternative resources are unrelated.",sourceFactId:"RE-WIND-MATCH"},
{stem:"Why are ridges and coastal passes often attractive for wind farms?",answer:"Topography can accelerate and channel winds",distractors:["They contain coal seams","Wind turbines require river dams","They are always cloud-free"],explanation:"Ridges, passes and coastal corridors can concentrate or accelerate airflow, improving the energy available to wind turbines.",sourceFactId:"RE-WIND-TOPOGRAPHY"},
{stem:"Which comparison is correct?",answer:"Rajasthan is prominent in solar power, while Tamil Nadu is prominent in wind power",distractors:["Both are known only for coal","Tamil Nadu is known only for uranium","Rajasthan has no renewable energy"],explanation:"Rajasthan's arid solar resource and Tamil Nadu's strong wind corridors are two classic renewable-energy geography patterns in India.",sourceFactId:"RE-SOLAR-WIND-COMPARE"}
]),
q("BIOMASS-AND-BIOGAS","Biomass and biogas",[
{stem:"Biogas is produced mainly by which process?",answer:"Anaerobic decomposition of organic matter",distractors:["Nuclear fission","Coal combustion","Evaporation of seawater"],explanation:"Biogas forms when microorganisms break down organic material in the absence of oxygen. The gas contains methane and can be used as fuel.",sourceFactId:"RE-BIOGAS-PROCESS"},
{stem:"Which material can serve as feedstock for a biogas plant?",answer:"Animal dung and organic waste",distractors:["Iron ore","Bauxite","Chromite"],explanation:"Biogas plants can use cattle dung, agricultural residues and other biodegradable organic wastes. These materials are digested anaerobically to release methane-rich gas.",sourceFactId:"RE-BIOGAS-FEED"},
{stem:"Consider the statements: I. Biomass energy can use crop residues. II. Biogas contains methane. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Crop residues are a common biomass resource, while methane is the principal combustible component of biogas. Both statements are correct.",sourceFactId:"RE-BIOMASS-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Biogas — anaerobic digestion",distractors:["Biogas — uranium fission","Biomass — offshore oil only","Biogas — hydropower turbine"],explanation:"Biogas is produced through anaerobic digestion of organic matter. The other processes belong to different energy systems.",sourceFactId:"RE-BIOGAS-MATCH"},
{stem:"Why can biomass energy be especially relevant in agricultural regions?",answer:"Crop residues and animal waste provide local feedstock",distractors:["Agricultural areas contain no organic matter","Biomass requires uranium","It depends only on offshore wind"],explanation:"Agricultural regions generate large quantities of residues and animal waste. These can be converted into heat, electricity or biogas near the source.",sourceFactId:"RE-BIOMASS-AGRICULTURE"},
{stem:"A village uses cattle dung in a sealed digester to produce cooking fuel. Which energy source is this?",answer:"Biogas",distractors:["Lignite","Hydropower","Nuclear power"],explanation:"A sealed anaerobic digester converts dung into methane-rich biogas. This is a decentralised renewable-energy system.",sourceFactId:"RE-BIOGAS-CLUE"}
]),
q("SMALL-HYDRO-AND-RUN-OF-RIVER","Small hydro and run-of-river power",[
{stem:"Small hydropower uses which primary energy source?",answer:"Flowing water",distractors:["Coal","Natural gas","Uranium"],explanation:"Small hydro projects use the energy of flowing water, often with modest dams or diversion structures. They operate on the same basic principle as larger hydropower schemes.",sourceFactId:"RE-SMALL-HYDRO"},
{stem:"A run-of-river hydropower project differs from a large storage dam because it generally has what?",answer:"Less reservoir storage",distractors:["No flowing water","No turbines","Coal-fired boilers"],explanation:"Run-of-river schemes usually divert part of a river flow through turbines with limited storage compared with large reservoir projects.",sourceFactId:"RE-RUN-OF-RIVER"},
{stem:"Consider the statements: I. Small hydro is renewable. II. Mountain streams can provide suitable head. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Small hydro uses the renewable water cycle, and steep mountain streams can provide the hydraulic head needed for generation.",sourceFactId:"RE-SMALL-HYDRO-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Run-of-river — limited storage hydropower",distractors:["Run-of-river — coking coal","Small hydro — petroleum refining","Hydropower — uranium fission"],explanation:"Run-of-river projects generate hydroelectricity using river flow with relatively limited storage. The other pairings are unrelated.",sourceFactId:"RE-SMALL-HYDRO-MATCH"},
{stem:"Which region is especially suitable for many small hydropower projects?",answer:"Himalayan and other mountainous states",distractors:["Flat salt pans only","Offshore oilfields","Desert interiors without streams"],explanation:"Mountain regions have steep gradients and numerous streams, giving them strong small-hydro potential where local conditions are suitable.",sourceFactId:"RE-SMALL-HYDRO-REGION"},
{stem:"Why can small hydro suit remote mountain communities?",answer:"Local streams can generate electricity near demand centres",distractors:["It requires imported coal","It must be offshore","It uses no water"],explanation:"Small hydro can use nearby streams to supply local or regional grids, reducing the need to transport fuel into difficult terrain.",sourceFactId:"RE-SMALL-HYDRO-REASONING"}
]),
q("TIDAL-ENERGY-INDIA","Tidal energy and Indian locations",[
{stem:"Tidal power uses energy from what?",answer:"Periodic rise and fall of sea level",distractors:["Coal seams","Uranium fission","River sediment only"],explanation:"Tidal energy comes from regular sea-level changes caused mainly by gravitational interactions involving the Moon and Sun. Suitable coastal geometry can concentrate this energy.",sourceFactId:"RE-TIDAL-BASIC"},
{stem:"Which Indian gulf is often identified as having notable tidal-energy potential?",answer:"Gulf of Khambhat",distractors:["Gulf of Mannar only","Palk Strait only","Chilika Lake"],explanation:"The Gulf of Khambhat in Gujarat experiences a large tidal range and has long been identified as a potential tidal-energy region.",sourceFactId:"RE-TIDAL-KHAMBHAT"},
{stem:"Consider the statements: I. The Gulf of Kachchh has tidal-energy potential. II. Tidal power depends on sea-level variation. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The Gulf of Kachchh is among India's potential tidal-energy areas, and tidal generation depends on the predictable rise and fall of the sea.",sourceFactId:"RE-TIDAL-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Gulf of Khambhat — tidal energy potential",distractors:["Gulf of Khambhat — coking coal","Gulf of Khambhat — uranium mine","Gulf of Khambhat — mica belt"],explanation:"The Gulf of Khambhat is notable for its large tidal range and potential tidal-energy applications. The other resources are unrelated.",sourceFactId:"RE-TIDAL-MATCH"},
{stem:"Why are narrow gulfs with large tidal ranges favourable for tidal power?",answer:"They can concentrate large volumes of moving water",distractors:["They create coal","They eliminate tides","They contain uranium"],explanation:"A large tidal range and confined coastal geometry can produce strong water movement, increasing the energy potentially available for tidal generation.",sourceFactId:"RE-TIDAL-GEOMETRY"},
{stem:"A renewable-energy question gives the clues 'Gulf of Khambhat, Gujarat, large tidal range'. Which source is indicated?",answer:"Tidal energy",distractors:["Biogas","Geothermal energy","Lignite"],explanation:"The Gulf of Khambhat is a classic Indian tidal-energy location. Its large tidal range is the key clue.",sourceFactId:"RE-TIDAL-CLUE"}
]),
q("GEOTHERMAL-ENERGY-INDIA","Geothermal energy and Indian locations",[
{stem:"Geothermal energy uses heat from where?",answer:"Inside the Earth",distractors:["Sunlight only","Coal combustion","Ocean waves only"],explanation:"Geothermal energy uses heat stored within the Earth. Hot water, steam or heated rocks can provide useful energy where geothermal conditions are favourable.",sourceFactId:"RE-GEOTHERMAL-BASIC"},
{stem:"Puga Valley, a well-known geothermal area, is located in which region?",answer:"Ladakh",distractors:["Rajasthan","Kerala","Jharkhand"],explanation:"Puga Valley in Ladakh is one of India's best-known geothermal fields. Hot springs and geothermal manifestations make it an important renewable-energy location.",sourceFactId:"RE-GEOTHERMAL-PUGA"},
{stem:"Consider the statements: I. Puga Valley has geothermal potential. II. Geothermal energy comes from Earth's internal heat. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Puga Valley is a recognised geothermal area, and geothermal energy is derived from subsurface heat. Both statements are correct.",sourceFactId:"RE-GEOTHERMAL-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Puga Valley — geothermal energy",distractors:["Puga Valley — coking coal","Puga Valley — petroleum offshore","Puga Valley — mica belt"],explanation:"Puga Valley is linked with geothermal manifestations in Ladakh. The other resources have unrelated geographical settings.",sourceFactId:"RE-GEOTHERMAL-MATCH"},
{stem:"Which physical sign may indicate geothermal activity?",answer:"Hot springs",distractors:["Coal seams only","Beach dunes only","Mica sheets"],explanation:"Hot springs can indicate subsurface heat and circulation of groundwater through heated rocks. They are common surface expressions of geothermal systems.",sourceFactId:"RE-GEOTHERMAL-SPRING"},
{stem:"A renewable-energy map marks Puga Valley in Ladakh. Which resource should be identified?",answer:"Geothermal energy",distractors:["Tidal energy","Biogas","Wind only"],explanation:"Puga Valley is one of India's classic geothermal locations. Its position in Ladakh distinguishes it from coastal tidal or agricultural biomass systems.",sourceFactId:"RE-GEOTHERMAL-MAP"}
]),
q("RENEWABLE-STATE-MAP-REASONING","Renewable-energy state and map reasoning",[
{stem:"Which pair is correctly matched?",answer:"Rajasthan — solar energy",distractors:["Rajasthan — tidal only","Tamil Nadu — no wind potential","Ladakh — marine tidal power"],explanation:"Rajasthan is especially strong in solar resources, while Tamil Nadu is a major wind state and Ladakh includes geothermal potential at Puga.",sourceFactId:"RE-MAP-RAJASTHAN"},
{stem:"Which pair is correctly matched?",answer:"Tamil Nadu — major wind-energy development",distractors:["Tamil Nadu — no renewable energy","Gujarat — geothermal Puga Valley","Ladakh — Muppandal wind farm"],explanation:"Tamil Nadu has major wind development including the Muppandal region. Puga is in Ladakh and Gujarat is better known for strong solar, wind and tidal potential.",sourceFactId:"RE-MAP-TAMILNADU"},
{stem:"Consider the statements: I. Gujarat has tidal-energy potential. II. Rajasthan has strong solar potential. III. Ladakh has geothermal potential. Which is correct?",answer:"I, II and III",distractors:["I and II only","II and III only","I and III only"],explanation:"All three are durable renewable-energy geography relationships: tidal potential in Gujarat, solar strength in Rajasthan and geothermal potential in Ladakh.",sourceFactId:"RE-MAP-STATEMENT"},
{stem:"Which sequence is correctly matched?",answer:"Rajasthan—solar; Tamil Nadu—wind; Ladakh—geothermal",distractors:["Rajasthan—geothermal; Tamil Nadu—tidal only; Ladakh—coal","All three—lignite","Rajasthan—offshore oil; Tamil Nadu—uranium; Ladakh—mica"],explanation:"The sequence correctly links three states or regions with prominent renewable-energy resources. The alternatives mix unrelated energy and mineral systems.",sourceFactId:"RE-MAP-SEQUENCE"},
{stem:"A map marks western Rajasthan, Muppandal and Puga Valley. Which three renewable sources are indicated respectively?",answer:"Solar, wind and geothermal",distractors:["Coal, oil and gas","Tidal, nuclear and lignite","Hydel, coal and petroleum"],explanation:"Western Rajasthan is a major solar region, Muppandal is a wind centre and Puga Valley is a geothermal location. The three map points represent different renewable technologies.",sourceFactId:"RE-MAP-THREE"},
{stem:"Which location-resource pair is incorrect?",answer:"Puga Valley — tidal energy",distractors:["Muppandal — wind","Rajasthan desert — solar","Gulf of Khambhat — tidal"],explanation:"Puga Valley is geothermal, not tidal. Muppandal, Rajasthan and the Gulf of Khambhat correctly match wind, solar and tidal resources.",sourceFactId:"RE-MAP-NEGATIVE"}
]),
q("RENEWABLE-ENERGY-COMPARATIVE-LOGIC","Renewable-energy comparative logic",[
{stem:"Which renewable source depends most directly on clear-sky solar radiation?",answer:"Solar power",distractors:["Wind power","Tidal power","Geothermal power"],explanation:"Solar output depends directly on incoming sunlight, while wind, tidal and geothermal systems draw on atmospheric motion, sea-level cycles and subsurface heat.",sourceFactId:"RE-COMPARE-SOLAR"},
{stem:"Which renewable source is the most predictable on a short-term astronomical cycle?",answer:"Tidal energy",distractors:["Wind energy","Solar energy during monsoon clouds","Biomass combustion"],explanation:"Tides are driven by highly predictable gravitational cycles, making their timing more predictable than wind variability. This does not necessarily make tidal power easier or cheaper to develop.",sourceFactId:"RE-COMPARE-TIDAL"},
{stem:"Consider the statements: I. Solar and wind output can vary with weather. II. Geothermal energy depends on suitable subsurface heat. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Solar and wind are weather-dependent resources, while geothermal systems require suitable geological heat and fluid conditions. Both statements correctly describe resource constraints.",sourceFactId:"RE-COMPARE-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Biogas — organic waste",distractors:["Tidal power — coal","Wind power — uranium","Solar power — coking coal"],explanation:"Biogas is produced from biodegradable organic material. The other pairs incorrectly link renewable technologies with fossil or nuclear fuels.",sourceFactId:"RE-COMPARE-MATCH"},
{stem:"Which renewable source is most naturally linked with cattle-rich rural areas?",answer:"Biogas",distractors:["Tidal energy","Offshore wind only","Geothermal only"],explanation:"Cattle dung and other organic wastes provide feedstock for village-scale biogas plants, making the technology especially relevant to rural agricultural settings.",sourceFactId:"RE-COMPARE-RURAL"},
{stem:"A region has strong sunlight, little surface water and large open land. Which renewable source is most naturally favoured?",answer:"Solar energy",distractors:["Large reservoir hydropower","Tidal energy","Biogas from fisheries only"],explanation:"Strong solar radiation and open land favour solar generation even where water resources are limited. This is a classic advantage of arid solar regions.",sourceFactId:"RE-COMPARE-ARID"}
])
]);
export const GEO_MIN_001_CP010_REVIEW_BATCH_V1=finalizeGeoMinCp(10,QLS);
export function auditGeoMin001Cp010ReviewBatchV1(){return auditGeoMinCp(10,QLS,GEO_MIN_001_CP010_REVIEW_BATCH_V1);}
