import { buildGeoMinQl, finalizeGeoMinCp, auditGeoMinCp } from "./geo-min-001-review-builder";

const COAL_SRC = ["NCERT-CLASS10-CONTEMPORARY-INDIA-II-CH5-MINERALS-ENERGY-2025-26","COAL-CONTROLLER-COAL-DIRECTORY-INDIA-2024-25","MINISTRY-OF-COAL-INDIAN-COAL-SCENARIO"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoMinQl(key,name,rows.map((r:any)=>({...r,sourceIds:COAL_SRC})) as any);

const QLS = Object.freeze([
q("COAL-RANK-TYPES-AND-CARBON-CONTENT","Coal types and carbon content",[
{stem:"Which coal has the highest carbon content among the common coal ranks?",answer:"Anthracite",distractors:["Bituminous","Lignite","Peat"],explanation:"Anthracite is the highest-rank coal and contains the largest proportion of carbon among the common coal types. It burns with relatively little smoke and is harder than lower-rank coals.",sourceFactId:"COAL-ANTHRACITE"},
{stem:"Which coal type is widely used in industry and includes many coking-coal varieties?",answer:"Bituminous",distractors:["Anthracite","Lignite","Peat"],explanation:"Bituminous coal is a major industrial coal and includes grades suitable for coke making. It generally has more carbon and calorific value than lignite but less than anthracite.",sourceFactId:"COAL-BITUMINOUS"},
{stem:"Which coal is commonly called brown coal because of its lower rank and higher moisture?",answer:"Lignite",distractors:["Anthracite","Bituminous","Coking coal only"],explanation:"Lignite is a low-rank brown coal with relatively high moisture content. It is commonly used near mine-mouth thermal power stations because long-distance transport is less economical.",sourceFactId:"COAL-LIGNITE"},
{stem:"Arrange these from lower to higher coal rank: peat, lignite, bituminous, anthracite. Which sequence is correct?",answer:"Peat → Lignite → Bituminous → Anthracite",distractors:["Anthracite → Bituminous → Lignite → Peat","Lignite → Peat → Anthracite → Bituminous","Bituminous → Anthracite → Peat → Lignite"],explanation:"Coal rank rises as carbon content and degree of coalification increase. The standard progression is peat, lignite, bituminous and finally anthracite.",sourceFactId:"COAL-RANK-SEQUENCE"},
{stem:"Consider the statements: I. Lignite is lower rank than bituminous coal. II. Anthracite is higher rank than bituminous coal. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Lignite lies below bituminous coal in rank, while anthracite lies above it. The sequence reflects increasing carbon content and coalification.",sourceFactId:"COAL-RANK-STATEMENT"},
{stem:"A coal sample is hard, lustrous and has very high carbon content. Which type is it?",answer:"Anthracite",distractors:["Lignite","Peat","Brown coal"],explanation:"Hardness, lustre and high carbon content are characteristic of anthracite. These clues separate it from softer and more moisture-rich lower-rank coals.",sourceFactId:"COAL-RANK-CLUE"}
]),
q("GONDWANA-AND-TERTIARY-COAL","Gondwana and Tertiary coal",[
{stem:"Most of India's major coalfields belong to which geological age group?",answer:"Gondwana",distractors:["Tertiary only","Recent alluvium","Archaean granite"],explanation:"The large coalfields of peninsular India are chiefly Gondwana in age. They occur in river-valley basins such as the Damodar, Son, Mahanadi and Godavari systems.",sourceFactId:"COAL-GONDWANA"},
{stem:"Tertiary coal in India is especially linked with which region?",answer:"North-eastern India",distractors:["Punjab plains","Western Rajasthan desert only","Kerala coast only"],explanation:"Tertiary coal occurs prominently in the north-eastern states, including Assam and adjoining regions. This contrasts with the major Gondwana coalfields of peninsular India.",sourceFactId:"COAL-TERTIARY-NE"},
{stem:"Consider the statements: I. Jharia is a Gondwana coalfield. II. Makum is linked with Tertiary coal. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Jharia in Jharkhand belongs to the Gondwana coal system, while Makum in Assam is a well-known Tertiary coalfield. The pair illustrates India's two major coal-age groupings.",sourceFactId:"COAL-GONDWANA-TERTIARY"},
{stem:"Which pair is correctly matched?",answer:"Makum — Tertiary coal",distractors:["Jharia — Tertiary coal","Raniganj — lignite only","Talcher — recent peat"],explanation:"Makum in Assam is a classic Tertiary coalfield. Jharia, Raniganj and Talcher belong to the older Gondwana coal system.",sourceFactId:"COAL-MAKUM-MATCH"},
{stem:"A coalfield lies in the Damodar valley. Which geological group is it most likely to belong to?",answer:"Gondwana coal",distractors:["Tertiary coal","Recent peat only","Marine evaporite"],explanation:"The Damodar valley hosts classic Gondwana coalfields such as Jharia, Raniganj and Bokaro. Their geology differs from the younger Tertiary coalfields of the north-east.",sourceFactId:"COAL-DAMODAR-GONDWANA"},
{stem:"Why are Gondwana coalfields especially important in Indian economic geography?",answer:"They contain most of the country's major bituminous coalfields",distractors:["They are confined to coastal salt pans","They contain only lignite","They occur only in the Himalayas"],explanation:"India's major bituminous coalfields are concentrated in Gondwana basins of peninsular India. These fields support thermal power, steel and other heavy industries.",sourceFactId:"COAL-GONDWANA-IMPORTANCE"}
]),
q("JHARIA-COALFIELD","Jharia coalfield",[
{stem:"Jharia coalfield is located in which state?",answer:"Jharkhand",distractors:["Odisha","Chhattisgarh","Assam"],explanation:"Jharia lies in Jharkhand and is one of India's most important coalfields. It is especially known for prime coking coal used by the iron and steel industry.",sourceFactId:"COAL-JHARIA-STATE"},
{stem:"Which type of coal gives Jharia special importance to the steel industry?",answer:"Coking coal",distractors:["Lignite","Peat","Only anthracite"],explanation:"Jharia is renowned for high-quality coking coal, which can be converted into coke for blast-furnace iron making. This gives it a direct connection with the steel industry.",sourceFactId:"COAL-JHARIA-COKING"},
{stem:"Consider the statements: I. Jharia is in the Damodar valley. II. It is important for coking coal. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Jharia is a Damodar-valley coalfield in Jharkhand and one of India's best-known coking-coal regions. Both its location and industrial significance are exam-relevant.",sourceFactId:"COAL-JHARIA-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Jharia — coking coal",distractors:["Jharia — lignite only","Jharia — petroleum","Jharia — mica"],explanation:"Jharia is strongly associated with coking coal. Lignite, petroleum and mica have different principal geographical centres.",sourceFactId:"COAL-JHARIA-MATCH"},
{stem:"Which heavy industry has the most direct raw-material link with Jharia coalfield?",answer:"Iron and steel industry",distractors:["Tea processing","Jute spinning","Sugar milling"],explanation:"Coking coal from Jharia is used to make coke for iron and steel production. That creates a direct mineral-industry connection with the eastern steel belt.",sourceFactId:"COAL-JHARIA-STEEL"},
{stem:"A map marks Dhanbad and Jharia together. Which resource should be identified?",answer:"Coal",distractors:["Bauxite","Petroleum","Mica"],explanation:"Dhanbad and Jharia form one of India's most famous coal-mining clusters in Jharkhand. Their appearance together is a strong coal-map clue.",sourceFactId:"COAL-JHARIA-MAP"}
]),
q("RANIGANJ-COALFIELD","Raniganj coalfield",[
{stem:"Raniganj coalfield is primarily located in which state?",answer:"West Bengal",distractors:["Jharkhand","Odisha","Maharashtra"],explanation:"Raniganj lies mainly in West Bengal and extends into adjoining Jharkhand. It is one of India's oldest and most historically important coal-mining regions.",sourceFactId:"COAL-RANIGANJ-STATE"},
{stem:"Which river-valley coal system includes Raniganj?",answer:"Damodar valley",distractors:["Narmada valley","Godavari delta only","Cauvery delta"],explanation:"Raniganj is part of the Damodar-valley coal belt along with Jharia and Bokaro. This valley forms a major coal-and-industry corridor in eastern India.",sourceFactId:"COAL-RANIGANJ-DAMODAR"},
{stem:"Consider the statements: I. Raniganj is a Gondwana coalfield. II. It lies in the eastern Indian coal belt. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Raniganj is a Gondwana-age coalfield in eastern India, centred in West Bengal. Both statements correctly identify its geology and regional setting.",sourceFactId:"COAL-RANIGANJ-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Raniganj — West Bengal coalfield",distractors:["Raniganj — Assam petroleum field","Raniganj — Tamil Nadu lignite only","Raniganj — Rajasthan gypsum"],explanation:"Raniganj is one of West Bengal's classic coalfields. The alternative resource-location pairs are unrelated.",sourceFactId:"COAL-RANIGANJ-MATCH"},
{stem:"Which coalfield lies farther east: Jharia or Raniganj?",answer:"Raniganj",distractors:["Jharia","Both occupy the same point","Neither lies in eastern India"],explanation:"Raniganj is centred in West Bengal, east of Jharia in Jharkhand. Both belong to the Damodar coal belt but occupy different positions along it.",sourceFactId:"COAL-RANIGANJ-COMPARE"},
{stem:"A question links Asansol industrial region with a nearby major coalfield. Which coalfield is it?",answer:"Raniganj",distractors:["Makum","Singrauli","Neyveli"],explanation:"The Asansol-Durgapur industrial belt developed close to Raniganj coalfield in West Bengal. Coal availability was a major locational advantage for heavy industry.",sourceFactId:"COAL-RANIGANJ-ASANSOL"}
]),
q("BOKARO-KARANPURA-DAMODAR-COALFIELDS","Bokaro and Karanpura coalfields",[
{stem:"East and West Bokaro coalfields are located in which state?",answer:"Jharkhand",distractors:["Odisha","Chhattisgarh","Tamil Nadu"],explanation:"East and West Bokaro are important Gondwana coalfields of Jharkhand. They form part of the broader Damodar-valley coal region.",sourceFactId:"COAL-BOKARO"},
{stem:"North and South Karanpura coalfields belong to which major coal region?",answer:"Jharkhand's Gondwana coal belt",distractors:["Tamil Nadu lignite belt","Assam Tertiary coal belt","Rajasthan salt belt"],explanation:"North and South Karanpura lie in Jharkhand and are Gondwana coalfields. They form part of the extensive coal-bearing basins of eastern peninsular India.",sourceFactId:"COAL-KARANPURA"},
{stem:"Consider the statements: I. Bokaro is a coalfield name as well as a steel-city name. II. Bokaro coalfield lies in Jharkhand. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Bokaro is known both for coal resources and for a major steel centre in Jharkhand. The close relationship reflects the coal-and-steel geography of the Damodar region.",sourceFactId:"COAL-BOKARO-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Karanpura — Jharkhand coalfield",distractors:["Karanpura — Gujarat petroleum basin","Bokaro — Tamil Nadu lignite","Karanpura — Kerala beach sand"],explanation:"Karanpura is a coalfield of Jharkhand, while Bokaro is another major coalfield in the same state. The other options combine unrelated regions and resources.",sourceFactId:"COAL-KARANPURA-MATCH"},
{stem:"Which set contains only Damodar-region coalfields?",answer:"Jharia, Raniganj and Bokaro",distractors:["Neyveli, Makum and Jharia","Talcher, Neyveli and Bokaro","Singrauli, Makum and Raniganj"],explanation:"Jharia, Raniganj and Bokaro all belong to the Damodar-valley coal system. Neyveli is lignite, Makum is Tertiary coal and Talcher/Singrauli belong to other basins.",sourceFactId:"COAL-DAMODAR-SET"},
{stem:"Why did the Damodar valley become a major heavy-industry corridor?",answer:"Its coalfields lie close to iron-ore and industrial centres",distractors:["It has no mineral resources","It depends only on imported coal","It is India's principal oil offshore basin"],explanation:"The Damodar region combines major coalfields with proximity to iron ore, transport routes and industrial markets. This helped concentrate steel, power and engineering industries in eastern India.",sourceFactId:"COAL-DAMODAR-INDUSTRY"}
]),
q("TALCHER-AND-IB-VALLEY-COALFIELDS","Talcher and Ib Valley coalfields",[
{stem:"Talcher coalfield is located in which state?",answer:"Odisha",distractors:["Jharkhand","Assam","Tamil Nadu"],explanation:"Talcher is a major Gondwana coalfield of Odisha. It is one of the country's important thermal-coal regions and supports large power and industrial complexes.",sourceFactId:"COAL-TALCHER"},
{stem:"Ib Valley coalfield belongs to which state?",answer:"Odisha",distractors:["West Bengal","Madhya Pradesh","Rajasthan"],explanation:"Ib Valley is another major coalfield in Odisha, extending through the western part of the state. Together with Talcher it forms the core of Odisha's coal geography.",sourceFactId:"COAL-IB-VALLEY"},
{stem:"Consider the statements: I. Talcher and Ib Valley are both in Odisha. II. Both are Gondwana coalfields. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Talcher and Ib Valley are major Gondwana coalfields of Odisha. Their coal supports thermal power and mineral-based industries.",sourceFactId:"COAL-ODISHA-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Talcher — Odisha coalfield",distractors:["Talcher — Assam petroleum field","Ib Valley — Tamil Nadu lignite only","Talcher — Rajasthan copper"],explanation:"Talcher is an Odisha coalfield, and Ib Valley is another major coal region in the state. The other pairings are incorrect.",sourceFactId:"COAL-TALCHER-MATCH"},
{stem:"A map marks Talcher and Ib Valley. Which resource is the common theme?",answer:"Coal",distractors:["Mica","Bauxite only","Natural gas only"],explanation:"Talcher and Ib Valley are both major coalfields in Odisha. Their joint appearance on a map clearly indicates coal geography.",sourceFactId:"COAL-ODISHA-MAP"},
{stem:"Which state combines Talcher coal with major iron ore and chromite resources?",answer:"Odisha",distractors:["Punjab","Kerala","Haryana"],explanation:"Odisha has a diversified mineral base including coal, iron ore and chromite. This combination gives the state a strong foundation for power, steel and ferro-alloy industries.",sourceFactId:"COAL-ODISHA-INTEGRATED"}
]),
q("SINGRAULI-COALFIELD","Singrauli coalfield",[
{stem:"Singrauli coalfield extends across which two states?",answer:"Madhya Pradesh and Uttar Pradesh",distractors:["Odisha and Jharkhand","Tamil Nadu and Kerala","Rajasthan and Gujarat"],explanation:"Singrauli straddles northeastern Madhya Pradesh and southeastern Uttar Pradesh. It is a major coal-and-thermal-power region of central India.",sourceFactId:"COAL-SINGRAULI-STATES"},
{stem:"Which activity is especially concentrated around Singrauli because of abundant coal?",answer:"Thermal power generation",distractors:["Marine fishing","Tea plantation","Jute retting"],explanation:"Large coal deposits and mine-mouth power stations have made Singrauli one of India's major thermal-power clusters. Coal availability is the key locational factor.",sourceFactId:"COAL-SINGRAULI-POWER"},
{stem:"Consider the statements: I. Singrauli is a coalfield. II. It is linked with major thermal power plants. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Singrauli is both a major coalfield and a large thermal-power region. The resource and industry are closely connected geographically.",sourceFactId:"COAL-SINGRAULI-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Singrauli — coal and thermal power",distractors:["Singrauli — mica belt","Singrauli — offshore oil","Singrauli — marine salt"],explanation:"Singrauli is famous for coal mining and coal-based power generation. The other resources have different geographical centres.",sourceFactId:"COAL-SINGRAULI-MATCH"},
{stem:"A map highlights the border area of Madhya Pradesh and Uttar Pradesh with a major coal-power complex. Which region is it?",answer:"Singrauli",distractors:["Raniganj","Makum","Neyveli"],explanation:"Singrauli lies across the Madhya Pradesh–Uttar Pradesh border and is a classic coal-power complex. The location clues distinguish it from eastern or southern coal regions.",sourceFactId:"COAL-SINGRAULI-MAP"},
{stem:"Why are very large thermal plants often located close to Singrauli coal mines?",answer:"Coal is bulky, so mine-mouth location reduces transport requirements",distractors:["Coal can only burn underground","Power plants require sea water only","The area has no transmission links"],explanation:"Thermal stations consume large volumes of coal. Locating them close to mines reduces the cost and logistical burden of transporting this bulky fuel.",sourceFactId:"COAL-SINGRAULI-REASONING"}
]),
q("KORBA-MAND-RAIGARH-COALFIELDS","Korba and Mand-Raigarh coalfields",[
{stem:"Korba coalfield is located in which state?",answer:"Chhattisgarh",distractors:["Jharkhand","Odisha","Assam"],explanation:"Korba is one of Chhattisgarh's major coalfields and a major thermal-power centre. Its coal resources have supported extensive power generation and industry.",sourceFactId:"COAL-KORBA"},
{stem:"Mand-Raigarh coalfield belongs to which state?",answer:"Chhattisgarh",distractors:["Maharashtra","West Bengal","Tamil Nadu"],explanation:"Mand-Raigarh is an important coalfield of Chhattisgarh. Along with Korba, it forms a major part of the state's coal-resource geography.",sourceFactId:"COAL-MAND-RAIGARH"},
{stem:"Consider the statements: I. Korba is a coalfield. II. Chhattisgarh is an important coal-bearing state. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Korba is a major Chhattisgarh coalfield, and the state contains several important coal basins. Both statements are therefore correct.",sourceFactId:"COAL-KORBA-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Mand-Raigarh — Chhattisgarh",distractors:["Mand-Raigarh — Assam","Korba — Tamil Nadu lignite","Korba — Gujarat petroleum"],explanation:"Mand-Raigarh and Korba are both important Chhattisgarh coal regions. The other pairings attach them to unrelated resources and states.",sourceFactId:"COAL-CHHATTISGARH-MATCH"},
{stem:"Which state is identified by the clues 'Korba coalfield, Mand-Raigarh coalfield and major thermal power generation'?",answer:"Chhattisgarh",distractors:["Punjab","Kerala","Goa"],explanation:"Korba and Mand-Raigarh are both in Chhattisgarh, and the state's coal resources support large thermal-power capacities. The combination strongly identifies Chhattisgarh.",sourceFactId:"COAL-CHHATTISGARH-CLUE"},
{stem:"Which comparison is correct?",answer:"Korba is in Chhattisgarh, while Talcher is in Odisha",distractors:["Both are in Assam","Korba is in Odisha and Talcher in Chhattisgarh","Both are lignite fields in Tamil Nadu"],explanation:"Korba and Talcher are important coalfields in neighbouring mineral-rich states, Chhattisgarh and Odisha respectively. Both support large power and industrial complexes.",sourceFactId:"COAL-KORBA-TALCHER"}
]),
q("GODAVARI-AND-WARDHA-VALLEY-COAL","Godavari and Wardha valley coalfields",[
{stem:"The Godavari Valley coalfields are located in which state?",answer:"Telangana",distractors:["Punjab","Rajasthan","Kerala"],explanation:"The Godavari Valley coal belt is centred in Telangana and is worked extensively by Singareni Collieries. It is a major Gondwana coal region of southern India.",sourceFactId:"COAL-GODAVARI"},
{stem:"Wardha Valley coalfield is located in which state?",answer:"Maharashtra",distractors:["Assam","West Bengal","Tamil Nadu"],explanation:"Wardha Valley is an important coalfield of Maharashtra. It forms part of the state's Gondwana coal resources along with fields such as Kamptee.",sourceFactId:"COAL-WARDHA"},
{stem:"Consider the statements: I. Godavari Valley coal is linked with Telangana. II. Wardha Valley coal is linked with Maharashtra. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Godavari Valley is a major Telangana coal belt, while Wardha Valley lies in Maharashtra. Both are important southern-central Gondwana coal regions.",sourceFactId:"COAL-GODAVARI-WARDHA"},
{stem:"Which pair is correctly matched?",answer:"Godavari Valley — Telangana coal",distractors:["Godavari Valley — Rajasthan lignite","Wardha Valley — Assam Tertiary coal","Godavari Valley — offshore petroleum only"],explanation:"The Godavari Valley coalfields are chiefly in Telangana. Wardha belongs to Maharashtra, while Assam's coal is associated with north-eastern Tertiary basins.",sourceFactId:"COAL-GODAVARI-MATCH"},
{stem:"Which coalfield is linked with Singareni Collieries?",answer:"Godavari Valley",distractors:["Raniganj","Jharia","Makum"],explanation:"Singareni Collieries operates in the Godavari Valley coalfields of Telangana. This company-region link is a durable feature of southern India's coal geography.",sourceFactId:"COAL-SINGARENI"},
{stem:"A map shows major coal deposits in Telangana along the Godavari basin. Which coal age is expected?",answer:"Gondwana",distractors:["Tertiary only","Recent peat","Marine salt"],explanation:"The Godavari Valley coalfields belong to the Gondwana system, like most major peninsular coal basins. Tertiary coal is more characteristic of north-eastern India.",sourceFactId:"COAL-GODAVARI-GONDWANA"}
]),
q("LIGNITE-NEYVELI-AND-OTHER-FIELDS","Lignite and Neyveli",[
{stem:"Neyveli is famous for deposits of which fuel mineral?",answer:"Lignite",distractors:["Anthracite","Petroleum","Natural gas"],explanation:"Neyveli in Tamil Nadu is India's classic lignite-mining region. Its brown coal supports large mine-mouth thermal-power stations and associated industries.",sourceFactId:"LIGNITE-NEYVELI"},
{stem:"Neyveli lignite field is located in which state?",answer:"Tamil Nadu",distractors:["Rajasthan","Gujarat","Jharkhand"],explanation:"Neyveli lies in Cuddalore district of Tamil Nadu and is the country's best-known lignite field. It has long supported lignite mining and power generation.",sourceFactId:"LIGNITE-NEYVELI-STATE"},
{stem:"Consider the statements: I. Lignite has higher moisture than bituminous coal. II. Neyveli is a major lignite field. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Lignite is a lower-rank, moisture-rich coal, and Neyveli is India's most familiar lignite region. The two facts are directly connected in exam geography.",sourceFactId:"LIGNITE-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Neyveli — lignite",distractors:["Jharia — lignite only","Makum — Neyveli lignite belt","Neyveli — coking coal"],explanation:"Neyveli is synonymous with lignite in Tamil Nadu. Jharia is famous for coking coal and Makum for Tertiary coal in Assam.",sourceFactId:"LIGNITE-MATCH"},
{stem:"Why are lignite-based thermal plants commonly located close to the mine?",answer:"Lignite is bulky and moisture-rich, making long-distance transport less efficient",distractors:["Lignite cannot be burned in power plants","It is available only offshore","It must be transported by pipeline"],explanation:"Lignite contains relatively high moisture and has lower energy density than higher-rank coals. Mine-mouth power generation therefore reduces transport cost and energy loss.",sourceFactId:"LIGNITE-MINEMOUTH"},
{stem:"Which state pair contains important lignite resources in addition to Tamil Nadu?",answer:"Rajasthan and Gujarat",distractors:["Punjab and Haryana only","Jharkhand and West Bengal only","Kerala and Goa only"],explanation:"Besides Tamil Nadu, significant lignite resources occur in western India, particularly Rajasthan and Gujarat. These deposits support additional lignite-based energy projects.",sourceFactId:"LIGNITE-WESTERN-INDIA"}
])
]);

export const GEO_MIN_001_CP006_REVIEW_BATCH_V1 = finalizeGeoMinCp(6, QLS);
export function auditGeoMin001Cp006ReviewBatchV1() { return auditGeoMinCp(6, QLS, GEO_MIN_001_CP006_REVIEW_BATCH_V1); }
