import { buildGeoMinQl, finalizeGeoMinCp, auditGeoMinCp } from "./geo-min-001-review-builder";

const HC_SRC = ["NCERT-CLASS10-CONTEMPORARY-INDIA-II-CH5-MINERALS-ENERGY-2025-26","DGH-INDIA-HYDROCARBON-OUTLOOK-2024","DGH-INDIAN-SEDIMENTARY-BASINS"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoMinQl(key,name,rows.map((r:any)=>({...r,sourceIds:HC_SRC})) as any);

const QLS = Object.freeze([
q("PETROLEUM-FORMATION-AND-SEDIMENTARY-BASINS","Petroleum formation and sedimentary basins",[
{stem:"Petroleum and natural gas are most commonly found in which type of geological basin?",answer:"Sedimentary basin",distractors:["Massive granite shield only","Recent alluvial plain only","Metamorphic core complex only"],explanation:"Petroleum and natural gas accumulate mainly in sedimentary basins where organic-rich sediments have been buried, transformed and trapped. India's hydrocarbon exploration is therefore organised largely around sedimentary basins.",sourceFactId:"HC-SEDIMENTARY-BASINS"},
{stem:"Why are porous reservoir rocks important in petroleum occurrence?",answer:"They can store oil and gas in interconnected pore spaces",distractors:["They create petroleum by themselves","They prevent all fluid movement","They contain only metallic ores"],explanation:"Reservoir rocks such as sandstone or limestone may contain connected pore spaces that hold hydrocarbons. A suitable seal is also needed to keep oil and gas from escaping.",sourceFactId:"HC-RESERVOIR-ROCK"},
{stem:"Consider the statements: I. Petroleum commonly accumulates in sedimentary basins. II. A sealing rock can help trap hydrocarbons. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Hydrocarbons typically form and migrate within sedimentary systems, then accumulate where porous reservoirs are capped by impermeable rocks. Both basin setting and trapping are important.",sourceFactId:"HC-BASIN-TRAP"},
{stem:"Which pair is correctly matched?",answer:"Reservoir rock — stores hydrocarbons",distractors:["Seal rock — generates all crude oil directly","Granite batholith — standard oil reservoir in every field","Coal seam — petroleum trap in all basins"],explanation:"A reservoir rock stores hydrocarbons in pore spaces, while a sealing rock prevents their upward escape. The distinction is basic to petroleum geology.",sourceFactId:"HC-RESERVOIR-MATCH"},
{stem:"An oilfield is discovered in porous sandstone beneath an impermeable shale layer. What is the shale doing?",answer:"Acting as a seal",distractors:["Acting as the main metal ore","Producing electricity directly","Forming a placer deposit"],explanation:"Impermeable shale can cap a porous reservoir and prevent hydrocarbons from migrating farther upward. This sealing function allows oil and gas to accumulate in a trap.",sourceFactId:"HC-SHALE-SEAL"},
{stem:"Why does India map sedimentary basins for hydrocarbon exploration?",answer:"Because these basins contain the geological systems in which oil and gas can form and accumulate",distractors:["Because petroleum forms only in igneous dykes","Because all sedimentary basins contain commercial oil","Because basin mapping is unrelated to exploration"],explanation:"Sedimentary basins provide source rocks, reservoirs, seals and traps needed for petroleum systems. Not every basin is commercially productive, but basin mapping is fundamental to exploration.",sourceFactId:"HC-BASIN-EXPLORATION"}
]),
q("ASSAM-OIL-DIGBOI-NAHARKATIYA-MORAN","Assam oilfields: Digboi, Naharkatiya and Moran",[
{stem:"Digboi, one of India's oldest oil-producing centres, is located in which state?",answer:"Assam",distractors:["Gujarat","Rajasthan","Odisha"],explanation:"Digboi is in Assam and is one of the country's historic petroleum centres. It is part of the long-established hydrocarbon geography of north-eastern India.",sourceFactId:"HC-DIGBOI"},
{stem:"Which resource is most strongly linked with Digboi?",answer:"Petroleum",distractors:["Iron ore","Bauxite","Mica"],explanation:"Digboi is a classic oilfield and refinery location in Assam. It should not be confused with metallic-mineral centres such as Bailadila or Khetri.",sourceFactId:"HC-DIGBOI-RESOURCE"},
{stem:"Consider the statements: I. Naharkatiya is an oilfield in Assam. II. Moran is also linked with Assam petroleum. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Naharkatiya and Moran are both important oil-producing areas in Assam. Together with Digboi they form a classic set of north-eastern petroleum locations.",sourceFactId:"HC-ASSAM-FIELDS"},
{stem:"Which pair is correctly matched?",answer:"Naharkatiya — petroleum",distractors:["Naharkatiya — chromite","Moran — mica only","Digboi — iron ore"],explanation:"Naharkatiya is a petroleum field in Assam, as are Moran and Digboi. The other mineral-resource pairings are incorrect.",sourceFactId:"HC-NAHARKATIYA-MATCH"},
{stem:"A map marks Digboi, Naharkatiya and Moran. Which resource should be identified?",answer:"Oil and natural gas",distractors:["Mica","Bauxite","Gypsum"],explanation:"All three locations belong to Assam's petroleum geography. Their joint appearance on a map strongly indicates hydrocarbons rather than solid minerals.",sourceFactId:"HC-ASSAM-MAP"},
{stem:"Which comparison is correct?",answer:"Digboi is in Assam, while Ankleshwar is in Gujarat",distractors:["Both are in Rajasthan","Digboi is in Gujarat and Ankleshwar in Assam","Both are offshore fields"],explanation:"Digboi is a historic onshore oil centre in Assam, whereas Ankleshwar is a major onshore petroleum field in Gujarat. The contrast is useful for state-location questions.",sourceFactId:"HC-DIGBOI-ANKLESHWAR"}
]),
q("CAMBAY-BASIN-AND-ANKLESHWAR","Cambay basin and Ankleshwar",[
{stem:"Ankleshwar oilfield is located in which state?",answer:"Gujarat",distractors:["Assam","Odisha","Tamil Nadu"],explanation:"Ankleshwar is one of Gujarat's major onshore petroleum fields and lies within the Cambay basin. It is a standard western India hydrocarbon location.",sourceFactId:"HC-ANKLESHWAR"},
{stem:"Which sedimentary basin is strongly linked with Gujarat's onshore petroleum production?",answer:"Cambay basin",distractors:["Damodar basin","Panna diamond tract","Sukinda valley"],explanation:"The Cambay basin is one of India's established hydrocarbon-producing basins and contains important fields in Gujarat. It is unrelated to coal or metallic-mineral regions.",sourceFactId:"HC-CAMBAY"},
{stem:"Consider the statements: I. Ankleshwar lies in Gujarat. II. It belongs to the Cambay petroleum basin. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Ankleshwar is an onshore petroleum field in Gujarat within the Cambay basin. Both statements correctly identify its state and basin.",sourceFactId:"HC-ANKLESHWAR-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Cambay basin — Gujarat hydrocarbons",distractors:["Cambay basin — Jharkhand coal","Ankleshwar — Rajasthan lignite","Cambay — mica belt"],explanation:"The Cambay basin is a major hydrocarbon basin of Gujarat, with fields such as Ankleshwar. The alternative pairs mix unrelated resources.",sourceFactId:"HC-CAMBAY-MATCH"},
{stem:"Which field is a better example of western India's onshore petroleum geography?",answer:"Ankleshwar",distractors:["Jharia","Koderma","Bailadila"],explanation:"Ankleshwar is a major Gujarat oilfield in the Cambay basin. Jharia is coal, Koderma mica and Bailadila iron ore.",sourceFactId:"HC-ANKLESHWAR-CLUE"},
{stem:"Why is the Cambay basin important in India's petroleum map?",answer:"It contains established onshore oil and gas fields in Gujarat",distractors:["It is India's principal iron-ore belt","It contains only lignite","It lies entirely outside India"],explanation:"The Cambay basin has long-established hydrocarbon production and several onshore fields in Gujarat. Its petroleum significance is durable and independent of annual production rankings.",sourceFactId:"HC-CAMBAY-IMPORTANCE"}
]),
q("MUMBAI-OFFSHORE-AND-MUMBAI-HIGH","Mumbai Offshore and Mumbai High",[
{stem:"Mumbai High is located in which setting?",answer:"Offshore in the Arabian Sea",distractors:["Onshore Assam valley","Rajasthan desert","Damodar coal basin"],explanation:"Mumbai High is an offshore oilfield in the Arabian Sea west of Mumbai. It is one of India's most familiar offshore petroleum locations.",sourceFactId:"HC-MUMBAI-HIGH-SETTING"},
{stem:"Which resource is most strongly linked with Mumbai High?",answer:"Petroleum",distractors:["Iron ore","Mica","Gypsum"],explanation:"Mumbai High is a major offshore petroleum field. Its location distinguishes it from onshore fields such as Digboi and Ankleshwar.",sourceFactId:"HC-MUMBAI-HIGH-RESOURCE"},
{stem:"Consider the statements: I. Mumbai High is offshore. II. It lies in the Mumbai Offshore basin. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Mumbai High is an offshore field in the Mumbai Offshore basin of the Arabian Sea. Both statements correctly describe its petroleum geography.",sourceFactId:"HC-MUMBAI-HIGH-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Mumbai High — offshore oilfield",distractors:["Mumbai High — inland coalfield","Mumbai High — mica belt","Mumbai High — lignite field"],explanation:"Mumbai High is a classic offshore oilfield. Coal, mica and lignite have completely different geological and geographical settings.",sourceFactId:"HC-MUMBAI-HIGH-MATCH"},
{stem:"A map marks a petroleum field west of Mumbai in the Arabian Sea. Which field is it?",answer:"Mumbai High",distractors:["Digboi","Ankleshwar","Barmer"],explanation:"The major offshore field west of Mumbai is Mumbai High. Digboi, Ankleshwar and Barmer are onshore petroleum locations.",sourceFactId:"HC-MUMBAI-HIGH-MAP"},
{stem:"Which comparison is correct?",answer:"Mumbai High is offshore, while Ankleshwar is onshore",distractors:["Both are offshore","Both are in Assam","Mumbai High is a coalfield"],explanation:"Mumbai High lies offshore in the Arabian Sea, whereas Ankleshwar is an onshore field in Gujarat. The contrast is useful for identifying field type and location.",sourceFactId:"HC-OFFSHORE-ONSHORE"}
]),
q("RAJASTHAN-BARMER-PETROLEUM","Rajasthan and Barmer petroleum",[
{stem:"Barmer petroleum fields are located in which state?",answer:"Rajasthan",distractors:["Assam","Gujarat","Odisha"],explanation:"Barmer in western Rajasthan has become a major onshore petroleum region. It lies within the Rajasthan sedimentary basin.",sourceFactId:"HC-BARMER"},
{stem:"Which resource transformed Barmer into an important energy-producing district?",answer:"Crude oil",distractors:["Mica","Chromite","Iron ore"],explanation:"Large petroleum discoveries and development made Barmer a major crude-oil centre in western India. The district is part of the Rajasthan hydrocarbon basin.",sourceFactId:"HC-BARMER-OIL"},
{stem:"Consider the statements: I. Barmer is in Rajasthan. II. Rajasthan is an established hydrocarbon-producing basin. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Barmer lies in Rajasthan, and the Rajasthan basin is among India's established petroleum-producing basins. Both statements are correct.",sourceFactId:"HC-BARMER-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Barmer — petroleum",distractors:["Barmer — mica","Barmer — chromite","Barmer — Jharia coal"],explanation:"Barmer is a major petroleum centre in Rajasthan. The other resources belong to different mineral regions.",sourceFactId:"HC-BARMER-MATCH"},
{stem:"Which field-region comparison is correct?",answer:"Barmer is an onshore western Indian oil region, while Mumbai High is offshore",distractors:["Both are coalfields","Barmer is offshore and Mumbai High inland","Both are in Assam"],explanation:"Barmer represents onshore petroleum in Rajasthan, whereas Mumbai High is an offshore Arabian Sea field. The contrast captures two major western Indian hydrocarbon settings.",sourceFactId:"HC-BARMER-MUMBAI"},
{stem:"A map marks an oil-producing basin in western Rajasthan near the Pakistan border. Which district is the strongest clue?",answer:"Barmer",distractors:["Dhanbad","Koderma","Panna"],explanation:"Barmer is the principal modern petroleum clue for western Rajasthan. Dhanbad, Koderma and Panna are associated with coal, mica and diamond respectively.",sourceFactId:"HC-BARMER-MAP"}
]),
q("KRISHNA-GODAVARI-BASIN","Krishna-Godavari basin",[
{stem:"The Krishna-Godavari basin lies mainly along the coast of which state?",answer:"Andhra Pradesh",distractors:["Gujarat","Kerala","Punjab"],explanation:"The Krishna-Godavari basin extends across onshore and offshore areas along the Andhra Pradesh coast. It is one of India's established hydrocarbon-producing basins.",sourceFactId:"HC-KG-STATE"},
{stem:"Which resource is the Krishna-Godavari basin especially known for?",answer:"Oil and natural gas",distractors:["Mica only","Iron ore only","Gypsum only"],explanation:"The KG basin contains significant hydrocarbon discoveries and production, including important natural-gas accumulations. It spans both land and offshore portions of the east coast.",sourceFactId:"HC-KG-HYDROCARBON"},
{stem:"Consider the statements: I. The KG basin is on India's east coast. II. It has both onshore and offshore hydrocarbon areas. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The Krishna-Godavari basin lies along the Andhra Pradesh coast and extends offshore into the Bay of Bengal. Both settings are important to exploration and production.",sourceFactId:"HC-KG-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Krishna-Godavari basin — Andhra Pradesh coast",distractors:["KG basin — Rajasthan desert","KG basin — Jharkhand coal belt","KG basin — Koderma mica"],explanation:"The Krishna-Godavari basin is an east-coast sedimentary basin centred on Andhra Pradesh. The other pairings are unrelated.",sourceFactId:"HC-KG-MATCH"},
{stem:"A hydrocarbon map marks a major producing basin opening into the Bay of Bengal between the Krishna and Godavari deltas. Which basin is it?",answer:"Krishna-Godavari basin",distractors:["Cambay basin","Rajasthan basin","Assam Shelf"],explanation:"The basin between the Krishna and Godavari river systems is the Krishna-Godavari basin. Its coastal and offshore setting makes it a major east-coast hydrocarbon region.",sourceFactId:"HC-KG-MAP"},
{stem:"Which comparison is correct?",answer:"KG basin is on the east coast, while Mumbai Offshore is on the west coast",distractors:["Both are inland coal basins","KG basin is in Rajasthan","Mumbai Offshore is in the Bay of Bengal"],explanation:"The KG basin lies along the Andhra Pradesh coast facing the Bay of Bengal, while Mumbai Offshore lies in the Arabian Sea. The contrast is a useful coast-to-basin map relationship.",sourceFactId:"HC-KG-MUMBAI"}
]),
q("CAUVERY-BASIN-HYDROCARBONS","Cauvery basin hydrocarbons",[
{stem:"The Cauvery hydrocarbon basin lies mainly along which coast?",answer:"South-eastern coast of India",distractors:["North-western Himalayan belt","Punjab plains only","Western Rajasthan desert"],explanation:"The Cauvery basin occupies parts of Tamil Nadu and adjoining offshore areas along India's south-eastern coast. It is an established hydrocarbon-producing basin.",sourceFactId:"HC-CAUVERY-COAST"},
{stem:"Which state is most strongly linked with the onshore part of the Cauvery petroleum basin?",answer:"Tamil Nadu",distractors:["Punjab","Jharkhand","Rajasthan"],explanation:"The Cauvery basin's principal onshore areas lie in Tamil Nadu, with extensions offshore into the Bay of Bengal. The basin contains oil and gas fields.",sourceFactId:"HC-CAUVERY-STATE"},
{stem:"Consider the statements: I. Cauvery is a hydrocarbon basin. II. It has both onshore and offshore sectors. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The Cauvery basin contains established petroleum systems in both land and offshore areas. Its geography is therefore similar in this respect to the KG basin.",sourceFactId:"HC-CAUVERY-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Cauvery basin — Tamil Nadu hydrocarbons",distractors:["Cauvery basin — Jharkhand coal","Cauvery basin — Rajasthan copper","Cauvery basin — Koderma mica"],explanation:"The Cauvery basin is an oil-and-gas basin of Tamil Nadu and adjoining offshore waters. The alternative resources have different locations.",sourceFactId:"HC-CAUVERY-MATCH"},
{stem:"Which basin lies south of the Krishna-Godavari basin along India's east coast?",answer:"Cauvery basin",distractors:["Cambay basin","Assam Shelf","Rajasthan basin"],explanation:"Moving south along the east coast from the KG basin, the Cauvery basin occupies Tamil Nadu and adjacent offshore areas. Both are important east-coast hydrocarbon provinces.",sourceFactId:"HC-CAUVERY-MAP"},
{stem:"Which comparison is correct?",answer:"Cauvery is an east-coast basin, while Cambay is a western onshore basin",distractors:["Both are coalfields","Cauvery is in Assam","Cambay lies only in the Bay of Bengal"],explanation:"The Cauvery basin lies along Tamil Nadu's east coast, while the Cambay basin is centred in Gujarat in western India. Both produce hydrocarbons but occupy very different regions.",sourceFactId:"HC-CAUVERY-CAMBAY"}
]),
q("NATURAL-GAS-AND-ASSOCIATED-GAS","Natural gas and associated gas",[
{stem:"Natural gas found together with crude oil in the same reservoir is called what?",answer:"Associated gas",distractors:["Lignite gas","Producer gas only","Biogas"],explanation:"Associated natural gas occurs in petroleum reservoirs together with crude oil, either dissolved in the oil or as a gas cap. Non-associated gas occurs in gas reservoirs without significant crude oil.",sourceFactId:"HC-ASSOCIATED-GAS"},
{stem:"Which fuel consists chiefly of methane?",answer:"Natural gas",distractors:["Lignite","Coke","Barytes"],explanation:"Natural gas is composed predominantly of methane, though it can contain other hydrocarbons and gases. Its clean combustion and pipeline transport make it an important energy resource.",sourceFactId:"HC-METHANE"},
{stem:"Consider the statements: I. Natural gas can occur with petroleum. II. It can also occur in gas-dominant reservoirs. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Natural gas may occur as associated gas with crude oil or as non-associated gas in separate gas reservoirs. Both forms are common in petroleum systems.",sourceFactId:"HC-GAS-TYPES"},
{stem:"Which pair is correctly matched?",answer:"Natural gas — methane-rich fuel",distractors:["Natural gas — iron ore","Natural gas — non-metallic mineral","Natural gas — placer deposit"],explanation:"Natural gas is a gaseous hydrocarbon fuel dominated by methane. It is not a solid mineral or placer resource.",sourceFactId:"HC-GAS-MATCH"},
{stem:"Why is natural gas often transported through pipelines?",answer:"It can move continuously as a pressurised gas over long distances",distractors:["It is a solid ore","It cannot be compressed","It must be carried only in open trucks"],explanation:"Pipeline networks allow large volumes of gas to move continuously from producing basins to power plants, fertilizer factories, cities and other consumers.",sourceFactId:"HC-GAS-PIPELINE"},
{stem:"Which industry uses natural gas both as fuel and as feedstock for ammonia-based fertilizers?",answer:"Fertilizer industry",distractors:["Mica cutting only","Jute retting","Iron-ore mining only"],explanation:"Natural gas provides both energy and hydrogen-rich feedstock for ammonia production. This creates a strong link between gas infrastructure and nitrogenous-fertilizer plants.",sourceFactId:"HC-GAS-FERTILIZER"}
]),
q("INDIA-PRODUCING-SEDIMENTARY-BASINS","India's established producing sedimentary basins",[
{stem:"Which of the following is an established hydrocarbon-producing basin of India?",answer:"Mumbai Offshore",distractors:["Koderma mica belt","Jharia coalfield","Sukinda chromite valley"],explanation:"DGH classifies Mumbai Offshore among India's established commercially producing sedimentary basins. Koderma, Jharia and Sukinda are important mineral regions but not petroleum basins.",sourceFactId:"HC-PRODUCING-BASIN"},
{stem:"Which set contains only established hydrocarbon-producing basins?",answer:"Assam Shelf, Cambay and Krishna-Godavari",distractors:["Jharia, Raniganj and Bokaro","Koderma, Nellore and Ajmer","Sukinda, Bailadila and Khetri"],explanation:"Assam Shelf, Cambay and Krishna-Godavari are established petroleum basins. The other sets are coal, mica or metallic-mineral regions.",sourceFactId:"HC-PRODUCING-SET"},
{stem:"Consider the statements: I. Rajasthan is an established hydrocarbon-producing basin. II. Mumbai Offshore is also a producing basin. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"DGH recognises both Rajasthan and Mumbai Offshore among India's producing sedimentary basins. The classification reflects established commercial hydrocarbon production.",sourceFactId:"HC-PRODUCING-STATEMENT"},
{stem:"Which pair is correctly matched?",answer:"Assam Shelf — hydrocarbon-producing basin",distractors:["Assam Shelf — iron-ore belt","Cambay — mica belt","Rajasthan basin — coalfield only"],explanation:"Assam Shelf is a producing hydrocarbon basin, as are Cambay and Rajasthan. The alternative resource classifications are incorrect.",sourceFactId:"HC-PRODUCING-MATCH"},
{stem:"Which producing basin lies offshore west of Maharashtra?",answer:"Mumbai Offshore",distractors:["Cauvery","Assam Shelf","Rajasthan"],explanation:"Mumbai Offshore lies in the Arabian Sea west of Maharashtra. Cauvery is on the south-east coast, while Assam Shelf and Rajasthan are onshore basins.",sourceFactId:"HC-PRODUCING-OFFSHORE"},
{stem:"Which coast-to-basin pairing is correct?",answer:"Andhra Pradesh east coast — Krishna-Godavari basin",distractors:["Gujarat west coast — Assam Shelf","Tamil Nadu east coast — Rajasthan basin","Assam valley — Mumbai Offshore"],explanation:"The Krishna-Godavari basin occupies the Andhra Pradesh coast and adjoining offshore Bay of Bengal. The other geographic pairings are mismatched.",sourceFactId:"HC-PRODUCING-MAP"}
]),
q("INTEGRATED-INDIAN-PETROLEUM-MAP","Integrated Indian petroleum map reasoning",[
{stem:"Which sequence correctly moves from north-east to west to offshore west to east coast?",answer:"Digboi → Ankleshwar → Mumbai High → Krishna-Godavari",distractors:["Mumbai High → Digboi → Jharia → Koderma","Ankleshwar → Digboi → Panna → Talcher","KG basin → Digboi → Barmer → Jharia"],explanation:"Digboi lies in Assam, Ankleshwar in Gujarat, Mumbai High offshore west of Maharashtra and the KG basin on the Andhra Pradesh east coast. The sequence spans India's major petroleum regions.",sourceFactId:"HC-MAP-SEQUENCE"},
{stem:"Which location-resource pair is incorrect?",answer:"Jharia — petroleum",distractors:["Digboi — petroleum","Barmer — petroleum","Mumbai High — petroleum"],explanation:"Jharia is a coalfield in Jharkhand, whereas Digboi, Barmer and Mumbai High are petroleum locations. The question tests separation of coal and oil geography.",sourceFactId:"HC-MAP-NEGATIVE"},
{stem:"Consider the statements: I. Digboi is onshore. II. Mumbai High is offshore. III. KG basin has both onshore and offshore sectors. Which is correct?",answer:"I, II and III",distractors:["I and II only","II and III only","I and III only"],explanation:"Digboi is an onshore Assam oil centre, Mumbai High is offshore in the Arabian Sea, and the KG basin spans land and offshore areas. All three statements are correct.",sourceFactId:"HC-MAP-STATEMENT"},
{stem:"Which state-resource chain is correct?",answer:"Gujarat → Cambay basin → Ankleshwar oilfield",distractors:["Jharkhand → Cambay basin → Digboi","Assam → Rajasthan basin → Barmer","Tamil Nadu → Mumbai Offshore → Jharia"],explanation:"The Cambay basin lies in Gujarat and includes important onshore fields such as Ankleshwar. The other chains mix states, basins and fields incorrectly.",sourceFactId:"HC-MAP-CHAIN"},
{stem:"A map shows an offshore field in the Arabian Sea and an east-coast basin in the Bay of Bengal. Which pair fits?",answer:"Mumbai High and Krishna-Godavari basin",distractors:["Digboi and Jharia","Barmer and Khetri","Raniganj and Neyveli"],explanation:"Mumbai High represents Arabian Sea offshore petroleum, while the KG basin extends into the Bay of Bengal off Andhra Pradesh. The pair captures India's west/east offshore contrast.",sourceFactId:"HC-MAP-OFFSHORE"},
{stem:"Which comparison correctly distinguishes India's older and newer petroleum geographies?",answer:"Assam has historic fields such as Digboi, while Rajasthan includes the modern Barmer oil region",distractors:["Both are coal-only regions","Barmer is offshore and Digboi is in Gujarat","Neither region contains petroleum"],explanation:"Assam has some of India's oldest petroleum development around Digboi, while Barmer represents a major later-developed onshore oil region in Rajasthan. Both are durable petroleum map facts.",sourceFactId:"HC-ASSAM-BARMER"}
])
]);

export const GEO_MIN_001_CP007_REVIEW_BATCH_V1 = finalizeGeoMinCp(7, QLS);
export function auditGeoMin001Cp007ReviewBatchV1() { return auditGeoMinCp(7, QLS, GEO_MIN_001_CP007_REVIEW_BATCH_V1); }
