import type{Eng012AuthorityV1,Eng012CpId,Eng012Difficulty,Eng012Pair}from"./eng-012-authorities-v1";
type F={topic:string;template:string;natural:readonly[string,string,string,string];v1:readonly[string,string,string,string];v2:readonly[string,string,string,string]};
const pairs:readonly Eng012Pair[]=[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]];
function expand(prefix:string,cpId:Eng012CpId,difficulty:(i:number)=>Eng012Difficulty,fs:readonly F[]):Eng012AuthorityV1[]{const out:Eng012AuthorityV1[]=[];fs.forEach((f,i)=>pairs.forEach((swap,j)=>out.push({id:`${prefix}-${String(i+1).padStart(2,"0")}-${j+1}`,cpId,difficulty:difficulty(i),topic:f.topic,template:f.template,natural:f.natural,swap,cue1:`${f.natural[swap[0]-1]} fits position ${swap[0]}`,cue2:`${f.natural[swap[1]-1]} fits position ${swap[1]}`,variants:[f.v1,f.v2]})));return out;}
const standard:F[]=[
{topic:"school administration",template:"The school {1} parents about the revised {2} and asked students to carry identity {3} during the annual {4}.",natural:["informed","schedule","cards","event"],v1:["notified","timetable","passes","function"],v2:["advised","programme","cards","meeting"]},
{topic:"road safety",template:"Drivers should {1} speed near the marked {2} and remain {3} when children cross the {4}.",natural:["reduce","crossing","alert","road"],v1:["lower","junction","careful","street"],v2:["control","crosswalk","watchful","road"]},
{topic:"library use",template:"Students may {1} books from the library and must {2} them before the due {3} shown on the issue {4}.",natural:["borrow","return","date","slip"],v1:["take","restore","deadline","card"],v2:["issue","deposit","date","record"]},
{topic:"public office",template:"Applicants should {1} the form carefully and {2} the required documents before visiting the service {3} at the district {4}.",natural:["complete","attach","counter","office"],v1:["fill","carry","desk","centre"],v2:["submit","upload","window","office"]},
{topic:"weather advisory",template:"Heavy rain may {1} traffic on low-lying {2}, so commuters should allow extra {3} and avoid flooded {4}.",natural:["slow","roads","time","routes"],v1:["delay","streets","margin","sections"],v2:["affect","roads","time","areas"]},
{topic:"health routine",template:"Regular exercise can {1} fitness, reduce {2} and support a healthy daily {3} when combined with adequate {4}.",natural:["improve","stress","routine","sleep"],v1:["increase","tension","schedule","rest"],v2:["support","anxiety","habit","sleep"]},
{topic:"water conservation",template:"Residents should {1} leaking taps, keep water from {2} unnecessarily and use a bucket while washing a {3} or cleaning the {4}.",natural:["repair","running","vehicle","floor"],v1:["fix","flowing","car","yard"],v2:["report","running","bike","driveway"]},
{topic:"school event",template:"The principal {1} the winners during the morning {2} and later {3} certificates in the school {4}.",natural:["congratulated","assembly","distributed","hall"],v1:["praised","function","presented","auditorium"],v2:["announced","meeting","gave","campus"]},
{topic:"public transport",template:"Passengers should {1} their ticket until the end of the {2} and keep their luggage {3} throughout the entire {4}.",natural:["retain","journey","secure","trip"],v1:["keep","ride","safe","journey"],v2:["hold","travel","close","trip"]},
{topic:"recycling",template:"Clean paper should be {1} from wet waste before it is {2} for recycling at the local collection {3} near the municipal {4}.",natural:["separated","sent","centre","yard"],v1:["removed","taken","point","depot"],v2:["kept apart","delivered","centre","site"]},
{topic:"exam preparation",template:"A realistic study {1} helps students divide their {2}, revise difficult {3} and prepare calmly for the final {4}.",natural:["plan","time","topics","exam"],v1:["schedule","hours","chapters","test"],v2:["routine","effort","areas","paper"]},
{topic:"public park",template:"Visitors should {1} litter in the bins provided, avoid {2} plants and remain on the walking {3} inside the public {4}.",natural:["place","damaging","path","park"],v1:["put","harming","track","garden"],v2:["drop","touching","trail","park"]},
{topic:"meeting",template:"The chairperson {1} the main issue, kept comments {2} and helped the meeting {3} on {4}.",natural:["introduced","brief","finish","time"],v1:["raised","short","end","schedule"],v2:["discussed","focused","close","time"]},
{topic:"electricity",template:"Households can {1} electricity by switching off unused {2}, choosing efficient {3} and avoiding unnecessary daytime {4}.",natural:["save","lights","appliances","use"],v1:["conserve","fans","devices","consumption"],v2:["reduce","bulbs","equipment","usage"]},
{topic:"digital safety",template:"Users should {1} strong passwords, protect account {2}, avoid suspicious {3} and report unusual activity by {4}.",natural:["create","details","links","email"],v1:["use","credentials","pages","message"],v2:["choose","information","links","phone"]},
{topic:"rainwater harvesting",template:"The building {1} rainwater from the roof, sends it through a {2}, stores it in a {3} and uses it later for garden {4}.",natural:["collects","filter","tank","watering"],v1:["captures","screen","reservoir","irrigation"],v2:["channels","filter","container","use"]}
];
const advanced:F[]=[
{topic:"evidence",template:"A strong argument should {1} relevant evidence, clearly {2} the central {3} and avoid unrelated {4}.",natural:["present","support","claim","information"],v1:["include","explain","conclusion","detail"],v2:["use","justify","argument","material"]},
{topic:"measurement",template:"A useful performance {1} should reflect the real {2}, discourage gaming the measured {3} and preserve attention to wider {4}.",natural:["metric","objective","number","outcomes"],v1:["indicator","goal","score","results"],v2:["measure","purpose","target","effects"]},
{topic:"risk communication",template:"Risk messages should {1} the probability, provide enough {2}, help readers {3} the figure and avoid unnecessary {4}.",natural:["state","context","interpret","alarm"],v1:["show","background","understand","fear"],v2:["present","comparison","read","confusion"]},
{topic:"policy evaluation",template:"Researchers should {1} outcomes, identify a credible {2}, avoid falsely {3} change to the policy and draw a careful {4}.",natural:["compare","counterfactual","attributing","conclusion"],v1:["examine","baseline","crediting","inference"],v2:["contrast","comparison","linking","finding"]},
{topic:"forecasting",template:"A forecast should {1} its assumptions, help users {2} uncertainty, update the original {3} and explain any major {4}.",natural:["state","judge","estimate","revision"],v1:["list","assess","projection","update"],v2:["show","understand","forecast","change"]},
{topic:"automation",template:"Automated systems can {1} routine decisions, flag unusual {2}, use available {3} and refer exceptional cases for human {4}.",natural:["process","cases","data","review"],v1:["handle","exceptions","information","checking"],v2:["make","cases","input","oversight"]},
{topic:"survey",template:"A large survey can still produce a {1} picture if the sample fails to {2} important groups in the wider {3} being {4}.",natural:["distorted","represent","population","studied"],v1:["biased","include","community","examined"],v2:["misleading","cover","group","surveyed"]},
{topic:"consultation",template:"Public consultation can {1} useful concerns, but officials should {2} the responses against the wider {3} affected by the proposed {4}.",natural:["reveal","assess","population","decision"],v1:["identify","compare","community","policy"],v2:["surface","judge","public","change"]},
{topic:"maintenance",template:"Preventive maintenance can {1} small defects, prevent costly {2}, use suitable inspection {3} and keep findings properly {4}.",natural:["identify","failures","intervals","recorded"],v1:["detect","breakdowns","periods","logged"],v2:["find","faults","times","documented"]},
{topic:"information overload",template:"Frequent alerts may {1} attention when every message receives the same {2} and users cannot {3} urgent information from routine {4}.",natural:["fragment","priority","separate","updates"],v1:["divide","importance","distinguish","messages"],v2:["reduce","weight","identify","notices"]},
{topic:"teamwork",template:"Teams need clear {1}, members who can {2} assigned work, final {3} for outcomes and a place where that responsibility will {4}.",natural:["ownership","handle","responsibility","rest"],v1:["roles","manage","accountability","lie"],v2:["duties","perform","ownership","remain"]},
{topic:"consumer disclosure",template:"A disclosure may be technically {1} yet still fail users if warnings are {2}, difficult to {3} and missed before a purchase {4}.",natural:["complete","buried","find","decision"],v1:["accurate","hidden","locate","choice"],v2:["detailed","placed","notice","decision"]},
{topic:"service design",template:"A service can appear {1} at one stage while the full customer {2} remains slow because separate {3} create repeated {4}.",natural:["efficient","journey","steps","handoffs"],v1:["fast","experience","stages","transfers"],v2:["smooth","process","steps","handoffs"]},
{topic:"feedback",template:"Useful feedback should {1} effective behaviour, clearly {2} what must change, help learners {3} the advice and improve the next {4}.",natural:["identify","explain","apply","attempt"],v1:["recognise","state","use","task"],v2:["show","describe","follow","effort"]},
{topic:"data quality",template:"Large datasets can support poor {1} when records are {2}, users assume volume guarantees {3} and teams fail to check data {4}.",natural:["decisions","missing","accuracy","quality"],v1:["judgments","incomplete","reliability","validity"],v2:["results","absent","correctness","quality"]},
{topic:"urban planning",template:"A transport project may {1} vehicle movement while reducing pedestrian {2}, creating wider {3} before a final {4}.",natural:["improve","space","trade-offs","design"],v1:["speed","access","effects","plan"],v2:["increase","room","costs","option"]}
];
export const ENG012_PRODUCTION_SSC_V2:readonly Eng012AuthorityV1[]=[...expand("WS-PROD-S","ENG-012-CP001",i=>i%3===0?"easy":"medium",standard),...expand("WS-PROD-A","ENG-012-CP002",i=>i%3===0?"medium":"hard",advanced)];
