import { extendedAuthority, type ExtendedSpellingAuthority } from "./CP002-extended-types";

export const CP002_EXTENDED_VARG: readonly ExtendedSpellingAuthority[] = [
  extendedAuthority("VARG_CONFUSION", "SPL-101", "ਪਾਣੀ", ["ਪਾਨੀ", "ਪਾਂਣੀ", "ਪਾਂਨੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-102", "ਰਾਣੀ", ["ਰਾਨੀ", "ਰਾਂਣੀ", "ਰਾਂਨੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-103", "ਕਹਾਣੀ", ["ਕਹਾਨੀ", "ਕਹਾੱਣੀ", "ਕਹਾਂਣੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-104", "ਗੁਣ", ["ਗੁਨ", "ਗੂਣ", "ਗੂਨ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-105", "ਮਾਣ", ["ਮਾਨ", "ਮਾਂਣ", "ਮਾਂਨ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-106", "ਪ੍ਰਾਣ", ["ਪ੍ਰਾਨ", "ਪਰਾਣ", "ਪਰਾਨ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-107", "ਵੀਣਾ", ["ਵੀਨਾ", "ਵਿਣਾ", "ਵੀਨਾਂ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-108", "ਬਾਣੀ", ["ਬਾਨੀ", "ਬਾਂਣੀ", "ਬਾਂਨੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-109", "ਪੁਰਾਣਾ", ["ਪੁਰਾਨਾ", "ਪੁਰਾਂਣਾ", "ਪੂਰਾਣਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-110", "ਸਿਆਣਾ", ["ਸਿਆਨਾ", "ਸਿਯਾਣਾ", "ਸਿਯਾਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-111", "ਦਾਣਾ", ["ਦਾਨਾ", "ਦਾਂਣਾ", "ਦਾਂਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-112", "ਗਾਣਾ", ["ਗਾਨਾ", "ਗਾਂਣਾ", "ਗਾਂਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-113", "ਖਾਣਾ", ["ਖਾਨਾ", "ਖਾਂਣਾ", "ਖਾਂਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-114", "ਜਾਣਾ", ["ਜਾਨਾ", "ਜਾਂਣਾ", "ਜਾਂਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-115", "ਆਉਣਾ", ["ਆਉਨਾ", "ਆਵਣਾ", "ਆਓਣਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-116", "ਦੇਣਾ", ["ਦੇਨਾ", "ਦੇਵਣਾ", "ਦੈਣਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-117", "ਲੈਣਾ", ["ਲੈਨਾ", "ਲੈਵਣਾ", "ਲੇਣਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-122", "ਵਹਿਣਾ", ["ਵਹਿਨਾ", "ਵੈਹਣਾ", "ਵੈਹਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-123", "ਧੋਬੀ", ["ਥੋਬੀ", "ਧੋਬਿ", "ਧੌਬੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-124", "ਧਰਮ", ["ਥਰਮ", "ਧਰੱਮ", "ਧ੍ਰਮ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-125", "ਧੁੱਪ", ["ਥੁੱਪ", "ਧੁਪ", "ਧੂਪ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-127", "ਘੰਟੀ", ["ਖੰਟੀ", "ਘਂਟੀ", "ਘੰਟਿ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-128", "ਭੋਜਨ", ["ਫੋਜਨ", "ਭੌਜਨ", "ਭੋਜਣ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-129", "ਮਧਾਣੀ", ["ਮਧਾਨੀ", "ਮਥਾਣੀ", "ਮਥਾਨੀ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-130", "ਟਿਕਾਣਾ", ["ਟਿਕਾਨਾ", "ਠਿਕਾਣਾ", "ਠਿਕਾਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-131", "ਸੋਹਣਾ", ["ਸੋਹਨਾ", "ਸੌਹਣਾ", "ਸੌਹਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-132", "ਪਹਿਨਣਾ", ["ਪਹਿਨਨਾ", "ਪੈਹਨਣਾ", "ਪਹਿਣਨਾ"], "VARG_CONFUSION"),
  extendedAuthority("VARG_CONFUSION", "SPL-133", "ਠਾਣੇਦਾਰ", ["ਥਾਣੇਦਾਰ", "ਥਾਨੇਦਾਰ", "ਠਾਨੇਦਾਰ"], "VARG_CONFUSION"),
] as const;
