import type { CP007SambandhakAuthority, CP007SambandhakKind } from "./CP007-authorities";

export const CP007_SAMBANDHAK_EXPANSION: readonly CP007SambandhakAuthority[] = [
  {id:"CP007-SR10",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-010",expression:"ਨੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਕਿਸਾਨ ਨੇ ਖੇਤ ਜੋਤਿਆ।",explanationPa:"‘ਨੇ’ ਇਕੱਲਾ ਹੀ ਕਰਤਾ ਦਾ ਹੋਰ ਸ਼ਬਦਾਂ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR11",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-011",expression:"ਨੂੰ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਅਧਿਆਪਕ ਨੇ ਵਿਦਿਆਰਥੀ ਨੂੰ ਕਿਤਾਬ ਦਿੱਤੀ।",explanationPa:"‘ਨੂੰ’ ਇਕੱਲਾ ਹੀ ‘ਵਿਦਿਆਰਥੀ’ ਦਾ ਕਿਰਿਆ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR12",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-012",expression:"ਤੋਂ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਰੇਲਗੱਡੀ ਸਟੇਸ਼ਨ ਤੋਂ ਚੱਲੀ।",explanationPa:"‘ਤੋਂ’ ਇਕੱਲਾ ਹੀ ਰਵਾਨਗੀ ਦੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR13",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-013",expression:"ਦਾ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਘਰ ਦਾ ਦਰਵਾਜ਼ਾ ਖੁੱਲ੍ਹਾ ਹੈ।",explanationPa:"‘ਦਾ’ ਆਪਣੇ ਆਪ ‘ਘਰ’ ਅਤੇ ‘ਦਰਵਾਜ਼ਾ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR14",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-014",expression:"ਦੀ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਕਲਾਸ ਦੀ ਖਿੜਕੀ ਬੰਦ ਹੈ।",explanationPa:"‘ਦੀ’ ਆਪਣੇ ਆਪ ਦੋ ਨਾਂਵਾਂ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR15",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-015",expression:"ਦੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਦਰੱਖ਼ਤ ਦੇ ਪੱਤੇ ਹਰੇ ਹਨ।",explanationPa:"‘ਦੇ’ ਇਕੱਲਾ ਹੀ ‘ਦਰੱਖ਼ਤ’ ਅਤੇ ‘ਪੱਤੇ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR16",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-016",expression:"ਨੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਅਧਿਆਪਕ ਨੇ ਪਾਠ ਸਮਝਾਇਆ।",explanationPa:"‘ਨੇ’ ਕਰਤਾ ਅਤੇ ਕਿਰਿਆ ਦਾ ਸੰਬੰਧ ਆਪਣੇ ਆਪ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR17",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-017",expression:"ਨੂੰ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਬੱਚੇ ਨੂੰ ਇਨਾਮ ਮਿਲਿਆ।",explanationPa:"‘ਨੂੰ’ ਆਪਣੇ ਆਪ ‘ਬੱਚੇ’ ਦਾ ਵਾਕ ਦੇ ਹੋਰ ਭਾਗ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR18",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-018",expression:"ਤੋਂ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਅਸੀਂ ਬਾਜ਼ਾਰ ਤੋਂ ਫਲ ਲਿਆਏ।",explanationPa:"‘ਤੋਂ’ ਇਕੱਲਾ ਹੀ ਪ੍ਰਾਪਤੀ ਦੇ ਸਰੋਤ ਦਾ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},

  {id:"CP007-SR19",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-019",expression:"ਨੇੜੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਘਰ ਦੇ ਨੇੜੇ ਬਾਗ ਹੈ।",explanationPa:"‘ਨੇੜੇ’ ਨੂੰ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਦੇ’ ਦਾ ਸਹਾਰਾ ਚਾਹੀਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR20",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-020",expression:"ਕੋਲ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਦਫ਼ਤਰ ਦੇ ਕੋਲ ਡਾਕਘਰ ਹੈ।",explanationPa:"‘ਕੋਲ’ ਇੱਥੇ ‘ਦੇ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR21",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-021",expression:"ਅੱਗੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਸਕੂਲ ਦੇ ਅੱਗੇ ਖੁੱਲ੍ਹਾ ਮੈਦਾਨ ਹੈ।",explanationPa:"‘ਅੱਗੇ’ ਨੂੰ ਸਥਾਨਕ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਦੇ’ ਦੀ ਲੋੜ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR22",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-022",expression:"ਪਿੱਛੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਮਕਾਨ ਦੇ ਪਿੱਛੇ ਬਾਗ ਹੈ।",explanationPa:"‘ਪਿੱਛੇ’ ‘ਦੇ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR23",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-023",expression:"ਅੰਦਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਕਮਰੇ ਦੇ ਅੰਦਰ ਮੇਜ਼ ਰੱਖਿਆ ਹੈ।",explanationPa:"‘ਅੰਦਰ’ ਨੂੰ ਸੰਬੰਧਕ ਕੰਮ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਦੇ’ ਦਾ ਸਹਾਰਾ ਮਿਲਿਆ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR24",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-024",expression:"ਬਾਹਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਦਫ਼ਤਰ ਦੇ ਬਾਹਰ ਲੋਕ ਉਡੀਕ ਰਹੇ ਹਨ।",explanationPa:"‘ਬਾਹਰ’ ‘ਦੇ’ ਨਾਲ ਮਿਲ ਕੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR25",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-025",expression:"ਹੇਠਾਂ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਦਰੱਖ਼ਤ ਦੇ ਹੇਠਾਂ ਛਾਂ ਹੈ।",explanationPa:"‘ਹੇਠਾਂ’ ਨੂੰ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਣ ਲਈ ‘ਦੇ’ ਦੀ ਲੋੜ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR26",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-026",expression:"ਉੱਪਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਅਲਮਾਰੀ ਦੇ ਉੱਪਰ ਡੱਬਾ ਪਿਆ ਹੈ।",explanationPa:"‘ਉੱਪਰ’ ਇੱਥੇ ‘ਦੇ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR27",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-027",expression:"ਵਿਚਕਾਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਦੋ ਇਮਾਰਤਾਂ ਦੇ ਵਿਚਕਾਰ ਰਸਤਾ ਹੈ।",explanationPa:"‘ਵਿਚਕਾਰ’ ਨੂੰ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਦੇ’ ਦਾ ਸਹਾਰਾ ਚਾਹੀਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},

  {id:"CP007-SR28",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-028",expression:"ਦੇ ਹੇਠਾਂ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਮੇਜ਼ ਦੇ ਹੇਠਾਂ ਬੈਗ ਪਿਆ ਹੈ।",explanationPa:"‘ਦੇ ਹੇਠਾਂ’ ਮਿਲ ਕੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR29",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-029",expression:"ਦੇ ਨੇੜੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਹਸਪਤਾਲ ਦੇ ਨੇੜੇ ਦਵਾਈ ਦੀ ਦੁਕਾਨ ਹੈ।",explanationPa:"‘ਦੇ ਨੇੜੇ’ ਮਿਲ ਕੇ ਦੋ ਥਾਵਾਂ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR30",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-030",expression:"ਦੇ ਕੋਲ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਬੱਸ ਅੱਡੇ ਦੇ ਕੋਲ ਪਾਰਕਿੰਗ ਹੈ।",explanationPa:"‘ਦੇ ਕੋਲ’ ਮਿਲ ਕੇ ਨੇੜਤਾ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR31",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-031",expression:"ਦੇ ਅੱਗੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਘਰ ਦੇ ਅੱਗੇ ਦਰੱਖ਼ਤ ਹੈ।",explanationPa:"‘ਦੇ ਅੱਗੇ’ ਮਿਲ ਕੇ ਸਥਾਨਕ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR32",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-032",expression:"ਦੇ ਪਿੱਛੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਸਕੂਲ ਦੇ ਪਿੱਛੇ ਖੇਡ ਮੈਦਾਨ ਹੈ।",explanationPa:"‘ਦੇ ਪਿੱਛੇ’ ਮਿਲ ਕੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR33",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-033",expression:"ਦੇ ਅੰਦਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਡੱਬੇ ਦੇ ਅੰਦਰ ਕਾਗਜ਼ ਹਨ।",explanationPa:"‘ਦੇ ਅੰਦਰ’ ਮਿਲ ਕੇ ਅੰਦਰਲੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR34",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-034",expression:"ਦੇ ਬਾਹਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਕਮਰੇ ਦੇ ਬਾਹਰ ਕੁਰਸੀਆਂ ਰੱਖੀਆਂ ਹਨ।",explanationPa:"‘ਦੇ ਬਾਹਰ’ ਮਿਲ ਕੇ ਬਾਹਰੀ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR35",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-035",expression:"ਦੇ ਵਿਚਕਾਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਦੋ ਪਿੰਡਾਂ ਦੇ ਵਿਚਕਾਰ ਨਹਿਰ ਵਗਦੀ ਹੈ।",explanationPa:"‘ਦੇ ਵਿਚਕਾਰ’ ਮਿਲ ਕੇ ਦੋ ਪੱਖਾਂ ਵਿਚਲੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR36",priorApprovedIds:[],breadthSourceId:"CP007-SAMB-BREADTH-036",expression:"ਦੇ ਪਰੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਪੁਲ ਦੇ ਪਰੇ ਖੇਤ ਸ਼ੁਰੂ ਹੋ ਜਾਂਦੇ ਹਨ।",explanationPa:"‘ਦੇ ਪਰੇ’ ਮਿਲ ਕੇ ਹੱਦ ਤੋਂ ਅੱਗੇ ਦਾ ਸੰਬੰਧ ਦੱਸਦੇ ਹਨ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
] as const;
