import type { CP007SambandhakAuthority, CP007SambandhakKind } from "./CP007-authorities";

/**
 * Context-breadth expansion for the already-approved three-way taxonomy.
 *
 * Source IDs are mapped to checked public references in CP007-SOURCES.md.
 * The expansion intentionally stays conservative:
 * - ਪੂਰਨ: only forms directly supported as complete sambandhak
 * - ਅਪੂਰਨ: only ਪਰੇ / ਉਰੇ / ਦੂਰ patterns
 * - ਦੁਬਾਜਰਾ: only ਉੱਤੇ / ਬਗੈਰ patterns shown in both standalone and supported forms
 */
export const CP007_SAMBANDHAK_EXPANSION: readonly CP007SambandhakAuthority[] = [
  {id:"CP007-SR10",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਨੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਕਿਸਾਨ ਨੇ ਖੇਤ ਜੋਤਿਆ।",explanationPa:"‘ਨੇ’ ਇਕੱਲਾ ਹੀ ਕਰਤਾ ਦਾ ਵਾਕ ਦੇ ਹੋਰ ਭਾਗਾਂ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR11",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਤੋਂ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਮੁਸਾਫ਼ਰ ਸਟੇਸ਼ਨ ਤੋਂ ਰਵਾਨਾ ਹੋਇਆ।",explanationPa:"‘ਤੋਂ’ ਆਪਣੇ ਆਪ ਰਵਾਨਗੀ ਦੇ ਸਥਾਨ ਦਾ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR12",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦਾ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਘਰ ਦਾ ਦਰਵਾਜ਼ਾ ਖੁੱਲ੍ਹਾ ਹੈ।",explanationPa:"‘ਦਾ’ ਆਪਣੇ ਆਪ ‘ਘਰ’ ਅਤੇ ‘ਦਰਵਾਜ਼ਾ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR13",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦੀ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਕਲਾਸ ਦੀ ਖਿੜਕੀ ਬੰਦ ਹੈ।",explanationPa:"‘ਦੀ’ ਆਪਣੇ ਆਪ ਦੋ ਨਾਂਵਾਂ ਦਾ ਸੰਬੰਧ ਜੋੜਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR14",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਦਰੱਖ਼ਤ ਦੇ ਪੱਤੇ ਹਰੇ ਹਨ।",explanationPa:"‘ਦੇ’ ਆਪਣੇ ਆਪ ‘ਦਰੱਖ਼ਤ’ ਅਤੇ ‘ਪੱਤੇ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR15",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦਾ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਕਮਰੇ ਦਾ ਪੱਖਾ ਚੱਲ ਰਿਹਾ ਹੈ।",explanationPa:"‘ਦਾ’ ਆਪਣੇ ਆਪ ‘ਕਮਰੇ’ ਅਤੇ ‘ਪੱਖੇ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR16",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦੀ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਦੁਕਾਨ ਦੀ ਛੱਤ ਨਵੀਂ ਹੈ।",explanationPa:"‘ਦੀ’ ਆਪਣੇ ਆਪ ‘ਦੁਕਾਨ’ ਅਤੇ ‘ਛੱਤ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR17",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਦੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਬਾਗ ਦੇ ਫੁੱਲ ਖਿੜੇ ਹੋਏ ਹਨ।",explanationPa:"‘ਦੇ’ ਆਪਣੇ ਆਪ ‘ਬਾਗ’ ਅਤੇ ‘ਫੁੱਲਾਂ’ ਦਾ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR18",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਨੇ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਅਧਿਆਪਕ ਨੇ ਪਾਠ ਸਮਝਾਇਆ।",explanationPa:"‘ਨੇ’ ਇਕੱਲਾ ਹੀ ਕਰਤਾ ਦਾ ਕਿਰਿਆ ਨਾਲ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR19",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-PURAN",expression:"ਤੋਂ",kind:"PURAN" as CP007SambandhakKind,sentence:"ਅਸੀਂ ਬਾਜ਼ਾਰ ਤੋਂ ਫਲ ਲਿਆਏ।",explanationPa:"‘ਤੋਂ’ ਆਪਣੇ ਆਪ ਪ੍ਰਾਪਤੀ ਦੇ ਸਰੋਤ ਦਾ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},

  {id:"CP007-SR20",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਪਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਨਹਿਰ ਤੋਂ ਪਰੇ ਖੇਤ ਸ਼ੁਰੂ ਹੁੰਦੇ ਹਨ।",explanationPa:"‘ਪਰੇ’ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਤੋਂ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਆਇਆ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR21",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਦੂਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਮੁੱਖ ਸੜਕ ਤੋਂ ਦੂਰ ਨਵੀਂ ਬਸਤੀ ਹੈ।",explanationPa:"‘ਦੂਰ’ ਦਾ ਸੰਬੰਧ ‘ਤੋਂ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਪੂਰਾ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR22",priorApprovedIds:[],breadthSourceId:"PSEB7-SAMB-APURAN",expression:"ਉਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਪੁਲ ਤੋਂ ਉਰੇ ਬੱਸ ਅੱਡਾ ਹੈ।",explanationPa:"‘ਉਰੇ’ ਇੱਥੇ ‘ਤੋਂ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR23",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਪਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਬਾਗ ਤੋਂ ਪਰੇ ਖੁੱਲ੍ਹਾ ਮੈਦਾਨ ਹੈ।",explanationPa:"‘ਪਰੇ’ ਇਕੱਲਾ ਸੰਬੰਧ ਪੂਰਾ ਨਹੀਂ ਕਰ ਰਿਹਾ; ਇਸ ਨੂੰ ‘ਤੋਂ’ ਦਾ ਸਹਾਰਾ ਮਿਲਿਆ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR24",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਦੂਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਸ਼ਹਿਰ ਤੋਂ ਦੂਰ ਇੱਕ ਕਾਰਖ਼ਾਨਾ ਹੈ।",explanationPa:"‘ਦੂਰ’ ਦਾ ਸੰਬੰਧ ‘ਤੋਂ’ ਨਾਲ ਪੂਰਾ ਹੋ ਰਿਹਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR25",priorApprovedIds:[],breadthSourceId:"PSEB7-SAMB-APURAN",expression:"ਉਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਨਦੀ ਤੋਂ ਉਰੇ ਛੋਟਾ ਪਿੰਡ ਹੈ।",explanationPa:"‘ਉਰੇ’ ਨੂੰ ਸੰਬੰਧ ਦੱਸਣ ਲਈ ‘ਤੋਂ’ ਦਾ ਸਹਾਰਾ ਚਾਹੀਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR26",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਪਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਰੇਲ ਲਾਈਨ ਤੋਂ ਪਰੇ ਗੋਦਾਮ ਹੈ।",explanationPa:"‘ਪਰੇ’ ਦਾ ਸੰਬੰਧ ‘ਤੋਂ’ ਦੇ ਸਹਾਰੇ ਨਾਲ ਪੂਰਾ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR27",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਦੂਰ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਸਕੂਲ ਤੋਂ ਦੂਰ ਖੇਡ ਮੈਦਾਨ ਬਣਿਆ ਹੈ।",explanationPa:"‘ਦੂਰ’ ਨੂੰ ਸਥਾਨਕ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਤੋਂ’ ਦਾ ਸਹਾਰਾ ਮਿਲਿਆ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR28",priorApprovedIds:[],breadthSourceId:"PSEB7-SAMB-APURAN",expression:"ਉਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਸੜਕ ਤੋਂ ਉਰੇ ਦੁਕਾਨਾਂ ਦੀ ਕਤਾਰ ਹੈ।",explanationPa:"‘ਉਰੇ’ ਇੱਥੇ ‘ਤੋਂ’ ਨਾਲ ਮਿਲ ਕੇ ਸੰਬੰਧ ਪੂਰਾ ਕਰਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR29",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-APURAN",expression:"ਪਰੇ",kind:"APURAN" as CP007SambandhakKind,sentence:"ਦੀਵਾਰ ਤੋਂ ਪਰੇ ਬਾਗ ਦਾ ਦੂਜਾ ਹਿੱਸਾ ਹੈ।",explanationPa:"‘ਪਰੇ’ ਨੂੰ ਸੰਬੰਧ ਪੂਰਾ ਕਰਨ ਲਈ ‘ਤੋਂ’ ਦਾ ਸਹਾਰਾ ਚਾਹੀਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਅਪੂਰਨ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},

  {id:"CP007-SR30",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਕੋਠੇ ਉੱਤੇ ਕਬੂਤਰ ਬੈਠੇ ਹਨ।",explanationPa:"‘ਉੱਤੇ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧ ਜੋੜ ਸਕਦਾ ਹੈ ਅਤੇ ‘ਦੇ ਉੱਤੇ’ ਵਜੋਂ ਵੀ ਵਰਤਿਆ ਜਾ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR31",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਦੇ ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਅਲਮਾਰੀ ਦੇ ਉੱਤੇ ਡੱਬਾ ਰੱਖਿਆ ਹੈ।",explanationPa:"ਇੱਥੇ ‘ਉੱਤੇ’ ‘ਦੇ’ ਨਾਲ ਆਇਆ ਹੈ, ਜਦਕਿ ‘ਉੱਤੇ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧਕ ਦਾ ਕੰਮ ਕਰ ਸਕਦਾ ਹੈ; ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR32",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਬਗੈਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਮਿਹਨਤ ਬਗੈਰ ਚੰਗਾ ਨਤੀਜਾ ਔਖਾ ਹੈ।",explanationPa:"‘ਬਗੈਰ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧ ਜੋੜ ਸਕਦਾ ਹੈ ਅਤੇ ‘ਦੇ ਬਗੈਰ’ ਵਜੋਂ ਵੀ ਆ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR33",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਦੇ ਬਗੈਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਪਾਣੀ ਦੇ ਬਗੈਰ ਜੀਵਨ ਸੰਭਵ ਨਹੀਂ।",explanationPa:"ਇੱਥੇ ‘ਬਗੈਰ’ ‘ਦੇ’ ਨਾਲ ਆਇਆ ਹੈ, ਜਦਕਿ ‘ਬਗੈਰ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧਕ ਦਾ ਕੰਮ ਕਰ ਸਕਦਾ ਹੈ; ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR34",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਮੇਜ਼ ਉੱਤੇ ਨਕਸ਼ਾ ਪਿਆ ਹੈ।",explanationPa:"‘ਉੱਤੇ’ ਇਕੱਲਾ ਸੰਬੰਧ ਦੱਸ ਰਿਹਾ ਹੈ ਅਤੇ ਇਹ ‘ਦੇ ਉੱਤੇ’ ਵਜੋਂ ਵੀ ਆ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR35",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਦੇ ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਡੱਬੇ ਦੇ ਉੱਤੇ ਕਿਤਾਬ ਰੱਖੀ ਹੈ।",explanationPa:"ਇੱਥੇ ‘ਉੱਤੇ’ ‘ਦੇ’ ਨਾਲ ਵਰਤਿਆ ਗਿਆ ਹੈ, ਪਰ ਇਹ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧ ਜੋੜ ਸਕਦਾ ਹੈ; ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR36",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਬਗੈਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਟਿਕਟ ਬਗੈਰ ਅੰਦਰ ਜਾਣਾ ਮਨਾਹੀ ਹੈ।",explanationPa:"‘ਬਗੈਰ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧ ਦੱਸਦਾ ਹੈ ਅਤੇ ‘ਦੇ ਬਗੈਰ’ ਵਜੋਂ ਵੀ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR37",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਦੇ ਬਗੈਰ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਇਜਾਜ਼ਤ ਦੇ ਬਗੈਰ ਅੰਦਰ ਨਾ ਜਾਓ।",explanationPa:"ਇੱਥੇ ‘ਬਗੈਰ’ ‘ਦੇ’ ਨਾਲ ਆਇਆ ਹੈ ਅਤੇ ਇਹ ਇਕੱਲਾ ਵੀ ਵਰਤਿਆ ਜਾ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR38",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਸ਼ੈਲਫ਼ ਉੱਤੇ ਫ਼ਾਈਲਾਂ ਪਈਆਂ ਹਨ।",explanationPa:"‘ਉੱਤੇ’ ਇਕੱਲਾ ਵੀ ਸੰਬੰਧ ਜੋੜਦਾ ਹੈ ਅਤੇ ‘ਦੇ ਉੱਤੇ’ ਵਜੋਂ ਵੀ ਵਰਤਿਆ ਜਾ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
  {id:"CP007-SR39",priorApprovedIds:[],breadthSourceId:"PSEB8-SAMB-DUBAJRA",expression:"ਦੇ ਉੱਤੇ",kind:"DUBAJRA" as CP007SambandhakKind,sentence:"ਮੰਚ ਦੇ ਉੱਤੇ ਕੁਰਸੀਆਂ ਲੱਗੀਆਂ ਹਨ।",explanationPa:"ਇੱਥੇ ‘ਉੱਤੇ’ ‘ਦੇ’ ਨਾਲ ਵਰਤਿਆ ਗਿਆ ਹੈ; ਇਸ ਦੀ ਇਕੱਲੀ ਵਰਤੋਂ ਵੀ ਸੰਬੰਧ ਦੱਸ ਸਕਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ ਦੁਬਾਜਰਾ ਸੰਬੰਧਕ ਹੈ।",sourceStatus:"REVIEW_PENDING"},
] as const;
