import type { KnowledgeV1Difficulty } from "../../types";
import { ENV_CP019_FACT_BY_ID_V1 } from "./env-cp019-facts";
import type { EnvCp019ReviewQuestion } from "./env-cp019-review-types";

type Seed = {
  qlId: string;
  qlName: string;
  difficulty: KnowledgeV1Difficulty;
  stem: string;
  correct: string;
  distractors: readonly [string, string, string];
  explanation: string;
  sourceFactIds: readonly string[];
};

const S: readonly Seed[] = Object.freeze([
  { qlId:"ENV-019-QL-001", qlName:"Wetland definition and types", difficulty:"Easy", stem:"Which of the following can be a wetland under the Ramsar definition?", correct:"A natural or artificial water area", distractors:["Only a natural freshwater lake","Only a protected forest","Only a coastal mangrove"], explanation:"The Ramsar definition is broad. Wetlands may be natural or artificial and can contain fresh, brackish or salt water.", sourceFactIds:["env-cp019-wetland-definition"] },
  { qlId:"ENV-019-QL-001", qlName:"Wetland definition and types", difficulty:"Easy", stem:"Which is an example of a coastal wetland?", correct:"Mangrove", distractors:["Dry scrubland","Alpine meadow","Rocky desert"], explanation:"Mangroves are coastal wetlands. Ramsar wetland types also include lagoons, estuaries and other shallow coastal-water systems.", sourceFactIds:["env-cp019-wetland-types"] },
  { qlId:"ENV-019-QL-001", qlName:"Wetland definition and types", difficulty:"Medium", stem:"Which human-made area may still be treated as a wetland?", correct:"Rice field", distractors:["Dry quarry","Mountain ridge","Urban flyover"], explanation:"The wetland concept can include human-made systems such as rice fields, fish ponds and salt pans when they function as wetland habitats.", sourceFactIds:["env-cp019-wetland-types"] },
  { qlId:"ENV-019-QL-001", qlName:"Wetland definition and types", difficulty:"Hard", stem:"Shallow marine water is included as wetland when its depth at low tide does not exceed:", correct:"6 metres", distractors:["2 metres","20 metres","60 metres"], explanation:"The Ramsar definition includes marine water up to six metres deep at low tide, along with inland, coastal and human-made wetlands.", sourceFactIds:["env-cp019-wetland-definition"] },

  { qlId:"ENV-019-QL-002", qlName:"India and the Ramsar system", difficulty:"Easy", stem:"India became a party to the Ramsar Convention in:", correct:"1982", distractors:["1971","1992","2002"], explanation:"India became a Contracting Party on 1 February 1982, bringing its wetland-conservation commitments under the Ramsar framework.", sourceFactIds:["env-cp019-india-party"] },
  { qlId:"ENV-019-QL-002", qlName:"India and the Ramsar system", difficulty:"Easy", stem:"Which pair contains India's first Ramsar Sites?", correct:"Chilika Lake and Keoladeo National Park", distractors:["Loktak Lake and Wular Lake","Harike Lake and Kanjli","Sambhar Lake and Deepor Beel"], explanation:"Chilika Lake in Odisha and Keoladeo National Park in Rajasthan were the first two Indian sites placed on the Ramsar List.", sourceFactIds:["env-cp019-first-sites"] },
  { qlId:"ENV-019-QL-002", qlName:"India and the Ramsar system", difficulty:"Medium", stem:"Chilika Lake and Keoladeo National Park share which Ramsar designation date?", correct:"1 October 1981", distractors:["2 February 1971","23 March 1990","19 August 2002"], explanation:"Both sites carry the Ramsar designation date 1 October 1981, although India formally became a Contracting Party in 1982.", sourceFactIds:["env-cp019-first-date","env-cp019-india-party"] },
  { qlId:"ENV-019-QL-002", qlName:"India and the Ramsar system", difficulty:"Hard", stem:"Which statement about India's Ramsar history is correct?", correct:"Its first two listed sites were Chilika and Keoladeo", distractors:["Loktak was India's first site","India joined only after 1992","Harike and Wular were the first pair"], explanation:"The first Indian Ramsar Sites were Chilika Lake and Keoladeo National Park; later designations expanded the network across many wetland types.", sourceFactIds:["env-cp019-first-sites"] },

  { qlId:"ENV-019-QL-003", qlName:"Chilika Lake", difficulty:"Easy", stem:"Chilika Lake is located in which state?", correct:"Odisha", distractors:["Rajasthan","Manipur","Assam"], explanation:"Chilika Lake is in Odisha. It is one of India's earliest Ramsar Sites and is internationally important for its wetland biodiversity.", sourceFactIds:["env-cp019-chilika-location"] },
  { qlId:"ENV-019-QL-003", qlName:"Chilika Lake", difficulty:"Easy", stem:"Chilika is best described as a:", correct:"Brackish lagoon", distractors:["High-altitude freshwater lake","Inland salt pan","Wastewater-fed urban wetland"], explanation:"Chilika is a brackish lagoon separated from the Bay of Bengal by a sandy ridge and linked to the sea through tidal exchange.", sourceFactIds:["env-cp019-chilika-type"] },
  { qlId:"ENV-019-QL-003", qlName:"Chilika Lake", difficulty:"Medium", stem:"Why was Chilika placed on the Montreux Record in 1993?", correct:"Its ecological character had seriously deteriorated", distractors:["It became a tiger reserve","It was converted into a salt mine","It lost Ramsar status permanently"], explanation:"Chilika entered the Montreux Record because of ecological degradation, including siltation and choking of its sea connection.", sourceFactIds:["env-cp019-chilika-montreux"] },
  { qlId:"ENV-019-QL-003", qlName:"Chilika Lake", difficulty:"Hard", stem:"Which statement best describes Chilika's Montreux history?", correct:"Listed in 1993 and removed after restoration in 2002", distractors:["Listed in 1981 and never reviewed","Removed in 1993 after designation","Added only because of tiger conservation"], explanation:"Chilika was put on the Montreux Record in 1993 and removed in 2002 after rehabilitation improved its ecological condition.", sourceFactIds:["env-cp019-chilika-montreux"] },

  { qlId:"ENV-019-QL-004", qlName:"Keoladeo and the Montreux Record", difficulty:"Easy", stem:"Keoladeo National Park is located in:", correct:"Rajasthan", distractors:["Odisha","Punjab","Kerala"], explanation:"Keoladeo National Park is a Ramsar Site in Rajasthan and was one of India's first two sites placed on the Ramsar List.", sourceFactIds:["env-cp019-keoladeo-location","env-cp019-first-sites"] },
  { qlId:"ENV-019-QL-004", qlName:"Keoladeo and the Montreux Record", difficulty:"Easy", stem:"The Montreux Record is used mainly for Ramsar Sites facing:", correct:"Changes in ecological character", distractors:["Only border disputes","Only wildlife-trade violations","Only forest-fire reporting"], explanation:"The Montreux Record highlights Ramsar Sites where ecological character has changed, is changing or is likely to change.", sourceFactIds:["env-cp019-montreux-concept"] },
  { qlId:"ENV-019-QL-004", qlName:"Keoladeo and the Montreux Record", difficulty:"Medium", stem:"Keoladeo National Park was placed on the Montreux Record in:", correct:"1990", distractors:["1971","1981","2002"], explanation:"Keoladeo was placed on the Montreux Record in 1990 after ecological-character concerns, including serious water-management problems.", sourceFactIds:["env-cp019-keoladeo-montreux"] },
  { qlId:"ENV-019-QL-004", qlName:"Keoladeo and the Montreux Record", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"Keoladeo — Rajasthan", distractors:["Chilika — Manipur","Loktak — Odisha","Wular — Assam"], explanation:"Keoladeo is in Rajasthan. Chilika is in Odisha, Loktak in Manipur, and Wular in Jammu and Kashmir.", sourceFactIds:["env-cp019-keoladeo-location","env-cp019-chilika-location","env-cp019-loktak-location","env-cp019-wular-location"] },

  { qlId:"ENV-019-QL-005", qlName:"Loktak Lake", difficulty:"Easy", stem:"Loktak Lake is located in:", correct:"Manipur", distractors:["Assam","Rajasthan","Punjab"], explanation:"Loktak Lake is a major Ramsar wetland in Manipur and is closely linked with the ecology of the state's central valley.", sourceFactIds:["env-cp019-loktak-location"] },
  { qlId:"ENV-019-QL-005", qlName:"Loktak Lake", difficulty:"Easy", stem:"Floating masses called phumdis are a characteristic feature of:", correct:"Loktak Lake", distractors:["Sambhar Lake","Wular Lake","Chilika Lake"], explanation:"Loktak is famous for phumdis, floating masses of vegetation, soil and organic matter that form a distinctive part of the lake ecosystem.", sourceFactIds:["env-cp019-loktak-phumdis"] },
  { qlId:"ENV-019-QL-005", qlName:"Loktak Lake", difficulty:"Medium", stem:"Keibul Lamjao National Park is closely linked with which wetland?", correct:"Loktak Lake", distractors:["Deepor Beel","Harike Wetland","Vembanad-Kol"], explanation:"Keibul Lamjao lies in the Loktak Lake system and is especially known as habitat of the Sangai deer.", sourceFactIds:["env-cp019-loktak-keibul"] },
  { qlId:"ENV-019-QL-005", qlName:"Loktak Lake", difficulty:"Hard", stem:"Which feature-site pair is correct?", correct:"Loktak — phumdis", distractors:["Chilika — alpine peatland","Sambhar — floating phumdis","Deepor Beel — brackish lagoon"], explanation:"Phumdis are characteristic of Loktak. Chilika is a brackish lagoon, Sambhar is saline, and Deepor Beel is a freshwater lake.", sourceFactIds:["env-cp019-loktak-phumdis","env-cp019-chilika-type","env-cp019-sambhar","env-cp019-deepor-type"] },

  { qlId:"ENV-019-QL-006", qlName:"Wular Lake", difficulty:"Easy", stem:"Wular Lake is a Ramsar Site in:", correct:"Jammu and Kashmir", distractors:["Ladakh","Assam","Kerala"], explanation:"Wular Lake is a major freshwater Ramsar Site in Jammu and Kashmir and forms part of the Jhelum River system.", sourceFactIds:["env-cp019-wular-location","env-cp019-wular-type"] },
  { qlId:"ENV-019-QL-006", qlName:"Wular Lake", difficulty:"Easy", stem:"Wular is mainly a:", correct:"Freshwater lake", distractors:["Brackish coastal lagoon","Urban wastewater wetland","Inland salt lake"], explanation:"Wular is a large freshwater lake, unlike Chilika's brackish lagoon or Sambhar's saline-lake system.", sourceFactIds:["env-cp019-wular-type","env-cp019-chilika-type","env-cp019-sambhar"] },
  { qlId:"ENV-019-QL-006", qlName:"Wular Lake", difficulty:"Medium", stem:"Wular Lake is associated with which river system?", correct:"Jhelum", distractors:["Godavari","Mahanadi","Cauvery"], explanation:"Wular forms part of the Jhelum River system; the Jhelum drains the lake westward through the Kashmir Valley region.", sourceFactIds:["env-cp019-wular-type"] },
  { qlId:"ENV-019-QL-006", qlName:"Wular Lake", difficulty:"Hard", stem:"Which distinction between Wular and Chilika is correct?", correct:"Wular is freshwater; Chilika is brackish", distractors:["Wular is saline; Chilika is alpine","Both are urban wastewater wetlands","Both are inland salt lakes"], explanation:"Wular is a freshwater lake in Jammu and Kashmir, while Chilika in Odisha is a brackish coastal lagoon.", sourceFactIds:["env-cp019-wular-type","env-cp019-chilika-type"] },

  { qlId:"ENV-019-QL-007", qlName:"Punjab Ramsar wetlands", difficulty:"Easy", stem:"Harike Lake is located in:", correct:"Punjab", distractors:["Haryana","Rajasthan","Himachal Pradesh"], explanation:"Harike is a Ramsar Site in Punjab and is one of the state's important river-linked wetland systems.", sourceFactIds:["env-cp019-harike-location"] },
  { qlId:"ENV-019-QL-007", qlName:"Punjab Ramsar wetlands", difficulty:"Easy", stem:"Harike Wetland lies near the confluence of which rivers?", correct:"Beas and Sutlej", distractors:["Ganga and Yamuna","Ravi and Chenab","Narmada and Tapi"], explanation:"Harike lies near the meeting of the Beas and Sutlej rivers, making it a major riverine wetland in Punjab.", sourceFactIds:["env-cp019-harike-confluence"] },
  { qlId:"ENV-019-QL-007", qlName:"Punjab Ramsar wetlands", difficulty:"Medium", stem:"Which of the following is also a Ramsar Site in Punjab?", correct:"Kanjli", distractors:["Deepor Beel","Sambhar Lake","Loktak Lake"], explanation:"Kanjli is one of Punjab's Ramsar Sites. Deepor Beel is in Assam, Sambhar in Rajasthan, and Loktak in Manipur.", sourceFactIds:["env-cp019-punjab-sites","env-cp019-deepor-location","env-cp019-sambhar","env-cp019-loktak-location"] },
  { qlId:"ENV-019-QL-007", qlName:"Punjab Ramsar wetlands", difficulty:"Hard", stem:"Which set contains only Punjab Ramsar Sites?", correct:"Harike, Kanjli and Ropar", distractors:["Harike, Loktak and Kanjli","Ropar, Sambhar and Deepor","Kanjli, Chilika and Wular"], explanation:"Harike, Kanjli and Ropar are all Ramsar Sites in Punjab; the other options mix wetlands from different states or Union Territories.", sourceFactIds:["env-cp019-punjab-sites"] },

  { qlId:"ENV-019-QL-008", qlName:"Deepor Beel", difficulty:"Easy", stem:"Deepor Beel is located in:", correct:"Assam", distractors:["West Bengal","Manipur","Odisha"], explanation:"Deepor Beel is an important Ramsar wetland in Assam and lies close to Guwahati in the Brahmaputra valley.", sourceFactIds:["env-cp019-deepor-location"] },
  { qlId:"ENV-019-QL-008", qlName:"Deepor Beel", difficulty:"Easy", stem:"Deepor Beel is best described as a:", correct:"Freshwater lake", distractors:["Brackish lagoon","Salt lake","Mangrove forest"], explanation:"Deepor Beel is a permanent freshwater lake formed in a former channel of the Brahmaputra River.", sourceFactIds:["env-cp019-deepor-type"] },
  { qlId:"ENV-019-QL-008", qlName:"Deepor Beel", difficulty:"Medium", stem:"Deepor Beel lies near which major city?", correct:"Guwahati", distractors:["Jaipur","Bhubaneswar","Srinagar"], explanation:"Deepor Beel lies south-west of Guwahati and is ecologically important within the wider Brahmaputra floodplain system.", sourceFactIds:["env-cp019-deepor-location","env-cp019-deepor-type"] },
  { qlId:"ENV-019-QL-008", qlName:"Deepor Beel", difficulty:"Hard", stem:"Which river is linked with the origin of Deepor Beel?", correct:"Brahmaputra", distractors:["Jhelum","Sutlej","Mahanadi"], explanation:"Deepor Beel occupies a former channel of the Brahmaputra River, which explains its freshwater floodplain character.", sourceFactIds:["env-cp019-deepor-type"] },

  { qlId:"ENV-019-QL-009", qlName:"East Kolkata Wetlands", difficulty:"Easy", stem:"East Kolkata Wetlands is located in:", correct:"West Bengal", distractors:["Assam","Kerala","Odisha"], explanation:"East Kolkata Wetlands is a Ramsar Site in West Bengal and forms a major wetland system on the eastern side of Kolkata.", sourceFactIds:["env-cp019-ekw-location"] },
  { qlId:"ENV-019-QL-009", qlName:"East Kolkata Wetlands", difficulty:"Easy", stem:"East Kolkata Wetlands is especially known for using urban wastewater in:", correct:"Fisheries and agriculture", distractors:["Tiger breeding","Salt mining only","Alpine grazing"], explanation:"The wetland is known for resource recovery in which city wastewater supports fish ponds, vegetable farming and other productive uses.", sourceFactIds:["env-cp019-ekw-wastewater"] },
  { qlId:"ENV-019-QL-009", qlName:"East Kolkata Wetlands", difficulty:"Medium", stem:"Which wetland best shows large-scale wastewater-based resource recovery?", correct:"East Kolkata Wetlands", distractors:["Tsomoriri","Wular Lake","Sambhar Lake"], explanation:"East Kolkata Wetlands is internationally noted for treating and reusing urban wastewater through fisheries and agriculture.", sourceFactIds:["env-cp019-ekw-wastewater"] },
  { qlId:"ENV-019-QL-009", qlName:"East Kolkata Wetlands", difficulty:"Hard", stem:"Which distinction is correct?", correct:"East Kolkata Wetlands uses wastewater; Sambhar is saline", distractors:["East Kolkata is alpine; Sambhar is mangrove","Both are brackish lagoons","Both are in Assam"], explanation:"East Kolkata Wetlands is a wastewater-based urban wetland system, while Sambhar Lake in Rajasthan is an inland saline lake.", sourceFactIds:["env-cp019-ekw-wastewater","env-cp019-sambhar"] },

  { qlId:"ENV-019-QL-010", qlName:"Sambhar and Kolleru", difficulty:"Easy", stem:"Sambhar Lake is located in:", correct:"Rajasthan", distractors:["Andhra Pradesh","Manipur","Kerala"], explanation:"Sambhar Lake is a Ramsar Site in Rajasthan and is well known as a large inland saline-lake system.", sourceFactIds:["env-cp019-sambhar"] },
  { qlId:"ENV-019-QL-010", qlName:"Sambhar and Kolleru", difficulty:"Easy", stem:"Kolleru Lake is located in:", correct:"Andhra Pradesh", distractors:["Rajasthan","Punjab","Assam"], explanation:"Kolleru Lake is a Ramsar Site in Andhra Pradesh and is an important freshwater wetland of peninsular India.", sourceFactIds:["env-cp019-kolleru"] },
  { qlId:"ENV-019-QL-010", qlName:"Sambhar and Kolleru", difficulty:"Medium", stem:"Which Ramsar Site is an inland saline lake?", correct:"Sambhar Lake", distractors:["Kolleru Lake","Deepor Beel","Wular Lake"], explanation:"Sambhar is saline. Kolleru, Deepor Beel and Wular are primarily freshwater wetland systems.", sourceFactIds:["env-cp019-sambhar","env-cp019-kolleru","env-cp019-deepor-type","env-cp019-wular-type"] },
  { qlId:"ENV-019-QL-010", qlName:"Sambhar and Kolleru", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"Kolleru — Andhra Pradesh", distractors:["Sambhar — Assam","Deepor Beel — Rajasthan","Loktak — Punjab"], explanation:"Kolleru is in Andhra Pradesh. Sambhar is in Rajasthan, Deepor Beel in Assam, and Loktak in Manipur.", sourceFactIds:["env-cp019-kolleru","env-cp019-sambhar","env-cp019-deepor-location","env-cp019-loktak-location"] },

  { qlId:"ENV-019-QL-011", qlName:"Vembanad-Kol and Tsomoriri", difficulty:"Easy", stem:"Vembanad-Kol Wetland is located in:", correct:"Kerala", distractors:["Ladakh","Punjab","Rajasthan"], explanation:"Vembanad-Kol is a Ramsar Site in Kerala and represents an important wetland system of India's south-west coast.", sourceFactIds:["env-cp019-vembanad"] },
  { qlId:"ENV-019-QL-011", qlName:"Vembanad-Kol and Tsomoriri", difficulty:"Easy", stem:"Tsomoriri is a Ramsar wetland in:", correct:"Ladakh", distractors:["Kerala","Assam","Odisha"], explanation:"Tsomoriri is a high-altitude Ramsar wetland in Ladakh, contrasting strongly with lowland coastal and floodplain wetlands.", sourceFactIds:["env-cp019-tsomoriri"] },
  { qlId:"ENV-019-QL-011", qlName:"Vembanad-Kol and Tsomoriri", difficulty:"Medium", stem:"Which Ramsar Site is a high-altitude wetland?", correct:"Tsomoriri", distractors:["East Kolkata Wetlands","Harike Lake","Sambhar Lake"], explanation:"Tsomoriri lies at high altitude in Ladakh. The other options are lowland urban, riverine or saline wetland systems.", sourceFactIds:["env-cp019-tsomoriri","env-cp019-ekw-location","env-cp019-harike-location","env-cp019-sambhar"] },
  { qlId:"ENV-019-QL-011", qlName:"Vembanad-Kol and Tsomoriri", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"Vembanad-Kol — Kerala", distractors:["Tsomoriri — West Bengal","Harike — Assam","Deepor Beel — Punjab"], explanation:"Vembanad-Kol is in Kerala. Tsomoriri is in Ladakh, Harike in Punjab, and Deepor Beel in Assam.", sourceFactIds:["env-cp019-vembanad","env-cp019-tsomoriri","env-cp019-harike-location","env-cp019-deepor-location"] },

  { qlId:"ENV-019-QL-012", qlName:"Integrated Ramsar-site identification", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"Chilika—Odisha; Loktak—Manipur; Wular—Jammu and Kashmir", distractors:["Chilika—Assam; Loktak—Punjab; Wular—Kerala","Chilika—Rajasthan; Loktak—Odisha; Wular—Assam","Chilika—Kerala; Loktak—Rajasthan; Wular—Punjab"], explanation:"Chilika is in Odisha, Loktak in Manipur, and Wular in Jammu and Kashmir; these are standard Ramsar site-state matches.", sourceFactIds:["env-cp019-chilika-location","env-cp019-loktak-location","env-cp019-wular-location"] },
  { qlId:"ENV-019-QL-012", qlName:"Integrated Ramsar-site identification", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"Harike—Punjab; Deepor Beel—Assam; Sambhar—Rajasthan", distractors:["Harike—Assam; Deepor—Punjab; Sambhar—Kerala","Harike—Odisha; Deepor—Rajasthan; Sambhar—Manipur","Harike—Kerala; Deepor—Odisha; Sambhar—Punjab"], explanation:"Harike is in Punjab, Deepor Beel in Assam, and Sambhar Lake in Rajasthan.", sourceFactIds:["env-cp019-harike-location","env-cp019-deepor-location","env-cp019-sambhar"] },
  { qlId:"ENV-019-QL-012", qlName:"Integrated Ramsar-site identification", difficulty:"Hard", stem:"Which feature-site pairing is NOT correct?", correct:"Wular — brackish coastal lagoon", distractors:["Loktak — phumdis","Sambhar — saline lake","East Kolkata Wetlands — wastewater reuse"], explanation:"Wular is a freshwater lake in the Jhelum system. The other three feature-site pairs are correct and exam-relevant.", sourceFactIds:["env-cp019-wular-type","env-cp019-loktak-phumdis","env-cp019-sambhar","env-cp019-ekw-wastewater"] },
  { qlId:"ENV-019-QL-012", qlName:"Integrated Ramsar-site identification", difficulty:"Hard", stem:"Which statement about the Montreux Record is correct?", correct:"It highlights Ramsar Sites with ecological-character concerns", distractors:["It lists only newly designated sites","It is India's tiger-reserve register","It records only wetland area rankings"], explanation:"The Montreux Record is a Ramsar mechanism for sites where ecological character has changed, is changing or is likely to change.", sourceFactIds:["env-cp019-montreux-concept"] },
]);

const POSITIONS = [0, 1, 2, 3] as const;
const qlCounts = new Map<string, number>();

export const ENV_CP019_REVIEW_QUESTIONS_V1: readonly EnvCp019ReviewQuestion[] = Object.freeze(S.map((seed, index) => {
  const qlIndex = qlCounts.get(seed.qlId) ?? 0;
  qlCounts.set(seed.qlId, qlIndex + 1);
  const correctIndex = POSITIONS[qlIndex % 4];
  const options = [...seed.distractors];
  options.splice(correctIndex, 0, seed.correct);
  const sourceIds = [...new Set(seed.sourceFactIds.flatMap((id) => ENV_CP019_FACT_BY_ID_V1.get(id)?.sourceIds ?? []))];
  return {
    questionId: `ENV-CP019-V1-${String(index + 1).padStart(3, "0")}`,
    chapterId: "ENV-001",
    cpId: "ENV-CP-019",
    qlId: seed.qlId,
    qlName: seed.qlName,
    difficulty: seed.difficulty,
    stem: seed.stem,
    options,
    correctIndex,
    canonicalAnswer: seed.correct,
    explanation: seed.explanation,
    sourceIds,
    sourceFactIds: [...seed.sourceFactIds],
    reviewOnly: true,
    runtimeRegistered: false,
  };
}));
