export const RNK_001_QUESTION_STUDIO_MULTILINGUAL_REVIEW_V1 = Object.freeze({
  chapterId: "RNK-001" as const,
  authority: "RNK-001-QUESTION-STUDIO-MULTILINGUAL-REVIEW-V1" as const,
  sourceFreeze: Object.freeze({
    pr: 945 as const,
    head: "d73b445916d8c10b4551d1a05e75a7ca3973081c" as const,
    workflowRun: 32335249084 as const,
    artifactId: 9394423204 as const,
    artifactDigest: "sha256:e83368ba7ae6e85e9aca493efcc529b36875b329c595babc212d92d52933f7cc" as const,
    multilingualFreeze: true as const,
  }),
  supportedLanguages: ["en", "hi", "pa"] as const,
  reviewGenerationEnabled: true as const,
  canonicalQlRange: "RNK-QL-001..042" as const,
  ql043Allocated: false as const,
  frozenLocaleRuntimeSourceCount: 26 as const,
  lifecycle: Object.freeze({
    questionStudioVisible: true as const,
    reviewOnly: true as const,
    questionBankStatus: "NOT_STORED" as const,
    questionBankWritable: false as const,
    testEligibility: "INELIGIBLE" as const,
    testEligible: false as const,
    mockTestEligible: false as const,
    publiclyPublishable: false as const,
    automaticStudentPublication: false as const,
    newMainMergeAuthorized: false as const,
  }),
});
