import { useEffect, useMemo, useState } from 'react';
import { Activity, Download, RefreshCw } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PageHeader } from '@/components/shared/PageHeader';
import { StatusBadge } from '@/components/shared/StatusBadge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { showToast } from '@/components/shared/toast';
import { getFirebaseAuth } from '@/integrations/firebase';

const apiBase=((import.meta.env.VITE_API_URL as string|undefined)?.trim()||'/api').replace(/\/$/,'');
const number=(value:number)=>new Intl.NumberFormat('en-US').format(Number(value||0));
const date=(value:string)=>new Date(value).toLocaleDateString('en-US',{month:'short',day:'numeric'});
type Data={windowDays:number;summary:{questionCount:number;approvedCount:number;needsFixCount:number;rejectedCount:number;underReviewCount:number;commentCount:number;openCommentCount:number};throughput:Array<{day:string;approved:number;rejected:number;comments:number;resolved:number}>;chapters:Array<{chapterId:string;code:string;name:string;questionCount:number;approvedCount:number;placeholderCount:number}>;reviewers:Array<{reviewerId:string;name:string;email:string;assignments:number;comments:number;resolutions:number}>;quality:{questionsWithoutCurrentVersion:number;approvedWithoutImmutableVersion:number;questionsWithoutTaxonomy:number}};
async function request(path:string):Promise<Data>{const user=getFirebaseAuth()?.currentUser;if(!user)throw new Error('Your administrator session has expired.');const response=await fetch(`${apiBase}${path}`,{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});const body=await response.json().catch(()=>null) as (Data&{error?:string})|null;if(!response.ok)throw new Error(body?.error||`Request failed (${response.status}).`);if(!body)throw new Error('Content Quality returned an empty response.');return body;}
export function ContentQualityPage(){const[windowDays,setWindowDays]=useState('30');const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const refresh=async()=>{setLoading(true);try{setData(await request(`/admin/analytics/content-quality?window=${windowDays}`));}catch(error){showToast.error('Unable to load Content Quality',error instanceof Error?error.message:'Request failed.');}finally{setLoading(false);}};useEffect(()=>{void refresh();},[windowDays]);const rate=useMemo(()=>data?.summary.questionCount?Math.round(data.summary.approvedCount/data.summary.questionCount*100):0,[data]);const exportCsv=async()=>{const user=getFirebaseAuth()?.currentUser;if(!user)return;const response=await fetch(`${apiBase}/admin/analytics/content-quality.csv?window=${windowDays}`,{headers:{Authorization:`Bearer ${await user.getIdToken()}`}});if(!response.ok){showToast.error('Export failed','Unable to export canonical content-quality data.');return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`content-quality-${windowDays}d.csv`;link.click();URL.revokeObjectURL(url);};return <div className="space-y-5"><PageHeader title="Content Quality" description="Canonical review throughput, chapter readiness, unresolved blockers and reviewer workload." icon={<Activity className="h-5 w-5"/>} actions={<><Select value={windowDays} onValueChange={setWindowDays}><SelectTrigger className="w-[150px]"><SelectValue/></SelectTrigger><SelectContent>{['7','30','90','365'].map(v=><SelectItem key={v} value={v}>Last {v} days</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>void exportCsv()}><Download className="mr-1.5 h-4 w-4"/>Export</Button><Button variant="outline" onClick={()=>void refresh()} disabled={loading}><RefreshCw className={`mr-1.5 h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</Button></>} />
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Questions touched" value={number(data?.summary.questionCount||0)}/><Metric label="Approval rate" value={`${rate}%`}/><Metric label="Open review comments" value={number(data?.summary.openCommentCount||0)}/><Metric label="Needs fix" value={number(data?.summary.needsFixCount||0)}/></div>
<Card><CardHeader><CardTitle className="text-base">Review throughput</CardTitle></CardHeader><CardContent>{data?.throughput.length?<ResponsiveContainer width="100%" height={260}><AreaChart data={data.throughput}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" tickFormatter={date}/><YAxis allowDecimals={false}/><Tooltip labelFormatter={(v)=>date(String(v))}/><Area type="monotone" dataKey="approved" name="Approved" fillOpacity={0.2}/><Area type="monotone" dataKey="resolved" name="Resolved comments" fillOpacity={0.1}/></AreaChart></ResponsiveContainer>:<p className="py-12 text-center text-sm text-muted-foreground">No review activity in this window.</p>}</CardContent></Card>
<div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Chapter readiness signals</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Chapter</TableHead><TableHead className="text-right">Approved</TableHead><TableHead className="text-right">Placeholders</TableHead></TableRow></TableHeader><TableBody>{data?.chapters.slice(0,20).map(row=><TableRow key={row.chapterId}><TableCell><p className="font-medium">{row.name}</p><p className="text-xs text-muted-foreground">{row.code} · {row.questionCount} questions</p></TableCell><TableCell className="text-right">{row.approvedCount}</TableCell><TableCell className="text-right"><StatusBadge tone={row.placeholderCount?'destructive':'success'}>{row.placeholderCount}</StatusBadge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Reviewer workload</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Reviewer</TableHead><TableHead className="text-right">Assigned</TableHead><TableHead className="text-right">Comments</TableHead><TableHead className="text-right">Resolved</TableHead></TableRow></TableHeader><TableBody>{data?.reviewers.map(row=><TableRow key={row.reviewerId}><TableCell><p className="font-medium">{row.name}</p><p className="text-xs text-muted-foreground">{row.email}</p></TableCell><TableCell className="text-right">{row.assignments}</TableCell><TableCell className="text-right">{row.comments}</TableCell><TableCell className="text-right">{row.resolutions}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
<Card><CardHeader><CardTitle className="text-base">Data-quality diagnostics</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Metric label="Without current version" value={number(data?.quality.questionsWithoutCurrentVersion||0)}/><Metric label="Approved without immutable version" value={number(data?.quality.approvedWithoutImmutableVersion||0)}/><Metric label="Without taxonomy" value={number(data?.quality.questionsWithoutTaxonomy||0)}/></CardContent></Card></div>}
function Metric({label,value}:{label:string;value:string}){return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>}
export default ContentQualityPage;
