import { canonicalMisSemanticAuthorityId } from './semantic-authority-registry';

export const MIS_PERMANENT_QL_IDS = Object.freeze([
  'MIS-QL-001',
  'MIS-QL-002',
  'MIS-QL-003',
  'MIS-QL-004',
  'MIS-QL-005',
  'MIS-QL-006',
  'MIS-QL-007',
  'MIS-QL-008',
  'MIS-QL-009',
  'MIS-QL-010',
  'MIS-QL-011',
  'MIS-QL-012',
  'MIS-QL-013',
  'MIS-QL-014',
  'MIS-QL-015',
  'MIS-QL-016',
  'MIS-QL-017',
  'MIS-QL-018',
  'MIS-QL-019',
  'MIS-QL-020',
  'MIS-QL-021',
  'MIS-QL-022',
  'MIS-QL-023',
  'MIS-QL-024',
  'MIS-QL-025',
  'MIS-QL-026',
  'MIS-QL-027',
  'MIS-QL-028',
  'MIS-QL-029',
  'MIS-QL-030',
  'MIS-QL-031',
  'MIS-QL-032',
  'MIS-QL-033',
  'MIS-QL-034',
  'MIS-QL-035',
  'MIS-QL-036',
  'MIS-QL-037',
  'MIS-QL-038',
  'MIS-QL-039',
  'MIS-QL-040',
  'MIS-QL-041',
  'MIS-QL-042',
  'MIS-QL-043',
  'MIS-QL-044',
  'MIS-QL-045',
  'MIS-QL-046',
  'MIS-QL-047',
  'MIS-QL-048',
  'MIS-QL-049',
  'MIS-QL-050',
  'MIS-QL-051',
  'MIS-QL-052',
  'MIS-QL-053',
  'MIS-QL-054',
  'MIS-QL-055',
  'MIS-QL-056',
  'MIS-QL-057',
  'MIS-QL-058',
  'MIS-QL-059',
  'MIS-QL-060',
  'MIS-QL-061',
  'MIS-QL-062',
  'MIS-QL-063',
  'MIS-QL-064',
  'MIS-QL-065',
  'MIS-QL-066',
  'MIS-QL-067',
  'MIS-QL-068',
  'MIS-QL-069',
  'MIS-QL-070',
  'MIS-QL-071',
  'MIS-QL-072',
  'MIS-QL-073',
] as const);

export type MisPermanentQlId = (typeof MIS_PERMANENT_QL_IDS)[number];

export interface MisPermanentQlRegistryEntry {
  readonly permanentQlId: MisPermanentQlId;
  readonly canonicalCandidateId: string;
  readonly checkpointId: string;
  readonly allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE';
}

export const MIS_SOURCE_THIN_CANONICAL_HOLDS = Object.freeze([
  'MIS-CAND-034',
  'MIS-CAND-095',
] as const);

export const MIS_PERMANENT_QL_REGISTRY: readonly MisPermanentQlRegistryEntry[] = Object.freeze([
  Object.freeze({ permanentQlId: 'MIS-QL-001', canonicalCandidateId: 'MIS-CAND-001', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-002', canonicalCandidateId: 'MIS-CAND-002', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-003', canonicalCandidateId: 'MIS-CAND-003', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-004', canonicalCandidateId: 'MIS-CAND-004', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-005', canonicalCandidateId: 'MIS-CAND-005', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-006', canonicalCandidateId: 'MIS-CAND-006', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-007', canonicalCandidateId: 'MIS-CAND-007', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-008', canonicalCandidateId: 'MIS-CAND-008', checkpointId: 'MIS-CP-001', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-009', canonicalCandidateId: 'MIS-CAND-009', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-010', canonicalCandidateId: 'MIS-CAND-010', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-011', canonicalCandidateId: 'MIS-CAND-011', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-012', canonicalCandidateId: 'MIS-CAND-012', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-013', canonicalCandidateId: 'MIS-CAND-013', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-014', canonicalCandidateId: 'MIS-CAND-014', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-015', canonicalCandidateId: 'MIS-CAND-015', checkpointId: 'MIS-CP-002', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-016', canonicalCandidateId: 'MIS-CAND-016', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-017', canonicalCandidateId: 'MIS-CAND-017', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-018', canonicalCandidateId: 'MIS-CAND-018', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-019', canonicalCandidateId: 'MIS-CAND-019', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-020', canonicalCandidateId: 'MIS-CAND-020', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-021', canonicalCandidateId: 'MIS-CAND-021', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-022', canonicalCandidateId: 'MIS-CAND-022', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-023', canonicalCandidateId: 'MIS-CAND-023', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-024', canonicalCandidateId: 'MIS-CAND-024', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-025', canonicalCandidateId: 'MIS-CAND-025', checkpointId: 'MIS-CP-003', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-026', canonicalCandidateId: 'MIS-CAND-026', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-027', canonicalCandidateId: 'MIS-CAND-027', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-028', canonicalCandidateId: 'MIS-CAND-030', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-029', canonicalCandidateId: 'MIS-CAND-031', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-030', canonicalCandidateId: 'MIS-CAND-032', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-031', canonicalCandidateId: 'MIS-CAND-033', checkpointId: 'MIS-CP-004', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-032', canonicalCandidateId: 'MIS-CAND-046', checkpointId: 'MIS-CP-006', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-033', canonicalCandidateId: 'MIS-CAND-050', checkpointId: 'MIS-CP-007', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-034', canonicalCandidateId: 'MIS-CAND-051', checkpointId: 'MIS-CP-007', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-035', canonicalCandidateId: 'MIS-CAND-053', checkpointId: 'MIS-CP-007', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-036', canonicalCandidateId: 'MIS-CAND-054', checkpointId: 'MIS-CP-007', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-037', canonicalCandidateId: 'MIS-CAND-059', checkpointId: 'MIS-CP-008', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-038', canonicalCandidateId: 'MIS-CAND-064', checkpointId: 'MIS-CP-009', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-039', canonicalCandidateId: 'MIS-CAND-067', checkpointId: 'MIS-CP-009', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-040', canonicalCandidateId: 'MIS-CAND-069', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-041', canonicalCandidateId: 'MIS-CAND-070', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-042', canonicalCandidateId: 'MIS-CAND-071', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-043', canonicalCandidateId: 'MIS-CAND-072', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-044', canonicalCandidateId: 'MIS-CAND-073', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-045', canonicalCandidateId: 'MIS-CAND-074', checkpointId: 'MIS-CP-010', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-046', canonicalCandidateId: 'MIS-CAND-075', checkpointId: 'MIS-CP-011', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-047', canonicalCandidateId: 'MIS-CAND-076', checkpointId: 'MIS-CP-011', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-048', canonicalCandidateId: 'MIS-CAND-077', checkpointId: 'MIS-CP-011', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-049', canonicalCandidateId: 'MIS-CAND-078', checkpointId: 'MIS-CP-011', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-050', canonicalCandidateId: 'MIS-CAND-084', checkpointId: 'MIS-CP-013', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-051', canonicalCandidateId: 'MIS-CAND-085', checkpointId: 'MIS-CP-013', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-052', canonicalCandidateId: 'MIS-CAND-087', checkpointId: 'MIS-CP-015', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-053', canonicalCandidateId: 'MIS-CAND-088', checkpointId: 'MIS-CP-015', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-054', canonicalCandidateId: 'MIS-CAND-089', checkpointId: 'MIS-CP-015', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-055', canonicalCandidateId: 'MIS-CAND-090', checkpointId: 'MIS-CP-016', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-056', canonicalCandidateId: 'MIS-CAND-091', checkpointId: 'MIS-CP-017', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-057', canonicalCandidateId: 'MIS-CAND-092', checkpointId: 'MIS-CP-018', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-058', canonicalCandidateId: 'MIS-CAND-093', checkpointId: 'MIS-CP-018', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-059', canonicalCandidateId: 'MIS-CAND-094', checkpointId: 'MIS-CP-018', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-060', canonicalCandidateId: 'MIS-CAND-096', checkpointId: 'MIS-CP-019', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-061', canonicalCandidateId: 'MIS-CAND-098', checkpointId: 'MIS-CP-019', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-062', canonicalCandidateId: 'MIS-CAND-099', checkpointId: 'MIS-CP-019', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-063', canonicalCandidateId: 'MIS-CAND-100', checkpointId: 'MIS-CP-019', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-064', canonicalCandidateId: 'MIS-CAND-101', checkpointId: 'MIS-CP-020', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-065', canonicalCandidateId: 'MIS-CAND-102', checkpointId: 'MIS-CP-020', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-066', canonicalCandidateId: 'MIS-CAND-103', checkpointId: 'MIS-CP-020', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-067', canonicalCandidateId: 'MIS-CAND-104', checkpointId: 'MIS-CP-021', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-068', canonicalCandidateId: 'MIS-CAND-105', checkpointId: 'MIS-CP-021', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-069', canonicalCandidateId: 'MIS-CAND-106', checkpointId: 'MIS-CP-022', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-070', canonicalCandidateId: 'MIS-CAND-107', checkpointId: 'MIS-CP-023', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-071', canonicalCandidateId: 'MIS-CAND-108', checkpointId: 'MIS-CP-024', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-072', canonicalCandidateId: 'MIS-CAND-111', checkpointId: 'MIS-CP-027', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
  Object.freeze({ permanentQlId: 'MIS-QL-073', canonicalCandidateId: 'MIS-CAND-112', checkpointId: 'MIS-CP-028', allocationStatus: 'PERMANENT_ID_ALLOCATED_INACTIVE' as const }),
]);

export const MIS_PERMANENT_QL_BY_ID: Readonly<Record<MisPermanentQlId, MisPermanentQlRegistryEntry>> =
  Object.freeze(Object.fromEntries(MIS_PERMANENT_QL_REGISTRY.map((entry) => [entry.permanentQlId, entry])) as Record<MisPermanentQlId, MisPermanentQlRegistryEntry>);

export const MIS_PERMANENT_QL_BY_CANONICAL_CANDIDATE: Readonly<Record<string, MisPermanentQlRegistryEntry>> =
  Object.freeze(Object.fromEntries(MIS_PERMANENT_QL_REGISTRY.map((entry) => [entry.canonicalCandidateId, entry])));

export function permanentQlForMisCandidate(candidateId: string): MisPermanentQlId | null {
  const canonicalCandidateId = canonicalMisSemanticAuthorityId(candidateId);
  const entry = MIS_PERMANENT_QL_BY_CANONICAL_CANDIDATE[canonicalCandidateId];
  return entry?.permanentQlId ?? null;
}

export const MIS_PERMANENT_QL_ALLOCATION_STATE = Object.freeze({
  registryVersion: 1,
  canonicalSemanticAuthorityCount: 75,
  allocatedPermanentQlCount: 73,
  sourceThinHoldCount: 2,
  firstAllocatedId: 'MIS-QL-001' as const,
  lastAllocatedId: 'MIS-QL-073' as const,
  nextAvailableId: 'MIS-QL-074' as const,
  allocatedRange: 'MIS-QL-001..MIS-QL-073' as const,
  englishStatus: 'ENGLISH_EDITORIAL_FROZEN' as const,
  localizationStatus: 'NOT_STARTED' as const,
  activeQlCount: 0,
  questionBankWritableCount: 0,
  testEligibleCount: 0,
  publiclyPublishableCount: 0,
});
