export const PFC_TPF_LOCALIZATION_PRODUCT_OWNER_APPROVAL_V2 = Object.freeze({
  authorityId: "PFC-TPF-HI-PA-LOCALIZATION-PRODUCT-OWNER-APPROVAL-V2" as const,
  approved: true,
  approvedAt: "2026-08-23" as const,
  approvalBasis: "PRODUCT_OWNER_APPROVED_LOCALIZATION_V2_1_REVIEW" as const,
  localizationAuthorityId: "PFC-TPF-HI-PA-LOCALIZATION-V2" as const,
  editorialRevision: "V2.1" as const,
  approvedExactHeadSha: "3ed5c5f523853791848f1be9ab44e3bb3be46584" as const,
  approvedWorkflowRunId: 32614131589,
  approvedArtifactId: 9486442090,
  approvedArtifactDigest: "sha256:a2af041c81300db6942ec9914bc623f8ed8f13e2213f69c3add8688a46a83c15" as const,
  approvedEnglishQuestionCount: 84,
  approvedHindiQuestionCount: 84,
  approvedPunjabiQuestionCount: 84,
  acceptedEditorialRemediations: [
    "HINDI_CASE_AGREEMENT_REMEDIATED",
    "PUNJABI_CASE_AGREEMENT_REMEDIATED",
    "LEARNER_FACING_ENGLISH_JARGON_REMOVED",
    "QUESTION_AWARE_EXPLANATION_DIVERSITY_ADDED",
    "GEOMETRY_OPTIONS_ANSWERS_IDS_AND_FINGERPRINTS_INVARIANT",
  ] as const,
  authorization: {
    localizationFreezeAllowed: true,
    seededQuestionStudioIntegrationAllowed: true,
    questionBankWritesAllowed: false,
    publicTestEligibilityAllowed: false,
    automaticPublicationAllowed: false,
    mergeAllowed: false,
    deploymentAllowed: false,
  },
  nextGate: "PFC_TPF_HI_PA_LOCALIZATION_FREEZE_V2" as const,
} as const);
