import {authorBilingualQl,ONE} from './com004-localization-authoring-v2';
const url='https://example.org/reports/index.html';
export const COM004_LOCALIZATION_QL008_V2=authorBilingualQl(8,[
['URL का पूरा नाम क्या है?','URL ਦਾ ਪੂਰਾ ਨਾਂ ਕੀ ਹੈ?','Uniform Resource Locator|Universal Routing Link|Unified Resource Language|User Reference Location','Uniform Resource Locator|Universal Routing Link|Unified Resource Language|User Reference Location','URL संसाधन का पता बताने वाला Uniform Resource Locator है।','URL ਸਰੋਤ ਦਾ ਪਤਾ ਦੱਸਣ ਵਾਲਾ Uniform Resource Locator ਹੈ।'],
[`${url} में scheme कौन-सी है?`,`${url} ਵਿੱਚ scheme ਕਿਹੜੀ ਹੈ?`,'https|example.org|/reports/index.html|.org','https|example.org|/reports/index.html|.org','कोलन से पहले https पहुँच के प्रोटोकॉल को दर्शाता है।','ਕੋਲਨ ਤੋਂ ਪਹਿਲਾਂ https ਪਹੁੰਚ ਦੇ ਪ੍ਰੋਟੋਕੋਲ ਨੂੰ ਦਰਸਾਉਂਦਾ ਹੈ।'],
[`${url} में host/domain कौन-सा है?`,`${url} ਵਿੱਚ host/domain ਕਿਹੜਾ ਹੈ?`,'example.org|https|/reports/index.html|केवल index.html, क्योंकि हर host एक फाइल है','example.org|https|/reports/index.html|ਕੇਵਲ index.html, ਕਿਉਂਕਿ ਹਰ host ਇੱਕ ਫਾਈਲ ਹੈ','example.org होस्ट है; https scheme और /reports/index.html path है।','example.org ਹੋਸਟ ਹੈ; https scheme ਅਤੇ /reports/index.html path ਹੈ।'],
[`${url} में संसाधन का path कौन-सा है?`,`${url} ਵਿੱਚ ਸਰੋਤ ਦਾ path ਕਿਹੜਾ ਹੈ?`,'/reports/index.html|https|example.org|.org','/reports/index.html|https|example.org|.org','होस्ट के बाद /reports/index.html संसाधन का पथ देता है।','ਹੋਸਟ ਤੋਂ ਬਾਅਦ /reports/index.html ਸਰੋਤ ਦਾ ਪੱਥ ਦਿੰਦਾ ਹੈ।'],
['वेब पते में example.org जैसे पढ़ने योग्य होस्ट नाम को क्या कहते हैं?','ਵੈੱਬ ਪਤੇ ਵਿੱਚ example.org ਵਰਗੇ ਪੜ੍ਹਨਯੋਗ ਹੋਸਟ ਨਾਂ ਨੂੰ ਕੀ ਕਹਿੰਦੇ ਹਨ?','Domain name|Browser cache|Search query|E-mail attachment','Domain name|Browser cache|Search query|E-mail attachment','example.org डोमेन नाम है; यह कैश, खोज प्रश्न या संलग्न फाइल नहीं है।','example.org ਡੋਮੇਨ ਨਾਂ ਹੈ; ਇਹ ਕੈਸ਼, ਖੋਜ ਪ੍ਰਸ਼ਨ ਜਾਂ ਨੱਥੀ ਫਾਈਲ ਨਹੀਂ ਹੈ।'],
['example.in के अंत में .in क्या दर्शाता है?','example.in ਦੇ ਅੰਤ ਵਿੱਚ .in ਕੀ ਦਰਸਾਉਂਦਾ ਹੈ?','भारत का देश-कोड शीर्ष-स्तरीय डोमेन|HTTPS scheme|पूरा URL path|ब्राउज़र नियंत्रण','ਭਾਰਤ ਦਾ ਦੇਸ਼-ਕੋਡ ਸਿਖਰ-ਪੱਧਰੀ ਡੋਮੇਨ|HTTPS scheme|ਪੂਰਾ URL path|ਬ੍ਰਾਊਜ਼ਰ ਕੰਟਰੋਲ','.in भारत का देश-कोड डोमेन प्रत्यय है, प्रोटोकॉल या पथ नहीं।','.in ਭਾਰਤ ਦਾ ਦੇਸ਼-ਕੋਡ ਡੋਮੇਨ ਪਿਛੇਤਰ ਹੈ, ਪ੍ਰੋਟੋਕੋਲ ਜਾਂ ਪੱਥ ਨਹੀਂ।'],
['.com और .org के बारे में कौन-सा कथन सही है?','.com ਅਤੇ .org ਬਾਰੇ ਕਿਹੜਾ ਕਥਨ ਸਹੀ ਹੈ?','प्रत्यय अकेला संस्था का वास्तविक प्रकार साबित नहीं करता|हर .org कानूनी रूप से गैर-लाभकारी है|हर .com सूचीबद्ध व्यावसायिक कंपनी का है|प्रत्यय सारी सामग्री की विश्वसनीयता साबित करता है','ਪਿਛੇਤਰ ਇਕੱਲਾ ਸੰਸਥਾ ਦੀ ਅਸਲੀ ਕਿਸਮ ਸਾਬਤ ਨਹੀਂ ਕਰਦਾ|ਹਰ .org ਕਾਨੂੰਨੀ ਤੌਰ ਉੱਤੇ ਗੈਰ-ਮੁਨਾਫ਼ਾਕਾਰੀ ਹੈ|ਹਰ .com ਸੂਚੀਬੱਧ ਵਪਾਰਕ ਕੰਪਨੀ ਦਾ ਹੈ|ਪਿਛੇਤਰ ਸਾਰੀ ਸਮੱਗਰੀ ਦੀ ਭਰੋਸੇਯੋਗਤਾ ਸਾਬਤ ਕਰਦਾ ਹੈ','ये सामान्य डोमेन प्रत्यय हैं। पंजीकरण से संस्था की प्रकृति या सामग्री सत्यापित नहीं होती।','ਇਹ ਆਮ ਡੋਮੇਨ ਪਿਛੇਤਰ ਹਨ। ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨਾਲ ਸੰਸਥਾ ਦੀ ਕਿਸਮ ਜਾਂ ਸਮੱਗਰੀ ਤਸਦੀਕ ਨਹੀਂ ਹੁੰਦੀ।'],
['वेब पते का कौन-सा घटक सही मिलाया गया है?','ਵੈੱਬ ਪਤੇ ਦਾ ਕਿਹੜਾ ਹਿੱਸਾ ਸਹੀ ਮਿਲਾਇਆ ਗਿਆ ਹੈ?','Scheme — आरंभ में पहुँच/प्रोटोकॉल बताती है|Path — हमेशा ISP बताता है|डोमेन प्रत्यय — संस्था का कानूनी प्रकार प्रमाणित करता है|Host name — हमेशा स्थानीय कैश है','Scheme — ਸ਼ੁਰੂ ਵਿੱਚ ਪਹੁੰਚ/ਪ੍ਰੋਟੋਕੋਲ ਦੱਸਦੀ ਹੈ|Path — ਹਮੇਸ਼ਾ ISP ਦੱਸਦਾ ਹੈ|ਡੋਮੇਨ ਪਿਛੇਤਰ — ਸੰਸਥਾ ਦੀ ਕਾਨੂੰਨੀ ਕਿਸਮ ਪ੍ਰਮਾਣਿਤ ਕਰਦਾ ਹੈ|Host name — ਹਮੇਸ਼ਾ ਸਥਾਨਕ ਕੈਸ਼ ਹੈ','Scheme पहुँच का तरीका बताती है; path होस्ट के भीतर संसाधन का स्थान बताता है।','Scheme ਪਹੁੰਚ ਦਾ ਤਰੀਕਾ ਦੱਸਦੀ ਹੈ; path ਹੋਸਟ ਦੇ ਅੰਦਰ ਸਰੋਤ ਦਾ ਸਥਾਨ ਦੱਸਦਾ ਹੈ।'],
['दो URL में domain समान लेकिन path अलग हैं। क्या निष्कर्ष सही है?','ਦੋ URL ਵਿੱਚ domain ਇੱਕੋ ਪਰ path ਵੱਖਰੇ ਹਨ। ਕਿਹੜਾ ਸਿੱਟਾ ਸਹੀ ਹੈ?','एक होस्ट के अलग संसाधन हो सकते हैं|ISP अनिवार्यतः अलग होंगे|शीर्ष-स्तरीय डोमेन अलग होंगे|दोनों HTTPS नहीं हो सकते','ਇੱਕ ਹੋਸਟ ਦੇ ਵੱਖਰੇ ਸਰੋਤ ਹੋ ਸਕਦੇ ਹਨ|ISP ਲਾਜ਼ਮੀ ਵੱਖਰੇ ਹੋਣਗੇ|ਸਿਖਰ-ਪੱਧਰੀ ਡੋਮੇਨ ਵੱਖਰੇ ਹੋਣਗੇ|ਦੋਵੇਂ HTTPS ਨਹੀਂ ਹੋ ਸਕਦੇ','समान होस्ट के भीतर अलग पथ अलग संसाधनों की पहचान कर सकते हैं।','ਇੱਕੋ ਹੋਸਟ ਦੇ ਅੰਦਰ ਵੱਖਰੇ ਪੱਥ ਵੱਖਰੇ ਸਰੋਤਾਂ ਦੀ ਪਛਾਣ ਕਰ ਸਕਦੇ ਹਨ।'],
['कथन: (1) URL में scheme, host और path हो सकते हैं। (2) प्रत्यय हमेशा साइट संचालक को प्रमाणित करता है।','ਕਥਨ: (1) URL ਵਿੱਚ scheme, host ਅਤੇ path ਹੋ ਸਕਦੇ ਹਨ। (2) ਪਿਛੇਤਰ ਹਮੇਸ਼ਾ ਸਾਈਟ ਚਲਾਉਣ ਵਾਲੇ ਨੂੰ ਪ੍ਰਮਾਣਿਤ ਕਰਦਾ ਹੈ।',...ONE,'पहला संरचना बताता है और सही है। प्रत्यय अकेला संचालक की पहचान का प्रमाण नहीं है।','ਪਹਿਲਾ ਬਣਤਰ ਦੱਸਦਾ ਹੈ ਅਤੇ ਸਹੀ ਹੈ। ਪਿਛੇਤਰ ਇਕੱਲਾ ਸੰਚਾਲਕ ਦੀ ਪਛਾਣ ਦਾ ਸਬੂਤ ਨਹੀਂ ਹੈ।'],
['https://portal.example.in/forms/apply में बाएँ से दाएँ क्रम क्या है?','https://portal.example.in/forms/apply ਵਿੱਚ ਖੱਬੇ ਤੋਂ ਸੱਜੇ ਕ੍ਰਮ ਕੀ ਹੈ?','Scheme → host/domain → path|Path → browser → ISP|Domain suffix → search engine → operating system|ISP → scheme → browser cache','Scheme → host/domain → path|Path → browser → ISP|Domain suffix → search engine → operating system|ISP → scheme → browser cache','https scheme, portal.example.in host और /forms/apply path है।','https scheme, portal.example.in host ਅਤੇ /forms/apply path ਹੈ।'],
['https://example.org/results और https://example.org/notices में क्या समान है?','https://example.org/results ਅਤੇ https://example.org/notices ਵਿੱਚ ਕੀ ਸਾਂਝਾ ਹੈ?','डोमेन example.org|पूरा संसाधन पथ|पूरा URL|पेज नाम results','ਡੋਮੇਨ example.org|ਪੂਰਾ ਸਰੋਤ ਪੱਥ|ਪੂਰਾ URL|ਪੰਨੇ ਦਾ ਨਾਂ results','होस्ट example.org समान है; /results और /notices अलग पथ हैं।','ਹੋਸਟ example.org ਸਾਂਝਾ ਹੈ; /results ਅਤੇ /notices ਵੱਖਰੇ ਪੱਥ ਹਨ।'],
]);
