export type HisCp010Fact=readonly[id:string,explanation:string,sourceIds:readonly string[]];

export const HIS_CP010_SOURCES_V1=[
  {id:"NIOS-HISTORY-315-LESSON10-MUGHAL-RULE",label:"NIOS History 315 Lesson 10 — Establishment of the Mughal Rule",url:"https://digital.nios.ac.in/content/315en/315_History_Eng_Lesson10.pdf"},
  {id:"NIOS-HISTORY-315-LESSON12-ADMINISTRATION",label:"NIOS History 315 Lesson 12 — Administrative System and Institutions",url:"https://digital.nios.ac.in/content/315en/315_History_Eng_Lesson12.pdf"},
] as const;

export const HIS_CP010_SOURCE_IDS_V1=new Set(HIS_CP010_SOURCES_V1.map(s=>s.id));
const L10=["NIOS-HISTORY-315-LESSON10-MUGHAL-RULE"] as const;
const L12=["NIOS-HISTORY-315-LESSON12-ADMINISTRATION"] as const;

export const HIS_CP010_FACTS_V1:readonly HisCp010Fact[]=[
  ["babur-timurid","Babur traced his paternal lineage to Timur, so the Mughal ruling house is also described as Timurid.",L10],
  ["babur-panipat","Babur defeated Ibrahim Lodi at the First Battle of Panipat in 1526 and gained control of Delhi and Agra.",L10],
  ["babur-rumi","At Panipat, Babur effectively used the Rumi or Ottoman method of warfare, including firearms and field defences.",L10],
  ["babur-khanwa","Babur defeated Rana Sanga at Khanwa in 1527, removing the strongest Rajput challenge to his new position in North India.",L10],
  ["babur-chanderi","Babur defeated Medini Rai at Chanderi in 1528.",L10],
  ["babur-challenges","After Panipat, Babur still faced Rajput resistance, Afghan resistance in the east, and reluctance among some of his own nobles to remain in India.",L10],
  ["humayun-succession","Humayun succeeded Babur in 1530.",L10],
  ["humayun-brothers","Humayun's position was weakened because Timurid custom required him to share power with his brothers, especially Kamran.",L10],
  ["sher-rise","Farid, later known as Sher Khan and Sher Shah, rose to become the leading Afghan power in Bihar and Bengal.",L10],
  ["chausa","Sher Shah defeated Humayun at Chausa in 1539.",L10],
  ["kannauj","Sher Shah defeated Humayun again at Kannauj in 1540, forcing Humayun out of North India.",L10],
  ["second-afghan","Sher Shah and his successors ruled the Second Afghan Empire from 1540 to 1555.",L10],
  ["sher-admin","Sher Shah introduced important administrative and revenue reforms and strengthened the road network, including the Grand Trunk Road.",L10],
  ["humayun-restoration","Humayun recaptured Delhi and Agra in 1555 and restored Mughal rule.",L10],
  ["humayun-death","Humayun died in 1556 after falling from the stairs of the library at Sher Mandal in Delhi.",L10],
  ["akbar-accession","Akbar became emperor in 1556 while still a teenager.",L10],
  ["bairam-regent","Bairam Khan served as Akbar's regent from 1556 to 1560.",L10],
  ["second-panipat","During Bairam Khan's regency, Mughal forces defeated Hemu at the Second Battle of Panipat in 1556.",L10],
  ["bairam-dismissal","Akbar removed Bairam Khan in 1560 when he was ready to exercise direct control over the empire.",L10],
  ["akbar-malwa","Akbar's early expansion into central India included the conquest of Malwa, ruled by Baz Bahadur.",L10],
  ["akbar-gondwana","Gondwana, ruled by Rani Durgawati, was conquered and annexed in 1564.",L10],
  ["akbar-bharmal","Raja Bharmal of Amber was among the earliest Rajput rulers to enter into alliance with Akbar.",L10],
  ["akbar-rajput-service","Akbar sought Rajput cooperation by admitting Rajput rulers and nobles into Mughal service and by building political alliances.",L10],
  ["akbar-mewar","Maharana Pratap of Mewar remained a major Rajput opponent and did not submit to Akbar.",L10],
  ["akbar-chittor","Akbar captured Chittor after a prolonged siege, although resistance from Mewar continued.",L10],
  ["akbar-gujarat","Akbar conquered Gujarat in 1572 and organised it as a Mughal province.",L10],
  ["akbar-bengal-bihar","Akbar's campaigns brought Bihar and Bengal, then strong centres of Afghan power, under Mughal control.",L10],
  ["akbar-kashmir","Kashmir was annexed to the Mughal Empire in 1586.",L10],
  ["akbar-northwest","By 1595 Mughal supremacy had been established across much of the north-west, including Kabul and parts of Sindh.",L10],
  ["akbar-deccan-offers","In 1591 Akbar sent envoys to Deccan states asking them to accept Mughal sovereignty, but the response was limited.",L10],
  ["akbar-watan-jagir","Many Rajput mansabdars retained their ancestral territories as hereditary Watan Jagirs while also serving the Mughal emperor.",L10],
  ["jahangir-mewar","Under Jahangir, Rana Amar Singh of Mewar accepted Mughal suzerainty and many territories were restored to him.",L10],
  ["jahangir-deccan","Jahangir made little territorial gain in the Deccan, where Malik Ambar remained a major opponent of Mughal expansion.",L10],
  ["shahjahan-ahmednagar","Shah Jahan pursued a more aggressive Deccan policy and ended the independence of Ahmednagar.",L10],
  ["shahjahan-treaties","In 1636, Bijapur and Golconda accepted Mughal suzerainty and agreed to pay tribute rather than being immediately annexed.",L10],
  ["shahjahan-rajputs","Rajput nobles continued to hold high mansabs under Shah Jahan and served in major Mughal campaigns.",L10],
  ["aurangzeb-marwar","Mughal-Rajput relations worsened under Aurangzeb, especially over the succession dispute in Marwar.",L10],
  ["aurangzeb-bijapur","Aurangzeb annexed Bijapur during the final phase of his Deccan policy.",L10],
  ["aurangzeb-golconda","Aurangzeb annexed Golconda by 1687.",L10],
  ["aurangzeb-marathas","The Marathas remained a major and prolonged challenge to Mughal authority under Aurangzeb.",L10],
  ["aurangzeb-deccan-years","Aurangzeb spent much of the last two decades of his reign campaigning in the Deccan.",L10],
  ["aurangzeb-extent","Under Aurangzeb, the Mughal Empire reached its greatest territorial extent.",L10],
  ["aurangzeb-revolts","Aurangzeb's reign also faced revolts and resistance from groups including Jats, Satnamis, Afghans, Sikhs and Marathas.",L10],
  ["aurangzeb-death","Aurangzeb died in 1707 in the Deccan.",L10],
  ["admin-diwan-kul","The Diwan-i-Kul was the chief financial officer and supervised imperial revenue and expenditure.",L12],
  ["admin-mir-bakshi","The Mir Bakshi supervised military administration, mansab appointments and the maintenance of mansabdars' contingents.",L12],
  ["admin-mir-saman","The Mir Saman supervised the royal karkhanas, purchases and stores for the imperial household.",L12],
  ["admin-suba","The Mughal Empire was divided into provinces called subas, each headed by a Subedar appointed by the emperor.",L12],
  ["admin-prov-diwan","The provincial Diwan supervised revenue collection and accounts independently of the Subedar.",L12],
  ["admin-local-hierarchy","Subas were divided into Sarkars, Sarkars into Parganas, and villages formed the smallest local administrative unit.",L12],
  ["mansab-purpose","Akbar developed the mansabdari system to rank officials, fix their pay and specify the military contingent they were expected to maintain.",L12],
  ["mansab-zat","Zat indicated a mansabdar's personal rank and position in the official hierarchy.",L12],
  ["mansab-sawar","Sawar indicated the size of the cavalry contingent associated with a mansabdar's rank.",L12],
  ["mansab-jahangir","Jahangir introduced the du-aspa sih-aspa provision to strengthen selected mansabdars' cavalry obligations without raising their Zat rank.",L12],
  ["mansab-shahjahan","Shah Jahan introduced the month-scale to adjust mansab payments when actual jagir income fell below estimated income.",L12],
  ["jagir-definition","A jagir was a revenue assignment granted to an official, commonly in place of cash salary.",L12],
  ["khalisa-definition","Khalisa revenue went directly to the imperial treasury rather than being assigned to a jagirdar.",L12],
  ["jagir-transfer","Most Mughal jagirs were transferable and were not permanent hereditary possessions.",L12],
  ["watan-jagir","Watan Jagirs were hereditary and non-transferable holdings of local rajas or zamindars in their own territories.",L12],
  ["jagir-supervision","Imperial officials monitored jagirdars and expected them to collect only authorised revenue under imperial regulations.",L12],
];

export const HIS_CP010_FACT_BY_ID_V1=new Map(HIS_CP010_FACTS_V1.map(f=>[f[0],f]));