import type { CaeScenarioFamilyAuthority } from "./types.ts";
import { CAE_SATURATION_RENDERING_CONSTRAINTS as constraints, saturationBranchVariant as branch, saturationChainVariant as chain, saturationEvent as e, saturationParallelVariant as parallel, saturationText as l, type SaturationScale } from "./causal-world-saturation-utils.ts";

const S0: SaturationScale = { scope: "REGIONAL", magnitude: "HIGH", severity: "MODERATE" };
const S1: SaturationScale = { scope: "SITE", magnitude: "HIGH", severity: "MODERATE" };
const S2: SaturationScale = { scope: "SITE", magnitude: "HIGH", severity: "HIGH" };

export const CAE_001_SATURATION_WAVE1_GROUP_A = [
  {
    id: "CAE-FAM-AGRICULTURE-SUPPLY", domain: "INFRASTRUCTURE", topology: "DIRECT_CHAIN",
    allowedProjectionKinds: ["DIRECT_RELATIONSHIP", "INDIRECT_CAUSAL_CHAIN", "MULTI_EVENT_SEQUENCE"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      chain("canal-irrigation", S0, l("On farms supplied by a canal during the irrigation cycle.", "सिंचाई चक्र के दौरान नहर से पानी पाने वाले खेतों में।", "ਸਿੰਚਾਈ ਚੱਕਰ ਦੌਰਾਨ ਨਹਿਰ ਤੋਂ ਪਾਣੀ ਲੈਣ ਵਾਲੇ ਖੇਤਾਂ ਵਿੱਚ।"), e("A canal gate was closed for emergency repair.", "नहर का एक गेट आपात मरम्मत के लिए बंद किया गया।", "ਨਹਿਰ ਦਾ ਇੱਕ ਗੇਟ ਐਮਰਜੈਂਸੀ ਮੁਰੰਮਤ ਲਈ ਬੰਦ ਕੀਤਾ ਗਿਆ।"), e("Water flow into the field channels fell.", "खेतों की नालियों में पानी का प्रवाह घट गया।", "ਖੇਤਾਂ ਵਾਲੀਆਂ ਖਾਲਾਂ ਵਿੱਚ ਪਾਣੀ ਦਾ ਵਹਾਅ ਘੱਟ ਗਿਆ।"), e("Irrigation of several fields was delayed.", "कई खेतों की सिंचाई में देरी हुई।", "ਕਈ ਖੇਤਾਂ ਦੀ ਸਿੰਚਾਈ ਵਿੱਚ ਦੇਰੀ ਹੋਈ।"), e("Farmers shifted irrigation to later hours.", "किसानों ने सिंचाई बाद के समय के लिए टाल दी।", "ਕਿਸਾਨਾਂ ਨੇ ਸਿੰਚਾਈ ਬਾਅਦ ਦੇ ਸਮੇਂ ਲਈ ਟਾਲ ਦਿੱਤੀ।")),
      chain("mandi-arrivals", S0, l("At an agricultural market on a harvest morning.", "कटाई के मौसम की सुबह एक कृषि मंडी में।", "ਫਸਲ ਕਟਾਈ ਦੇ ਮੌਸਮ ਦੀ ਸਵੇਰ ਇੱਕ ਖੇਤੀ ਮੰਡੀ ਵਿੱਚ।"), e("Heavy rain slowed tractor-trolleys on rural roads.", "तेज बारिश से ग्रामीण सड़कों पर ट्रैक्टर-ट्रॉलियां धीमी हो गईं।", "ਤੇਜ਼ ਮੀਂਹ ਕਾਰਨ ਪਿੰਡਾਂ ਦੀਆਂ ਸੜਕਾਂ ਉੱਤੇ ਟਰੈਕਟਰ-ਟਰਾਲੀਆਂ ਹੌਲੀਆਂ ਹੋ ਗਈਆਂ।"), e("Crop arrivals at the market became irregular.", "मंडी में फसल की आवक अनियमित हो गई।", "ਮੰਡੀ ਵਿੱਚ ਫਸਲ ਦੀ ਆਮਦ ਅਨਿਯਮਿਤ ਹੋ ਗਈ।"), e("Auction lots formed later than usual.", "नीलामी के लॉट सामान्य से देर से बने।", "ਨੀਲਾਮੀ ਵਾਲੇ ਲਾਟ ਆਮ ਨਾਲੋਂ ਦੇਰ ਨਾਲ ਬਣੇ।"), e("Some sales continued into the afternoon.", "कुछ बिक्री दोपहर तक चली।", "ਕੁਝ ਵਿਕਰੀ ਦੁਪਹਿਰ ਤੱਕ ਚੱਲੀ।")),
      chain("fertilizer-delivery", S0, l("For villages served by one fertilizer depot.", "एक उर्वरक डिपो से सेवा पाने वाले गांवों में।", "ਇੱਕ ਖਾਦ ਡਿਪੋ ਤੋਂ ਸੇਵਾ ਲੈਣ ਵਾਲੇ ਪਿੰਡਾਂ ਵਿੱਚ।"), e("A supply truck broke down before reaching the depot.", "डिपो पहुँचने से पहले आपूर्ति ट्रक खराब हो गया।", "ਡਿਪੋ ਪਹੁੰਚਣ ਤੋਂ ਪਹਿਲਾਂ ਸਪਲਾਈ ਟਰੱਕ ਖਰਾਬ ਹੋ ਗਿਆ।"), e("Fresh fertilizer stock reached the depot late.", "नया उर्वरक स्टॉक डिपो पर देर से पहुँचा।", "ਨਵਾਂ ਖਾਦ ਸਟਾਕ ਡਿਪੋ ਵਿੱਚ ਦੇਰ ਨਾਲ ਪਹੁੰਚਿਆ।"), e("Distribution to village outlets started late.", "गांव के विक्रय केंद्रों को वितरण देर से शुरू हुआ।", "ਪਿੰਡਾਂ ਦੇ ਵਿਕਰੀ ਕੇਂਦਰਾਂ ਨੂੰ ਵੰਡ ਦੇਰ ਨਾਲ ਸ਼ੁਰੂ ਹੋਈ।"), e("Farmers returned later to collect supplies.", "किसान सामग्री लेने के लिए बाद में लौटे।", "ਕਿਸਾਨ ਸਮੱਗਰੀ ਲੈਣ ਲਈ ਬਾਅਦ ਵਿੱਚ ਮੁੜੇ।")),
      chain("milk-chilling", S0, l("At a milk collection centre during the morning shift.", "सुबह की पाली में एक दूध संग्रह केंद्र पर।", "ਸਵੇਰ ਦੀ ਪਾਲੀ ਵਿੱਚ ਇੱਕ ਦੁੱਧ ਇਕੱਠਾ ਕਰਨ ਵਾਲੇ ਕੇਂਦਰ ਤੇ।"), e("The chilling unit lost power.", "चिलिंग यूनिट की बिजली चली गई।", "ਚਿਲਿੰਗ ਯੂਨਿਟ ਦੀ ਬਿਜਲੀ ਚਲੀ ਗਈ।"), e("Milk cooling stopped temporarily.", "दूध ठंडा करने की प्रक्रिया अस्थायी रूप से रुक गई।", "ਦੁੱਧ ਠੰਢਾ ਕਰਨ ਦੀ ਪ੍ਰਕਿਰਿਆ ਕੁਝ ਸਮੇਂ ਲਈ ਰੁਕ ਗਈ।"), e("Tankers waited before loading.", "टैंकर लोडिंग से पहले प्रतीक्षा करने लगे।", "ਟੈਂਕਰ ਲੋਡਿੰਗ ਤੋਂ ਪਹਿਲਾਂ ਉਡੀਕ ਕਰਨ ਲੱਗੇ।"), e("Dispatch to the dairy plant was delayed.", "डेयरी प्लांट के लिए भेजाई में देरी हुई।", "ਡੇਅਰੀ ਪਲਾਂਟ ਵੱਲ ਭੇਜਣ ਵਿੱਚ ਦੇਰੀ ਹੋਈ।")),
    ],
  },
  {
    id: "CAE-FAM-BANKING-SERVICE", domain: "CIVIC", topology: "DIRECT_CHAIN",
    allowedProjectionKinds: ["DIRECT_RELATIONSHIP", "INDIRECT_CAUSAL_CHAIN", "MULTI_EVENT_SEQUENCE"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      chain("atm-network", S1, l("Across several ATMs during a busy banking hour.", "व्यस्त बैंकिंग समय में कई एटीएम पर।", "ਰੁੱਝੇ ਬੈਂਕਿੰਗ ਸਮੇਂ ਦੌਰਾਨ ਕਈ ਏਟੀਐਮਾਂ ਤੇ।"), e("The bank's ATM network lost connectivity.", "बैंक के एटीएम नेटवर्क का संपर्क टूट गया।", "ਬੈਂਕ ਦੇ ਏਟੀਐਮ ਨੈੱਟਵਰਕ ਦੀ ਕਨੈਕਟਿਵਿਟੀ ਟੁੱਟ ਗਈ।"), e("Cash-withdrawal requests could not be processed.", "नकद निकासी अनुरोध संसाधित नहीं हो सके।", "ਨਕਦ ਕਢਵਾਉਣ ਵਾਲੀਆਂ ਬੇਨਤੀਆਂ ਪ੍ਰਕਿਰਿਆ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।"), e("More customers went to nearby branches.", "अधिक ग्राहक नजदीकी शाखाओं में गए।", "ਵੱਧ ਗਾਹਕ ਨੇੜਲੀਆਂ ਸ਼ਾਖਾਵਾਂ ਵਿੱਚ ਗਏ।"), e("Queues at branch cash counters grew.", "शाखा के नकद काउंटरों पर कतारें बढ़ गईं।", "ਸ਼ਾਖਾ ਦੇ ਨਕਦ ਕਾਊਂਟਰਾਂ ਤੇ ਕਤਾਰਾਂ ਵੱਧ ਗਈਆਂ।")),
      chain("cheque-clearing", S1, l("At a bank branch on a clearing day.", "क्लीयरिंग दिवस पर एक बैंक शाखा में।", "ਕਲੀਅਰਿੰਗ ਦਿਨ ਇੱਕ ਬੈਂਕ ਸ਼ਾਖਾ ਵਿੱਚ।"), e("The cheque-scanning system stopped working.", "चेक स्कैनिंग प्रणाली ने काम करना बंद कर दिया।", "ਚੈਕ ਸਕੈਨਿੰਗ ਪ੍ਰਣਾਲੀ ਨੇ ਕੰਮ ਕਰਨਾ ਬੰਦ ਕਰ ਦਿੱਤਾ।"), e("Cheque images could not be uploaded on time.", "चेक की छवियां समय पर अपलोड नहीं हो सकीं।", "ਚੈਕਾਂ ਦੀਆਂ ਤਸਵੀਰਾਂ ਸਮੇਂ ਤੇ ਅਪਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ।"), e("Some cheques missed the scheduled clearing batch.", "कुछ चेक निर्धारित क्लीयरिंग बैच में शामिल नहीं हो सके।", "ਕੁਝ ਚੈਕ ਨਿਰਧਾਰਤ ਕਲੀਅਰਿੰਗ ਬੈਚ ਵਿੱਚ ਸ਼ਾਮਲ ਨਹੀਂ ਹੋ ਸਕੇ।"), e("Customers received credit later than expected.", "ग्राहकों को राशि अपेक्षा से देर से मिली।", "ਗਾਹਕਾਂ ਨੂੰ ਰਕਮ ਉਮੀਦ ਨਾਲੋਂ ਦੇਰ ਨਾਲ ਮਿਲੀ।")),
      chain("mobile-banking", S1, l("During salary day on a mobile-banking service.", "वेतन दिवस पर मोबाइल बैंकिंग सेवा में।", "ਤਨਖਾਹ ਵਾਲੇ ਦਿਨ ਮੋਬਾਈਲ ਬੈਂਕਿੰਗ ਸੇਵਾ ਤੇ।"), e("Login requests rose sharply within a short period.", "थोड़े समय में लॉगिन अनुरोध बहुत बढ़ गए।", "ਥੋੜ੍ਹੇ ਸਮੇਂ ਵਿੱਚ ਲਾਗਇਨ ਬੇਨਤੀਆਂ ਬਹੁਤ ਵੱਧ ਗਈਆਂ।"), e("The authentication service became slow.", "प्रमाणीकरण सेवा धीमी हो गई।", "ਪ੍ਰਮਾਣਿਕਤਾ ਸੇਵਾ ਹੌਲੀ ਹੋ ਗਈ।"), e("Many users could not complete transfers quickly.", "कई उपयोगकर्ता जल्दी धन हस्तांतरण पूरा नहीं कर सके।", "ਕਈ ਵਰਤੋਂਕਾਰ ਜਲਦੀ ਪੈਸੇ ਟ੍ਰਾਂਸਫਰ ਨਹੀਂ ਕਰ ਸਕੇ।"), e("Support calls to the bank increased.", "बैंक को सहायता कॉल बढ़ गईं।", "ਬੈਂਕ ਨੂੰ ਸਹਾਇਤਾ ਕਾਲਾਂ ਵੱਧ ਗਈਆਂ।")),
      chain("cash-van", S1, l("At rural bank branches before a market day.", "बाजार दिवस से पहले ग्रामीण बैंक शाखाओं में।", "ਮੰਡੀ ਵਾਲੇ ਦਿਨ ਤੋਂ ਪਹਿਲਾਂ ਪਿੰਡਾਂ ਦੀਆਂ ਬੈਂਕ ਸ਼ਾਖਾਵਾਂ ਵਿੱਚ।"), e("A cash van was delayed by a road closure.", "सड़क बंद होने से नकद वैन देर से पहुँची।", "ਸੜਕ ਬੰਦ ਹੋਣ ਕਾਰਨ ਨਕਦ ਵੈਨ ਦੇਰ ਨਾਲ ਪਹੁੰਚੀ।"), e("Fresh cash reached the branches late.", "नई नकदी शाखाओं में देर से पहुँची।", "ਨਵੀਂ ਨਕਦੀ ਸ਼ਾਖਾਵਾਂ ਵਿੱਚ ਦੇਰ ਨਾਲ ਪਹੁੰਚੀ।"), e("Cash availability at some counters fell.", "कुछ काउंटरों पर नकदी की उपलब्धता घट गई।", "ਕੁਝ ਕਾਊਂਟਰਾਂ ਤੇ ਨਕਦੀ ਦੀ ਉਪਲਬਧਤਾ ਘੱਟ ਗਈ।"), e("Some withdrawals were postponed.", "कुछ निकासी बाद के लिए टाल दी गईं।", "ਕੁਝ ਨਕਦ ਕਢਵਾਉਣ ਬਾਅਦ ਲਈ ਟਾਲੇ ਗਏ।")),
    ],
  },
  {
    id: "CAE-FAM-HEALTH-SERVICE", domain: "CIVIC", topology: "DIRECT_CHAIN",
    allowedProjectionKinds: ["DIRECT_RELATIONSHIP", "INDIRECT_CAUSAL_CHAIN", "MULTI_EVENT_SEQUENCE"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      chain("lab-analyser", S2, l("At a district hospital laboratory in the morning.", "सुबह एक जिला अस्पताल की प्रयोगशाला में।", "ਸਵੇਰੇ ਇੱਕ ਜ਼ਿਲ੍ਹਾ ਹਸਪਤਾਲ ਦੀ ਲੈਬ ਵਿੱਚ।"), e("A blood analyser stopped working.", "रक्त जांच मशीन ने काम करना बंद कर दिया।", "ਖੂਨ ਜਾਂਚਣ ਵਾਲੀ ਮਸ਼ੀਨ ਨੇ ਕੰਮ ਕਰਨਾ ਬੰਦ ਕਰ ਦਿੱਤਾ।"), e("Routine samples had to be shifted to another analyser.", "नियमित नमूनों को दूसरी मशीन पर भेजना पड़ा।", "ਰੁਟੀਨ ਨਮੂਨਿਆਂ ਨੂੰ ਦੂਜੀ ਮਸ਼ੀਨ ਤੇ ਭੇਜਣਾ ਪਿਆ।"), e("Report processing became slower.", "रिपोर्ट तैयार होने की प्रक्रिया धीमी हो गई।", "ਰਿਪੋਰਟ ਤਿਆਰ ਕਰਨ ਦੀ ਪ੍ਰਕਿਰਿਆ ਹੌਲੀ ਹੋ ਗਈ।"), e("Some patients waited longer for reports.", "कुछ मरीजों को रिपोर्ट के लिए अधिक प्रतीक्षा करनी पड़ी।", "ਕੁਝ ਮਰੀਜ਼ਾਂ ਨੂੰ ਰਿਪੋਰਟਾਂ ਲਈ ਵੱਧ ਉਡੀਕ ਕਰਨੀ ਪਈ।")),
      chain("vaccine-refrigerator", S2, l("At a health centre during an immunisation session.", "टीकाकरण सत्र के दौरान एक स्वास्थ्य केंद्र पर।", "ਟੀਕਾਕਰਨ ਸੈਸ਼ਨ ਦੌਰਾਨ ਇੱਕ ਸਿਹਤ ਕੇਂਦਰ ਤੇ।"), e("The vaccine refrigerator developed a temperature fault.", "टीका रेफ्रिजरेटर में तापमान संबंधी खराबी आ गई।", "ਟੀਕੇ ਵਾਲੇ ਫ੍ਰਿਜ ਵਿੱਚ ਤਾਪਮਾਨ ਦੀ ਖਰਾਬੀ ਆ ਗਈ।"), e("Vaccine stock was moved to a backup unit.", "टीका स्टॉक को बैकअप यूनिट में स्थानांतरित किया गया।", "ਟੀਕਿਆਂ ਦਾ ਸਟਾਕ ਬੈਕਅੱਪ ਯੂਨਿਟ ਵਿੱਚ ਭੇਜਿਆ ਗਿਆ।"), e("The session started later than planned.", "सत्र तय समय से देर से शुरू हुआ।", "ਸੈਸ਼ਨ ਨਿਰਧਾਰਤ ਸਮੇਂ ਨਾਲੋਂ ਦੇਰ ਨਾਲ ਸ਼ੁਰੂ ਹੋਇਆ।"), e("Waiting time for beneficiaries increased.", "लाभार्थियों की प्रतीक्षा अवधि बढ़ गई।", "ਲਾਭਪਾਤਰੀਆਂ ਦੀ ਉਡੀਕ ਦਾ ਸਮਾਂ ਵੱਧ ਗਿਆ।")),
      chain("ambulance-route", S2, l("For an ambulance travelling to an emergency ward.", "आपातकालीन वार्ड की ओर जा रही एम्बुलेंस के लिए।", "ਐਮਰਜੈਂਸੀ ਵਾਰਡ ਵੱਲ ਜਾ ਰਹੀ ਐਂਬੂਲੈਂਸ ਲਈ।"), e("A major junction was blocked after an accident.", "एक दुर्घटना के बाद मुख्य चौराहा बंद हो गया।", "ਇੱਕ ਹਾਦਸੇ ਤੋਂ ਬਾਅਦ ਮੁੱਖ ਚੌਰਾਹਾ ਬੰਦ ਹੋ ਗਿਆ।"), e("The ambulance took an alternate route.", "एम्बुलेंस ने वैकल्पिक मार्ग लिया।", "ਐਂਬੂਲੈਂਸ ਨੇ ਵਿਕਲਪਿਕ ਰਸਤਾ ਲਿਆ।"), e("Travel time to the hospital increased.", "अस्पताल तक पहुँचने का समय बढ़ गया।", "ਹਸਪਤਾਲ ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ ਵੱਧ ਗਿਆ।"), e("The emergency team prepared for a later arrival.", "आपातकालीन टीम ने देर से पहुँचने के अनुसार तैयारी की।", "ਐਮਰਜੈਂਸੀ ਟੀਮ ਨੇ ਦੇਰ ਨਾਲ ਪਹੁੰਚਣ ਅਨੁਸਾਰ ਤਿਆਰੀ ਕੀਤੀ।")),
      chain("registration-server", S2, l("At a hospital registration desk during peak hours.", "व्यस्त समय में अस्पताल के पंजीकरण डेस्क पर।", "ਰੁੱਝੇ ਸਮੇਂ ਦੌਰਾਨ ਹਸਪਤਾਲ ਦੇ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਡੈਸਕ ਤੇ।"), e("The patient-registration server became unavailable.", "मरीज पंजीकरण सर्वर उपलब्ध नहीं रहा।", "ਮਰੀਜ਼ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਰਵਰ ਉਪਲਬਧ ਨਹੀਂ ਰਿਹਾ।"), e("New patient records had to be entered manually.", "नए मरीजों के रिकॉर्ड हाथ से दर्ज करने पड़े।", "ਨਵੇਂ ਮਰੀਜ਼ਾਂ ਦੇ ਰਿਕਾਰਡ ਹੱਥੋਂ ਦਰਜ ਕਰਨੇ ਪਏ।"), e("Registration at the desk slowed down.", "डेस्क पर पंजीकरण धीमा हो गया।", "ਡੈਸਕ ਤੇ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਹੌਲੀ ਹੋ ਗਈ।"), e("The waiting queue became longer.", "प्रतीक्षा कतार लंबी हो गई।", "ਉਡੀਕ ਵਾਲੀ ਕਤਾਰ ਲੰਮੀ ਹੋ ਗਈ।")),
    ],
  },
] as const satisfies readonly CaeScenarioFamilyAuthority[];
