import type { CaeScenarioFamilyAuthority } from "./types.ts";
import { CAE_SATURATION_RENDERING_CONSTRAINTS as constraints, saturationBranchVariant as branch, saturationEvent as e, saturationText as l, type SaturationScale } from "./causal-world-saturation-utils.ts";

const CITY: SaturationScale = { scope: "CITY", magnitude: "HIGH", severity: "MODERATE" };
const LOCAL: SaturationScale = { scope: "LOCAL", magnitude: "MODERATE", severity: "MODERATE" };
const SITE: SaturationScale = { scope: "SITE", magnitude: "MODERATE", severity: "LOW" };

export const CAE_001_SATURATION_WAVE4_BRANCH_FAMILIES: readonly CaeScenarioFamilyAuthority[] = Object.freeze([
  {
    id: "CAE-FAM-WEATHER-DISRUPTION-PRESSURE", domain: "WEATHER", topology: "BRANCHING_COMMON_CAUSE",
    allowedProjectionKinds: ["COMMON_OR_INDEPENDENT", "PROBABLE_EFFECT"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      branch("dense-fog", CITY, l("Across a city during a dense-fog morning.", "घने कोहरे वाली सुबह पूरे शहर में।", "ਘਣੀ ਧੁੰਦ ਵਾਲੀ ਸਵੇਰ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ।"), e("Dense fog sharply reduced visibility across the city.", "घने कोहरे से पूरे शहर में दृश्यता बहुत कम हो गई।", "ਘਣੀ ਧੁੰਦ ਨਾਲ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ ਦਿੱਖ ਬਹੁਤ ਘੱਟ ਹੋ ਗਈ।"), e("Road traffic moved more slowly than usual.", "सड़क यातायात सामान्य से धीमा हो गया।", "ਸੜਕੀ ਆਵਾਜਾਈ ਆਮ ਨਾਲੋਂ ਹੌਲੀ ਹੋ ਗਈ।"), e("Several morning flights were delayed.", "कई सुबह की उड़ानें देर से चलीं।", "ਕਈ ਸਵੇਰੇ ਦੀਆਂ ਉਡਾਣਾਂ ਦੇਰੀ ਨਾਲ ਚੱਲੀਆਂ।")),
      branch("heavy-rain", CITY, l("Across a city during several hours of heavy rain.", "कई घंटों की तेज बारिश के दौरान पूरे शहर में।", "ਕਈ ਘੰਟਿਆਂ ਦੀ ਭਾਰੀ ਵਰਖਾ ਦੌਰਾਨ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ।"), e("Heavy rain continued for several hours.", "कई घंटों तक तेज बारिश जारी रही।", "ਕਈ ਘੰਟਿਆਂ ਤੱਕ ਭਾਰੀ ਵਰਖਾ ਜਾਰੀ ਰਹੀ।"), e("Water accumulated on several low-lying roads.", "कई निचली सड़कों पर पानी भर गया।", "ਕਈ ਨੀਵੀਆਂ ਸੜਕਾਂ ਉੱਤੇ ਪਾਣੀ ਇਕੱਠਾ ਹੋ ਗਿਆ।"), e("Demand for app-based taxis increased.", "ऐप आधारित टैक्सियों की मांग बढ़ गई।", "ਐਪ-ਆਧਾਰਿਤ ਟੈਕਸੀਆਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।")),
      branch("heatwave", CITY, l("Across a city during an intense heatwave.", "तेज गर्मी की लहर के दौरान पूरे शहर में।", "ਤੀਬਰ ਗਰਮੀ ਦੀ ਲਹਿਰ ਦੌਰਾਨ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ।"), e("Daytime temperatures remained unusually high for several days.", "कई दिनों तक दिन का तापमान असामान्य रूप से ऊंचा रहा।", "ਕਈ ਦਿਨਾਂ ਤੱਕ ਦਿਨ ਦਾ ਤਾਪਮਾਨ ਅਸਧਾਰਣ ਤੌਰ ਤੇ ਉੱਚਾ ਰਿਹਾ।"), e("Electricity demand for cooling increased.", "ठंडक के लिए बिजली की मांग बढ़ गई।", "ਠੰਢਕ ਲਈ ਬਿਜਲੀ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Sales of bottled drinking water increased.", "बोतलबंद पेयजल की बिक्री बढ़ गई।", "ਬੋਤਲਬੰਦ ਪੀਣ ਵਾਲੇ ਪਾਣੀ ਦੀ ਵਿਕਰੀ ਵੱਧ ਗਈ।")),
      branch("cold-wave", CITY, l("Across a city during a sudden cold wave.", "अचानक आई शीत लहर के दौरान पूरे शहर में।", "ਅਚਾਨਕ ਆਈ ਠੰਢ ਦੀ ਲਹਿਰ ਦੌਰਾਨ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ।"), e("A sudden cold wave lowered temperatures sharply.", "अचानक आई शीत लहर से तापमान तेजी से गिर गया।", "ਅਚਾਨਕ ਆਈ ਠੰਢ ਦੀ ਲਹਿਰ ਨਾਲ ਤਾਪਮਾਨ ਤੇਜ਼ੀ ਨਾਲ ਘਟ ਗਿਆ।"), e("Demand for room heaters increased.", "रूम हीटर की मांग बढ़ गई।", "ਕਮਰੇ ਦੇ ਹੀਟਰਾਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Morning attendance at outdoor markets fell.", "बाहरी बाजारों में सुबह की उपस्थिति घट गई।", "ਖੁੱਲ੍ਹੇ ਬਾਜ਼ਾਰਾਂ ਵਿੱਚ ਸਵੇਰ ਦੀ ਹਾਜ਼ਰੀ ਘੱਟ ਗਈ।")),
    ],
  },
  {
    id: "CAE-FAM-COMMUTER-DEMAND-PRESSURE", domain: "TRANSPORT", topology: "BRANCHING_COMMON_CAUSE",
    allowedProjectionKinds: ["COMMON_OR_INDEPENDENT", "PROBABLE_EFFECT"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      branch("metro-closure", CITY, l("Near a busy corridor after a metro section closed temporarily.", "एक व्यस्त मार्ग पर मेट्रो खंड अस्थायी रूप से बंद होने के बाद।", "ਇੱਕ ਰੁਸ਼ ਵਾਲੇ ਰਸਤੇ ਉੱਤੇ ਮੈਟਰੋ ਹਿੱਸਾ ਅਸਥਾਈ ਤੌਰ ਤੇ ਬੰਦ ਹੋਣ ਤੋਂ ਬਾਅਦ।"), e("A metro section was closed temporarily for an urgent inspection.", "तत्काल निरीक्षण के लिए मेट्रो का एक खंड अस्थायी रूप से बंद किया गया।", "ਤੁਰੰਤ ਜਾਂਚ ਲਈ ਮੈਟਰੋ ਦਾ ਇੱਕ ਹਿੱਸਾ ਅਸਥਾਈ ਤੌਰ ਤੇ ਬੰਦ ਕੀਤਾ ਗਿਆ।"), e("Passenger demand on nearby bus routes increased.", "पास के बस मार्गों पर यात्रियों की मांग बढ़ गई।", "ਨੇੜਲੇ ਬੱਸ ਰੂਟਾਂ ਉੱਤੇ ਯਾਤਰੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Traffic on the parallel road corridor increased.", "समानांतर सड़क मार्ग पर यातायात बढ़ गया।", "ਸਮਾਂਤਰ ਸੜਕੀ ਰਸਤੇ ਉੱਤੇ ਆਵਾਜਾਈ ਵੱਧ ਗਈ।")),
      branch("rail-cancellation", CITY, l("Around a major station after several commuter trains were cancelled.", "एक बड़े स्टेशन के आसपास कई लोकल ट्रेनें रद्द होने के बाद।", "ਇੱਕ ਵੱਡੇ ਸਟੇਸ਼ਨ ਦੇ ਆਲੇ-ਦੁਆਲੇ ਕਈ ਯਾਤਰੀ ਰੇਲਾਂ ਰੱਦ ਹੋਣ ਤੋਂ ਬਾਅਦ।"), e("Several commuter trains were cancelled at short notice.", "कई लोकल ट्रेनें कम समय की सूचना पर रद्द कर दी गईं।", "ਕਈ ਯਾਤਰੀ ਰੇਲਾਂ ਘੱਟ ਸੂਚਨਾ ਉੱਤੇ ਰੱਦ ਕਰ ਦਿੱਤੀਆਂ ਗਈਆਂ।"), e("Queues at intercity bus counters increased.", "इंटरसिटी बस काउंटरों पर कतारें बढ़ गईं।", "ਇੰਟਰਸਿਟੀ ਬੱਸ ਕਾਊਂਟਰਾਂ ਉੱਤੇ ਕਤਾਰਾਂ ਵੱਧ ਗਈਆਂ।"), e("Demand for taxis outside the station increased.", "स्टेशन के बाहर टैक्सियों की मांग बढ़ गई।", "ਸਟੇਸ਼ਨ ਦੇ ਬਾਹਰ ਟੈਕਸੀਆਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।")),
      branch("bridge-restriction", CITY, l("Across a river corridor after traffic restrictions were imposed on a bridge.", "एक नदी मार्ग पर पुल पर यातायात प्रतिबंध लगाए जाने के बाद।", "ਇੱਕ ਦਰਿਆਈ ਰਸਤੇ ਉੱਤੇ ਪੁਲ ਉੱਤੇ ਆਵਾਜਾਈ ਪਾਬੰਦੀਆਂ ਲੱਗਣ ਤੋਂ ਬਾਅਦ।"), e("Heavy vehicles were temporarily restricted from using a major bridge.", "भारी वाहनों के लिए एक बड़े पुल का उपयोग अस्थायी रूप से प्रतिबंधित किया गया।", "ਭਾਰੀ ਵਾਹਨਾਂ ਲਈ ਇੱਕ ਵੱਡੇ ਪੁਲ ਦੀ ਵਰਤੋਂ ਅਸਥਾਈ ਤੌਰ ਤੇ ਰੋਕੀ ਗਈ।"), e("Truck traffic on the alternate bridge increased.", "वैकल्पिक पुल पर ट्रक यातायात बढ़ गया।", "ਵਿਕਲਪਕ ਪੁਲ ਉੱਤੇ ਟਰੱਕ ਆਵਾਜਾਈ ਵੱਧ ਗਈ।"), e("Travel time on the diversion route increased.", "वैकल्पिक मार्ग पर यात्रा समय बढ़ गया।", "ਬਦਲਵੇਂ ਰਸਤੇ ਉੱਤੇ ਯਾਤਰਾ ਸਮਾਂ ਵੱਧ ਗਿਆ।")),
      branch("bus-strike", CITY, l("Across a city during a one-day bus strike.", "एक दिन की बस हड़ताल के दौरान पूरे शहर में।", "ਇੱਕ ਦਿਨ ਦੀ ਬੱਸ ਹੜਤਾਲ ਦੌਰਾਨ ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ।"), e("A one-day bus strike reduced the number of buses in service.", "एक दिन की बस हड़ताल से सेवा में चल रही बसों की संख्या घट गई।", "ਇੱਕ ਦਿਨ ਦੀ ਬੱਸ ਹੜਤਾਲ ਨਾਲ ਸੇਵਾ ਵਿੱਚ ਚੱਲ ਰਹੀਆਂ ਬੱਸਾਂ ਦੀ ਗਿਣਤੀ ਘੱਟ ਗਈ।"), e("Demand for shared auto-rickshaws increased.", "साझा ऑटो-रिक्शा की मांग बढ़ गई।", "ਸਾਂਝੇ ਆਟੋ-ਰਿਕਸ਼ਿਆਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Passenger loads on suburban trains increased.", "उपनगरीय ट्रेनों में यात्रियों की संख्या बढ़ गई।", "ਉਪਨਗਰੀ ਰੇਲਾਂ ਵਿੱਚ ਯਾਤਰੀ ਭੀੜ ਵੱਧ ਗਈ।")),
    ],
  },
  {
    id: "CAE-FAM-CAMPUS-EVENT-PRESSURE", domain: "EDUCATION", topology: "BRANCHING_COMMON_CAUSE",
    allowedProjectionKinds: ["COMMON_OR_INDEPENDENT", "PROBABLE_EFFECT"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      branch("convocation", SITE, l("At a university during convocation day.", "विश्वविद्यालय में दीक्षांत समारोह के दिन।", "ਯੂਨੀਵਰਸਿਟੀ ਵਿੱਚ ਡਿਗਰੀ ਸਮਾਰੋਹ ਦੇ ਦਿਨ।"), e("The university held its annual convocation.", "विश्वविद्यालय ने अपना वार्षिक दीक्षांत समारोह आयोजित किया।", "ਯੂਨੀਵਰਸਿਟੀ ਨੇ ਆਪਣਾ ਸਾਲਾਨਾ ਡਿਗਰੀ ਸਮਾਰੋਹ ਕਰਵਾਇਆ।"), e("Visitor traffic at the main gate increased.", "मुख्य द्वार पर आगंतुक यातायात बढ़ गया।", "ਮੁੱਖ ਗੇਟ ਉੱਤੇ ਆਗੰਤੁਕ ਆਵਾਜਾਈ ਵੱਧ ਗਈ।"), e("Demand for campus parking increased.", "कैंपस पार्किंग की मांग बढ़ गई।", "ਕੈਂਪਸ ਪਾਰਕਿੰਗ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।")),
      branch("entrance-test", SITE, l("At a college hosting a large entrance test.", "एक बड़े प्रवेश परीक्षा केंद्र वाले कॉलेज में।", "ਇੱਕ ਵੱਡੀ ਦਾਖਲਾ ਪ੍ਰੀਖਿਆ ਕਰਵਾ ਰਹੇ ਕਾਲਜ ਵਿੱਚ।"), e("A large entrance examination was held on campus.", "कैंपस में एक बड़ी प्रवेश परीक्षा आयोजित हुई।", "ਕੈਂਪਸ ਵਿੱਚ ਇੱਕ ਵੱਡੀ ਦਾਖਲਾ ਪ੍ਰੀਖਿਆ ਹੋਈ।"), e("Use of photocopy shops near the gate increased.", "मुख्य द्वार के पास फोटोकॉपी दुकानों का उपयोग बढ़ गया।", "ਮੁੱਖ ਗੇਟ ਨੇੜੇ ਫੋਟੋਕਾਪੀ ਦੁਕਾਨਾਂ ਦੀ ਵਰਤੋਂ ਵੱਧ ਗਈ।"), e("Passenger demand at the nearby bus stop increased.", "पास के बस स्टॉप पर यात्रियों की मांग बढ़ गई।", "ਨੇੜਲੇ ਬੱਸ ਸਟਾਪ ਉੱਤੇ ਯਾਤਰੀ ਮੰਗ ਵੱਧ ਗਈ।")),
      branch("sports-meet", SITE, l("At a university during an inter-college sports meet.", "विश्वविद्यालय में अंतर-महाविद्यालय खेल प्रतियोगिता के दौरान।", "ਯੂਨੀਵਰਸਿਟੀ ਵਿੱਚ ਅੰਤਰ-ਕਾਲਜ ਖੇਡ ਮੇਲੇ ਦੌਰਾਨ।"), e("An inter-college sports meet brought many teams to campus.", "अंतर-महाविद्यालय खेल प्रतियोगिता से कई टीमें कैंपस में आईं।", "ਅੰਤਰ-ਕਾਲਜ ਖੇਡ ਮੇਲੇ ਨਾਲ ਕਈ ਟੀਮਾਂ ਕੈਂਪਸ ਵਿੱਚ ਆਈਆਂ।"), e("Demand at the campus cafeteria increased.", "कैंपस कैफेटेरिया में मांग बढ़ गई।", "ਕੈਂਪਸ ਕੈਫੇਟੇਰੀਆ ਵਿੱਚ ਮੰਗ ਵੱਧ ਗਈ।"), e("Use of the campus medical desk increased.", "कैंपस मेडिकल डेस्क का उपयोग बढ़ गया।", "ਕੈਂਪਸ ਮੈਡੀਕਲ ਡੈਸਕ ਦੀ ਵਰਤੋਂ ਵੱਧ ਗਈ।")),
      branch("admission-counselling", SITE, l("At a college during the final admission-counselling day.", "कॉलेज में प्रवेश परामर्श के अंतिम दिन।", "ਕਾਲਜ ਵਿੱਚ ਦਾਖਲਾ ਕਾਊਂਸਲਿੰਗ ਦੇ ਆਖਰੀ ਦਿਨ।"), e("The final admission-counselling round drew many applicants to campus.", "अंतिम प्रवेश परामर्श दौर से कई आवेदक कैंपस आए।", "ਆਖਰੀ ਦਾਖਲਾ ਕਾਊਂਸਲਿੰਗ ਦੌਰ ਨਾਲ ਕਈ ਅਰਜ਼ੀਦਾਰ ਕੈਂਪਸ ਆਏ।"), e("Waiting time at document-verification counters increased.", "दस्तावेज सत्यापन काउंटरों पर प्रतीक्षा समय बढ़ गया।", "ਦਸਤਾਵੇਜ਼ ਜਾਂਚ ਕਾਊਂਟਰਾਂ ਉੱਤੇ ਉਡੀਕ ਸਮਾਂ ਵੱਧ ਗਿਆ।"), e("Demand for printing services near the campus increased.", "कैंपस के पास प्रिंटिंग सेवाओं की मांग बढ़ गई।", "ਕੈਂਪਸ ਨੇੜੇ ਪ੍ਰਿੰਟਿੰਗ ਸੇਵਾਵਾਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।")),
    ],
  },
  {
    id: "CAE-FAM-UTILITY-OUTAGE-PRESSURE", domain: "UTILITIES", topology: "BRANCHING_COMMON_CAUSE",
    allowedProjectionKinds: ["COMMON_OR_INDEPENDENT", "PROBABLE_EFFECT"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      branch("power-outage", LOCAL, l("In a neighbourhood during an extended electricity outage.", "एक मोहल्ले में लंबे बिजली कटौती के दौरान।", "ਇੱਕ ਮੁਹੱਲੇ ਵਿੱਚ ਲੰਬੇ ਬਿਜਲੀ ਬੰਦ ਦੌਰਾਨ।"), e("An extended electricity outage affected the neighbourhood.", "लंबी बिजली कटौती ने मोहल्ले को प्रभावित किया।", "ਲੰਬੇ ਬਿਜਲੀ ਬੰਦ ਨੇ ਮੁਹੱਲੇ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕੀਤਾ।"), e("Use of backup generators increased.", "बैकअप जनरेटर का उपयोग बढ़ गया।", "ਬੈਕਅੱਪ ਜਨਰੇਟਰਾਂ ਦੀ ਵਰਤੋਂ ਵੱਧ ਗਈ।"), e("Calls to the electricity complaint centre increased.", "बिजली शिकायत केंद्र पर कॉल बढ़ गईं।", "ਬਿਜਲੀ ਸ਼ਿਕਾਇਤ ਕੇਂਦਰ ਨੂੰ ਕਾਲਾਂ ਵੱਧ ਗਈਆਂ।")),
      branch("water-cut", LOCAL, l("In a neighbourhood during an unscheduled water-supply cut.", "एक मोहल्ले में बिना सूचना पानी की आपूर्ति बंद होने के दौरान।", "ਇੱਕ ਮੁਹੱਲੇ ਵਿੱਚ ਬਿਨਾਂ ਸੂਚਨਾ ਪਾਣੀ ਸਪਲਾਈ ਬੰਦ ਹੋਣ ਦੌਰਾਨ।"), e("An unscheduled water-supply cut affected the area.", "बिना सूचना पानी की आपूर्ति बंद होने से क्षेत्र प्रभावित हुआ।", "ਬਿਨਾਂ ਸੂਚਨਾ ਪਾਣੀ ਸਪਲਾਈ ਬੰਦ ਹੋਣ ਨਾਲ ਇਲਾਕਾ ਪ੍ਰਭਾਵਿਤ ਹੋਇਆ।"), e("Demand for private water tankers increased.", "निजी पानी टैंकरों की मांग बढ़ गई।", "ਨਿੱਜੀ ਪਾਣੀ ਟੈਂਕਰਾਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Complaints to the municipal helpline increased.", "नगरपालिका हेल्पलाइन पर शिकायतें बढ़ गईं।", "ਨਗਰ ਨਿਗਮ ਹੈਲਪਲਾਈਨ ਉੱਤੇ ਸ਼ਿਕਾਇਤਾਂ ਵੱਧ ਗਈਆਂ।")),
      branch("gas-supply", LOCAL, l("In a residential area during a temporary piped-gas interruption.", "एक आवासीय क्षेत्र में पाइप गैस की अस्थायी रुकावट के दौरान।", "ਇੱਕ ਰਿਹਾਇਸ਼ੀ ਇਲਾਕੇ ਵਿੱਚ ਪਾਈਪ ਗੈਸ ਦੀ ਅਸਥਾਈ ਰੁਕਾਵਟ ਦੌਰਾਨ।"), e("Piped-gas supply was temporarily interrupted.", "पाइप गैस की आपूर्ति अस्थायी रूप से बाधित हुई।", "ਪਾਈਪ ਗੈਸ ਸਪਲਾਈ ਅਸਥਾਈ ਤੌਰ ਤੇ ਰੁਕ ਗਈ।"), e("Demand for LPG cylinders increased.", "एलपीजी सिलेंडरों की मांग बढ़ गई।", "ਐਲਪੀਜੀ ਸਿਲੰਡਰਾਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।"), e("Calls to the gas distributor increased.", "गैस वितरक को कॉल बढ़ गईं।", "ਗੈਸ ਡਿਸਟ੍ਰਿਬਿਊਟਰ ਨੂੰ ਕਾਲਾਂ ਵੱਧ ਗਈਆਂ।")),
      branch("broadband-outage", LOCAL, l("In a residential area during a broadband outage.", "एक आवासीय क्षेत्र में ब्रॉडबैंड बंद होने के दौरान।", "ਇੱਕ ਰਿਹਾਇਸ਼ੀ ਇਲਾਕੇ ਵਿੱਚ ਬ੍ਰਾਡਬੈਂਡ ਬੰਦ ਹੋਣ ਦੌਰਾਨ।"), e("A broadband outage affected many local connections.", "ब्रॉडबैंड बंद होने से कई स्थानीय कनेक्शन प्रभावित हुए।", "ਬ੍ਰਾਡਬੈਂਡ ਬੰਦ ਹੋਣ ਨਾਲ ਕਈ ਸਥਾਨਕ ਕਨੈਕਸ਼ਨ ਪ੍ਰਭਾਵਿਤ ਹੋਏ।"), e("Mobile-data usage increased in the area.", "क्षेत्र में मोबाइल डेटा का उपयोग बढ़ गया।", "ਇਲਾਕੇ ਵਿੱਚ ਮੋਬਾਈਲ ਡਾਟਾ ਦੀ ਵਰਤੋਂ ਵੱਧ ਗਈ।"), e("Support calls to the internet provider increased.", "इंटरनेट प्रदाता को सहायता कॉल बढ़ गईं।", "ਇੰਟਰਨੈੱਟ ਪ੍ਰਦਾਤਾ ਨੂੰ ਸਹਾਇਤਾ ਕਾਲਾਂ ਵੱਧ ਗਈਆਂ।")),
    ],
  },
  {
    id: "CAE-FAM-CIVIC-DEADLINE-PRESSURE", domain: "CIVIC", topology: "BRANCHING_COMMON_CAUSE",
    allowedProjectionKinds: ["COMMON_OR_INDEPENDENT", "PROBABLE_EFFECT"], allowedQuestionProfiles: ["FOUR_WAY", "FIVE_WAY"], renderingConstraints: constraints,
    variants: [
      branch("property-tax", LOCAL, l("At a municipal office near the property-tax deadline.", "संपत्ति कर की अंतिम तिथि के पास नगरपालिका कार्यालय में।", "ਜਾਇਦਾਦ ਕਰ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਨੇੜੇ ਨਗਰ ਨਿਗਮ ਦਫ਼ਤਰ ਵਿੱਚ।"), e("The property-tax payment deadline was approaching.", "संपत्ति कर भुगतान की अंतिम तिथि नजदीक थी।", "ਜਾਇਦਾਦ ਕਰ ਭੁਗਤਾਨ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਨੇੜੇ ਸੀ।"), e("Footfall at municipal payment counters increased.", "नगरपालिका भुगतान काउंटरों पर भीड़ बढ़ गई।", "ਨਗਰ ਨਿਗਮ ਭੁਗਤਾਨ ਕਾਊਂਟਰਾਂ ਉੱਤੇ ਭੀੜ ਵੱਧ ਗਈ।"), e("Online property-tax transactions increased.", "ऑनलाइन संपत्ति कर लेनदेन बढ़ गए।", "ਆਨਲਾਈਨ ਜਾਇਦਾਦ ਕਰ ਲੈਣ-ਦੇਣ ਵੱਧ ਗਏ।")),
      branch("licence-renewal", LOCAL, l("At a transport office near a licence-renewal deadline.", "लाइसेंस नवीनीकरण की अंतिम तिथि के पास परिवहन कार्यालय में।", "ਲਾਇਸੈਂਸ ਨਵੀਨੀਕਰਨ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਨੇੜੇ ਟਰਾਂਸਪੋਰਟ ਦਫ਼ਤਰ ਵਿੱਚ।"), e("A licence-renewal deadline was approaching for many applicants.", "कई आवेदकों के लिए लाइसेंस नवीनीकरण की अंतिम तिथि नजदीक थी।", "ਕਈ ਅਰਜ਼ੀਦਾਰਾਂ ਲਈ ਲਾਇਸੈਂਸ ਨਵੀਨੀਕਰਨ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਨੇੜੇ ਸੀ।"), e("Queues at renewal counters increased.", "नवीनीकरण काउंटरों पर कतारें बढ़ गईं।", "ਨਵੀਨੀਕਰਨ ਕਾਊਂਟਰਾਂ ਉੱਤੇ ਕਤਾਰਾਂ ਵੱਧ ਗਈਆਂ।"), e("Use of the online renewal portal increased.", "ऑनलाइन नवीनीकरण पोर्टल का उपयोग बढ़ गया।", "ਆਨਲਾਈਨ ਨਵੀਨੀਕਰਨ ਪੋਰਟਲ ਦੀ ਵਰਤੋਂ ਵੱਧ ਗਈ।")),
      branch("certificate-window", LOCAL, l("At a district office before a scholarship-document deadline.", "छात्रवृत्ति दस्तावेज जमा करने की अंतिम तिथि से पहले जिला कार्यालय में।", "ਵਜ਼ੀਫ਼ਾ ਦਸਤਾਵੇਜ਼ ਜਮ੍ਹਾਂ ਕਰਨ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਤੋਂ ਪਹਿਲਾਂ ਜ਼ਿਲ੍ਹਾ ਦਫ਼ਤਰ ਵਿੱਚ।"), e("A scholarship-document deadline was approaching.", "छात्रवृत्ति दस्तावेज जमा करने की अंतिम तिथि नजदीक थी।", "ਵਜ਼ੀਫ਼ਾ ਦਸਤਾਵੇਜ਼ ਜਮ੍ਹਾਂ ਕਰਨ ਦੀ ਆਖਰੀ ਤਾਰੀਖ ਨੇੜੇ ਸੀ।"), e("Applications for income certificates increased.", "आय प्रमाणपत्र के लिए आवेदन बढ़ गए।", "ਆਮਦਨ ਸਰਟੀਫਿਕੇਟ ਲਈ ਅਰਜ਼ੀਆਂ ਵੱਧ ਗਈਆਂ।"), e("Demand at document-attestation counters increased.", "दस्तावेज सत्यापन काउंटरों पर मांग बढ़ गई।", "ਦਸਤਾਵੇਜ਼ ਤਸਦੀਕ ਕਾਊਂਟਰਾਂ ਉੱਤੇ ਮੰਗ ਵੱਧ ਗਈ।")),
      branch("building-permit", LOCAL, l("At a civic office before a new permit-fee schedule took effect.", "नई परमिट शुल्क व्यवस्था लागू होने से पहले नागरिक कार्यालय में।", "ਨਵੀਂ ਪਰਮਿਟ ਫੀਸ ਲਾਗੂ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਨਾਗਰਿਕ ਦਫ਼ਤਰ ਵਿੱਚ।"), e("A higher building-permit fee was due to take effect the following week.", "अगले सप्ताह अधिक भवन परमिट शुल्क लागू होना था।", "ਅਗਲੇ ਹਫ਼ਤੇ ਵੱਧ ਇਮਾਰਤ ਪਰਮਿਟ ਫੀਸ ਲਾਗੂ ਹੋਣੀ ਸੀ।"), e("Building-permit applications increased before the change.", "बदलाव से पहले भवन परमिट आवेदन बढ़ गए।", "ਬਦਲਾਅ ਤੋਂ ਪਹਿਲਾਂ ਇਮਾਰਤ ਪਰਮਿਟ ਅਰਜ਼ੀਆਂ ਵੱਧ ਗਈਆਂ।"), e("Demand for plan-verification appointments increased.", "नक्शा सत्यापन अपॉइंटमेंट की मांग बढ़ गई।", "ਨਕਸ਼ਾ ਜਾਂਚ ਅਪਾਇੰਟਮੈਂਟਾਂ ਦੀ ਮੰਗ ਵੱਧ ਗਈ।")),
    ],
  },
]);
