import { CAE_001_MANIFEST } from "./chapter-manifest.ts";

export const CAE_001_CURRENT_QL_ALLOCATION_STATUS =
  CAE_001_MANIFEST.qlDiscovery.status;

export const CAE_001_HISTORICAL_SOURCE_QL_ALLOCATION_STATUS =
  "PROVISIONAL_PENDING_SOURCE_SATURATION" as const;

export const CAE_001_POST_CLOSURE_MAPPING_PROOF_AUTHORITY =
  "CAE_001_FINAL_GRAPH_TO_QUESTION_STUDIO_MAPPING_PROOF_2026_10_04" as const;
