import type { KnowledgeV1Difficulty } from "../../types";
import { ENV_CP017_FACT_BY_ID_V1 } from "./env-cp017-facts";
import type { EnvCp017ReviewQuestion } from "./env-cp017-review-types";

type Seed = {
  qlId: string;
  qlName: string;
  difficulty: KnowledgeV1Difficulty;
  stem: string;
  correct: string;
  distractors: readonly [string, string, string];
  explanation: string;
  sourceFactIds: readonly string[];
};

const S: readonly Seed[] = Object.freeze([
  { qlId:"ENV-017-QL-001", qlName:"Ramsar Convention", difficulty:"Easy", stem:"The Ramsar Convention is mainly concerned with:", correct:"Wetlands", distractors:["Migratory species","Hazardous wastes","Mercury pollution"], explanation:"The Convention on Wetlands provides the international framework for conservation and wise use of wetlands and their resources.", sourceFactIds:["env-cp017-ramsar-purpose"] },
  { qlId:"ENV-017-QL-001", qlName:"Ramsar Convention", difficulty:"Easy", stem:"The Ramsar Convention was adopted in 1971 in:", correct:"Iran", distractors:["Japan","Switzerland","Germany"], explanation:"The treaty was adopted in the Iranian city of Ramsar in 1971, which is why it is commonly called the Ramsar Convention.", sourceFactIds:["env-cp017-ramsar-year-place"] },
  { qlId:"ENV-017-QL-001", qlName:"Ramsar Convention", difficulty:"Medium", stem:"Wetlands of International Importance are placed on the:", correct:"Ramsar List", distractors:["CITES Appendices","CMS Appendices","Montreal Schedule"], explanation:"Parties designate suitable wetlands for the List of Wetlands of International Importance, commonly known as the Ramsar List.", sourceFactIds:["env-cp017-ramsar-list"] },
  { qlId:"ENV-017-QL-001", qlName:"Ramsar Convention", difficulty:"Hard", stem:"Which phrase best describes the Ramsar approach?", correct:"Conservation and wise use of wetlands", distractors:["Ban on all wildlife trade","Control of hazardous-waste exports only","Binding carbon targets for developed countries"], explanation:"Ramsar is built around conserving wetlands while promoting their wise use, not around wildlife trade, waste transport or emission targets.", sourceFactIds:["env-cp017-ramsar-purpose"] },

  { qlId:"ENV-017-QL-002", qlName:"CITES", difficulty:"Easy", stem:"CITES mainly regulates:", correct:"International trade in wild animals and plants", distractors:["Transboundary hazardous waste","Wetland management","Greenhouse-gas targets"], explanation:"CITES regulates international trade in specimens of wild fauna and flora so that trade does not threaten species survival.", sourceFactIds:["env-cp017-cites-purpose"] },
  { qlId:"ENV-017-QL-002", qlName:"CITES", difficulty:"Easy", stem:"CITES was adopted in 1973 in:", correct:"Washington, D.C.", distractors:["Bonn","Ramsar","Kyoto"], explanation:"CITES was adopted in Washington, D.C., in 1973 and is therefore also associated with the name Washington Convention.", sourceFactIds:["env-cp017-cites-year-place"] },
  { qlId:"ENV-017-QL-002", qlName:"CITES", difficulty:"Medium", stem:"CITES classifies listed species mainly through:", correct:"Three Appendices", distractors:["Two Schedules","Five Protocols","One global red list"], explanation:"CITES uses three Appendices to apply different levels and forms of control to international trade in listed species.", sourceFactIds:["env-cp017-cites-appendices"] },
  { qlId:"ENV-017-QL-002", qlName:"CITES", difficulty:"Hard", stem:"Which statement best distinguishes CITES from CMS?", correct:"CITES focuses on trade; CMS focuses on migratory species", distractors:["CITES covers wetlands; CMS covers ozone","CITES covers mercury; CMS covers waste","Both have exactly the same purpose"], explanation:"CITES is centred on international wildlife trade, while CMS provides a framework for conserving migratory wild animals across their ranges.", sourceFactIds:["env-cp017-cites-purpose","env-cp017-cms-purpose"] },

  { qlId:"ENV-017-QL-003", qlName:"CMS / Bonn Convention", difficulty:"Easy", stem:"The Bonn Convention is another name for the:", correct:"Convention on Migratory Species", distractors:["Convention on Biological Diversity","Ramsar Convention","Basel Convention"], explanation:"CMS is the Convention on Migratory Species and is also called the Bonn Convention because it was negotiated in Bonn.", sourceFactIds:["env-cp017-cms-bonn"] },
  { qlId:"ENV-017-QL-003", qlName:"CMS / Bonn Convention", difficulty:"Easy", stem:"CMS mainly deals with the conservation of:", correct:"Migratory wild animals", distractors:["Wetlands only","Persistent organic pollutants","Hazardous wastes"], explanation:"CMS provides an international framework for conserving migratory species of wild animals that move across national boundaries.", sourceFactIds:["env-cp017-cms-purpose"] },
  { qlId:"ENV-017-QL-003", qlName:"CMS / Bonn Convention", difficulty:"Medium", stem:"CMS was negotiated in Bonn in:", correct:"1979", distractors:["1971","1987","1992"], explanation:"The Convention on Migratory Species was negotiated in Bonn in 1979 and later entered into force in 1983.", sourceFactIds:["env-cp017-cms-bonn"] },
  { qlId:"ENV-017-QL-003", qlName:"CMS / Bonn Convention", difficulty:"Hard", stem:"Under CMS, endangered migratory species are listed mainly in:", correct:"Appendix I", distractors:["Appendix III","Ramsar List","Annex B of Kyoto"], explanation:"CMS Appendix I covers endangered migratory species, while Appendix II covers species needing or benefiting from international agreements.", sourceFactIds:["env-cp017-cms-appendices"] },

  { qlId:"ENV-017-QL-004", qlName:"Convention on Biological Diversity", difficulty:"Easy", stem:"The Convention on Biological Diversity was opened for signature at the:", correct:"1992 Rio Earth Summit", distractors:["1972 Stockholm Conference","1997 Kyoto Conference","2015 Paris Conference"], explanation:"CBD was opened for signature at the 1992 Rio Earth Summit and became a central global biodiversity agreement.", sourceFactIds:["env-cp017-cbd-year"] },
  { qlId:"ENV-017-QL-004", qlName:"Convention on Biological Diversity", difficulty:"Easy", stem:"Which is an objective of the CBD?", correct:"Conservation of biological diversity", distractors:["Control of ozone-depleting substances","Regulation of hazardous-waste transport","Reduction of mercury use only"], explanation:"Conservation of biological diversity is one of CBD's three central objectives, along with sustainable use and benefit sharing.", sourceFactIds:["env-cp017-cbd-objectives"] },
  { qlId:"ENV-017-QL-004", qlName:"Convention on Biological Diversity", difficulty:"Medium", stem:"Which concept is directly linked with the CBD?", correct:"Fair and equitable benefit sharing", distractors:["Wetland listing only","Zoo recognition","Hazardous-waste export permits"], explanation:"CBD links biodiversity conservation and sustainable use with fair and equitable sharing of benefits arising from genetic resources.", sourceFactIds:["env-cp017-cbd-objectives"] },
  { qlId:"ENV-017-QL-004", qlName:"Convention on Biological Diversity", difficulty:"Hard", stem:"Which set gives the three core CBD objectives?", correct:"Conservation, sustainable use, benefit sharing", distractors:["Trade control, wetland listing, waste disposal","Ozone protection, mercury control, forest mapping","Emission targets, zoo standards, wildlife policing"], explanation:"CBD's three objectives are biodiversity conservation, sustainable use of its components, and fair and equitable benefit sharing.", sourceFactIds:["env-cp017-cbd-objectives"] },

  { qlId:"ENV-017-QL-005", qlName:"UNFCCC", difficulty:"Easy", stem:"UNFCCC is the main international framework convention on:", correct:"Climate change", distractors:["Wetlands","Wildlife trade","Hazardous waste"], explanation:"UNFCCC provides the international framework for cooperation on climate change and greenhouse-gas emissions.", sourceFactIds:["env-cp017-unfccc-climate"] },
  { qlId:"ENV-017-QL-005", qlName:"UNFCCC", difficulty:"Easy", stem:"UNFCCC was adopted in:", correct:"1992", distractors:["1971","1987","2001"], explanation:"The UN Framework Convention on Climate Change was adopted in 1992 and entered into force in 1994.", sourceFactIds:["env-cp017-unfccc-year"] },
  { qlId:"ENV-017-QL-005", qlName:"UNFCCC", difficulty:"Medium", stem:"Which two agreements were developed under the UNFCCC framework?", correct:"Kyoto Protocol and Paris Agreement", distractors:["Ramsar and CITES","Basel and Stockholm","Vienna and Montreal"], explanation:"The Kyoto Protocol and Paris Agreement are major climate agreements developed within the broader UNFCCC framework.", sourceFactIds:["env-cp017-unfccc-framework"] },
  { qlId:"ENV-017-QL-005", qlName:"UNFCCC", difficulty:"Hard", stem:"Which relationship is correct?", correct:"UNFCCC is the framework; Kyoto and Paris build on it", distractors:["Paris created CITES","Kyoto created Ramsar","Montreal created CBD"], explanation:"UNFCCC is the parent climate framework, while the Kyoto Protocol and Paris Agreement add later treaty mechanisms under that framework.", sourceFactIds:["env-cp017-unfccc-framework"] },

  { qlId:"ENV-017-QL-006", qlName:"Kyoto Protocol", difficulty:"Easy", stem:"The Kyoto Protocol was adopted in:", correct:"1997", distractors:["1979","1989","2015"], explanation:"The Kyoto Protocol was adopted in Kyoto, Japan, in 1997 and entered into force in 2005.", sourceFactIds:["env-cp017-kyoto-year"] },
  { qlId:"ENV-017-QL-006", qlName:"Kyoto Protocol", difficulty:"Easy", stem:"The Kyoto Protocol is linked mainly with:", correct:"Greenhouse-gas emission commitments", distractors:["Wetland designation","Wildlife trade permits","Mercury poisoning"], explanation:"Kyoto operationalized the UNFCCC by setting agreed greenhouse-gas limitation and reduction commitments for specified industrialized parties.", sourceFactIds:["env-cp017-kyoto-role"] },
  { qlId:"ENV-017-QL-006", qlName:"Kyoto Protocol", difficulty:"Medium", stem:"Kyoto's binding emission targets mainly applied to:", correct:"Industrialized countries and economies in transition", distractors:["Only least developed countries","Only island states","Every country with identical targets"], explanation:"Kyoto used differentiated commitments, with binding targets focused on industrialized countries and economies in transition.", sourceFactIds:["env-cp017-kyoto-role"] },
  { qlId:"ENV-017-QL-006", qlName:"Kyoto Protocol", difficulty:"Hard", stem:"Which best distinguishes Kyoto from Paris?", correct:"Kyoto used specified developed-country targets; Paris uses NDCs", distractors:["Kyoto regulates wetlands; Paris regulates wildlife trade","Kyoto controls mercury; Paris controls hazardous waste","Both use identical legal mechanisms"], explanation:"Kyoto centred on binding targets for specified developed parties, while Paris uses nationally determined contributions submitted by parties.", sourceFactIds:["env-cp017-kyoto-distinction","env-cp017-paris-ndc"] },

  { qlId:"ENV-017-QL-007", qlName:"Paris Agreement", difficulty:"Easy", stem:"The Paris Agreement was adopted at COP21 in:", correct:"2015", distractors:["1992","1997","2005"], explanation:"The Paris Agreement was adopted at COP21 in Paris in 2015 and entered into force in 2016.", sourceFactIds:["env-cp017-paris-year"] },
  { qlId:"ENV-017-QL-007", qlName:"Paris Agreement", difficulty:"Easy", stem:"The Paris Agreement is an international treaty on:", correct:"Climate change", distractors:["Hazardous waste","Wetlands","Wildlife trade"], explanation:"The Paris Agreement is a climate treaty under the UNFCCC framework and addresses global efforts to limit warming.", sourceFactIds:["env-cp017-paris-year","env-cp017-unfccc-framework"] },
  { qlId:"ENV-017-QL-007", qlName:"Paris Agreement", difficulty:"Medium", stem:"The Paris Agreement asks parties to communicate climate action through:", correct:"Nationally determined contributions", distractors:["Ramsar designations","CITES Appendices","People's Biodiversity Registers"], explanation:"Paris uses nationally determined contributions, or NDCs, through which parties communicate their climate actions and ambitions.", sourceFactIds:["env-cp017-paris-ndc"] },
  { qlId:"ENV-017-QL-007", qlName:"Paris Agreement", difficulty:"Hard", stem:"Which temperature goal belongs to the Paris Agreement?", correct:"Well below 2°C, while pursuing efforts toward 1.5°C", distractors:["Exactly 3°C with no lower aim","Below 4°C only","No temperature objective"], explanation:"Paris seeks to keep warming well below 2°C above pre-industrial levels while pursuing efforts to limit it to 1.5°C.", sourceFactIds:["env-cp017-paris-temperature"] },

  { qlId:"ENV-017-QL-008", qlName:"Vienna, Montreal and Kigali", difficulty:"Easy", stem:"Which treaty directly controls ozone-depleting substances?", correct:"Montreal Protocol", distractors:["Ramsar Convention","Basel Convention","Paris Agreement"], explanation:"The Montreal Protocol contains control measures for ozone-depleting substances and operates under the broader Vienna Convention framework.", sourceFactIds:["env-cp017-montreal-year","env-cp017-ozone-distinction"] },
  { qlId:"ENV-017-QL-008", qlName:"Vienna, Montreal and Kigali", difficulty:"Easy", stem:"The Vienna Convention for ozone protection was adopted in:", correct:"1985", distractors:["1971","1989","1997"], explanation:"The Vienna Convention for the Protection of the Ozone Layer was adopted in 1985 as the international framework for ozone cooperation.", sourceFactIds:["env-cp017-vienna-year"] },
  { qlId:"ENV-017-QL-008", qlName:"Vienna, Montreal and Kigali", difficulty:"Medium", stem:"The Montreal Protocol was adopted in:", correct:"1987", distractors:["1979","1992","2001"], explanation:"The Montreal Protocol on Substances that Deplete the Ozone Layer was adopted in 1987, two years after the Vienna Convention.", sourceFactIds:["env-cp017-montreal-year","env-cp017-vienna-year"] },
  { qlId:"ENV-017-QL-008", qlName:"Vienna, Montreal and Kigali", difficulty:"Hard", stem:"The Kigali Amendment mainly provides for phasedown of:", correct:"Hydrofluorocarbons", distractors:["Mercury","Persistent organic pollutants","Hazardous wastes"], explanation:"The Kigali Amendment extends the Montreal framework to phase down HFCs, potent greenhouse gases that are not major ozone-depleting substances.", sourceFactIds:["env-cp017-kigali"] },

  { qlId:"ENV-017-QL-009", qlName:"Basel Convention", difficulty:"Easy", stem:"The Basel Convention mainly deals with:", correct:"Transboundary movement of hazardous wastes", distractors:["Migratory animals","Wetland conservation","Ozone depletion"], explanation:"Basel addresses the generation, management, cross-border movement and disposal of hazardous and other wastes.", sourceFactIds:["env-cp017-basel-purpose"] },
  { qlId:"ENV-017-QL-009", qlName:"Basel Convention", difficulty:"Easy", stem:"The Basel Convention was adopted in:", correct:"1989", distractors:["1973","1985","2001"], explanation:"The Basel Convention was adopted in Basel, Switzerland, in 1989 and entered into force in 1992.", sourceFactIds:["env-cp017-basel-year"] },
  { qlId:"ENV-017-QL-009", qlName:"Basel Convention", difficulty:"Medium", stem:"A shipment of hazardous waste crosses national borders. Which treaty is most relevant?", correct:"Basel Convention", distractors:["CITES","Ramsar Convention","CMS"], explanation:"Basel specifically addresses transboundary movements of hazardous and other wastes and their environmentally sound management and disposal.", sourceFactIds:["env-cp017-basel-purpose"] },
  { qlId:"ENV-017-QL-009", qlName:"Basel Convention", difficulty:"Hard", stem:"Which issue helped drive negotiation of the Basel Convention?", correct:"International dumping and trade in hazardous waste", distractors:["Loss of migratory-bird flyways","Decline of stratospheric ozone alone","International zoo recognition"], explanation:"Basel emerged partly in response to concern over hazardous wastes being shipped and dumped across borders, especially into developing countries.", sourceFactIds:["env-cp017-basel-toxic-trade"] },

  { qlId:"ENV-017-QL-010", qlName:"Stockholm Convention", difficulty:"Easy", stem:"The Stockholm Convention mainly targets:", correct:"Persistent organic pollutants", distractors:["Mercury only","Wetlands","Migratory species"], explanation:"The Stockholm Convention is the global treaty designed to protect health and the environment from persistent organic pollutants, or POPs.", sourceFactIds:["env-cp017-stockholm-purpose"] },
  { qlId:"ENV-017-QL-010", qlName:"Stockholm Convention", difficulty:"Easy", stem:"The Stockholm Convention was adopted in:", correct:"2001", distractors:["1987","1997","2013"], explanation:"The Stockholm Convention on Persistent Organic Pollutants was adopted in 2001 and entered into force in 2004.", sourceFactIds:["env-cp017-stockholm-year"] },
  { qlId:"ENV-017-QL-010", qlName:"Stockholm Convention", difficulty:"Medium", stem:"POPs are especially concerning because they can:", correct:"Persist, accumulate and travel long distances", distractors:["Disappear immediately after release","Affect only one country","Exist only in water"], explanation:"Persistent organic pollutants remain in the environment, can move over long distances, accumulate in organisms and cause harmful effects.", sourceFactIds:["env-cp017-pops"] },
  { qlId:"ENV-017-QL-010", qlName:"Stockholm Convention", difficulty:"Hard", stem:"Which pairing is correct?", correct:"Stockholm Convention — persistent organic pollutants", distractors:["Basel Convention — mercury only","Minamata Convention — wetlands","Ramsar Convention — hazardous waste"], explanation:"Stockholm addresses POPs. Basel focuses on hazardous wastes, Minamata on mercury, and Ramsar on wetlands.", sourceFactIds:["env-cp017-stockholm-purpose","env-cp017-basel-purpose","env-cp017-minamata-purpose","env-cp017-ramsar-purpose"] },

  { qlId:"ENV-017-QL-011", qlName:"Minamata Convention", difficulty:"Easy", stem:"The Minamata Convention mainly addresses:", correct:"Mercury", distractors:["Ozone-depleting substances","Wetlands","Migratory species"], explanation:"The Minamata Convention is the global treaty focused on mercury and the risks mercury pollution poses to health and the environment.", sourceFactIds:["env-cp017-minamata-purpose"] },
  { qlId:"ENV-017-QL-011", qlName:"Minamata Convention", difficulty:"Easy", stem:"The Minamata Convention was adopted in:", correct:"2013", distractors:["1989","1992","2001"], explanation:"The Minamata Convention on Mercury was adopted in Japan in 2013 and entered into force in 2017.", sourceFactIds:["env-cp017-minamata-year"] },
  { qlId:"ENV-017-QL-011", qlName:"Minamata Convention", difficulty:"Medium", stem:"Why is the treaty called the Minamata Convention?", correct:"It recalls the Japanese city linked to severe mercury poisoning", distractors:["It was named after a wetland in Iran","It was negotiated in Bonn","It was the site of the first climate COP"], explanation:"The treaty's name recalls Minamata, Japan, where severe industrial mercury pollution caused major human health impacts.", sourceFactIds:["env-cp017-minamata-name"] },
  { qlId:"ENV-017-QL-011", qlName:"Minamata Convention", difficulty:"Hard", stem:"Which treaty-substance pair is correctly matched?", correct:"Minamata — mercury", distractors:["Stockholm — ozone only","Montreal — hazardous waste","Basel — migratory species"], explanation:"Minamata addresses mercury; Stockholm addresses POPs, Montreal ozone-depleting substances, and Basel hazardous wastes.", sourceFactIds:["env-cp017-minamata-purpose","env-cp017-stockholm-purpose","env-cp017-montreal-year","env-cp017-basel-purpose"] },

  { qlId:"ENV-017-QL-012", qlName:"Integrated treaty matching", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"Ramsar—wetlands; CITES—wildlife trade; CMS—migratory species", distractors:["Ramsar—mercury; CITES—climate; CMS—waste","Ramsar—ozone; CITES—wetlands; CMS—POPs","Ramsar—waste; CITES—mercury; CMS—climate"], explanation:"Ramsar covers wetlands, CITES international wildlife trade, and CMS the conservation of migratory wild animals.", sourceFactIds:["env-cp017-ramsar-purpose","env-cp017-cites-purpose","env-cp017-cms-purpose"] },
  { qlId:"ENV-017-QL-012", qlName:"Integrated treaty matching", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"Basel—hazardous waste; Stockholm—POPs; Minamata—mercury", distractors:["Basel—wetlands; Stockholm—tigers; Minamata—ozone","Basel—climate; Stockholm—wildlife trade; Minamata—forests","Basel—migratory species; Stockholm—wetlands; Minamata—CFCs"], explanation:"Basel deals with hazardous wastes, Stockholm with persistent organic pollutants, and Minamata with mercury.", sourceFactIds:["env-cp017-basel-purpose","env-cp017-stockholm-purpose","env-cp017-minamata-purpose"] },
  { qlId:"ENV-017-QL-012", qlName:"Integrated treaty matching", difficulty:"Hard", stem:"Which chronological order is correct?", correct:"Ramsar → CMS → Montreal → CBD → Kyoto → Paris", distractors:["CMS → Ramsar → CBD → Montreal → Paris → Kyoto","Montreal → Ramsar → CMS → Kyoto → CBD → Paris","Ramsar → Montreal → CMS → Paris → CBD → Kyoto"], explanation:"The adoption years are Ramsar 1971, CMS 1979, Montreal 1987, CBD 1992, Kyoto 1997 and Paris 2015.", sourceFactIds:["env-cp017-ramsar-year-place","env-cp017-cms-bonn","env-cp017-montreal-year","env-cp017-cbd-year","env-cp017-kyoto-year","env-cp017-paris-year"] },
  { qlId:"ENV-017-QL-012", qlName:"Integrated treaty matching", difficulty:"Hard", stem:"Which treaty-place association is NOT correct?", correct:"Basel Convention — Bonn", distractors:["Ramsar Convention — Ramsar","Kyoto Protocol — Kyoto","Paris Agreement — Paris"], explanation:"The Basel Convention was adopted in Basel, Switzerland. Bonn is associated with the Convention on Migratory Species.", sourceFactIds:["env-cp017-basel-year","env-cp017-cms-bonn","env-cp017-ramsar-year-place","env-cp017-kyoto-year","env-cp017-paris-year"] },
]);

const POSITIONS = [0, 1, 2, 3] as const;
const qlCounts = new Map<string, number>();

export const ENV_CP017_REVIEW_QUESTIONS_V1: readonly EnvCp017ReviewQuestion[] = Object.freeze(S.map((seed, index) => {
  const qlIndex = qlCounts.get(seed.qlId) ?? 0;
  qlCounts.set(seed.qlId, qlIndex + 1);
  const correctIndex = POSITIONS[qlIndex % 4];
  const options = [...seed.distractors];
  options.splice(correctIndex, 0, seed.correct);
  const sourceIds = [...new Set(seed.sourceFactIds.flatMap((id) => ENV_CP017_FACT_BY_ID_V1.get(id)?.sourceIds ?? []))];
  return {
    questionId: `ENV-CP017-V1-${String(index + 1).padStart(3, "0")}`,
    chapterId: "ENV-001",
    cpId: "ENV-CP-017",
    qlId: seed.qlId,
    qlName: seed.qlName,
    difficulty: seed.difficulty,
    stem: seed.stem,
    options,
    correctIndex,
    canonicalAnswer: seed.correct,
    explanation: seed.explanation,
    sourceIds,
    sourceFactIds: [...seed.sourceFactIds],
    reviewOnly: true,
    runtimeRegistered: false,
  };
}));
