import type { PolCp027SeedRow } from "./pol-cp027-types";

const T=["CONSTITUTION-PART-XIII-2026"] as const;

export const POL_CP027_PART_2: readonly PolCp027SeedRow[] = [
["POL-027-QL-006","Easy","Reasonable State restrictions on trade in the public interest are dealt with in:","Article 304(b)","Article 304(a)","Article 302 only","Article 307","Article 304(b) permits a State Legislature to impose reasonable restrictions on trade, commerce or intercourse when required in the public interest.",T],
["POL-027-QL-006","Easy","What additional constitutional requirement applies before introducing a Bill under Article 304(b)?","Previous sanction of the President","Approval of the Supreme Court","Consent of all neighbouring States","A Rajya Sabha resolution","The proviso to Article 304 requires previous presidential sanction before a Bill or amendment imposing restrictions under clause (b) is introduced or moved.",T],
["POL-027-QL-006","Easy","The restriction permitted by Article 304(b) must be:","Reasonable and required in the public interest","Permanent and nationwide","Approved by the Finance Commission","Limited to imported goods only","Article 304(b) combines two express limits: the restriction must be reasonable and it must be required in the public interest.",T],
["POL-027-QL-006","Easy","Does Article 304(b) allow a State to impose any trade restriction merely by passing an ordinary Bill?","No","Yes, without any constitutional condition","Yes, if the Governor agrees","Only if the tax rate is equal","Article 304(b) requires a reasonable public-interest restriction and previous presidential sanction for the Bill or amendment, so ordinary passage alone is insufficient.",T],

["POL-027-QL-007","Medium","Existing laws and laws relating to State monopolies are specially saved by:","Article 305","Article 301","Article 303","Article 307","Article 305 protects specified existing laws and laws connected with State monopolies from the ordinary operation of certain Part XIII restrictions.",T],
["POL-027-QL-007","Medium","Can Article 305 protect laws connected with State monopolies from the full effect of Article 301?","Yes","No, Article 301 always overrides them","Only during scarcity","Only after a referendum","Article 305 contains an express saving connected with laws on matters referred to in Article 19(6)(ii), which includes State monopoly arrangements.",T],
["POL-027-QL-007","Medium","The present text of Article 305 was substituted by the:","Fourth Amendment","Seventh Amendment","Forty-second Amendment","Forty-fourth Amendment","The Constitution (Fourth Amendment) Act, 1955 substituted Article 305 and shaped its present saving for existing laws and State-monopoly legislation.",T],
["POL-027-QL-007","Medium","Which Article protects specified existing trade laws unless the President directs otherwise?","Article 305","Article 302","Article 304","Article 306","Article 305 saves existing laws from Articles 301 and 303 except to the extent the President may direct otherwise by order.",T],

["POL-027-QL-008","Medium","Article 306 in the present Constitution is:","Omitted","A State taxation provision","A parliamentary restriction power","An authority-appointment provision","Article 306, which once concerned certain Part B States and trade restrictions, is shown as omitted in the current constitutional text.",T],
["POL-027-QL-008","Medium","Which amendment omitted Article 306?","Seventh Amendment","Fourth Amendment","Twenty-fourth Amendment","Forty-fourth Amendment","The Constitution (Seventh Amendment) Act, 1956 omitted Article 306 as part of the constitutional reorganisation changes effective from 1 November 1956.",T],
["POL-027-QL-008","Medium","The subject formerly covered by Article 306 concerned:","Trade restrictions by certain Part B States","Inter-State Council disputes","Public Service Commissions","Co-operative society elections","Before its omission, Article 306 dealt with the power of certain States in Part B of the First Schedule to impose trade restrictions.",T],
["POL-027-QL-008","Medium","Does Article 306 currently provide an operative trade restriction power?","No","Yes, for all States","Yes, only for Union Territories","Only during a National Emergency","The current Constitution marks Article 306 as omitted, so it no longer supplies an operative source of trade-restriction power.",T],

["POL-027-QL-009","Medium","Authority for carrying out Articles 301 to 304 may be appointed under:","Article 307","Article 305","Article 306","Article 312","Article 307 authorises Parliament by law to appoint an authority for carrying out the purposes of Articles 301, 302, 303 and 304.",T],
["POL-027-QL-009","Medium","Who may create the authority contemplated by Article 307?","Parliament by law","President by executive order alone","State Legislature alone","Supreme Court","Article 307 places the power with Parliament, which may establish the authority by law and assign it necessary powers and duties.",T],
["POL-027-QL-009","Medium","The authority under Article 307 may receive:","Powers and duties Parliament considers necessary","Only advisory functions","Only taxing powers","Only judicial powers","Article 307 leaves Parliament discretion to confer the powers and duties it considers necessary for carrying out Articles 301 to 304.",T],
["POL-027-QL-009","Medium","Does Article 307 itself permanently establish a named constitutional authority?","No","Yes, the Inter-State Trade Commission","Yes, the Finance Commission","Yes, the GST Council","Article 307 is an enabling provision: it allows Parliament to appoint an appropriate authority rather than itself creating a permanently named body.",T],

["POL-027-QL-010","Medium","A State wants to tax imported goods at the same rate as similar local goods. The relevant provision is:","Article 304(a)","Article 302","Article 303(2)","Article 307","Equal taxation of imported and similar local goods falls under Article 304(a), provided the tax does not discriminate against the imported goods.",T],
["POL-027-QL-010","Medium","Previous presidential sanction for a State Bill imposing reasonable public-interest trade restrictions is required by:","Article 304(b)","Article 304(a)","Article 302","Article 305","The special procedural condition belongs to Article 304(b), where a State proposes reasonable restrictions on trade in the public interest.",T],
["POL-027-QL-010","Medium","Parliament wants to permit a temporary preference because goods are scarce. Which provision directly supports this?","Article 303(2)","Article 301","Article 304(a)","Article 307","Article 303(2) permits Parliament to depart from the general non-discrimination rule when dealing with a situation arising from scarcity of goods.",T],
["POL-027-QL-010","Medium","Which statement correctly distinguishes Articles 302 and 304(b)?","Article 302 empowers Parliament; Article 304(b) permits State restrictions with conditions","Both empower only State Legislatures","Both require State ratification","Article 304(b) applies only to Parliament","Article 302 is Parliament's public-interest restriction power, while Article 304(b) concerns reasonable State restrictions and carries the previous-presidential-sanction condition.",T],
];
