import type { PolCp027SeedRow } from "./pol-cp027-types";

const C=["CONSTITUTION-PART-IXB-2026"] as const;
const A=["CONSTITUTION-97TH-AMENDMENT-2026"] as const;
const S=["SC-RAJENDRA-N-SHAH-2021"] as const;

export const POL_CP027_PART_3: readonly PolCp027SeedRow[] = [
["POL-027-QL-011","Medium","Part IXB entered the Constitution through the:","Ninety-seventh Amendment","Seventy-third Amendment","Seventy-fourth Amendment","One Hundred and First Amendment","The Constitution (Ninety-seventh Amendment) Act, 2011 inserted Part IXB dealing with co-operative societies; its present operation is limited by the Rajendra N. Shah ruling.",[...A,...S]],
["POL-027-QL-011","Medium","The Ninety-seventh Amendment added co-operative societies to which Fundamental Right provision?","Article 19(1)(c)","Article 14","Article 21A","Article 32","The Ninety-seventh Amendment added co-operative societies to Article 19(1)(c), alongside associations and unions; that amendment was not invalidated in Rajendra N. Shah.",[...A,...S]],
["POL-027-QL-011","Medium","Along with Part IXB, the Ninety-seventh Amendment inserted:","Article 43B","Article 39A","Article 48A","Article 51A","The Ninety-seventh Amendment inserted Article 43B on promotion of co-operative societies; detailed DPSP coverage remains separate from this Part IXB chapter.",A],
["POL-027-QL-011","Medium","Did Rajendra N. Shah strike down the Ninety-seventh Amendment in its entirety?","No","Yes, the entire amendment was struck down","Only Article 43B survived","Only Article 19(1)(c) survived","Rajendra N. Shah did not invalidate the whole amendment; the Court limited the invalidity concerning Part IXB while leaving the other amendment changes unaffected.",S],

["POL-027-QL-012","Medium","Definitions used in Part IXB are provided in:","Article 243ZH","Article 243ZI","Article 243ZJ","Article 243ZR","Article 243ZH opens Part IXB with definitions used in the co-operative-society provisions, including board, office bearer, Registrar and multi-State co-operative society.",C],
["POL-027-QL-012","Medium","What feature distinguishes a multi-State co-operative society under Article 243ZH?","Its objects are not confined to one State","It must operate only within one district","It must be owned by the Union Government","It must have exactly twenty-one directors","Article 243ZH defines a multi-State co-operative society by objects not confined to one State and registration under the law relating to such co-operatives.",C],
["POL-027-QL-012","Medium","For multi-State co-operatives, Article 243ZH refers to the:","Central Registrar","State Election Commissioner","Comptroller and Auditor General","Finance Commission Chairperson","Article 243ZH identifies the Central Registrar appointed by the Central Government in relation to multi-State co-operative societies.",C],
["POL-027-QL-012","Medium","Is a Treasurer included in the Article 243ZH definition of office bearer?","Yes","No","Only if nominated by Parliament","Only in a State-level society","Article 243ZH expressly includes President, Vice-President, Chairperson, Vice-Chairperson, Secretary and Treasurer among the listed office-bearer positions.",C],

["POL-027-QL-013","Medium","One principle specifically associated with Article 243ZI is:","Voluntary formation","Compulsory government membership","Permanent State control","Hereditary board membership","The text of Article 243ZI lists voluntary formation among the governing principles; current Part IXB operation is confined to multi-State societies and Union Territories.",[...C,...S]],
["POL-027-QL-013","Medium","Which of the following reflects a principle stated in Article 243ZI?","Democratic member-control","Judicial management","Compulsory profit distribution","Executive nomination of every director","Article 243ZI expressly mentions democratic member-control together with voluntary formation, member-economic participation and autonomous functioning.",[...C,...S]],
["POL-027-QL-013","Medium","The member-related economic principle under Article 243ZI is:","Member-economic participation","Union tax sharing","Mandatory government subsidy","Equal State grants","Member-economic participation is one of the four principles stated in Article 243ZI for incorporation, regulation and winding up of co-operative societies.",[...C,...S]],
["POL-027-QL-013","Medium","Which of the following does NOT form part of the Article 243ZI principles?","Compulsory government control","Voluntary formation","Democratic member-control","Autonomous functioning","Article 243ZI emphasises voluntary, democratic and autonomous co-operation; compulsory government control is not one of the principles stated in the text.",[...C,...S]],

["POL-027-QL-014","Medium","Under Article 243ZJ, the board may have at most:","Twenty-one","Fifteen","Twenty-five","Thirty","Article 243ZJ sets a maximum of twenty-one directors in the Part IXB framework, subject to the present constitutional scope recognised by the Supreme Court.",[...C,...S]],
["POL-027-QL-014","Medium","What is the normal term of elected board members under Article 243ZJ?","Five years from the date of election","Three years","Four years","Six years","Article 243ZJ provides a five-year term from the date of election for elected board members and makes office-bearer terms conterminous with the board.",[...C,...S]],
["POL-027-QL-014","Medium","The reservation pattern stated in Article 243ZJ includes:","One SC/ST seat and two seats for women","Two SC/ST seats and one seat for women","Only one seat for women","No board reservation provision","The text provides one seat for Scheduled Castes or Scheduled Tribes and two seats for women on qualifying co-operative boards.",[...C,...S]],
["POL-027-QL-014","Medium","Do co-opted expert members under Article 243ZJ have voting rights in society elections?","No","Yes, with full voting rights","Only after five years","Only if elected as office bearers","Article 243ZJ allows up to two co-opted experts but denies them voting rights in society elections and eligibility for election as board office bearers.",[...C,...S]],

["POL-027-QL-015","Medium","Timely election of a co-operative board before its term expires is required under:","Article 243ZK","Article 243ZJ","Article 243ZL","Article 243ZM","Article 243ZK contains the Part IXB rules concerning board elections, including timing and control of electoral rolls and election conduct.",[...C,...S]],
["POL-027-QL-015","Medium","By when should a co-operative board election be completed under Article 243ZK?","Before the outgoing board's term expires","Within one year after expiry","Only after supersession","Whenever the Registrar chooses","Article 243ZK requires the election before the outgoing board's term expires so newly elected members can assume office immediately afterward.",[...C,...S]],
["POL-027-QL-015","Medium","Under Article 243ZK, control of electoral rolls and board elections rests with:","An authority or body provided by law","The Supreme Court","The Finance Commission","The Comptroller and Auditor General","Article 243ZK places election superintendence, direction and control in an authority or body provided by the applicable law.",[...C,...S]],
["POL-027-QL-015","Medium","Does Article 243ZK aim to avoid a gap between outgoing and incoming boards?","Yes","No, a six-month gap is required","Only after parliamentary approval","Only after an audit is completed","Article 243ZK is designed to avoid a gap by requiring timely elections so the incoming board assumes office immediately on expiry of the outgoing term.",[...C,...S]],
];
