import type { PolCp027SeedRow } from "./pol-cp027-types";

const T=["CONSTITUTION-PART-XIII-2026"] as const;

export const POL_CP027_PART_2: readonly PolCp027SeedRow[] = [
["POL-027-QL-006","Easy","Reasonable public-interest restrictions imposed by a State are permitted under:","Article 304(b)","Article 304(a)","Article 302 only","Article 307","Article 304(b) permits a State Legislature to impose reasonable restrictions on trade, commerce or intercourse when required in the public interest.",T],
["POL-027-QL-006","Easy","Before introducing a Bill under Article 304(b), what prior approval is required?","Previous sanction of the President","Approval of the Supreme Court","Consent of all neighbouring States","A Rajya Sabha resolution","The proviso to Article 304 requires previous presidential sanction before a Bill or amendment imposing restrictions under clause (b) is introduced or moved.",T],
["POL-027-QL-006","Easy","A restriction under Article 304(b) must satisfy which standard?","Reasonable and required in the public interest","Permanent and nationwide","Approved by the Finance Commission","Limited to imported goods only","Article 304(b) combines two express limits: the restriction must be reasonable and it must be required in the public interest.",T],
["POL-027-QL-006","Easy","Can a State impose a trade restriction under Article 304(b) without meeting its constitutional conditions?","No","Yes, without any constitutional condition","Yes, if the Governor agrees","Only if the tax rate is equal","Article 304(b) requires a reasonable public-interest restriction and previous presidential sanction for the Bill or amendment, so ordinary passage alone is insufficient.",T],

["POL-027-QL-007","Medium","Existing trade laws and State-monopoly laws receive protection under:","Article 305","Article 301","Article 303","Article 307","Article 305 protects specified existing laws and laws connected with State monopolies from the ordinary operation of certain Part XIII restrictions.",T],
["POL-027-QL-007","Medium","Can State-monopoly laws receive protection from Article 301 under Article 305?","Yes","No, Article 301 always overrides them","Only during scarcity","Only after a referendum","Article 305 contains an express saving connected with laws on matters referred to in Article 19(6)(ii), which includes State monopoly arrangements.",T],
["POL-027-QL-007","Medium","The present form of Article 305 came through the:","Fourth Amendment","Seventh Amendment","Forty-second Amendment","Forty-fourth Amendment","The Constitution (Fourth Amendment) Act, 1955 substituted Article 305 and shaped its present saving for existing laws and State-monopoly legislation.",T],
["POL-027-QL-007","Medium","Specified existing trade laws are saved, subject to presidential direction, under which Article?","Article 305","Article 302","Article 304","Article 306","Article 305 saves existing laws from Articles 301 and 303 except to the extent the President may direct otherwise by order.",T],

["POL-027-QL-008","Medium","In the present Constitution, Article 306 stands:","Omitted","A State taxation provision","A parliamentary restriction power","An authority-appointment provision","Article 306, which once concerned certain Part B States and trade restrictions, is shown as omitted in the current constitutional text.",T],
["POL-027-QL-008","Medium","Article 306 was omitted by which Constitutional Amendment?","Seventh Amendment","Fourth Amendment","Twenty-fourth Amendment","Forty-fourth Amendment","The Constitution (Seventh Amendment) Act, 1956 omitted Article 306 as part of the constitutional reorganisation changes effective from 1 November 1956.",T],
["POL-027-QL-008","Medium","Before its omission, Article 306 dealt with:","Trade restrictions by certain Part B States","Inter-State Council disputes","Public Service Commissions","Co-operative society elections","Before its omission, Article 306 dealt with the power of certain States in Part B of the First Schedule to impose trade restrictions.",T],
["POL-027-QL-008","Medium","Does Article 306 still confer any operative trade-restriction power?","No","Yes, for all States","Yes, only for Union Territories","Only during a National Emergency","The current Constitution marks Article 306 as omitted, so it no longer supplies an operative source of trade-restriction power.",T],

["POL-027-QL-009","Medium","Parliament may create an authority to implement Articles 301–304 under:","Article 307","Article 305","Article 306","Article 312","Article 307 authorises Parliament by law to appoint an authority for carrying out the purposes of Articles 301, 302, 303 and 304.",T],
["POL-027-QL-009","Medium","Under Article 307, which institution may create the implementing authority?","Parliament by law","President by executive order alone","State Legislature alone","Supreme Court","Article 307 places the power with Parliament, which may establish the authority by law and assign it necessary powers and duties.",T],
["POL-027-QL-009","Medium","An authority created under Article 307 may be given:","Powers and duties Parliament considers necessary","Only advisory functions","Only taxing powers","Only judicial powers","Article 307 leaves Parliament discretion to confer the powers and duties it considers necessary for carrying out Articles 301 to 304.",T],
["POL-027-QL-009","Medium","Does Article 307 itself create a permanently named constitutional body?","No","Yes, the Inter-State Trade Commission","Yes, the Finance Commission","Yes, the GST Council","Article 307 is an enabling provision: it allows Parliament to appoint an appropriate authority rather than itself creating a permanently named body.",T],

["POL-027-QL-010","Medium","A State taxes imported and similar local goods at the same rate. The relevant provision is:","Article 304(a)","Article 302","Article 303(2)","Article 307","Equal taxation of imported and similar local goods falls under Article 304(a), provided the tax does not discriminate against the imported goods.",T],
["POL-027-QL-010","Medium","A State Bill imposing reasonable trade restrictions needs previous presidential sanction under:","Article 304(b)","Article 304(a)","Article 302","Article 305","The special procedural condition belongs to Article 304(b), where a State proposes reasonable restrictions on trade in the public interest.",T],
["POL-027-QL-010","Medium","Which provision allows Parliament to make a scarcity-based exception to the inter-State non-discrimination rule?","Article 303(2)","Article 301","Article 304(a)","Article 307","Article 303(2) permits Parliament to depart from the general non-discrimination rule when dealing with a situation arising from scarcity of goods.",T],
["POL-027-QL-010","Medium","Which statement correctly compares Parliament's power under Article 302 with a State's power under Article 304(b)?","Article 302 empowers Parliament; Article 304(b) permits State restrictions with conditions","Both empower only State Legislatures","Both require State ratification","Article 304(b) applies only to Parliament","Article 302 is Parliament's public-interest restriction power, while Article 304(b) concerns reasonable State restrictions and carries the previous-presidential-sanction condition.",T],
];
