import { LP_009_ENGLISH_FREEZE_V1 } from "./lp-009-permanent-freeze.ts";
import { LP_009_HI_PA_LOCALIZATION_REVIEW_V3 } from "./lp-009-localization-v3.ts";

export const LP_009_HI_PA_LOCALIZATION_FREEZE_V3 = Object.freeze({
  authorityId: "LP_009_HI_PA_LOCALIZATION_FREEZE_V3" as const,
  sourceEnglishAuthorityId: LP_009_ENGLISH_FREEZE_V1.authorityId,
  sourceLocalizationAuthorityId: LP_009_HI_PA_LOCALIZATION_REVIEW_V3.authorityId,
  packageId: "LP-009" as const,
  checkpointId: "LP-CP-009" as const,
  permanentQlIds: ["LP-QL-033", "LP-QL-034", "LP-QL-035", "LP-QL-036"] as const,
  supportedLanguages: ["en", "hi", "pa"] as const,
  locales: ["en-IN", "hi-IN", "pa-IN"] as const,
  status: "HI_PA_HUMAN_REVIEWED_V3_LOCALIZATION_FROZEN" as const,
  approvedOn: "2026-09-10" as const,
  approvalBasis: "EXPLICIT_HUMAN_REVIEW_APPROVAL" as const,
  approvalRecord: "LP-009-HI-PA-LOCALIZATION-APPROVAL-V3" as const,
  localizationMethod: "SEMANTIC_REBUILD_FROM_FROZEN_SOLVED_CASELET" as const,
  englishFreezeStatus: "FROZEN_V1" as const,
  localizationFreezeStatus: "FROZEN_V3" as const,
  runtimeMode: "REVIEW_ONLY" as const,
  questionStudioLanguageActivation: "ALLOWED_AFTER_INTEGRATION_PROOF" as const,
  questionBankStatus: "NOT_STORED" as const,
  questionBankWritable: false as const,
  testEligibility: "INELIGIBLE" as const,
  testEligible: false as const,
  mockTestEligible: false as const,
  publiclyPublishable: false as const,
  automaticStudentPublication: false as const,
  invariants: Object.freeze({
    samePermanentQlOwnership: true,
    sameSolvedAssignments: true,
    sameDifficultyBands: true,
    sameCorrectOptionIndices: true,
    sameExplanationStepCounts: true,
    progressiveExplanationTables: true,
    nativeHindiPunjabiLearnerCopy: true,
    optionByOptionAnalysisForbidden: true,
    questionBankLocked: true,
    testAndMockLocked: true,
    publicationLocked: true,
  }),
});
