import type { StaEnglishCorpusScenario } from "../english-corpus-types.ts";
import { CORPUS_CANDIDATE, SOURCE_SUPPORTED, c, d, p } from "./helpers.ts";

export const STA_QL002_ENGLISH_EXPANSION = [
  {
    scenarioId: "STA-EN-QL002-COUNTER-HOURS",
    corpusFamilyId: "QL002-CAPACITY-POLICY",
    domain: "PUBLIC_SERVICE",
    semanticShape: "NEED_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "SSC",
    discourseAct: "RECOMMENDATION",
    objectiveIds: ["REDUCE_END_OF_DAY_APPLICATION_BACKLOG"],
    statementVariants: [
      "The service centre should keep one counter open an hour longer to reduce the end-of-day application backlog.",
      "To reduce the application backlog near closing time, one service counter should remain open for an extra hour.",
    ],
    propositions: [
      p("P1", "END_OF_DAY_APPLICATION_BACKLOG_EXISTS", "END_OF_DAY_APPLICATION_BACKLOG_DOES_NOT_EXIST", ["service centre", "applications"]),
      p("P2", "EXTRA_COUNTER_HOUR_CAN_REDUCE_BACKLOG", "EXTRA_COUNTER_HOUR_CANNOT_REDUCE_BACKLOG", ["counter", "backlog"]),
      p("P3", "ALL_APPLICANTS_ARRIVE_IN_LAST_HOUR", "NOT_ALL_APPLICANTS_ARRIVE_IN_LAST_HOUR", ["applicants", "last hour"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "EXISTENCE", ["REDUCE_END_OF_DAY_APPLICATION_BACKLOG"], "BREAKS_RATIONALE"),
      d("D2", "P2", "EFFICACY", ["REDUCE_END_OF_DAY_APPLICATION_BACKLOG"], "BREAKS_RATIONALE"),
    ],
    candidates: [
      c("C1", "P1", ["An application backlog exists near the end of the day.", "The service centre faces a backlog close to closing time."], "IMPLICIT", "The recommendation is specifically intended to reduce an end-of-day backlog, so that problem must exist."),
      c("C2", "P2", ["Keeping a counter open longer can reduce the backlog.", "An extra counter hour can help clear the end-of-day application backlog."], "IMPLICIT", "The proposed extension needs to be capable of improving the problem it is meant to solve."),
      c("C3", "P3", ["All applicants arrive only in the final hour.", "Every applicant comes to the centre during the last hour."], "NOT_IMPLICIT", "A late-day backlog can exist without every applicant arriving during the final hour.", "TOO_STRONG_QUANTIFIER"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN-QL002-REMEDIAL-CLASS",
    corpusFamilyId: "QL002-TARGETED-SUPPORT",
    domain: "EDUCATION",
    semanticShape: "NEED_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "SSC",
    discourseAct: "PROPOSAL",
    objectiveIds: ["HELP_STUDENTS_STRUGGLING_WITH_TOPIC"],
    statementVariants: [
      "The school should offer a short remedial class for students struggling with the topic.",
      "To help students who are finding the topic difficult, the school should arrange a remedial class.",
    ],
    propositions: [
      p("P1", "SOME_STUDENTS_STRUGGLE_WITH_TOPIC", "NO_STUDENT_STRUGGLES_WITH_TOPIC", ["students", "topic"], "SOME"),
      p("P2", "REMEDIAL_CLASS_CAN_HELP_STRUGGLING_STUDENTS", "REMEDIAL_CLASS_CANNOT_HELP_STRUGGLING_STUDENTS", ["remedial class", "students"]),
      p("P3", "ALL_STUDENTS_WANT_EXTRA_CLASS", "NOT_ALL_STUDENTS_WANT_EXTRA_CLASS", ["students", "extra class"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "RELEVANCE", ["HELP_STUDENTS_STRUGGLING_WITH_TOPIC"], "BREAKS_RELEVANCE"),
      d("D2", "P2", "EFFICACY", ["HELP_STUDENTS_STRUGGLING_WITH_TOPIC"], "BREAKS_RATIONALE"),
    ],
    candidates: [
      c("C1", "P1", ["Some students are struggling with the topic.", "There are students who need additional help with the topic."], "IMPLICIT", "The proposed remedial class is targeted at struggling students, so such a need must be relevant."),
      c("C2", "P2", ["A remedial class can help students who are struggling.", "Additional guided teaching can help the targeted students with the topic."], "IMPLICIT", "The proposal depends on the remedial class being capable of helping the group it is meant to support."),
      c("C3", "P3", ["All students want an extra class.", "Every student wants to attend additional classes."], "NOT_IMPLICIT", "The proposal targets students who need help and does not require universal demand from all students.", "TOO_STRONG_QUANTIFIER"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN-QL002-STAGGERED-BREAKS",
    corpusFamilyId: "QL002-STAFFING-POLICY",
    domain: "BANKING_SERVICE",
    semanticShape: "NEED_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "BANKING",
    discourseAct: "DECISION",
    objectiveIds: ["MAINTAIN_LUNCH_HOUR_COUNTER_CAPACITY"],
    statementVariants: [
      "The branch will stagger staff lunch breaks so that service counters do not become understaffed at noon.",
      "To avoid too few staffed counters at noon, the branch has decided to stagger employee lunch breaks.",
    ],
    propositions: [
      p("P1", "SIMULTANEOUS_LUNCH_BREAKS_CAN_REDUCE_COUNTER_CAPACITY", "SIMULTANEOUS_LUNCH_BREAKS_DO_NOT_REDUCE_COUNTER_CAPACITY", ["lunch breaks", "counter capacity"]),
      p("P2", "STAGGERING_BREAKS_CAN_MAINTAIN_COUNTER_CAPACITY", "STAGGERING_BREAKS_CANNOT_MAINTAIN_COUNTER_CAPACITY", ["staggered breaks", "counter capacity"]),
      p("P3", "ALL_CUSTOMERS_VISIT_AT_NOON", "NOT_ALL_CUSTOMERS_VISIT_AT_NOON", ["customers", "noon"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "RELEVANCE", ["MAINTAIN_LUNCH_HOUR_COUNTER_CAPACITY"], "BREAKS_RELEVANCE"),
      d("D2", "P2", "EFFICACY", ["MAINTAIN_LUNCH_HOUR_COUNTER_CAPACITY"], "BREAKS_RATIONALE"),
    ],
    candidates: [
      c("C1", "P1", ["If too many staff take lunch together, counter capacity can fall.", "Simultaneous lunch breaks can leave too few staffed counters."], "IMPLICIT", "The decision is intended to prevent a noon staffing shortfall, so overlapping breaks must be capable of creating that problem."),
      c("C2", "P2", ["Staggering lunch breaks can help maintain counter capacity.", "Different lunch times can keep more service counters staffed."], "IMPLICIT", "The decision depends on staggering breaks being able to preserve the staffing level it is meant to protect."),
      c("C3", "P3", ["All customers visit the branch at noon.", "Every customer comes to the branch during the lunch hour."], "NOT_IMPLICIT", "A noon staffing problem can matter without every customer visiting at that time.", "TOO_STRONG_QUANTIFIER"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Hard",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN-QL002-FEEDER-BUS",
    corpusFamilyId: "QL002-TRANSPORT-CAPACITY",
    domain: "TRANSPORT",
    semanticShape: "NEED_PLUS_FEASIBILITY_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "PUNJAB_STATE",
    discourseAct: "RECOMMENDATION",
    objectiveIds: ["IMPROVE_SHIFT_CHANGE_CONNECTIVITY"],
    statementVariants: [
      "A feeder bus should run at factory shift-change time to improve transport from the industrial area to the main bus stand.",
      "To improve shift-change connectivity, a feeder bus should link the industrial area with the main bus stand.",
    ],
    propositions: [
      p("P1", "SHIFT_CHANGE_CONNECTIVITY_NEED_EXISTS", "SHIFT_CHANGE_CONNECTIVITY_NEED_DOES_NOT_EXIST", ["industrial area", "shift change"]),
      p("P2", "FEEDER_BUS_CAN_IMPROVE_CONNECTIVITY", "FEEDER_BUS_CANNOT_IMPROVE_CONNECTIVITY", ["feeder bus", "connectivity"]),
      p("P3", "FEEDER_BUS_CAN_OPERATE_AT_SHIFT_CHANGE", "FEEDER_BUS_CANNOT_OPERATE_AT_SHIFT_CHANGE", ["feeder bus", "shift change"]),
      p("P4", "ALL_FACTORY_WORKERS_USE_BUSES", "NOT_ALL_FACTORY_WORKERS_USE_BUSES", ["factory workers", "buses"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "EXISTENCE", ["IMPROVE_SHIFT_CHANGE_CONNECTIVITY"], "BREAKS_RATIONALE"),
      d("D2", "P2", "EFFICACY", ["IMPROVE_SHIFT_CHANGE_CONNECTIVITY"], "BREAKS_RATIONALE"),
      d("D3", "P3", "FEASIBILITY", ["IMPROVE_SHIFT_CHANGE_CONNECTIVITY"], "BREAKS_FEASIBILITY"),
    ],
    candidates: [
      c("C1", "P1", ["There is a transport-connectivity need around shift-change time.", "Shift-change travel from the industrial area needs improvement."], "IMPLICIT", "The proposal's stated purpose presupposes a real connectivity need at that time."),
      c("C2", "P2", ["A feeder bus can improve the stated connectivity.", "Linking the industrial area by feeder bus can improve access to the main bus stand."], "IMPLICIT", "The recommended service must be capable of addressing the transport problem it targets."),
      c("C3", "P4", ["All factory workers use buses for travel.", "Every factory worker depends on bus transport."], "NOT_IMPLICIT", "A feeder service can be useful to some workers without every worker using buses.", "TOO_STRONG_QUANTIFIER"),
      c("C4", "P3", ["The feeder bus can operate at shift-change time.", "Running the feeder service at the proposed time is feasible."], "IMPLICIT", "The recommendation requires the proposed service to be operable at the time it is meant to help."),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Hard",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN-QL002-HANDOFF-CHECKLIST",
    corpusFamilyId: "QL002-PROCESS-CONTROL",
    domain: "WORKPLACE",
    semanticShape: "NEED_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "BANKING",
    discourseAct: "PROPOSAL",
    objectiveIds: ["REDUCE_MISSED_SHIFT_HANDOFFS"],
    statementVariants: [
      "The operations team should use a handoff checklist to reduce tasks being missed between shifts.",
      "To reduce missed tasks during shift changes, the operations team should introduce a handoff checklist.",
    ],
    propositions: [
      p("P1", "MISSED_SHIFT_HANDOFF_TASKS_OCCUR", "MISSED_SHIFT_HANDOFF_TASKS_DO_NOT_OCCUR", ["shift handoffs", "tasks"]),
      p("P2", "HANDOFF_CHECKLIST_CAN_REDUCE_MISSED_TASKS", "HANDOFF_CHECKLIST_CANNOT_REDUCE_MISSED_TASKS", ["checklist", "missed tasks"]),
      p("P3", "CHECKLIST_WILL_REMOVE_ALL_WORK_ERRORS", "CHECKLIST_WILL_NOT_REMOVE_ALL_WORK_ERRORS", ["checklist", "work errors"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "EXISTENCE", ["REDUCE_MISSED_SHIFT_HANDOFFS"], "BREAKS_RATIONALE"),
      d("D2", "P2", "EFFICACY", ["REDUCE_MISSED_SHIFT_HANDOFFS"], "BREAKS_RATIONALE"),
    ],
    candidates: [
      c("C1", "P1", ["Tasks are sometimes missed during shift handoffs.", "The team has a problem with tasks being missed between shifts."], "IMPLICIT", "A checklist proposed to reduce missed handoffs assumes that such misses are a real problem."),
      c("C2", "P2", ["A handoff checklist can reduce missed tasks.", "Using a checklist can help prevent tasks from being overlooked between shifts."], "IMPLICIT", "The proposal depends on the checklist being capable of improving the specific handoff problem."),
      c("C3", "P3", ["The checklist will eliminate every type of work error.", "No work error will occur once the checklist is introduced."], "NOT_IMPLICIT", "The proposal concerns missed handoff tasks, not elimination of all workplace errors.", "CAUSE_EFFECT_OVERREACH"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN-QL002-STATUS-TRACKING",
    corpusFamilyId: "QL002-DIGITAL-SERVICE-POLICY",
    domain: "CIVIC_ADMIN",
    semanticShape: "NEED_PLUS_EFFICACY",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-002",
    checkpointId: "STA-CP-002",
    sourceProfile: "PUNJAB_STATE",
    discourseAct: "RECOMMENDATION",
    objectiveIds: ["REDUCE_REPEAT_STATUS_VISITS"],
    statementVariants: [
      "The office should provide online application-status tracking to reduce repeat visits made only to ask for updates.",
      "To reduce repeated status-enquiry visits, the office should let applicants track their applications online.",
    ],
    propositions: [
      p("P1", "REPEAT_STATUS_ENQUIRY_VISITS_OCCUR", "REPEAT_STATUS_ENQUIRY_VISITS_DO_NOT_OCCUR", ["applicants", "status enquiries"]),
      p("P2", "ONLINE_TRACKING_CAN_REDUCE_STATUS_VISITS", "ONLINE_TRACKING_CANNOT_REDUCE_STATUS_VISITS", ["online tracking", "status visits"]),
      p("P3", "EVERY_APPLICANT_PREFERS_ONLINE_SERVICE", "NOT_EVERY_APPLICANT_PREFERS_ONLINE_SERVICE", ["applicants", "online service"], "ALL"),
    ],
    explicitPropositionIds: [],
    hiddenDependencies: [
      d("D1", "P1", "EXISTENCE", ["REDUCE_REPEAT_STATUS_VISITS"], "BREAKS_RATIONALE"),
      d("D2", "P2", "EFFICACY", ["REDUCE_REPEAT_STATUS_VISITS"], "BREAKS_RATIONALE"),
    ],
    candidates: [
      c("C1", "P1", ["Applicants make repeat visits merely to ask about application status.", "Repeated status-enquiry visits are a real issue for the office."], "IMPLICIT", "The stated reason for online tracking is to reduce such visits, so that issue must exist."),
      c("C2", "P2", ["Online status tracking can reduce repeat enquiry visits.", "Giving applicants online status information can reduce trips made only for updates."], "IMPLICIT", "The proposal needs online tracking to be capable of changing the behaviour it is meant to reduce."),
      c("C3", "P3", ["Every applicant prefers online services.", "All applicants would rather use an online service than visit an office."], "NOT_IMPLICIT", "The measure can reduce some status visits without universal preference for online service.", "TOO_STRONG_QUANTIFIER"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
] as const satisfies readonly StaEnglishCorpusScenario[];
