import type { StaEnglishCorpusScenario } from "../english-corpus-types.ts";
import { CORPUS_CANDIDATE, SOURCE_SUPPORTED, c, d, p } from "./helpers.ts";

export const STA_QL004_V2_GAPFILL = [
  {
    scenarioId: "STA-EN2-QL004-FLOOR-MARKINGS",
    corpusFamilyId: "QL004-MARKINGS-TO-CROWD-DISTRIBUTION",
    domain: "PUBLIC_SERVICE",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "SSC",
    discourseAct: "ASSERTION",
    objectiveIds: ["CLAIM_MARKINGS_REDUCE_DOORWAY_CROWDING"],
    statementVariants: [
      "The waiting hall now has separate floor markings for each service queue; this should reduce crowding near the entrance doorway.",
      "Separate service-queue markings have been added to the waiting hall, and the hall expects less crowding around the entrance.",
    ],
    propositions: [
      p("P0", "WAITING_HALL_HAS_SEPARATE_QUEUE_MARKINGS", "WAITING_HALL_DOES_NOT_HAVE_SEPARATE_QUEUE_MARKINGS", ["waiting hall", "queue markings"]),
      p("P1", "CLEAR_QUEUE_MARKINGS_CAN_DISTRIBUTE_WAITING_PEOPLE_AWAY_FROM_DOORWAY", "CLEAR_QUEUE_MARKINGS_CANNOT_DISTRIBUTE_WAITING_PEOPLE_AWAY_FROM_DOORWAY", ["queue markings", "waiting people", "doorway"]),
      p("P2", "EVERY_VISITOR_ALWAYS_FOLLOWS_FLOOR_MARKINGS", "NOT_EVERY_VISITOR_ALWAYS_FOLLOWS_FLOOR_MARKINGS", ["visitors", "floor markings"], "ALL"),
      p("P3", "MARKINGS_WILL_ELIMINATE_ALL_WAITING", "MARKINGS_WILL_NOT_ELIMINATE_ALL_WAITING", ["markings", "waiting"], "ALL"),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["CLAIM_MARKINGS_REDUCE_DOORWAY_CROWDING"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["Clear queue markings can spread waiting people away from the entrance doorway.", "Separating queues with visible markings can reduce clustering near the doorway."], "IMPLICIT", "The claim moves from separate queue markings to less doorway crowding, so the markings must be capable of changing how people distribute themselves while waiting."),
      c("C2", "P2", ["Every visitor always follows floor markings perfectly.", "All visitors obey every queue marking without exception."], "NOT_IMPLICIT", "The claim only requires the markings to influence enough people to reduce crowding; perfect universal compliance is unnecessary.", "TOO_STRONG_QUANTIFIER"),
      c("C3", "P3", ["The floor markings will eliminate all waiting.", "Nobody will have to wait once the markings are added."], "NOT_IMPLICIT", "Reducing crowding near one area is not the same as eliminating the need to wait.", "CAUSE_EFFECT_OVERREACH"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN2-QL004-DUPLICATE-ID-FLAG",
    corpusFamilyId: "QL004-DETECTION-TO-DUPLICATE-REDUCTION",
    domain: "DIGITAL_SERVICE",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "BANKING",
    discourseAct: "ASSERTION",
    objectiveIds: ["CLAIM_DUPLICATE_CHECK_REDUCES_DUPLICATE_ENTRIES"],
    statementVariants: [
      "The new registration system flags matching identity numbers for manual review, so duplicate customer entries should become less common.",
      "Matching identity numbers are now flagged before registration is completed; the bank expects fewer duplicate customer records.",
    ],
    propositions: [
      p("P0", "SYSTEM_FLAGS_MATCHING_ID_NUMBERS_FOR_REVIEW", "SYSTEM_DOES_NOT_FLAG_MATCHING_ID_NUMBERS_FOR_REVIEW", ["registration system", "identity numbers"]),
      p("P1", "FLAGGING_MATCHES_CAN_PREVENT_SOME_DUPLICATE_RECORD_CREATION", "FLAGGING_MATCHES_CANNOT_PREVENT_ANY_DUPLICATE_RECORD_CREATION", ["flagging matches", "duplicate records"], "SOME"),
      p("P2", "ALL_MATCHING_ID_NUMBERS_ARE_FRAUD", "NOT_ALL_MATCHING_ID_NUMBERS_ARE_FRAUD", ["matching identity numbers", "fraud"], "ALL"),
      p("P3", "DUPLICATE_RECORDS_CAUSE_SYSTEM_TO_FLAG_MATCHES_AFTER_CREATION", "DUPLICATE_RECORDS_DO_NOT_CAUSE_SYSTEM_TO_FLAG_MATCHES_AFTER_CREATION", ["duplicate records", "matching flags"]),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["CLAIM_DUPLICATE_CHECK_REDUCES_DUPLICATE_ENTRIES"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["Flagging matching identity numbers before completion can prevent some duplicate records from being created.", "Reviewing matching identity numbers can stop at least some duplicate customer entries."], "IMPLICIT", "The expected reduction in duplicate records requires the flag-and-review step to interrupt at least some duplicate registrations."),
      c("C2", "P2", ["Every matching identity number indicates fraud.", "All identity-number matches are fraudulent attempts."], "NOT_IMPLICIT", "Duplicate-record prevention does not require every match to be fraudulent; legitimate duplicates or data issues can still justify review.", "TOO_STRONG_QUANTIFIER"),
      c("C3", "P3", ["Duplicate records first cause the system to flag matching identity numbers after they have been created.", "The flagging happens because duplicate records already exist and then trigger the check."], "NOT_IMPLICIT", "This reverses the intended direction: the system check is presented as a control before completion, not as an effect of duplicates already created.", "REVERSE_DEPENDENCY"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Hard",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN2-QL004-EXPRESS-DEPOSIT-LANE",
    corpusFamilyId: "QL004-CHANNEL-SUBSTITUTION-DEPOSIT-WAIT",
    domain: "BANKING_SERVICE",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "BANKING",
    discourseAct: "ASSERTION",
    objectiveIds: ["CLAIM_EXPRESS_LANE_REDUCES_SIMPLE_DEPOSIT_WAIT"],
    statementVariants: [
      "An express lane now handles simple cash deposits separately, so customers making those deposits should wait less at the regular counters.",
      "Simple cash deposits have been moved to a separate express lane; this is expected to shorten the regular-counter wait for those customers.",
    ],
    propositions: [
      p("P0", "EXPRESS_LANE_HANDLES_SIMPLE_CASH_DEPOSITS", "EXPRESS_LANE_DOES_NOT_HANDLE_SIMPLE_CASH_DEPOSITS", ["express lane", "simple cash deposits"]),
      p("P1", "MOVING_SIMPLE_DEPOSITS_TO_EXPRESS_LANE_CAN_DIVERT_RELEVANT_QUEUE_LOAD", "MOVING_SIMPLE_DEPOSITS_TO_EXPRESS_LANE_CANNOT_DIVERT_RELEVANT_QUEUE_LOAD", ["simple deposits", "express lane", "regular counter"]),
      p("P2", "EXPRESS_LANE_CAN_HANDLE_EVERY_BANK_TRANSACTION", "EXPRESS_LANE_CANNOT_HANDLE_EVERY_BANK_TRANSACTION", ["express lane", "bank transactions"], "ALL"),
      p("P3", "REGULAR_COUNTER_WAIT_WILL_FALL_NEXT_YEAR_ONLY", "REGULAR_COUNTER_WAIT_WILL_NOT_FALL_NEXT_YEAR_ONLY", ["regular counter wait", "next year"]),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["CLAIM_EXPRESS_LANE_REDUCES_SIMPLE_DEPOSIT_WAIT"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["Moving simple deposits to the express lane can divert relevant load from regular counters.", "A separate express lane can remove some simple-deposit customers from the regular-counter queue."], "IMPLICIT", "The claim depends on the separate lane changing the queue load faced by the customers whose waiting time is expected to fall."),
      c("C2", "P2", ["The express lane can perform every type of bank transaction.", "No banking transaction is beyond the express lane's capability."], "NOT_IMPLICIT", "The lane only needs to handle the stated simple deposits; universal transaction capability is unnecessary.", "FEASIBILITY_OVERREACH"),
      c("C3", "P3", ["The regular-counter waiting time will fall only next year.", "Any reduction in waiting will occur in a later year rather than under the current arrangement."], "NOT_IMPLICIT", "The claim concerns the effect of the newly introduced lane, not a change restricted to an unrelated future period.", "WRONG_TIMEFRAME"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Hard",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN2-QL004-CHECKLIST-BOARD",
    corpusFamilyId: "QL004-CHECKLIST-TO-COMPLETENESS",
    domain: "CIVIC_ADMIN",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "PUNJAB_STATE",
    discourseAct: "PREDICTION",
    objectiveIds: ["PREDICT_FEWER_INCOMPLETE_DOCUMENT_SUBMISSIONS"],
    statementVariants: [
      "A document checklist is now displayed beside the submission counter, so incomplete document sets are expected to decrease.",
      "Because applicants can see the required-document checklist before reaching the counter, the office expects fewer incomplete submissions.",
    ],
    propositions: [
      p("P0", "REQUIRED_DOCUMENT_CHECKLIST_DISPLAYED_BEFORE_SUBMISSION", "REQUIRED_DOCUMENT_CHECKLIST_NOT_DISPLAYED_BEFORE_SUBMISSION", ["document checklist", "submission counter"]),
      p("P1", "VISIBLE_CHECKLIST_CAN_HELP_APPLICANTS_IDENTIFY_MISSING_DOCUMENTS", "VISIBLE_CHECKLIST_CANNOT_HELP_APPLICANTS_IDENTIFY_MISSING_DOCUMENTS", ["checklist", "applicants", "missing documents"]),
      p("P2", "ALL_INCOMPLETE_SUBMISSIONS_ARE_INTENTIONAL", "NOT_ALL_INCOMPLETE_SUBMISSIONS_ARE_INTENTIONAL", ["incomplete submissions"], "ALL"),
      p("P3", "ANOTHER_DISTRICT_USES_SAME_CHECKLIST", "ANOTHER_DISTRICT_DOES_NOT_USE_SAME_CHECKLIST", ["another district", "checklist"]),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["PREDICT_FEWER_INCOMPLETE_DOCUMENT_SUBMISSIONS"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["Seeing the checklist can help applicants identify a missing required document before submission.", "A visible required-document list can help applicants correct an incomplete document set before reaching the counter."], "IMPLICIT", "The prediction requires the checklist to influence at least some applicants to identify and correct missing-document problems."),
      c("C2", "P2", ["All incomplete submissions are made intentionally.", "Every incomplete document set is submitted on purpose."], "NOT_IMPLICIT", "The expected effect of a checklist does not require one universal explanation for why submissions are incomplete.", "TOO_STRONG_QUANTIFIER"),
      c("C3", "P3", ["Another district office uses exactly the same checklist.", "The same document checklist is used in a different district."], "NOT_IMPLICIT", "An external office's practice is not needed to support the local prediction.", "EXTERNAL_KNOWLEDGE"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN2-QL004-LOW-STOCK-ALERT",
    corpusFamilyId: "QL004-ALERT-TO-REPLENISHMENT-BRIDGE",
    domain: "FACILITY_OPERATIONS",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "CROSS_EXAM_DISCOVERY",
    discourseAct: "PREDICTION",
    objectiveIds: ["PREDICT_FEWER_SUPPLY_STOCKOUT_INTERRUPIONS"],
    statementVariants: [
      "The storeroom system now sends a low-stock alert before essential supplies run out, so stockout-related work interruptions should decrease.",
      "Because essential supplies now trigger an early low-stock alert, fewer work interruptions from stockouts are expected.",
    ],
    propositions: [
      p("P0", "SYSTEM_SENDS_LOW_STOCK_ALERT_BEFORE_STOCKOUT", "SYSTEM_DOES_NOT_SEND_LOW_STOCK_ALERT_BEFORE_STOCKOUT", ["storeroom system", "low-stock alert"]),
      p("P1", "EARLY_LOW_STOCK_ALERT_CAN_TRIGGER_REPLENISHMENT_BEFORE_STOCKOUT", "EARLY_LOW_STOCK_ALERT_CANNOT_TRIGGER_REPLENISHMENT_BEFORE_STOCKOUT", ["low-stock alert", "replenishment"]),
      p("P2", "ALL_WORK_INTERRUPTION_IS_CAUSED_BY_STOCKOUTS", "NOT_ALL_WORK_INTERRUPTION_IS_CAUSED_BY_STOCKOUTS", ["work interruptions", "stockouts"], "ALL"),
      p("P3", "LOW_STOCK_ALERTS_ARE_BEST_INVENTORY_METHOD", "LOW_STOCK_ALERTS_ARE_NOT_BEST_INVENTORY_METHOD", ["low-stock alerts", "inventory method"]),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["PREDICT_FEWER_SUPPLY_STOCKOUT_INTERRUPIONS"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["An early low-stock alert can lead to replenishment before supplies run out.", "Low-stock alerts can enable staff to restock essential supplies before a stockout occurs."], "IMPLICIT", "The expected reduction in stockout interruptions requires the alert to create an opportunity for replenishment before supplies are exhausted."),
      c("C2", "P2", ["Every work interruption is caused by a supply stockout.", "Stockouts are the cause of all work interruptions."], "NOT_IMPLICIT", "The prediction concerns one category of interruption and does not require stockouts to explain every interruption.", "TOO_STRONG_QUANTIFIER"),
      c("C3", "P3", ["Low-stock alerts are the best possible inventory-control method.", "No inventory-control method is better than a low-stock alert system."], "NOT_IMPLICIT", "The prediction does not require a value judgement that this is the best possible inventory method.", "VALUE_JUDGEMENT_NOT_REQUIRED"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Medium",
    sourceStatus: SOURCE_SUPPORTED,
  },
  {
    scenarioId: "STA-EN2-QL004-COUNTER-DIRECTION-DISPLAY",
    corpusFamilyId: "QL004-DIRECTION-TO-WRONG-COUNTER-REDUCTION",
    domain: "PUBLIC_SERVICE",
    semanticShape: "EXPLICIT_PREMISE_PLUS_HIDDEN_BRIDGE",
    corpusStatus: CORPUS_CANDIDATE,
    proposedQlId: "STA-QL-004",
    checkpointId: "STA-CP-002",
    sourceProfile: "SSC",
    discourseAct: "ASSERTION",
    objectiveIds: ["CLAIM_DIRECTION_DISPLAY_REDUCES_WRONG_COUNTER_APPROACHES"],
    statementVariants: [
      "A large display now shows which counter handles each service, so fewer visitors should approach the wrong counter.",
      "Counter-to-service directions are now shown on a large display; the centre expects fewer wrong-counter enquiries.",
    ],
    propositions: [
      p("P0", "DISPLAY_SHOWS_COUNTER_FOR_EACH_SERVICE", "DISPLAY_DOES_NOT_SHOW_COUNTER_FOR_EACH_SERVICE", ["display", "counters", "services"]),
      p("P1", "CLEAR_COUNTER_INFORMATION_CAN_HELP_VISITOR_CHOOSE_CORRECT_COUNTER", "CLEAR_COUNTER_INFORMATION_CANNOT_HELP_VISITOR_CHOOSE_CORRECT_COUNTER", ["counter information", "visitor"]),
      p("P2", "DISPLAY_ITSELF_IS_ALREADY_STATED", "DISPLAY_ITSELF_IS_NOT_ALREADY_STATED", ["display"]),
      p("P3", "ALL_VISITORS_CAN_READ_EVERY_LANGUAGE", "NOT_ALL_VISITORS_CAN_READ_EVERY_LANGUAGE", ["visitors", "languages"], "ALL"),
    ],
    explicitPropositionIds: ["P0"],
    hiddenDependencies: [d("D1", "P1", "EFFICACY", ["CLAIM_DIRECTION_DISPLAY_REDUCES_WRONG_COUNTER_APPROACHES"], "BREAKS_RATIONALE")],
    candidates: [
      c("C1", "P1", ["Clear counter information can help visitors choose the correct counter.", "Showing which counter handles each service can reduce mistakes in choosing a counter."], "IMPLICIT", "The claim requires the displayed directions to be capable of changing at least some visitors' counter choices."),
      c("C2", "P0", ["A large display shows which counter handles each service.", "Counter-to-service directions are shown on the display."], "NOT_IMPLICIT", "The presence and content of the display are already stated directly, so this is not an unstated assumption.", "EXPLICIT_RESTATEMENT"),
      c("C3", "P3", ["Every visitor can read every language.", "All visitors understand every language used anywhere."], "NOT_IMPLICIT", "The claim does not require universal language ability; the display only needs to help enough visitors for wrong-counter approaches to decline.", "TOO_STRONG_QUANTIFIER"),
    ],
    allowedCandidateCounts: [2, 3],
    difficulty: "Hard",
    sourceStatus: SOURCE_SUPPORTED,
  },
] as const satisfies readonly StaEnglishCorpusScenario[];
