import type { PolCp025SeedRow } from "./pol-cp025-types";

const U=["CONSTITUTION-PART-VIII-2025"] as const;
const S=["CONSTITUTION-PART-XXI-2025"] as const;
const A=["CONSTITUTION-AMENDMENT-FOOTNOTES-2025"] as const;

export const POL_CP025_PART_3: readonly PolCp025SeedRow[] = [
["POL-025-QL-011","Medium","The President's regulation-making power under Article 240 applies to which of the following Union Territories?","Andaman and Nicobar Islands","Delhi","Chandigarh","Jammu and Kashmir","Article 240 expressly includes the Andaman and Nicobar Islands among territories for which the President may make specified regulations.",U],
["POL-025-QL-011","Medium","Which of the following Union Territories is also covered by Article 240?","Lakshadweep","Delhi","Chandigarh","Ladakh only","Lakshadweep is expressly listed in Article 240 among the Union Territories covered by the President's regulation-making power.",U],
["POL-025-QL-011","Medium","Which merged Union Territory is presently included in the list under Article 240?","Dadra and Nagar Haveli and Daman and Diu","Delhi and Chandigarh","Jammu and Kashmir and Ladakh","Puducherry and Lakshadweep","Article 240 names the merged Union Territory of Dadra and Nagar Haveli and Daman and Diu.",U],
["POL-025-QL-011","Medium","Once Puducherry's Legislature begins functioning, what is the normal position regarding the President's Article 240 regulation power?","It does not operate from the first meeting of that Legislature","It becomes unlimited","It transfers to the Supreme Court","It converts into ordinance power","Article 240 generally pauses that presidential regulation power once Puducherry's Legislature begins functioning, subject to the dissolution or suspension proviso.",U],

["POL-025-QL-012","Medium","Under Article 241, a High Court for a Union Territory may be constituted by whom?","Parliament by law","President by ordinance alone","Chief Justice of India alone","Administrator by notification","Article 241 empowers Parliament by law to constitute a High Court for a Union Territory or declare a court to be such a High Court.",U],
["POL-025-QL-012","Medium","Under Article 241, may Parliament declare an existing court to be a High Court for a Union Territory?","Yes","No","Only during Emergency","Only after State ratification","Article 241 expressly allows Parliament to declare an existing court to be a High Court for a Union Territory.",U],
["POL-025-QL-012","Medium","Which Article correctly corresponds to the general administration of Union Territories?","Article 239—Union Territory administration","Article 240—Delhi Assembly","Article 241—official language","Article 239AA—Fifth Schedule areas","Article 239 establishes the general framework for Union Territory administration through the President and an appointed administrator.",U],
["POL-025-QL-012","Medium","Which Article correctly corresponds to High Courts for Union Territories?","Article 241—High Courts for Union Territories","Article 239B—Finance Commission","Article 240—Election Commission","Article 239AB—official language","Article 241 concerns High Courts for Union Territories, while nearby provisions deal with administration, ordinances and regulations.",U],

["POL-025-QL-013","Medium","The special responsibilities provided under Article 371 relate to which two States?","Maharashtra and Gujarat","Nagaland and Mizoram","Assam and Manipur","Goa and Karnataka","Article 371 authorises special responsibilities of the Governor in relation to specified regions of Maharashtra and Gujarat.",S],
["POL-025-QL-013","Medium","Article 371 specifically provides separate development-board arrangements for which Maharashtra regions?","Vidarbha and Marathwada","Konkan and Khandesh only","Mumbai and Pune only","Nagpur and Nashik only","Article 371 mentions separate development boards for Vidarbha, Marathwada and the rest of Maharashtra.",S],
["POL-025-QL-013","Medium","Which Gujarat regions are specifically named in the development-board framework under Article 371?","Saurashtra and Kutch","Ahmedabad and Surat","Vadodara and Bharuch","North Gujarat and South Gujarat only","Article 371 specifically mentions Saurashtra, Kutch and the rest of Gujarat in its development-board framework.",S],
["POL-025-QL-013","Medium","Besides equitable development funding, Article 371 also seeks equitable arrangements in which area?","Technical education, vocational training and State employment opportunities","Supreme Court appointments","Union defence recruitment only","Election Commission membership","Article 371 also addresses equitable facilities for technical and vocational education and opportunities in services under the State Government.",S],

["POL-025-QL-014","Medium","Article 371A contains special constitutional protections for which State?","Nagaland","Mizoram","Manipur","Sikkim","Article 371A contains special provisions for Nagaland, including protection for specified Naga social, legal and land matters.",S],
["POL-025-QL-014","Medium","A Parliamentary law on which subject does not automatically apply to Nagaland unless its Assembly so resolves?","Naga customary law and procedure","Currency and coinage","Citizenship","Inter-State trade generally","Article 371A protects Naga customary law and procedure from automatic application of Parliamentary Acts unless the State Assembly resolves otherwise.",S],
["POL-025-QL-014","Medium","Which land-related matter receives special protection under Article 371A?","Ownership and transfer of land and its resources","Union customs duties","Railway fares","Foreign exchange","Article 371A includes ownership and transfer of land and its resources among the subjects requiring a Nagaland Assembly resolution.",S],
["POL-025-QL-014","Medium","Article 371A was inserted by which Constitutional Amendment?","Thirteenth Amendment","Twenty-seventh Amendment","Fifty-third Amendment","Ninety-eighth Amendment","The Constitution (Thirteenth Amendment) Act, 1962 inserted Article 371A for Nagaland as a special provision.",A],

["POL-025-QL-015","Medium","Article 371B contains a special constitutional arrangement for which State?","Assam","Manipur","Nagaland","Sikkim","Article 371B permits a special committee arrangement within the Assam Legislative Assembly for specified tribal-area representation.",S],
["POL-025-QL-015","Medium","The special Legislative Assembly committee under Article 371C is connected with which areas of Manipur?","Hill Areas","Coastal Areas","Capital Region","Border Districts only","Article 371C allows a committee of Manipur Assembly members elected from the Hill Areas to be constitutionally provided for.",S],
["POL-025-QL-015","Medium","Under Article 371C, how often must Manipur's Governor report on the administration of the Hill Areas?","Annually or whenever required by the President","Every five years only","Monthly","Only once after appointment","Article 371C requires an annual report to the President and also a report whenever the President requires one.",S],
["POL-025-QL-015","Medium","For the purposes of Article 371C, Hill Areas may be declared by whom?","President by order","Governor alone","Parliamentary committee","Election Commission","The explanation to Article 371C defines Hill Areas as areas that the President may declare by order.",S],
];
