import type { PolCp025SeedRow } from "./pol-cp025-types";

const U=["CONSTITUTION-PART-VIII-2025"] as const;

export const POL_CP025_PART_2: readonly PolCp025SeedRow[] = [
["POL-025-QL-006","Easy","Which Article deals with failure of constitutional machinery in Delhi?","Article 239AB","Article 239B","Article 240","Article 241","Article 239AB deals with situations where Delhi's administration cannot be carried on according to Article 239AA or related law.",U],
["POL-025-QL-006","Easy","Which Article gives an administrator ordinance-making power during a Union Territory Legislature's recess?","Article 239B","Article 239AA","Article 240","Article 241","Article 239B provides ordinance-making power to the administrator of the relevant Union Territory during a legislative recess.",U],
["POL-025-QL-006","Easy","Which Article empowers the President to make regulations for certain Union Territories?","Article 240","Article 239A","Article 241","Article 371","Article 240 authorises the President to make regulations for the peace, progress and good government of specified Union Territories.",U],
["POL-025-QL-006","Easy","Which Article deals with High Courts for Union Territories?","Article 241","Article 239","Article 240","Article 371A","Article 241 authorises Parliament to constitute a High Court for a Union Territory or declare another court to be such a High Court.",U],

["POL-025-QL-007","Medium","Delhi's Assembly cannot normally legislate on which State List subject under Article 239AA?","Public order","Agriculture","Public health","Markets and fairs","Article 239AA excludes State List Entry 1, public order, from the ordinary legislative competence of Delhi's Assembly.",U],
["POL-025-QL-007","Medium","Which State List subject is excluded from Delhi Assembly's ordinary legislative power?","Police","Agriculture","Irrigation","Libraries","Police, covered by State List Entry 2, is specifically excluded from Delhi Assembly's ordinary law-making power.",U],
["POL-025-QL-007","Medium","Which State List subject is specifically excluded from Delhi Assembly's legislative competence?","Land","Fisheries","Local markets","State public services generally","Article 239AA excludes land under State List Entry 18, along with related Entries 64, 65 and 66 where applicable.",U],
["POL-025-QL-007","Medium","Who retains power to legislate for Delhi on any matter in the State or Concurrent Lists?","Parliament","Delhi Assembly exclusively","Lieutenant Governor alone","Municipal Corporation","Article 239AA preserves Parliament's power to make laws for Delhi on matters in the State List or Concurrent List.",U],

["POL-025-QL-008","Medium","If a Delhi law conflicts with a Parliamentary law on the same subject, what is the general rule?","Parliamentary law prevails","Delhi law always prevails","Both laws automatically lapse","Supreme Court chooses one before either operates","Article 239AA generally gives primacy to Parliamentary law where it conflicts with a Delhi Assembly law on the same matter.",U],
["POL-025-QL-008","Medium","Who heads Delhi's Council of Ministers under Article 239AA?","Chief Minister","Lieutenant Governor","President","Speaker of the Assembly","The Council of Ministers is headed by the Chief Minister and aids and advises the Lieutenant Governor on matters within Assembly competence.",U],
["POL-025-QL-008","Medium","If the Lieutenant Governor and Delhi Ministers differ on a matter, to whom may it be referred?","President","Chief Justice of India","Speaker of Lok Sabha","Election Commission","Article 239AA permits the Lieutenant Governor to refer a difference of opinion with Ministers to the President for decision.",U],
["POL-025-QL-008","Medium","Pending a presidential decision on an urgent Delhi matter, what may the Lieutenant Governor do?","Take immediate action considered necessary","Dissolve Parliament","Amend the Constitution","Remove Supreme Court judges","Article 239AA permits urgent interim action by the Lieutenant Governor while a referred difference awaits the President's decision.",U],

["POL-025-QL-009","Medium","Under Article 239AB, who may suspend provisions of Article 239AA in specified circumstances?","President","Lieutenant Governor alone","Parliamentary Speaker","Supreme Court","Article 239AB empowers the President to suspend specified provisions when Delhi's administration cannot function under the constitutional framework.",U],
["POL-025-QL-009","Medium","A report from which authority may trigger consideration under Article 239AB?","Lieutenant Governor","Chief Election Commissioner","Comptroller and Auditor General","Attorney-General for India","Article 239AB expressly contemplates the President acting on a report from the Lieutenant Governor or otherwise.",U],
["POL-025-QL-009","Medium","Article 239AB applies when administration of which territory cannot follow Article 239AA?","National Capital Territory of Delhi","Puducherry","Lakshadweep","Chandigarh","Article 239AB is tied specifically to failure of the constitutional machinery created for the National Capital Territory under Article 239AA.",U],
["POL-025-QL-009","Medium","Which provision is the closest Union Territory counterpart to a constitutional-machinery failure clause for Delhi?","Article 239AB","Article 240","Article 241","Article 371C","Article 239AB is Delhi's specific constitutional provision for breakdown or impracticability of administration under the Article 239AA framework.",U],

["POL-025-QL-010","Medium","When may an administrator promulgate an Ordinance under Article 239B?","When the relevant Legislature is not in session and immediate action is necessary","Whenever Parliament is in session","Only during a National Emergency","Only after a Supreme Court order","Article 239B operates during a recess of the relevant Union Territory Legislature when circumstances require immediate action.",U],
["POL-025-QL-010","Medium","Whose instructions must generally be obtained before an Ordinance is promulgated under Article 239B?","President","Prime Minister personally","Chief Justice of India","Governor of a neighbouring State","Article 239B requires the administrator to obtain instructions from the President before promulgating an Ordinance.",U],
["POL-025-QL-010","Medium","An Ordinance under Article 239B has broadly the same force as what?","An Act of the Union Territory Legislature assented to by the President","A constitutional amendment","A Supreme Court judgment","A municipal by-law","Article 239B gives a valid Ordinance the same force and effect as an Act of the local Legislature duly assented to by the President.",U],
["POL-025-QL-010","Medium","Can an Article 239B Ordinance validly contain a provision the local Legislature could not enact?","No","Yes, without limit","Yes, if the administrator prefers","Yes, if Parliament is adjourned","Article 239B does not allow the Ordinance power to exceed the legislative competence available under the governing Union Territory law.",U],
];
