import type{Eng009Cp004PassageV1}from"./eng-009-cp004-authorities-v1";
export const ENG009_CP004_BREADTH_WAVE1:readonly Eng009Cp004PassageV1[]=[
{id:"ENG009-BM-C11",title:"The Risk of Supplier Concentration",topic:"supply chains",template:`Companies often reduce the number of suppliers they use because larger orders can improve bargaining power and simplify quality control. Yet concentration can create hidden risk. If one supplier provides a large share of a critical component, a disruption at that firm can affect the buyer far more than its share of spending suggests. The important question is not only how much a company buys from a supplier, but how difficult that supply would be to replace. A low-cost component can still be critical if no alternative producer can meet the same specification quickly. Good supply-chain analysis therefore examines dependency as well as price. Managers need to know which inputs have substitutes, how long qualification of a new supplier would take and whether several suppliers depend on the same upstream source. Two apparently independent vendors may rely on the same factory, port or raw-material producer. Visible diversification can therefore hide common exposure.

Companies can reduce concentration risk by qualifying backup suppliers, redesigning products to accept more standard components or holding strategic inventory for hard-to-replace items. Each option has a cost. The aim is not maximum diversification but protection where failure would have the greatest __(1)__. Managers should compare the cost of protection with the likely cost of disruption. They should also avoid assuming that past reliability guarantees future supply. A supplier with an excellent record may still face a new financial, geographic or regulatory problem. Risk maps therefore need to remain __(2)__.

Scenario exercises can reveal dependencies that normal purchasing reports miss. They also help identify decisions that should be made before a crisis. Preparation matters because switching suppliers during disruption is usually harder and more expensive than preparing beforehand. The strongest programmes therefore protect the points where interruption would be hardest to absorb. This makes resilience spending more __(3)__ and avoids treating every supplier as equally important.

Supplier concentration is not automatically bad. It becomes dangerous when dependence is high and alternatives are weak. Measuring importance, substitutability and recovery time allows managers to make a more __(4)__ trade-off between efficiency and resilience. Backup capacity is easier to justify when it is linked to a specific risk. Such capacity preserves the ability to __(5)__ when conditions change. A supply chain is strongest when it can continue operating even when one path is __(6)__.`,blanks:[
{id:"C11-B1",blankNo:1,difficulty:"hard",kind:"context",answer:"impact",distractors:["cost","volume","change"],explanation:"Diversification should focus where failure would matter most. 'Impact' fits.",clue:"greatest ..."},
{id:"C11-B2",blankNo:2,difficulty:"medium",kind:"vocabulary",answer:"current",distractors:["formal","visible","stable"],explanation:"Risk maps need to reflect present conditions, so they must remain current.",clue:"remain ..."},
{id:"C11-B3",blankNo:3,difficulty:"hard",kind:"phrase-fit",answer:"targeted",distractors:["general","uniform","automatic"],explanation:"Protection should focus on the highest-risk points. 'Targeted' fits.",clue:"spending more ..."},
{id:"C11-B4",blankNo:4,difficulty:"hard",kind:"logic-link",answer:"informed",distractors:["simple","quick","fixed"],explanation:"Measuring the key factors allows a better-informed trade-off.",clue:"more ... trade-off"},
{id:"C11-B5",blankNo:5,difficulty:"medium",kind:"collocation",answer:"adapt",distractors:["pause","wait","remain"],explanation:"Options give the company the ability to adapt when conditions change.",clue:"ability to ..."},
{id:"C11-B6",blankNo:6,difficulty:"hard",kind:"discourse",answer:"blocked",distractors:["visible","tested","priced"],explanation:"The point is continuing when one supply route becomes unavailable.",clue:"one path is ..."}]},
{id:"ENG009-BM-C12",title:"Why Climate Risk Enters Lending Decisions",topic:"financial risk",template:`Banks usually evaluate borrowers by looking at income, assets, debt and repayment history. Increasingly, they also consider whether physical or economic changes linked to climate could affect future cash flow. A business in an area exposed to repeated flooding may face higher repair costs or periods when operations stop. A company dependent on a fuel or technology facing tighter regulation may face a different pressure. For lenders, the important question is how such changes could affect repayment over the life of the loan.

Because long-term outcomes are uncertain, banks often use scenarios rather than one precise forecast. A scenario might test what happens if insurance costs rise, a facility is disrupted or demand shifts away from a product. The purpose is not to predict exactly but to identify where the loan is most __(1)__. However, exposure alone is not enough. A borrower may also have adaptation measures, diversified operations or enough financial strength to absorb losses. Good analysis therefore considers vulnerability and capacity together. Broad sector labels can help with screening, but final decisions need more specific evidence. This makes the process more __(2)__.

Time horizon also matters. A short-term loan may be less affected by a slowly growing risk than a long-term project loan. The analysis should therefore match the duration and structure of the exposure. Climate information becomes useful when it is connected to the same financial question as other credit risks: could the factor materially affect repayment? If the answer is unclear, assumptions and ranges should be shown openly. This makes the analysis more __(3)__ and avoids false precision.

Banks should also revise their methods as better evidence appears. A framework designed today should not be assumed to remain perfect. A mature system combines consistency with the willingness to __(4)__. The aim is to make uncertainty manageable, not to pretend it has disappeared. When climate information is connected clearly to repayment risk, lending analysis can become more forward-looking without becoming less __(5)__. The purpose is to improve judgment, not replace it with a checklist. A new risk factor should therefore inform a credit decision without becoming an automatic reason to __(6)__ credit.`,blanks:[
{id:"C12-B1",blankNo:1,difficulty:"hard",kind:"vocabulary",answer:"vulnerable",distractors:["weak","sensitive","exposed"],explanation:"The scenario is used to find where repayment is most vulnerable to change.",clue:"loan is most ..."},
{id:"C12-B2",blankNo:2,difficulty:"medium",kind:"context",answer:"granular",distractors:["large","uniform","general"],explanation:"More specific evidence makes analysis more detailed or granular.",clue:"more specific evidence"},
{id:"C12-B3",blankNo:3,difficulty:"hard",kind:"phrase-fit",answer:"transparent",distractors:["accurate","certain","simple"],explanation:"Showing assumptions and ranges makes the analysis easier to understand.",clue:"assumptions and ranges ... openly"},
{id:"C12-B4",blankNo:4,difficulty:"hard",kind:"logic-link",answer:"adapt",distractors:["pause","repeat","remain"],explanation:"Methods should change when better evidence appears, so 'adapt' fits.",clue:"better evidence appears"},
{id:"C12-B5",blankNo:5,difficulty:"medium",kind:"collocation",answer:"disciplined",distractors:["strict","formal","narrow"],explanation:"The analysis should remain financially disciplined even as it becomes forward-looking.",clue:"without becoming less ..."},
{id:"C12-B6",blankNo:6,difficulty:"hard",kind:"discourse",answer:"deny",distractors:["price","review","study"],explanation:"A new risk factor should not automatically mean refusing credit. 'Deny' fits.",clue:"reason to ... credit"}]}
];