import type{Eng009Cp004PassageV1}from"./eng-009-cp004-authorities-v1";
export const ENG009_CP004_BREADTH_WAVE2:readonly Eng009Cp004PassageV1[]=[
{id:"ENG009-BM-C13",title:"Why Deposit Competition Matters",topic:"banking competition",template:`Banks compete not only for borrowers but also for deposits. Deposits provide a relatively stable source of funding, and the price banks pay for them can affect the cost of lending. When competition for deposits rises, banks may offer higher interest rates or better account features to attract customers. This can benefit savers, but it can also increase funding costs for banks. A bank that raises deposit rates aggressively may gain balances quickly, yet the strategy is sustainable only if the higher cost can be recovered through lending income or other revenue. Deposit competition therefore creates a trade-off between growth and margin.

The quality of deposits also matters. Some deposits remain in accounts for long periods, while others move quickly in response to small rate changes. A bank that attracts only highly rate-sensitive money may face greater outflows when another institution offers a better return. Funding that appears abundant today may therefore be less __(1)__ than it seems. Banks monitor the behaviour of different customer groups to understand this risk. Retail deposits are often viewed differently from large institutional balances because their withdrawal patterns may differ.

Pricing decisions also affect customer relationships. A bank that offers attractive rates only to new customers may gain accounts but frustrate existing customers if they feel overlooked. On the other hand, matching every competitor's rate can damage profitability. Banks therefore need a pricing framework that considers funding needs, customer behaviour and market conditions together. The goal is not simply to offer the highest rate but to attract funding at a cost that remains __(2)__.

Deposit competition becomes especially important when market interest rates change quickly. Customers may begin moving money from low-interest accounts into term deposits or other investments. Banks that respond too slowly can lose funding, while those that respond too aggressively may lock themselves into expensive liabilities. Good asset-liability management therefore considers both the amount and the repricing speed of deposits. This helps the bank understand how quickly its funding cost could rise.

Technology has also made switching easier. Customers can compare rates online and move money with less effort than in the past. This may make some deposit categories more sensitive to price. At the same time, customers still value convenience, trust and service quality. Rate is important, but it is not the only factor. Banks that understand this can compete on a broader set of benefits rather than relying only on price. This can make funding relationships more __(3)__.

The wider lesson is that deposits are not simply passive balances. They are part of a bank's funding strategy and respond to competition, customer preferences and interest-rate conditions. A strong bank monitors how stable its funding really is and avoids assuming that all deposits behave the same way. It also considers what might happen if competitors change rates or market confidence weakens. Stress testing can reveal how much funding might leave under different scenarios. This makes liquidity planning more __(4)__.

Healthy competition can improve returns for savers and encourage better service, but it also requires discipline from banks. Chasing deposits at any price can weaken margins and create future repricing problems. Ignoring competition can leave the bank underfunded. The best strategy therefore balances cost, stability and customer value. It treats deposit pricing as a dynamic decision rather than a fixed rule. In this sense, the bank is not merely buying money; it is managing a relationship between funding cost and funding __(5)__. That relationship becomes especially important when conditions change quickly. Banks that understand it are better able to grow without making their funding structure too __(6)__.`,blanks:[
{id:"C13-B1",blankNo:1,difficulty:"hard",kind:"vocabulary",answer:"stable",distractors:["large","cheap","visible"],explanation:"Rate-sensitive deposits may leave quickly, so they may be less stable than they appear.",clue:"funding ... less ..."},
{id:"C13-B2",blankNo:2,difficulty:"medium",kind:"context",answer:"sustainable",distractors:["simple","fixed","rapid"],explanation:"The funding cost must remain manageable over time, so 'sustainable' fits.",clue:"cost that remains ..."},
{id:"C13-B3",blankNo:3,difficulty:"hard",kind:"phrase-fit",answer:"durable",distractors:["short","formal","uniform"],explanation:"Competing on trust and service can create longer-lasting funding relationships.",clue:"relationships more ..."},
{id:"C13-B4",blankNo:4,difficulty:"hard",kind:"logic-link",answer:"robust",distractors:["narrow","quick","simple"],explanation:"Stress testing makes liquidity planning better able to handle shocks. 'Robust' fits.",clue:"planning more ..."},
{id:"C13-B5",blankNo:5,difficulty:"medium",kind:"collocation",answer:"stability",distractors:["volume","shape","speed"],explanation:"Deposit strategy balances funding cost with funding stability.",clue:"funding cost and funding ..."},
{id:"C13-B6",blankNo:6,difficulty:"hard",kind:"discourse",answer:"fragile",distractors:["expensive","large","complex"],explanation:"Poorly managed funding can become too fragile when conditions change.",clue:"structure too ..."}]},
{id:"ENG009-BM-C14",title:"The Risks of Dynamic Pricing",topic:"pricing strategy",template:`Dynamic pricing allows a business to change prices in response to demand, capacity or timing. Airlines and hotels have used such systems for years, and digital platforms have made the approach common in other industries. The economic logic is straightforward: when demand is high and capacity is limited, a higher price can help allocate scarce supply. When demand is weak, lower prices can attract more customers. Yet the same flexibility that improves revenue can also create fairness concerns.

Customers often accept price differences when they understand the reason. A hotel room costing more during a major event may feel predictable. The reaction can be very different when two customers appear to receive different prices at the same moment without explanation. This is why transparency matters. A pricing system that is technically efficient but difficult to explain may weaken trust. The business therefore needs to consider not only whether a price maximises revenue, but whether the rule behind it is __(1)__ to customers.

Data quality is another risk. Dynamic systems may use demand forecasts, competitor prices and inventory levels. If these inputs are wrong, prices can move in the wrong direction. Automated systems can also react too strongly to temporary signals. A short spike in demand may trigger a large increase even when the underlying market has not changed. Guardrails can limit extreme movements and require human review in unusual cases. This makes the system more __(2)__.

Competitive effects also matter. If several firms use similar automated tools, prices may move rapidly in response to one another. A small change by one seller can trigger repeated adjustments across the market. Such feedback can create volatility that no individual firm intended. Companies therefore need to monitor not only their own algorithm but also the market behaviour it produces. The goal is to capture useful flexibility without allowing the system to become __(3)__.

Dynamic pricing can also create reputational risk during emergencies. Raising prices sharply when customers have few alternatives may be seen as exploitation even if demand has increased. Some firms therefore place limits on price changes during sensitive periods. These limits sacrifice some short-term revenue but may protect long-term trust. The correct rule depends on the market, but the principle is broader: pricing decisions have social as well as financial effects.

Good systems also separate experimentation from permanent policy. A firm may test different prices to learn how demand responds, but experiments should be designed carefully. If customers discover large unexplained differences, the learning benefit may be outweighed by dissatisfaction. Testing should therefore remain controlled and consistent with the brand's wider pricing promise. This keeps experimentation more __(4)__.

The strongest dynamic pricing systems combine data, constraints and judgment. They allow prices to respond to real conditions but prevent short-term signals from driving extreme outcomes. They also give managers a way to explain why prices changed. This is important because a pricing decision that cannot be defended may create more damage than the additional revenue it generates. Dynamic pricing is therefore not simply a mathematical optimisation problem. It is a governance problem as well.

The wider lesson is that flexibility creates value only when it is bounded by clear rules. Businesses need to know which variables may influence price, how far prices may move and when human intervention is required. This makes pricing both adaptive and __(5)__. A good system can respond to market conditions without surprising customers in ways that feel arbitrary. When these safeguards are missing, dynamic pricing may increase revenue in the short term while making demand less predictable in the long term. The best approach therefore uses flexibility without allowing the system to become too __(6)__.`,blanks:[
{id:"C14-B1",blankNo:1,difficulty:"hard",kind:"context",answer:"defensible",distractors:["visible","profitable","simple"],explanation:"Customers should be able to understand and justify the pricing rule. 'Defensible' fits.",clue:"rule behind it is ..."},
{id:"C14-B2",blankNo:2,difficulty:"medium",kind:"vocabulary",answer:"controlled",distractors:["rapid","broad","automatic"],explanation:"Guardrails keep price changes under control.",clue:"system more ..."},
{id:"C14-B3",blankNo:3,difficulty:"hard",kind:"logic-link",answer:"unstable",distractors:["expensive","complex","visible"],explanation:"Repeated automated reactions can make the market unstable.",clue:"system to become ..."},
{id:"C14-B4",blankNo:4,difficulty:"hard",kind:"phrase-fit",answer:"disciplined",distractors:["frequent","broad","random"],explanation:"Controlled experiments are more disciplined than uncontrolled price changes.",clue:"experimentation more ..."},
{id:"C14-B5",blankNo:5,difficulty:"medium",kind:"collocation",answer:"accountable",distractors:["formal","stable","quick"],explanation:"Clear rules make pricing easier to explain and take responsibility for.",clue:"adaptive and ..."},
{id:"C14-B6",blankNo:6,difficulty:"hard",kind:"discourse",answer:"erratic",distractors:["flexible","profitable","competitive"],explanation:"Without safeguards, price changes may become unpredictable or erratic.",clue:"too ..."}]}
];