import type { KnowledgeV1Difficulty } from "../../types";
import { ENV_CP018_FACT_BY_ID_V1 } from "./env-cp018-facts";
import type { EnvCp018ReviewQuestion } from "./env-cp018-review-types";

type Seed = {
  qlId: string;
  qlName: string;
  difficulty: KnowledgeV1Difficulty;
  stem: string;
  correct: string;
  distractors: readonly [string, string, string];
  explanation: string;
  sourceFactIds: readonly string[];
};

const S: readonly Seed[] = Object.freeze([
  { qlId:"ENV-018-QL-001", qlName:"Project Tiger basics", difficulty:"Easy", stem:"Project Tiger was launched in India in:", correct:"1973", distractors:["1969","1981","1986"], explanation:"Project Tiger was launched by the Government of India in April 1973 to strengthen tiger conservation and protect important tiger habitats.", sourceFactIds:["env-cp018-launch"] },
  { qlId:"ENV-018-QL-001", qlName:"Project Tiger basics", difficulty:"Easy", stem:"The main aim of Project Tiger is to conserve:", correct:"Tigers and their habitats", distractors:["Only zoo animals","Only wetlands","Only migratory birds"], explanation:"Project Tiger aims to maintain viable tiger populations while protecting biologically important tiger habitats and landscapes.", sourceFactIds:["env-cp018-objective"] },
  { qlId:"ENV-018-QL-001", qlName:"Project Tiger basics", difficulty:"Medium", stem:"Project Tiger is implemented as a:", correct:"Centrally Sponsored Scheme", distractors:["State-only scheme","Private conservation programme","International treaty"], explanation:"Project Tiger is an ongoing Centrally Sponsored Scheme under the Union environment ministry, with support provided to tiger range States.", sourceFactIds:["env-cp018-css"] },
  { qlId:"ENV-018-QL-001", qlName:"Project Tiger basics", difficulty:"Hard", stem:"Which approach best describes Project Tiger?", correct:"In-situ conservation in designated tiger reserves", distractors:["Captive breeding in zoos only","Ex-situ seed conservation","Trade regulation through CITES only"], explanation:"Project Tiger supports in-situ conservation, meaning tigers are conserved in their natural habitats through designated tiger reserves and landscape management.", sourceFactIds:["env-cp018-in-situ"] },

  { qlId:"ENV-018-QL-002", qlName:"Original Project Tiger reserves", difficulty:"Easy", stem:"Which was among the original Project Tiger reserves?", correct:"Bandipur", distractors:["Periyar","Buxa","Nagarjunsagar-Srisailam"], explanation:"Bandipur was one of the nine reserves in the original Project Tiger network established in the early phase of the programme.", sourceFactIds:["env-cp018-original-nine"] },
  { qlId:"ENV-018-QL-002", qlName:"Original Project Tiger reserves", difficulty:"Easy", stem:"Which reserve was part of the original Project Tiger network?", correct:"Kanha", distractors:["Sariska","Periyar","Indravati"], explanation:"Kanha was among the original nine Project Tiger reserves, together with reserves such as Corbett, Manas and Ranthambore.", sourceFactIds:["env-cp018-original-nine"] },
  { qlId:"ENV-018-QL-002", qlName:"Original Project Tiger reserves", difficulty:"Medium", stem:"Which set contains only original Project Tiger reserves?", correct:"Corbett, Manas, Melghat", distractors:["Periyar, Buxa, Sariska","Indravati, Periyar, Bandipur","Buxa, Kanha, Sariska"], explanation:"Corbett, Manas and Melghat were all part of the original nine-reserve Project Tiger network launched in 1973.", sourceFactIds:["env-cp018-original-nine"] },
  { qlId:"ENV-018-QL-002", qlName:"Original Project Tiger reserves", difficulty:"Hard", stem:"Which was NOT among the original nine Project Tiger reserves?", correct:"Periyar", distractors:["Palamau","Similipal","Sundarban"], explanation:"Palamau, Similipal and Sundarban were among the original nine. Periyar joined Project Tiger later.", sourceFactIds:["env-cp018-original-nine"] },

  { qlId:"ENV-018-QL-003", qlName:"Tiger reserve–state matching", difficulty:"Easy", stem:"Bandipur Tiger Reserve is in:", correct:"Karnataka", distractors:["Kerala","Madhya Pradesh","Rajasthan"], explanation:"Bandipur Tiger Reserve is in Karnataka and was one of the original reserves under Project Tiger.", sourceFactIds:["env-cp018-bandipur"] },
  { qlId:"ENV-018-QL-003", qlName:"Tiger reserve–state matching", difficulty:"Easy", stem:"Manas Tiger Reserve is in:", correct:"Assam", distractors:["Odisha","Jharkhand","West Bengal"], explanation:"Manas Tiger Reserve is in Assam and formed part of the original Project Tiger network.", sourceFactIds:["env-cp018-manas"] },
  { qlId:"ENV-018-QL-003", qlName:"Tiger reserve–state matching", difficulty:"Medium", stem:"Which pair is correctly matched?", correct:"Melghat — Maharashtra", distractors:["Kanha — Rajasthan","Palamau — Odisha","Ranthambore — Madhya Pradesh"], explanation:"Melghat Tiger Reserve is in Maharashtra. Kanha is in Madhya Pradesh, Palamau in Jharkhand and Ranthambore in Rajasthan.", sourceFactIds:["env-cp018-melghat","env-cp018-kanha","env-cp018-palamau","env-cp018-ranthambore"] },
  { qlId:"ENV-018-QL-003", qlName:"Tiger reserve–state matching", difficulty:"Hard", stem:"Which set is fully correct?", correct:"Similipal—Odisha; Sundarban—West Bengal", distractors:["Corbett—Rajasthan; Kanha—Maharashtra","Palamau—Assam; Manas—Jharkhand","Ranthambore—Gujarat; Bandipur—Kerala"], explanation:"Similipal is in Odisha and Sundarban is in West Bengal. The other pairs mix up the states of major tiger reserves.", sourceFactIds:["env-cp018-similipal","env-cp018-sundarban"] },

  { qlId:"ENV-018-QL-004", qlName:"Core and buffer strategy", difficulty:"Easy", stem:"Tiger reserves are mainly organized into:", correct:"Core and buffer areas", distractors:["Urban and rural zones","East and west zones","Wet and dry zones"], explanation:"Project Tiger uses a core-buffer strategy so that strict conservation and surrounding multiple-use management can be handled differently.", sourceFactIds:["env-cp018-core-buffer"] },
  { qlId:"ENV-018-QL-004", qlName:"Core and buffer strategy", difficulty:"Easy", stem:"The core area of a tiger reserve generally has the legal status of a:", correct:"National park or wildlife sanctuary", distractors:["Municipal forest","Revenue village only","Biosphere reserve only"], explanation:"The core area has the legal status of a national park or wildlife sanctuary, giving it a strong protected-area basis.", sourceFactIds:["env-cp018-core-status"] },
  { qlId:"ENV-018-QL-004", qlName:"Core and buffer strategy", difficulty:"Medium", stem:"Which best describes the buffer of a tiger reserve?", correct:"A multiple-use area around the core", distractors:["An area with no human activity at all","A zoo-based breeding zone","An international trade-control zone"], explanation:"The buffer or peripheral area can include forest and non-forest land and is managed as a multiple-use landscape around the core.", sourceFactIds:["env-cp018-buffer-character"] },
  { qlId:"ENV-018-QL-004", qlName:"Core and buffer strategy", difficulty:"Hard", stem:"Which distinction between core and buffer is correct?", correct:"Core emphasizes tiger protection; buffer uses a more people-oriented approach", distractors:["Core is for trade; buffer is for zoos","Core has no conservation role; buffer has all protection","Both must be managed identically"], explanation:"Project Tiger emphasizes an exclusive tiger-conservation agenda in the core while using a more inclusive people-oriented approach in the buffer.", sourceFactIds:["env-cp018-core-agenda","env-cp018-buffer-agenda"] },

  { qlId:"ENV-018-QL-005", qlName:"NTCA and Project Tiger", difficulty:"Easy", stem:"Which body gives statutory authority to Project Tiger?", correct:"National Tiger Conservation Authority", distractors:["Central Zoo Authority","Forest Survey of India","National Biodiversity Authority"], explanation:"NTCA provides the statutory authority and national oversight framework for Project Tiger and tiger-reserve management.", sourceFactIds:["env-cp018-ntca-statutory"] },
  { qlId:"ENV-018-QL-005", qlName:"NTCA and Project Tiger", difficulty:"Easy", stem:"NTCA works under the framework of the:", correct:"Wild Life (Protection) Act, 1972", distractors:["Water Act, 1974","Air Act, 1981","Biological Diversity Act, 2002"], explanation:"NTCA's statutory role for tiger conservation is anchored in the Wild Life (Protection) Act framework.", sourceFactIds:["env-cp018-ntca-statutory"] },
  { qlId:"ENV-018-QL-005", qlName:"NTCA and Project Tiger", difficulty:"Medium", stem:"Which function belongs to NTCA?", correct:"Approving Tiger Conservation Plans", distractors:["Recognizing all zoos","Preparing the India State of Forest Report","Regulating international wildlife trade"], explanation:"State Governments prepare Tiger Conservation Plans for tiger reserves, and NTCA has the statutory function of approving them.", sourceFactIds:["env-cp018-tcp"] },
  { qlId:"ENV-018-QL-005", qlName:"NTCA and Project Tiger", difficulty:"Hard", stem:"Which activity can NTCA restrict within tiger reserves on ecological grounds?", correct:"Ecologically unsustainable mining or industry", distractors:["All scientific monitoring","All anti-poaching patrols","All habitat improvement"], explanation:"NTCA may assess ecological sustainability and disallow land uses such as mining or industry when they are ecologically unsustainable within tiger reserves.", sourceFactIds:["env-cp018-unsustainable-use"] },

  { qlId:"ENV-018-QL-006", qlName:"Tiger Conservation Plans", difficulty:"Easy", stem:"A Tiger Conservation Plan is prepared mainly for a:", correct:"Tiger reserve", distractors:["Ramsar site only","Zoo only","Botanical garden only"], explanation:"Tiger Conservation Plans guide conservation and management of tiger reserves and are part of the statutory Project Tiger framework.", sourceFactIds:["env-cp018-tcp"] },
  { qlId:"ENV-018-QL-006", qlName:"Tiger Conservation Plans", difficulty:"Medium", stem:"Who prepares a Tiger Conservation Plan for a tiger reserve?", correct:"State Government", distractors:["CITES Secretariat","Central Zoo Authority","Forest Survey of India"], explanation:"The State Government prepares the Tiger Conservation Plan, while NTCA reviews and approves it under the tiger-conservation framework.", sourceFactIds:["env-cp018-tcp"] },
  { qlId:"ENV-018-QL-006", qlName:"Tiger Conservation Plans", difficulty:"Medium", stem:"Tourism standards in tiger reserves are laid down mainly by the:", correct:"National Tiger Conservation Authority", distractors:["Botanical Survey of India","Zoological Survey of India","State Biodiversity Board"], explanation:"NTCA lays down normative standards and guidelines for tourism activities in the core and buffer areas of tiger reserves.", sourceFactIds:["env-cp018-tourism-guidelines"] },
  { qlId:"ENV-018-QL-006", qlName:"Tiger Conservation Plans", difficulty:"Hard", stem:"Human-wildlife conflict and coexistence around tiger landscapes fall within whose conservation role?", correct:"NTCA and tiger-reserve management", distractors:["CITES trade permitting only","Ramsar wetland listing only","CZA zoo recognition only"], explanation:"The tiger-conservation framework includes measures for conflict management and coexistence in and around tiger landscapes, not just protection inside the core.", sourceFactIds:["env-cp018-conflict"] },

  { qlId:"ENV-018-QL-007", qlName:"M-STrIPES basics", difficulty:"Easy", stem:"M-STrIPES is used mainly for management of:", correct:"Tiger reserves", distractors:["Ramsar sites","Urban forests","Botanical gardens"], explanation:"M-STrIPES is a technology-based monitoring and management platform designed specifically for tiger reserves.", sourceFactIds:["env-cp018-mstripes-purpose"] },
  { qlId:"ENV-018-QL-007", qlName:"M-STrIPES basics", difficulty:"Easy", stem:"In M-STrIPES, the letter M stands for:", correct:"Monitoring", distractors:["Migration","Mapping only","Management only"], explanation:"M-STrIPES expands to Monitoring System for Tigers: Intensive Protection and Ecological Status.", sourceFactIds:["env-cp018-mstripes-full"] },
  { qlId:"ENV-018-QL-007", qlName:"M-STrIPES basics", difficulty:"Medium", stem:"Which is a major purpose of M-STrIPES?", correct:"Supporting patrolling and ecological monitoring", distractors:["Issuing CITES trade permits","Recognizing zoos","Declaring Ramsar sites"], explanation:"M-STrIPES helps managers use field data for patrolling, ecological-status assessment and conflict management in tiger reserves.", sourceFactIds:["env-cp018-mstripes-purpose"] },
  { qlId:"ENV-018-QL-007", qlName:"M-STrIPES basics", difficulty:"Hard", stem:"Which full form of M-STrIPES is correct?", correct:"Monitoring System for Tigers: Intensive Protection and Ecological Status", distractors:["Monitoring Scheme for Tigers: International Protection and Ecological Survey","Management System for Tigers: Intensive Patrol and Environmental Status","Monitoring Service for Tigers: Indian Protection and Ecological Study"], explanation:"The official expansion is Monitoring System for Tigers: Intensive Protection and Ecological Status, reflecting both protection and ecological monitoring.", sourceFactIds:["env-cp018-mstripes-full"] },

  { qlId:"ENV-018-QL-008", qlName:"M-STrIPES tools and modules", difficulty:"Easy", stem:"Which technology is used by M-STrIPES?", correct:"GPS", distractors:["Only paper maps","Only radio collars","Only satellite television"], explanation:"M-STrIPES uses GPS and other digital tools to record patrol and ecological information with location data.", sourceFactIds:["env-cp018-mstripes-tools"] },
  { qlId:"ENV-018-QL-008", qlName:"M-STrIPES tools and modules", difficulty:"Medium", stem:"Which is one of the M-STrIPES modules?", correct:"Patrol module", distractors:["Customs module","Wetland module","Zoo licensing module"], explanation:"M-STrIPES includes patrol, ecological and conflict modules for different parts of tiger-reserve monitoring and management.", sourceFactIds:["env-cp018-mstripes-modules"] },
  { qlId:"ENV-018-QL-008", qlName:"M-STrIPES tools and modules", difficulty:"Medium", stem:"What does the M-STrIPES patrol module record?", correct:"Patrol tracks and field observations", distractors:["International treaty ratifications","Zoo recognition certificates","State forest budgets only"], explanation:"The patrol module stores spatial records of patrol tracks, crime scenes and important field observations made by frontline staff.", sourceFactIds:["env-cp018-patrol"] },
  { qlId:"ENV-018-QL-008", qlName:"M-STrIPES tools and modules", difficulty:"Hard", stem:"Which combination best describes M-STrIPES?", correct:"GPS, remote sensing, GIS and field data", distractors:["Only manual registers and paper maps","Only wildlife-trade permits","Only zoo-breeding records"], explanation:"M-STrIPES combines field data with GPS, remote sensing, GIS and analytical tools to support evidence-based tiger-reserve management.", sourceFactIds:["env-cp018-mstripes-tools"] },

  { qlId:"ENV-018-QL-009", qlName:"Tiger monitoring", difficulty:"Easy", stem:"Tiger monitoring in India commonly uses:", correct:"Camera traps", distractors:["Only aerial photographs","Only zoo records","Only trade permits"], explanation:"Modern tiger assessment combines camera traps with digital field information, GPS and analytical methods rather than relying on a single technique.", sourceFactIds:["env-cp018-monitoring-tech"] },
  { qlId:"ENV-018-QL-009", qlName:"Tiger monitoring", difficulty:"Medium", stem:"The national tiger assessment is carried out broadly on a:", correct:"Four-year cycle", distractors:["Monthly cycle","Annual census only","Ten-year cycle only"], explanation:"NTCA and Project Tiger conduct country-level tiger, prey and habitat assessment on a four-year cycle using standardized scientific methods.", sourceFactIds:["env-cp018-assessment-cycle"] },
  { qlId:"ENV-018-QL-009", qlName:"Tiger monitoring", difficulty:"Medium", stem:"Why is digital field data useful in tiger assessment?", correct:"It reduces error and improves georeferenced monitoring", distractors:["It replaces all field surveys","It removes the need for camera traps","It measures only rainfall"], explanation:"Digital field collection allows observations and photo evidence to be geotagged, improving consistency and reducing avoidable recording errors.", sourceFactIds:["env-cp018-monitoring-tech"] },
  { qlId:"ENV-018-QL-009", qlName:"Tiger monitoring", difficulty:"Hard", stem:"Which statement about tiger assessment is correct?", correct:"It combines tiger, prey and habitat information", distractors:["It measures tiger numbers without habitat data","It is based only on zoo populations","It is carried out only when a new reserve is declared"], explanation:"The country-level assessment examines tigers together with prey and habitat conditions, giving managers a broader ecological picture.", sourceFactIds:["env-cp018-assessment-cycle"] },

  { qlId:"ENV-018-QL-010", qlName:"Protection and anti-poaching", difficulty:"Easy", stem:"STPF stands for a force used mainly for:", correct:"Focused anti-poaching protection", distractors:["Wetland mapping","Zoo accreditation","Plant taxonomy"], explanation:"The Special Tiger Protection Force is deployed in selected tiger reserves to strengthen focused anti-poaching protection.", sourceFactIds:["env-cp018-stpf"] },
  { qlId:"ENV-018-QL-010", qlName:"Protection and anti-poaching", difficulty:"Medium", stem:"Which system helps track patrol effort in tiger reserves?", correct:"M-STrIPES", distractors:["Ramsar List","CITES Appendix I","People's Biodiversity Register"], explanation:"M-STrIPES records patrol tracks and field observations, helping reserve managers monitor protection effort and improve anti-poaching management.", sourceFactIds:["env-cp018-patrol"] },
  { qlId:"ENV-018-QL-010", qlName:"Protection and anti-poaching", difficulty:"Medium", stem:"Which measure directly strengthens field protection in vulnerable tiger reserves?", correct:"Special Tiger Protection Force", distractors:["Ramsar designation","Zoo recognition","Botanical survey"], explanation:"STPF is designed for focused anti-poaching operations in selected tiger reserves where stronger field protection is needed.", sourceFactIds:["env-cp018-stpf"] },
  { qlId:"ENV-018-QL-010", qlName:"Protection and anti-poaching", difficulty:"Hard", stem:"Which pair is correctly matched?", correct:"STPF — anti-poaching; M-STrIPES — monitoring", distractors:["STPF — zoo recognition; M-STrIPES — wetland listing","STPF — plant taxonomy; M-STrIPES — wildlife trade","STPF — forest-cover report; M-STrIPES — biodiversity law"], explanation:"STPF strengthens anti-poaching protection, while M-STrIPES is the technology platform used for patrol and ecological monitoring in tiger reserves.", sourceFactIds:["env-cp018-stpf","env-cp018-mstripes-purpose"] },

  { qlId:"ENV-018-QL-011", qlName:"Tiger reintroduction", difficulty:"Easy", stem:"Which tiger reserve is known for tiger reintroduction?", correct:"Sariska", distractors:["Sundarban","Manas","Melghat"], explanation:"Sariska is one of India's established examples where tigers were reintroduced after the local tiger population had been lost.", sourceFactIds:["env-cp018-reintroduction"] },
  { qlId:"ENV-018-QL-011", qlName:"Tiger reintroduction", difficulty:"Easy", stem:"Panna is important in tiger conservation because of successful:", correct:"Tiger reintroduction", distractors:["Wetland designation","Zoo recognition","CITES listing"], explanation:"Panna is a major Indian example of tiger reintroduction and recovery under the national tiger-conservation programme.", sourceFactIds:["env-cp018-reintroduction"] },
  { qlId:"ENV-018-QL-011", qlName:"Tiger reintroduction", difficulty:"Medium", stem:"Which pair is linked with tiger reintroduction in India?", correct:"Sariska and Panna", distractors:["Bandipur and Manas","Melghat and Sundarban","Corbett and Kanha"], explanation:"Sariska and Panna are well-established examples of tiger reintroduction, making them important applied cases in Project Tiger history.", sourceFactIds:["env-cp018-reintroduction"] },
  { qlId:"ENV-018-QL-011", qlName:"Tiger reintroduction", difficulty:"Hard", stem:"Tiger reintroduction is best described as:", correct:"Restoring tigers to a landscape where they were locally lost", distractors:["Moving all tigers into zoos","Adding a reserve to the Ramsar List","Changing the legal name of a sanctuary"], explanation:"Reintroduction restores tigers to suitable habitat after local loss, with Sariska and Panna providing important Indian examples.", sourceFactIds:["env-cp018-reintroduction"] },

  { qlId:"ENV-018-QL-012", qlName:"Integrated Project Tiger identification", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"NTCA—oversight; M-STrIPES—monitoring; STPF—anti-poaching", distractors:["NTCA—wetland listing; M-STrIPES—trade permits; STPF—zoo regulation","NTCA—plant taxonomy; M-STrIPES—forest report; STPF—benefit sharing","NTCA—CITES permits; M-STrIPES—zoo breeding; STPF—Ramsar listing"], explanation:"NTCA provides tiger-conservation oversight, M-STrIPES supports monitoring, and STPF strengthens anti-poaching protection in selected reserves.", sourceFactIds:["env-cp018-ntca-statutory","env-cp018-mstripes-purpose","env-cp018-stpf"] },
  { qlId:"ENV-018-QL-012", qlName:"Integrated Project Tiger identification", difficulty:"Medium", stem:"Which set is correctly matched?", correct:"Corbett—Uttarakhand; Kanha—Madhya Pradesh; Manas—Assam", distractors:["Corbett—Rajasthan; Kanha—Maharashtra; Manas—Odisha","Corbett—Assam; Kanha—Jharkhand; Manas—Karnataka","Corbett—West Bengal; Kanha—Rajasthan; Manas—Gujarat"], explanation:"Corbett is in Uttarakhand, Kanha in Madhya Pradesh and Manas in Assam. All three were among the original Project Tiger reserves.", sourceFactIds:["env-cp018-corbett","env-cp018-kanha","env-cp018-manas"] },
  { qlId:"ENV-018-QL-012", qlName:"Integrated Project Tiger identification", difficulty:"Hard", stem:"Which sequence best describes tiger-reserve management?", correct:"Core protection → buffer coexistence → landscape monitoring", distractors:["Zoo breeding → wetland listing → trade permits","Forest survey → botanical taxonomy → zoo licensing","Pollution control → mercury regulation → Ramsar listing"], explanation:"Project Tiger combines strong core protection, people-oriented buffer management and broader landscape monitoring rather than relying on one isolated action.", sourceFactIds:["env-cp018-core-agenda","env-cp018-buffer-agenda","env-cp018-mstripes-purpose"] },
  { qlId:"ENV-018-QL-012", qlName:"Integrated Project Tiger identification", difficulty:"Hard", stem:"Which statement is NOT correct?", correct:"Project Tiger depends only on captive breeding in zoos", distractors:["Project Tiger supports in-situ conservation","Tiger reserves use a core-buffer strategy","NTCA approves Tiger Conservation Plans"], explanation:"Project Tiger is an in-situ conservation programme based on tiger reserves and landscape management; it is not a zoo-only captive-breeding programme.", sourceFactIds:["env-cp018-in-situ","env-cp018-core-buffer","env-cp018-tcp"] },
]);

const POSITIONS = [0, 1, 2, 3] as const;
const qlCounts = new Map<string, number>();

export const ENV_CP018_REVIEW_QUESTIONS_V1: readonly EnvCp018ReviewQuestion[] = Object.freeze(S.map((seed, index) => {
  const qlIndex = qlCounts.get(seed.qlId) ?? 0;
  qlCounts.set(seed.qlId, qlIndex + 1);
  const correctIndex = POSITIONS[qlIndex % 4];
  const options = [...seed.distractors];
  options.splice(correctIndex, 0, seed.correct);
  const sourceIds = [...new Set(seed.sourceFactIds.flatMap((id) => ENV_CP018_FACT_BY_ID_V1.get(id)?.sourceIds ?? []))];
  return {
    questionId: `ENV-CP018-V1-${String(index + 1).padStart(3, "0")}`,
    chapterId: "ENV-001",
    cpId: "ENV-CP-018",
    qlId: seed.qlId,
    qlName: seed.qlName,
    difficulty: seed.difficulty,
    stem: seed.stem,
    options,
    correctIndex,
    canonicalAnswer: seed.correct,
    explanation: seed.explanation,
    sourceIds,
    sourceFactIds: [...seed.sourceFactIds],
    reviewOnly: true,
    runtimeRegistered: false,
  };
}));
