import type { MensurationLocalizedLanguage } from "./mensuration-localization-foundation-v3";

type Pair = readonly [string, string];
type Dict = Readonly<Record<string, string>>;

const HI_PHRASES: readonly Pair[] = [
  ["How many distinct grid-plane cuts are required?", "कुल कितने अलग-अलग ग्रिड-तल कट आवश्यक हैं?"],
  ["including both curved walls and both annular ends", "दोनों वक्र पृष्ठों और दोनों वलयाकार सिरों सहित"],
  ["complete exposed surface area", "पूरा खुला पृष्ठ क्षेत्रफल"],
  ["melted together and recast into one solid sphere", "एक साथ पिघलाकर एक ठोस गोले के रूप में फिर से ढाला गया"],
  ["correct to two decimal places", "दो दशमलव स्थान तक सही"],
  ["rolled into a thinner rectangular plate", "बेलकर एक पतली आयताकार चादर बनाई गई"],
  ["Assuming no loss", "कोई पदार्थ नष्ट न होने पर"],
  ["decorative metal model consists of a cylinder surmounted by a hemisphere", "सजावटी धातु मॉडल एक बेलन से बना है, जिसके ऊपर एक अर्धगोला है"],
  ["shows a water-level rise", "जल-स्तर में वृद्धि दिखाता है"],
  ["are completely immersed", "पूरी तरह डुबोए गए हैं"],
  ["identical solid spheres", "समान ठोस गोले"],
  ["is inscribed in a sphere", "एक गोले में अंतर्लिखित है"],
  ["A sphere is inscribed in a cube", "एक गोला एक घन में अंतर्लिखित है"],
  ["hollow metallic pipe", "खोखली धातु की पाइप"],
  ["external radius", "बाहरी त्रिज्या"],
  ["bore radius", "भीतरी छेद की त्रिज्या"],
  ["volume of metal used", "प्रयुक्त धातु का आयतन"],
  ["identical solid cubes", "समान ठोस घन"],
  ["joined face to face", "पृष्ठ से पृष्ठ जोड़े गए"],
  ["straight row", "सीधी पंक्ति"],
  ["resulting solid", "बना हुआ ठोस"],
  ["coaxial inner surface", "समाक्षीय भीतरी पृष्ठ"],
  ["inner-to-outer scale", "भीतरी-बाहरी माप-गुणक"],
  ["inner curved lining cost", "भीतरी वक्र पृष्ठ की अस्तर लागत"],
  ["right square-pyramid frustum", "समकोण वर्गाकार पिरामिडीय फ्रस्टम"],
  ["lower side", "निचली भुजा"],
  ["upper side", "ऊपरी भुजा"],
  ["complete parent solid", "पूर्ण मूल ठोस"],
  ["regular-polygon frustum", "समबहुभुजीय फ्रस्टम"],
  ["base perimeters", "आधारों के परिमाप"],
  ["base areas", "आधारों के क्षेत्रफल"],
  ["in exact terms of", "के ठीक पदों में"],
  ["in terms of", "के पदों में"],
  ["minimum possible total surface area", "न्यूनतम संभव कुल पृष्ठ क्षेत्रफल"],
  ["in the same order", "उसी क्रम में"],
  ["semicircle whose diameter equals the rectangle's width", "अर्धवृत्त जिसका व्यास आयत की चौड़ाई के बराबर है"],
  ["attached externally along one shorter side", "एक छोटी भुजा के बाहर जोड़ा गया"],
  ["semicircular pieces", "अर्धवृत्ताकार टुकड़े"],
  ["shared diameter", "साझा व्यास"],
  ["is inscribed in a circle", "एक वृत्त में अंतर्लिखित है"],
  ["inside the circle but outside the square", "वृत्त के अंदर लेकिन वर्ग के बाहर"],
  ["measuring tape", "माप-फीता"],
  ["straightened and rebent", "सीधा करके फिर मोड़ा गया"],
  ["metallic wire", "धातु का तार"],
  ["rectangular frame", "आयताकार फ्रेम"],
  ["circular frame", "वृत्ताकार फ्रेम"],
  ["square frame", "वर्गाकार फ्रेम"],
  ["rectangular hall floor", "आयताकार हॉल का फर्श"],
  ["cover it completely", "इसे पूरी तरह ढकने"],
  ["uniform width", "समान चौड़ाई"],
  ["rectangular paving tiles", "आयताकार फर्श-टाइलें"],
  ["inside boundary", "भीतरी सीमा"],
  ["circular ring", "वृत्ताकार छल्ला"],
  ["complete revolutions", "पूरे चक्कर"],
  ["trapezium-shaped plot", "समलंबाकार भूखंड"],
  ["parallel sides", "समानांतर भुजाएँ"],
  ["perpendicular distance between them", "उनके बीच की लंबवत दूरी"],
  ["equilateral field", "समबाहु त्रिभुजाकार क्षेत्र"],
  ["cube-shaped storage block", "घनाकार भंडारण खंड"],
  ["cuboidal block", "घनाभाकार खंड"],
  ["internal grid plane", "भीतरी ग्रिड-तल"],
  ["grid-plane cuts", "ग्रिड-तल कट"],
  ["regular-polygon", "समबहुभुजीय"],
  ["trapezium-shaped", "समलंबाकार"],
  ["cube-shaped", "घनाकार"],
  ["water-level", "जल-स्तर"],
  ["sheet-metal", "धातु की चादर"],
  ["How many", "कितने"],
  ["How much", "कितना"],
];

const PA_PHRASES: readonly Pair[] = [
  ["How many distinct grid-plane cuts are required?", "ਕੁੱਲ ਕਿੰਨੇ ਵੱਖਰੇ ਗ੍ਰਿਡ-ਤਲ ਕੱਟ ਲੋੜੀਂਦੇ ਹਨ?"],
  ["including both curved walls and both annular ends", "ਦੋਵੇਂ ਵਕਰ ਸਤਹਾਂ ਅਤੇ ਦੋਵੇਂ ਛੱਲਾਕਾਰ ਸਿਰਿਆਂ ਸਮੇਤ"],
  ["complete exposed surface area", "ਪੂਰਾ ਖੁੱਲ੍ਹਾ ਸਤਹ ਖੇਤਰਫਲ"],
  ["melted together and recast into one solid sphere", "ਇਕੱਠੇ ਪਿਘਲਾ ਕੇ ਇੱਕ ਠੋਸ ਗੋਲੇ ਵਜੋਂ ਮੁੜ ਢਾਲਿਆ ਗਿਆ"],
  ["correct to two decimal places", "ਦੋ ਦਸ਼ਮਲਵ ਥਾਵਾਂ ਤੱਕ ਸਹੀ"],
  ["rolled into a thinner rectangular plate", "ਰੋਲ ਕਰਕੇ ਇੱਕ ਪਤਲੀ ਆਇਤਾਕਾਰ ਚਾਦਰ ਬਣਾਈ ਗਈ"],
  ["Assuming no loss", "ਕੋਈ ਪਦਾਰਥ ਨਾ ਘਟਣ ਦੀ ਸਥਿਤੀ ਵਿੱਚ"],
  ["decorative metal model consists of a cylinder surmounted by a hemisphere", "ਸਜਾਵਟੀ ਧਾਤ ਮਾਡਲ ਇੱਕ ਬੇਲਨ ਤੋਂ ਬਣਿਆ ਹੈ, ਜਿਸ ਦੇ ਉੱਪਰ ਇੱਕ ਅਰਧਗੋਲਾ ਹੈ"],
  ["shows a water-level rise", "ਪਾਣੀ ਦੇ ਪੱਧਰ ਵਿੱਚ ਵਾਧਾ ਦਿਖਾਉਂਦਾ ਹੈ"],
  ["are completely immersed", "ਪੂਰੀ ਤਰ੍ਹਾਂ ਡੁੱਬੇ ਹੋਏ ਹਨ"],
  ["identical solid spheres", "ਇੱਕੋ ਜਿਹੇ ਠੋਸ ਗੋਲੇ"],
  ["is inscribed in a sphere", "ਇੱਕ ਗੋਲੇ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ"],
  ["A sphere is inscribed in a cube", "ਇੱਕ ਗੋਲਾ ਇੱਕ ਘਣ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ"],
  ["hollow metallic pipe", "ਖੋਖਲੀ ਧਾਤ ਦੀ ਪਾਈਪ"],
  ["external radius", "ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ"],
  ["bore radius", "ਅੰਦਰਲੇ ਛੇਦ ਦਾ ਅਰਧ-ਵਿਆਸ"],
  ["volume of metal used", "ਵਰਤੀ ਧਾਤ ਦਾ ਆਇਤਨ"],
  ["identical solid cubes", "ਇੱਕੋ ਜਿਹੇ ਠੋਸ ਘਣ"],
  ["joined face to face", "ਪਾਸੇ ਨਾਲ ਪਾਸਾ ਜੋੜੇ ਗਏ"],
  ["straight row", "ਸਿੱਧੀ ਕਤਾਰ"],
  ["resulting solid", "ਬਣਿਆ ਹੋਇਆ ਠੋਸ"],
  ["coaxial inner surface", "ਸਮ-ਅਕਸੀ ਅੰਦਰਲੀ ਸਤਹ"],
  ["inner-to-outer scale", "ਅੰਦਰਲੇ-ਬਾਹਰੀ ਮਾਪ ਦਾ ਗੁਣਕ"],
  ["inner curved lining cost", "ਅੰਦਰਲੀ ਵਕਰ ਸਤਹ ਦੀ ਲਾਈਨਿੰਗ ਲਾਗਤ"],
  ["right square-pyramid frustum", "ਲੰਬ ਵਰਗ-ਆਧਾਰ ਪਿਰਾਮਿਡੀ ਫਰਸਟਮ"],
  ["lower side", "ਹੇਠਲੀ ਭੁਜਾ"],
  ["upper side", "ਉੱਪਰਲੀ ਭੁਜਾ"],
  ["complete parent solid", "ਪੂਰਾ ਮੂਲ ਠੋਸ"],
  ["regular-polygon frustum", "ਸਮ-ਬਹੁਭੁਜੀ ਫਰਸਟਮ"],
  ["base perimeters", "ਆਧਾਰਾਂ ਦੇ ਪਰਿਮਾਪ"],
  ["base areas", "ਆਧਾਰਾਂ ਦੇ ਖੇਤਰਫਲ"],
  ["in exact terms of", "ਦੇ ਠੀਕ ਪਦਾਂ ਵਿੱਚ"],
  ["in terms of", "ਦੇ ਪਦਾਂ ਵਿੱਚ"],
  ["minimum possible total surface area", "ਘੱਟੋ-ਘੱਟ ਸੰਭਵ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ"],
  ["in the same order", "ਉਸੇ ਕ੍ਰਮ ਵਿੱਚ"],
  ["semicircle whose diameter equals the rectangle's width", "ਅਰਧ-ਵ੍ਰਿਤ ਜਿਸ ਦਾ ਵਿਆਸ ਆਇਤ ਦੀ ਚੌੜਾਈ ਦੇ ਬਰਾਬਰ ਹੈ"],
  ["attached externally along one shorter side", "ਇੱਕ ਛੋਟੀ ਭੁਜਾ ਦੇ ਬਾਹਰ ਜੋੜਿਆ ਗਿਆ"],
  ["semicircular pieces", "ਅਰਧ-ਵ੍ਰਿਤਾਕਾਰ ਟੁਕੜੇ"],
  ["shared diameter", "ਸਾਂਝਾ ਵਿਆਸ"],
  ["is inscribed in a circle", "ਇੱਕ ਵ੍ਰਿਤ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ"],
  ["inside the circle but outside the square", "ਵ੍ਰਿਤ ਦੇ ਅੰਦਰ ਪਰ ਵਰਗ ਦੇ ਬਾਹਰ"],
  ["measuring tape", "ਮਾਪ-ਫੀਤਾ"],
  ["straightened and rebent", "ਸਿੱਧਾ ਕਰਕੇ ਮੁੜ ਮੋੜਿਆ ਗਿਆ"],
  ["metallic wire", "ਧਾਤ ਦੀ ਤਾਰ"],
  ["rectangular frame", "ਆਇਤਾਕਾਰ ਫਰੇਮ"],
  ["circular frame", "ਵ੍ਰਿਤਾਕਾਰ ਫਰੇਮ"],
  ["square frame", "ਵਰਗਾਕਾਰ ਫਰੇਮ"],
  ["rectangular hall floor", "ਆਇਤਾਕਾਰ ਹਾਲ ਦਾ ਫਰਸ਼"],
  ["cover it completely", "ਇਸ ਨੂੰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਢੱਕਣ"],
  ["uniform width", "ਇੱਕੋ ਚੌੜਾਈ"],
  ["rectangular paving tiles", "ਆਇਤਾਕਾਰ ਫਰਸ਼-ਟਾਈਲਾਂ"],
  ["inside boundary", "ਅੰਦਰਲੀ ਸੀਮਾ"],
  ["circular ring", "ਵ੍ਰਿਤਾਕਾਰ ਛੱਲਾ"],
  ["complete revolutions", "ਪੂਰੇ ਚੱਕਰ"],
  ["trapezium-shaped plot", "ਸਮਲੰਬਾਕਾਰ ਪਲਾਟ"],
  ["parallel sides", "ਸਮਾਂਤਰ ਭੁਜਾਵਾਂ"],
  ["perpendicular distance between them", "ਉਹਨਾਂ ਵਿਚਕਾਰ ਦੀ ਲੰਬ ਦੂਰੀ"],
  ["equilateral field", "ਸਮਭੁਜ ਤਿਕੋਣਾ ਖੇਤ"],
  ["cube-shaped storage block", "ਘਣਾਕਾਰ ਸਟੋਰੇਜ ਬਲਾਕ"],
  ["cuboidal block", "ਘਣਾਭਾਕਾਰ ਬਲਾਕ"],
  ["internal grid plane", "ਅੰਦਰਲਾ ਗ੍ਰਿਡ-ਤਲ"],
  ["grid-plane cuts", "ਗ੍ਰਿਡ-ਤਲ ਕੱਟ"],
  ["regular-polygon", "ਸਮ-ਬਹੁਭੁਜੀ"],
  ["trapezium-shaped", "ਸਮਲੰਬਾਕਾਰ"],
  ["cube-shaped", "ਘਣਾਕਾਰ"],
  ["water-level", "ਪਾਣੀ-ਪੱਧਰ"],
  ["sheet-metal", "ਧਾਤ ਦੀ ਚਾਦਰ"],
  ["How many", "ਕਿੰਨੇ"],
  ["How much", "ਕਿੰਨਾ"],
];

const HI_WORDS: Dict = {
  wide:"चौड़ा", measuring:"माप", metallic:"धातु", inscribed:"अंतर्लिखित", identical:"समान",
  parallel:"समानांतर", shaped:"आकार", made:"बनाया", completely:"पूरी तरह", attached:"जुड़ा",
  whose:"जिसका", shorter:"छोटी", shows:"दिखाता", frame:"फ्रेम", rebent:"फिर मोड़ा", bent:"मोड़ा",
  straightened:"सीधा किया", block:"खंड", how:"कितना", many:"कितने", terms:"पदों", pipe:"पाइप",
  exposed:"खुला", melted:"पिघलाया", percentage:"प्रतिशत", bounded:"घिरा", enclosure:"घेरा",
  field:"क्षेत्र", equilateral:"समबाहु", them:"उनके", plot:"भूखंड", trapezium:"समलंब", other:"अन्य",
  ring:"छल्ला", covers:"तय करता", wheel:"पहिया", uniform:"समान", hall:"हॉल", cover:"ढकें",
  paving:"फर्श", runs:"चलता", paved:"पक्का", externally:"बाहर", semicircular:"अर्धवृत्ताकार",
  pieces:"टुकड़े", shared:"साझा", tape:"फीता", producing:"जिससे", multiplied:"गुणा किया",
  cube:"घन", storage:"भंडारण", edges:"किनारे", costs:"लागत", twelve:"बारह", cuboidal:"घनाभाकार",
  cutting:"काटकर", internal:"भीतरी", cuts:"कट", distinct:"अलग", grid:"ग्रिड", plane:"तल",
  leave:"रखें", minimum:"न्यूनतम", possible:"संभव", designed:"बनाया", order:"क्रम", lower:"निचली",
  pyramid:"पिरामिड", upper:"ऊपरी", parent:"मूल", polygon:"बहुभुज", perimeters:"परिमाप",
  regular:"सम", annular:"वलयाकार", including:"सहित", walls:"पृष्ठ", external:"बाहरी", ends:"सिरे",
  bore:"भीतरी छेद", joined:"जोड़े", row:"पंक्ति", resulting:"बना", inner:"भीतरी", coaxial:"समाक्षीय",
  outer:"बाहरी", lining:"अस्तर", casing:"आवरण", rolled:"बेला", thinner:"पतली", assuming:"मानते हुए",
  plate:"चादर", slab:"पट्टी", thick:"मोटी", loss:"हानि", thickness:"मोटाई", lost:"नष्ट", together:"साथ",
  decimal:"दशमलव", recast:"फिर ढाला", places:"स्थान", model:"मॉडल", decorative:"सजावटी",
  consists:"बना है", toy:"मॉडल", surmounted:"ऊपर रखा", rise:"वृद्धि", level:"स्तर", immersed:"डुबोए",
  water:"पानी", completely:"पूरी तरह",
};

const PA_WORDS: Dict = {
  wide:"ਚੌੜਾ", measuring:"ਮਾਪ", metallic:"ਧਾਤ", inscribed:"ਅੰਦਰ ਅੰਕਿਤ", identical:"ਇੱਕੋ ਜਿਹੇ",
  parallel:"ਸਮਾਂਤਰ", shaped:"ਆਕਾਰ", made:"ਬਣਾਇਆ", completely:"ਪੂਰੀ ਤਰ੍ਹਾਂ", attached:"ਜੁੜਿਆ",
  whose:"ਜਿਸਦਾ", shorter:"ਛੋਟੀ", shows:"ਦਿਖਾਉਂਦਾ", frame:"ਫਰੇਮ", rebent:"ਮੁੜ ਮੋੜਿਆ", bent:"ਮੋੜਿਆ",
  straightened:"ਸਿੱਧਾ ਕੀਤਾ", block:"ਬਲਾਕ", how:"ਕਿੰਨਾ", many:"ਕਿੰਨੇ", terms:"ਪਦਾਂ", pipe:"ਪਾਈਪ",
  exposed:"ਖੁੱਲ੍ਹਾ", melted:"ਪਿਘਲਾਇਆ", percentage:"ਪ੍ਰਤੀਸ਼ਤ", bounded:"ਘਿਰਿਆ", enclosure:"ਘੇਰਾ",
  field:"ਖੇਤ", equilateral:"ਸਮਭੁਜ", them:"ਉਹਨਾਂ", plot:"ਪਲਾਟ", trapezium:"ਸਮਲੰਬ", other:"ਹੋਰ",
  ring:"ਛੱਲਾ", covers:"ਤੈਅ ਕਰਦਾ", wheel:"ਪਹੀਆ", uniform:"ਇੱਕੋ", hall:"ਹਾਲ", cover:"ਢੱਕੋ",
  paving:"ਫਰਸ਼", runs:"ਜਾਂਦਾ", paved:"ਪੱਕਾ", externally:"ਬਾਹਰ", semicircular:"ਅਰਧ-ਵ੍ਰਿਤਾਕਾਰ",
  pieces:"ਟੁਕੜੇ", shared:"ਸਾਂਝਾ", tape:"ਫੀਤਾ", producing:"ਜਿਸ ਨਾਲ", multiplied:"ਗੁਣਾ ਕੀਤਾ",
  cube:"ਘਣ", storage:"ਸਟੋਰੇਜ", edges:"ਕਿਨਾਰੇ", costs:"ਲਾਗਤ", twelve:"ਬਾਰਾਂ", cuboidal:"ਘਣਾਭਾਕਾਰ",
  cutting:"ਕੱਟ ਕੇ", internal:"ਅੰਦਰਲਾ", cuts:"ਕੱਟ", distinct:"ਵੱਖਰੇ", grid:"ਗ੍ਰਿਡ", plane:"ਤਲ",
  leave:"ਰੱਖੋ", minimum:"ਘੱਟੋ-ਘੱਟ", possible:"ਸੰਭਵ", designed:"ਬਣਾਇਆ", order:"ਕ੍ਰਮ", lower:"ਹੇਠਲੀ",
  pyramid:"ਪਿਰਾਮਿਡ", upper:"ਉੱਪਰਲੀ", parent:"ਮੂਲ", polygon:"ਬਹੁਭੁਜ", perimeters:"ਪਰਿਮਾਪ",
  regular:"ਸਮ", annular:"ਛੱਲਾਕਾਰ", including:"ਸਮੇਤ", walls:"ਸਤਹਾਂ", external:"ਬਾਹਰੀ", ends:"ਸਿਰੇ",
  bore:"ਅੰਦਰਲਾ ਛੇਦ", joined:"ਜੋੜੇ", row:"ਕਤਾਰ", resulting:"ਬਣਿਆ", inner:"ਅੰਦਰਲਾ", coaxial:"ਸਮ-ਅਕਸੀ",
  outer:"ਬਾਹਰੀ", lining:"ਲਾਈਨਿੰਗ", casing:"ਆਵਰਨ", rolled:"ਰੋਲ ਕੀਤਾ", thinner:"ਪਤਲੀ", assuming:"ਮੰਨਦੇ ਹੋਏ",
  plate:"ਚਾਦਰ", slab:"ਪੱਟੀ", thick:"ਮੋਟੀ", loss:"ਘਾਟ", thickness:"ਮੋਟਾਈ", lost:"ਘਟਿਆ", together:"ਇਕੱਠੇ",
  decimal:"ਦਸ਼ਮਲਵ", recast:"ਮੁੜ ਢਾਲਿਆ", places:"ਥਾਵਾਂ", model:"ਮਾਡਲ", decorative:"ਸਜਾਵਟੀ",
  consists:"ਬਣਿਆ ਹੈ", toy:"ਮਾਡਲ", surmounted:"ਉੱਪਰ ਰੱਖਿਆ", rise:"ਵਾਧਾ", level:"ਪੱਧਰ", immersed:"ਡੁੱਬੇ",
  water:"ਪਾਣੀ",
};

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function phrasePass(text: string, pairs: readonly Pair[]) {
  let out = text;
  for (const [source, target] of [...pairs].sort((a, b) => b[0].length - a[0].length)) {
    const escaped = escapeRegExp(source);
    const left = /^[A-Za-z]/.test(source) ? "\\b" : "";
    const right = /[A-Za-z]$/.test(source) ? "\\b" : "";
    out = out.replace(new RegExp(`${left}${escaped}${right}`, "gi"), target);
  }
  return out;
}

function wordPass(text: string, dict: Dict) {
  return text.replace(/\b[A-Za-z]+\b/g, (word) => dict[word.toLowerCase()] ?? word);
}

export function prelocalizeMensurationStemSourceV2(
  text: string,
  language: MensurationLocalizedLanguage,
) {
  const phrases = language === "hi" ? HI_PHRASES : PA_PHRASES;
  const words = language === "hi" ? HI_WORDS : PA_WORDS;
  return wordPass(phrasePass(text, phrases), words);
}
