import type { MensurationLocalizedLanguage } from "./mensuration-localization-foundation-v3";

type Pair = readonly [string, string];

/**
 * Stem-only source editorial layer.
 *
 * These are sentence/phrase translations taken from the frozen English
 * Question Studio stem families. They run before the generic token translator
 * so learner questions keep natural Hindi/Punjabi word order. Mathematical
 * spans and numeric values are deliberately not rewritten here.
 */
const HI: readonly Pair[] = [
  ["Calculate the complete exposed surface area, including both curved walls and both annular ends.", "दोनों वक्र पृष्ठों और दोनों वलयाकार सिरों सहित पूरा खुला पृष्ठ क्षेत्रफल ज्ञात कीजिए."],
  ["A cuboidal block measuring", "एक घनाभाकार खंड, जिसका माप"],
  ["is divided into cubes of side", "है, उसे भुजा"],
  ["by cutting every required internal grid plane once across the full block.", "वाले घनों में बाँटने के लिए प्रत्येक आवश्यक भीतरी कट-तल पर पूरे खंड को एक बार काटा जाता है."],
  ["How many distinct grid-plane cuts are required?", "कुल कितने अलग-अलग कट आवश्यक हैं?"],
  ["A cylindrical container of radius", "त्रिज्या"],
  ["shows a water-level rise of", "वाला एक बेलनाकार पात्र, समान ठोस गोले डुबोने पर जल-स्तर में"],
  ["when identical solid spheres of radius", "की वृद्धि दिखाता है. प्रत्येक गोले की त्रिज्या"],
  ["are completely immersed. How many spheres were immersed?", "है और वे पूरी तरह डुबोए गए हैं. कुल कितने गोले डुबोए गए थे?"],
  ["Three solid metal spheres of radii", "त्रिज्याओं"],
  ["are melted together and recast into one solid sphere.", "वाले तीन ठोस धातु के गोलों को पिघलाकर एक ठोस गोले के रूप में फिर से ढाला जाता है."],
  ["Find the percentage decrease in their total surface area, correct to two decimal places.", "उनके कुल पृष्ठ क्षेत्रफल में प्रतिशत कमी दो दशमलव स्थान तक ज्ञात कीजिए."],
  ["A rectangular metal slab is", "एक आयताकार धातु की पट्टी"],
  ["long,", "लंबी,"],
  ["wide and", "चौड़ी और"],
  ["thick. It is rolled into a thinner rectangular plate of the same width but thickness", "मोटी है. इसे बेलकर समान चौड़ाई की एक पतली आयताकार चादर बनाई जाती है, जिसकी मोटाई"],
  ["Assuming no loss, find the new plate length.", "कोई पदार्थ नष्ट न होने पर नई चादर की लंबाई ज्ञात कीजिए."],
  ["A metal cube of side", "भुजा"],
  ["is melted into", "वाले धातु के घन को पिघलाकर"],
  ["cubes of side", "घन बनाए जाते हैं, प्रत्येक की भुजा"],
  ["What percentage of the metal was lost?", "धातु का कितने प्रतिशत भाग नष्ट हुआ?"],
  ["is recast into identical cubes of side", "वाले धातु के घन को समान छोटे घनों में फिर से ढाला जाता है, प्रत्येक की भुजा"],
  ["How many small cubes are formed?", "कुल कितने छोटे घन बनेंगे?"],
  ["A decorative metal model consists of a cylinder surmounted by a hemisphere of radius", "एक सजावटी धातु मॉडल में एक बेलन है, जिसके ऊपर त्रिज्या"],
  ["The total height of the toy is", "वाले अर्धगोले को रखा गया है. मॉडल की कुल ऊँचाई"],
  ["Calculate its volume.", "उसका आयतन ज्ञात कीजिए."],
  ["A cube of edge", "किनारे"],
  ["is inscribed in a sphere.", "वाला घन एक गोले में अंतर्लिखित है."],
  ["Determine the diameter of the sphere.", "गोले का व्यास ज्ञात कीजिए."],
  ["A sphere is inscribed in a cube of edge", "एक गोला किनारे"],
  ["Find the total surface area of the sphere.", "वाले घन में अंतर्लिखित है. गोले का कुल पृष्ठ क्षेत्रफल ज्ञात कीजिए."],
  ["A hollow metallic pipe is", "एक खोखली धातु की पाइप"],
  ["long with external radius", "लंबी है, जिसकी बाहरी त्रिज्या"],
  ["and bore radius", "और भीतरी छेद की त्रिज्या"],
  ["A hollow metallic pipe has outer radius", "एक खोखली धातु की पाइप की बाहरी त्रिज्या"],
  ["inner radius", "भीतरी त्रिज्या"],
  ["and length", "और लंबाई"],
  ["Find the volume of metal used.", "प्रयुक्त धातु का आयतन ज्ञात कीजिए."],
  ["identical solid cubes, each of side", "समान ठोस घन हैं, प्रत्येक की भुजा"],
  ["are joined face to face to form a straight row of", "है. उन्हें पृष्ठ से पृष्ठ जोड़कर"],
  ["cubes. Find the total exposed surface area of the resulting solid.", "घनों की सीधी पंक्ति बनाई जाती है. बने हुए ठोस का कुल खुला पृष्ठ क्षेत्रफल ज्ञात कीजिए."],
  ["The outer cone of a casing has radius", "एक आवरण के बाहरी शंकु की त्रिज्या"],
  ["and slant height", "और तिर्यक ऊँचाई"],
  ["The coaxial inner surface is similar with inner-to-outer scale", "समाक्षीय भीतरी पृष्ठ समरूप है और भीतरी-बाहरी रैखिक माप-गुणक"],
  ["Calculate the inner curved lining cost at", "भीतरी वक्र पृष्ठ पर अस्तर लगाने की लागत"],
  ["A right square-pyramid frustum has lower side", "एक समकोण वर्गाकार पिरामिडीय फ्रस्टम की निचली भुजा"],
  ["upper side", "ऊपरी भुजा"],
  ["Find its total surface area.", "उसका कुल पृष्ठ क्षेत्रफल ज्ञात कीजिए."],
  ["Find the height of the complete parent solid.", "पूर्ण मूल ठोस की ऊँचाई ज्ञात कीजिए."],
  ["For a regular-polygon frustum, base perimeters", "एक समबहुभुजीय फ्रस्टम में आधारों के परिमाप"],
  ["base areas", "आधारों के क्षेत्रफल"],
  ["and total surface area", "और कुल पृष्ठ क्षेत्रफल"],
  ["Find slant height.", "तिर्यक ऊँचाई ज्ञात कीजिए."],
  ["Leave the answer in terms of", "उत्तर को"],
  ["Find its volume in exact terms of", "उसका आयतन ठीक"],
  ["Find the volume of a cylinder whose curved and total surface areas are", "उस बेलन का आयतन ज्ञात कीजिए, जिसका वक्र और कुल पृष्ठ क्षेत्रफल क्रमशः"],
  ["A closed right circular cylinder of volume", "आयतन"],
  ["is designed to have the minimum possible total surface area.", "वाले एक बंद समवृत्त बेलन को न्यूनतम संभव कुल पृष्ठ क्षेत्रफल के लिए बनाया गया है."],
  ["Find its height.", "उसकी ऊँचाई ज्ञात कीजिए."],
  ["Two spheres have radii", "दो गोलों की त्रिज्याएँ"],
  ["What is the ratio of their volumes, in the same order?", "उसी क्रम में उनके आयतनों का अनुपात ज्ञात कीजिए."],
  ["For a solid hemisphere, total surface area : volume is", "एक ठोस अर्धगोले के लिए कुल पृष्ठ क्षेत्रफल : आयतन ="],
  ["What is its radius?", "उसकी त्रिज्या ज्ञात कीजिए."],
  ["A rectangle is", "एक आयत"],
  ["A semicircle whose diameter equals the rectangle's width is attached externally along one shorter side.", "है. आयत की चौड़ाई के बराबर व्यास वाला एक अर्धवृत्त उसकी एक छोटी भुजा के बाहर जोड़ा गया है."],
  ["Find the total area.", "कुल क्षेत्रफल ज्ञात कीजिए."],
  ["Two semicircular pieces, each of diameter", "व्यास"],
  ["are cut from a", "वाले दो अर्धवृत्ताकार टुकड़े"],
  ["rectangle. Find the remaining area.", "के आयत से काटे जाते हैं. शेष क्षेत्रफल ज्ञात कीजिए."],
  ["has a semicircle of diameter", "है. व्यास"],
  ["attached along one shorter side. Find the outside perimeter; do not count the shared diameter.", "वाला एक अर्धवृत्त उसकी एक छोटी भुजा पर जुड़ा है. बाहरी परिमाप ज्ञात कीजिए; साझा व्यास को न गिनें."],
  ["A square is inscribed in a circle.", "एक वर्ग एक वृत्त में अंतर्लिखित है."],
  ["The area inside the circle but outside the square is", "वृत्त के अंदर लेकिन वर्ग के बाहर का क्षेत्रफल"],
  ["Find the radius of the circle.", "वृत्त की त्रिज्या ज्ञात कीजिए."],
  ["A measuring tape shows a length of", "एक माप-फीते पर लंबाई"],
  ["Express this length in metres.", "दिखाई गई है. इस लंबाई को मीटर में व्यक्त कीजिए."],
  ["Every length of a figure was multiplied by", "किसी आकृति की प्रत्येक लंबाई को"],
  ["producing an area of", "से गुणा करने पर क्षेत्रफल"],
  ["Find the original area.", "मिलता है. मूल क्षेत्रफल ज्ञात कीजिए."],
  ["A metallic wire is bent into a rectangular frame", "एक धातु के तार को मोड़कर"],
  ["The same wire is then straightened and rebent into a square frame.", "का आयताकार फ्रेम बनाया गया है. उसी तार को सीधा करके फिर वर्गाकार फ्रेम बनाया जाता है."],
  ["Find the side of the square.", "वर्ग की भुजा ज्ञात कीजिए."],
  ["A metallic wire is bent into a circular frame of radius", "एक धातु के तार को मोड़कर त्रिज्या"],
  ["It is then straightened and rebent into a square frame.", "का वृत्ताकार फ्रेम बनाया गया है. फिर तार को सीधा करके वर्गाकार फ्रेम बनाया जाता है."],
  ["Find the area enclosed by the square.", "वर्ग से घिरा क्षेत्रफल ज्ञात कीजिए."],
  ["A rectangular hall floor measures", "एक आयताकार हॉल के फर्श का माप"],
  ["Square tiles of side", "है. भुजा"],
  ["are used to cover it completely. Find the number of tiles required.", "वाली वर्गाकार टाइलों से इसे पूरी तरह ढका जाता है. आवश्यक टाइलों की संख्या ज्ञात कीजिए."],
  ["A path of uniform width", "समान चौड़ाई"],
  ["is made outside it. Find the area of the path.", "का पथ इसके बाहर बनाया गया है. पथ का क्षेत्रफल ज्ञात कीजिए."],
  ["A path", "एक पथ"],
  ["wide is made outside it and covered with rectangular paving tiles measuring", "चौड़ा इसके बाहर बनाया गया है और उसे माप"],
  ["How many tiles are required?", "वाली आयताकार टाइलों से ढका गया है. कितनी टाइलें चाहिए?"],
  ["wide runs along its inside boundary and is paved with tiles measuring", "चौड़ा उसकी भीतरी सीमा के साथ बना है और उस पर माप"],
  ["A circular ring has outer radius", "एक वृत्ताकार छल्ले की बाहरी त्रिज्या"],
  ["and inner radius", "और भीतरी त्रिज्या"],
  ["A wheel covers", "एक पहिया"],
  ["in", "दूरी"],
  ["complete revolutions. Find its radius.", "पूरे चक्करों में तय करता है. उसकी त्रिज्या ज्ञात कीजिए."],
  ["The parallel sides of a trapezium-shaped plot are", "एक समलंबाकार भूखंड की समानांतर भुजाएँ"],
  ["and the perpendicular distance between them is", "हैं और उनके बीच की लंबवत दूरी"],
  ["The parallel sides of a trapezium are", "एक समलंब की समानांतर भुजाएँ"],
  ["while its other sides are", "हैं, जबकि उसकी अन्य भुजाएँ"],
  ["Find its perimeter.", "उसका परिमाप ज्ञात कीजिए."],
  ["The area of an equilateral field is", "एक समबाहु त्रिभुजाकार क्षेत्र का क्षेत्रफल"],
  ["Find the length of each side.", "है. प्रत्येक भुजा की लंबाई ज्ञात कीजिए."],
];

const PA: readonly Pair[] = [
  ["Calculate the complete exposed surface area, including both curved walls and both annular ends.", "ਦੋਵੇਂ ਵਕਰ ਸਤਹਾਂ ਅਤੇ ਦੋਵੇਂ ਛੱਲਾਕਾਰ ਸਿਰਿਆਂ ਸਮੇਤ ਪੂਰਾ ਖੁੱਲ੍ਹਾ ਸਤਹ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["A cuboidal block measuring", "ਇੱਕ ਘਣਾਭਾਕਾਰ ਬਲਾਕ, ਜਿਸ ਦਾ ਮਾਪ"],
  ["is divided into cubes of side", "ਹੈ, ਉਸ ਨੂੰ ਭੁਜਾ"],
  ["by cutting every required internal grid plane once across the full block.", "ਵਾਲੇ ਘਣਾਂ ਵਿੱਚ ਵੰਡਣ ਲਈ ਹਰ ਲੋੜੀਂਦੇ ਅੰਦਰਲੇ ਕੱਟ-ਤਲ ਉੱਤੇ ਪੂਰੇ ਬਲਾਕ ਨੂੰ ਇੱਕ ਵਾਰ ਕੱਟਿਆ ਜਾਂਦਾ ਹੈ."],
  ["How many distinct grid-plane cuts are required?", "ਕੁੱਲ ਕਿੰਨੇ ਵੱਖਰੇ ਕੱਟ ਲੋੜੀਂਦੇ ਹਨ?"],
  ["A cylindrical container of radius", "ਅਰਧ-ਵਿਆਸ"],
  ["shows a water-level rise of", "ਵਾਲਾ ਇੱਕ ਬੇਲਨਾਕਾਰ ਭਾਂਡਾ, ਇੱਕੋ ਜਿਹੇ ਠੋਸ ਗੋਲੇ ਡੁੱਬਣ 'ਤੇ ਪਾਣੀ ਦੇ ਪੱਧਰ ਵਿੱਚ"],
  ["when identical solid spheres of radius", "ਦਾ ਵਾਧਾ ਦਿਖਾਉਂਦਾ ਹੈ. ਹਰ ਗੋਲੇ ਦਾ ਅਰਧ-ਵਿਆਸ"],
  ["are completely immersed. How many spheres were immersed?", "ਹੈ ਅਤੇ ਉਹ ਪੂਰੀ ਤਰ੍ਹਾਂ ਡੁੱਬੇ ਹੋਏ ਹਨ. ਕੁੱਲ ਕਿੰਨੇ ਗੋਲੇ ਡੁੱਬੇ ਸਨ?"],
  ["Three solid metal spheres of radii", "ਅਰਧ-ਵਿਆਸਾਂ"],
  ["are melted together and recast into one solid sphere.", "ਵਾਲੇ ਤਿੰਨ ਠੋਸ ਧਾਤ ਦੇ ਗੋਲਿਆਂ ਨੂੰ ਪਿਘਲਾ ਕੇ ਇੱਕ ਠੋਸ ਗੋਲੇ ਵਜੋਂ ਮੁੜ ਢਾਲਿਆ ਜਾਂਦਾ ਹੈ."],
  ["Find the percentage decrease in their total surface area, correct to two decimal places.", "ਉਹਨਾਂ ਦੇ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ ਵਿੱਚ ਪ੍ਰਤੀਸ਼ਤ ਘਾਟ ਦੋ ਦਸ਼ਮਲਵ ਥਾਵਾਂ ਤੱਕ ਪਤਾ ਕਰੋ."],
  ["A rectangular metal slab is", "ਇੱਕ ਆਇਤਾਕਾਰ ਧਾਤ ਦੀ ਪੱਟੀ"],
  ["long,", "ਲੰਮੀ,"],
  ["wide and", "ਚੌੜੀ ਅਤੇ"],
  ["thick. It is rolled into a thinner rectangular plate of the same width but thickness", "ਮੋਟੀ ਹੈ. ਇਸ ਨੂੰ ਰੋਲ ਕਰਕੇ ਇੱਕੋ ਚੌੜਾਈ ਦੀ ਪਤਲੀ ਆਇਤਾਕਾਰ ਚਾਦਰ ਬਣਾਈ ਜਾਂਦੀ ਹੈ, ਜਿਸ ਦੀ ਮੋਟਾਈ"],
  ["Assuming no loss, find the new plate length.", "ਕੋਈ ਧਾਤ ਨਾ ਘਟਣ ਦੀ ਸਥਿਤੀ ਵਿੱਚ ਨਵੀਂ ਚਾਦਰ ਦੀ ਲੰਬਾਈ ਪਤਾ ਕਰੋ."],
  ["A metal cube of side", "ਭੁਜਾ"],
  ["is melted into", "ਵਾਲੇ ਧਾਤ ਦੇ ਘਣ ਨੂੰ ਪਿਘਲਾ ਕੇ"],
  ["cubes of side", "ਘਣ ਬਣਾਏ ਜਾਂਦੇ ਹਨ, ਹਰ ਇੱਕ ਦੀ ਭੁਜਾ"],
  ["What percentage of the metal was lost?", "ਧਾਤ ਦਾ ਕਿੰਨਾ ਪ੍ਰਤੀਸ਼ਤ ਹਿੱਸਾ ਘਟ ਗਿਆ?"],
  ["is recast into identical cubes of side", "ਵਾਲੇ ਧਾਤ ਦੇ ਘਣ ਨੂੰ ਇੱਕੋ ਜਿਹੇ ਛੋਟੇ ਘਣਾਂ ਵਿੱਚ ਮੁੜ ਢਾਲਿਆ ਜਾਂਦਾ ਹੈ, ਹਰ ਇੱਕ ਦੀ ਭੁਜਾ"],
  ["How many small cubes are formed?", "ਕੁੱਲ ਕਿੰਨੇ ਛੋਟੇ ਘਣ ਬਣਣਗੇ?"],
  ["A decorative metal model consists of a cylinder surmounted by a hemisphere of radius", "ਇੱਕ ਸਜਾਵਟੀ ਧਾਤ ਮਾਡਲ ਵਿੱਚ ਇੱਕ ਬੇਲਨ ਹੈ, ਜਿਸ ਦੇ ਉੱਪਰ ਅਰਧ-ਵਿਆਸ"],
  ["The total height of the toy is", "ਵਾਲਾ ਅਰਧਗੋਲਾ ਰੱਖਿਆ ਹੈ. ਮਾਡਲ ਦੀ ਕੁੱਲ ਉਚਾਈ"],
  ["Calculate its volume.", "ਇਸ ਦਾ ਆਇਤਨ ਪਤਾ ਕਰੋ."],
  ["A cube of edge", "ਕਿਨਾਰੇ"],
  ["is inscribed in a sphere.", "ਵਾਲਾ ਘਣ ਇੱਕ ਗੋਲੇ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ."],
  ["Determine the diameter of the sphere.", "ਗੋਲੇ ਦਾ ਵਿਆਸ ਪਤਾ ਕਰੋ."],
  ["A sphere is inscribed in a cube of edge", "ਇੱਕ ਗੋਲਾ ਕਿਨਾਰੇ"],
  ["Find the total surface area of the sphere.", "ਵਾਲੇ ਘਣ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ. ਗੋਲੇ ਦਾ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["A hollow metallic pipe is", "ਇੱਕ ਖੋਖਲੀ ਧਾਤ ਦੀ ਪਾਈਪ"],
  ["long with external radius", "ਲੰਮੀ ਹੈ, ਜਿਸ ਦਾ ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ"],
  ["and bore radius", "ਅਤੇ ਅੰਦਰਲੇ ਛੇਦ ਦਾ ਅਰਧ-ਵਿਆਸ"],
  ["A hollow metallic pipe has outer radius", "ਇੱਕ ਖੋਖਲੀ ਧਾਤ ਦੀ ਪਾਈਪ ਦਾ ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ"],
  ["inner radius", "ਅੰਦਰਲਾ ਅਰਧ-ਵਿਆਸ"],
  ["and length", "ਅਤੇ ਲੰਬਾਈ"],
  ["Find the volume of metal used.", "ਵਰਤੀ ਧਾਤ ਦਾ ਆਇਤਨ ਪਤਾ ਕਰੋ."],
  ["identical solid cubes, each of side", "ਇੱਕੋ ਜਿਹੇ ਠੋਸ ਘਣ ਹਨ, ਹਰ ਇੱਕ ਦੀ ਭੁਜਾ"],
  ["are joined face to face to form a straight row of", "ਹੈ. ਉਹਨਾਂ ਨੂੰ ਪਾਸੇ ਨਾਲ ਪਾਸਾ ਜੋੜ ਕੇ"],
  ["cubes. Find the total exposed surface area of the resulting solid.", "ਘਣਾਂ ਦੀ ਸਿੱਧੀ ਕਤਾਰ ਬਣਾਈ ਜਾਂਦੀ ਹੈ. ਬਣੇ ਠੋਸ ਦਾ ਕੁੱਲ ਖੁੱਲ੍ਹਾ ਸਤਹ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["The outer cone of a casing has radius", "ਇੱਕ ਆਵਰਨ ਦੇ ਬਾਹਰੀ ਸ਼ੰਕੂ ਦਾ ਅਰਧ-ਵਿਆਸ"],
  ["and slant height", "ਅਤੇ ਤਿਰਛੀ ਉਚਾਈ"],
  ["The coaxial inner surface is similar with inner-to-outer scale", "ਸਮ-ਅਕਸੀ ਅੰਦਰਲੀ ਸਤਹ ਸਮਰੂਪ ਹੈ ਅਤੇ ਅੰਦਰਲੇ-ਬਾਹਰੀ ਰੇਖੀ ਮਾਪ ਦਾ ਗੁਣਕ"],
  ["Calculate the inner curved lining cost at", "ਅੰਦਰਲੀ ਵਕਰ ਸਤਹ ਉੱਤੇ ਲਾਈਨਿੰਗ ਦੀ ਲਾਗਤ"],
  ["A right square-pyramid frustum has lower side", "ਇੱਕ ਲੰਬ ਵਰਗ-ਆਧਾਰ ਪਿਰਾਮਿਡੀ ਫਰਸਟਮ ਦੀ ਹੇਠਲੀ ਭੁਜਾ"],
  ["upper side", "ਉੱਪਰਲੀ ਭੁਜਾ"],
  ["Find its total surface area.", "ਇਸ ਦਾ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["Find the height of the complete parent solid.", "ਪੂਰੇ ਮੂਲ ਠੋਸ ਦੀ ਉਚਾਈ ਪਤਾ ਕਰੋ."],
  ["For a regular-polygon frustum, base perimeters", "ਇੱਕ ਸਮ-ਬਹੁਭੁਜੀ ਫਰਸਟਮ ਵਿੱਚ ਆਧਾਰਾਂ ਦੇ ਪਰਿਮਾਪ"],
  ["base areas", "ਆਧਾਰਾਂ ਦੇ ਖੇਤਰਫਲ"],
  ["and total surface area", "ਅਤੇ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ"],
  ["Find slant height.", "ਤਿਰਛੀ ਉਚਾਈ ਪਤਾ ਕਰੋ."],
  ["Leave the answer in terms of", "ਉੱਤਰ ਨੂੰ"],
  ["Find its volume in exact terms of", "ਇਸ ਦਾ ਆਇਤਨ ਠੀਕ"],
  ["Find the volume of a cylinder whose curved and total surface areas are", "ਉਸ ਬੇਲਨ ਦਾ ਆਇਤਨ ਪਤਾ ਕਰੋ, ਜਿਸ ਦੇ ਵਕਰ ਅਤੇ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ ਕ੍ਰਮਵਾਰ"],
  ["A closed right circular cylinder of volume", "ਆਇਤਨ"],
  ["is designed to have the minimum possible total surface area.", "ਵਾਲੇ ਇੱਕ ਬੰਦ ਲੰਬ ਵ੍ਰਿਤਾਕਾਰ ਬੇਲਨ ਨੂੰ ਘੱਟੋ-ਘੱਟ ਸੰਭਵ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ ਲਈ ਬਣਾਇਆ ਗਿਆ ਹੈ."],
  ["Find its height.", "ਇਸ ਦੀ ਉਚਾਈ ਪਤਾ ਕਰੋ."],
  ["Two spheres have radii", "ਦੋ ਗੋਲਿਆਂ ਦੇ ਅਰਧ-ਵਿਆਸ"],
  ["What is the ratio of their volumes, in the same order?", "ਉਸੇ ਕ੍ਰਮ ਵਿੱਚ ਉਹਨਾਂ ਦੇ ਆਇਤਨਾਂ ਦਾ ਅਨੁਪਾਤ ਪਤਾ ਕਰੋ."],
  ["For a solid hemisphere, total surface area : volume is", "ਇੱਕ ਠੋਸ ਅਰਧਗੋਲੇ ਲਈ ਕੁੱਲ ਸਤਹ ਖੇਤਰਫਲ : ਆਇਤਨ ="],
  ["What is its radius?", "ਇਸ ਦਾ ਅਰਧ-ਵਿਆਸ ਪਤਾ ਕਰੋ."],
  ["A rectangle is", "ਇੱਕ ਆਇਤ"],
  ["A semicircle whose diameter equals the rectangle's width is attached externally along one shorter side.", "ਹੈ. ਆਇਤ ਦੀ ਚੌੜਾਈ ਦੇ ਬਰਾਬਰ ਵਿਆਸ ਵਾਲਾ ਇੱਕ ਅਰਧ-ਵ੍ਰਿਤ ਇਸ ਦੀ ਇੱਕ ਛੋਟੀ ਭੁਜਾ ਦੇ ਬਾਹਰ ਜੋੜਿਆ ਗਿਆ ਹੈ."],
  ["Find the total area.", "ਕੁੱਲ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["Two semicircular pieces, each of diameter", "ਵਿਆਸ"],
  ["are cut from a", "ਵਾਲੇ ਦੋ ਅਰਧ-ਵ੍ਰਿਤਾਕਾਰ ਟੁਕੜੇ"],
  ["rectangle. Find the remaining area.", "ਦੇ ਆਇਤ ਵਿਚੋਂ ਕੱਟੇ ਜਾਂਦੇ ਹਨ. ਬਾਕੀ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["has a semicircle of diameter", "ਹੈ. ਵਿਆਸ"],
  ["attached along one shorter side. Find the outside perimeter; do not count the shared diameter.", "ਵਾਲਾ ਇੱਕ ਅਰਧ-ਵ੍ਰਿਤ ਇਸ ਦੀ ਇੱਕ ਛੋਟੀ ਭੁਜਾ ਨਾਲ ਜੁੜਿਆ ਹੈ. ਬਾਹਰੀ ਪਰਿਮਾਪ ਪਤਾ ਕਰੋ; ਸਾਂਝੇ ਵਿਆਸ ਨੂੰ ਨਾ ਗਿਣੋ."],
  ["A square is inscribed in a circle.", "ਇੱਕ ਵਰਗ ਇੱਕ ਵ੍ਰਿਤ ਵਿੱਚ ਅੰਦਰ ਅੰਕਿਤ ਹੈ."],
  ["The area inside the circle but outside the square is", "ਵ੍ਰਿਤ ਦੇ ਅੰਦਰ ਪਰ ਵਰਗ ਦੇ ਬਾਹਰ ਦਾ ਖੇਤਰਫਲ"],
  ["Find the radius of the circle.", "ਵ੍ਰਿਤ ਦਾ ਅਰਧ-ਵਿਆਸ ਪਤਾ ਕਰੋ."],
  ["A measuring tape shows a length of", "ਇੱਕ ਮਾਪ-ਫੀਤੇ ਉੱਤੇ ਲੰਬਾਈ"],
  ["Express this length in metres.", "ਦਿਖਾਈ ਗਈ ਹੈ. ਇਸ ਲੰਬਾਈ ਨੂੰ ਮੀਟਰ ਵਿੱਚ ਲਿਖੋ."],
  ["Every length of a figure was multiplied by", "ਕਿਸੇ ਆਕ੍ਰਿਤੀ ਦੀ ਹਰ ਲੰਬਾਈ ਨੂੰ"],
  ["producing an area of", "ਨਾਲ ਗੁਣਾ ਕਰਨ 'ਤੇ ਖੇਤਰਫਲ"],
  ["Find the original area.", "ਮਿਲਦਾ ਹੈ. ਮੂਲ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["A metallic wire is bent into a rectangular frame", "ਇੱਕ ਧਾਤ ਦੀ ਤਾਰ ਨੂੰ ਮੋੜ ਕੇ"],
  ["The same wire is then straightened and rebent into a square frame.", "ਦਾ ਆਇਤਾਕਾਰ ਫਰੇਮ ਬਣਾਇਆ ਗਿਆ ਹੈ. ਉਸੇ ਤਾਰ ਨੂੰ ਸਿੱਧਾ ਕਰਕੇ ਮੁੜ ਵਰਗਾਕਾਰ ਫਰੇਮ ਬਣਾਇਆ ਜਾਂਦਾ ਹੈ."],
  ["Find the side of the square.", "ਵਰਗ ਦੀ ਭੁਜਾ ਪਤਾ ਕਰੋ."],
  ["A metallic wire is bent into a circular frame of radius", "ਇੱਕ ਧਾਤ ਦੀ ਤਾਰ ਨੂੰ ਮੋੜ ਕੇ ਅਰਧ-ਵਿਆਸ"],
  ["It is then straightened and rebent into a square frame.", "ਦਾ ਵ੍ਰਿਤਾਕਾਰ ਫਰੇਮ ਬਣਾਇਆ ਗਿਆ ਹੈ. ਫਿਰ ਤਾਰ ਨੂੰ ਸਿੱਧਾ ਕਰਕੇ ਵਰਗਾਕਾਰ ਫਰੇਮ ਬਣਾਇਆ ਜਾਂਦਾ ਹੈ."],
  ["Find the area enclosed by the square.", "ਵਰਗ ਨਾਲ ਘਿਰਿਆ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["A rectangular hall floor measures", "ਇੱਕ ਆਇਤਾਕਾਰ ਹਾਲ ਦੇ ਫਰਸ਼ ਦਾ ਮਾਪ"],
  ["Square tiles of side", "ਹੈ. ਭੁਜਾ"],
  ["are used to cover it completely. Find the number of tiles required.", "ਵਾਲੀਆਂ ਵਰਗਾਕਾਰ ਟਾਈਲਾਂ ਨਾਲ ਇਸ ਨੂੰ ਪੂਰੀ ਤਰ੍ਹਾਂ ਢੱਕਿਆ ਜਾਂਦਾ ਹੈ. ਲੋੜੀਂਦੀਆਂ ਟਾਈਲਾਂ ਦੀ ਗਿਣਤੀ ਪਤਾ ਕਰੋ."],
  ["A path of uniform width", "ਇੱਕੋ ਚੌੜਾਈ"],
  ["is made outside it. Find the area of the path.", "ਦਾ ਰਸਤਾ ਇਸ ਦੇ ਬਾਹਰ ਬਣਾਇਆ ਗਿਆ ਹੈ. ਰਸਤੇ ਦਾ ਖੇਤਰਫਲ ਪਤਾ ਕਰੋ."],
  ["A path", "ਇੱਕ ਰਸਤਾ"],
  ["wide is made outside it and covered with rectangular paving tiles measuring", "ਚੌੜਾ ਇਸ ਦੇ ਬਾਹਰ ਬਣਾਇਆ ਗਿਆ ਹੈ ਅਤੇ ਉਸ ਨੂੰ ਮਾਪ"],
  ["How many tiles are required?", "ਵਾਲੀਆਂ ਆਇਤਾਕਾਰ ਟਾਈਲਾਂ ਨਾਲ ਢੱਕਿਆ ਗਿਆ ਹੈ. ਕਿੰਨੀਆਂ ਟਾਈਲਾਂ ਚਾਹੀਦੀਆਂ ਹਨ?"],
  ["wide runs along its inside boundary and is paved with tiles measuring", "ਚੌੜਾ ਇਸ ਦੀ ਅੰਦਰਲੀ ਸੀਮਾ ਦੇ ਨਾਲ ਬਣਿਆ ਹੈ ਅਤੇ ਉਸ ਉੱਤੇ ਮਾਪ"],
  ["A circular ring has outer radius", "ਇੱਕ ਵ੍ਰਿਤਾਕਾਰ ਛੱਲੇ ਦਾ ਬਾਹਰੀ ਅਰਧ-ਵਿਆਸ"],
  ["and inner radius", "ਅਤੇ ਅੰਦਰਲਾ ਅਰਧ-ਵਿਆਸ"],
  ["A wheel covers", "ਇੱਕ ਪਹੀਆ"],
  ["in", "ਦੂਰੀ"],
  ["complete revolutions. Find its radius.", "ਪੂਰੇ ਚੱਕਰਾਂ ਵਿੱਚ ਤੈਅ ਕਰਦਾ ਹੈ. ਇਸ ਦਾ ਅਰਧ-ਵਿਆਸ ਪਤਾ ਕਰੋ."],
  ["The parallel sides of a trapezium-shaped plot are", "ਇੱਕ ਸਮਲੰਬਾਕਾਰ ਪਲਾਟ ਦੀਆਂ ਸਮਾਂਤਰ ਭੁਜਾਵਾਂ"],
  ["and the perpendicular distance between them is", "ਹਨ ਅਤੇ ਉਹਨਾਂ ਵਿਚਕਾਰ ਦੀ ਲੰਬ ਦੂਰੀ"],
  ["The parallel sides of a trapezium are", "ਇੱਕ ਸਮਲੰਬ ਦੀਆਂ ਸਮਾਂਤਰ ਭੁਜਾਵਾਂ"],
  ["while its other sides are", "ਹਨ, ਜਦਕਿ ਇਸ ਦੀਆਂ ਹੋਰ ਭੁਜਾਵਾਂ"],
  ["Find its perimeter.", "ਇਸ ਦਾ ਪਰਿਮਾਪ ਪਤਾ ਕਰੋ."],
  ["The area of an equilateral field is", "ਇੱਕ ਸਮਭੁਜ ਤਿਕੋਣੇ ਖੇਤ ਦਾ ਖੇਤਰਫਲ"],
  ["Find the length of each side.", "ਹੈ. ਹਰ ਭੁਜਾ ਦੀ ਲੰਬਾਈ ਪਤਾ ਕਰੋ."],
];

export function prelocalizeMensurationStemSource(
  text: string,
  language: MensurationLocalizedLanguage,
) {
  const pairs = language === "hi" ? HI : PA;
  let out = text;
  for (const [source, target] of [...pairs].sort((a, b) => b[0].length - a[0].length)) {
    out = out.split(source).join(target);
  }
  return out;
}
