import type { PolCp018ReviewSeed } from "./pol-cp018-review-seed-types";

const S = ["LEGISLATIVE-DEPT-CONSTITUTION-2026"] as const;

export const POL_CP018_SEEDS_D: readonly PolCp018ReviewSeed[] = Object.freeze([
  { qlId:"POL-018-QL-016", difficulty:"Medium", stem:"Which emergency requires parliamentary approval within one month rather than two months?", answer:"National Emergency under Article 352", distractors:["President's Rule under Article 356","Financial Emergency under Article 360","All three require two months"], explanation:"Article 352 uses a one-month approval window; Articles 356 and 360 normally use a two-month parliamentary approval window.", sourceIds:S },
  { qlId:"POL-018-QL-016", difficulty:"Medium", stem:"Which emergency has an ordinary maximum constitutional duration of three years?", answer:"President's Rule", distractors:["National Emergency","Financial Emergency","All three emergencies"], explanation:"President's Rule is normally capped at three years, while National Emergency and Financial Emergency follow different continuation rules.", sourceIds:S },
  { qlId:"POL-018-QL-016", difficulty:"Medium", stem:"Which emergency needs fresh parliamentary approval every six months but has no fixed overall maximum duration?", answer:"National Emergency", distractors:["President's Rule","Financial Emergency","Article 355 protection duty"], explanation:"A National Emergency can continue in six-month blocks with repeated special-majority approval and has no fixed overall maximum in Article 352.", sourceIds:S },
  { qlId:"POL-018-QL-016", difficulty:"Medium", stem:"After approval, which emergency has no constitutional six-month renewal requirement?", answer:"Financial Emergency", distractors:["National Emergency","President's Rule","Both National Emergency and President's Rule"], explanation:"Article 360 sets the initial parliamentary approval requirement but does not require fresh six-month approvals after that approval.", sourceIds:S },

  { qlId:"POL-018-QL-017", difficulty:"Hard", stem:"A grave threat from armed rebellion is imminent but has not begun. Can Article 352 be used?", answer:"Yes, if the President is satisfied of imminent danger and Cabinet decision is written", distractors:["No, actual rebellion must begin first","Yes, but only after Supreme Court approval","No, armed rebellion is not an Article 352 ground"], explanation:"Article 352 allows action before the actual event when danger is imminent, but the Union Cabinet's written decision remains required.", sourceIds:S },
  { qlId:"POL-018-QL-017", difficulty:"Hard", stem:"Lok Sabha is dissolved when a National Emergency is proclaimed. Rajya Sabha approves it. What must the new Lok Sabha do?", answer:"Approve within 30 days of its first sitting", distractors:["Approve within six months","Nothing; Rajya Sabha approval is final","Approve within two months of election results"], explanation:"Rajya Sabha can keep the proclamation alive temporarily, but the reconstituted Lok Sabha must approve it within thirty days of first sitting.", sourceIds:S },
  { qlId:"POL-018-QL-017", difficulty:"Hard", stem:"One-tenth of Lok Sabha members give valid Emergency-disapproval notice while the House is not sitting. What follows?", answer:"A special sitting must be held within 14 days", distractors:["The Emergency ends immediately","Rajya Sabha must meet within 30 days","The notice waits until the next regular session"], explanation:"Article 352 requires a special Lok Sabha sitting within fourteen days after valid notice is received by the President when the House is not sitting.", sourceIds:S },
  { qlId:"POL-018-QL-017", difficulty:"Hard", stem:"Which combination correctly states the Article 352 approval majority?", answer:"Majority of total House membership and at least two-thirds present and voting", distractors:["Simple majority in both Houses","Two-thirds of total membership only","Three-fourths present and voting"], explanation:"Each House must meet both parts of the special majority: total-membership majority and two-thirds of members present and voting.", sourceIds:S },

  { qlId:"POL-018-QL-018", difficulty:"Hard", stem:"President's Rule has lasted one year. No National Emergency is operating. Can Parliament extend it further under the normal Article 356 rule?", answer:"No", distractors:["Yes, automatically for six months","Yes, if the Governor agrees","Yes, for up to two more years without conditions"], explanation:"Beyond one year, continuation requires the relevant National Emergency condition plus Election Commission certification of election difficulty.", sourceIds:S },
  { qlId:"POL-018-QL-018", difficulty:"Hard", stem:"President's Rule ends after Parliament made a State law under Article 357. Does that law automatically expire?", answer:"No, it continues until changed by a competent authority", distractors:["Yes, immediately","Yes, after six months","Only tax provisions survive"], explanation:"Article 357 keeps such laws in force after President's Rule until a competent Legislature or authority alters, repeals or amends them.", sourceIds:S },
  { qlId:"POL-018-QL-018", difficulty:"Hard", stem:"Which power cannot be taken over by the President through an Article 356 proclamation?", answer:"Powers vested in or exercisable by a High Court", distractors:["State executive functions","Governor's executive powers","State Legislature's law-making powers through Parliament"], explanation:"Article 356 protects High Courts by preventing the President from assuming their powers or suspending constitutional provisions relating to them.", sourceIds:S },
  { qlId:"POL-018-QL-018", difficulty:"Hard", stem:"Which pair is required for President's Rule continuation beyond one year?", answer:"Relevant National Emergency and Election Commission certificate", distractors:["Governor report and Supreme Court order","Rajya Sabha special majority and Finance Commission advice","Cabinet resolution and State referendum"], explanation:"Both safeguards are required after one year: the relevant National Emergency must operate and the Election Commission must certify election difficulty.", sourceIds:S },

  { qlId:"POL-018-QL-019", difficulty:"Hard", stem:"A National Emergency is based only on armed rebellion. Does Article 358 automatically free laws from Article 19 restrictions?", answer:"No", distractors:["Yes","Only for the first month","Only after Parliament renews the Emergency"], explanation:"Article 358 applies only to Emergencies based on war or external aggression, so armed rebellion alone does not activate it.", sourceIds:S },
  { qlId:"POL-018-QL-019", difficulty:"Hard", stem:"Can an Article 359 order suspend the right to move court for protection of Article 21?", answer:"No", distractors:["Yes","Only during war","Only with special-majority approval"], explanation:"Articles 20 and 21 are expressly excluded from Article 359 orders, so their court-enforcement remedies cannot be suspended under that Article.", sourceIds:S },
  { qlId:"POL-018-QL-019", difficulty:"Hard", stem:"Which statement correctly distinguishes Articles 358 and 359?", answer:"Article 358 concerns Article 19 in war/external-aggression Emergency; Article 359 needs a Presidential order", distractors:["Both automatically suspend all Fundamental Rights","Article 359 applies only to Article 19","Article 358 requires an Election Commission certificate"], explanation:"Article 358 has a limited automatic Article 19 effect, while Article 359 depends on a presidential order naming enforceable rights.", sourceIds:S },
  { qlId:"POL-018-QL-019", difficulty:"Hard", stem:"A law made during war Emergency has no recital connecting it to the Emergency. Can it claim Article 358 protection?", answer:"No", distractors:["Yes, automatically","Only if a State passes it","Only after Emergency ends"], explanation:"Article 358 protection requires the law itself to state that it relates to the Emergency then in operation.", sourceIds:S },

  { qlId:"POL-018-QL-020", difficulty:"Hard", stem:"Consider the statements:\n1. Article 352 approval is needed within one month.\n2. Article 356 approval is needed within two months.\n3. Article 360 requires six-month renewals.\nWhich are correct?", answer:"Statements 1 and 2 only", distractors:["Statement 1 only","Statements 2 and 3 only","All three"], explanation:"The first two approval periods are correct. Article 360 does not impose a six-month renewal cycle after parliamentary approval.", sourceIds:S },
  { qlId:"POL-018-QL-020", difficulty:"Hard", stem:"Consider the statements:\n1. Article 355 creates a Union protection duty.\n2. Article 356 protects High Court powers from takeover.\n3. Article 359 allows suspension of Articles 20 and 21 enforcement.\nWhich are correct?", answer:"Statements 1 and 2 only", distractors:["Statement 1 only","Statements 2 and 3 only","All three"], explanation:"Articles 355 and 356 support statements 1 and 2. Article 359 expressly excludes Articles 20 and 21 from suspension orders.", sourceIds:S },
  { qlId:"POL-018-QL-020", difficulty:"Hard", stem:"During Financial Emergency, which direction is constitutionally possible?", answer:"Reserve specified State financial Bills for Presidential consideration", distractors:["Suspend Article 21","Abolish the Supreme Court","Transfer all State List subjects permanently to Parliament"], explanation:"Article 360 permits directions requiring State Money Bills and other Article 207 Bills to be reserved for the President after passage.", sourceIds:S },
  { qlId:"POL-018-QL-020", difficulty:"Hard", stem:"Which emergency provision may directly support salary reductions for Supreme Court and High Court Judges?", answer:"Article 360 Financial Emergency", distractors:["Article 352 alone","Article 356 President's Rule","Article 355 Union duty"], explanation:"Article 360 expressly allows presidential directions reducing Union-service salaries and allowances, including those of Supreme Court and High Court Judges.", sourceIds:S },
]);
