import type { PolCp018ReviewSeed } from "./pol-cp018-review-seed-types";

const S = ["LEGISLATIVE-DEPT-CONSTITUTION-2026"] as const;

export const POL_CP018_SEEDS_B: readonly PolCp018ReviewSeed[] = Object.freeze([
  { qlId:"POL-018-QL-006", difficulty:"Easy", stem:"Which Article explains how State legislative powers may be exercised during President's Rule?", answer:"Article 357", distractors:["Article 356","Article 358","Article 360"], explanation:"Article 357 explains how Parliament may exercise or delegate State law-making powers while an Article 356 proclamation is operating.", sourceIds:S },
  { qlId:"POL-018-QL-006", difficulty:"Easy", stem:"Which Article deals specifically with Article 19 during certain National Emergencies?", answer:"Article 358", distractors:["Article 356","Article 359","Article 360"], explanation:"Article 358 concerns Article 19 and applies only when the National Emergency is based on war or external aggression.", sourceIds:S },
  { qlId:"POL-018-QL-006", difficulty:"Easy", stem:"Which Article permits suspension of court enforcement of specified Fundamental Rights during Emergency?", answer:"Article 359", distractors:["Article 355","Article 358","Article 360"], explanation:"Article 359 allows the President to suspend the right to move courts for specified Part III rights, except Articles 20 and 21.", sourceIds:S },
  { qlId:"POL-018-QL-006", difficulty:"Easy", stem:"Which Article contains the provisions for a Financial Emergency?", answer:"Article 360", distractors:["Article 352","Article 356","Article 359"], explanation:"Article 360 deals with a Financial Emergency when the financial stability or credit of India or any part is threatened.", sourceIds:S },

  { qlId:"POL-018-QL-007", difficulty:"Medium", stem:"How many Lok Sabha members must sign notice to trigger the special disapproval-sitting rule under Article 352?", answer:"At least one-tenth of total membership", distractors:["At least one-third","At least half","At least two-thirds"], explanation:"Written notice signed by at least one-tenth of Lok Sabha's total membership can trigger a special sitting to consider disapproval.", sourceIds:S },
  { qlId:"POL-018-QL-007", difficulty:"Medium", stem:"Within how many days must the special Lok Sabha sitting on Emergency disapproval be held after valid notice?", answer:"14 days", distractors:["7 days","30 days","60 days"], explanation:"Article 352 requires the special Lok Sabha sitting to be held within fourteen days after the Speaker or President receives valid notice.", sourceIds:S },
  { qlId:"POL-018-QL-007", difficulty:"Medium", stem:"If Lok Sabha is not in session, to whom is Article 352 disapproval notice given?", answer:"President", distractors:["Prime Minister","Rajya Sabha Chairman","Chief Justice of India"], explanation:"When Lok Sabha is not sitting, the written notice for the special disapproval process is given to the President.", sourceIds:S },
  { qlId:"POL-018-QL-007", difficulty:"Medium", stem:"What must the President do if Lok Sabha passes a resolution disapproving continuation of a National Emergency?", answer:"Revoke the proclamation", distractors:["Refer it to Rajya Sabha","Wait six months","Seek Supreme Court approval"], explanation:"Article 352 makes Lok Sabha disapproval effective: the President must revoke the National Emergency proclamation once that resolution is passed.", sourceIds:S },

  { qlId:"POL-018-QL-008", difficulty:"Medium", stem:"During a National Emergency, what additional executive power does Article 353 give the Union?", answer:"Power to give directions to States", distractors:["Power to abolish High Courts","Power to suspend all elections automatically","Power to remove Governors without law"], explanation:"Article 353 lets the Union give directions to States about how their executive power should be exercised during the Emergency.", sourceIds:S },
  { qlId:"POL-018-QL-008", difficulty:"Medium", stem:"During a National Emergency, Parliament's law-making power extends to which normally State-controlled area?", answer:"State List matters", distractors:["Only Union List matters","Only municipal by-laws","Judicial appointments only"], explanation:"Article 353 expands Parliament's law-making reach during Emergency so it can legislate on matters normally reserved for State Legislatures.", sourceIds:S },
  { qlId:"POL-018-QL-008", difficulty:"Medium", stem:"Who may modify the operation of Articles 268 to 279 during a National Emergency?", answer:"President by order", distractors:["Finance Commission","Supreme Court","Rajya Sabha Chairman"], explanation:"Article 354 allows the President to temporarily adjust how specified revenue-sharing provisions operate while the National Emergency continues.", sourceIds:S },
  { qlId:"POL-018-QL-008", difficulty:"Medium", stem:"Must an Article 354 revenue order be laid before Parliament?", answer:"Yes, before each House", distractors:["No","Only before Lok Sabha","Only before Rajya Sabha"], explanation:"Every presidential order under Article 354 must be placed before both Houses of Parliament as soon as possible after it is made.", sourceIds:S },

  { qlId:"POL-018-QL-009", difficulty:"Medium", stem:"Under Article 356, may the President assume functions of the State Government?", answer:"Yes", distractors:["No","Only judicial functions","Only municipal functions"], explanation:"A President's Rule proclamation may allow the President to assume State Government functions and powers normally vested in the Governor or other authorities.", sourceIds:S },
  { qlId:"POL-018-QL-009", difficulty:"Medium", stem:"Can Article 356 suspend constitutional provisions relating to High Courts?", answer:"No", distractors:["Yes","Only for six months","Only with Rajya Sabha approval"], explanation:"High Court provisions are specifically protected under Article 356 and cannot be suspended through a President's Rule proclamation.", sourceIds:S },
  { qlId:"POL-018-QL-009", difficulty:"Medium", stem:"If Lok Sabha is dissolved when Article 356 is proclaimed, which House may first approve it?", answer:"Rajya Sabha", distractors:["No House can approve it","State Assembly","Legislative Council"], explanation:"Rajya Sabha may approve the proclamation during Lok Sabha dissolution, but the reconstituted Lok Sabha must approve it within the constitutional deadline.", sourceIds:S },
  { qlId:"POL-018-QL-009", difficulty:"Medium", stem:"After reconstitution, how long does Lok Sabha get to approve Article 356 if Rajya Sabha approved during dissolution?", answer:"30 days from its first sitting", distractors:["14 days","Two months","Six months"], explanation:"The proclamation ends thirty days after the new Lok Sabha first sits unless Lok Sabha approves it within that thirty-day period.", sourceIds:S },

  { qlId:"POL-018-QL-010", difficulty:"Medium", stem:"What two conditions are required to continue President's Rule beyond one year?", answer:"Relevant National Emergency plus Election Commission certification", distractors:["Governor request plus Supreme Court approval","Rajya Sabha resolution plus Finance Commission advice","Cabinet decision plus State Council approval"], explanation:"Beyond one year, Article 356 requires both the Emergency condition and Election Commission certification that Assembly elections cannot properly be held.", sourceIds:S },
  { qlId:"POL-018-QL-010", difficulty:"Medium", stem:"For President's Rule beyond one year, must a National Emergency cover the whole of India?", answer:"No", distractors:["Yes","Only if Lok Sabha is dissolved","Only for the first extension"], explanation:"The Emergency may operate throughout India or in the whole or relevant part of the State concerned for the Article 356 condition.", sourceIds:S },
  { qlId:"POL-018-QL-010", difficulty:"Medium", stem:"Why is Election Commission certification required for Article 356 continuation beyond one year?", answer:"Because of difficulty in holding Assembly elections", distractors:["Because Parliament lacks quorum","Because State taxes are unpaid","Because the Governor's term expired"], explanation:"The Election Commission must certify that continuing President's Rule is necessary because general elections to the State Assembly face difficulties.", sourceIds:S },
  { qlId:"POL-018-QL-010", difficulty:"Medium", stem:"Does Article 356 permit unlimited six-month extensions if Parliament keeps approving them?", answer:"No", distractors:["Yes","Only in small States","Only if Rajya Sabha agrees"], explanation:"No. The Constitution normally caps President's Rule at three years and adds stricter conditions once the first year has passed.", sourceIds:S },
]);
