export const HIS_CP003_EXPLANATION_OVERRIDES_V1:Readonly<Record<number,string>>={
1:"Rajagriha, also known as Girivraja, was an early capital of Magadha. Magadha later became one of the strongest Mahajanapadas, but this question asks for its earlier political centre.",
2:"Kaushambi was the capital of Vatsa. Keeping Vatsa–Kaushambi separate from Kosala–Sravasti and Surasena–Mathura is useful because these capital pairs are frequently compared.",
3:"Sravasti was the capital of Kosala. It should not be confused with Kaushambi of Vatsa, Mathura of Surasena or Champa of Anga, all of which belong to different Mahajanapadas.",
4:"Mathura was the capital of Surasena. This capital pair belongs to the northern Mahajanapada geography and is distinct from Taxila in Gandhara and Kaushambi in Vatsa.",
5:"Taxila was the capital of Gandhara, an important northwestern Mahajanapada. The pairing is especially useful for distinguishing Gandhara from Kamboja and the states of the middle Ganga region.",
6:"Champa was the capital of Anga. Anga was one of the sixteen Mahajanapadas and lay in the eastern part of the political landscape of the sixth century BCE.",
7:"Panchala had important centres at Ahichhatra and Kampilya, while Kasi was centred on Kasi or Varanasi. The combined pairing brings two Mahajanapada-capital facts into one comparison.",
8:"Kuru was associated with Indraprastha, while Chedi is linked with Sothivati or Banda. These are separate Mahajanapada-capital traditions and should not be mixed with Taxila, Mathura or Champa.",
9:"Matsya was associated with Viratanagar, while Kamboja is linked with Pooncha. Pairing them together helps cover two less frequently tested Mahajanapadas without reducing the question to isolated recall.",
10:"Avanti had important capitals at Ujjain and Mahishmati. This double-capital association distinguishes Avanti from states such as Vatsa, Gandhara and Anga.",
11:"Asmaka was associated with Pratishthana or Paithan near the Godavari region, while Malla had Kusinara as an important capital. The pair also shows the wide geographical spread of the Mahajanapadas.",
12:"Vajji, with its capital at Vaishali, was an important gana-sangha. Unlike a typical monarchy, political authority in such a polity operated through clan councils or assemblies.",
13:"Lumbini in present-day Nepal is associated with the birth of Gautama Buddha. It is the first of the four major places commonly linked with the main stages of Buddha's life.",
14:"Bodh Gaya is associated with Buddha's attainment of enlightenment. It follows Lumbini in the life sequence and comes before the first sermon at Sarnath.",
15:"Sarnath near Varanasi is associated with Buddha's first sermon. This event came after enlightenment at Bodh Gaya and before his death at Kushinagar.",
16:"Buddha's first sermon is traditionally called Dharma-chakra-pravartana, meaning the turning of the wheel of law. The event is associated with Sarnath near Varanasi.",
17:"Kushinagar, also called Kusinara, is associated with the death of Gautama Buddha. It comes after Lumbini, Bodh Gaya and Sarnath in the conventional sequence of major life events.",
18:"The sequence is Lumbini for birth, Bodh Gaya for enlightenment, Sarnath for the first sermon and Kushinagar for death. Keeping the event-place links in order prevents common chronology errors.",
19:"Mahavira is regarded as the twenty-fourth and last Tirthankara of Jainism and was born near Vaishali in present-day Bihar. The answer therefore combines his position in Jain tradition with his birthplace.",
20:"The Jain Triratna consists of right faith, right knowledge and right conduct. These three principles form a central ethical and spiritual framework and should not be confused with the Buddhist Eightfold Path.",
21:"Animal sacrifice is not one of the five great Jain vows. The vows are ahimsa, satya, asteya, brahmacharya and aparigraha, emphasizing restraint and non-violence.",
22:"Anuvratas were milder forms of the great vows intended for Jain householders. They allowed lay followers to practise the ethical principles without following the full severity expected of ascetics.",
23:"Anekantavada teaches that truth can be understood from more than one point of view. It therefore emphasizes the many-sided character of reality rather than insisting that only one perspective can be valid.",
24:"Digambara and Svetambara are the two major Jain sects. Mahayana and Hinayana belong to Buddhist tradition, so the two pairs should not be confused.",
25:"The Buddhist Middle Path rejects both extreme worldly indulgence and extreme asceticism. It presents a balanced approach and is one of the central ideas associated with Buddha's teaching.",
26:"The Four Noble Truths focus on suffering, its cause, the possibility of ending it and the path that leads to its end. They provide the basic diagnosis and goal around which Buddhist teaching is organized.",
27:"In the Four Noble Truths, craving or desire is identified as the cause that must be overcome to end suffering. The teaching links the problem of suffering with a practical path toward liberation.",
28:"Right speech is one element of the Buddhist Eightfold Path. The path also includes forms of right understanding, resolve, action, livelihood, effort, thought and concentration.",
29:"Royal ritual is not part of the Eightfold Path. The Buddhist path is built around ethical conduct, mental discipline and understanding rather than royal sacrifices or political ceremonies.",
30:"The Eightfold Path gives the practical means for overcoming suffering described by the Four Noble Truths. It translates the diagnosis of suffering into a disciplined set of ethical and mental practices.",
31:"Mahavira used Prakrit to spread his teachings to a wider audience. The use of a commonly understood language helped religious ideas reach people beyond specialists in learned traditions.",
32:"Buddha used Pali to communicate his teachings, and the Buddhist sangha admitted women and people from lower varnas. These features helped Buddhism reach a socially broad audience.",
33:"Digambara and Svetambara are the two major sects of Jainism. Mahayana and Hinayana are associated with Buddhist development, so their sectarian identities must be kept distinct.",
34:"The fourth Buddhist council is associated with the reign of Kanishka. This council belongs to later Buddhist institutional history and should not be assigned to rulers such as Bimbisara or Harsha.",
35:"Mahayana was one of the major Buddhist traditions and became associated with wider use of Sanskrit and worship of Buddha in image form. These features distinguish it from the description of Hinayana used here.",
36:"Hinayana is described here as a Buddhist tradition that continued the use of Pali and treated Buddha mainly as a guide. That contrasts with Mahayana's wider Sanskrit use and stronger image worship.",
37:"The growth of towns in the middle Ganga basin from about the sixth century BCE is often called the Second Urbanisation. It was part of a wider period of expanding settlement, trade and political change.",
38:"Improved agriculture, iron tools, larger settlements and growing trade helped some janapadas develop into Mahajanapadas. Political expansion therefore rested partly on wider economic and technological change.",
39:"Punch-marked coins are named for the symbols punched onto their metal surfaces. Their use, mainly in silver and sometimes copper, reflects the expansion of exchange in the period.",
40:"Makkhali Gosala is associated with the Ajivika sect. He should be distinguished from Mahavira of Jainism, Gautama Buddha of Buddhism and Kanishka of later Buddhist history.",
41:"Urban growth, social change and dissatisfaction with elaborate ritualism helped Jainism and Buddhism gain support. Their rise should therefore be understood within a changing economic and social setting.",
42:"Most Mahajanapadas were monarchies, but some such as Vajji were gana-sanghas governed through clan councils or assemblies. The distinction concerns political organization, not the absence of government.",
43:"Gandhara is correctly matched with Taxila. Kosala was associated with Sravasti, Vatsa with Kaushambi and Surasena with Mathura, so those alternative pairings are incorrect.",
44:"Kuru is incorrectly paired with Viratanagar because Kuru's capital was Indraprastha. Viratanagar belonged to Matsya, while Anga–Champa and Vatsa–Kaushambi are correctly matched.",
45:"Bodh Gaya is correctly associated with Buddha's enlightenment. Lumbini marks his birth, Sarnath the first sermon and Kushinagar his death, so each site has a distinct event association.",
46:"Anuvrata means the milder vow followed by Jain householders. Anekantavada concerns many-sided truth, Triratna is the threefold path, and aparigraha is the vow of non-possession.",
47:"Tripitaka, Milindapanho and Buddhacharita are important works connected with Buddhist literary tradition. The other groups contain texts belonging to different religious or historical traditions.",
48:"Buddhism strongly encouraged forms such as stupas, rock-cut caves and paintings. Important examples of Buddhist artistic activity developed at places including Sanchi, Bharhut, Amaravati and Ajanta.",
49:"The broad development ran from more permanent settlements and janapadas toward larger Mahajanapadas. Improved agriculture, iron technology and trade helped support this political expansion.",
50:"The major life sequence is birth at Lumbini, enlightenment at Bodh Gaya, first sermon at Sarnath and death at Kushinagar. The correct answer preserves both chronology and the proper event-place pairings.",
51:"Gandhara represents the northwest, Vajji belongs to the middle Ganga political zone and Asmaka lay near the Godavari region. The set therefore spans three distinct geographical areas.",
52:"Most Mahajanapadas were monarchies, while Vajji was an important gana-sangha using councils or assemblies. This contrast shows that sixth-century BCE states did not all share the same political form.",
53:"Jainism emphasizes the Triratna and the great vows, while Buddhism centres on the Four Noble Truths and Eightfold Path. Both traditions stress ethical discipline but organize their teachings differently.",
54:"Mahavira is linked with Prakrit and the Jain Triratna, while Buddha is linked here with Pali and the Buddhist Eightfold Path. The combined match correctly separates the teachers, languages and doctrines.",
55:"Statements 1 and 2 are correct: sixteen Mahajanapadas emerged and most were monarchies. Statement 3 is false because Vajji was an important gana-sangha, not simply a hereditary monarchy.",
56:"Statements 1 and 3 are correct: Mahavira was the twenty-fourth Tirthankara and anuvratas were milder vows for householders. Statement 2 is false because Triratna means right faith, knowledge and conduct.",
57:"Statements 2 and 3 are correct: the Four Noble Truths address suffering and the Eightfold Path provides a practical path. Statement 1 is false because the Middle Path rejects extreme asceticism.",
58:"Statements 1 and 3 are correct: Lumbini is linked with Buddha's birth and Sarnath with his first sermon. Statement 2 is false because Bodh Gaya is associated with enlightenment.",
59:"Statements 1 and 3 are correct: punch-marked coins reflect expanding exchange and social change helped new religions gain support. Statement 2 is false because the middle Ganga basin saw renewed urban growth.",
60:"Statements 2 and 3 are correct: Mahayana is linked with wider Sanskrit use and the fourth Buddhist council with Kanishka. Statement 1 is false because Mahayana is Buddhist, not a Jain sect.",
};