import { QUESTION_STUDIO_STANDARD_BANK_ONLY_LIFECYCLE_V1 } from "../../../../../question-studio/standard-lifecycle";
import {
  ALGEBRA_QUESTION_STUDIO_DELIVERY_V5_AUTHORITY,
  ALGEBRA_QUESTION_STUDIO_PACKAGE_V5,
  type AlgebraQuestionStudioQuestionV5,
} from "./algebra-question-studio-runtime-v5";

export const ALGEBRA_QUESTION_BANK_ACTIVATION_V1_AUTHORITY =
  "ALGEBRA-QUESTION-STUDIO-BANK-ONLY-ACTIVATION-V1" as const;

const lifecycle = QUESTION_STUDIO_STANDARD_BANK_ONLY_LIFECYCLE_V1;

export const ALGEBRA_QUESTION_STUDIO_BANK_ONLY_PACKAGE_V1 = Object.freeze({
  ...ALGEBRA_QUESTION_STUDIO_PACKAGE_V5,
  lifecycleId: lifecycle.lifecycleId,
  lifecycleStage: lifecycle.stage,
  reviewSurfaceRequired: lifecycle.reviewSurfaceRequired,
  reviewRunPersistenceAllowed: lifecycle.reviewRunPersistenceAllowed,
  canonicalQuestionPersistenceAllowed: lifecycle.canonicalQuestionPersistenceAllowed,
  manualApprovalRequired: lifecycle.manualApprovalRequired,
  questionBankStatus: lifecycle.questionBankStatus,
  questionBankWritable: lifecycle.questionBankWritable,
  questionBankAcceptanceMode: lifecycle.questionBankAcceptanceMode,
  questionBankAcceptanceAuthority: lifecycle.questionBankAcceptanceAuthority,
  testEligibility: lifecycle.testEligibility,
  testEligible: lifecycle.testEligible,
  mockTestEligible: lifecycle.mockTestEligible,
  publiclyPublishable: lifecycle.publiclyPublishable,
  automaticStudentPublication: lifecycle.automaticStudentPublication,
  productionReleaseAuthorized: lifecycle.productionReleaseAuthorized,
  activationAuthority: ALGEBRA_QUESTION_BANK_ACTIVATION_V1_AUTHORITY,
  activationStatus: "ACTIVE_INTERNAL_BANK_ONLY" as const,
  sourceDeliveryAuthority: ALGEBRA_QUESTION_STUDIO_DELIVERY_V5_AUTHORITY,
});

export function buildAlgebraBankOnlyReviewPayload(question: AlgebraQuestionStudioQuestionV5) {
  return Object.freeze({
    text: question.stem,
    stem: question.stem,
    options: [...question.options],
    optionDetails: question.optionDetails,
    correct: question.correctIndex,
    correctIndex: question.correctIndex,
    answer: question.answer,
    canonicalAnswer: question.canonicalAnswer,
    explanation: question.explanation.steps.join("\n"),
    richExplanation: question.explanation,
    renderer: question.renderer,
    difficulty: question.difficultyBand,
    difficultyLabel: question.difficultyBand,
    patternId: question.patternId,
    prototypeId: question.prototypeId,
    variantIndex: question.variantIndex,
    qlId: question.qlId,
    permanentQlId: question.qlId,
    packageId: question.packageId,
    chapterId: "ALGEBRA" as const,
    canonicalProblemId: question.cpId,
    canonicalItemId: question.canonicalItemId,
    questionLanguageId: question.questionLanguageId,
    questionId: question.questionId,
    topic: "Advanced Mathematics" as const,
    subtopic: "Algebra" as const,
    subject: "Quantitative Aptitude" as const,
    language: question.language,
    locale: question.locale,
    seed: question.seed,
    solveMode: question.solveMode,
    examProfile: question.examProfile,
    centralExamProfile: question.centralExamProfile,
    optionCount: question.optionCount,
    runtimeMode: ALGEBRA_QUESTION_STUDIO_PACKAGE_V5.runtimeMode,
    reviewStatus: ALGEBRA_QUESTION_STUDIO_PACKAGE_V5.reviewStatus,
    sourceAuthority: question.sourceAuthority,
    sourceReviewStatus: question.sourceReviewStatus,
    sourceMaturity: question.sourceMaturity,
    sourceStateSeed: question.sourceStateSeed,
    questionStudioRegistrationStatus: "REGISTERED_BANK_ONLY_INTERNAL" as const,
    questionStudioStagingStatus: "REVIEW_QUEUE_ENABLED" as const,
    lifecycleId: lifecycle.lifecycleId,
    lifecycleStage: lifecycle.stage,
    reviewSurfaceRequired: lifecycle.reviewSurfaceRequired,
    reviewRunPersistenceAllowed: lifecycle.reviewRunPersistenceAllowed,
    canonicalQuestionPersistenceAllowed: lifecycle.canonicalQuestionPersistenceAllowed,
    questionBankStatus: lifecycle.questionBankStatus,
    questionBankWritable: lifecycle.questionBankWritable,
    questionBankAcceptanceMode: lifecycle.questionBankAcceptanceMode,
    questionBankAcceptanceAuthority: lifecycle.questionBankAcceptanceAuthority,
    testEligibility: lifecycle.testEligibility,
    testEligible: lifecycle.testEligible,
    mockTestEligible: lifecycle.mockTestEligible,
    publiclyPublishable: lifecycle.publiclyPublishable,
    manualApprovalRequired: lifecycle.manualApprovalRequired,
    automaticStudentPublication: lifecycle.automaticStudentPublication,
    productionReleaseAuthorized: lifecycle.productionReleaseAuthorized,
    integrationAuthority: question.integrationAuthority,
    deliveryAuthority: question.deliveryAuthority,
    bankActivationAuthority: ALGEBRA_QUESTION_BANK_ACTIVATION_V1_AUTHORITY,
    sourceValidation: question.validation,
    generationContext: Object.freeze({
      generationDomain: "quant-v4" as const,
      chapter: "Algebra" as const,
      chapterId: "ALGEBRA" as const,
      packageId: question.packageId,
      canonicalProblemId: question.cpId,
      patternId: question.patternId,
      prototypeId: question.prototypeId,
      variantIndex: question.variantIndex,
      permanentQlId: question.qlId,
      qlId: question.qlId,
      language: question.language,
      locale: question.locale,
      examProfile: question.examProfile,
      centralExamProfile: question.centralExamProfile,
      optionCount: question.optionCount,
      integrationAuthority: question.integrationAuthority,
      deliveryAuthority: question.deliveryAuthority,
      sourceAuthority: question.sourceAuthority,
      sourceStateSeed: question.sourceStateSeed,
      questionStudioDiscoverable: true as const,
      persistenceAllowed: true as const,
      lifecycleId: lifecycle.lifecycleId,
      lifecycleStage: lifecycle.stage,
      reviewSurfaceRequired: lifecycle.reviewSurfaceRequired,
      reviewRunPersistenceAllowed: lifecycle.reviewRunPersistenceAllowed,
      canonicalQuestionPersistenceAllowed: lifecycle.canonicalQuestionPersistenceAllowed,
      questionBankStatus: lifecycle.questionBankStatus,
      questionBankWritable: lifecycle.questionBankWritable,
      questionBankAcceptanceMode: lifecycle.questionBankAcceptanceMode,
      questionBankAcceptanceAuthority: lifecycle.questionBankAcceptanceAuthority,
      testEligibility: lifecycle.testEligibility,
      testEligible: lifecycle.testEligible,
      mockTestEligible: lifecycle.mockTestEligible,
      publiclyPublishable: lifecycle.publiclyPublishable,
      manualApprovalRequired: lifecycle.manualApprovalRequired,
      automaticStudentPublication: lifecycle.automaticStudentPublication,
      productionReleaseAuthorized: lifecycle.productionReleaseAuthorized,
      bankActivationAuthority: ALGEBRA_QUESTION_BANK_ACTIVATION_V1_AUTHORITY,
    }),
  });
}
