import type { AlgPermanentQlId } from "./allocation";
import type { AlgReviewLocale } from "./multilingual-review-v1";
import {
  generateAlgPermanentMultilingualReviewV2Editorial,
} from "./multilingual-review-v2-editorial";
import type { AlgPermanentMultilingualReviewV2Item } from "./multilingual-review-v2";

type Rule = readonly [RegExp, string, string];

const PHRASE_RULES: readonly Rule[] = [
  [/\bthe required value is\b/gi, "आवश्यक मान है", "ਲੋੜੀਂਦਾ ਮਾਨ ਹੈ"],
  [/\bthe required value\b/gi, "आवश्यक मान", "ਲੋੜੀਂਦਾ ਮਾਨ"],
  [/\bthe required expression\b/gi, "आवश्यक व्यंजक", "ਲੋੜੀਂਦਾ ਵਿਆੰਜਕ"],
  [/\bsubstitution in both original equations verifies it\b/gi, "दोनों मूल समीकरणों में प्रतिस्थापन इसकी पुष्टि करता है", "ਦੋਵੇਂ ਮੂਲ ਸਮੀਕਰਨਾਂ ਵਿੱਚ ਪ੍ਰਤਿਸਥਾਪਨ ਇਸ ਦੀ ਪੁਸ਼ਟੀ ਕਰਦਾ ਹੈ"],
  [/\bsubstitution in both original equations verifies the pair\b/gi, "दोनों मूल समीकरणों में प्रतिस्थापन इस युग्म की पुष्टि करता है", "ਦੋਵੇਂ ਮੂਲ ਸਮੀਕਰਨਾਂ ਵਿੱਚ ਪ੍ਰਤਿਸਥਾਪਨ ਇਸ ਜੋੜੇ ਦੀ ਪੁਸ਼ਟੀ ਕਰਦਾ ਹੈ"],
  [/\bsubstitution satisfies all three original equations\b/gi, "प्रतिस्थापन तीनों मूल समीकरणों को संतुष्ट करता है", "ਪ੍ਰਤਿਸਥਾਪਨ ਤਿੰਨੋਂ ਮੂਲ ਸਮੀਕਰਨਾਂ ਨੂੰ ਸੰਤੁਸ਼ਟ ਕਰਦਾ ਹੈ"],
  [/\bStatement I alone is sufficient\b/g, "कथन I अकेला पर्याप्त है", "ਕਥਨ I ਇਕੱਲਾ ਕਾਫ਼ੀ ਹੈ"],
  [/\bStatement II alone is sufficient\b/g, "कथन II अकेला पर्याप्त है", "ਕਥਨ II ਇਕੱਲਾ ਕਾਫ਼ੀ ਹੈ"],
  [/\beither statement alone is sufficient\b/gi, "किसी भी एक कथन से अकेले उत्तर मिल जाता है", "ਕਿਸੇ ਵੀ ਇੱਕ ਕਥਨ ਨਾਲ ਇਕੱਲੇ ਉੱਤਰ ਮਿਲ ਜਾਂਦਾ ਹੈ"],
  [/\bboth statements together are sufficient, but neither alone is sufficient\b/gi, "दोनों कथन साथ में पर्याप्त हैं, पर कोई भी अकेला पर्याप्त नहीं है", "ਦੋਵੇਂ ਕਥਨ ਇਕੱਠੇ ਕਾਫ਼ੀ ਹਨ, ਪਰ ਕੋਈ ਵੀ ਇਕੱਲਾ ਕਾਫ਼ੀ ਨਹੀਂ ਹੈ"],
  [/\beven both statements together are not sufficient\b/gi, "दोनों कथन साथ लेने पर भी पर्याप्त नहीं हैं", "ਦੋਵੇਂ ਕਥਨ ਇਕੱਠੇ ਲੈਣ ਤੇ ਵੀ ਕਾਫ਼ੀ ਨਹੀਂ ਹਨ"],
  [/\bis excluded from the domain\b/gi, "मान्य क्षेत्र से वर्जित है", "ਮਨਜ਼ੂਰ ਖੇਤਰ ਤੋਂ ਬਾਹਰ ਹੈ"],
  [/\bevery real x except\b/gi, "प्रत्येक वास्तविक x, सिवाय", "ਹਰ ਵਾਸਤਵਿਕ x, ਤੋਂ ਇਲਾਵਾ"],
  [/\bthe polynomials\b/gi, "बहुपद", "ਬਹੁਪਦ"],
  [/\bleave the same remainder when divided by\b/gi, "से भाग देने पर समान शेषफल देते हैं", "ਨਾਲ ਭਾਗ ਦੇਣ ਤੇ ਇੱਕੋ ਬਾਕੀ ਦਿੰਦੇ ਹਨ"],
  [/\bleaves remainder\b/gi, "शेषफल देता है", "ਬਾਕੀ ਦਿੰਦਾ ਹੈ"],
  [/\bwhen divided by\b/gi, "से भाग देने पर", "ਨਾਲ ਭਾਗ ਦੇਣ ਤੇ"],
  [/\bthe common remainder\b/gi, "समान शेषफल", "ਸਾਂਝਾ ਬਾਕੀ"],
  [/\band the common remainder\b/gi, "और समान शेषफल", "ਅਤੇ ਸਾਂਝਾ ਬਾਕੀ"],
  [/\band m\b/g, "और m", "ਅਤੇ m"],
  [/\bthe equation\b/gi, "समीकरण", "ਸਮੀਕਰਨ"],
  [/\bcannot be established\b/gi, "निर्धारित नहीं किया जा सकता", "ਨਿਰਧਾਰਤ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ"],
  [/\bopens upward\b/gi, "ऊपर खुलता है", "ਉੱਪਰ ਖੁੱਲ੍ਹਦਾ ਹੈ"],
  [/\bopens downward\b/gi, "नीचे खुलता है", "ਹੇਠਾਂ ਖੁੱਲ੍ਹਦਾ ਹੈ"],
  [/\blie strictly between the roots\b/gi, "दोनों मूलों के बीच, सिरों को छोड़कर, आते हैं", "ਦੋਵੇਂ ਮੂਲਾਂ ਦੇ ਵਿਚਕਾਰ, ਸਿਰਿਆਂ ਤੋਂ ਬਿਨਾਂ, ਆਉਂਦੇ ਹਨ"],
  [/\blie between the roots including both endpoints\b/gi, "दोनों मूलों के बीच, दोनों सिरों सहित, आते हैं", "ਦੋਵੇਂ ਮੂਲਾਂ ਦੇ ਵਿਚਕਾਰ, ਦੋਵੇਂ ਸਿਰਿਆਂ ਸਮੇਤ, ਆਉਂਦੇ ਹਨ"],
  [/\blie between the roots\b/gi, "दोनों मूलों के बीच आते हैं", "ਦੋਵੇਂ ਮੂਲਾਂ ਦੇ ਵਿਚਕਾਰ ਆਉਂਦੇ ਹਨ"],
  [/\bincluding both endpoints\b/gi, "दोनों सिरों सहित", "ਦੋਵੇਂ ਸਿਰਿਆਂ ਸਮੇਤ"],
  [/\bstrictly between\b/gi, "सख्ती से बीच में", "ਸਖ਼ਤੀ ਨਾਲ ਵਿਚਕਾਰ"],
  [/\bcounting integers in that interval gives\b/gi, "उस अंतराल के पूर्णांक गिनने पर", "ਉਸ ਅੰਤਰਾਲ ਦੇ ਪੂਰਨ ਅੰਕ ਗਿਣਣ ਤੇ"],
  [/\bcounting only the integers contained in that exact interval gives\b/gi, "उस सटीक अंतराल के केवल पूर्णांक गिनने पर", "ਉਸ ਸਹੀ ਅੰਤਰਾਲ ਦੇ ਕੇਵਲ ਪੂਰਨ ਅੰਕ ਗਿਣਣ ਤੇ"],
  [/\ba positive multiple of\b/gi, "का धनात्मक गुणज", "ਦਾ ਧਨਾਤਮਕ ਗੁਣਜ"],
  [/\ba negative multiple of\b/gi, "का ऋणात्मक गुणज", "ਦਾ ਰਣਾਤਮਕ ਗੁਣਜ"],
  [/\bnever negative\b/gi, "कभी ऋणात्मक नहीं", "ਕਦੇ ਰਣਾਤਮਕ ਨਹੀਂ"],
  [/\bnever positive\b/gi, "कभी धनात्मक नहीं", "ਕਦੇ ਧਨਾਤਮਕ ਨਹੀਂ"],
  [/\bfor all real x\b/gi, "प्रत्येक वास्तविक x के लिए", "ਹਰ ਵਾਸਤਵਿਕ x ਲਈ"],
  [/\ban absolute value is greater than zero everywhere except where the inside expression equals zero\b/gi, "परम मान हर जगह शून्य से बड़ा होता है, सिवाय उस स्थान के जहाँ अंदर का व्यंजक शून्य हो", "ਪਰਮ ਮਾਨ ਹਰ ਥਾਂ ਸਿਫ਼ਰ ਤੋਂ ਵੱਡਾ ਹੁੰਦਾ ਹੈ, ਸਿਵਾਏ ਉਸ ਥਾਂ ਦੇ ਜਿੱਥੇ ਅੰਦਰਲਾ ਵਿਆੰਜਕ ਸਿਫ਼ਰ ਹੋਵੇ"],
  [/\ban absolute value is positive everywhere except where the inside expression equals zero\b/gi, "परम मान हर जगह धनात्मक होता है, सिवाय उस स्थान के जहाँ अंदर का व्यंजक शून्य हो", "ਪਰਮ ਮਾਨ ਹਰ ਥਾਂ ਧਨਾਤਮਕ ਹੁੰਦਾ ਹੈ, ਸਿਵਾਏ ਉਸ ਥਾਂ ਦੇ ਜਿੱਥੇ ਅੰਦਰਲਾ ਵਿਆੰਜਕ ਸਿਫ਼ਰ ਹੋਵੇ"],
  [/\bexcluding that single root gives\b/gi, "उस एक मूल को छोड़ने पर", "ਉਸ ਇੱਕ ਮੂਲ ਨੂੰ ਛੱਡਣ ਤੇ"],
  [/\bthe absolute value is at least\b/gi, "परम मान कम-से-कम", "ਪਰਮ ਮਾਨ ਘੱਟੋ-ਘੱਟ"],
  [/\bthe absolute value is greater than\b/gi, "परम मान से बड़ा", "ਪਰਮ ਮਾਨ ਤੋਂ ਵੱਡਾ"],
  [/\bwhen the inside expression lies beyond either boundary\b/gi, "जब अंदर का व्यंजक किसी एक सीमा के बाहर हो", "ਜਦੋਂ ਅੰਦਰਲਾ ਵਿਆੰਜਕ ਕਿਸੇ ਇੱਕ ਸੀਮਾ ਤੋਂ ਬਾਹਰ ਹੋਵੇ"],
  [/\bthe inside expression\b/gi, "अंदर का व्यंजक", "ਅੰਦਰਲਾ ਵਿਆੰਜਕ"],
  [/\blies beyond either boundary\b/gi, "किसी एक सीमा के बाहर हो", "ਕਿਸੇ ਇੱਕ ਸੀਮਾ ਤੋਂ ਬਾਹਰ ਹੋਵੇ"],
  [/\beverywhere except where\b/gi, "हर जगह, सिवाय जहाँ", "ਹਰ ਥਾਂ, ਸਿਵਾਏ ਜਿੱਥੇ"],
  [/\bat least\b/gi, "कम-से-कम", "ਘੱਟੋ-ਘੱਟ"],
  [/\bat most\b/gi, "अधिकतम", "ਵੱਧ ਤੋਂ ਵੱਧ"],
  [/\bgreater than\b/gi, "से बड़ा", "ਤੋਂ ਵੱਡਾ"],
  [/\bless than\b/gi, "से छोटा", "ਤੋਂ ਛੋਟਾ"],
  [/\bthe relation\b/gi, "संबंध", "ਸੰਬੰਧ"],
  [/\bthe relationship\b/gi, "संबंध", "ਸੰਬੰਧ"],
  [/\bthe original equation\b/gi, "मूल समीकरण", "ਮੂਲ ਸਮੀਕਰਨ"],
  [/\bthe original equations\b/gi, "मूल समीकरण", "ਮੂਲ ਸਮੀਕਰਨ"],
  [/\bthe original denominator\b/gi, "मूल हर", "ਮੂਲ ਹਰ"],
  [/\bthe original denominators\b/gi, "मूल हर", "ਮੂਲ ਹਰ"],
  [/\bthe original domain\b/gi, "मूल मान्य क्षेत्र", "ਮੂਲ ਮਨਜ਼ੂਰ ਖੇਤਰ"],
  [/\bthe denominator\b/gi, "हर", "ਹਰ"],
  [/\bthe numerator\b/gi, "अंश", "ਅੰਸ਼"],
  [/\bthe first equation\b/gi, "पहला समीकरण", "ਪਹਿਲਾ ਸਮੀਕਰਨ"],
  [/\bthe second equation\b/gi, "दूसरा समीकरण", "ਦੂਜਾ ਸਮੀਕਰਨ"],
  [/\bthe two equations\b/gi, "दोनों समीकरण", "ਦੋਵੇਂ ਸਮੀਕਰਨ"],
  [/\bthe known terms\b/gi, "ज्ञात पद", "ਪਤਾ ਪਦ"],
  [/\bthe given relation\b/gi, "दिया गया संबंध", "ਦਿੱਤਾ ਸੰਬੰਧ"],
  [/\bthe given value\b/gi, "दिया गया मान", "ਦਿੱਤਾ ਮਾਨ"],
  [/\bthe given values\b/gi, "दिए गए मान", "ਦਿੱਤੇ ਮਾਨ"],
  [/\bthe factorisation\b/gi, "गुणनखंड", "ਗੁਣਨਖੰਡ"],
  [/\bthe factorization\b/gi, "गुणनखंड", "ਗੁਣਨਖੰਡ"],
  [/\bthe bracket\b/gi, "कोष्ठक", "ਕੋਠੀ"],
  [/\bthe calculation\b/gi, "गणना", "ਗਣਨਾ"],
  [/\bthe interval\b/gi, "अंतराल", "ਅੰਤਰਾਲ"],
  [/\bthe endpoints\b/gi, "सिरे", "ਸਿਰੇ"],
  [/\bthe roots\b/gi, "मूल", "ਮੂਲ"],
  [/\bthe root\b/gi, "मूल", "ਮੂਲ"],
  [/\bthe values\b/gi, "मान", "ਮਾਨ"],
  [/\bthe value\b/gi, "मान", "ਮਾਨ"],
  [/\bthe system\b/gi, "समीकरण-तंत्र", "ਸਮੀਕਰਨ-ਤੰਤਰ"],
  [/\bthe line\b/gi, "रेखा", "ਰੇਖਾ"],
  [/\bthe lines\b/gi, "रेखाएँ", "ਰੇਖਾਵਾਂ"],
  [/\bthe constants\b/gi, "अचर", "ਅਚਲ"],
  [/\bthe coefficients\b/gi, "गुणांक", "ਗੁਣਾਂਕ"],
  [/\bthe coefficient\b/gi, "गुणांक", "ਗੁਣਾਂਕ"],
  [/\bthe expression\b/gi, "व्यंजक", "ਵਿਆੰਜਕ"],
  [/\bthe inequality\b/gi, "असमानता", "ਅਸਮਾਨਤਾ"],
  [/\bthe polynomial\b/gi, "बहुपद", "ਬਹੁਪਦ"],
  [/\bthe remainder\b/gi, "शेषफल", "ਬਾਕੀ"],
  [/\bthe factor\b/gi, "गुणनखंड", "ਗੁਣਨਖੰਡ"],
  [/\bthe product\b/gi, "गुणनफल", "ਗੁਣਨਫਲ"],
  [/\bthe sum\b/gi, "योग", "ਜੋੜ"],
  [/\bthe square\b/gi, "वर्ग", "ਵਰਗ"],
  [/\bthe cube\b/gi, "घन", "ਘਣ"],
  [/\bthe solution\b/gi, "हल", "ਹੱਲ"],
  [/\bthe domain\b/gi, "मान्य क्षेत्र", "ਮਨਜ਼ੂਰ ਖੇਤਰ"],
  [/\bthis value\b/gi, "यह मान", "ਇਹ ਮਾਨ"],
  [/\bthat value\b/gi, "वह मान", "ਉਹ ਮਾਨ"],
  [/\bthis relation\b/gi, "यह संबंध", "ਇਹ ਸੰਬੰਧ"],
  [/\bthat relation\b/gi, "वह संबंध", "ਉਹ ਸੰਬੰਧ"],
  [/\bthis equation\b/gi, "यह समीकरण", "ਇਹ ਸਮੀਕਰਨ"],
  [/\bthis expression\b/gi, "यह व्यंजक", "ਇਹ ਵਿਆੰਜਕ"],
  [/\bthis interval\b/gi, "यह अंतराल", "ਇਹ ਅੰਤਰਾਲ"],
  [/\bexact form\b/gi, "सटीक रूप", "ਸਹੀ ਰੂਪ"],
  [/\bdecimal approximation\b/gi, "दशमलव सन्निकटन", "ਦਸ਼ਮਲਵ ਅਨੁਮਾਨ"],
  [/\bpairwise products\b/gi, "युग्म गुणनफल", "ਜੋੜਾ ਗੁਣਨਫਲ"],
  [/\bpairwise-product sum\b/gi, "युग्म-गुणनफल-योग", "ਜੋੜਾ-ਗੁਣਨਫਲ-ਜੋੜ"],
  [/\broot sum\b/gi, "मूल-योग", "ਮੂਲ-ਜੋੜ"],
  [/\broot product\b/gi, "मूल-गुणनफल", "ਮੂਲ-ਗੁਣਨਫਲ"],
];

const WORD_RULES: readonly Rule[] = [
  [/\bFind\b/g, "ज्ञात कीजिए", "ਪਤਾ ਕਰੋ"], [/\bSolve\b/g, "हल कीजिए", "ਹੱਲ ਕਰੋ"], [/\bCompare\b/g, "तुलना कीजिए", "ਤੁਲਨਾ ਕਰੋ"],
  [/\bFactorise\b/g, "गुणनखंड कीजिए", "ਗੁਣਨਖੰਡ ਕਰੋ"], [/\bClassify\b/g, "प्रकार बताइए", "ਕਿਸਮ ਦੱਸੋ"],
  [/\band\b/gi, "और", "ਅਤੇ"], [/\bor\b/gi, "या", "ਜਾਂ"], [/\bbut\b/gi, "लेकिन", "ਪਰ"], [/\bso\b/gi, "इसलिए", "ਇਸ ਲਈ"],
  [/\bthen\b/gi, "तब", "ਤਦ"], [/\bbecause\b/gi, "क्योंकि", "ਕਿਉਂਕਿ"], [/\bsince\b/gi, "क्योंकि", "ਕਿਉਂਕਿ"],
  [/\btherefore\b/gi, "अतः", "ਇਸ ਲਈ"], [/\bhence\b/gi, "अतः", "ਇਸ ਲਈ"], [/\bthus\b/gi, "इसलिए", "ਇਸ ਲਈ"],
  [/\bfirst\b/gi, "पहले", "ਪਹਿਲਾਂ"], [/\bsecond\b/gi, "दूसरा", "ਦੂਜਾ"], [/\bboth\b/gi, "दोनों", "ਦੋਵੇਂ"], [/\beach\b/gi, "प्रत्येक", "ਹਰ"],
  [/\bevery\b/gi, "प्रत्येक", "ਹਰ"], [/\ball\b/gi, "सभी", "ਸਾਰੇ"], [/\beither\b/gi, "किसी एक", "ਕਿਸੇ ਇੱਕ"], [/\bneither\b/gi, "कोई भी नहीं", "ਕੋਈ ਵੀ ਨਹੀਂ"],
  [/\balone\b/gi, "अकेला", "ਇਕੱਲਾ"], [/\btogether\b/gi, "साथ में", "ਇਕੱਠੇ"], [/\beven\b/gi, "भी", "ਵੀ"], [/\banother\b/gi, "दूसरी", "ਦੂਜੀ"],
  [/\bsame\b/gi, "समान", "ਇੱਕੋ"], [/\bdifferent\b/gi, "अलग", "ਵੱਖ"], [/\bdistinct\b/gi, "भिन्न", "ਵੱਖ"], [/\bcommon\b/gi, "समान", "ਸਾਂਝਾ"],
  [/\bexact\b/gi, "सटीक", "ਸਹੀ"], [/\bexactly\b/gi, "ठीक", "ਠੀਕ"], [/\breal\b/gi, "वास्तविक", "ਵਾਸਤਵਿਕ"], [/\binteger\b/gi, "पूर्णांक", "ਪੂਰਨ ਅੰਕ"],
  [/\bintegers\b/gi, "पूर्णांक", "ਪੂਰਨ ਅੰਕ"], [/\bfractional\b/gi, "भिन्नात्मक", "ਭਿੰਨਾਤਮਕ"], [/\bfraction\b/gi, "भिन्न", "ਭਿੰਨ"],
  [/\blinear\b/gi, "रैखिक", "ਰੇਖੀ"], [/\bquadratic\b/gi, "द्विघात", "ਦੋ-ਘਾਤੀ"], [/\bcubic\b/gi, "घन", "ਘਣ"],
  [/\bpositive\b/gi, "धनात्मक", "ਧਨਾਤਮਕ"], [/\bnegative\b/gi, "ऋणात्मक", "ਰਣਾਤਮਕ"], [/\bnonnegative\b/gi, "ऋणेतर", "ਗੈਰ-ਰਣਾਤਮਕ"],
  [/\bnonpositive\b/gi, "धनेतर", "ਗੈਰ-ਧਨਾਤਮਕ"], [/\bnonzero\b/gi, "गैर-शून्य", "ਗੈਰ-ਸਿਫ਼ਰ"], [/\bzero\b/gi, "शून्य", "ਸਿਫ਼ਰ"],
  [/\bperfect\b/gi, "पूर्ण", "ਪੂਰਨ"], [/\bsquare\b/gi, "वर्ग", "ਵਰਗ"], [/\bsquares\b/gi, "वर्ग", "ਵਰਗ"], [/\bcube\b/gi, "घन", "ਘਣ"],
  [/\broot\b/gi, "मूल", "ਮੂਲ"], [/\broots\b/gi, "मूल", "ਮੂਲ"], [/\bsolution\b/gi, "हल", "ਹੱਲ"], [/\bsolutions\b/gi, "हल", "ਹੱਲ"],
  [/\bvalue\b/gi, "मान", "ਮਾਨ"], [/\bvalues\b/gi, "मान", "ਮਾਨ"], [/\bterm\b/gi, "पद", "ਪਦ"], [/\bterms\b/gi, "पद", "ਪਦ"],
  [/\bcoefficient\b/gi, "गुणांक", "ਗੁਣਾਂਕ"], [/\bcoefficients\b/gi, "गुणांक", "ਗੁਣਾਂਕ"], [/\bconstant\b/gi, "अचर", "ਅਚਲ"], [/\bconstants\b/gi, "अचर", "ਅਚਲ"],
  [/\bequation\b/gi, "समीकरण", "ਸਮੀਕਰਨ"], [/\bequations\b/gi, "समीकरण", "ਸਮੀਕਰਨ"], [/\binequality\b/gi, "असमानता", "ਅਸਮਾਨਤਾ"],
  [/\bexpression\b/gi, "व्यंजक", "ਵਿਆੰਜਕ"], [/\bpolynomial\b/gi, "बहुपद", "ਬਹੁਪਦ"], [/\bdenominator\b/gi, "हर", "ਹਰ"], [/\bnumerator\b/gi, "अंश", "ਅੰਸ਼"],
  [/\bremainder\b/gi, "शेषफल", "ਬਾਕੀ"], [/\bfactor\b/gi, "गुणनखंड", "ਗੁਣਨਖੰਡ"], [/\bfactors\b/gi, "गुणनखंड", "ਗੁਣਨਖੰਡ"],
  [/\bproduct\b/gi, "गुणनफल", "ਗੁਣਨਫਲ"], [/\bsum\b/gi, "योग", "ਜੋੜ"], [/\bdifference\b/gi, "अंतर", "ਅੰਤਰ"],
  [/\binterval\b/gi, "अंतराल", "ਅੰਤਰਾਲ"], [/\bboundary\b/gi, "सीमा", "ਸੀਮਾ"], [/\bboundaries\b/gi, "सीमाएँ", "ਸੀਮਾਵਾਂ"], [/\bendpoints\b/gi, "सिरे", "ਸਿਰੇ"],
  [/\bdomain\b/gi, "मान्य क्षेत्र", "ਮਨਜ਼ੂਰ ਖੇਤਰ"], [/\brelation\b/gi, "संबंध", "ਸੰਬੰਧ"], [/\brelationship\b/gi, "संबंध", "ਸੰਬੰਧ"],
  [/\bstatement\b/gi, "कथन", "ਕਥਨ"], [/\bstatements\b/gi, "कथन", "ਕਥਨ"], [/\bcase\b/gi, "स्थिति", "ਸਥਿਤੀ"], [/\bcases\b/gi, "स्थितियाँ", "ਸਥਿਤੀਆਂ"],
  [/\bpair\b/gi, "युग्म", "ਜੋੜਾ"], [/\bpairs\b/gi, "युग्म", "ਜੋੜੇ"], [/\bline\b/gi, "रेखा", "ਰੇਖਾ"], [/\blines\b/gi, "रेखाएँ", "ਰੇਖਾਵਾਂ"],
  [/\bvertex\b/gi, "शीर्ष", "ਸਿਖਰ"], [/\baxis\b/gi, "अक्ष", "ਅਕਸ"], [/\bdistance\b/gi, "दूरी", "ਦੂਰੀ"], [/\bmidpoint\b/gi, "मध्यबिंदु", "ਮੱਧ-ਬਿੰਦੂ"],
  [/\bparameter\b/gi, "पैरामीटर", "ਪੈਰਾਮੀਟਰ"], [/\bunknown\b/gi, "अज्ञात", "ਅਣਜਾਣ"], [/\bunknowns\b/gi, "अज्ञात", "ਅਣਜਾਣ"],
  [/\bcalculation\b/gi, "गणना", "ਗਣਨਾ"], [/\bevaluation\b/gi, "गणना", "ਗਣਨਾ"], [/\bapproximation\b/gi, "सन्निकटन", "ਅਨੁਮਾਨ"],
  [/\bsubstitute\b/gi, "मान रखें", "ਮਾਨ ਰੱਖੋ"], [/\bsubstitution\b/gi, "प्रतिस्थापन", "ਪ੍ਰਤਿਸਥਾਪਨ"], [/\bsolve\b/gi, "हल करें", "ਹੱਲ ਕਰੋ"],
  [/\bsolving\b/gi, "हल करने पर", "ਹੱਲ ਕਰਨ ਤੇ"], [/\bevaluate\b/gi, "गणना करें", "ਗਣਨਾ ਕਰੋ"], [/\bexpand\b/gi, "विस्तार करें", "ਵਿਸਥਾਰ ਕਰੋ"],
  [/\bexpanding\b/gi, "विस्तार करने पर", "ਵਿਸਥਾਰ ਕਰਨ ਤੇ"], [/\bsimplify\b/gi, "सरल करें", "ਸਰਲ ਕਰੋ"], [/\bsimplifies\b/gi, "सरल होकर", "ਸਰਲ ਹੋ ਕੇ"],
  [/\bcombine\b/gi, "मिलाएँ", "ਮਿਲਾਓ"], [/\bcombining\b/gi, "मिलाने पर", "ਮਿਲਾਉਣ ਤੇ"], [/\bcollect\b/gi, "एकत्र करें", "ਇਕੱਠੇ ਕਰੋ"], [/\bcollecting\b/gi, "एकत्र करने पर", "ਇਕੱਠੇ ਕਰਨ ਤੇ"],
  [/\bdivide\b/gi, "भाग दें", "ਭਾਗ ਦਿਓ"], [/\bdividing\b/gi, "भाग देने पर", "ਭਾਗ ਦੇਣ ਤੇ"], [/\bdivision\b/gi, "भाग", "ਭਾਗ"], [/\bmultiply\b/gi, "गुणा करें", "ਗੁਣਾ ਕਰੋ"],
  [/\bmultiplying\b/gi, "गुणा करने पर", "ਗੁਣਾ ਕਰਨ ਤੇ"], [/\bsquaring\b/gi, "वर्ग करने पर", "ਵਰਗ ਕਰਨ ਤੇ"], [/\bcreates\b/gi, "बनाता है", "ਬਣਾਉਂਦਾ ਹੈ"],
  [/\bbecomes\b/gi, "बन जाता है", "ਬਣ ਜਾਂਦਾ ਹੈ"], [/\bgives\b/gi, "मिलता है", "ਮਿਲਦਾ ਹੈ"], [/\bgiving\b/gi, "जिससे मिलता है", "ਜਿਸ ਤੋਂ ਮਿਲਦਾ ਹੈ"],
  [/\bconfirms\b/gi, "पुष्टि करता है", "ਪੁਸ਼ਟੀ ਕਰਦਾ ਹੈ"], [/\bverifies\b/gi, "पुष्टि करता है", "ਪੁਸ਼ਟੀ ਕਰਦਾ ਹੈ"], [/\bsatisfies\b/gi, "संतुष्ट करता है", "ਸੰਤੁਸ਼ਟ ਕਰਦਾ ਹੈ"],
  [/\breject\b/gi, "अस्वीकार करें", "ਰੱਦ ਕਰੋ"], [/\bexcluded\b/gi, "वर्जित", "ਮਨਾਹੀ"], [/\binvalid\b/gi, "अमान्य", "ਅਮਾਨਯ"], [/\bvalid\b/gi, "मान्य", "ਮਨਜ਼ੂਰ"],
  [/\bdefined\b/gi, "परिभाषित", "ਪਰਿਭਾਸ਼ਿਤ"], [/\bproportional\b/gi, "समानुपाती", "ਅਨੁਪਾਤੀ"], [/\bratio\b/gi, "अनुपात", "ਅਨੁਪਾਤ"],
  [/\bparallel\b/gi, "समांतर", "ਸਮਾਂਤਰ"], [/\bindependent\b/gi, "स्वतंत्र", "ਸੁਤੰਤਰ"], [/\bconsistent\b/gi, "संगत", "ਸੰਗਤ"],
  [/\bsufficient\b/gi, "पर्याप्त", "ਕਾਫ਼ੀ"], [/\binsufficient\b/gi, "अपर्याप्त", "ਅਪਰਿਆਪਤ"], [/\bunique\b/gi, "अद्वितीय", "ਇਕੋ"],
  [/\bpossible\b/gi, "संभव", "ਸੰਭਵ"], [/\ballowed\b/gi, "मान्य", "ਮਨਜ਼ੂਰ"], [/\badmissible\b/gi, "मान्य", "ਮਨਜ਼ੂਰ"],
  [/\blarger\b/gi, "बड़ा", "ਵੱਡਾ"], [/\bsmaller\b/gi, "छोटा", "ਛੋਟਾ"], [/\blargest\b/gi, "सबसे बड़ा", "ਸਭ ਤੋਂ ਵੱਡਾ"], [/\bsmallest\b/gi, "सबसे छोटा", "ਸਭ ਤੋਂ ਛੋਟਾ"],
  [/\bminimum\b/gi, "न्यूनतम", "ਘੱਟੋ-ਘੱਟ"], [/\bmaximum\b/gi, "अधिकतम", "ਵੱਧੋ-ਵੱਧ"], [/\bleast\b/gi, "सबसे छोटा", "ਸਭ ਤੋਂ ਘੱਟ"],
  [/\bbound\b/gi, "सीमा", "ਸੀਮਾ"], [/\battainable\b/gi, "प्राप्त होने योग्य", "ਪ੍ਰਾਪਤ ਹੋਣ ਯੋਗ"], [/\breachable\b/gi, "प्राप्त होने योग्य", "ਪ੍ਰਾਪਤ ਹੋਣ ਯੋਗ"],
  [/\bactual\b/gi, "वास्तविक", "ਅਸਲ"], [/\blower\b/gi, "निचला", "ਹੇਠਲਾ"], [/\bupper\b/gi, "ऊपरी", "ਉੱਪਰਲਾ"],
  [/\binside\b/gi, "अंदर", "ਅੰਦਰ"], [/\bbeyond\b/gi, "बाहर", "ਬਾਹਰ"], [/\bbetween\b/gi, "बीच", "ਵਿਚਕਾਰ"], [/\beverywhere\b/gi, "हर जगह", "ਹਰ ਥਾਂ"],
  [/\bexcept\b/gi, "सिवाय", "ਤੋਂ ਇਲਾਵਾ"], [/\bexcluding\b/gi, "छोड़कर", "ਛੱਡ ਕੇ"], [/\bsingle\b/gi, "एक", "ਇੱਕ"], [/\bmultiple\b/gi, "गुणज", "ਗੁਣਜ"],
  [/\bstrict\b/gi, "कठोर", "ਸਖ਼ਤ"], [/\bstrictly\b/gi, "सख्ती से", "ਸਖ਼ਤੀ ਨਾਲ"], [/\btrue\b/gi, "सत्य", "ਸੱਚ"], [/\bfalse\b/gi, "असत्य", "ਗਲਤ"],
  [/\bneeded\b/gi, "आवश्यक", "ਲੋੜੀਂਦਾ"], [/\bneed\b/gi, "आवश्यकता", "ਲੋੜ"], [/\bremain\b/gi, "रहते हैं", "ਰਹਿੰਦੇ ਹਨ"], [/\bremains\b/gi, "रहता है", "ਰਹਿੰਦਾ ਹੈ"],
  [/\bstay\b/gi, "रहे", "ਰਹੇ"], [/\blies\b/gi, "हो", "ਹੋਵੇ"], [/\blie\b/gi, "हों", "ਹੋਣ"], [/\baffect\b/gi, "प्रभावित करता", "ਅਸਰ ਕਰਦਾ"],
  [/\bscalar\b/gi, "अदिश", "ਅਦਿਸ਼"], [/\bzeros\b/gi, "शून्य-बिंदु", "ਸਿਫ਼ਰ-ਬਿੰਦੂ"], [/\bcandidates\b/gi, "संभावित मान", "ਸੰਭਾਵਿਤ ਮਾਨ"], [/\bcandidate\b/gi, "संभावित मान", "ਸੰਭਾਵਿਤ ਮਾਨ"],
  [/\bcross-multiplied\b/gi, "क्रॉस-गुणा किया", "ਕ੍ਰਾਸ-ਗੁਣਾ ਕੀਤਾ"], [/\bcross-multiplying\b/gi, "क्रॉस-गुणा करने पर", "ਕ੍ਰਾਸ-ਗੁਣਾ ਕਰਨ ਤੇ"],
  [/\bnote\b/gi, "ध्यान दें", "ਧਿਆਨ ਦਿਓ"], [/\bbring\b/gi, "ले जाएँ", "ਲਿਜਾਓ"], [/\bside\b/gi, "ओर", "ਪਾਸੇ"], [/\bsides\b/gi, "पक्ष", "ਪਾਸੇ"],
  [/\bopposite\b/gi, "विपरीत", "ਵੱਖਰੇ"], [/\bbracket\b/gi, "कोष्ठक", "ਕੋਠੀ"], [/\bbracketed\b/gi, "कोष्ठक वाला", "ਕੋਠੀ ਵਾਲਾ"],
  [/\boutside\b/gi, "बाहर", "ਬਾਹਰ"], [/\bback\b/gi, "वापस", "ਵਾਪਸ"], [/\breproduces\b/gi, "फिर से देता है", "ਮੁੜ ਦਿੰਦਾ ਹੈ"], [/\bcomplete\b/gi, "पूर्ण", "ਪੂਰਾ"],
  [/\busing\b/gi, "उपयोग करने पर", "ਵਰਤਣ ਤੇ"], [/\buse\b/gi, "उपयोग करें", "ਵਰਤੋ"], [/\bset\b/gi, "रखें", "ਰੱਖੋ"], [/\binvert\b/gi, "व्युत्क्रम लें", "ਵਿਉਤਕ੍ਰਮ ਲਓ"],
  [/\bmove\b/gi, "ले जाएँ", "ਲਿਜਾਓ"], [/\brearrange\b/gi, "पुनर्व्यवस्थित करें", "ਦੁਬਾਰਾ ਵਿਵਸਥਿਤ ਕਰੋ"], [/\bapply\b/gi, "लगाएँ", "ਲਗਾਓ"],
  [/\brequired\b/gi, "आवश्यक", "ਲੋੜੀਂਦਾ"], [/\bgiven\b/gi, "दिया गया", "ਦਿੱਤਾ"], [/\bknown\b/gi, "ज्ञात", "ਪਤਾ"], [/\boriginal\b/gi, "मूल", "ਮੂਲ"],
  [/\bdirect\b/gi, "सीधा", "ਸਿੱਧਾ"], [/\bdirectly\b/gi, "सीधे", "ਸਿੱਧਾ"], [/\bcondition\b/gi, "शर्त", "ਸ਼ਰਤ"], [/\bconditions\b/gi, "शर्तें", "ਸ਼ਰਤਾਂ"],
  [/\bwithout\b/gi, "बिना", "ਬਿਨਾਂ"], [/\bwith\b/gi, "के साथ", "ਨਾਲ"], [/\bfrom\b/gi, "से", "ਤੋਂ"], [/\binto\b/gi, "में", "ਵਿੱਚ"],
  [/\bfor\b/gi, "के लिए", "ਲਈ"], [/\bwhen\b/gi, "जब", "ਜਦੋਂ"], [/\bwhile\b/gi, "जबकि", "ਜਦਕਿ"], [/\bafter\b/gi, "के बाद", "ਤੋਂ ਬਾਅਦ"],
  [/\bbefore\b/gi, "से पहले", "ਤੋਂ ਪਹਿਲਾਂ"], [/\bwhere\b/gi, "जहाँ", "ਜਿੱਥੇ"], [/\bwhich\b/gi, "जो", "ਜੋ"], [/\bwhat\b/gi, "क्या", "ਕੀ"],
  [/\bonly\b/gi, "केवल", "ਕੇਵਲ"], [/\bnot\b/gi, "नहीं", "ਨਹੀਂ"], [/\bno\b/gi, "कोई नहीं", "ਕੋਈ ਨਹੀਂ"], [/\bcan\b/gi, "सकता है", "ਸਕਦਾ ਹੈ"],
  [/\bcannot\b/gi, "नहीं किया जा सकता", "ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ"], [/\bmust\b/gi, "अवश्य", "ਲਾਜ਼ਮੀ"], [/\bshould\b/gi, "चाहिए", "ਚਾਹੀਦਾ ਹੈ"],
  [/\bis\b/gi, "है", "ਹੈ"], [/\bare\b/gi, "हैं", "ਹਨ"], [/\bbe\b/gi, "हो", "ਹੋਵੇ"], [/\bhas\b/gi, "है", "ਹੈ"], [/\bhave\b/gi, "हैं", "ਹਨ"],
  [/\bdoes\b/gi, "", ""], [/\bdo\b/gi, "", ""], [/\bdid\b/gi, "", ""], [/\bof\b/gi, "का", "ਦਾ"], [/\bin\b/gi, "में", "ਵਿੱਚ"],
  [/\bto\b/gi, "को", "ਨੂੰ"], [/\bby\b/gi, "से", "ਤੋਂ"], [/\bas\b/gi, "के रूप में", "ਦੇ ਰੂਪ ਵਿੱਚ"], [/\bat\b/gi, "पर", "ਤੇ"],
  [/\bthan\b/gi, "से", "ਤੋਂ"], [/\bthis\b/gi, "यह", "ਇਹ"], [/\bthat\b/gi, "वह", "ਉਹ"], [/\bthese\b/gi, "ये", "ਇਹ"],
  [/\bthose\b/gi, "वे", "ਉਹ"], [/\bit\b/gi, "यह", "ਇਹ"], [/\bits\b/gi, "इसका", "ਇਸ ਦਾ"], [/\btheir\b/gi, "उनका", "ਉਨ੍ਹਾਂ ਦਾ"],
  [/\bthem\b/gi, "उन्हें", "ਉਨ੍ਹਾਂ ਨੂੰ"], [/\bone\b/gi, "एक", "ਇੱਕ"], [/\btwo\b/gi, "दो", "ਦੋ"], [/\bthree\b/gi, "तीन", "ਤਿੰਨ"],
  [/\ba\b/g, "a", "a"], [/\ban\b/gi, "एक", "ਇੱਕ"], [/\bthe\b/gi, "", ""],
];

const PUNJABI_SCRIPT_FIXES: readonly [RegExp, string][] = [
  [/और/g, "ਅਤੇ"], [/या/g, "ਜਾਂ"], [/इसलिए/g, "ਇਸ ਲਈ"], [/तब/g, "ਤਦ"], [/क्योंकि/g, "ਕਿਉਂਕਿ"], [/अतः/g, "ਇਸ ਲਈ"],
  [/दिया है/g, "ਦਿੱਤਾ ਹੈ"], [/दिया गया/g, "ਦਿੱਤਾ"], [/ज्ञात करना है/g, "ਪਤਾ ਕਰਨਾ ਹੈ"], [/ज्ञात/g, "ਪਤਾ"], [/आवश्यक/g, "ਲੋੜੀਂਦਾ"],
  [/व्यंजक/g, "ਵਿਆੰਜਕ"], [/समीकरण/g, "ਸਮੀਕਰਨ"], [/असमानता/g, "ਅਸਮਾਨਤਾ"], [/बहुपद/g, "ਬਹੁਪਦ"], [/गुणनखंड/g, "ਗੁਣਨਖੰਡ"],
  [/शेषफल/g, "ਬਾਕੀ"], [/गुणांक/g, "ਗੁਣਾਂਕ"], [/अचर/g, "ਅਚਲ"], [/हर/g, "ਹਰ"], [/अंश/g, "ਅੰਸ਼"], [/मूल/g, "ਮੂਲ"],
  [/हल/g, "ਹੱਲ"], [/मान/g, "ਮਾਨ"], [/पद/g, "ਪਦ"], [/वर्ग/g, "ਵਰਗ"], [/घन/g, "ਘਣ"], [/गुणनफल/g, "ਗੁਣਨਫਲ"], [/योग/g, "ਜੋੜ"],
  [/संबंध/g, "ਸੰਬੰਧ"], [/अंतराल/g, "ਅੰਤਰਾਲ"], [/सीमा/g, "ਸੀਮਾ"], [/प्रतिस्थापन/g, "ਪ੍ਰਤਿਸਥਾਪਨ"], [/गणना/g, "ਗਣਨਾ"],
  [/विस्तार/g, "ਵਿਸਥਾਰ"], [/सरल/g, "ਸਰਲ"], [/भाग/g, "ਭਾਗ"], [/गुणा/g, "ਗੁਣਾ"], [/रैखिक/g, "ਰੇਖੀ"], [/सटीक/g, "ਸਹੀ"],
  [/वास्तविक/g, "ਵਾਸਤਵਿਕ"], [/शाखा/g, "ਸ਼ਾਖਾ"], [/युग्म/g, "ਜੋੜਾ"], [/व्युत्क्रम/g, "ਵਿਉਤਕ੍ਰਮ"], [/गैर-शून्य/g, "ਗੈਰ-ਸਿਫ਼ਰ"],
  [/शून्य/g, "ਸਿਫ਼ਰ"], [/पूर्ण/g, "ਪੂਰਨ"], [/पहले/g, "ਪਹਿਲਾਂ"], [/पहला/g, "ਪਹਿਲਾ"], [/दूसरा/g, "ਦੂਜਾ"], [/दोनों/g, "ਦੋਵੇਂ"], [/प्रत्येक/g, "ਹਰ"],
  [/सीधे/g, "ਸਿੱਧਾ"], [/सीधा/g, "ਸਿੱਧਾ"], [/शर्त/g, "ਸ਼ਰਤ"], [/पर्याप्त/g, "ਕਾਫ਼ੀ"], [/अपर्याप्त/g, "ਅਪਰਿਆਪਤ"],
  [/अद्वितीय/g, "ਇਕੋ"], [/स्वतंत्र/g, "ਸੁਤੰਤਰ"], [/समांतर/g, "ਸਮਾਂਤਰ"], [/भिन्न/g, "ਭਿੰਨ"], [/समानुपाती/g, "ਅਨੁਪਾਤੀ"],
  [/अनुपात/g, "ਅਨੁਪਾਤ"], [/मान्य/g, "ਮਨਜ਼ੂਰ"], [/अमान्य/g, "ਅਮਾਨਯ"], [/वर्जित/g, "ਮਨਾਹੀ"], [/धनात्मक/g, "ਧਨਾਤਮਕ"], [/ऋणात्मक/g, "ਰਣਾਤਮਕ"],
  [/ऋणेतर/g, "ਗੈਰ-ਰਣਾਤਮਕ"], [/धनेतर/g, "ਗੈਰ-ਧਨਾਤਮਕ"], [/बड़ा/g, "ਵੱਡਾ"], [/छोटा/g, "ਛੋਟਾ"], [/न्यूनतम/g, "ਘੱਟੋ-ਘੱਟ"],
  [/अधिकतम/g, "ਵੱਧੋ-ਵੱਧ"], [/सबसे/g, "ਸਭ ਤੋਂ"], [/प्राप्त/g, "ਪ੍ਰਾਪਤ"], [/निचला/g, "ਹੇਠਲਾ"], [/पैरामीटर/g, "ਪੈਰਾਮੀਟਰ"],
  [/अज्ञात/g, "ਅਣਜਾਣ"], [/संख्या/g, "ਸੰਖਿਆ"], [/पूर्णांक/g, "ਪੂਰਨ ਅੰਕ"], [/शीर्ष/g, "ਸਿਖਰ"], [/निर्देशांक/g, "ਨਿਰਦੇਸ਼ਾਂਕ"],
  [/अक्ष/g, "ਅਕਸ"], [/दूरी/g, "ਦੂਰੀ"], [/कथन/g, "ਕਥਨ"], [/स्थिति/g, "ਸਥਿਤੀ"], [/सत्य/g, "ਸੱਚ"], [/असत्य/g, "ਗਲਤ"],
  [/बिना/g, "ਬਿਨਾਂ"], [/के साथ/g, "ਨਾਲ"], [/के लिए/g, "ਲਈ"], [/जबकि/g, "ਜਦਕਿ"], [/जब/g, "ਜਦੋਂ"], [/के बाद/g, "ਤੋਂ ਬਾਅਦ"],
  [/से पहले/g, "ਤੋਂ ਪਹਿਲਾਂ"], [/केवल/g, "ਕੇਵਲ"], [/नहीं/g, "ਨਹੀਂ"], [/सकता है/g, "ਸਕਦਾ ਹੈ"], [/चाहिए/g, "ਚਾਹੀਦਾ ਹੈ"],
  [/हैं/g, "ਹਨ"], [/है/g, "ਹੈ"], [/हो/g, "ਹੋਵੇ"], [/का/g, "ਦਾ"], [/की/g, "ਦੀ"], [/के/g, "ਦੇ"], [/में/g, "ਵਿੱਚ"],
  [/को/g, "ਨੂੰ"], [/से/g, "ਤੋਂ"], [/पर/g, "ਤੇ"], [/यह/g, "ਇਹ"], [/वह/g, "ਉਹ"], [/ये/g, "ਇਹ"], [/वे/g, "ਉਹ"],
  [/उनका/g, "ਉਨ੍ਹਾਂ ਦਾ"], [/इसका/g, "ਇਸ ਦਾ"], [/उन्हें/g, "ਉਨ੍ਹਾਂ ਨੂੰ"], [/एक/g, "ਇੱਕ"], [/दो/g, "ਦੋ"], [/तीन/g, "ਤਿੰਨ"],
  [/रखें/g, "ਰੱਖੋ"], [/करें/g, "ਕਰੋ"], [/करने पर/g, "ਕਰਨ ਤੇ"], [/मिलता है/g, "ਮਿਲਦਾ ਹੈ"], [/मिलते हैं/g, "ਮਿਲਦੇ ਹਨ"],
  [/बनता है/g, "ਬਣਦਾ ਹੈ"], [/बन जाता है/g, "ਬਣ ਜਾਂਦਾ ਹੈ"], [/ले जाएँ/g, "ਲਿਜਾਓ"], [/छोड़कर/g, "ਛੱਡ ਕੇ"], [/सिवाय/g, "ਤੋਂ ਇਲਾਵਾ"],
  [/बीच/g, "ਵਿਚਕਾਰ"], [/बाहर/g, "ਬਾਹਰ"], [/अंदर/g, "ਅੰਦਰ"], [/ओर/g, "ਪਾਸੇ"], [/पक्ष/g, "ਪਾਸੇ"], [/समान/g, "ਇੱਕੋ"],
];

function applyRules(locale: AlgReviewLocale, input: string, rules: readonly Rule[]): string {
  let value = input;
  for (const [pattern, hi, pa] of rules) value = value.replace(pattern, locale === "hi-IN" ? hi : pa);
  return value;
}

function clean(locale: AlgReviewLocale, text: string): string {
  let value = applyRules(locale, text, PHRASE_RULES);
  value = applyRules(locale, value, WORD_RULES);
  if (locale === "pa-IN") {
    for (const [pattern, replacement] of PUNJABI_SCRIPT_FIXES) value = value.replace(pattern, replacement);
  }
  return value
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([।,.!?;:])/g, "$1")
    .replace(/\.\s*$/gm, "।")
    .trim();
}

export function generateAlgPermanentMultilingualReviewV2Final(
  qlId: AlgPermanentQlId,
  seed: number,
  locale: AlgReviewLocale,
  requestedVariantIndex?: number,
): AlgPermanentMultilingualReviewV2Item {
  const item = generateAlgPermanentMultilingualReviewV2Editorial(qlId, seed, locale, requestedVariantIndex);
  return {
    ...item,
    question: clean(locale, item.question),
    explanation: clean(locale, item.explanation),
  };
}
