import type { PolCp010Difficulty, PolCp010QuestionSeed } from "./pol-cp010-review-types";
const C = "LEGISLATIVE-DEPT-CONSTITUTION-2025";
const s = (ql:number,difficulty:PolCp010Difficulty,stem:string,canonicalAnswer:string,distractors:[string,string,string],explanation:string,fact:string):PolCp010QuestionSeed => ({ qlId:`POL-010-QL-${String(ql).padStart(3,"0")}`, difficulty, stem, canonicalAnswer, distractors, explanation, sourceIds:[C], sourceFactIds:[fact] });
export const POL_CP010_SEEDS_B: readonly PolCp010QuestionSeed[] = [
s(6,"Easy","Article 81 allows up to how many members from States in Lok Sabha?","530",["500","520","550"],"Article 81 allows not more than 530 members chosen by direct election from State territorial constituencies.","pol-cp010-parliament-structure"),
s(6,"Easy","Article 81 allows up to how many members to represent Union territories in Lok Sabha?","20",["12","18","25"],"Article 81 allows not more than twenty members to represent Union territories in Lok Sabha.","pol-cp010-parliament-structure"),
s(6,"Easy","Members representing States in Lok Sabha are chosen by:","Direct election from territorial constituencies",["State Legislative Assemblies","Rajya Sabha","The President"],"State representatives in Lok Sabha are chosen directly from territorial constituencies under Article 81.","pol-cp010-parliament-structure"),
s(6,"Easy","Lok Sabha is also called the:","House of the People",["Council of States","Federal Council","National Council"],"The Constitution uses House of the People as the formal name for Lok Sabha.","pol-cp010-parliament-structure"),
s(7,"Medium","Readjustment of Lok Sabha seats after a census is mainly covered by:","Article 82",["Article 80","Article 83","Article 85"],"Article 82 deals with readjusting State seat allocation and territorial constituencies after a census.","pol-cp010-art82"),
s(7,"Medium","Who determines by law the authority and manner for readjustment under Article 82?","Parliament",["Election Commission alone","President alone","Supreme Court"],"Article 82 leaves the authority and manner of readjustment to be determined by Parliament by law.","pol-cp010-art82"),
s(7,"Medium","A readjustment under Article 82 affects the existing Lok Sabha immediately:","No",["Yes","Only if Rajya Sabha agrees","Only during an Emergency"],"Article 82 says a readjustment does not affect representation in the existing Lok Sabha until its dissolution.","pol-cp010-art82"),
s(7,"Medium","The present constitutional freeze refers to figures from the first census taken after:","2026",["2001","2011","2031"],"Article 82 keeps the stated readjustment freeze until relevant figures from the first census after 2026 are published.","pol-cp010-art82"),
s(8,"Medium","Rajya Sabha is:","A continuing House not subject to dissolution",["Dissolved every five years","Dissolved with Lok Sabha","Dissolved every six years"],"Article 83 makes Rajya Sabha a continuing House, so the House itself is not dissolved.","pol-cp010-parliament-structure"),
s(8,"Medium","About one-third of Rajya Sabha members retire after every:","Two years",["One year","Three years","Five years"],"As nearly as possible one-third of Rajya Sabha members retire at the end of every second year.","pol-cp010-parliament-structure"),
s(8,"Medium","The normal term of Lok Sabha is:","Five years from its first meeting",["Five years from election notification","Six years from its first meeting","Four years from election"],"Lok Sabha normally continues for five years from the date appointed for its first meeting unless sooner dissolved.","pol-cp010-parliament-structure"),
s(8,"Medium","During a national Emergency, Lok Sabha may be extended at a time by up to:","One year",["Six months","Two years","Five years"],"Parliament may extend Lok Sabha during an Emergency by up to one year at a time, subject to the post-Emergency limit.","pol-cp010-parliament-structure"),
s(9,"Medium","Minimum age for Rajya Sabha membership is:","30 years",["25 years","28 years","35 years"],"Article 84 qualifications:\n• Citizen of India\n• Oath/affirmation in the Third Schedule before an Election Commission-authorised person\n• At least 30 for Rajya Sabha, 25 for Lok Sabha\n• Other qualifications prescribed by Parliament.","pol-cp010-membership-qualifications"),
s(9,"Medium","Minimum age for Lok Sabha membership is:","25 years",["21 years","30 years","35 years"],"Article 84 qualifications:\n• Citizen of India\n• Oath/affirmation in the Third Schedule before an Election Commission-authorised person\n• At least 25 for Lok Sabha, 30 for Rajya Sabha\n• Other qualifications prescribed by Parliament.","pol-cp010-membership-qualifications"),
s(9,"Medium","For Article 84 qualification, the required oath is made before a person authorised by the:","Election Commission",["President","Chief Justice of India","Speaker of Lok Sabha"],"Article 84 qualifications:\n• Citizen of India\n• Required oath/affirmation before an Election Commission-authorised person\n• Age 25 for Lok Sabha or 30 for Rajya Sabha\n• Other qualifications prescribed by Parliament.","pol-cp010-membership-qualifications"),
s(9,"Medium","The Article 84 qualification oath follows the form in the:","Third Schedule",["Second Schedule","Fourth Schedule","Tenth Schedule"],"Article 84 qualifications:\n• Citizen of India\n• Oath/affirmation in the Third Schedule before an Election Commission-authorised person\n• Age 25 for Lok Sabha or 30 for Rajya Sabha\n• Other qualifications prescribed by Parliament.","pol-cp010-membership-qualifications"),
s(10,"Medium","Who summons each House of Parliament?","President",["Prime Minister","Speaker and Chairman jointly","Chief Justice of India"],"Article 85 formally gives the President the power to summon each House of Parliament.","pol-cp010-sessions-address-rights"),
s(10,"Medium","The Constitution allows a gap of six months or more between the relevant sittings of two sessions:","No",["Yes","Only for Rajya Sabha","Only with Supreme Court approval"],"Article 85 says six months shall not intervene between the last sitting of one session and first sitting of the next.","pol-cp010-sessions-address-rights"),
s(10,"Medium","Who may prorogue either House of Parliament?","President",["Prime Minister alone","Speaker alone","Election Commission"],"Article 85 gives the President the formal power to prorogue either House of Parliament.","pol-cp010-sessions-address-rights"),
s(10,"Medium","Which House may be dissolved under Article 85?","Lok Sabha",["Rajya Sabha","Both Houses","Neither House"],"Article 85 allows dissolution of Lok Sabha; Rajya Sabha is a continuing House and is not dissolved.","pol-cp010-sessions-address-rights")
];
