import type { QuantExternalCoverageObservation } from "./external-source-audit-v1";

export const TRG_001_DISHA_SSC_BOOK_WAVE2_V1 = Object.freeze({
  sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE" as const,
  sourceSection: "Trigonometry and Its Applications" as const,
  pdfPages: "414-416" as const,
  status: "SECOND_CLASSIFICATION_RUNTIME_MAPPING_OPEN" as const,
  observations: Object.freeze([
    {
      observationId: "DISHA-TRG-W2-001",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p414 Q7-Q17",
      packageId: "TRG-001",
      proposedFamily: "COMPOUND_ANGLE_CONJUGATE_HIGHER_POWER_IDENTITY",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      candidateMappedQlIds: ["TRG-001-QL-126"],
      candidateCoverageStatus: "AUDIT_CANDIDATE",
      confidence: "HIGH",
      notes: "Most compound-angle/conjugate forms map to active families, but the higher-power quadratic-relation sibling matching this book wave is part of the P2 audit candidate and is not active yet. Keep the aggregate observation pending until active/candidate subforms are split or runtime-sampled.",
    },
    {
      observationId: "DISHA-TRG-W2-002",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p414 Q18-Q22 and p415 Q31/Q38 and p416 Q45",
      packageId: "TRG-002",
      proposedFamily: "HEIGHTS_DISTANCES_APPLICATION_SET",
      disposition: "OWNED_BY_OTHER_PACKAGE",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Broken tree, aircraft, kite, complementary tower observations, rock/tower and changing-shadow problems belong to TRG-002.",
    },
    {
      observationId: "DISHA-TRG-W2-003",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p414 Q23 and p415 Q36",
      packageId: "TRG-001",
      proposedFamily: "PARAMETRIC_LINEAR_SIN_COS_ELIMINATION",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "MEDIUM",
      notes: "Elimination of sin/cos parameters into x,y invariants is mathematically aligned with linear-sin/cos relation authority; exact multi-variable surface still merits runtime sample confirmation.",
    },
    {
      observationId: "DISHA-TRG-W2-004",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q24/Q30/Q32/Q33 and p416 Q41-Q44",
      packageId: "TRG-001",
      proposedFamily: "CONJUGATE_RECIPROCAL_COFUNCTION_STANDARD_VALUE_COMPOSITES",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "sec+tan recovery, conjugate product simplification, complementary-angle substitutions and reciprocal cubic/linear relations fit established CP003-CP006 coverage.",
    },
    {
      observationId: "DISHA-TRG-W2-005",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q25/Q26/Q35",
      packageId: "TRG-001",
      proposedFamily: "DEGREE_RADIAN_CONVERSION_AND_GEOMETRIC_ANGLE_MEASURE",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Degree-radian conversion and simple triangle angle-to-radian forms are within the package angle-measure/reduction authority.",
    },
    {
      observationId: "DISHA-TRG-W2-006",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q27-Q29",
      packageId: "TRG-001",
      proposedFamily: "HIGHER_POWER_RATIO_AND_COFUNCTION_ANGLE_EQUATION",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      candidateMappedQlIds: ["TRG-001-QL-126"],
      candidateCoverageStatus: "AUDIT_CANDIDATE",
      confidence: "MEDIUM",
      notes: "Fourth-power relations and cofunction angle equations are broadly within TRG authority, but higher-power P2 expansion is not active. Verify active constructions before scoring covered.",
    },
    {
      observationId: "DISHA-TRG-W2-007",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q34",
      packageId: "TRG-001",
      proposedFamily: "LONG_COMPLEMENTARY_COT_PRODUCT_WITH_SUM_DENOMINATOR",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Large cot product paired across complementary angles plus cos20°+cos70° structure. Repeats Wave-1 evidence that long aggregation is a distinct construction concern.",
    },
    {
      observationId: "DISHA-TRG-W2-008",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q37",
      packageId: "TRG-001",
      proposedFamily: "TAN_COT_RELATION_TO_HIGH_ODD_POWERS",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "tan a+cot a=2 forces tan a=cot a=1; high odd powers then collapse. Existing controlled tan/cot equation authority covers the reasoning, though exponent depth differs.",
    },
    {
      observationId: "DISHA-TRG-W2-009",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p415 Q39",
      packageId: "TRG-001",
      proposedFamily: "LONG_COMPLEMENTARY_SINE_SQUARED_SUM",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Long sin² sequence aggregation appears to rely on complementary pairing. This is the same aggregation seam as Wave-1 long products but a different operator (sum instead of product).",
    },
    {
      observationId: "DISHA-TRG-W2-010",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p416 Q40",
      packageId: "TRG-001",
      proposedFamily: "CUBIC_SUM_DIFFERENCE_TRIG_FACTORIZATION",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      candidateMappedQlIds: ["TRG-001-QL-143"],
      candidateCoverageStatus: "AUDIT_CANDIDATE",
      confidence: "HIGH",
      notes: "The P2 audit candidate explicitly remediates QL-143 to a cubic trig-factorization construction, but current New-main still has QL-143 as triangle-area angle recovery. Candidate coverage must not be counted as active coverage before refreeze/rebind.",
    },
  ] satisfies readonly QuantExternalCoverageObservation[]),
});
