import type { QuantExternalCoverageObservation } from "./external-source-audit-v1";

export const TRG_001_DISHA_SSC_BOOK_WAVE1_V1 = Object.freeze({
  sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE" as const,
  sourceSection: "Trigonometry and Its Applications" as const,
  pdfPages: "409-413" as const,
  status: "INITIAL_CLASSIFICATION_RUNTIME_MAPPING_OPEN" as const,
  observations: Object.freeze([
    {
      observationId: "DISHA-TRG-W1-001",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p409 Q1",
      packageId: "TRG-001",
      proposedFamily: "LONG_STANDARD_ANGLE_PRODUCT_ZERO_FACTOR",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "cos1°·cos2°·...·cos179°; answer follows from the cos90° zero factor. Check whether active runtime has long-product construction rather than only standard-value primitives.",
    },
    {
      observationId: "DISHA-TRG-W1-002",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p409 Q5 and p411 Q50",
      packageId: "TRG-001",
      proposedFamily: "COMPLEMENTARY_TAN_PRODUCT_PAIRING",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Products such as tan9°tan27°tan63°tan81° and tan7°tan23°tan60°tan67°tan83°. Concept is cofunction pairing; verify explicit multi-factor product construction.",
    },
    {
      observationId: "DISHA-TRG-W1-003",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p409 Q6-Q9",
      packageId: "TRG-001",
      proposedFamily: "RATIO_TO_RECIPROCAL_AND_LINEAR_EXPRESSION",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "sin→cos, tan→sec and tan-given linear sin/cos ratio forms match established right-triangle/reconstruction/derived-ratio families.",
    },
    {
      observationId: "DISHA-TRG-W1-004",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p409 Q10-Q16",
      packageId: "TRG-001",
      proposedFamily: "DOUBLE_ANGLE_STANDARD_VALUE_COFUNCTION_IDENTITY",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Double-angle evaluations, cofunction angle equation and sec²−tan² identity align with established CP002/CP003/CP004/CP006 coverage.",
    },
    {
      observationId: "DISHA-TRG-W1-005",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p410 Q17-Q21",
      packageId: "TRG-001",
      proposedFamily: "SEC_TAN_CONJUGATE_BASIC_RELATION_COFUNCTION_SOLVE",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Includes (secA+tanA)(1−sinA), direct ratio relationship and cos(40°+x)=sin30°. Existing conjugate, basic-ratio and cofunction families cover these forms.",
    },
    {
      observationId: "DISHA-TRG-W1-006",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p410 Q23",
      packageId: "TRG-001",
      proposedFamily: "FULL_COMPLEMENTARY_TAN_PRODUCT_1_TO_89",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "tan1°tan2°...tan89°. Same cofunction principle but materially different aggregation depth; exact runtime construction must be demonstrated before calling covered.",
    },
    {
      observationId: "DISHA-TRG-W1-007",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p410 Q29",
      packageId: "TRG-001",
      proposedFamily: "TRIPLE_ANGLE_COSINE_POLYNOMIAL",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Given sinθ=1/2, evaluate 3cosθ−4cos³θ. Current authority explicitly includes double-angle and angle-sum/difference; verify whether triple-angle polynomial is intentionally supported or should be a new SSC archetype.",
    },
    {
      observationId: "DISHA-TRG-W1-008",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p410 Q30-Q34",
      packageId: "TRG-001",
      proposedFamily: "TAN_COT_RELATION_COFUNCTION_STANDARD_ANGLE_SUMS",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "tan+cot relation, cofunction equations, standard-value evaluation and complementary simplification all have established runtime families; exact long-sum surface may vary.",
    },
    {
      observationId: "DISHA-TRG-W1-009",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p410 Q35 through p411 Q47",
      packageId: "TRG-002",
      proposedFamily: "HEIGHTS_DISTANCES_LINE_OF_SIGHT",
      disposition: "OWNED_BY_OTHER_PACKAGE",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Tower, depression, moving observation point, shadow, kite, chimney, poles and opposite-side observer scenarios belong to TRG-002, not TRG-001.",
    },
    {
      observationId: "DISHA-TRG-W1-010",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p411 Q48",
      packageId: "TRG-001",
      proposedFamily: "RIGHT_TRIANGLE_TAN_B_PLUS_TAN_C",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Right-triangle side-to-ratio composite is within CP001/derived-ratio authority; check exact target-expression surface only if needed.",
    },
    {
      observationId: "DISHA-TRG-W1-011",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p411 Q51-Q52",
      packageId: "TRG-001",
      proposedFamily: "RECIPROCAL_COMPOSITE_AND_COMPOUND_ANGLE_SYSTEM",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "MEDIUM",
      notes: "Composite reciprocal identity is established; two-angle tan/sec system should be checked against mixed CP006 surfaces during runtime mapping.",
    },
    {
      observationId: "DISHA-TRG-W1-012",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p412 Q54-Q56",
      packageId: "TRG-001",
      proposedFamily: "MINIMUM_TAN_COT_SUM_DIFFERENCE_SQUARE_CONJUGATE",
      disposition: "DIRECTLY_COVERED",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "Minimum 4tan²θ+9cot²θ, given sin−cos to find sin+cos, and cosec−cot conjugate recovery match existing max/min, square-relation and conjugate families.",
    },
    {
      observationId: "DISHA-TRG-W1-013",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p412 Q58-Q68",
      packageId: "TRG-001",
      proposedFamily: "IDENTITY_SOLVE_MIXED_SIMPLIFICATION_LINEAR_TRIG_RELATION",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "sec/tan identity solve, mixed Pythagorean simplification, linear sin/cos expressions and cos²−sin² acute-angle relation fit existing CP004-CP006 families.",
    },
    {
      observationId: "DISHA-TRG-W1-014",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p413 Q69",
      packageId: "TRG-001",
      proposedFamily: "TRIG_EQUALITY_WITH_ALGEBRAIC_FEASIBILITY_CONDITION",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "MEDIUM",
      notes: "cos²θ=(x+y)²/(4xy) only possible under an algebraic feasibility/equality condition. Check whether this is intentionally cross-topic/out-of-scope or a supported SSC composite.",
    },
    {
      observationId: "DISHA-TRG-W1-015",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p413 Q72",
      packageId: "TRG-001",
      proposedFamily: "QUADRATIC_TRIG_RELATION_TO_SHIFTED_ANGLE",
      disposition: "COVERED_WITH_VARIATION",
      mappedQlIds: [],
      confidence: "MEDIUM",
      notes: "Solve quadratic relation in cosθ for acute θ, then evaluate tan(θ−15°). Controlled equations plus angle-difference coverage likely provides a home; verify exact composition.",
    },
    {
      observationId: "DISHA-TRG-W1-016",
      sourceId: "BOOK-DISHA-SSC-MATHEMATICS-GUIDE",
      sourceLocator: "PDF p413 Q73",
      packageId: "TRG-001",
      proposedFamily: "SUM_OF_SQUARES_ZERO_TO_SEC_TAN_COMPOSITE",
      disposition: "RUNTIME_MAPPING_PENDING",
      mappedQlIds: [],
      confidence: "HIGH",
      notes: "(r cosθ−3)²+(r sinθ−1)²=0 followed by a sec/tan rational expression. Verify active runtime can compose zero-sum square reconstruction with the requested trig target.",
    },
  ] satisfies readonly QuantExternalCoverageObservation[]),
});
