export const HIS_CP023_QL_NAMES_V1:Record<number,string>={
  "1": "Orientalist institutions and early education policy",
  "2": "Macaulay and Anglicist education policy",
  "3": "Wood's Dispatch and education structure",
  "4": "Hunter Commission and university expansion",
  "5": "Early press regulation and liberalisation",
  "6": "Vernacular Press and Arms Acts",
  "7": "Constitutional and university-policy supplements",
  "8": "Young Bengal and Phule reform",
  "9": "Comparative policy and reform chronology",
  "10": "Theosophical Society and public-sphere synthesis"
};
export type HisCp023Spec=readonly[ql:number,stem:string,answer:string,distractors:readonly[string,string,string],factIds:readonly string[]];
export const HIS_CP023_SPECS_V1:readonly HisCp023Spec[]=[
  [1,"Which institution was founded by Warren Hastings in 1781?","Calcutta Madrasa",["Asiatic Society of Bengal","Fort William College","Sanskrit College, Benares"],["edu-calcutta-madrasa"]],
  [1,"The Asiatic Society of Bengal was founded in 1784 by:","William Jones",["Jonathan Duncan","Charles Wood","T.B. Macaulay"],["edu-asiatic-society"]],
  [1,"The Sanskrit College at Benares was founded by:","Jonathan Duncan",["Warren Hastings","Wellesley","W.W. Hunter"],["edu-benares-sanskrit"]],
  [1,"Fort William College was founded in 1800 mainly to train:","Company civil servants",["Indian sepoys","Missionary priests","Indian merchants"],["edu-fort-william"]],
  [1,"The Charter Act of 1813 earmarked how much annually for education?","One lakh rupees",["Ten thousand rupees","Five lakh rupees","Ten lakh rupees"],["edu-charter-lakh"]],
  [1,"The early Orientalists favoured the study of:","Indian languages, laws and traditions",["Only English literature","Only military science","Only European law"],["edu-orientalists"]],
  [2,"T.B. Macaulay became Law Member of the Governor-General's Council in:","1834",["1813","1854","1882"],["edu-macaulay-lawmember"]],
  [2,"Macaulay's Minute on Indian Education was issued in:","1835",["1813","1854","1882"],["edu-macaulay-minute"]],
  [2,"After the Anglicist victory, official education policy increasingly promoted:","European literature and science through English",["Persian as the sole medium","Only Sanskrit learning","Only vocational training"],["edu-anglicist-victory"]],
  [2,"The 'downward filtration' theory aimed first to educate:","A small English-educated elite",["The entire rural population at once","Only European children","Only military recruits"],["edu-downward-filtration"]],
  [2,"One colonial expectation from English education was the supply of Indians for:","Subordinate clerical posts",["Hereditary princely offices","Independent judicial control","Military command of British troops"],["edu-clerical-purpose"]],
  [2,"Wood's Dispatch was issued in:","1854",["1835","1857","1882"],["edu-wood-1854"]],
  [3,"Wood's Dispatch preferred English mainly for:","Higher education",["Village primary education","Traditional pathshalas only","Military schools only"],["edu-wood-medium"]],
  [3,"Which sequence reflects the school hierarchy proposed in Wood's Dispatch?","Vernacular primary → Anglo-vernacular high school → affiliated college",["College → village school → madrasa","Military school → university → pathshala","Primary school → army camp → court"],["edu-wood-hierarchy"]],
  [3,"Wood's Dispatch introduced which financial support for private education?","Grants-in-aid",["Permanent Settlement","Subsidiary subsidy","Military pension"],["edu-grants-aid"]],
  [3,"Departments of Public Instruction were established in:","1855",["1835","1857","1882"],["edu-dpi-1855"]],
  [3,"Which three universities were established in 1857?","Calcutta, Bombay and Madras",["Allahabad, Punjab and Delhi","Bombay, Poona and Lahore","Calcutta, Aligarh and Banaras"],["edu-universities-1857"]],
  [3,"Wood's Dispatch also supported teacher training, vocational education and:","Women's education",["Separate electorates","Arms licensing","Land settlement"],["edu-wood-training-women"]],
  [4,"The Hunter Commission was appointed in:","1882",["1854","1878","1904"],["edu-hunter-1882"]],
  [4,"The Hunter Commission gave special emphasis to:","Primary education",["Military education","University autonomy only","Civil-service training"],["edu-hunter-primary"]],
  [4,"At the secondary level, the Hunter Commission proposed:","Literary and practical-vocational streams",["Only classical Sanskrit studies","Only military training","Only English clerical training"],["edu-hunter-secondary"]],
  [4,"The Hunter Commission supported private initiative and wider facilities for:","Women's education",["Arms manufacture","Plantation labour","Military recruitment"],["edu-hunter-private"]],
  [4,"Punjab University was founded in:","1882",["1857","1887","1904"],["edu-punjab-univ"]],
  [4,"Allahabad University was founded in:","1887",["1857","1882","1904"],["edu-allahabad-univ"]],
  [5,"The first newspaper in India is commonly identified as:","Bengal Gazette",["Kesari","Amrita Bazar Patrika","The Hindu"],["press-bengal-gazette"]],
  [5,"The Censorship of the Press Act of 1799 was imposed by:","Lord Wellesley",["Lord Hastings","Charles Metcalfe","Lord Ripon"],["press-wellesley-1799"]],
  [5,"The 1799 press regulations required:","Pre-publication government clearance",["Universal adult franchise","Compulsory vernacular publication","Election of editors"],["press-1799-precensor"]],
  [5,"Pre-censorship of the press was removed in 1818 by:","Lord Hastings",["John Adam","Lord Lytton","Lord Curzon"],["press-hastings-1818"]],
  [5,"The 1823 press regulations made what compulsory?","A licence for starting or using a press",["Election of newspaper editors","Publication only in English","Government ownership of presses"],["press-adam-1823"]],
  [5,"Charles Metcalfe's 1835 press policy mainly required publishers to:","Declare the place and premises of publication",["Submit every article for pre-censorship","Publish only in English","Obtain permission from Parliament"],["press-metcalfe-1835"]],
  [6,"The Vernacular Press Act was enacted in:","1878",["1857","1882","1904"],["press-vpa-1878"]],
  [6,"The Vernacular Press Act chiefly targeted:","Indian-language newspapers",["English newspapers only","Missionary schools","Legislative councils"],["press-vpa-language"]],
  [6,"Under the Vernacular Press Act, an adverse decision of the district magistrate had:","No ordinary appeal",["Automatic review by Parliament","Mandatory jury trial","Appeal only to municipal boards"],["press-vpa-magistrate"]],
  [6,"The Vernacular Press Act was repealed in 1882 by:","Lord Ripon",["Lord Lytton","Lord Curzon","Lord Wellesley"],["press-vpa-repeal"]],
  [6,"The Indian Arms Act of 1878 was enacted during the viceroyalty of:","Lord Lytton",["Lord Ripon","Lord Mayo","Lord Dufferin"],["arms-1878"]],
  [6,"Under the Arms Act of 1878, Indians generally required a licence to:","Possess or carry arms",["Publish newspapers","Open schools","Vote in councils"],["arms-license"]],
  [7,"Why was the Arms Act of 1878 widely regarded as discriminatory?","Important European and Anglo-Indian categories were exempted",["It applied only to British soldiers","It abolished all arms licences","It gave Indians unrestricted access to weapons"],["arms-racial"]],
  [7,"The Indian Councils Act of 1861 is important because it marked:","An early step towards representative institutions",["The introduction of separate electorates","The start of provincial autonomy","The end of Crown rule"],["const-councils-1861"]],
  [7,"One reason given for the Indian Councils Act of 1861 was to improve contact between:","Colonial rulers and the ruled population",["Indian merchants and European planters","Zamindars and moneylenders only","Princely rulers and foreign powers"],["const-1861-contact"]],
  [7,"The Indian Councils Act of 1892 mainly enlarged the legislature by adding:","Non-official members",["Military officers only","Princely rulers only","Company shareholders"],["const-councils-1892"]],
  [7,"The Indian Councils Act of 1892 was a limited response to demands made by the:","Early Moderates",["Revolutionary terrorists","Khilafat leaders","Quit India activists"],["const-1892-moderates"]],
  [7,"Lord Curzon's Indian Universities Act was passed in:","1904",["1878","1892","1909"],["edu-curzon-1904"]],
  [8,"The Young Bengal movement was inspired by:","Henry Louis Vivian Derozio",["Jyotirao Phule","M.G. Ranade","H.S. Olcott"],["reform-young-bengal"]],
  [8,"Derozio encouraged his students to:","Question established authority",["Reject all modern science","Support caste restrictions","Avoid public debate"],["reform-derozio-authority"]],
  [8,"The Paramhansa Mandali was founded in 1849 and opposed:","Caste restrictions",["Women's education","Widow remarriage","Vernacular education"],["reform-paramhansa"]],
  [8,"Jyotirao and Savitribai Phule are especially linked with the promotion of:","Girls' education",["Separate electorates","Indigo cultivation","Military reform"],["reform-phule-school"]],
  [8,"Jyotirao Phule also opened schools for:","Children of the depressed classes",["European officials only","Company soldiers only","Zamindars only"],["reform-phule-lowercastes"]],
  [8,"The Satyashodhak Samaj was founded in:","1873",["1849","1875","1885"],["reform-satyashodhak-1873"]],
  [9,"Which pair is correctly matched?","Satyashodhak Samaj — lower-caste emancipation; Pandita Ramabai — women's rights",["Satyashodhak Samaj — press censorship; Pandita Ramabai — arms licensing","Satyashodhak Samaj — indigo planting; Pandita Ramabai — military reform","Satyashodhak Samaj — separate electorates; Pandita Ramabai — land revenue"],["reform-satyashodhak-aim","reform-pandita-ramabai"]],
  [9,"Which combination reflects efforts to widen access to education?","Ranade supported vernacular university study; Phule promoted education for girls and lower castes",["Ranade opposed vernaculars; Phule restricted education to elites","Both opposed women's education","Both focused only on military colleges"],["reform-ranade-vernacular","reform-phule-school","reform-phule-lowercastes"]],
  [9,"Which sequence is chronologically correct?","Macaulay's Minute → Wood's Dispatch → Hunter Commission",["Hunter Commission → Macaulay's Minute → Wood's Dispatch","Wood's Dispatch → Macaulay's Minute → Hunter Commission","Macaulay's Minute → Hunter Commission → Wood's Dispatch"],["edu-macaulay-minute","edu-wood-1854","edu-hunter-1882"]],
  [9,"Which sequence correctly traces press policy?","Wellesley censorship → John Adam licensing → Metcalfe liberalisation → Vernacular Press Act",["Metcalfe liberalisation → Wellesley censorship → John Adam licensing → Vernacular Press Act","John Adam licensing → Vernacular Press Act → Wellesley censorship → Metcalfe liberalisation","Vernacular Press Act → Wellesley censorship → Metcalfe liberalisation → John Adam licensing"],["press-wellesley-1799","press-adam-1823","press-metcalfe-1835","press-vpa-1878"]],
  [9,"Which comparison of Lytton-era measures is correct?","The Vernacular Press Act restricted Indian-language newspapers, while the Arms Act restricted Indians' possession of arms",["Both measures expanded representative government","Both measures promoted university autonomy","Both measures ended racial distinctions"],["press-vpa-language","arms-license","arms-racial"]],
  [9,"Which pair shows limited constitutional and educational change in the late nineteenth century?","Indian Councils Act 1892 and Hunter Commission 1882",["Arms Act 1878 and Vernacular Press Act 1878","Doctrine of Lapse and Permanent Settlement","Rowlatt Act and Simon Commission"],["const-councils-1892","edu-hunter-1882"]],
  [10,"Which sequence about the Theosophical Society is correct?","Founded in the USA in 1875 by Blavatsky and Olcott → introduced to India in 1879 → headquarters at Adyar",["Founded at Adyar in 1875 → moved to London in 1879","Founded by Annie Besant in 1893 → headquarters at Poona","Founded by Phule in 1873 → headquarters at Banaras"],["reform-theosophy-founders","reform-theosophy-india"]],
  [10,"Which combination reflects the Theosophical programme in India?","Study of ancient religions and universal brotherhood, along with opposition to untouchability and support for women's uplift",["Separate electorates and press censorship","Land settlement and military recruitment","Indigo cultivation and revenue farming"],["reform-theosophy-aim","reform-theosophy-social"]],
  [10,"Which pair links Annie Besant's cultural and educational work?","Expansion of Theosophical influence and the Central Hindu College at Banaras",["Young Bengal and Fort William College","Satyashodhak Samaj and Calcutta Madrasa","Hunter Commission and Bengal Gazette"],["reform-besant-1893","reform-central-hindu"]],
  [10,"Which comparison of Phule and the Theosophical Society is correct?","Phule's Satyashodhak Samaj attacked caste oppression, while Theosophy stressed ancient religions and universal brotherhood",["Both were founded to enforce press censorship","Both focused mainly on arms licensing","Neither addressed social reform"],["reform-satyashodhak-aim","reform-theosophy-aim"]],
  [10,"Which sequence correctly links education and reform?","Wood's Dispatch 1854 → Satyashodhak Samaj 1873 → Hunter Commission 1882",["Hunter Commission 1882 → Wood's Dispatch 1854 → Satyashodhak Samaj 1873","Satyashodhak Samaj 1873 → Macaulay's Minute 1835 → Wood's Dispatch 1854","Wood's Dispatch 1854 → Hunter Commission 1882 → Satyashodhak Samaj 1873"],["edu-wood-1854","reform-satyashodhak-1873","edu-hunter-1882"]],
  [10,"Which statement explains the link between reform, print and nationalism?","Education created new readers, print widened public debate, and reform movements helped form the educated public from which nationalism drew support",["Press restrictions eliminated public debate","Reform movements rejected education and newspapers","Nationalism developed without an educated public sphere"],["press-public-sphere","reform-press-link","reform-public-consciousness"]],
];
