import assert from "node:assert/strict";
import { HIS_CP023_REQUIRED_FACTS_V1,HIS_CP023_REVIEW_BATCH_V1,auditHisCp023ReviewBatchV1 } from "./his-cp023-review-v1";
const audit=auditHisCp023ReviewBatchV1();
assert.equal(audit.valid,true,audit.issues.join(" | "));
assert.equal(audit.questionCount,60);
assert.equal(audit.semanticCount,60);
assert.equal(audit.canonicalFactCount,60);
assert.equal(HIS_CP023_REQUIRED_FACTS_V1.length,60);
assert.deepEqual(audit.difficultyCounts,{Easy:18,Medium:30,Hard:12});
assert.equal(Object.keys(audit.qlCounts).length,10);
assert.ok(Object.values(audit.qlCounts).every(count=>count===6));
assert.deepEqual(audit.answerPositions,[15,15,15,15]);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.every(q=>q.reviewOnly&&!q.runtimeRegistered),true);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.filter(q=>q.difficulty==="Hard").every(q=>q.sourceFactIds.length>=2),true);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.some(q=>/\bbest describ(?:e|es)\b|\bassociated with\b|which correctly identifies|^how did\b|^what was the usual relationship\b|^what was the main purpose\b|^what effect did\b/i.test(q.stem)),false);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.some(q=>/\b(?:NIOS|NCERT|UNESCO|textbook|Ministry of Culture)\b/i.test(q.stem+" "+q.explanation)),false);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.some(q=>q.stem.length>235),false);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.some(q=>q.explanation.length<150||q.explanation.length>850),false);
assert.equal(HIS_CP023_REVIEW_BATCH_V1.some(q=>(q.explanation.match(/[.!?](?:\s|$)/g)??[]).length<2),false);
console.log(JSON.stringify(audit,null,2));
