import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["NCERT-CLASS10-CONTEMPORARY-INDIA-II-MANUFACTURING-INDUSTRIES","NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES","DPIIT-INDUSTRIAL-GEOGRAPHY-AND-POLICY"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("MATCH-INDUSTRIAL-CENTRES","Match industrial centres and industries",[
{stem:"Which set correctly matches Jamshedpur, Tiruppur and Sindri with their industries?",answer:"Steel; knitwear; fertilizer",distractors:["Jute; cement; steel","Sugar; aluminium; jute","Petroleum; silk; cement"],explanation:"Jamshedpur is a steel centre, Tiruppur a knitwear cluster and Sindri a fertilizer centre.",sourceFactId:"INT-MATCH-1"},
{stem:"Which set correctly matches Coimbatore, Surat and Ludhiana with textile specialisations?",answer:"Cotton/spinning; synthetic textiles; hosiery/woollens",distractors:["Jute; steel; petrochemicals","Sugar; cement; jute","Silk; iron ore; coal"],explanation:"The three cities represent distinct textile clusters.",sourceFactId:"INT-MATCH-2"},
{stem:"Which set correctly matches Rourkela, Visakhapatnam and Salem with their states?",answer:"Odisha; Andhra Pradesh; Tamil Nadu",distractors:["Jharkhand; Odisha; Karnataka","West Bengal; Gujarat; Kerala","Chhattisgarh; Maharashtra; Telangana"],explanation:"The three steel centres lie in Odisha, Andhra Pradesh and Tamil Nadu respectively.",sourceFactId:"INT-MATCH-3"},
{stem:"Which set correctly matches Khetri, Damanjodi and Korba with their industrial role?",answer:"Copper; alumina; aluminium/power",distractors:["Jute; steel; sugar","Cotton; fertilizer; jute","Petroleum; silk; cement"],explanation:"Khetri is a copper centre, Damanjodi an alumina location and Korba a power-linked aluminium centre.",sourceFactId:"INT-MATCH-4"},
{stem:"Which set correctly matches Mumbai-Pune, Hugli and Chotanagpur with a defining feature?",answer:"Engineering/market; jute; mineral-heavy industry",distractors:["Jute; automobiles; sugar","Coal only; silk; tea","Sugar; port only; jute"],explanation:"The three industrial regions have distinct traditional specialisations.",sourceFactId:"INT-MATCH-5"},
{stem:"Which set correctly matches Chennai, Pune and Gurugram-Manesar with a common sector?",answer:"Automobile manufacturing",distractors:["Jute milling","Sugar refining","Cement production"],explanation:"All three are major automobile-manufacturing clusters.",sourceFactId:"INT-MATCH-6"}
]),
q("STATEMENT-INDUSTRIAL-GEOGRAPHY","Multi-statement industrial geography",[
{stem:"Consider the statements: I. Jamshedpur is in Jharkhand. II. Rourkela is in Odisha. III. Durgapur is in West Bengal. Which is correct?",answer:"I, II and III",distractors:["I and II only","II and III only","I and III only"],explanation:"All three steel-centre state pairs are correct.",sourceFactId:"INT-STATEMENT-1"},
{stem:"Consider the statements: I. Tiruppur is known for knitwear. II. Surat is known for synthetic textiles. III. Ludhiana is known for hosiery. Which is correct?",answer:"I, II and III",distractors:["I and II only","II and III only","I and III only"],explanation:"All three are standard textile-cluster associations.",sourceFactId:"INT-STATEMENT-2"},
{stem:"Consider the statements: I. Natural gas is used in nitrogenous fertilizer production. II. Rock phosphate is used in phosphatic fertilizer production. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The statements correctly identify key fertilizer feedstocks.",sourceFactId:"INT-STATEMENT-3"},
{stem:"Consider the statements: I. Fly ash can be used in blended cement. II. Blast-furnace slag can also be used in cement. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are industrial by-products that can be used in cement manufacture.",sourceFactId:"INT-STATEMENT-4"},
{stem:"Consider the statements: I. Mumbai-Pune is a major western industrial region. II. Hugli is strongly linked with jute. III. Chotanagpur is strongly linked with mineral-based heavy industry. Which is correct?",answer:"I, II and III",distractors:["I and II only","II and III only","I and III only"],explanation:"All three statements correctly describe major industrial regions.",sourceFactId:"INT-STATEMENT-5"},
{stem:"Consider the statements: I. Industrial corridors improve freight connectivity. II. Port access can attract bulk-cargo industries. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both transport advantages can strongly influence industrial location.",sourceFactId:"INT-STATEMENT-6"}
]),
q("ODD-ONE-OUT-INDUSTRIAL-GEOGRAPHY","Odd-one-out industrial geography",[
{stem:"Which is the odd one out: Jamshedpur, Rourkela, Bokaro, Tiruppur?",answer:"Tiruppur",distractors:["Jamshedpur","Rourkela","Bokaro"],explanation:"The first three are major steel centres; Tiruppur is a knitwear cluster.",sourceFactId:"INT-ODD-1"},
{stem:"Which is the odd one out: Coimbatore, Tiruppur, Surat, Jharia?",answer:"Jharia",distractors:["Coimbatore","Tiruppur","Surat"],explanation:"The first three are textile centres; Jharia is a coalfield.",sourceFactId:"INT-ODD-2"},
{stem:"Which is the odd one out: Khetri, Malanjkhand, Ghatsila, Neyveli?",answer:"Neyveli",distractors:["Khetri","Malanjkhand","Ghatsila"],explanation:"The first three are copper centres; Neyveli is a lignite-energy centre.",sourceFactId:"INT-ODD-3"},
{stem:"Which is the odd one out: Sindri, Namrup, Damanjodi, fertilizer gas pipeline?",answer:"Damanjodi",distractors:["Sindri","Namrup","fertilizer gas pipeline"],explanation:"Damanjodi is linked with alumina refining rather than fertilizer production.",sourceFactId:"INT-ODD-4"},
{stem:"Which is the odd one out: Mumbai-Pune, Hugli, Chotanagpur, Sambhar?",answer:"Sambhar",distractors:["Mumbai-Pune","Hugli","Chotanagpur"],explanation:"The first three are major industrial regions; Sambhar is a salt-producing location.",sourceFactId:"INT-ODD-5"},
{stem:"Which is the odd one out: Delhi-Mumbai corridor, Chennai-Bengaluru corridor, Amritsar-Kolkata corridor, Koderma mica belt?",answer:"Koderma mica belt",distractors:["Delhi-Mumbai corridor","Chennai-Bengaluru corridor","Amritsar-Kolkata corridor"],explanation:"The first three are industrial corridors; Koderma is a mineral belt.",sourceFactId:"INT-ODD-6"}
]),
q("RAW-MATERIAL-TO-INDUSTRY-CHAIN","Raw material to industry chains",[
{stem:"Which chain is correct?",answer:"Bauxite → alumina → aluminium",distractors:["Jute → alumina → aluminium","Coal → cotton → steel","Sugarcane → cement → clinker"],explanation:"Bauxite is refined to alumina and then smelted to aluminium.",sourceFactId:"INT-CHAIN-1"},
{stem:"Which chain is correct for fertilizer manufacture?",answer:"Natural gas → ammonia → urea",distractors:["Iron ore → ammonia → urea","Jute → ammonia → steel","Bauxite → urea → aluminium"],explanation:"Natural gas is used to make ammonia, which is then used for urea.",sourceFactId:"INT-CHAIN-2"},
{stem:"Which chain correctly shows cement production logic?",answer:"Limestone → clinker → cement",distractors:["Cotton → clinker → cement","Jute → clinker → steel","Bauxite → clinker → sugar"],explanation:"Limestone is a principal raw material used to make clinker and cement.",sourceFactId:"INT-CHAIN-3"},
{stem:"Which chain correctly shows sugar-industry value addition?",answer:"Sugarcane → sugar + bagasse + molasses",distractors:["Sugarcane → steel + slag","Sugarcane → aluminium + alumina","Sugarcane → jute + cotton"],explanation:"Sugar processing creates sugar and useful by-products including bagasse and molasses.",sourceFactId:"INT-CHAIN-4"},
{stem:"Which chain correctly shows textile value addition?",answer:"Cotton fibre → yarn → cloth",distractors:["Iron ore → yarn → cloth","Jute → alumina → cloth","Coal → cotton → yarn"],explanation:"Spinning converts cotton fibre into yarn and weaving converts yarn into cloth.",sourceFactId:"INT-CHAIN-5"},
{stem:"Which chain correctly shows industrial symbiosis?",answer:"Thermal power plant → fly ash → blended cement",distractors:["Jute mill → fly ash → steel","Sugar mill → chromite → cement","Cotton mill → uranium → clinker"],explanation:"Fly ash can be used as an input in blended cement.",sourceFactId:"INT-CHAIN-6"}
]),
q("LOCATION-CLUE-IDENTIFICATION","Industrial location clue identification",[
{stem:"A city is described as 'Jharkhand, Tata Steel, Singhbhum mineral belt'. Which city is it?",answer:"Jamshedpur",distractors:["Bhilai","Rourkela","Salem"],explanation:"Jamshedpur is the Tata Steel centre in Jharkhand near the Singhbhum iron-ore belt.",sourceFactId:"INT-CLUE-1"},
{stem:"A textile city is described as 'Tamil Nadu, knitwear, export-oriented garment cluster'. Which city is it?",answer:"Tiruppur",distractors:["Surat","Ludhiana","Ahmedabad"],explanation:"Tiruppur is Tamil Nadu's best-known knitwear cluster.",sourceFactId:"INT-CLUE-2"},
{stem:"A fertilizer centre is described as 'Assam, natural-gas feedstock'. Which place is it?",answer:"Namrup",distractors:["Sindri","Damanjodi","Khetri"],explanation:"Namrup is a major gas-linked fertilizer centre in Assam.",sourceFactId:"INT-CLUE-3"},
{stem:"An aluminium centre is described as 'Uttar Pradesh, Sonbhadra, power-rich location'. Which place is it?",answer:"Renukoot",distractors:["Korba","Angul","Khetri"],explanation:"Renukoot is a major aluminium centre in Sonbhadra, Uttar Pradesh.",sourceFactId:"INT-CLUE-4"},
{stem:"An industrial region is described as 'West Bengal, Kolkata port, jute mills'. Which region is it?",answer:"Hugli industrial region",distractors:["Mumbai-Pune region","Chotanagpur region","Delhi-NCR region"],explanation:"The Hugli belt developed around Kolkata port and jute milling.",sourceFactId:"INT-CLUE-5"},
{stem:"A corridor is described as 'southern manufacturing axis linking an automobile port city with a technology-engineering centre'. Which corridor is it?",answer:"Chennai-Bengaluru Industrial Corridor",distractors:["Delhi-Mumbai Industrial Corridor","Amritsar-Kolkata Industrial Corridor","Hugli industrial region"],explanation:"Chennai and Bengaluru anchor this southern industrial corridor.",sourceFactId:"INT-CLUE-6"}
]),
q("CROSS-INDUSTRY-COMPARATIVE-REASONING","Cross-industry comparative reasoning",[
{stem:"Which comparison is correct?",answer:"Steel is strongly mineral-oriented, while garments can be labour- and market-oriented",distractors:["Both depend only on sugarcane","Garments require iron ore","Steel depends only on tourism"],explanation:"Different industries respond to different location factors.",sourceFactId:"INT-COMPARE-1"},
{stem:"Which comparison is correct for aluminium and cement?",answer:"Aluminium smelting is especially power-intensive, while cement is strongly linked with limestone",distractors:["Both depend only on jute","Cement is made from bauxite","Aluminium uses sugarcane"],explanation:"The two industries have distinct raw-material and energy requirements.",sourceFactId:"INT-COMPARE-2"},
{stem:"Which comparison is correct for Tiruppur and Jamshedpur?",answer:"Tiruppur is a textile cluster, while Jamshedpur is a steel centre",distractors:["Both are jute centres","Both are coalfields","Jamshedpur is a garment cluster"],explanation:"The two cities represent very different industrial sectors.",sourceFactId:"INT-COMPARE-3"},
{stem:"Which comparison is correct for Hugli and Chotanagpur?",answer:"Hugli is strongly linked with jute, while Chotanagpur is linked with mineral-heavy industry",distractors:["Both are textile-only regions","Chotanagpur has no minerals","Hugli is a steel belt only"],explanation:"Their industrial identities arise from different resource and transport bases.",sourceFactId:"INT-COMPARE-4"},
{stem:"Which comparison is correct for port-based and mine-mouth industry?",answer:"Port-based industry stresses maritime logistics, while mine-mouth industry stresses raw-material proximity",distractors:["Both ignore transport","Ports are mineral deposits","Mine-mouth plants depend only on imports"],explanation:"The two location strategies reflect different transport and input conditions.",sourceFactId:"INT-COMPARE-5"},
{stem:"Which comparison is correct for Sindri and Namrup?",answer:"Both are fertilizer centres, but Namrup is especially linked with natural gas",distractors:["Both are jute centres","Sindri is a steel plant","Namrup is a cement centre"],explanation:"Both are fertilizer locations, while Namrup's gas-feedstock link is particularly distinctive.",sourceFactId:"INT-COMPARE-6"}
])
]);
export const GEO_IND_001_CP012_REVIEW_BATCH_V1=finalizeGeoIndCp(12,QLS);
export function auditGeoInd001Cp012ReviewBatchV1(){return auditGeoIndCp(12,QLS,GEO_IND_001_CP012_REVIEW_BATCH_V1);}
