import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["NCERT-CLASS10-CONTEMPORARY-INDIA-II-MANUFACTURING-INDUSTRIES","NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES","MINISTRY-OF-MINES-INDIA"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("CEMENT-RAW-MATERIALS","Cement raw materials",[
{stem:"Which mineral is the principal raw material for cement manufacture?",answer:"Limestone",distractors:["Mica","Bauxite","Chromite"],explanation:"Limestone supplies the calcium-rich material required for cement manufacture.",sourceFactId:"CEMENT-LIMESTONE"},
{stem:"Which mineral is added to cement to help control setting time?",answer:"Gypsum",distractors:["Manganese","Copper","Barytes"],explanation:"Gypsum is added in small quantities during cement manufacture to regulate setting.",sourceFactId:"CEMENT-GYPSUM"},
{stem:"Consider the statements: I. Limestone is a key cement raw material. II. Gypsum is used during cement manufacture. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both limestone and gypsum are important inputs in the cement industry.",sourceFactId:"CEMENT-STATEMENT"},
{stem:"Which industry directly depends on large limestone deposits?",answer:"Cement industry",distractors:["Jute industry","Sugar industry","Cotton textile industry"],explanation:"Cement manufacture requires large quantities of limestone, making the industry strongly linked with limestone geography.",sourceFactId:"CEMENT-LIMESTONE-IND"},
{stem:"Which pair is correctly matched in cement raw materials?",answer:"Limestone — principal raw material",distractors:["Mica — principal raw material","Cotton — principal mineral input","Jute — flux"],explanation:"Limestone is the dominant mineral raw material for cement production.",sourceFactId:"CEMENT-MATCH"},
{stem:"A plant receives limestone, gypsum and fuel before producing clinker and cement. Which industry is it?",answer:"Cement industry",distractors:["Sugar industry","Steel industry","Jute industry"],explanation:"These inputs and clinker production identify a cement plant.",sourceFactId:"CEMENT-CLUE"}
]),
q("CEMENT-LOCATION-LOGIC","Cement industry location logic",[
{stem:"Why are cement plants often located close to limestone deposits?",answer:"Limestone is bulky and required in large quantities",distractors:["Cement uses only imported cotton","Limestone cannot be moved at all","Markets are irrelevant"],explanation:"Transporting large volumes of limestone is costly, so proximity to deposits can reduce freight costs.",sourceFactId:"CEMENT-LOCATION"},
{stem:"Which factor most directly explains a cement plant beside a limestone quarry?",answer:"Raw-material proximity",distractors:["Tourism","Tidal range","Cotton supply"],explanation:"The plant is source-oriented because limestone is the dominant bulky input.",sourceFactId:"CEMENT-RAW-LOC"},
{stem:"Consider the statements: I. Cement plants can be raw-material oriented. II. Transport remains important for moving cement to markets. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Plants benefit from limestone proximity but also need efficient transport to distribute finished cement.",sourceFactId:"CEMENT-LOC-STATEMENT"},
{stem:"Which factor becomes especially important after cement is produced?",answer:"Transport to construction markets",distractors:["Ore beneficiation only","Sugarcane harvesting","Jute retting"],explanation:"Cement is bulky, so distribution logistics are important even when plants are located near raw materials.",sourceFactId:"CEMENT-MARKET-TRANSPORT"},
{stem:"Which pair is correctly matched in cement-location logic?",answer:"Limestone deposits — source-oriented plant location",distractors:["Tea gardens — cement plant location","Cotton belt — clinker source","Jute belt — limestone source"],explanation:"Cement plants are often linked closely to limestone deposits.",sourceFactId:"CEMENT-LOC-MATCH"},
{stem:"A cement factory is near a quarry but connected by rail to large cities. Which two factors are being combined?",answer:"Raw material and market transport",distractors:["Tidal energy and fisheries","Cotton and jute","Tea and coffee"],explanation:"The plant minimises limestone freight while maintaining access to urban construction markets.",sourceFactId:"CEMENT-TWO-FACTORS"}
]),
q("RAJASTHAN-CEMENT-GEOGRAPHY","Rajasthan cement geography",[
{stem:"Which state is strongly linked with limestone-based cement production in north-western India?",answer:"Rajasthan",distractors:["Assam","Punjab","Kerala"],explanation:"Rajasthan has extensive limestone resources and a major cement-industry presence.",sourceFactId:"CEMENT-RAJASTHAN"},
{stem:"Why is Rajasthan favourable for cement manufacture?",answer:"It has large limestone resources",distractors:["It lacks mineral raw materials","It depends only on imported sugarcane","It has no transport links"],explanation:"Abundant limestone gives Rajasthan a major raw-material advantage for cement production.",sourceFactId:"CEMENT-RAJASTHAN-REASON"},
{stem:"Consider the statements: I. Rajasthan has major limestone deposits. II. Limestone supports cement manufacture. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two facts are directly connected in Rajasthan's industrial geography.",sourceFactId:"CEMENT-RAJASTHAN-STATEMENT"},
{stem:"Which pair correctly identifies Rajasthan's cement-resource geography?",answer:"Rajasthan — limestone and cement",distractors:["Rajasthan — jute only","Rajasthan — no cement industry","Rajasthan — offshore oil only"],explanation:"Rajasthan is a major limestone and cement state.",sourceFactId:"CEMENT-RAJASTHAN-MATCH"},
{stem:"A map marks a major cement belt over limestone-rich north-western India. Which state is a strong answer?",answer:"Rajasthan",distractors:["Nagaland","Manipur","Tripura"],explanation:"Rajasthan is one of the country's best-known limestone-rich cement regions.",sourceFactId:"CEMENT-RAJASTHAN-MAP"},
{stem:"Which industry-resource chain is correct for Rajasthan?",answer:"Limestone → cement",distractors:["Mica → sugar","Cotton → steel","Jute → aluminium"],explanation:"Limestone is the key cement raw material and is abundant in Rajasthan.",sourceFactId:"CEMENT-RAJASTHAN-CHAIN"}
]),
q("CENTRAL-WESTERN-CEMENT-BELTS","Central and western cement belts",[
{stem:"Which central Indian state has major limestone resources supporting cement manufacture?",answer:"Madhya Pradesh",distractors:["Punjab","Assam","Goa only"],explanation:"Madhya Pradesh contains large limestone deposits and significant cement-industry activity.",sourceFactId:"CEMENT-MP"},
{stem:"Which western state has both limestone resources and a major cement industry?",answer:"Gujarat",distractors:["Sikkim","Nagaland","Tripura"],explanation:"Gujarat combines limestone deposits, industrial infrastructure and strong market/port connections.",sourceFactId:"CEMENT-GUJARAT"},
{stem:"Consider the statements: I. Madhya Pradesh is important for cement. II. Gujarat also has major cement production. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both states have durable limestone-cement geography.",sourceFactId:"CEMENT-MP-GJ"},
{stem:"Which pair correctly identifies a central Indian cement region?",answer:"Madhya Pradesh — limestone-based cement",distractors:["Madhya Pradesh — jute only","Gujarat — no limestone","Gujarat — only tea processing"],explanation:"Madhya Pradesh is a major limestone-cement region, and Gujarat also has an important cement industry.",sourceFactId:"CEMENT-MP-MATCH"},
{stem:"Why can Gujarat support large cement plants beyond raw-material availability?",answer:"Ports, transport and large markets add locational advantages",distractors:["It has no transport","It lacks markets","It depends only on forests"],explanation:"Industrial infrastructure and market access complement Gujarat's raw-material base.",sourceFactId:"CEMENT-GUJARAT-ADV"},
{stem:"Which comparison is correct for cement geography?",answer:"Rajasthan and Madhya Pradesh both have major limestone-cement regions",distractors:["Both are jute-only regions","Neither has limestone","Both depend only on imported clinker"],explanation:"Both states are important limestone-rich cement regions.",sourceFactId:"CEMENT-RJ-MP"}
]),
q("CEMENT-ENERGY-AND-TRANSPORT","Cement energy and transport requirements",[
{stem:"Why does cement manufacture require substantial energy?",answer:"Raw materials must be heated to high temperatures to make clinker",distractors:["Cement is grown in fields","No heat is used","Only sunlight is required"],explanation:"Clinker production uses high-temperature kilns, making energy a major input.",sourceFactId:"CEMENT-ENERGY"},
{stem:"Which stage of cement production is especially energy-intensive?",answer:"Clinker production in kilns",distractors:["Retail sale only","Packaging only","Limestone mapping only"],explanation:"Kilns require high heat to transform raw meal into clinker.",sourceFactId:"CEMENT-CLINKER"},
{stem:"Consider the statements: I. Cement plants need energy for kilns. II. Transport is important because cement is bulky. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both energy use and freight requirements shape cement economics and location.",sourceFactId:"CEMENT-ENERGY-TRANSPORT"},
{stem:"Which transport mode is useful for moving large quantities of cement over land?",answer:"Rail freight",distractors:["Only air freight","Only pipelines","Only animal transport"],explanation:"Railways are efficient for bulk movement of cement and other heavy industrial goods.",sourceFactId:"CEMENT-RAIL"},
{stem:"Which pair is correctly matched in cement production?",answer:"Clinker kiln — high energy use",distractors:["Clinker kiln — cotton spinning","Gypsum — sugar refining","Limestone — jute retting"],explanation:"Clinker formation is the high-temperature core of cement manufacture.",sourceFactId:"CEMENT-KILN-MATCH"},
{stem:"A plant has nearby limestone, reliable power and a rail siding. Which industry fits best?",answer:"Cement",distractors:["Jute textiles","Sugar","Tea processing"],explanation:"The combination of limestone, energy and bulk transport strongly indicates cement manufacturing.",sourceFactId:"CEMENT-CLUE-2"}
]),
q("CHHATTISGARH-CEMENT-REGION","Chhattisgarh cement region",[
{stem:"Which state combines major limestone resources with a strong cement industry in central-eastern India?",answer:"Chhattisgarh",distractors:["Punjab","Assam","Kerala"],explanation:"Chhattisgarh has substantial limestone resources that support cement manufacture.",sourceFactId:"CEMENT-CG"},
{stem:"Why is Chhattisgarh favourable for cement plants?",answer:"Limestone and energy resources are available",distractors:["It has no mineral resources","Only jute matters","Only ports matter"],explanation:"The state combines limestone with coal, power and industrial infrastructure.",sourceFactId:"CEMENT-CG-REASON"},
{stem:"Consider the statements: I. Chhattisgarh has limestone. II. Limestone supports cement manufacture. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The state's limestone base is directly linked with cement-industry development.",sourceFactId:"CEMENT-CG-STATEMENT"},
{stem:"Which pair is correctly matched in Chhattisgarh industrial geography?",answer:"Chhattisgarh — limestone-based cement",distractors:["Chhattisgarh — jute only","Chhattisgarh — no limestone","Chhattisgarh — tea only"],explanation:"Chhattisgarh is a major limestone-cement region.",sourceFactId:"CEMENT-CG-MATCH"},
{stem:"A cement map highlights the state containing Raipur and Durg. Which state is it?",answer:"Chhattisgarh",distractors:["Haryana","Punjab","Kerala"],explanation:"Raipur and Durg lie within Chhattisgarh's industrial and limestone-rich belt.",sourceFactId:"CEMENT-CG-MAP"},
{stem:"Which comparison is correct for central cement geography?",answer:"Madhya Pradesh and Chhattisgarh both have major limestone-based cement industries",distractors:["Neither has limestone","Both are jute-only states","Both depend only on imported clinker"],explanation:"Both states possess major limestone resources and cement industries.",sourceFactId:"CEMENT-MP-CG"}
]),
q("BLENDED-CEMENT-BYPRODUCTS","Blended cement and industrial by-products",[
{stem:"Which thermal-power by-product can be used in blended cement?",answer:"Fly ash",distractors:["Bagasse","Raw jute","Bauxite ore"],explanation:"Fly ash can be used in Portland pozzolana cement and related blended products.",sourceFactId:"CEMENT-FLYASH"},
{stem:"Which iron-and-steel by-product can be used in some blended cements?",answer:"Granulated blast-furnace slag",distractors:["Cotton fibre","Molasses","Raw mica"],explanation:"Granulated blast-furnace slag can be ground and used in slag cement.",sourceFactId:"CEMENT-SLAG"},
{stem:"Consider the statements: I. Fly ash can be used in blended cement. II. Blast-furnace slag can also be used in cement manufacture. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both industrial by-products can serve as supplementary cementitious materials.",sourceFactId:"CEMENT-BLEND-STATEMENT"},
{stem:"Which chain correctly shows industrial symbiosis?",answer:"Thermal power plant → fly ash → blended cement",distractors:["Jute mill → iron ore → cement","Sugar mill → chromite → cement","Cotton mill → uranium → cement"],explanation:"Using fly ash in cement links one industry's by-product with another industry's input.",sourceFactId:"CEMENT-FLYASH-CHAIN"},
{stem:"Which pair is correctly matched in blended-cement production?",answer:"Steel-plant slag — cement input",distractors:["Steel slag — cotton fibre","Fly ash — jute fibre","Molasses — clinker"],explanation:"Processed blast-furnace slag can be used in cement manufacture.",sourceFactId:"CEMENT-SLAG-MATCH"},
{stem:"Why can cement plants benefit from proximity to thermal power or steel complexes?",answer:"They can use fly ash or slag as supplementary materials",distractors:["They receive sugarcane there","They mine jute there","They need tea leaves"],explanation:"Industrial by-products can become useful cement inputs, reducing waste and transport.",sourceFactId:"CEMENT-SYMBIOSIS"}
])
]);
export const GEO_IND_001_CP005_REVIEW_BATCH_V1=finalizeGeoIndCp(5,QLS);
export function auditGeoInd001Cp005ReviewBatchV1(){return auditGeoIndCp(5,QLS,GEO_IND_001_CP005_REVIEW_BATCH_V1);}
