import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES","DPIIT-INDUSTRIAL-GEOGRAPHY-AND-POLICY"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("MUMBAI-PUNE-INDUSTRIAL-REGION","Mumbai-Pune industrial region",[
{stem:"Which industrial region combines Mumbai's port and market advantages with Pune's engineering base?",answer:"Mumbai-Pune industrial region",distractors:["Hugli industrial region","Chotanagpur industrial region","Kollam-Thiruvananthapuram region"],explanation:"The Mumbai-Pune belt is one of India's major diversified industrial regions.",sourceFactId:"REG-MUMBAI-PUNE"},
{stem:"Which state contains the Mumbai-Pune industrial region?",answer:"Maharashtra",distractors:["Gujarat","West Bengal","Karnataka"],explanation:"Mumbai and Pune are both in Maharashtra.",sourceFactId:"REG-MP-STATE"},
{stem:"Which factors helped Mumbai-Pune become a major industrial region?",answer:"Port, market, capital, transport and skilled labour",distractors:["Only iron ore","Only sugarcane","Only rainfall"],explanation:"The region grew through a combination of port access, finance, labour, markets and transport.",sourceFactId:"REG-MP-FACTORS"},
{stem:"Consider the statements: I. Mumbai is a major port city. II. Pune is a major engineering and automobile centre. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both cities contribute different strengths to the wider industrial region.",sourceFactId:"REG-MP-STATEMENT"},
{stem:"Which pair correctly identifies the Mumbai-Pune industrial region?",answer:"Mumbai-Pune — Maharashtra",distractors:["Mumbai-Pune — West Bengal","Mumbai-Pune — Odisha","Mumbai-Pune — Assam"],explanation:"The region lies in Maharashtra.",sourceFactId:"REG-MP-MATCH"},
{stem:"Which industry is strongly represented in the Pune part of the Mumbai-Pune region?",answer:"Automobiles and engineering",distractors:["Jute only","Tea processing only","Coal mining only"],explanation:"Pune is a major automobile and engineering centre.",sourceFactId:"REG-MP-PUNE"}
]),
q("HUGLI-INDUSTRIAL-REGION","Hugli industrial region",[
{stem:"Which river is central to the Hugli industrial region?",answer:"Hugli River",distractors:["Narmada","Godavari","Sutlej"],explanation:"The Hugli industrial belt developed along the Hugli River around Kolkata.",sourceFactId:"REG-HUGLI-RIVER"},
{stem:"Which industry is historically prominent in the Hugli industrial belt?",answer:"Jute textiles",distractors:["Aluminium only","Sugar only","Cement only"],explanation:"The Hugli belt is India's classic jute-milling region.",sourceFactId:"REG-HUGLI-JUTE"},
{stem:"Which state contains the Hugli industrial region?",answer:"West Bengal",distractors:["Gujarat","Tamil Nadu","Punjab"],explanation:"The Hugli belt lies in West Bengal.",sourceFactId:"REG-HUGLI-STATE"},
{stem:"Consider the statements: I. Kolkata port supported the Hugli region. II. Jute mills concentrated along the river. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Port, river, labour and jute supply all supported the region.",sourceFactId:"REG-HUGLI-STATEMENT"},
{stem:"Which pair correctly identifies the Hugli industrial region?",answer:"Hugli — West Bengal",distractors:["Hugli — Rajasthan","Hugli — Karnataka","Hugli — Punjab"],explanation:"The Hugli industrial region lies in West Bengal.",sourceFactId:"REG-HUGLI-MATCH"},
{stem:"Why did the Hugli region become highly industrialised?",answer:"Port, coal access, labour, transport and raw materials were available",distractors:["It had no transport","It depended only on tourism","Only climate mattered"],explanation:"The region combined multiple industrial-location advantages.",sourceFactId:"REG-HUGLI-REASON"}
]),
q("CHOTANAGPUR-INDUSTRIAL-REGION","Chotanagpur industrial region",[
{stem:"Which industrial region is centred on India's major coal and iron-ore belt?",answer:"Chotanagpur industrial region",distractors:["Mumbai-Pune region","Hugli region","Kollam-Thiruvananthapuram region"],explanation:"Chotanagpur combines coal, iron ore, steel plants and heavy engineering.",sourceFactId:"REG-CHOTANAGPUR"},
{stem:"Which industries dominate the Chotanagpur industrial region?",answer:"Iron and steel, engineering and mineral-based industries",distractors:["Jute only","Sugar only","Tea only"],explanation:"The region's mineral base supports heavy and metallurgical industries.",sourceFactId:"REG-CHOTANAGPUR-IND"},
{stem:"Which states are strongly represented in the Chotanagpur mineral-industrial belt?",answer:"Jharkhand, Odisha and adjoining eastern-central states",distractors:["Kerala and Goa only","Punjab and Haryana only","Assam and Meghalaya only"],explanation:"The industrial belt extends across the eastern mineral zone.",sourceFactId:"REG-CHOTANAGPUR-STATES"},
{stem:"Consider the statements: I. Jamshedpur lies in this region. II. Coal and iron ore are major locational advantages. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both facts are central to Chotanagpur industrial geography.",sourceFactId:"REG-CHOTANAGPUR-STATEMENT"},
{stem:"Which pair correctly identifies the Chotanagpur industrial region?",answer:"Chotanagpur — heavy mineral-based industry",distractors:["Chotanagpur — jute only","Chotanagpur — no minerals","Chotanagpur — sugar only"],explanation:"The region is dominated by mineral-based heavy industries.",sourceFactId:"REG-CHOTANAGPUR-MATCH"},
{stem:"Why is the Chotanagpur region a classic resource-oriented industrial belt?",answer:"Major mineral and energy resources occur close together",distractors:["It has no coal","It has no iron ore","Only ports matter"],explanation:"Coal, iron ore and other minerals occur in close proximity, supporting heavy industry.",sourceFactId:"REG-CHOTANAGPUR-REASON"}
]),
q("GUJARAT-INDUSTRIAL-REGION","Gujarat industrial region",[
{stem:"Which industrial region is strongly linked with Ahmedabad, Vadodara and Surat?",answer:"Gujarat industrial region",distractors:["Hugli region","Chotanagpur region","Kollam region"],explanation:"Ahmedabad, Vadodara and Surat are major industrial centres of Gujarat.",sourceFactId:"REG-GUJARAT"},
{stem:"Which industries are prominent in Gujarat's industrial region?",answer:"Textiles, chemicals, petrochemicals and engineering",distractors:["Jute only","Tea only","Coal mining only"],explanation:"Gujarat has a diversified industrial base supported by ports, refineries and markets.",sourceFactId:"REG-GUJARAT-IND"},
{stem:"Which locational factor especially strengthens Gujarat's industrial region?",answer:"Port access and refinery-petrochemical infrastructure",distractors:["Only snow cover","Only forest products","Only iron ore"],explanation:"Ports and hydrocarbon infrastructure are major advantages.",sourceFactId:"REG-GUJARAT-FACTOR"},
{stem:"Consider the statements: I. Ahmedabad is a textile centre. II. Surat is important for synthetic textiles. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are major textile centres with different specialisations.",sourceFactId:"REG-GUJARAT-STATEMENT"},
{stem:"Which pair correctly identifies the Bengaluru-Tamil Nadu industrial region?",answer:"Gujarat — textiles and petrochemicals",distractors:["Gujarat — jute only","Gujarat — no ports","Gujarat — no chemicals"],explanation:"The state combines major textile and petrochemical industries.",sourceFactId:"REG-GUJARAT-MATCH"},
{stem:"Which city is especially important for synthetic textiles within Gujarat?",answer:"Surat",distractors:["Dhanbad","Rourkela","Jharia"],explanation:"Surat is one of India's major synthetic-textile centres.",sourceFactId:"REG-GUJARAT-SURAT"}
]),
q("BENGALURU-TAMIL-NADU-INDUSTRIAL-REGION","Bengaluru-Tamil Nadu industrial region",[
{stem:"Which industrial region combines Bengaluru's engineering base with Tamil Nadu's automobile and textile clusters?",answer:"Bengaluru-Tamil Nadu industrial region",distractors:["Hugli industrial region","Chotanagpur industrial region","Mumbai-Pune only"],explanation:"Southern peninsular industry forms a broad belt linking Bengaluru with major Tamil Nadu centres.",sourceFactId:"REG-BLR-TN"},
{stem:"Which industries are prominent in this southern industrial region?",answer:"Engineering, automobiles, textiles and high-technology manufacturing",distractors:["Jute only","Coal mining only","Sugar only"],explanation:"The region is diversified across engineering and manufacturing sectors.",sourceFactId:"REG-BLR-TN-IND"},
{stem:"Consider the statements: I. Bengaluru is a major engineering centre. II. Chennai is a major automobile centre. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both cities are major anchors of southern industrial geography.",sourceFactId:"REG-BLR-TN-STATEMENT"},
{stem:"Which pair is correctly matched in southern industrial geography?",answer:"Bengaluru — engineering and aerospace",distractors:["Bengaluru — jute only","Chennai — coalfield","Coimbatore — petroleum field"],explanation:"Bengaluru is a major engineering and aerospace centre.",sourceFactId:"REG-BLR-TN-MATCH"},
{stem:"Which Tamil Nadu city is especially important for automobiles?",answer:"Chennai",distractors:["Jharia","Koderma","Sambhar"],explanation:"Chennai anchors one of India's largest automobile clusters.",sourceFactId:"REG-BLR-TN-CHENNAI"},
{stem:"Why has this region grown despite being away from the classic eastern coal-steel belt?",answer:"Skilled labour, markets, infrastructure and modern transport reduce dependence on coalfield proximity",distractors:["It has no industry","Only minerals matter","Ports prevent growth"],explanation:"Modern industries often rely more on skills, markets and infrastructure than on direct coalfield access.",sourceFactId:"REG-BLR-TN-REASON"}
]),
q("VISAKHAPATNAM-GUNTUR-INDUSTRIAL-REGION","Visakhapatnam-Guntur industrial region",[
{stem:"Which coastal industrial region is centred on Visakhapatnam and extends through parts of Andhra Pradesh?",answer:"Visakhapatnam-Guntur industrial region",distractors:["Hugli region","Mumbai-Pune region","Chotanagpur region"],explanation:"The Visakhapatnam-Guntur belt is a recognised industrial region of Andhra Pradesh.",sourceFactId:"REG-VIZAG-GUNTUR"},
{stem:"Which factor strongly supports Visakhapatnam's industrial growth?",answer:"Major port access",distractors:["Jute cultivation only","No transport","Only rainfall"],explanation:"The port supports bulk cargo, steel, petroleum and other industrial activities.",sourceFactId:"REG-VIZAG-PORT"},
{stem:"Consider the statements: I. Visakhapatnam is a major port. II. It hosts major steel and industrial activity. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are key features of the region.",sourceFactId:"REG-VIZAG-STATEMENT"},
{stem:"Which pair correctly identifies the Visakhapatnam-Guntur industrial region?",answer:"Visakhapatnam-Guntur — Andhra Pradesh",distractors:["Visakhapatnam-Guntur — Punjab","Visakhapatnam-Guntur — Rajasthan","Visakhapatnam-Guntur — Assam"],explanation:"The region lies in Andhra Pradesh.",sourceFactId:"REG-VIZAG-MATCH"},
{stem:"Which heavy industry is especially important at Visakhapatnam?",answer:"Iron and steel",distractors:["Jute only","Sugar only","Wool only"],explanation:"Visakhapatnam Steel Plant is a major heavy-industry anchor.",sourceFactId:"REG-VIZAG-STEEL"},
{stem:"Why is the region suited to diversified industry?",answer:"Port, transport, markets and a large hinterland are available",distractors:["It lacks infrastructure","Only one crop matters","It has no labour"],explanation:"Its coastal and transport advantages support multiple industries.",sourceFactId:"REG-VIZAG-REASON"}
]),
q("DELHI-MEERUT-GURUGRAM-INDUSTRIAL-REGION","Delhi-Meerut-Gurugram industrial region",[
{stem:"Which industrial region is strongly shaped by the large Delhi-NCR market?",answer:"Delhi-Meerut-Gurugram industrial region",distractors:["Hugli region","Chotanagpur region","Kollam region"],explanation:"The NCR industrial belt is strongly market- and transport-oriented.",sourceFactId:"REG-NCR"},
{stem:"Which industries are prominent in Delhi-NCR?",answer:"Automobiles, electronics, engineering and consumer goods",distractors:["Jute only","Coal mining only","Tea only"],explanation:"The region has a diversified manufacturing base.",sourceFactId:"REG-NCR-IND"},
{stem:"Which factor is especially important to Delhi-NCR industrial growth?",answer:"Large market and transport connectivity",distractors:["Iron ore only","Jute cultivation","Tidal power"],explanation:"NCR benefits from dense demand, highways, labour and supplier networks.",sourceFactId:"REG-NCR-FACTOR"},
{stem:"Consider the statements: I. Gurugram-Manesar is an automobile belt. II. NCR has a very large consumer market. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both facts support the region's industrial geography.",sourceFactId:"REG-NCR-STATEMENT"},
{stem:"Which pair correctly identifies the Delhi-NCR industrial region?",answer:"Gurugram-Manesar — automobile manufacturing",distractors:["Gurugram-Manesar — jute only","Meerut — coalfield","Delhi — iron-ore mine"],explanation:"The Gurugram-Manesar belt is a major automobile-manufacturing cluster.",sourceFactId:"REG-NCR-MATCH"},
{stem:"Why is this region less dependent on proximity to mineral raw materials than Chotanagpur?",answer:"Many industries are market-, skill- and infrastructure-oriented",distractors:["It has no industry","All industries need coal mines","Transport is irrelevant"],explanation:"Modern engineering and consumer industries can locate close to markets and labour rather than mineral sources.",sourceFactId:"REG-NCR-REASON"}
]),
q("KOLLAM-THIRUVANANTHAPURAM-INDUSTRIAL-REGION","Kollam-Thiruvananthapuram industrial region",[
{stem:"Which industrial region lies in southern Kerala?",answer:"Kollam-Thiruvananthapuram industrial region",distractors:["Hugli industrial region","Chotanagpur industrial region","Mumbai-Pune industrial region"],explanation:"The Kollam-Thiruvananthapuram belt is one of India's recognised industrial regions.",sourceFactId:"REG-KOLLAM-TVM"},
{stem:"Which state contains the Kollam-Thiruvananthapuram industrial region?",answer:"Kerala",distractors:["Tamil Nadu","Karnataka","Gujarat"],explanation:"Both Kollam and Thiruvananthapuram are in Kerala.",sourceFactId:"REG-KOLLAM-TVM-STATE"},
{stem:"Which industries have traditionally contributed to this region?",answer:"Agro-processing, mineral-based and light manufacturing",distractors:["Only integrated steel","Only jute","Only coal mining"],explanation:"The region is more diversified toward processing and lighter industries than the eastern heavy-industry belt.",sourceFactId:"REG-KOLLAM-TVM-IND"},
{stem:"Consider the statements: I. The region is in Kerala. II. It differs from Chotanagpur in having less dependence on coal and iron ore. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two industrial regions have very different resource and location bases.",sourceFactId:"REG-KOLLAM-TVM-STATEMENT"},
{stem:"Which pair is correctly matched in industrial-region geography?",answer:"Kollam-Thiruvananthapuram — Kerala",distractors:["Kollam-Thiruvananthapuram — Jharkhand","Kollam-Thiruvananthapuram — Gujarat","Kollam-Thiruvananthapuram — Punjab"],explanation:"The region lies in southern Kerala.",sourceFactId:"REG-KOLLAM-TVM-MATCH"},
{stem:"Which comparison is correct for Indian industrial regions?",answer:"Chotanagpur is mineral-heavy, while Kollam-Thiruvananthapuram is less dependent on coal and iron ore",distractors:["Both are identical steel belts","Kerala region is a coalfield","Chotanagpur is a port-only region"],explanation:"The comparison highlights contrasting industrial-location foundations.",sourceFactId:"REG-KOLLAM-TVM-COMPARE"}
]),
q("INDUSTRIAL-REGION-COMPARATIVE-IDENTIFICATION","Industrial-region comparative identification",[
{stem:"Which Indian industrial region is the classic jute belt?",answer:"Hugli",distractors:["Chotanagpur","Mumbai-Pune","Bengaluru-Tamil Nadu"],explanation:"The Hugli belt is India's classic jute industrial region.",sourceFactId:"REG-COMPARE-JUTE"},
{stem:"Which Indian industrial region is centred on coal, iron ore and steel?",answer:"Chotanagpur",distractors:["Kollam-Thiruvananthapuram","Delhi-NCR","Mumbai-Pune"],explanation:"Coal, iron ore and steel dominate Chotanagpur's industrial identity.",sourceFactId:"REG-COMPARE-HEAVY"},
{stem:"Which industrial region is strongly identified with automobiles and engineering in western India?",answer:"Mumbai-Pune",distractors:["Hugli","Kollam-Thiruvananthapuram","Visakhapatnam-Guntur only"],explanation:"Pune is a major auto-engineering centre within the Mumbai-Pune belt.",sourceFactId:"REG-COMPARE-AUTO"},
{stem:"Which industrial region is especially market-oriented around India's largest northern metropolitan area?",answer:"Delhi-Meerut-Gurugram",distractors:["Chotanagpur","Hugli","Kollam-Thiruvananthapuram"],explanation:"The NCR industrial belt benefits strongly from a vast consumer market and connectivity.",sourceFactId:"REG-COMPARE-NCR"},
{stem:"Which industrial region combines major southern engineering and automobile centres?",answer:"Bengaluru-Tamil Nadu",distractors:["Hugli","Chotanagpur","Gujarat only"],explanation:"Bengaluru and Chennai anchor a major southern manufacturing region.",sourceFactId:"REG-COMPARE-SOUTH"},
{stem:"Which sequence correctly matches industrial regions with a defining feature?",answer:"Hugli—jute; Chotanagpur—steel; Mumbai-Pune—engineering",distractors:["Hugli—steel only; Chotanagpur—jute; Mumbai-Pune—coal mining","All three—jute","All three—sugar"],explanation:"The sequence captures the distinctive traditional specialisations of the three regions.",sourceFactId:"REG-COMPARE-SEQUENCE"}
])
]);
export const GEO_IND_001_CP009_REVIEW_BATCH_V1=finalizeGeoIndCp(9,QLS);
export function auditGeoInd001Cp009ReviewBatchV1(){return auditGeoIndCp(9,QLS,GEO_IND_001_CP009_REVIEW_BATCH_V1);}
