import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES","DEPARTMENT-OF-CHEMICALS-PETROCHEMICALS-INDIA","DEPARTMENT-OF-FERTILIZERS-INDIA"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("PETROCHEMICAL-FEEDSTOCK-LOGIC","Petrochemical feedstock and location logic",[
{stem:"Which industry supplies the basic feedstocks for many synthetic fibres and plastics?",answer:"Petrochemical industry",distractors:["Sugar industry","Jute industry","Cement industry"],explanation:"Petrochemicals provide feedstocks for plastics, synthetic fibres, rubbers and many chemicals.",sourceFactId:"PETRO-FEEDSTOCK"},
{stem:"Why do petrochemical complexes often develop near oil refineries?",answer:"Refineries supply hydrocarbon feedstocks",distractors:["They need jute fibre","They depend on limestone only","They require sugarcane"],explanation:"Refineries provide naphtha and other hydrocarbon streams used by petrochemical plants.",sourceFactId:"PETRO-REFINERY-LINK"},
{stem:"Consider the statements: I. Petrochemicals use hydrocarbon feedstocks. II. Refineries can provide these feedstocks. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both statements explain why refinery-petrochemical integration is common.",sourceFactId:"PETRO-STATEMENT"},
{stem:"Which pair is correctly matched in petrochemical location logic?",answer:"Oil refinery — petrochemical feedstock source",distractors:["Jute mill — naphtha source","Sugar mill — ethylene source","Cement plant — polymer feedstock"],explanation:"Refineries are important upstream suppliers to petrochemical complexes.",sourceFactId:"PETRO-MATCH"},
{stem:"Which product is commonly derived from petrochemical feedstocks?",answer:"Synthetic polymer",distractors:["Raw jute","Iron ore","Limestone"],explanation:"Polymers and many synthetic materials originate from petrochemical feedstocks.",sourceFactId:"PETRO-POLYMER"},
{stem:"A chemical complex is built next to a large refinery and port. Which industry is the strongest fit?",answer:"Petrochemicals",distractors:["Jute textiles","Sugar","Cement"],explanation:"Feedstock supply and port logistics strongly favour petrochemical development.",sourceFactId:"PETRO-CLUE"}
]),
q("GUJARAT-PETROCHEMICAL-REGION","Gujarat petrochemical region",[
{stem:"Which western state is a major petrochemical and refining region?",answer:"Gujarat",distractors:["Punjab","Assam","Kerala"],explanation:"Gujarat has major refineries, ports, chemical industries and petrochemical complexes.",sourceFactId:"PETRO-GUJARAT"},
{stem:"Which factor supports petrochemical growth in Gujarat?",answer:"Refineries, ports and hydrocarbon infrastructure",distractors:["Jute fields","Tea gardens","Iron-ore mines only"],explanation:"The state combines feedstock availability, ports, pipelines and industrial markets.",sourceFactId:"PETRO-GUJARAT-FACTOR"},
{stem:"Consider the statements: I. Gujarat has major refining capacity. II. Petrochemical industries benefit from refinery feedstocks. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both statements explain the state's strong petrochemical geography.",sourceFactId:"PETRO-GUJARAT-STATEMENT"},
{stem:"Which pair is correctly matched in petrochemical geography?",answer:"Gujarat — refinery-petrochemical region",distractors:["Gujarat — jute-only belt","Gujarat — no refineries","Gujarat — sugar-only region"],explanation:"Gujarat is one of India's major refining and petrochemical states.",sourceFactId:"PETRO-GUJARAT-MATCH"},
{stem:"Why do coastal locations help Gujarat's chemical industries?",answer:"Ports support bulk import and export of feedstocks and products",distractors:["Ports grow sugarcane","Ports create iron ore","Ports replace pipelines entirely"],explanation:"Bulk liquid and chemical cargo can move efficiently through ports.",sourceFactId:"PETRO-GUJARAT-PORT"},
{stem:"Which comparison is correct for Gujarat industry?",answer:"Petrochemicals benefit from refineries, while cement benefits from limestone",distractors:["Both depend only on jute","Neither uses transport","Cement depends on naphtha"],explanation:"The two industries have distinct raw-material and location logic.",sourceFactId:"PETRO-GUJARAT-COMPARE"}
]),
q("FERTILIZER-NATURAL-GAS-FEEDSTOCK","Fertilizer and natural-gas feedstock",[
{stem:"Which fuel is an important feedstock for nitrogenous fertilizer manufacture?",answer:"Natural gas",distractors:["Jute","Mica","Limestone only"],explanation:"Natural gas is widely used to produce hydrogen for ammonia, a key input in nitrogenous fertilizers.",sourceFactId:"FERT-GAS"},
{stem:"Which intermediate chemical is central to nitrogenous fertilizer production?",answer:"Ammonia",distractors:["Clinker","Pig iron","Alumina"],explanation:"Ammonia is a basic chemical used to manufacture urea and other nitrogen fertilizers.",sourceFactId:"FERT-AMMONIA"},
{stem:"Consider the statements: I. Natural gas is used as fertilizer feedstock. II. Ammonia is important to nitrogenous fertilizers. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are core parts of the nitrogen-fertilizer production chain.",sourceFactId:"FERT-GAS-STATEMENT"},
{stem:"Which chain correctly shows nitrogenous-fertilizer production?",answer:"Natural gas → ammonia → urea",distractors:["Iron ore → ammonia → urea","Jute → ammonia → steel","Limestone → urea → cement"],explanation:"Natural gas supplies hydrogen for ammonia, which is then used to produce urea.",sourceFactId:"FERT-CHAIN"},
{stem:"Which pair is correctly matched in fertilizer-industry logic?",answer:"Natural gas — ammonia feedstock",distractors:["Jute — ammonia feedstock","Bauxite — urea feedstock","Mica — fertilizer gas"],explanation:"Natural gas is a major feedstock for ammonia-based fertilizer production.",sourceFactId:"FERT-MATCH"},
{stem:"A fertilizer plant is located near a major gas pipeline. Which location factor is being used?",answer:"Feedstock access",distractors:["Jute cultivation","Iron-ore grade","Tidal power"],explanation:"Pipeline gas can provide a reliable raw-material and energy supply to fertilizer plants.",sourceFactId:"FERT-PIPELINE"}
]),
q("PHOSPHATIC-FERTILIZER-RAW-MATERIAL","Phosphatic fertilizer raw-material logic",[
{stem:"Which mineral is a key raw material for phosphatic fertilizers?",answer:"Rock phosphate",distractors:["Mica","Chromite","Bauxite"],explanation:"Rock phosphate is the principal mineral source of phosphorus for fertilizer production.",sourceFactId:"FERT-ROCK-PHOSPHATE"},
{stem:"Which industrial acid is commonly used in phosphatic-fertilizer manufacture?",answer:"Sulphuric acid",distractors:["Carbonic acid only","Acetic acid only","Hydrochloric acid only"],explanation:"Sulphuric acid is widely used to process phosphate rock into phosphatic fertilizers.",sourceFactId:"FERT-SULPHURIC"},
{stem:"Consider the statements: I. Rock phosphate supplies phosphorus. II. Sulphuric acid is important in phosphatic-fertilizer processing. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both inputs are central to phosphatic-fertilizer manufacture.",sourceFactId:"FERT-PHOS-STATEMENT"},
{stem:"Which pair is correctly matched in fertilizer raw materials?",answer:"Rock phosphate — phosphatic fertilizer",distractors:["Rock phosphate — jute fibre","Gypsum — nitrogen gas feedstock","Bauxite — urea"],explanation:"Rock phosphate is the key phosphorus-bearing mineral input.",sourceFactId:"FERT-PHOS-MATCH"},
{stem:"Why can phosphatic-fertilizer plants develop near ports?",answer:"Imported phosphate rock and sulphur can be handled in bulk",distractors:["Ports supply sugarcane","Ports create coal","Ports eliminate transport"],explanation:"Bulk imports can make coastal locations advantageous for phosphatic-fertilizer plants.",sourceFactId:"FERT-PHOS-PORT"},
{stem:"A fertilizer complex imports phosphate rock through a port. Which fertilizer family is indicated?",answer:"Phosphatic fertilizers",distractors:["Only nitrogenous fertilizers","Jute products","Cement"],explanation:"Phosphate rock directly points to phosphatic-fertilizer production.",sourceFactId:"FERT-PHOS-CLUE"}
]),
q("CHEMICAL-INDUSTRY-CLUSTER-LOGIC","Chemical-industry cluster logic",[
{stem:"Why do chemical industries often cluster together?",answer:"They can share feedstocks, utilities, pipelines and by-products",distractors:["They require no infrastructure","They depend only on farmland","They avoid transport links"],explanation:"Chemical complexes benefit from integrated material flows, shared utilities and logistics.",sourceFactId:"CHEM-CLUSTER"},
{stem:"Which factor strongly favours a large chemical complex?",answer:"Reliable power, water and transport",distractors:["Only high rainfall","Only fertile soil","Only tourism"],explanation:"Chemical manufacturing often needs substantial utilities and bulk logistics.",sourceFactId:"CHEM-UTILITIES"},
{stem:"Consider the statements: I. Chemical plants can exchange intermediate products. II. Shared infrastructure can lower costs. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Industrial integration is a major advantage of chemical clusters.",sourceFactId:"CHEM-STATEMENT"},
{stem:"Which pair is correctly matched in chemical-cluster logic?",answer:"Pipeline network — feedstock movement",distractors:["Pipeline network — jute cultivation","Cold storage — naphtha production","Limestone quarry — polymer feedstock"],explanation:"Pipelines are efficient for moving gases and liquids between chemical facilities.",sourceFactId:"CHEM-MATCH"},
{stem:"Why are ports useful to chemical and petrochemical industries?",answer:"They handle bulk liquid and imported feedstocks",distractors:["They supply iron ore automatically","They replace all pipelines","They produce fertilizers directly"],explanation:"Ports improve access to global feedstocks and export markets.",sourceFactId:"CHEM-PORT"},
{stem:"A coastal industrial zone has refineries, chemical plants and storage terminals. Which pattern is this?",answer:"Integrated chemical-petrochemical cluster",distractors:["Agricultural mandi","Jute-growing belt","Mining camp"],explanation:"The co-location of linked processing facilities is characteristic of an integrated chemical cluster.",sourceFactId:"CHEM-CLUE"}
]),
q("FERTILIZER-LOCATION-AND-MARKET-LOGIC","Fertilizer location and market logic",[
{stem:"Why do fertilizer plants value access to agricultural markets?",answer:"Fertilizers are bulky inputs used widely by farmers",distractors:["Fertilizers are mined as finished goods","They are used only by ports","They have no transport cost"],explanation:"Large farm markets create strong demand and influence distribution networks.",sourceFactId:"FERT-MARKET"},
{stem:"Which two factors often influence fertilizer-plant location together?",answer:"Feedstock supply and agricultural market access",distractors:["Iron ore and tourism","Jute and fisheries","Coal seam thickness and tea gardens"],explanation:"Plants need raw materials such as gas or phosphate and efficient access to farming regions.",sourceFactId:"FERT-TWO-FACTORS"},
{stem:"Consider the statements: I. Gas pipelines can influence fertilizer location. II. Agricultural demand can also influence distribution. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both source-side and market-side factors matter.",sourceFactId:"FERT-LOC-STATEMENT"},
{stem:"Which pair is correctly matched in fertilizer geography?",answer:"Gas pipeline — nitrogenous-fertilizer feedstock access",distractors:["Gas pipeline — jute raw material","Port — sugarcane source only","Rock phosphate — cotton fibre"],explanation:"Natural gas pipelines can supply ammonia and urea plants.",sourceFactId:"FERT-LOC-MATCH"},
{stem:"Which type of fertilizer plant may particularly benefit from port access?",answer:"Phosphatic-fertilizer plant using imported raw material",distractors:["Jute mill","Cotton gin","Sugar mill"],explanation:"Ports facilitate bulk import of phosphate rock, sulphur and related inputs.",sourceFactId:"FERT-PORT"},
{stem:"A plant lies near a gas pipeline and a major farming belt. Which industry is the strongest fit?",answer:"Nitrogenous fertilizer",distractors:["Jute textiles","Aluminium smelting","Cement"],explanation:"Gas feedstock plus agricultural demand strongly points to nitrogenous fertilizer production.",sourceFactId:"FERT-CLUE"}
]),
q("SINDRI-FERTILIZER-GEOGRAPHY","Sindri fertilizer geography",[
{stem:"Sindri is historically known for which industry?",answer:"Fertilizer industry",distractors:["Jute milling","Shipbuilding","Cotton spinning"],explanation:"Sindri in Jharkhand is one of India's historic fertilizer-industry locations.",sourceFactId:"FERT-SINDRI"},
{stem:"Sindri is located in which state?",answer:"Jharkhand",distractors:["Gujarat","Tamil Nadu","Punjab"],explanation:"Sindri lies in Jharkhand within the Damodar industrial region.",sourceFactId:"FERT-SINDRI-STATE"},
{stem:"Consider the statements: I. Sindri is in Jharkhand. II. It is historically linked with fertilizer manufacture. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both statements are durable industrial-location facts.",sourceFactId:"FERT-SINDRI-STATEMENT"},
{stem:"Which pair is correctly matched in fertilizer geography?",answer:"Sindri — Jharkhand",distractors:["Sindri — Kerala","Sindri — Rajasthan","Sindri — Tamil Nadu"],explanation:"Sindri is located in Jharkhand.",sourceFactId:"FERT-SINDRI-MATCH"},
{stem:"Which industrial region contains Sindri?",answer:"Damodar-Chotanagpur industrial belt",distractors:["Konkan coast only","Thar Desert","Kaveri delta only"],explanation:"Sindri lies within the mineral-industrial belt of eastern India.",sourceFactId:"FERT-SINDRI-REGION"},
{stem:"A map marks a historic fertilizer centre near Dhanbad in Jharkhand. Which place is it?",answer:"Sindri",distractors:["Tiruppur","Khetri","Sambhar"],explanation:"Sindri is near Dhanbad and is historically linked with fertilizer manufacture.",sourceFactId:"FERT-SINDRI-MAP"}
]),
q("NAMRUP-FERTILIZER-NATURAL-GAS","Namrup fertilizer and natural gas",[
{stem:"Namrup is an important fertilizer centre in which state?",answer:"Assam",distractors:["Gujarat","Odisha","Rajasthan"],explanation:"Namrup in Assam is a long-established fertilizer-industry location.",sourceFactId:"FERT-NAMRUP-STATE"},
{stem:"Which local resource strongly influenced fertilizer production at Namrup?",answer:"Natural gas",distractors:["Jute","Bauxite","Limestone"],explanation:"Assam's natural-gas resources provided feedstock for nitrogenous fertilizer production.",sourceFactId:"FERT-NAMRUP-GAS"},
{stem:"Consider the statements: I. Namrup is in Assam. II. Natural gas supports nitrogenous fertilizer production. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both facts explain Namrup's industrial location.",sourceFactId:"FERT-NAMRUP-STATEMENT"},
{stem:"Which pair is correctly matched in fertilizer geography?",answer:"Namrup — natural-gas-based fertilizer",distractors:["Namrup — jute only","Namrup — cement only","Namrup — aluminium smelting"],explanation:"Namrup is a classic gas-linked fertilizer centre.",sourceFactId:"FERT-NAMRUP-MATCH"},
{stem:"Why is Namrup a useful example of raw-material-oriented industry?",answer:"The plant used nearby natural gas as feedstock",distractors:["It depended on jute farms","Only ports mattered","It had no local resource link"],explanation:"Gas availability strongly influenced fertilizer location.",sourceFactId:"FERT-NAMRUP-REASON"},
{stem:"Which chain correctly represents Namrup's industrial logic?",answer:"Natural gas → ammonia/urea fertilizer",distractors:["Jute → ammonia → steel","Bauxite → fertilizer → aluminium","Coal → cotton → urea"],explanation:"Natural gas is used to produce ammonia and nitrogen fertilizers.",sourceFactId:"FERT-NAMRUP-CHAIN"}
]),
q("MUMBAI-THANE-CHEMICAL-REGION","Mumbai-Thane chemical region",[
{stem:"Which western metropolitan region has a major concentration of chemical industries?",answer:"Mumbai-Thane region",distractors:["Jharia-Bokaro","Koderma-Gaya","Sambhar-Khetri"],explanation:"Mumbai-Thane is an important chemical and petrochemical industrial region.",sourceFactId:"CHEM-MUMBAI-THANE"},
{stem:"Which factors support chemical industries around Mumbai-Thane?",answer:"Port access, refineries, market and transport",distractors:["Jute fields only","Iron ore only","Tea plantations"],explanation:"The metropolitan coastal setting provides feedstocks, logistics and a large market.",sourceFactId:"CHEM-MUMBAI-THANE-FACTORS"},
{stem:"Consider the statements: I. Mumbai has major port access. II. Refineries and chemical industries benefit from this location. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Port and refinery infrastructure reinforce chemical-industry location.",sourceFactId:"CHEM-MUMBAI-THANE-STATEMENT"},
{stem:"Which pair is correctly matched in chemical-industry geography?",answer:"Mumbai-Thane — chemicals and petrochemicals",distractors:["Mumbai-Thane — jute only","Mumbai-Thane — coalfield","Mumbai-Thane — sugar only"],explanation:"The region has a diversified chemical and petrochemical base.",sourceFactId:"CHEM-MUMBAI-THANE-MATCH"},
{stem:"Why do metropolitan chemical regions persist even without nearby mines?",answer:"They rely on ports, pipelines, markets and industrial networks",distractors:["Chemical plants need no inputs","Only ore matters","Transport is irrelevant"],explanation:"Modern chemical industries can be highly infrastructure- and market-oriented.",sourceFactId:"CHEM-MUMBAI-THANE-REASON"},
{stem:"Which comparison is correct for chemical regions?",answer:"Gujarat and Mumbai-Thane both benefit from western-coast refinery and port infrastructure",distractors:["Both are jute-only regions","Neither has ports","Both depend only on iron ore"],explanation:"Coastal hydrocarbon infrastructure supports both regions.",sourceFactId:"CHEM-WEST-COAST-COMPARE"}
]),
q("PHARMACEUTICAL-INDUSTRY-CLUSTERS","Pharmaceutical industry clusters",[
{stem:"Which Indian city is an important pharmaceutical-manufacturing centre?",answer:"Hyderabad",distractors:["Jharia","Sambhar","Panna"],explanation:"Hyderabad is one of India's major pharmaceutical and life-sciences manufacturing centres.",sourceFactId:"PHARMA-HYDERABAD"},
{stem:"Which western state also has a major pharmaceutical and chemical industry?",answer:"Gujarat",distractors:["Punjab","Assam","Meghalaya"],explanation:"Gujarat has a strong pharmaceutical and chemical-manufacturing base.",sourceFactId:"PHARMA-GUJARAT"},
{stem:"Which location factor is especially important to pharmaceutical manufacturing?",answer:"Skilled scientific labour and chemical-industry infrastructure",distractors:["Jute fields","Coal seams only","Sugarcane supply"],explanation:"Pharmaceutical manufacturing depends heavily on technical skills, laboratories and chemical inputs.",sourceFactId:"PHARMA-SKILLS"},
{stem:"Consider the statements: I. Hyderabad is a pharmaceutical centre. II. Skilled scientific labour supports pharmaceutical clusters. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both facts are important to modern pharmaceutical geography.",sourceFactId:"PHARMA-STATEMENT"},
{stem:"Which pair is correctly matched in pharmaceutical geography?",answer:"Hyderabad — pharmaceuticals",distractors:["Hyderabad — jute only","Hyderabad — coking coal","Hyderabad — sugar only"],explanation:"Hyderabad is a major pharmaceutical-manufacturing hub.",sourceFactId:"PHARMA-MATCH"},
{stem:"Why can pharmaceutical plants cluster near research institutions?",answer:"They benefit from scientific skills, research and specialised services",distractors:["They require iron ore","They depend only on farms","They avoid technical labour"],explanation:"Knowledge and specialised labour are major location factors for pharmaceutical industries.",sourceFactId:"PHARMA-CLUSTER"}
])
]);
export const GEO_IND_001_CP008_REVIEW_BATCH_V1=finalizeGeoIndCp(8,QLS);
export function auditGeoInd001Cp008ReviewBatchV1(){return auditGeoIndCp(8,QLS,GEO_IND_001_CP008_REVIEW_BATCH_V1);}
