import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["DPIIT-INDUSTRIAL-GEOGRAPHY-AND-POLICY","NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("PORT-LED-INDUSTRIAL-LOCATION","Port-led industrial location",[
{stem:"Why do some heavy industries locate near major ports?",answer:"Ports reduce the cost of importing raw materials and exporting products",distractors:["Ports supply iron ore automatically","Ports remove the need for markets","Ports eliminate transport"],explanation:"Bulk cargo such as crude oil, coal, ore, chemicals and steel can move efficiently by sea.",sourceFactId:"PORT-IND-LOGIC"},
{stem:"Which industry especially benefits from crude-oil import through ports?",answer:"Petroleum refining",distractors:["Jute cultivation","Sugarcane milling only","Handloom weaving only"],explanation:"Refineries process imported or domestic crude and often benefit from coastal tanker access.",sourceFactId:"PORT-REFINERY"},
{stem:"Consider the statements: I. Ports handle bulk cargo. II. Port access can attract refineries and petrochemical plants. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Bulk import/export capability can strongly influence coastal industrial location.",sourceFactId:"PORT-STATEMENT"},
{stem:"Which pair is correctly matched in port-led industry?",answer:"Major port — refinery and petrochemical advantage",distractors:["Major port — jute cultivation","Major port — iron-ore formation","Major port — sugarcane growth"],explanation:"Ports support bulk movement of liquid and solid industrial cargo.",sourceFactId:"PORT-MATCH"},
{stem:"Which coastal steel plant has an important port-location advantage?",answer:"Visakhapatnam",distractors:["Bokaro","Jamshedpur","Bhilai"],explanation:"Visakhapatnam is a coastal steel centre with direct port access.",sourceFactId:"PORT-VIZAG"},
{stem:"Which factor distinguishes a port-based plant from a classic mine-mouth plant?",answer:"Greater reliance on maritime transport rather than immediate raw-material proximity",distractors:["No transport is needed","Ports are mines","Mine-mouth plants depend on imports only"],explanation:"Port-based plants can source materials over long distances by sea.",sourceFactId:"PORT-COMPARE"}
]),
q("DELHI-MUMBAI-INDUSTRIAL-CORRIDOR","Delhi-Mumbai Industrial Corridor geography",[
{stem:"The Delhi-Mumbai Industrial Corridor links which two major metropolitan regions?",answer:"Delhi and Mumbai",distractors:["Kolkata and Chennai","Bengaluru and Kochi","Guwahati and Jaipur"],explanation:"The corridor is organised along the Delhi-Mumbai axis.",sourceFactId:"CORRIDOR-DMIC"},
{stem:"Which transport axis strongly underpins the Delhi-Mumbai industrial corridor?",answer:"Western Dedicated Freight Corridor axis",distractors:["Konkan Railway only","Kalka-Shimla line","Darjeeling Himalayan Railway"],explanation:"The western freight corridor provides a major logistics spine for the Delhi-Mumbai industrial corridor.",sourceFactId:"CORRIDOR-DMIC-DFC"},
{stem:"Consider the statements: I. The corridor connects major western and northern markets. II. Freight infrastructure is central to its industrial logic. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Market linkage and freight efficiency are core corridor advantages.",sourceFactId:"CORRIDOR-DMIC-STATEMENT"},
{stem:"Which pair is correctly matched in corridor geography?",answer:"Delhi-Mumbai corridor — western freight axis",distractors:["Delhi-Mumbai corridor — jute belt","Delhi-Mumbai corridor — tea belt","Delhi-Mumbai corridor — coalfield only"],explanation:"The corridor follows a major north-western freight and industrial axis.",sourceFactId:"CORRIDOR-DMIC-MATCH"},
{stem:"Why can industrial corridors attract manufacturing?",answer:"They combine freight connectivity, industrial nodes, markets and infrastructure",distractors:["They remove all transport","They depend only on mines","They exclude cities"],explanation:"Corridors reduce logistics friction and concentrate infrastructure and investment.",sourceFactId:"CORRIDOR-DMIC-REASON"},
{stem:"Which location factor is most directly improved by a dedicated freight corridor?",answer:"Transport and logistics efficiency",distractors:["Ore grade","Rainfall","Soil fertility"],explanation:"Dedicated freight lines improve movement of industrial inputs and finished goods.",sourceFactId:"CORRIDOR-DMIC-LOGISTICS"}
]),
q("CHENNAI-BENGALURU-INDUSTRIAL-CORRIDOR","Chennai-Bengaluru industrial corridor",[
{stem:"Which two metropolitan regions anchor the Chennai-Bengaluru industrial corridor?",answer:"Chennai and Bengaluru",distractors:["Delhi and Mumbai","Kolkata and Patna","Jaipur and Lucknow"],explanation:"The corridor links two major southern manufacturing and technology centres.",sourceFactId:"CORRIDOR-CBIC"},
{stem:"Which industries are strongly represented along the Chennai-Bengaluru axis?",answer:"Automobiles, engineering and electronics",distractors:["Jute only","Coal mining only","Sugar only"],explanation:"The corridor connects major manufacturing clusters in Tamil Nadu and Karnataka.",sourceFactId:"CORRIDOR-CBIC-IND"},
{stem:"Consider the statements: I. Chennai is a major automobile centre. II. Bengaluru is a major engineering and technology centre. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both anchors contribute complementary industrial strengths.",sourceFactId:"CORRIDOR-CBIC-STATEMENT"},
{stem:"Which pair is correctly matched in corridor geography?",answer:"Chennai-Bengaluru — southern manufacturing axis",distractors:["Chennai-Bengaluru — jute-only belt","Chennai-Bengaluru — coalfield only","Chennai-Bengaluru — tea belt"],explanation:"The axis is a major southern manufacturing corridor.",sourceFactId:"CORRIDOR-CBIC-MATCH"},
{stem:"Why is this corridor attractive to modern manufacturing?",answer:"It links skilled labour, ports, markets and supplier clusters",distractors:["It has no cities","It lacks transport","Only mineral proximity matters"],explanation:"The region combines complementary industrial and logistical advantages.",sourceFactId:"CORRIDOR-CBIC-REASON"},
{stem:"Which transport advantage does Chennai contribute to the corridor?",answer:"Major seaport access",distractors:["Iron-ore mine only","Coalfield only","Tidal farming"],explanation:"Chennai's port improves international and coastal logistics.",sourceFactId:"CORRIDOR-CBIC-PORT"}
]),
q("AMRITSAR-KOLKATA-INDUSTRIAL-CORRIDOR","Amritsar-Kolkata industrial corridor",[
{stem:"Which corridor follows a major northern and eastern freight-industrial axis?",answer:"Amritsar-Kolkata Industrial Corridor",distractors:["Chennai-Bengaluru corridor","Delhi-Mumbai corridor","Kochi-Coimbatore corridor"],explanation:"The Amritsar-Kolkata corridor is planned along a major northern-eastern industrial and freight axis.",sourceFactId:"CORRIDOR-AKIC"},
{stem:"Which broad region does the Amritsar-Kolkata corridor connect?",answer:"North-western India with the eastern industrial belt",distractors:["Only coastal Kerala","Only the Deccan interior","Only the Thar Desert"],explanation:"The corridor links major population, agricultural and industrial regions across the north and east.",sourceFactId:"CORRIDOR-AKIC-REGION"},
{stem:"Consider the statements: I. The corridor spans several major northern states. II. Freight connectivity is central to its purpose. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Industrial corridors depend heavily on integrated freight and node infrastructure.",sourceFactId:"CORRIDOR-AKIC-STATEMENT"},
{stem:"Which pair is correctly matched in corridor geography?",answer:"Amritsar-Kolkata — northern-eastern industrial axis",distractors:["Amritsar-Kolkata — southern coast only","Amritsar-Kolkata — jute-only corridor","Amritsar-Kolkata — no freight link"],explanation:"The corridor links northern and eastern industrial regions.",sourceFactId:"CORRIDOR-AKIC-MATCH"},
{stem:"Why can this corridor support agro-processing as well as manufacturing?",answer:"It passes through large agricultural and urban markets",distractors:["It has no farmland","Only mines matter","Markets are absent"],explanation:"The corridor crosses productive agricultural regions and major population centres.",sourceFactId:"CORRIDOR-AKIC-AGRO"},
{stem:"Which location factor is strengthened by industrial corridors in general?",answer:"Inter-regional connectivity",distractors:["Mineral chemistry","Crop genetics","Rainfall formation"],explanation:"Corridors primarily improve movement between production centres, suppliers and markets.",sourceFactId:"CORRIDOR-AKIC-CONNECTIVITY"}
]),
q("PORT-INDUSTRIAL-CLUSTERS-WEST-COAST","West-coast port-industrial clusters",[
{stem:"Which coast contains major port-industrial centres such as Mumbai and Kandla-Deendayal?",answer:"Western coast",distractors:["Eastern Himalaya","Upper Ganga plain","Central plateau only"],explanation:"The western coast hosts several major ports serving industrial and petrochemical regions.",sourceFactId:"PORT-WEST"},
{stem:"Which industry is strongly linked with port-based crude-oil handling on the west coast?",answer:"Petroleum refining",distractors:["Jute farming","Tea cultivation","Coal mining only"],explanation:"Crude-oil imports and product exports make ports important to refineries.",sourceFactId:"PORT-WEST-REFINING"},
{stem:"Consider the statements: I. Gujarat has major ports. II. Gujarat also has major petrochemical industries. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Port access and petrochemical development reinforce each other.",sourceFactId:"PORT-GUJARAT-STATEMENT"},
{stem:"Which pair is correctly matched in west-coast industrial geography?",answer:"Gujarat ports — petrochemical logistics",distractors:["Gujarat ports — jute cultivation","Mumbai port — coal mine","Kandla — sugarcane source"],explanation:"Ports support bulk hydrocarbon and chemical cargo flows.",sourceFactId:"PORT-WEST-MATCH"},
{stem:"Why can west-coast ports attract export-oriented manufacturing?",answer:"They provide direct access to international shipping routes",distractors:["They eliminate labour needs","They create raw materials","They replace markets"],explanation:"Port proximity lowers maritime logistics cost for export and import flows.",sourceFactId:"PORT-WEST-EXPORT"},
{stem:"Which comparison is correct for industrial location?",answer:"Port-based industries stress maritime logistics, while mine-mouth industries stress source proximity",distractors:["Both ignore transport","Ports are mines","Mine-mouth plants depend only on imports"],explanation:"The two location types respond to different transport and input conditions.",sourceFactId:"PORT-WEST-COMPARE"}
]),
q("PORT-INDUSTRIAL-CLUSTERS-EAST-COAST","East-coast port-industrial clusters",[
{stem:"Which east-coast city combines a major port with steel and petroleum-related industry?",answer:"Visakhapatnam",distractors:["Jharia","Koderma","Sambhar"],explanation:"Visakhapatnam is a major port-industrial centre with steel, refining and other industries.",sourceFactId:"PORT-EAST-VIZAG"},
{stem:"Which factor supports heavy industry at Visakhapatnam?",answer:"Port access for bulk cargo",distractors:["Jute cultivation only","Tea gardens","No transport"],explanation:"The port enables efficient movement of raw materials and finished products.",sourceFactId:"PORT-EAST-FACTOR"},
{stem:"Consider the statements: I. Visakhapatnam is on the east coast. II. It has a major steel plant. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both statements are central to its port-industrial geography.",sourceFactId:"PORT-EAST-STATEMENT"},
{stem:"Which pair is correctly matched in east-coast port industry?",answer:"Visakhapatnam — steel and port",distractors:["Visakhapatnam — jute-only belt","Visakhapatnam — inland coalfield","Visakhapatnam — sugar-only region"],explanation:"Visakhapatnam is a port city with major steel and industrial activity.",sourceFactId:"PORT-EAST-MATCH"},
{stem:"Why can east-coast ports support mineral-based industry?",answer:"They can handle ore, coal and other bulk cargo efficiently",distractors:["They grow minerals","They eliminate freight","They depend only on tourism"],explanation:"Ports reduce the cost of moving bulky industrial inputs.",sourceFactId:"PORT-EAST-BULK"},
{stem:"Which comparison is correct for steel-plant location?",answer:"Visakhapatnam is port-oriented, while Jamshedpur is mineral-belt oriented",distractors:["Both are offshore","Jamshedpur is a port city","Visakhapatnam is in Jharkhand"],explanation:"The two plants illustrate different location strategies.",sourceFactId:"PORT-EAST-COMPARE"}
])
]);
export const GEO_IND_001_CP010_REVIEW_BATCH_V1=finalizeGeoIndCp(10,QLS);
export function auditGeoInd001Cp010ReviewBatchV1(){return auditGeoIndCp(10,QLS,GEO_IND_001_CP010_REVIEW_BATCH_V1);}
