import { buildGeoIndQl, finalizeGeoIndCp, auditGeoIndCp } from "./geo-ind-001-review-builder";
const SRC=["NCERT-CLASS10-CONTEMPORARY-INDIA-II-MANUFACTURING-INDUSTRIES","NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-MANUFACTURING-INDUSTRIES","MINISTRY-OF-FOOD-PROCESSING-INDUSTRIES-INDIA"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoIndQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("SUGAR-INDUSTRY-RAW-MATERIAL-AND-LOCATION","Sugar industry raw material and location",[
{stem:"Which crop is the principal raw material for India's sugar industry?",answer:"Sugarcane",distractors:["Cotton","Jute","Tea"],explanation:"Sugarcane is processed into sugar, making the sugar industry agro-based.",sourceFactId:"SUGAR-RAW"},
{stem:"Why are sugar mills usually located near sugarcane-growing areas?",answer:"Sugarcane is bulky and loses sucrose after harvesting",distractors:["Sugarcane is a mineral","Mills require iron ore only","Sugarcane cannot be transported at all"],explanation:"Quick crushing after harvest helps reduce sucrose loss, while proximity also lowers transport of a bulky crop.",sourceFactId:"SUGAR-PERISHABLE"},
{stem:"Consider the statements: I. Sugar is an agro-based industry. II. Cane perishability influences mill location. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The industry depends on an agricultural crop and is strongly source-oriented because cane quality declines after harvest.",sourceFactId:"SUGAR-STATEMENT"},
{stem:"Which factor most directly explains the location of a sugar mill inside a cane-growing belt?",answer:"Raw-material proximity",distractors:["Iron-ore access","Port access only","Tidal range"],explanation:"Sugarcane supply is the dominant raw-material factor for mill location.",sourceFactId:"SUGAR-LOCATION"},
{stem:"Which pair is correctly matched in sugar-industry geography?",answer:"Sugar mill — sugarcane belt",distractors:["Sugar mill — iron-ore belt","Sugar mill — uranium belt","Sugar mill — petroleum field"],explanation:"Sugar mills depend directly on nearby sugarcane-growing regions.",sourceFactId:"SUGAR-MATCH"},
{stem:"A factory crushes freshly harvested cane and produces crystalline sugar. Which industry is this?",answer:"Sugar industry",distractors:["Jute industry","Steel industry","Cement industry"],explanation:"Crushing cane and refining juice into sugar are the basic processes of the sugar industry.",sourceFactId:"SUGAR-CLUE"}
]),
q("UTTAR-PRADESH-SUGAR-BELT","Uttar Pradesh sugar belt",[
{stem:"Which northern state is a major sugarcane and sugar-producing region?",answer:"Uttar Pradesh",distractors:["Rajasthan","Assam","Odisha"],explanation:"Uttar Pradesh has a large sugarcane-growing belt and many sugar mills.",sourceFactId:"SUGAR-UP"},
{stem:"Which region of Uttar Pradesh is strongly linked with sugarcane cultivation and sugar mills?",answer:"Western Uttar Pradesh",distractors:["Thar Desert","Chotanagpur Plateau","Konkan coast"],explanation:"Western Uttar Pradesh has dense sugarcane cultivation and a long-established sugar-mill network.",sourceFactId:"SUGAR-WEST-UP"},
{stem:"Consider the statements: I. Uttar Pradesh has a major sugar industry. II. The industry is linked with nearby cane-growing areas. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The state's large cane belt supports a dense network of sugar mills.",sourceFactId:"SUGAR-UP-STATEMENT"},
{stem:"Which pair is correctly matched in sugar geography?",answer:"Western Uttar Pradesh — sugarcane and sugar mills",distractors:["Western Uttar Pradesh — jute only","Western Uttar Pradesh — petroleum only","Western Uttar Pradesh — iron ore only"],explanation:"Western Uttar Pradesh is one of India's classic sugarcane-sugar regions.",sourceFactId:"SUGAR-UP-MATCH"},
{stem:"Why is the sugar industry widespread across western Uttar Pradesh?",answer:"Large cane supplies, irrigation, labour and market access are available",distractors:["The region has major bauxite mines","It depends only on ports","It has no agriculture"],explanation:"The region combines cane cultivation with transport, labour and market conditions favourable to milling.",sourceFactId:"SUGAR-UP-REASON"},
{stem:"A map marks a dense sugar-mill belt in the upper Ganga plain. Which state is the best answer?",answer:"Uttar Pradesh",distractors:["Kerala","Goa","Assam"],explanation:"The upper Ganga plain, especially western Uttar Pradesh, is a major sugarcane and sugar-mill belt.",sourceFactId:"SUGAR-UP-MAP"}
]),
q("MAHARASHTRA-SUGAR-COOPERATIVES","Maharashtra sugar and cooperative geography",[
{stem:"Which western state is especially known for cooperative sugar mills?",answer:"Maharashtra",distractors:["Punjab","Assam","Jharkhand"],explanation:"Maharashtra has a strong tradition of cooperative sugar factories linked with cane-growing regions.",sourceFactId:"SUGAR-MH-COOP"},
{stem:"Why did cooperative sugar mills become important in Maharashtra?",answer:"Cane growers could collectively own and support processing units",distractors:["Sugarcane is a mineral","Only government can own mills","Cooperatives require no farmers"],explanation:"Cooperative ownership allowed producers to organise processing and share in the enterprise.",sourceFactId:"SUGAR-COOP-LOGIC"},
{stem:"Consider the statements: I. Maharashtra is a major sugar state. II. Cooperative ownership has been important in its sugar industry. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both the state's large cane-processing sector and cooperative tradition are standard industrial-geography facts.",sourceFactId:"SUGAR-MH-STATEMENT"},
{stem:"Which pair is correctly matched in sugar-industry ownership geography?",answer:"Maharashtra — cooperative sugar mills",distractors:["Maharashtra — jute mills only","Maharashtra — no sugar industry","Maharashtra — uranium-based sugar"],explanation:"Maharashtra is strongly linked with cooperative sugar production.",sourceFactId:"SUGAR-MH-MATCH"},
{stem:"Which ownership model is illustrated when cane growers jointly own a sugar mill?",answer:"Cooperative sector",distractors:["Public sector only","Private sector only","Joint sector only"],explanation:"A producer-owned mill organised through a cooperative society belongs to the cooperative sector.",sourceFactId:"SUGAR-COOP-OWNERSHIP"},
{stem:"Which comparison is correct for Indian sugar geography?",answer:"Uttar Pradesh has a major northern belt, while Maharashtra has a major western cooperative belt",distractors:["Both are jute-only regions","Maharashtra has no cane cultivation","Uttar Pradesh has no sugar mills"],explanation:"The two states represent major but regionally distinct sugar-industry concentrations.",sourceFactId:"SUGAR-UP-MH"}
]),
q("FOOD-PROCESSING-RAW-MATERIAL-LOGIC","Food-processing raw-material logic",[
{stem:"Why do many food-processing industries locate near agricultural areas?",answer:"Fresh and bulky raw materials can be processed quickly near the source",distractors:["They require iron ore","They use no agricultural inputs","Only ports matter"],explanation:"Perishability, bulk and seasonal supply can make proximity to farms an important locational factor.",sourceFactId:"FOOD-RAW-LOGIC"},
{stem:"Which industry is most likely to locate near a major fruit-growing region?",answer:"Fruit processing",distractors:["Steel making","Aluminium smelting","Cement production"],explanation:"Fruit-processing plants benefit from proximity to fresh raw material to reduce spoilage and transport cost.",sourceFactId:"FOOD-FRUIT"},
{stem:"Consider the statements: I. Perishability can affect food-industry location. II. Cold storage can extend the usable life of raw materials. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Perishability favours quick processing, while cold-chain infrastructure can reduce losses and widen sourcing areas.",sourceFactId:"FOOD-COLD-CHAIN"},
{stem:"Which factor is especially important for milk-processing plants?",answer:"Reliable collection and cold-chain links",distractors:["Iron-ore grade","Coal seam thickness","Tidal range"],explanation:"Milk is highly perishable, so fast collection, chilling and transport are central to dairy processing.",sourceFactId:"FOOD-DAIRY"},
{stem:"Which pair is correctly matched in food-processing location?",answer:"Dairy plant — milk-producing region",distractors:["Dairy plant — iron-ore belt","Fruit cannery — coalfield only","Sugar mill — petroleum basin"],explanation:"Food-processing plants commonly reflect the geography of their agricultural raw materials.",sourceFactId:"FOOD-MATCH"},
{stem:"A plant is built close to vegetable farms because the produce spoils quickly. Which factor is dominant?",answer:"Perishable raw material",distractors:["Mineral reserve","Hydropower head","Tidal energy"],explanation:"Fast spoilage creates a strong incentive to locate processing close to the producing area.",sourceFactId:"FOOD-PERISHABLE"}
]),
q("DAIRY-PROCESSING-AND-COOPERATIVE-LOGIC","Dairy processing and cooperative logic",[
{stem:"Which industry converts milk into products such as butter, cheese and milk powder?",answer:"Dairy-processing industry",distractors:["Jute industry","Steel industry","Cement industry"],explanation:"Dairy plants process raw milk into a range of consumer products.",sourceFactId:"FOOD-DAIRY-INDUSTRY"},
{stem:"Why can dairy cooperatives help rural producers?",answer:"They organise milk collection, processing and marketing collectively",distractors:["They eliminate milk production","They depend on iron ore","They replace cold storage with mining"],explanation:"Cooperatives can link many small producers with chilling, processing and marketing systems.",sourceFactId:"FOOD-DAIRY-COOP"},
{stem:"Consider the statements: I. Milk is perishable. II. Chilling infrastructure is important to dairy processing. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Milk quality declines quickly without cooling, so collection and chilling are essential.",sourceFactId:"FOOD-DAIRY-STATEMENT"},
{stem:"Which factor most directly explains dairy plants near dense milk-producing regions?",answer:"Raw-material supply",distractors:["Iron ore","Bauxite","Chromite"],explanation:"Regular milk supply from surrounding producers is the key source-side requirement.",sourceFactId:"FOOD-DAIRY-RAW"},
{stem:"Which ownership model is often important in organised milk processing in India?",answer:"Cooperative model",distractors:["Mining lease only","Port authority only","Nuclear corporation only"],explanation:"Milk cooperatives are a major organisational form linking producers to processing and marketing.",sourceFactId:"FOOD-DAIRY-OWNERSHIP"},
{stem:"Which chain correctly shows dairy value addition?",answer:"Milk → processing → packaged dairy products",distractors:["Iron ore → milk → cheese","Jute → milk powder → steel","Coal → butter → cement"],explanation:"Processing converts raw milk into higher-value products such as butter, cheese and milk powder.",sourceFactId:"FOOD-DAIRY-CHAIN"}
]),
q("FOOD-PROCESSING-MARKET-TRANSPORT-COLD-CHAIN","Food-processing market, transport and cold-chain factors",[
{stem:"Why is refrigerated transport important to food processing?",answer:"It reduces spoilage of perishable products during movement",distractors:["It raises ore grade","It creates coal","It replaces markets"],explanation:"Cold transport helps maintain quality from farm to plant and from plant to market.",sourceFactId:"FOOD-REFRIGERATED"},
{stem:"Which factor allows perishable food industries to serve distant urban markets?",answer:"Cold-chain logistics",distractors:["Iron-ore mines","Tidal barrages","Coal washing"],explanation:"Cold stores and refrigerated transport extend shelf life and enable longer-distance distribution.",sourceFactId:"FOOD-DISTANT-MARKET"},
{stem:"Consider the statements: I. Urban markets can attract packaged-food industries. II. Efficient transport widens the market area. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Demand concentration and transport networks both influence food-processing location.",sourceFactId:"FOOD-MARKET-STATEMENT"},
{stem:"Which location is favoured for a packaged-food plant serving a large city?",answer:"A site with strong transport and market access",distractors:["A remote ore mine only","A tidal creek without roads","A site chosen only for rainfall"],explanation:"Consumer demand and logistics can be decisive for packaged foods.",sourceFactId:"FOOD-PACKAGED"},
{stem:"Which pair is correctly matched in food logistics?",answer:"Cold storage — reduction of post-harvest spoilage",distractors:["Cold storage — steel smelting","Cold storage — cement clinker","Cold storage — uranium enrichment"],explanation:"Cold storage preserves temperature-sensitive agricultural and food products.",sourceFactId:"FOOD-COLD-MATCH"},
{stem:"A processing plant sources vegetables from farms and sells packaged products in a nearby city. Which two location factors are most evident?",answer:"Raw material and market",distractors:["Ore and tidal power","Coal and uranium","Mineral grade and river head"],explanation:"The plant depends on farm inputs and consumer demand, illustrating source and market orientation together.",sourceFactId:"FOOD-TWO-FACTORS"}
]),
q("TROPICAL-SUBTROPICAL-SUGAR-BELTS","Tropical and subtropical sugar belts",[
{stem:"Which state is part of India's tropical sugarcane belt?",answer:"Maharashtra",distractors:["Punjab","Haryana","Uttarakhand"],explanation:"Maharashtra lies in the tropical peninsular sugarcane belt.",sourceFactId:"SUGAR-TROPICAL-MH"},
{stem:"Which state is a major part of India's subtropical sugarcane belt?",answer:"Uttar Pradesh",distractors:["Kerala","Goa","Tamil Nadu"],explanation:"Uttar Pradesh lies in the subtropical northern sugarcane belt.",sourceFactId:"SUGAR-SUBTROPICAL-UP"},
{stem:"Why can peninsular sugar regions have a longer crushing season?",answer:"Warmer tropical conditions extend the cane-growing and crushing period",distractors:["Sugarcane cannot grow there","Only ports matter","There is no winter anywhere in India"],explanation:"Warmer peninsular conditions generally allow a longer crushing season than the cooler north.",sourceFactId:"SUGAR-LONGER-SEASON"},
{stem:"Consider the statements: I. Maharashtra represents tropical sugar geography. II. Uttar Pradesh represents subtropical sugar geography. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two states represent India's major tropical and subtropical sugar patterns.",sourceFactId:"SUGAR-BELT-STATEMENT"},
{stem:"Which comparison is correct for sugar-industry geography?",answer:"Maharashtra generally has a longer crushing season than Uttar Pradesh",distractors:["Uttar Pradesh is tropical","Both have identical climate","Sugarcane grows only in northern India"],explanation:"The warmer peninsular climate generally supports a longer crushing season.",sourceFactId:"SUGAR-SEASON-COMPARE"},
{stem:"Which factor helped sugar-industry growth shift toward parts of peninsular India?",answer:"Longer crushing season and favourable tropical conditions",distractors:["Absence of sugarcane","Lack of labour","No irrigation anywhere"],explanation:"Climatic and organisational advantages improved the competitiveness of peninsular sugar regions.",sourceFactId:"SUGAR-SOUTHWARD"}
]),
q("SUGAR-BYPRODUCTS","Sugar-industry by-products",[
{stem:"Which sugar-industry by-product can be used for cogeneration of electricity?",answer:"Bagasse",distractors:["Iron slag","Bauxite residue","Mica"],explanation:"Bagasse is the fibrous residue after cane crushing and can be burned to generate steam and power.",sourceFactId:"SUGAR-BAGASSE"},
{stem:"Which sugar-industry by-product is used in distilleries?",answer:"Molasses",distractors:["Limestone","Jute fibre","Iron ore"],explanation:"Molasses is used to produce alcohol and ethanol.",sourceFactId:"SUGAR-MOLASSES"},
{stem:"Consider the statements: I. Bagasse can generate energy. II. Molasses can be used for alcohol production. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both by-products support additional industrial activities.",sourceFactId:"SUGAR-BYPRODUCT-STATEMENT"},
{stem:"Which chain correctly shows integrated sugar-industry use?",answer:"Sugarcane → sugar + bagasse + molasses",distractors:["Sugarcane → iron + steel","Sugarcane → bauxite + aluminium","Sugarcane → jute + mica"],explanation:"Sugar processing produces sugar along with useful by-products such as bagasse and molasses.",sourceFactId:"SUGAR-BYPRODUCT-CHAIN"},
{stem:"Which pair is correctly matched in sugar by-products?",answer:"Bagasse — cogeneration",distractors:["Bagasse — iron smelting","Molasses — cement clinker","Molasses — jute fibre"],explanation:"Bagasse is widely used as boiler fuel for steam and electricity generation.",sourceFactId:"SUGAR-BAGASSE-MATCH"},
{stem:"Why can a modern sugar complex produce more than sugar alone?",answer:"By-products can support power and distillery operations",distractors:["Sugar mills mine iron ore","Cane produces bauxite","Sugar refining creates coal seams"],explanation:"Integrated use of bagasse and molasses allows cogeneration and distillery production.",sourceFactId:"SUGAR-INTEGRATION"}
])
]);
export const GEO_IND_001_CP004_REVIEW_BATCH_V1=finalizeGeoIndCp(4,QLS);
export function auditGeoInd001Cp004ReviewBatchV1(){return auditGeoIndCp(4,QLS,GEO_IND_001_CP004_REVIEW_BATCH_V1);}
