import type {
  IntCp001PrototypeId,
  IntCp001PrototypeRegistryEntry,
} from "./types";

export const INT_CP001_PROTOTYPE_REGISTRY: readonly IntCp001PrototypeRegistryEntry[] = [
  {
    prototypeId: "INT-CP001-PROT-SI-FROM-PRT",
    cpId: "INT-CP-001",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLE_INTEREST",
    topology: "DIRECT_INTEREST",
    timePresentation: "YEARS",
    baseDifficulty: "Easy",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-AMOUNT-FROM-PRT",
    cpId: "INT-CP-001",
    taskDirection: "FORWARD",
    answerSemantic: "TOTAL_AMOUNT",
    topology: "DIRECT_AMOUNT",
    timePresentation: "YEARS",
    baseDifficulty: "Easy",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-PRINCIPAL-FROM-INTEREST",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "PRINCIPAL",
    topology: "PRINCIPAL_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-PRINCIPAL-FROM-AMOUNT",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "PRINCIPAL",
    topology: "PRINCIPAL_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-RATE-FROM-INTEREST",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "ANNUAL_RATE_PERCENT",
    topology: "RATE_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-RATE-FROM-AMOUNT",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "ANNUAL_RATE_PERCENT",
    topology: "RATE_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-TIME-FROM-INTEREST",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "TIME_YEARS",
    topology: "TIME_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-TIME-FROM-AMOUNT",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "TIME_YEARS",
    topology: "TIME_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-INTEREST-FOR-MONTHS",
    cpId: "INT-CP-001",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLE_INTEREST",
    topology: "TIME_UNIT_CONVERSION",
    timePresentation: "MONTHS",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-INTEREST-FOR-DAYS",
    cpId: "INT-CP-001",
    taskDirection: "FORWARD",
    answerSemantic: "SIMPLE_INTEREST",
    topology: "TIME_UNIT_CONVERSION",
    timePresentation: "DAYS",
    baseDifficulty: "Hard",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-ANNUAL-INTEREST-FROM-TOTAL",
    cpId: "INT-CP-001",
    taskDirection: "RECONSTRUCTION",
    answerSemantic: "ANNUAL_INTEREST",
    topology: "ANNUALISATION",
    timePresentation: "YEARS",
    baseDifficulty: "Easy",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-INTEREST-FOR-SUBDURATION",
    cpId: "INT-CP-001",
    taskDirection: "RECONSTRUCTION",
    answerSemantic: "SIMPLE_INTEREST",
    topology: "SUBDURATION_PROPORTION",
    timePresentation: "MIXED",
    baseDifficulty: "Medium",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-RATE-FROM-AMOUNT-MULTIPLE",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "ANNUAL_RATE_PERCENT",
    topology: "AMOUNT_MULTIPLE_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Hard",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-TIME-FROM-AMOUNT-MULTIPLE",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "TIME_YEARS",
    topology: "AMOUNT_MULTIPLE_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Hard",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-TIME-FROM-INTEREST-MULTIPLE",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "TIME_YEARS",
    topology: "INTEREST_RATIO_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Hard",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
  {
    prototypeId: "INT-CP001-PROT-RATE-FROM-INTEREST-PRINCIPAL-RATIO",
    cpId: "INT-CP-001",
    taskDirection: "INVERSE",
    answerSemantic: "ANNUAL_RATE_PERCENT",
    topology: "INTEREST_RATIO_INVERSE",
    timePresentation: "YEARS",
    baseDifficulty: "Hard",
    permanentQlId: null,
    publiclyPublishable: false,
    questionStudioDiscoverable: false,
  },
] as const;

const registryById = new Map<IntCp001PrototypeId, IntCp001PrototypeRegistryEntry>(
  INT_CP001_PROTOTYPE_REGISTRY.map((entry) => [entry.prototypeId, entry]),
);

export function getIntCp001PrototypeEntry(
  prototypeId: IntCp001PrototypeId,
): IntCp001PrototypeRegistryEntry {
  const entry = registryById.get(prototypeId);
  if (!entry) throw new Error(`Unknown INT-CP-001 prototype ID: ${prototypeId}.`);
  return entry;
}
