export type HisCp016Fact=readonly[id:string,explanation:string,sourceIds:readonly string[]];

export const HIS_CP016_SOURCES_V1=Object.freeze([
  {id:"NIOS-HIS-315-L21",label:"NIOS History 315 Lesson 21 — Indian National Movement",url:"https://digital.nios.ac.in/content/315en/315_History_Eng_Lesson21.pdf"},
  {id:"NIOS-SS-213-L08",label:"NIOS Social Science 213 Lesson 8 — Indian National Movement",url:"https://digital.nios.ac.in/content/213en/Lesson-08.pdf"},
  {id:"GOI-CULTURE-RIN-1946",label:"Ministry of Culture — Royal Indian Navy uprising of 1946",url:"https://cmsadmin.amritmahotsav.nic.in/district-reopsitory-detail.htm?25150="},
] as const);
export const HIS_CP016_SOURCE_IDS_V1=new Set(HIS_CP016_SOURCES_V1.map(s=>s.id));

export const HIS_CP016_FACTS_V1:readonly HisCp016Fact[]=[
  ["rowlatt-powers","The Rowlatt law allowed detention and punishment without ordinary trial safeguards.",["NIOS-HIS-315-L21"]],
  ["rowlatt-hartal","The nationwide hartal against the Rowlatt law was observed on 6 April 1919.",["NIOS-HIS-315-L21"]],
  ["jallianwala-date","The Jallianwala Bagh firing took place at Amritsar on 13 April 1919.",["NIOS-HIS-315-L21"]],
  ["jallianwala-dyer","General Dyer ordered troops to fire on the unarmed gathering without prior warning.",["NIOS-HIS-315-L21"]],
  ["punjab-repression","The Jallianwala Bagh firing was followed by martial law and harsh repression in Punjab.",["NIOS-HIS-315-L21"]],
  ["rowlatt-nationwide","The Rowlatt Satyagraha was Gandhi's first nationwide protest in India.",["NIOS-HIS-315-L21"]],
  ["ncm-three-issues","Non-Cooperation was linked with the Khilafat issue, the Punjab wrong and the demand for Swaraj.",["NIOS-HIS-315-L21"]],
  ["ncm-calcutta","The Congress adopted a Non-Cooperation programme at its Calcutta special session in September 1920.",["NIOS-HIS-315-L21"]],
  ["ncm-programme","The Non-Cooperation programme included surrender of titles and boycott of schools, courts, councils and foreign goods.",["NIOS-HIS-315-L21"]],
  ["ncm-khadi","Khadi and the charkha became important symbols of the Non-Cooperation movement.",["NIOS-HIS-315-L21"]],
  ["chauri-chaura","A Congress-Khilafat procession at Chauri Chaura turned violent on 5 February 1922.",["NIOS-HIS-315-L21"]],
  ["ncm-withdrawal","Gandhi withdrew the Non-Cooperation movement on 12 February 1922 after the Chauri Chaura violence.",["NIOS-HIS-315-L21"]],
  ["swaraj-party-1923","C.R. Das and Motilal Nehru formed the Swaraj Party in 1923.",["NIOS-HIS-315-L21"]],
  ["swaraj-party-roles","C.R. Das became president and Motilal Nehru secretary of the Swaraj Party.",["NIOS-SS-213-L08"]],
  ["swaraj-councils","The Swarajists entered legislative councils to oppose colonial policies from within.",["NIOS-HIS-315-L21"]],
  ["simon-no-indian","The Simon Commission had no Indian member.",["NIOS-SS-213-L08"]],
  ["simon-boycott","The Simon Commission faced nationwide boycott and black-flag protests when it arrived in India in 1928.",["NIOS-HIS-315-L21"]],
  ["lajpat-rai","Lala Lajpat Rai was severely injured in a police lathi charge during protests against the Simon Commission and later died.",["NIOS-SS-213-L08"]],
  ["nehru-report","The Nehru Report proposed measures including a declaration of rights, parliamentary government and an independent judiciary.",["NIOS-SS-213-L08"]],
  ["lahore-purna","At its Lahore session in 1929, the Congress adopted Purna Swaraj, or complete independence, as its goal.",["NIOS-SS-213-L08"]],
  ["independence-day-1930","The Congress observed 26 January 1930 as Independence Day after the Purna Swaraj declaration.",["NIOS-SS-213-L08"]],
  ["dandi-march","Gandhi marched from Sabarmati Ashram to Dandi in March-April 1930 to challenge the salt law.",["NIOS-SS-213-L08"]],
  ["salt-law-break","Gandhi broke the salt law at Dandi on 6 April 1930.",["NIOS-SS-213-L08"]],
  ["cdm-participation","Farmers, traders, students and women participated widely in the Civil Disobedience movement.",["NIOS-SS-213-L08"]],
  ["gandhi-irwin","The Gandhi-Irwin Pact was signed in March 1931; Congress agreed to suspend Civil Disobedience and join the next Round Table Conference.",["NIOS-HIS-315-L21"]],
  ["second-rtc","Gandhi attended the Second Round Table Conference in London in 1931 as the Congress representative.",["NIOS-SS-213-L08"]],
  ["karachi-rights","The Karachi Congress of 1931 adopted resolutions on Fundamental Rights and a National Economic Programme.",["NIOS-HIS-315-L21"]],
  ["cdm-resumed","The Congress resumed Civil Disobedience after the Second Round Table Conference failed to produce a settlement.",["NIOS-HIS-315-L21"]],
  ["chittagong","Surya Sen led the Chittagong Armoury Raid, in which revolutionaries seized the local armoury and proclaimed an Indian Republican Army.",["NIOS-HIS-315-L21"]],
  ["hsra-assembly","Bhagat Singh and Batukeshwar Dutt threw bombs in the Central Legislative Assembly on 8 April 1929 to protest repressive bills; no one was killed in the incident.",["NIOS-SS-213-L08"]],
  ["goi-act-1935","The Government of India Act was passed in 1935.",["NIOS-SS-213-L08"]],
  ["goi-federation","The Government of India Act 1935 proposed an All-India Federation of British Indian provinces and princely states.",["NIOS-SS-213-L08"]],
  ["goi-franchise","Under the 1935 Act, voting rights remained limited; only about 14 percent of the population in British India could vote.",["NIOS-SS-213-L08"]],
  ["congress-ministries","After the 1937 elections, Congress ministries were formed in seven of the eleven provinces.",["NIOS-SS-213-L08"]],
  ["ministries-resign","Congress ministries resigned in 1939 after Britain involved India in the Second World War without accepting Congress demands on India's political status.",["NIOS-SS-213-L08"]],
  ["individual-satyagraha","Vinoba Bhave was the first individual satyagrahi in the campaign launched in 1940.",["NIOS-SS-213-L08"]],
  ["cripps-1942","Sir Stafford Cripps came to India in March 1942 with British constitutional proposals.",["NIOS-SS-213-L08"]],
  ["cripps-dominion","The Cripps proposals offered Dominion Status after the war rather than immediate complete independence.",["NIOS-SS-213-L08"]],
  ["cripps-rejected","Both the Congress and the Muslim League rejected the Cripps proposals, though for different reasons.",["NIOS-SS-213-L08"]],
  ["ina-formation","In 1942 the Indian Independence League moved to organize the Indian National Army for India's liberation.",["NIOS-SS-213-L08"]],
  ["bose-east-asia","Subhas Chandra Bose reached East Asia in 1943 and became leader of the Indian Independence League and the INA.",["NIOS-SS-213-L08"]],
  ["ina-chalo-dilli","Under Subhas Chandra Bose, the INA became popularly known as Azad Hind Fauj and used the call 'Chalo Dilli'.",["NIOS-SS-213-L08"]],
  ["quit-wardha","The Congress Working Committee passed the Quit India resolution at Wardha on 14 July 1942.",["NIOS-SS-213-L08"]],
  ["quit-bombay","The Quit India resolution was endorsed at the Bombay session of the Congress on 8 August 1942.",["NIOS-SS-213-L08"]],
  ["quit-do-or-die","At the Bombay session in August 1942, Gandhi gave the call commonly remembered as 'Do or Die'.",["NIOS-SS-213-L08"]],
  ["quit-arrests","The British authorities arrested Gandhi and other top Congress leaders at the start of the Quit India movement.",["NIOS-HIS-315-L21"]],
  ["quit-spontaneous","With many leaders imprisoned, local protests during Quit India often developed through local initiative and underground activity.",["NIOS-HIS-315-L21"]],
  ["quit-repression","The Quit India movement faced severe repression, mass arrests and police firing.",["NIOS-HIS-315-L21"]],
  ["transfer-talks-1945","After the Second World War ended in 1945, negotiations over the transfer of power became central to British policy in India.",["NIOS-SS-213-L08"]],
  ["cabinet-mission-1946","The Cabinet Mission arrived in India in 1946 to seek an agreed constitutional settlement.",["NIOS-SS-213-L08"]],
  ["cabinet-talks","The Cabinet Mission held discussions with leaders of major Indian political organizations.",["NIOS-SS-213-L08"]],
  ["interim-govt","A Congress-led Interim Government was formed at the Centre in September 1946.",["NIOS-SS-213-L08"]],
  ["direct-action-day","The Muslim League observed Direct Action Day on 16 August 1946 amid its campaign for Pakistan; major communal violence followed.",["NIOS-SS-213-L08"]],
  ["mountbatten-plan","Lord Mountbatten announced a transfer-of-power plan in June 1947 that provided for partition.",["NIOS-SS-213-L08"]],
  ["rin-1946","The Royal Indian Navy uprising began at HMIS Talwar in Bombay in February 1946 and spread to other naval establishments.",["GOI-CULTURE-RIN-1946"]],
  ["rin-demands","Naval ratings in 1946 combined service grievances with political demands, including the release of prisoners connected with the INA trials.",["GOI-CULTURE-RIN-1946"]],
  ["independence-act","The Indian Independence Act of 1947 provided for two independent dominions, India and Pakistan.",["NIOS-SS-213-L08"]],
  ["independence-date","India became independent on 15 August 1947.",["NIOS-SS-213-L08"]],
  ["partition-violence","Partition in 1947 was accompanied by large-scale communal violence and displacement.",["NIOS-SS-213-L08"]],
  ["multiple-strands","India's national movement included constitutional politics, mass movements, revolutionary activity and military efforts; it was not a single homogeneous strand.",["NIOS-HIS-315-L21"]],
];
export const HIS_CP016_FACT_BY_ID_V1=new Map(HIS_CP016_FACTS_V1.map(f=>[f[0],f]));
