import type { PolCp016Seed } from "./pol-cp016-review-seed-types";
const C = "LEGISLATIVE-DEPT-CONSTITUTION-2026";
const q=(ql:number,stem:string,canonicalAnswer:string,distractors:[string,string,string],explanation:string,fact:string):PolCp016Seed=>({qlId:`POL-016-QL-${String(ql).padStart(3,"0")}`,difficulty:"Easy",stem,canonicalAnswer,distractors,explanation,sourceIds:[C],sourceFactIds:[fact]});

export const POL_CP016_SEEDS_A: readonly PolCp016Seed[] = Object.freeze([
// QL-001 — Article map
q(1,"Which Article deals with the constitution of State Legislatures?","Article 168",["Article 169","Article 170","Article 171"],"Article 168 sets out the basic structure of State Legislatures and distinguishes between unicameral and bicameral States.","pol-cp016-art168"),
q(1,"Which Article provides the procedure for creation or abolition of a State Legislative Council?","Article 169",["Article 168","Article 170","Article 172"],"Article 169 allows Parliament to create or abolish a Legislative Council after the State Assembly passes the required special resolution.","pol-cp016-art169"),
q(1,"Which Article mainly deals with the composition of State Legislative Assemblies?","Article 170",["Article 168","Article 171","Article 173"],"Article 170 provides the general constitutional framework for the size and territorial election of State Legislative Assemblies.","pol-cp016-art170"),
q(1,"Which Article deals with the composition of State Legislative Councils?","Article 171",["Article 169","Article 170","Article 172"],"Article 171 prescribes the broad size, elected categories and nominated category of a State Legislative Council.","pol-cp016-art171-composition"),

// QL-002 — Structure and Council creation
q(2,"What forms part of every State Legislature under Article 168?","Governor",["Chief Minister only","High Court Chief Justice","State Public Service Commission"],"Article 168 treats the Governor as a component of the State Legislature along with the House or Houses.","pol-cp016-art168"),
q(2,"Who may create or abolish a State Legislative Council after the required Assembly resolution?","Parliament by law",["Governor by notification","President by executive order alone","Supreme Court by judgment"],"Article 169 places the final legislative power with Parliament after the State Assembly adopts the constitutionally required resolution.","pol-cp016-art169"),
q(2,"What majority is required in the State Assembly resolution under Article 169?","Majority of total membership plus two-thirds present and voting",["Simple majority present and voting","Two-thirds of total membership only","Unanimous vote of the Assembly"],"Article 169 combines two thresholds: a majority of total Assembly membership and at least two-thirds of members present and voting.","pol-cp016-art169"),
q(2,"Is a law made under Article 169 treated as a constitutional amendment under Article 368?","No",["Yes","Only when a Council is created","Only when a Council is abolished"],"Article 169 expressly says such a law is not deemed a constitutional amendment for the purposes of Article 368.","pol-cp016-art169"),

// QL-003 — Assembly composition
q(3,"What is the general constitutional maximum strength of a State Legislative Assembly under Article 170?","500 members",["400 members","550 members","600 members"],"Article 170 generally fixes the Assembly between sixty and five hundred members, subject to constitutional exceptions and special provisions.","pol-cp016-art170"),
q(3,"What is the general constitutional minimum strength of a State Legislative Assembly under Article 170?","60 members",["40 members","50 members","75 members"],"Article 170 generally provides a minimum Assembly strength of sixty members, though separate constitutional provisions create specific exceptions.","pol-cp016-art170"),
q(3,"How are members of a State Legislative Assembly generally chosen under Article 170?","Direct election from territorial constituencies",["Election by local authorities","Nomination by the Governor","Election by Parliament"],"Article 170 generally provides for direct election of Assembly members from territorial constituencies within the State.","pol-cp016-art170"),
q(3,"What principle does Article 170 apply to constituency population and seat allocation within a State?","The ratio should be as nearly equal as practicable",["Every district must have equal seats","Population is irrelevant","Only area determines seat allocation"],"Article 170 seeks, so far as practicable, a similar population-to-seat ratio across territorial constituencies within the State.","pol-cp016-art170"),

// QL-004 — Council composition
q(4,"A State Legislative Council may have at most what fraction of the Legislative Assembly's total strength?","One-third",["One-fourth","One-half","Two-thirds"],"Article 171 caps the Legislative Council at one-third of the total membership of the State Legislative Assembly.","pol-cp016-art171-size"),
q(4,"What is the ordinary constitutional minimum strength of a State Legislative Council under Article 171?","40 members",["30 members","50 members","60 members"],"Article 171 provides that a State Legislative Council shall ordinarily have no fewer than forty members.","pol-cp016-art171-size"),
q(4,"Approximately what fraction of a Legislative Council is elected by local-authority electorates?","One-third",["One-twelfth","One-sixth","One-half"],"Article 171 assigns approximately one-third of Council seats to electorates formed from specified local authorities in the State.","pol-cp016-art171-composition"),
q(4,"Approximately what fraction of a Legislative Council is elected by State Assembly members from persons who are not MLAs?","One-third",["One-twelfth","One-fourth","One-half"],"Article 171 assigns approximately one-third of Council seats to election by MLAs from persons who are not Assembly members.","pol-cp016-art171-composition"),

// QL-005 — Duration and qualifications
q(5,"What is the normal term of a State Legislative Assembly unless sooner dissolved?","Five years",["Four years","Six years","Seven years"],"Article 172 gives a Legislative Assembly a normal five-year life from its first meeting unless it is dissolved earlier.","pol-cp016-art172"),
q(5,"Is a State Legislative Council subject to dissolution?","No",["Yes, every five years","Only during an Emergency","Only by the Governor"],"Article 172 treats the Legislative Council as a continuing body rather than a House that is periodically dissolved.","pol-cp016-art172"),
q(5,"What is the minimum age for membership of a State Legislative Assembly?","25 years",["21 years","30 years","35 years"],"Article 173 qualifications:\n• Citizen of India\n• Oath/affirmation before an Election Commission-authorised person\n• At least 25 for Assembly, 30 for Council\n• Other qualifications prescribed by Parliament.","pol-cp016-art173"),
q(5,"What is the minimum age for membership of a State Legislative Council?","30 years",["25 years","35 years","40 years"],"Article 173 qualifications:\n• Citizen of India\n• Oath/affirmation before an Election Commission-authorised person\n• At least 30 for Council, 25 for Assembly\n• Other qualifications prescribed by Parliament.","pol-cp016-art173"),

// QL-006 — Sessions, addresses and participation
q(6,"What is the maximum interval permitted between two sessions of a State Legislature?","Six months",["Three months","Nine months","One year"],"Article 174 requires that no more than six months intervene between the last sitting of one session and the next session's first sitting.","pol-cp016-art174"),
q(6,"Who formally summons a State Legislature under Article 174?","Governor",["Chief Minister","Speaker alone","President"],"Article 174 gives the Governor the formal constitutional power to summon the House or Houses of the State Legislature.","pol-cp016-art174"),
q(6,"When is the Governor's special address required under Article 176?","First session after each Assembly general election and first session each year",["Every sitting","Only before dissolution","Only during Budget sessions"],"Article 176 requires the special address at the first session after a general election and at the first session of each year.","pol-cp016-art176"),
q(6,"Does Article 177 itself give a State Minister the right to vote in a House merely because the person is a Minister?","No",["Yes","Only in the Legislative Council","Only on financial business"],"Article 177 grants Ministers speaking and participation rights but expressly does not create a voting right by virtue of that Article alone.","pol-cp016-art177")
]);
