import type { PolCp016Seed } from "./pol-cp016-review-seed-types";
const C = "LEGISLATIVE-DEPT-CONSTITUTION-2026";
const q=(ql:number,difficulty:"Medium"|"Hard",stem:string,canonicalAnswer:string,distractors:[string,string,string],explanation:string,fact:string):PolCp016Seed=>({qlId:`POL-016-QL-${String(ql).padStart(3,"0")}`,difficulty,stem,canonicalAnswer,distractors,explanation,sourceIds:[C],sourceFactIds:[fact]});

export const POL_CP016_SEEDS_D: readonly PolCp016Seed[] = Object.freeze([
// QL-019 — Appropriation and additional grants
q(19,"Medium","What is the main purpose of a State Appropriation Bill under Article 204?","Authorising withdrawal from the Consolidated Fund of the State",["Creating the Legislative Council","Electing the Speaker","Amending the Constitution"],"Article 204 authorises withdrawals needed for Assembly grants and charged expenditure from the Consolidated Fund of the State.","pol-cp016-art204"),
q(19,"Medium","Can an Appropriation Bill amendment vary the amount or destination of a grant already made?","No",["Yes","Only in the Legislative Council","Only with Governor approval"],"Article 204 makes such amendments inadmissible, and the presiding officer's decision on admissibility is final.","pol-cp016-art204"),
q(19,"Medium","Which grant is used when the authorised amount for an existing service proves insufficient?","Supplementary grant",["Exceptional grant","Vote of credit","Money Bill certificate"],"Article 205 uses supplementary expenditure when the amount already authorised for a service is insufficient during the financial year.","pol-cp016-art205"),
q(19,"Medium","Which situation gives rise to an excess grant?","Money was spent beyond the amount granted for a service",["A new service was proposed but not begun","The Budget was not presented","The Council rejected an ordinary Bill"],"Article 205 deals with excess expenditure when spending on a service has already gone beyond the amount granted for that year.","pol-cp016-art205"),

// QL-020 — Vote on account, credit and exceptional grant
q(20,"Medium","What is the purpose of a vote on account under Article 206?","Advance funding for part of the year pending normal budget procedure",["Funding an undefined emergency demand","Financing a service outside the current year","Creating a new tax"],"A vote on account provides an advance for part of the financial year while the regular grant and appropriation procedure is completed.","pol-cp016-art206"),
q(20,"Medium","Which grant addresses an unexpected demand whose magnitude or indefinite character prevents normal detailed presentation?","Vote of credit",["Vote on account","Exceptional grant","Supplementary grant only"],"Article 206 uses a vote of credit for an unexpected demand that cannot be stated with the usual budget detail.","pol-cp016-art206"),
q(20,"Medium","Which grant is for a purpose that forms no part of the current service of any financial year?","Exceptional grant",["Vote on account","Vote of credit","Demand for grant"],"Article 206 defines an exceptional grant by its purpose being outside the current service of any financial year.","pol-cp016-art206"),
q(20,"Medium","Which House has the constitutional power to make grants under Article 206?","Legislative Assembly",["Legislative Council","Both Houses jointly","Governor alone"],"Article 206 places votes on account, votes of credit and exceptional grants in the hands of the Legislative Assembly.","pol-cp016-art206"),

// QL-021 — Financial Bills
q(21,"Hard","A State Bill contains matters listed in Article 199(1)(a)–(f). What is required for its introduction?","Governor's recommendation",["Speaker's casting vote","High Court permission","Legislative Council resolution"],"Article 207 requires the Governor's recommendation for introducing a Bill containing the specified Article 199 financial matters.","pol-cp016-art207"),
q(21,"Hard","Can a State financial Bill containing Article 199(1)(a)–(f) matters be introduced in the Legislative Council?","No",["Yes","Only with unanimous Council approval","Only after the Assembly rejects it"],"Article 207 bars such a financial Bill from originating in the Legislative Council, preserving Assembly primacy in financial legislation.","pol-cp016-art207"),
q(21,"Hard","Does an amendment reducing or abolishing a tax require the Governor's recommendation under Article 207(1)?","No",["Yes","Only if moved in the Assembly","Only if the Council agrees"],"The proviso to Article 207(1) specifically exempts an amendment that reduces or abolishes a tax from that recommendation requirement.","pol-cp016-art207"),
q(21,"Hard","A Bill would involve expenditure from the State Consolidated Fund. What must happen before a House passes it?","Governor must recommend consideration of the Bill",["Legislative Council must certify it","Speaker must declare it a Money Bill","President must summon the House"],"Article 207(3) prevents passage of such a Bill unless the Governor has recommended its consideration to that House.","pol-cp016-art207"),

// QL-022 — Rules, language and judicial limits
q(22,"Hard","Who may make rules regulating the procedure and conduct of business of a State Legislature House?","The House itself, subject to the Constitution",["Governor alone","High Court","Election Commission"],"Article 208 allows each House to make procedural rules, but those rules remain subject to the Constitution.","pol-cp016-art208"),
q(22,"Hard","What happens if a State law under Article 209 conflicts with a House rule on financial procedure?","The inconsistent House rule yields to the State law",["The State law is automatically void","The Governor decides case by case","The High Court rewrites the rule"],"Article 209 permits State law to regulate timely financial business and gives that law priority over inconsistent procedural rules.","pol-cp016-art209"),
q(22,"Hard","May a State Legislature discuss the conduct of a Supreme Court or High Court Judge in discharge of judicial duties?","No",["Yes","Only in the Legislative Council","Only during a special address"],"Article 211 expressly prohibits such discussion in a State Legislature when it concerns judicial conduct in discharge of duties.","pol-cp016-art211"),
q(22,"Hard","Can a court invalidate State legislative proceedings merely because of an alleged procedural irregularity?","No",["Yes","Only the Supreme Court can","Only if quorum was questioned"],"Article 212 prevents courts from questioning legislative proceedings merely on the ground of an alleged irregularity of procedure.","pol-cp016-art212"),

// QL-023 — Integrated Assembly vs Council
q(23,"Hard","Which statement correctly compares the Legislative Assembly and Legislative Council?","Assembly may be dissolved; Council is a continuing body",["Both are dissolved every five years","Council alone votes demands for grants","Money Bills may originate in either House"],"Article 172 makes the Assembly time-limited and dissolvable while the Legislative Council continues with staggered retirement.","pol-cp016-art172"),
q(23,"Hard","Which combination correctly shows Assembly financial primacy in a bicameral State?","Money Bills originate in Assembly and demands for grants are voted there",["Council originates Money Bills and votes grants","Both Houses have equal grant-voting power","Council certifies Money Bills"],"Articles 198 and 203 place Money Bill origin and demands-for-grants voting with the Legislative Assembly rather than the Council.","pol-cp016-art198"),
q(23,"Hard","An ordinary Bill returns to the Council after Assembly repassage. What is the Council's maximum second-stage delay?","One month",["14 days","Three months","Six months"],"Article 197 reduces the Council's second-stage delaying power to one month after the Assembly has passed the Bill again.","pol-cp016-art197"),
q(23,"Hard","Which rule correctly distinguishes Money Bills from ordinary Bills in a bicameral State?","Council has 14 days on Money Bills, but may delay ordinary Bills longer",["Council can veto both permanently","Both use a joint sitting","Both must originate in the Assembly"],"Money Bills follow a fourteen-day recommendation process, while ordinary Bills face the separate three-month and one-month delay structure.","pol-cp016-art198"),

// QL-024 — Integrated constitutional cases
q(24,"Hard","Consider the statements:\n1. A Legislative Council is not dissolved.\n2. About one-third of its members retire every two years.\n3. Its normal term is five years.\nWhich are correct?","Statements 1 and 2 only",["Statement 1 only","Statements 2 and 3 only","All three"],"Article 172 makes the Council a continuing body with staggered retirement, so it has no five-year collective term like an Assembly.","pol-cp016-art172"),
q(24,"Hard","Consider the statements:\n1. A Money Bill cannot originate in the Council.\n2. The Council may recommend changes within 14 days.\n3. The Assembly must accept those recommendations.\nWhich are correct?","Statements 1 and 2 only",["Statement 1 only","Statements 2 and 3 only","All three"],"Article 198 gives the Council a recommendation role for fourteen days, but the Assembly may accept or reject those recommendations.","pol-cp016-art198"),
q(24,"Hard","A House has 80 members. Until State law provides otherwise, what quorum is required?","10 members",["8 members","16 members","40 members"],"One-tenth of eighty is eight, but Article 189 uses ten members or one-tenth, whichever is greater, so ten is required.","pol-cp016-art189"),
q(24,"Hard","A House has 150 members. Until State law provides otherwise, what quorum is required?","15 members",["10 members","20 members","75 members"],"One-tenth of one hundred fifty is fifteen, which is greater than ten and therefore becomes the constitutional quorum.","pol-cp016-art189")
]);
