import type { EnglishDifficulty } from "../../../../core/types";
import type { ConjunctionRuleId } from "../../../../grammar/conjunctions-parallelism";

export interface ConjunctionSceneV1 {
  id: string;
  difficulty: EnglishDifficulty;
  ruleId: ConjunctionRuleId;
  domain: string;
  correctSegments: readonly [string, string, string, string];
  errorSegments: readonly [string, string, string, string];
  errorIndex: 0 | 1 | 2 | 3;
  correction: string;
  reason: string;
}

const s = (
  id: string,
  difficulty: EnglishDifficulty,
  ruleId: ConjunctionRuleId,
  domain: string,
  correctSegments: ConjunctionSceneV1["correctSegments"],
  errorSegments: ConjunctionSceneV1["errorSegments"],
  errorIndex: ConjunctionSceneV1["errorIndex"],
  correction: string,
  reason: string,
): ConjunctionSceneV1 => ({ id, difficulty, ruleId, domain, correctSegments, errorSegments, errorIndex, correction, reason });

export const CP007_SCENES_V1: readonly ConjunctionSceneV1[] = [
  // EASY — two scenes per rule.
  s("CON-E01", "easy", "GR-CON-001", "office",
    ["The report was brief,", "but it covered", "all the main findings", "clearly."],
    ["The report was brief,", "so it covered", "all the main findings", "clearly."], 1, "but it covered",
    "The second clause contrasts with the first, so 'but' is the suitable coordinating conjunction."),
  s("CON-E02", "easy", "GR-CON-001", "weather",
    ["It rained all morning,", "so the match", "was postponed", "until Sunday."],
    ["It rained all morning,", "but the match", "was postponed", "until Sunday."], 1, "so the match",
    "The postponement is a result of the rain, so 'so' is required."),
  s("CON-E03", "easy", "GR-CON-002", "school",
    ["Both the teacher", "and the students", "supported the plan", "for the library."],
    ["Both the teacher", "or the students", "supported the plan", "for the library."], 1, "and the students",
    "The fixed correlative pair is 'both ... and'."),
  s("CON-E04", "easy", "GR-CON-002", "travel",
    ["The tour includes", "both the museum", "and the fort", "in one day."],
    ["The tour includes", "both the museum", "as well as the fort", "in one day."], 2, "and the fort",
    "After 'both', the matching conjunction is 'and'."),
  s("CON-E05", "easy", "GR-CON-003", "shopping",
    ["You may choose", "either the blue shirt", "or the black one", "for the event."],
    ["You may choose", "either the blue shirt", "nor the black one", "for the event."], 2, "or the black one",
    "The correct correlative pair for alternatives is 'either ... or'."),
  s("CON-E06", "easy", "GR-CON-003", "transport",
    ["We can travel", "either by bus", "or by train", "tomorrow morning."],
    ["We can travel", "neither by bus", "or by train", "tomorrow morning."], 1, "either by bus",
    "The sentence presents two alternatives, so it needs 'either ... or'."),
  s("CON-E07", "easy", "GR-CON-004", "food",
    ["She ordered", "neither tea", "nor coffee", "with breakfast."],
    ["She ordered", "neither tea", "or coffee", "with breakfast."], 2, "nor coffee",
    "The fixed negative correlative pair is 'neither ... nor'."),
  s("CON-E08", "easy", "GR-CON-004", "sports",
    ["Neither the captain", "nor the coach", "accepted the proposal", "after the meeting."],
    ["Either the captain", "nor the coach", "accepted the proposal", "after the meeting."], 0, "Neither the captain",
    "When both alternatives are rejected, use 'neither ... nor'."),
  s("CON-E09", "easy", "GR-CON-005", "music",
    ["The singer", "not only wrote the song", "but also composed", "the music."],
    ["The singer", "not only wrote the song", "and also composed", "the music."], 2, "but also composed",
    "The matching pair is 'not only ... but also'."),
  s("CON-E10", "easy", "GR-CON-005", "workplace",
    ["The new system", "is not only faster", "but also easier", "to use."],
    ["The new system", "is not only faster", "but easier also", "to use."], 2, "but also easier",
    "Use the standard correlative pair 'not only ... but also' with parallel complements."),
  s("CON-E11", "easy", "GR-CON-006", "weather",
    ["Although it was cold,", "the children", "played outside", "for an hour."],
    ["Although it was cold,", "but the children", "played outside", "for an hour."], 1, "the children",
    "Do not add 'but' after an 'although' clause in the same sentence."),
  s("CON-E12", "easy", "GR-CON-006", "study",
    ["Though the chapter was long,", "Riya finished it", "before dinner", "without help."],
    ["Though the chapter was long,", "but Riya finished it", "before dinner", "without help."], 1, "Riya finished it",
    "'Though' already marks contrast, so 'but' is unnecessary."),
  s("CON-E13", "easy", "GR-CON-007", "traffic",
    ["The bus was late", "because the road", "was blocked", "after the accident."],
    ["The bus was late", "because of the road", "was blocked", "after the accident."], 1, "because the road",
    "Use 'because' before a finite clause such as 'the road was blocked'."),
  s("CON-E14", "easy", "GR-CON-007", "health",
    ["The event was cancelled", "because of heavy rain", "in the area", "that evening."],
    ["The event was cancelled", "because heavy rain", "in the area", "that evening."], 1, "because of heavy rain",
    "Use 'because of' before a noun phrase such as 'heavy rain'."),
  s("CON-E15", "easy", "GR-CON-008", "travel",
    ["Despite the delay,", "the train", "reached the station", "before noon."],
    ["Although the delay,", "the train", "reached the station", "before noon."], 0, "Despite the delay,",
    "Use 'despite' before a noun phrase; 'although' requires a clause."),
  s("CON-E16", "easy", "GR-CON-008", "school",
    ["Although the test was difficult,", "most students", "completed it", "on time."],
    ["Despite the test was difficult,", "most students", "completed it", "on time."], 0, "Although the test was difficult,",
    "Use 'although' before a finite clause such as 'the test was difficult'."),
  s("CON-E17", "easy", "GR-CON-009", "fitness",
    ["Her routine includes", "walking in the morning,", "stretching after lunch,", "and cycling in the evening."],
    ["Her routine includes", "walking in the morning,", "to stretch after lunch,", "and cycling in the evening."], 2, "stretching after lunch,",
    "Items in a coordinated list should use the same grammatical form; all three are gerunds here."),
  s("CON-E18", "easy", "GR-CON-009", "office",
    ["The assistant had to", "check the files,", "update the register,", "and send the emails."],
    ["The assistant had to", "check the files,", "updating the register,", "and send the emails."], 2, "update the register,",
    "The three coordinated actions should all use the base verb form after 'had to'."),
  s("CON-E19", "easy", "GR-CON-010", "education",
    ["The course helps students", "both to write clearly", "and to speak confidently", "in formal settings."],
    ["The course helps students", "both to write clearly", "and speaking confidently", "in formal settings."], 2, "and to speak confidently",
    "The elements after 'both' and 'and' should have matching infinitive structure."),
  s("CON-E20", "easy", "GR-CON-010", "hobbies",
    ["She enjoys", "not only reading novels", "but also writing stories", "on weekends."],
    ["She enjoys", "not only reading novels", "but also to write stories", "on weekends."], 2, "but also writing stories",
    "The two elements joined by 'not only ... but also' should be parallel gerund phrases."),

  // MEDIUM
  s("CON-M01", "medium", "GR-CON-001", "research",
    ["The sample was small,", "yet the pattern", "appeared consistently", "across three trials."],
    ["The sample was small,", "so the pattern", "appeared consistently", "across three trials."], 1, "yet the pattern",
    "The clauses express contrast rather than cause and result, so 'yet' fits the relation."),
  s("CON-M02", "medium", "GR-CON-001", "finance",
    ["The company reduced costs,", "so its operating margin", "improved during", "the next quarter."],
    ["The company reduced costs,", "or its operating margin", "improved during", "the next quarter."], 1, "so its operating margin",
    "The second clause states a result, so 'so' is the suitable coordinator."),
  s("CON-M03", "medium", "GR-CON-002", "public-service",
    ["The scheme benefits", "both rural workers", "and small farmers", "in the district."],
    ["The scheme benefits", "both rural workers", "or small farmers", "in the district."], 2, "and small farmers",
    "Use 'both ... and' when including two groups together."),
  s("CON-M04", "medium", "GR-CON-002", "technology",
    ["The update improves", "both system stability", "and battery performance", "on older devices."],
    ["The update improves", "either system stability", "and battery performance", "on older devices."], 1, "both system stability",
    "The sentence includes both improvements, so the pair must be 'both ... and'."),
  s("CON-M05", "medium", "GR-CON-003", "admissions",
    ["Applicants may submit", "either a passport", "or another approved identity document", "with the form."],
    ["Applicants may submit", "either a passport", "and another approved identity document", "with the form."], 2, "or another approved identity document",
    "Two alternatives after 'either' must be joined by 'or'."),
  s("CON-M06", "medium", "GR-CON-003", "workplace",
    ["The interview will be held", "either on Monday", "or on Tuesday", "depending on availability."],
    ["The interview will be held", "both on Monday", "or on Tuesday", "depending on availability."], 1, "either on Monday",
    "Only one of the two days will be chosen, so use 'either ... or'."),
  s("CON-M07", "medium", "GR-CON-004", "administration",
    ["The committee accepted", "neither the original proposal", "nor the revised draft", "at its meeting."],
    ["The committee accepted", "neither the original proposal", "or the revised draft", "at its meeting."], 2, "nor the revised draft",
    "After 'neither', the second alternative is introduced by 'nor'."),
  s("CON-M08", "medium", "GR-CON-004", "banking",
    ["Neither the branch office", "nor the regional office", "issued a clarification", "that day."],
    ["Neither the branch office", "or the regional office", "issued a clarification", "that day."], 1, "nor the regional office",
    "The negative pair is 'neither ... nor'."),
  s("CON-M09", "medium", "GR-CON-005", "education",
    ["The workshop", "not only explains the concept", "but also demonstrates", "its practical use."],
    ["The workshop", "not only explains the concept", "but demonstrates also", "its practical use."], 2, "but also demonstrates",
    "Use 'not only ... but also' in the standard paired form."),
  s("CON-M10", "medium", "GR-CON-005", "environment",
    ["The policy aims", "not only to reduce waste", "but also to improve recycling", "across the city."],
    ["The policy aims", "not only to reduce waste", "but improving recycling also", "across the city."], 2, "but also to improve recycling",
    "The pair should be 'not only ... but also', and the joined infinitive phrases should remain parallel."),
  s("CON-M11", "medium", "GR-CON-006", "economy",
    ["Although demand weakened,", "prices remained stable", "during most of", "the quarter."],
    ["Although demand weakened,", "but prices remained stable", "during most of", "the quarter."], 1, "prices remained stable",
    "'Although' already introduces the contrast; adding 'but' is redundant in the same clause pair."),
  s("CON-M12", "medium", "GR-CON-006", "sports",
    ["Though the team lost early wickets,", "it recovered", "and reached", "a competitive total."],
    ["Though the team lost early wickets,", "but it recovered", "and reached", "a competitive total."], 1, "it recovered",
    "Do not use 'but' after a clause already introduced by 'though'."),
  s("CON-M13", "medium", "GR-CON-007", "aviation",
    ["Several flights were delayed", "because visibility", "had fallen sharply", "before sunrise."],
    ["Several flights were delayed", "because of visibility", "had fallen sharply", "before sunrise."], 1, "because visibility",
    "A finite clause follows, so use 'because', not 'because of'."),
  s("CON-M14", "medium", "GR-CON-007", "agriculture",
    ["Crop output declined", "because of prolonged drought", "in several districts", "during the season."],
    ["Crop output declined", "because prolonged drought", "in several districts", "during the season."], 1, "because of prolonged drought",
    "A noun phrase follows, so 'because of' is required."),
  s("CON-M15", "medium", "GR-CON-008", "healthcare",
    ["Despite repeated reminders,", "some patients", "missed their follow-up visits", "during the month."],
    ["Although repeated reminders,", "some patients", "missed their follow-up visits", "during the month."], 0, "Despite repeated reminders,",
    "A noun phrase follows, so use 'despite', not 'although'."),
  s("CON-M16", "medium", "GR-CON-008", "industry",
    ["Although production increased,", "the factory", "did not meet", "its annual target."],
    ["Despite production increased,", "the factory", "did not meet", "its annual target."], 0, "Although production increased,",
    "A finite clause follows, so 'although' is correct; 'despite' takes a noun or gerund phrase."),
  s("CON-M17", "medium", "GR-CON-009", "management",
    ["The role requires", "planning weekly schedules,", "reviewing team performance,", "and resolving customer complaints."],
    ["The role requires", "planning weekly schedules,", "to review team performance,", "and resolving customer complaints."], 2, "reviewing team performance,",
    "All three duties should be expressed as parallel gerund phrases."),
  s("CON-M18", "medium", "GR-CON-009", "science",
    ["The experiment was designed", "to measure pressure,", "to record temperature,", "and to compare the results."],
    ["The experiment was designed", "to measure pressure,", "recording temperature,", "and to compare the results."], 2, "to record temperature,",
    "The coordinated purposes should use matching infinitive forms."),
  s("CON-M19", "medium", "GR-CON-010", "training",
    ["The programme teaches staff", "both how to identify risks", "and how to report them", "without delay."],
    ["The programme teaches staff", "both how to identify risks", "and reporting them", "without delay."], 2, "and how to report them",
    "The two elements after 'both' and 'and' must have matching clause structure."),
  s("CON-M20", "medium", "GR-CON-010", "business",
    ["The manager wanted", "not only to cut expenses", "but also to improve service", "before the next review."],
    ["The manager wanted", "not only to cut expenses", "but also improving service", "before the next review."], 2, "but also to improve service",
    "Correlative elements should be structurally parallel; both are infinitive phrases here."),

  // HARD — complexity comes from longer dependency and closer distractors, not obscure vocabulary.
  s("CON-H01", "hard", "GR-CON-001", "policy",
    ["The regulation simplified filing requirements,", "yet several small firms", "reported higher compliance costs", "during the transition period."],
    ["The regulation simplified filing requirements,", "so several small firms", "reported higher compliance costs", "during the transition period."], 1, "yet several small firms",
    "The second clause contrasts with the expected effect of simplification, so 'yet' is required."),
  s("CON-H02", "hard", "GR-CON-001", "research",
    ["The revised method reduced measurement error,", "so the final estimates", "were more consistent", "across the three laboratories."],
    ["The revised method reduced measurement error,", "but the final estimates", "were more consistent", "across the three laboratories."], 1, "so the final estimates",
    "The second clause is a result of reduced measurement error, so 'so' fits the logical relation."),
  s("CON-H03", "hard", "GR-CON-002", "governance",
    ["The reform strengthened", "both local oversight mechanisms", "and central reporting standards", "without changing the funding formula."],
    ["The reform strengthened", "both local oversight mechanisms", "as well as central reporting standards", "without changing the funding formula."], 2, "and central reporting standards",
    "The formal correlative construction is 'both ... and'; do not mix 'both' with 'as well as'."),
  s("CON-H04", "hard", "GR-CON-002", "education",
    ["The new assessment measures", "both conceptual understanding", "and the ability to apply it", "in unfamiliar situations."],
    ["The new assessment measures", "either conceptual understanding", "and the ability to apply it", "in unfamiliar situations."], 1, "both conceptual understanding",
    "Both abilities are included, so the sentence requires the pair 'both ... and'."),
  s("CON-H05", "hard", "GR-CON-003", "law",
    ["A candidate may satisfy the requirement", "either by completing the course", "or by passing the qualifying examination", "within the prescribed period."],
    ["A candidate may satisfy the requirement", "either by completing the course", "nor by passing the qualifying examination", "within the prescribed period."], 2, "or by passing the qualifying examination",
    "The construction presents two alternatives, so 'either' must be paired with 'or'."),
  s("CON-H06", "hard", "GR-CON-003", "administration",
    ["The authority may issue the notice", "either through the online portal", "or by registered post", "after the application is reviewed."],
    ["The authority may issue the notice", "neither through the online portal", "or by registered post", "after the application is reviewed."], 1, "either through the online portal",
    "The sentence offers two possible methods, so use 'either ... or'."),
  s("CON-H07", "hard", "GR-CON-004", "audit",
    ["The auditors found", "neither documentary evidence of approval", "nor a record of later ratification", "in the files they examined."],
    ["The auditors found", "neither documentary evidence of approval", "or a record of later ratification", "in the files they examined."], 2, "nor a record of later ratification",
    "Two rejected alternatives after 'neither' must be linked by 'nor'."),
  s("CON-H08", "hard", "GR-CON-004", "science",
    ["Neither the initial hypothesis", "nor the alternative explanation", "accounted for the observed variation", "across all four samples."],
    ["Neither the initial hypothesis", "or the alternative explanation", "accounted for the observed variation", "across all four samples."], 1, "nor the alternative explanation",
    "The negative correlative pair is 'neither ... nor'."),
  s("CON-H09", "hard", "GR-CON-005", "public-policy",
    ["The revised programme", "not only expanded access to training", "but also reduced waiting times", "for applicants in remote areas."],
    ["The revised programme", "not only expanded access to training", "and also reduced waiting times", "for applicants in remote areas."], 2, "but also reduced waiting times",
    "Use the complete pair 'not only ... but also'."),
  s("CON-H10", "hard", "GR-CON-005", "technology",
    ["The redesign was intended", "not only to improve accessibility", "but also to reduce loading time", "on lower-powered devices."],
    ["The redesign was intended", "not only to improve accessibility", "but also reducing loading time", "on lower-powered devices."], 2, "but also to reduce loading time",
    "The correlative pair should join parallel infinitive phrases."),
  s("CON-H11", "hard", "GR-CON-006", "economics",
    ["Although borrowing costs fell during the quarter,", "investment remained weak", "because firms were uncertain", "about future demand."],
    ["Although borrowing costs fell during the quarter,", "but investment remained weak", "because firms were uncertain", "about future demand."], 1, "investment remained weak",
    "'Although' already marks the contrast between falling costs and weak investment, so 'but' is not used."),
  s("CON-H12", "hard", "GR-CON-006", "history",
    ["Though the agreement ended the immediate dispute,", "several underlying issues", "continued to affect relations", "for many years afterward."],
    ["Though the agreement ended the immediate dispute,", "but several underlying issues", "continued to affect relations", "for many years afterward."], 1, "several underlying issues",
    "The concessive conjunction 'though' already links the contrasting clauses; 'but' is redundant."),
  s("CON-H13", "hard", "GR-CON-007", "infrastructure",
    ["Construction slowed", "because material deliveries", "were repeatedly interrupted", "during the monsoon period."],
    ["Construction slowed", "because of material deliveries", "were repeatedly interrupted", "during the monsoon period."], 1, "because material deliveries",
    "A full clause follows, so use 'because' before 'material deliveries were repeatedly interrupted'."),
  s("CON-H14", "hard", "GR-CON-007", "banking",
    ["The branch remained closed", "because of an extended power outage", "in the surrounding area", "through most of the afternoon."],
    ["The branch remained closed", "because an extended power outage", "in the surrounding area", "through most of the afternoon."], 1, "because of an extended power outage",
    "A noun phrase follows, so 'because of' is required."),
  s("CON-H15", "hard", "GR-CON-008", "environment",
    ["Despite several months of below-average rainfall,", "the reservoirs", "retained enough water", "to meet essential demand."],
    ["Although several months of below-average rainfall,", "the reservoirs", "retained enough water", "to meet essential demand."], 0, "Despite several months of below-average rainfall,",
    "The complement is a noun phrase, so 'despite' is correct; 'although' requires a clause."),
  s("CON-H16", "hard", "GR-CON-008", "industry",
    ["Although the plant had upgraded its equipment,", "output remained below target", "during the first half", "of the financial year."],
    ["Despite the plant had upgraded its equipment,", "output remained below target", "during the first half", "of the financial year."], 0, "Although the plant had upgraded its equipment,",
    "A finite clause follows, so use 'although', not 'despite'."),
  s("CON-H17", "hard", "GR-CON-009", "research",
    ["The review process involved", "checking the raw data,", "verifying the calculations,", "and comparing the conclusions with earlier studies."],
    ["The review process involved", "checking the raw data,", "to verify the calculations,", "and comparing the conclusions with earlier studies."], 2, "verifying the calculations,",
    "All three coordinated activities after 'involved' should use parallel gerund forms."),
  s("CON-H18", "hard", "GR-CON-009", "administration",
    ["Before approval, the officer must", "confirm the applicant's identity,", "check the supporting documents,", "and record the decision in the system."],
    ["Before approval, the officer must", "confirm the applicant's identity,", "checking the supporting documents,", "and record the decision in the system."], 2, "check the supporting documents,",
    "After 'must', each coordinated action should remain in the base verb form."),
  s("CON-H19", "hard", "GR-CON-010", "leadership",
    ["The chairperson asked the team", "not only to identify the immediate causes", "but also to recommend long-term remedies", "before the next meeting."],
    ["The chairperson asked the team", "not only to identify the immediate causes", "but also recommending long-term remedies", "before the next meeting."], 2, "but also to recommend long-term remedies",
    "The paired elements after 'not only' and 'but also' should both be infinitive phrases."),
  s("CON-H20", "hard", "GR-CON-010", "education",
    ["The scholarship is intended", "both for students who need financial support", "and for those who have strong academic records", "but limited access to other funding."],
    ["The scholarship is intended", "both for students who need financial support", "and those who have strong academic records", "but limited access to other funding."], 2, "and for those who have strong academic records",
    "The two elements linked by 'both ... and' should have matching prepositional structure."),
] as const;

export const CP007_SCENES_BY_DIFFICULTY_V1: Readonly<Record<EnglishDifficulty, readonly ConjunctionSceneV1[]>> = {
  easy: CP007_SCENES_V1.filter((scene) => scene.difficulty === "easy"),
  medium: CP007_SCENES_V1.filter((scene) => scene.difficulty === "medium"),
  hard: CP007_SCENES_V1.filter((scene) => scene.difficulty === "hard"),
};
