import type{Eng008Cp005PassageV1}from"./eng-008-cp005-authorities-v1";
const q=(id:string,familyId:any,difficulty:any,question:string,correctAnswer:string,distractors:readonly[string,string,string],explanation:string,evidence:string)=>({id,familyId,difficulty,question,correctAnswer,distractors,explanation,evidence});
export const ENG008_CP005_EXPANSION_WAVE8_V1:readonly Eng008Cp005PassageV1[]=[
{
 id:"ENG008-RS-W06",title:"Does Meeting-Free Wednesday Improve Focus?",genre:"workplace-study",
 text:`A software company tested a meeting-free Wednesday policy with four product teams for eight weeks. Routine internal meetings were moved to other weekdays, although urgent client calls and incident-response meetings were still allowed. The company wanted to know whether a predictable block of uninterrupted time changed how employees completed concentrated work.

Researchers compared calendar data, task-completion logs and a weekly employee survey with the eight weeks before the pilot. The number of scheduled internal meeting hours fell sharply on Wednesdays but rose slightly on Tuesdays and Thursdays. Total weekly meeting time declined only modestly. Employees reported more uninterrupted work periods on Wednesdays. Code-review and design-document completion also increased on that day, but total weekly output changed much less. Some work had simply moved from other days rather than representing additional production.

The effect varied by role. Engineers and designers reported the largest benefit, while project coordinators sometimes found Tuesdays and Thursdays more crowded because meetings had been compressed into fewer days. Several employees also said that a meeting-free day was less useful when chat messages continued at normal volume.

The company therefore added a second phase in which teams marked non-urgent messages for delayed response during two Wednesday blocks. This reduced interruptions further, although managers warned employees not to treat delayed response as a rule during operational incidents. A limitation is that the study was not random. Teams volunteered for the pilot, and they may already have been more interested in reducing meetings. Seasonal workload also differed between the baseline and test periods.

Researchers will now compare volunteer teams with similar non-participating teams and track whether meeting load simply shifts across the week. They also plan to measure employee stress and after-hours work, because a quiet Wednesday would be less valuable if compressed meetings caused longer evenings elsewhere.

The preliminary result is therefore narrower than “meeting-free days increase productivity.” The pilot suggests that a predictable low-meeting period can improve perceived focus and same-day completion of concentration-heavy tasks, but the effect on weekly output and workload balance remains uncertain.

The researchers also plan to compare the type of work completed on Wednesdays, not just the quantity. A day with fewer meetings may help employees finish deeper tasks that are difficult to divide into short intervals, even if the weekly count of completed items barely changes. They will therefore code tasks by estimated concentration demand and examine whether the policy shifts complex work into the protected blocks rather than simply moving routine work between days.

Researchers also checked how the policy affected calendar fragmentation. Although total weekly meeting hours changed little, participating teams had fewer days containing three or more separate meeting blocks. Employees said this mattered because scattered meetings made it harder to begin work requiring sustained attention. The company will therefore analyse not only total meeting hours but also how those hours are distributed across the day.`,
 questions:[
 q("W06-Q1","RS-F01","medium","What changed most clearly on Wednesdays during the pilot?","Employees had more uninterrupted work periods",["Weekly meeting time fell to zero","Every role produced more work","Client calls were banned"],"The survey and calendar pattern both show a clearer increase in uninterrupted Wednesday work than in total weekly output.","more uninterrupted work periods"),
 q("W06-Q2","RS-F02","medium","What can be inferred from the small change in total weekly output?","Some Wednesday gains may reflect work shifting from other days",["The policy had no effect on focus","Meeting time doubled","Task logs were not collected"],"The passage explicitly notes that same-day completion increased more than total weekly production, suggesting redistribution of work.","simply moved from other days"),
 q("W06-Q3","RS-F03","hard","Which summary is most accurate?","The policy improved Wednesday focus, but weekly productivity and workload effects remain uncertain",["Meeting-free Wednesdays clearly increased all productivity","The policy harmed every coordinator","Chat interruptions disappeared automatically"],"The study finds a focused benefit while retaining uncertainty about weekly output, compressed meetings and after-hours work.","effect on weekly output and workload balance remains uncertain"),
 q("W06-Q4","RS-F04","hard","Which limitation most weakens a strong causal claim?","Teams volunteered rather than being randomly assigned",["Calendars were available","The pilot lasted eight weeks","Urgent meetings were allowed"],"Volunteer teams may differ systematically from non-participating teams, so the observed differences cannot be attributed only to the policy.","study was not random"),
 q("W06-Q5","RS-F05","hard","Which claim would be unjustified?","Meeting-free Wednesdays always increase total weekly productivity",["Some roles benefited more than others","Meetings shifted partly to other days","Messaging could reduce the benefit"],"The study explicitly says total weekly output changed much less and several confounding factors remain.","weekly output changed much less"),
 q("W06-Q6","RS-F06","medium","Which is a directly reported finding?","Tuesday and Thursday meeting hours rose slightly",["All after-hours work declined","Every team reduced weekly meeting time by half","Stress was already lower"],"The calendar data directly recorded a small increase in meetings on adjacent days.","rose slightly on Tuesdays and Thursdays"),
 q("W06-Q7","RS-F07","hard","Which competing mechanism is explicitly identified?","Compressed meetings on other days may offset some benefit",["The company reduced salaries","Employees worked fewer total days","Software tools stopped functioning"],"The passage notes that concentrating meetings on fewer days may create crowding and potentially longer evenings.","meetings had been compressed"),
 q("W06-Q8","RS-F08","medium","Which next step is best supported?","Compare volunteer teams with similar non-participating teams and track after-hours work",["Declare the policy successful permanently","Ban all client calls","Measure only Wednesday output"],"The proposed follow-up directly addresses selection bias and possible displacement of workload to other times.","compare volunteer teams")
 ]
},
{
 id:"ENG008-RS-W07",title:"Do Shared Checklists Reduce Warehouse Picking Errors?",genre:"workplace-study",
 text:`A distribution warehouse tested a shared digital checklist for workers assembling multi-item orders. Previously, pickers scanned each product but relied on memory for several packaging steps, such as adding temperature packs or special labels. Managers wanted to know whether a visible checklist would reduce avoidable packing errors.

Six picking teams used the checklist for ten weeks, while six similar teams continued with the existing process. The checklist automatically displayed extra steps when an order contained fragile, chilled or regulated items. Workers still scanned products in both groups. Recorded packing errors fell more in the checklist teams than in the comparison teams, especially for missed labels and temperature packs. Product-selection errors changed little because barcode scanning already prevented many of those mistakes.

Average packing time increased during the first two weeks as workers learned the interface, then returned close to the previous level. Experienced workers sometimes felt the checklist repeated steps they already knew, while newer workers said it reduced uncertainty during unusual orders.

The study also found an implementation issue. Some workers clicked through every item at the end of packing instead of confirming steps as they were completed. That behaviour weakened the checklist as a real-time control even though the digital record appeared complete.

Managers responded by simplifying repetitive items and moving critical confirmations closer to the relevant packing stage. They did not add a rule requiring a supervisor to watch every order because that would have changed the workflow substantially. The comparison was not perfectly controlled. Teams worked on different mixes of orders, although researchers adjusted results for order complexity. Error reporting could also improve simply because the new system made certain mistakes easier to detect.

The warehouse plans a longer trial using randomly rotated team assignments and periodic observation of how workers actually interact with the checklist. Researchers also want to measure rework cost rather than error count alone, because different mistakes have very different consequences. The current evidence suggests that a well-timed checklist can reduce omissions in a complex process, but its value depends on how closely recorded confirmations match real actions.

Researchers will also compare error severity across the two groups. Missing a decorative insert and missing a temperature pack both count as one error in a simple total, but their operational consequences are very different. A cost-weighted measure may therefore show a larger or smaller benefit than the raw error count. The team will also examine whether checklist fatigue develops as experienced workers become familiar with repeated prompts over longer periods.

A secondary analysis separated first-time errors from repeated errors by the same worker. The checklist teams showed fewer repeated omission patterns, suggesting that visible prompts may have helped workers notice steps they had previously forgotten. Researchers caution that this finding is exploratory because the trial was not designed primarily to measure learning over time and workers changed assignments during busy periods.`,
 questions:[
 q("W07-Q1","RS-F01","medium","Which errors declined most clearly in checklist teams?","Missed labels and temperature packs",["Barcode-selection errors only","Every possible error equally","Supplier invoicing errors"],"The largest observed improvement concerned packaging omissions that the checklist explicitly surfaced.","especially for missed labels and temperature packs"),
 q("W07-Q2","RS-F02","medium","What can be inferred from the small change in product-selection errors?","Barcode scanning was already controlling many selection mistakes",["The checklist caused more wrong products","Products were never scanned","Selection errors were not measured"],"The passage explains that both groups retained barcode scanning, leaving less room for the checklist to improve that error type.","barcode scanning already prevented"),
 q("W07-Q3","RS-F03","hard","Which summary is most accurate?","The checklist reduced some omissions, but effectiveness depends on real-time use rather than superficial confirmation",["The checklist eliminated all warehouse errors","Digital records always prove correct behaviour","Experienced workers received no benefit"],"The study shows gains alongside evidence that end-of-task clicking can make the record look complete without providing real-time control.","match real actions"),
 q("W07-Q4","RS-F04","hard","Which limitation could inflate the apparent error reduction?","The new system may make some mistakes easier to detect and record",["Teams used barcode scanners","The trial lasted ten weeks","The checklist had visible steps"],"If detection differs between systems, observed error rates may change partly because of measurement rather than true performance.","mistakes easier to detect"),
 q("W07-Q5","RS-F05","hard","Which claim is not justified?","Any digital checklist will reduce every type of warehouse error",["Omission errors declined","Learning initially increased packing time","Order mix differed across teams"],"The effect was concentrated in certain packaging omissions and depended on interface design and user behaviour.","Product-selection errors changed little"),
 q("W07-Q6","RS-F06","medium","Which is a directly reported finding?","Packing time returned close to its earlier level after the first two weeks",["Packing time kept rising for ten weeks","Every worker preferred the checklist","Rework cost was already measured"],"The study directly reports a short learning-period increase followed by a return near the previous packing time.","returned close to the previous level"),
 q("W07-Q7","RS-F07","hard","Which competing mechanism is explicitly identified?","Clicking through steps at the end can make records look complete without guiding work",["Barcode scans create labels automatically","Supervisors choose all products","Orders contain no special conditions"],"The passage identifies retrospective confirmation as a behaviour that weakens the checklist's intended mechanism.","clicked through every item at the end"),
 q("W07-Q8","RS-F08","medium","Which next step is best supported?","Randomly rotate teams and observe actual checklist use",["Remove barcode scanning","Judge only by worker preference","Require supervisors on every order"],"The proposed next phase addresses group differences and whether digital confirmations correspond to real-time actions.","randomly rotated team assignments")
 ]
},
{
 id:"ENG008-RS-T06",title:"Do Real-Time Bus Crowding Displays Change Boarding Choices?",genre:"transport-survey",
 text:`A city transit agency tested real-time crowding information on three bus routes. The mobile app showed each approaching bus as low, medium or high occupancy using automatic passenger-count data. Researchers wanted to know whether riders would wait for a later bus when the first one appeared crowded.

For six weeks, half of registered app users on the routes saw the crowding indicator and half saw the normal arrival-time screen. Boarding records were linked anonymously to app sessions when users had opted into research tracking.

Riders who saw a “high” crowding label were slightly more likely to let that bus pass when another bus was due within eight minutes. The effect was much smaller when the next bus was more than fifteen minutes away. This suggests that information matters most when travellers have a practical alternative.

The indicator also changed expectations. Survey respondents who saw the labels reported fewer surprises about crowded conditions, even when they boarded the first bus anyway. Satisfaction rose slightly among these users despite little change in average journey time. The system was imperfect. Passenger counts occasionally lagged after large groups boarded or left, so a bus could appear more or less crowded than it actually was. Researchers excluded sessions where the data feed had obvious faults, but smaller inaccuracies remained possible.

Another limitation is selection. Only app users who opted into tracking could be linked to individual boarding choices. Riders who use cash, do not carry smartphones or ignore the app may respond differently. The agency will next test platform displays at major stops so non-app users receive the same information. It will also compare whether crowding labels redistribute passengers enough to make loads more even across closely spaced buses.

Researchers caution against interpreting the pilot as evidence that information creates capacity. If every bus is crowded, a label cannot produce an empty seat. The value of the system lies in helping riders use existing alternatives more effectively when those alternatives are actually available.

The next analysis will also separate riders making discretionary trips from those travelling to fixed-time work or appointments. A traveller with a flexible arrival time may respond to a crowding warning differently from someone who cannot risk being late. Researchers will compare route frequency, trip purpose and waiting tolerance so that a small average effect does not hide much larger behavioural differences between groups with different constraints.

The agency also compared stops with different service frequencies. At high-frequency stops, riders responded more strongly to crowding information because another bus was usually close behind. At low-frequency stops, the same label changed expectations but rarely changed boarding. This supports the idea that information and service design interact: a useful signal has more behavioural value when the network offers a realistic alternative.`,
 questions:[
 q("T06-Q1","RS-F01","medium","When were riders most likely to skip a highly crowded bus?","When another bus was due within eight minutes",["When the next bus was over thirty minutes away","Only when the route was empty","Whenever the app was closed"],"The behavioural effect was strongest when waiting for the next bus imposed only a short additional delay.","another bus was due within eight minutes"),
 q("T06-Q2","RS-F02","medium","What can be inferred from the smaller effect with long waits?","Information changes behaviour less when travellers lack a practical alternative",["Crowding labels become more accurate with longer waits","Riders prefer long delays","Arrival time no longer matters"],"The passage explicitly links response strength to whether a realistic next option exists.","practical alternative"),
 q("T06-Q3","RS-F03","hard","Which summary is most accurate?","Crowding information modestly changed choices and expectations when alternatives were available, but did not add transport capacity",["The app eliminated crowded buses","Every rider waited for a later bus","Journey times fell sharply"],"The study finds small behavioural and satisfaction effects while clearly limiting the claim about capacity.","information creates capacity"),
 q("T06-Q4","RS-F04","hard","Which limitation most affects generalising the individual-choice result?","Only opted-in app users could be linked to boarding behaviour",["Buses had route numbers","The trial lasted six weeks","The app showed arrival times"],"Tracked users may differ from cash users, non-smartphone riders and people who do not use the app.","Only app users who opted into tracking"),
 q("T06-Q5","RS-F05","hard","Which claim is unjustified?","Crowding labels guarantee that riders can find a less crowded bus",["Some users experienced fewer surprises","Count data sometimes lagged","Effect size depended on next-bus timing"],"If all buses are crowded or alternatives are distant, information cannot guarantee a better option.","If every bus is crowded"),
 q("T06-Q6","RS-F06","medium","Which is a directly reported finding?","Satisfaction rose slightly among users who saw crowding labels",["Average journey time fell by half","All count errors were eliminated","Non-app users were already included"],"The survey directly reports a small satisfaction increase even though average journey time changed little.","Satisfaction rose slightly"),
 q("T06-Q7","RS-F07","hard","Which competing mechanism is explicitly identified?","Labels may improve expectations even when they do not change boarding behaviour",["The app adds extra buses","Riders stop checking arrival time","Drivers change routes automatically"],"Survey responses suggest reduced surprise itself can improve experience independently of changing which bus is boarded.","changed expectations"),
 q("T06-Q8","RS-F08","medium","Which next step is best supported?","Test stop displays and measure whether loads become more even across nearby buses",["Remove arrival-time information","Study only smartphone owners","Assume capacity has increased"],"The proposed follow-up broadens access and tests whether individual choices improve distribution across the service.","test platform displays")
 ]
},
{
 id:"ENG008-RS-S04",title:"Does a Fixed Wake Time Improve Sleep Regularity?",genre:"sleep-study",
 text:`A university sleep laboratory recruited 180 students who reported irregular sleep schedules. Researchers wanted to test whether keeping a consistent wake time would improve sleep regularity even if bedtime was not fixed. Participants were randomly assigned to two groups for four weeks. One group was asked to wake within the same thirty-minute window every day, including weekends. The comparison group received general sleep-health advice but no fixed schedule. Both groups wore wrist activity monitors and completed short morning diaries.

The fixed-wake group showed a larger reduction in day-to-day variation in wake time and a smaller improvement in bedtime regularity. Average sleep duration changed very little between groups. This suggests that participants often shifted bedtime gradually rather than simply sleeping less.

Self-reported daytime alertness improved modestly in the fixed-wake group, especially among students whose schedules had been most irregular at baseline. However, exam periods occurred during the final week, which may have affected sleep and alertness independently of the intervention.

Adherence was uneven. About one quarter of the fixed-wake group missed the target window on at least two weekend days. Students with late social events reported the most difficulty maintaining the schedule. Researchers also observed that the wrist monitors estimate sleep from movement and cannot identify every period of quiet wakefulness. Diaries helped provide context, but self-reports have their own biases.

A follow-up period will examine whether students maintain regular wake times after daily reminders stop. The researchers are particularly interested in whether regularity persists because a habit formed or disappears once external prompts are removed.

The study does not show that everyone should use the same wake time, nor does it prove that regularity alone improves every aspect of sleep. It tests a narrower question: whether anchoring one part of the daily schedule can make sleep timing more consistent in students who begin with irregular routines.

Researchers will also examine whether the intervention changes light exposure and meal timing, because waking at a consistent hour may indirectly shift other daily cues that influence sleep. The follow-up will compare weekday and weekend effects separately and record caffeine use, late-night study and social events. These measurements may help distinguish whether improved regularity comes from the wake-time rule itself or from broader changes in routine that occur after participants begin planning mornings more consistently.

Researchers examined whether the fixed wake-time group compensated by napping more often. Diary data showed a small increase in short afternoon naps during the first week, but the difference between groups narrowed later. The study did not determine whether naps helped adaptation or simply reflected temporary tiredness. Future analysis will compare nap timing, evening sleepiness and adherence to see whether the intervention changes the distribution of sleep across the day as well as night-time regularity.`,
 questions:[
 q("S04-Q1","RS-F01","medium","What changed most clearly in the fixed-wake group?","Day-to-day variation in wake time decreased",["Average sleep duration doubled","Every bedtime became identical","Weekend adherence was perfect"],"The largest direct change was a reduction in variation around the targeted wake-time window.","larger reduction in day-to-day variation"),
 q("S04-Q2","RS-F02","medium","What can be inferred from stable average sleep duration?","Participants often adjusted bedtime rather than simply losing sleep",["The wake-time rule had no effect","Bedtime was fixed by researchers","Monitors stopped recording duration"],"Regularity improved while average duration stayed similar, consistent with gradual bedtime adaptation.","shifted bedtime gradually"),
 q("S04-Q3","RS-F03","hard","Which summary is most accurate?","A consistent wake-time target improved sleep timing regularity modestly, with uneven adherence and uncertain persistence",["The intervention cured all sleep problems","Everyone should wake at the same clock time","Sleep duration increased substantially"],"The randomised study supports a narrow regularity effect while highlighting adherence, measurement and follow-up questions.","tests a narrower question"),
 q("S04-Q4","RS-F04","hard","Which factor complicates interpretation of the final-week alertness data?","Exam periods may have independently changed sleep and alertness",["Participants were not randomly assigned","No diaries were used","The study had no comparison group"],"Exams occurred during the final week and could influence the same outcomes researchers were measuring.","exam periods occurred"),
 q("S04-Q5","RS-F05","hard","Which claim is unjustified?","A fixed wake time improves every dimension of sleep for every person",["Wake-time regularity improved","Weekend adherence was difficult for some","Movement monitors have limits"],"The passage explicitly restricts the conclusion and does not claim universal improvement across all sleep outcomes.","does not prove that regularity alone improves every aspect"),
 q("S04-Q6","RS-F06","medium","Which is a directly reported finding?","Students with late social events had more difficulty following the schedule",["Every student maintained the target","Bedtime variation disappeared completely","The follow-up has already ended"],"The adherence section directly identifies late social events as a common difficulty.","reported the most difficulty"),
 q("S04-Q7","RS-F07","hard","Which measurement concern is explicitly identified?","Activity monitors may mistake quiet wakefulness for sleep",["Diaries measure brain waves","Random assignment creates bias","Wake time cannot be recorded"],"The passage states that movement-based monitors cannot identify every period when a person is awake but still.","quiet wakefulness"),
 q("S04-Q8","RS-F08","medium","Which next step is best supported?","Check whether regularity persists after reminders stop",["Replace random assignment with volunteers","Measure only sleep duration","Require identical bedtimes"],"The proposed follow-up directly tests whether the observed schedule becomes a durable habit rather than reminder-dependent behaviour.","after daily reminders stop")
 ]
},
{
 id:"ENG008-RS-C05",title:"How Shoppers Interpret Unit-Price Labels",genre:"consumer-survey",
 text:`A consumer research group studied whether clearer unit-price labels help shoppers compare package sizes. In many stores, shelf tags show both the total price and a smaller price per kilogram or litre, but the unit information is often difficult to notice.

Researchers created a simulated grocery aisle with twenty common products. Four hundred adults were randomly assigned to see either the standard shelf tag or a redesigned tag that displayed the unit price in larger type directly beneath the total price.

Participants completed twelve comparison tasks. They were asked which of two packages offered the lower unit cost, not which package had the lower total price. Accuracy was higher in the redesigned-label group, especially when packages differed greatly in size.

The benefit was smaller for participants who already reported using unit prices frequently. Their baseline accuracy was relatively high even with the standard labels. The largest gains appeared among shoppers who said they usually compared only total prices. Speed also changed. The redesigned group answered comparison questions somewhat faster, although researchers cautioned that a simulated aisle lacks the distractions and time pressure of real shopping.

After the tasks, participants rated both label formats. Most preferred the redesigned version, but some said the larger unit price made the shelf look visually crowded. This creates a design trade-off because stores also need space for promotions, loyalty prices and legally required information.

The study did not examine whether shoppers would actually buy different products or spend less money over time. Correctly identifying the lower unit price is only one step in a purchase decision; quality, brand preference and household needs still matter. Researchers plan an in-store trial using anonymised sales data and brief exit surveys. They will test whether clearer unit-price presentation changes real comparisons without confusing shoppers about the amount they pay at checkout.

The in-store phase will also test products sold in different units, such as price per 100 grams, per kilogram and per litre. Researchers want to know whether a larger label helps only when the comparison unit is already familiar or whether standardising the displayed unit produces an additional benefit. They will also track whether shoppers notice temporary promotions that make the lower total price differ from the lower unit price, since those situations require more careful interpretation. Researchers will record whether shoppers actually use the unit comparison before choosing.

Researchers also tested whether the redesigned labels created mistakes when shoppers compared products sold in different units. A small subset of tasks deliberately mixed price-per-100-grams and price-per-kilogram displays. Accuracy fell in both groups, showing that visual prominence cannot compensate for inconsistent units. The team therefore recommends that any redesign standardise the comparison unit within a product category before increasing font size or changing colour hierarchy.`,
 questions:[
 q("C05-Q1","RS-F01","medium","Which group was more accurate at unit-price comparisons?","Participants who saw the redesigned labels",["Only participants seeing standard labels","Both groups had identical accuracy","Participants who saw no prices"],"Random assignment produced higher comparison accuracy when unit price was made more visually prominent.","Accuracy was higher in the redesigned-label group"),
 q("C05-Q2","RS-F02","medium","Why were gains smaller among frequent unit-price users?","They already performed relatively well with standard labels",["They ignored every shelf tag","They were not randomly assigned","Their packages were smaller"],"Higher baseline skill left less room for the redesigned display to improve comparison accuracy.","baseline accuracy was relatively high"),
 q("C05-Q3","RS-F03","hard","Which summary is most accurate?","Prominent unit prices improved simulated comparison accuracy, but real purchase effects remain untested",["Redesigned labels proved shoppers spend less","Unit pricing replaces brand preference","Standard labels produced no correct answers"],"The experiment supports a task-performance effect while explicitly limiting claims about real purchases and spending.","did not examine whether shoppers would actually buy different products"),
 q("C05-Q4","RS-F04","hard","Which limitation most affects real-world generalisation?","The simulated aisle lacks normal shopping distractions and consequences",["Participants were randomly assigned","Both prices were visible","The sample included adults"],"Performance in a controlled comparison task may not match behaviour in a busy store with many competing considerations.","simulated aisle lacks the distractions"),
 q("C05-Q5","RS-F05","hard","Which claim is unjustified?","Clearer unit labels necessarily cause shoppers to spend less money",["Comparison accuracy improved","Some users found the design crowded","Brand preferences can still matter"],"The study measures comparison performance, not long-term spending or actual purchasing decisions.","spend less money over time"),
 q("C05-Q6","RS-F06","medium","Which is a directly reported finding?","Most participants preferred the redesigned label",["Every participant preferred it","Sales changed during the experiment","Loyalty prices were removed"],"The post-task rating directly showed a majority preference for the larger unit-price display.","Most preferred the redesigned version"),
 q("C05-Q7","RS-F07","hard","Which competing consideration is explicitly identified?","Making unit prices larger uses shelf space needed for other information",["Unit prices cannot be calculated","Stores do not display total prices","Package size never matters"],"The passage notes a visual-space trade-off with promotions, loyalty pricing and required information.","stores also need space"),
 q("C05-Q8","RS-F08","medium","Which next step is best supported?","Run an in-store trial using real sales behaviour and exit surveys",["Remove unit prices entirely","Measure only stated preference","Assume simulated choices equal purchases"],"The planned field trial directly tests whether the lab-style accuracy result changes actual shopping behaviour.","in-store trial")
 ]
},
{
 id:"ENG008-RS-E06",title:"Do Reflective Schoolyard Surfaces Reduce Heat Exposure?",genre:"environment-study",
 text:`Researchers studied whether a light-coloured reflective coating could reduce afternoon heat on paved schoolyards. Four schools scheduled resurfacing work during the same summer. Two used the reflective coating and two used conventional dark material. Temperature sensors were installed at similar locations in each yard and recorded surface and air temperature every five minutes for six weeks. Researchers also measured shade and noted days when irrigation, sports events or maintenance changed normal use.

On clear afternoons, coated surfaces were substantially cooler than conventional dark surfaces. The difference in air temperature one metre above the ground was smaller. This distinction matters because surface temperature affects contact heat and radiant exposure, while air temperature better represents only one part of what people experience.

Students and staff completed short comfort surveys during lunch periods. Reports of the yard feeling “very hot” declined at the coated schools, but the difference was strongest in unshaded sections. Shaded seating remained more comfortable than either type of open pavement.

The study was not a randomised trial. Schools chose resurfacing material before researchers joined the project, and the four sites differed in tree cover and building layout. Statistical adjustment reduced some differences but cannot remove every site-level factor.

The coating also had a practical drawback: glare was higher around midday when the sun angle was strong. One school added shaded waiting areas near a bright section used for dismissal. Researchers will revisit the yards after a year because dirt and wear may reduce reflectivity. They will also compare maintenance cost and measure whether students change where they gather during hot periods.

The findings support a limited conclusion. Reflective pavement can lower exposed surface temperature and may improve perceived comfort, but it does not replace shade and should be evaluated alongside glare, durability and site design.

A later phase will place wearable temperature and light sensors on volunteer staff walking fixed routes across the yards. The researchers want to compare stationary surface readings with actual short-term exposure during movement. They will also examine whether the coating changes evening heat release after sunset, because a surface that stays cooler in the afternoon may behave differently later in the day. These additions should help separate material performance from the broader question of how people experience the schoolyard. Weather conditions will be logged throughout.

Researchers supplemented the fixed sensors with thermal images on selected afternoons. The images showed that benches, metal play equipment and shaded pavement could have very different surface temperatures even within the same schoolyard. This reinforced the decision not to describe a whole site using one pavement reading. The team plans to map where children actually spend time so exposure estimates reflect both physical temperature and patterns of use rather than assuming equal contact with every surface.`,
 questions:[
 q("E06-Q1","RS-F01","medium","Which temperature effect was largest?","The reduction in paved surface temperature",["The reduction in indoor temperature","The reduction in air temperature far above the school","No temperature changed"],"The coated pavement showed a much stronger change in surface temperature than in air temperature one metre above it.","coated surfaces were substantially cooler"),
 q("E06-Q2","RS-F02","medium","What can be inferred from the comfort results in shaded areas?","Shade remained an important heat-control measure even with reflective pavement",["Reflective coating made shade unnecessary","Shade increased surface heat","Students avoided all shaded seating"],"The passage says shaded seating was more comfortable than either open pavement type.","Shaded seating remained more comfortable"),
 q("E06-Q3","RS-F03","hard","Which summary is most accurate?","Reflective pavement reduced exposed surface heat, but benefits were partial and accompanied by glare and site-specific limits",["The coating solved all outdoor heat","Air temperature fell dramatically everywhere","Conventional surfaces were cooler"],"The study reports meaningful surface cooling while maintaining clear limits related to shade, design and durability.","does not replace shade"),
 q("E06-Q4","RS-F04","hard","Which limitation most weakens a causal comparison between surface types?","Schools were not randomly assigned to coating type",["Sensors recorded every five minutes","Comfort surveys were collected","Clear afternoons were analysed"],"Pre-existing differences in tree cover and layout may be associated with both school choice and heat outcomes.","not a randomised trial"),
 q("E06-Q5","RS-F05","hard","Which claim is unjustified?","Reflective pavement alone is sufficient to make every schoolyard comfortable",["Surface temperature fell","Glare increased in some conditions","Shade still mattered"],"The passage explicitly argues that reflective material should complement rather than replace shade and broader site design.","does not replace shade"),
 q("E06-Q6","RS-F06","medium","Which is a directly reported finding?","Glare was higher around midday on coated surfaces",["The coating wore out within six weeks","Every school added new trees","Air temperature fell more than surface temperature"],"Researchers directly observed higher glare around midday and one school responded with added shade.","glare was higher around midday"),
 q("E06-Q7","RS-F07","hard","Which competing mechanism is explicitly identified?","Differences in tree cover and building layout could affect comfort independently of pavement type",["The coating creates more rainfall","Sensors reduce surface temperature","Students control the sun angle"],"Site characteristics varied across schools and may partly explain observed differences despite adjustment.","differed in tree cover and building layout"),
 q("E06-Q8","RS-F08","medium","Which next step is best supported?","Reassess reflectivity, wear and maintenance after longer use",["End temperature measurement permanently","Measure only colour preference","Assume coating performance never changes"],"The planned one-year follow-up directly addresses whether dirt, wear and maintenance alter the initial thermal benefit.","revisit the yards after a year")
 ]
},
{
 id:"ENG008-RS-D07",title:"Do Retrieval Quizzes Improve Long-Term Vocabulary Recall?",genre:"digital-learning-evaluation",
 text:`An online language course tested two review methods for newly introduced vocabulary. After a lesson, learners either completed a short retrieval quiz that asked them to produce the word from a definition or viewed the same word-definition pairs again for an equal amount of time.

Eight hundred learners were randomly assigned to one of the two review methods for four weeks. Both groups studied the same number of words and received the same initial lessons. On a test given ten minutes after review, performance was similar. On a delayed test one week later, the retrieval-practice group remembered more words on average. The difference was largest for words that learners had initially answered incorrectly but then corrected after feedback.

The quiz group reported slightly higher mental effort. Some learners also said that being asked to retrieve a word before feeling ready was frustrating. However, dropout rates did not differ meaningfully between groups.

Researchers examined whether the advantage came simply from extra feedback. The restudy group also saw the correct word for the same amount of time, while the quiz group received it after each response. This design reduced, but did not entirely eliminate, differences in attention caused by actively attempting an answer.

A limitation is that the experiment measured isolated vocabulary rather than sentence production or conversation. Remembering a word on a delayed test does not guarantee fluent use in context. The platform will next test retrieval practice inside short passages and speaking tasks. Researchers also want to vary the spacing between review and test to determine how long the advantage persists.

The current result supports a specific learning claim: attempting to retrieve recently studied vocabulary can strengthen later recall compared with simply seeing the same material again, even when immediate performance looks similar.

The next experiment will also vary feedback timing. One group will see the correct answer immediately after each retrieval attempt, while another will receive feedback after a short block of questions. Researchers want to determine whether delayed feedback changes retention or frustration. They will also classify words by frequency and similarity to known vocabulary, since retrieval may help unfamiliar terms differently from words that resemble forms learners already know. This should show whether the average advantage is broad or concentrated in particular item types. Researchers will also compare response confidence.

Researchers also separated words by initial difficulty. Retrieval practice produced the largest delayed advantage for medium-difficulty items, while very easy words were remembered well in both groups and very difficult words often remained weak even after feedback. This pattern suggests that the benefit is not uniform across material. The next study will adjust item difficulty and number of retrieval attempts to test whether extra practice helps the hardest words or mainly adds frustration without durable gain.`,
 questions:[
 q("D07-Q1","RS-F01","medium","Where did the clearest performance difference appear?","On the delayed test one week later",["On the immediate ten-minute test only","Before any review occurred","In dropout rate"],"Immediate performance was similar, while delayed recall favoured the retrieval-practice group.","delayed test one week later"),
 q("D07-Q2","RS-F02","medium","What can be inferred from similar immediate scores?","A learning benefit may appear later even when short-term performance looks similar",["The methods are identical in every respect","Delayed testing is unnecessary","Retrieval caused lower recall"],"The delayed divergence shows that immediate success does not fully capture retention.","immediate performance looks similar"),
 q("D07-Q3","RS-F03","hard","Which summary is most accurate?","Retrieval practice improved delayed vocabulary recall, though transfer to real language use remains untested",["Retrieval made conversation fluent","Restudy produced no learning","The quiz reduced all frustration"],"The experiment supports delayed recall of isolated words but explicitly limits claims about contextual use.","does not guarantee fluent use in context"),
 q("D07-Q4","RS-F04","hard","Which limitation most restricts the educational conclusion?","The outcome was isolated-word recall rather than contextual language use",["Participants were randomly assigned","Both groups studied equal word counts","Feedback was provided"],"The task may not represent sentence production, conversation or other broader language skills.","measured isolated vocabulary"),
 q("D07-Q5","RS-F05","hard","Which claim is unjustified?","Retrieval quizzes guarantee fluent vocabulary use in conversation",["Quiz learners reported more effort","Delayed recall improved","Dropout rates were similar"],"The study did not test fluent conversation and explicitly warns against that inference.","does not guarantee fluent use in context"),
 q("D07-Q6","RS-F06","medium","Which is a directly reported finding?","Dropout rates were similar between groups",["The quiz group had no frustration","Immediate recall was much higher with quizzes","Every learner corrected every error"],"The study directly reports no meaningful dropout difference despite higher effort and some frustration.","dropout rates did not differ meaningfully"),
 q("D07-Q7","RS-F07","hard","Which alternative explanation did researchers try to reduce?","That the quiz advantage came only from seeing corrective feedback",["That learners studied different numbers of words","That one group had longer lessons","That delayed tests were easier"],"Both groups saw correct word-definition information for equal time, limiting a simple feedback-exposure explanation.","restudy group also saw the correct word"),
 q("D07-Q8","RS-F08","medium","Which next step is best supported?","Test retrieval practice in passages and speaking tasks",["Stop delayed testing","Use only isolated words forever","Remove feedback"],"The proposed follow-up directly addresses whether the delayed recall benefit transfers to more realistic language use.","inside short passages and speaking tasks")
 ]
},
{
 id:"ENG008-RS-D08",title:"Can Progress Forecasts Improve Course Completion?",genre:"digital-learning-evaluation",
 text:`A professional-learning platform tested a progress forecast designed to help learners plan a twelve-week online course. The normal dashboard showed percentage completed. The experimental dashboard also estimated how many study sessions per week a learner would need to finish by the chosen target date.

The forecast used recent study pace and remaining lesson length. It updated weekly rather than after every session so that short-term fluctuations did not cause the recommendation to change constantly. Six thousand learners who had completed at least two weeks of the course were randomly assigned to the standard or forecast dashboard. After eight weeks, the forecast group completed slightly more lessons and was more likely to remain active on the platform.

The effect was concentrated among learners whose previous pace was close to what they needed. Learners who were far behind often ignored the forecast or changed their target date. Interviews suggested that an achievable recommendation felt useful, while a very large required increase could feel discouraging.

Researchers also found a risk of false precision. The forecast sometimes underestimated workload for lessons containing long projects because historical average lesson time did not capture those assignments well. The platform added a range rather than a single predicted number of sessions.

Completion by the original target date has not yet been measured because many participants are still within the course period. For that reason, the study cannot yet claim that the forecast improves final completion. Another limitation is that only learners who had already stayed active for two weeks entered the experiment. The feature may have different effects on people who disengage immediately after enrolment.

The next phase will begin at course registration and will test different wording for learners who are substantially behind schedule. Researchers want to know whether supportive planning options work better than simply displaying a demanding catch-up number. The pilot suggests that progress forecasts can influence short-term engagement, but usefulness depends on realistic estimates and on presenting a recommendation that learners can act on rather than merely observe.

Researchers will additionally test whether learners respond differently to forecasts framed as a minimum weekly pace, a range of acceptable study plans or a calendar with suggested session dates. The underlying workload estimate can be identical while the presentation changes how demanding the plan feels. The team will also measure target-date changes explicitly, because moving a deadline may represent sensible replanning rather than disengagement. That distinction is important when interpreting whether a forecast truly improves progress.

Researchers inspected how often users opened the forecast details rather than viewing only the headline recommendation. Learners who opened the explanation were more likely to adjust their weekly plan, but this association is not causal because more motivated users may be more likely to inspect any planning tool. The next experiment will vary whether the explanation is shown automatically so researchers can separate motivation from the effect of additional guidance.`,
 questions:[
 q("D08-Q1","RS-F01","medium","What did the experimental dashboard add?","An estimate of study sessions needed per week to meet a target date",["A guaranteed final grade","A live tutor in every lesson","A fixed daily exam"],"The forecast translated remaining work and recent pace into a planning estimate for weekly study sessions.","sessions per week"),
 q("D08-Q2","RS-F02","medium","What can be inferred from the strongest effect among near-target learners?","Recommendations may work better when the required change feels achievable",["Forecasts help only learners who are failing","Large catch-up targets always motivate users","Target dates have no effect"],"Interviews directly connect perceived achievability with usefulness and very large required increases with discouragement.","achievable recommendation felt useful"),
 q("D08-Q3","RS-F03","hard","Which summary is most accurate?","Forecasts modestly improved short-term engagement, but final completion effects and estimate accuracy remain uncertain",["Forecasts guaranteed course completion","The standard dashboard caused dropout","Every learner followed the suggested pace"],"The pilot shows increased activity while explicitly withholding a conclusion about final target-date completion.","cannot yet claim that the forecast improves final completion"),
 q("D08-Q4","RS-F04","hard","Which limitation restricts generalisation to all enrolled learners?","Participants had already remained active for at least two weeks",["The sample was randomly assigned","The forecast updated weekly","Lessons had different lengths"],"Early disengagers were excluded, so the observed effect may not represent users who leave soon after enrolment.","only learners who had already stayed active"),
 q("D08-Q5","RS-F05","hard","Which claim is unjustified?","The forecast has already been proven to increase completion by the original deadline",["Lesson completion increased slightly","Some far-behind learners changed targets","Project lessons reduced forecast accuracy"],"Many learners have not yet reached their target date, so final completion cannot yet be evaluated.","has not yet been measured"),
 q("D08-Q6","RS-F06","medium","Which is a directly reported finding?","The forecast group was more likely to remain active after eight weeks",["Every learner finished the course","Forecast estimates were always exact","Far-behind learners studied the most"],"The experiment directly reports a modest increase in retained activity in the forecast-dashboard group.","more likely to remain active"),
 q("D08-Q7","RS-F07","hard","Which design problem is explicitly identified?","Average lesson time can understate workload for project-heavy lessons",["Weekly updates always confuse learners","Percentage complete cannot be calculated","Target dates are legally fixed"],"Long projects were not well represented by historical average lesson duration, creating false precision in the forecast.","underestimated workload for lessons containing long projects"),
 q("D08-Q8","RS-F08","medium","Which next step is best supported?","Test the feature from registration and improve guidance for learners far behind schedule",["Remove uncertainty ranges","Study only near-target learners","Assume final completion will improve"],"The next phase directly addresses both the excluded early learners and the weak response to intimidating catch-up estimates.","begin at course registration")
 ]
}
] as const;
