import type { HisCp002Spec } from "./his-cp002-review-specs-v1";

export const HIS_CP002_HARD_SPECS_V1:readonly HisCp002Spec[]=[
  [10,"Consider the statements: 1. Early Vedic life was mainly pastoral. 2. Agriculture became more important in the Later Vedic period. 3. Iron tools supported agricultural expansion. Which are correct?","1, 2 and 3",["1 and 2 only","2 and 3 only","1 and 3 only"],["ved-early-pastoral","ved-later-agriculture","ved-iron-impact"]],
  [10,"Which option best describes a social change from Early to Later Vedic times?","A more flexible occupation pattern gave way to clearer varna divisions and stronger gotra rules",["Varna divisions disappeared and gotra lost importance","Occupation became less linked to birth and same-gotra marriage became common","The family disappeared as a social unit and only the jana remained"],["ved-early-occupation","ved-four-varnas","ved-gotra"]],
  [10,"Which option correctly contrasts Early and Later Vedic polity?","Early chiefs were checked by assemblies; later chiefship became more hereditary",["Early Vedic polity had a large bureaucracy; Later Vedic polity had none","Early Vedic chiefs were always hereditary; Later Vedic chiefs were always elected","Assemblies became stronger as Later Vedic kingship grew"],["ved-sabha-samiti","ved-later-hereditary"]],
  [10,"Which option correctly shows the broad economic change from Early to Later Vedic times?","Pastoral dominance → stronger agricultural economy",["Agricultural dominance → cattle-only economy","Coin economy → barter economy","Urban sea trade → hunting economy"],["ved-early-pastoral","ved-later-agriculture"]],
  [10,"Which set is correctly matched?","Indra — war and rain; Varuna — rita; Pushan — roads and cattle",["Indra — rita; Varuna — roads and cattle; Pushan — war and rain","Indra — roads and cattle; Varuna — war and rain; Pushan — rita","Indra — fire intermediary; Varuna — singing; Pushan — royal sacrifice"],["ved-indra","ved-varuna","ved-pushan"]],
  [10,"Which option correctly matches the Vedic texts with their main features?","Samaveda — singing; Yajurveda — rituals; Upanishads — philosophical ideas",["Samaveda — rituals; Yajurveda — spells; Upanishads — battle hymns","Samaveda — philosophical ideas; Yajurveda — singing; Upanishads — rituals","Samaveda — spells; Yajurveda — forest treatises; Upanishads — cattle lists"],["ved-samaveda","ved-yajurveda","ved-upanishads"]],
];
