import { DM_001_CHECKPOINT_IDS, DM_001_QL_IDS } from "./types.ts";
import { DM_001_QL_REGISTRY } from "./ql-registry.ts";

export const DM_001_MANIFEST = Object.freeze({
  chapterId: "DM-001",
  subjectCode: "REAS-DCS",
  title: "Decision Making / Eligibility",
  family: "FAMILY_C_LOGIC_AND_DEDUCTION",
  examinations: ["SSC", "BANKING", "PUNJAB_STATE", "CLERICAL_ADMINISTRATIVE"] as const,
  locales: ["en-IN", "hi-IN", "pa-IN"] as const,
  blueprintCheckpointIds: ["DM-001", "DM-002", "DM-003", "DM-004", "DM-005", "DM-006", "DM-007", "DM-008", "DM-009", "DM-010", "DM-011", "DM-012", "DM-013", "DM-014", "DM-015", "DM-016", "DM-017", "DM-018", "DM-019", "DM-020"] as const,
  checkpointIds: DM_001_CHECKPOINT_IDS,
  semanticQlCount: DM_001_QL_IDS.length,
  qlIds: DM_001_QL_IDS,
  qlRegistry: DM_001_QL_REGISTRY,
  checkpoints: [
    { checkpointId: "DM-CP-001", blueprintCheckpointId: "DM-001", purpose: "Basic direct decisions over person or product fields with three or four conditions", scenarioTarget: 30 },
    { checkpointId: "DM-CP-002", blueprintCheckpointId: "DM-002", purpose: "Five to seven simultaneous eligibility or quality conditions and boundary checks", scenarioTarget: 30 },
    { checkpointId: "DM-CP-003", blueprintCheckpointId: "DM-003", purpose: "Ordered conditional exceptions, tolerances and referral outcomes", scenarioTarget: 30 },
    { checkpointId: "DM-CP-004", blueprintCheckpointId: "DM-004", purpose: "Selection, rejection, authority referral and insufficient-data decisions", scenarioTarget: 25 },
    { checkpointId: "DM-CP-005", blueprintCheckpointId: "DM-005", purpose: "Age on a specified date, qualification level and relevant experience", scenarioTarget: 25 },
    { checkpointId: "DM-CP-006", blueprintCheckpointId: "DM-006", purpose: "Recruitment, admission, training, apprenticeship and scholarship eligibility", scenarioTarget: 25 },
    { checkpointId: "DM-CP-007", blueprintCheckpointId: "DM-007", purpose: "Fictional loan, grant and benefit rules with income, residence, repayment and collateral conditions", scenarioTarget: 25 },
    { checkpointId: "DM-CP-008", blueprintCheckpointId: "DM-008", purpose: "Multiple score or quality cut-offs with boundary values", scenarioTarget: 30 },
    { checkpointId: "DM-CP-009", blueprintCheckpointId: "DM-009", purpose: "Dependent relaxations or quality tolerances with explicit precedence", scenarioTarget: 30 },
    { checkpointId: "DM-CP-010", blueprintCheckpointId: "DM-010", purpose: "Limited allocation of applicants or qualifying lots through a structured priority order and tie-break", scenarioTarget: 30 },
    { checkpointId: "DM-CP-011", blueprintCheckpointId: "DM-011", purpose: "Administrative action through verification, procedure, authorized escalation and documentation", scenarioTarget: 75 },
    { checkpointId: "DM-CP-012", blueprintCheckpointId: "DM-012", purpose: "Best immediate action with explicit first-step sequencing", scenarioTarget: 75 },
    { checkpointId: "DM-CP-013", blueprintCheckpointId: "DM-013", purpose: "Complaint and grievance registration, verification, correction and impartial escalation", scenarioTarget: 75 },
    { checkpointId: "DM-CP-014", blueprintCheckpointId: "DM-014", purpose: "Neutral workplace decisions covering priorities, records, procedure and confidentiality", scenarioTarget: 75 },
    { checkpointId: "DM-CP-015", blueprintCheckpointId: "DM-015", purpose: "Fair public-service handling of applications, queues, records and urgent requests", scenarioTarget: 75 },
    { checkpointId: "DM-CP-016", blueprintCheckpointId: "DM-016", purpose: "Explicit emergency, deadline and routine resource-allocation priorities", scenarioTarget: 75 },
    { checkpointId: "DM-CP-017", blueprintCheckpointId: "DM-017", purpose: "Conflicting preference rules resolved only through an explicit precedence and tie-break chain", scenarioTarget: 25 },
    { checkpointId: "DM-CP-018", blueprintCheckpointId: "DM-018", purpose: "Three-valued decisions that distinguish material missing information from already decisive failure", scenarioTarget: 25 },
    { checkpointId: "DM-CP-019", blueprintCheckpointId: "DM-019", purpose: "Computed decisions over four-to-six profiles under one common rule block", scenarioTarget: 25 },
    { checkpointId: "DM-CP-020", blueprintCheckpointId: "DM-020", purpose: "Five-question mixed sets combining eligibility, exceptions, referral, relaxation and incomplete data", scenarioTarget: 25 },
  ] as const,
  qlAllocation: {
    policy: "NEED_BASED",
    qlIdPermanence: "PERMANENT_AFTER_MERGE",
    qlSequence: "CHAPTER_WIDE_CONTINUOUS",
    implementedRange: "DM-QL-001..DM-QL-060",
    waveOneQlCount: 15,
    waveTwoQlCount: 15,
    waveThreeQlCount: 18,
    waveFourQlCount: 12,
    laterWaveQlAllocation: "CHAPTER_COMPLETE_NO_UNALLOCATED_QLS",
  },
  runtime: {
    deterministic: true,
    structuralRuleRepresentation: true,
    independentSolverRequired: true,
    conditionByConditionExplanation: true,
    fourUniqueOptions: true,
    supportedLanguages: ["en", "hi", "pa"] as const,
    baseRuleScenarioAuthoritiesPerCheckpoint: 25,
    structuredProductScenarioAuthorities: 30,
    structuredProductCheckpoints: ["DM-CP-001", "DM-CP-002", "DM-CP-003", "DM-CP-008", "DM-CP-009", "DM-CP-010"] as const,
    situationalScenarioAuthoritiesPerCheckpoint: 75,
    advancedScenarioAuthoritiesPerCheckpoint: 25,
    freeFormScenarioGenerationAllowed: false,
  },
  lifecycle: {
    status: "CONTENT_DEEP_AUDIT_CLOSED_REVIEW_ONLY",
    questionStudioRegisteredReviewOnly: true,
    questionBankWritable: false,
    testEligible: false,
    mockEligible: false,
    publicEligible: false,
    automaticPublication: false,
    finalDeepAuditAuthority: "DM-001-FINAL-DEEP-AUDIT-CLOSURE-20261003.md",
    controlledNoveltyAuthority: "DM-001-CONTROLLED-NOVELTY-AUDIT-CLOSURE-20261003.md",
  },
  boundary: {
    recruitmentAdmissionEligibilityOwnedBy: "REAS-DCS",
    courseOfActionJudgmentOwnedBy: "REAS-DCS_DM-011_TO_DM-016",
    subjectiveMoralityOrPersonalityTestsExcluded: true,
    currentGovernmentSchemeFactsExcluded: true,
    downstreamReleaseAndActivation: "QUESTION_STUDIO_GOVERNANCE_ONLY",
  },
});