import { DM_001_CHECKPOINT_IDS, DM_001_QL_IDS, type DmCheckpointId, type DmQlId } from "./types.ts";

export type DmQlEntry = Readonly<{
  qlId: DmQlId;
  checkpointId: DmCheckpointId;
  ruleFamily: string;
  solveMode: string;
  answerType: "DECISION_OUTCOME" | "RANKED_CANDIDATE_SET" | "SITUATIONAL_ACTION" | "DECISION_SET_RESULT";
  renderer: "RULES_AND_CANDIDATE_PROFILE" | "PRIORITY_ORDER_AND_CANDIDATE_POOL" | "SITUATION_AND_ACTIONS" | "RULES_AND_MULTI_PERSON_SET";
  localeMode: "TRANSLATABLE";
  status: "IMPLEMENTED_REVIEW_ONLY";
}>;

const QL_DEFINITIONS = [
  ["BASIC_THREE_FIELD_DIRECT_RULE", "CONJUNCTIVE_RULE_EVALUATION"],
  ["BASIC_MIXED_NUMERIC_STATUS_RULE", "CONJUNCTIVE_RULE_EVALUATION"],
  ["BASIC_BOUNDARY_AND_STATUS_RULE", "CONJUNCTIVE_RULE_EVALUATION"],
  ["FIVE_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SIX_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SEVEN_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SINGLE_CONDITIONAL_EXCEPTION_OR_TOLERANCE", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["DEPENDENT_THRESHOLD_EXCEPTION", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["MULTI_FIELD_EXCEPTION", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["DOCUMENT_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["AGE_BASED_DIRECTOR_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["BORDERLINE_COMMITTEE_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["AGE_ON_CUTOFF_DATE", "DATE_DERIVED_AGE_EVALUATION"],
  ["QUALIFICATION_AND_RELEVANT_EXPERIENCE", "MULTI_FIELD_PROFILE_EVALUATION"],
  ["AGE_QUALIFICATION_EXPERIENCE_COMBINATION", "MULTI_FIELD_PROFILE_EVALUATION"],
  ["RECRUITMENT_ADMISSION_TRAINING_ELIGIBILITY", "CONJUNCTIVE_RULE_EVALUATION"],
  ["ADMISSION_MARKS_RESIDENCE_CREDENTIAL", "CONJUNCTIVE_RULE_EVALUATION"],
  ["APPRENTICESHIP_EXPERIENCE_QUALIFICATION", "CONJUNCTIVE_RULE_EVALUATION"],
  ["FICTIONAL_GRANT_INCOME_RESIDENCE_EMPLOYMENT", "BENEFIT_RULE_EVALUATION"],
  ["FICTIONAL_LOAN_REPAYMENT_COLLATERAL_CATEGORY", "BENEFIT_RULE_EVALUATION"],
  ["FICTIONAL_BENEFIT_INCOME_AGE_CATEGORY", "BENEFIT_RULE_EVALUATION"],
  ["TWO_FIELD_MINIMUM_OR_MAXIMUM_CUTOFFS", "MULTI_CUTOFF_EVALUATION"],
  ["THREE_FIELD_MIXED_CUTOFFS", "MULTI_CUTOFF_EVALUATION"],
  ["MULTI_FIELD_QUALITY_OR_SCORE_CUTOFFS", "MULTI_CUTOFF_EVALUATION"],
  ["DEPENDENT_LIMIT_TOLERANCE", "DEPENDENT_RELAXATION_EVALUATION"],
  ["DEPENDENT_THRESHOLD_TOLERANCE", "DEPENDENT_RELAXATION_EVALUATION"],
  ["ORDERED_DEPENDENT_TOLERANCE_EVALUATION", "ORDERED_DEPENDENT_RELAXATION_EVALUATION"],
  ["RANKED_ALLOCATION_MULTI_CRITERIA", "EXPLICIT_PRIORITY_RANKING"],
  ["RANKED_ALLOCATION_SCORE_OR_QUALITY", "EXPLICIT_PRIORITY_RANKING"],
  ["RANKED_ALLOCATION_CUTOFF_AND_TIE_BREAK", "EXPLICIT_PRIORITY_RANKING"],
  ["ADMINISTRATIVE_VERIFY_THEN_PROCESS", "DEFENSIBLE_ACTION_ORDERING"],
  ["ADMINISTRATIVE_AUTHORIZED_ESCALATION", "DEFENSIBLE_ACTION_ORDERING"],
  ["ADMINISTRATIVE_DOCUMENT_AND_PROTECT", "DEFENSIBLE_ACTION_ORDERING"],
  ["IMMEDIATE_VERIFICATION", "FIRST_ACTION_SEQUENCE"],
  ["IMMEDIATE_SAFETY_OR_CONTAINMENT", "FIRST_ACTION_SEQUENCE"],
  ["IMMEDIATE_AUTHORIZED_CONTINUITY", "FIRST_ACTION_SEQUENCE"],
  ["GRIEVANCE_RECORD_AND_VERIFY", "GRIEVANCE_PROCEDURE"],
  ["GRIEVANCE_CORRECTION_AND_RESPONSE", "GRIEVANCE_PROCEDURE"],
  ["GRIEVANCE_IMPARTIAL_ESCALATION", "GRIEVANCE_PROCEDURE"],
  ["WORKPLACE_TASK_PRIORITY", "WORKPLACE_ACTION_ORDERING"],
  ["WORKPLACE_RECORD_OR_PROCEDURE", "WORKPLACE_ACTION_ORDERING"],
  ["WORKPLACE_CONFIDENTIALITY", "WORKPLACE_ACTION_ORDERING"],
  ["CITIZEN_APPLICATION_PROCEDURE", "PUBLIC_SERVICE_ACTION_ORDERING"],
  ["CITIZEN_FAIR_ACCESS", "PUBLIC_SERVICE_ACTION_ORDERING"],
  ["CITIZEN_RECORD_AND_PRIVACY", "PUBLIC_SERVICE_ACTION_ORDERING"],
  ["RESOURCE_EMERGENCY_PRIORITY", "EXPLICIT_RESOURCE_PRIORITY"],
  ["RESOURCE_DEADLINE_PRIORITY", "EXPLICIT_RESOURCE_PRIORITY"],
  ["RESOURCE_ROUTINE_DEFERMENT", "EXPLICIT_RESOURCE_PRIORITY"],
  ["CONFLICTING_PREFERENCES_PRECEDENCE", "EXPLICIT_PRIORITY_RANKING"],
  ["COMPLETE_TIE_BREAK_CHAIN", "EXPLICIT_PRIORITY_RANKING"],
  ["WAITLIST_PRECEDENCE", "EXPLICIT_PRIORITY_RANKING"],
  ["MATERIAL_MISSING_INFORMATION", "THREE_VALUED_RULE_EVALUATION"],
  ["DECISIVE_FAILURE_WITH_IRRELEVANT_MISSING_DATA", "THREE_VALUED_RULE_EVALUATION"],
  ["UNRESOLVED_EXCEPTION_INFORMATION", "THREE_VALUED_EXCEPTION_EVALUATION"],
  ["MULTI_PERSON_SELECTION_COUNT", "COMPUTED_DECISION_SET"],
  ["MULTI_PERSON_OUTCOME_IDENTIFICATION", "COMPUTED_DECISION_SET"],
  ["MULTI_PERSON_SAME_DECISION_PAIR", "COMPUTED_DECISION_SET"],
  ["MIXED_SET_CORE_AND_EXCEPTION_OUTCOMES", "COMPUTED_MIXED_DECISION_SET"],
  ["MIXED_SET_RELAXATION_AND_REFERRAL", "COMPUTED_MIXED_DECISION_SET"],
  ["MIXED_SET_INCOMPLETE_INFORMATION", "COMPUTED_MIXED_DECISION_SET"],
] as const;

export const DM_001_QL_REGISTRY: readonly DmQlEntry[] = Object.freeze(
  DM_001_QL_IDS.map((qlId, index) => Object.freeze({
    qlId,
    checkpointId: DM_001_CHECKPOINT_IDS[Math.floor(index / 3)]!,
    ruleFamily: QL_DEFINITIONS[index]![0],
    solveMode: QL_DEFINITIONS[index]![1],
    answerType: (index >= 54 ? "DECISION_SET_RESULT" : index >= 48 && index < 51 ? "RANKED_CANDIDATE_SET" : index >= 30 && index < 48 ? "SITUATIONAL_ACTION" : index >= 27 && index < 30 ? "RANKED_CANDIDATE_SET" : "DECISION_OUTCOME") as DmQlEntry["answerType"],
    renderer: (index >= 54 ? "RULES_AND_MULTI_PERSON_SET" : index >= 48 && index < 51 ? "PRIORITY_ORDER_AND_CANDIDATE_POOL" : index >= 30 && index < 48 ? "SITUATION_AND_ACTIONS" : index >= 27 && index < 30 ? "PRIORITY_ORDER_AND_CANDIDATE_POOL" : "RULES_AND_CANDIDATE_PROFILE") as DmQlEntry["renderer"],
    localeMode: "TRANSLATABLE" as const,
    status: "IMPLEMENTED_REVIEW_ONLY" as const,
  })),
);

export function assertContinuousDmQlIds(entries: readonly Pick<DmQlEntry, "qlId">[] = DM_001_QL_REGISTRY): void {
  const expected = DM_001_QL_IDS;
  const actual = entries.map((entry) => entry.qlId);
  if (actual.length !== expected.length || actual.some((id, index) => id !== expected[index])) {
    throw new Error("DM-001 QL IDs must be continuous and match the permanent chapter registry.");
  }
}

export function dmQlEntry(qlId: string): DmQlEntry {
  const entry = DM_001_QL_REGISTRY.find((candidate) => candidate.qlId === qlId);
  if (!entry) throw new Error("Unknown DM-001 QL: " + qlId);
  return entry;
}

export function dmQlIdsForCheckpoint(checkpointId: DmCheckpointId): readonly DmQlId[] {
  return DM_001_QL_REGISTRY.filter((entry) => entry.checkpointId === checkpointId).map((entry) => entry.qlId);
}