import { DM_001_CHECKPOINT_IDS, DM_001_QL_IDS, type DmCheckpointId, type DmQlId } from "./types.ts";

export type DmQlEntry = Readonly<{
  qlId: DmQlId;
  checkpointId: DmCheckpointId;
  ruleFamily: string;
  solveMode: string;
  answerType: "DECISION_OUTCOME" | "RANKED_CANDIDATE_SET";
  renderer: "RULES_AND_CANDIDATE_PROFILE" | "PRIORITY_ORDER_AND_CANDIDATE_POOL";
  localeMode: "TRANSLATABLE";
  status: "IMPLEMENTED_REVIEW_ONLY";
}>;

const QL_DEFINITIONS = [
  ["BASIC_AGE_QUALIFICATION_REGISTRATION", "CONJUNCTIVE_RULE_EVALUATION"],
  ["BASIC_MARKS_RESIDENCE_CREDENTIAL", "CONJUNCTIVE_RULE_EVALUATION"],
  ["BASIC_AGE_EXPERIENCE_CERTIFICATE", "CONJUNCTIVE_RULE_EVALUATION"],
  ["FIVE_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SIX_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SEVEN_RULE_SIMULTANEOUS_CHECK", "CONJUNCTIVE_RULE_EVALUATION"],
  ["SINGLE_CONDITIONAL_EXCEPTION", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["NESTED_AGE_RELAXATION", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["MARKS_AND_QUALIFICATION_EXCEPTION", "PRIORITIZED_EXCEPTION_EVALUATION"],
  ["DOCUMENT_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["AGE_BASED_DIRECTOR_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["BORDERLINE_COMMITTEE_REFERRAL", "ORDERED_ESCALATION_EVALUATION"],
  ["AGE_ON_CUTOFF_DATE", "DATE_DERIVED_AGE_EVALUATION"],
  ["QUALIFICATION_AND_RELEVANT_EXPERIENCE", "MULTI_FIELD_PROFILE_EVALUATION"],
  ["AGE_QUALIFICATION_EXPERIENCE_COMBINATION", "MULTI_FIELD_PROFILE_EVALUATION"],
  ["RECRUITMENT_ADMISSION_TRAINING_ELIGIBILITY", "CONJUNCTIVE_RULE_EVALUATION"],
  ["ADMISSION_MARKS_RESIDENCE_CREDENTIAL", "CONJUNCTIVE_RULE_EVALUATION"],
  ["APPRENTICESHIP_EXPERIENCE_QUALIFICATION", "CONJUNCTIVE_RULE_EVALUATION"],
  ["FICTIONAL_GRANT_INCOME_RESIDENCE_EMPLOYMENT", "BENEFIT_RULE_EVALUATION"],
  ["FICTIONAL_LOAN_REPAYMENT_COLLATERAL_CATEGORY", "BENEFIT_RULE_EVALUATION"],
  ["FICTIONAL_BENEFIT_INCOME_AGE_CATEGORY", "BENEFIT_RULE_EVALUATION"],
  ["WRITTEN_AND_SECTIONAL_MINIMUMS", "MULTI_CUTOFF_EVALUATION"],
  ["INTERVIEW_AND_OVERALL_MINIMUMS", "MULTI_CUTOFF_EVALUATION"],
  ["ALL_SCORE_AND_EXPERIENCE_CUTOFFS", "MULTI_CUTOFF_EVALUATION"],
  ["AGE_RELAXATION_DEPENDS_ON_EXPERIENCE", "DEPENDENT_RELAXATION_EVALUATION"],
  ["POSTGRADUATE_MARKS_RELAXATION", "DEPENDENT_RELAXATION_EVALUATION"],
  ["COMBINED_RELAXATIONS_USE_RULE_PRIORITY", "ORDERED_DEPENDENT_RELAXATION_EVALUATION"],
  ["SEAT_SELECTION_QUALIFICATION_EXPERIENCE_MARKS", "EXPLICIT_PRIORITY_RANKING"],
  ["SEAT_SELECTION_EXAM_AND_INTERVIEW_SCORES", "EXPLICIT_PRIORITY_RANKING"],
  ["SEAT_SELECTION_CUTOFF_AND_TIE_BREAK", "EXPLICIT_PRIORITY_RANKING"],
] as const;

export const DM_001_QL_REGISTRY: readonly DmQlEntry[] = Object.freeze(
  DM_001_QL_IDS.map((qlId, index) => Object.freeze({
    qlId,
    checkpointId: DM_001_CHECKPOINT_IDS[Math.floor(index / 3)]!,
    ruleFamily: QL_DEFINITIONS[index]![0],
    solveMode: QL_DEFINITIONS[index]![1],
    answerType: (index >= 27 ? "RANKED_CANDIDATE_SET" : "DECISION_OUTCOME") as DmQlEntry["answerType"],
    renderer: (index >= 27 ? "PRIORITY_ORDER_AND_CANDIDATE_POOL" : "RULES_AND_CANDIDATE_PROFILE") as DmQlEntry["renderer"],
    localeMode: "TRANSLATABLE" as const,
    status: "IMPLEMENTED_REVIEW_ONLY" as const,
  })),
);

export function assertContinuousDmQlIds(entries: readonly Pick<DmQlEntry, "qlId">[] = DM_001_QL_REGISTRY): void {
  const expected = DM_001_QL_IDS;
  const actual = entries.map((entry) => entry.qlId);
  if (actual.length !== expected.length || actual.some((id, index) => id !== expected[index])) {
    throw new Error("DM-001 QL IDs must be continuous and match the permanent chapter registry.");
  }
}

export function dmQlEntry(qlId: string): DmQlEntry {
  const entry = DM_001_QL_REGISTRY.find((candidate) => candidate.qlId === qlId);
  if (!entry) throw new Error("Unknown DM-001 QL: " + qlId);
  return entry;
}

export function dmQlIdsForCheckpoint(checkpointId: DmCheckpointId): readonly DmQlId[] {
  return DM_001_QL_REGISTRY.filter((entry) => entry.checkpointId === checkpointId).map((entry) => entry.qlId);
}
