export const HIS_CP012_EXPLANATION_OVERRIDES_V2:Readonly<Record<number,string>>={
1:"The Portuguese were the first major European maritime power to establish a lasting trading presence in India. Their arrival opened the early phase of direct European competition for Indian Ocean trade.",
2:"Vasco da Gama reached Calicut on the Malabar Coast in 1498. His voyage created a direct sea link between Europe and India around the Cape of Good Hope.",
3:"Afonso de Albuquerque captured Goa for the Portuguese in 1510. Goa later became the principal Portuguese political and commercial centre on the western coast of India.",
4:"The Dutch East India Company was formed in 1602. It became a major commercial rival of the Portuguese and English in Asian trade during the seventeenth century.",
5:"The Dutch established a factory at Masulipatnam in 1605. The settlement gave them an important foothold on the Coromandel Coast and access to the region's textile trade.",
6:"Marthanda Varma of Travancore defeated the Dutch at the Battle of Colachel in 1741. The defeat significantly weakened Dutch political and military influence on the Malabar Coast.",
7:"The French East India Company was founded in 1664. It later became the main European rival of the English Company in the struggle for political influence in South India.",
8:"Francois Martin developed Pondicherry into an important French trading centre from 1674. Pondicherry later served as the main base of French political activity in India.",
9:"Joseph Francois Dupleix took charge of French affairs in India in 1742. He became a central figure in the Anglo-French struggle for influence during the Carnatic Wars.",
10:"The British and French fought three Carnatic Wars in South India during the eighteenth century. These conflicts linked European rivalry with succession disputes and regional politics in the Carnatic and Hyderabad.",
11:"The British defeated the French at Wandiwash in 1760 during the Third Carnatic War. The defeat broke the main French military challenge to British political expansion in India.",
12:"Wandiwash ended the French challenge for political supremacy, although some French settlements remained afterward. France continued to trade, but it no longer matched the Company's territorial ambitions.",
13:"The English East India Company was established in 1600 as a trading corporation. Over the next century and a half, it gradually moved from commercial activity toward political and territorial power.",
14:"Siraj-ud-Daula became the Nawab of Bengal in 1756. His conflict with the Company over trade privileges and fortification soon led to the confrontation that culminated at Plassey.",
15:"The Battle of Plassey was fought in 1757 between Siraj-ud-Daula and the English East India Company. The Company's victory greatly increased its political influence in Bengal.",
16:"The Company's victory at Plassey depended heavily on a conspiracy involving Mir Jafar and other influential Bengal elites. The battle was therefore shaped by political betrayal as well as military action.",
17:"After Plassey, the Company helped install Mir Jafar as Nawab of Bengal. This demonstrated the Company's growing ability to influence succession and political authority in the province.",
18:"Mir Qasim replaced Mir Jafar as Nawab of Bengal in 1760 with Company support. He later tried to strengthen his independence, which brought him into serious conflict with Company interests.",
19:"Company traders enjoyed special duty privileges, while Mir Qasim tried to remove their unequal commercial advantage. The dispute over customs and duty-free trade became a major cause of conflict.",
20:"Mir Qasim shifted his capital from Murshidabad to Munger while trying to strengthen administration and the army. The move formed part of his attempt to reduce dependence on the Company.",
21:"The Company won a decisive victory at the Battle of Buxar in 1764. The victory strengthened its position against Bengal, Awadh and the Mughal emperor and had wider consequences than Plassey.",
22:"At Buxar, the Company faced the combined forces of Mir Qasim, Shuja-ud-Daula of Awadh and Mughal emperor Shah Alam II. Their defeat greatly increased Company political leverage in eastern India.",
23:"The Treaty of Allahabad was concluded in 1765 after the Company's victory at Buxar. The settlement reorganised relations among the Company, the Mughal emperor and Awadh.",
24:"In 1765, Shah Alam II granted the Company the Diwani, or revenue-collection rights, of Bengal, Bihar and Orissa. This gave the Company a major fiscal base for further military and territorial expansion.",
25:"The Company restored Awadh to Shuja-ud-Daula because it wanted a buffer state between Company territories and powers farther northwest. This policy combined political control with strategic restraint.",
26:"Under Dual Government in Bengal, the Company controlled revenue while the Nawab remained formally responsible for administration. Real power and official responsibility were therefore separated.",
27:"The weakness of Dual Government was that the Company held revenue and effective power while the Nawab carried administrative responsibility without adequate authority or resources. This produced serious governance problems.",
28:"Haidar Ali became ruler of Mysore in 1761 and developed it into a major military power. Mysore became one of the strongest southern opponents of Company expansion during the later eighteenth century.",
29:"Haidar Ali rose to power in 1761, Tipu Sultan continued resistance, and Tipu was killed in 1799. The fall of Mysore removed one of the Company's strongest military rivals in South India.",
30:"The fall of Mysore in 1799 removed one of the strongest southern checks on Company expansion. After Tipu Sultan's defeat, the balance of power in peninsular India shifted decisively toward the Company.",
31:"Lord Wellesley expanded the Subsidiary Alliance system from 1798. It promised Company protection while sharply limiting the allied ruler's military independence and freedom in foreign relations.",
32:"Under the Subsidiary Alliance, the Company promised protection against external attack and internal disorder. In return, the allied state accepted major restrictions that increased Company influence.",
33:"A ruler entering the Subsidiary Alliance had to accept the stationing of a British force within the state. This gave the Company a permanent military presence close to the allied court.",
34:"The allied ruler had to pay for the British force, usually through a subsidy or territorial cession. The arrangement shifted military costs onto Indian states while expanding Company control.",
35:"A ruler under the Subsidiary Alliance could not wage war or make alliances with other powers without Company permission. The restriction substantially reduced the state's independent foreign policy.",
36:"A British Resident stayed at the allied court, while the ruler's foreign policy remained subject to Company permission. Together these conditions increased direct political supervision over allied states.",
37:"Hyderabad entered a Subsidiary Alliance with the Company in 1798 under Lord Wellesley's policy. It became an important early example of expansion through treaty rather than outright conquest.",
38:"Delhi came under Company control in 1803, effective Peshwa power ended by 1818, and Sindh was annexed in 1843. The sequence shows the steady westward and northward growth of Company territory.",
39:"The Anglo-Maratha Wars greatly expanded Company control in western and central India. Their outcome weakened the major Maratha houses and ended effective Peshwa power by 1818.",
40:"Delhi came under Company control in 1803 during the struggle against Maratha power. Control of the old Mughal capital increased the Company's political prestige as well as its strategic influence.",
41:"The British annexed Sindh in 1843. The annexation extended Company power farther into the northwest before the later conquest of Punjab.",
42:"Maharaja Ranjit Singh united several Sikh misls and built a powerful state in Punjab. His rule created a strong regional power that limited Company expansion beyond the Sutlej for much of his lifetime.",
43:"Company relations with Ranjit Singh were generally workable and relatively stable during his lifetime. The balance changed after his death, when internal instability in Punjab contributed to open conflict.",
44:"After Ranjit Singh's death, the Company fought two Anglo-Sikh Wars as it expanded into Punjab. These conflicts ended the earlier period of comparatively stable relations with his state.",
45:"Ranjit Singh died first, the two Anglo-Sikh Wars followed, and Punjab was annexed in 1849. The sequence traces the transition from an independent Sikh kingdom to Company rule.",
46:"The Doctrine of Lapse is closely associated with Governor-General Lord Dalhousie. The policy became one of the Company's major methods of annexation during the decade before the Revolt of 1857.",
47:"Under the Doctrine of Lapse, the Company could refuse to recognise an adopted heir when a dependent ruler died without a natural male heir. The state could then be annexed to Company territory.",
48:"Satara, Sambalpur, Nagpur and Jhansi were among the states annexed under the Doctrine of Lapse. These annexations expanded Company territory and created resentment among affected ruling families.",
49:"Awadh was annexed in 1856 on the stated ground of misgovernment, whereas Jhansi was annexed under the Doctrine of Lapse. The two cases show that the Company used different legal-political justifications for annexation.",
50:"The Company expanded through direct war and conquest, treaty systems such as the Subsidiary Alliance, and annexation policies such as the Doctrine of Lapse. Territorial growth therefore used several methods rather than one strategy.",
51:"British naval strength and the growing financial resources of Bengal gave the Company an important advantage over European rivals. Maritime power and revenue together supported sustained military operations.",
52:"Bengal supplied financial resources for military expansion, while allied rulers under the Subsidiary Alliance helped finance British troops. Both developments reduced the Company's dependence on resources from Britain alone.",
53:"The East India Company began as a trading corporation, gained political influence through conflict and alliances, and eventually became a territorial power. This transformation is central to understanding British expansion in India.",
54:"The Third Carnatic War was connected to the wider Seven Years' War, and the British defeated the French at Wandiwash in 1760. The result weakened the French political challenge in India.",
55:"The Battle of Wandiwash was fought in 1760, and Pondicherry fell to the British in 1761. Wandiwash therefore came first and paved the way for the collapse of the main French military position.",
56:"Two major causes of tension before Plassey were the misuse of duty-free trade privileges and the Company's unauthorised fortification of Calcutta. Both issues challenged the Nawab's authority in Bengal.",
57:"The conflict before Plassey involved more than battlefield rivalry because trade privileges and unauthorised fortification directly challenged the Nawab's political and fiscal authority. Commercial disputes became political disputes.",
58:"Buxar strengthened the Company's position over Awadh and led to the 1765 settlement in which the Company received Diwani rights. The victory therefore produced major territorial and fiscal consequences in eastern India.",
59:"The Company increasingly supplemented European troops with locally recruited sepoys organised through the presidency armies. This larger military structure allowed it to fight sustained campaigns across different regions.",
60:"Madras, Bengal and Bombay developed into major administrative and military centres for the Company. Their presidency armies and institutions provided regional bases from which territorial expansion could be organised.",
};
