export type Eng007Difficulty="easy"|"medium"|"hard";
export type Eng007SpellingTrap="omitted-letter"|"extra-letter"|"letter-order"|"vowel-sequence"|"double-letter"|"ending-pattern"|"internal-pattern";
export interface Eng007CP004EntryV1{id:string;correct:string;misspelling:string;difficulty:Eng007Difficulty;domain:string;sourceRef:string;trap:Eng007SpellingTrap;}
const RAW=`
alcove|alccove|easy|architecture_buildings|ENG-006-CP006|extra-letter
alexia|alexxia|easy|speech_language_disorders|ENG-006-CP006|extra-letter
anomia|anmia|easy|speech_language_disorders|ENG-006-CP006|omitted-letter
canyon|caynon|easy|geography_landforms|ENG-006-CP005|letter-order
cupola|cuppola|easy|architecture_buildings|ENG-006-CP006|extra-letter
embryo|embbryo|easy|biology_anatomy|ENG-006-CP005|extra-letter
enzyme|enyzme|easy|biology_anatomy|ENG-006-CP005|letter-order
famine|fammine|easy|earth_weather|ENG-006-CP005|extra-letter
geyser|geysser|easy|earth_weather|ENG-006-CP005|extra-letter
isobar|isobbar|easy|chemistry_materials|ENG-006-CP006|extra-letter
lintel|litnel|easy|architecture_buildings|ENG-006-CP006|letter-order
meteor|metor|easy|astronomy_space|ENG-006-CP006|omitted-letter
myopia|mypoia|easy|medicine_conditions|ENG-006-CP005|letter-order
nebula|neubla|easy|astronomy_space|ENG-006-CP006|letter-order
pistil|pisitl|easy|botany_plants|ENG-006-CP006|letter-order
porous|porrous|easy|material_properties|ENG-006-CP003|extra-letter
router|roter|easy|computing_digital|ENG-006-CP006|omitted-letter
server|servver|easy|computing_digital|ENG-006-CP006|extra-letter
solute|sollute|easy|chemistry_materials|ENG-006-CP006|extra-letter
stamen|stammen|easy|botany_plants|ENG-006-CP006|extra-letter
stolon|stlon|easy|botany_plants|ENG-006-CP006|omitted-letter
strait|strit|easy|geography_landforms|ENG-006-CP005|omitted-letter
zenith|zeinth|easy|astronomy_space|ENG-006-CP006|letter-order
amalgam|amlagam|easy|chemistry_materials|ENG-006-CP006|letter-order
antigen|anitgen|easy|biology_anatomy|ENG-006-CP005|letter-order
auditor|auidtor|easy|professions_specialists|ENG-006-CP002|letter-order
browser|browesr|easy|computing_digital|ENG-006-CP006|letter-order
curator|cuartor|easy|professions_specialists|ENG-006-CP002|letter-order
cyclone|cycllone|easy|earth_weather|ENG-006-CP005|extra-letter
density|denstiy|easy|science_physics|ENG-006-CP005|letter-order
ductile|ductlie|easy|material_properties|ENG-006-CP003|letter-order
elastic|elatsic|easy|material_properties|ENG-006-CP003|letter-order
equinox|equniox|easy|astronomy_space|ENG-006-CP006|letter-order
habitat|habtiat|easy|environment_resources|ENG-006-CP005|letter-order
hormone|hormnoe|easy|biology_anatomy|ENG-006-CP005|letter-order
inertia|inretia|easy|science_physics|ENG-006-CP005|letter-order
isotone|istoone|easy|chemistry_materials|ENG-006-CP006|letter-order
isotope|isotpoe|easy|chemistry_materials|ENG-006-CP006|letter-order
isthmus|ishtmus|easy|geography_landforms|ENG-006-CP005|letter-order
malware|malawre|easy|computing_digital|ENG-006-CP006|letter-order
mimicry|mimircy|easy|science_nature|ENG-006-CP002|letter-order
minaret|mianret|easy|architecture_buildings|ENG-006-CP006|letter-order
mitosis|mitoiss|easy|biology_anatomy|ENG-006-CP005|letter-order
monomer|monommer|easy|chemistry_materials|ENG-006-CP006|extra-letter
osmosis|osmsois|easy|science_nature|ENG-006-CP002|letter-order
parapet|parpaet|easy|architecture_buildings|ENG-006-CP006|letter-order
petiole|peitole|easy|botany_plants|ENG-006-CP006|letter-order
polymer|poylmer|easy|chemistry_materials|ENG-006-CP006|letter-order
portico|portcio|easy|architecture_buildings|ENG-006-CP006|letter-order
reagent|reagant|easy|chemistry_materials|ENG-006-CP006|ending-pattern
rotunda|rotunnda|easy|architecture_buildings|ENG-006-CP006|extra-letter
solvent|sollvent|easy|chemistry_materials|ENG-006-CP006|extra-letter
sterile|sterlie|easy|material_properties|ENG-006-CP003|letter-order
syncope|synocpe|easy|medicine_conditions|ENG-006-CP005|letter-order
tendril|tendirl|easy|botany_plants|ENG-006-CP006|letter-order
tornado|tornnado|easy|earth_weather|ENG-006-CP005|extra-letter
tsunami|tsunmai|easy|earth_weather|ENG-006-CP005|letter-order
vertigo|vertgio|easy|medical_psychological|ENG-006-CP003|letter-order
vintner|vintenr|easy|advanced_specialists|ENG-006-CP003|letter-order
volcano|voclano|easy|geography_landforms|ENG-006-CP005|letter-order
anorexia|anoerxia|easy|medical_psychological|ENG-006-CP003|letter-order
antibody|anitbody|easy|biology_anatomy|ENG-006-CP005|letter-order
asteroid|astreoid|easy|astronomy_space|ENG-006-CP006|letter-order
catalyst|catallyst|easy|chemistry_materials|ENG-006-CP006|extra-letter
compiler|copmiler|easy|computing_digital|ENG-006-CP006|letter-order
cyanosis|cyaonsis|easy|medicine_conditions|ENG-006-CP005|letter-order
database|datbaase|easy|computing_digital|ENG-006-CP006|letter-order
delirium|delirrium|easy|medical_psychological|ENG-006-CP003|extra-letter
dyslexia|dysllexia|easy|medical_psychological|ENG-006-CP003|extra-letter
firmware|fimrware|easy|computing_digital|ENG-006-CP006|letter-order
fusion|fution|medium|science_physics|ENG-006-CP005|ending-pattern
gangrene|ganggrene|medium|medicine_conditions|ENG-006-CP005|extra-letter
hardware|hadrware|medium|computing_digital|ENG-006-CP006|letter-order
invasive|invassive|medium|biology_ecology|ENG-006-CP003|extra-letter
jaundice|jaudnice|medium|medicine_conditions|ENG-006-CP005|letter-order
lethargy|lehtargy|medium|medical_psychological|ENG-006-CP003|letter-order
momentum|momnetum|medium|science_physics|ENG-006-CP005|letter-order
mutism|mutsm|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
pathogen|pathgoen|medium|biology_anatomy|ENG-006-CP005|letter-order
pediment|pedimant|medium|architecture_buildings|ENG-006-CP006|ending-pattern
placenta|placanta|medium|biology_anatomy|ENG-006-CP005|internal-pattern
ruminant|ruminent|medium|biology_ecology|ENG-006-CP003|ending-pattern
software|sotfware|medium|computing_digital|ENG-006-CP006|letter-order
solstice|sosltice|medium|astronomy_space|ENG-006-CP006|letter-order
velocity|veloccity|medium|science_physics|ENG-006-CP005|extra-letter
volatile|voaltile|medium|material_properties|ENG-006-CP003|letter-order
actuary|acturay|medium|professions_specialists|ENG-006-CP002|letter-order
algorithm|algorrithm|medium|computing_digital|ENG-006-CP006|extra-letter
apogee|apoege|medium|astronomy_space|ENG-006-CP006|letter-order
arthritis|arhtritis|medium|medicine_conditions|ENG-006-CP005|letter-order
avalanche|avalannche|medium|earth_weather|ENG-006-CP005|extra-letter
bandwidth|banddwidth|medium|computing_digital|ENG-006-CP006|extra-letter
client|cliant|medium|computing_digital|ENG-006-CP006|vowel-sequence
cosmogony|cosmgoony|medium|astronomy_space|ENG-006-CP006|letter-order
cotyledon|cotyleddon|medium|botany_plants|ENG-006-CP006|extra-letter
echolalia|echoallia|medium|speech_language_disorders|ENG-006-CP006|letter-order
ecology|ecolgoy|medium|environment_resources|ENG-006-CP005|letter-order
ecosystem|ecossytem|medium|environment_resources|ENG-006-CP005|letter-order
ectotherm|ectottherm|medium|biology_ecology|ENG-006-CP003|extra-letter
endotherm|endohterm|medium|biology_ecology|ENG-006-CP003|letter-order
erosion|erossion|medium|environment_resources|ENG-006-CP005|extra-letter
estuary|esturay|medium|geography_landforms|ENG-006-CP005|letter-order
foetus|foeuts|medium|biology_anatomy|ENG-006-CP005|letter-order
frugivore|frugivvore|medium|biology_ecology|ENG-006-CP003|extra-letter
hepatitis|hepattitis|medium|medicine_conditions|ENG-006-CP005|extra-letter
lagoon|laogon|medium|geography_landforms|ENG-006-CP005|letter-order
landslide|ladnslide|medium|earth_weather|ENG-006-CP005|letter-order
latency|latancy|medium|computing_digital|ENG-006-CP006|internal-pattern
loggia|logiga|medium|architecture_buildings|ENG-006-CP006|letter-order
marsupial|masrupial|medium|biology_ecology|ENG-006-CP003|letter-order
meteorite|meteoirte|medium|astronomy_space|ENG-006-CP006|letter-order
nostalgia|nostlagia|medium|medical_psychological|ENG-006-CP003|letter-order
oedema|oedma|medium|medicine_conditions|ENG-006-CP005|omitted-letter
oviparous|ovipraous|medium|biology_ecology|ENG-006-CP003|letter-order
palilalia|paillalia|medium|speech_language_disorders|ENG-006-CP006|letter-order
paralysis|paarlysis|medium|medical_psychological|ENG-006-CP003|letter-order
peninsula|peinnsula|medium|geography_landforms|ENG-006-CP005|letter-order
phobia|phboia|medium|medical_psychological|ENG-006-CP003|letter-order
pyromania|pyormania|medium|medical_psychological|ENG-006-CP003|letter-order
sepsis|sepiss|medium|medicine_conditions|ENG-006-CP005|letter-order
supernova|superrnova|medium|astronomy_space|ENG-006-CP006|extra-letter
symbiosis|symbisois|medium|science_nature|ENG-006-CP002|letter-order
tissue|tisuse|medium|biology_anatomy|ENG-006-CP005|letter-order
valley|valely|medium|geography_landforms|ENG-006-CP005|letter-order
vestibule|vetsibule|medium|architecture_buildings|ENG-006-CP006|letter-order
watershed|waterrshed|medium|geography_landforms|ENG-006-CP005|extra-letter
amnesia|amensia|medium|medical_psychological|ENG-006-CP003|letter-order
anaemia|anemia|medium|medical_psychological|ENG-006-CP003|omitted-letter
aphasia|aphhasia|medium|medical_psychological|ENG-006-CP003|extra-letter
aphonia|aphnoia|medium|speech_language_disorders|ENG-006-CP006|letter-order
aseptic|asetpic|medium|material_properties|ENG-006-CP003|letter-order
astrologer|asrtologer|medium|professions_specialists|ENG-006-CP002|letter-order
astronomer|asrtonomer|medium|professions_specialists|ENG-006-CP002|letter-order
balustrade|balusstrade|medium|architecture_buildings|ENG-006-CP006|extra-letter
biomass|biomas|medium|environment_resources|ENG-006-CP005|omitted-letter
botanist|botainst|medium|professions_specialists|ENG-006-CP002|letter-order
bradylalia|bradyylalia|medium|speech_language_disorders|ENG-006-CP006|extra-letter
bronchitis|broncchitis|medium|medicine_conditions|ENG-006-CP005|extra-letter
buoyancy|buoayncy|medium|science_physics|ENG-006-CP005|letter-order
chromosome|chormosome|medium|biology_anatomy|ENG-006-CP005|letter-order
conductive|condcutive|medium|material_properties|ENG-006-CP003|letter-order
coprolalia|corpolalia|medium|speech_language_disorders|ENG-006-CP006|letter-order
decomposer|decomposser|medium|biology_ecology|ENG-006-CP003|extra-letter
dermatitis|dermtaitis|medium|medicine_conditions|ENG-006-CP005|letter-order
drizzle|drizle|medium|earth_weather|ENG-006-CP005|omitted-letter
drought|drught|medium|earth_weather|ENG-006-CP005|omitted-letter
dysarthria|dysarthhria|medium|speech_language_disorders|ENG-006-CP006|extra-letter
dysprosody|dysporsody|medium|speech_language_disorders|ENG-006-CP006|letter-order
earthquake|earthqquake|medium|earth_weather|ENG-006-CP005|extra-letter
emulsion|emuslion|medium|chemistry_materials|ENG-006-CP006|letter-order
friction|fritcion|medium|science_physics|ENG-006-CP005|letter-order
geothermal|getohermal|medium|environment_resources|ENG-006-CP005|letter-order
glacier|glaccier|medium|geography_landforms|ENG-006-CP005|extra-letter
hydrolysis|hydrloysis|medium|chemistry_materials|ENG-006-CP006|letter-order
indigenous|indiggenous|medium|biology_ecology|ENG-006-CP003|extra-letter
insulating|inuslating|medium|material_properties|ENG-006-CP003|letter-order
meiosis|meioiss|medium|biology_anatomy|ENG-006-CP005|letter-order
monsoon|monnsoon|medium|earth_weather|ENG-006-CP005|extra-letter
mutation|muttation|medium|biology_anatomy|ENG-006-CP005|extra-letter
organism|oragnism|medium|biology_anatomy|ENG-006-CP005|letter-order
perigee|perrigee|medium|astronomy_space|ENG-006-CP006|extra-letter
perihelion|perihhelion|medium|astronomy_space|ENG-006-CP006|extra-letter
plateau|pltaeau|medium|geography_landforms|ENG-006-CP005|letter-order
presbyopia|presybopia|medium|medicine_conditions|ENG-006-CP005|letter-order
rhizome|rhizmoe|medium|botany_plants|ENG-006-CP006|letter-order
rotation|rottaion|medium|astronomy_space|ENG-006-CP006|letter-order
stammer|stmmer|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
steeple|steelpe|medium|architecture_buildings|ENG-006-CP006|letter-order
tachylalia|tachlyalia|medium|speech_language_disorders|ENG-006-CP006|letter-order
vaccine|vaccne|medium|biology_anatomy|ENG-006-CP005|omitted-letter
vertebrate|vertberate|medium|biology_ecology|ENG-006-CP003|letter-order
viscous|visscous|medium|material_properties|ENG-006-CP003|extra-letter
viviparous|viivparous|medium|biology_ecology|ENG-006-CP003|letter-order
weathering|wetahering|medium|environment_resources|ENG-006-CP005|letter-order
agraphia|agrraphia|medium|speech_language_disorders|ENG-006-CP006|extra-letter
aphelion|afelion|medium|astronomy_space|ENG-006-CP006|omitted-letter
archivist|archhivist|medium|professions_specialists|ENG-006-CP002|extra-letter
blizzard|blizazrd|medium|earth_weather|ENG-006-CP005|letter-order
bradycardia|bradcyardia|medium|medicine_conditions|ENG-006-CP005|letter-order
buttress|butrtess|medium|architecture_buildings|ENG-006-CP006|letter-order
cosmology|comsology|hard|astronomy_space|ENG-006-CP006|letter-order
deciduous|decidduous|hard|botany_plants|ENG-006-CP006|extra-letter
ecologist|ecoolgist|hard|medical_specialists|ENG-006-CP005|letter-order
epiphyte|epifyte|hard|botany_plants|ENG-006-CP006|omitted-letter
firewall|firewal|hard|computing_digital|ENG-006-CP006|omitted-letter
geologist|geoolgist|hard|professions_specialists|ENG-006-CP002|letter-order
insectivore|insecctivore|hard|biology_ecology|ENG-006-CP003|extra-letter
insomnia|inosmnia|hard|medical_psychological|ENG-006-CP003|letter-order
interpreter|inetrpreter|hard|professions_specialists|ENG-006-CP002|letter-order
magnetic|magnteic|hard|material_properties|ENG-006-CP003|letter-order
megalomania|megalomannia|hard|medical_psychological|ENG-006-CP003|extra-letter
migratory|mirgatory|hard|biology_ecology|ENG-006-CP003|letter-order
mutualism|mutulaism|hard|science_nature|ENG-006-CP002|letter-order
oxidation|oxdiation|hard|chemistry_materials|ENG-006-CP006|letter-order
permeable|perrmeable|hard|material_properties|ENG-006-CP003|extra-letter
phishing|phsihing|hard|computing_digital|ENG-006-CP006|letter-order
radiation|raidation|hard|science_physics|ENG-006-CP005|letter-order
radioactive|radioacctive|hard|material_properties|ENG-006-CP003|extra-letter
reduction|redduction|hard|chemistry_materials|ENG-006-CP006|extra-letter
renewable|rennewable|hard|environment_resources|ENG-006-CP005|extra-letter
tachycardia|tachyccardia|hard|medicine_conditions|ENG-006-CP005|extra-letter
titration|titrasion|hard|chemistry_materials|ENG-006-CP006|ending-pattern
transept|trasnept|hard|architecture_buildings|ENG-006-CP006|letter-order
tributary|tributery|hard|geography_landforms|ENG-006-CP005|ending-pattern
urologist|urloogist|hard|medical_specialists|ENG-006-CP005|letter-order
agronomist|agornomist|hard|advanced_specialists|ENG-006-CP003|letter-order
autotroph|autotrof|hard|biology_ecology|ENG-006-CP003|omitted-letter
colonnade|collonnade|hard|architecture_buildings|ENG-006-CP006|extra-letter
conduction|conudction|hard|science_physics|ENG-006-CP005|letter-order
convection|convecsion|hard|science_physics|ENG-006-CP005|ending-pattern
corrosive|corosive|hard|material_properties|ENG-006-CP003|omitted-letter
cytologist|cytollogist|hard|medical_specialists|ENG-006-CP005|extra-letter
debugging|debguging|hard|computing_digital|ENG-006-CP006|letter-order
dysphonia|dysphhonia|hard|speech_language_disorders|ENG-006-CP006|extra-letter
evergreen|evergrreen|hard|botany_plants|ENG-006-CP006|extra-letter
filtration|filrtation|hard|science_nature|ENG-006-CP002|letter-order
fission|fisson|hard|science_physics|ENG-006-CP005|omitted-letter
geneticist|geenticist|hard|medical_specialists|ENG-006-CP005|letter-order
halophyte|halofyte|hard|botany_plants|ENG-006-CP006|omitted-letter
herbaceous|herbbaceous|hard|botany_plants|ENG-006-CP006|extra-letter
hurricane|hurrciane|hard|earth_weather|ENG-006-CP005|letter-order
ionisation|ionnisation|hard|science_physics|ENG-006-CP005|extra-letter
mesophyte|mespohyte|hard|botany_plants|ENG-006-CP006|letter-order
metabolism|meatbolism|hard|biology_anatomy|ENG-006-CP005|letter-order
mycologist|mycoolgist|hard|advanced_specialists|ENG-006-CP003|letter-order
nephritis|neprhitis|hard|medicine_conditions|ENG-006-CP005|letter-order
oncologist|onoclogist|hard|medical_specialists|ENG-006-CP005|letter-order
piscivore|picsivore|hard|biology_ecology|ENG-006-CP003|letter-order
reflection|reflecction|hard|science_physics|ENG-006-CP005|extra-letter
refraction|reffraction|hard|science_physics|ENG-006-CP005|extra-letter
refractory|refracttory|hard|material_properties|ENG-006-CP003|extra-letter
revolution|revvolution|hard|astronomy_space|ENG-006-CP006|extra-letter
satellite|sattellite|hard|astronomy_space|ENG-006-CP006|extra-letter
scavenger|scavneger|hard|biology_ecology|ENG-006-CP003|letter-order
succulent|sucuclent|hard|botany_plants|ENG-006-CP006|letter-order
suspension|suspennsion|hard|chemistry_materials|ENG-006-CP006|extra-letter
virologist|viorlogist|hard|medical_specialists|ENG-006-CP005|letter-order
viscosity|vicsosity|hard|science_physics|ENG-006-CP005|letter-order
xerophyte|xerpohyte|hard|botany_plants|ENG-006-CP006|letter-order
acrophobia|acrofobia|hard|medical_psychological|ENG-006-CP003|omitted-letter
antiseptic|anitseptic|hard|material_properties|ENG-006-CP003|letter-order
astigmatism|astiggmatism|hard|medicine_conditions|ENG-006-CP005|extra-letter
combustible|combusstible|hard|material_properties|ENG-006-CP003|extra-letter
dysgraphia|dysrgaphia|hard|speech_language_disorders|ENG-006-CP006|letter-order
etymologist|etmyologist|hard|experts_studies|ENG-006-CP001|letter-order
evaporation|evaopration|hard|science_nature|ENG-006-CP002|letter-order
genealogist|geenalogist|hard|experts_studies|ENG-006-CP001|letter-order
germination|germinnation|hard|science_nature|ENG-006-CP002|extra-letter
gravitation|graivtation|hard|science_physics|ENG-006-CP005|letter-order
hibernation|hibernnation|hard|science_nature|ENG-006-CP002|extra-letter
histologist|histologgist|hard|medical_specialists|ENG-006-CP005|extra-letter
hydrophyte|hydorphyte|hard|botany_plants|ENG-006-CP006|letter-order
impermeable|impermmeable|hard|material_properties|ENG-006-CP003|extra-letter
neurologist|neurollogist|hard|advanced_specialists|ENG-006-CP003|extra-letter
numismatist|nuimsmatist|hard|experts_studies|ENG-006-CP001|letter-order
optician|opticcian|hard|professions_specialists|ENG-006-CP002|extra-letter
paraphasia|parafasia|hard|speech_language_disorders|ENG-006-CP006|omitted-letter
pathologist|pahtologist|hard|professions_specialists|ENG-006-CP002|letter-order
peripheral|periferal|hard|computing_digital|ENG-006-CP006|omitted-letter
radiologist|radiollogist|hard|medical_specialists|ENG-006-CP005|extra-letter
`.trim();
export const ENG007_CP004_ENTRIES_V1=Object.freeze(RAW.split("\n").map((line,index)=>{
  const [correct,misspelling,difficulty,domain,sourceRef,trap]=line.split("|") as [string,string,Eng007Difficulty,string,string,Eng007SpellingTrap];
  return{id:`SPL004-${String(index+1).padStart(3,"0")}`,correct,misspelling,difficulty,domain,sourceRef,trap}as const;
}));
export function eng007Cp004PoolV1(difficulty:Eng007Difficulty){return ENG007_CP004_ENTRIES_V1.filter(x=>x.difficulty===difficulty);}
