export type Eng007Difficulty="easy"|"medium"|"hard";
export type Eng007SpellingTrap="omitted-letter"|"extra-letter"|"letter-order"|"vowel-sequence"|"double-letter"|"ending-pattern"|"internal-pattern";
export interface Eng007CP004EntryV1{id:string;correct:string;misspelling:string;difficulty:Eng007Difficulty;domain:string;sourceRef:string;trap:Eng007SpellingTrap;}
const RAW=`
alcove|alcve|easy|architecture_buildings|ENG-006-CP006|omitted-letter
alexia|alxia|easy|speech_language_disorders|ENG-006-CP006|omitted-letter
anomia|anmia|easy|speech_language_disorders|ENG-006-CP006|omitted-letter
canyon|caynon|easy|geography_landforms|ENG-006-CP005|letter-order
cupola|cupla|easy|architecture_buildings|ENG-006-CP006|omitted-letter
embryo|emrbyo|easy|biology_anatomy|ENG-006-CP005|letter-order
enzyme|enyzme|easy|biology_anatomy|ENG-006-CP005|letter-order
famine|famne|easy|earth_weather|ENG-006-CP005|omitted-letter
geyser|gesyer|easy|earth_weather|ENG-006-CP005|letter-order
isobar|isbar|easy|chemistry_materials|ENG-006-CP006|omitted-letter
lintel|litnel|easy|architecture_buildings|ENG-006-CP006|letter-order
meteor|metor|easy|astronomy_space|ENG-006-CP006|omitted-letter
myopia|mypia|easy|medicine_conditions|ENG-006-CP005|omitted-letter
nebula|nebla|easy|astronomy_space|ENG-006-CP006|omitted-letter
pistil|pitsil|easy|botany_plants|ENG-006-CP006|letter-order
porous|porus|easy|material_properties|ENG-006-CP003|omitted-letter
router|roter|easy|computing_digital|ENG-006-CP006|omitted-letter
server|sevrer|easy|computing_digital|ENG-006-CP006|letter-order
solute|solte|easy|chemistry_materials|ENG-006-CP006|omitted-letter
stamen|stmen|easy|botany_plants|ENG-006-CP006|omitted-letter
stolon|stlon|easy|botany_plants|ENG-006-CP006|omitted-letter
strait|strit|easy|geography_landforms|ENG-006-CP005|omitted-letter
zenith|zenth|easy|astronomy_space|ENG-006-CP006|omitted-letter
amalgam|amlgam|easy|chemistry_materials|ENG-006-CP006|omitted-letter
antigen|antgen|easy|biology_anatomy|ENG-006-CP005|omitted-letter
auditor|audtor|easy|professions_specialists|ENG-006-CP002|omitted-letter
browser|brwser|easy|computing_digital|ENG-006-CP006|omitted-letter
curator|curtor|easy|professions_specialists|ENG-006-CP002|omitted-letter
cyclone|cyclne|easy|earth_weather|ENG-006-CP005|omitted-letter
density|densty|easy|science_physics|ENG-006-CP005|omitted-letter
ductile|ductle|easy|material_properties|ENG-006-CP003|omitted-letter
elastic|elstic|easy|material_properties|ENG-006-CP003|omitted-letter
equinox|eqinox|easy|astronomy_space|ENG-006-CP006|omitted-letter
habitat|habtat|easy|environment_resources|ENG-006-CP005|omitted-letter
hormone|hormne|easy|biology_anatomy|ENG-006-CP005|omitted-letter
inertia|inrtia|easy|science_physics|ENG-006-CP005|omitted-letter
isotone|istone|easy|chemistry_materials|ENG-006-CP006|omitted-letter
isotope|istope|easy|chemistry_materials|ENG-006-CP006|omitted-letter
isthmus|ishtmus|easy|geography_landforms|ENG-006-CP005|letter-order
malware|malwre|easy|computing_digital|ENG-006-CP006|omitted-letter
mimicry|mimcry|easy|science_nature|ENG-006-CP002|omitted-letter
minaret|minret|easy|architecture_buildings|ENG-006-CP006|omitted-letter
mitosis|mitsis|easy|biology_anatomy|ENG-006-CP005|omitted-letter
monomer|monmer|easy|chemistry_materials|ENG-006-CP006|omitted-letter
osmosis|osmsis|easy|science_nature|ENG-006-CP002|omitted-letter
parapet|parpet|easy|architecture_buildings|ENG-006-CP006|omitted-letter
petiole|petole|easy|botany_plants|ENG-006-CP006|omitted-letter
polymer|poylmer|easy|chemistry_materials|ENG-006-CP006|letter-order
portico|portco|easy|architecture_buildings|ENG-006-CP006|omitted-letter
reagent|reagant|easy|chemistry_materials|ENG-006-CP006|ending-pattern
rotunda|rotnda|easy|architecture_buildings|ENG-006-CP006|omitted-letter
solvent|solvant|easy|chemistry_materials|ENG-006-CP006|ending-pattern
sterile|strile|easy|material_properties|ENG-006-CP003|omitted-letter
syncope|syncpe|easy|medicine_conditions|ENG-006-CP005|omitted-letter
tendril|tednril|easy|botany_plants|ENG-006-CP006|letter-order
tornado|torndo|easy|earth_weather|ENG-006-CP005|omitted-letter
tsunami|tsnami|easy|earth_weather|ENG-006-CP005|omitted-letter
vertigo|vertgo|easy|medical_psychological|ENG-006-CP003|omitted-letter
vintner|vitnner|easy|advanced_specialists|ENG-006-CP003|letter-order
volcano|volcno|easy|geography_landforms|ENG-006-CP005|omitted-letter
anorexia|anrexia|easy|medical_psychological|ENG-006-CP003|omitted-letter
antibody|antbody|easy|biology_anatomy|ENG-006-CP005|omitted-letter
asteroid|astroid|easy|astronomy_space|ENG-006-CP006|omitted-letter
catalyst|catlyst|easy|chemistry_materials|ENG-006-CP006|omitted-letter
compiler|compler|easy|computing_digital|ENG-006-CP006|omitted-letter
cyanosis|cynosis|easy|medicine_conditions|ENG-006-CP005|omitted-letter
database|datbase|easy|computing_digital|ENG-006-CP006|omitted-letter
delirium|delrium|easy|medical_psychological|ENG-006-CP003|omitted-letter
dyslexia|dyslxia|easy|medical_psychological|ENG-006-CP003|omitted-letter
firmware|firmwre|easy|computing_digital|ENG-006-CP006|omitted-letter
fusion|fution|medium|science_physics|ENG-006-CP005|ending-pattern
gangrene|gangrne|medium|medicine_conditions|ENG-006-CP005|omitted-letter
hardware|hardwre|medium|computing_digital|ENG-006-CP006|omitted-letter
invasive|invsive|medium|biology_ecology|ENG-006-CP003|omitted-letter
jaundice|jandice|medium|medicine_conditions|ENG-006-CP005|omitted-letter
lethargy|lethrgy|medium|medical_psychological|ENG-006-CP003|omitted-letter
momentum|momantum|medium|science_physics|ENG-006-CP005|internal-pattern
mutism|mutsm|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
pathogen|pathgen|medium|biology_anatomy|ENG-006-CP005|omitted-letter
pediment|pedimant|medium|architecture_buildings|ENG-006-CP006|ending-pattern
placenta|placanta|medium|biology_anatomy|ENG-006-CP005|internal-pattern
ruminant|ruminent|medium|biology_ecology|ENG-006-CP003|ending-pattern
software|softwre|medium|computing_digital|ENG-006-CP006|omitted-letter
solstice|solstce|medium|astronomy_space|ENG-006-CP006|omitted-letter
velocity|velcity|medium|science_physics|ENG-006-CP005|omitted-letter
volatile|voltile|medium|material_properties|ENG-006-CP003|omitted-letter
actuary|actuery|medium|professions_specialists|ENG-006-CP002|ending-pattern
algorithm|algrithm|medium|computing_digital|ENG-006-CP006|omitted-letter
apogee|apoge|medium|astronomy_space|ENG-006-CP006|omitted-letter
arthritis|arthrtis|medium|medicine_conditions|ENG-006-CP005|omitted-letter
avalanche|avlanche|medium|earth_weather|ENG-006-CP005|omitted-letter
bandwidth|bandwdth|medium|computing_digital|ENG-006-CP006|omitted-letter
client|cleint|medium|computing_digital|ENG-006-CP006|letter-order
cosmogony|cosmgony|medium|astronomy_space|ENG-006-CP006|omitted-letter
cotyledon|cotyldon|medium|botany_plants|ENG-006-CP006|omitted-letter
echolalia|echlalia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
ecology|eclogy|medium|environment_resources|ENG-006-CP005|omitted-letter
ecosystem|ecsystem|medium|environment_resources|ENG-006-CP005|omitted-letter
ectotherm|ecttherm|medium|biology_ecology|ENG-006-CP003|omitted-letter
endotherm|endtherm|medium|biology_ecology|ENG-006-CP003|omitted-letter
erosion|erotion|medium|environment_resources|ENG-006-CP005|ending-pattern
estuary|estuery|medium|geography_landforms|ENG-006-CP005|ending-pattern
foetus|fetus|medium|biology_anatomy|ENG-006-CP005|omitted-letter
frugivore|frgivore|medium|biology_ecology|ENG-006-CP003|omitted-letter
hepatitis|heptitis|medium|medicine_conditions|ENG-006-CP005|omitted-letter
lagoon|lagon|medium|geography_landforms|ENG-006-CP005|omitted-letter
landslide|landslde|medium|earth_weather|ENG-006-CP005|omitted-letter
latency|latancy|medium|computing_digital|ENG-006-CP006|internal-pattern
loggia|logia|medium|architecture_buildings|ENG-006-CP006|omitted-letter
marsupial|marspial|medium|biology_ecology|ENG-006-CP003|omitted-letter
meteorite|metorite|medium|astronomy_space|ENG-006-CP006|omitted-letter
nostalgia|nostlgia|medium|medical_psychological|ENG-006-CP003|omitted-letter
oedema|oedma|medium|medicine_conditions|ENG-006-CP005|omitted-letter
oviparous|ovparous|medium|biology_ecology|ENG-006-CP003|omitted-letter
palilalia|pallalia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
paralysis|parlysis|medium|medical_psychological|ENG-006-CP003|omitted-letter
peninsula|pennsula|medium|geography_landforms|ENG-006-CP005|omitted-letter
phobia|phbia|medium|medical_psychological|ENG-006-CP003|omitted-letter
pyromania|pyrmania|medium|medical_psychological|ENG-006-CP003|omitted-letter
sepsis|sespis|medium|medicine_conditions|ENG-006-CP005|letter-order
supernova|suprnova|medium|astronomy_space|ENG-006-CP006|omitted-letter
symbiosis|symbosis|medium|science_nature|ENG-006-CP002|omitted-letter
tissue|tisue|medium|biology_anatomy|ENG-006-CP005|omitted-letter
valley|valey|medium|geography_landforms|ENG-006-CP005|omitted-letter
vestibule|vestbule|medium|architecture_buildings|ENG-006-CP006|omitted-letter
watershed|watrshed|medium|geography_landforms|ENG-006-CP005|omitted-letter
amnesia|amnsia|medium|medical_psychological|ENG-006-CP003|omitted-letter
anaemia|anemia|medium|medical_psychological|ENG-006-CP003|omitted-letter
aphasia|afasia|medium|medical_psychological|ENG-006-CP003|omitted-letter
aphonia|afonia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
aseptic|asptic|medium|material_properties|ENG-006-CP003|omitted-letter
astrologer|astrloger|medium|professions_specialists|ENG-006-CP002|omitted-letter
astronomer|astrnomer|medium|professions_specialists|ENG-006-CP002|omitted-letter
balustrade|balstrade|medium|architecture_buildings|ENG-006-CP006|omitted-letter
biomass|biomas|medium|environment_resources|ENG-006-CP005|omitted-letter
botanist|botnist|medium|professions_specialists|ENG-006-CP002|omitted-letter
bradylalia|brdylalia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
bronchitis|brnchitis|medium|medicine_conditions|ENG-006-CP005|omitted-letter
buoyancy|buoyency|medium|science_physics|ENG-006-CP005|internal-pattern
chromosome|chrmosome|medium|biology_anatomy|ENG-006-CP005|omitted-letter
conductive|condctive|medium|material_properties|ENG-006-CP003|omitted-letter
coprolalia|coprlalia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
decomposer|decmposer|medium|biology_ecology|ENG-006-CP003|omitted-letter
dermatitis|dermtitis|medium|medicine_conditions|ENG-006-CP005|omitted-letter
drizzle|drizle|medium|earth_weather|ENG-006-CP005|omitted-letter
drought|drught|medium|earth_weather|ENG-006-CP005|omitted-letter
dysarthria|dysrthria|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
dysprosody|dysprsody|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
earthquake|earthqake|medium|earth_weather|ENG-006-CP005|omitted-letter
emulsion|emultion|medium|chemistry_materials|ENG-006-CP006|ending-pattern
friction|fricsion|medium|science_physics|ENG-006-CP005|ending-pattern
geothermal|gethermal|medium|environment_resources|ENG-006-CP005|omitted-letter
glacier|glaceir|medium|geography_landforms|ENG-006-CP005|letter-order
hydrolysis|hydrlysis|medium|chemistry_materials|ENG-006-CP006|omitted-letter
indigenous|indgenous|medium|biology_ecology|ENG-006-CP003|omitted-letter
insulating|inslating|medium|material_properties|ENG-006-CP003|omitted-letter
meiosis|mieosis|medium|biology_anatomy|ENG-006-CP005|letter-order
monsoon|monson|medium|earth_weather|ENG-006-CP005|omitted-letter
mutation|mutasion|medium|biology_anatomy|ENG-006-CP005|ending-pattern
organism|orgnism|medium|biology_anatomy|ENG-006-CP005|omitted-letter
perigee|perige|medium|astronomy_space|ENG-006-CP006|omitted-letter
perihelion|perhelion|medium|astronomy_space|ENG-006-CP006|omitted-letter
plateau|plteau|medium|geography_landforms|ENG-006-CP005|omitted-letter
presbyopia|prsbyopia|medium|medicine_conditions|ENG-006-CP005|omitted-letter
rhizome|rhzome|medium|botany_plants|ENG-006-CP006|omitted-letter
rotation|rotasion|medium|astronomy_space|ENG-006-CP006|ending-pattern
stammer|stamer|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
steeple|steple|medium|architecture_buildings|ENG-006-CP006|omitted-letter
tachylalia|tachyllia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
vaccine|vacine|medium|biology_anatomy|ENG-006-CP005|omitted-letter
vertebrate|vertbrate|medium|biology_ecology|ENG-006-CP003|omitted-letter
viscous|viscus|medium|material_properties|ENG-006-CP003|omitted-letter
viviparous|vivparous|medium|biology_ecology|ENG-006-CP003|omitted-letter
weathering|wethering|medium|environment_resources|ENG-006-CP005|omitted-letter
agraphia|agrafia|medium|speech_language_disorders|ENG-006-CP006|omitted-letter
aphelion|afelion|medium|astronomy_space|ENG-006-CP006|omitted-letter
archivist|archvist|medium|professions_specialists|ENG-006-CP002|omitted-letter
blizzard|blizard|medium|earth_weather|ENG-006-CP005|omitted-letter
bradycardia|brdycardia|medium|medicine_conditions|ENG-006-CP005|omitted-letter
buttress|butress|medium|architecture_buildings|ENG-006-CP006|omitted-letter
cosmology|cosmlogy|hard|astronomy_space|ENG-006-CP006|omitted-letter
deciduous|decduous|hard|botany_plants|ENG-006-CP006|omitted-letter
ecologist|eclogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
epiphyte|epifyte|hard|botany_plants|ENG-006-CP006|omitted-letter
firewall|firewal|hard|computing_digital|ENG-006-CP006|omitted-letter
geologist|gelogist|hard|professions_specialists|ENG-006-CP002|omitted-letter
insectivore|insctivore|hard|biology_ecology|ENG-006-CP003|omitted-letter
insomnia|insmnia|hard|medical_psychological|ENG-006-CP003|omitted-letter
interpreter|intrpreter|hard|professions_specialists|ENG-006-CP002|omitted-letter
magnetic|magntic|hard|material_properties|ENG-006-CP003|omitted-letter
megalomania|meglomania|hard|medical_psychological|ENG-006-CP003|omitted-letter
migratory|migrtory|hard|biology_ecology|ENG-006-CP003|omitted-letter
mutualism|mutalism|hard|science_nature|ENG-006-CP002|omitted-letter
oxidation|oxidasion|hard|chemistry_materials|ENG-006-CP006|ending-pattern
permeable|permeible|hard|material_properties|ENG-006-CP003|ending-pattern
phishing|phshing|hard|computing_digital|ENG-006-CP006|omitted-letter
radiation|radiasion|hard|science_physics|ENG-006-CP005|ending-pattern
radioactive|radoactive|hard|material_properties|ENG-006-CP003|omitted-letter
reduction|reducsion|hard|chemistry_materials|ENG-006-CP006|ending-pattern
renewable|renewible|hard|environment_resources|ENG-006-CP005|ending-pattern
tachycardia|tachycrdia|hard|medicine_conditions|ENG-006-CP005|omitted-letter
titration|titrasion|hard|chemistry_materials|ENG-006-CP006|ending-pattern
transept|trnsept|hard|architecture_buildings|ENG-006-CP006|omitted-letter
tributary|tributery|hard|geography_landforms|ENG-006-CP005|ending-pattern
urologist|urlogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
agronomist|agrnomist|hard|advanced_specialists|ENG-006-CP003|omitted-letter
autotroph|autotrof|hard|biology_ecology|ENG-006-CP003|omitted-letter
colonnade|colonade|hard|architecture_buildings|ENG-006-CP006|omitted-letter
conduction|conducsion|hard|science_physics|ENG-006-CP005|ending-pattern
convection|convecsion|hard|science_physics|ENG-006-CP005|ending-pattern
corrosive|corosive|hard|material_properties|ENG-006-CP003|omitted-letter
cytologist|cytlogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
debugging|debuging|hard|computing_digital|ENG-006-CP006|omitted-letter
dysphonia|dysfonia|hard|speech_language_disorders|ENG-006-CP006|omitted-letter
evergreen|evergren|hard|botany_plants|ENG-006-CP006|omitted-letter
filtration|filtrasion|hard|science_nature|ENG-006-CP002|ending-pattern
fission|fision|hard|science_physics|ENG-006-CP005|omitted-letter
geneticist|genticist|hard|medical_specialists|ENG-006-CP005|omitted-letter
halophyte|halofyte|hard|botany_plants|ENG-006-CP006|omitted-letter
herbaceous|herbceous|hard|botany_plants|ENG-006-CP006|omitted-letter
hurricane|huricane|hard|earth_weather|ENG-006-CP005|omitted-letter
ionisation|ionisasion|hard|science_physics|ENG-006-CP005|ending-pattern
mesophyte|mesofyte|hard|botany_plants|ENG-006-CP006|omitted-letter
metabolism|metbolism|hard|biology_anatomy|ENG-006-CP005|omitted-letter
mycologist|myclogist|hard|advanced_specialists|ENG-006-CP003|omitted-letter
nephritis|nefritis|hard|medicine_conditions|ENG-006-CP005|omitted-letter
oncologist|onclogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
piscivore|piscvore|hard|biology_ecology|ENG-006-CP003|omitted-letter
reflection|reflecsion|hard|science_physics|ENG-006-CP005|ending-pattern
refraction|refracsion|hard|science_physics|ENG-006-CP005|ending-pattern
refractory|refrctory|hard|material_properties|ENG-006-CP003|omitted-letter
revolution|revolusion|hard|astronomy_space|ENG-006-CP006|ending-pattern
satellite|satelite|hard|astronomy_space|ENG-006-CP006|omitted-letter
scavenger|scvenger|hard|biology_ecology|ENG-006-CP003|omitted-letter
succulent|suculent|hard|botany_plants|ENG-006-CP006|omitted-letter
suspension|suspention|hard|chemistry_materials|ENG-006-CP006|ending-pattern
virologist|virlogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
viscosity|viscsity|hard|science_physics|ENG-006-CP005|omitted-letter
xerophyte|xerofyte|hard|botany_plants|ENG-006-CP006|omitted-letter
acrophobia|acrofobia|hard|medical_psychological|ENG-006-CP003|omitted-letter
antiseptic|antseptic|hard|material_properties|ENG-006-CP003|omitted-letter
astigmatism|astgmatism|hard|medicine_conditions|ENG-006-CP005|omitted-letter
combustible|combustable|hard|material_properties|ENG-006-CP003|ending-pattern
dysgraphia|dysgrafia|hard|speech_language_disorders|ENG-006-CP006|omitted-letter
etymologist|etymlogist|hard|experts_studies|ENG-006-CP001|omitted-letter
evaporation|evaporasion|hard|science_nature|ENG-006-CP002|ending-pattern
genealogist|genalogist|hard|experts_studies|ENG-006-CP001|omitted-letter
germination|germinasion|hard|science_nature|ENG-006-CP002|ending-pattern
gravitation|gravitasion|hard|science_physics|ENG-006-CP005|ending-pattern
hibernation|hibernasion|hard|science_nature|ENG-006-CP002|ending-pattern
histologist|histlogist|hard|medical_specialists|ENG-006-CP005|omitted-letter
hydrophyte|hydrofyte|hard|botany_plants|ENG-006-CP006|omitted-letter
impermeable|impermeible|hard|material_properties|ENG-006-CP003|ending-pattern
neurologist|nerologist|hard|advanced_specialists|ENG-006-CP003|omitted-letter
numismatist|numsmatist|hard|experts_studies|ENG-006-CP001|omitted-letter
optician|optcian|hard|professions_specialists|ENG-006-CP002|omitted-letter
paraphasia|parafasia|hard|speech_language_disorders|ENG-006-CP006|omitted-letter
pathologist|pathlogist|hard|professions_specialists|ENG-006-CP002|omitted-letter
peripheral|periferal|hard|computing_digital|ENG-006-CP006|omitted-letter
radiologist|radologist|hard|medical_specialists|ENG-006-CP005|omitted-letter
`.trim();
export const ENG007_CP004_ENTRIES_V1=Object.freeze(RAW.split("\n").map((line,index)=>{
  const [correct,misspelling,difficulty,domain,sourceRef,trap]=line.split("|") as [string,string,Eng007Difficulty,string,string,Eng007SpellingTrap];
  return{id:`SPL004-${String(index+1).padStart(3,"0")}`,correct,misspelling,difficulty,domain,sourceRef,trap}as const;
}));
export function eng007Cp004PoolV1(difficulty:Eng007Difficulty){return ENG007_CP004_ENTRIES_V1.filter(x=>x.difficulty===difficulty);}
