import { buildGeoTrnQl, finalizeGeoTrnCp, auditGeoTrnCp } from "./geo-trn-001-review-builder";
const SRC=["NCERT-CLASS12-INDIA-PEOPLE-ECONOMY-TRANSPORT-COMMUNICATION","MINISTRY-OF-RAILWAYS-INDIA","DEDICATED-FREIGHT-CORRIDOR-CORPORATION-INDIA"] as const;
const q=(key:string,name:string,rows:readonly any[])=>buildGeoTrnQl(key,name,rows.map((r:any)=>({...r,sourceIds:SRC})) as any);
const QLS=Object.freeze([
q("RAILWAY-NETWORK-FUNCTIONS","Railway network and transport functions",[
{stem:"Which transport mode is especially suitable for moving large volumes of passengers and bulk freight over long distances on land?",answer:"Railways",distractors:["Village paths","Pipelines only","Inland ferries only"],explanation:"Railways combine high carrying capacity with long-distance efficiency for both passengers and freight.",sourceFactId:"RAIL-FUNCTION"},
{stem:"Why are railways important to India's economy?",answer:"They connect production regions, markets, cities and ports",distractors:["They serve only tourism","They move no freight","They replace all roads"],explanation:"Railways integrate major economic regions through large-scale movement of people and goods.",sourceFactId:"RAIL-ECONOMIC-ROLE"},
{stem:"Consider the statements: I. Railways carry bulk freight. II. Railways also support long-distance passenger movement. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both functions are central to India's railway network.",sourceFactId:"RAIL-FUNCTION-STATEMENT"},
{stem:"Which pair is correctly matched in transport geography?",answer:"Railway — high-capacity land transport",distractors:["Railway — sea transport","Railway — crude-oil pipeline","Railway — air corridor"],explanation:"Railways are a high-capacity land transport system.",sourceFactId:"RAIL-FUNCTION-MATCH"},
{stem:"Which commodity is especially suited to bulk rail movement?",answer:"Coal",distractors:["Electronic mail","Natural gas through a pipeline","Air passengers"],explanation:"Heavy bulk commodities such as coal are efficiently moved by rail over long inland distances.",sourceFactId:"RAIL-BULK"},
{stem:"A transport system carries coal, steel, grain and millions of passengers across long inland routes. Which mode is it?",answer:"Railways",distractors:["Pipeline only","Air transport only","Village roads only"],explanation:"The mix of bulk freight and mass passenger movement strongly indicates rail transport.",sourceFactId:"RAIL-CLUE"}
]),
q("RAILWAY-GAUGES","Railway gauges and network standardisation",[
{stem:"Which railway gauge is the dominant standard on the Indian Railways network?",answer:"Broad gauge",distractors:["Metre gauge only","Narrow gauge only","Monorail gauge"],explanation:"Broad gauge forms the overwhelming majority of the modern Indian Railways network.",sourceFactId:"RAIL-BROAD-GAUGE"},
{stem:"Why does gauge standardisation improve railway operations?",answer:"It reduces breaks of gauge and allows smoother movement of trains",distractors:["It increases transshipment","It prevents through running","It eliminates stations"],explanation:"A common gauge allows trains and freight to move across wider networks without changing rolling stock.",sourceFactId:"RAIL-GAUGE-STANDARD"},
{stem:"Consider the statements: I. Broad gauge is dominant in India. II. Converting smaller gauges can improve network integration. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Gauge conversion reduces operational fragmentation.",sourceFactId:"RAIL-GAUGE-STATEMENT"},
{stem:"Which pair is correctly matched in railway gauge geography?",answer:"Broad gauge — dominant Indian Railways standard",distractors:["Narrow gauge — dominant national standard","Metre gauge — only gauge in India","Broad gauge — inland waterway"],explanation:"Broad gauge is the main standard across the Indian Railways system.",sourceFactId:"RAIL-GAUGE-MATCH"},
{stem:"What problem occurs when two connected railway lines use different gauges?",answer:"Break of gauge",distractors:["Port congestion only","Air turbulence","Pipeline leakage"],explanation:"Passengers or freight may need to be transferred between trains where gauges differ.",sourceFactId:"RAIL-BREAK-GAUGE"},
{stem:"A programme converts metre-gauge routes to broad gauge. What is the main network benefit?",answer:"Better interoperability",distractors:["More breaks of gauge","Less route continuity","Elimination of freight"],explanation:"A common gauge improves through movement and operational integration.",sourceFactId:"RAIL-GAUGE-CLUE"}
]),
q("RAILWAY-ELECTRIFICATION","Railway electrification and traction",[
{stem:"What is one major operational advantage of railway electrification?",answer:"Reduced dependence on diesel traction",distractors:["Elimination of tracks","Need for more steam locomotives","Removal of signalling"],explanation:"Electric traction reduces direct diesel use and can improve energy efficiency and performance.",sourceFactId:"RAIL-ELECTRIFICATION"},
{stem:"Which energy source directly powers an electric locomotive?",answer:"Electricity",distractors:["Crude oil burned onboard only","Coal in a steam boiler only","Natural gas pipeline only"],explanation:"Electric locomotives draw power from the railway's electrical traction system.",sourceFactId:"RAIL-ELECTRIC-TRACTION"},
{stem:"Consider the statements: I. Electrification can reduce diesel use. II. Electric traction can support high-capacity rail operations. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are important reasons for railway electrification.",sourceFactId:"RAIL-ELECTRIFICATION-STATEMENT"},
{stem:"Which pair is correctly matched in railway traction?",answer:"Electric locomotive — overhead electrical supply",distractors:["Electric locomotive — jute fibre","Diesel locomotive — railway gauge","Steam engine — pipeline gas only"],explanation:"Electric trains normally receive traction power from electrified railway infrastructure.",sourceFactId:"RAIL-ELECTRIFICATION-MATCH"},
{stem:"Which railway change most directly reduces use of diesel locomotives?",answer:"Route electrification",distractors:["Gauge narrowing","Track removal","Station closure"],explanation:"Electrified routes allow electric locomotives and trainsets to replace diesel traction.",sourceFactId:"RAIL-ELECTRIFICATION-USE"},
{stem:"A rail corridor receives overhead traction equipment along its route. What upgrade is being carried out?",answer:"Railway electrification",distractors:["Gauge removal","Port dredging","Road widening"],explanation:"Overhead traction equipment is a defining feature of electrified railway lines.",sourceFactId:"RAIL-ELECTRIFICATION-CLUE"}
]),
q("MAJOR-TRUNK-RAIL-ROUTES","Major trunk rail routes and metropolitan connectivity",[
{stem:"Why are trunk railway routes important?",answer:"They connect major cities and economic regions over long distances",distractors:["They serve only one village","They operate only inside ports","They carry no passengers"],explanation:"Trunk routes form the main long-distance axes of the national railway network.",sourceFactId:"RAIL-TRUNK-ROLE"},
{stem:"Which cities are linked by major trunk railway routes in India's metropolitan network?",answer:"Delhi, Mumbai, Chennai and Kolkata",distractors:["Only Leh and Kargil","Only Panaji and Shimla","Only small village centres"],explanation:"India's largest metropolitan regions are interconnected by major long-distance rail corridors.",sourceFactId:"RAIL-TRUNK-METROS"},
{stem:"Consider the statements: I. Trunk routes carry long-distance traffic. II. They link major industrial and population centres. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"High-volume long-distance movement defines trunk railway routes.",sourceFactId:"RAIL-TRUNK-STATEMENT"},
{stem:"Which pair is correctly matched in railway hierarchy?",answer:"Trunk route — major long-distance corridor",distractors:["Trunk route — village footpath","Branch line — international air route","Rail corridor — pipeline only"],explanation:"Trunk routes connect major centres across long distances.",sourceFactId:"RAIL-TRUNK-MATCH"},
{stem:"Why do major trunk routes usually have high traffic density?",answer:"They connect large cities, industrial regions and markets",distractors:["They avoid population centres","They carry no freight","They serve only remote farms"],explanation:"Demand is concentrated where major population and economic centres are linked.",sourceFactId:"RAIL-TRUNK-DENSITY"},
{stem:"A rail line carries heavy passenger and freight traffic between major metropolitan regions. What type of route is it?",answer:"Trunk railway route",distractors:["Village spur only","Industrial siding only","Mountain toy train only"],explanation:"High-volume long-distance metropolitan movement is characteristic of trunk routes.",sourceFactId:"RAIL-TRUNK-CLUE"}
]),
q("KONKAN-RAILWAY","Konkan Railway geography",[
{stem:"Which railway route runs along India's western coastal belt through difficult terrain?",answer:"Konkan Railway",distractors:["Darjeeling Himalayan Railway","Kalka-Shimla Railway","Western DFC"],explanation:"The Konkan Railway runs along the western coast through Maharashtra, Goa and Karnataka.",sourceFactId:"RAIL-KONKAN"},
{stem:"Which states are directly linked by the Konkan Railway corridor?",answer:"Maharashtra, Goa and Karnataka",distractors:["Punjab, Haryana and Rajasthan","Bihar, Jharkhand and Odisha","Assam, Meghalaya and Tripura"],explanation:"The route follows the Konkan coast through Maharashtra and Goa into coastal Karnataka.",sourceFactId:"RAIL-KONKAN-STATES"},
{stem:"Why was construction of the Konkan Railway especially challenging?",answer:"The route crosses steep Western Ghats, rivers and unstable terrain",distractors:["The entire route is flat desert","There are no rivers","It lies only in plains"],explanation:"Tunnels, bridges and cuttings were required across complex coastal and mountain terrain.",sourceFactId:"RAIL-KONKAN-TERRAIN"},
{stem:"Consider the statements: I. Konkan Railway follows the west coast. II. It passes through Goa. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both are defining facts of the Konkan Railway.",sourceFactId:"RAIL-KONKAN-STATEMENT"},
{stem:"Which pair is correctly matched in railway geography?",answer:"Konkan Railway — western coastal belt",distractors:["Konkan Railway — eastern Himalaya","Konkan Railway — Thar Desert","Konkan Railway — Ganga plain only"],explanation:"The route follows India's western coastal Konkan region.",sourceFactId:"RAIL-KONKAN-MATCH"},
{stem:"A railway map shows a line linking coastal Maharashtra, Goa and Karnataka. Which route is it?",answer:"Konkan Railway",distractors:["Kalka-Shimla Railway","Eastern DFC","Darjeeling Himalayan Railway"],explanation:"Those states and the western coastal alignment identify the Konkan Railway.",sourceFactId:"RAIL-KONKAN-CLUE"}
]),
q("MOUNTAIN-RAILWAYS","Mountain railways and difficult terrain",[
{stem:"Darjeeling Himalayan Railway is located in which state?",answer:"West Bengal",distractors:["Himachal Pradesh","Tamil Nadu","Maharashtra"],explanation:"The Darjeeling Himalayan Railway climbs from the plains of West Bengal into the Darjeeling hills.",sourceFactId:"RAIL-DHR"},
{stem:"Kalka-Shimla Railway is located in which state/region?",answer:"Himachal Pradesh",distractors:["West Bengal","Kerala","Gujarat"],explanation:"The Kalka-Shimla mountain railway serves the Himalayan region of Himachal Pradesh.",sourceFactId:"RAIL-KSR"},
{stem:"Nilgiri Mountain Railway is located in which state?",answer:"Tamil Nadu",distractors:["West Bengal","Himachal Pradesh","Assam"],explanation:"The Nilgiri Mountain Railway operates in the Nilgiri hills of Tamil Nadu.",sourceFactId:"RAIL-NMR"},
{stem:"Consider the statements: I. Darjeeling Himalayan Railway is in West Bengal. II. Nilgiri Mountain Railway is in Tamil Nadu. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Both state-location pairs are correct.",sourceFactId:"RAIL-MOUNTAIN-STATEMENT"},
{stem:"Which pair is correctly matched in mountain railway geography?",answer:"Kalka-Shimla — Himachal Pradesh",distractors:["Kalka-Shimla — Tamil Nadu","Nilgiri — West Bengal","Darjeeling — Kerala"],explanation:"Kalka-Shimla serves Himachal Pradesh, Nilgiri is in Tamil Nadu and Darjeeling is in West Bengal.",sourceFactId:"RAIL-MOUNTAIN-MATCH"},
{stem:"Why do mountain railways require special engineering?",answer:"They must negotiate steep gradients and difficult relief",distractors:["Mountains are completely flat","They cross no rivers","They use no bridges or tunnels"],explanation:"Sharp curves, gradients, bridges and tunnels are often necessary in mountain terrain.",sourceFactId:"RAIL-MOUNTAIN-ENGINEERING"}
]),
q("RAILWAY-ZONES-AND-ADMINISTRATION","Railway zones and network administration",[
{stem:"Why is the Indian Railways network divided into zones?",answer:"For administrative and operational management",distractors:["To create different gauges in every state","To prevent inter-zone trains","To replace railway stations"],explanation:"Zones help manage a very large national railway system through regional administrative units.",sourceFactId:"RAIL-ZONE-PURPOSE"},
{stem:"Which organisation operates India's national railway network?",answer:"Indian Railways",distractors:["NHAI","AAI","IWAI"],explanation:"Indian Railways functions under the Ministry of Railways and operates the national rail system.",sourceFactId:"RAIL-IR"},
{stem:"Consider the statements: I. Railway zones are administrative units. II. Trains can operate across zonal boundaries. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Zones organise management but do not divide the national network into isolated systems.",sourceFactId:"RAIL-ZONE-STATEMENT"},
{stem:"Which pair is correctly matched in railway administration?",answer:"Ministry of Railways — Indian Railways",distractors:["NHAI — railway zones","AAI — freight rail corridors","IWAI — passenger rail network"],explanation:"Indian Railways operates under the Ministry of Railways.",sourceFactId:"RAIL-ZONE-MATCH"},
{stem:"What is the main reason for regional railway administration?",answer:"Manage operations, infrastructure and services across a vast network",distractors:["Prevent national connectivity","Separate every state permanently","Eliminate trunk routes"],explanation:"Regional administration makes network management more practical.",sourceFactId:"RAIL-ZONE-MANAGEMENT"},
{stem:"A railway division reports to a larger regional administrative unit. What is that larger unit?",answer:"Railway zone",distractors:["National Highway","Airport authority","Port trust"],explanation:"Divisions are organised under railway zones within Indian Railways administration.",sourceFactId:"RAIL-ZONE-CLUE"}
]),
q("DEDICATED-FREIGHT-CORRIDORS","Dedicated Freight Corridors",[
{stem:"What is the main purpose of a Dedicated Freight Corridor?",answer:"Provide high-capacity railway routes primarily for freight",distractors:["Carry only urban metro passengers","Replace all roads","Serve only tourist trains"],explanation:"Dedicated Freight Corridors separate large freight flows from mixed passenger-heavy routes to improve capacity and efficiency.",sourceFactId:"RAIL-DFC-PURPOSE"},
{stem:"Which organisation develops India's Dedicated Freight Corridors?",answer:"DFCCIL",distractors:["NHAI","AAI","IWAI"],explanation:"Dedicated Freight Corridor Corporation of India Limited develops and operates the major dedicated freight corridors.",sourceFactId:"RAIL-DFCCIL"},
{stem:"Consider the statements: I. Dedicated Freight Corridors focus on goods movement. II. They can reduce pressure on congested mixed-traffic routes. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Separating freight from passenger-heavy lines improves capacity and reliability.",sourceFactId:"RAIL-DFC-STATEMENT"},
{stem:"Which pair is correctly matched in freight-rail geography?",answer:"DFCCIL — Dedicated Freight Corridors",distractors:["DFCCIL — national highways","DFCCIL — airports","DFCCIL — inland waterways"],explanation:"DFCCIL is the specialised freight-corridor railway organisation.",sourceFactId:"RAIL-DFC-MATCH"},
{stem:"Which commodity flow is especially suited to dedicated freight rail?",answer:"Large-volume industrial and container freight",distractors:["Only local pedestrians","Only air mail","Only village bicycles"],explanation:"Dedicated rail corridors are designed for high-volume goods movement.",sourceFactId:"RAIL-DFC-FREIGHT"},
{stem:"A new rail line is built primarily to move freight and free capacity on existing mixed routes. What is it?",answer:"Dedicated Freight Corridor",distractors:["Mountain railway","Urban tram only","National Highway"],explanation:"Its defining purpose is dedicated high-capacity freight movement.",sourceFactId:"RAIL-DFC-CLUE"}
]),
q("EASTERN-WESTERN-DFC-GEOGRAPHY","Eastern and Western DFC geography",[
{stem:"Which Dedicated Freight Corridor is aligned with the major Delhi-Mumbai industrial-freight axis?",answer:"Western Dedicated Freight Corridor",distractors:["Eastern Dedicated Freight Corridor","Konkan Railway","North-South road corridor"],explanation:"The Western DFC forms the major freight spine linking the Delhi region with western India.",sourceFactId:"RAIL-WDFC"},
{stem:"Which Dedicated Freight Corridor serves a major northern-eastern freight axis?",answer:"Eastern Dedicated Freight Corridor",distractors:["Western Dedicated Freight Corridor","Golden Quadrilateral","Konkan Railway"],explanation:"The Eastern DFC serves freight movement across northern and eastern India.",sourceFactId:"RAIL-EDFC"},
{stem:"Consider the statements: I. Western DFC supports the Delhi-Mumbai axis. II. Eastern DFC supports a northern-eastern freight axis. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"The two corridors serve different major freight geographies.",sourceFactId:"RAIL-DFC-GEO-STATEMENT"},
{stem:"Which pair is correctly matched in freight-corridor geography?",answer:"Western DFC — Delhi-Mumbai axis",distractors:["Western DFC — eastern coal belt only","Eastern DFC — Mumbai port only","Western DFC — mountain toy railway"],explanation:"The Western DFC underpins the Delhi-western India freight corridor.",sourceFactId:"RAIL-DFC-GEO-MATCH"},
{stem:"Which corridor is more directly linked with western industrial and port logistics?",answer:"Western Dedicated Freight Corridor",distractors:["Eastern Dedicated Freight Corridor","Darjeeling Himalayan Railway","Kalka-Shimla Railway"],explanation:"The Western DFC connects the Delhi region with western industrial and port systems.",sourceFactId:"RAIL-WDFC-PORT"},
{stem:"A freight map shows one major corridor running westward from the Delhi region and another toward eastern India. What are they?",answer:"Western and Eastern Dedicated Freight Corridors",distractors:["Golden Quadrilateral and Konkan Railway","North-South and East-West roads","Two mountain railways"],explanation:"The map pattern identifies India's two principal dedicated freight-corridor axes.",sourceFactId:"RAIL-DFC-GEO-CLUE"}
]),
q("RAIL-FREIGHT-PASSENGER-CAPACITY-LOGIC","Freight, passenger and capacity logic",[
{stem:"Why can separating freight and passenger traffic improve railway capacity?",answer:"Trains with different speeds and stopping patterns interfere less",distractors:["It removes tracks","It increases gauge breaks","It prevents freight movement"],explanation:"Dedicated paths reduce conflicts between slower freight trains and faster passenger services.",sourceFactId:"RAIL-CAPACITY-SEPARATION"},
{stem:"Which type of railway traffic usually carries heavier axle loads?",answer:"Freight traffic",distractors:["Pedestrian traffic","Air passengers","Village buses"],explanation:"Freight trains move bulk goods and typically impose heavier loads on track infrastructure.",sourceFactId:"RAIL-FREIGHT-LOAD"},
{stem:"Consider the statements: I. Freight trains and passenger trains have different operating patterns. II. Dedicated freight routes can improve reliability. Which is correct?",answer:"Both I and II are correct",distractors:["Only I is correct","Only II is correct","Neither I nor II is correct"],explanation:"Separating traffic types reduces scheduling conflicts.",sourceFactId:"RAIL-CAPACITY-STATEMENT"},
{stem:"Which pair is correctly matched in railway operations?",answer:"Freight corridor — goods movement",distractors:["Freight corridor — village road","Passenger platform — pipeline","Rail siding — airport runway"],explanation:"Freight corridors are designed around high-volume goods movement.",sourceFactId:"RAIL-CAPACITY-MATCH"},
{stem:"Which network problem can Dedicated Freight Corridors help reduce?",answer:"Congestion on mixed passenger-freight routes",distractors:["Sea-port silting","Air turbulence","Road potholes"],explanation:"Freight diversion can release capacity on conventional rail lines.",sourceFactId:"RAIL-CAPACITY-CONGESTION"},
{stem:"A busy railway carries express trains and slow freight trains on the same tracks. What is the key operational issue?",answer:"Capacity conflict between traffic types",distractors:["Break of sea gauge","Airport congestion","Pipeline pressure only"],explanation:"Different train speeds and stopping patterns compete for limited track capacity.",sourceFactId:"RAIL-CAPACITY-CLUE"}
]),
q("INTEGRATED-RAILWAY-MAP-REASONING","Integrated railway-map reasoning",[
{stem:"Which route is identified by Maharashtra, Goa and Karnataka along the west coast?",answer:"Konkan Railway",distractors:["Eastern DFC","Kalka-Shimla Railway","Golden Quadrilateral"],explanation:"The Konkan Railway follows the western coastal belt through those three states.",sourceFactId:"RAIL-INTEGRATED-1"},
{stem:"Which set contains only mountain railways?",answer:"Darjeeling Himalayan, Kalka-Shimla and Nilgiri Mountain Railway",distractors:["Konkan, Western DFC and Eastern DFC","Delhi-Mumbai, Konkan and Golden Quadrilateral","Bokaro, Jharia and Raniganj"],explanation:"All three are famous mountain railway systems.",sourceFactId:"RAIL-INTEGRATED-2"},
{stem:"Which organisation is the strongest clue for dedicated freight-rail development?",answer:"DFCCIL",distractors:["NHAI","AAI","BRO"],explanation:"DFCCIL is dedicated to freight-corridor rail infrastructure.",sourceFactId:"RAIL-INTEGRATED-3"},
{stem:"Which comparison is correct for Indian railways?",answer:"Konkan Railway is terrain-oriented coastal infrastructure, while DFCs are freight-capacity corridors",distractors:["Both are mountain toy trains","Both are highways","DFCs carry only tourists"],explanation:"The two systems solve different transport problems.",sourceFactId:"RAIL-INTEGRATED-4"},
{stem:"Which railway change most directly improves network interoperability?",answer:"Gauge standardisation",distractors:["Adding more gauge breaks","Removing trunk routes","Closing junctions"],explanation:"A common gauge allows through movement of rolling stock.",sourceFactId:"RAIL-INTEGRATED-5"},
{stem:"A rail map highlights broad gauge trunk routes, a west-coast line and two major freight axes. What does this illustrate?",answer:"Different railway systems serve passenger, regional and freight functions",distractors:["All railways serve identical purposes","Only mountain railways matter","Freight cannot use rail"],explanation:"India's rail geography includes multiple route types with distinct operational roles.",sourceFactId:"RAIL-INTEGRATED-6"}
])
]);
export const GEO_TRN_001_CP002_REVIEW_BATCH_V1=finalizeGeoTrnCp(2,QLS);
export function auditGeoTrn001Cp002ReviewBatchV1(){return auditGeoTrnCp(2,QLS,GEO_TRN_001_CP002_REVIEW_BATCH_V1);}
