import type { EnglishDifficulty, GerundInfinitiveParticipleRuleId } from "../../../../core/types";

export interface GerundInfinitiveParticipleSceneV1 {
  id: string;
  difficulty: EnglishDifficulty;
  ruleId: GerundInfinitiveParticipleRuleId;
  domain: string;
  correctSegments: readonly [string, string, string, string];
  errorSegments: readonly [string, string, string, string];
  errorIndex: 0 | 1 | 2 | 3;
  correction: string;
  reason: string;
}

const q = (
  id: string, difficulty: EnglishDifficulty, ruleId: GerundInfinitiveParticipleRuleId, domain: string,
  correctSegments: GerundInfinitiveParticipleSceneV1["correctSegments"], errorSegments: GerundInfinitiveParticipleSceneV1["errorSegments"],
  errorIndex: GerundInfinitiveParticipleSceneV1["errorIndex"], correction: string, reason: string,
): GerundInfinitiveParticipleSceneV1 => ({ id, difficulty, ruleId, domain, correctSegments, errorSegments, errorIndex, correction, reason });

export const CP009_SCENES_V1: readonly GerundInfinitiveParticipleSceneV1[] = [
  // EASY
  q("GIP-E01", "easy", "GR-GIP-001", "school", ["The children", "enjoy reading stories", "after lunch", "in the library."], ["The children", "enjoy to read stories", "after lunch", "in the library."], 1, "enjoy reading stories", "The verb 'enjoy' is followed by a gerund, so 'reading' is required."),
  q("GIP-E02", "easy", "GR-GIP-001", "workplace", ["She avoided", "speaking about the dispute", "during the meeting", "with her colleagues."], ["She avoided", "to speak about the dispute", "during the meeting", "with her colleagues."], 1, "speaking about the dispute", "The verb 'avoid' is followed by a gerund, so use 'speaking', not 'to speak'."),
  q("GIP-E03", "easy", "GR-GIP-002", "travel", ["We decided", "to leave early", "because the road", "was becoming crowded."], ["We decided", "leaving early", "because the road", "was becoming crowded."], 1, "to leave early", "The verb 'decide' is normally followed by a to-infinitive, so 'to leave' is required."),
  q("GIP-E04", "easy", "GR-GIP-002", "education", ["He hopes", "to join the course", "after completing", "his final examination."], ["He hopes", "joining the course", "after completing", "his final examination."], 1, "to join the course", "The verb 'hope' is followed by a to-infinitive in this construction."),
  q("GIP-E05", "easy", "GR-GIP-003", "health", ["The doctor advised", "the patient to rest", "for two days", "after the treatment."], ["The doctor advised", "the patient resting", "for two days", "after the treatment."], 1, "the patient to rest", "After 'advise' with an object, use object + to-infinitive: 'the patient to rest'."),
  q("GIP-E06", "easy", "GR-GIP-003", "classroom", ["The teacher asked", "the students to submit", "their notebooks", "before Friday."], ["The teacher asked", "the students submitting", "their notebooks", "before Friday."], 1, "the students to submit", "After 'ask' with an object, use object + to-infinitive: 'the students to submit'."),
  q("GIP-E07", "easy", "GR-GIP-004", "public-service", ["The guard made", "the visitors wait", "outside the hall", "for a few minutes."], ["The guard made", "the visitors to wait", "outside the hall", "for a few minutes."], 1, "the visitors wait", "In the active voice, 'make' takes an object followed by the bare infinitive: 'made the visitors wait'."),
  q("GIP-E08", "easy", "GR-GIP-004", "home", ["Please let", "the child finish", "his meal", "before leaving."], ["Please let", "the child to finish", "his meal", "before leaving."], 1, "the child finish", "The verb 'let' takes an object followed by the bare infinitive: 'let the child finish'."),
  q("GIP-E09", "easy", "GR-GIP-005", "administration", ["You should", "check the form", "before you", "sign it."], ["You should", "to check the form", "before you", "sign it."], 1, "check the form", "A modal verb such as 'should' is followed by the bare infinitive, so use 'check'."),
  q("GIP-E10", "easy", "GR-GIP-005", "office", ["They can", "complete the work", "without any help", "by evening."], ["They can", "to complete the work", "without any help", "by evening."], 1, "complete the work", "A modal verb such as 'can' is followed by the bare infinitive, so use 'complete'."),
  q("GIP-E11", "easy", "GR-GIP-006", "learning", ["She is interested", "in learning French", "before her", "next assignment."], ["She is interested", "in learn French", "before her", "next assignment."], 1, "in learning French", "A verb that follows the preposition 'in' must take the -ing form here: 'in learning'."),
  q("GIP-E12", "easy", "GR-GIP-006", "daily-life", ["He left the room", "without checking", "whether the lights", "were switched off."], ["He left the room", "without check", "whether the lights", "were switched off."], 1, "without checking", "After the preposition 'without', use the gerund: 'without checking'."),
  q("GIP-E13", "easy", "GR-GIP-007", "habit", ["My grandfather", "used to walk", "five kilometres", "every morning."], ["My grandfather", "used to walking", "five kilometres", "every morning."], 1, "used to walk", "'Used to' for a past habit is followed by the base form of the verb: 'used to walk'."),
  q("GIP-E14", "easy", "GR-GIP-007", "workplace", ["She is", "used to working", "late during", "the audit season."], ["She is", "used to work", "late during", "the audit season."], 1, "used to working", "In 'be used to', 'to' is a preposition, so a following verb takes the -ing form: 'used to working'."),
  q("GIP-E15", "easy", "GR-GIP-008", "records", ["The clerk went", "to collect the files", "from the record room", "before lunch."], ["The clerk went", "collecting the files", "from the record room", "before lunch."], 1, "to collect the files", "The to-infinitive can express purpose; the clerk went there in order to collect the files."),
  q("GIP-E16", "easy", "GR-GIP-008", "recruitment", ["We called the office", "to confirm the time", "of the interview", "scheduled for Monday."], ["We called the office", "confirming the time", "of the interview", "scheduled for Monday."], 1, "to confirm the time", "Use the to-infinitive to show the purpose of the call: 'to confirm the time'."),
  q("GIP-E17", "easy", "GR-GIP-009", "office", ["Please remember", "to lock the door", "before you leave", "the office tonight."], ["Please remember", "locking the door", "before you leave", "the office tonight."], 1, "to lock the door", "'Remember to do' refers to an action that still needs to be done; here the door must be locked before leaving."),
  q("GIP-E18", "easy", "GR-GIP-009", "health", ["After the warning,", "he stopped smoking", "for the sake", "of his health."], ["After the warning,", "he stopped to smoke", "for the sake", "of his health."], 1, "he stopped smoking", "'Stop doing' means end an activity; the sentence says he ended the habit of smoking."),
  q("GIP-E19", "easy", "GR-GIP-010", "education", ["Having finished", "the assignment,", "Riya submitted it", "before the deadline."], ["Having finish", "the assignment,", "Riya submitted it", "before the deadline."], 0, "Having finished", "The perfect participle is formed with 'having' + past participle: 'having finished'."),
  q("GIP-E20", "easy", "GR-GIP-010", "records", ["The documents", "submitted yesterday", "are now ready", "for verification."], ["The documents", "submitting yesterday", "are now ready", "for verification."], 1, "submitted yesterday", "The documents received the action, so the past participle 'submitted' is required."),
  // MEDIUM
  q("GIP-M01", "medium", "GR-GIP-001", "management", ["The manager avoids delaying decisions", "when enough information", "is already available", "to the committee."], ["The manager avoids to delay decisions", "when enough information", "is already available", "to the committee."], 0, "The manager avoids delaying decisions", "The verb 'avoid' takes a gerund, so 'delaying' is the correct form."),
  q("GIP-M02", "medium", "GR-GIP-001", "transport", ["Although the route was longer,", "the driver considered", "taking the bypass", "to avoid the traffic."], ["Although the route was longer,", "the driver considered", "to take the bypass", "to avoid the traffic."], 2, "taking the bypass", "The verb 'consider' is followed by a gerund, so use 'taking the bypass'."),
  q("GIP-M03", "medium", "GR-GIP-002", "committee", ["The committee agreed to review", "the revised proposal", "after the secretary", "circulated the notes."], ["The committee agreed reviewing", "the revised proposal", "after the secretary", "circulated the notes."], 0, "The committee agreed to review", "The verb 'agree' is followed by a to-infinitive in this pattern: 'agreed to review'."),
  q("GIP-M04", "medium", "GR-GIP-002", "procurement", ["After discussing the budget,", "the officers finally decided", "to postpone the purchase", "until the next quarter."], ["After discussing the budget,", "the officers finally decided", "postponing the purchase", "until the next quarter."], 2, "to postpone the purchase", "The verb 'decide' takes a to-infinitive here: 'decided to postpone'."),
  q("GIP-M05", "medium", "GR-GIP-003", "workplace", ["The supervisor reminded", "the new employees", "before the shift", "to wear their identity cards."], ["The supervisor reminded", "the new employees", "before the shift", "wearing their identity cards."], 3, "to wear their identity cards.", "After 'remind' with an object, use a to-infinitive for the action: 'reminded them to wear'."),
  q("GIP-M06", "medium", "GR-GIP-003", "sports", ["The coach encouraged the players to practise", "with the new equipment", "before the tournament", "began on Saturday."], ["The coach encouraged the players practising", "with the new equipment", "before the tournament", "began on Saturday."], 0, "The coach encouraged the players to practise", "After 'encourage' with an object, use object + to-infinitive: 'encouraged the players to practise'."),
  q("GIP-M07", "medium", "GR-GIP-004", "public-service", ["Because the queue was growing,", "the officer made", "the applicants wait", "in a separate room."], ["Because the queue was growing,", "the officer made", "the applicants to wait", "in a separate room."], 2, "the applicants wait", "In active voice, 'make' is followed by object + bare infinitive: 'made the applicants wait'."),
  q("GIP-M08", "medium", "GR-GIP-004", "hostel", ["The parents", "did not let their son", "leave the hostel early", "without informing the warden."], ["The parents", "did not let their son", "to leave the hostel early", "without informing the warden."], 2, "leave the hostel early", "After 'let' and its object, use the bare infinitive: 'let their son leave'."),
  q("GIP-M09", "medium", "GR-GIP-005", "recruitment", ["Candidates must carry", "a valid identity card", "when they report", "for document verification."], ["Candidates must to carry", "a valid identity card", "when they report", "for document verification."], 0, "Candidates must carry", "The modal 'must' is followed by the bare infinitive, so 'carry' is correct."),
  q("GIP-M10", "medium", "GR-GIP-005", "engineering", ["During the test,", "the operator was warned", "that the machine may", "stop suddenly."], ["During the test,", "the operator was warned", "that the machine may", "to stop suddenly."], 3, "stop suddenly.", "The modal 'may' is followed by the bare infinitive: 'may stop'."),
  q("GIP-M11", "medium", "GR-GIP-006", "administration", ["Before submitting the form,", "please read the declaration", "without skipping any section", "that asks for consent."], ["Before submitting the form,", "please read the declaration", "without skip any section", "that asks for consent."], 2, "without skipping any section", "After the preposition 'without', a following verb takes the -ing form: 'without skipping'."),
  q("GIP-M12", "medium", "GR-GIP-006", "training", ["The trainees look forward", "to the practical session", "and are interested", "in learning the new procedure."], ["The trainees look forward", "to the practical session", "and are interested", "in learn the new procedure."], 3, "in learning the new procedure.", "After the preposition 'in', use the gerund: 'in learning the new procedure'."),
  q("GIP-M13", "medium", "GR-GIP-007", "customer-service", ["The clerk is used to handling", "several requests at once", "during the busiest", "hours of the day."], ["The clerk is used to handle", "several requests at once", "during the busiest", "hours of the day."], 0, "The clerk is used to handling", "In 'be used to', 'to' is a preposition, so the following verb takes the -ing form."),
  q("GIP-M14", "medium", "GR-GIP-007", "commute", ["When he was younger,", "the officer used to", "travel by bus", "to the district office."], ["When he was younger,", "the officer used to", "travelling by bus", "to the district office."], 2, "travel by bus", "'Used to' for a past habit is followed by the base form: 'used to travel'."),
  q("GIP-M15", "medium", "GR-GIP-008", "education", ["After the final bell,", "the students stayed back", "in the classroom", "to complete the project."], ["After the final bell,", "the students stayed back", "in the classroom", "completing the project."], 3, "to complete the project.", "The to-infinitive states the purpose for staying back: 'to complete the project'."),
  q("GIP-M16", "medium", "GR-GIP-008", "maintenance", ["The technician came to inspect", "the control panel", "after the alarm", "sounded for a second time."], ["The technician came inspecting", "the control panel", "after the alarm", "sounded for a second time."], 0, "The technician came to inspect", "Use the to-infinitive to express the purpose of coming: 'came to inspect'."),
  q("GIP-M17", "medium", "GR-GIP-009", "accounts", ["While walking past the counter,", "the supervisor noticed a mismatch", "and stopped to check", "the disputed entry carefully."], ["While walking past the counter,", "the supervisor noticed a mismatch", "and stopped checking", "the disputed entry carefully."], 2, "and stopped to check", "'Stop to do' means pause one activity in order to do another; here the supervisor paused to check the entry."),
  q("GIP-M18", "medium", "GR-GIP-009", "seminar", ["I clearly remember meeting", "the officer at the seminar", "because he explained", "the new procedure to us."], ["I clearly remember to meet", "the officer at the seminar", "because he explained", "the new procedure to us."], 0, "I clearly remember meeting", "'Remember doing' refers to a memory of a completed past event; the seminar meeting is being recalled."),
  q("GIP-M19", "medium", "GR-GIP-010", "accounts", ["The accountant sent", "the final statement", "to the branch manager", "after having checked the figures."], ["The accountant sent", "the final statement", "to the branch manager", "after having check the figures."], 3, "after having checked the figures.", "After 'having', use the past participle: 'having checked'."),
  q("GIP-M20", "medium", "GR-GIP-010", "selection", ["The committee will review", "only those forms", "submitted before noon", "during today's meeting."], ["The committee will review", "only those forms", "submitting before noon", "during today's meeting."], 2, "submitted before noon", "The forms receive the action, so the past participle 'submitted' is required."),
  // HARD
  q("GIP-H01", "hard", "GR-GIP-001", "recruitment", ["Even after the deadline was extended,", "several applicants admitted", "that they had delayed", "submitting the required certificates."], ["Even after the deadline was extended,", "several applicants admitted", "that they had delayed", "to submit the required certificates."], 3, "submitting the required certificates.", "The verb 'delay' is followed by a gerund, so 'delayed submitting' is the correct pattern."),
  q("GIP-H02", "hard", "GR-GIP-001", "audit", ["The audit team recommended reviewing", "the disputed entries again", "before the report", "was sent to headquarters."], ["The audit team recommended to review", "the disputed entries again", "before the report", "was sent to headquarters."], 0, "The audit team recommended reviewing", "When no object is inserted, 'recommend' can be followed by a gerund: 'recommended reviewing'."),
  q("GIP-H03", "hard", "GR-GIP-002", "engineering", ["Although the first attempt failed,", "the engineers finally managed", "to restore the connection", "before the backup window closed."], ["Although the first attempt failed,", "the engineers finally managed", "restoring the connection", "before the backup window closed."], 2, "to restore the connection", "The verb 'manage' is followed by a to-infinitive: 'managed to restore'."),
  q("GIP-H04", "hard", "GR-GIP-002", "committee", ["The board rejected two options", "but after further discussion", "it eventually agreed", "to reconsider the third proposal."], ["The board rejected two options", "but after further discussion", "it eventually agreed", "reconsidering the third proposal."], 3, "to reconsider the third proposal.", "The verb 'agree' is followed by a to-infinitive in this construction."),
  q("GIP-H05", "hard", "GR-GIP-003", "recruitment", ["The revised notice requires applicants to provide", "two recent photographs", "along with the declaration", "signed on the final page."], ["The revised notice requires applicants providing", "two recent photographs", "along with the declaration", "signed on the final page."], 0, "The revised notice requires applicants to provide", "With a person as object, 'require' takes object + to-infinitive: 'requires applicants to provide'."),
  q("GIP-H06", "hard", "GR-GIP-003", "training", ["During the briefing,", "the officer warned the trainees", "and reminded them", "to keep their phones switched off."], ["During the briefing,", "the officer warned the trainees", "and reminded them", "keeping their phones switched off."], 3, "to keep their phones switched off.", "After 'remind' with an object, use a to-infinitive for the required action."),
  q("GIP-H07", "hard", "GR-GIP-004", "records", ["Although the request was unusual,", "the director would not let", "the staff leave", "before the records were secured."], ["Although the request was unusual,", "the director would not let", "the staff to leave", "before the records were secured."], 2, "the staff leave", "After 'let' and its object, use the bare infinitive: 'let the staff leave'."),
  q("GIP-H08", "hard", "GR-GIP-004", "construction", ["The sudden inspection made the contractor revise", "the safety plan", "before any further work", "could begin on the site."], ["The sudden inspection made the contractor to revise", "the safety plan", "before any further work", "could begin on the site."], 0, "The sudden inspection made the contractor revise", "In active voice, 'make' takes object + bare infinitive: 'made the contractor revise'."),
  q("GIP-H09", "hard", "GR-GIP-005", "examination", ["According to the instructions,", "every candidate who qualifies", "for the final stage must", "report at the centre by eight."], ["According to the instructions,", "every candidate who qualifies", "for the final stage must", "to report at the centre by eight."], 3, "report at the centre by eight.", "The modal 'must' is followed by the bare infinitive, so use 'report'."),
  q("GIP-H10", "hard", "GR-GIP-005", "emergency", ["Even if the weather improves,", "the rescue team may", "resume the search", "only after receiving clearance."], ["Even if the weather improves,", "the rescue team may", "to resume the search", "only after receiving clearance."], 2, "resume the search", "The modal 'may' is followed by the bare infinitive: 'may resume'."),
  q("GIP-H11", "hard", "GR-GIP-006", "administration", ["Without checking the supporting documents,", "the clerk approved the request", "and forwarded it", "to the accounts section."], ["Without to check the supporting documents,", "the clerk approved the request", "and forwarded it", "to the accounts section."], 0, "Without checking the supporting documents,", "After the preposition 'without', use a gerund: 'without checking'."),
  q("GIP-H12", "hard", "GR-GIP-006", "scheduling", ["The committee objected", "to changing the schedule", "at such short notice", "without consulting the candidates."], ["The committee objected", "to changing the schedule", "at such short notice", "without to consult the candidates."], 3, "without consulting the candidates.", "After the preposition 'without', use the gerund: 'without consulting'."),
  q("GIP-H13", "hard", "GR-GIP-007", "customer-service", ["After several months in the new role,", "she has become", "used to handling urgent queries", "without additional supervision."], ["After several months in the new role,", "she has become", "used to handle urgent queries", "without additional supervision."], 2, "used to handling urgent queries", "In 'become used to', 'to' is a preposition, so the following verb takes the -ing form."),
  q("GIP-H14", "hard", "GR-GIP-007", "commute", ["Before his transfer, he used to travel", "nearly two hours each day", "to reach the office", "from his village."], ["Before his transfer, he used to travelling", "nearly two hours each day", "to reach the office", "from his village."], 0, "Before his transfer, he used to travel", "'Used to' for a former habit is followed by the base form: 'used to travel'."),
  q("GIP-H15", "hard", "GR-GIP-008", "inventory", ["The inspection team returned", "after the lunch break", "to the storage area", "to verify the remaining stock."], ["The inspection team returned", "after the lunch break", "to the storage area", "verifying the remaining stock."], 3, "to verify the remaining stock.", "The final to-infinitive expresses the purpose of returning to the storage area."),
  q("GIP-H16", "hard", "GR-GIP-008", "investigation", ["Because the first report was incomplete,", "the officer called the witness", "to clarify two points", "before recording the statement."], ["Because the first report was incomplete,", "the officer called the witness", "clarifying two points", "before recording the statement."], 2, "to clarify two points", "The to-infinitive expresses why the officer called the witness: 'to clarify two points'."),
  q("GIP-H17", "hard", "GR-GIP-009", "audit", ["After checking the figures twice, the auditor remembered sending", "the corrected sheet", "to the branch manager", "the previous evening."], ["After checking the figures twice, the auditor remembered to send", "the corrected sheet", "to the branch manager", "the previous evening."], 0, "After checking the figures twice, the auditor remembered sending", "'Remember doing' refers to recalling a completed action; the sentence places the sending on the previous evening."),
  q("GIP-H18", "hard", "GR-GIP-009", "workplace", ["When the alarm sounded,", "the workers who were drilling", "stopped immediately", "to listen for further instructions."], ["When the alarm sounded,", "the workers who were drilling", "stopped immediately", "listening for further instructions."], 3, "to listen for further instructions.", "'Stop to do' means stop the current activity in order to do something else; they stopped drilling in order to listen."),
  q("GIP-H19", "hard", "GR-GIP-010", "laboratory", ["After the final samples were tested,", "the report included", "the results obtained from all three laboratories", "in a separate appendix."], ["After the final samples were tested,", "the report included", "the results obtaining from all three laboratories", "in a separate appendix."], 2, "the results obtained from all three laboratories", "The results receive the action, so the past participle 'obtained' is required."),
  q("GIP-H20", "hard", "GR-GIP-010", "verification", ["Having completed the verification,", "the officer returned the original documents", "to the applicant", "before closing the counter."], ["Having complete the verification,", "the officer returned the original documents", "to the applicant", "before closing the counter."], 0, "Having completed the verification,", "The perfect participle uses 'having' + past participle: 'having completed'."),
];

export const CP009_SCENES_BY_DIFFICULTY_V1: Readonly<Record<EnglishDifficulty, readonly GerundInfinitiveParticipleSceneV1[]>> = Object.freeze({
  easy: CP009_SCENES_V1.filter((scene) => scene.difficulty === "easy"),
  medium: CP009_SCENES_V1.filter((scene) => scene.difficulty === "medium"),
  hard: CP009_SCENES_V1.filter((scene) => scene.difficulty === "hard"),
});
