import type{Eng008Cp003PassageV1}from"./eng-008-cp003-authorities-v1";
const q=(id:string,familyId:any,difficulty:any,question:string,correctAnswer:string,distractors:readonly[string,string,string],explanation:string,evidence:string)=>({id,familyId,difficulty,question,correctAnswer,distractors,explanation,evidence});

export const ENG008_CP003_EXPANSION_WAVE1_V1:readonly Eng008Cp003PassageV1[]=[
{
 id:"ENG008-BP-N03",title:"The Library Card Left at Home",genre:"narrative",
 text:`Ananya had planned to spend Saturday morning at the district library preparing for an entrance test. She reached the building just after it opened, only to realise that her library card was still on her study table at home. The trip back would take nearly an hour, and she considered giving up on the visit.

At the information desk, a staff member asked whether she had any other identification. Ananya showed a college identity card, and the staff member checked her membership in the library system. She was allowed to enter the reading hall, though she could not borrow books without the physical library card.

The restriction changed her plan but did not ruin the morning. Instead of collecting two books to take home, Ananya used the catalogue to locate the relevant chapters and made notes in the reading hall. She also downloaded a free practice paper from the library's public computer.

During lunch, she realised that she had almost treated one missing item as a reason to abandon the entire task. The staff member had not ignored the rule; borrowing still required the card. But the library had another way to verify membership for on-site use.

When Ananya returned the next week with her card, she borrowed the books she had identified earlier. Because she had already read the most important chapters, she chose only the sections she still needed. The inconvenience had forced her to organise the material more carefully than she usually did.

She later added a small note to the inside of her study folder: “Check essentials before leaving, but do not confuse a setback with the end of the plan.” The lesson she remembered was not that rules were flexible, but that a useful alternative can exist even when the original route is blocked.`,
 questions:[
 q("N03-Q1","BP-F01","easy","Why could Ananya not borrow books on her first visit?","She had forgotten her physical library card",["The library had stopped lending books","Her membership had expired","She arrived after the borrowing desk closed"],"The passage says she could enter but could not borrow without the physical card.","could not borrow books without the physical library card"),
 q("N03-Q2","BP-F02","medium","What can be inferred about the library staff member?","The staff member followed the borrowing rule while still helping Ananya use the library",["The staff member ignored all membership rules","The staff member gave Ananya a new card immediately","The staff member refused to verify her identity"],"The staff member verified membership for entry but kept the borrowing restriction in place.","borrowing still required the card"),
 q("N03-Q3","BP-F03","medium","What is the central idea of the passage?","A setback does not always require abandoning the larger goal",["Library rules should be removed for students","Entrance tests should be prepared only in libraries","Digital practice papers are better than books"],"Ananya adapts her plan and still uses the visit productively.","do not confuse a setback with the end of the plan"),
 q("N03-Q4","BP-F04","medium","Which statement is supported by the passage?","Ananya used the library catalogue during her first visit",["Ananya returned home immediately for the card","The library allowed her to borrow books with a college ID","She had never used the library before"],"The passage explicitly says she used the catalogue to locate relevant chapters.","used the catalogue to locate the relevant chapters"),
 q("N03-Q5","BP-F05","easy","In context, “restriction” is closest in meaning to:","a limit on what was allowed",["a reward for membership","a written exam","a change in opening hours"],"The restriction refers to being unable to borrow without the card.","The restriction changed her plan"),
 q("N03-Q6","BP-F06","easy","Which word is opposite in meaning to “relevant” as used in the passage?","unrelated",["useful","connected","appropriate"],"Relevant means connected to the purpose, so unrelated is the opposite.","relevant chapters"),
 q("N03-Q7","BP-F07","medium","What does the phrase “the original route is blocked” mean here?","The first planned method is unavailable",["The road to the library is closed","The library building is inaccessible","Ananya has forgotten where the books are kept"],"The phrase refers to adapting when the initial plan cannot be followed exactly.","a useful alternative can exist even when the original route is blocked"),
 q("N03-Q8","BP-F08","medium","What most directly allowed Ananya to make use of the visit despite forgetting her card?","The staff member verified her membership using another ID",["The library waived all rules for the day","A friend brought her card later","She found the books outside the library"],"Alternative membership verification allowed on-site use even though borrowing stayed restricted.","checked her membership in the library system"),
 q("N03-Q9","BP-F09","medium","Which title best suits the passage?","A Missing Card, Not a Lost Morning",["The Library That Changed Its Rules","A Test Without Books","The Long Journey Home"],"The story centres on salvaging a useful study visit despite forgetting the card.","The restriction changed her plan but did not ruin the morning")
 ]
},
{
 id:"ENG008-BP-SC03",title:"Measuring Noise Around a Hospital",genre:"science",
 text:`A city health team placed simple sound meters at six points around a large public hospital after patients and staff complained about traffic noise. The devices recorded average sound levels for ten minutes every hour over two weeks. The aim was not to identify every individual vehicle but to understand when and where noise was most persistent.

The highest readings appeared near the main road between 8 a.m. and 10 a.m. and again in the early evening. A side entrance used mainly by staff had much lower readings even though it was only a short distance away. The team suspected that vehicle volume and repeated horn use were both contributing to the difference.

To check that idea, observers spent selected hours counting vehicles and noting horn use. They found that the noisiest periods did coincide with heavier traffic, but horn use varied more sharply than the number of vehicles. On some evenings, traffic volume was similar to the morning level while average noise was lower.

The team therefore avoided saying that traffic volume alone explained the pattern. Road width, stopping behaviour, horn use and nearby construction could all affect the readings. The meters also measured sound outside the buildings, so they did not show exactly what patients heard inside each ward.

Hospital administrators used the results to move one ambulance waiting point away from a congested gate and asked traffic police to discourage unnecessary horn use near the entrance. They did not expect these steps to remove all noise, but wanted to reduce the most avoidable sources first.

A follow-up measurement is planned after the traffic changes. The team will use the same locations and times so that the new readings can be compared with the original pattern. The project treats noise as a problem that can be measured and managed gradually rather than solved by one dramatic action.`,
 questions:[
 q("SC03-Q1","BP-F01","easy","Where were the highest noise readings recorded?","Near the main road during morning and early-evening busy periods",["Inside the quietest ward at night","At the staff entrance throughout the day","Only near the ambulance parking area"],"The second paragraph identifies the main road and the two busiest time periods.","highest readings appeared near the main road"),
 q("SC03-Q2","BP-F02","medium","What can be inferred from the difference between morning and evening readings?","The number of vehicles alone may not explain the noise level",["Evening traffic was always lighter","The meters stopped working in the evening","Construction occurred only in the morning"],"Similar traffic volumes sometimes produced different noise levels, suggesting other factors mattered.","traffic volume was similar ... while average noise was lower"),
 q("SC03-Q3","BP-F03","medium","What is the main idea of the passage?","Careful measurement can identify several contributors to traffic noise and guide targeted changes",["Hospitals should be built far from all roads","Horn use is the only cause of hospital noise","Sound meters can identify every noisy vehicle"],"The project combines measurement and observation to support limited practical interventions.","measured and managed gradually"),
 q("SC03-Q4","BP-F04","medium","Which statement is supported?","The sound meters were placed outside hospital buildings",["The team measured noise inside every ward","Traffic volume was identical at all six points","The hospital closed the main entrance after the study"],"The passage explicitly says the meters measured sound outside the buildings.","measured sound outside the buildings"),
 q("SC03-Q5","BP-F05","easy","In context, “persistent” is closest in meaning to:","continuing or repeatedly present",["sudden and brief","completely silent","easy to remove"],"The team wanted to know when noise continued rather than appearing as a single event.","when and where noise was most persistent"),
 q("SC03-Q6","BP-F06","easy","Which word is opposite in meaning to “avoidable”?","unavoidable",["preventable","reducible","optional"],"Avoidable means capable of being prevented, so unavoidable is the opposite.","most avoidable sources"),
 q("SC03-Q7","BP-F07","medium","What does “traffic volume alone” refer to?","The number of vehicles considered without other factors",["The loudness of every horn","The width of the road","The number of hospital patients"],"The passage distinguishes vehicle count from horn use and other contributors.","traffic volume alone explained the pattern"),
 q("SC03-Q8","BP-F08","medium","Why did the team also count vehicles and note horn use?","To compare possible causes with the measured noise pattern",["To issue fines to every driver","To replace the sound meters","To estimate hospital visitor numbers"],"The observations were added to test possible explanations for the readings.","To check that idea, observers ... counting vehicles and noting horn use"),
 q("SC03-Q9","BP-F09","medium","Which title best suits the passage?","Listening to the Traffic Around a Hospital",["The Hospital Without Ambulances","Why Sound Meters Fail","A Road Closed for Two Weeks"],"The passage is about measuring and interpreting traffic noise around a hospital.","sound meters at six points around a large public hospital")
 ]
}
] as const;