import type{Eng008Cp003PassageV1}from"./eng-008-cp003-authorities-v1";
const q=(id:string,familyId:any,difficulty:any,question:string,correctAnswer:string,distractors:readonly[string,string,string],explanation:string,evidence:string)=>({id,familyId,difficulty,question,correctAnswer,distractors,explanation,evidence});
export const ENG008_CP003_EXPANSION_WAVE12_V1:readonly Eng008Cp003PassageV1[]=[
{
 id:"ENG008-BP-N17",title:"The Reissued Examination Admit Card",genre:"narrative",
 text:`Karan downloaded his examination admit card a week before the test. It showed Centre 14, Room 6 and reporting time 8:30 a.m. Two days later, he received an official message asking candidates in one roll-number range to download a reissued admit card because a room allocation had changed.

Karan checked the roll-number range and found that it included him. The new admit card still showed the same examination centre and reporting time, but his room had changed from 6 to 11. The document also carried a new issue date and a line stating that earlier versions for affected candidates should not be used.

A friend told Karan that the first admit card should remain valid because it had already been downloaded from the official site. Karan did not rely on that assumption. He opened the examination portal and confirmed that only the newer document now appeared under his login.

On examination morning, temporary signs at the centre directed candidates from his roll-number range to Room 11. A staff member explained that the change had been made to balance seating capacity after one room lost several desks.

Karan noticed that most information on both admit cards was identical. The change did not mean that the earlier document had been fraudulent; it had simply been superseded for one operational detail. The new issue date and the portal record showed which version was current.

After the test, Karan kept both files for reference but renamed the older one “superseded” so he would not accidentally use it in future communication. The experience taught him that when an authority formally reissues a document, the correct question is not whether the earlier version was once valid but which version now governs the event.  The examination authority later published a short version-history note listing the date, affected roll-number range and changed field. Karan found this useful because it separated a targeted operational revision from a completely new admission process. He also noticed that candidates outside the affected range continued using their original cards. This reinforced the idea that version control can be selective: one document may be superseded for some people while remaining current for others. In future, he decided to check not only the document date but also whether a reissue notice actually covered his own identifier.`,
 questions:[
 q("N17-Q1","BP-F01","easy","What changed on Karan's reissued admit card?","His room number",["His examination centre","His reporting time","His roll number"],"The centre and reporting time stayed the same, while the room changed from 6 to 11.","room had changed"),
 q("N17-Q2","BP-F02","medium","Why did Karan check his roll-number range?","The reissue applied only to certain candidates",["He had forgotten his roll number","The centre had changed cities","The portal required a new application"],"The official message specified that only one range of candidates needed the new document.","one roll-number range"),
 q("N17-Q3","BP-F03","medium","What is the central idea of the passage?","When an official document is reissued, the latest governing version should be identified rather than relying on an older valid copy",["Downloaded documents never change","Old documents are always fraudulent","Room changes require new roll numbers"],"The narrative distinguishes earlier validity from current authority after a formal reissue.","which version now governs"),
 q("N17-Q4","BP-F04","medium","Which statement is supported?","The older admit card had once been valid",["The old card came from an unofficial source","Karan's reporting time changed","Room 11 had fewer desks"],"The passage says the earlier card was not fraudulent; it had simply been superseded.","once valid"),
 q("N17-Q5","BP-F05","easy","In context, “superseded” is closest in meaning to:","replaced by a newer valid version",["cancelled forever without replacement","printed twice","verified by a friend"],"The older card no longer governed because a newer official document had taken its place.","superseded"),
 q("N17-Q6","BP-F06","easy","Which word is opposite in meaning to “current”?","outdated",["present","latest","active"],"Current means presently valid; outdated means no longer current.","which version was current"),
 q("N17-Q7","BP-F07","medium","What did the new issue date help Karan determine?","Which admit card was the newer official version",["Which room had more desks","When the exam would end","When he first applied"],"The date was one piece of version evidence showing which document should govern.","new issue date"),
 q("N17-Q8","BP-F08","medium","Why was the room allocation changed?","To balance seating capacity after desks became unavailable",["The centre building moved","The examination time was shortened","Karan requested another room"],"Staff explained the operational reason for moving affected candidates.","balance seating capacity"),
 q("N17-Q9","BP-F09","medium","Which title best suits the passage?","The Reissued Examination Admit Card",["The Missing Roll Number","A Cancelled Examination","The New Test Centre"],"The story centres on recognising and using a newer official admit card.","reissued admit card")
 ]
},
{
 id:"ENG008-BP-N18",title:"The Duplicate Train Reservation Message",genre:"narrative",
 text:`Sonia booked a train ticket through an authorised app and received a confirmation message with one booking reference. Ten minutes later, a second message arrived showing the same journey but a different payment reference. She worried that two tickets might have been purchased accidentally.

The app's trip page showed only one passenger booking and one seat. Sonia opened the payment history and found that the first card transaction had briefly shown “pending” before becoming “reversed”. The second payment had succeeded and was linked to the confirmed booking.

The two text messages looked similar because both contained the train number and date. However, one message referred to the booking reference while the other contained a payment reference generated during the failed first attempt. The numbers served different purposes.

Sonia checked her bank balance later that evening. The amount from the first attempt had been released, while only the successful payment remained charged. She saved the reversal notification until the statement updated.

Customer support explained that temporary authorisation can sometimes make a failed payment appear active for a short period. That does not create a second reservation unless the booking system issues another passenger record.

The experience showed Sonia why similar-looking numbers should not automatically be treated as duplicate bookings. A booking reference identifies the travel reservation; a payment reference identifies a financial transaction. The correct way to check for duplication was to compare passenger records and completed charges rather than count every message containing a new number.  Sonia later reviewed her monthly statement and found only one settled charge for the journey. The reversed authorisation no longer affected her available balance. She also learned that some banking apps show temporary holds differently, so a pending line should be interpreted together with the final settlement status. Customer support advised her to use the booking page as the source of truth for passenger reservations and the bank statement as the source of truth for completed card charges. That distinction helped her avoid treating every financial message as evidence of another ticket.`,
 questions:[
 q("N18-Q1","BP-F01","easy","How many passenger bookings appeared in Sonia's trip page?","One",["Two","Three","None"],"The app showed one seat and one passenger reservation despite two messages.","only one passenger booking"),
 q("N18-Q2","BP-F02","medium","Why did Sonia initially think she might have bought two tickets?","A second message arrived with another reference number",["The train number changed","Two seats appeared in the app","Her bank balance doubled"],"The similar messages made different transaction identifiers look like duplicate reservations.","different payment reference"),
 q("N18-Q3","BP-F03","medium","What is the central idea of the passage?","Different reference numbers can identify different processes and do not necessarily represent duplicate purchases",["Every second payment creates another ticket","Pending payments are always successful","Booking and payment references are interchangeable"],"The passage separates travel-reservation identity from financial-transaction identity.","served different purposes"),
 q("N18-Q4","BP-F04","medium","Which statement is supported?","The first card transaction was later reversed",["Both payments remained charged","Two seats were assigned","Customer support cancelled the trip"],"The payment history showed one pending attempt later becoming reversed.","became “reversed”"),
 q("N18-Q5","BP-F05","easy","In context, “authorisation” is closest in meaning to:","a temporary payment approval or hold",["a train ticket number","a seat upgrade","a travel refund"],"The passage explains that a temporary card approval can appear before a transaction ultimately fails.","temporary authorisation"),
 q("N18-Q6","BP-F06","easy","Which word is opposite in meaning to “duplicate”?","single",["copied","repeated","additional"],"Duplicate implies more than one equivalent item; single means only one.","duplicate bookings"),
 q("N18-Q7","BP-F07","medium","What does the booking reference identify?","The travel reservation",["The failed bank transaction","The train platform","The card balance"],"The passage explicitly contrasts the booking reference with the payment reference.","identifies the travel reservation"),
 q("N18-Q8","BP-F08","medium","Why did Sonia keep the reversal notification?","She wanted evidence until the bank statement reflected the released amount",["She needed it to board the train","The booking page was unavailable","The second payment had failed"],"The notification documented the financial reversal while account records were still updating.","until the statement updated"),
 q("N18-Q9","BP-F09","medium","Which title best suits the passage?","The Duplicate Train Reservation Message",["The Missing Train Ticket","A Cancelled Journey","The Wrong Platform"],"The story concerns resolving an apparent duplicate caused by different transaction references.","two tickets might have been purchased")
 ]
},
{
 id:"ENG008-BP-S16",title:"Shared Laundry Machine Queue",genre:"social",
 text:`A university hostel had four shared washing machines. Students previously waited near the laundry room and tried to guess which machine would finish first. The hostel installed a small dashboard showing “running”, “cycle ended”, “door open” or “available” for each machine.

The first version marked a machine available as soon as the washing cycle ended. This caused frustration because clothes could still remain inside for several minutes while the owner was walking back to the laundry room.

The hostel changed the status. After a cycle ended, the machine showed “collection period” for ten minutes. If the door was opened and clothes removed, the status became available immediately. If the machine remained occupied after ten minutes, the dashboard showed “collection overdue”.

Students could choose to receive a reminder five minutes before their cycle ended. The reminder reduced overdue collections, but some users disabled notifications because they received them during classes. The hostel therefore allowed quiet periods and kept the timer visible in the app.

Another issue involved maintenance. A machine taken out of service initially looked merely unavailable. Staff added a separate “maintenance” state so students would not wait for a machine that could not return to service soon.

The dashboard did not increase the number of washers. It reduced uncertainty about the stage each machine was in and made the short collection grace period visible to everyone. Hostel staff concluded that shared equipment needs more than an occupied/free label. A machine can be washing, finished but not emptied, temporarily protected by a collection window or unavailable because of maintenance. Clear status helped users understand which kind of waiting was reasonable.  Hostel staff later reviewed machine turnover before and after the dashboard change. Average idle time between one user's collection and the next user's start fell slightly, but the largest improvement came during evening peaks. Staff also noticed that repeated overdue collections were concentrated among a small group of users. Instead of removing the grace period, they added an optional second reminder near the end of the collection window. The hostel decided not to impose penalties during the trial because it first wanted to understand whether clearer information alone could improve behaviour.`,
 questions:[
 q("S16-Q1","BP-F01","easy","How long was the laundry collection period?","Ten minutes",["Five minutes","Thirty minutes","One hour"],"The revised system allowed ten minutes after a cycle ended before marking collection overdue.","for ten minutes"),
 q("S16-Q2","BP-F02","medium","Why was “cycle ended” separated from “available”?","Clothes could still be inside after the wash finished",["The machine needed new water","Every user wanted another cycle","The dashboard had no timer"],"A completed cycle did not mean the physical machine was immediately ready for another user.","clothes could still remain inside"),
 q("S16-Q3","BP-F03","medium","What is the central idea of the passage?","Shared equipment status should represent the actual stage of use rather than only occupied or free",["Laundry machines should never have grace periods","Notifications solve all waiting problems","More machines are unnecessary"],"The dashboard becomes useful by distinguishing running, collection and maintenance states.","more than an occupied/free label"),
 q("S16-Q4","BP-F04","medium","Which statement is supported?","Users could set quiet periods for reminders",["All reminders were compulsory","Maintenance machines appeared available","The hostel added more washers"],"The app was changed so reminders would not disturb users during unsuitable times.","allowed quiet periods"),
 q("S16-Q5","BP-F05","easy","In context, “overdue” is closest in meaning to:","later than the allowed time",["newly started","under repair","available early"],"The collection is overdue when clothes remain after the ten-minute grace period.","collection overdue"),
 q("S16-Q6","BP-F06","easy","Which word is opposite in meaning to “available”?","unavailable",["free","ready","open"],"Available means ready for use; unavailable is its direct opposite.","available"),
 q("S16-Q7","BP-F07","medium","What does the maintenance status communicate?","The machine is out of service rather than merely occupied",["The wash cycle is nearly done","Clothes are waiting for collection","The reminder is disabled"],"The separate state prevents students from expecting a quick return to availability.","taken out of service"),
 q("S16-Q8","BP-F08","medium","Why did the reminder not work equally well for everyone?","Some notifications arrived during classes and were disabled",["The machines had no timers","Students could not use phones","Every cycle ended at the same time"],"Timing affected whether users accepted the notification feature.","during classes"),
 q("S16-Q9","BP-F09","medium","Which title best suits the passage?","Shared Laundry Machine Queue",["The Hostel Laundry Closure","Buying New Washing Machines","Why Clothes Take Longer to Dry"],"The passage evaluates status and waiting rules for shared laundry equipment.","shared washing machines")
 ]
},
{
 id:"ENG008-BP-S17",title:"Neighbourhood Package Shelf Codes",genre:"social",
 text:`A residential complex received many courier packages while residents were at work. Security staff placed parcels on numbered shelves and sent each resident a message containing the shelf number. The system worked well until several packages for people with similar names arrived on the same day.

One evening, a resident named Aman Singh collected a box addressed to another Aman living in a different tower. Both messages said “Shelf 4”, and the guard had relied on name alone instead of checking the flat number.

The committee changed the collection process. Messages now included a short pickup code linked to the specific parcel. The resident showed the code, and the guard matched it with the label before handing over the package.

Shelf number remained useful because it told staff where to find the parcel, but it no longer acted as the main identity check. The pickup code answered a different question: which package was authorised for this resident.

The complex also added an expiry rule. Packages uncollected for five days were moved to a separate storage room. Their original shelf code was then marked inactive so old messages would not direct residents to an empty location.

The change reduced wrong-package collections, but guards were told not to read pickup codes aloud when several residents were waiting nearby. Codes were treated as temporary access information. Managers concluded that location and identity are related but different. A shelf number can help find an object, yet it should not be treated as proof that the object belongs to the person asking for it.  The committee also added a collection history showing when each parcel entered the shelf system, when its code was used and when it moved to long-term storage. This helped staff resolve disputes when a resident claimed that a code had expired too early. The history did not reveal other residents' details. Managers also asked guards to check the flat number printed on the parcel even after a correct code was shown, because the code reduced error but did not remove the value of a second visible identity check.`,
 questions:[
 q("S17-Q1","BP-F01","easy","What was added to parcel collection messages?","A parcel-specific pickup code",["The courier driver's salary","A building map only","The resident's bank details"],"The new code linked the resident to one specific package.","pickup code"),
 q("S17-Q2","BP-F02","medium","Why was shelf number alone insufficient?","Different residents' parcels could share the same shelf",["Every shelf had one parcel only","Shelf numbers changed every hour","Residents could not read numbers"],"Shelf number described location, not ownership.","location and identity"),
 q("S17-Q3","BP-F03","medium","What is the central idea of the passage?","Location information should not be confused with identity verification",["Packages should never use shelves","Names are always unique","Pickup codes should remain active forever"],"The system improves by separating where a parcel sits from who may collect it.","different questions"),
 q("S17-Q4","BP-F04","medium","Which statement is supported?","Old shelf codes were marked inactive after packages moved to long-term storage",["All parcels were returned after one day","Guards stopped using shelves","Codes were permanent"],"The system prevented an outdated message from directing a resident to the wrong location.","marked inactive"),
 q("S17-Q5","BP-F05","easy","In context, “expiry” is closest in meaning to:","the point when information or permission stops being active",["the delivery price","the shelf height","the resident name"],"The original shelf code stopped being valid after a parcel was moved.","expiry rule"),
 q("S17-Q6","BP-F06","easy","Which word is opposite in meaning to “inactive”?","active",["expired","unused","silent"],"Active is the direct opposite of inactive.","inactive"),
 q("S17-Q7","BP-F07","medium","What does the pickup code verify?","Which parcel the resident is authorised to collect",["Which courier route was used","How long the parcel has waited","The shelf location only"],"The code is the identity/permission check rather than a storage-location label.","authorised for this resident"),
 q("S17-Q8","BP-F08","medium","Why were guards told not to read codes aloud?","The codes acted as temporary access information",["Codes were too long","Residents could not hear","The shelf number was secret"],"Someone overhearing a valid code could misuse it during collection.","temporary access information"),
 q("S17-Q9","BP-F09","medium","Which title best suits the passage?","Neighbourhood Package Shelf Codes",["The Missing Courier","A New Apartment Tower","Why Packages Are Too Large"],"The passage concerns separating shelf location from parcel pickup verification.","pickup code")
 ]
},
{
 id:"ENG008-BP-SC15",title:"Testing Ice-Melting Surfaces",genre:"science",
 text:`A school science group tested how quickly equal ice cubes melted on four surfaces: metal, wood, plastic and a folded cloth. Each cube was taken from the same freezer tray and placed on a surface at room temperature. Students recorded the time until the cube had visibly lost half its height.

The metal surface produced the fastest melting, while the folded cloth produced the slowest. Some students initially concluded that the metal must have been “hotter”. Their teacher asked them to measure surface temperature before the next trial. All four surfaces were close to the same room temperature.

The class then discussed thermal conductivity. Metal can transfer heat from the surrounding room and table into the ice more rapidly than materials such as cloth, even when both begin at similar temperatures.

The measurement method had weaknesses. Judging when an ice cube had lost half its height was subjective, and melting changed shape unevenly. In a second trial, students instead weighed the meltwater collected after a fixed ten-minute period.

The new measure produced the same broad ordering. Metal still transferred heat fastest, although individual results varied because small cubes were not perfectly identical.

The students also noticed that the metal plate was thinner than the wooden board. Thickness and contact area could affect heat transfer. A stronger experiment would use materials with more closely matched dimensions and repeat more trials. The group therefore made a limited conclusion: under the tested setup, the metal surface transferred heat to the ice more quickly than the other surfaces. The experiment did not prove that metal objects are always at a higher temperature than wooden ones in the same room.  In a later discussion, students considered why a metal surface can feel colder than wood at the same room temperature. Their teacher explained that rapid heat transfer from the hand can create that sensation, again showing that transfer rate and temperature are related but different ideas. The class planned to repeat the experiment with equal-thickness samples and identical contact areas. It would also use digital image analysis to estimate ice volume rather than rely only on height, reducing observer judgement in the measurement.`,
 questions:[
 q("SC15-Q1","BP-F01","easy","On which surface did the ice melt fastest?","Metal",["Wood","Plastic","Folded cloth"],"The metal surface produced the fastest visible melting and the most meltwater in the follow-up.","metal surface"),
 q("SC15-Q2","BP-F02","medium","Why did the teacher measure surface temperatures?","To test whether faster melting meant the metal had started hotter",["To measure ice weight","To warm the cloth","To change room temperature"],"The temperature check challenged the mistaken explanation that metal was simply hotter.","close to the same room temperature"),
 q("SC15-Q3","BP-F03","medium","What is the central idea of the passage?","Heat-transfer rate can differ between materials even when their starting temperatures are similar",["Metal is always hotter than wood","Ice melts at one fixed speed","Surface temperature does not matter"],"The experiment distinguishes thermal conductivity from initial temperature.","thermal conductivity"),
 q("SC15-Q4","BP-F04","medium","Which statement is supported?","The second measurement method produced the same broad ordering",["The cloth became fastest","All results were identical","Surface temperatures were very different"],"Using meltwater after a fixed time still placed metal ahead overall.","same broad ordering"),
 q("SC15-Q5","BP-F05","easy","In context, “conductivity” is closest in meaning to:","ability to transfer heat",["surface colour","melting temperature","object weight"],"Thermal conductivity describes how readily a material passes heat.","transfer heat"),
 q("SC15-Q6","BP-F06","easy","Which word is opposite in meaning to “subjective”?","objective",["personal","uncertain","visual"],"Subjective judgement depends on the observer; objective measurement is less dependent on personal judgement.","subjective"),
 q("SC15-Q7","BP-F07","medium","Why was judging half-height a weak measure?","Melting changed the ice shape unevenly and required visual judgement",["No ice melted","Students had no rulers","The cubes were heated"],"The class replaced a subjective visual point with a fixed-time meltwater measure.","subjective"),
 q("SC15-Q8","BP-F08","medium","Why did students mention plate thickness?","Material thickness could also affect heat transfer",["Thickness determines freezer temperature","Only thick surfaces melt ice","The wood had no contact area"],"A design difference besides material could partly contribute to the observed rate.","Thickness and contact area"),
 q("SC15-Q9","BP-F09","medium","Which title best suits the passage?","Testing Ice-Melting Surfaces",["Why Metal Is Always Hot","Making Ice Without a Freezer","The Wooden Table Experiment"],"The passage describes a comparative heat-transfer experiment using several surfaces.","melted on four surfaces")
 ]
},
{
 id:"ENG008-BP-SC16",title:"Comparing Homemade Water Filters",genre:"science",
 text:`A science club built three simple water-filter columns using gravel, sand and activated charcoal in different arrangements. The aim was to compare how much visible cloudiness each design removed from muddy water. The students did not intend the filtered water to be safe for drinking.

Each column received the same volume of prepared muddy water. Students collected the output and measured turbidity with a classroom sensor. They also recorded how long the water took to pass through the filter.

The column containing fine sand above charcoal produced the clearest water, but it was also the slowest. A design with larger gravel layers filtered much faster but left more cloudiness. Students repeated each design three times. One slow trial clogged because the sand had been packed more tightly than usual. They kept the result and recorded the packing difference rather than discarding it.

The club noticed that “best filter” depended on the goal. If maximum clarity mattered, the slow fine-sand design performed well. If flow rate mattered, the faster gravel-heavy design had an advantage.

Their teacher also warned that clear water is not necessarily microbiologically safe. The experiment measured visible particles, not bacteria, dissolved chemicals or disease-causing organisms.

For a follow-up, students planned to standardise packing pressure, weigh each filtering material and compare both turbidity reduction and flow per minute. They would still label all output “not for drinking”. The project showed that one device can perform well on one outcome and poorly on another. A useful comparison needs to state which property is being measured and which important properties remain untested.  The club also compared how much filtering material each design used. The clearest-water column contained more fine material, so its better turbidity result came with a cost in both flow and material quantity. Students therefore planned to calculate turbidity reduction per minute and per gram of filter material. They also discussed how a household filter would need cleaning or replacement over time, something the short classroom trial did not test. The teacher emphasised again that none of these measures could replace proper testing for drinking-water safety.`,
 questions:[
 q("SC16-Q1","BP-F01","easy","Which filter produced the clearest water?","The fine-sand-and-charcoal design",["The gravel-heavy design","All filters were identical","The empty column"],"That arrangement produced the lowest visible cloudiness but also the slowest flow.","clearest water"),
 q("SC16-Q2","BP-F02","medium","Why was the clogged trial kept in the results?","The students wanted to record real variation and its possible cause rather than hide it",["The filter worked fastest","No other trials existed","The sensor failed"],"The class documented tighter packing as a possible reason for the outlier.","recorded the packing difference"),
 q("SC16-Q3","BP-F03","medium","What is the central idea of the passage?","Filter performance depends on the outcome measured, and clear water does not prove safe water",["The slowest filter is always best","Gravel removes all bacteria","Turbidity measures every contaminant"],"The experiment distinguishes clarity, flow and unmeasured health risks.","one outcome ... another"),
 q("SC16-Q4","BP-F04","medium","Which statement is supported?","The faster gravel-heavy design left more cloudiness",["Charcoal made water safe to drink","Every trial used different water volumes","Students discarded the clogged result"],"Higher flow came with weaker visible-particle removal in that design.","left more cloudiness"),
 q("SC16-Q5","BP-F05","easy","In context, “turbidity” is closest in meaning to:","cloudiness caused by suspended particles",["water temperature","chemical toxicity","flow speed"],"The classroom sensor measured how cloudy the output remained.","visible cloudiness"),
 q("SC16-Q6","BP-F06","easy","Which word is opposite in meaning to “clear”?","cloudy",["transparent","clean-looking","bright"],"Cloudy is the opposite of visually clear in the context of water.","clear water"),
 q("SC16-Q7","BP-F07","medium","What does the teacher's warning establish?","Visual clarity is not enough to prove drinking safety",["All filtered water contains disease","Turbidity sensors detect bacteria","Charcoal is unsafe"],"The experiment does not test microbial or dissolved hazards.","not necessarily microbiologically safe"),
 q("SC16-Q8","BP-F08","medium","Why will the follow-up standardise packing pressure?","Different packing can change flow and filtration performance",["Pressure changes water volume only","Students need heavier columns","Gravel cannot be packed"],"The clogged trial showed that packing variation can affect results.","packed more tightly"),
 q("SC16-Q9","BP-F09","medium","Which title best suits the passage?","Comparing Homemade Water Filters",["Making Drinking Water Safe","Why Gravel Removes Bacteria","The Fastest Water Pump"],"The passage compares several simple filter designs on clarity and flow.","three simple water-filter columns")
 ]
},
{
 id:"ENG008-BP-B18",title:"Retail Pickup Reservation Expiry",genre:"business",
 text:`A clothing retailer allowed customers to reserve store items online without paying immediately. The first version held every reservation until closing time. Popular sizes sometimes remained unavailable to walk-in shoppers for hours even when the reserving customer never arrived.

The retailer introduced a two-hour pickup hold. The app showed the exact expiry time and sent a reminder thirty minutes before the item returned to normal selling stock.

Customers asked what would happen if they were delayed. The retailer allowed one extension of sixty minutes if the customer requested it before the original hold expired. After the extension ended, the item became available to other shoppers automatically.

The system also distinguished “reserved” from “paid”. A reservation prevented immediate sale to someone else but did not mean the customer had completed a purchase. Paid click-and-collect orders followed a different policy and were held longer.

During the first month, more uncollected items returned to sale during the same day. Staff reported fewer situations in which the last popular size sat behind the counter until closing.

One problem involved inventory updates. If staff forgot to scan an item when putting it back on the shelf, the online system could continue showing it unavailable. The retailer added an end-of-shift reconciliation for expired reservations. Managers concluded that a reservation is a temporary claim, not permanent ownership. A useful system needs a clear hold period, a visible extension rule and a reliable way to return abandoned reservations to sellable stock.  The retailer also measured how often customers arrived shortly after a reservation expired. A small number did, especially during evening traffic. To reduce surprise, the app changed colour during the final thirty minutes and showed a message that the item could be sold to someone else after expiry. Staff could still choose to honour a recently expired hold if the item had not yet been returned to the shelf or sold. Managers treated this as a limited service decision rather than an entitlement, because extending every expired reservation would recreate the original stock-blocking problem.`,
 questions:[
 q("B18-Q1","BP-F01","easy","How long was the normal unpaid pickup hold?","Two hours",["Thirty minutes","One hour","Until closing every day"],"The revised policy held unpaid reservations for two hours.","two-hour pickup hold"),
 q("B18-Q2","BP-F02","medium","Why did the retailer shorten the hold period?","Popular items could remain blocked for customers who never arrived",["Stores closed earlier","Customers paid too quickly","Inventory had no sizes"],"Long holds reduced availability for walk-in shoppers even when reservations were abandoned.","never arrived"),
 q("B18-Q3","BP-F03","medium","What is the central idea of the passage?","Unpaid reservations should be treated as temporary claims with clear expiry and return-to-stock rules",["Reservations are the same as purchases","Popular sizes should never be reserved","Extension should be unlimited"],"The system balances customer convenience against keeping abandoned stock available.","temporary claim"),
 q("B18-Q4","BP-F04","medium","Which statement is supported?","Customers could request one sixty-minute extension before expiry",["Every hold could be extended indefinitely","Paid orders used the same hold period","Expired items were destroyed"],"The retailer allowed one limited extension when requested in time.","one extension"),
 q("B18-Q5","BP-F05","easy","In context, “reconciliation” is closest in meaning to:","checking that physical and system stock records agree",["a customer refund","a new product launch","a delivery fee"],"Staff compared expired reservations with actual shelf return status.","end-of-shift reconciliation"),
 q("B18-Q6","BP-F06","easy","Which word is opposite in meaning to “temporary”?","permanent",["short","limited","brief"],"Permanent is the opposite of temporary.","temporary claim"),
 q("B18-Q7","BP-F07","medium","What does “reserved” mean in the system?","The item is held for a customer but not yet purchased",["The item has been fully paid","The item is defective","The store no longer owns it"],"The passage explicitly separates reservation from completed payment.","did not mean ... completed a purchase"),
 q("B18-Q8","BP-F08","medium","Why was an end-of-shift check added?","Expired items could physically return to the shelf without the online status updating",["Customers forgot expiry times","Paid orders disappeared","Stores had no scanners"],"A missed return scan could leave stale digital unavailability.","forgot to scan"),
 q("B18-Q9","BP-F09","medium","Which title best suits the passage?","Retail Pickup Reservation Expiry",["The Closed Clothing Store","Why Popular Sizes Cost More","A New Payment Card"],"The passage focuses on time-limited unpaid pickup reservations.","expiry time")
 ]
},
{
 id:"ENG008-BP-B19",title:"Service Quote Approval Windows",genre:"business",
 text:`A home-appliance repair company emailed customers a quote after diagnosing a fault. The original process left quotes open indefinitely. Weeks later, some customers tried to approve an old quote even though parts prices or availability had changed.

The company introduced a seven-day approval window. Each quote showed the expiry date and stated that approval after that date would require a refreshed price and parts check.

Customers sometimes needed more time to decide. They could request an extension before expiry, but the company did not promise that supplier prices would remain unchanged during a long extension. If a key part became unavailable, staff issued a revised quote even within the original window.

The business also separated “quote approved” from “repair scheduled”. Approval meant the customer accepted the proposed work and price; scheduling happened only after the required part was confirmed and a technician slot was assigned.

This distinction reduced calls from customers who believed pressing “approve” guaranteed a repair appointment that same day.

The company tracked how often quotes expired without action. Some customers had chosen not to repair the appliance, while others had simply missed the email. A reminder was therefore sent two days before expiry. Managers concluded that a quote is time-sensitive information, not a permanent promise detached from supply conditions. A clear validity window protects customers from surprise repricing and helps the business avoid pretending that old supplier costs remain available forever.  The company later separated quotes into labour, parts and optional work so customers could see which elements were most likely to change. Labour rates were usually stable across the seven-day window, while imported part prices changed more often. If only an optional item changed, staff could refresh that line without repeating the entire diagnosis. The firm also tracked how many customers approved a refreshed quote after expiry. This helped managers distinguish genuinely lost jobs from customers who still wanted the repair but needed updated commercial terms before committing.`,
 questions:[
 q("B19-Q1","BP-F01","easy","How long was the normal quote approval window?","Seven days",["Two days","One month","Indefinitely"],"The company introduced a seven-day validity period.","seven-day approval window"),
 q("B19-Q2","BP-F02","medium","Why were old quotes risky to approve weeks later?","Parts prices or availability could have changed",["Diagnosis always changes daily","Technicians forget the appliance","Customers cannot use email"],"The original commercial assumptions behind the quote might no longer hold.","prices or availability had changed"),
 q("B19-Q3","BP-F03","medium","What is the central idea of the passage?","Service quotes should have clear validity periods because price and supply conditions can change",["Approved quotes guarantee immediate appointments","Parts prices never change","Quotes should remain open forever"],"The passage treats a quote as time-sensitive rather than permanent information.","time-sensitive information"),
 q("B19-Q4","BP-F04","medium","Which statement is supported?","An approved quote did not automatically mean the repair was scheduled",["Approval had no meaning","The company never used technician slots","Every part was already in stock"],"Scheduling required part confirmation and an available technician after approval.","separated “quote approved”"),
 q("B19-Q5","BP-F05","easy","In context, “validity” is closest in meaning to:","the period during which the quote remains applicable",["the repair quality","the technician's identity","the customer's address"],"The approval window defines how long the offered terms can be relied upon.","validity window"),
 q("B19-Q6","BP-F06","easy","Which word is opposite in meaning to “approve”?","reject",["accept","confirm","agree"],"Reject is the opposite of approve.","approve"),
 q("B19-Q7","BP-F07","medium","What does a refreshed quote involve?","Checking current price and parts availability again",["Repeating the entire appliance purchase","Cancelling diagnosis","Changing the customer's email"],"Expired commercial assumptions need to be verified before a new offer is made.","refreshed price and parts check"),
 q("B19-Q8","BP-F08","medium","Why was a reminder sent two days before expiry?","Some customers missed the original quote email",["All customers rejected quotes","Parts were always unavailable","Technicians needed more diagnosis"],"The reminder addresses inaction caused by missed communication rather than deliberate refusal.","simply missed the email"),
 q("B19-Q9","BP-F09","medium","Which title best suits the passage?","Service Quote Approval Windows",["The Broken Appliance Factory","A New Technician Uniform","Why Repairs Need No Parts"],"The passage is about how long a repair quote remains open for acceptance.","approval window")
 ]
}
] as const;