import type { PolCp023SeedRow } from "./pol-cp023-types";

const N=["NITI-CABINET-RESOLUTION-2015"] as const;
const H=["PHRA-1993-AS-AMENDED-2019"] as const;

export const POL_CP023_PART_1: readonly PolCp023SeedRow[] = [
  ["POL-023-QL-001","Easy","NITI Aayog was constituted through which mechanism?","Resolution of the Union Cabinet","Constitutional amendment","Act of Parliament","Presidential ordinance","NITI Aayog was constituted by a Union Cabinet resolution dated 1 January 2015; it is not a constitutional or statutory body.",N],
  ["POL-023-QL-001","Easy","On which date did NITI Aayog come into effect?","1 January 2015","15 March 1950","26 January 1950","12 October 1993","The Cabinet resolution constituting NITI Aayog took effect on 1 January 2015 and superseded the earlier Planning Commission resolution.",N],
  ["POL-023-QL-001","Easy","Which institution did NITI Aayog replace?","Planning Commission","Finance Commission","National Development Council","Inter-State Council","NITI Aayog replaced the Planning Commission, whose 1950 resolution was superseded by the Cabinet resolution creating NITI Aayog.",N],
  ["POL-023-QL-001","Easy","Which description best fits NITI Aayog?","Executive policy think tank","Constitutional audit authority","Statutory election body","Judicial tribunal","NITI Aayog is an executive policy institution created by Cabinet resolution and serves as the Government of India's apex policy think tank.",N],
  ["POL-023-QL-002","Easy","What is a central purpose of NITI Aayog?","Providing strategic and policy inputs","Auditing Union accounts","Conducting parliamentary elections","Trying election petitions","NITI Aayog provides directional, strategic and technical policy inputs to the Union, States and Union Territories.",N],
  ["POL-023-QL-002","Easy","Which principle is strongly associated with NITI Aayog's federal role?","Cooperative federalism","Judicial supremacy","Separate electorates","Unitary taxation","NITI Aayog is designed as a platform for Centre-State consultation and is expressly associated with promoting cooperative federalism.",N],
  ["POL-023-QL-002","Easy","Who chairs the Governing Council of NITI Aayog?","Prime Minister","President","Finance Minister","Vice-President","The Prime Minister chairs NITI Aayog's Governing Council, which brings together States and Union Territories for shared policy discussion.",N],
  ["POL-023-QL-002","Easy","Which group is part of NITI Aayog's Governing Council structure?","Chief Ministers of States","Judges of all High Courts","Members of the Election Commission","Comptroller and Auditor General only","The Governing Council includes State Chief Ministers and relevant Union Territory leadership, supporting joint discussion of national development priorities.",N],
  ["POL-023-QL-003","Easy","The National Human Rights Commission was established under which law?","Protection of Human Rights Act, 1993","Right to Information Act, 2005","Central Vigilance Commission Act, 2003","Lokpal and Lokayuktas Act, 2013","The NHRC was established under the Protection of Human Rights Act, 1993, which was later amended, including by the 2019 Amendment Act.",H],
  ["POL-023-QL-003","Easy","When was the National Human Rights Commission established?","12 October 1993","1 January 2015","12 October 2005","16 January 2014","The National Human Rights Commission came into existence on 12 October 1993 under the Protection of Human Rights Act, 1993.",H],
  ["POL-023-QL-003","Easy","Which description correctly classifies the NHRC?","Statutory body","Constitutional body","Executive body created only by resolution","Court established by the Constitution","NHRC is a statutory commission because its legal basis is the Protection of Human Rights Act, 1993 rather than the Constitution.",H],
  ["POL-023-QL-003","Easy","Under the Human Rights Act, human rights broadly relate to which values?","Life, liberty, equality and dignity","Taxation, trade, customs and banking","Elections, delimitation, parties and symbols","Defence, railways, currency and posts","The Act defines human rights around life, liberty, equality and dignity guaranteed by the Constitution or recognised international covenants and enforceable by courts.",H],
  ["POL-023-QL-004","Easy","Who may serve as Chairperson of the NHRC under the amended law?","A former Chief Justice of India or Supreme Court Judge","Only a serving High Court Judge","Only a former Governor","Only a retired Cabinet Secretary","The amended Act broadens eligibility for the NHRC Chairperson.\n\nQualifications:\n- has been Chief Justice of India; or\n- has been a Judge of the Supreme Court.",H],
  ["POL-023-QL-004","Easy","Besides the Chairperson, how many full-time Members does the NHRC have under Section 3?","Five","Two","Three","Ten","Section 3 provides five full-time Members besides the Chairperson: one Supreme Court Judge category, one former High Court Chief Justice, and three human-rights experts.",H],
  ["POL-023-QL-004","Easy","How many NHRC expert Members must have human-rights knowledge or practical experience?","Three","One","Two","Five","Three NHRC Members are drawn from persons with knowledge of or practical experience in human rights, and at least one must be a woman.",H],
  ["POL-023-QL-004","Easy","What minimum gender requirement applies to the three NHRC human-rights expert Members?","At least one must be a woman","All must be women","Exactly two must be women","No gender requirement exists","The amended Protection of Human Rights Act requires at least one woman among the three Members selected for human-rights knowledge or experience.",H],
  ["POL-023-QL-005","Easy","Who appoints the NHRC Chairperson and Members?","President","Prime Minister","Chief Justice of India","Parliament","The President appoints the NHRC Chairperson and Members on the recommendations of the statutory selection committee headed by the Prime Minister.",H],
  ["POL-023-QL-005","Easy","Who heads the committee recommending appointments to the NHRC?","Prime Minister","President","Speaker of Lok Sabha","Chief Justice of India","The Prime Minister chairs the statutory selection committee that recommends names for appointment as NHRC Chairperson and Members.",H],
  ["POL-023-QL-005","Easy","Which is a core function of the NHRC?","Inquiring into alleged human-rights violations","Conducting civil-service examinations","Recommending tax devolution","Registering political parties","The NHRC may inquire into complaints or certain cases concerning human-rights violations or negligence in preventing such violations.",H],
  ["POL-023-QL-005","Easy","During specified inquiries, the NHRC has powers similar to which body?","Civil court trying a suit","Finance Commission","Election Commission polling team","Municipal corporation","For statutory inquiries, the NHRC has specified powers of a civil court, including summoning persons and requiring documents.",H],
];
