import type { PhysicsLocaleV1 } from "./sci-physics-localization-types-v1";

type ExplanationSet = Readonly<Record<PhysicsLocaleV1, string>>;
type Row = readonly [en: string, hi: string, pa: string];

function build(cp: "005" | "006", rows: readonly Row[]): Readonly<Record<string, ExplanationSet>> {
  return Object.freeze(Object.fromEntries(rows.map((row, index) => [
    `SCI-CP${cp}-EXH-A${String(index + 1).padStart(2, "0")}`,
    { en: row[0], hi: row[1], pa: row[2] } satisfies ExplanationSet,
  ])));
}

const CP005: readonly Row[] = [
  ["Temperature describes how hot or cold a body is; it is not the same as the total heat stored in the body. Heat flows spontaneously from a higher-temperature body to a lower-temperature body until thermal equilibrium is reached.", "तापमान किसी वस्तु के गर्म या ठंडा होने की अवस्था बताता है; यह वस्तु में मौजूद कुल ऊष्मा के समान नहीं है। ऊष्मा अधिक तापमान वाली वस्तु से कम तापमान वाली वस्तु की ओर बहती है।", "ਤਾਪਮਾਨ ਕਿਸੇ ਵਸਤੂ ਦੇ ਗਰਮ ਜਾਂ ਠੰਢਾ ਹੋਣ ਦੀ ਅਵਸਥਾ ਦੱਸਦਾ ਹੈ; ਇਹ ਵਸਤੂ ਵਿੱਚ ਮੌਜੂਦ ਕੁੱਲ ਤਾਪ ਦੇ ਬਰਾਬਰ ਨਹੀਂ ਹੁੰਦਾ। ਤਾਪ ਵੱਧ ਤਾਪਮਾਨ ਵਾਲੀ ਵਸਤੂ ਤੋਂ ਘੱਟ ਤਾਪਮਾਨ ਵਾਲੀ ਵਸਤੂ ਵੱਲ ਜਾਂਦਾ ਹੈ।"],
  ["Two bodies are in thermal equilibrium when they have the same temperature and therefore exchange no net heat. They need not have the same mass, volume or total internal energy.", "दो वस्तुएँ तापीय संतुलन में तब होती हैं जब उनका तापमान समान हो और उनके बीच शुद्ध ऊष्मा प्रवाह न हो। उनका द्रव्यमान, आयतन या कुल आंतरिक ऊर्जा समान होना आवश्यक नहीं है।", "ਦੋ ਵਸਤੂਆਂ ਤਾਪੀ ਸੰਤੁਲਨ ਵਿੱਚ ਤਦੋਂ ਹੁੰਦੀਆਂ ਹਨ ਜਦੋਂ ਉਨ੍ਹਾਂ ਦਾ ਤਾਪਮਾਨ ਇੱਕੋ ਹੋਵੇ ਅਤੇ ਉਨ੍ਹਾਂ ਵਿਚਕਾਰ ਕੁੱਲ ਤਾਪ ਪ੍ਰਵਾਹ ਨਾ ਹੋਵੇ। ਉਨ੍ਹਾਂ ਦਾ ਪੁੰਜ, ਆਇਤਨ ਜਾਂ ਕੁੱਲ ਅੰਦਰੂਨੀ ਊਰਜਾ ਇੱਕੋ ਹੋਣਾ ਲਾਜ਼ਮੀ ਨਹੀਂ।"],
  ["Kelvin and Celsius have the same size degree, but their zero points differ. The school-level conversion is K ≈ °C + 273, so 0°C is about 273 K.", "केल्विन और सेल्सियस में एक डिग्री का आकार समान होता है, पर उनके शून्य बिंदु अलग हैं। सामान्य रूपांतरण K ≈ °C + 273 है, इसलिए 0°C लगभग 273 K होता है।", "ਕੈਲਵਿਨ ਅਤੇ ਸੈਲਸੀਅਸ ਵਿੱਚ ਇੱਕ ਡਿਗਰੀ ਦਾ ਅੰਤਰ ਇੱਕੋ ਹੁੰਦਾ ਹੈ, ਪਰ ਉਨ੍ਹਾਂ ਦੇ ਸਿਫ਼ਰ ਬਿੰਦੂ ਵੱਖ ਹਨ। ਆਮ ਬਦਲਾਅ K ≈ °C + 273 ਹੈ, ਇਸ ਲਈ 0°C ਲਗਭਗ 273 K ਹੁੰਦਾ ਹੈ।"],
  ["A clinical thermometer is designed for the narrow temperature range of the human body. It is not intended for measuring very high temperatures such as boiling water.", "क्लिनिकल थर्मामीटर मानव शरीर की अपेक्षाकृत छोटी तापमान सीमा मापने के लिए बनाया जाता है। उबलते पानी जैसे बहुत ऊँचे तापमान मापने के लिए इसका उपयोग नहीं किया जाता।", "ਕਲੀਨੀਕਲ ਥਰਮਾਮੀਟਰ ਮਨੁੱਖੀ ਸਰੀਰ ਦੀ ਛੋਟੀ ਤਾਪਮਾਨ ਸੀਮਾ ਮਾਪਣ ਲਈ ਬਣਾਇਆ ਜਾਂਦਾ ਹੈ। ਉਬਲਦੇ ਪਾਣੀ ਵਰਗੇ ਬਹੁਤ ਉੱਚੇ ਤਾਪਮਾਨ ਮਾਪਣ ਲਈ ਇਸ ਦੀ ਵਰਤੋਂ ਨਹੀਂ ਕੀਤੀ ਜਾਂਦੀ।"],
  ["Heating usually increases the average separation between particles in a solid, so most solids expand. This is why expansion gaps are provided in structures such as railway tracks and bridges.", "गर्म करने पर ठोस के कणों के बीच औसत दूरी बढ़ती है, इसलिए अधिकांश ठोस फैलते हैं। इसी कारण रेलवे पटरियों और पुलों जैसी संरचनाओं में प्रसार के लिए जगह छोड़ी जाती है।", "ਗਰਮ ਕਰਨ ਨਾਲ ਠੋਸ ਦੇ ਕਣਾਂ ਵਿਚਕਾਰ ਔਸਤ ਦੂਰੀ ਵਧਦੀ ਹੈ, ਇਸ ਲਈ ਜ਼ਿਆਦਾਤਰ ਠੋਸ ਫੈਲਦੇ ਹਨ। ਇਸੇ ਕਰਕੇ ਰੇਲ ਪਟੜੀਆਂ ਅਤੇ ਪੁਲਾਂ ਵਰਗੀਆਂ ਬਣਤਰਾਂ ਵਿੱਚ ਪ੍ਰਸਾਰ ਲਈ ਥਾਂ ਛੱਡੀ ਜਾਂਦੀ ਹੈ।"],
  ["A bimetallic strip contains two bonded metals with different coefficients of thermal expansion. When heated, one expands more than the other, so the strip bends and can operate devices such as thermostats.", "द्विधातु पट्टी में दो ऐसी धातुएँ जुड़ी होती हैं जिनकी तापीय प्रसार दर अलग होती है। गर्म करने पर एक धातु अधिक फैलती है, इसलिए पट्टी मुड़ती है और थर्मोस्टेट जैसे उपकरणों में काम करती है।", "ਦੋ-ਧਾਤੀ ਪੱਟੀ ਵਿੱਚ ਦੋ ਐਸੀਆਂ ਧਾਤਾਂ ਜੁੜੀਆਂ ਹੁੰਦੀਆਂ ਹਨ ਜਿਨ੍ਹਾਂ ਦੀ ਤਾਪੀ ਪ੍ਰਸਾਰ ਦਰ ਵੱਖ ਹੁੰਦੀ ਹੈ। ਗਰਮ ਕਰਨ ਤੇ ਇੱਕ ਧਾਤ ਵੱਧ ਫੈਲਦੀ ਹੈ, ਇਸ ਲਈ ਪੱਟੀ ਮੁੜਦੀ ਹੈ ਅਤੇ ਥਰਮੋਸਟੈਟ ਵਰਗੇ ਯੰਤਰਾਂ ਵਿੱਚ ਕੰਮ ਕਰਦੀ ਹੈ।"],
  ["Water has maximum density at about 4°C. Between 4°C and 0°C it expands on further cooling, an anomalous behaviour that helps lakes freeze first at the surface.", "जल का घनत्व लगभग 4°C पर अधिकतम होता है। 4°C से 0°C तक और ठंडा करने पर जल फैलता है; इसी असामान्य व्यवहार के कारण झीलें पहले सतह से जमती हैं।", "ਪਾਣੀ ਦੀ ਘਣਤਾ ਲਗਭਗ 4°C ਤੇ ਸਭ ਤੋਂ ਵੱਧ ਹੁੰਦੀ ਹੈ। 4°C ਤੋਂ 0°C ਤੱਕ ਹੋਰ ਠੰਢਾ ਕਰਨ ਤੇ ਪਾਣੀ ਫੈਲਦਾ ਹੈ; ਇਸ ਅਸਧਾਰਣ ਵਿਹਾਰ ਕਰਕੇ ਝੀਲਾਂ ਪਹਿਲਾਂ ਸਤਹ ਤੋਂ ਜਮਦੀਆਂ ਹਨ।"],
  ["Conduction transfers heat through particle-to-particle interaction without bulk movement of the material. It is especially important in solids, where neighbouring particles pass energy along the material.", "चालन में पदार्थ का बड़े पैमाने पर स्थानांतरण किए बिना कणों के परस्पर संपर्क से ऊष्मा आगे बढ़ती है। यह विशेष रूप से ठोसों में महत्वपूर्ण है, जहाँ पड़ोसी कण ऊर्जा आगे पहुँचाते हैं।", "ਚਾਲਨ ਵਿੱਚ ਪਦਾਰਥ ਦੀ ਵੱਡੇ ਪੱਧਰ ਦੀ ਗਤੀ ਬਿਨਾਂ ਕਣਾਂ ਦੇ ਪਰਸਪਰ ਸੰਪਰਕ ਰਾਹੀਂ ਤਾਪ ਅੱਗੇ ਜਾਂਦਾ ਹੈ। ਇਹ ਖ਼ਾਸ ਤੌਰ ਤੇ ਠੋਸਾਂ ਵਿੱਚ ਮਹੱਤਵਪੂਰਨ ਹੈ, ਜਿੱਥੇ ਨੇੜਲੇ ਕਣ ਊਰਜਾ ਅੱਗੇ ਪਹੁੰਚਾਉਂਦੇ ਹਨ।"],
  ["Metals such as copper are good thermal conductors because energy is transferred through them efficiently. Materials such as wood, wool and trapped air are much poorer conductors and therefore act as insulators.", "ताँबा जैसी धातुएँ ऊष्मा की अच्छी चालक हैं क्योंकि उनमें ऊर्जा आसानी से आगे बढ़ती है। लकड़ी, ऊन और फँसी हुई वायु खराब चालक होती हैं, इसलिए वे ऊष्मारोधक की तरह काम करती हैं।", "ਤਾਂਬੇ ਵਰਗੀਆਂ ਧਾਤਾਂ ਤਾਪ ਦੀਆਂ ਚੰਗੀਆਂ ਚਾਲਕ ਹਨ ਕਿਉਂਕਿ ਉਨ੍ਹਾਂ ਵਿੱਚ ਊਰਜਾ ਆਸਾਨੀ ਨਾਲ ਅੱਗੇ ਜਾਂਦੀ ਹੈ। ਲੱਕੜ, ਉੱਨ ਅਤੇ ਫਸੀ ਹਵਾ ਮਾੜੀਆਂ ਚਾਲਕ ਹਨ, ਇਸ ਲਈ ਇਹ ਤਾਪ-ਰੋਧਕ ਵਾਂਗ ਕੰਮ ਕਰਦੀਆਂ ਹਨ।"],
  ["Convection transfers heat by the bulk movement of a fluid. Warmer fluid generally becomes less dense and rises, while cooler denser fluid sinks, setting up convection currents.", "संवहन में द्रव या गैस की बड़े पैमाने की गति से ऊष्मा का स्थानांतरण होता है। गर्म द्रव सामान्यतः कम घनत्व का होकर ऊपर उठता है और ठंडा, अधिक घनत्व वाला द्रव नीचे आता है।", "ਸੰਵਹਨ ਵਿੱਚ ਤਰਲ ਜਾਂ ਗੈਸ ਦੀ ਵੱਡੇ ਪੱਧਰ ਦੀ ਗਤੀ ਨਾਲ ਤਾਪ ਦਾ ਸੰਚਾਰ ਹੁੰਦਾ ਹੈ। ਗਰਮ ਤਰਲ ਆਮ ਤੌਰ ਤੇ ਘੱਟ ਘਣਤਾ ਵਾਲਾ ਹੋ ਕੇ ਉੱਪਰ ਚੜ੍ਹਦਾ ਹੈ ਅਤੇ ਠੰਢਾ, ਵੱਧ ਘਣਤਾ ਵਾਲਾ ਤਰਲ ਹੇਠਾਂ ਆਉਂਦਾ ਹੈ।"],
  ["During the day, land heats faster than the sea, so warm air over land rises. Cooler air then moves from the sea toward the land, producing a sea breeze.", "दिन में स्थल समुद्र की तुलना में जल्दी गर्म होता है और उसके ऊपर की गर्म वायु ऊपर उठती है। उसकी जगह लेने के लिए समुद्र से ठंडी वायु स्थल की ओर आती है, जिससे समुद्री समीर बनती है।", "ਦਿਨ ਵੇਲੇ ਧਰਤੀ ਸਮੁੰਦਰ ਨਾਲੋਂ ਜਲਦੀ ਗਰਮ ਹੁੰਦੀ ਹੈ ਅਤੇ ਉਸ ਦੇ ਉੱਪਰ ਦੀ ਗਰਮ ਹਵਾ ਚੜ੍ਹਦੀ ਹੈ। ਉਸ ਦੀ ਥਾਂ ਲੈਣ ਲਈ ਸਮੁੰਦਰ ਤੋਂ ਠੰਢੀ ਹਵਾ ਧਰਤੀ ਵੱਲ ਆਉਂਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਸਮੁੰਦਰੀ ਹਵਾ ਬਣਦੀ ਹੈ।"],
  ["At night, land cools faster than the sea, so the air above the sea remains relatively warmer. Cooler denser air therefore moves from land toward the sea, producing a land breeze.", "रात में स्थल समुद्र की तुलना में जल्दी ठंडा होता है, इसलिए समुद्र के ऊपर की वायु अपेक्षाकृत गर्म रहती है। ठंडी और अधिक घनी वायु स्थल से समुद्र की ओर चलती है, जिससे स्थलीय समीर बनती है।", "ਰਾਤ ਨੂੰ ਧਰਤੀ ਸਮੁੰਦਰ ਨਾਲੋਂ ਜਲਦੀ ਠੰਢੀ ਹੁੰਦੀ ਹੈ, ਇਸ ਲਈ ਸਮੁੰਦਰ ਦੇ ਉੱਪਰ ਦੀ ਹਵਾ ਤੁਲਨਾਤਮਕ ਤੌਰ ਤੇ ਗਰਮ ਰਹਿੰਦੀ ਹੈ। ਠੰਢੀ ਅਤੇ ਵੱਧ ਘਣਤਾ ਵਾਲੀ ਹਵਾ ਧਰਤੀ ਤੋਂ ਸਮੁੰਦਰ ਵੱਲ ਵੱਗਦੀ ਹੈ।"],
  ["Radiation transfers thermal energy through electromagnetic waves and does not require a material medium. Therefore heat from the Sun can cross the vacuum of space and reach Earth.", "विकिरण विद्युतचुंबकीय तरंगों द्वारा ऊष्मीय ऊर्जा का स्थानांतरण करता है और इसके लिए भौतिक माध्यम आवश्यक नहीं है। इसलिए सूर्य की ऊष्मा अंतरिक्ष के निर्वात को पार करके पृथ्वी तक पहुँच सकती है।", "ਵਿਕਿਰਣ ਬਿਜਲ-ਚੁੰਬਕੀ ਤਰੰਗਾਂ ਰਾਹੀਂ ਤਾਪੀ ਊਰਜਾ ਦਾ ਸੰਚਾਰ ਕਰਦਾ ਹੈ ਅਤੇ ਇਸ ਲਈ ਪਦਾਰਥਕ ਮਾਧਿਅਮ ਲੋੜੀਂਦਾ ਨਹੀਂ। ਇਸ ਕਰਕੇ ਸੂਰਜ ਦਾ ਤਾਪ ਅੰਤਰਿਕਸ਼ ਦੇ ਨਿਰਵਾਤ ਵਿੱਚੋਂ ਲੰਘ ਕੇ ਧਰਤੀ ਤੱਕ ਪਹੁੰਚਦਾ ਹੈ।"],
  ["Dull black surfaces are good absorbers as well as good emitters of thermal radiation. Shiny polished surfaces are comparatively poor absorbers and good reflectors, which is why reflective surfaces reduce radiative heat transfer.", "काली और खुरदरी सतहें ऊष्मीय विकिरण की अच्छी अवशोषक और अच्छी उत्सर्जक होती हैं। चमकीली पॉलिश सतहें अपेक्षाकृत खराब अवशोषक और अच्छी परावर्तक होती हैं।", "ਕਾਲੀਆਂ ਅਤੇ ਖੁਰਦਰੀਆਂ ਸਤਹਾਂ ਤਾਪੀ ਵਿਕਿਰਣ ਦੀਆਂ ਚੰਗੀਆਂ ਅਵਸ਼ੋਸ਼ਕ ਅਤੇ ਚੰਗੀਆਂ ਉਤਸਰਜਕ ਹੁੰਦੀਆਂ ਹਨ। ਚਮਕੀਲੀਆਂ ਪਾਲਿਸ਼ ਸਤਹਾਂ ਤੁਲਨਾਤਮਕ ਤੌਰ ਤੇ ਮਾੜੀਆਂ ਅਵਸ਼ੋਸ਼ਕ ਅਤੇ ਚੰਗੀਆਂ ਪਰਾਵਰਤਕ ਹੁੰਦੀਆਂ ਹਨ।"],
  ["Specific heat capacity is the heat needed to raise the temperature of unit mass of a substance by one degree. From Q = mcΔT, a larger specific heat means more heat is needed for the same mass and temperature rise.", "विशिष्ट ऊष्मा धारिता वह ऊष्मा है जो इकाई द्रव्यमान का तापमान 1 डिग्री बढ़ाने के लिए चाहिए। Q = mcΔT के अनुसार अधिक विशिष्ट ऊष्मा वाले पदार्थ को समान ताप-वृद्धि के लिए अधिक ऊष्मा चाहिए।", "ਵਿਸ਼ੇਸ਼ ਤਾਪ ਸਮਰੱਥਾ ਉਹ ਤਾਪ ਹੈ ਜੋ ਇਕਾਈ ਪੁੰਜ ਦਾ ਤਾਪਮਾਨ 1 ਡਿਗਰੀ ਵਧਾਉਣ ਲਈ ਚਾਹੀਦਾ ਹੈ। Q = mcΔT ਅਨੁਸਾਰ ਵੱਧ ਵਿਸ਼ੇਸ਼ ਤਾਪ ਵਾਲੇ ਪਦਾਰਥ ਨੂੰ ਇੱਕੋ ਤਾਪ-ਵਾਧੇ ਲਈ ਵੱਧ ਤਾਪ ਚਾਹੀਦਾ ਹੈ।"],
  ["In ideal calorimetry, the system is treated as thermally isolated, so energy is conserved within it. Hence heat lost by the hotter body equals heat gained by the colder body until they reach a common temperature.", "आदर्श कैलोरीमिति में तंत्र को ऊष्मीय रूप से पृथक माना जाता है, इसलिए ऊर्जा संरक्षित रहती है। इस कारण गर्म वस्तु द्वारा खोई ऊष्मा ठंडी वस्तु द्वारा प्राप्त ऊष्मा के बराबर होती है।", "ਆਦਰਸ਼ ਕੈਲੋਰੀਮਿਤੀ ਵਿੱਚ ਪ੍ਰਣਾਲੀ ਨੂੰ ਤਾਪੀ ਤੌਰ ਤੇ ਅਲੱਗ ਮੰਨਿਆ ਜਾਂਦਾ ਹੈ, ਇਸ ਲਈ ਊਰਜਾ ਸੰਰੱਖਿਤ ਰਹਿੰਦੀ ਹੈ। ਇਸ ਕਰਕੇ ਗਰਮ ਵਸਤੂ ਵੱਲੋਂ ਗੁਆਇਆ ਤਾਪ ਠੰਢੀ ਵਸਤੂ ਵੱਲੋਂ ਪ੍ਰਾਪਤ ਤਾਪ ਦੇ ਬਰਾਬਰ ਹੁੰਦਾ ਹੈ।"],
  ["During melting at the melting point, supplied heat is used mainly to overcome intermolecular attractions and change the state. The temperature therefore remains nearly constant until the phase change is complete; this energy is latent heat.", "गलनांक पर पिघलते समय दी गई ऊष्मा मुख्यतः अवस्था बदलने में उपयोग होती है, तापमान बढ़ाने में नहीं। इसलिए अवस्था परिवर्तन पूरा होने तक तापमान लगभग स्थिर रहता है; इस ऊर्जा को गुप्त ऊष्मा कहते हैं।", "ਪਿਘਲਣ ਅੰਕ ਤੇ ਦਿੱਤਾ ਤਾਪ ਮੁੱਖ ਤੌਰ ਤੇ ਅਵਸਥਾ ਬਦਲਣ ਲਈ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ, ਤਾਪਮਾਨ ਵਧਾਉਣ ਲਈ ਨਹੀਂ। ਇਸ ਲਈ ਅਵਸਥਾ-ਬਦਲਾਅ ਪੂਰਾ ਹੋਣ ਤੱਕ ਤਾਪਮਾਨ ਲਗਭਗ ਸਥਿਰ ਰਹਿੰਦਾ ਹੈ; ਇਸ ਨੂੰ ਗੁਪਤ ਤਾਪ ਕਹਿੰਦੇ ਹਨ।"],
  ["Evaporation preferentially removes faster, higher-energy molecules from a liquid surface. The average kinetic energy of the molecules left behind decreases, so the liquid cools.", "वाष्पीकरण में सतह से अधिक ऊर्जा वाले तेज अणु पहले बाहर निकलते हैं। पीछे बचे अणुओं की औसत गतिज ऊर्जा घट जाती है, इसलिए तरल ठंडा हो जाता है।", "ਵਾਸ਼ਪੀਕਰਨ ਵਿੱਚ ਸਤਹ ਤੋਂ ਵੱਧ ਊਰਜਾ ਵਾਲੇ ਤੇਜ਼ ਅਣੂ ਪਹਿਲਾਂ ਬਾਹਰ ਨਿਕਲਦੇ ਹਨ। ਪਿੱਛੇ ਬਚੇ ਅਣੂਆਂ ਦੀ ਔਸਤ ਗਤਿਜ ਊਰਜਾ ਘਟ ਜਾਂਦੀ ਹੈ, ਇਸ ਲਈ ਤਰਲ ਠੰਢਾ ਹੋ ਜਾਂਦਾ ਹੈ।"],
  ["Increasing pressure raises the boiling point of water inside a pressure cooker. Water and steam can therefore reach a temperature above 100°C, allowing food to cook faster.", "प्रेशर कुकर में दाब बढ़ने से पानी का क्वथनांक बढ़ जाता है। इसलिए पानी और भाप 100°C से अधिक तापमान तक पहुँच सकते हैं और भोजन जल्दी पकता है।", "ਪ੍ਰੈਸ਼ਰ ਕੁੱਕਰ ਵਿੱਚ ਦਬਾਅ ਵਧਣ ਨਾਲ ਪਾਣੀ ਦਾ ਉਬਾਲ ਅੰਕ ਵਧ ਜਾਂਦਾ ਹੈ। ਇਸ ਲਈ ਪਾਣੀ ਅਤੇ ਭਾਫ਼ 100°C ਤੋਂ ਵੱਧ ਤਾਪਮਾਨ ਤੱਕ ਪਹੁੰਚ ਸਕਦੇ ਹਨ ਅਤੇ ਭੋਜਨ ਜਲਦੀ ਪੱਕਦਾ ਹੈ।"],
  ["Inside a refrigerator, the refrigerant evaporates at low pressure and absorbs latent heat from the cabinet. It later releases this heat to the surroundings while condensing outside the cooled space.", "रेफ्रिजरेटर के भीतर कम दाब पर शीतलक वाष्पित होकर अंदर से गुप्त ऊष्मा अवशोषित करता है। बाद में यह बाहर संघनित होते समय वही ऊष्मा वातावरण में छोड़ देता है।", "ਫ੍ਰਿਜ ਦੇ ਅੰਦਰ ਘੱਟ ਦਬਾਅ ਤੇ ਰੈਫ੍ਰਿਜਰੈਂਟ ਵਾਸ਼ਪੀਕਰਨ ਕਰਕੇ ਅੰਦਰੋਂ ਗੁਪਤ ਤਾਪ ਸੋਖਦਾ ਹੈ। ਬਾਅਦ ਵਿੱਚ ਬਾਹਰ ਸੰਘਣਨ ਦੌਰਾਨ ਇਹ ਤਾਪ ਵਾਤਾਵਰਣ ਵਿੱਚ ਛੱਡ ਦਿੰਦਾ ਹੈ।"],
  ["A vacuum contains very few particles, so conduction and convection through the gap of a thermos are greatly reduced. Reflective surfaces are used separately to reduce heat transfer by radiation.", "निर्वात में कण बहुत कम होते हैं, इसलिए थर्मस की दीवारों के बीच चालन और संवहन बहुत कम हो जाते हैं। विकिरण कम करने के लिए अलग से चमकीली परावर्तक सतहें उपयोग की जाती हैं।", "ਨਿਰਵਾਤ ਵਿੱਚ ਕਣ ਬਹੁਤ ਘੱਟ ਹੁੰਦੇ ਹਨ, ਇਸ ਲਈ ਥਰਮਸ ਦੀਆਂ ਕੰਧਾਂ ਵਿਚਕਾਰ ਚਾਲਨ ਅਤੇ ਸੰਵਹਨ ਬਹੁਤ ਘੱਟ ਹੋ ਜਾਂਦੇ ਹਨ। ਵਿਕਿਰਣ ਘਟਾਉਣ ਲਈ ਵੱਖਰੇ ਤੌਰ ਤੇ ਚਮਕੀਲੀਆਂ ਪਰਾਵਰਤਕ ਸਤਹਾਂ ਵਰਤੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।"],
  ["Latent heat of vaporization is the energy needed to change a liquid into gas at constant temperature and pressure conditions. During the phase change, energy changes molecular separation rather than immediately raising temperature.", "वाष्पन की गुप्त ऊष्मा वह ऊर्जा है जो द्रव को गैस में बदलने के लिए आवश्यक होती है। अवस्था परिवर्तन के दौरान ऊर्जा मुख्यतः अणुओं के बीच दूरी बढ़ाने में लगती है, इसलिए तापमान तुरंत नहीं बढ़ता।", "ਵਾਸ਼ਪੀਕਰਨ ਦਾ ਗੁਪਤ ਤਾਪ ਉਹ ਊਰਜਾ ਹੈ ਜੋ ਤਰਲ ਨੂੰ ਗੈਸ ਵਿੱਚ ਬਦਲਣ ਲਈ ਲੋੜੀਂਦੀ ਹੁੰਦੀ ਹੈ। ਅਵਸਥਾ-ਬਦਲਾਅ ਦੌਰਾਨ ਊਰਜਾ ਮੁੱਖ ਤੌਰ ਤੇ ਅਣੂਆਂ ਦੀ ਦੂਰੀ ਵਧਾਉਣ ਵਿੱਚ ਲੱਗਦੀ ਹੈ, ਇਸ ਲਈ ਤਾਪਮਾਨ ਤੁਰੰਤ ਨਹੀਂ ਵਧਦਾ।"],
  ["For a fixed heat input and equal mass, Q = mcΔT gives ΔT = Q/(mc). Therefore a substance with lower specific heat capacity undergoes a larger temperature rise.", "समान ऊष्मा Q और समान द्रव्यमान m के लिए Q = mcΔT से ΔT = Q/(mc) मिलता है। इसलिए कम विशिष्ट ऊष्मा वाले पदार्थ में तापमान की वृद्धि अधिक होती है।", "ਇੱਕੋ ਤਾਪ Q ਅਤੇ ਇੱਕੋ ਪੁੰਜ m ਲਈ Q = mcΔT ਤੋਂ ΔT = Q/(mc) ਮਿਲਦਾ ਹੈ। ਇਸ ਲਈ ਘੱਟ ਵਿਸ਼ੇਸ਼ ਤਾਪ ਵਾਲੇ ਪਦਾਰਥ ਦਾ ਤਾਪਮਾਨ ਵੱਧ ਚੜ੍ਹਦਾ ਹੈ।"],
  ["To convert Celsius to kelvin at this level, add approximately 273. Thus 27°C corresponds to 27 + 273 = 300 K.", "सेल्सियस से केल्विन में बदलने के लिए लगभग 273 जोड़ते हैं। इसलिए 27°C = 27 + 273 = 300 K होता है।", "ਸੈਲਸੀਅਸ ਤੋਂ ਕੈਲਵਿਨ ਵਿੱਚ ਬਦਲਣ ਲਈ ਲਗਭਗ 273 ਜੋੜਦੇ ਹਾਂ। ਇਸ ਲਈ 27°C = 27 + 273 = 300 K ਹੁੰਦਾ ਹੈ।"],
];

const CP006: readonly Row[] = [
  ["Sound is produced when a source vibrates and disturbs the surrounding medium. Those disturbances travel outward as sound waves, while the source itself need not move from one place to another.", "ध्वनि तब उत्पन्न होती है जब कोई स्रोत कंपन करके आसपास के माध्यम में विक्षोभ पैदा करता है। ये विक्षोभ ध्वनि तरंगों के रूप में आगे बढ़ते हैं।", "ਧੁਨੀ ਤਦੋਂ ਪੈਦਾ ਹੁੰਦੀ ਹੈ ਜਦੋਂ ਕੋਈ ਸਰੋਤ ਕੰਪਨ ਕਰਕੇ ਆਲੇ-ਦੁਆਲੇ ਦੇ ਮਾਧਿਅਮ ਵਿੱਚ ਵਿਘਨ ਪੈਦਾ ਕਰਦਾ ਹੈ। ਇਹ ਵਿਘਨ ਧੁਨੀ ਤਰੰਗਾਂ ਦੇ ਰੂਪ ਵਿੱਚ ਅੱਗੇ ਵਧਦੇ ਹਨ।"],
  ["Sound in air is a mechanical wave because it is transmitted through the motion and interaction of material particles. Unlike electromagnetic waves, ordinary sound cannot propagate without a material medium.", "वायु में ध्वनि यांत्रिक तरंग है क्योंकि इसका संचरण माध्यम के कणों की गति और परस्पर क्रिया से होता है। विद्युतचुंबकीय तरंगों के विपरीत सामान्य ध्वनि को भौतिक माध्यम चाहिए।", "ਹਵਾ ਵਿੱਚ ਧੁਨੀ ਯਾਂਤ੍ਰਿਕ ਤਰੰਗ ਹੈ ਕਿਉਂਕਿ ਇਸ ਦਾ ਸੰਚਾਰ ਮਾਧਿਅਮ ਦੇ ਕਣਾਂ ਦੀ ਗਤੀ ਅਤੇ ਪਰਸਪਰ ਕਿਰਿਆ ਨਾਲ ਹੁੰਦਾ ਹੈ। ਬਿਜਲ-ਚੁੰਬਕੀ ਤਰੰਗਾਂ ਤੋਂ ਵੱਖ ਆਮ ਧੁਨੀ ਲਈ ਪਦਾਰਥਕ ਮਾਧਿਅਮ ਲੋੜੀਂਦਾ ਹੈ।"],
  ["A perfect vacuum contains no particles to pass on mechanical vibrations. Therefore ordinary sound cannot travel through a perfect vacuum, though light and other electromagnetic waves can.", "पूर्ण निर्वात में कंपन आगे पहुँचाने के लिए कण नहीं होते। इसलिए सामान्य ध्वनि पूर्ण निर्वात में नहीं चल सकती, जबकि प्रकाश जैसी विद्युतचुंबकीय तरंगें चल सकती हैं।", "ਪੂਰਨ ਨਿਰਵਾਤ ਵਿੱਚ ਕੰਪਨ ਅੱਗੇ ਪਹੁੰਚਾਉਣ ਲਈ ਕਣ ਨਹੀਂ ਹੁੰਦੇ। ਇਸ ਲਈ ਆਮ ਧੁਨੀ ਪੂਰਨ ਨਿਰਵਾਤ ਵਿੱਚ ਨਹੀਂ ਚੱਲ ਸਕਦੀ, ਜਦਕਿ ਪ੍ਰਕਾਸ਼ ਵਰਗੀਆਂ ਬਿਜਲ-ਚੁੰਬਕੀ ਤਰੰਗਾਂ ਚੱਲ ਸਕਦੀਆਂ ਹਨ।"],
  ["Sound waves in air are mainly longitudinal: air particles vibrate back and forth parallel to the direction in which the wave travels. This produces alternating compressions and rarefactions.", "वायु में ध्वनि तरंगें मुख्यतः अनुदैर्ध्य होती हैं; वायु के कण तरंग के प्रसार की दिशा के समानांतर आगे-पीछे कंपन करते हैं। इससे क्रमशः संपीड़न और विरलन बनते हैं।", "ਹਵਾ ਵਿੱਚ ਧੁਨੀ ਤਰੰਗਾਂ ਮੁੱਖ ਤੌਰ ਤੇ ਅਨੁਦੈਰਘੀ ਹੁੰਦੀਆਂ ਹਨ; ਹਵਾ ਦੇ ਕਣ ਤਰੰਗ ਦੇ ਫੈਲਣ ਦੀ ਦਿਸ਼ਾ ਦੇ ਸਮਾਂਤਰ ਅੱਗੇ-ਪਿੱਛੇ ਕੰਪਨ ਕਰਦੇ ਹਨ। ਇਸ ਨਾਲ ਵਾਰ-ਵਾਰ ਸੰਪੀੜਨ ਅਤੇ ਵਿਰਲਨ ਬਣਦੇ ਹਨ।"],
  ["A compression is a region where particles are closer together, so pressure and density are higher than average. A rarefaction is the opposite region, where particles are farther apart.", "संपीड़न वह क्षेत्र है जहाँ कण पास-पास होते हैं, इसलिए दाब और घनत्व औसत से अधिक होते हैं। विरलन में कण अपेक्षाकृत दूर होते हैं और दाब कम होता है।", "ਸੰਪੀੜਨ ਉਹ ਖੇਤਰ ਹੈ ਜਿੱਥੇ ਕਣ ਨੇੜੇ-ਨੇੜੇ ਹੁੰਦੇ ਹਨ, ਇਸ ਲਈ ਦਬਾਅ ਅਤੇ ਘਣਤਾ ਔਸਤ ਨਾਲੋਂ ਵੱਧ ਹੁੰਦੇ ਹਨ। ਵਿਰਲਨ ਵਿੱਚ ਕਣ ਤੁਲਨਾਤਮਕ ਤੌਰ ਤੇ ਦੂਰ ਹੁੰਦੇ ਹਨ ਅਤੇ ਦਬਾਅ ਘੱਟ ਹੁੰਦਾ ਹੈ।"],
  ["Pitch is the sensation mainly associated with frequency. A higher-frequency sound is generally heard as a higher-pitched or sharper sound, while amplitude mainly affects loudness.", "तारता मुख्यतः ध्वनि की आवृत्ति से जुड़ी अनुभूति है। अधिक आवृत्ति वाली ध्वनि अधिक तीखी सुनाई देती है, जबकि आयाम मुख्यतः प्रबलता को प्रभावित करता है।", "ਤਾਰਤਾ ਮੁੱਖ ਤੌਰ ਤੇ ਧੁਨੀ ਦੀ ਆਵਿਰਤੀ ਨਾਲ ਜੁੜੀ ਅਨੁਭੂਤੀ ਹੈ। ਵੱਧ ਆਵਿਰਤੀ ਵਾਲੀ ਧੁਨੀ ਵੱਧ ਤਿੱਖੀ ਸੁਣਾਈ ਦਿੰਦੀ ਹੈ, ਜਦਕਿ ਆਯਾਮ ਮੁੱਖ ਤੌਰ ਤੇ ਪ੍ਰਬਲਤਾ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ।"],
  ["Loudness is mainly related to the amplitude of vibration and the resulting sound intensity. Increasing amplitude generally makes a sound louder, whereas frequency mainly changes pitch.", "ध्वनि की प्रबलता मुख्यतः कंपन के आयाम और उससे जुड़ी ध्वनि तीव्रता पर निर्भर करती है। आयाम बढ़ने पर ध्वनि सामान्यतः अधिक तेज सुनाई देती है, जबकि आवृत्ति मुख्यतः तारता बदलती है।", "ਧੁਨੀ ਦੀ ਪ੍ਰਬਲਤਾ ਮੁੱਖ ਤੌਰ ਤੇ ਕੰਪਨ ਦੇ ਆਯਾਮ ਅਤੇ ਉਸ ਨਾਲ ਜੁੜੀ ਧੁਨੀ ਤੀਬਰਤਾ ਤੇ ਨਿਰਭਰ ਕਰਦੀ ਹੈ। ਆਯਾਮ ਵਧਣ ਨਾਲ ਧੁਨੀ ਆਮ ਤੌਰ ਤੇ ਵੱਧ ਉੱਚੀ ਸੁਣਾਈ ਦਿੰਦੀ ਹੈ, ਜਦਕਿ ਆਵਿਰਤੀ ਮੁੱਖ ਤੌਰ ਤੇ ਤਾਰਤਾ ਬਦਲਦੀ ਹੈ।"],
  ["Frequency is the number of oscillations per second and time period is the time for one oscillation. They are reciprocals, so f = 1/T and T = 1/f.", "आवृत्ति प्रति सेकंड कंपन की संख्या है और आवर्तकाल एक कंपन में लगा समय है। दोनों व्युत्क्रम हैं, इसलिए f = 1/T और T = 1/f।", "ਆਵਿਰਤੀ ਪ੍ਰਤੀ ਸਕਿੰਟ ਕੰਪਨਾਂ ਦੀ ਗਿਣਤੀ ਹੈ ਅਤੇ ਆਵਰਤ-ਕਾਲ ਇੱਕ ਕੰਪਨ ਲਈ ਲੱਗਿਆ ਸਮਾਂ ਹੈ। ਦੋਵੇਂ ਇੱਕ-ਦੂਜੇ ਦੇ ਉਲਟ ਹਨ, ਇਸ ਲਈ f = 1/T ਅਤੇ T = 1/f।"],
  ["Wave speed is related to frequency and wavelength by v = fλ. If the speed in a medium is fixed, increasing frequency decreases wavelength proportionally.", "तरंग की चाल, आवृत्ति और तरंगदैर्ध्य का संबंध v = fλ है। किसी निश्चित माध्यम में चाल स्थिर हो तो आवृत्ति बढ़ने पर तरंगदैर्ध्य उसी अनुपात में घटता है।", "ਤਰੰਗ ਦੀ ਚਾਲ, ਆਵਿਰਤੀ ਅਤੇ ਤਰੰਗ-ਲੰਬਾਈ ਦਾ ਸੰਬੰਧ v = fλ ਹੈ। ਕਿਸੇ ਨਿਸ਼ਚਿਤ ਮਾਧਿਅਮ ਵਿੱਚ ਚਾਲ ਸਥਿਰ ਹੋਵੇ ਤਾਂ ਆਵਿਰਤੀ ਵਧਣ ਨਾਲ ਤਰੰਗ-ਲੰਬਾਈ ਉਸੇ ਅਨੁਪਾਤ ਵਿੱਚ ਘਟਦੀ ਹੈ।"],
  ["Sound generally travels fastest in solids, slower in liquids and slowest in gases under comparable conditions. Stronger particle coupling and elastic response in solids transmit disturbances rapidly.", "सामान्य परिस्थितियों में ध्वनि ठोसों में सबसे तेज, द्रवों में उससे धीमी और गैसों में सबसे धीमी चलती है। ठोसों में कणों का मजबूत पारस्परिक संपर्क कंपन को तेजी से आगे पहुँचाता है।", "ਆਮ ਹਾਲਾਤਾਂ ਵਿੱਚ ਧੁਨੀ ਠੋਸਾਂ ਵਿੱਚ ਸਭ ਤੋਂ ਤੇਜ਼, ਤਰਲਾਂ ਵਿੱਚ ਉਸ ਨਾਲੋਂ ਹੌਲੀ ਅਤੇ ਗੈਸਾਂ ਵਿੱਚ ਸਭ ਤੋਂ ਹੌਲੀ ਚੱਲਦੀ ਹੈ। ਠੋਸਾਂ ਵਿੱਚ ਕਣਾਂ ਦਾ ਮਜ਼ਬੂਤ ਪਰਸਪਰ ਸੰਪਰਕ ਕੰਪਨ ਨੂੰ ਤੇਜ਼ੀ ਨਾਲ ਅੱਗੇ ਪਹੁੰਚਾਉਂਦਾ ਹੈ।"],
  ["A healthy young person can typically hear frequencies from about 20 Hz to 20,000 Hz (20 kHz). The exact upper limit varies with age and individual hearing ability.", "स्वस्थ युवा व्यक्ति की सामान्य श्रव्य सीमा लगभग 20 Hz से 20,000 Hz यानी 20 kHz तक होती है। वास्तविक ऊपरी सीमा आयु और व्यक्ति की श्रवण क्षमता के साथ बदल सकती है।", "ਤੰਦਰੁਸਤ ਨੌਜਵਾਨ ਵਿਅਕਤੀ ਦੀ ਆਮ ਸੁਣਨਯੋਗ ਸੀਮਾ ਲਗਭਗ 20 Hz ਤੋਂ 20,000 Hz ਅਰਥਾਤ 20 kHz ਤੱਕ ਹੁੰਦੀ ਹੈ। ਅਸਲ ਉੱਪਰੀ ਸੀਮਾ ਉਮਰ ਅਤੇ ਵਿਅਕਤੀ ਦੀ ਸੁਣਨ ਸਮਰੱਥਾ ਨਾਲ ਬਦਲ ਸਕਦੀ ਹੈ।"],
  ["Frequencies below about 20 Hz are called infrasonic because they lie below the usual lower limit of human hearing. Some animals and natural events can produce or detect such low-frequency sound.", "लगभग 20 Hz से कम आवृत्ति की ध्वनि अवश्रव्य कहलाती है क्योंकि वह सामान्य मानव श्रवण सीमा से नीचे होती है। कुछ पशु और प्राकृतिक घटनाएँ ऐसी कम आवृत्ति की ध्वनि उत्पन्न या अनुभव कर सकती हैं।", "ਲਗਭਗ 20 Hz ਤੋਂ ਘੱਟ ਆਵਿਰਤੀ ਵਾਲੀ ਧੁਨੀ ਅਵਸ਼੍ਰਵਣ ਕਹਾਉਂਦੀ ਹੈ ਕਿਉਂਕਿ ਇਹ ਮਨੁੱਖ ਦੀ ਆਮ ਸੁਣਨ ਸੀਮਾ ਤੋਂ ਹੇਠਾਂ ਹੁੰਦੀ ਹੈ। ਕੁਝ ਜਾਨਵਰ ਅਤੇ ਕੁਦਰਤੀ ਘਟਨਾਵਾਂ ਐਸੀ ਘੱਟ ਆਵਿਰਤੀ ਦੀ ਧੁਨੀ ਪੈਦਾ ਜਾਂ ਮਹਿਸੂਸ ਕਰ ਸਕਦੀਆਂ ਹਨ।"],
  ["Frequencies above about 20 kHz are called ultrasonic because they lie above the usual upper limit of human hearing. Ultrasound is useful in imaging, cleaning, distance measurement and SONAR.", "लगभग 20 kHz से अधिक आवृत्ति की ध्वनि पराश्रव्य कहलाती है क्योंकि वह सामान्य मानव श्रवण सीमा से ऊपर होती है। पराश्रव्य तरंगों का उपयोग इमेजिंग, सफाई, दूरी मापन और SONAR में किया जाता है।", "ਲਗਭਗ 20 kHz ਤੋਂ ਵੱਧ ਆਵਿਰਤੀ ਵਾਲੀ ਧੁਨੀ ਪਰਾਸ਼੍ਰਵਣ ਕਹਾਉਂਦੀ ਹੈ ਕਿਉਂਕਿ ਇਹ ਮਨੁੱਖ ਦੀ ਆਮ ਸੁਣਨ ਸੀਮਾ ਤੋਂ ਉੱਪਰ ਹੁੰਦੀ ਹੈ। ਪਰਾਸ਼੍ਰਵਣ ਤਰੰਗਾਂ ਦੀ ਵਰਤੋਂ ਤਸਵੀਰ ਬਣਾਉਣ, ਸਫ਼ਾਈ, ਦੂਰੀ ਮਾਪਣ ਅਤੇ SONAR ਵਿੱਚ ਹੁੰਦੀ ਹੈ।"],
  ["An echo is a reflected sound heard separately after the original sound. A sufficiently large time delay is needed so the reflected sound is perceived as a distinct repetition rather than merging with the original.", "प्रतिध्वनि परावर्तित ध्वनि है जो मूल ध्वनि के बाद अलग सुनाई देती है। परावर्तित ध्वनि में पर्याप्त समय-अंतर होना चाहिए, नहीं तो वह मूल ध्वनि के साथ मिल जाती है।", "ਗੂੰਜ ਪਰਾਵਰਤਿਤ ਧੁਨੀ ਹੈ ਜੋ ਮੂਲ ਧੁਨੀ ਤੋਂ ਬਾਅਦ ਵੱਖ ਸੁਣਾਈ ਦਿੰਦੀ ਹੈ। ਪਰਾਵਰਤਿਤ ਧੁਨੀ ਵਿੱਚ ਕਾਫ਼ੀ ਸਮਾਂ-ਅੰਤਰ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ, ਨਹੀਂ ਤਾਂ ਇਹ ਮੂਲ ਧੁਨੀ ਨਾਲ ਮਿਲ ਜਾਂਦੀ ਹੈ।"],
  ["SONAR sends ultrasonic sound pulses through water and detects their echoes. Measuring the travel time and knowing sound speed allows distance or depth to be estimated using the round-trip relation d = vt/2.", "SONAR जल में पराश्रव्य ध्वनि स्पंद भेजता है और उनकी प्रतिध्वनि प्राप्त करता है। समय और ध्वनि की चाल जानकर d = vt/2 से दूरी या गहराई निकाली जा सकती है।", "SONAR ਪਾਣੀ ਵਿੱਚ ਪਰਾਸ਼੍ਰਵਣ ਧੁਨੀ ਪਲਸ ਭੇਜਦਾ ਹੈ ਅਤੇ ਉਨ੍ਹਾਂ ਦੀ ਗੂੰਜ ਪ੍ਰਾਪਤ ਕਰਦਾ ਹੈ। ਸਮਾਂ ਅਤੇ ਧੁਨੀ ਦੀ ਚਾਲ ਜਾਣ ਕੇ d = vt/2 ਨਾਲ ਦੂਰੀ ਜਾਂ ਡੂੰਘਾਈ ਕੱਢੀ ਜਾ ਸਕਦੀ ਹੈ।"],
  ["Medical ultrasonography uses high-frequency sound waves and the echoes reflected from boundaries inside the body. A computer processes these echoes to form images without using ionising X-rays.", "चिकित्सीय अल्ट्रासोनोग्राफी उच्च आवृत्ति की ध्वनि और शरीर के भीतर से लौटने वाली प्रतिध्वनियों का उपयोग करती है। कंप्यूटर इन संकेतों से छवि बनाता है और इसमें आयनीकारी X-किरणों की आवश्यकता नहीं होती।", "ਮੈਡੀਕਲ ਅਲਟ੍ਰਾਸੋਨੋਗ੍ਰਾਫੀ ਉੱਚ ਆਵਿਰਤੀ ਦੀ ਧੁਨੀ ਅਤੇ ਸਰੀਰ ਦੇ ਅੰਦਰੋਂ ਵਾਪਸ ਆਉਣ ਵਾਲੀਆਂ ਗੂੰਜਾਂ ਦੀ ਵਰਤੋਂ ਕਰਦੀ ਹੈ। ਕੰਪਿਊਟਰ ਇਨ੍ਹਾਂ ਸੰਕੇਤਾਂ ਤੋਂ ਤਸਵੀਰ ਬਣਾਉਂਦਾ ਹੈ ਅਤੇ ਇਸ ਵਿੱਚ ਆਇਓਨਾਈਜ਼ਿੰਗ X-ਕਿਰਨਾਂ ਦੀ ਲੋੜ ਨਹੀਂ ਹੁੰਦੀ।"],
  ["Incoming sound waves make the eardrum vibrate. The middle-ear bones transmit and amplify these vibrations toward the inner ear, where they are converted into nerve signals.", "आने वाली ध्वनि तरंगें कान के पर्दे को कंपन कराती हैं। मध्य कान की अस्थियाँ इन कंपनों को अंदर के कान तक पहुँचाती और बढ़ाती हैं, जहाँ वे तंत्रिका संकेतों में बदलते हैं।", "ਆਉਣ ਵਾਲੀਆਂ ਧੁਨੀ ਤਰੰਗਾਂ ਕੰਨ ਦੇ ਪਰਦੇ ਨੂੰ ਕੰਪਨ ਕਰਾਉਂਦੀਆਂ ਹਨ। ਮੱਧ ਕੰਨ ਦੀਆਂ ਹੱਡੀਆਂ ਇਨ੍ਹਾਂ ਕੰਪਨਾਂ ਨੂੰ ਅੰਦਰਲੇ ਕੰਨ ਤੱਕ ਪਹੁੰਚਾਉਂਦੀਆਂ ਅਤੇ ਵਧਾਉਂਦੀਆਂ ਹਨ, ਜਿੱਥੇ ਇਹ ਤੰਤ੍ਰਿਕ ਸੰਕੇਤਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਨ।"],
  ["The cochlea is a fluid-filled inner-ear structure containing sensory hair cells. These cells convert mechanical vibrations into electrical nerve signals that travel to the brain.", "कर्णावर्त अंदर के कान की द्रव-भरी संरचना है जिसमें संवेदी केशिकाएँ होती हैं। ये कोशिकाएँ यांत्रिक कंपन को विद्युत तंत्रिका संकेतों में बदलती हैं, जिन्हें मस्तिष्क ग्रहण करता है।", "ਕੋਕਲੀਆ ਅੰਦਰਲੇ ਕੰਨ ਦੀ ਤਰਲ-ਭਰੀ ਬਣਤਰ ਹੈ ਜਿਸ ਵਿੱਚ ਸੰਵੇਦੀ ਵਾਲ-ਕੋਸ਼ ਹੁੰਦੇ ਹਨ। ਇਹ ਕੋਸ਼ ਯਾਂਤ੍ਰਿਕ ਕੰਪਨਾਂ ਨੂੰ ਬਿਜਲਈ ਤੰਤ੍ਰਿਕ ਸੰਕੇਤਾਂ ਵਿੱਚ ਬਦਲਦੇ ਹਨ, ਜੋ ਦਿਮਾਗ ਤੱਕ ਜਾਂਦੇ ਹਨ।"],
  ["Reverberation is the persistence of sound caused by many closely spaced reflections in an enclosure. Too much reverberation reduces speech clarity, so halls use absorbing materials to control it.", "अनुनादिता बंद स्थान में कई निकट-निकट परावर्तनों के कारण ध्वनि का कुछ समय तक बने रहना है। बहुत अधिक अनुनादिता बोलने की स्पष्टता घटाती है, इसलिए सभागारों में ध्वनि-अवशोषक सामग्री लगाई जाती है।", "ਪ੍ਰਤਿਧੁਨੀ-ਸਥਾਇਤਾ ਬੰਦ ਥਾਂ ਵਿੱਚ ਬਹੁਤ ਸਾਰੇ ਨੇੜੇ-ਨੇੜੇ ਪਰਾਵਰਤਨਾਂ ਕਾਰਨ ਧੁਨੀ ਦਾ ਕੁਝ ਸਮਾਂ ਬਣਿਆ ਰਹਿਣਾ ਹੈ। ਬਹੁਤ ਵੱਧ ਪ੍ਰਤਿਧੁਨੀ-ਸਥਾਇਤਾ ਬੋਲਣ ਦੀ ਸਪਸ਼ਟਤਾ ਘਟਾਉਂਦੀ ਹੈ, ਇਸ ਲਈ ਹਾਲਾਂ ਵਿੱਚ ਧੁਨੀ-ਸੋਖਣ ਵਾਲੀ ਸਮੱਗਰੀ ਵਰਤੀ ਜਾਂਦੀ ਹੈ।"],
  ["Soft porous materials absorb part of the sound energy instead of reflecting most of it. Coverings, curtains and acoustic panels therefore reduce repeated reflections and excessive reverberation in an auditorium.", "मुलायम और छिद्रयुक्त पदार्थ ध्वनि ऊर्जा का कुछ भाग सोख लेते हैं और कम ध्वनि वापस परावर्तित करते हैं। इसलिए पर्दे, आवरण और ध्वनिक पैनल सभागार में बार-बार होने वाले परावर्तन और अनुनादिता को घटाते हैं।", "ਨਰਮ ਅਤੇ ਛਿਦਰਦਾਰ ਪਦਾਰਥ ਧੁਨੀ ਊਰਜਾ ਦਾ ਕੁਝ ਹਿੱਸਾ ਸੋਖ ਲੈਂਦੇ ਹਨ ਅਤੇ ਘੱਟ ਧੁਨੀ ਵਾਪਸ ਪਰਾਵਰਤਿਤ ਕਰਦੇ ਹਨ। ਇਸ ਲਈ ਪਰਦੇ ਅਤੇ ਧੁਨੀ-ਸੋਖਣ ਵਾਲੇ ਪੈਨਲ ਹਾਲ ਵਿੱਚ ਵਾਰ-ਵਾਰ ਪਰਾਵਰਤਨ ਅਤੇ ਪ੍ਰਤਿਧੁਨੀ-ਸਥਾਇਤਾ ਘਟਾਉਂਦੇ ਹਨ।"],
  ["Resonance occurs when a periodic driving frequency is equal or close to a system's natural frequency. Under this condition energy transfer is especially efficient and the vibration amplitude can become large.", "अनुनाद तब होता है जब बाहरी आवर्ती बल की आवृत्ति किसी तंत्र की प्राकृतिक आवृत्ति के बराबर या उसके बहुत पास हो। इस स्थिति में ऊर्जा का स्थानांतरण बहुत प्रभावी होता है और कंपन का आयाम बड़ा हो सकता है।", "ਅਨੁਨਾਦ ਤਦੋਂ ਹੁੰਦਾ ਹੈ ਜਦੋਂ ਬਾਹਰੀ ਆਵਰਤੀ ਬਲ ਦੀ ਆਵਿਰਤੀ ਕਿਸੇ ਪ੍ਰਣਾਲੀ ਦੀ ਕੁਦਰਤੀ ਆਵਿਰਤੀ ਦੇ ਬਰਾਬਰ ਜਾਂ ਬਹੁਤ ਨੇੜੇ ਹੋਵੇ। ਇਸ ਹਾਲਤ ਵਿੱਚ ਊਰਜਾ ਦਾ ਸੰਚਾਰ ਬਹੁਤ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਹੁੰਦਾ ਹੈ ਅਤੇ ਕੰਪਨ ਦਾ ਆਯਾਮ ਵੱਡਾ ਹੋ ਸਕਦਾ ਹੈ।"],
  ["The Doppler effect is the apparent change in received frequency caused by relative motion between source and observer. Approaching motion generally raises the observed frequency, while receding motion lowers it.", "डॉप्लर प्रभाव स्रोत और प्रेक्षक की सापेक्ष गति के कारण प्राप्त आवृत्ति में दिखाई देने वाला परिवर्तन है। पास आने पर आवृत्ति सामान्यतः बढ़ती है और दूर जाने पर घटती है।", "ਡੌਪਲਰ ਪ੍ਰਭਾਵ ਸਰੋਤ ਅਤੇ ਸੁਣਨ ਵਾਲੇ ਦੀ ਸਾਪੇਖ ਗਤੀ ਕਾਰਨ ਪ੍ਰਾਪਤ ਆਵਿਰਤੀ ਵਿੱਚ ਦਿੱਖਣ ਵਾਲਾ ਬਦਲਾਅ ਹੈ। ਨੇੜੇ ਆਉਣ ਤੇ ਆਵਿਰਤੀ ਆਮ ਤੌਰ ਤੇ ਵਧਦੀ ਹੈ ਅਤੇ ਦੂਰ ਜਾਣ ਤੇ ਘਟਦੀ ਹੈ।"],
  ["Prolonged exposure to very loud sound can damage sensitive structures in the inner ear and cause temporary or permanent hearing loss. Noise control therefore depends on limiting both sound level and exposure time.", "बहुत तेज ध्वनि के लंबे संपर्क से अंदर के कान की संवेदनशील संरचनाएँ क्षतिग्रस्त हो सकती हैं और सुनने की क्षमता घट सकती है। इसलिए शोर नियंत्रण में ध्वनि स्तर और संपर्क समय दोनों को सीमित करना जरूरी है।", "ਬਹੁਤ ਉੱਚੀ ਧੁਨੀ ਨਾਲ ਲੰਬੇ ਸਮੇਂ ਤੱਕ ਸੰਪਰਕ ਅੰਦਰਲੇ ਕੰਨ ਦੀਆਂ ਸੰਵੇਦਨਸ਼ੀਲ ਬਣਤਰਾਂ ਨੂੰ ਨੁਕਸਾਨ ਪਹੁੰਚਾ ਸਕਦਾ ਹੈ ਅਤੇ ਸੁਣਨ ਦੀ ਸਮਰੱਥਾ ਘਟ ਸਕਦੀ ਹੈ। ਇਸ ਲਈ ਸ਼ੋਰ ਨਿਯੰਤਰਣ ਵਿੱਚ ਧੁਨੀ ਪੱਧਰ ਅਤੇ ਸੰਪਰਕ ਸਮਾਂ ਦੋਵੇਂ ਘਟਾਉਣੇ ਜ਼ਰੂਰੀ ਹਨ।"],
  ["For an echo, the measured time is for the sound to travel to the surface and back, so the one-way distance is d = vt/2. With v = 340 m/s and t = 2 s, d = 340 × 2 / 2 = 340 m.", "प्रतिध्वनि में मापा समय ध्वनि के सतह तक जाने और वापस आने दोनों का होता है, इसलिए एक तरफ की दूरी d = vt/2 होती है। v = 340 m/s और t = 2 s रखने पर d = 340 m मिलता है।", "ਗੂੰਜ ਵਿੱਚ ਮਾਪਿਆ ਸਮਾਂ ਧੁਨੀ ਦੇ ਸਤਹ ਤੱਕ ਜਾਣ ਅਤੇ ਵਾਪਸ ਆਉਣ ਦੋਵਾਂ ਦਾ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਇੱਕ ਪਾਸੇ ਦੀ ਦੂਰੀ d = vt/2 ਹੁੰਦੀ ਹੈ। v = 340 m/s ਅਤੇ t = 2 s ਰੱਖਣ ਤੇ d = 340 m ਮਿਲਦਾ ਹੈ।"],
];

export const SCI_PHYSICS_EXPLANATION_QUALITY_V4 = Object.freeze({ ...build("005", CP005), ...build("006", CP006) });

export function getPhysicsExplanationV4(anchorId: string, locale: PhysicsLocaleV1): string {
  const set = SCI_PHYSICS_EXPLANATION_QUALITY_V4[anchorId];
  if (!set) throw new Error(`Missing Physics explanation V4 for ${anchorId}`);
  return set[locale];
}
