import { SCI_PHYSICS_EXHAUSTIVE_CP_META_V2 } from "../physics-exhaustive-v2/sci-physics-exhaustive-domain-v2";
import {
  SCI_PHYSICS_CP009_HI_SURFACES_V1,
  SCI_PHYSICS_CP009_PA_SURFACES_V1,
  SCI_PHYSICS_CP010_HI_SURFACES_V1,
  SCI_PHYSICS_CP010_PA_SURFACES_V1,
} from "./sci-physics-cp009-cp010-localization-data-v1";
import type { PhysicsLocaleV1 } from "./sci-physics-localization-types-v1";

type Note = Readonly<{ en: string; hi: string; pa: string }>;

const NOTES: readonly Note[] = [
  { en: "This simple pole rule is the magnetic analogue used to predict attraction or repulsion between bar magnets.", hi: "इसी नियम से दंड चुंबकों के पास लाने पर आकर्षण या विकर्षण की दिशा समझी जाती है।", pa: "ਇਸੇ ਨਿਯਮ ਨਾਲ ਦੰਡ ਚੁੰਬਕਾਂ ਨੂੰ ਨੇੜੇ ਲਿਆਉਣ ਉੱਤੇ ਆਕਰਸ਼ਣ ਜਾਂ ਵਿਕਰਸ਼ਣ ਸਮਝਿਆ ਜਾਂਦਾ ਹੈ।" },
  { en: "Magnetic field lines form closed loops: outside the magnet they go north to south and inside they return south to north.", hi: "चुंबकीय क्षेत्र रेखाएँ बंद वक्र बनाती हैं; बाहर उत्तर से दक्षिण और भीतर दक्षिण से उत्तर जाती हैं।", pa: "ਚੁੰਬਕੀ ਖੇਤਰ ਰੇਖਾਵਾਂ ਬੰਦ ਲੂਪ ਬਣਾਉਂਦੀਆਂ ਹਨ; ਬਾਹਰ ਉੱਤਰ ਤੋਂ ਦੱਖਣ ਅਤੇ ਅੰਦਰ ਦੱਖਣ ਤੋਂ ਉੱਤਰ ਜਾਂਦੀਆਂ ਹਨ।" },
  { en: "A denser pattern of field lines means a larger magnetic field magnitude, especially near the poles of a bar magnet.", hi: "जहाँ क्षेत्र रेखाएँ अधिक पास होती हैं, वहाँ चुंबकीय क्षेत्र अधिक प्रबल माना जाता है, जैसे दंड चुंबक के ध्रुवों के पास।", pa: "ਜਿੱਥੇ ਖੇਤਰ ਰੇਖਾਵਾਂ ਵੱਧ ਨੇੜੇ ਹੁੰਦੀਆਂ ਹਨ, ਉੱਥੇ ਚੁੰਬਕੀ ਖੇਤਰ ਵੱਧ ਮਜ਼ਬੂਤ ਮੰਨਿਆ ਜਾਂਦਾ ਹੈ, ਜਿਵੇਂ ਦੰਡ ਚੁੰਬਕ ਦੇ ਧ੍ਰੁਵਾਂ ਕੋਲ।" },
  { en: "Because the compass needle is itself a tiny magnet, its north-seeking end turns along the local magnetic-field direction.", hi: "कम्पास की सुई स्वयं छोटा चुंबक है, इसलिए उसका उत्तर खोजने वाला सिरा स्थानीय चुंबकीय क्षेत्र की दिशा में घूमता है।", pa: "ਕੰਪਾਸ ਦੀ ਸੂਈ ਆਪ ਇੱਕ ਛੋਟਾ ਚੁੰਬਕ ਹੈ, ਇਸ ਲਈ ਇਸ ਦਾ ਉੱਤਰ ਵੱਲ ਜਾਣ ਵਾਲਾ ਸਿਰਾ ਸਥਾਨਕ ਚੁੰਬਕੀ ਖੇਤਰ ਦੇ ਅਨੁਸਾਰ ਮੁੜਦਾ ਹੈ।" },
  { en: "Ferromagnetic materials such as iron can acquire strong magnetization because many magnetic domains can align together.", hi: "लोहे जैसे लौहचुंबकीय पदार्थों में अनेक चुंबकीय डोमेन एक दिशा में व्यवस्थित होकर प्रबल चुंबकत्व दे सकते हैं।", pa: "ਲੋਹੇ ਵਰਗੇ ਲੋਹ-ਚੁੰਬਕੀ ਪਦਾਰਥਾਂ ਵਿੱਚ ਕਈ ਚੁੰਬਕੀ ਡੋਮੇਨ ਇੱਕ ਦਿਸ਼ਾ ਵਿੱਚ ਸੱਜ ਕੇ ਮਜ਼ਬੂਤ ਚੁੰਬਕਤਾ ਦੇ ਸਕਦੇ ਹਨ।" },
  { en: "Soft iron loses most of its magnetism when current is switched off, so an electromagnet can be turned on and off quickly.", hi: "धारा बंद करने पर नरम लोहा अधिकांश चुंबकत्व जल्दी खो देता है, इसलिए विद्युतचुंबक को आसानी से चालू-बंद किया जा सकता है।", pa: "ਧਾਰਾ ਬੰਦ ਕਰਨ ਉੱਤੇ ਨਰਮ ਲੋਹਾ ਜ਼ਿਆਦਾਤਰ ਚੁੰਬਕਤਾ ਜਲਦੀ ਗੁਆ ਦਿੰਦਾ ਹੈ, ਇਸ ਲਈ ਬਿਜਲਈ ਚੁੰਬਕ ਨੂੰ ਆਸਾਨੀ ਨਾਲ ਚਾਲੂ-ਬੰਦ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।" },
  { en: "The circular field direction reverses if the current direction reverses, which can be predicted using the right-hand thumb rule.", hi: "यदि धारा की दिशा उलट दी जाए तो वृत्ताकार चुंबकीय क्षेत्र की दिशा भी उलट जाती है; इसे दाएँ हाथ के अंगूठे के नियम से जाना जाता है।", pa: "ਜੇ ਧਾਰਾ ਦੀ ਦਿਸ਼ਾ ਉਲਟ ਦਿੱਤੀ ਜਾਵੇ ਤਾਂ ਵਰਤੂਲ ਚੁੰਬਕੀ ਖੇਤਰ ਦੀ ਦਿਸ਼ਾ ਵੀ ਉਲਟ ਜਾਂਦੀ ਹੈ; ਇਹ ਸੱਜੇ ਹੱਥ ਦੇ ਅੰਗੂਠੇ ਦੇ ਨਿਯਮ ਨਾਲ ਪਤਾ ਲੱਗਦਾ ਹੈ।" },
  { en: "Point the right thumb along conventional current; the curled fingers then show the direction of the surrounding magnetic field.", hi: "दाएँ हाथ का अंगूठा परंपरागत धारा की दिशा में रखें; मुड़ी हुई उँगलियाँ चुंबकीय क्षेत्र की दिशा बताती हैं।", pa: "ਸੱਜੇ ਹੱਥ ਦਾ ਅੰਗੂਠਾ ਰਵਾਇਤੀ ਧਾਰਾ ਦੀ ਦਿਸ਼ਾ ਵਿੱਚ ਰੱਖੋ; ਮੁੜੀਆਂ ਉਂਗਲਾਂ ਆਲੇ-ਦੁਆਲੇ ਚੁੰਬਕੀ ਖੇਤਰ ਦੀ ਦਿਸ਼ਾ ਦੱਸਦੀਆਂ ਹਨ।" },
  { en: "Inside a long solenoid the field is nearly uniform, while its two ends behave approximately like the poles of a bar magnet.", hi: "लंबी परिनालिका के भीतर चुंबकीय क्षेत्र लगभग समान रहता है और उसके दो सिरे दंड चुंबक के ध्रुवों जैसा व्यवहार करते हैं।", pa: "ਲੰਮੀ ਸੋਲੇਨਾਇਡ ਦੇ ਅੰਦਰ ਚੁੰਬਕੀ ਖੇਤਰ ਲਗਭਗ ਇੱਕਸਾਰ ਹੁੰਦਾ ਹੈ ਅਤੇ ਇਸ ਦੇ ਦੋ ਸਿਰੇ ਦੰਡ ਚੁੰਬਕ ਦੇ ਧ੍ਰੁਵਾਂ ਵਰਗਾ ਵਰਤਾਉਂਦੇ ਹਨ।" },
  { en: "Electromagnet strength can also be increased by increasing coil turns or by placing a soft-iron core inside the solenoid.", hi: "धारा के साथ-साथ कुंडली के फेरों की संख्या बढ़ाने या नरम लोहे का कोर लगाने से भी विद्युतचुंबक अधिक प्रबल बनता है।", pa: "ਧਾਰਾ ਦੇ ਨਾਲ ਕੁੰਡਲੀ ਦੇ ਫੇਰਿਆਂ ਦੀ ਗਿਣਤੀ ਵਧਾਉਣ ਜਾਂ ਨਰਮ ਲੋਹੇ ਦਾ ਕੋਰ ਲਗਾਉਣ ਨਾਲ ਵੀ ਬਿਜਲਈ ਚੁੰਬਕ ਹੋਰ ਮਜ਼ਬੂਤ ਹੁੰਦਾ ਹੈ।" },
  { en: "In an electric bell the electromagnet repeatedly attracts the armature, opening and closing the contact to produce ringing.", hi: "विद्युत घंटी में विद्युतचुंबक आर्मेचर को बार-बार खींचता है और संपर्क टूटने-जुड़ने से घंटी बजती रहती है।", pa: "ਬਿਜਲਈ ਘੰਟੀ ਵਿੱਚ ਬਿਜਲਈ ਚੁੰਬਕ ਆਰਮੇਚਰ ਨੂੰ ਵਾਰ-ਵਾਰ ਖਿੱਚਦਾ ਹੈ ਅਤੇ ਸੰਪਰਕ ਟੁੱਟਣ-ਜੁੜਣ ਨਾਲ ਘੰਟੀ ਵੱਜਦੀ ਰਹਿੰਦੀ ਹੈ।" },
  { en: "This force on a current-carrying conductor is the basic motor effect and can make a coil rotate inside a magnetic field.", hi: "धारा-वाहित चालक पर लगने वाला यही चुंबकीय बल मोटर प्रभाव है और चुंबकीय क्षेत्र में कुंडली को घुमा सकता है।", pa: "ਧਾਰਾ ਵਾਲੇ ਚਾਲਕ ਉੱਤੇ ਲੱਗਣ ਵਾਲਾ ਇਹੀ ਚੁੰਬਕੀ ਬਲ ਮੋਟਰ ਪ੍ਰਭਾਵ ਹੈ ਅਤੇ ਚੁੰਬਕੀ ਖੇਤਰ ਵਿੱਚ ਕੁੰਡਲੀ ਨੂੰ ਘੁਮਾ ਸਕਦਾ ਹੈ।" },
  { en: "For the left-hand rule, forefinger shows field, middle finger current and thumb force or motion; the three are mutually perpendicular.", hi: "बाएँ हाथ के नियम में तर्जनी क्षेत्र, मध्यमा धारा और अंगूठा बल या गति की दिशा बताता है; तीनों दिशाएँ परस्पर लंब होती हैं।", pa: "ਖੱਬੇ ਹੱਥ ਦੇ ਨਿਯਮ ਵਿੱਚ ਤਰਜਨੀ ਖੇਤਰ, ਵਿਚਲੀ ਉਂਗਲ ਧਾਰਾ ਅਤੇ ਅੰਗੂਠਾ ਬਲ ਜਾਂ ਗਤੀ ਦੀ ਦਿਸ਼ਾ ਦੱਸਦਾ ਹੈ; ਤਿੰਨੇ ਇਕ-ਦੂਜੇ ਨੂੰ ਲੰਬ ਹੁੰਦੇ ਹਨ।" },
  { en: "A motor uses magnetic force on a current-carrying coil to produce torque, so the output is rotational mechanical motion.", hi: "मोटर में धारा-वाहित कुंडली पर चुंबकीय बल आघूर्ण पैदा करता है, इसलिए उसका उपयोगी आउटपुट घूर्णन यांत्रिक गति है।", pa: "ਮੋਟਰ ਵਿੱਚ ਧਾਰਾ ਵਾਲੀ ਕੁੰਡਲੀ ਉੱਤੇ ਚੁੰਬਕੀ ਬਲ ਘੁੰਮਾਉ ਪ੍ਰਭਾਵ ਪੈਦਾ ਕਰਦਾ ਹੈ, ਇਸ ਲਈ ਇਸ ਦਾ ਨਿਕਾਸ ਘੁੰਮਣ ਵਾਲੀ ਯਾਂਤ੍ਰਿਕ ਗਤੀ ਹੁੰਦਾ ਹੈ।" },
  { en: "Faraday's idea is that induced emf depends on change of magnetic flux, so moving a magnet and coil relative to each other can induce current.", hi: "फैराडे के सिद्धांत के अनुसार प्रेरित विद्युत वाहक बल चुंबकीय फ्लक्स के परिवर्तन से जुड़ा है; इसलिए चुंबक और कुंडली की सापेक्ष गति से धारा प्रेरित हो सकती है।", pa: "ਫੈਰਾਡੇ ਦੇ ਸਿਧਾਂਤ ਅਨੁਸਾਰ ਪ੍ਰੇਰਿਤ ਬਿਜਲਈ ਵਾਹਕ ਬਲ ਚੁੰਬਕੀ ਫਲਕਸ ਦੇ ਬਦਲਾਅ ਨਾਲ ਜੁੜਿਆ ਹੈ; ਇਸ ਲਈ ਚੁੰਬਕ ਅਤੇ ਕੁੰਡਲੀ ਦੀ ਆਪਸੀ ਗਤੀ ਨਾਲ ਧਾਰਾ ਪ੍ਰੇਰਿਤ ਹੋ ਸਕਦੀ ਹੈ।" },
  { en: "In the right-hand rule, thumb shows motion, forefinger field and middle finger induced current for a generator situation.", hi: "दाएँ हाथ के नियम में अंगूठा गति, तर्जनी चुंबकीय क्षेत्र और मध्यमा प्रेरित धारा की दिशा बताती है।", pa: "ਸੱਜੇ ਹੱਥ ਦੇ ਨਿਯਮ ਵਿੱਚ ਅੰਗੂਠਾ ਗਤੀ, ਤਰਜਨੀ ਚੁੰਬਕੀ ਖੇਤਰ ਅਤੇ ਵਿਚਲੀ ਉਂਗਲ ਪ੍ਰੇਰਿਤ ਧਾਰਾ ਦੀ ਦਿਸ਼ਾ ਦੱਸਦੀ ਹੈ।" },
  { en: "Rotating a coil in a magnetic field changes flux through it and produces an induced emf, which is the working principle of a generator.", hi: "चुंबकीय क्षेत्र में कुंडली घुमाने से उससे जुड़ा फ्लक्स बदलता है और प्रेरित विद्युत वाहक बल उत्पन्न होता है; यही जनित्र का आधार है।", pa: "ਚੁੰਬਕੀ ਖੇਤਰ ਵਿੱਚ ਕੁੰਡਲੀ ਘੁਮਾਉਣ ਨਾਲ ਇਸ ਨਾਲ ਜੁੜਿਆ ਫਲਕਸ ਬਦਲਦਾ ਹੈ ਅਤੇ ਪ੍ਰੇਰਿਤ ਬਿਜਲਈ ਵਾਹਕ ਬਲ ਬਣਦਾ ਹੈ; ਇਹੀ ਜਨਰੇਟਰ ਦਾ ਆਧਾਰ ਹੈ।" },
  { en: "Mains electricity is AC because its direction reverses periodically; frequency tells how many cycles occur each second.", hi: "घरेलू मुख्य आपूर्ति AC होती है क्योंकि उसकी दिशा आवर्ती रूप से उलटती है; आवृत्ति प्रति सेकंड होने वाले चक्रों की संख्या बताती है।", pa: "ਘਰੇਲੂ ਮੁੱਖ ਸਪਲਾਈ AC ਹੁੰਦੀ ਹੈ ਕਿਉਂਕਿ ਇਸ ਦੀ ਦਿਸ਼ਾ ਆਵਰਤੀ ਤਰੀਕੇ ਨਾਲ ਉਲਟਦੀ ਹੈ; ਆਵਿਰਤੀ ਪ੍ਰਤੀ ਸਕਿੰਟ ਚੱਕਰਾਂ ਦੀ ਗਿਣਤੀ ਦੱਸਦੀ ਹੈ।" },
  { en: "A cell or battery normally supplies DC, whose polarity and current direction remain fixed during normal operation.", hi: "सेल या बैटरी सामान्यतः DC देती है, जिसमें सामान्य संचालन के दौरान ध्रुवता और धारा की दिशा स्थिर रहती है।", pa: "ਸੈੱਲ ਜਾਂ ਬੈਟਰੀ ਆਮ ਤੌਰ ਤੇ DC ਦਿੰਦੀ ਹੈ, ਜਿਸ ਵਿੱਚ ਆਮ ਕੰਮ ਦੌਰਾਨ ਧ੍ਰੁਵਤਾ ਅਤੇ ਧਾਰਾ ਦੀ ਦਿਸ਼ਾ ਇੱਕੋ ਰਹਿੰਦੀ ਹੈ।" },
  { en: "A transformer needs changing current, so it works with AC; a steady DC supply does not continuously induce emf in the secondary coil.", hi: "ट्रांसफॉर्मर को बदलती धारा चाहिए, इसलिए वह AC पर काम करता है; स्थिर DC द्वितीयक कुंडली में लगातार विद्युत वाहक बल प्रेरित नहीं करती।", pa: "ਟ੍ਰਾਂਸਫਾਰਮਰ ਨੂੰ ਬਦਲਦੀ ਧਾਰਾ ਚਾਹੀਦੀ ਹੈ, ਇਸ ਲਈ ਇਹ AC ਉੱਤੇ ਕੰਮ ਕਰਦਾ ਹੈ; ਸਥਿਰ DC ਸੈਕੰਡਰੀ ਕੁੰਡਲੀ ਵਿੱਚ ਲਗਾਤਾਰ ਬਿਜਲਈ ਵਾਹਕ ਬਲ ਪ੍ਰੇਰਿਤ ਨਹੀਂ ਕਰਦੀ।" },
  { en: "For an ideal transformer V_s/V_p = N_s/N_p; a larger secondary-turn count therefore gives a larger secondary voltage.", hi: "आदर्श ट्रांसफॉर्मर में V_s/V_p = N_s/N_p होता है; इसलिए द्वितीयक फेरों की संख्या अधिक होने पर द्वितीयक वोल्टता भी अधिक होती है।", pa: "ਆਦਰਸ਼ ਟ੍ਰਾਂਸਫਾਰਮਰ ਵਿੱਚ V_s/V_p = N_s/N_p ਹੁੰਦਾ ਹੈ; ਇਸ ਲਈ ਸੈਕੰਡਰੀ ਫੇਰੇ ਵੱਧ ਹੋਣ ਉੱਤੇ ਸੈਕੰਡਰੀ ਵੋਲਟੇਜ ਵੀ ਵੱਧ ਹੁੰਦਾ ਹੈ।" },
  { en: "For the same transmitted power, raising voltage lowers current; because line loss is I²R, the heating loss then drops sharply.", hi: "समान शक्ति संचार के लिए वोल्टता बढ़ाने से धारा घटती है; क्योंकि लाइन हानि I²R होती है, इसलिए तापन हानि बहुत कम हो जाती है।", pa: "ਇੱਕੋ ਸ਼ਕਤੀ ਸੰਚਾਰ ਲਈ ਵੋਲਟੇਜ ਵਧਾਉਣ ਨਾਲ ਧਾਰਾ ਘਟਦੀ ਹੈ; ਕਿਉਂਕਿ ਲਾਈਨ ਹਾਨੀ I²R ਹੁੰਦੀ ਹੈ, ਇਸ ਲਈ ਤਾਪ ਹਾਨੀ ਕਾਫ਼ੀ ਘਟ ਜਾਂਦੀ ਹੈ।" },
  { en: "A relay lets a small control current operate contacts in another circuit, providing electrical isolation and remote switching.", hi: "रिले में छोटी नियंत्रण धारा विद्युतचुंबक चलाकर दूसरे परिपथ के संपर्क खोल या बंद कर सकती है, जिससे दूरस्थ स्विचिंग संभव होती है।", pa: "ਰੀਲੇ ਵਿੱਚ ਛੋਟੀ ਕੰਟਰੋਲ ਧਾਰਾ ਬਿਜਲਈ ਚੁੰਬਕ ਚਲਾ ਕੇ ਦੂਜੇ ਸਰਕਟ ਦੇ ਸੰਪਰਕ ਖੋਲ੍ਹ ਜਾਂ ਬੰਦ ਕਰ ਸਕਦੀ ਹੈ, ਜਿਸ ਨਾਲ ਦੂਰੋਂ ਸਵਿੱਚਿੰਗ ਸੰਭਵ ਹੁੰਦੀ ਹੈ।" },
  { en: "Since the turn ratio is 2, the ideal voltage ratio is also 2; this is a direct use of V_s/V_p = N_s/N_p.", hi: "फेरों का अनुपात 2 होने से आदर्श वोल्टता अनुपात भी 2 होगा; यह V_s/V_p = N_s/N_p का सीधा उपयोग है।", pa: "ਫੇਰਿਆਂ ਦਾ ਅਨੁਪਾਤ 2 ਹੋਣ ਕਰਕੇ ਆਦਰਸ਼ ਵੋਲਟੇਜ ਅਨੁਪਾਤ ਵੀ 2 ਹੋਵੇਗਾ; ਇਹ V_s/V_p = N_s/N_p ਦੀ ਸਿੱਧੀ ਵਰਤੋਂ ਹੈ।" },

  { en: "An atom's nucleus contains protons and neutrons, while negatively charged electrons occupy the surrounding region.", hi: "परमाणु के नाभिक में प्रोटॉन और न्यूट्रॉन होते हैं, जबकि ऋणावेशित इलेक्ट्रॉन नाभिक के बाहर के क्षेत्र में पाए जाते हैं।", pa: "ਪਰਮਾਣੂ ਦੇ ਨਾਭਿਕ ਵਿੱਚ ਪ੍ਰੋਟਾਨ ਅਤੇ ਨਿਊਟ੍ਰਾਨ ਹੁੰਦੇ ਹਨ, ਜਦਕਿ ਰਿਣਾਤਮਕ ਚਾਰਜ ਵਾਲੇ ਇਲੈਕਟ੍ਰਾਨ ਨਾਭਿਕ ਦੇ ਬਾਹਰਲੇ ਖੇਤਰ ਵਿੱਚ ਹੁੰਦੇ ਹਨ।" },
  { en: "A transistor can use a small input signal to control a larger current, which is why it is useful for amplification and electronic switching.", hi: "ट्रांजिस्टर छोटा इनपुट संकेत लेकर बड़ी धारा को नियंत्रित कर सकता है, इसलिए यह प्रवर्धन और इलेक्ट्रॉनिक स्विचिंग दोनों में उपयोगी है।", pa: "ਟ੍ਰਾਂਜ਼ਿਸਟਰ ਛੋਟੇ ਇਨਪੁੱਟ ਸੰਕੇਤ ਨਾਲ ਵੱਡੀ ਧਾਰਾ ਨੂੰ ਕਾਬੂ ਕਰ ਸਕਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਪ੍ਰਵਰਧਨ ਅਤੇ ਇਲੈਕਟ੍ਰਾਨਿਕ ਸਵਿੱਚਿੰਗ ਦੋਵੇਂ ਲਈ ਲਾਭਦਾਇਕ ਹੈ।" },
  { en: "Because proton number fixes the element's identity, isotopes remain the same element even though their neutron and mass numbers differ.", hi: "तत्व की पहचान प्रोटॉन संख्या से तय होती है, इसलिए न्यूट्रॉन और द्रव्यमान संख्या अलग होने पर भी समस्थानिक उसी तत्व के रहते हैं।", pa: "ਤੱਤ ਦੀ ਪਛਾਣ ਪ੍ਰੋਟਾਨ ਗਿਣਤੀ ਨਾਲ ਤੈਅ ਹੁੰਦੀ ਹੈ, ਇਸ ਲਈ ਨਿਊਟ੍ਰਾਨ ਅਤੇ ਪੁੰਜ ਅੰਕ ਵੱਖਰੇ ਹੋਣ ਉੱਤੇ ਵੀ ਸਮਸਥਾਨਿਕ ਉਸੇ ਤੱਤ ਦੇ ਰਹਿੰਦੇ ਹਨ।" },
  { en: "Radioactive decay is a nuclear process and is largely unaffected by ordinary changes of temperature, pressure or chemical state.", hi: "रेडियोधर्मी क्षय नाभिकीय प्रक्रिया है और सामान्य तापमान, दाब या रासायनिक अवस्था के बदलाव से बहुत कम प्रभावित होती है।", pa: "ਰੇਡੀਓਧਰਮੀ ਵਿਘਟਨ ਨਾਭਿਕੀ ਪ੍ਰਕਿਰਿਆ ਹੈ ਅਤੇ ਆਮ ਤਾਪਮਾਨ, ਦਬਾਅ ਜਾਂ ਰਸਾਇਣਕ ਹਾਲਤ ਦੇ ਬਦਲਾਅ ਨਾਲ ਬਹੁਤ ਘੱਟ ਪ੍ਰਭਾਵਿਤ ਹੁੰਦਾ ਹੈ।" },
  { en: "An alpha particle has charge +2e and relatively large mass, so it ionizes strongly but penetrates only a short distance.", hi: "अल्फा कण पर +2e आवेश और अपेक्षाकृत अधिक द्रव्यमान होता है, इसलिए उसकी आयनीकरण क्षमता अधिक लेकिन भेदन क्षमता कम होती है।", pa: "ਅਲਫਾ ਕਣ ਉੱਤੇ +2e ਚਾਰਜ ਅਤੇ ਤੁਲਨਾਤਮਕ ਤੌਰ ਤੇ ਵੱਧ ਪੁੰਜ ਹੁੰਦਾ ਹੈ, ਇਸ ਲਈ ਇਸ ਦੀ ਆਇਨੀਕਰਨ ਸਮਰੱਥਾ ਵੱਧ ਪਰ ਭੇਦਨ ਸਮਰੱਥਾ ਘੱਟ ਹੁੰਦੀ ਹੈ।" },
  { en: "A beta-minus particle is an electron emitted from the nucleus during beta decay; it is much lighter than an alpha particle.", hi: "बीटा-माइनस कण नाभिकीय बीटा क्षय में निकला इलेक्ट्रॉन है और उसका द्रव्यमान अल्फा कण की तुलना में बहुत कम होता है।", pa: "ਬੀਟਾ-ਮਾਇਨਸ ਕਣ ਨਾਭਿਕੀ ਬੀਟਾ ਵਿਘਟਨ ਵਿੱਚ ਨਿਕਲਿਆ ਇਲੈਕਟ੍ਰਾਨ ਹੈ ਅਤੇ ਇਸ ਦਾ ਪੁੰਜ ਅਲਫਾ ਕਣ ਨਾਲੋਂ ਬਹੁਤ ਘੱਟ ਹੁੰਦਾ ਹੈ।" },
  { en: "Gamma rays are high-energy photons, so they carry no electric charge and travel at the speed of light in vacuum.", hi: "गामा किरणें उच्च ऊर्जा वाले फोटॉन हैं, इसलिए उन पर विद्युत आवेश नहीं होता और निर्वात में वे प्रकाश की चाल से चलती हैं।", pa: "ਗਾਮਾ ਕਿਰਨਾਂ ਉੱਚ ਊਰਜਾ ਵਾਲੇ ਫੋਟਾਨ ਹਨ, ਇਸ ਲਈ ਉਨ੍ਹਾਂ ਉੱਤੇ ਬਿਜਲਈ ਚਾਰਜ ਨਹੀਂ ਹੁੰਦਾ ਅਤੇ ਖਲਾਅ ਵਿੱਚ ਇਹ ਪ੍ਰਕਾਸ਼ ਦੀ ਚਾਲ ਨਾਲ ਚਲਦੀਆਂ ਹਨ।" },
  { en: "Penetration generally increases from alpha to beta to gamma, while ionizing ability shows the opposite broad trend.", hi: "सामान्यतः भेदन क्षमता अल्फा से बीटा और फिर गामा की ओर बढ़ती है, जबकि आयनीकरण क्षमता का क्रम मोटे तौर पर उल्टा होता है।", pa: "ਆਮ ਤੌਰ ਤੇ ਭੇਦਨ ਸਮਰੱਥਾ ਅਲਫਾ ਤੋਂ ਬੀਟਾ ਅਤੇ ਫਿਰ ਗਾਮਾ ਵੱਲ ਵਧਦੀ ਹੈ, ਜਦਕਿ ਆਇਨੀਕਰਨ ਸਮਰੱਥਾ ਦਾ ਰੁਝਾਨ ਲਗਭਗ ਉਲਟ ਹੁੰਦਾ ਹੈ।" },
  { en: "After one half-life 1/2 remains, after two 1/4 remains and after three 1/8 remains; the decay is exponential, not linear.", hi: "एक अर्ध-आयु बाद 1/2, दो के बाद 1/4 और तीन के बाद 1/8 नाभिक बचे रहते हैं; यह क्षय घातीय है, रैखिक नहीं।", pa: "ਇੱਕ ਅਰਧ-ਆਯੁ ਬਾਅਦ 1/2, ਦੋ ਬਾਅਦ 1/4 ਅਤੇ ਤਿੰਨ ਬਾਅਦ 1/8 ਨਾਭਿਕ ਬਚਦੇ ਹਨ; ਇਹ ਵਿਘਟਨ ਘਾਤੀ ਹੈ, ਰੇਖੀ ਨਹੀਂ।" },
  { en: "In fission a heavy nucleus such as uranium can split into smaller nuclei and release neutrons that may continue a chain reaction.", hi: "विखंडन में यूरेनियम जैसा भारी नाभिक छोटे नाभिकों में टूट सकता है और निकले न्यूट्रॉन आगे श्रृंखला अभिक्रिया चला सकते हैं।", pa: "ਵਿਖੰਡਨ ਵਿੱਚ ਯੂਰੇਨੀਅਮ ਵਰਗਾ ਭਾਰੀ ਨਾਭਿਕ ਛੋਟੇ ਨਾਭਿਕਾਂ ਵਿੱਚ ਟੁੱਟ ਸਕਦਾ ਹੈ ਅਤੇ ਨਿਕਲੇ ਨਿਊਟ੍ਰਾਨ ਅੱਗੇ ਲੜੀਵਾਰ ਕਿਰਿਆ ਚਲਾ ਸਕਦੇ ਹਨ।" },
  { en: "Fusion requires extremely high temperature to overcome repulsion between positive nuclei, but it can release enormous energy once nuclei combine.", hi: "संलयन के लिए धनावेशित नाभिकों का प्रतिकर्षण पार करने हेतु बहुत उच्च तापमान चाहिए, पर नाभिक जुड़ने पर बहुत अधिक ऊर्जा निकल सकती है।", pa: "ਸੰਲਯਨ ਲਈ ਧਨਾਤਮਕ ਨਾਭਿਕਾਂ ਦਾ ਵਿਕਰਸ਼ਣ ਪਾਰ ਕਰਨ ਵਾਸਤੇ ਬਹੁਤ ਉੱਚ ਤਾਪਮਾਨ ਚਾਹੀਦਾ ਹੈ, ਪਰ ਨਾਭਿਕ ਮਿਲਣ ਉੱਤੇ ਬਹੁਤ ਵੱਡੀ ਊਰਜਾ ਨਿਕਲ ਸਕਦੀ ਹੈ।" },
  { en: "The moderator slows neutrons without being the main absorber; this distinction separates it from control rods in reactor operation.", hi: "मॉडरेटर का काम न्यूट्रॉन धीमे करना है, उन्हें मुख्य रूप से सोखना नहीं; यही बात उसे नियंत्रण छड़ों से अलग करती है।", pa: "ਮਾਡਰੇਟਰ ਦਾ ਕੰਮ ਨਿਊਟ੍ਰਾਨ ਹੌਲੇ ਕਰਨਾ ਹੈ, ਉਨ੍ਹਾਂ ਨੂੰ ਮੁੱਖ ਤੌਰ ਤੇ ਸੋਖਣਾ ਨਹੀਂ; ਇਹ ਗੱਲ ਇਸ ਨੂੰ ਕੰਟਰੋਲ ਛੜਾਂ ਤੋਂ ਵੱਖ ਕਰਦੀ ਹੈ।" },
  { en: "Control rods are inserted further to absorb more neutrons and reduce the fission rate, or withdrawn to allow the reaction rate to rise.", hi: "नियंत्रण छड़ों को अधिक भीतर करने पर अधिक न्यूट्रॉन अवशोषित होते हैं और विखंडन दर घटती है; बाहर खींचने पर दर बढ़ सकती है।", pa: "ਕੰਟਰੋਲ ਛੜਾਂ ਹੋਰ ਅੰਦਰ ਕਰਨ ਨਾਲ ਵੱਧ ਨਿਊਟ੍ਰਾਨ ਸੋਖੇ ਜਾਂਦੇ ਹਨ ਅਤੇ ਵਿਖੰਡਨ ਦਰ ਘਟਦੀ ਹੈ; ਬਾਹਰ ਕੱਢਣ ਨਾਲ ਦਰ ਵਧ ਸਕਦੀ ਹੈ।" },
  { en: "All electromagnetic waves travel at the same speed in vacuum, but radio waves have the lowest frequencies and longest wavelengths of the listed regions.", hi: "निर्वात में सभी विद्युतचुंबकीय तरंगें समान चाल से चलती हैं, पर दिए गए क्षेत्रों में रेडियो तरंगों की आवृत्ति सबसे कम और तरंगदैर्ध्य सबसे लंबी होती है।", pa: "ਖਲਾਅ ਵਿੱਚ ਸਾਰੀਆਂ ਬਿਜਲਈ-ਚੁੰਬਕੀ ਤਰੰਗਾਂ ਇੱਕੋ ਚਾਲ ਨਾਲ ਚਲਦੀਆਂ ਹਨ, ਪਰ ਦਿੱਤੇ ਖੇਤਰਾਂ ਵਿੱਚ ਰੇਡੀਓ ਤਰੰਗਾਂ ਦੀ ਆਵਿਰਤੀ ਸਭ ਤੋਂ ਘੱਟ ਅਤੇ ਤਰੰਗ ਲੰਬਾਈ ਸਭ ਤੋਂ ਵੱਧ ਹੁੰਦੀ ਹੈ।" },
  { en: "Radar uses reflected electromagnetic waves to determine the position or motion of targets; microwave frequencies are especially useful for this purpose.", hi: "रडार परावर्तित विद्युतचुंबकीय तरंगों से लक्ष्य की स्थिति या गति पता करता है और इस काम के लिए माइक्रोवेव आवृत्तियाँ बहुत उपयोगी हैं।", pa: "ਰਡਾਰ ਪਰਾਵਰਤਿਤ ਬਿਜਲਈ-ਚੁੰਬਕੀ ਤਰੰਗਾਂ ਨਾਲ ਨਿਸ਼ਾਨੇ ਦੀ ਸਥਿਤੀ ਜਾਂ ਗਤੀ ਪਤਾ ਕਰਦਾ ਹੈ ਅਤੇ ਇਸ ਕੰਮ ਲਈ ਮਾਈਕਰੋਵੇਵ ਆਵਿਰਤੀਆਂ ਖਾਸ ਤੌਰ ਤੇ ਲਾਭਦਾਇਕ ਹਨ।" },
  { en: "Thermal cameras detect infrared emitted by objects; hotter objects generally emit more thermal radiation and shift its distribution.", hi: "ऊष्मीय कैमरे वस्तुओं से निकलने वाला अवरक्त विकिरण पहचानते हैं; अधिक गर्म वस्तुएँ सामान्यतः अधिक ऊष्मीय विकिरण उत्सर्जित करती हैं।", pa: "ਤਾਪੀ ਕੈਮਰੇ ਵਸਤੂਆਂ ਤੋਂ ਨਿਕਲਦਾ ਅਵਰਕਤ ਵਿਕਿਰਣ ਪਛਾਣਦੇ ਹਨ; ਵੱਧ ਗਰਮ ਵਸਤੂਆਂ ਆਮ ਤੌਰ ਤੇ ਵੱਧ ਤਾਪੀ ਵਿਕਿਰਣ ਛੱਡਦੀਆਂ ਹਨ।" },
  { en: "Moderate UV exposure contributes to vitamin D formation, but excessive UV can damage skin cells and increase long-term health risk.", hi: "सीमित UV संपर्क विटामिन D बनने में सहायक हो सकता है, लेकिन अधिक UV त्वचा कोशिकाओं और DNA को नुकसान पहुँचा सकता है।", pa: "ਸੀਮਿਤ UV ਸੰਪਰਕ ਵਿਟਾਮਿਨ D ਬਣਨ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦਾ ਹੈ, ਪਰ ਵੱਧ UV ਚਮੜੀ ਦੀਆਂ ਕੋਸ਼ਿਕਾਵਾਂ ਅਤੇ DNA ਨੂੰ ਨੁਕਸਾਨ ਪਹੁੰਚਾ ਸਕਦਾ ਹੈ।" },
  { en: "X-ray images show contrast because bone absorbs more X-rays than surrounding soft tissue, so less radiation reaches the detector behind bone.", hi: "हड्डी मुलायम ऊतकों की तुलना में अधिक एक्स-किरणें अवशोषित करती है, इसलिए डिटेक्टर तक कम किरणें पहुँचती हैं और छवि में स्पष्ट अंतर बनता है।", pa: "ਹੱਡੀ ਨਰਮ ਤੰਤੂਆਂ ਨਾਲੋਂ ਵੱਧ ਐਕਸ-ਕਿਰਨਾਂ ਸੋਖਦੀ ਹੈ, ਇਸ ਲਈ ਡਿਟੈਕਟਰ ਤੱਕ ਘੱਟ ਕਿਰਨਾਂ ਪਹੁੰਚਦੀਆਂ ਹਨ ਅਤੇ ਤਸਵੀਰ ਵਿੱਚ ਸਪਸ਼ਟ ਫਰਕ ਬਣਦਾ ਹੈ।" },
  { en: "Semiconductor conductivity can be deliberately changed by doping, which is why semiconductors are useful for diodes, transistors and integrated circuits.", hi: "डोपिंग से अर्धचालक की चालकता नियंत्रित की जा सकती है, इसलिए अर्धचालक डायोड, ट्रांजिस्टर और समाकलित परिपथों के लिए उपयोगी हैं।", pa: "ਡੋਪਿੰਗ ਨਾਲ ਅਰਧਚਾਲਕ ਦੀ ਚਾਲਕਤਾ ਕਾਬੂ ਕੀਤੀ ਜਾ ਸਕਦੀ ਹੈ, ਇਸ ਲਈ ਅਰਧਚਾਲਕ ਡਾਇਓਡ, ਟ੍ਰਾਂਜ਼ਿਸਟਰ ਅਤੇ ਇਕੀਕ੍ਰਿਤ ਸਰਕਟਾਂ ਲਈ ਲਾਭਦਾਇਕ ਹਨ।" },
  { en: "A diode has low resistance in forward bias and very high resistance in reverse bias, which gives it its rectifying action.", hi: "डायोड अग्र अभिनति में कम और पश्च अभिनति में बहुत अधिक प्रतिरोध देता है, इसलिए वह धारा को मुख्यतः एक दिशा में जाने देता है।", pa: "ਡਾਇਓਡ ਅੱਗੇ ਬਾਇਸ ਵਿੱਚ ਘੱਟ ਅਤੇ ਉਲਟ ਬਾਇਸ ਵਿੱਚ ਬਹੁਤ ਵੱਧ ਪ੍ਰਤੀਰੋਧ ਦਿੰਦਾ ਹੈ, ਇਸ ਲਈ ਇਹ ਧਾਰਾ ਨੂੰ ਮੁੱਖ ਤੌਰ ਤੇ ਇੱਕ ਦਿਸ਼ਾ ਵਿੱਚ ਵਹਿਣ ਦਿੰਦਾ ਹੈ।" },
  { en: "In an LED, electron-hole recombination releases photon energy; the semiconductor material helps determine the emitted colour.", hi: "LED में इलेक्ट्रॉन-होल पुनर्संयोजन से फोटॉन निकलते हैं और प्रयुक्त अर्धचालक पदार्थ उत्सर्जित प्रकाश के रंग को प्रभावित करता है।", pa: "LED ਵਿੱਚ ਇਲੈਕਟ੍ਰਾਨ-ਹੋਲ ਪੁਨਰ-ਸੰਯੋਗ ਨਾਲ ਫੋਟਾਨ ਨਿਕਲਦੇ ਹਨ ਅਤੇ ਵਰਤਿਆ ਅਰਧਚਾਲਕ ਪਦਾਰਥ ਨਿਕਲਦੇ ਪ੍ਰਕਾਸ਼ ਦੇ ਰੰਗ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦਾ ਹੈ।" },
  { en: "A solar cell uses the photovoltaic effect: light creates charge carriers in the semiconductor junction and an electric potential drives current through a load.", hi: "सौर सेल में फोटोवोल्टिक प्रभाव से प्रकाश अर्धचालक जंक्शन में आवेश वाहक बनाता है और उत्पन्न विभव बाहरी परिपथ में धारा चलाता है।", pa: "ਸੂਰਜੀ ਸੈੱਲ ਵਿੱਚ ਫੋਟੋਵੋਲਟਿਕ ਪ੍ਰਭਾਵ ਨਾਲ ਪ੍ਰਕਾਸ਼ ਅਰਧਚਾਲਕ ਜੰਕਸ਼ਨ ਵਿੱਚ ਚਾਰਜ ਵਾਹਕ ਬਣਾਉਂਦਾ ਹੈ ਅਤੇ ਬਣਿਆ ਵਿਭਵ ਬਾਹਰੀ ਸਰਕਟ ਵਿੱਚ ਧਾਰਾ ਚਲਾਉਂਦਾ ਹੈ।" },
  { en: "Photoelectric emission needs photon frequency above a threshold; increasing intensity below that threshold does not eject electrons.", hi: "प्रकाश-विद्युत उत्सर्जन के लिए फोटॉन की आवृत्ति सीमा आवृत्ति से अधिक होनी चाहिए; उससे कम आवृत्ति पर केवल तीव्रता बढ़ाना पर्याप्त नहीं है।", pa: "ਪ੍ਰਕਾਸ਼-ਬਿਜਲਈ ਨਿਕਾਸ ਲਈ ਫੋਟਾਨ ਦੀ ਆਵਿਰਤੀ ਸੀਮਾ ਆਵਿਰਤੀ ਤੋਂ ਵੱਧ ਹੋਣੀ ਚਾਹੀਦੀ ਹੈ; ਇਸ ਤੋਂ ਘੱਟ ਆਵਿਰਤੀ ਉੱਤੇ ਸਿਰਫ਼ ਤੀਬਰਤਾ ਵਧਾਉਣਾ ਕਾਫ਼ੀ ਨਹੀਂ ਹੈ।" },
  { en: "Coherence means the waves maintain a stable phase relation; this, together with directionality and near-monochromaticity, makes lasers useful in precision applications.", hi: "सुसंगति का अर्थ है कि तरंगों के बीच चरण संबंध स्थिर रहता है; दिशात्मकता और लगभग एकवर्णिता के साथ यही लेज़र को सूक्ष्म कार्यों में उपयोगी बनाता है।", pa: "ਸੁਸੰਗਤਤਾ ਦਾ ਅਰਥ ਹੈ ਕਿ ਤਰੰਗਾਂ ਵਿਚਕਾਰ ਚਰਨ ਸੰਬੰਧ ਸਥਿਰ ਰਹਿੰਦਾ ਹੈ; ਦਿਸ਼ਾਤਮਕਤਾ ਅਤੇ ਲਗਭਗ ਇੱਕ-ਰੰਗੀ ਹੋਣ ਨਾਲ ਲੇਜ਼ਰ ਸੁਚੋਕ ਕੰਮਾਂ ਲਈ ਲਾਭਦਾਇਕ ਬਣਦਾ ਹੈ।" },
];

const cp009 = SCI_PHYSICS_EXHAUSTIVE_CP_META_V2.find((cp) => cp.cpId === "SCI-CP-009");
const cp010 = SCI_PHYSICS_EXHAUSTIVE_CP_META_V2.find((cp) => cp.cpId === "SCI-CP-010");
if (!cp009 || !cp010) throw new Error("Missing Physics CP009/CP010 metadata");
const anchors = [...cp009.anchors, ...cp010.anchors];
if (anchors.length !== 48 || NOTES.length !== 48) throw new Error("Physics V6 explanation cardinality drift");

export const SCI_PHYSICS_EXPLANATION_QUALITY_V6: Readonly<Record<string, Readonly<Record<PhysicsLocaleV1, string>>>> = Object.freeze(
  Object.fromEntries(anchors.map((anchor, index) => {
    const note = NOTES[index];
    const hiSurface = anchor.id.startsWith("SCI-CP009-") ? SCI_PHYSICS_CP009_HI_SURFACES_V1[anchor.id] : SCI_PHYSICS_CP010_HI_SURFACES_V1[anchor.id];
    const paSurface = anchor.id.startsWith("SCI-CP009-") ? SCI_PHYSICS_CP009_PA_SURFACES_V1[anchor.id] : SCI_PHYSICS_CP010_PA_SURFACES_V1[anchor.id];
    if (!hiSurface || !paSurface) throw new Error(`Missing localized surface for ${anchor.id}`);
    return [anchor.id, Object.freeze({
      en: `${anchor.explanation} ${note.en}`,
      hi: `${hiSurface.explanation} ${note.hi}`,
      pa: `${paSurface.explanation} ${note.pa}`,
    })];
  })),
);

export function getPhysicsExplanationV6(anchorId: string, locale: PhysicsLocaleV1): string {
  const localized = SCI_PHYSICS_EXPLANATION_QUALITY_V6[anchorId];
  if (!localized) throw new Error(`Missing Physics explanation V6 for ${anchorId}`);
  return localized[locale];
}
