import type { ComparisonRuleId, EnglishDifficulty } from "../../../../core/types";

export interface ComparisonSceneV1 {
  id: string;
  domain: string;
  ruleId: ComparisonRuleId;
  difficulty: EnglishDifficulty;
  correctSegments: readonly [string, string, string, string];
  errorSegments: readonly [string, string, string, string];
  errorIndex: 0 | 1 | 2 | 3;
  correction: string;
  reason: string;
}

const s = (
  id: string,
  domain: string,
  ruleId: ComparisonRuleId,
  difficulty: EnglishDifficulty,
  correctSegments: readonly [string, string, string, string],
  errorSegments: readonly [string, string, string, string],
  errorIndex: 0 | 1 | 2 | 3,
  correction: string,
  reason: string,
): ComparisonSceneV1 => ({ id, domain, ruleId, difficulty, correctSegments, errorSegments, errorIndex, correction, reason });

const EASY: readonly ComparisonSceneV1[] = [
  s("CMP-E01", "office", "GR-CMP-001", "easy", ["The clerk completed", "the register carefully", "before the counter", "closed for the day."], ["The clerk completed", "the register careful", "before the counter", "closed for the day."], 1, "the register carefully", "Carefully is an adverb and tells how the clerk completed the register."),
  s("CMP-E02", "school", "GR-CMP-001", "easy", ["The students listened", "quietly to the instructions", "before starting", "the exercise."], ["The students listened", "quiet to the instructions", "before starting", "the exercise."], 1, "quietly to the instructions", "Quietly is the adverb needed to describe how the students listened."),
  s("CMP-E03", "transport", "GR-CMP-002", "easy", ["The road looks", "clear after the rain", "and traffic has", "started moving again."], ["The road looks", "clearly after the rain", "and traffic has", "started moving again."], 1, "clear after the rain", "Looks is a linking verb here, so clear describes the road."),
  s("CMP-E04", "healthcare", "GR-CMP-002", "easy", ["The patient feels", "better this morning", "after taking", "the prescribed medicine."], ["The patient feels", "wellly this morning", "after taking", "the prescribed medicine."], 1, "better this morning", "Feels links the subject to an adjective complement; better describes the patient’s condition."),
  s("CMP-E05", "banking", "GR-CMP-003", "easy", ["The new form is", "as simple as", "the earlier version", "used at the branch."], ["The new form is", "as simpler as", "the earlier version", "used at the branch."], 1, "as simple as", "Use the positive degree simple between as and as."),
  s("CMP-E06", "sports", "GR-CMP-003", "easy", ["Ravi ran", "as fast as", "his teammate", "in the final lap."], ["Ravi ran", "as faster as", "his teammate", "in the final lap."], 1, "as fast as", "Use the positive degree fast in the as ... as structure."),
  s("CMP-E07", "education", "GR-CMP-004", "easy", ["This chapter is", "shorter than", "the previous chapter", "in the handbook."], ["This chapter is", "short than", "the previous chapter", "in the handbook."], 1, "shorter than", "A direct comparison with than requires the comparative form shorter."),
  s("CMP-E08", "agriculture", "GR-CMP-004", "easy", ["This field is", "larger than", "the one near the road", "by several acres."], ["This field is", "large than", "the one near the road", "by several acres."], 1, "larger than", "A comparison of two fields requires the comparative form larger."),
  s("CMP-E09", "science", "GR-CMP-005", "easy", ["Mercury is", "the smallest planet", "in the solar system", "by diameter."], ["Mercury is", "smallest planet", "in the solar system", "by diameter."], 1, "the smallest planet", "Use the before an ordinary superlative that identifies one member of a group."),
  s("CMP-E10", "library", "GR-CMP-005", "easy", ["This is", "the oldest book", "in the display", "near the entrance."], ["This is", "oldest book", "in the display", "near the entrance."], 1, "the oldest book", "The is required before the superlative oldest in this group comparison."),
  s("CMP-E11", "workplace", "GR-CMP-007", "easy", ["The revised process is", "easier than", "the old process", "for new employees."], ["The revised process is", "more easier than", "the old process", "for new employees."], 1, "easier than", "Easier is already comparative, so more must not be added."),
  s("CMP-E12", "technology", "GR-CMP-007", "easy", ["The updated screen is", "brighter than", "the previous one", "at the same setting."], ["The updated screen is", "more brighter than", "the previous one", "at the same setting."], 1, "brighter than", "Brighter is already a comparative form; more brighter is a double comparative."),
  s("CMP-E13", "exam", "GR-CMP-010", "easy", ["Her second attempt was", "better than", "her first attempt", "in every section."], ["Her second attempt was", "gooder than", "her first attempt", "in every section."], 1, "better than", "The comparative form of good is better."),
  s("CMP-E14", "weather", "GR-CMP-010", "easy", ["The visibility became", "worse after sunset", "because the fog", "grew thicker."], ["The visibility became", "badder after sunset", "because the fog", "grew thicker."], 1, "worse after sunset", "The comparative form of bad is worse."),
  s("CMP-E15", "public-service", "GR-CMP-001", "easy", ["The officer explained", "the procedure clearly", "to the applicants", "at the help desk."], ["The officer explained", "the procedure clear", "to the applicants", "at the help desk."], 1, "the procedure clearly", "Clearly is the adverb that describes how the procedure was explained."),
  s("CMP-E16", "commerce", "GR-CMP-002", "easy", ["The fresh stock appears", "ready for sale", "after the final", "quality check."], ["The fresh stock appears", "readily for sale", "after the final", "quality check."], 1, "ready for sale", "Appears is a linking verb here, so the adjective ready describes the stock."),
  s("CMP-E17", "housing", "GR-CMP-003", "easy", ["The second room is", "as bright as", "the front room", "during the day."], ["The second room is", "as brighter as", "the front room", "during the day."], 1, "as bright as", "Use the positive degree bright between as and as."),
  s("CMP-E18", "research", "GR-CMP-004", "easy", ["The new method is", "safer than", "the earlier method", "under the same conditions."], ["The new method is", "safe than", "the earlier method", "under the same conditions."], 1, "safer than", "Than introduces a direct comparison, so safer is required."),
  s("CMP-E19", "administration", "GR-CMP-005", "easy", ["It was", "the busiest day", "of the month", "at the service centre."], ["It was", "busiest day", "of the month", "at the service centre."], 1, "the busiest day", "Use the before the superlative busiest when one day is identified within a group."),
  s("CMP-E20", "travel", "GR-CMP-010", "easy", ["This route is", "better than", "the longer route", "during peak hours."], ["This route is", "more good than", "the longer route", "during peak hours."], 1, "better than", "Better is the standard comparative form of good."),
];

const MEDIUM: readonly ComparisonSceneV1[] = [
  s("CMP-M01", "audit", "GR-CMP-001", "medium", ["The audit team examined", "the supporting records closely", "before accepting", "the revised statement."], ["The audit team examined", "the supporting records close", "before accepting", "the revised statement."], 1, "the supporting records closely", "Closely is the adverb that describes the manner of examination."),
  s("CMP-M02", "engineering", "GR-CMP-001", "medium", ["The technician adjusted", "the valve precisely", "before the pressure", "was tested again."], ["The technician adjusted", "the valve precise", "before the pressure", "was tested again."], 1, "the valve precisely", "Precisely modifies the action adjusted, so the adverb form is required."),
  s("CMP-M03", "environment", "GR-CMP-002", "medium", ["The river remained", "calm despite the wind", "until the storm", "reached the valley."], ["The river remained", "calmly despite the wind", "until the storm", "reached the valley."], 1, "calm despite the wind", "Remained is a linking verb here; calm describes the river."),
  s("CMP-M04", "recruitment", "GR-CMP-002", "medium", ["The instructions seem", "clear to most candidates", "after the examples", "were added."], ["The instructions seem", "clearly to most candidates", "after the examples", "were added."], 1, "clear to most candidates", "Seem links the subject to the adjective clear."),
  s("CMP-M05", "manufacturing", "GR-CMP-003", "medium", ["The repaired machine now runs", "as smoothly as", "the newer unit", "on the next line."], ["The repaired machine now runs", "as more smoothly as", "the newer unit", "on the next line."], 1, "as smoothly as", "The as ... as frame takes the positive degree smoothly."),
  s("CMP-M06", "finance", "GR-CMP-003", "medium", ["The revised estimate is", "as accurate as", "the figure in", "the audited report."], ["The revised estimate is", "as more accurate as", "the figure in", "the audited report."], 1, "as accurate as", "Use the positive degree accurate between as and as."),
  s("CMP-M07", "infrastructure", "GR-CMP-004", "medium", ["The eastern bridge is", "wider than", "the older bridge", "across the canal."], ["The eastern bridge is", "widest than", "the older bridge", "across the canal."], 1, "wider than", "Two bridges are being compared, so the comparative wider is required."),
  s("CMP-M08", "healthcare", "GR-CMP-004", "medium", ["The new test is", "more reliable than", "the earlier screening method", "for this purpose."], ["The new test is", "most reliable than", "the earlier screening method", "for this purpose."], 1, "more reliable than", "A comparison of two methods requires the comparative more reliable."),
  s("CMP-M09", "education", "GR-CMP-006", "medium", ["The institute is", "one of the oldest colleges", "in the region", "still offering this course."], ["The institute is", "one of the oldest college", "in the region", "still offering this course."], 1, "one of the oldest colleges", "After one of the, the superlative is followed by a plural count noun."),
  s("CMP-M10", "banking", "GR-CMP-006", "medium", ["This branch is", "one of the busiest branches", "in the district", "during pension week."], ["This branch is", "one of the busiest branch", "in the district", "during pension week."], 1, "one of the busiest branches", "One of the busiest must be followed by the plural noun branches."),
  s("CMP-M11", "planning", "GR-CMP-007", "medium", ["The revised schedule is", "simpler than", "the original schedule", "for field teams."], ["The revised schedule is", "more simpler than", "the original schedule", "for field teams."], 1, "simpler than", "Simpler is already comparative; adding more creates a double comparative."),
  s("CMP-M12", "logistics", "GR-CMP-008", "medium", ["This was", "the fastest delivery", "recorded by the depot", "during the quarter."], ["This was", "the most fastest delivery", "recorded by the depot", "during the quarter."], 1, "the fastest delivery", "Fastest is already superlative, so most must not be added."),
  s("CMP-M13", "energy", "GR-CMP-008", "medium", ["January recorded", "the lowest demand", "among the three winter months", "covered by the report."], ["January recorded", "the most lowest demand", "among the three winter months", "covered by the report."], 1, "the lowest demand", "Lowest is already a superlative; most lowest is incorrect."),
  s("CMP-M14", "technology", "GR-CMP-009", "medium", ["The new processor is", "much faster than", "the earlier model", "under the same test."], ["The new processor is", "very faster than", "the earlier model", "under the same test."], 1, "much faster than", "Much can intensify a comparative; very does not normally stand directly before faster."),
  s("CMP-M15", "agriculture", "GR-CMP-009", "medium", ["This variety grows", "far better than", "the older variety", "in dry soil."], ["This variety grows", "very better than", "the older variety", "in dry soil."], 1, "far better than", "Far is a standard intensifier with the comparative better."),
  s("CMP-M16", "public-policy", "GR-CMP-010", "medium", ["The latest survey produced", "worse results than", "the previous survey", "in two categories."], ["The latest survey produced", "more bad results than", "the previous survey", "in two categories."], 1, "worse results than", "Worse is the irregular comparative form of bad."),
  s("CMP-M17", "commerce", "GR-CMP-010", "medium", ["This outlet had", "the best sales record", "among all five outlets", "during the festival."], ["This outlet had", "the goodest sales record", "among all five outlets", "during the festival."], 1, "the best sales record", "Best is the irregular superlative form of good."),
  s("CMP-M18", "law", "GR-CMP-005", "medium", ["That was", "the clearest provision", "in the revised rules", "issued that year."], ["That was", "clearest provision", "in the revised rules", "issued that year."], 1, "the clearest provision", "Use the with an ordinary superlative that identifies one provision from a stated set."),
  s("CMP-M19", "research", "GR-CMP-006", "medium", ["The finding is", "one of the most useful results", "reported by the team", "during the study."], ["The finding is", "one of the most useful result", "reported by the team", "during the study."], 1, "one of the most useful results", "One of the requires a plural noun after the superlative phrase."),
  s("CMP-M20", "transport", "GR-CMP-009", "medium", ["The express service is", "a little quicker than", "the regular service", "on this route."], ["The express service is", "very quicker than", "the regular service", "on this route."], 1, "a little quicker than", "A little can modify a comparative; very quicker is not the standard construction."),
];

const HARD: readonly ComparisonSceneV1[] = [
  s("CMP-H01", "administration", "GR-CMP-001", "hard", ["Although the file contained several annexures,", "the reviewing officer checked each entry carefully", "before forwarding the complete case", "to the approving authority."], ["Although the file contained several annexures,", "the reviewing officer checked each entry careful", "before forwarding the complete case", "to the approving authority."], 1, "the reviewing officer checked each entry carefully", "Carefully modifies checked even though other descriptive words appear nearby."),
  s("CMP-H02", "science", "GR-CMP-001", "hard", ["After the initial readings were discarded,", "the researchers measured the remaining samples accurately", "under the same controlled conditions", "used in the earlier trial."], ["After the initial readings were discarded,", "the researchers measured the remaining samples accurate", "under the same controlled conditions", "used in the earlier trial."], 1, "the researchers measured the remaining samples accurately", "Accurately describes how the researchers measured the samples, so the adverb is required."),
  s("CMP-H03", "healthcare", "GR-CMP-002", "hard", ["Even after the dosage was reduced,", "the patient remained stable", "throughout the observation period", "specified by the doctor."], ["Even after the dosage was reduced,", "the patient remained stably", "throughout the observation period", "specified by the doctor."], 1, "the patient remained stable", "Remained functions as a linking verb and stable describes the patient."),
  s("CMP-H04", "inspection", "GR-CMP-002", "hard", ["Despite several minor scratches on the casing,", "the equipment appears safe", "for routine laboratory use", "after the electrical checks."], ["Despite several minor scratches on the casing,", "the equipment appears safely", "for routine laboratory use", "after the electrical checks."], 1, "the equipment appears safe", "Appears is a linking verb here, so safe describes the equipment."),
  s("CMP-H05", "economy", "GR-CMP-003", "hard", ["After seasonal effects are removed,", "the revised index is as stable as", "the measure used in the previous quarter", "for the same group of goods."], ["After seasonal effects are removed,", "the revised index is as more stable as", "the measure used in the previous quarter", "for the same group of goods."], 1, "the revised index is as stable as", "The as ... as structure requires the positive degree stable."),
  s("CMP-H06", "engineering", "GR-CMP-003", "hard", ["When both systems operate at full load,", "the older unit performs as efficiently as", "the replacement installed last month", "under the specified test conditions."], ["When both systems operate at full load,", "the older unit performs as more efficiently as", "the replacement installed last month", "under the specified test conditions."], 1, "the older unit performs as efficiently as", "Use the positive degree efficiently inside the as ... as frame."),
  s("CMP-H07", "banking", "GR-CMP-004", "hard", ["For customers making frequent small payments,", "the digital option is more convenient than", "the paper-based method previously used", "at the same service counter."], ["For customers making frequent small payments,", "the digital option is most convenient than", "the paper-based method previously used", "at the same service counter."], 1, "the digital option is more convenient than", "Two methods are compared, so the comparative more convenient is required."),
  s("CMP-H08", "environment", "GR-CMP-004", "hard", ["After rainfall patterns from both years were adjusted,", "the second season proved drier than", "the first season recorded at the station", "under the same reporting standard."], ["After rainfall patterns from both years were adjusted,", "the second season proved driest than", "the first season recorded at the station", "under the same reporting standard."], 1, "the second season proved drier than", "The sentence compares two seasons, so drier, not the superlative driest, is required."),
  s("CMP-H09", "public-service", "GR-CMP-005", "hard", ["Among all applications received before the deadline,", "this was the most complete file", "examined by the scrutiny team", "during the first review cycle."], ["Among all applications received before the deadline,", "this was most complete file", "examined by the scrutiny team", "during the first review cycle."], 1, "this was the most complete file", "The ordinary superlative most complete requires the definite article the."),
  s("CMP-H10", "education", "GR-CMP-006", "hard", ["Although the programme began only recently,", "it has become one of the most popular courses", "offered by the institute", "to first-year students."], ["Although the programme began only recently,", "it has become one of the most popular course", "offered by the institute", "to first-year students."], 1, "it has become one of the most popular courses", "One of the selects one member from a plural class, so courses must be plural."),
  s("CMP-H11", "infrastructure", "GR-CMP-006", "hard", ["After the latest expansion was completed,", "the terminal became one of the busiest transport hubs", "serving the northern region", "during the holiday season."], ["After the latest expansion was completed,", "the terminal became one of the busiest transport hub", "serving the northern region", "during the holiday season."], 1, "the terminal became one of the busiest transport hubs", "The noun after one of the + superlative must be plural: hubs."),
  s("CMP-H12", "manufacturing", "GR-CMP-007", "hard", ["Once the unnecessary approval stage was removed,", "the revised workflow became simpler than", "the procedure followed in the older unit", "for the same production task."], ["Once the unnecessary approval stage was removed,", "the revised workflow became more simpler than", "the procedure followed in the older unit", "for the same production task."], 1, "the revised workflow became simpler than", "Simpler already expresses the comparative degree; more simpler is a double comparative."),
  s("CMP-H13", "technology", "GR-CMP-007", "hard", ["Even when both devices use the same network,", "the newer model responds faster than", "the version issued two years earlier", "under a comparable workload."], ["Even when both devices use the same network,", "the newer model responds more faster than", "the version issued two years earlier", "under a comparable workload."], 1, "the newer model responds faster than", "Faster is already comparative; more must not be added."),
  s("CMP-H14", "agriculture", "GR-CMP-008", "hard", ["Of all the plots tested under identical irrigation,", "the northern plot produced the highest yield", "during the final harvest", "recorded by the field team."], ["Of all the plots tested under identical irrigation,", "the northern plot produced the most highest yield", "during the final harvest", "recorded by the field team."], 1, "the northern plot produced the highest yield", "Highest is already superlative, so most highest is incorrect."),
  s("CMP-H15", "planning", "GR-CMP-008", "hard", ["Among the alternatives that met every safety condition,", "the third design required the least space", "inside the existing building", "without reducing capacity."], ["Among the alternatives that met every safety condition,", "the third design required the most least space", "inside the existing building", "without reducing capacity."], 1, "the third design required the least space", "Least already expresses the superlative degree; most least is incorrect."),
  s("CMP-H16", "research", "GR-CMP-009", "hard", ["After the calibration error was corrected,", "the second set of readings was far more consistent than", "the data collected during the preliminary trial", "with the same measuring device."], ["After the calibration error was corrected,", "the second set of readings was very more consistent than", "the data collected during the preliminary trial", "with the same measuring device."], 1, "the second set of readings was far more consistent than", "Far can intensify a comparative phrase; very directly before more consistent is not standard here."),
  s("CMP-H17", "transport", "GR-CMP-009", "hard", ["Once the damaged section of road was repaired,", "the morning journey became much shorter than", "the trip recorded during the previous week", "under similar traffic conditions."], ["Once the damaged section of road was repaired,", "the morning journey became very shorter than", "the trip recorded during the previous week", "under similar traffic conditions."], 1, "the morning journey became much shorter than", "Much is a standard intensifier with shorter; very shorter is not."),
  s("CMP-H18", "performance", "GR-CMP-010", "hard", ["Although both teams improved after the break,", "the second team performed better than", "the first team in the final round", "under the same scoring rules."], ["Although both teams improved after the break,", "the second team performed more good than", "the first team in the final round", "under the same scoring rules."], 1, "the second team performed better than", "Better is the irregular comparative form of good."),
  s("CMP-H19", "quality-control", "GR-CMP-010", "hard", ["Of the three batches tested after recalibration,", "the first batch showed the worst defect rate", "under the revised inspection method", "used throughout the plant."], ["Of the three batches tested after recalibration,", "the first batch showed the baddest defect rate", "under the revised inspection method", "used throughout the plant."], 1, "the first batch showed the worst defect rate", "Worst is the irregular superlative form of bad."),
  s("CMP-H20", "governance", "GR-CMP-005", "hard", ["Among the recommendations accepted by every department,", "this was the most practical proposal", "for reducing duplicate paperwork", "without changing the approval process."], ["Among the recommendations accepted by every department,", "this was most practical proposal", "for reducing duplicate paperwork", "without changing the approval process."], 1, "this was the most practical proposal", "The definite article the is required before the ordinary superlative most practical."),
];

export const CP006_SCENES_BY_DIFFICULTY_V1: Readonly<Record<EnglishDifficulty, readonly ComparisonSceneV1[]>> = Object.freeze({
  easy: EASY,
  medium: MEDIUM,
  hard: HARD,
});

export const CP006_SCENES_V1: readonly ComparisonSceneV1[] = Object.freeze([...EASY, ...MEDIUM, ...HARD]);
