export const HIS_CP011_STEM_OVERRIDES_V2:Readonly<Record<number,string>>={
  1:"After Aurangzeb's death in 1707, which political trend became prominent?",
  2:"Bahadur Shah I generally followed which policy towards powerful nobles and regional chiefs?",
  3:"Who exercised considerable executive authority during Jahandar Shah's reign?",
  4:"Who helped Farrukh Siyar gain the Mughal throne and later became dominant at court?",
  5:"During Muhammad Shah's reign, which political trend became more pronounced?",
  6:"Which statement correctly describes the position of many regional rulers in relation to the Mughal emperor?",
  7:"Shivaji belonged to which Maratha clan?",
  8:"Who succeeded Rajaram in 1708 and played a major role in reviving Maratha power?",
  9:"In the Maratha administration, the term 'Peshwa' referred to which office?",
  10:"Which Peshwa played an important role in securing Shahu's position?",
  11:"Who held the office of Peshwa from 1720 to 1740?",
  12:"Which political development took place during Shahu's reign?",
  13:"Which Maratha house was associated with Nagpur?",
  14:"Which Maratha house was associated with Baroda?",
  15:"Which Maratha house established its principal base at Indore?",
  16:"Which Maratha house later became centred at Gwalior?",
  17:"Who played a major role in consolidating Holkar power at Indore?",
  18:"Who ruled the Holkar domains from 1765 to 1794?",
  19:"Balaji Vishwanath and Baji Rao I are associated with which administrative development?",
  20:"Which pair represented two important Maratha tribute claims?",
  21:"The use of Mughal-derived revenue terms in Maratha administration indicates which of the following?",
  22:"Which of the following pairs is correctly matched regarding Maratha expansion?",
  23:"Raghuji Bhonsle is chiefly associated with Maratha incursions into which region?",
  24:"Which statement correctly describes Maratha expansion and administration in the early eighteenth century?",
  25:"What followed the suppression of Banda Bahadur?",
  26:"Which city emerged as an important centre of Sikh activity during the 1720s and 1730s?",
  27:"Which of the following correctly describes early Sikh consolidation?",
  28:"Which of the following pairs is correctly matched?",
  29:"Which Sikh leader later founded the kingdom of Kapurthala?",
  30:"By which period had Sikh authority been established over Lahore?",
  31:"Which of the following comparisons between Bengal and Awadh is correct?",
  32:"Who took control of Bengal in 1739?",
  33:"Which statement best describes Bengal under the eighteenth-century Nawabs?",
  34:"Who established an autonomous hereditary power base in Awadh?",
  35:"Which pair consisted of important Nawabs of Awadh after Saadat Khan?",
  36:"Which ruler strengthened Jaipur in the early eighteenth century?",
  37:"Which of the following pairs is correctly matched?",
  38:"Which sequence correctly shows the events leading to the Third Battle of Panipat?",
  39:"Who defeated the Marathas in the Third Battle of Panipat in 1761?",
  40:"Which statement correctly describes the impact of the Third Battle of Panipat on Maratha power?",
  41:"Which statement correctly describes resistance to Afghan influence in Punjab?",
  42:"The period from 1707 to 1761 is best associated with which political development?",
  43:"Which statement correctly describes the regional states of eighteenth-century India?",
  44:"Why did many regional rulers continue to use Mughal titles and honours?",
  45:"Which administrative feature was common to several Maratha, Sikh and other regional states?",
  46:"Which statement best describes the political trend in India after 1707?",
  47:"Which of the following sets is correctly matched?",
  48:"Which pair best illustrates the continued influence of Mughal administrative practices?",
  49:"Which of the following sequences is chronologically correct?",
  50:"Which statement correctly describes the Maratha Confederacy?",
  51:"Which of the following pairs is correctly matched?",
  52:"Which conclusion is correct regarding Maratha power after the Third Battle of Panipat?",
  53:"Which combination correctly explains the changing political balance in Punjab during the eighteenth century?",
  54:"Which statement correctly describes Sikh political organisation by the 1770s?",
  55:"Which comparison between Maratha and Sikh administration is correct?",
  56:"Which statement correctly describes the rise of Ranjit Singh?",
  57:"Which set correctly matches rulers with their eighteenth-century regional power centres?",
  58:"Which sequence correctly represents the expansion, setback and recovery of Maratha power?",
  59:"1. Regional rulers retained Mughal political symbols. 2. Mughal-derived fiscal practices continued in several successor states. Which are correct?",
  60:"Which statement best summarises the political transformation of India during the eighteenth century?",
};
